### ISSUE TITLE
Drupal version in config files is ignored, drush hangs

### ISSUE THREAD

**Issue by banzo** [geerlingguy/drupal-vm#100]
I changed the Drupal version/core from 8 to 7 in config.yml and drupal.make.yml, as instructed [here](https://github.com/geerlingguy/drupal-vm#customizing-the-vm)

1. ```vagrant up``` hangs when enabling the modules (```drush en -y devel chdir=/var/www/drupal```)
2. if I skip that step, the drupal version installed is not 7.x but 8.0.x

The d7 branch of drupal-vm does not have this issue, but I was hoping to use the master branch to do drupal 7 deployments.

My config:

Ansible 1.9.1
Vagrant 1.7.2
Mac OS 10.10.3
Drush 7 (same with 6.0.5)

**Comment by geerlingguy** [comment]
@banzo - Please see the recreated `d7` branch (which is back in sync with master)—specifically, these are all the required changes to get it working: https://github.com/geerlingguy/drupal-vm/compare/d7
