### ISSUE TITLE
TASK [Install Drupal with drush.] fails

### ISSUE THREAD

**Issue by cg433n** [geerlingguy/drupal-vm#1003]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.6r110634
ansible 2.1.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.12.1 (16B2555)

### Summary

The `Install Drupal with drush.` command seems to be failing.
I've already read through #981 and run `sudo rm -rf /opt/vagrant/embedded/bin/curl`

```
TASK [Install Drupal with drush.] **********************************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:00.148339", "end": "2016-11-18 23:00:32.876992", "failed": true, "rc": 1, "start": "2016-11-18 23:00:32.728653", "stderr": "Command site-install needs a higher bootstrap level to run - you will\u001b[31;40m\u001b[1m[error]\u001b[0m\nneed to invoke drush from a more functional Drupal environment to run\nthis command.\nThe drush command 'site-install standard' could not be executed.     \u001b[31;40m\u001b[1m[error]\u001b[0m", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/Users/cg433n/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=154  changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by oxyc** [comment]
Can you post the entire ansible output?

**Comment by geerlingguy** [comment]
@cg433n - Ditto what `oxyc` said; you could either attach it in a txt file to a comment or link to a pastebin or gist... @oxyc do you think we should maybe add a 'please do this if possible' note in the new issue template to show people where to stick the full error output?

**Comment by oxyc** [comment]
@geerlingguy might be a good idea. I think that's our first question on 90% of bug reports :)

**Comment by cg433n** [comment]
Here's a Gist of the entire ansible output: https://gist.github.com/cg433n/13d122ffa38a37c5565f26fc9e86decd
Let me know if it would be better to embed the entire output right in this thread.

**Comment by oxyc** [comment]
A gist works better, thanks!

So the issue is:

> TASK [Generate Drupal project with composer package.] **************************
skipping: [drupalvm]

Assuming you're using the default setup where Drupal is installed with `composer create-project`, this should not be skipped. The reason for the task being skipped is usually that you already have a partial or broken code base. More specifically, the task is skipped if you have an `index.php` file in `/var/www/drupalvm/drupal/web/index.php`.

If you post your `config.yml` I can give more specific details on where this is on your system. To fix it, delete this `web/` directory and run `vagrant provision` again.

**Comment by cg433n** [comment]
@oxyc I'm guessing my code base was broken by my first `vagrant up`, when I ran into problems detailed in #981. Your fix worked!
