### ISSUE TITLE
How to use DrupalVM to develop Drush itself?

### ISSUE THREAD

**Issue by TravisCarden** [geerlingguy/drupal-vm#1006]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.0.26r108824
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.11.6)

### Summary

I periodically submit pull requests to Drush, and the workflow for that within Drupal VM is not easy. Where it's installed presently, the code cannot be edited from the host machine (in an IDE) making it very tedious and error-prone to code and test. It would be great if this were easier. The Drush directory, as it is, could be exposed outside the VM somehow, but I think it would be better to add the option to use the Drush instance in the site's `vendor` directory. That has the benefit that the code in the application repo is the same code that's actually being used in the VM, allowing for easy testing of changes and exposing the active code to the IDE for debugging and correct code completion, among other things.

**Comment by oxyc** [comment]
Heh good timing. #711 makes this possible. As of 3.6.0 (not yet released) f you have drush set as a composer dependency, it will be used rather than the globally installed drush. This only applies to provision and the host drush alias though. If you ssh to the machine and use `drush` it will resolve to the globally installed drush though.

**Comment by geerlingguy** [comment]
@TravisCarden - Also note that if you remove `drush` from `installed_extras` in 3.6.0+ (or current master), then Drush won't be installed internally at all, and you could clone it yourself as-needed.

**Comment by geerlingguy** [comment]
Going to mark as closed, as I think we have a couple decent options for this now; use `master` until `3.6.x` is released.
