### ISSUE TITLE
Wrong wording in issue template

### ISSUE THREAD

**Issue by UTANdev** [geerlingguy/drupal-vm#1009]
### Issue Type

 - Bug Report / Support Request

### Summary

When creating an issue, the template includes this instruction:
```
<!--- Paste the output from the following command: `vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version` (paste it in the space between the three tildes) -->
```

It's actually three grave accents, not three tildes.

**Comment by geerlingguy** [comment]
D'oh! Just turn it about 45 degrees and make it squiggly and it's a tilde :D
