### ISSUE TITLE
"No such file or directory" when building with drush makefile

### ISSUE THREAD

**Issue by ameenshake** [geerlingguy/drupal-vm#1013]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026

ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

### Your OS

 - **Linux** (Ubuntu 16.04)

### Full console output

https://gist.github.com/ameenshake/dee57a0558c7b3b4496b4cd6944a03f3

### Summary

Building new DrupalVM from scratch throws the following error:

```
TASK [Generate Drupal site with drush makefile.] *******************************
fatal: [drupalvm]: FAILED! => {"changed": false, "cmd": "/usr/local/bin/drush make -y /tmp/drupal.make.yml --no-gitinfofile", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
	to retry, use: --limit @/home/ameenshake/drupalVM/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=138  changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Not sure what to do here. I have tried deleting .vagrant and .vagrant.d. I have tried sshing into the VM and doing "composer install". Please help.

This is my drupal.make.yml: https://gist.github.com/ameenshake/8ad57b9e9c6e21f51d5f43df7198db14

**Comment by oxyc** [comment]
Are you using the latest master of Drupal VM? We recently made the `drush` installation optional and it seems you might be using an outdated `config.yml`.

Make sure you have [`drush` listed in `installed_extras`](https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L195).

**Comment by ameenshake** [comment]
Ah yes that is it, I was using the latest master with the old ```config.yml```. Thank you very much, you saved the day.
