### ISSUE TITLE
Unable to find '../../scripts' in expected paths

### ISSUE THREAD

**Issue by kiwimind** [geerlingguy/drupal-vm#1014]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.6r110634
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** El Capitan 10.11.6

### Full console output

```
TASK [Run configured post-provision ansible task files.] ***********************
 [WARNING]: Unable to find '../../scripts' in expected paths.
```

### Summary

The documentation at https://github.com/geerlingguy/drupal-vm/blob/2997dc9a3db2108f14ac1e3bb0b6d1540a5beef3/docs/extras/scripts.md shows the path for post provision tasks as `../../scripts/post-provision.yml`, but this fails with the above error.

When I update the path to be `../scripts/post-provision.yml` it appears to read the correct file (although this is currently failing on me since updating drupalvm, but that's another issue.

**Comment by geerlingguy** [comment]
@kiwimind - Are you using Drupal VM standalone, or as part of some other tool (e.g. BLT)? If used standalone, I believe the pathing would be correct, if the `vagrant` commands are run inside Drupal VM's folder. But if with a tool, the path might be different.

I haven't confirmed this to be the case, but I do vaguely remember having to change that path when used with BLT at least.

**Comment by kiwimind** [comment]
@geerlingguy Thanks for your prompt response.

No, not using any other tools with this.

Have updated to the latest Drupal VM alongside my custom config file, trying to add in both a post provisioning task and script.

It's working with the amended path to the post-provision.yml file.

Can investigate further if it helps when back in the office on Monday.

Thanks again.

**Comment by geerlingguy** [comment]
@kiwimind - Sounds good, I'll try to test sometime too, when I get a chance!

**Comment by geerlingguy** [comment]
Confirmed—this was incorrect, so I updated the docs. Thanks, @kiwimind, for the error report!

**Comment by oxyc** [comment]
https://github.com/ansible/ansible/issues/14036

**Comment by geerlingguy** [comment]
@oxyc ++ — I knew it was working when we merged it originally :P

**Comment by kiwimind** [comment]
@geerlingguy no worries, thanks for the swift response.
