### ISSUE TITLE
Hyper-V support on windows ?

### ISSUE THREAD

**Issue by sinasalek** [geerlingguy/drupal-vm#1015]
Is it possible to use this with Hyper-V as provider in Windows 10 ?

**Comment by geerlingguy** [comment]
@sinasalek - I haven't looked into this at all, as I'm not as familiar with Vagrant + Hyper-V on Windows (and I only boot up my Windows laptop every couple weeks to do some debugging)... if someone else can provide instructions/documentation, I'm willing to add it to the project.

**Comment by sinasalek** [comment]
Great,
Here is a basic instruction :
1. Add a virtual network switch in hyperv manager
2. Adding NAT and DHCP: https://4sysops.com/archives/native-nat-in-windows-10-hyper-v-using-a-nat-virtual-switch/
3. Modify config.yaml and change vagrant_box to hashicorp/precise64
4. Open cmd as administrtator and run the follwing command
vagrant up --provider hyperv

**Comment by geerlingguy** [comment]
I'm going to close this for now, as I am unable to offer any extra support for Hyper-V on Windows (my time is thin enough to support Docker for Windows and VirtualBox...); if there are any other notes/improvements, I would be willing to accept a PR adding to the existing Drupal VM Windows documentation here: http://docs.drupalvm.com/en/latest/getting-started/installation-windows/
