### ISSUE TITLE
Possible syntax problem in solr role.

### ISSUE THREAD

**Issue by TipiT** [geerlingguy/drupal-vm#1018]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.8r111374
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **Linux** Ubuntu 15.10	wily

### Full console output

vagrant up --provision

statically included: drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in 'drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Run systemd daemon_reload (RHEL 7 workaround).
  ^ here

The error appears to have been in 'drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Run systemd daemon_reload (RHEL 7 workaround).
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

### Summary

I just can't seem to figure out what is the exact syntax problem is here or why it even affects my provisioning because I don't use RedHat distro.

So of course the solution was to comment out the these two plays.

This appeared when I pulled to commit: da79ab78b80acff34cb5a787b3b33ac097bec28d

**Comment by geerlingguy** [comment]
@TipiT - Can you upgrade to Ansible 2.2.x? Otherwise the `daemon_reload` configuration in the solr role's latest version won't work.

**Comment by geerlingguy** [comment]
Also pushed up a change that I'll test to bump the minimum Ansible requirement; sorry for missing that!

**Comment by TipiT** [comment]
Upgrading to ansible 2.2.0.0 did the trick. Thank you for the quick help!

**Comment by geerlingguy** [comment]
@TipiT - Thanks for the bug report :)
