### ISSUE TITLE
Fresh VM fails to start on Linux Mint with NS_ERROR_FAILURE

### ISSUE THREAD

**Issue by enapthine** [geerlingguy/drupal-vm#1019]
- Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS
 - **Linux** Mint 18.1

### Full console output

https://gist.github.com/enapthine/758560e586939281f8bb8db68bddca22

### Summary

Fresh git clone of DrupalVM, updated vagrant and virtualbox, fails to start.

**Comment by geerlingguy** [comment]
Does this help at all? http://askubuntu.com/a/223763

Also, make sure you update to Ansible 2.2.x soon, as some roles will start requiring it.

**Comment by enapthine** [comment]
![image](https://cloud.githubusercontent.com/assets/3314830/20703407/1a9e4c90-b64e-11e6-8ac6-5d89f4cd0b5a.png)

The top answer in your link, the directory doesn't exist. Nor does the command on the second answer.

I ran the suggested command in the above screenshot (when just testing if it will boot via GUI), which ran, however did not resolve the issue.

Any other ideas?

**Comment by geerlingguy** [comment]
Hmm, can you try this: `vagrant plugin install vagrant-vbguest` and then make sure the VM is destroyed (`vagrant destroy -f`), and try `vagrant up` again?

**Comment by mk1952** [comment]
I think I have a similar issue. This is the first time I have tried to use Vagrant or DrupalVM so there are lots of things I don't understand, and I have stuck to the "Quick Start Guide". I'm running on Mac OSX 10.10.5 and have just installed Vagrant so this is version 1.9.0. I created a new directory ~/Sites/dev1 and unpacked the downloaded DrupalVM zip file into it.
Here is the console output:
`imac-1:dev1 martinknapp$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/ubuntu1604'
    drupalvm: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1604
==> drupalvm: Adding box 'geerlingguy/ubuntu1604' (v1.0.5) for provider: virtualbox
    drupalvm: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604/versions/1.0.5/providers/virtualbox.box
==> drupalvm: Successfully added box 'geerlingguy/ubuntu1604' (v1.0.5) for 'virtualbox'!
==> drupalvm: Importing base box 'geerlingguy/ubuntu1604'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.`

**Comment by geerlingguy** [comment]
@mk1952 - Can you run `vagrant plugin install vagrant-vbguest` and then run these commands:

```
vagrant destroy -f
vagrant up
```

Ref: https://github.com/geerlingguy/drupal-vm/issues/1030

**Comment by geerlingguy** [comment]
@enapthine - for the particular error:

```
==> ck: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "5febd899-a312-4711-a7cb-c5e95e977b55", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'ck.dev' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
```

That seems like something coming from VirtualBox and/or Vagrant. Can you open up VirtualBox itself and try to run the VM? Also, can you confirm your computer's BIOS has VT-x support enabled? This seems like a virtualization issue.

**Comment by mk1952** [comment]
Your suggestion doesn't appear to have made any difference. What is odd though, is that when I look in the VirtualBox GUI I can see the machine there, supposedly up and running. And actually I can also start it directly from the GUI and login as "vagrant" (a real pain because I have a French Mac keyboard). However, when I trying switching to /var/www/drupalvm for example, it says that the directory doesn't exist - in fact there seem to be no directories at all in the machine which seems a bit odd

**Comment by geerlingguy** [comment]
@mk1952 - Can you run `vagrant plugin list`? Maybe there's a plugin conflicting here...

Also, can you run the command: `vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version` and paste the output here?

**Comment by mk1952** [comment]
```
imac-1:dev1 martinknapp$ vagrant plugin list
vagrant-share (1.1.6, system)
vagrant-vbguest (0.13.0)
```
Then
```
imac-1:dev1 martinknapp$ vagrant --version && echo "VirtualBox vboxmanage --version" && ansible --version
Vagrant 1.9.0
VirtualBox vboxmanage --version
-bash: ansible: command not found
```
However
```
imac-1:dev1 martinknapp$ vboxmanage --version
4.3.12r93733
```
Perhaps I'm doing something wrong?

**Comment by geerlingguy** [comment]
@mk1952 ah... 4.3.12 is quite a bit older—you will need to download and install 5.1.10 (preferred) or 5.1.6. See: https://www.virtualbox.org/wiki/Downloads

**Comment by mk1952** [comment]
Do I have to `vagrant destroy` the box when I've installed the new version of VB? Or do I just try `vagrant up` again?

**Comment by geerlingguy** [comment]
@mk1952 - This issue seems different from what is being reported above (concerning Mint Linux and the NS_* error). Could you maybe open a separate issue? I don't want to crowd out the original issue report too much :)

**Comment by geerlingguy** [comment]
@mk1952 - And yes, you would need to `vagrant destroy` the box first—and also it would be a good idea to do a `vagrant box remove [box-name-here]` for all your installed geerlingguy/* boxes.

**Comment by enapthine** [comment]
No change after previous commands.. still:

`==> ck: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "3f9463c4-bde1-4190-acb7-72a9e83ef6bc", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'ck.dev' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine
`

**Comment by geerlingguy** [comment]
@enapthine - Are you able to start the VM within VirtualBox's GUI? E.g. open VirtualBox and double-click on the VM name in the list.

Also, using the GUI might reveal some other related error.

**Comment by epicflux** [comment]
@geerlingguy I know you asked that this error report be moved to another ticket, I'm not sure if that occurred so I'll comment here.

I was helping a Windows user get setup and they had this network connection setup issue. Switching versions of VirtualBox didn't help.

What finally seemed to do the trick was installing VirtualBox with this command:

> VirtualBox-5.x.x-xxxx-Win.exe -msiparams NETWORKTYPE=NDIS5

I hope this helps.

**Comment by enapthine** [comment]
Still no good.

```
Failed to open a session for the virtual machine ck.dev.

The virtual machine 'ck.dev' has terminated unexpectedly during startup with exit code 1 (0x1).

Result Code: NS_ERROR_FAILURE (0x80004005)
Component: MachineWrap
Interface: IMachine {b2547866-a0a1-4391-8b86-6952d82efaa0}

```

![image](https://cloud.githubusercontent.com/assets/3314830/21130547/e0ae1fb2-c13b-11e6-92f3-b243eb8f84f9.png)

**Comment by enapthine** [comment]
Reinstalling Virtualbox fixed the issue. Updated to latest DrupalVM after, and Ansible 2.2.

Ref:
http://askubuntu.com/questions/703746/how-to-completely-remove-virtualbox
https://www.virtualbox.org/wiki/Linux_Downloads
http://docs.ansible.com/ansible/intro_installation.html#latest-releases-via-apt-ubuntu
