### ISSUE TITLE
'geerlingguy/ubuntu1604' could not be found

### ISSUE THREAD

**Issue by capsular** [geerlingguy/drupal-vm#1021]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
ansible 2.2.0.0
```

### Your OS
 - Mac OS 10.12.1

### Full console output

andres-MacBook-Pro:drupalvm andremu$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
The box 'geerlingguy/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1604"]
Error: 

### Summary

I had no Problems installing drupalvm on my old macbook, have been working with it for quite some time and loving it. Just got my a macbook pro (touchbar) and now I can't get it installed.. the empty error message doesn't really help here : ( 

**EDIT: Solution for all Sierra users (vagrant issue):
https://github.com/mitchellh/vagrant/issues/7969**

**Comment by geerlingguy** [comment]
@capsular - see https://github.com/geerlingguy/drupal-vm/issues/981

**Comment by justincletus** [comment]
The box 'hashicorp/precise64' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/hashicorp/precise64"]
Error: The requested URL returned error: 404 Not Found

I am using vagrant version  1.9.1
ansible version 2.5.1
I removed sudo rm /opt/vagrant/embedded/bin/curl
I have the same above issue how to fix it. Any idea please.

**Comment by justincletus** [comment]
Thanks for your reply, I fixed issue using vagrant version 2.0 or latest.
