### ISSUE TITLE
no visibility outside the host

### ISSUE THREAD

**Issue by GhostInTheMachinesAtTSBVI** [geerlingguy/drupal-vm#1022]
### Issue Type

 - Bug Report / Support Request
 

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
ansible 2.0.0.2
```

### Your OS

 - **Linux** (16.0 Xenial amd64 server)

### Full console output
Support-Request:  Can not reach the DrupalVM instance with the web browser outside of the host.  Request is how to change the config.yml to bridge the connection instead of using Host Only

### Summary

I have a separate bare metal server running virtual box and the DrupalVM and I would like to be able to access the Drupal Admin front end from a desktop within our teams network.  If I were using just Vagrant this can be accomplished by setting up a port forward.  Attempting to do this inside the config.yml gives me an error that these ports are already in use.

What is the best practice for being able to reach DrupalVM front end from other desktops on the network?

**Comment by thom8** [comment]
You could look into using Vagrant share -- https://www.vagrantup.com/docs/share/

Alternatively you could setup a bridged adapter on the VM so it can receive an IP from your local network DHCP server.

**Comment by GhostInTheMachinesAtTSBVI** [comment]
It looks like all of the vagrant share options use the Atlas cloud as a proxy so I am back to trying to find out how to change either the vagrant file or the config.yml so that it sets up a bridged connection keeping the access inside my local LAN.

Are you saying that this is not possible and that I should try to change this through the VirtualBox GUI or possibly by using some CLI commands?

**Comment by thom8** [comment]
This should be possible with a [`Vagrantfile.local`](http://docs.drupalvm.com/en/latest/other/overriding-configurations/#extending-the-vagrantfile-with-vagrantfilelocal).

You would override `config.vm.network` with a bridged config see `:bridge` here --
https://www.vagrantup.com/docs/networking/public_network.html

**Comment by joestewart** [comment]
Or maybe just use ngrok for access from outside the host.

**Comment by GhostInTheMachinesAtTSBVI** [comment]
@thom8, 
When you say "override" do you mean I can  include the statement config.vm.network "pulic_network", ip: "my static ip"  in the config.yml file and it will override the Vagrant file?

**Comment by thom8** [comment]
@GhostInTheMachinesAtTSBVI yes redefining `config.vm.network` here will override this configuration, just be aware that some config options allow multiple definitions eg. `config.vm.provision` so you'd need to specify the name to override otherwise it will be additional config.

**Comment by geerlingguy** [comment]
I'd say the two best ways would be to use a `Vagrantfile.local` to override the config, and set up your own `network` for the VM (follow this documentation: https://www.vagrantup.com/docs/networking/)—this way you have fine grained control over every aspect of what's accessible local vs. on a network interface—or to use `vagrant share` or some other proxying solution.

**Comment by GhostInTheMachinesAtTSBVI** [comment]
Actually it was very simple after I read the vagrant documentation again about "public_network" actually being a misnomer for "bridged".  This made the line in the config.yml with the variable "vagrant_public_ip" seem more like the place to put my bridged ip.

Once I did this the DrupalVM became accessible on my local LAN and the Apache splash page now comes up when I visit that IP.

All I have to fix now is the spot where the script crashes complaining about Composer.  I am going to try switching to the drush make file method to see if I can get around this issue.  If it doesn't fix it I will start a new thread.

Thanks

**Comment by geerlingguy** [comment]
Great! Thanks for the update.
