### ISSUE TITLE
How to use mysql and postgres together

### ISSUE THREAD

**Issue by anacona16** [geerlingguy/drupal-vm#1023]
Is posible to use mysql and postgres together? 

If not, what is the best way to add to drupal-vm machines, one with mysql and another with postgres?

Thanks in advance.

### Issue Type

 - Documentation Report

### Your OS

 - **macOS** 10.12 Sierra

**Comment by geerlingguy** [comment]
@anacona16 - Currently the configuration is set up so you can use either MySQL or Postgres per-VM.

You can create multiple instances of Drupal VM (I have 2 running right now, and about 45 different configurations set up for different projects :)—just download Drupal VM separately, and set a unique machine name and IP address in `config.yml`. Or if using as part of another project (using Composer), just make sure to customize the IP/machine name in each config.yml file.

Also, note that you could customize Drupal VM slightly and have both installed at the same time inside one VM, but this isn't supported OOTB, and would likely require a few manual steps and/or a forked version of Drupal VM.
