### ISSUE TITLE
Add custom repos during provisioning

### ISSUE THREAD

**Issue by paulsheldrake** [geerlingguy/drupal-vm#1025]
### Issue Type

 - Documentation Report

### Summary

Is it possible to add custom repos during the provisioning process? I would like to install [Yarn](https://yarnpkg.com/en/docs/install#linux-tab) during provisioning but it's in a custom repo.  I was hoping to install the repo and then add `yarn` as an item under `extra_packages` in my config.yml

Cheers,
Paul

**Comment by oxyc** [comment]
At the moment there is not such a functionality. You can also install `yarn` with `npm` though.

```yaml
nodejs_npm_global_packages:
  - name: yarn
```

**Comment by paulsheldrake** [comment]
Cheers, thank you.

**Comment by geerlingguy** [comment]
Closing as hopefully this should take care of the question. Thanks!
