### ISSUE TITLE
Error when trying to load a D6 site with DrupalVM

### ISSUE THREAD

**Issue by jesrig** [geerlingguy/drupal-vm#1026]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

```

### Your OS

 - **Windows** (version)

### Full console output
https://gist.github.com/jesrig/ec948f3250268de2e4d554b4ba0d01d0

### Summary

I am trying to get a D6 site into Drupalvm and I'm hitting this error:

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [wtplaw]: FAILED! => {"changed": false, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.756104", "end": "2016-11-29 21:02:43.927397", "failed": true, "rc": 1, "start": "2016-11-29 21:02:43.171293", "stderr": " [error]  Drush 9 does not support Drupal 6. 

I actually have `install_site` set to `false` so I'm not even sure how it knew that I was planning on importing a D6 database.

**Comment by geerlingguy** [comment]
@jesrig - Please see: https://github.com/geerlingguy/drupal-vm/issues/1020

It looks like your best bet is to set `drush_version: 8.x` (or a specific older version) in `config.yml` and either rebuild your environment, or it might just work if you do another `vagrant provision`.

**Comment by jesrig** [comment]
@geerlingguy This worked, thanks!

**Comment by geerlingguy** [comment]
Perfect!
