### ISSUE TITLE
Solr 5.3.1, solr.in.sh doesn't exist where drupalvm thinks it should

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/drupal-vm#1028]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.6r110634
ansible 2.1.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

- **macOS** (10.11.6)

### Full console output

```
TASK [geerlingguy.solr : Apply Solr memory configuration changes.] *************
failed: [drupalvm] (item={u'regexp': u'^.?SOLR_JAVA_MEM=', u'line': u'SOLR_JAVA_MEM="-Xms64M -Xmx128M"'}) => {"failed": true, "item": {"line": "SOLR_JAVA_MEM=\"-Xms64M -Xmx128M\"", "regexp": "^.?SOLR_JAVA_MEM="}, "msg": "Destination /etc/default/solr.in.sh does not exist !", "rc": 257}
failed: [drupalvm] (item={u'regexp': u'^SOLR_PORT=', u'line': u'SOLR_PORT="8983"'}) => {"failed": true, "item": {"line": "SOLR_PORT=\"8983\"", "regexp": "^SOLR_PORT="}, "msg": "Destination /etc/default/solr.in.sh does not exist !", "rc": 257}
```

### Summary

If I run `cp /opt/solr-5.3.1/bin/solr.in.sh /etc/default/` and run `vagrant provision` the error goes away and provisioning completes. Guessing there's no task for moving this file, maybe because of the version I'm using?

**Comment by geerlingguy** [comment]
Strange... if that file doesn't exist, then I would think the `Remove existing SOLR_HEAP configuration.` task would also fail (unless Ansible doesn't care about the file not existing for `absent` lineinfile declarations.

Can you log into the VM and run `ls -lah /etc/` to see if that file is in `/etc`?

**Comment by geerlingguy** [comment]
Also, are you using `geerlingguy/ubuntu1604`, and any other changes to your `config.yml`?

The Solr installation process should copy the file over to `/etc`, so there shouldn't be a need to copy the file manually IIRC.

**Comment by cdmo** [comment]
It isn't in `/etc` and I'm running `geerlingguy/centos7`. Only change is the version.

Yeah, was figuring Ansible was thinking "yep, that line isn't in there" (because it doesn't exist, but it's technically true maybe).

I didn't see any task that copied that file specifically, but maybe I missed it... Thanks.

Maybe this would be interesting (note the first line is the one I manually copied):

```
[vagrant@staff drupalroot]$ sudo find / -name solr.in.sh -type f
/etc/default/solr.in.sh
/root/solr-5.3.1/bin/solr.in.sh
/var/solr/solr.in.sh
/opt/solr-5.3.1/bin/solr.in.sh
```

**Comment by geerlingguy** [comment]
Ah... it looks like on RHEL, it might be stored in `/etc/default/solr.in.sh` then (or maybe the proper one to edit is in `/var/solr`

Can you open an issue in the https://github.com/geerlingguy/ansible-role-solr/issues issue queue? This should be fixed upstream.

**Comment by geerlingguy** [comment]
Hard to test right now because of this Vagrant bug: https://github.com/mitchellh/vagrant/issues/8024

I'll have to downgrade Vagrant to test, or bring up a CentOS 7 Docker image instead.

**Comment by geerlingguy** [comment]
Closing in favor of the upstream issue https://github.com/geerlingguy/ansible-role-solr/issues/50
