### ISSUE TITLE
Question - php5-sybase, php5-odbc, freetds-common no longer work

### ISSUE THREAD

**Issue by chumkui** [geerlingguy/drupal-vm#1029]
### Issue Type

 -  Support Request

### Your Environment
```
Vagrant 1.8.7 (Windows)
VirtualBox 5.1.6r110634 (Qt5.5.1) (Windows)
ansible 2.2.0.0 (Ubuntu 14.04 LTS)
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
DVM Machine Ubuntu 14.04 LTS  - PHP 5.6
```

### Your OS

 - **Windows** (10)

### Full console output

N/A
### Summary

I know this has been deprecated but we still use these libraries to access data in MS SQL Server.  I used to have no problem using the  php5-sybase, php5-odbc and freetds-common libraries to connect to MS SQL Server - I just added them to the list of PHP packages in the config.yml.  I am now getting 'Call to undefined function mssql_connect()'.  I did a quick check between this and a working server and I am guessing it might be related to the Server API - FPM/FastCGI versus Apache.  When I do a PHPINFO() I cannot see the modules loaded.  The libraries are definitely installed, but there was no mssql.ini lsited and no MSSQL section.  I have searched around and tried to manually add an mssql.ini without luck. Is there a different approach in terms of getting PHP/Apache to load these libraries for a DVM machine?  Not sure when this crept in for me as just spun up an environment for a bug fix - pretty sure there was no problem 2-3 months ago.  Any help gratefully accepted

**Comment by geerlingguy** [comment]
@chumkui - Interesting... we did switch from Ondrej's old PHP 5.6 repository to a new general php library, so maybe the packages are gone from the new repository (the old one is now offline).

You might need to update the package names (assuming you're on the latest version of Drupal VM) to:

```
  - php5.6-sybase
  - php5.6-odbc
```

See: https://launchpad.net/~ondrej/+archive/ubuntu/php/+packages?field.name_filter=php5&field.status_filter=published&field.series_filter=

**Comment by chumkui** [comment]
Yup they are the ones I am using and I just updated to a 3 day old version of DVM to be sure.  These are what I added in the PHP package section:
  - php5.6-sybase
  - php5.6-odbc
  - freetds-common
  -freetds-bin

I used to use php5-sybase etc.  Just checked the link, the php5.6-sybase and php5.6-odbc are there

tsql from the command line works no issue...!

**Comment by geerlingguy** [comment]
So things work correctly in CLI, but not from Drupal itself?

**Comment by chumkui** [comment]
I do not think this is a Drupal issue.  I have tested with a really simple php file in the root of my test machine that just does the DB connect and I still get undefined function for mssql_connect().  It is working fine on our production websites, but these have been provisioned for ages.  It is a bit of a mystery to be honest.  You do not even need to have MS SQL Server to test this, just calling the function will throw the error.  Maybe there is more config that needs to be done - it is almost as if Apache cant see it.

**Comment by oxyc** [comment]
@chumkui would you mind posting your `config.yml` and I can see if I can reproduce/fix it

**Comment by geerlingguy** [comment]
Going to close for now—but @chumkui if you can post your `config.yml` so we can reproduce the issue, we can reopen the issue and go from there. Thanks!
