### ISSUE TITLE
PHP 7.1 - Timeline for switching to default

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1031]
[PHP 7.1.0](https://secure.php.net/releases/7_1_0.php) rolled in just in time for the new year!

It may take a short time before it's available through Remi's repos on RHEL, and Ondrej's PPA on Ubuntu, so this won't happen right away, but I would like to add support for it ASAP, and then decide when to switch the default from 7.0 to 7.1.

Also, we'd probably need to convert the existing [PHP 5.6 docs page](http://docs.drupalvm.com/en/latest/other/php-56/) over to something like "Using older versions of PHP", and list instructions for 5.6 and 7.0.

As part of this process, I'd like Ubuntu to default to using Ondrej's PPA no matter what, so we could technically swap out PHP 5.6, 7.0, and 7.1 on Ubuntu 16.04 (the current setup only allows PHP 7.0 on 16.04).

**Comment by oxyc** [comment]
Tests are passing for #1043 (I'm building 5.6, 7.0 and 7.1)! https://travis-ci.org/geerlingguy/drupal-vm/builds/182736056

Still needs manual testing though.

**Comment by geerlingguy** [comment]
@oxyc - Awesome, glad you could take up the gauntlet on this. I hope to get some time to test (now that I have a retina MBP for work, it has the beef to be able to do things without bogging down everything else on the system), and then maybe we can sneak this into the 3.6.0 release as well (since we're adding a few other slightly-breaking changes).

But what's your opinion of making this the 4.x release? We have enough little things, and this would be a really slick feature to headline a 4.0.

**Comment by oxyc** [comment]
Defaulting to 7.1 does sounds like a nice Drupal VM 4.0 👍 https://github.com/geerlingguy/drupal-vm/releases/tag/3.0.0

**Comment by oxyc** [comment]
XDebug does not work with 7.1 https://github.com/oerdnj/deb.sury.org/issues/444

**Comment by geerlingguy** [comment]
@oxyc - Good point about drush and failed builds. Switching major versions would do a lot to make sure people at least read through the 4.0 release notes!

I think I'll keep the default at 7.0—for various reasons (some Drupal bits and bobs still have edge case issues with 7.1 I'm hearing), but announce that 7.1 support is here. Hopefully within a few months we'll be able to find a way to get xhprof, xdebug, etc. all working splendidly with 7.1 as well!

**Comment by oxyc** [comment]
Another possible alternative to XHProf is [tideways](https://github.com/tideways/php-profiler-extension). Currently there's not 7.1 support, but it's still in development and the 7.1 build was recently added on travis. Tideways a XHProf fork which unfortunately, isn't a drop-in-replacement but has a data-format that is 100% compatible with XHProf–so the old GUI works. The PHP extension is open-source while users can pay for access to an online profiler UI. 

- https://www.drupal.org/project/tideways
- https://tideways.io/profiler/blog/php-7-release-of-tideways
- https://tideways.io/profiler/xhprof-for-php7-php5.6
- https://github.com/tideways/php-profiler-extension
- https://github.com/bdlangton/xhprof/commit/da127d922045d41044d36a7efbf1077bfeded59d

**Comment by geerlingguy** [comment]
Definitely an option... related, Blackfire support is also present. I haven't tried Tideways yet, but in either case, it's annoying to use external services to actually view/debug stuff. One of my favorite aspects of XHProf is that the entire process is local :)

**Comment by oxyc** [comment]
Same for me, I do prefer XHProf. Also found https://www.drupal.org/node/2832666 which would make this a very viable solution once merged and the extension supports 7.1

**Comment by geerlingguy** [comment]
@oxyc - Apparently the PHP Tideways extension can be used standalone, just like XHProf: https://github.com/tideways/php-profiler-extension#usage-without-tidewaysio-ui

I haven't had time to play with it... but it could be a good alternative since the extension seems to be actively maintained and not dying on the vine like XHProf.

**Comment by oxyc** [comment]
Yeah the data export should be compatible with the xhprof gui. I haven't verified that though.

**Comment by oxyc** [comment]
Update: The XHProf module now has support for [tideways](https://www.drupal.org/node/2832666).

**Comment by geerlingguy** [comment]
Working on a Tideways role...

**Comment by geerlingguy** [comment]
Working on it here: https://github.com/geerlingguy/ansible-role-php-tideways

**Comment by geerlingguy** [comment]
Giving up for the night—all tests pass, and the extension is loaded fine. Didn't get time to futz around with PHP 7.1 and getting actual profiling completed, or finalizing documentation, but I'm opening an issue + PR to kick off the work. Will link it in a minute.

**Comment by geerlingguy** [comment]
I did get some time to test after all (I guess, instead of sleeping...). It works just fine with the XHProf module, but I couldn't install the Tideways module on a D8 site, so I opened up a ticket on Drupal.org for that: [Can't install latest dev release on 8.x](https://www.drupal.org/node/2843481).

**Comment by geerlingguy** [comment]
I went ahead and merged the preliminary Tideways support. I haven't done any testing with the paid service at all, but I'm assuming it could be made to work if someone adds their API key to the configuration as documented in the role's README.

So @oxyc please check things over and see if there might be anything else holding back a 7.1 default. In my quick testing tonight, things look mostly good...

**Comment by oxyc** [comment]
Looks good! The one thing I would miss is the standalone XHProf UI. Could we somehow install it with a separate `ansible-php-xhprof-ui` role or a `ansible-php-xhprof` variable? 

The only task needed is https://github.com/geerlingguy/ansible-role-php-xhprof/blob/master/tasks/main.yml#L61:L64

**Comment by geerlingguy** [comment]
@oxyc - I think I prefer adding that task to Tideways, and have an optional install of XHProf UI (maybe even make that default, since I'd rather easy local experience be the default rather than all the complication of getting the site connected to tideways.io (I just burned an hour trying to get things going with the Drupal.org module... it's not as simple as locally displaying runs with the XHProf module + Tideways.so!

**Comment by heddn** [comment]
Where are we at with changing the default to 7.1?

**Comment by geerlingguy** [comment]
@heddn - I think it's time! If you'd like to submit a PR, I'll merge it. I've been on 7.1 for most things for a few months with no issues.

**Comment by geerlingguy** [comment]
'Tis done—thanks @heddn !
