### ISSUE TITLE
Trouble getting DrupalVM started on Mac OSX

### ISSUE THREAD

**Issue by mk1952** [geerlingguy/drupal-vm#1033]
### Issue Type

 - Support Request

### Your Environment

```
imac-1:dev2 martinknapp$ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 1.9.0
VirtualBox 5.1.10r112026
-bash: ansible: command not found
```

### Your OS

 - **macOS** (10.10.5)

### Full console output

https://gist.github.com/mk1952/18c7cafe48ea2b775f62e28cdb671b96
### Summary

I've been having trouble getting DrupalVM started on Mac OSX, apparently my first issue was with the old version of VirtualBox. I've now upgraded to VB1.5.10 things are going better, however I now get stuck at a password prompt. What should the password be? I've tried both "admin" and "drupal" to no effect.
Also, the ansible --version command suggests that ansible is not installed on my workstation - should this also have figured in the prerequisites along with vagrant and VB?

Just to summarise the Gist, here is where I'm getting stuck:
```
....
VirtualBox Guest Additions installer
Removing installed version 5.1.8 of VirtualBox Guest Additions...
Copying additional installer modules ...
Installing additional modules ...
vboxadd.sh: Building Guest Additions kernel modules.
vboxadd.sh: You should restart your guest to make sure the new modules are actually used.
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
mesg: ttyname failed: Inappropriate ioctl for device

==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
Sorry, try again.
```

**Comment by Jonfor** [comment]
The password is the password to the user on your actual machine. The same password you type in when you use sudo :)

You can also see the README mentioning why/how to install Ansible:

For faster provisioning (macOS/Linux only): Install [Ansible](https://docs.ansible.com/ansible/intro_installation.html) on your host machine, so Drupal VM can run the provisioning steps locally instead of inside the VM.

**Comment by mk1952** [comment]
Cool! I now seem to have a functioning Drupal VM, however I have a few suggestions especially to benefit folks like me. I don't know if this is general practice but when I see a "Quick Start Guide" my instinct is just to follow that to get something up and running so I can see what it does before I start digging deeper. So, there are a couple of things which could usefully be added to the "Quick Start Guide" IMHO (so that the start really is quick!):

1. Check the software versions (in fact couldn't this be automatic?).
2. Tell us about the host password we're going to need. IMHO the message is hardly explicit, if you look at my original report you can see we're getting a message from "drupalvm" about needing admin privileges, which rather suggests these are admin privileges in the VM, not on the workstation.

**Comment by geerlingguy** [comment]
> Check the software versions (in fact couldn't this be automatic?).

We can (and do) automatically check the Ansible version (if it's installed on the host), and the Vagrant version (currently 1.9.0 in `master`). But we can't automatically check the VirtualBox version for a few reasons. Instead, there's a 'recommended versions' note in the project's README.

> Tell us about the host password we're going to need. IMHO the message is hardly explicit, if you look at my original report you can see we're getting a message from "drupalvm" about needing admin privileges, which rather suggests these are admin privileges in the VM, not on the workstation.

This prompt is part of Vagrant/hostsupdater itself (or NFS, also part of Vagrant), so it's not a prompt we can override/change. Also, note that you can skip that altogether by modifying your sudoers file like I do—saves me time every day :) http://www.jeffgeerling.com/blogs/jeff-geerling/better-vagrant-development-workflow
