### ISSUE TITLE
Drupal 7.52 php 5.6 postgres or mysql results in SQLITE DB

### ISSUE THREAD

**Issue by i813380** [geerlingguy/drupal-vm#1035]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
-bash: ansible: command not found
```

### Your OS

 - **macOS** (version 10.12.1)

### Full console output

https://gist.github.com/i813380/5fc81dd86c1e1cc7d9e01f337aa4b2e1

### Summary

Configuration of ubuntu/trusty64, PHP 5.6 Drupal 7, using postgres (or mysql) results in database=sqlite

Forked repo with config here: https://github.com/i813380/drupal-vm

![image](https://cloud.githubusercontent.com/assets/15381286/20902678/2d873dc8-bb06-11e6-8a0d-082680011beb.png)

**Comment by geerlingguy** [comment]
Interesting... I haven't noticed this happening on D8 site builds, so I wonder if it's something with Drush and D7 in particular. Can you check what you have `drush_version` set to on your machine?

**Comment by i813380** [comment]
To answer your question:
```
vagrant@drupalvm:~$ drush --version
 Drush Version   :  8.2-dev 
```

It appears to be PHP related as the problem doesn't happen with PHP 7.  When I make the following changes, it switches to sqlite: http://docs.drupalvm.com/en/latest/other/php-56/

```
vagrant@drupalvm:~$ php -v
PHP 5.6.28-1+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
vagrant@drupalvm:~$ 
```

I'll continue to fiddle with the PHP stack...

**Comment by i813380** [comment]
Fixed.  Turns out needed missing packages:

```
@@ -247,6 +247,8 @@ php_packages:
   - php5.6-dev
   - php5.6-fpm
   - php5.6-gd
+  - php5.6-mysql
+  - php5.6-pgsql
```

![image](https://cloud.githubusercontent.com/assets/15381286/20932280/1610ae80-bba2-11e6-93dc-8ad69ec14e19.png)
