### ISSUE TITLE
Drupal Folder Not Empty error after deleting /drupal directory

### ISSUE THREAD

**Issue by GhostInTheMachinesAtTSBVI** [geerlingguy/drupal-vm#1041]
### Issue Type

Support Request

### Your Environment

Vagrant 1.9.0
VirtualBox
5.1.10r112026
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

```

### Your OS

Linux 16.04 LTS server

### Full console output

fatal: [goliath-drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:02.780428", "end": "2016-12-09 10:33:43.181445", "failed": true, "rc": 1, "start": "2016-12-09 10:33:40.401017", "stderr": "Installing drupal-composer/drupal-project (8.x-dev 3b9ee0d3a1c9363d53fc6da4111701269496e9ca)\n\n                                                             \n  [InvalidArgumentException]                                 \n  Project directory /var/www/drupalvm/drupal/ is not empty.  \n                                                             \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}

### Summary

vagrant provision command goes all the way through until composer install and then fails stating that the /drupal directory is not empty even after deleting the /drupal directory prior to running vagrant provision.

To get to this point I had to prevent a prior errror which could not find drupal.composer.json by copying example.drupal.composer.json over to this file name to prevent drupalvm from throwing the error that it is not there.  (seems like this should be in the quick start directions if it is a requirement)

**Comment by geerlingguy** [comment]
@GhostInTheMachinesAtTSBVI - Can you check, inside the VM, if the directory `/var/www/drupalvm/drupal` is empty?

```
$ ls -lah /var/www/drupalvm/drupal
```

It could be that you emptied the folder on your localhost, but it's not synced into the VM properly (which would be a different issue). Also, I usually nuke the entire folder (and not just the contents) in case there are hidden files still part of the folder (like .git, .htaccess, etc.).

**Comment by GhostInTheMachinesAtTSBVI** [comment]
Yes,  in the past few iterations I have been going into the synced folder, removing the contents then verifying with ls -al

This time,  I actually did a vagrant ssh and removed the drupal folder with a rm -rf drupal

Really a strange error unless directories get cached in some kind of variable.  I guess the next thing I will do is just remove everything from scratch again and see if I can reproduce the same set of errors.

I'll use debug mode on all of them in case I am missing some kind of prior error that is allowing trace files to get installed early on before Ansible runs.  (Reasoning being that the drupal directory does not look complete but I will have to look at the install at work and compare it with this one to verify that)

I am starting to get a feel for the different types of errors, but this new one is really a head scratcher.

**Comment by geerlingguy** [comment]
Maybe there's a... Ghost in the machine! 👻  :D

**Comment by geerlingguy** [comment]
I'll see myself out...

**Comment by GhostInTheMachinesAtTSBVI** [comment]
YES!  I diff'd the two instances I have of the config file and found a small error with seemingly "fatal" issues.  I had set the "build_composer" value to true on one of my config tweaks instead of the "build_composer_project" variable.  Once I have the time to learn more about changing this config file to fit my needs I suppose I will catch things like this faster.

Oh...and before you see yourself out,  ponder the immortal words of  Dudley Moore (Aurthur circa 1980) "Are you sure you want to be a night club comic?".

**Comment by geerlingguy** [comment]
:)

Glad you could get ti fixed! I'll go ahead and close this issue now.
