### ISSUE TITLE
Composer is only installing the latest 8.2.4 release though 8.3.x was set

### ISSUE THREAD

**Issue by rpkoller** [geerlingguy/drupal-vm#1044]
So far I never set the up a proper workflow for testing new stuff with Drupal. So far I ran a standard install on DrupalVM and that worked fine. But when I needed to try a newer Drupal version I manually upgraded and it felt a bit of hacky and cumbersome. Today along the UX sprint day I started first time little steps towards core with a tiny ticket. But it ended while updating to Drupal 8.3.x manually and later copying changed files over to test the changes with a complete unaccessible vm. ;) So I wanted to change a few things. One VM for 8.3.x-dev related stuff and the others with regular. Problem is when I try to set up `drupal/core` to `8.3.x-dev` or `8.3` or `8.3.x` inside the `durpal.composer.json` I end up with `8.2.4`anyway. :/ The `drupal/core` version is the only thing changed in comparison to `example.drupal.composer.json`. 
In`config.yml`I basically only adjusted `vagrant_hostname` and `vagrant_machine_name` and the username and password for Drupal and MYSQL as well as the DB name. The rest is identical to the `default.config.yml` . The particular lines relevant for composer are: 

```
build_composer_project: true
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"
```

So the idea was provision the VM when I need the latest Drupal version and after I am done destroy it and in case I need again reprovision for the latest Drupal dev version. Reasonable approach? But regarding the sticking to 8.2.4 I have no idea at all why. :/ Any clues appreciated. :) 

Oh and I am running on virtual box 5.1.10, vagrant 1.9.0 and ansible 2.2.0 on OSX 10.11.6. Thanks Ralf

**Comment by oxyc** [comment]
Using `build_composer_project: true` wont actually use the `drupal.composer.json` file. It's only used when you have `build_composer: true`. You can follow the instructions in the [docs](http://docs.drupalvm.com/en/latest/deployment/composer/#using-composerjson) on how to set it up.

**Comment by geerlingguy** [comment]
@rpkoller - Yeah, basically, what @oxyc said—you should only use `build_composer_project` if you want to build a project based on the Composer template (https://github.com/drupal-composer/drupal-project)—that process completely ignores the `drupal.composer.json` file, and it would require some other work to try to grab a dev/HEAD release of Drupal core.

Please check the docs link @oxyc provided, and if you have any questions about that process, let us know and we can reopen the ticket and discuss. Thanks!

**Comment by rpkoller** [comment]
thanks and sorry @geerlingguy @oxyc after yesterdays confusion I was in doubt of everything and not clearly thinking anymore. ;) But reread the documentation in a calm state today and redid the configuration (I already tried parts before but failed). Now it works. Booted with `8.3.0-dev` right now. :) thanks!

**Comment by geerlingguy** [comment]
@rpkoller - Awesome, glad you got it working!
