### ISSUE TITLE
Can't get Drupal 7 to install using DrupalVM v4

### ISSUE THREAD

**Issue by mikedaul** [geerlingguy/drupal-vm#1046]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.0.30r112061
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (version)

### Full console output

https://gist.github.com/mikedaul/afe16093e206a2ec7779de5c87554904

### Summary

I'm attempting to build a Drupal VM instance using Drupal 7. I've set my config file to specify:
- build_makefile: true
- build_composer: false
- drupal_major_version: 7
- php_version: 5.6
contents here: https://gist.github.com/mikedaul/7f58d33cbe15debf73b7379b19936760

And I've set the makefile to use 7.x and specified 7.44
contents here: https://gist.github.com/mikedaul/873c7dd4cba935965d928d63a3b7b78f

Once 'vagrant up' is done running, I can sign in to drupalvm.dev, but it's installed Drupal 8.2.4.

PHP is the correct version, fwiw.
Status Report here: https://gist.github.com/mikedaul/e3977d405a6cf51194496f51da0ed010

Thanks for any help!

-Michael Daul

**Comment by oxyc** [comment]
At least for the log you posted, there was already a drupal installation present when provisioning began.

> TASK [Copy drush makefile into place.] *****************************************
skipping: [drupalvm]
> TASK [Check if a composer.json file is present.] *******************************
skipping: [drupalvm]
> TASK [Generate Drupal project with composer package.] **************************
skipping: [drupalvm]

All three of them were skipped, so maybe you built D8 in the same directory before? Make sure you empty out the `drupal/` directory and then try again.

**Comment by mikedaul** [comment]
Doh! Now I feel silly. That totally did the trick.

I'd assumed running _vagrant destroy_ was all I needed to do in order to clean things up.

Thanks for your assistance!

**Comment by oxyc** [comment]
It's a pretty common problem around here :) Glad I could help!

**Comment by geerlingguy** [comment]
Yeah, don't be ashamed... I do the same thing at least once a week or so. It's easy to forget that the Drupal files aren't affected by a `vagrant destroy`.

**Comment by mikedaul** [comment]
Thanks Jeff - DrupalVM has been a huge help for us at work, so thanks for all of y'alls efforts!
