### ISSUE TITLE
Syntax Error running Vagrant Up (provisioning/roles/geerlingguy.solr/tasks/install.yml: line 27, column 3)

### ISSUE THREAD

**Issue by farah0808** [geerlingguy/drupal-vm#1052]
### Issue Type

 - Bug Report / Support Request

### Your Environment

vagrant@machine:~$ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 1.8.1
VirtualBox 5.0.24_Ubuntur108355
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

### Your OS

 - **macOS** 10.12.1

### Full console output

https://gist.github.com/farah0808/32d1c451d55a09c5c618623900300d31

### Summary

When trying to run 'vagrant up,' I get an error that no action was detected in task and the install.yml file, line 27, column 3 is the offending line (full error located in gist link) causing vagrant up and ansible to fail.

Attempting to set up a new box for Drupal 8. I have another (completely separate) box for Drupal 7 that works fine. I checked other issues. Upgraded to ansible 2.2.0.0, made sure there were no extra spaces in any part of the file, still getting the same error. Please let me know what other info you need. Thanks in advance!

**Comment by geerlingguy** [comment]
Two things to try—can you try upgrading Vagrant to 1.9.0 or 1.9.1, and also VirtualBox to 5.1.10?

Second, this usually happens if Ansible 2.1 or lower is running... I wonder if it's possible that Ansible isn't detected by Vagrant? Probably not, but worth checking—run `which ansible` and `ansible --version` again just to confirm you can see it.

**Comment by farah0808** [comment]
vagrant@machine:~$ which ansible
/usr/bin/ansible
vagrant@machine:~$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

I'll try updating now. I was hesitant because my 7 box seems to go haywire when the versions are even a little newer. I'll give it a try

**Comment by geerlingguy** [comment]
Closing for now - please let me know if this is still an issue after the upgrades!
