### ISSUE TITLE
Install dependencies with composer require.

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#1057]
I am getting this error with drupalvm 4 even after vagrant destroy several times 

TASK [Install dependencies with composer require.] *****************************
failed: [drupalvm] (item=drupal/devel:1.x-dev) => {"changed": true, "cmd": ["/usr/bin/composer", "require", "drupal/devel:1.x-dev"], "delta": "0:02:04.873647", "end": "2016-12-17 18:40:42.393952", "failed": true, "item": "drupal/devel:1.x-dev", "rc": 1, "start": "2016-12-17 18:38:37.520305", "stderr": "You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug\n./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\n  - Updating drupal/devel dev-1.x (e693a59 => 065551b)\n\nInstallation failed, reverting ./composer.json to its original content.\n\n                                                                       \n  [RuntimeException]                                                   \n  Source directory web/modules/contrib/devel has uncommitted changes.  \n                                                                       \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...", "stdout": "Patching is disabled. Skipping.", "stdout_lines": ["Patching is disabled. Skipping."], "warnings": []}
	to retry, use: --limit @/Users/martinoru/Sites/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=148  changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by oxyc** [comment]
Did you delete the `drupal/` directory before destroying the VM? It sounds as if the codebase already exists and that the devel directory has some untracked changes.

**Comment by mooru** [comment]
Fixed

**Comment by shrop** [comment]
Thanks @oxyc. Your solution resolved the same issue for me!
