### ISSUE TITLE
Composer-installer.php allowed memory size exhausted

### ISSUE THREAD

**Issue by robbdavis** [geerlingguy/drupal-vm#1063]
### Issue Type

 - Bug Report / Support Request
 

### Your Environment

Vagrant 1.9.0
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

### Your OS

 - **macOS** (version)

### Full console output
fatal: [fgsvm]: FAILED! => {"changed": true, "cmd": ["php", "composer-installer.php"], "delta": "0:00:00.039621", "end": "2016-12-20 17:23:36.172577", "failed": true, "rc": 255, "start": "2016-12-20 17:23:36.132956", "stderr": "PHP Fatal error:  Allowed memory size of 262144 bytes exhausted (tried to allocate 12288 bytes) in /tmp/composer-installer.php on line 253", "stdout": "\nFatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 12288 bytes) in /tmp/composer-installer.php on line 253", "stdout_lines": ["", "Fatal error: Allowed memory size of 262144 bytes exhausted (tried to allocate 12288 bytes) in /tmp/composer-installer.php on line 253"], "warnings": []}

### Summary

I seem to be running into a memory limit with composer-installer

Trying to set up PHP5.6 on NGINX

**Comment by robbdavis** [comment]
Uhg.. never mind. I changed the PHP memory limit and accidentally left off the  M.  Closing this.

Thanks for all the work on this by the way! I really appreciate it and have now abandoned my stale old "bare metal" dev environment.

**Comment by geerlingguy** [comment]
Glad you got it figured out!

**Comment by siliconmeadow** [comment]
I did the same thing just now - I left off the M.

Searching closed issues ftw.
