### ISSUE TITLE
Drupal VM on production does not set hostname

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1067]
### Issue Type

 - Feature request

### Full console output

> Dec 21 11:16:40 ubuntu postfix/smtp[31700]: 7610339C0F: to=public@oxy.fi, relay=mail.oxy.fi[80.83.6.133]:25, delay=0.71, delays=0/0/0.61/0.1, dsn=5.0.0, status=bounced (host mail.oxy.fi[80.83.6.133] said: 550-Verification failed for www-data@ubuntu.members.linode.com 550-The mail server could not deliver mail to www-data@ubuntu.members.linode.com. The account or domain may not exist, they may be blacklisted, or missing the proper dns entries. 550 Sender verify failed (in reply to RCPT TO command))

### Summary

If we want to improve on how well drupal vm works on production environments, this would be nice to provision out of the box. Otherwise maybe just some docs?

On Ubuntu 16.04
- `vagrant_hostname` needs to be set to `drupal_domain` in the `prod.config.yml` example. This also fixes issues with mailhog/solr using the wrong hostname in the dashboard
- Add `127.0.0.1 {{ vagrant_hostname }}` to `/etc/hosts`
- Change the contents of `/etc/hostname` to `{{ vagrant_hostname }}` (edit: just realized this is usually set to the hostname without the TLD. Why is that?)
- Change the contents of `/etc/mailname` to `{{ vagrant_hostname }}`
- Maybe call `hostname {{ vagrant_hostname }}` so it works without a reboot? `service hostname restart` did not work.

Sidenote: Amazing how well this worked otherwise! I got wildcard subdomains with https and proxy-only access to dev tools with just making changes in `config.yml`. Following the docs worked great for linode as well.

Edit: We also fix this on travis to be able to run the tests https://github.com/geerlingguy/drupal-vm/blob/master/.travis.yml#L66

**Comment by geerlingguy** [comment]
The rabbit hole goes deeper of course, see [How to get your server's emails through Gmail's spam filter with Exim](http://www.jeffgeerling.com/blog/2016/how-get-your-servers-emails-through-gmails-spam-filter-exim) and [Configure sendmail on CentOS to allow sending of email from localhost](http://www.jeffgeerling.com/blogs/jeff-geerling/configure-sendmail-centos), among other articles about SPF, reverse DNS, DKIM, etc.

But we should at least get the basics correct, so I'd be fine configuring the things you list above there.

**Comment by oxyc** [comment]
True... maybe I should rename the issue to _Drupal VM on production does not set correct hostname_ and we just make sure `/etc/mailname` is set as well :)

**Comment by geerlingguy** [comment]
That sounds good to me.

**Comment by geerlingguy** [comment]
Fixed via PR https://github.com/geerlingguy/drupal-vm/pull/1070
