### ISSUE TITLE
Syntax error in solr .install file on macOS with Ubuntu 16.04.01

### ISSUE THREAD

**Issue by jamiehollern** [geerlingguy/drupal-vm#1069]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.10r112026
ansible 2.2.0.0
```

### Your OS

 - **macOS** Sierra (10.12.1 (16B2555))

### Full console output

Tried to reinstall the latest DrupalVM. Destroyed the old VM, ran a cleanup then ran `composer install && vagrant up`. The error output is below, with the full console output in the Gist above.

https://gist.github.com/jamiehollern/530f80dc092d11ebae5fa4046f27e3f1

### Summary

```
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/jamie.hollern/Projects/elife/journal/test-cms-fork/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Run systemd daemon_reload (RHEL 7 workaround).
  ^ here


The error appears to have been in '/Users/jamie.hollern/Projects/elife/journal/test-cms-fork/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.solr/tasks/install.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Run systemd daemon_reload (RHEL 7 workaround).
  ^ here

Ansible failed to complete successfully. Any error out
```

**Comment by geerlingguy** [comment]
Please see my comment on https://github.com/geerlingguy/drupal-vm/issues/1065

**Comment by jamiehollern** [comment]
@geerlingguy Many thanks for your prompt response, but unfortunately I'm already running that latest version of Ansible (2.2.0.0).

**Comment by geerlingguy** [comment]
Hmm... so you are.

Can you verify that running `which ansible` shows the path to Ansible, and `ansible --version` definitely gives `2.2.0`?

This warning occurs when Ansible can't find the module that's used in that task. In this case, it's the `systemd` module, which was only included in 2.2.0+: https://github.com/geerlingguy/ansible-role-solr/blob/master/tasks/install.yml#L31

**Comment by geerlingguy** [comment]
Also, it is definitely using system Ansible according to the gist you posted... so this is perplexing, because 2.2.0 definitely includes the `systemd` module :/

**Comment by jamiehollern** [comment]
@geerlingguy Figured it out. Whilst my version of Ansible was correct, the command being run was using `ansible-playbook` which was at version 2.1.1.0. I symlinked that location to the normal ansible binary and it works perfectly now.

**Comment by geerlingguy** [comment]
Great! Glad you could get that working. Also, if you're not using `pip` or `brew` to manage your Ansible installation, it might be best to switch to one of those package managers—helps to make sure all the `ansible-*` commands are correct :)
