### ISSUE TITLE
Drush make failed. [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by ryanschmidt** [geerlingguy/drupal-vm#1072]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.8r111374
-bash: ansible: command not found
```

### Your OS

 - **macOS** 10.12.2

### Full console output

https://gist.github.com/ryanschmidt/3cd90bc6a3d370e402426e2eb43afe19

### Summary

I've upgraded to the most recent version of Drupal VM. The last version I had was from no more than 30 days ago. Now after running `vagrant up` with no other config changes I am receiving this error related to the location of drush.

By the way, I am intentionally running Ansible locally (not on my machine but on the vm) and would like to keep it that way.

Any help would be appreciated!

**Comment by oxyc** [comment]
We recently made `drush` optional and you need to update your `config.yml`. See the release notes https://github.com/geerlingguy/drupal-vm/releases/tag/4.0.0. Also https://github.com/geerlingguy/drupal-vm/issues/1013#issuecomment-262871890.

**Comment by ryanschmidt** [comment]
@oxyc thanks! I can't believe I didn't catch that. Is it best practice to not touch default.config.yml and instead make all overrides in config.yml? Seems like that might be the easiest way to keep a custom version of Drupal VM still easily upgradable.

**Comment by oxyc** [comment]
Yeah that's what I do, and I would say it's the easiest way. BLT does that as well [for example](https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/config.yml).

**Comment by geerlingguy** [comment]
@ryanschmidt - I do the same as @oxyc — the quick start guide still mentions copying the default to `config.yml`, I think... maybe we need to change the wording to say "overrides only" or something?

**Comment by ryanschmidt** [comment]
@geerlingguy I think that's a good idea. The BLT example really helped me. Feeling good about my fresh new `config.yml` now. Thanks again for both of your hard work on this project. Much appreciated!

**Comment by oxyc** [comment]
https://github.com/geerlingguy/drupal-vm/pull/648#issuecomment-221428201. I can't find where we actually decided that though 😄. But yes I agree, it might be time to update and suggest overriding rather than copying.

**Comment by cdmo** [comment]
just merged the latest after not merging for (too many months) and this caught me too. Thanks.
