### ISSUE TITLE
Split out site installation from makefile build process

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#108]
Currently there is:
build_from_makefile = TRUE

Want to split this up into:
build_from_makefile = TRUE
site = “default”
site_install = TRUE

Desire to split up the make file execution from the site installation

**Comment by geerlingguy** [comment]
This looks like a good idea—one question, what would the `site = "default"` be used for?

**Comment by nerdstein** [comment]
This idea is already done. It is "site_name"

**Comment by geerlingguy** [comment]
The var for that is `drupal_site_name` :)

**Comment by geerlingguy** [comment]
I think I'll go with two vars, `build_makefile`, and `install_site`.

**Comment by geerlingguy** [comment]
I've updated https://github.com/geerlingguy/drupal-vm/wiki/Local-Drupal-codebase, and will push up the fix in a few min.

**Comment by nerdstein** [comment]
Awesome!

**Comment by geerlingguy** [comment]
:)
