### ISSUE TITLE
Provisioning fails: UNREACHABLE! Failed to connect to host with ssh

### ISSUE THREAD

**Issue by bleen** [geerlingguy/drupal-vm#1083]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.12.2

### Full console output
https://gist.github.com/bleen/32b54d7cb04a4fb79db006029d617d74

### Summary
As you can see in the gist linked above, the error I am getting happens on the [setup] task in the ansible playbook:

```
TASK [setup] *******************************************************************
fatal: [drupalvm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: command-line line 0: garbage at end of line; \"(Personal)/Mackup/.ansible/cp/ansible-ssh-%h-%p-%r\".\r\n", "unreachable": true}
```

I've been following the quickstart instructions on a newly wiped machine ... there is not a lot installed or configured on this Mac yet.

Also, note that I made no customizations to config.yml.

Any thoughts?

**Comment by geerlingguy** [comment]
@bleen - Two things to try: can you run the following commands and then see if `vagrant destroy -f` and `vagrant up` fixes things?

```
vagrant plugin install vagrant-vbguest
vagrant plugin install vagrant-hostsupdater
```

**Comment by bleen** [comment]
identical result 😢

**Comment by geerlingguy** [comment]
@bleen - If you run `vagrant ssh` does it do the same? And if you run `vagrant ssh-config`, can you paste the results?

Finally, can you list the output for all the vboxnet interfaces when running `ifconfig`?

**Comment by bleen** [comment]
```
> vagrant ssh                                                                                                                                                                     2.5m  Tue Dec 27 11:32:49 2016
Welcome to Ubuntu 16.04.1 LTS (GNU/Linux 4.4.0-31-generic x86_64)
```

```
> vagrant ssh-config                                                                                                                                                                 44.5s  Tue Dec 27 13:24:02 2016
Host drupalvm
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/bleen/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
```

```
> ifconfig
...
vboxnet0: flags=8943<UP,BROADCAST,RUNNING,PROMISC,SIMPLEX,MULTICAST> mtu 1500
	ether 0a:00:27:00:00:00
	inet 192.168.88.1 netmask 0xffffff00 broadcast 192.168.88.255
```

**Comment by geerlingguy** [comment]
Interesting... in this case, it looks like SSH is running okay, and Vagrant can connect to the site.

Can you share what the URL is for the site, and can you print off `cat /etc/hosts`?

**Comment by bleen** [comment]
```
> cat /etc/hosts

##
# Host Database
#
# localhost is used to configure the loopback interface
# when the system is booting.  Do not change this entry.
##
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
192.168.88.88  drupalvm.dev  # VAGRANT: 44ad77f101510a3a82e26b39e18217a1 (drupalvm) / 80221a71-b1a2-4b2b-ac0f-93a177a01090
192.168.88.88  www.drupalvm.dev  # VAGRANT: 44ad77f101510a3a82e26b39e18217a1 (drupalvm) / 80221a71-b1a2-4b2b-ac0f-93a177a01090
192.168.88.88  adminer.drupalvm.dev  # VAGRANT: 44ad77f101510a3a82e26b39e18217a1 (drupalvm) / 80221a71-b1a2-4b2b-ac0f-93a177a01090
192.168.88.88  xhprof.drupalvm.dev  # VAGRANT: 44ad77f101510a3a82e26b39e18217a1 (drupalvm) / 80221a71-b1a2-4b2b-ac0f-93a177a01090
192.168.88.88  pimpmylog.drupalvm.dev  # VAGRANT: 44ad77f101510a3a82e26b39e18217a1 (drupalvm) / 80221a71-b1a2-4b2b-ac0f-93a177a01090
192.168.88.88  dashboard.drupalvm.dev  # VAGRANT: 44ad77f101510a3a82e26b39e18217a1 (drupalvm) / 80221a71-b1a2-4b2b-ac0f-93a177a01090
```

> Can you share what the URL is for the site
I didn't ever get this far. I was just following the instructions at https://github.com/geerlingguy/drupal-vm#quick-start-guide and got to step 2.5

**Comment by geerlingguy** [comment]
If you run `ping drupalvm.dev`, does it return a response? If so, the Ansible connection should be working, I should think...

**Comment by bleen** [comment]
```
ping drupalvm.dev
```
works fine...

**Comment by bleen** [comment]
was talking @scottrigby and he was reminding me that directories with spaces may actually be the issue:

```
ls -la ~/.ansible                                                                                                                                                                                                  Tue Dec 27 13:52:47 2016
lrwxr-xr-x  1 bleen  staff  47 Dec 21 16:12 .ansible -> /Users/bleen/Dropbox (Personal)/Mackup/.ansible
```

Ill try moving my .ansible somewhere safer and see what happens

**Comment by geerlingguy** [comment]
Yeah, that could definitely be it—I try to avoid spaces and anything outside of 0-9/A-Z/a-z in directory paths because there's always something weird that happens... Ansible seems to not like the space in this case (or it could be a Vagrant bug in the Ansible provisioner).

**Comment by bleen** [comment]
Ok ... I have confirmed that spaces are, indeed, the devil. 

Thanks for the help.

**Comment by scottrigby** [comment]
Yep, it's a Vagrant issue (was an upstream Ruby issue, but that's since been resolved). There's an open PR for it now, if anyone wants to test it!: https://github.com/mitchellh/vagrant/pull/7967

**Comment by geerlingguy** [comment]
Takeaway: _spaces are the devil_

Glad we could figure it out... that was a weird one!

**Comment by tomasbreffitt** [comment]
I am also having this issue, but my ansible folder is not aliased anywhere and sits in my home directory with no spaces
