### ISSUE TITLE
Vagrant provision failing with MySQL install section

### ISSUE THREAD

**Issue by BrianWillows** [geerlingguy/drupal-vm#1087]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.0
sh.exe": vboxmanage: command not found
VirtualBox
sh.exe": ansible: command not found
```

### Your OS

 - **Windows** 8.1 Pro

### Full console output

TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
failed: [drupalvm] (item=[u'mysql-common', u'mysql-server']) => {"cache_update_time": 1483007417, "cache_updated": false, "failed": true, "item": ["mysql-common", "mysql-server"], "msg": "'/usr/bin/ap
t-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'mysql-server'' failed: E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify
a solution).\n", "stderr": "E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading stat
e information...\nYou might want to run 'apt-get -f install' to correct these:\nThe following packages have unmet dependencies:\n mariadb-server : Depends: mariadb-server-10.0 (>= 10.0.28-0ubuntu0.16.
04.1) but it is not going to be installed\n mysql-server : Depends: mysql-server-5.7 but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...",
 "Reading state information...", "You might want to run 'apt-get -f install' to correct these:", "The following packages have unmet dependencies:", " mariadb-server : Depends: mariadb-server-10.0 (>=
10.0.28-0ubuntu0.16.04.1) but it is not going to be installed", " mysql-server : Depends: mysql-server-5.7 but it is not going to be installed"]}

### Summary

Windows GitBash shell is rubbish for "full output" (so this is just the offending section). I've not yet managed to get vagrant provision to work yet and I've made no modifications to the basic git checkout master.

**Comment by geerlingguy** [comment]
@BrianWillows - Do you have any modifications in your `config.yml`? It looks like it might be trying to install both `mariadb` and `mysql`. Also, have you switched between CentOS and Ubuntu at all? CentOS would attempt installing MariaDB by default if using the `geerlingguy/centos7` box.

**Comment by BrianWillows** [comment]
No modifications, but I had switched. I had tried CentOS to see if it was different. I've retried with clean up-to-date pull from origin and it was getting the same error.  I then did vagrant destroy followed by

```
$ vagrant up --provision
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.dev
==> drupalvm: Running provisioner: ansible_local...
An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again.

If the problem persists, please report a bug to the net-ssh project.

timeout during server version negotiating
```
Sorry about this - I've probably got a misunderstanding of what's going on but any help to clear this up is much appreciated.

**Comment by geerlingguy** [comment]
@BrianWillows - For the SSH issue... can you make sure you're running VirtualBox 5.1.6 or later? 5.0.x has some issues with connection in new versions of Vagrant.

**Comment by BrianWillows** [comment]
That totally fixed it. Thanks for your help

**Comment by geerlingguy** [comment]
@BrianWillows - Awesome, thanks for posting back!
