### ISSUE TITLE
4.1.0 release tasks

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1089]
Amazingly, there weren't any major bugs as a result of the 4.0.0 release requiring a separate bugfix release... so we're skipping straight ahead to 4.1.0!

  - [x] Update CHANGELOG
  - [x] Cut a <s>rug</s> tag
  - [x] Add tag release notes
  - [x] <s>Blog post on Planet</s> (not big enough for this kind of fanfare)
  - [x] Submit PR to update BLT
  - [x] Update www.drupalvm.com (needed?)

**Comment by oxyc** [comment]
Oh right, we should probably all the vhost examples in `docs/` I'll submit a PR.

**Comment by geerlingguy** [comment]
@oxyc - Sounds good! Would've definitely forgotten.

**Comment by geerlingguy** [comment]
I'll get back to this tonight or tomorrow morning; gotta run.

**Comment by geerlingguy** [comment]
Working on the changelog now.

**Comment by geerlingguy** [comment]
Tagged: https://github.com/geerlingguy/drupal-vm/releases/tag/4.1.0

**Comment by geerlingguy** [comment]
BLT PR: https://github.com/acquia/blt/pull/899

**Comment by geerlingguy** [comment]
No need to make any updates to the public site. Woohoo, 4.1.0 is a thing!
