### ISSUE TITLE
Re-organize docs for better usability

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1092]
For a while we've been piling docs into existing topics which make them difficult to find. Also the list of topics have grown and should be organized so the reader can more easily find what they're looking for.

The problems I see:

- There are too many items in _Other information_. This should be the last place people look for answers.
- Extra software is as well, too long. Also I expect this to be related to `installed_extras`, while it actually contains tons of other things.
- Vagrantfile.local is too well hidden
- Drupal VM as a Composer Dependency should probably be brought to readers attention more
- Currently there's not much order in which you're supposed to read through the docs.

---

A first draft with some of my thoughts:

- Getting Started
  - How to configure Drupal VM
  - Vagrant synced folders
- Building your codebase:
    _(This is probably the most common thing users want to understand.)_
  - A local Drupal codebase
  - Using composer.json
  - Using a composer package
  - Using a Drush Make file
  - Drupal VM as a Composer Dependency
    _(I feel this should be more visible in the docs)_
- Basic configurations:
    _(Second most common thing would be webserver/database/php. Maybe this could be merged with Getting Started.)_
  - Using different Ubuntu/Centos base OSes
  - Using other versions of PHP
  - Webservers:
    - Using Apache
    - Using Nginx
    - SSL VirtualHosts
  - Databases:
    - Connect to the MySQL Database
    - Use MariaDB instead of MySQL
    - Use PostgreSQL instead of MySQL
- Installed Extras:
    _(Idea is that this matches `installed_extras` variable)_
  - Adminer: Connect to the database
  - Drush
  - Drupal Console
  - MailHog: Catching Emails
  - Node.js and NPM
  - Pimp My Log: View server logs
  - Selenium: Testing with Behat and Selenium
  - Solr: For search
  - Varnish
  - XDebug: Debug Code
  - XHProf, Blackfire, XDebug: Profiling code
- Advanced Configuration:
  - Overriding with local.config.yml, vagrant.config.yml, prod.config.yml files
  - Extending Vagrantfile with Vagrantfile.local
  - Passing on CLI arguments to ansible
  - Pre- and Post-Provision Scripts
- Vagrant troubleshooting:
    _(If I used linux/windows and wanted to debug I would look for a troubleshooting section)_
  - Linux
  - Windows
  - Networking
  - Vagrant and VirtualBox Tips
- Other Information:
  - BigPipe with Drupal VM
  - Drupal multisite
  - Drupal 6 Notes
  - Drupal VM Management Tools
  - Deploying to a production environment

**Comment by oxyc** [comment]
@geerlingguy maybe you can ask on twitter what actual Drupal VM users found difficult/illogical about the docs?

**Comment by geerlingguy** [comment]
@oxyc - 140 characters is a little rough, but here we go: https://twitter.com/geerlingguy/status/814871272400318464

**Comment by geerlingguy** [comment]
(I'm also thinking about doing a brief survey to see how users are using Drupal VM sometime, like a Google Forms form to fill out, or SurveyMonkey.)

**Comment by oxyc** [comment]
How about making _Getting started into a page, not just a section heading_.

- Getting Started
  - Installation
    - Mac OSX
    - Linux
    - Windows
  - How to configure Drupal VM
  - Vagrant synced folders

## Getting started

Read the quick start guide.... link.

Installation steps/instructions for windows (link), osx, linux (..)

### Subpage: Mac OSX

Video

### Subpage: Linux

Same OSX video

Move the _Platform-specific Install Instructions_ docs from _Linux Notes_ here.

### Subpage: Windows

Video

Move _Windows Subsystem for Linux / Ubuntu bash_ and _Command line environment_ from _Windows Notes_.

---

Maybe move all those notes into these sections? Or maybe keep troubleshooting/configugration options separated but end the _Getting started_ section with clear links to the possible issues.

**Comment by geerlingguy** [comment]
I like that... much more clear for a newcomer. And I can work on the videos soon, and do one for Ubuntu, one for macOS, and another for Windows.

**Comment by oxyc** [comment]
@geerlingguy is it better to keep the quick start guide in the README or should we move it to docs instead?

**Comment by geerlingguy** [comment]
@oxyc - That's a good question. I kinda like it in the README just because I know _I_ usually skip a project's docs site and head straight through the README to hopefully get off the ground. But we could trim down the README by putting it in the docs, and focus the README on getting people to the right place, quickly.

**Comment by geerlingguy** [comment]
@oxyc - I'll try to take a look at docs overall with a goal of merging this work by the end of the month. Now that search is working, the only main concern I have is that existing links from many places will get broken (I wish it were possible to set up 301/302s in RTD...).

**Comment by oxyc** [comment]
@geerlingguy if we change the structure entirely (as with the current suggestion) we could keep the old files but add meta redirect tags as their only content.

> The meta refresh is a directive in the header of a document indicating that, after a certain quantity of time is passed, the browser should redirect to a new location (or reload the page). Search engines appear to treat most short meta refreshes (a few seconds in length) as permanent redirects, passing the link equity and ranking metrics to the target page (they also claim to do this 100% of the time for meta refreshes marked with "0" seconds of delay). 
> https://moz.com/blog/answers-to-the-seo-professionals-litmus-test

http://sebastians-pamphlets.com/google-and-yahoo-treat-undelayed-meta-refresh-as-301-redirect/

**Comment by geerlingguy** [comment]
@oxyc - Would that work while not affecting the new structure in RTD? I imagine we could leave the old files a few months then remove them in a follow up.

**Comment by oxyc** [comment]
Darn, I guess not. https://github.com/mkdocs/mkdocs/issues/699 mkdocs really does not like me.

**Comment by geerlingguy** [comment]
Shucks :(

**Comment by oxyc** [comment]
@geerlingguy anything you want me to start working on?

**Comment by oxyc** [comment]
Additions that have come up in other issues recently:

> Could we add a paragraph in the docs, along the lines of "this is how to setup DrupalVM for contributing to core"?
> https://github.com/geerlingguy/drupal-vm/issues/1116#issuecomment-272159320

Definitely useful. Could reference both https://github.com/thom8/drupal8-vagrant and @geerlingguy workflow as some examples.

> Add drupalvm_cron_jobs to documentation.
> https://github.com/geerlingguy/drupal-vm/issues/1110

I think this would be good to have available somewhere in the docs so you something is found when you search for _cron_. I dont necessarily think it needs its own section as it is pretty straight forward and clear in the `default.config.yml`. The issue is you dont find anything when searching for it in the docs. @geerlingguy mentioned interest in adding support for letsencrypt eventually. Maybe this could qualify as we obviously would want to add a cron task for renewing the certificates.

**Comment by geerlingguy** [comment]
@oxyc - I'm kinda willing to say 'screw it' to all the existing URLs and just merge your PR and go from there :)

Now that search is working, I'm not as opposed to breaking URLs, and technically I could proxy the site and manage redirects through my own reverse proxy or something (since I control the DNS)... but instead I think we could just switch to what's in your PR and go from there.

Do you want to give it another once-over and then I'll merge today sometime?

**Comment by oxyc** [comment]
The PR is pretty outdated by now, but if you think the outline I have above is good, I can start working on it.

**Comment by oxyc** [comment]
Also, do you prefer if I just restructure and leave addition/changes for another PR or should I just open up a "Change all the things!"-PR? :D

**Comment by geerlingguy** [comment]
@oxyc - Change all the things!

![](http://m.memegen.com/odpbg5.jpg)
