### ISSUE TITLE
#1090 SetHandler PR broke Ubuntu 14.04

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1093]
### Issue Type

- Bug Report / Support Request

### Full console output

```
$ curl http://drupalvm.dev/
<?php

/**
 * @file
 * The PHP page that serves all page requests on a Drupal installation.
 *
 * All Drupal code is released under the GNU General Public License.
 * See COPYRIGHT.txt and LICENSE.txt files in the "core" directory.
 */

use Drupal\Core\DrupalKernel;
use Symfony\Component\HttpFoundation\Request;

$autoloader = require_once 'autoload.php';

$kernel = new DrupalKernel('prod', $autoloader);

$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send()
```

### Summary

We were too hasty :( The PR broke older Ubuntu versions (just tested on 14.04) which install Apache 2.4.7. Apparently SetHandler requires 2.4.9.

**Comment by oxyc** [comment]
I guess we either revert the PR, or add ondrejs apache ppa.

**Comment by geerlingguy** [comment]
@oxyc let's go with 2.4.9+.

Ugh, Ubuntu!!!

**Comment by geerlingguy** [comment]
Fixed in #1093

**Comment by geerlingguy** [comment]
Tagged in 4.1.1 https://github.com/geerlingguy/drupal-vm/releases/tag/4.1.1

**Comment by geerlingguy** [comment]
Hmm... on one of my own projects, the page was loading plain text .php files, and when I logged in and checked, I got:

```
$ apache2 -v
Server version: Apache/2.4.7 (Ubuntu)
Server built:   Jul 15 2016 15:34:04
```

Do we need to add anything to the `geerlingguy.apache` role to support different repos for the Apache install? https://github.com/geerlingguy/ansible-role-apache/blob/master/tasks/setup-Debian.yml#L6

**Comment by oxyc** [comment]
Shouldn't this cover it? https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L24:L28

**Comment by geerlingguy** [comment]
One would think... Testing on another Mac.

**Comment by oxyc** [comment]
> Server built:   Jul 15 2016 15:34:04

So the provision never triggered a re-install. We need `state=latest` rather than `installed`?

**Comment by geerlingguy** [comment]
@oxyc ah, that could be it... maybe if that's not configurable, it _should_ be configurable in the role.

**Comment by oxyc** [comment]
I'd say that's a good feature for the role. `geerlingguy.php` has `php_packages_state`, and if I recall a few of your other roles have this as well (`geerlingguy.mysql` doesnt).

**Comment by geerlingguy** [comment]
@oxyc yep! Forgot to finish testing, will do later today I hope.

**Comment by geerlingguy** [comment]
@oxyc - I added it upstream in 2.0.1. Need to run for now, but if you want to update the role in a Drupal VM PR I'll merge whenever (otherwise I'll get to it sooner or later!).
