### ISSUE TITLE
VM loses time when host sleeps

### ISSUE THREAD

**Issue by wturrell** [geerlingguy/drupal-vm#1097]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file = /Users/wt/.ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.11.6

### Full console output

n/a

### Summary

What's your technique for keeping the time of the Vagrant box in sync with the host?

Mine steadily loses time every time the host Mac sleeps.  

There is a [StackOverflow question](http://stackoverflow.com/questions/19490652/how-to-sync-time-on-host-wake-up-within-virtualbox) about this, but the top-voted answer doesn't work for me with DrupalVM for some reason ("Could not find a registered machine named" either the id or the name).

**Comment by oxyc** [comment]
Does it work if you create a `Vagrantfile.local` with:

```rb
config.vm.provider :virtualbox do |v|
  v.customize ['guestproperty', 'set', :id, '/VirtualBox/GuestAdd/VBoxService/--timesync-threshold', 10000]
end
```

**Comment by wturrell** [comment]
@oxyc it doesn't *seem* to make any difference - I've added that file, taken the VM up and down, also run `vagrant provision` on it, and if I sleep the host Mac for a few minutes then wake it again, the clock is still where it was when it slept, even waiting 10 seconds+ for it to reset.

**Comment by oxyc** [comment]
@wturrell it might. Same result if you run `vagrant destroy` using the id? There's also `vagrant global-status --prune` that maybe can help.

**Comment by oxyc** [comment]
Worth noting, `VBoxManage` has a different vm name than vagran's machine name. Run `VBoxManage list vms` to see the names.

I tested adding a `Vagrantfile.local` with:

```rb
config.vm.provider :virtualbox do |v|
  v.customize ['guestproperty', 'set', :id, '/VirtualBox/GuestAdd/VBoxService/--timesync-threshold', 10000]
end
```

If I put my computer to sleep the VM time is off until I run `vagrant reload`, at that point it syncs.

**Comment by oxyc** [comment]
My example had a "typo", it should be `--timesync-set-threshold`, not `--timesync-threshold`:

```rb
config.vm.provider :virtualbox do |v|
  v.customize ['guestproperty', 'set', :id, '/VirtualBox/GuestAdd/VBoxService/--timesync-set-threshold', 10000] 
end
```

I can confirm this fixed the sync for me. As soon as I wake my host, the VM's clock is correct.

**Comment by jimmyko** [comment]
I am trying this. Looks good. I need one week to see how it goes.

**Comment by wturrell** [comment]
@oxyc `vagrant global-status --prune` has cleaned up the duplicate entry, thanks.  Meanwhile the time started syncing (after a while, for no obvious reason) with your first snippet of code...

**Comment by geerlingguy** [comment]
@wturrell - Thanks for the update! And @oxyc thanks for the info! I'll close this issue out as it seems there is a resolution.

**Comment by josephdpurcell** [comment]
I believe following https://github.com/geerlingguy/drupal-vm/issues/1097#issuecomment-271213478 has solved the issue for me.
