### ISSUE TITLE
The box 'geerlingguy/ubuntu1604' could not be found or could not be accessed in the remote catalog

### ISSUE THREAD

**Issue by ashabed** [geerlingguy/drupal-vm#1098]
### Issue Type

 - Bug Report (solution provided)

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.12r112440
ansible not installed
```

### Your OS

 - **macOS** (Sierra)

### Full console output

`
vagrant up
Bringing machine 'academyvm170' up with 'virtualbox' provider...
==> academyvm170: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    academyvm170: Box Provider: virtualbox
    academyvm170: Box Version: >= 0
The box 'geerlingguy/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1604"]
Error: 
`
### Summary
Running `vagrant up` returned "The box geerlingguy/ubuntu1604 could not be found or could not be accessed in the remote catalog." 

**The solution was to run:** `sudo rm /opt/vagrant/embedded/bin/curl`

I'm posting this here so that others who face the same issue can find a solution more easily.

**Comment by geerlingguy** [comment]
@ashabed - Vagrant 1.8.7 had some _major_ issues, and not finding any boxes was one of them. Please either downgrade to 1.8.6 or upgrade to 1.9.0/1.9.1 to resolve this issue.

**Comment by geerlingguy** [comment]
And see:

  - https://github.com/geerlingguy/drupal-vm/issues/1021
  - https://github.com/geerlingguy/drupal-vm/issues/1010
  - https://github.com/geerlingguy/drupal-vm/issues/985
  - https://github.com/geerlingguy/drupal-vm/issues/981

This issue has been a scourge for the past couple months :(
