### ISSUE TITLE
drupal.org is now stable. Commence the celebrations.

### ISSUE THREAD

**Issue by RossGammon** [geerlingguy/drupal-vm#1099]
### Issue Type

Support Request

### Your Environment

```
Vagrant 1.8.1
VirtualBox 5.0.24_Ubuntur108355
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

- **Linux** (Ubuntu Xenial 16.04)

### Full console output

https://gist.github.com/RossGammon/5a4ae0f7c1caf1390e0a012eeb085dc5

### Summary

I am a bit new to Vagrant & Ansible, and I am trying to fire up a Drupal-VM in order to test the resurrection of an old Drupal site of mine from a backup.

Vagrant is the version that exists in Ubuntu Xenial, and Ansible is a backported version (from Ubuntu Yakkety).

Due to these version constraints, I have checked out a Drupal-VM git branch from the 3.2.3 release tag. I have not tweaked or moved any config files, just run $ vagrant up & $ vagrant provision a few times from the project root directory.

Any help and advice to get past this error would be appreciated. The whole console log is linked in the above gist, but just in case it is enough, I paste the failure output here:
TASK [Install dependencies with composer require.] *****************************
failed: [drupalvm] (item=drupal/devel:8.*) => {"changed": true, "cmd": ["/usr/bin/composer", "require", "drupal/devel:8.*"], "delta": "0:00:31.420087", "end": "2017-01-02 20:07:51.501755", "failed": true, "item": "drupal/devel:8.*", "rc": 2, "start": "2017-01-02 20:07:20.081668", "stderr": "Warning from https://packages.drupal.org/8: packages.drupal.org is now stable. Commence the celebrations.\n    1/1:\thttps://packages.drupal.org/8/drupal/provider-2017-1$eba9d2b078663d34df0418ea13e33df9f7b936555bc79dd851890695875a2c76.json\n    Finished: success: 1, skipped: 0, failure: 0, total: 1\n    1/5:\thttp://packagist.org/p/provider-latest$7b22386a3bbf36f162fb08550499b1318a40509c06bdaa92ef325ca9203d402e.json\n    2/5:\thttp://packagist.org/p/provider-2016$8ef59d7ba642a426bc8dbe2f37137885356f933ce6a4fddd2d9b0284179d70fc.json\n    3/5:\thttp://packagist.org/p/provider-2016-04$96fec705e5902d439ee4790446e20b7ee4e4d6a9f4142feea34d634470c88354.json\n    4/5:\thttp://packagist.org/p/provider-2016-07$dc67fbbfa064f7b1fbd37ec3651d011dee9fd41624e83c14463c6c1a4b7ed70c.json\n    5/5:\thttp://packagist.org/p/provider-2016-10$d5aab41871c4690d683807f95f7ec36bc55231e3320b4797ad87887e7cc412b1.json\n    Finished: success: 5, skipped: 0, failure: 0, total: 5\n./composer.json has been updated\nWarning from https://packages.drupal.org/8: packages.drupal.org is now stable. Commence the celebrations.\n    1/5:\thttp://packagist.org/p/provider-latest$7b22386a3bbf36f162fb08550499b1318a40509c06bdaa92ef325ca9203d402e.json\n    2/5:\thttp://packagist.org/p/provider-2016-04$96fec705e5902d439ee4790446e20b7ee4e4d6a9f4142feea34d634470c88354.json\n    3/5:\thttp://packagist.org/p/provider-2016$8ef59d7ba642a426bc8dbe2f37137885356f933ce6a4fddd2d9b0284179d70fc.json\n    4/5:\thttp://packagist.org/p/provider-2016-07$dc67fbbfa064f7b1fbd37ec3651d011dee9fd41624e83c14463c6c1a4b7ed70c.json\n    5/5:\thttp://packagist.org/p/provider-2016-10$d5aab41871c4690d683807f95f7ec36bc55231e3320b4797ad87887e7cc412b1.json\n    Finished: success: 5, skipped: 0, failure: 0, total: 5\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nWarning from https://packages.drupal.org/8: packages.drupal.org is now stable. Commence the celebrations.\nUpdating dependencies (including require-dev)\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - The requested package drupal/devel 8.* exists as drupal/devel[dev-1.x, 1.x-dev, 1.0.0-beta1, 1.0.0-alpha1] but these are rejected by your constraint.\n\n\nInstallation failed, reverting ./composer.json to its original content.", "stdout": "", "stdout_lines": [], "warnings": []}

Cheers,

Ross

**Comment by oxyc** [comment]
I think the commit you'll need is https://github.com/geerlingguy/drupal-vm/commit/81812990a5a4ca704c0f3012a6fcb988f07d8a95 (https://github.com/geerlingguy/drupal-vm/issues/913)

**Comment by geerlingguy** [comment]
Also, for the "drupal.org is now stable. Commence the celebrations." warning in particular... that's something the Drupal.org composer maintainers seem to have stuck in there to celebrate the stability of the drupal.org Composer packagist endpoint. Hopefully it goes away soon—most of my sites now show this warning for any composer-related commands I run!

**Comment by RossGammon** [comment]
Thanks very much for the fast response! That commit did the trick. Sorry my searching didn't pick that old issue up.
