### ISSUE TITLE
Failed to connect to the host via ssh.

### ISSUE THREAD

**Issue by jimmyko** [geerlingguy/drupal-vm#1100]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.6r110634
ansible 2.2.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **OSX** EI Capitan

### Full console output

https://gist.github.com/jimmyko/86818aa66406c1a18837606506a324cf

### Summary

Failed to connect to the host via ssh.

**Comment by jimmyko** [comment]
I have added `ansible.verbose = "vvvv"` in Vagrantfile to showing more error details.

**Comment by oxyc** [comment]
If you boot it through the VirtualBox GUI does it show any other clue?

**Comment by oxyc** [comment]
A successful SSH command on my system is:

> SSH: EXEC ssh -vvv -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/Users/cindy/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/cindy/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1483445339.51-15253943089592 `" && echo ansible-tmp-1483445339.51-15253943089592="` echo $HOME/.ansible/tmp/ansible-tmp-1483445339.51-15253943089592 `" ) && sleep 0'"'"''

The main difference is that I have `-o User=vagrant` while you have `-o 'User=b'"'"'vagrant'"'"''`

**Comment by oxyc** [comment]
I believe you're hitting https://github.com/ansible/ansible/issues/17832. Unfortunately this is still not in a release https://github.com/ansible/ansible/commit/64c446d9c0efd472298ac6a51a56d7869b17c404

**Comment by jimmyko** [comment]
@oxyc Thanks for your quick response! I have spotted that weird `-o 'User=b'"'"'vagrant'"'"''` and guess it would probably is the cause. Let me try to install python 2 and let you know.

**Comment by jimmyko** [comment]
@oxyc I have python2 on my machine. and set `ansible_python_interpreter` to `python2`. The output is same.
```
➜  drupal-vm git:(68feefa) ✗ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
```

**Comment by oxyc** [comment]
Hmm if the global `python` bin points to version 2, you shouldn't need the `ansible_python_interpreter` variable. Could you post the log output again now that you have python2?

Are you using python3 for something? Easiest might be to try and purge away v3, remove that `ansible_python_interpreter ` and then reinstall ansible. Before your log had this:

> Using module file /usr/local/lib/python3.5/site-packages/ansible/modules/core/system/setup.py

If you do need python3, I'll try and help debug it. Could you post the verbose output from running `vagrant provision`. I'm wondering if it's some other upstream bug, eg. https://github.com/ansible/ansible/issues/15635. If that's the case setting `ansible_python_interpreter` to the specific path might fix it. Eg. `ansible_python_interpreter: "/usr/local/bin/python2"`

**Comment by jimmyko** [comment]
@oxyc Since I am using python 2.7.10 in the very beginning and didn't change it. The output of `vagrant provision` is same as the gist I provided.
I tried `ansible_python_interpreter: "/usr/bin/python"` but it's still no luck.
```
➜  drupal-vm-test git:(68feefa) ✗ which python
/usr/bin/python
➜  drupal-vm-test git:(68feefa) ✗ python
Python 2.7.10 (default, Oct 23 2015, 19:19:21) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)] on darwin
```

**Comment by oxyc** [comment]
How did you install ansible?

> Using module file /usr/local/lib/python3.5/site-packages/ansible/modules/core/system/setup.py

From your original gist indicates you installed ansible using python 3.5

**Comment by jimmyko** [comment]
@oxyc You called back my memory... I did installed python 3.5 and used it to install ansible but the default python is still the python 2.

Should I indicate `ansible_python_interpreter` to python 3.5 or reinstall the ansible under 'python 2' ?

**Comment by oxyc** [comment]
I'd try re-installing under python2. As long as the log outputs `User=b'"'"'vagrant'"'"''` rather than `User=vagrant` that means it's being evaluated using python3. 

> A prefix of 'b' or 'B' is ignored in Python 2; it indicates that the literal should become a bytes literal in Python 3 (e.g. when code is automatically converted with 2to3). A 'u' or 'b' prefix may be followed by an 'r' prefix.

https://docs.python.org/2/reference/lexical_analysis.html#string-literals

**Comment by jimmyko** [comment]
@oxyc I didn't try to install ansible with python 2 but updated python to 3.6 and reinstall ansible. Everything working fine now. Thanks for your help!

**Comment by oxyc** [comment]
Great, glad you got it working! Python2 vs python3 has some pretty difficult to figure out bugs.
