### ISSUE TITLE
ruby_install_gem, gem installed but not working

### ISSUE THREAD

**Issue by fb-multimedia** [geerlingguy/drupal-vm#1102]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
vagrant 1.9.1
virtualbox 5.1.10
```

### Your OS

 - **Windows** (8)

### Summary
First, I want thank you Geerlingguy for this project ! I'm a beginner on linux vm and I was  before working with wamp for my drupal theming projects. It's really help me to introduce linux environment.

So I've a little issue with ruby_install_gems. When I add to my config.yml:
```
ruby_install_gems:
  - compass
  - sass
  - less
```
After vagrant up, gems are ok in the gem list with versions. But I can't use them, for exemple when I enter 'compass -v' the console say there is no program compass installed. same for a compass watch command.
as you can see below :
```
vagrant@drupalvmGEMBUG:~$ gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
bundler (1.13.7)
chunky_png (1.3.8)
commonjs (0.2.7)
compass (1.0.3)
compass-core (1.0.3)
compass-import-once (1.0.5)
did_you_mean (1.0.0)
ffi (1.9.14)
io-console (0.4.5)
json (1.8.3)
less (2.6.0)
minitest (5.8.4)
multi_json (1.12.1)
net-telnet (0.1.1)
power_assert (0.2.7)
psych (2.0.17)
rake (10.5.0)
rb-fsevent (0.9.8)
rb-inotify (0.9.7)
rdoc (4.2.1)
sass (3.4.23)
test-unit (3.1.7)
vagrant@drupalvmGEMBUG:~$ compass -v
The program 'compass' is currently not installed. You can install it by typing:
sudo apt install ruby-compass
```
Other gems seems to work, for exemple $ bundler -v return the version.

So to make my gems working after a vagrant up I have to install them in a .sh file (linked in config.yml) with :
```
yes | sudo apt install ruby-compass
yes | sudo apt install ruby-sass
```
Did I miss something to make it work simply with ruby_install_gem ?
Thanks in advance

**Comment by oxyc** [comment]
This is a bug https://github.com/geerlingguy/ansible-role-ruby/issues/33

**Comment by geerlingguy** [comment]
The fix is in `geerlingguy.ruby` 2.4.2.

**Comment by fb-multimedia** [comment]
Nice ! thank you
