### ISSUE TITLE
Need help with ssh configuration/ansible

### ISSUE THREAD

**Issue by rbreedlove** [geerlingguy/drupal-vm#1104]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.1
"VirtualBox vboxmanage --version'"
'ansible' is not recognized as an internal or external command,
operable program or batch file

### Your OS
 - **Windows** (version)

### Full console output
https://gist.github.com/anonymous/0d5c4d8b07ffde63d32c4e4d89ae8bde#file-gistfile1-txt

### Summary

I"m new to Drupal VM and trying to set it up on my PC. When running vagrant ssh, I get the attached [gist] above.  Ealier when doing vagrant up, I had received an ansible error, but I could not figure out how to install ansible.

Thanks ahead of time for you support on this...
Rel Breedlove

**Comment by oxyc** [comment]
I haven't used windows but I'm assuming you need either `Cmder` or `Cygwin` installed. http://docs.drupalvm.com/en/latest/other/windows/#command-line-environment

**Comment by oxyc** [comment]
Also https://www.youtube.com/watch?v=mNio_aXMLos

**Comment by rbreedlove** [comment]
Thanks for the quick response.

I will check those out.

--Rel

**Comment by oxyc** [comment]
@geerlingguy is the task to update the video? Otherwise I think the new windows docs make is a lot clearer.

http://docs.drupalvm.com/en/latest/getting-started/installation-windows/

**Comment by geerlingguy** [comment]
I think the docs cover this decently well now. I will remake my Windows video at some point, but even the existing 3.0 video covers setup pretty well. I also just posted a video on BLT + Drupal VM here: [Setup BLT and Drupal VM on Windows 10](https://www.youtube.com/watch?v=D60Ifoo0t08)

**Comment by geerlingguy** [comment]
I think I start every video with "In _this_ video..."

I should come up with something more exciting!
