### ISSUE TITLE
Ansible failed to complete successfully. reopening #1065

### ISSUE THREAD

**Issue by gettysburger** [geerlingguy/drupal-vm#1108]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.10.5)

### Full console output

https://gist.github.com/gettysburger/5293989dab70be8548db4365bf5386bc

### Summary

In issue #1065 I tried to spin up a fresh instance and got an Ansible error. You recommended that I upgrade Ansible and that worked for that instance. Today I tried to spin up another fresh instance and got the same error, even though I have the latest Ansible.

Thanks,
Stephen

**Comment by gettysburger** [comment]
I think I may have figured it out. I forgot to set "build_composer_project: false"

**Comment by gettysburger** [comment]
Yes, that was it. I'm a dope. Sorry to waste your time. Great software Thanks!

**Comment by geerlingguy** [comment]
Ha, no problem!
