### ISSUE TITLE
Add drupalvm_cron_jobs to documentation.

### ISSUE THREAD

**Issue by jimmyko** [geerlingguy/drupal-vm#1110]
### Issue Type

 - Documentation Report

### Summary

I am looking the way to set cron job and found it did not mention in documentation.

**Comment by oxyc** [comment]
For now the only documentation is in the [`default.config.yml`](https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L90:L95).

Probably a good idea adding to docs as well–so everything is in one place.

**Comment by jimmyko** [comment]
@oxyc You are right. It is no doubt that `default.config.yml` must have the latest documentation. But if it can be included in the documentation with more explanation, it definitely help those who is looking for this feature. :)

Anyway, I do think Drupalvm did a great job on documentation. Thanks mate.

**Comment by oxyc** [comment]
I think that's a good idea. Currently docs are a bit too spread out. I'll add it to the docs in https://github.com/geerlingguy/drupal-vm/issues/1092

**Comment by jimmyko** [comment]
Cool. If I have any other idea on documentation, I will raise there :)
