### ISSUE TITLE
Better Drush alias creation to support multiple environments for each site. 

### ISSUE THREAD

**Issue by jimmyko** [geerlingguy/drupal-vm#1111]
### Issue Type

 - Feature Idea

### Summary

Currently if I setup multiple sites under `apache_vhosts`, all drush alias will be created in single _aliases.drushrc.php_.

**Example**
```php
/**
 * @file
 * host_name.aliases.drushrc.php
 */
$aliases['site1.local'] = array(
  'uri' => 'site1.local',
  'root' => '/var/www/site',
);

$aliases['site2.local'] = array(
  'uri' => 'site2',
  'root' => '/var/www/site',
);

$aliases['site3.local'] = array(
  'uri' => 'site3',
  'root' => '/var/www/site',
);
```

It is good but I found a better way from [an article from Community Docs](https://www.drupal.org/node/1401522). It sounds more reasonable and be able to help developer to manage different environment.

If the alias files can be split into separate files and add extra options to configure the alias and environment name. It would be a great help.

**Example**
```php
/**
 * @file
 * site1.aliases.drushrc.php
 */
$aliases['local'] = array(
  'uri' => 'site1.local',
  'root' => '/var/www/site',
);
$aliases['prod'] = array (
  'parent' => '@site1.local',  
  'uri' => 'site1.local',
  'root' => '/var/www/site',
  'remote-user' => 'ssh-user',
  'remote-host' => 'ssh-host',
);
```
```php
/**
 * @file
 * site2.aliases.drushrc.php
 */
$aliases['local'] = array(
  'uri' => 'site2.local',
  'root' => '/var/www/site',
);
$aliases['prod'] = array (
  'parent' => '@site2.local',  
  'uri' => 'site2.local',
  'root' => '/var/www/site',
  'remote-user' => 'ssh-user',
  'remote-host' => 'ssh-host',
);
```

I am a newbie of ansible and not good at Python, otherwise, I would like to make a push request. If you don't have the time to make this improvement, I will try to study it when I am free :)

**Comment by oxyc** [comment]
Unfortunately it's not a good idea editing the drupal-vm edited alias files as they will always be overridden and reset on `vagrant provision`. I agree that the change you suggest is a nicer setup but it's only really useful when you can configure the remote hosts, which you cant as long as Drupal VM maintains the alias file.

Without the real environments configured I don't really see much gain from splitting vhosts into separate alias files. It mostly makes it more difficult to keep track of which file belongs to which VM.

A pretty common setup is to bundle the drush aliases within the repository and disable drupal-vm's. Drush [looks for alias files](https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php#L49:L51) in the current site as well.

[BLT](https://github.com/acquia/blt/tree/8.x/template/drush/site-aliases) places this `drush` directory in the root path next to `web/`.

**Comment by geerlingguy** [comment]
Agreed with @oxyc above—generally speaking, it's best to manage aliases per-project, since they can't be abstracted beyond that, and I don't want to try to turn Drupal VM into a full site management platform (e.g. something akin to BLT's `project.yml` file).
