### ISSUE TITLE
 Drush error when deploying DVM to prod w/DVM as a Composer dependency

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#1112]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (version)
 - **Linux** (version)

### Full console output
Refer to summary below for context.
```
DRUPALVM_ENV=prod ansible-playbook -i deploy/inventory vendor/geerlingguy/drupal-vm/provisioning/playbook.yml -e "config_dir=$(pwd)/config" --sudo --ask-sudo-pass
```
```
TASK [Install Drupal with drush.] **********************************************
fatal: [redacted]: FAILED! => {"changed": true, "cmd": ["/var/www/drupalvm/vendor/drush/drush/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=redacted", "--db-url=mysql://redacted:redacted@localhost/redacted"], "delta": "0:00:00.117899", "end": "2017-01-09 19:51:12.269741", "failed": true, "rc": 1, "start": "2017-01-09 19:51:12.151842", "stderr": "Command site-install needs a higher bootstrap level to run - you will\u001b[31;40m\u001b[1m[error]\u001b[0m\nneed to invoke drush from a more functional Drupal environment to run\nthis command.\nThe drush command 'site-install standard' could not be executed.     \u001b[31;40m\u001b[1m[error]\u001b[0m", "stdout": "", "stdout_lines": [], "warnings": []}
```
### Summary

I am working through the docs on deploying Drupal VM to a production environment with Drupal VM as a composer dependency. I have everything working as expected, up to a point. The local Vagrant instances spins out without any issues but I'm getting an error on the production side.

Local directories look like this:
```
config/config.yml (default)
config/local.config.yml #contains overrides for local Vagrant
config/prod.config.yml #contains overrides for remote server
config/Vagrantfile.local
```
prod.config.yml looks like this:
```
build_composer_project: false
build_composer: true
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
drupal_composer_dependencies: []
```
Ansible roles successfully build the LAMP stack and Composer builds Drupal at docroot as expected, i.e.:
```
TASK [Run composer install.] ***************************************************
changed: [x.x.x.x]
```
So far, so good....but I'm getting hung up here:
```
TASK [Install Drupal with drush.] **********************************************
```
which throws the error pasted above. I can't tell why it's attempting to execute a Drupal install w/Drush.

build_makefile is set to false. So I'm not sure if I missed another override somewhere or there's some other variable I'm missing. I'm pretty sure I had this working correctly over the weekend....{grumble}

**Comment by oxyc** [comment]
To skip the installation step you need to set `install_site: false` https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L70

**Comment by oxyc** [comment]
FYI `local.config.yml` is loaded for both production and vagrant.  There's `vagrant.config.yml` if you need it.

**Comment by minorscience** [comment]
Thanks for the tip @oxyc. I changed local.config.yml to vagrant.config.yml and everything now works as designed. As you described, the task runner was trying to load both local and prod. Still, I don't instructions for installing via drush in any of my configs.

```
build_composer_project: false
build_composer: true
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
drupal_composer_dependencies: []
```

On another note, I've seen some discussion on further developing DVM for production use cases. Is there a coordinated effort on that front? To move it from "experimental" to "supported"? DVM is truly an incredibly useful development tool and, speaking for myself, I'd like to see it also regarded as a useful _deployment_ tool. For frontend developers and designers, It's in a really nice sweet spot between cutting and pasting shell commands and full-blown devops deployment strategies. Speaking for myself, I'm not quite ready to go down the container rabbithole. Thanks again.

**Comment by geerlingguy** [comment]
> I'm not quite ready to go down the container rabbit hole.

Hehe, same here. At least not for production. Not _yet_.

> On another note, I've seen some discussion on further developing DVM for production use cases. Is there a coordinated effort on that front? To move it from "experimental" to "supported"?

It's mostly just my laziness. I don't have any automated testing set up on the prod side of things, so I can't guarantee changes won't break people's prod configurations. I think we could get around that by making a major caveat like _always run updates in --check mode before deploying to production_...

**Comment by oxyc** [comment]
> It's mostly just my laziness. I don't have any automated testing set up on the prod side of things

Travis tests this quite well no? Any additional features we should test? Saying that Drupal VM supports production use _is_ a bit scary though...

**Comment by geerlingguy** [comment]
> Saying that Drupal VM supports production use is a bit scary though...

Yeah, that's the gist of it—I'd want to have my own servers running through Drupal VM for more assurance that I won't break things :)

A few of my servers have something I call 'Drupal VM lite' (basically a fork with almost nothing besides LAMP and a firewall), but nothing is running Drupal VM proper at this time.

**Comment by geerlingguy** [comment]
I'd like a canary server, at least. Maybe I could toss my non-monetarily-important sites on a Drupal-VM-powered droplet?

**Comment by oxyc** [comment]
> A few of my servers have something I call 'Drupal VM lite' (basically a fork with almost nothing besides LAMP and a firewall), but nothing is running Drupal VM proper at this time.

We're currently running a basic intranet and a shared wildcard staging environment for 10+ small sites on Drupal VM–works great!

**Comment by geerlingguy** [comment]
@oxyc - One thing I would like to add to make things even spiffier for prod is certbot/LE integration. I use it for most of my sites now and have _mostly_ automated things, but my certbot role is still in need of a little extra TLC in terms of automating initial setup further.

Also, backup is another area that I have through a private role that I should really open source and make public (it backs up to another server over SSH, and grabs databases, files, etc. with configurable paths).

**Comment by oxyc** [comment]
> One thing I would like to add to make things even spiffier for prod is certbot/LE integration. I use it for most of my sites now and have mostly automated things, but my certbot role is still in need of a little extra TLC in terms of automating initial setup further.

Awesome, I was actually thinking about opening up an issue for this.

> Also, backup is another area that I have through a private role that I should really open source and make public (it backs up to another server over SSH, and grabs databases, files, etc. with configurable paths).

I'm pretty sure we would use this if you release it.

**Comment by minorscience** [comment]
I agree it is a pretty monumental shift in the declared intention of the project. (Think of it as bonus functionality!) I just can't think of another solution that works as well, short of writing my own fleet of ansible projects. 

I guess my own use case is pretty constrained: small-ish 2-tier applications hosted on AWS (public facing www, db on a private subnet). I launch the EC2 instances with Terraform and let DVM do the rest. This works well for independent freelancer and small agency work, as most client requirements are satisfied by this approach. 

I plan on documenting my approach and providing it to our community of users. It's a good exercise for me and would be useful to gauge interest. 

If you're interested in taking input on _incrementally_ adding support for additional features in production, I think ngnix and (very definitely) backups would be appreciated.

**Comment by minorscience** [comment]
Do we want to change the title of this issue to something relevant in case others want to chime in?

**Comment by geerlingguy** [comment]
@minorscience - How about we start a new issue, as this one has served its course :)

**Comment by minorscience** [comment]
:thumbsup:

**Comment by minorscience** [comment]
Just wanted to tack one quick question on to this thread. It looks like ansible isn't loading my local composer.json into the production environment.

```
TASK [Copy drush makefile into place.] *****************************************
skipping: [34.192.145.93]

TASK [Ensure drupal_core_path directory exists.] *******************************
skipping: [34.192.145.93]

TASK [Generate Drupal site with drush makefile.] *******************************
skipping: [34.192.145.93]

TASK [Check if a composer.json file is present.] *******************************
skipping: [34.192.145.93]

TASK [Run composer install if composer.json is present.] ***********************
skipping: [34.192.145.93]

TASK [Ensure drupal_composer_install_dir directory exists.] ********************
skipping: [34.192.145.93]

TASK [Copy composer.json into temporary location.] *****************************
skipping: [34.192.145.93]

TASK [Move composer.json into place.] ******************************************
skipping: [34.192.145.93]

TASK [Run composer install.] ***************************************************
fatal: [34.192.145.93]: FAILED! => {"changed": true, "cmd": ["composer", "install"], "delta": "0:00:00.082901", "end": "2017-01-15 21:18:16.406508", "failed": true, "rc": 1, "start": "2017-01-15 21:18:16.323607", "stderr": "Composer could not find a composer.json file in /var/www/drupalvm\nTo initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section", "stdout": "", "stdout_lines": [], "warnings": []}
```
If I manually copy my composer.json file to /var/www/drupalvm and retry the playbook, all is well.

Looking at build-composer.yml task, it looks pretty straightforward, copying composer.json into /tmp, then moving it to the configured Drupal install directory.

Am I missing something?

**Comment by oxyc** [comment]
Earlier you mentioned that you had:

```yaml
drupal_composer_path: false
```

By doing this you're telling Drupal VM not to move a composer.json file into place. Combining this setting with:

```yaml
build_composer: true
```

Requires you to have a `composer.json` already in place (the `drupal_composer_install_dir` directory).

> The file set in drupal_composer_path (which defaults to drupal.composer.json) will be copied from your host computer into the VM's drupal_composer_install_dir and renamed composer.json. If you already have a composer.json within that directory, set drupal_composer_path: false.

http://docs.drupalvm.com/en/latest/deployment/composer/#using-composerjson

**Comment by minorscience** [comment]
Right. My settings correspond to those stipulated here: http://docs.drupalvm.com/en/latest/deployment/composer/#using-composer-when-drupal-vm-is-a-composer-dependency-itself

and also referenced here:
http://docs.drupalvm.com/en/latest/other/production/#provision-drupal-vm-on-the-droplet

```
build_composer_project: false
build_composer: true
drupal_composer_path: false
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
```
So what's missing is a mechanism to upload the local composer.json to the remote host directory specified at drupal_composer_install_dir, correct?

**Comment by oxyc** [comment]
Ah, yes you need to set the `drupal_composer_path` as there's no NFS/rsync to upload it to a remote environment otherwise.

Do you have your `config.yml` in the same directory as you` composer.json`, or did you set a config subdirectory with [`DRUPALVM_CONFIG_DIR`](http://docs.drupalvm.com/en/latest/other/drupalvm-composer-dependency/#create-a-delegating-vagrantfile)?

If your `composer.json` file is in the same directory as your `config.yml` use:

```yaml
drupal_composer_path: "{{ config_dir }}/composer.json"
```

If the configurations are in a subdirectory as shown in the [example here](http://docs.drupalvm.com/en/latest/other/drupalvm-composer-dependency/#create-a-delegating-vagrantfile), use:

```yaml
drupal_composer_path: "{{ config_dir }}/../composer.json"
```

**Comment by oxyc** [comment]
@minorscience any updates on this?

**Comment by oxyc** [comment]
I'll close this as I assume you got it working. If not, please re-open and we can discuss it further.
