### ISSUE TITLE
How to install Soap PHP Extension?

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#1117]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides

```

### Your OS

 - **macOS** (version)

### Summary

Trying to figure out the best way to install the the php soap extension. Can I just add the following to my config.yml?

```
extra_packages:
  - php56-soap
```

**Comment by justinlevi** [comment]
Answered my own question... Yes you can do that but I had the syntax wrong. 

```
extra_packages:
  - php5.6-soap
```

**Comment by oxyc** [comment]
In the master branch (still not released) you can also use [`php_packages_extra`](https://github.com/geerlingguy/drupal-vm/commit/bc59c072f1d3c9338b202c2f8b5b21cdf1a68c26).

```yaml
php_packages_extra:
  - "php{{ php_version }}-soap"
```

@geerlingguy to get version switching version working for packages defined in this variable, I think we need to add it to the debian purge task.

**Comment by subson** [comment]
I am trying to install php73-php-soap in DrupalVM for centos7, it says it installed the extension but its not available in phpinfo. any help please?

**Comment by joel-travieso** [comment]
Yeah I have `php73-php-soap` under `php_packages_extra` and can see it among installed packages after `vagrant destroy && vagrant up` but `php -m | grep -i soap` returns empty.

**Comment by joel-travieso** [comment]
I circumvented this issue by creating symlinks to the necessary soap files that exist under the remi repo: 
```
sudo ln -s /etc/opt/remi/php73/php.d/20-soap.ini /etc/php.d/20-soap.ini
sudo ln -s /opt/remi/php73/root/usr/lib64/php/modules/soap.so /usr/lib64/php/modules/soap.so
```

**Comment by gareth-cohaesus** [comment]
```
php_packages_extra:
  - php7.3-soap

```
worked for me
```
php -i | grep Soap
```
returned
```
Soap Client => enabled
Soap Server => enabled
```
