### ISSUE TITLE
Solr schema.xml?

### ISSUE THREAD

**Issue by wmostrey** [geerlingguy/drupal-vm#1118]
### Issue Type
 - Support Request

### Your Environment
```
 - Vagrant 1.9.1
 - VirtualBox 5.1.12r112440
 - -bash: ansible: command not found
```

### Your OS
 - **macOS** (10.12.2)

### Summary
I read the Solr documentation and Solr is up and running. I can't seem to figure out however where to find/put the schema.xml.

**Comment by geerlingguy** [comment]
@wmostrey - Please see the example solr setup script in the example scripts directory: https://github.com/geerlingguy/drupal-vm/tree/master/examples/scripts

It automatically downloads the latest Drupal 8.x Search API Solr configuration and puts it in the right place for the default Solr version.

If you use a different Solr version, or use a different module for Solr in Drupal, you would either need to modify that setup file to your liking, or do something else to place the configuration files in the right core directory, then restart Solr.
