### ISSUE TITLE
add a toggle for xdebug

### ISSUE THREAD

**Issue by YesCT** [geerlingguy/drupal-vm#112]
when using xhprof, we should not have xdebug enabled.

add a toggle for xdebug

could be /usr/local/bin/xdebug-toggle

```php
#!/bin/sh -i
XFIND="zend_extension"
case "$1" in
        on)
            XREPLACE="$XFIND"
            XFIND=";$XFIND"
            ;;

        off)
            XREPLACE=";$XFIND"
            ;;

        *)
            echo $"Usage: $0 {on|off}"
            exit 1

esac

sudo sed -i -e "s/^$XFIND/$XREPLACE/" /etc/php5/apache2/conf.d/xdebug.ini
if [ ! $2 ]; then
  sudo apachectl restart
  php -v
fi
```

based on https://gist.github.com/alexpott/2c0f6cb74a420a4c60f4 from @alexpott

**Comment by geerlingguy** [comment]
This toggle would be a quick on/off switch, though you can already disable xdebug using some built in vars from the `geerlingguy.xdebug` role: https://github.com/geerlingguy/ansible-role-php-xdebug#role-variables

First, add the following lines in `config.yml`:

```
php_xdebug_default_enable: 0
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 0
```

Then, run `vagrant provision` and xdebug will be disabled after the run is complete.

This takes a minute or two to run, so maybe that's a little bit of a turn-off. @YesCT - would you still prefer something more quick-n-dirty like the above script? I'm not opposed to sticking some scripts in a `scripts` directory and symlinking them inside the VM so you can use them to do things like toggle settings or run specific commands/tests...

**Comment by geerlingguy** [comment]
I think the solution above should work for most people easily enough. It's not as blinding-fast as a script that toggles xdebug internally, but it's how I do it in my workflow (I generally leave xdebug disabled unless I explicitly need it).

**Comment by oxyc** [comment]
This is now better supported and you can read more in the docs http://docs.drupalvm.com/en/latest/extras/xdebug/#xdebug-over-sshdrush (available in the next release).
