### ISSUE TITLE
Mailhog / postfix: MX addresses  not resolved in VM

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#1121]
### Issue Type

 - Bug Report / Support Request

### My Environment

```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

And the latest version of the provisioning scripts: 

```
e9a8855 Update to latest Elasticsearch role version.
085e7e7 Update Firewall role to latest version.
...
```

### My OS

 - **macOS** (version)

### Summary

When using mailhog with postfix; sending mail fails as postfix cannot resolve MX  addresses which are seemingly accessible from other programs running in the VM. However DNS "A" records are found OK.

The same `nslookup` in the VM's host finds the MX addresses OK.

Is there something in the vagrant config that is preventing this?

### Full console output

```
vagrant@drupal8vm:~$ nslookup       
> set q=mx
> me.com
Server:		10.0.2.3
Address:	10.0.2.3#53

** server can't find me.com: NOTIMP
> set q=a 
> me.com
Server:		10.0.2.3
Address:	10.0.2.3#53

Non-authoritative answer:
Name:	me.com
Address: 17.172.224.103
Name:	me.com
Address: 17.142.160.83
Name:	me.com
Address: 17.178.96.97

vagrant@drupal8vm:~$ sudo tail  /var/log/mail.log
Jan 13 09:23:12 drupal8vm postfix[1804]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Jan 13 09:23:12 drupal8vm postfix/master[1173]: terminating on signal 15
Jan 13 09:23:12 drupal8vm postfix[1896]: Postfix is running with backwards-compatible default settings
Jan 13 09:23:12 drupal8vm postfix[1896]: See http://www.postfix.org/COMPATIBILITY_README.html for details
Jan 13 09:23:12 drupal8vm postfix[1896]: To disable backwards compatibility use "postconf compatibility_level=2" and "postfix reload"
Jan 13 09:23:13 drupal8vm postfix/master[1933]: daemon started -- version 3.1.0, configuration /etc/postfix
Jan 13 09:25:25 drupal8vm postfix/pickup[1934]: 48BE1382B3C: uid=900 from=<vagrant>
Jan 13 09:25:25 drupal8vm postfix/cleanup[1981]: 48BE1382B3C: message-id=<20170113092525.48BE1382B3C@drupal8vm.dev>
Jan 13 09:25:25 drupal8vm postfix/qmgr[1935]: 48BE1382B3C: from=<vagrant@drupal8vm.dev>, size=274, nrcpt=1 (queue active)
Jan 13 09:25:25 drupal8vm postfix/smtp[1983]: 48BE1382B3C: to=<iainhouston@me.com>, relay=none, delay=11, delays=11/0.02/0/0, dsn=4.4.3, status=deferred (Host or domain name not found. Name service error for name=me.com type=MX: Host not found, try again)
```

**Comment by geerlingguy** [comment]
@iainhouston - This looks strange; I haven't noticed the issue with my @mac.com email address lately (though I haven't tried me.com). I'll try to do some testing if I get a chance.

Was this with a stock install of Drupal VM, or any other customizations? And was it an email routed through Drupal or something else?

**Comment by iainhouston** [comment]
No, its weird that `nslookup` can resolve "A" records for `me.com` but not "MX` records .... yes, it's a pretty straightforward drupal-vm although originally provisioned a few months back; pulled latest; edited `config.yml` per any diffs with `default.config.yml`.

I'll destroy the VM and re-provision to see if this has any effect.

**Comment by iainhouston** [comment]
Hmmm .... weirdness persists with `mac.com` after freshly created and provisioned VM:
```
vagrant@drupal8vm:~$ nslookup
> set type=a 
> mac.com
Server:		10.0.2.3
Address:	10.0.2.3#53

Non-authoritative answer:
Name:	mac.com
Address: 17.146.233.11
> set type=mx
> mac.com
Server:		10.0.2.3
Address:	10.0.2.3#53

** server can't find mac.com: NOTIMP
```

**Comment by iainhouston** [comment]
Perhaps I am just using DIG and nslookup incorrectly. Mail *is* now being sent to mail hop OK now after re-provision. Anyway .... spent enough time banging head on wall.

**Comment by iainhouston** [comment]
Closed

**Comment by geerlingguy** [comment]
Sometimes... eesh, I guess there was just a ghost lurking somewhere!
