### ISSUE TITLE
Error : Preparing to edit /etc/exports. Administrator privileges will be required...

### ISSUE THREAD

**Issue by ytokan** [geerlingguy/drupal-vm#1125]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.1
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides

### Your OS

macOS sierra

### Full console output

```
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
userdev is not in the sudoers file.  This incident will be reported.
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: 3 incorrect password attempts
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o vers=3,udp 192.168.88.1:/Users/userdev/Public/drupal-vm /var/www/drupalvm
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/var/www/drupalvm
fi
else
exit $result
fi
Stdout from the command:
Stderr from the command:
mesg: ttyname failed: Inappropriate ioctl for device
mount.nfs: Connection timed out
```

### Summary

Hy my problem is that my user account **userdev** dont have root privilege, how switch to a root user account ? 

Or what the settings to write in /etc/exports 

Thanks

**Comment by oxyc** [comment]
You need to enter the password of the user on your host computer

**Comment by ytokan** [comment]
Password:
**userdev** is not in the sudoers file.  This incident will be reported.

I'm not sudo user to execute 
Preparing to edit /etc/exports. Administrator privileges will be required...

**Comment by geerlingguy** [comment]
@ytokan - In that case, you'll either have to use an account with admin privileges, or not use `nfs` for the synced folders (it requires sudo access to work). You could instead set the type to `''`, or `rsync`, or one of the other supported methods.

**Comment by oxyc** [comment]
In addition to the changing the type of the folders in `vagrant_synced_folders`, you would also need to change `vagrant_synced_folder_default_type` (it's used for syncing Drupal VM to `/vagrant` on the guest).

**Comment by geerlingguy** [comment]
True!

**Comment by ytokan** [comment]
Thank's for all your comments
i create a config.yml file to override default **nsf** settings

**Comment by geerlingguy** [comment]
@ytokan - Great! I'll close this issue for now, then. Thanks for the patience.

**Comment by attheshow** [comment]
Just in case anyone else stumbles on this issue using NFS, I was able to get it working on my Mac without the password by following the recommended solution here:

https://askubuntu.com/questions/412525/vagrant-up-and-annoying-nfs-password-asking
