### ISSUE TITLE
Add docs on how to build your own pre-provisioned base box

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1126]
### Issue Type

 - Documentation Report

### Summary

My laptop just ran out of space (`71 GiB	~/VirtualBox VMs`) so I thought it might be a good idea to build a pre-provisioned box and leverage linked clones. As Drupal VM is so awesome for teams, might this be something worth adding to the docs?

I've never used packer or looked into building boxes, but it looks easy enough and quite useful. I know other co-workers have complained about the VM disk usage..

**Comment by geerlingguy** [comment]
"But 512 K is enough for everybody, right?" /s

In all seriousness, though... basically something like "how to build and host your own derivative box" would be a decent addition. Or if not that, at least a blog post, akin to one I did a while back about Packer + Ansible: [Building VM images with Ansible and Packer](http://www.jeffgeerling.com/blog/server-vm-images-ansible-and-packer).

Or more specifically, how to optimize a project for your team even _further_ than something like [Beetbox](https://github.com/beetboxvm/beetbox).

**Comment by oxyc** [comment]
Thanks for the link! Currently I'm just testing it out by building our boilerplate project together with a post-provision task that runs:

```sh
#!/bin/bash

rm -f /home/vagrant/.ssh/known_hosts
apt-get clean
dd if=/dev/zero of=/EMPTY bs=1M
rm -f /EMPTY
cat /dev/null > ~/.bash_history
```

And then I was planning to run:

```sh
vagrant package --output mybox.box
```

**Comment by oxyc** [comment]
The simple solution works great. To make it maintainable I guess I do need packer though.

**Comment by oxyc** [comment]
For packer I guess the easiest is to fork on your box repositories and configuring it to run Drupal VM's playbook with the instructions from _Deploying Drupal VM to a production environment_.

@geerlingguy feel free to close this if you think it's better suited as a blog post or in general too far from the common use case.

**Comment by geerlingguy** [comment]
Not necessarily... it might still be suited for a blog post, but we can explore the topic in this issue a bit more before closing it out.

For months, I've been wanting to do basically what you've suggested:

> fork one of your box repositories and configuring it to run Drupal VM's playbook with the instructions from Deploying Drupal VM to a production environment

But make it into a digestible and as-simple-as-possible process so it's really easy for people to do it on their own.

It would also alleviate some of my bandwidth, for which I'm now up to about $25/month just to host my boxes 😳

**Comment by thom8** [comment]
@oxyc take a look @ the minimize script in the boxcutter project - https://github.com/boxcutter/ubuntu/blob/master/script/minimize.sh 

This massively reduced the size of the beetbox base image -- https://atlas.hashicorp.com/beet/boxes/box (was > 800MB)

@geerlingguy maybe this could be added to your build?

**Comment by thom8** [comment]
Also just to explain where beetbox heading RE: "preprovisioned profiles" which could provide a bunch of preprovisioned base boxes eg. PHP7, Acquia, Platform.sh etc.

We've added the concept of a [profile](https://github.com/beetboxvm/beetbox/tree/master/provisioning/ansible/config/profiles) which extends the default config so maintenance is reduced.

This is set by `BEET_PROFILE /beet_profile` so our docker container uses the [docker profile](https://github.com/beetboxvm/beetbox/blob/master/Dockerfile#L5).
The idea going forward is to include more profiles and add more [boxes](https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/config/default.config.yml#L298), but first I'd like to get a full replica docker build which will help for CI and eventually plan to make it a docker first project which also works with Vagrant so each base box would also have a corresponding container.

Maybe even a [Centos / RHEL](https://github.com/beetboxvm/beetbox/issues/354) box/container...

It's not much overhead to manage as each box is automatically built on a new tag & thanks to Hashicorp we've been sponsored a Vagrant Enterprise account.

**Comment by oxyc** [comment]
@thom8 nice thanks for the links!

> We've added the concept of a profile which extends the default config so maintenance is reduced.

Drupal VM's `DRUPALVM_ENV` variable could be used in a similar matter. We'd just need to set it to docker and include a `docker.config.yml` file.

**Comment by geerlingguy** [comment]
@thom8 - The Ansible packer roles for Debian/RHEL do clean up all the packages they installed for configuration (or at least they _should_), and the minimal base box images are already as close to barebones as I can get them. I think I gave up doing things like removing all man pages and such, just because my base boxes are meant to emulate the actual minimal OS installs, and they still include things like man pages.

**Comment by oxyc** [comment]
A bit related. But you can now use `beet/box` for faster provisions. It's essentially a pre-provisioned Drupal VM box. https://github.com/acquia/blt/issues/1986

**Comment by thom8** [comment]
@oxyc this has actually always worked, the difference described in that issue is that all of BLT's [default config](https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/config.yml) is now part of the preprovisioning.

Even, before the changes it still worked as it would just provision anything that wasn't already included.

**Comment by oxyc** [comment]
I just didn't think of doing that before you mentioned it in the issue queue. Once linked clones are working again I'll give it a try and see how it compares.

**Comment by thom8** [comment]
All good, the reverse is also true `beetbox` using `geerlingguy/ubuntu1604` as the base box.

```
vagrant_box: geerlingguy/ubuntu1604
vagrant_box_version: "~> 1.1.0"
```

even the default ubuntu `xenial64` should work >>

```
vagrant_box: ubuntu/xenial64
vagrant_box_version: ">= 0"
```

**Comment by oxyc** [comment]
One annoyance with `beet/box` on Drupal VM with `vagrant-vbguest` is that the pre-installed VirtualBox Guest Additions are older than the ones I have on the host. With @geerlingguy boxes the box almost always have a newer version than I do. Thus when I update the box, the guest additions iso is updated on my host and then used on all new VMs until I run `vagrant box update` again.

With `beet/box` the `vagrant up` takes quite some time because it needs to update the box guest additions rather than the iso on the host.

For reference `beet/box v0.7.4 (latest)` has guest additions v5.0.40 while `geerlingguy/ubuntu1604 v1.1.4 (not latest)` has Guest Additions v5.1.22

**Comment by oxyc** [comment]
@thom8 is that a bug or?

**Comment by thom8** [comment]
@oxyc it's just using the default version on [atlas](https://atlas.hashicorp.com) -- https://github.com/beetboxvm/beetbox/blob/master/provisioning/ubuntu-16.04.json#L56

I don't use `vagrant-vbguest` so don't run into this issue and haven't had any issues with the old versions.

Looks like packer now supports `guest_additions_url` -- https://www.packer.io/docs/builders/virtualbox-iso.html#guest_additions_url but would have to manually keep this updated..

**Comment by oxyc** [comment]
Alright, it's a bit annoying with the plugin installed. Checked some more and it's just tied to the installed version of VirtualBox.

Guess it's just worked well for me with `geerlingguy/ubuntu1604` because anytime I update VirtualBox I'm usually on an update mission bumping all the things and `geerlingguy/ubuntu1604` almost always have the latest version.

**Comment by thom8** [comment]
happy to add the latest version to the Atlas build -- https://github.com/beetboxvm/beetbox/pull/446

**Comment by thom8** [comment]
@oxyc looks like it's working with `vagrant-vbguest` on the latest release `beet/dev`, will be rolled into the next release `0.8.0` later in the week.

```
==> beetbox: Machine booted and ready!
[beetbox] GuestAdditions 5.1.28 running --- OK.
==> beetbox: Checking for guest additions in VM...
```

**Comment by thom8** [comment]
@oxyc pushed `0.8.0` yesterday, mainly a clean up release and everything looks good.

Also publishing link to build --> https://github.com/beetboxvm/beetbox/releases/tag/0.8.0

Which should help with any debugging, wish I could make the Atlas build public... but happy to give you access if you're interested

**Comment by geerlingguy** [comment]
Also related:

* https://github.com/geerlingguy/drupal-vm/issues/1774 (see, specifically, the Packer build for Drupal VM here: https://github.com/geerlingguy/packer-drupal-vm
* https://github.com/geerlingguy/drupal-vm/issues/1844

**Comment by geerlingguy** [comment]
I'm going to close this issue and move further work into #1774 — basically to document how the Drupal VM base box is built, and how you can customize that further.
