### ISSUE TITLE
Unable to restart service apache2: Job for apache2.service

### ISSUE THREAD

**Issue by iefrati** [geerlingguy/drupal-vm#1127]
### Issue Type
 Bug Report / Support Request
### Your Environment
Vagrant 1.9.1
VirtualBox
vboxmanage --version
5.1.8r111374

### Your OS
 **macOS** (10.11.6)

### Full console output
When running vagrant up /vagrant provision I am getting

```
RUNNING HANDLER [geerlingguy.apache : restart apache] **************************
fatal: [dev-vm]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to restart service apache2: Job for apache2.service failed because the control process exited with error code. See \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\n"}

```
### Summary
When I ran vagrant up, it asked me to run vagrant box update,
after the update I am getting the above error 
when running systemctl status apache2.service
I am getting 
```
* apache2.service - LSB: Apache2 web server
   Loaded: loaded (/etc/init.d/apache2; bad; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           `-apache2-systemd.conf
   Active: failed (Result: exit-code) since Tue 2017-01-17 15:24:25 UTC; 6min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 4164 ExecStop=/etc/init.d/apache2 stop (code=exited, status=0/SUCCESS)
  Process: 4190 ExecStart=/etc/init.d/apache2 start (code=exited, status=1/FAILURE)

```

**Comment by iefrati** [comment]
```
sudo journalctl | tail
Jan 17 15:32:49 apache2[4363]: Action 'configtest' failed.
Jan 17 15:32:49 apache2[4363]: The Apache error log may have more information.
Jan 17 15:32:49 systemd[1]: apache2.service: Control process exited, code=exited status=1
Jan 17 15:32:49 systemd[1]: Failed to start LSB: Apache2 web server.
Jan 17 15:32:49 systemd[1]: apache2.service: Unit entered failed state.
Jan 17 15:32:49 systemd[1]: apache2.service: Failed with result 'exit-code'.
Jan 17 15:32:49 sudo[4336]: pam_unix(sudo:session): session closed for user root
Jan 17 15:33:12 mailhog[2812]: [APIv1] KEEPALIVE /api/v1/events
Jan 17 15:34:05 sudo[4381]:  vagrant : TTY=pts/0 ; PWD=/home/vagrant ; USER=root ; COMMAND=/bin/journalctl
Jan 17 15:34:05 sudo[4381]: pam_unix(sudo:session): session opened for user root by vagrant(uid=0)
```

**Comment by johnreytanquinco** [comment]
Hello @iefrati . I am actually getting the same error as yours now. How are you able to overcome this. But I am only running the command in my local machine, with the latest installed version of Ubuntu 17.04. Appreciate your response. Thanks!

**Comment by ErdemStar** [comment]
is there somebody to solve this problem.I faced same problem.What can i do or i think i remove then again install may it run ?

**Comment by oxyc** [comment]
What's the result from running:

```
sudo journalctl | tail
```

**Comment by ErdemStar** [comment]
i want to start apache2 but it give me error , i shared error flowing.
This is my OS
http://imguploads.net/image/5FBD1
When i write in my terminal -> service apache2 start.it give me this error
http://imguploads.net/image/5FlRi
then i tried to fix it
http://imguploads.net/image/5Fujg
http://imguploads.net/image/5F7XD

http://imguploads.net/image/5F04A

**Comment by oxyc** [comment]
There's a syntax error somewhere in the Apache config, please post your `config.yml`.

**Comment by minjurul** [comment]
sudo apt-get install apache2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package apache2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'apache2' has no installation candidate
sudo apt-get install apache2
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package apache2 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'apache2' has no installation candidate
