### ISSUE TITLE
installing ansible fail

### ISSUE THREAD

**Issue by kyliepace** [geerlingguy/drupal-vm#1130]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
vagrant 1.9.1
VirtualBox - 5.1.12
ansible: command not found
```

### Your OS
- **Windows** 8.1

### Full console output

[gist](https://gist.github.com/kyliepace/a3682429cf0523983cd180461b069c28)

### Summary
Am trying to install Drupal 7. Upon running vagrant up, ansible fails to install.

> The following SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed! add-apt-respository ppa:ansible/ansible -y  Stdout from the command: mesg: ttyname failed: Inappropriate ioctl for device

**Comment by geerlingguy** [comment]
@kyliepace - Do you happen to be behind a proxy? See: http://askubuntu.com/questions/738727/installing-ansible-on-ubuntu

**Comment by geerlingguy** [comment]
See also: http://docs.drupalvm.com/en/latest/other/overriding-configurations/#example-using-drupal-vm-behind-a-corporate-proxy-with-vagrant-proxyconf

**Comment by kyliepace** [comment]
ahhah! Thanks that was it!

**Comment by geerlingguy** [comment]
@kyliepace - Great! Glad I could help.
