### ISSUE TITLE
Could not find the requested service \"'solr'\"

### ISSUE THREAD

**Issue by twerthmueller** [geerlingguy/drupal-vm#1131]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.6
VirtualBox 5.1.12 r112440
ansible 2.2.0.0
DrupalVM 4.1.1 
```

### Your OS
 - **macOS** (Sierra 10.12.2)

### Full console output

https://gist.github.com/twerthmueller/b5a746f9fcb46e16e7bcfb5ba844334a

### Summary
When I provision a complete new VM with Solr, I get the following error:

fatal: [wa]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'solr'\": "}

My Solf configuration:

```
# Solr Configuration (if enabled above).
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"
solr_port: "8081"
```
Mybe this is related to other issues with "Could not find the requested service", but I could not find a solution for the problem.

Thanks for your help,
Thomas

**Comment by twerthmueller** [comment]
Ok, this problem seems only to happen when I set the solr version to 4.10.4. When I use the version 5.x then provision works as expected.

**Comment by geerlingguy** [comment]
This was just fixed upstream in https://github.com/geerlingguy/ansible-role-solr/pull/55 — I'm going to pull that fixed version into Drupal VM `master` now, hopefully for a new tagged release this week or next.

**Comment by twerthmueller** [comment]
Thank you for the always quick response!

**Comment by geerlingguy** [comment]
We aim to please! Plus, I'm using Solr 4.10 on a couple of my own projects still, and this unblocks upgrading those servers to 16.04 (a couple of my older servers are still on 12.04!)

**Comment by twerthmueller** [comment]
Good to know then I was try 16.04 and there was no error on provisioning but the Solr instance was not accessible. I switched to 14.04 and it works. Thank you for the hint!
