### ISSUE TITLE
Improve the Solr script in example folder.

### ISSUE THREAD

**Issue by jimmyko** [geerlingguy/drupal-vm#1133]
### Issue Type

 - Feature Idea

### Summary

In example folder, the solr script is the recommended way to configure solr in documentation. But this script only replace the conf folder of the default collection. My idea is that this script should create a new collection.

If someone wants to create multiple solr collection, it can be a starting point to customize in their environment.

**Comment by oxyc** [comment]
This was merged in the above PR, thanks for your work @jimmyko!

**Comment by geerlingguy** [comment]
Ah... keeping issue count below 25 :)
