### ISSUE TITLE
Use geerlingguy.firewall role's UFW/Firewalld disabling capability

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1138]
Since Drupal VM uses `geerlingguy.firewall` to configure an `iptables`-based firewall, UFW (Ubuntu's default) and Firewalld (RHEL/CentOS 7's default) are redundant and can cause issues.

We currently manually disable `ufw` in the Debian pre-tasks. And we don't disable Firewalld at all.

The Firewall role now has the ability to manage both, so we should use that instead of our own tasks: https://github.com/geerlingguy/ansible-role-firewall/issues/30

**Comment by derekderaps** [comment]
FYI the `firewall_disable_firewalld` setting seems incompatible with the `geerlingguy/centos6` box. Changing its value to `false` fixed provisioning.

**Comment by geerlingguy** [comment]
@derekderaps - There are a few defaults that, unfortunately, don't play nice with CentOS 6. We might want to add something to the docs page about this and other changes required to make CentOS work correctly 'out of the box': http://docs.drupalvm.com/en/latest/configurations/base-os/#redhat-enterprise-linux-centos-6

@derekderaps - Can you open a docs issue for that separately?

**Comment by derekderaps** [comment]
Sure thing - done in #1188.
