### ISSUE TITLE
I can't provision, I get an error in "TASK: [Configure host machine drush aliases.]"

### ISSUE THREAD

**Issue by jclopez** [geerlingguy/drupal-vm#114]
When I run provision i got this error:
Ansible version: 1.8.2
Vagrant version: 1.7.2
Mac OSX: 10.10.3

    TASK: [Configure host machine drush aliases.] ********************************* 
    failed: [drupaldev -> 127.0.0.1] => {"failed": true}
    msg: Destination directory /Users/username/.drush does not exist

    FATAL: all hosts have already failed -- aborting

    PLAY RECAP ******************************************************************** 
               to retry, use: --limit @/Users/username/playbook.retry

    drupaldev                  : ok=155  changed=9    unreachable=0    failed=1   

    Ansible failed to complete successfully. Any error output should be
    visible above. Please fix these errors and try again.

Does anyone have an idea what could be wrong?

**Comment by geerlingguy** [comment]
@jclopez - It seems your `~` alias might not be configured correctly. What is the output of the command `echo ~` (if you enter it in your Terminal)?

It should point to, in your case, `/Users/jclopez` or something like that. Maybe something you have running that's taking over your `.profile` or `.bash_profile` is messing with the `~` path?

**Comment by jclopez** [comment]
problably is that Im running fish 


     ~/Projects/drupal · (master±)
      ⟩ echo ~ 
      /Users/jclopez

**Comment by jclopez** [comment]
Same error runing Vagrant provision without fish

**Comment by jclopez** [comment]
should I have to install drush on the host?

**Comment by geerlingguy** [comment]
Ah... I just realized the task prior to the one that was failing wasn't configured correctly. The above commit should _hopefully_ fix this—can you update your clone to the latest revision and run `vagrant provision` again to see if it gets past that command?

**Comment by geerlingguy** [comment]
And no, you don't need to have Drush installed on the host (though that's usually more convenient than having to remain logged into the guest to run drush commands, in my experience).

**Comment by jclopez** [comment]
It worked like a champ with the latest commit.
Thanks and for the advice on Drush

**Comment by geerlingguy** [comment]
Awesome, glad I could help, and thanks for posting an issue!
