### ISSUE TITLE
drupal console error

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#1140]
I am getting this error when i enter drupal list. I have to run vendor/bin/drupal and that is not convenient. How do i fix this please?

TypeError: Argument 1 passed to Drupal\Console\Core\Utils\TwigRenderer::__construct() must be an instance of Drupal\Console\Core\Utils\TranslatorManagerInterface, instance of Drupal\Console\Utils\TranslatorManager given in /var/www/drupalvm/drupal/vendor/drupal/console-core/src/Utils/TwigRenderer.php on line 43 #0 [internal function]: Drupal\Console\Core\Utils\TwigRenderer->__construct(Object(Drupal\Console\Utils\TranslatorManager), Object(Drupal\Console\Core\Utils\StringConverter))
#1 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.rendere...')
#3 /var/www/drupalvm/drupal/vendor/drupal/console/src/Bootstrap/Drupal.php(108): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.rendere...')
#4 /var/www/drupalvm/drupal/vendor/drupal/console/bin/drupal.php(46): Drupal\Console\Bootstrap\Drupal->boot()
#5 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(28): include_once('/var/www/drupal...')
#6 phar:///usr/local/bin/drupal/bin/drupal.php(87): Drupal\Console\Utils\Launcher->launch('/var/www/drupal...')
#7 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#8 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#9 {main}
TypeError: Argument 1 passed to Drupal\Console\Core\Utils\TwigRenderer::__construct() must be an instance of Drupal\Console\Core\Utils\TranslatorManagerInterface, instance of Drupal\Console\Utils\TranslatorManager given in Drupal\Console\Core\Utils\TwigRenderer->__construct() (line 43 of /var/www/drupalvm/drupal/vendor/drupal/console-core/src/Utils/TwigRenderer.php).

**Comment by geerlingguy** [comment]
@mooru - It looks like the Drupal Console version being used is installed as part of your Drupal project (`/var/www/drupalvm/drupal/vendor/drupal/console-core/src/Utils/TwigRenderer.php`).

If you go somewhere else in the VM and run the `drupal` command, does it give the same error? Do you have `drupalconsole` in the VM's `config.yml` `installed_extras` list?

**Comment by mooru** [comment]
When i run drupal from anywhere outside the web folder it seems ok. Yes drupalconsole is installed in the config.yml file

**Comment by geerlingguy** [comment]
@mooru - In that case, it sounds like the Drupal Console version installed with your Drupal site is the culprit. Do you know if you're using something like BLT to build your site, or is it a custom project? Or did you manually run `composer require` for Console?

If the version installed outside your project is working fine, it seems that this isn't something Drupal VM would be able to help with... Drupal VM can't/doesn't manage project-specific installs of Drush, Console, etc.

**Comment by mooru** [comment]
The drupal console the vm has came installed with drupalvm and vagrant. i noticed after i upgraded to version 4 but can't explain why or what happened. No, i am not using BLT

**Comment by geerlingguy** [comment]
@mooru - I'm guessing the Drupal site you installed was created by [drupal-project](), then. In that case, it might just be an old version of Drupal Console locked into your drupal project, and to update it, you can `cd` into the project root (probably `/var/www/drupalvm/drupal`), and run `composer require drupal/console:~1.0`. See if this updates the Drupal Console project to a later version that works.

**Comment by mooru** [comment]
The drupal project was installed using drupalvm. I have tried installing drupal console as suggested but still having the error

**Comment by geerlingguy** [comment]
Closing in favor of #1141 — it seems like these are related.

Also, @mooru - after running that command, what version of Drupal Console got installed?

**Comment by geerlingguy** [comment]
One last thing—for Drupal Console-related issues, it may be better to file an issue with Drupal Console itself, as it doesn't look like any of these errors are related to Drupal VM or the environment, but more something in Console reacting with the Drupal site you're building.
