### ISSUE TITLE
Support request for Drupal console error

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#1141]
Possibly related to #1140. Console is included in installed extras. I am installing Drupal VM as a composer dependency.

Following provisioning `which drupal` returns `/usr/local/bin/drupal` and ```composer update``` returns:
```
- Installing drupal/console-en (1.0.0-rc12)
```

But running 'drupal` from project root returns:
```
ArgumentCountError: Too few arguments to function Drupal\Console\Command\Config\ValidateCommand::__construct(), 0 passed and exactly 1 expected in /var/www/drupalvm/vendor/drupal/console/src/Command/Config/ValidateCommand.php on line 30 #0 [internal function]: Drupal\Console\Command\Config\ValidateCommand->__construct()
#1 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(928): ReflectionClass->newInstanceArgs(Array)
#2 phar:///usr/local/bin/drupal/vendor/symfony/dependency-injection/ContainerBuilder.php(468): Symfony\Component\DependencyInjection\ContainerBuilder->createService(Object(Symfony\Component\DependencyInjection\Definition), 'console.config_...')
#3 /var/www/drupalvm/vendor/drupal/console/src/Application.php(149): Symfony\Component\DependencyInjection\ContainerBuilder->get('console.config_...')
#4 /var/www/drupalvm/vendor/drupal/console/src/Application.php(39): Drupal\Console\Application->registerCommands()
#5 phar:///usr/local/bin/drupal/vendor/symfony/console/Application.php(124): Drupal\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 /var/www/drupalvm/vendor/drupal/console/bin/drupal.php(69): Symfony\Component\Console\Application->run()
#7 phar:///usr/local/bin/drupal/src/Utils/Launcher.php(30): include_once('/var/www/drupal...')
#8 phar:///usr/local/bin/drupal/bin/drupal.php(87): Drupal\Console\Launcher\Utils\Launcher->launch('/var/www/drupal...')
#9 phar:///usr/local/bin/drupal/bin/drupal(3): require('phar:///usr/loc...')
#10 /usr/local/bin/drupal(10): require('phar:///usr/loc...')
#11 {main}
ArgumentCountError: Too few arguments to function Drupal\Console\Command\Config\ValidateCommand::__construct(), 0 passed and exactly 1 expected in Drupal\Console\Command\Config\ValidateCommand->__construct() (line 30 of /var/www/drupalvm/vendor/drupal/console/src/Command/Config/ValidateCommand.php).
```

Running ```composer require drupal/console:~1.0``` from the project root returns: 

```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
```

However, note that vendor files pulled into an older instance via `composer update` on January 14 shows:
```
$ which drupal 
/usr/local/bin/drupal
```
and
```
$ drupal
Drupal Console (1.0.0-rc14)
===========================
```
Everything checks out on the older build. I guess I'll diff the relevant vendor directories in the morning?

**Comment by geerlingguy** [comment]
Yeah; I'm guessing this is related to a bug that was fixed 28 days ago: https://github.com/hechoendrupal/drupal-console/issues/3041

The answer would seem to be to force installation of rc14 or later. Unfortunately, what gets installed by `drupal-project` itself is out of my control... but you'd need to make sure to update Drupal Console manually, because once it's been required the first time, Drupal VM won't do anything with the version installed inside a Drupal project.

For the version installed globally, you can add `drupal_console_keep_updated: true` to your `config.yml` to make sure it's updated every time you run `vagrant provision`.

**Comment by minorscience** [comment]
👍 

Sounds good, thanks. Running ```composer update``` from ```/var/www/drupalvm``` does the trick. Appropriate to add this to my ```post_provision_scripts```?

**Comment by geerlingguy** [comment]
@minorscience - Typically `composer update` would be something you'd want to manage carefully. On most of my sites, I only run `composer update` rarely, after I make sure all my individual critical dependencies (themes, modules, core) are updated separately (via `composer update drupal/modulename` and the like).

If you run `composer update` a lot, then you may end up with module updates or core updates that break things from time to time, and it might not be what you expected.

**Comment by minorscience** [comment]
@geerlingguy Yep, running ```composer update``` like that that was just a quick test to confirm. Your advice is well-taken. 

Using ```composer update drupal/console``` solely moving fowrard.

**Comment by geerlingguy** [comment]
@minorscience awesome, sounds good!
