### ISSUE TITLE
Build composer tasks skipped following vagrant up?

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#1142]
Peripherally related to #1112.

I'm having a hard time wondering why the task runner is skipping the ```build_composer``` tasks, or least appears to. 

I'm building Drupal VM as a Composer dependency (which works very well in team environments by the way).

With the following directory structure:
```
config/config.yml
config/local.config.yml
config/Vagrantfile.local
composer.json
docroot
vendor
Vagrantfile
```
and the relevant block in local.config.yml (which overrides config.yml):
```
install_site: true
build_composer_project: false
build_composer: true
drupal_composer_path: "{{ config_dir }}/../composer.json"
drupal_composer_install_dir: "/var/www/drupalvm"
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
drupal_composer_dependencies: []
drupal_enabled_modules: []
```
I'm seeing the following during build:
```
TASK [Copy drush makefile into place.] *****************************************
skipping: [dvm]

TASK [Ensure drupal_core_path directory exists.] *******************************
skipping: [dvm]

TASK [Generate Drupal site with drush makefile.] *******************************
skipping: [dvm]

TASK [Check if a composer.json file is present.] *******************************
skipping: [dvm]

TASK [Run composer install if composer.json is present.] ***********************
skipping: [dvm]

TASK [Ensure drupal_composer_install_dir directory exists.] ********************
skipping: [dvm]

TASK [Copy composer.json into temporary location.] *****************************
skipping: [dvm]

TASK [Move composer.json into place.] ******************************************
skipping: [dvm]

TASK [Run composer install.] ***************************************************
skipping: [dvm]

TASK [Install dependencies with composer require.] *****************************

TASK [Ensure drupal_composer_install_dir directory has proper permissions.] ****
skipping: [dvm]

TASK [Generate Drupal project with composer package.] **************************
skipping: [dvm]

TASK [Install dependencies with composer require.] *****************************

TASK [Check if a project specific Drush binary exists.] ************************
ok: [dvm]

TASK [Use project specific Drush if available.] ********************************
ok: [dvm]

TASK [Check if site is already installed.] *************************************
ok: [dvm]

TASK [Configure database correctly if using PostgreSQL.] ***********************
skipping: [dvm]

TASK [Install Drupal with drush.] **********************************************
changed: [dvm]

TASK [Install configured modules with drush.] **********************************
changed: [dvm]
```
I guess it doesn't matter too much because I wind up with a working DVM installation, easily updating infrastructure by editing the appropriate yml file and running ```vagrant provision```. Or modifying ```composer.json``` to modify Drupal projects. But it is puzzling. Am I missing an override somewhere or otherwise misunderstanding the output above?

**Comment by geerlingguy** [comment]
@minorscience - I'm guessing you have already set up the Drupal site—here are the two tasks in question:

```yaml
  tasks:
    - name: Check if Drupal is already set up.
      stat: "path={{ drupal_core_path }}/index.php"
      register: drupal_site
      ignore_errors: true

    - name: Define drupal_site_exists
      set_fact:
        drupal_site_exists: "{{ drupal_site.stat.exists|default(false) }}"
```

Basically, if there's already an `index.php` inside the `drupal_core_path`, that means someone already ran `composer install`, so Drupal VM doesn't do it anymore (Drupal VM is only meant to bootstrap the first installation of a site, and doesn't currently have any ongoing site maintenance or deployment functionality, like Acquia BLT or other deploy tools.

The way the composer installation is set up, it expects that `drupal/core` is one of the dependencies of your project, and the first time you build your project, Drupal core would be downloaded as part of the `composer install`.

**Comment by minorscience** [comment]
Reading your notes, here's what is happening. 

When I run ```composer update``` from the host machine, against an empty docroot directory, it downloads Drupal core into docroot (along with vendor files to the vendor dir). Later, the task runner sees Drupal core in docroot, skips build_composer (as designed), and moves on to drush settings configuration. 

Does that sound right?

**Comment by geerlingguy** [comment]
@minorscience - Yes, exactly.

**Comment by oxyc** [comment]
I'll close this as your description of the process was correct and I assume you got everything working. Please re-open if you're still having issues.
