### ISSUE TITLE
Include cloud9 as an extra

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#1145]
### Issue Type

 - Feature Idea

### Summary

c9 is a cloud based IDE that opens in the browser. It would probably take a bit of work to include this, but it would be awesome to have the option of installing [c9](https://github.com/c9/core) as an optional extra.

This would bundle the IDE with the development environment.

**Comment by thom8** [comment]
@frob we looked into adding c9 to a drupal sprintbox and built a role [here](https://github.com/beetboxvm/ansible-role-beetbox-cloud9)

Still needs some tidy up but you're welcome to fork and publish on galaxy.

**Comment by frob** [comment]
@thom8 why did you abandon the effort?

**Comment by geerlingguy** [comment]
Eeh, all these newfangled editors and such, running on top of JS... give my my Vim and my Sublime Text, and I'll be happy :)

But more seriously... If this is dead simple and there's a galaxy role that does all the work, I might not be opposed to having it as an installed_extra, but definitely not a default.

**Comment by frob** [comment]
lol, my motivation is that we are looking to use that as a way for site builders with some CSS knowledge to do some work without having to maintain local development environments. I agree this shouldn't be a default as I expect my use-case is non-standard.

**Comment by thom8** [comment]
@frob wouldn't say it's abandoned, as much of the work behind the main project has been push upstream :)

However, for us the c9 role hasn't been of much use outside the context of a sprint VM.

**Comment by thom8** [comment]
@frob you can give it a try [here](https://github.com/beetboxvm/sprintbox)

Once provisioning is complete c9 should be available @ http://d8.ddns.net:8181/ide.html

**Comment by geerlingguy** [comment]
For now I'm going to close this out; if another project (like @thom8's sprint-focused Drupal 8 VM) would like to include it, that's great. But few (none?) of the Drupal VM users I've asked use anything besides PHPStorm, Vim, Emacs, Sublime Text, Atom, NetBeans, etc.

Plus, I'd push people away from developing in the browser regardless, for various reasons :)
