### ISSUE TITLE
Virtual Box Drupal Instance disappears

### ISSUE THREAD

**Issue by drmedrme** [geerlingguy/drupal-vm#1146]
### Issue Type

 - Bug Report / Support Request
 

### Your Environment

```
Vagrant 1.9.1
Echo is on.
VirtualBox 5.1.14r112924


```

### Your OS

 - **Windows** 10

### Summary

I have recently moved from acquia dev desktop to vagrant to test drupal environments.  I have downloaded the most recent vagrant, virtualbox, and drupalvm.

I can get my virtual box instance running with no problem.  I can access 192.168.88.88 and everything is there.  If I ssh into my virtual box to vagrant@drupalvm:/var/www/drupalvm/drupal/web I can see core modules and the normal drupal files.  However, if I power down the instance and restart it the drupal folder disappears and when ssh into vagrant@drupalvm:/var/www/drupalvm there are no other directors or files and the who drupal instance is gone.  Solr is still there, adminer is still there, but anything with drupalvm.dev is gone.

I have not touched the  drupalvm directory on the windows desktop.  So I havent done vagrant destroy to remove the instance.  Also, I can't use vagrant provision as it can not find the playbook.yml.  Also I can't do a vagrant up as it already has the drupal file in the drupalvm directory.

Apologies if any of my terminology is incorrect as I have been using acquia dev desktop which has been relatively easy but not nearly as powerful as vagrant.

Thanks in advance
gerald

**Comment by geerlingguy** [comment]
@drmedrme - The only way the folder will be present is if you use Vagrant (and only Vagrant) to manage the VM; so to stop the VM, you would run `vagrant halt` (or `vagrant suspsend` to just sleep it), and to start the VM, you would run `vagrant up` again.

You should be able to run `vagrant up` from the directory where you downloaded Drupal VM, and it should always have the Vagrantfile in that directory. Are you also using something like BLT, or just Drupal VM separate from your website's codebase?

**Comment by drmedrme** [comment]
Thanks.  I was stopping the VM through Virtual Box.  When doing as you suggested, everything work fine.  Thanks for answer and a good product.
gerald

**Comment by geerlingguy** [comment]
Great!
