### ISSUE TITLE
updates on drupal module

### ISSUE THREAD

**Issue by vibanu** [geerlingguy/drupal-vm#1148]
### Issue Type

  - Documentation Report

### Your Environment

```
Vagrant 1.9.1
vagrant@compscisbu:~$ vboxmanage --version
The program 'vboxmanage' is currently not installed. You can install it by typing:
sudo apt install virtualbox
vagrant@compscisbu:~$ ansible --version
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

### Your OS

 - **Windows** (version)

### Summary
I am new to vagrant. I have a local copy working. There are security updates that I applied to my local site. I want to push them to acquia cloud dev site. I can do git push etc. I am not clear on how to pull the changes in cloud from my local vm.

**Comment by geerlingguy** [comment]
@vibanu - This is not something in the purview of Drupal VM's support—this is more a question for how you would manage sites using Acquia Cloud as your hosting environment.

Typically, you would either build your website and have the codebase and configuration in Git, then push changes to your Git repository (either hosted at Acquia or somewhere else), or you could also use Drush or some other tool to run `sql-sync` to transfer databases between environments too.

But it's not something that Drupal VM supports out of the box—you would need to use other tools. One often-recommended tool for Drupal 8 projects hosted in Acquia Cloud is [BLT](https://github.com/acquia/blt).

For my own projects, I usually just use Drush to pull down databases, then I make changes locally, export configuration to my Git codebase, push those changes up to my webserver, then have some commands on the webserver (e.g. `drush updb -y && drush cim && drush cr`) run to finish the deployment.

**Comment by vibanu** [comment]
This is helpful.

Thank you.
