### ISSUE TITLE
blt vm issue

### ISSUE THREAD

**Issue by nirojghale-iheartmedia** [geerlingguy/drupal-vm#1150]
- Bug Report / Support Request
### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (version)

### Full console output

https://gist.github.com/nirojghale-iheartmedia/b0fdee5c7985d42f91882712bc3a71ef

**Comment by geerlingguy** [comment]
I'm presuming this was the original issue: https://github.com/acquia/blt/issues/1020

In which case, the following addition to `config.yml` solved the issue:

```yaml
selenium_install_firefox: yes
selenium_install_chrome: no
```
