### ISSUE TITLE
pecl_http install

### ISSUE THREAD

**Issue by Topplestack** [geerlingguy/drupal-vm#1153]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
5.1.6r110634
ansible 2.1.2.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.11.6

### Summary

Trouble installing pecl_http/php-pecl-http w/cURL option

Tried multiple approaches. I'm not familiar enough with ansible to know what I am missing.

**Comment by geerlingguy** [comment]
@Topplestack - What have you tried so far? There's no console output or any other way to help debug... have you taken a look at the php-pecl role documentation? (https://github.com/geerlingguy/ansible-role-php-pecl)

**Comment by Topplestack** [comment]
adding pecl_http to the php=pecl role errors out. I believe due to the raphf dependency not being there.

TASK [geerlingguy.php-pecl : Install PECL libaries.] ***************************
failed: [drupalvm] (item=pecl_http) => {"changed": false, "cmd": "yes \"\" | pecl install pecl_http", "delta": "0:00:00.002348", "end": "2017-02-06 15:29:12.982982", "failed": true, "failed_when_result": true, "item": "pecl_http", "rc": 127, "start": "2017-02-06 15:29:12.980634", "stderr": "/bin/sh: 1: pecl: not found\nyes: standard output: Broken pipe", "stdout": "", "stdout_lines": [], "warnings": []}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************
	to retry, use: --limit @/Users/jessetaylor/github/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=80   changed=24   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.



From what I can see the php-pecl-http package needs to be installed with apt-get in order for the raphf dependency to be there. For some reason PHP still does not recognize the pecl_http extension even though there is a .ini file for it in /etc/php/7.0/fpm/conf.d

**Comment by geerlingguy** [comment]
It sounds like a versioning problem, or if you're overriding the list of `php_packages`, maybe the pecl package wasn't included. You could either use `php_packages_extra` or some other method of adding in the appropriate apt packages required.

**Comment by Topplestack** [comment]
I finally got it added by including php-pecl-http in extra_packages in config.yml and then adding it to the php defaults. From what I can tell this is a PHP 7 change

It turns out the greater issue was that much of the functionality the module required isn't supported by modern versions of PHP, so it's a null issue now.
