### ISSUE TITLE
Drush Tools after provision?

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#1157]
### Issue Type
- Support Request

### Your Environment
```
Vagrant 1.9.0
VirtualBox 5.1.14r112924
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
- **macOS** (10.12.3)

### Summary

Wondering how to get drush tools in drupal vm. For example:
* [Registry Rebuild](https://www.drupal.org/project/registry_rebuild)
* [SAR](https://www.drupal.org/project/sar) 
* [GRN](https://www.drupal.org/project/grn)
* [Cache Audit](https://www.drupal.org/project/cacheaudit) 
* [Site Audit](https://www.drupal.org/project/site_audit)

I've manually downloaded them in the VM but wondering if there was a better way to do that during provision or after provision?

**Comment by oxyc** [comment]
Currently I don't think there is unless you use composer or add them to the make file. See https://github.com/geerlingguy/ansible-role-drush/pull/24 though.

You could also add a post-provision shell script of course.

**Comment by joelpittet** [comment]
The post-provision shell script sounds like a decent approach though for some reason I couldn't get it working last I tried.

**Comment by thom8** [comment]
You could try [drupal_enable_modules](https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/install-site.yml#L34-L39) and add the module paths to `.gitignore`, but composer `require-dev` would be better.

```
drupal_enable_modules:
  - registry_rebuild
  - sar
  - grn
  - cacheaudit
  - site_audit
```

**Comment by joelpittet** [comment]
Thanks @thom8, I gave that a try but it didn't seem to do it if I didn't install drupal through this.  Nice idea though.  

Here's the output when I try to run a post provision shell script.
```failed: [drupalvm] (item=../scripts/drush-extensions.sh) => {"changed": true, "failed": true, "item": "../scripts/drush-extensions.sh", "rc": 127, "stderr": "Shared connection to 127.0.0.1 closed.\r\n", "stdout": "Post Provisioning virtual machine...\r\n/home/vagrant/.ansible/tmp/ansible-tmp-1486597817.75-181001006121206/drush-extensions.sh: line 5: drush: command not found\r\n", "stdout_lines": ["Post Provisioning virtual machine...", "/home/vagrant/.ansible/tmp/ansible-tmp-1486597817.75-181001006121206/drush-extensions.sh: line 5: drush: command not found"]}```

So I guess the command is not found or the path is missing. I'll try again but that was the error I was running into before.

**Comment by thom8** [comment]
Ahh true this task is skipped when not a new install.

You may need to use the full path to `drush` as the post provisioning tasks are run as `root` eg.

`/usr/local/bin/drush pm-enable ... -y`

**Comment by joelpittet** [comment]
Yeah that was a path issue. 
ended up with this working:

```
#!/bin/bash
/bin/su - vagrant -c "drush dl -y --default-major=7 sar grn site_audit cacheaudit registry_rebuild"
```

**Comment by thom8** [comment]
An alternative would be to duplicate the [`Install configured modules with drush.`](https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/install-site.yml#L34-L39) task as a custom post provisioning [ansible task](http://docs.drupalvm.com/en/latest/extending/scripts/#ansible-task-files), then you have access to all ansible variables like `"{{ drush_path }}"` & `"{{ drupal_enable_modules }}"`.

**Comment by joelpittet** [comment]
That sounds pretty handy thanks again @thom8
