### ISSUE TITLE
install.php redirects to /core/install.php (which then 404s) even in D7?

### ISSUE THREAD

**Issue by ellyjonez** [geerlingguy/drupal-vm#1158]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.0.26r108824
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.11.6)

### Summary

I've got the single site install turned off and am using Drupal VM to run  a few different drupal 7 sites at different vhosts, the docroots of which I'm syncing via nfs. The folders seem to be syncing fine - I can create html files in them and go to myhostname.dvm/file.html and see it. However, when I put drupal core into the folder, if I visit the site in a browser, `install.php` does a 301 redirect to `/core/install.php` which does not exist.  This seems to be Drupal 8 behavior getting applied to a Drupal 7 site? 

I was using nginx for my webserver, I'm currently rebuilding with apache to see if the problem is happening when using apache also.

**Comment by oxyc** [comment]
My bad, I already forgot about D7 when I made that commit... It should work with apache though.

**Comment by geerlingguy** [comment]
I'm fortunate enough to not have touched any new D7 sites in the past year now :D

**Comment by ibuildit** [comment]
This creates issues when you have more than one site, and the other site is a D7.

The "drupal_major_version" flag is a global flag for the entire VM.

That's not very practical when you have several sites configured.

**Comment by Jasper-Grasmaijer** [comment]
I have this problem with DrupalVM 4.7.0.
Is there a solution for this (redirect problem with mixed D7 & D8 sites on one instance of DrupalVM)? Or should I just setup a separate VM for Drupal 7 sites?

**Comment by FinBoWa** [comment]
you could go vm per project also. That's what I do.

**Comment by Jasper-Grasmaijer** [comment]
Tnanx @FinBoWa but I have a small ssd and not enough space for a vm per project.

**Comment by FinBoWa** [comment]
Time to upgrade then :)... Personally i think drupalvm as per project basis. Its a box that suits the needs of that particular project, nothing else. I run only the tools that work for that site in there.

**Comment by Jasper-Grasmaijer** [comment]
Thanks for your input (I'm aware of the things you mention). I also use DrupalVM to set up my VPS with both D8 and D7 sites. The solution I'll use for now is to ssh into my server and manually remove the redirect from the server block for my D7 sites. 

For those having this issue and don't know where to find the server block configuration it's at /etc/nginx/sites-enabled. You need to remove:
# Redirect common PHP files to their new locations.
     location ~ ^((?!.*(?:core)).*)/(install.php|rebuild.php) {
          return 301 $scheme://$host$1/core/$2$is_args$args;
     }

**Comment by oxyc** [comment]
Nowadays you can use custom templates on a per vhost basis with the nginx role.

```yaml
nginx_hosts:
  - server_name: "site1.test"
    root: "{{ drupal_core_path }}/site1"
    is_php: true
    template: "{{ config_dir }}/nginx-d7.conf.j2"

  - server_name: "site2.test"
    root: "{{ drupal_core_path }}/site2"
    is_php: true
    template: "{{ config_dir }}/nginx-d8.conf.j2"
```

Or if you want to drop the redirect you can override the default template with:

```yaml
nginx_conf_template: "{{ config_dir }}/nginx.conf.j2"
```

**Comment by Jasper-Grasmaijer** [comment]
Thanks oxyc!

I just tried another way and if you want to use the default template you can set:

`drupal_major_version: 7`

and add extra parameters to nginx_hosts for the drupal 8 website(s), like so:

```
nginx_hosts:
  - server_name: "local.website.com www.local.website.com"
    root: "/var/www/localwebsite/web"
    is_php: true
    extra_parameters: |
        # Redirect common PHP files to their new locations.
        location ~ ^((?!.(?:core)).)/(install.php|rebuild.php) {
             return 301 $scheme://$host$1/core/$2$is_args$args;
        }
```
