### ISSUE TITLE
bcmath no longer loads

### ISSUE THREAD

**Issue by cdbingh1** [geerlingguy/drupal-vm#1161]
### Issue Type

 - Bug Report / Support Request
 
### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.14r112924
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.3)
 

### Summary

Despite adding this to config.yml (and despite this working less than a month ago), bcmath doesn't load and hence implementing drupal commerce 2 is impossible:

extra_packages:
  - php-bcmath

**Comment by oxyc** [comment]
Try with `php_packages_extra` instead of `extra_packages`.

php_packages_extra:
  - "php{{ php_version }}-bcmath"

**Comment by geerlingguy** [comment]
What @oxyc should work in the latest Drupal VM versions, and is the preferred way to add extra PHP-related packages to the system.
