### ISSUE TITLE
How To enable install of modules from drupal.org 

### ISSUE THREAD

**Issue by skorasaurus** [geerlingguy/drupal-vm#1163]
### Issue Type

 - Bug Report / Support Request
 - Documentation Report

### Your Environment
```
Vagrant 1.8.7
vbox 5.1.10r112026
ansible 2.2.1.0
```

### Your OS
ubuntu 14.04.1, 64bit. 

### Summary

My first time using drupal-vm; set it up without a problem and initializes fine, able to connect to my drupal instance (created on the fly by having 'build_composer_project' set to true).
After sshing into the vagrant instance: I run: ```composer require drupal/devel:1.x``` to install a module.

output https://gist.github.com/skorasaurus/c34b556c8bfd9e02c868a4beb50441a9
I'm a unclear why packages within composer aren't found by default when [the default composer.json](https://github.com/geerlingguy/drupal-vm/blob/81812990a5a4ca704c0f3012a6fcb988f07d8a95/example.drupal.composer.json) for a new project includes drupal.org 

How does a user install additional modules in composer to the newly created drupal site?

I haven't modified config.yml at all; just getting my bearings wet, learning Drupal through drupal-vm. 

(Sorry, I'm aware that this is a request for support, and after reading over the docs, I wasn't sure if there was any informal place - i.e. slack/IRC channel to ask them and couldn't find an answer after some search and trial and error).

**Comment by geerlingguy** [comment]
No problem at all! This is a great place to ask away.

One quick note (don't have time for more right now)—you can add a module using all Drupal VM's defaults by adding the following to a `config.yml` file:

```yaml
drupal_composer_dependencies:
  - "drupal/devel:1.x-dev"
  - "drupal/xhprof:1.x-dev"
  - "drupal/honeypot:^1.0"

drupal_enable_modules:
  - devel
  - xhprof
  - honeypot
```

The second command only takes effect on the first provisioning of the VM, when Drupal is initially installed.

**Comment by oxyc** [comment]
Closing as I assume @geerlingguy explanation was sufficient. If you're having any further questions or issues, please open an issue.
