### ISSUE TITLE
Can't change path of host drupal installation

### ISSUE THREAD

**Issue by adriadrop** [geerlingguy/drupal-vm#1164]
- Bug Report / Support Request
 - **macOS** 

I am trying to change drupal installation folder but whenever I change the

drupal_core_path: "{{ drupal_composer_install_dir }}/web"

to something like

drupal_core_path: "{{ drupal_composer_install_dir }}/whatever"

vagrant provisioning gets broken and it is still instaling drupal in /drupal/web directory, like its hardcoded somewhere else. Seems like a bug as I cant change path of my host drupal installation.

**Comment by oxyc** [comment]
Are you using the default option to install [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project). The composer.json of this project has `web/` hardcoded so you cant really change it unless you switch to a different composer project, or a different codebase setup.

http://docs.drupalvm.com/en/latest/deployment/composer-package/
http://docs.drupalvm.com/en/latest/deployment/composer/

**Comment by adriadrop** [comment]
I cloned drupal-vm and I just changed this 
drupal_core_path: "{{ drupal_composer_install_dir }}/web"

as I wanted to have it in different directory.

If I am not mistaking, you are refering to this json file and settings in it?
https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json


Maybe because I am new with composer, but I find this a bit misleading, thinking I can just change config there in config.yml, tried so many times to install vagrant with drupal to non "/web"  folder :(

**Comment by oxyc** [comment]
That's correct, and also you have a very good point. This could use some clarification!

**Comment by adriadrop** [comment]
Thanx on clarification, would have save me some time trying to force vagrant and drupal to respect my folder wishes. Hope some new comment info helps someone in future.

**Comment by oxyc** [comment]
Thanks for the report! I'll open a PR later on at some point.

**Comment by adriadrop** [comment]
BTW drop by Croatia on your nomad trips :)

**Comment by oxyc** [comment]
Actually it's already mentioned in the docs

> Ensure that the webroot configured in the Composer package matches the one set in drupal_core_path. The default is set to web/.

Not sure if we really to highlight it more? Maybe in the `default.config.yml`?

**Comment by geerlingguy** [comment]
Hmm... it's one of those things where it's a composer issue that isn't easy to teach through a comment/comments in the config file. I'd say we can just leave it be for now, and if it continues to be a barrier, we can reconsider. Closing this issue for now, as at least there's some documented commentary on the issue in this thread!
