### ISSUE TITLE
Escaped html tags in docs [minor]

### ISSUE THREAD

**Issue by weitzman** [geerlingguy/drupal-vm#1168]
### Issue Type

 - Documentation Report

### Summary

I see escaped titles like &lt;small&gt; in the search result item titles at http://docs.drupalvm.com/en/latest/search.html?q=tideways

**Comment by geerlingguy** [comment]
Hmm... I noticed that too, recently. @oxyc do you know if there's any way in RTD to avoid this. I like having the smaller text in the sidebar... but we could stick to parens instead to make titles (and Google search titles) a little nicer.

**Comment by geerlingguy** [comment]
And for reference:

<img width="515" alt="tideways" src="https://cloud.githubusercontent.com/assets/481677/22869994/35b54b86-f169-11e6-93c9-51da2be6aa2a.png">

**Comment by oxyc** [comment]
Ah, I didn't think of that. Maybe parens then yes. Even if I found it quite difficult to get a good overview when I tried it.
