### ISSUE TITLE
Start XDebug session from browser when using PHPStorm with drupalvm

### ISSUE THREAD

**Issue by nkgokul** [geerlingguy/drupal-vm#1169]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.11.6 (15G31))

### Full console output

vagrant:///Users/gokul/drupalvm/drupalvm/usr/bin/php -dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=10.0.2.2 /vagrant/drupal/web/index.php
XDebug could not open the remote debug file '/tmp/xdebug.log'.

### Summary

I have set up xdebug with drupalvm and phpstorm. When I debug from phpstorm I am able to step debug. But I am unable start the debug session from the browser using the bookmark. Has anybody got this working before?

**Comment by thom8** [comment]
Try adding `?XDEBUG_SESSION_START=1` to the URL, you'll also need to path mappings but you should be prompted by phpstorm.

**Comment by geerlingguy** [comment]
@nkgokul - Did that help?

**Comment by oxyc** [comment]
Closing this as we haven't heard back in a while. If @thom8 suggestion didn't work, please re-open the issue and we can dig deeper.

**Comment by nkgokul** [comment]
Path mapping was the missing point. After setting it up it worked. Sorry for the delay in responding.

**Comment by mah-sanjay** [comment]
> Try adding `?XDEBUG_SESSION_START=1` to the URL, you'll also need to path mappings but you should be prompted by phpstorm.

This really helped. Thank you @thom8 !
