### ISSUE TITLE
XHProf and PimpMyLog not respecting specified hostname

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#117]
Apache is taking 'host.dev' but XHProf and PimpMyLog are both showing up as xhprof.drupalvm.dev and pimpmylog.drupalvm.dev respectively.

I was expecting both to inherit *.host.dev

**Comment by geerlingguy** [comment]
@nerdstein - So you're saying you'd expect them to behave more like:

```
xhprof.{{vagrant_hostname}}
pimpmylog.{{vagrant_hostname}}
```

Instead of being hardcoded in the apache vhosts with `drupalvm.dev`?

Makes sense to me!

**Comment by nerdstein** [comment]
Yes please :)
