### ISSUE TITLE
Support Drush and xdebug inside DrupalVM

### ISSUE THREAD

**Issue by japerry** [geerlingguy/drupal-vm#1171]
### Issue Type
 - Feature Idea
 - Documentation Report

### Your Environment
Vagrant 1.9.1
VirtualBox 5.1.4r110228
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides

### Your OS
 - **macOS** 10.11.6

### Summary
Drush+xdebug is a powerful tool for stepping through code that isn't available via the UI, with migrate being the biggest example. 

DrupalVM is almost capable of allowing for this, however it needs to accept the following three environment variables: 
```bash
# Allow client to pass locale environment variables
AcceptEnv PHP_IDE_CONFIG
AcceptEnv XDEBUG_CONFIG
AcceptEnv PHP_OPTIONS
```

**Comment by oxyc** [comment]
Also https://github.com/geerlingguy/drupal-vm/issues/716#issuecomment-267700090

**Comment by heddn** [comment]
I'm able to test drush & migrate in d8 with xdebug right now inside the VM. You just have to setup things inside the VM to send its xdebug stuff to outside so PHPStorm can catch things.

**Comment by oxyc** [comment]
@japerry does the above PR solve it? any chance you could provide an example on how to use it? Or some docs would be greatly appreciated.

**Comment by geerlingguy** [comment]
Oh haha, I just read this comment after I made an almost identical comment in the PR. @japerry ^^

**Comment by oxyc** [comment]
Ops, forgot to mention it was WIP. 

Or @mirsoftacquia, any chance you could [provide a good example](https://github.com/geerlingguy/drupal-vm/issues/716#issuecomment-267700090) we could add to the docs?

**Comment by oxyc** [comment]
As I understand we can load XDebug on demand with this (I use vim and haven't set up an IDE so can't test this right now though).

```sh
export PHP_OPTIONS="-d xdebug.profiler_enable=1"
```

and then xdebug will be enabled in the CLI whenever you (or your IDE) SSH into Drupal VM.

Tested that the following scenario works:

```sh
PHP_OPTIONS="-d xdebug.profiler_enable=1" drush @drupalvm.drupalvm.dev php-eval 'echo file_get_contents(xdebug_get_profiler_filename());'
```

while the following does not:

```sh
drush @drupalvm.drupalvm.dev php-eval 'echo file_get_contents(xdebug_get_profiler_filename());'
```

To get it working I also need to add `SendEnv=PHP_OPTIONS` to the drush alias.

```
'ssh-options' => '-o SendEnv=PHP_OPTIONS -o PasswordAuthentication=no -i ' . drush_server_home() . '/.vagrant.d/insecure_private_key',
```

Pretty cool tbh. @MKorostoff https://github.com/geerlingguy/drupal-vm/issues/1001 you might be interested too.

---

Unrelated but this also made me recall this comment

> Yeah, this looks like it's related to removing mailhog from the installed_extras. You will need to update the php_sendmail variable to default back to PHP's built-in mail handling.
>
> I wish Drupal core didn't require working sendmail just to install :P
> – https://github.com/geerlingguy/drupal-vm/issues/1081#issuecomment-269068762

Which we could simply disable by setting the following environment variable for the site install task ```PHP_OPTIONS="-d sendmail_path=`which true`"```

**Comment by joelpittet** [comment]
One thing I had to do to get this working was set the remote_host to `10.0.2.2` instead of `localhost`
remote_host=10.0.2.2  this seems to work better.

**Comment by oxyc** [comment]
This type of scenario is now fixed but I also believe it works out of the box thanks to https://github.com/geerlingguy/drupal-vm/commit/dd60793da4dd02fbe3079fe750ce0ee03b015377.
