### ISSUE TITLE
Getting warning: remote connection disconnect during vagrant up on release 4.2.1

### ISSUE THREAD

**Issue by leolandotan** [geerlingguy/drupal-vm#1172]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.0.20r106931
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.10.5)

### Full console output

https://gist.github.com/leolandotan/30632cf3eff80ec68ac55aa255b4d01b
https://gist.github.com/leolandotan/eac9232b48ac9c166bbdee828b6fdd19

### Summary

After using drupalvm release 4.2.1, updated the vagrant box to the latest(1.0.8 I think) and running `ansible-galaxy install -r requirements.yml --force` inside /provisioning I cannot start a fresh VM.

I just copied the default.config.yml file to config.yml and did `vagrant up`. Prior to running the command, I ran `vagrant destroy` and `rm -rf .vagrant/`

Other VMs still work not related to drupalvm.

**Comment by geerlingguy** [comment]
@leolandotan - Drupal VM now requires VirtualBox 5.1.x (and the latest version is 5.1.14). There are likely a few different issues you'll run into if you try running Drupal VM with older versions of VirtualBox.

**Comment by leolandotan** [comment]
Hi @geerlingguy ! Thank you for your response. I'll definitely try that and provide feedback asap.

**Comment by gitressa** [comment]
I followed this guide to upgrade to Virtualbox 5.1 on Ubuntu 16.04:
[How to Install Latest VirtualBox 5.1 on Ubuntu 16.04/Debian 8](https://www.linuxbabe.com/virtualbox/install-latest-virtualbox-5-1-ubuntu-16-04)

**Comment by leolandotan** [comment]
@gitressa I'll try to follow that. Thank you!

**Comment by leolandotan** [comment]
I can confirm that updating VirtualBox to 5.1.x fixed the `vagrant up`. Thank you very much guys!
