### ISSUE TITLE
Is there a workaround to use run-tests.sh --browser?

### ISSUE THREAD

**Issue by wturrell** [geerlingguy/drupal-vm#1174]
### Issue Type
 - Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
ansible 2.2.1.0
  config file = /Users/wt/.ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.11.6 El Capitan)

### Full console output

> Couldn't get a file descriptor referring to the console

when using
`run-tests.sh --browser`

### Summary

I realise _why_ this is happening - obviously if I run tests from the Mac itself it can easily launch my  browser when finished.  However certain tests (such as the core issue I was working on today, simply don't work properly when run in OS X, only in DrupalVM, and it's really helpful to use `--browser` and `--verbose` to look at individual pages.

Is there anyway to start tests in the VM (or possibly via Ansible??) - and thus filter by individual method, as well as class - but still get the full HTML reports? (even if I have to check what the URL is myself each time.)

**Comment by geerlingguy** [comment]
Adding a few bits and pieces to make sure this is reproducible:

  1. Install a Drupal 8 site.
  2. Enable the Simpletest module.
  3. `vagrant ssh` into Drupal VM.
  4. `cd` into `/path/to/[docroot]/scripts`
  5. Run `php run-tests.sh --browser Test`

**Comment by geerlingguy** [comment]
It looks like the `run-tests.sh` script is looking to run either `open [url]` (macOS, most often), `xdg-open [url]` (Linux flavors), or `start [url]` (Windows flavors).

To get `xdg-open` working inside Drupal VM (these instructions assume Ubuntu, tested on 16.04 at least):

  1. Install `xdg-open`: `sudo apt-get install -y xdg-utils`
  2. Run a test: `php run-tests.sh --browser Test`

Then it will show an error like:

```
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links2: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: links: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: lynx: not found
/usr/bin/xdg-open: 461: /usr/bin/xdg-open: w3m: not found
xdg-open: no method available for opening 'http://localhost/sites/default/files/simpletest/verbose/results-487d9cd9-5d8a-474c-bad3-73fdb03bcedf.html'
```

I've tried installing and using `links2` and `lynx`, but it seems the `run-tests.sh` script just pauses until stopped manually if it detects a CLI browser.

So in lieu of that, I just copied the link that was spit out at the end, replaced `localhost` with my Drupal VM's hostname (`drupalvm.dev` by default), then pasted it in a browser on my Mac/host, and voila!

<img width="864" alt="test-results-in-browser-on-host" src="https://cloud.githubusercontent.com/assets/481677/25032542/7a70bde0-209a-11e7-95ae-a0822e3cadb1.png">

**Comment by geerlingguy** [comment]
And I was about to file a core issue to fall back to printing the URL alone if no valid OS helper was found (it searches for `xdg-open`, then `open`, then `start`)... but then realized that Ubuntu flavors (don't know about others) include `/bin/open`, which apparently is a [wrapper around openvt](https://unix.stackexchange.com/a/253531) and doesn't actually have anything to do with opening a file from the CLI.

So, I'll just leave it be, and recommend you install `xdg-utils` to get the URL to view the full test results.

**Comment by malcomio** [comment]
thanks, that did the trick
