### ISSUE TITLE
Install mysql 5.6

### ISSUE THREAD

**Issue by anacona16** [geerlingguy/drupal-vm#1179]
How to install mysql 5.6?

**Comment by geerlingguy** [comment]
The best way to get a particular version right now is to use whatever base OS box defaults to that in the system repos. For example, 5.5 on Ubuntu 14.04, 5.7 on Ubuntu 16.04...

But see: https://github.com/geerlingguy/ansible-role-mysql/issues/64 for more info—I'm closing this ticket and recommending the discussion stay focused in the MySQL role repo.
