### ISSUE TITLE
XHProf not showing memory consumption

### ISSUE THREAD

**Issue by subhojit777** [geerlingguy/drupal-vm#1182]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.14r112924
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.2)

### Full console output

N/A

### Summary

PHP 7.0.15-1+deb.sury.org~xenial+1

XHProf is supposed to show memory consumption by default like here http://www.md-systems.ch/blog/techblog/2011/08/23/finding-performance-bottlenecks-xhprof. But in my case I don't see memory consumtion.

<img width="439" alt="screen shot 2017-02-27 at 4 58 06 pm" src="https://cloud.githubusercontent.com/assets/1435641/23359785/ef768e36-fd0d-11e6-8470-5c3d1f2f031a.png">

What could be the issue?

**Comment by oxyc** [comment]
Could you check if it works with [tideway](http://docs.drupalvm.com/en/latest/extras/tideways/)? Tideways is a well-maintained fork of xhprof

**Comment by subhojit777** [comment]
The documentation does not says how to integrate Tideways with DrupalVM.

**Comment by oxyc** [comment]
> To enable profiling of Drupal pages using the Tideways PHP Extension, follow the directions for [configuring the XHProf and the XHProf module](http://docs.drupalvm.com/en/latest/extras/xhprof/#xhprof-module), but choose the Tideways extension under in the Profiling settings section.

> As with the XHProf extension, you can view callgraphs (and a listing of all stored runs) using Drupal VM's own XHProf UI installation by visiting http://xhprof.drupalvm.dev/ and clicking on the relevant run, then clicking the [View Full Callgraph] link.

it does miss the instruction about adding `tideways` to the `installed_extras` list.

**Comment by subhojit777** [comment]
Where can I see the available role variables. This repo https://github.com/geerlingguy/ansible-role-tideways does not exist.

**Comment by geerlingguy** [comment]
@subhojit777 - It's actually https://github.com/geerlingguy/ansible-role-php-tideways

**Comment by geerlingguy** [comment]
Also, I have been using the XHProf module for Drupal with Tideways and it seems to work well (with both CPU and memory profiling data intact). I use the XHProf UI instead of the more boring one included with the XHProf module :)

**Comment by oxyc** [comment]
Whops, I'll submit a PR fixing these issues in a bit

**Comment by subhojit777** [comment]
Seems like Tideways PHP extension is installed
<img width="959" alt="phpinfo__" src="https://cloud.githubusercontent.com/assets/1435641/23367469/6313f55a-fd30-11e6-8c53-6af4757903c4.png">

And as per the documentation here I should see an option to select Tideways
<img width="1070" alt="xhprof_settings___telus_web_store" src="https://cloud.githubusercontent.com/assets/1435641/23367493/7361bc44-fd30-11e6-989d-3afbdf172958.png">

Am I missing something?

**Comment by subhojit777** [comment]
I am using Drupal 7.

**Comment by geerlingguy** [comment]
@subhojit777 - Oh... I've never tried it using Drupal 7 since a couple years ago :/

I wonder if that's a bug in the Drupal 7 version of the XHProf module.

**Comment by oxyc** [comment]
Unfortunately the D7 version of the XHProf module hasn't been updated in 3 years, so there's no tideways support. XHProf not being maintained anymore I don't think there's a way to get this working.

**Comment by geerlingguy** [comment]
Closing this issue for now—this is definitely an upstream issue with the XHProf module for Drupal 7. I'd recommend sticking to older Devel releases which actually supported XHProf better than XHProf did :)
