### ISSUE TITLE
Task: add repository for PHP 5.6 fails

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1183]
### Issue Type
 - Support Request

### Your Environment

```
5.1.14r112924
ansible 2.2.1.0
```

### Your OS

 - **macOS** (10.12.1)

### Full console output

TASK [Add repository for PHP 5.6.] *********************************************
fatal: [pncbdev]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}

### Summary

I destroyed an existing project and wanted to rebuild it. I have updated Vagrant to 1.9.2 and latest Virtual Box (was getting SSH networking / timeout errors - that has gone away). Now I consistently get this message on this task, whereas everything else goes fine.

Do I need to replace and redo my DrupalVM for the project?

**Comment by geerlingguy** [comment]
@kevinquillen - Can you try again? Sometimes this error just goes away on it's own. Also, what version of Drupal VM are you running?

**Comment by kevinquillen** [comment]
Hmm... I think the last time I updated was Novermber.

**Comment by kevinquillen** [comment]
I just overwrote with 4.2.1 and running, it passed that task. Weird.

**Comment by geerlingguy** [comment]
Definitely strange! Maybe some dependency had a bad variable.
