### ISSUE TITLE
Error: cannot find role

### ISSUE THREAD

**Issue by singerxt** [geerlingguy/drupal-vm#119]
Hello ! ;-)

After 
```
vagrant reload
```

I'm getting error
```
ERROR: cannot find role in /Users/mateusz/Desktop/foxprod/provisioning/roles/geerlingguy.repo-remi or /Users/mateusz/Desktop/foxprod/provisioning/geerlingguy.repo-remi or /etc/ansible/roles/geerlingguy.repo-remi
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

any thoughts ? ;-)

**Comment by geerlingguy** [comment]
I'm guessing the same thing happened to you that has happened to a few others who have some of the roles pre-installed... If you run `sudo ansible-galaxy install -r provisioning/requirements.txt --force` in the same directory as the Vagrantfile, then it should force install all the roles and not error out.

**Comment by geerlingguy** [comment]
I think I'll update the README to use the `--force` flag by default.

**Comment by singerxt** [comment]
```--force``` is fix for this issue. Thanks !

**Comment by devekko** [comment]
yaml ified

 sudo ansible-galaxy install -r provisioning/requirements.yml --force

**Comment by devekko** [comment]
getting this 

 downloading role '---', owned by 
Sorry, --- was not found on galaxy.ansible.com.
 downloading role 'selenium', owned by -%20src%3A%20arknoll
Sorry, - src: arknoll.selenium was not found on galaxy.ansible.com.
 downloading role 'adminer', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.adminer was not found on galaxy.ansible.com.
 downloading role 'apache', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.apache was not found on galaxy.ansible.com.
 downloading role 'composer', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.composer was not found on galaxy.ansible.com.
 downloading role 'daemonize', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.daemonize was not found on galaxy.ansible.com.
 downloading role 'drupal-console', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.drupal-console was not found on galaxy.ansible.com.
 downloading role 'drush', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.drush was not found on galaxy.ansible.com.
 downloading role 'firewall', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.firewall was not found on galaxy.ansible.com.
 downloading role 'git', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.git was not found on galaxy.ansible.com.
 downloading role 'java', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.java was not found on galaxy.ansible.com.
 downloading role 'mailhog', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.mailhog was not found on galaxy.ansible.com.
 downloading role 'memcached', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.memcached was not found on galaxy.ansible.com.
 downloading role 'mysql', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.mysql was not found on galaxy.ansible.com.
 downloading role 'nginx', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.nginx was not found on galaxy.ansible.com.
 downloading role 'nodejs', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.nodejs was not found on galaxy.ansible.com.
 downloading role 'php', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.php was not found on galaxy.ansible.com.
 downloading role 'php-memcached', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.php-memcached was not found on galaxy.ansible.com.
 downloading role 'php-mysql', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.php-mysql was not found on galaxy.ansible.com.
 downloading role 'php-pecl', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.php-pecl was not found on galaxy.ansible.com.
 downloading role 'php-xdebug', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.php-xdebug was not found on galaxy.ansible.com.
 downloading role 'php-xhprof', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.php-xhprof was not found on galaxy.ansible.com.
 downloading role 'pimpmylog', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.pimpmylog was not found on galaxy.ansible.com.
 downloading role 'postfix', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.postfix was not found on galaxy.ansible.com.
 downloading role 'repo-remi', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.repo-remi was not found on galaxy.ansible.com.
 downloading role 'ruby', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.ruby was not found on galaxy.ansible.com.
 downloading role 'security', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.security was not found on galaxy.ansible.com.
 downloading role 'solr', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.solr was not found on galaxy.ansible.com.
 downloading role 'varnish', owned by -%20src%3A%20geerlingguy
Sorry, - src: geerlingguy.varnish was not found on galaxy.ansible.com.

doesnt install D8

**Comment by devekko** [comment]
outdated Ansible version from ppa 
https://github.com/roots/trellis/issues/181

**Comment by devekko** [comment]
updated Ansible and yml parses properly

I have to admit, I miss those Ansible role installation instructions everytime
