### ISSUE TITLE
How To enable install of modules from drupal.org 

### ISSUE THREAD

**Issue by skorasaurus** [geerlingguy/drupal-vm#1190]
Referencing https://github.com/geerlingguy/drupal-vm/issues/1163

I'm sorry for not replying and I appreciate your responses but I was still wondering how to install new modules after setting up the drupal-vm instance. Is installing them in composer not a good practice? 

(I recall reading somewhere that installing them directly through the browser is not preferred).  

My reasons are that 
I'd like to maintain a development version of a website and be able to install and remove modules without having to destroy my vagrant instance and starting over from scratch.

**Comment by geerlingguy** [comment]
@skorasaurus - I'm actually planning on doing somewhat of a tutorial on the workflow at MidCamp in a month's time... but until then—the default supported method would be something like:

  1. Build new Drupal VM instance.
  2. This creates a `drupal` folder in the Drupal VM directory.
  3. This folder contains a `composer.json` and `composer.lock`, as well as a `web` directory.
  4. To add a new module, you want to add it via Composer:
    1. You can just add the module to the list of `drupal_composer_dependencies` so it's added at the time the site is first built.
    2. You can `cd` into the `drupal` directory and run `composer require drupal/modulename:^1.0`
  5. Enable the module either using Drush or while logged into the site.

Other than that, there are still a dozen or so other ways you can manage Drupal 8 sites... but this way you can (if you want) just commit the composer files to your site repo, and not have to track all the contrib modules, core, Packagist libraries, etc.

Composer and other workflows for site management are slightly outside the purview of Drupal VM and its own documentation, though, so I'd recommend asking deeper questions on [Drupal Answers](http://drupal.stackexchange.com) or on the #drupal channel on Freenode IRC.

**Comment by geerlingguy** [comment]
> (I recall reading somewhere that installing them directly through the browser is not preferred).

And yes, this is correct—it's potentially insecure and definitely not a best practice to modify your codebase through a web browser, especially if you do it in a live environment!

Unfortunately, Drupal's own [Installing Modules](https://www.drupal.org/docs/8/extending-drupal-8/installing-modules) documentation focuses mostly on the most basic case, where you're not using Composer at all... And it's definitely a valid way to manage a site, but not necessarily the most efficient way.

See also:

  - [Use composer to build sites](https://www.drupal.org/node/2477789)
  - [Using Composer to manage Drupal site dependencies](https://www.drupal.org/docs/develop/using-composer/using-composer-to-manage-drupal-site-dependencies)

**Comment by geerlingguy** [comment]
The session in question at MidCamp: [Developing for Drupal 8 with Drupal VM](https://www.midcamp.org/session/developing-drupal-8-drupal-vm)

**Comment by skorasaurus** [comment]
Thank you very much for the detailed answer and related resources!
