### ISSUE TITLE
How to run a script after 'vagrant up' automatically

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#1194]
I need to run 'forever start /my/path/app.js' each time after doing 'vargant up'.

**Comment by geerlingguy** [comment]
There are a few things you can do to get this to happen automatically:

  - [Use a Vagrantfile.local](http://docs.drupalvm.com/en/latest/extending/vagrantfile/)
  - [Use a post-provision script/playbook to add it in](http://docs.drupalvm.com/en/latest/extending/scripts/)
  - Add a cron job (https://github.com/geerlingguy/drupal-vm/blob/4.2.1/default.config.yml#L90-L92)

**Comment by ArtuGit** [comment]
I do not see an appropriate way to run a script after `vagrant up` ,  not after provisioning.

**Comment by geerlingguy** [comment]
You can use a pre-provision script to run a script at the beginning of Ansible provisioning. Or you can modify the provisioners in a `Vagrantfile.local` (see the links in my earlier comment for docs). I don't have an example right now, but basically you should be able to inject a script or Ansible task file either before or after Drupal VM does all of its own setup.

**Comment by geerlingguy** [comment]
Ah, you mean just on `vagrant up` but not necessarily `vagrant provision`. For that, that's definitely more complicated.

**Comment by geerlingguy** [comment]
But you could still use a cron job at `@reboot`, or you could set up a systemd service unit file to run the job. Searching around for `forever boot ubuntu`, I found resources like:

  - http://stackoverflow.com/a/13388741
  - https://www.axllent.org/docs/view/nodejs-service-with-systemd/
  - https://blog.codeship.com/running-node-js-linux-systemd/

Please ask more details in a separate forum, as this isn't an issue with Drupal VM per-se, more a question of either 'how do I get a node.js app to start running on system boot', or 'how can I run specific commands when I run `vagrant up`'.

**Comment by ArtuGit** [comment]
Thank you, @geerlingguy .
It is a clear answer and now I know where it should work.
I will try.

**Comment by pavel-ruban** [comment]
@geerlingguy one of the reasons why we need such a on up script is like this: https://github.com/geerlingguy/drupal-vm/issues/1813

it annoys a lot, maybe there is more proper way to fix in xdebug context but anyway creating a file in /tmp mount point on vagrant up is quite straight forward solution, I know that you can move this file from /tmp to other place but again you need to do cron to clean it up & other things. Script on vagrant up is just handy for many dupal vm application & fixing minor issues on the fly. As you pointed I guess can be addressed by creating service, it would be nice to have some kind of setting which will create such a services automatically

**Comment by oxyc** [comment]
You can create a `Vagrantfile.local` with:

```
config.trigger.after :up do |trigger|
  trigger.name = 'Foobar'
  trigger.run_remote = {inline: "echo Foobar"}
end
```
