### ISSUE TITLE
Drush is Unable to load autoload.php

### ISSUE THREAD

**Issue by dogwolf** [geerlingguy/drupal-vm#1195]
- Bug Report

Vagrant 1.9.1
VirtualBox 5.1.14
Windows 10

### Full console output

```
TASK [geerlingguy.drush : Ensure Drush can be installed on Debian Wheezy.] *****
skipping: [drupalvm]

TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
skipping: [drupalvm]

TASK [geerlingguy.drush : Create drush symlink.] *******************************
ok: [drupalvm]

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.281308", "end": "2017-03-02 17:23:00.834570", "failed": true, "rc": 1, "start": "2017-03-02 17:23:00.553262", "stderr": "Unable to load autoload.php. Run composer install to fetch dependencies and write this file (http://docs.drush.org/en/master/install-alternative/). Or if you prefer, use the drush.phar which already has dependencies included (http://docs.drush.org/en/master/install).", "stdout": "", "stdout_lines": [], "warnings": []}
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=119  changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Full console output

Dear Sir,
I just downloaded the zip and typed the command vagrant up .. no changes, just renamed default.config.yml to config.yml

Thank you

**Comment by geerlingguy** [comment]
Please see:

  - https://github.com/geerlingguy/drupal-vm/issues/420
  - https://github.com/geerlingguy/drupal-vm/issues/326

And check on whether a `vagrant destroy` and `vagrant up` fixes the issue. Also check on what Version of Ansible you have installed (needs to be 2.2.x or later), and check on what version of PHP is installed inside the VM (`vagrant ssh` then run `php -v` to get the exact version).

**Comment by dogwolf** [comment]
Php 7.0.16-4+deb.sury.org~xenial+1
Ansible 2.2.1.0-1ppa~xenial

Re-running isn't fixing it for me.

**Comment by geerlingguy** [comment]
@dogwolf did you run `vagrant destroy`? Also, do you have something set in a config file for `drush_version` anywhere?

**Comment by geerlingguy** [comment]
Oh also, did you copy default.config.yml, or rename it? It should still be there, and then you should only put _overrides_ inside `config.yml` (so you don't even technically need to have a `config.yml` if you're not overriding anything).

**Comment by dogwolf** [comment]
Hi, after some vagrant destroy and up finally the problem disappear and all seems to work nicely.
Thank you

**Comment by geerlingguy** [comment]
Great! I'll close this for now. It could be there was some composer error during the initial install, that's my best guess. Then Drush gets stuck in some weird state where it's not completely installed.
