### ISSUE TITLE
Provisioning a prod server; user's password not working

### ISSUE THREAD

**Issue by SummittDweller** [geerlingguy/drupal-vm#1196]
### Issue Type
 - Documentation Report
I picked Documentation Report because I doubt this is a bug; more likely something I got wrong in translation.

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.14r112924
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (Sierra 10.12.3)

### Full console output
https://gist.github.com/SummittDweller/85db7272ad2ed4bc8a4eac1bdb51bd56

### Summary
Attempting to deploy a working drupal-vm instance to an Ubuntu 16.04 LTS bare-bones server with this...
```
ansible-playbook -vvvv -b -K -i prod/inventory prod/bootstrap/init.yml -e "ansible_ssh_user=mark" 
```
...per the documentation in http://docs.drupalvm.com/en/latest/other/production/.  Latest console output is in my gist with some things obfuscated and with some of my prod config files included.

I don't have root access to this server, but 'mark' is (or was) a sudoer and I have a working SSH key in place.  It appears that an initial SSH connection is established, but later on I'm getting a sudo failure.  What's really odd is that the password I set previously for 'mark' is NO LONGER VALID.  So now I can't even sudo from a command line on this server, although I can still login since my key is intact. 

This is the first time I've tried to push a working drupal-vm configuration to production so I haven't a clue what I'm doing wrong.

Thanks.

**Comment by geerlingguy** [comment]
This could be a bug... but I'll have to do a little more digging. Just marking with question label for now.

**Comment by SummittDweller** [comment]
Thanks.  My host/provider restored the server so I have sudo access again.  I've created an additional sudoer account too, just in case.  He also informed me that the original configuration did not have a 'root' user defined, just 'mark'.  He has since created 'root' and I am going to try provisioning with Ansible again.  I'll post the result when I can.

**Comment by SummittDweller** [comment]
Rats...  same result as before.  And the 'mark' account password has evidently been changed again?

mark@mm3:~$ passwd
Changing password for mark.
(current) UNIX password: 
passwd: Authentication token manipulation error
passwd: password unchanged

**Comment by SummittDweller** [comment]
Now that the box has a 'root' account, and I have access to it, I copied my SSH key to root and tried all of this again but running as root, no --become or sudo.  The script ran to completion with no errors.  Now to try provisioning!  Wish me luck.

**Comment by SummittDweller** [comment]
So I reset my inventory file to run everything as 'mark' and tried to provision.  It failed, said my password for 'mark' was wrong again?  The init script must be changing or removing that?

Anyway, I logged in as 'root' and reset mark's password and added the account back to sudo.  Restarted the provisioning and it's running now...so far so good.  Current TASK is 'Get software for Python-based control.'

**Comment by SummittDweller** [comment]
And the provisioning ran without a hitch.  I'm off to test the server configuration now.

**Comment by geerlingguy** [comment]
@SummittDweller - Thanks for all the feedback, and sorry I couldn't take a look earlier—hope it goes well, and please open issues for bugs you encounter, especially if there are bugs in the documentation!

**Comment by FinBoWa** [comment]
To quickly point out to @SummittDweller 

https://gist.github.com/SummittDweller/85db7272ad2ed4bc8a4eac1bdb51bd56#file-gistfile1-txt-L73

you have the `extra_security_enabled: true` enabled so it will install this role https://github.com/geerlingguy/ansible-role-security

That might explain few of the issues you faced if you check what its used for.
