### ISSUE TITLE
What is the username and password to log into the VM via VirtualBox UI?

### ISSUE THREAD

**Issue by reubenjn** [geerlingguy/drupal-vm#1203]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.2
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found
```

### Your OS

 - **Windows** (10)

### Summary

I just ran "vagrant up". When it was done I went to VirtualBox and ran drupalvm.dev. When it got to the login screen, I was unable to log in. I tried admin/admin, admin/<blank pw>, drupal/drupal, and various other combinations. Every time it says "Login incorrect". (Picture attached.)
![loginnotworking](https://cloud.githubusercontent.com/assets/7150395/23729150/408ed55e-042e-11e7-82ff-97a0b3c01e3d.PNG)

Did I do something wrong in the setup?

**Comment by geerlingguy** [comment]
@reubenjn - The `admin`/`admin` login is for the Drupal site that would be set up if you allow Drupal VM to install the site (assuming you're using the default username and password).

To log into the VM itself, you can either use `vagrant ssh` (this will do all the login stuff for you), or if you want to open the VM from within VirtualBox and login using the UI, it's `vagrant`/`vagrant` (that's the default Vagrant account).

**Comment by geerlingguy** [comment]
Marking as fixed for now—please let me know if there are any other questions you had, thanks!

**Comment by ajayghatt8888** [comment]
Ajay

**Comment by mzejcom** [comment]
Appreciated

**Comment by Tovervlag** [comment]
helped me too thanks.
