### ISSUE TITLE
Mounting NFS shared folders fails on Ubuntu 16.04 host

### ISSUE THREAD

**Issue by petiar** [geerlingguy/drupal-vm#1204]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.12r112440
-bash: ansible: command not found
```

### Your OS

 - **macOS** (version)

### Full console output

```
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 192.168.88.1:/Users/petiar/Sites/1843.vm /var/www/drupalvm
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/var/www/drupalvm
fi
else
exit $result
fi


Stdout from the command:



Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
mount.nfs: Connection timed out
```

### Summary

It just stopped working one day. No change in config.yml at all in recent couple of weeks, but today I just could not make vagrant up. I can't make provision either, getting some error saying some playbook missing... How could this happen???

**Comment by petiar** [comment]
It's the same with clean DrupalVM installation. This ruined my VM completely, I can't bring it up, therefore this is **critical**.

**Comment by FinBoWa** [comment]
@petiar is the box centos 7? If so thats vagrant 1.9.1 issue with it; nothing to do with DRUPAL VM. 

Upgrade vagrant to 1.9.2 or go back to 1.9.0

**Comment by geerlingguy** [comment]
@petiar - What @FinBoWa said—if you're using CentOS 7 then it's definitely the Vagrant bug.

**Comment by geerlingguy** [comment]
Also, another alternative is to set the synced folder type to `""` or `"rsync"` or some other option Vagrant supports (instead of `nfs`) if you still can't get it working.

**Comment by petiar** [comment]
It's Ubuntu:
`Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)`

**Comment by geerlingguy** [comment]
@petiar - Did you try rsync at least, or an empty string there? I just want to see if anything else will work. Also, can you still upgrade to Vagrant 1.9.2 and see if that makes a difference. Also upgrade to either VirtualBox 5.1.14 or 5.1.16.

**Comment by d70rr3s** [comment]
Hi, I getting the same here but not the

> mesg: ttyname failed: Inappropriate ioctl for device

Only timeout

### Your Environment
Vagrant 1.9.2
VirtualBox 5.1.16
Ansible 2.2.1
Box: 14.04-1.1.8

### Your OS
Ubuntu 16.04

I changed the synced method to "rsync" and it's working now (slowly but working).

**Comment by geerlingguy** [comment]
@d70rr3s - ah, yes, that can definitely have an effect. If you have `ufw` enabled, it can mess with NFS's ability to share to internal VMs. @petiar can you see if your firewall rules might be blocking NFS from allowing the mount?

**Comment by John-B** [comment]
I encountered a known problem mounting NFS with Vagrant 1.9.2 + VirtualBox 5.1.16. My error message was different. The workaround top answer [here](http://stackoverflow.com/questions/42074246/vagrant-error-unable-to-mount-virtualbox-shared-folders-guest-additions-vboxs) fixed it for me.

**Comment by oxyc** [comment]
@petiar are you still having this issue? Have you tried upgrading to Vagrant 1.9.2?

**Comment by geerlingguy** [comment]
Closing this issue for now; please let me know if you're still having the issue.
