### ISSUE TITLE
Globally required packages task fails, says ext-curl is required

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1205]
### Your Environment

```
5.1.16r113841
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** 10.12.1

### Full console output

`TASK [geerlingguy.composer : Install configured globally-required packages.] ***
failed: [velir] (item={u'release': u'^0.3', u'name': u'hirak/prestissimo'}) => {"changed": true, "cmd": ["/usr/bin/composer", "global", "require", "hirak/prestissimo:^0.3", "--no-progress"], "delta": "0:00:03.456421", "end": "2017-03-09 19:05:18.580233", "failed": true, "item": {"name": "hirak/prestissimo", "release": "^0.3"}, "rc": 2, "start": "2017-03-09 19:05:15.123812", "stderr": "Changed current directory to /home/vagrant/.composer\n./composer.json has been created\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - hirak/prestissimo 0.3.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.\n    - hirak/prestissimo 0.3.4 requires ext-curl * -> the requested PHP extension curl is missing from your system.\n    - hirak/prestissimo 0.3.3 requires ext-curl * -> the requested PHP extension curl is missing from your system.\n    - hirak/prestissimo 0.3.2 requires ext-curl * -> the requested PHP extension curl is missing from your system.\n    - hirak/prestissimo 0.3.1 requires ext-curl * -> the requested PHP extension curl is missing from your system.\n    - hirak/prestissimo 0.3.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.\n    - Installation request for hirak/prestissimo ^0.3 -> satisfiable by hirak/prestissimo[0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.3.4, 0.3.5].\n\n  To enable extensions, verify that they are enabled in your .ini files:\n    - /etc/php/7.1/cli/php.ini\n    - /etc/php/7.1/cli/conf.d/10-opcache.ini\n    - /etc/php/7.1/cli/conf.d/10-pdo.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu_bc.ini\n    - /etc/php/7.1/cli/conf.d/20-calendar.ini\n    - /etc/php/7.1/cli/conf.d/20-ctype.ini\n    - /etc/php/7.1/cli/conf.d/20-exif.ini\n    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.1/cli/conf.d/20-ftp.ini\n    - /etc/php/7.1/cli/conf.d/20-gettext.ini\n    - /etc/php/7.1/cli/conf.d/20-iconv.ini\n    - /etc/php/7.1/cli/conf.d/20-json.ini\n    - /etc/php/7.1/cli/conf.d/20-phar.ini\n    - /etc/php/7.1/cli/conf.d/20-posix.ini\n    - /etc/php/7.1/cli/conf.d/20-readline.ini\n    - /etc/php/7.1/cli/conf.d/20-shmop.ini\n    - /etc/php/7.1/cli/conf.d/20-sockets.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini\n    - /etc/php/7.1/cli/conf.d/20-yaml.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.\n\nInstallation failed, deleting ./composer.json.", "stdout": "", "stdout_lines": [], "warnings": []}`

### Summary

Fresh download of 4.2.1, this task fails every time. Cannot get VM to provision.

PHP in config.yml:

```
vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs

php_version: "5.6"
php_memory_limit: "256M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php5 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ drupalvm_user }}/.composer"
composer_home_owner: "{{ drupalvm_user }}"
composer_home_group: "{{ drupalvm_user }}"
composer_global_packages:
  - { name: hirak/prestissimo, release: '^0.3' }
```

**Comment by kevinquillen** [comment]
I ssh'ed into the machine, and even though I am specifying the PHP version to be 5.6, this is the output in the box:

```
vagrant@local:~$ php --version
PHP 7.1.2-4+deb.sury.org~trusty+1 (cli) (built: Mar  2 2017 13:23:06) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2-4+deb.sury.org~trusty+1, Copyright (c) 1999-2017, by Zend Technologies
```

**Comment by kevinquillen** [comment]
Destroying and re-upping had the same result. Can't install 5.6.

**Comment by geerlingguy** [comment]
@kevinquillen - Can you post your full config.yml?

**Comment by geerlingguy** [comment]
Also, the only way PHP 7.1 can be installed (at this time, at least), is if you'd manually set `php_version: "7.1"` at some point, AFAICT? Do you have a `local.config.yml` as well?

The default version is still 7.0: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L244

**Comment by kevinquillen** [comment]
Nope, this is brand new download of 4.2.1. I set up the file before doing `vagrant up`.

Full file:

`
---
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1404, geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: local.velir.com
vagrant_machine_name: velir
vagrant_ip: 0.0.0.0

# Allow Drupal VM to be accessed via a public network interface on your host.
# Vagrant boxes are insecure by default, so be careful. You've been warned!
# See: https://docs.vagrantup.com/v2/networking/public_network.html
vagrant_public_ip: ""

# A list of synced folders, with the keys 'local_path', 'destination', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares). See
# http://docs.drupalvm.com/en/latest/extras/syncing-folders/ for more info.
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ../../
    destination: /var/www
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2

# Minimum required versions.
drupalvm_vagrant_version_min: '1.8.6'
drupalvm_ansible_version_min: '2.2'

# Force use of ansible_local provisioner, even if Ansible is installed on host.
force_ansible_local: false

# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: apache

# The database system to use. Can be either 'mysql' or 'pgsql'.
drupalvm_database: mysql

# Set this to 'false' if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
build_makefile: false
drush_makefile_path: "{{ config_dir }}/drupal.make.yml"
drush_make_options: "--no-gitinfofile"

# Set 'build_makefile' to 'false' and this to 'true' if you are using a
# composer based site deployment strategy.
build_composer: false
drupal_composer_path: "{{ config_dir }}/drupal.composer.json"
drupal_composer_install_dir: "/var/www/drupalvm/drupal"
drupal_composer_dependencies:
  - "drupal/devel:1.x-dev"

# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
# are using Composer's create-project as a site deployment strategy.
build_composer_project: false
drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

# Required Drupal settings.
drupal_core_path: "/var/www/docroot"
drupal_db_user: drupal
drupal_db_password: drupal
drupal_db_name: drupal

# Settings for installing a Drupal site if 'install_site:' is 'true'.
drupal_major_version: 7
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin

# Additional arguments or options to pass to `drush site-install`.
drupal_site_install_extra_args: []

# Cron jobs are added to the vagrant user's crontab. Keys include name
# (required), minute, hour, day, weekday, month, job (required), and state.
drupalvm_cron_jobs: []

# Drupal VM automatically creates a drush alias file in your ~/.drush folder if
# this variable is 'true'.
configure_drush_aliases: true

# Helper variable to configure the PHP-FPM connection for each Apache
# VirtualHost in the `apache_vhosts` list.
apache_vhost_php_fpm_parameters: |
    <FilesMatch \.php$>
      SetHandler "proxy:fcgi://{{ php_fpm_listen }}"
    </FilesMatch>

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
# View the geerlingguy.apache Ansible Role README for more options.
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

apache_packages_state: latest
apache_remove_default_vhost: true
apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load

# Nginx hosts. Each site will get a server entry using the configuration defined
# here. Set the 'is_php' property for document roots that contain PHP apps like
# Drupal.
nginx_hosts:
  - server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "adminer.{{ vagrant_hostname }}"
    root: "{{ adminer_install_dir }}"
    is_php: true

  - server_name: "xhprof.{{ vagrant_hostname }}"
    root: "{{ php_xhprof_html_dir }}"
    is_php: true

  - server_name: "pimpmylog.{{ vagrant_hostname }}"
    root: "{{ pimpmylog_install_dir }}"
    is_php: true

  - server_name: "{{ vagrant_ip }} dashboard.{{ vagrant_hostname }}"
    root: "{{ dashboard_install_dir }}"
    is_php: true

nginx_remove_default_vhost: true
nginx_ppa_use: true

# MySQL databases and users.
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci

mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_password }}"
    priv: "{{ drupal_db_name }}.*:ALL"

# PostgreSQL databases and users.
postgresql_databases:
  - name: "{{ drupal_db_name }}"

postgresql_users:
  - name: "{{ drupal_db_user }}"
    password: "{{ drupal_db_password }}"
    db: "{{ drupal_db_name }}"
    priv: "ALL"

# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  #- drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - upload-progress
  #- varnish
  - xdebug
  # - xhprof

# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite

# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false

drush_version: "8.x"
drush_keep_updated: true
drush_composer_cli_options: "--prefer-dist --no-interaction"

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
firewall_log_dropped_packets: false
firewall_disable_firewalld: true
firewall_disable_ufw: true

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.6"
php_memory_limit: "256M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php5 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

composer_path: /usr/bin/composer
composer_home_path: "/home/{{ drupalvm_user }}/.composer"
composer_home_owner: "{{ drupalvm_user }}"
composer_home_group: "{{ drupalvm_user }}"
composer_global_packages: []
  #- { name: hirak/prestissimo, release: '^0.3' }

# Run specified scripts before or after VM is provisioned. Path is relative to
# the `provisioning/playbook.yml` file.
pre_provision_scripts: []
post_provision_scripts: []
  # - "../examples/scripts/configure-solr.sh"

# MySQL Configuration.
mysql_root_password: root
mysql_slow_query_log_enabled: true
mysql_slow_query_time: 2
mysql_wait_timeout: 300
adminer_install_filename: index.php

# Node.js configuration (if enabled above).
# Valid examples: "0.10", "0.12", "4.x", "5.x".
nodejs_version: "0.12"
nodejs_npm_global_packages: []
nodejs_install_npm_user: "{{ drupalvm_user }}"
npm_config_prefix: "/home/{{ drupalvm_user }}/.npm-global"

# Ruby Configuration (if enabled above).
ruby_install_gems_user: "{{ drupalvm_user }}"
ruby_install_gems: []

# Varnish Configuration (if enabled above).
varnish_listen_port: "81"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "80"

# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_port: "10000"

# Solr Configuration (if enabled above).
solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"

# Selenium configuration.
selenium_version: 2.53.0

# Other configuration.
dashboard_install_dir: /var/www/dashboard
known_hosts_path: ~/.ssh/known_hosts
#ssh_home: "{{ drupal_core_path }}"
`

**Comment by kevinquillen** [comment]
Hm. Destroyed again, and this time I got a different error:

```
TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
fatal: [velir]: FAILED! => {"changed": true, "cmd": "/usr/bin/composer install --prefer-dist --no-interaction", "delta": "0:00:00.363649", "end": "2017-03-09 20:27:06.899363", "failed": true, "rc": 2, "start": "2017-03-09 20:27:06.535714", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for phpunit/phpunit 4.8.31 -> satisfiable by phpunit/phpunit[4.8.31].\n    - phpunit/phpunit 4.8.31 requires ext-dom * -> the requested PHP extension dom is missing from your system.\n\n  To enable extensions, verify that they are enabled in your .ini files:\n    - /etc/php/7.1/cli/php.ini\n    - /etc/php/7.1/cli/conf.d/10-opcache.ini\n    - /etc/php/7.1/cli/conf.d/10-pdo.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu.ini\n    - /etc/php/7.1/cli/conf.d/20-apcu_bc.ini\n    - /etc/php/7.1/cli/conf.d/20-calendar.ini\n    - /etc/php/7.1/cli/conf.d/20-ctype.ini\n    - /etc/php/7.1/cli/conf.d/20-exif.ini\n    - /etc/php/7.1/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.1/cli/conf.d/20-ftp.ini\n    - /etc/php/7.1/cli/conf.d/20-gettext.ini\n    - /etc/php/7.1/cli/conf.d/20-iconv.ini\n    - /etc/php/7.1/cli/conf.d/20-json.ini\n    - /etc/php/7.1/cli/conf.d/20-phar.ini\n    - /etc/php/7.1/cli/conf.d/20-posix.ini\n    - /etc/php/7.1/cli/conf.d/20-readline.ini\n    - /etc/php/7.1/cli/conf.d/20-shmop.ini\n    - /etc/php/7.1/cli/conf.d/20-sockets.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.1/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.1/cli/conf.d/20-tokenizer.ini\n    - /etc/php/7.1/cli/conf.d/20-yaml.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by geerlingguy** [comment]
> phpunit/phpunit 4.8.31 requires ext-dom

Means that `php5.6-xml` wasn't being installed...

Now, if you go in and run `php -v` does it still say 7.1?

**Comment by geerlingguy** [comment]
It looks like it's still looking around in 7.1 stuff. I'm going to copy your `config.yml` and see if I can reproduce this.

**Comment by kevinquillen** [comment]
Yep:

```
PHP 7.1.2-4+deb.sury.org~trusty+1 (cli) (built: Mar  2 2017 13:23:06) ( NTS
)
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2-4+deb.sury.org~trusty+1, Copyright (c)
1999-2017, by Zend Technologies
```

**Comment by geerlingguy** [comment]
@kevinquillen - Could there be _any_ other changes? E.g. do you have a `Vagrantfile.local`, or a `local.config.yml`, or a `vagrant.config.yml`, or anything like that?

I just copied and pasted your `config.yml` contents into a new `config.yml` file in a fresh download of Drupal VM 4.2.1 and ran `vagrant up`, and it completed successfully. Logging in, I ran `php -v` and it gave:

```
vagrant@local:~$ php -v
PHP 5.6.30-7+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by geerlingguy** [comment]
...or a prod.config.yml or anything other than your `config.yml` and `default.config.yml`? Also, is this a direct download of Drupal VM, or did you maybe use Composer to include it somehow, or is it part of a BLT project?

**Comment by kevinquillen** [comment]
Nope, downloaded right from github. I don't see any other config.yml files.

Let me try to start fresh.

**Comment by kevinquillen** [comment]
This time I got a new error:

```
==> velir: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,udp 10.20.1.1:/Users/kevinquillen /var/www
result=$?
if test $result -eq 0; then
if test -x /sbin/initctl && command -v /sbin/init && /sbin/init 2>/dev/null --version | grep upstart; then
/sbin/initctl emit --no-wait vagrant-mounted MOUNTPOINT=/var/www
fi
else
exit $result
fi


Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 10.20.1.1:/Users/kevinquillen
```

So I checked /etc/exports and this entry is odd:

```
# VAGRANT-BEGIN: 501 c0706a1f-645d-42ba-97e7-1a15fc8e948f
"/Users/kevinquillen" "/Users/kevinquillen/.Trash/drupalvm" "/Users/kevinquillen/.vagrant.d/cache/geerlingguy/ubuntu1404" 10.20.1.3 -alldirs -mapall=501:20
# VAGRANT-END: 501 c0706a1f-645d-42ba-97e7-1a15fc8e948f
```

So I destroyed the VM, removed those lines manually from exports, downloaded and ran vagrant up again. The error about mount.nfs persists. Vagrant version is 1.9.2.

**Comment by kevinquillen** [comment]
Wow, so odd. 

So I cleared the exports entry, destroyed the busted VM, deleted the folder, added 4.2.1 back in and my config.yml. _This time_ I force quit **iTerm2** and rebooted the app. VM ran through and installed, no problem.

**Comment by kevinquillen** [comment]
```
vagrant@local:~$ php -v
PHP 5.6.30-7+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

Either iTerm2 has some sort of session caching or I just need to head home for the day. It didn't work at all until I rebooted iTerm2.

**Comment by geerlingguy** [comment]
You're the second person in the past two weeks that has reported very weird (and totally inexplicable) behaviors using Vagrant (not just Drupal VM) with iTerm2. Makes me smug about using Terminal :P

**Comment by kevinquillen** [comment]
Yeah, I have regular Terminal/zsh setup on my home Macbook Pro and not my
work one. I just need to bring in my configs and remove iTerm.

So weird!

**Comment by charginghawk** [comment]
I also encountered this issue. I also don't know what was the direct cause, but it started working after I restarted the computer and used vanilla Terminal instead of iTerm2.

**Comment by keithstewart23** [comment]
I don't think using Terminal is necessarily the solution. I use Terminal and I get exactly the same message.
