### ISSUE TITLE
Bootstrap pimpmylog with sane defaults

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#121]
1. Add in Apache, MySQL, and PHP log files
2. Create default admin account

**Comment by geerlingguy** [comment]
Can you please file this in https://github.com/geerlingguy/ansible-role-pimpmylog?

**Comment by nerdstein** [comment]
Dunzo; https://github.com/geerlingguy/ansible-role-pimpmylog/issues/1
