### ISSUE TITLE
Some new Vagrant builds seem excessively slow (as of March 10, 2017)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1210]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.1.16r113841
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.3)

### Summary

@grasmash mentioned something about slow local builds this morning... and since I had just done some testing last night (for the 4.3.0 release) and didn't have any issues, I dismissed it initially.

Then, later in the day when I ran through all my base boxes and regenerated them with VirtualBox 5.1.16 Guest Additions (they're all up to date now), I found that I, too, was having some inexplicable slowness—but only with PHP-related operations.

I checked, and the docroot was still mounted via NFS (so that doesn't _seem_ like it would be the culprit), and I used `top`, `iotop`, `iftop`, and `atop` to see if there was anything obvious causing the slowdown. But there wasn't.

Of note—so far I can only replicate this issue with sites that are built via Acquia BLT. My other vanilla Drupal 8 sites built just with Drupal VM or otherwise don't seem to be affected...

**Comment by geerlingguy** [comment]
Scratch that... it seems things are pretty slow on a fresh Ubuntu 16.04 build today as well. I might compare to a debian8 or centos7 build and see if it's Vagrant, the config, or something else... this seems highly suspicious, like a package install or actual Ubuntu system update that happened in the past day is causing this major slowdown.

**Comment by geerlingguy** [comment]
As an example, the entire provisioning is _super_ fast, but when it gets to anything PHP/Composer/Drupal related (e.g. `geerlingguy.drupal : Install dependencies with composer require.`), it gets _really_ slow. And this affects 4.3.0, as well as at least 4.2.1, etc. (so it's not any recent change).

Of note: the main box where I first saw this was just peachy yesterday, and I had rebuilt it about four times yesterday. I rebuilt it once a few hours ago, and since then everything PHP-related is about 5x slower.

I _did_ upgrade to VirtualBox 5.1.16 today... that's the only other variable. I'll check if downgrading back to 5.1.14 makes this problem go away. Maybe 5.1.16 is horribly un-good.

**Comment by geerlingguy** [comment]
Some more data points. After enabling Tideways/XHProf following [this guide](TODO):

  - XHProf dashboard itself loads instantly, leading me to believe it's something Drupal-codebase-related, maybe.
  - D8 uncached standard install page load is taking **11**s!
  - The first 10 or so function calls (all around .7-1s long) were file-related.
  - Callgraph is attached

![callgraph php](https://cloud.githubusercontent.com/assets/481677/23816825/797ecb1c-05b4-11e7-85e3-7372466df784.png)

This screams of a filesystem issue to me... I wonder if VirtualBox 5.1.16 breaks NFS somehow?

**Comment by geerlingguy** [comment]
So... I wonder if it might be related to this bugfix in VirtualBox: https://www.virtualbox.org/ticket/16404

**Comment by geerlingguy** [comment]
Might be: https://github.com/mitchellh/vagrant/issues/8359

Also likely related: https://github.com/geerlingguy/drupal-vm/issues/1202

**Comment by geerlingguy** [comment]
Trying VirtualBox 5.1.14 now, exact same configs.

**Comment by grasmash** [comment]
I did not upgrade anything apart from Drupal VM,  I found that there is a considerable recent increase in time for PHP operations. So, I would discount versions of VirtualBox and Vagrant as possible causes.

**Comment by geerlingguy** [comment]
@grasmash - Yeah, one other thing I'm checking on now: what box version do you have? E.g. run `vagrant box list` and see what version of the 1404 box is installed.

It seems it _could_ be related to the 1.1.8 box version... but probably not.

**Comment by geerlingguy** [comment]
On a known good computer:

```
Welcome to Ubuntu 14.04.5 LTS (GNU/Linux 3.13.0-110-generic x86_64)

$ php -v
PHP 5.6.30-4+deb.sury.org~trusty+1 (cli) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

$ sudo mount
192.168.88.1:/Users/jgeerling/Sites/acquia/beagov on /var/www/beagov type nfs (rw,vers=3,udp,addr=192.168.88.1)
192.168.88.1:/Users/jgeerling/Sites/acquia/beagov on /vagrant type nfs (rw,vers=3,udp,addr=192.168.88.1)
192.168.88.1:/Users/jgeerling/.vagrant.d/cache/geerlingguy/ubuntu1404 on /tmp/vagrant-cache type nfs (rw,vers=3,udp,addr=192.168.88.1)

# IOZone benchmarks.
# See: http://www.pidramble.com/wiki/benchmarks/microsd-cards
4K rand read: 23906
4K rand write: 13354
```

**Comment by geerlingguy** [comment]
Adding on to the weird factor—one of my VMs was running slow through all my testing (on 5.1.16 and 5.1.14), but after yet another `vagrant destroy -f && vagrant up`, now it's running just fine, like nothing ever happened.

However, another build (vanilla Drupal VM) is still sluggish. Results from that VM:

```
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-62-generic x86_64)

$ php -v
PHP 7.1.2-4+deb.sury.org~xenial+1 (cli) (built: Mar  2 2017 10:39:59) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.1.2-4+deb.sury.org~xenial+1, Copyright (c) 1999-2017, by Zend Technologies

192.168.88.1:/Users/jeff.geerling/Sites/drupalvm on /var/www/drupalvm type nfs (rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.88.1,mountvers=3,mountport=702,mountproto=udp,local_lock=none,addr=192.168.88.1)
192.168.88.1:/Users/jeff.geerling/Dropbox/Development/GitHub/drupal-vm on /vagrant type nfs (rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.88.1,mountvers=3,mountport=702,mountproto=udp,local_lock=none,addr=192.168.88.1)

# IOZone benchmarks.

```

One thing to note—there's a heck of a lot more going on with the NFS mounts in the slower machine...

Compare:

```
# Faster VM:
rw,vers=3,udp,addr=192.168.88.1

# Slower VM:
rw,relatime,vers=3,rsize=8192,wsize=8192,namlen=255,hard,proto=udp,timeo=11,retrans=3,sec=sys,mountaddr=192.168.88.1,mountvers=3,mountport=702,mountproto=udp,local_lock=none,addr=192.168.88.1

**Comment by geerlingguy** [comment]
And checking across multiple VMs, it seems like all the ones that are operating normally have the same settings for the NFS mounts.

I'm going to try remounting manually with the simpler set of options maybe and see if that makes a difference?

**Comment by geerlingguy** [comment]
That might just be something with Ubuntu 16.04 vs 14.04. This is puzzling.

**Comment by geerlingguy** [comment]
I'm also going to risk upgrading the current known-good VM internally (`sudo apt-get update && sudo apt-get upgrade`) and see if that bumps a package...

```
The following packages will be upgraded:
  dh-python google-chrome-stable krb5-locales libbsd0 libcups2 libedit2
  libgeoip1 libgssapi-krb5-2 libk5crypto3 libkrb5-3 libkrb5support0
  libpam-systemd libsystemd-daemon0 libsystemd-login0 libtiff5 libudev1
  linux-libc-dev linux-source-3.13.0 openssl php-common php5.6 php5.6-bz2
  php5.6-cli php5.6-common php5.6-curl php5.6-dev php5.6-fpm php5.6-gd
  php5.6-imap php5.6-json php5.6-mbstring php5.6-mcrypt php5.6-mysql
  php5.6-opcache php5.6-readline php5.6-sqlite3 php5.6-xml systemd-services
  udev
```

Full output: https://gist.github.com/geerlingguy/5d0e66e4c6c3a2d5243569674dd3bd8a

**Comment by geerlingguy** [comment]
Even after the `apt-get upgrade`, the VM is running quite well under `geerlingguy/ubuntu1404` version 1.1.7.

So I'm going to update the Vagrant box itself to 1.1.8 and see if _that's_ the difference.

**Comment by geerlingguy** [comment]
I just ran `blt local:refresh`, which normally takes 2 or so minutes on this computer, and it took a little over 2 minutes.

So I can rule out the base box version (none of the versions tested had this issue on this computer). I just noticed I'm still on Vagrant 1.9.1 on this computer though too... hmm.

**Comment by geerlingguy** [comment]
Just destroyed the VM, installed Vagrant 1.9.2, then rebuilt and ran again. Just over 2 minutes.

Maybe it's the computer?? This is quite puzzling.

**Comment by geerlingguy** [comment]
Trying a reboot now. I haven't restarted since beginning debugging earlier today... stranger things have happened.

**Comment by geerlingguy** [comment]
Reboot has not helped. I'm trying to see if there are _any_ other differences between these workstations—they're both kept almost identically in sync, and the only major difference is one is a 2015 Retina MBP, the other is a 2016...

**Comment by geerlingguy** [comment]
At this point, the only substantial difference I can think of is the computer where things are slow had 5.1.16 installed at one point (though I downgraded to 5.1.14). I haven't upgraded the other computer at all yet—it's still on 5.1.14.

But that just seems too outlandish. I'll have to do some more testing later. Maybe next week.

**Comment by geerlingguy** [comment]
Updated the title. This seems to be computer-specific, and so far the only data I have comes from three different Macs.

**Comment by geerlingguy** [comment]
Just like that... today I rebuilt my VMs yet again, and there is no sign of slowdown whatsoever. No clue what caused the issues last week, but they seem to be resolved.

@grasmash - Can you do a `vagrant destroy` and `vagrant up` again and see if things are speedy again?

I wonder if some upstream Ubuntu package was breaking NFS or causing some other filesystem issue...?

Or it could be that somehow some ghost from VirtualBox 5.1.16 snuck in and screwed things up temporarily, and after a few days, it was cleaned up (temp file somewhere?).

I'll leave this open for now; apparently many Windows users have been having issues from Vagrant 5.1.16 too, with NFS mounts.

**Comment by oniric85** [comment]
Following this because I have a similar slowness problem but using a CentOS 7 box on a Windows host with Virtualbox shared folders. It happened out of the blue..

**Comment by geerlingguy** [comment]
@oniric85 - What version of VirtualBox are you running?

**Comment by geerlingguy** [comment]
I can also confirm that 5.1.17 fixes the issue for me, so consider either downgrading to 5.1.14, or upgrading to 5.1.17 (or .18 whenever it's released). .17 is a preview release—you have to scroll down on the VirtualBox downloads page to get it.

**Comment by oniric85** [comment]
@geerlingguy I'm running Virtualbox 5.1.16 but was running 5.1.10 before and had the same issue. I've only upgraded as an attempt to solve the problem but it did not work. I'll try 5.1.17 now!

**Comment by oniric85** [comment]
@geerlingguy Updating to Virtualbox 5.1.17 fixed the shared folders problem introduced by 5.1.16 but the machine is still super slow. Seems like the cause is something else. Did you completely uninstall previous virtualbox?

**Comment by oniric85** [comment]
@geerlingguy Updated also to Vagrant 1.9.2, same problem.

**Comment by geerlingguy** [comment]
@oniric85 - I wonder if it could be something else then. Have you done a full `vagrant destroy` then built a new VM from scratch? And are you on Windows or another OS?

**Comment by oniric85** [comment]
@geerlingguy yes, I've tried to rebuild the machine a few times already with no success. I'm on a Windows 10 host.

**Comment by agoradesign** [comment]
@oniric85 Are you using Avast AV software? A few weeks ago, I observed a dramatic slow down of my VMs. After trying around and researching, I've found that Avast was to blame, to be more precise their hardware virtualization option was the problem. I turned it off, then it was better. Interestingly, on another Windows 10 computer with Avast, this isn't a problem at all.

I've just updated to Virtualbox 5.1.18, Vagrant 1.9.2 and started a fresh DrupalVM (on 4.3.1) and everything worked fine. I'd even say that it is running faster than it used to be on older versions

**Comment by oniric85** [comment]
@agoradesign OMG, that was it! I've disabled the assisted hardware virtualization option (Settings -> Troubleshooting problems) and my machine are now in perfect shape, thank you for pointing this out! I've wasted a lot of time over this issue, I had the feeling that Avast could be the cause and I disabled the protection but probably that option was still active somehow. Good catch!

**Comment by geerlingguy** [comment]
@agoradesign @oniric85 - Wow, good catch! Since I've not had to use a virus scanner for a few years, I rarely think about that being a possible cause for these kinds of slowdowns.

Now that it seems we have some resolution here, I'm going to close out this ticket (especially since VirtualBox 5.1.18 is out and fixes all issues on my computers now!).

**Comment by stuartcusackie** [comment]
Disabling the hardware virtualization option on Avast made a big difference to my vagrant speeds on Windows 10.  Turn on Avast shields did nothing

Thank you! @oniric85

**Comment by helit** [comment]
@agoradesign that solved my issue too. Uninstalled Avast and now it's running smoothly again! Thank you so much!
