### ISSUE TITLE
Drupal codebase doesn't seem to appear on host with VirtualBox 5.1.16

### ISSUE THREAD

**Issue by brentratliff** [geerlingguy/drupal-vm#1218]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.1.16r113841
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - macOS Sierra

### Full console output
NA

### Summary

I think I'm losing my mind.  I used 'drupal_build_composer_project: true' and can't find the drupal codebase anywhere in my local filesystem.  I can vagrant ssh in and see it in the vm.  Site works fine.

**Comment by geerlingguy** [comment]
@brentratliff - I wonder if it might be NFS issues. See https://github.com/geerlingguy/drupal-vm/issues/1210 and https://github.com/mitchellh/vagrant/issues/8359

It might just be that VirtualBox 5.1.16 is causing the issue. Try downloading 5.1.14, and installing that older version. That may be it.

Another alternative is to switch the vagrant synced folder `type` to `rsync`. That works for me (though there are some other annoyances inherent with that type).

**Comment by geerlingguy** [comment]
@brentratliff - It's definitely not you :)

Please either downgrade to VirtualBox 5.1.14, or upgrade to the 5.1.17 preview release. This should be resolved once 5.1.18 comes out!

**Comment by brentratliff** [comment]
Thanks for the quick reply. 5.1.18 fixed it and another issue that caused 5 local sync attempt failures previously.  The good news is that maybe I'm not crazy after all.

**Comment by geerlingguy** [comment]
@brentratliff - Excellent! Glad they could release 5.1.18 so quickly. I'm building new base box versions with guest additions for 5.1.18 now.
