### ISSUE TITLE
No package matching php error while installing Debian box, whichever php version set

### ISSUE THREAD

**Issue by visages** [geerlingguy/drupal-vm#1219]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.1.16r113841
ansible is not installed (windows)
```
### Your OS

 - **Windows 7 SP1** 

### Full console output

**Command** : `$ vagrant up --debug`
**Config.yml** : 
```
---
vagrant_box: geerlingguy/debian8
vagrant_hostname: drupalvm2.dev
vagrant_machine_name: drupalvm2
vagrant_ip: 192.168.88.89
php_version: "5.6"
```
**Relevant error :** 

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
INFO interface: info: failed: [drupalvm2] (item=[u'php5.6', u'php5.6-apcu', u'php5.6-cli', u'php5.6-common', u'php5.6-curl', u'php5.6-dev', u'php5.6-fpm', u'php5.6-gd', u'php5.6-imap', u'php5.6-json', u'php5.6-mbstring', u'php5.6-mcrypt', u'php5.6-opcache', u'php5.6-sqlite3', u'php5.6-xml', u'php5.6-yaml']) => {"failed": true, "item": ["php5.6", "php5.6-apcu", "php5.6-cli", "php5.6-common", "php5.6-curl", "php5.6-dev", "php5.6-fpm", "php5.6-gd", "php5.6-imap", "php5.6-json", "php5.6-mbstring", "php5.6-mcrypt", "php5.6-opcache", "php5.6-sqlite3", "php5.6-xml", "php5.6-yaml"], 
"msg": "No package matching 'php5.6' is available"}
   (...)
PLAY RECAP *********************************************************************
drupalvm2                  : ok=63   changed=17   unreachable=0    failed=1
   (...)
DEBUG ssh: Exit status: 2
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
Please see https://gist.github.com/visages/ef9ba01592fd15cc57da280f74f86ac3 for full debug output

### Summary

I tried several times to install a Debian box. Even with no custom `config.yml`, it always fails at _Ensure PHP packages are installed_ TASK. 

With `default.config.yml` php version (7.0) , it returns "_No package matching 'php7.0-yaml' is available_", while with PHP 5.6 it returns "_No package matching 'php5.6' is available_".

I successfully installed a Ubuntu box on that same environment, and Drupal 8 is running nicely. I'd like to mirror a Debian Jessie production server built with Nginx, PHP 5.6, MariaDb, Varnish and Redis, but until now I'm stuck at that point. 

Your help is really appreciated. Thank you.

**Comment by geerlingguy** [comment]
@visages - Last time I was testing Debian was when PHP 7.0 was brand new, and 5.6 was the mainline version of PHP, so that's why this is currently failing.

Please see https://github.com/geerlingguy/drupal-vm/pull/1208 for some progress on the issue.

Basically, I need to make sure that Ondrej's Debian repo is correctly configured so everything will work on Debian like it does on Ubuntu. Just haven't had the time to do that yet.

**Comment by visages** [comment]
@geerlingguy I'll follow both issues then. Thanks for such a quick reply and your amazing work :).

**Comment by geerlingguy** [comment]
Sure thing! I'm testing the changes locally now.

**Comment by geerlingguy** [comment]
@visages - Fixed in https://github.com/geerlingguy/drupal-vm/pull/1208 — please use the `master` branch of Drupal VM until 4.3.2 is released. Thanks for the issue!

**Comment by visages** [comment]
Awesome ! I confirm I ran `geerlingguy/debian8` box with master branch, reconfigured `config.yml` and got a brand new _Debian 8 + Nginx (php 5.6)+ MariaDB + Redis + Varnish_ running VM

Commited faster than Lucky Luke 🥇 Thank you.

**Comment by geerlingguy** [comment]
Haha, nice! And glad you could test all that, as I've only been testing the basic things, not necessarily _all_ the packages.
