### ISSUE TITLE
D8 test module doesn't work in VM

### ISSUE THREAD

**Issue by Kalpana-Goel** [geerlingguy/drupal-vm#122]
I have created one very simple Drupal 8 module and I tested it on D8 instance (outside VM) and I was able to access the page with bunch of links. 
I wanted to run xhprof on another D8 instance inside VM using the same Drupal 8 module but when I tried to access the page, I got "page not found". My test module is https://github.com/Kalpana-Goel/D8-Test-Module. Can you please look into this and share your thoughts as why this may not be working in drupal-vm?

**Comment by geerlingguy** [comment]
@Kalpana-Goel - where did you place the test module?

With the default setup and shared folders, you would want to place your 'links' folder in the D8-Test-Module into the following directory on your host machine: `~/Sites/drupalvm/drupal/modules/`

You would then have the info.yml file at `~/Sites/drupalvm/drupal/modules/links/links.info.yml`.
