### ISSUE TITLE
Unable to upload images inline-images

### ISSUE THREAD

**Issue by skorasaurus** [geerlingguy/drupal-vm#1220]
### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.16r113841
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
drupal-vm version: of https://github.com/geerlingguy/drupal-vm/commit/1a981762840072121c4c1b102e6ff242ce6cfede
```

### Your OS

ubuntu 16.04.02

### Full console output
none, see below

### Summary

Unable to upload an image in a page in the default site that was created. Vanilla setup, no modifications to the config file. 

Here's the error that I receive in the log messages: ![selection_005](https://cloud.githubusercontent.com/assets/955351/23964344/8c4f3ad6-098a-11e7-8ba6-bbce99f2cd0a.png)

or as text ```The upload directory public://inline-images for the file field could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled.```

I found this had occurred in the past [with #99](https://github.com/geerlingguy/drupal-vm/issues/99) and was fixed at https://github.com/geerlingguy/drupal-vm/commit/1a39996fb2f9c6e54e78f6522647eb684484eee7  but apparently the issue still exists or a regression occurred. 

My file permissions inside the VM suggest that I should be able to create them:
```
vagrant@drupalvm:/var/www/drupalvm/drupal/web/sites/default/files$ ls -lah
total 64K
drwxrwxrwx 8 1000 admin 4.0K Mar 15 18:08 .
dr-xr-xr-x 3 1000 admin 4.0K Mar 14 16:36 ..
drwxrwxr-x 3 1000 admin 4.0K Mar 14 16:37 config_rAIeGI6LbF2nVldKW-LdnNL_9Rur7HDdFi5zv1Q9b1me2-bmNRjnJ5VCMrjIrVYBTyXWgLmBUA
drwxrwxr-x 2 1000 admin  12K Mar 15 18:14 css
-r--r--r-- 1 1000 admin  487 Mar 14 16:37 .htaccess
drwxrwxr-x 2 1000 admin 4.0K Mar 15 18:08 inline-images
drwxrwxr-x 2 1000 admin  12K Mar 15 18:14 js
-rw-rw-r-- 1 1000 admin 9.5K Mar 15 18:04 logo.png
drwxrwxrwx 3 1000 admin 4.0K Mar 14 16:46 php
drwxrwxr-x 3 1000 admin 4.0K Mar 15 15:05 styles
```

**Comment by oxyc** [comment]
The fix in #99 is macOS specific. I'll see if we can work around this in a more general way. Otherwise [`vagrant-bindfs`](http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors) can be used as a workaround for now.

**Comment by skorasaurus** [comment]
closing this; @oxyc - will make a PR for this?

**Comment by oxyc** [comment]
Great! Let's keep this open though. @geerlingguy might have some input on that PR, it's a bit sketchy

**Comment by oxyc** [comment]
Related #1170

**Comment by oxyc** [comment]
It might take a while for this to get merged, for now you can either

a) use [`vagrant-bindfs`](http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors)
b) add those tasks to a [post provision task file](http://docs.drupalvm.com/en/latest/extending/scripts/#ansible-task-files).

**Comment by oxyc** [comment]
Got merged sooner than I thought :)
