### ISSUE TITLE
Ansible roles not defined.

### ISSUE THREAD

**Issue by TendoAki** [geerlingguy/drupal-vm#123]
Mac OSX Yosemite keeps hitting this error

ERROR: cannot find role in /Users/mmorris/Sites/drupal-vm-master/provisioning/roles/geerlingguy.repo-remi or /Users/mmorris/Sites/drupal-vm-master/provisioning/geerlingguy.repo-remi or /usr/local/etc/ansible/roles/geerlingguy.repo-remi
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Please make sure you follow the instructions here: https://github.com/geerlingguy/drupal-vm#2---build-the-virtual-machine — notably, the part where you install all the role requirements with the command below:

```
sudo ansible-galaxy install -r provisioning/requirements.txt --force
```
