### ISSUE TITLE
Look for Vagrantfile.local in both project_dir and config_dir

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1231]
### Issue Type

 - Feature Idea

### Summary

This always bothered me a bit when using Drupal VM as a composer dependency. At the moment the `Vagrantfile.local` needs to reside next to your `config.yml`, which in my case is a `config/` subdirectory. Makes more sense for it to be located next to the delegating`Vagrantfile`.

**Comment by geerlingguy** [comment]
That's true. Same situation with BLT projects.

**Comment by geerlingguy** [comment]
Fixed via PR #1230.
