### ISSUE TITLE
vagrant up: TASK [geerlingguy.drush : Install Drush.]. HTTP Error 404: Not Found

### ISSUE THREAD

**Issue by hannupaasonen** [geerlingguy/drupal-vm#1234]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.14r112924
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.12.3)

### Full console output
TASK [geerlingguy.drush : Install Drush.] **************************************
fatal: [crape]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drush", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://github.com/drush-ops/drush/releases/download/8.x/drush.phar"}
	to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************                      : ok=134  changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

### Summary
https://github.com/drush-ops/drush/releases/download/8.x/drush.phar is not found while running vagrant up on a fresh install.

**Comment by oxyc** [comment]
You'll need to update the `drush_version` variable in your config.yml

```yaml
drush_version: "8.1.10"
```

Or simply remove it and let the default from `default.config.yml` take effect.

**Comment by hannupaasonen** [comment]
Fixed. Thanks!
