### ISSUE TITLE
Failing to download `drush.phar` 7.x

### ISSUE THREAD

**Issue by loren-osborn** [geerlingguy/drupal-vm#1235]
### Drupal 7 Compatibility

- Bug Report / Support Request

### Your Environment

(on Host)
```
Vagrant 1.9.1
VirtualBox 5.1.14r112924
```
(On guest:)
```
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 -  macOS Sierra 10.12.3

### Summary

Drupal-VM should not try to download nonexistent `drush.phar` file in Drupal 7 mode.

**Comment by geerlingguy** [comment]
@loren-osborn - Can you give more detail about what's happening, what's going wrong, etc.?

Is there a task that's failing? Can you provide some log output?

Drush is now installed differently than in the past, but the installation method should be the same for the global Drush install regardless of the Drupal version being installed. You can also disable the Drush installation entirely by removing it from `installed_extras` in your `config.yml`.

**Comment by loren-osborn** [comment]
I can't give you any log output until Monday, but my understanding was the version of drush installed needed to match the major drupal version number. None of the drush releases for 7.x were released (at least on github) as `.phar` builds. Although I don't have the logs in front of me, I remember ansible reporting a 404 http error trying to fetch the `drush.phar` from github.

**Comment by oxyc** [comment]
Drush version doesn't need to match the major drupal version. There's a [table of version supports on drush.org](http://www.drush.org/en/master/install/#drupal-compatibility) that you can use. Basically all versions except for 9.x supports Drupal 7.

You're most likely seeing the same issue as https://github.com/geerlingguy/drupal-vm/issues/1234.

So depending on which branch you want you need to update your config.yml with:

```yaml
drush_version: "8.1.10"
drush_version: "7.4.0"
```

**Comment by loren-osborn** [comment]
Umm... while this looks like a short term solution, I eventually want the machine configuration to match our production environment which I believe is running a 7.x version of drush. If a version of drush is specified that DOES NOT have a `.phar` file release available, I don't think failing with a 404 error is the correct behavior.

I think a better alternative would EITHER

- prevent attempting to download a drush `.phar` file if the specified version is below 8.0
- in the event of a `drush.phar` file download failure, failover to the previous default source archive drush install method instead of giving up.

Comments?

**Comment by oxyc** [comment]
The issue here is that `7.x` is not a release, it's a branch that was used for the previous git checkout installation. As the installation method now downloads `.phar` files, it needs to be an actual release, not just a branch.

So if your production environment runs eg `7.3.0` you need to set

```yaml
drush_version: "7.3.0"
```

Before when it used the git branch, it was even somewhat unstable as that points to a development branch, and not an actual released version.

**Comment by geerlingguy** [comment]
@loren-osborn - And note that you can always revert back to the old 'install-from-source' behavior by setting:

```yaml
drush_install_from_source: true
drush_version: "7.x" # or "7.3.0"
```

The only downside is it takes about 1 extra minute to do the build.

This will get Drupal VM to match production for you if you're still on the 7.x release series. But note that 7.x is not actively developed (and hasn't been for some time), so it would be a good idea to switch to Drush 8.x as soon as you can (even though you're on Drupal 7).

**Comment by benhosmer** [comment]
I found this issue after encountering the same error that @loren-osborn had:

```
TASK [geerlingguy.drush : Install Drush.] **************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drush", "failed": true, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "https://github.com/drush-ops/drush/releases/download/7.x/drush.phar"}
```

```
# You can configure almost anything else on the server in the rest of this file.
extra_security_enabled: false                                                   
                                                                                
drush_version: "7.x"   
```
I was also using an outdated exampl.config.yaml.
