### ISSUE TITLE
How do you create additional Solr cores?

### ISSUE THREAD

**Issue by 24ma13wg** [geerlingguy/drupal-vm#1236]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.7
VirtualBox 5.1.8r111374
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (Sierra)

### Full console output
N/A

### Summary
How do you create additional Solr cores? When I click 'Add Core' in the Solr Admin I am prompted:

> instanceDir and dataDir need to exist before you can create the core

If I then do:

```
ssh vagrant@192.168.88.88 // enter password
sudo su
cd /var/solr/data
mkdir -p new_core/data
chown -R solr:solr new_core
```

then hit 'Add Core' in the Solr Admin I get an error

> Error CREATEing SolrCore 'new_core': Unable to create core [new_core] Caused by: Can't find resource 'solrconfig.xml' in classpath or '/var/solr/data/new_core'

If I try to recursively copy collection1, renaming it to new_core, then click 'Add Core' I get:

> new_core: org.apache.solr.common.SolrException:org.apache.solr.common.SolrException: Could not load conf for core new_core: Error loading solr config from /var/solr/data/new_core/conf/solrconfig.xml

I also tried:

`/opt/solr/bin/solr create -c new_core`

This appears to create a new core, but when I ran `vagrant provision` it disappeared, and I just had collection1 again.

Can you explain how to correctly create additional Solr cores?

**Comment by geerlingguy** [comment]
@24ma13wg - The easiest way is to add them via the `solr_cores` variable:

https://github.com/geerlingguy/ansible-role-solr#role-variables

Then to make sure the configuration is correct (it differs if you're using it for D7 Search API, D7 Apache Solr, D8 Search API, D6, the Solr version in use, etc.), you need to download and place in the correct solrconfig.xml, schema.xml, and other supporting config files as needed.

See the example solr setup script for some details of what's required—after adding the core name to `solr_cores`: https://github.com/geerlingguy/drupal-vm/blob/master/examples/scripts/configure-solr.sh

**Comment by geerlingguy** [comment]
Closing this issue for now; please let me know if you still have any questions.

**Comment by berdyshev** [comment]
Where I have to add this `solr_cores` variable? I've added it to the `config.yml` but even after provisioning the cores don't appear. 
And try to create new core using `/opt/solr/bin/solr create` fails with this error:
```
ERROR: create not supported!


Usage: solr COMMAND OPTIONS
       where COMMAND is one of: start, stop, restart, healthcheck
```

Maybe it's worth to improve documentation on that point.

**Comment by geerlingguy** [comment]
@berdyshev - Did you read through the documentation on the Solr role? https://github.com/geerlingguy/ansible-role-solr#role-variables

**Comment by berdyshev** [comment]
@geerlingguy yes, sure, as you can see I have added in `config.yml` such piece of configuration:
```
solr_cores:
   - d7_core
   - d8_core
```
but they wasn't be created after provisioning — it says "skipping", I don't know why. Maybe I'm missing something?

**Comment by geerlingguy** [comment]
@berdyshev - Do you have `solr` in your `installed_extras` list?

**Comment by berdyshev** [comment]
yes, I have. Solr is installed and I can reach its Admin UI, but I can't create cores.
I see `collection1` folder in `/opt/solr/node1/solr` and in `/var/solr`, but creating manually new core dir in `/var/solr` just adds it in Admin UI cores list, but it didn't work — Solr tells that this core has `example` config but not drupal's (I have copied config files from drupal's module; and directory permissions are OK too).

By the way, I have been configuring solr in drupalvm a long time ago and it worked, but after some update (I can't tell which one exactly, because I missed that moment) it stopped work and I can't make it works again.
