### ISSUE TITLE
Drush cannot be downloaded due to 404 error

### ISSUE THREAD

**Issue by jamiehollern** [geerlingguy/drupal-vm#1239]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.1.18r114002
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (OS X El Capitan 10.11.6 (15G1217))

### Full console output

https://gist.github.com/jamiehollern/d0b50914e7f90b97d9fc496e9ee09d1f

### Summary

When attempting to provision Drupal VM, Drush cannot be downloaded. Ansible reports a `404` HTTP response for https://github.com/drush-ops/drush/releases/download/8.x/drush.phar. A manual check confirms that this URL is non-existent. It is not referenced on the [releases page](https://github.com/drush-ops/drush/releases) either.

It may be pertinent to note that I am using Drupal VM as a Composer dependency.

**Comment by oxyc** [comment]
This is due a recent upstream change in the `drush` role. You'll need to update the `drush_version` variable in your config.yml

```yaml
drush_version: "8.1.10"
```

Or simply remove it and let the default from `default.config.yml` take effect.

#1234

**Comment by jamiehollern** [comment]
Thanks for the prompt response!
