### ISSUE TITLE
What? No PHPUnit?

### ISSUE THREAD

**Issue by TendoAki** [geerlingguy/drupal-vm#124]
Considering half the tests in Drupal 8 are now PHPUnit based its omission from the base install is a bit of an oversight I'd think.  Otherwise works great.

**Comment by geerlingguy** [comment]
PHPUnit should be installed along with other composer dependencies as required per-project... how else would you like to see it installed?

**Comment by TendoAki** [comment]
Globally..
composer global require "phpunit/phpunit=4.7.*"

Also PHP Code Sniffer would be useful to have off the bat for code format compliance.

composer global require "squizlabs/php_codesniffer=*"

I ran each of these after I got it up and running, then added the composer bin directory to my path.

They're easy enough to setup though including them would further help people hit the ground running.

**Comment by geerlingguy** [comment]
I've updated the upstream `geerlingguy.composer` role (see https://github.com/geerlingguy/ansible-role-composer/issues/2), so now you can add something like the following in your `config.yml` file (I'll add a commented example in the project's example file in a commit in a minute or two):

```yaml
composer_global_packages:
  - { name: phpunit/phpunit, release: '4.7.*' }
  - { name: phpmd/phpmd, release: '2.2.*' }
```
