### ISSUE TITLE
Errors in configuration for aws build

### ISSUE THREAD

**Issue by haynescw** [geerlingguy/drupal-vm#1241]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.6
VirtualBox 5.1.12r112440
ansible 2.2.0.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.11.6)

### Full console output
https://gist.github.com/haynescw/5ec7afb85d1f2f0dd8eb21a1ea14193d

### Summary

So I have all my aws info and have the proper data stored as env variables and with ussing what you have in your documentation i get only one error about a region must being specified. I tried specifying that region within the config but i still get the same results.

**Comment by oxyc** [comment]
What does your `Vagrantfile.local` look like? It's best to follow the docs over at the [`vagrant-aws`](https://github.com/mitchellh/vagrant-aws) plugin itself.

Whatever variable you place in `config.yml` will be available in the `vconfig` hash, as the example shows.
