### ISSUE TITLE
Are you planning to create an AWS hashicorp box

### ISSUE THREAD

**Issue by haynescw** [geerlingguy/drupal-vm#1243]
### Issue Type
 - Feature Idea

### Summary

Are you ever planning to create an AWS hashicorp box?

**Comment by geerlingguy** [comment]
At this time, no; you'd be best served by using an AWS box that has ubuntu 16.04 minimal (or whatever OS most closely matches one of:

  - Ubuntu 16.04 LTS minimal
  - Ubuntu 14.04 LTS minimal
  - Ubuntu 12.04 LTS minimal
  - CentOS 7 minimal ('Amazon Linux')
  - CentOS 6 minimal ('Amazon Linux')
  - Debian 8 minimal

**Comment by geerlingguy** [comment]
See: https://vagrantcloud.com/boxes/search?provider=aws
