### ISSUE TITLE
"Generate Drupal project with composer package" hanging.

### ISSUE THREAD

**Issue by laurencefass** [geerlingguy/drupal-vm#1248]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.3
```

### Your OS

 - **Windows** 10

### Full console output

TASK [geerlingguy.solr : Expand Solr.] *****************************************
skipping: [drupalvm]

TASK [geerlingguy.solr : Check if Solr is already installed.] ******************
skipping: [drupalvm]

TASK [geerlingguy.solr : Copy Solr into place.] ********************************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure Solr install files are owned by the solr_user.]
skipping: [drupalvm]

TASK [geerlingguy.solr : Check if solr_home is already set up.] ****************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure solr_home directory exists.] *******************
skipping: [drupalvm]

TASK [geerlingguy.solr : Copy Solr example into solr_home.] ********************
skipping: [drupalvm]

TASK [geerlingguy.solr : Fix the example solrconfig.xml file.] *****************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure Solr home files are owned by the solr_user.] ***
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure log file is created and has proper permissions.] ***
skipping: [drupalvm]

TASK [geerlingguy.solr : Copy solr init script into place.] ********************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure daemon is installed (Debian).] *****************
skipping: [drupalvm]

TASK [geerlingguy.solr : Copy solr systemd unit file into place (for systemd systems).] ***
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure lsof is present (RedHat).] *********************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure setfacl support is present.] *******************
skipping: [drupalvm]

TASK [geerlingguy.solr : Run Solr installation script.] ************************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure solr is stopped (RHEL 7 workaround).] **********
skipping: [drupalvm]

TASK [geerlingguy.solr : Run systemd daemon_reload (RHEL 7 workaround).] *******
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure solr is started and enabled on boot.] **********
skipping: [drupalvm]

TASK [geerlingguy.solr : Check current list of Solr cores.] ********************
skipping: [drupalvm]

TASK [geerlingguy.solr : Ensure Solr conf directories exist.] ******************
skipping: [drupalvm] => (item=collection1)

TASK [geerlingguy.solr : Ensure core configuration directories exist.] *********
skipping: [drupalvm] => (item=collection1)

TASK [geerlingguy.solr : Create configured cores.] *****************************
skipping: [drupalvm] => (item=collection1)

TASK [geerlingguy.solr : Remove existing SOLR_HEAP configuration.] *************
skipping: [drupalvm]

TASK [geerlingguy.solr : Apply Solr configuration changes.] ********************
skipping: [drupalvm] => (item={u'regexp': u'^.?SOLR_JAVA_MEM=', u'line': u'SOLR_JAVA_MEM="-Xms64M -Xmx128M"'})
skipping: [drupalvm] => (item={u'regexp': u'^.?SOLR_TIMEZONE=', u'line': u'SOLR_TIMEZONE="UTC"'})
skipping: [drupalvm] => (item={u'regexp': u'^SOLR_PORT=', u'line': u'SOLR_PORT="8983"'})

TASK [geerlingguy.solr : include] **********************************************
skipping: [drupalvm]

TASK [geerlingguy.java : Include OS-specific variables.] ***********************
skipping: [drupalvm]

TASK [geerlingguy.java : Include OS-specific variables for Fedora.] ************
skipping: [drupalvm]

TASK [geerlingguy.java : Include version-specific variables for Ubuntu.] *******
skipping: [drupalvm]

TASK [geerlingguy.java : Define java_packages.] ********************************
skipping: [drupalvm]

TASK [geerlingguy.java : include] **********************************************
skipping: [drupalvm]

TASK [geerlingguy.java : include] **********************************************
skipping: [drupalvm]

TASK [geerlingguy.java : include] **********************************************
skipping: [drupalvm]

TASK [geerlingguy.java : Set JAVA_HOME if configured.] *************************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Add Elasticsearch GPG key.] ******************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Add Elasticsearch repository.] ***************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Install Elasticsearch.] **********************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Add Elasticsearch apt key.] ******************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Add Elasticsearch repository.] ***************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Install Elasticsearch.] **********************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Configure Elasticsearch.] ********************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Start Elasticsearch.] ************************
skipping: [drupalvm]

TASK [geerlingguy.elasticsearch : Make sure Elasticsearch is running before proceeding.] ***
skipping: [drupalvm]

TASK [geerlingguy.varnish : Include OS-specific variables.] ********************
ok: [drupalvm]

TASK [geerlingguy.varnish : Ensure Varnish dependencies are installed.] ********
skipping: [drupalvm] => (item=[])

TASK [geerlingguy.varnish : Add Varnish repository.] ***************************
skipping: [drupalvm]

TASK [geerlingguy.varnish : Set repo fact appropriately.] **********************
skipping: [drupalvm]

TASK [geerlingguy.varnish : Install Varnish.] **********************************
skipping: [drupalvm]

TASK [geerlingguy.varnish : Ensure APT HTTPS Transport is installed.] **********
skipping: [drupalvm]

TASK [geerlingguy.varnish : Add Varnish apt key.] ******************************
skipping: [drupalvm]

TASK [geerlingguy.varnish : Add Varnish apt repository.] ***********************
skipping: [drupalvm]

TASK [geerlingguy.varnish : Install Varnish.] **********************************
changed: [drupalvm]

TASK [geerlingguy.varnish : Copy Varnish configuration (sysvinit).] ************
skipping: [drupalvm]

TASK [geerlingguy.varnish : Copy Debian Jessie/Xenial specific Varnish configs (systemd).] ***
changed: [drupalvm]

TASK [geerlingguy.varnish : Copy Varnish configuration (systemd).] *************
changed: [drupalvm]

TASK [geerlingguy.varnish : Ensure Varnish config path exists.] ****************
ok: [drupalvm]

TASK [geerlingguy.varnish : Copy Varnish default VCL.] *************************
changed: [drupalvm]

TASK [geerlingguy.varnish : Copy varnish secret.] ******************************
changed: [drupalvm]

TASK [geerlingguy.varnish : Ensure Varnish services are started enabled on startup.] ***
ok: [drupalvm] => (item=varnish)

TASK [geerlingguy.security : Include OS-specific variables.] *******************
skipping: [drupalvm]

TASK [geerlingguy.security : Install fail2ban.] ********************************
skipping: [drupalvm]

TASK [geerlingguy.security : Install fail2ban.] ********************************
skipping: [drupalvm]

TASK [geerlingguy.security : Ensure fail2ban is running and enabled on boot.] **
skipping: [drupalvm]

TASK [geerlingguy.security : Update SSH configuration to be more secure.] ******
skipping: [drupalvm] => (item={u'regexp': u'^PermitRootLogin', u'line': u'PermitRootLogin no'})
skipping: [drupalvm] => (item={u'regexp': u'^X11Forwarding', u'line': u'X11Forwarding no'})
skipping: [drupalvm] => (item={u'regexp': u'^GSSAPIAuthentication', u'line': u'GSSAPIAuthentication no'})
skipping: [drupalvm] => (item={u'regexp': u'^ChallengeResponseAuthentication', u'line': u'ChallengeResponseAuthentication no'})
skipping: [drupalvm] => (item={u'regexp': u'^PermitEmptyPasswords', u'line': u'PermitEmptyPasswords no'})
skipping: [drupalvm] => (item={u'regexp': u'^UseDNS', u'line': u'UseDNS no'})
skipping: [drupalvm] => (item={u'regexp': u'^Port', u'line': u'Port 22'})
skipping: [drupalvm] => (item={u'regexp': u'^PasswordAuthentication', u'line': u'PasswordAuthentication no'})

TASK [geerlingguy.security : Add configured user accounts to passwordless sudoers.] ***

TASK [geerlingguy.security : Add configured user accounts to passworded sudoers.] ***

TASK [geerlingguy.security : Install yum-cron.] ********************************
skipping: [drupalvm]

TASK [geerlingguy.security : Ensure yum-cron is running and enabled on boot.] **
skipping: [drupalvm]

TASK [geerlingguy.security : Configure autoupdates (RHEL 7).] ******************
skipping: [drupalvm]

TASK [geerlingguy.security : Install unattended upgrades package.] *************
skipping: [drupalvm]

TASK [geerlingguy.security : Copy unattended-upgrades configuration files in place.] ***
skipping: [drupalvm] => (item=50unattended-upgrades)
skipping: [drupalvm] => (item=10periodic)

TASK [Do not accept locale environment variables passed over SSH.] *************
changed: [drupalvm]

TASK [Check if local known_hosts file is present.] *****************************
ok: [drupalvm]

TASK [Copy known_hosts file from host into Drupal VM.] *************************
skipping: [drupalvm]

TASK [Set SSH home directory.] *************************************************
skipping: [drupalvm]

TASK [Install extra apt packages (if any are configured).] *********************
changed: [drupalvm] => (item=[u'sqlite'])

TASK [Install extra yum packages (if any are configured).] *********************
skipping: [drupalvm] => (item=[])

TASK [Define drupalvm_webserver_user (Debian).] ********************************
ok: [drupalvm]

TASK [Define drupalvm_webserver_user (RedHat).] ********************************
skipping: [drupalvm]

TASK [Register information about the /vagrant directory.] **********************
ok: [drupalvm]

TASK [Ensure a group with the same GID as used to sync directories exist (Ansible 2.3+).] ***
skipping: [drupalvm]

TASK [Ensure the webserver user is in the same group as the owner of synced directories (Ansible
2.3+).] ***
skipping: [drupalvm]

TASK [Detect if group used to sync directories already exist (Ansible 2.2).] ***
ok: [drupalvm]

TASK [Ensure a group with the same GID as used to sync directories exist (Ansible 2.2).] ***
skipping: [drupalvm]

TASK [Ensure the webserver user is in the same group as the owner of synced directories (Ansible
2.2).] ***
changed: [drupalvm]

TASK [Ensure admin group exist.] ***********************************************
changed: [drupalvm]

TASK [Ensure vagrant user is in admin group.] **********************************
changed: [drupalvm]

TASK [Set nicer permissions on Apache log directory.] **************************
changed: [drupalvm]

TASK [Copy Nginx vhosts into place.] *******************************************
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/var/www/drupalvm/drupal/web', u'server_name': u'drupalvm.dev www.drupalvm.dev'})
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/var/www/dashboard', u'server_name': u'192.168.88.88 dashboard.drupalvm.dev'})
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/usr/share/php/pimpmylog', u'server_name': u'pimpmylog.drupalvm.dev'})
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/usr/share/php/xhprof_html', u'server_name': u'xhprof.drupalvm.dev'})
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/opt/adminer', u'server_name': u'adminer.drupalvm.dev'})

TASK [Detect if AppArmor is working.] ******************************************
ok: [drupalvm]
 [WARNING]: Consider using service module rather than running service

TASK [Ensure MySQL AppArmor profile is disabled (for slow query log).] *********
changed: [drupalvm]

TASK [Restart the AppArmor if necessary.] **************************************
changed: [drupalvm]

TASK [include_role] ************************************************************

TASK [geerlingguy.drupal : Add backwards-compatibility shims.] *****************
included: /vagrant/provisioning/roles/geerlingguy.drupal/tasks/backwards-compatibility.yml for drupalvm

TASK [geerlingguy.drupal : build_makefile shim] ********************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : build_composer shim] ********************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : build_composer_project shim] ************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : install_site shim] **********************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : drupalvm_database shim] *****************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : Check if Drupal is already set up.] *****************
ok: [drupalvm]

TASK [geerlingguy.drupal : Define drupal_site_exists] **************************
ok: [drupalvm]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : include] ********************************************
included: /vagrant/provisioning/roles/geerlingguy.drupal/tasks/build-composer-project.yml for drupalvm

TASK [geerlingguy.drupal : Ensure drupal_composer_install_dir directory has proper permissions.]
***
changed: [drupalvm]

TASK [geerlingguy.drupal : Generate Drupal project with composer package.] *****

C:\Users\laurence\VirtualBox VMs\Vagrant Boxes\drupal-vm>==> drupalvm: Waiting for cleanup before exiting...

### Summary

I have been trying for two days to get this working basically deleting and re-running. Tried the zip file on the site and cloning latest github Just hangs at Generate Drupal project message. No idea whats going on. any help appreciated.

**Comment by geerlingguy** [comment]
@laurencefass - How long have you let this run before killing it? Sometimes it can take 20, 30, 40 minutes, depending on your Internet connection and how Composer is feeling that day.

I typically avoid using that method of building new sites if I'm just trying to get a quick Drupal 8 site put together—I instead use the example `drupal.composer.json` file and the composer install technique. But it usually takes less than 5 minutes on my home computer and Internet connection, and about the same in the Travis CI automated builds here on GitHub.

**Comment by laurencefass** [comment]
thanks for quick reply. im happy to do whatever to get the site running. please can you give some steps for using the composer method. do i vagrant ssh onto box or run commands on my vbox host? is it as simple as php compose install? which directory? thanks.

**Comment by laurencefass** [comment]
also: ive left it running for hours. some sort of progress or activity indicator may be useful... but ill wait for the drupal.composer.json solution and go with it...

**Comment by geerlingguy** [comment]
@laurencefass see: http://docs.drupalvm.com/en/latest/deployment/composer/

You can also build from a Drush Make file (see other links in the docs linked above).

**Comment by laurencefass** [comment]
I dont really understand the context of this link. http://docs.drupalvm.com/en/latest/deployment/composer/

do i make the detailed changes and then run vagrant up? vagrant provision? do i need to make these changes on a totally clean box (so delete the one i have) or can i re-run existing box? should i see a different output?

**Comment by geerlingguy** [comment]
@laurencefass - You would make those changes then if you already built the VM once, run `vagrant provision`. Though it might be cleanest if you do `vagrant destroy` to delete the VM, then `vagrant up` from scratch again.

**Comment by laurencefass** [comment]
ill try in the morning (its night here in the UK) and let you know how i get on. thanks so much for responding so quickly.

**Comment by laurencefass** [comment]
following instructions ive added entries into config.yml and left default.config.yml untouched. im assuming the former is parsed after the default file. 

drupal_build_makefile: false
drupal_build_composer: true
drupal_build_composer_project: false
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"

OUTPUT from > vagrant provision
====================


TASK [geerlingguy.drupal : include] ********************************************
skipping: [drupalvm]

TASK [geerlingguy.drupal : include] ********************************************
included: /vagrant/provisioning/roles/geerlingguy.drupal/tasks/build-composer.yml for drupalvm

TASK [geerlingguy.drupal : Ensure drupal_composer_install_dir directory exists.] ***
ok: [drupalvm]

TASK [geerlingguy.drupal : Copy composer.json into temporary location.] ********
changed: [drupalvm]

TASK [geerlingguy.drupal : Move composer.json into place.] *********************
changed: [drupalvm]

TASK [geerlingguy.drupal : Run composer install.] ******************************


...so its stopping here. the longest ive waited is an hour. is there a log file i can look somewhere? have you seen this before?

**Comment by laurencefass** [comment]
how do i use composer.json and drupal.composer.json? do i overwrite the former with the latter?

**Comment by laurencefass** [comment]
i ran vagrant provision a couple of times and it just worked.

**Comment by geerlingguy** [comment]
@laurencefass - I'm guessing it was just a network slowdown, or it could've just been super slow if your computer has a spinning hard disk instead of SSD, something like that.

**Comment by ananyakar2012** [comment]
I am trying to run vagrant up in windows 10. But getting this error -
TASK [geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while).] ***
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal/recommended-project:^9@dev", "/tmp/composer-project", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:30.199718", "end": "2020-09-08 07:40:38.273486", "msg": "non-zero return code", "rc": 1, "start": "2020-09-08 07:40:08.073768", "stderr": "    1/5:\thttp://repo.packagist.org/p/provider-latest$0e7e2e28ddc4fba18b0423e5c231a2f309dd7a6f86c6fb49ebd06b72eb6df0a1.json\n    2/5:\thttp://repo.packagist.org/p/provider-2020-01$9b89d58c6306aed7da9d22c30a7620db5dcd6614a56b238859073478d84e0373.json\n    3/5:\thttp://repo.packagist.org/p/provider-2020-04$b4cd377d81ef5312aba23b7dd6caaa87f3cf53064cef1a327accd76a8967b5df.json\n    4/5:\thttp://repo.packagist.org/p/provider-2019$96a23217ee6d45f8ec6f76d641fc875940ec1777cdd3161927ca1e28a95e72e3.json\n    5/5:\thttp://repo.packagist.org/p/provider-2020-07$eb7894cc88843498e08e8d9223d2f8c3316eff82add860e0f633be2df9955f9b.json\n    Finished: success: 5, skipped: 0, failure: 0, total: 5\n    1/5:\thttp://repo.packagist.org/p/provider-latest$0e7e2e28ddc4fba18b0423e5c231a2f309dd7a6f86c6fb49ebd06b72eb6df0a1.json\n    2/5:\thttp://repo.packagist.org/p/provider-2020-01$9b89d58c6306aed7da9d22c30a7620db5dcd6614a56b238859073478d84e0373.json\n    3/5:\thttp://repo.packagist.org/p/provider-2019$96a23217ee6d45f8ec6f76d641fc875940ec1777cdd3161927ca1e28a95e72e3.json\n    4/5:\thttp://repo.packagist.org/p/provider-2020-07$eb7894cc88843498e08e8d9223d2f8c3316eff82add860e0f633be2df9955f9b.json\n    5/5:\thttp://repo.packagist.org/p/provider-2020-04$b4cd377d81ef5312aba23b7dd6caaa87f3cf53064cef1a327accd76a8967b5df.json\n    Finished: success: 5, skipped: 0, failure: 0, total: 5\n    1/5:\thttp://repo.packagist.org/p/provider-2020-01$9b89d58c6306aed7da9d22c30a7620db5dcd6614a56b238859073478d84e0373.json\n    2/5:\thttp://repo.packagist.org/p/provider-latest$0e7e2e28ddc4fba18b0423e5c231a2f309dd7a6f86c6fb49ebd06b72eb6df0a1.json\n    3/5:\thttp://repo.packagist.org/p/provider-2019$96a23217ee6d45f8ec6f76d641fc875940ec1777cdd3161927ca1e28a95e72e3.json\n    4/5:\thttp://repo.packagist.org/p/provider-2020-04$b4cd377d81ef5312aba23b7dd6caaa87f3cf53064cef1a327accd76a8967b5df.json\n    5/5:\thttp://repo.packagist.org/p/provider-2020-07$eb7894cc88843498e08e8d9223d2f8c3316eff82add860e0f633be2df9955f9b.json\n
   Finished: success: 5, skipped: 0, failure: 0, total: 5\nCreating a \"drupal/recommended-project:^9@dev\" project at \"/tmp/composer-project\"\nInstalling drupal/recommended-project (9.1.x-dev b19274227a2e723389bc9082b069f5afb887fe7e)\n  - Installing drupal/recommended-project (9.1.x-dev b192742): Loading from cache\nCreated project in /tmp/composer-project\n    1/2:\thttps://packages.drupal.org/8/drupal/provider-2020-2$6e1e13a519e5df061d623a7ff7a057cf1664acb0e6cc6675f92248e835bb1c06.json\n    2/2:\thttps://packages.drupal.org/8/drupal/provider-2020-3$74fce31854d7aa9febdefbb9c3b07816083c9d986fb7fb5dd33237a19fb7a803.json\n
   Finished: success: 2, skipped: 0, failure: 0, total: 2\nLoading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nPackage operations: 115 installs, 0 updates, 0 removals\n  - Installing composer/installers (v1.9.0): Loading from cache\n  - Installing drupal/core-composer-scaffold (9.1.x-dev 7b12551): Loading from cache\n  - Installing drupal/core-project-message (9.1.x-dev ae723fe): Loading from cache\n  - Installing typo3/phar-stream-wrapper (v3.1.5): Loading from cache\n  - Installing symfony/polyfill-mbstring (v1.18.1): Loading from cache\n    Failed to download symfony/polyfill-mbstring from dist: Failed to execute (2) unzip -qq -o '/tmp/composer-project/vendor/symfony/polyfill-mbstring/228d3298ea92dc5db0f55d7534bd6049' -d '/tmp/composer-project/vendor/composer/cbf2f3d5'\n\n/tmp/composer-project/vendor/composer/cbf2f3d5/symfony-polyfill-mbstring-a6977d6/Resources/unidata/lowerCase.php  bad CRC 68ab13c6  (should be 8a9fb65a)\n\n    Now trying to download from source\n  - Installing symfony/polyfill-mbstring (v1.18.1): Cloning a6977d63bf from cache\n  - Installing symfony/polyfill-ctype (v1.18.1): Loading from cache\n  - Installing twig/twig (v2.13.1): Loading from cache\n  - Installing symfony/yaml (v4.4.12): Loading from cache\n  - Installing symfony/polyfill-php80 (v1.18.1): Loading from cache\n  - Installing symfony/var-dumper (v5.1.4): Loading from cache\n  - Installing symfony/translation-contracts (v2.1.3): Loading from cache\n  - Installing symfony/validator (v4.4.12): Loading from cache\n    Failed to download symfony/validator from dist: Failed to execute (2) unzip -qq -o '/tmp/composer-project/vendor/symfony/validator/feb2d3a99c1a88725561fb3ac0a2f4fe' -d '/tmp/composer-project/vendor/composer/c5fb5657'\n\n/tmp/composer-project/vendor/composer/c5fb5657/symfony-validator-cee2f13/Constraints/RangeValidator.php  bad CRC dd5913d3  (should be 1bc28ae6)\n\n    Now trying to download from source\n  - Installing symfony/validator (v4.4.12): Cloning cee2f13ddc\n\n                                                                                                \n  [RuntimeException]
                                                \n  Failed to clone https://github.com/symfony/validator.git via https, ssh protocols, aborting.  \n
                                                                                      \n  - https://github.com/symfony/validator.git
                          \n    Cloning into '/tmp/composer-project/vendor/symfony/validator'...                            \n    error: inflate: data stream error (invalid bit length repeat)                               \n    fatal: pack has bad object at offset 408208: inflate returned -3
    \n    fatal: index-pack failed                                                                    \n
                                          \n  - git@github.com:symfony/validator.git                                                        \n    Cloning into '/tmp/composer-project/vendor/symfony/validator'...                            \n    git@github.com: Permission denied (publickey).
                    \n    fatal: Could not read from remote repository.                                               \n
                                                          \n    Please make sure you have the correct access rights                                         \n
    and the repository exists.                                                                  \n
                                    \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stderr_lines": ["    1/5:\thttp://repo.packagist.org/p/provider-latest$0e7e2e28ddc4fba18b0423e5c231a2f309dd7a6f86c6fb49ebd06b72eb6df0a1.json", "    2/5:\thttp://repo.packagist.org/p/provider-2020-01$9b89d58c6306aed7da9d22c30a7620db5dcd6614a56b238859073478d84e0373.json", "    3/5:\thttp://repo.packagist.org/p/provider-2020-04$b4cd377d81ef5312aba23b7dd6caaa87f3cf53064cef1a327accd76a8967b5df.json", "    4/5:\thttp://repo.packagist.org/p/provider-2019$96a23217ee6d45f8ec6f76d641fc875940ec1777cdd3161927ca1e28a95e72e3.json", "    5/5:\thttp://repo.packagist.org/p/provider-2020-07$eb7894cc88843498e08e8d9223d2f8c3316eff82add860e0f633be2df9955f9b.json", "    Finished: success: 5, skipped: 0, failure: 0, total: 5", "    1/5:\thttp://repo.packagist.org/p/provider-latest$0e7e2e28ddc4fba18b0423e5c231a2f309dd7a6f86c6fb49ebd06b72eb6df0a1.json", "    2/5:\thttp://repo.packagist.org/p/provider-2020-01$9b89d58c6306aed7da9d22c30a7620db5dcd6614a56b238859073478d84e0373.json", "    3/5:\thttp://repo.packagist.org/p/provider-2019$96a23217ee6d45f8ec6f76d641fc875940ec1777cdd3161927ca1e28a95e72e3.json", "    4/5:\thttp://repo.packagist.org/p/provider-2020-07$eb7894cc88843498e08e8d9223d2f8c3316eff82add860e0f633be2df9955f9b.json", "    5/5:\thttp://repo.packagist.org/p/provider-2020-04$b4cd377d81ef5312aba23b7dd6caaa87f3cf53064cef1a327accd76a8967b5df.json", "    Finished: success: 5, skipped: 0, failure: 0, total: 5", "    1/5:\thttp://repo.packagist.org/p/provider-2020-01$9b89d58c6306aed7da9d22c30a7620db5dcd6614a56b238859073478d84e0373.json", "    2/5:\thttp://repo.packagist.org/p/provider-latest$0e7e2e28ddc4fba18b0423e5c231a2f309dd7a6f86c6fb49ebd06b72eb6df0a1.json", "    3/5:\thttp://repo.packagist.org/p/provider-2019$96a23217ee6d45f8ec6f76d641fc875940ec1777cdd3161927ca1e28a95e72e3.json", "    4/5:\thttp://repo.packagist.org/p/provider-2020-04$b4cd377d81ef5312aba23b7dd6caaa87f3cf53064cef1a327accd76a8967b5df.json", "    5/5:\thttp://repo.packagist.org/p/provider-2020-07$eb7894cc88843498e08e8d9223d2f8c3316eff82add860e0f633be2df9955f9b.json", "    Finished: success: 5, skipped: 0, failure: 0, total: 5", "Creating a \"drupal/recommended-project:^9@dev\" project at \"/tmp/composer-project\"", "Installing drupal/recommended-project (9.1.x-dev b19274227a2e723389bc9082b069f5afb887fe7e)", "  - Installing drupal/recommended-project (9.1.x-dev b192742): Loading from cache", "Created project in /tmp/composer-project", "    1/2:\thttps://packages.drupal.org/8/drupal/provider-2020-2$6e1e13a519e5df061d623a7ff7a057cf1664acb0e6cc6675f92248e835bb1c06.json", "    2/2:\thttps://packages.drupal.org/8/drupal/provider-2020-3$74fce31854d7aa9febdefbb9c3b07816083c9d986fb7fb5dd33237a19fb7a803.json", "    Finished: success: 2, skipped: 0, failure: 0, total: 2", "Loading composer repositories with package information", "Installing dependencies (including require-dev) from lock file", "Package operations: 115 installs, 0 updates, 0 removals", "  - Installing composer/installers (v1.9.0): Loading from cache", "  - Installing drupal/core-composer-scaffold (9.1.x-dev 7b12551): Loading from cache", "  - Installing drupal/core-project-message (9.1.x-dev ae723fe): Loading from cache", "  - Installing typo3/phar-stream-wrapper (v3.1.5): Loading from cache", "  - Installing symfony/polyfill-mbstring (v1.18.1): Loading from cache", "    Failed to download symfony/polyfill-mbstring from dist: Failed to execute (2) unzip -qq -o '/tmp/composer-project/vendor/symfony/polyfill-mbstring/228d3298ea92dc5db0f55d7534bd6049' -d '/tmp/composer-project/vendor/composer/cbf2f3d5'", "", "/tmp/composer-project/vendor/composer/cbf2f3d5/symfony-polyfill-mbstring-a6977d6/Resources/unidata/lowerCase.php  bad CRC 68ab13c6  (should be 8a9fb65a)", "", "    Now trying to download from source", "  - Installing symfony/polyfill-mbstring (v1.18.1): Cloning a6977d63bf from cache", "  - Installing symfony/polyfill-ctype (v1.18.1): Loading from cache", "  - Installing twig/twig (v2.13.1): Loading from cache", "  - Installing symfony/yaml (v4.4.12): Loading from cache", "  - Installing symfony/polyfill-php80 (v1.18.1): Loading from cache", "  - Installing symfony/var-dumper (v5.1.4): Loading from cache", "  - Installing symfony/translation-contracts (v2.1.3): Loading from cache", "  - Installing symfony/validator (v4.4.12): Loading from cache", "    Failed to download symfony/validator from dist: Failed to execute (2) unzip -qq -o '/tmp/composer-project/vendor/symfony/validator/feb2d3a99c1a88725561fb3ac0a2f4fe' -d '/tmp/composer-project/vendor/composer/c5fb5657'", "", "/tmp/composer-project/vendor/composer/c5fb5657/symfony-validator-cee2f13/Constraints/RangeValidator.php  bad CRC dd5913d3  (should be 1bc28ae6)", "", "    Now trying to download from source", "  - Installing symfony/validator (v4.4.12): Cloning cee2f13ddc", "", "                                                                                                ", "  [RuntimeException]
                                               ", "  Failed to clone https://github.com/symfony/validator.git via https, ssh protocols, aborting.  ", "
                                                                                         ", "  - https://github.com/symfony/validator.git
                               ", "    Cloning into '/tmp/composer-project/vendor/symfony/validator'...                            ", "    error: inflate: data stream error (invalid bit length repeat)                               ", "    fatal: pack has bad object at offset 408208: inflate returned -3
               ", "    fatal: index-pack failed                                                                    ", "
                                                         ", "  - git@github.com:symfony/validator.git                                                        ", "    Cloning into '/tmp/composer-project/vendor/symfony/validator'...                            ", "    git@github.com: Permission denied (publickey).
                                         ", "    fatal: Could not read from remote repository.                                               ", "
                                                                                   ", "    Please make sure you have the correct access rights
                         ", "    and the repository exists.                                                                  ", "
                                                                   ", "", "create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]"], "stdout": "", "stdout_lines": []}
