### ISSUE TITLE
Can't get to install NodeJS through Composer

### ISSUE THREAD

**Issue by Didel** [geerlingguy/drupal-vm#1249]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.2
VirtualBox 5.1.18r114002
```
In the VM:
```
ansible 2.2.1.0
```

### Your OS
 - **macOS** 10.12.3

### Full console output

https://gist.github.com/Didel/ab5aace19eb2a44159e6bb61a5364f9e

### config.yml file
https://gist.github.com/Didel/be52ad5aa6e34f9b1e89dc870b8551ad

### Summary

To try out the Thunder distribution on a clean environment, I'm trying to set up a new DrupalVM. Thunder requires composer and nodejs to be present. I'm using the build_composer_project option, but can't get it to work. Every time I try to provision, the above error (see bottom of console output gist) is shown. I have specified node 6.x, but I'd be glad to get it working on any version. Is there something I'm missing here, or is this a bug in the configuration?

**Comment by oxyc** [comment]
Looks like you're not using proper quotes:

```yaml
nodejs_version: “6.x”
```

vs

```yaml
nodejs_version: "6.x"
```

**Comment by geerlingguy** [comment]
Seconded... see:

```
ok: [thundervm] => (item=deb https://deb.nodesource.com/node_?6.x? xenial main)
ok: [thundervm] => (item=deb-src https://deb.nodesource.com/node_?6.x? xenial main)
```

The `?` likely means the ascii translation blew up when it got some crazy smart quotes :)

**Comment by geerlingguy** [comment]
Closing this hoping the above solution works (switching from smart quotes to normal quotes). Let us know if it doesn't!

**Comment by Didel** [comment]
I couldn't respond any earlier... Thanks a lot for the quick answer, replacing the quotes with regular ones and clearing the apt cache did it. They really should forbid those quotes...
