### ISSUE TITLE
Please add MariaDB Support

### ISSUE THREAD

**Issue by Greg-Boggs** [geerlingguy/drupal-vm#125]
Are there special steps to enabling MariaDB for DrupalVM?

**Comment by geerlingguy** [comment]
I'm glad you asked! Currently the following would need to be done:

  1. Switch `vagrant_box` in `config.yml` to: `geerlingguy/centos7`
  2. Manually apply this PR/patch to the `geerlingguy.mysql` role (by default, it should be in `/etc/ansible/roles/geerlingguy.mysql` on the host machine): https://github.com/geerlingguy/ansible-role-mysql/pull/38 ([patch](https://github.com/geerlingguy/ansible-role-mysql/pull/38.patch)).

Technically, you could even use MariaDB without switching to CentOS 7, if you can get the Ubuntu packages right, but I haven't tested that yet.

I'd like to add a Wiki page with instructions for switching to MariaDB from MySQL, but I just haven't had the time yet.

**Comment by geerlingguy** [comment]
See new Wiki page: [Use MariaDB instead of MySQL](https://github.com/geerlingguy/drupal-vm/wiki/Use-MariaDB-instead-of-MySQL).

I'll be adding instructions there (and linking to them from the README and project home page) soon. You can now use MariaDB easily in either Ubuntu 14.04 or CentOS 7.

**Comment by geerlingguy** [comment]
Added docs. You will need at least `geerlingguy.mysql` version 1.5.1 to use MariaDB with Drupal VM either on Ubuntu 14.04 or CentOS 7. You can update your roles with `ansible-galaxy install -r provisioning/requirements.yml --force`.
