### ISSUE TITLE
Add Certbot / LetsEncrypt support for automatic SSL certificates

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1251]
### Issue Type

 - Feature Idea

### Summary

I'm currently using [`geerlingguy.certbot`](https://github.com/geerlingguy/ansible-role-certbot) to generate SSL certificates for all my Nginx-based servers, and the way I have that role set up, it is able to be used on any CentOS, Debian, or Ubuntu server to generate certs.

At a minimum, I'd like to add the role to Drupal VM and make it so that it installs certbot and allows configuration via the role variables.

At a maximum, I'd like to make it easy for users to generate a cert for every vhost on their VM—or at least for the main drupal site. One caveat: It's probably best to just do this for production VMs and not local dev (maybe?).

**Comment by oxyc** [comment]
Is it even possible to generate certificates for dev domains? I assume it has to have a valid DNS record

**Comment by geerlingguy** [comment]
@oxyc - Yeah... that's true. So definitely not for local dev. But for production usage, this would rock :)

Working on http://prod.drupalvm.com/ right now, just for testing. We'll see how far I can get by the time MidCamp rolls around next weekend. At some point I need to stop procrastinating on my actual slides/practice by working on Drupal VM itself!

**Comment by geerlingguy** [comment]
Dropping the 4.5.0 milestone, as this will require more work than I can push through with current projects I'm working on. Might be a 5.x thing, or could be in another minor point release.

**Comment by mxr576** [comment]
Any update about this?

**Comment by geerlingguy** [comment]
More options for local dev self-signed certs: https://www.jeffgeerling.com/blog/2017/generating-self-signed-openssl-certs-ansible-24s-crypto-modules

**Comment by geerlingguy** [comment]
I'm working on a chapter on HTTPS and Ansible for Ansible for DevOps currently. After that's complete (hopefully soon!) I will have a few different methods for fully automated local + public certs.

**Comment by betz** [comment]
Love

**Comment by IT-Cru** [comment]
Any news or plans for us on this issue?

I have one site in drupalvm D8 multisite which needs HTTPS on PROD environment. Other sites and local environment is currently not such a pain point. If it needs more time to integrate, I'll check how to get a letsencrypt CERT as workaround for this site only for PROD.

**Comment by geerlingguy** [comment]
@IT-Cru - Not yet; though the certbot role now can automatically generate a new cert on first run, then adds the cron command to keep it updated over time. It's not integrated with Drupal VM yet, but if you're doing infra outside of Drupal VM you can add it in a lot easier now.

One example implementation (with Nginx + Jenkins): https://github.com/geerlingguy/drupal-jenkins-multisite

**Comment by mglaman** [comment]
I start working on this, for prod, based on the Nginx+Jenkins. Hitting

```
TASK [geerlingguy.certbot : Start services after cert has been generated.] ********************************************************************************************************************************************
failed: [162.243.12.18] (item=nginx) => {"changed": false, "item": "nginx", "msg": "Unable to start service nginx: Job for nginx.service failed because the control process exited with error code. See \"systemctl status nginx.service\" and \"journalctl -xe\" for details.\n"}
```

But will update with progress!

**Comment by mglaman** [comment]
I was able to add this to DrupalVM with the following config. However the nginx vhost had bad indentation for first line of extra parameters.


```
nginx_hosts:
  - listen: "80 default_server"
    server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    extra_parameters: |
      return 301 https://$host$request_uri;
  - listen: "443 ssl default_server"
    server_name: "{{ drupal_domain }} www.{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true
    extra_parameters: |
      ssl_certificate /etc/letsencrypt/live/{{ drupal_domain }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ drupal_domain }}/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/{{ drupal_domain }}/fullchain.pem;
      ssl_session_timeout 1d;
      ssl_session_cache shared:SSL:50m;
      ssl_session_tickets off;
      ssl_protocols TLSv1.2;
      ssl_ciphers EECDH+AESGCM:EECDH+AES;
      ssl_ecdh_curve secp384r1;
      ssl_prefer_server_ciphers on;
      ssl_stapling on;
      ssl_stapling_verify on;
      add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload";
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;

# Certbot configuration.
certbot_install_from_source: yes
certbot_repo: https://github.com/certbot/certbot.git
certbot_version: master
certbot_keep_updated: yes
certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook 'service nginx stop' --post-hook 'service nginx start'"
certbot_create_if_missing: yes
certbot_create_method: standalone
certbot_admin_email: "xxx"
certbot_certs:
  - email: "xxx"
    domains:
      - "{{ drupal_domain }}"
certbot_create_standalone_stop_services:
  - nginx
```

**Comment by mglaman** [comment]
@geerlingguy would the next steps be to just open a PR and add

```
- src: geerlingguy.certbot
  version: 3.0.0
```

```
- { role: geerlingguy.certbot, when: '"certbot" in installed_extras', tags: ['certbot'] }
```

```
# Certbot configuration.
certbot_install_from_source: yes
certbot_repo: https://github.com/certbot/certbot.git
certbot_version: master
certbot_keep_updated: yes
certbot_auto_renew_options: "--quiet --no-self-upgrade --pre-hook 'service {{ drupalvm_webserver }} stop' --post-hook 'service {{ drupalvm_webserver }} start'"
certbot_create_if_missing: yes
certbot_create_method: standalone
certbot_admin_email: "{{ certbot_admin_email }}"
certbot_certs:
  - email: "{{ certbot_admin_email }}"
    domains:
      - "{{ drupal_domain }}"
certbot_create_standalone_stop_services:
  - "{{ drupalvm_webserver }}"
```

Then I suppose add this snippet into the vhost templates

```
      ssl_certificate /etc/letsencrypt/live/{{ drupal_domain }}/fullchain.pem;
      ssl_certificate_key /etc/letsencrypt/live/{{ drupal_domain }}/privkey.pem;
      ssl_trusted_certificate /etc/letsencrypt/live/{{ drupal_domain }}/fullchain.pem;
      ssl_session_timeout 1d;
      ssl_session_cache shared:SSL:50m;
      ssl_session_tickets off;
      ssl_protocols TLSv1.2;
      ssl_ciphers EECDH+AESGCM:EECDH+AES;
      ssl_ecdh_curve secp384r1;
      ssl_prefer_server_ciphers on;
      ssl_stapling on;
      ssl_stapling_verify on;
      add_header Strict-Transport-Security "max-age=15768000; includeSubdomains; preload";
      add_header X-Frame-Options DENY;
      add_header X-Content-Type-Options nosniff;
```

**Comment by geerlingguy** [comment]
Pretty much!
