### ISSUE TITLE
Allow provided templates to be extended through template inheritance

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1254]
### Issue Type

 - Feature Idea

### Summary

Trellis has a convention of splitting complicated Jinja2 templates into separete blocks that can be [inherited in child templates](https://github.com/roots/trellis/tree/master/roles/sshd#customize-via-child-templates).

Eg. their nginx vhost template https://github.com/roots/trellis/blob/master/roles/wordpress-setup/templates/wordpress-site.conf.j2

This would be useful especially for the quite opinionated nginx and varnish templates that Drupal VM provides.

**Comment by oxyc** [comment]
One thing to discuss is how fine grained the blocks should be. I opened a PR with an example of a quite fine grained version.

**Comment by geerlingguy** [comment]
So, we have Nginx and Varnish at least. Should we hit Apache as well? That would at least give us all the frontend/webserver stuff. MySQL/Postgres would also be potential candidates, but at this time it seems fewer people have had issues that would be more easily resolved extending templates.

**Comment by geerlingguy** [comment]
Opened #1382 as a follow-up. Going to mark this issue as fixed for a 4.5.0 release, at least.
