### ISSUE TITLE
Document Ansible version requirements

### ISSUE THREAD

**Issue by mchelen** [geerlingguy/drupal-vm#126]
It might be good to state the recommended minimum Ansible version.

When using Ansible 1.7.2 (default Ubuntu 15.04 package) I get the following error:

```
TASK: [geerlingguy.php | Ensure configuration directories exist.] ************* 
failed: [drupaldev] => (item=/etc/php5/apache2) => {"failed": true, "item": "/etc/php5/apache2"}
msg: unsupported parameter for module: follow
failed: [drupaldev] => (item=/etc/php5/apache2/conf.d) => {"failed": true, "item": "/etc/php5/apache2/conf.d"}
msg: unsupported parameter for module: follow

FATAL: all hosts have already failed -- aborting
```

Using version 1.9.1 from the PPA fixes the error.

**Comment by geerlingguy** [comment]
Good idea; the README doesn't really enforce using `pip` to install Ansible, so I should probably be more explicit. I don't want to put a particular version in the instructions, but I would like to make it known that everything assumes you're running the latest version of Ansible, Vagrant, and VirtualBox or VMware.

**Comment by senz** [comment]
1.9.1 still has the problem

```
- name: install docker-py
  pip: name=docker-py vesion=1.1.0
```

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
```

```
msg: unsupported parameter for module: vesion
```

**Comment by mchelen** [comment]
Thanks!
