### ISSUE TITLE
Error playbook.yml': line 129

### ISSUE THREAD

**Issue by demoncash** [geerlingguy/drupal-vm#1260]
- Bug Report / Support Request

Digitalocean Droplet
Ubuntu 16.04.2 x64

`fox@ubuntu:~/drupal-vm-master$ ansible-playbook -i examples/prod/inventory examples/prod/bootstrap/init.yml -e "ansible_ssh_user=root"

PLAY ***************************************************************************

TASK [Install Python if it's not available.] ***********************************
Enter passphrase for key '/home/fox/.ssh/id_rsa':
ok: [207.154.197.109]

TASK [setup] *******************************************************************
ok: [207.154.197.109]

TASK [Create admin user account.] **********************************************
changed: [207.154.197.109]

TASK [Add local SSH public key to admin account authorized_keys.] **************
changed: [207.154.197.109]

TASK [Disable requiretty.] *****************************************************
changed: [207.154.197.109]

PLAY RECAP *********************************************************************
207.154.197.109            : ok=5    changed=3    unreachable=0    failed=0

fox@ubuntu:~/drupal-vm-master$ ssh fox@207.154.197.109
Enter passphrase for key '/home/fox/.ssh/id_rsa':
Welcome to Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-66-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

  Get cloud support with Ubuntu Advantage Cloud Guest:
    http://www.ubuntu.com/business/services/cloud

0 packages can be updated.
0 updates are security updates.

The programs included with the Ubuntu system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Ubuntu comes with ABSOLUTELY NO WARRANTY, to the extent permitted by
applicable law.

To run a command as administrator (user "root"), use "sudo <command>".
See "man sudo_root" for details.

fox@my-vm:~$ exit
logout
Connection to 207.154.197.109 closed.
fox@ubuntu:~/drupal-vm-master$ DRUPALVM_ENV=prod ansible-playbook -i examples/prod/inventory provisioning/playbook.yml --sudo --ask-sudo-pass
SUDO password:
[DEPRECATION WARNING]: Specifying include variables at the top-level of the task is deprecated. Please see:
http://docs.ansible.com/ansible/playbooks_roles.html#task-
include-files-and-encouraging-reuse

 for currently supported syntax regarding included files and variables. This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
ERROR! no action detected in task

The error appears to have been in '/home/fox/drupal-vm-master/provisioning/playbook.yml': line 129, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Build and configure the Drupal site.
    - include_role: name=geerlingguy.drupal
      ^ here
`

Hey. How to fix the error?

**Comment by oxyc** [comment]
You'll need to update your ansible version to 2.2+

**Comment by geerlingguy** [comment]
That's most definitely the issue; make sure you have Ansible 2.2+ installed locally.
