### ISSUE TITLE
Samba share from drupalvm guest to windows Host failed

### ISSUE THREAD

**Issue by fb-multimedia** [geerlingguy/drupal-vm#1265]
### Issue Type

 - Bug Report / Support Request

### Your OS

Host - **Windows** (8.1)
VirtualBox 5.1.10
vagrant 1.9.2
Drupal vm 4.3.1  : ubuntu 14.04
samba 4.3.11-Ubuntu
### Summary

Hello at all
I try to share with samba a directory on my drupal vm that can be accessible in my windows host.
I ever used this solution that work great in other Vbox, simply like this :
I install samba :
`apt-get install samba`
I create my shared directory with rights permissions and owner :
```
mkdir /var/partage
chown -R dev:dev /var/partage
chmod -R 0777 /var/partage
```
I add the vagrant user to samba and give a pass with :
`smbpasswd -a vagrant`

I configure samba :
`sudo nano /etc/samba/smb.conf`
change the workgroup with my windows workgroup :
`workgroup = mshome`
and add at the bottom :
```
[partage]
   comment = /var/partage
   browseable = yes
   path = /var/partage
   read only = no
   directory mask = 0777
   create mask = 0777
   valid users = vagrant
```
I restart samba :
`sudo /etc/init.d/samba restart`

Normaly I should now access in windows (8.1) to my shared repository while connect to \\192.168.88.88\partage but it doesn't work at all.

I have two other vbox, one with debian and another with ubuntu 14.04 (scotchbox) using samba like this and I can browse correctly their shared folder under windows network. so I think it's a problem between samba and drupal vm.

The ufw firewall is disable on the drupal vm.
From windows cmd I can ping 192.168.88.88 and see the server with `net view` command table :
```
C:\VMs>net view
Nom de serveur         Remarque

-------------------------------------------------------------------------------
\\FB-DRUPALVM          fb-drupalvm server (Samba, Ubuntu)
\\FB-MULTIMEDIA
\\VOSTRO-200           Vostron
La commande s'est terminée correctement.
```
But no share
here is my testparm -s command result :
```
vagrant@fb-drupalvm:~$ testparm -s
Load smb config files from /etc/samba/smb.conf
rlimit_max: increasing rlimit_max (1024) to minimum Windows limit (16384)
WARNING: The "syslog" option is deprecated
Processing section "[printers]"
Processing section "[print$]"
Processing section "[partage]"
Loaded services file OK.
Server role: ROLE_STANDALONE

# Global parameters
[global]
        workgroup = MSHOME
        server string = %h server (Samba, Ubuntu)
        server role = standalone server
        map to guest = Bad User
        obey pam restrictions = Yes
        pam password change = Yes
        passwd program = /usr/bin/passwd %u
        passwd chat = *Enter\snew\s*\spassword:* %n\n *Retype\snew\s*\spassword:   * %n\n *password\supdated\ssuccessfully* .
        unix password sync = Yes
        syslog = 0
        log file = /var/log/samba/log.%m
        max log size = 1000
        dns proxy = No
        usershare allow guests = Yes
        panic action = /usr/share/samba/panic-action %d
        idmap config * : backend = tdb


[printers]
        comment = All Printers
        path = /var/spool/samba
        create mask = 0700
        printable = Yes
        browseable = No


[print$]
        comment = Printer Drivers
        path = /var/lib/samba/printers


[partage]
        comment = /var/partage
        path = /var/partage
        valid users = vagrant
        read only = No
        create mask = 0777
        directory mask = 0777
        directory mode = 0777
```

If a specialist of samba share could help It will be great cause I've investigate a lot and no way.

Thanks

**Comment by geerlingguy** [comment]
@fb-multimedia have you looked at https://superuser.com/a/258103 ?

**Comment by geerlingguy** [comment]
SSHFS might also be a good option: https://github.com/dustymabe/vagrant-sshfs#sharing-vagrant-guest-directory-to-vagrant-host---5-of-users

**Comment by fb-multimedia** [comment]
hello geerlingguy,
I've try sshfs with this link https://fedoramagazine.org/vagrant-sharing-folders-vagrant-sshfs/
But performances problem are the same as default for me with timeout on composer...

**Comment by geerlingguy** [comment]
@fb-multimedia - You'd need to probably do a `reverse` mount for it to work well. I'm going through the process of setting up a fresh BLT project this way right now, and will likely blog about it.

If you don't share the files at all (basically disable the synced folder config), then things are _very_ fast :)

**Comment by geerlingguy** [comment]
I got SMB working well... documenting the process now.

**Comment by geerlingguy** [comment]
I'm going to do a full writeup tomorrow, on my blog, and then link to it here and add a link in the Drupal VM docs. It's slightly more complicated than I'd like... and I might consider adding better first-party support inside Drupal VM itself (just so you could avoid doing 2-3 steps by hand when building a new VM) if that is easy enough to do.

**Comment by AMDAndy** [comment]
@geerlingguy "working well" is way more than I could have expected. I tried opening up firewall ports manually when I tried setting it up but that didn't work for me. I'm looking forward to your write up. It sounds very promising!

**Comment by geerlingguy** [comment]
I'm working on this today; hopefully I'll have a blog posted by EOD.

**Comment by fb-multimedia** [comment]
Super ! Merci geerlingguy !
I m impatient to read your blog.
Thanks a lot.

**Comment by geerlingguy** [comment]
Here's the blog post! https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development

(includes a video that's currently uploading... give it 10 or so minutes and it should be up on YouTube).

I'll make sure to update Drupal VM's docs as well before closing this issue.

**Comment by fb-multimedia** [comment]
Super ! grand merci, ça marche ! I 've test and the samba share is working with your settings. The force permissions on the directory was missing on my initial smb.conf :

```
   create mask = 0777
   directory mask = 0777
   force create mode = 777
   force directory mode = 777
   force security mode = 777
   force directory security mode = 777
```
Now the reverse share is OK ! and composer take 3 minutes to install D8 !
Do you think we could install samba in the config.yml with :
```
# Add any extra apt or yum packages you would like installed.
extra_packages:
  - sqlite
  - samba
```
And add a sh script to manage the smb.conf during vagrant up in the futur ?

I'm Very happy to use drupal vm as solid solution for virtual lamp server under windows. 
Thanks again

**Comment by geerlingguy** [comment]
@fb-multimedia - Possibly. I already have a role ([`geerlingguy.samba`](https://github.com/geerlingguy/ansible-role-samba)) that installs Samba and gets it running. It would be nice to allow that role to also manage shares, and once that's in, it would just be a matter of adding `samba` as a new installed_extra...

**Comment by geerlingguy** [comment]
And see related issue in that role: https://github.com/geerlingguy/ansible-role-samba/issues/5
