### ISSUE TITLE
 Is there a Docker version to install and privision DrupalVM to a docker container? 

### ISSUE THREAD

**Issue by laurencefass** [geerlingguy/drupal-vm#1267]
### Issue Type

 - Feature Idea

### Your Environment

```
VBox 5.x
Ansible 2.x
```

### Your OS

 - **Windows** (version)

### Summary

Is there a Docker version to install and privision DrupalVM to a docker container?

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/issues/1206

Also, note that Drupal VM's automated tests run on Docker currently—and all the Ansible roles Drupal VM uses also run inside Docker containers (indeed, I use some for parts of my own infrastructure, like https://github.com/geerlingguy/docker-image-solr ).
