### ISSUE TITLE
Add better documentation for installed_extras varaiable

### ISSUE THREAD

**Issue by mchelen** [geerlingguy/drupal-vm#127]
Commenting out every `installed_extras` causes an error:
```
TASK: [geerlingguy.memcached | Install Memcached.] **************************** 
fatal: [drupaldev] => Failed to template {% if "memcached" in installed_extras %} True {% else %} False {% endif %}: an unexpected type error occurred. Error was argument of type 'NoneType' is not iterable
```

`config.yml`:

```
# Comment out any extra utilities you don't want to install.
installed_extras:
#  - adminer
#  - mailhog
#  - memcached
#  - pimpmylog
  # - solr
#  - varnish
#  - xdebug
#  - xhprof
```
Probably the way I'm supposed to do it is similar to the `extra_packages` section:
```
installed_extras: []
```

**Comment by geerlingguy** [comment]
True, true... that is presumed based on yaml syntax, but we might want to make the documentation line more specific, like "If you don't want _any_ installed extras, set this to an empty list, e.g. `[]`.

**Comment by mchelen** [comment]
Thanks! Saves some headaches for people like me using these config files without enough sleep =)
