### ISSUE TITLE
Find a way to not have to run PHP role for --tags=drupal

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1271]
### Issue Type

 - Feature Idea

### Summary

To make sure the `drupal` tag option worked correctly, I added the `geerlingguy.php` role to the `drupal` tag, I think because there was a webserver var that was set by the PHP role that was used, or maybe a handler.

Basically, since the PHP role takes like 1 minute to run on a prod server (mostly due to the plethora of config files it has to check), I'd rather make it so `--tags=drupal` only runs the drupal role and the bare minimum elsewhere (that way deployments will get run more swiftly).

**Comment by geerlingguy** [comment]
The issue is:

```
RUNNING HANDLER [geerlingguy.php : restart webserver] **************************
fatal: [138.197.108.187]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined. The error was: 'php_webserver_daemon' is undefined\n\nThe error appears to have been in '/Users/jgeerling/Sites/drupalvm-live/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php/handlers/main.yml': line 2, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n---\n- name: restart webserver\n  ^ here\n"}
```

I don't know if we actually need to explicitly restart the webserver... there might be a better way.

**Comment by geerlingguy** [comment]
It's an upstream issue: https://github.com/geerlingguy/ansible-role-drupal/issues/35

**Comment by mglaman** [comment]
The upstream issue was fixed, so we could give this a try!

**Comment by geerlingguy** [comment]
It works :)
