### ISSUE TITLE
www.adminer.org not available

### ISSUE THREAD

**Issue by valentine94** [geerlingguy/drupal-vm#1275]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.0.26r108824
ansible 2.2.1.0
```

### Your OS

 - **macOS** (10.11.6)

### Summary

When I'm trying to do provision for drupal-vm I'm getting a timeout error for adminer role, because www.adminer.org doesn't work

**Comment by geerlingguy** [comment]
I noticed you're running Vagrant 1.9.1 and VirtualBox 5.0.26; both of those versions had some known issues with Drupal VM. Can you upgrade both and try provisioning again?

**Comment by geerlingguy** [comment]
It also looks like the site is a bit slower to respond than normal... I need to file an upstream bug about this; we can increase the timeout so it works more consistently.
