### ISSUE TITLE
Drupal vm ssh time out on ubuntu 16.04

### ISSUE THREAD

**Issue by mapasteper** [geerlingguy/drupal-vm#1276]
### Issue Type

 - Bug Report / Support Request
 

### Your Environment

```
Vagrant 1.9.2
VirtualBox 5.0.24_Ubuntur108355
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

```

### Your OS

 - **Linux** (version)
Ubuntu 16.04.2 LTS

### Full console output

 

$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Importing base box 'geerlingguy/ubuntu1604'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

### Summary

When I try to bring the Vm up. it got stock on ssh auth method.

**Comment by thom8** [comment]
@mapasteper first thing would be to use the latest version of vbox -- https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by geerlingguy** [comment]
@mapasteper - Yeah, in this case, you need to manually download the latest version of VirtualBox 5.1.x—if you're in 5.0.x, VirtualBox doesn't actually tell you there's an update available.

If you must remain on 5.0.x, you will have to manually 'connect the virtual network cable' to make it work with Drupal VM (in the VM's settings in the VirtualBox GUI). But I'd recommend upgrading so it all works automatically :)

**Comment by mapasteper** [comment]
Hey Thom and geerlinguy, thabks for your quick reply.
 I did it indeed, I installed virtualbox-5.1_5.1.18-114002~Ubuntu~xenial_amd64 but I got a different error.
I found a solution. I upgraded vagrant to version 1.9.3 and viratualbox to version 5.0.32.
Now the Vm is running so I'll play around a bit and probably I'll replace beetbox with drupalvm.
My current software version is:

Vagrant 1.9.3
VirtualBox 5.0.32_Ubuntur112930
ansible 2.2.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides

**Comment by thom8** [comment]
@mapasteper would highly recommend using vbox `5.1.x` as you're more than likely going to run into other issues.

**Comment by mapasteper** [comment]
@thom8 I'll remove viratualbox and install version 5.1 from deb package.

**Comment by thom8** [comment]
Also try to keep vbox up to date as they're usually just bug fix releases.

**Comment by thom8** [comment]
You can always just add the `virtualbox` repo and continue to use `apt`

https://www.virtualbox.org/wiki/Linux_Downloads

see Debian-based Linux distributions

**Comment by mapasteper** [comment]
@thom8 I did that, I added the virtualbox to my repo, but I got different errors, I couldn't install it properly.

**Comment by mapasteper** [comment]
@thom8 I upgraded virtualbox to 5.1 from a deb package and everything is running very well.
I'm intalled this one http://download.virtualbox.org/virtualbox/5.1.18/virtualbox-5.1_5.1.18-114002~Ubuntu~wily_amd64.deb

Thanks

**Comment by thom8** [comment]
There might not be much difference but if you're using 16.04 (Xenial) this is probably the best one -- http://download.virtualbox.org/virtualbox/5.1.18/virtualbox-5.1_5.1.18-114002~Ubuntu~xenial_amd64.deb

**Comment by mapasteper** [comment]
@thom8 yeah, that's what I got. Sorry, mistake copying the link on my last post. I just fixed it
