### ISSUE TITLE
GIT 

### ISSUE THREAD

**Issue by itzpraveen18** [geerlingguy/drupal-vm#1277]
no vagrant up for this 

D:\vg>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'geerlingguy♣ntos6' could not be found. Attempting to find and
install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/uri/common.rb:176:in `split': bad U
RI(is not URI?): file:D:/vg/geerlingguy♣ntos6 (URI::InvalidURIError)
        from C:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/uri/common.rb:211:in `

### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

**Comment by geerlingguy** [comment]
@itzpraveen18 - Can you please file a new issue, and fill out all the issue summary fields (e.g. your OS, environment, console output, etc.)?

From the little bit of info here, it looks like you may have something outdated, and `geerlingguy♣ntos6` makes it look like maybe your terminal isn't actually doing the right thing. The box should be `geerlingguy/centos6`.

Finally, it's _really_ hard to get the `centos6` box to work well with all of Drupal VM's features. You'd have much better luck using a more modern OS version like CentOS 7 or Ubuntu 16.04.

**Comment by itzpraveen18** [comment]
thank you so much jeff its working now an one thing i wanna know about
centos 6 why its not running as vagrant up what would be actaull problem
