### ISSUE TITLE
vagrant up and not booting issue 

### ISSUE THREAD

**Issue by itzpraveen18** [geerlingguy/drupal-vm#1278]
If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

**Comment by geerlingguy** [comment]
@itzpraveen18 - When you create a new issue on GitHub (which you did for this issue), there's a template in the comment field that you need to fill in—it gives you a command to run, tells you where to paste certain things, etc. Please read that template and follow all the instructions within. Once you finish doing that, all the sections like 'Your OS', 'Full console output', Summary, etc. should be filled in (see how they're blank above).
