### ISSUE TITLE
Broken link for more about overriding configurations

### ISSUE THREAD

**Issue by ilyar** [geerlingguy/drupal-vm#1279]
### Issue Type

 - Documentation Report

### Summary

Broken link for more about overriding configurations: `http://docs.drupalvm.com/en/latest/other/overriding-configurations/`

https://github.com/geerlingguy/drupal-vm/blame/master/README.md#L45

**Comment by geerlingguy** [comment]
Thanks for reporting this! I fixed it in https://github.com/geerlingguy/drupal-vm/commit/6620b42efc7447870bcc2a741da11abdc6a120cc — entered the wrong issue number in that commit message, though. Oops!
