### ISSUE TITLE
Forwarded port already in use

### ISSUE THREAD

**Issue by robdecker** [geerlingguy/drupal-vm#128]
When I have a VM running, and attempt to start another suspended VM, I'm getting the following error:

```
Bringing machine 'drupaldev' up with 'virtualbox' provider...
==> drupaldev: Checking if box 'geerlingguy/ubuntu1404' is up to date...
Vagrant cannot forward the specified ports on this VM, since they
would collide with some other application that is already listening
on these ports. The forwarded port to 2222 is already in use
on the host machine.

To fix this, modify your current projects Vagrantfile to use another
port. Example, where '1234' would be replaced by a unique host port:

  config.vm.network :forwarded_port, guest: 22, host: 1234

Sometimes, Vagrant will attempt to auto-correct this for you. In this
case, Vagrant was unable to. This is usually because the guest machine
is in a state which doesn't allow modifying port forwarding.
```

A quick Google search provides some differing solutions to this issue. Is there a `config.yml` solution ?

**Comment by geerlingguy** [comment]
This is a Vagrant issue that will occur when you have a suspended VM that used a port that a now-running VM is using, and I don't think there's any simple fix. The best thing is to `vagrant halt` your running VM, then bring up the suspended VM, then `vagrant up` the machine you just halted.

The local ports (e.g. 2200+) are set automatically by Vagrant and it's best to let Vagrant manage them as it sees fit.
