### ISSUE TITLE
Cannot install SOLR when not using shared folders

### ISSUE THREAD

**Issue by xymox12** [geerlingguy/drupal-vm#1280]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.3
VirtualBox 5.1.18r114002
ansible -

```

### Your OS

 - **Windows** 7 Enterprise

### Full console output

The gist below shows the result for ```vagrant provision``` but this also happens on the ```vagrant up```

- https://gist.github.com/xymox12/6a45168d5f19e95a8d3df3224d97258d

### Summary

I have been working towards using the Ubuntu guest on a Windows host without needing shared folders. I am using Samba to help make working on a Windows host bearable (I have seen a recent blog by yourself that you are also using a similar technique.)

I have documented the config.yml and additional scripts of my current setup here:

- https://gist.github.com/xymox12/41eec3c0fa655ad05f20a65f40710843

The first issue I ran into on up was that {{ drupal_composer_install_dir }} was not created when using anything other than the composer projects method - and so the VM creation failed. I have resolved this by adding the pre-provision.sh script (see gist) to create the directories manually.  

The issue I have now is that I cannot add SOLR to the mix via the config.yml without the issue below breaking the install:

```
TASK [geerlingguy.solr : Ensure Solr conf directories exist.] ******************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "The conditional check ''{{ item }}' not in '{{ solr_cores_current.content }}'' failed. The error was: Invalid conditional detected: EOL while scanning string literal (<unknown>, line 1)\n\nThe error appears to have been in '/vagrant/provisioning/roles/geerlingguy.solr/tasks/cores.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Solr conf directories exist.\n  ^ here\n"}
```

SOLR has been downloaded  to /root/solr-5.5.3.tgz and extracted to /root/solr-5.5.3 but no folder has been created at /etc/solr.

Any ideas?

Thanks

**Comment by geerlingguy** [comment]
This was just fixed a couple days ago by this commit: https://github.com/geerlingguy/drupal-vm/commit/866c1dbeb7100eb65d2ee608d5e97c10bf8870b3

I haven't tagged a release with the fix just yet, so the best solution is to switch to using Drupal VM `master` right now, until the tag is fixed. Alternatively, you can patch the files yourself temporarily (based on that commit).

**Comment by attheshow** [comment]
I've tried updating to master to fix the issue above but now I'm getting:

```
TASK [geerlingguy.solr : Ensure core configuration directories exist.] *********
failed: [drupalvm] (item=building-your-library richlandlibrary) => {"changed": true, "cmd": "cp -r /opt/solr/example/files/conf/ /var/solr/data/building-your-library richlandlibrary/", "delta": "0:00:00.047784", "end": "2017-04-07 14:29:14.532033", "failed": true, "item": "building-your-library richlandlibrary", "rc": 1, "start": "2017-04-07 14:29:14.484249", "stderr": "cp: target ‘richlandlibrary/’ is not a directory", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by attheshow** [comment]
Oh, I found the issue. I was missing hyphens in front of my two solr_cores in the config.yml file.

**Comment by geerlingguy** [comment]
@attheshow - Ah yes, that'd do it—if you don't do that the YAML interpreter will make a bit of a mess of the variable!
