### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by 4hmedSamir** [geerlingguy/drupal-vm#1285]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.1
VirtualBox 5.1.18r114002
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.12.4)

### Full console output
My config.yml
https://gist.github.com/4hmedSamir/38f9d6174abfe3e569531a7caa804dfa
### Summary

 I'm getting a 503 error when trying to navigate to my drupal site or Adminer.

**Comment by oxyc** [comment]
One value that sticks out is:

```yaml
drupal_core_path: "~/dev/dvm/sites/code"
```

This should point to Drupal core inside the VM. As you've disabled `drupal_install_site` I dont think this is actually used though so it might be some other issue.

Is there anything interesting in the error logs?

- /var/log/apache2/error.log
- /var/log/php7.1-fpm.log

**Comment by 4hmedSamir** [comment]
> ~/dev/dvm/sites/code
 This is just a new Drupal 7 installation.

apache2/error.log
`[Sat Apr 08 00:08:32.522874 2017] [proxy_fcgi:error] [pid 19224:tid 140035772892928] [client 192.168.88.1:53165] AH01067: Failed to read FastCGI header, referer: http://dashboard.drupalvm.dev/
[Sat Apr 08 00:08:32.522904 2017] [proxy_fcgi:error] [pid 19224:tid 140035772892928] (104)Connection reset by peer: [client 192.168.88.1:53165] AH01075: Error dispatching request to : , referer: http://dashboard.drupalvm.dev/
`
I don't see anything unusual in php7.1-fpm.log

**Comment by oxyc** [comment]
I'm able to reproduce this. Seems to work if I disable XDebug but unfortunately I dont have time to look into it more today.

**Comment by 4hmedSamir** [comment]
Any updates? this seems to be a bug to me. I believe php-fpm and xdebug both are using same port 9000

**Comment by geerlingguy** [comment]
@4hmedSamir - I haven't had any time to take a look, but I am using XDebug with the default setup on a bunch of different Drupal VM instances (for various projects) and am not having the issue. It looks like @oxyc was testing in the PR above, but I don't know if he found anything useful. I won't have time to look into the issue soon, but the only real difference I notice between your setup and my own is the VirtualBox version (you have 5.1.18, and I'm still on 5.1.16).

Can you install the older version and see if maybe that makes a difference? It _shouldn't_, but stranger things have happened with VirtualBox releases.

**Comment by oxyc** [comment]
Just realized the problem. You're installing xhprof which doesn't support PHP 7.1. You should use Tideways instead. http://docs.drupalvm.com/en/latest/extras/tideways/

**Comment by geerlingguy** [comment]
Ah, that'll do it! And yeah, the D7 module is not maintained much anymore, so you'd have to do manual work to get profile runs to happen on a D7 codebase.

**Comment by 4hmedSamir** [comment]
Cool, Thanks!
