### ISSUE TITLE
Update ElasticSearch to 5.x

### ISSUE THREAD

**Issue by IT-Cru** [geerlingguy/drupal-vm#1288]
### Issue Type

 - Feature Idea

### Your OS

 - **Linux** (version)

### Summary

I think it would be nice to have current version of ElasticSearch available. Found some documentation how to install 5.x on debian related systems.

https://www.elastic.co/guide/en/elasticsearch/reference/current/deb.html

Have someone tried to update ElasticSearch to 5.x? Current version 8.x-5.x of D8 ElasticSearch Connector module got more love then the older one for 2.x

**Comment by geerlingguy** [comment]
@IT-Cru - Can you open an issue upstream, in the es role: https://github.com/geerlingguy/ansible-role-elasticsearch

**Comment by IT-Cru** [comment]
@geerlingguy - I see in other repo a PR for this feature request already exists: https://github.com/geerlingguy/ansible-role-elasticsearch/pull/27

**Comment by jamesgrobertson** [comment]
After applying that pull request, I can't get Drupal to build via Composer. I get a segmentation fault when trying to use Composer when logged in to the VM.

**Comment by jamesgrobertson** [comment]
I changed the php_version in my config.yml to 7.0 and it seems to be working now.

**Comment by IT-Cru** [comment]
@geerlingguy : Any news for us on this issue?

Have anyone a hint how to apply the patch for the ansible-role-elasticsearch via composer to current drupal VM? I have no luck yet.

**Comment by jamesgrobertson** [comment]
@IT-Cru What I ended up doing is creating a post-install playbook that installed Elasticsearch 5.x via other roles. I think I used drunomics/ansible-role-elasticsearch which has a dependency on drunomics/ansible-role-java. Docs for using a post-install playbook are here: http://docs.drupalvm.com/en/latest/extending/scripts/#ansible-task-files

**Comment by geerlingguy** [comment]
@IT-Cru and @jamesgrobertson - Note that the upstream `geerlingguy.elasticsearch` role now supports 5.x and 6.x using the new `elasticsearch_version` parameter. Closing this issue, sorry for the delay in getting things updated!
