### ISSUE TITLE
Automate db backup

### ISSUE THREAD

**Issue by robdecker** [geerlingguy/drupal-vm#129]
I'd like to automate database backups. Is something like [ansible-automysqlbackup-role](https://github.com/lyrasis/ansible-automysqlbackup-role) possible? If so, how would I go about adding this functionality?

**Comment by geerlingguy** [comment]
@robdecker - This is something I'd rather leave out of the purview of drupal-vm, as the primary intention is a development environment.

I'd recommend either setting up some sort of cron-based script that `mysqldump`s all databases, or using a service like NodeSquirrel (or something similar but different) with the [Backup and Migrate](https://www.drupal.org/project/backup_migrate) module.

**Comment by robdecker** [comment]
IMO, there is valid reason to have automated db backups in a development environment. Without a backup, if the vm gets destroyed or damaged, I'm without a working site. Sure I have my codebase in a synced folder, but I still need a db.

I could go with a script. What's the preferred method of copying files from the host to the guest during provisioning? Can I create a cron job during provisioning as well?

**Comment by geerlingguy** [comment]
A simple cron job can be created like so (using Ansible's [cron](http://docs.ansible.com/cron_module.html) module):

```yaml
- cron: name="Drupal DB Backup" minute="0" hour="21" job="/path/to/backup-script.sh"
```

And as far as files go, you automatically get a share to the folder containing the Vagrantfile at `/vagrant`, and you can add as many extra `vagrant_synced_folders` as you want. So just add a share to a folder containing the scripts you'd like to run, then add a cron job that runs the backup script at an interval of your choosing.

If you'd like, I would consider adding a new configuration option, `cron_jobs` or something like that, which you could put cron jobs into, e.g.:

```yaml
cron_jobs:
  - {
    name: "Drupal DB Backup",
    minute: "0",
    hour: "21",
    job: "/path/to/backup-script.sh"
  }
```

If you'd like something like that, please file a new issue and I'll see what I can do :)
