### ISSUE TITLE
How to run just a part of provisioning playbook?

### ISSUE THREAD

**Issue by davision** [geerlingguy/drupal-vm#1293]
Is there a way to play just a part of provisioning? For example just nginx vhosts provisioning. I'm running drupal-vm as multi drupal sites environment and constantly adding new sites (virtual hosts). Now I have to run the whole provisioning which takes quite some time. I've searched everywhere but didn't find any sufficient solution.

Thank you for your help!

**Comment by thom8** [comment]
@davision take a look at http://docs.drupalvm.com/en/latest/extending/ansible-args/#run-a-specific-set-of-tagged-tasks

**Comment by davision** [comment]
Thank you for your reply! I'm looking at that, but lacking the information, where to put this ` DRUPALVM_ANSIBLE_TAGS=webserver,database vagrant provision` and how to run it. On that link nothing about that is provided.

**Comment by thom8** [comment]
It's​ an environment variable which you can either set globally or prefix a vagrant command.

So example above is the command you run.

**Comment by geerlingguy** [comment]
@davision - As @thom8 mentioned, you basically prefix the `vagrant provision` command with the environment variable. For example, in my terminal, if Drupal VM is already running, I'd just paste in the command:

```
DRUPALVM_ANSIBLE_TAGS=webserver vagrant provision
```

Then the Ansible playbook will limit itself to just configuring Apache or Nginx (whatever webserver you're using).

I hope this answers your question; if not, please let me know and we can reopen the issue.

**Comment by davision** [comment]
Thank you very much for your answer! All clear now!

**Comment by deepakaryan1988** [comment]
@geerlingguy @davision 
I am getting different type of error.
Can you guys, please help with this? Please refer to screenshot.
![capture](https://user-images.githubusercontent.com/3737867/32438577-015df49e-c311-11e7-8c93-c096600650c1.PNG)

**Comment by FinBoWa** [comment]
@deepakaryan1988 why are you running that command in the projects director? You should run that under D:/drupalvm if thats has the vagrant box. 

Also commenting on a closed issue is really a bad practice > open a new one.

**Comment by deepakaryan1988** [comment]
@FinBoWa Ahh..
Good catch.
Sorry for the late reply, but you are right.
Thanks.
