### ISSUE TITLE
Generating Drupal project regardless of settings.

### ISSUE THREAD

**Issue by mikebell** [geerlingguy/drupal-vm#1296]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.3
VirtualBox 5.1.14r112924
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

Drupal-vm 4.4.2

### Your OS

 - **Linux** (Ubuntu 16.04)

### Summary

Drupal vm is trying to generate a drupal project regardless of settings in my config.yml - https://gist.github.com/mikebell/eaa6b8d626490a5613876a756aaff181

```
build_composer: false
build_composer_project: false
install_site: false
```

https://gist.github.com/mikebell/6745e9b469711ba5ac12edb9bf2bddda

It then hangs there. Am I missing an extra config option to not have the geerlingguy.drupal playbook run?

**Comment by geerlingguy** [comment]
@mikebell - If you're using a new-ish version of Drupal VM, those variables have changed; they all have a `drupal_` prefix now.

See the changelog for 4.3.0 for more details: https://github.com/geerlingguy/drupal-vm/releases/tag/4.3.0

**Comment by mikebell** [comment]
Argh! Really sorry, I should have read the release notes.
