### ISSUE TITLE
Where to add drush/config-extra 

### ISSUE THREAD

**Issue by JohnatasJMO** [geerlingguy/drupal-vm#1297]
### Issue Type
 -Support Request

### Your Environment
Virtualbox

### Your OS
Mac OS 10.11.6

How  to add drush/config-extra in config.yml file?

**Comment by geerlingguy** [comment]
@JohnatasJMO - What do you mean by `drush/config-extra`? You can set these variables in `config.yml`: https://github.com/geerlingguy/ansible-role-drush#role-variables

But anything else would be things you'd need to set up on your own in Drush configuration files or by including them (e.g. as Composer dependencies).

**Comment by JohnatasJMO** [comment]
Noted. I will set up with composer within drush.
