### ISSUE TITLE
Can I specify a different language than English from the start?

### ISSUE THREAD

**Issue by Chameo523** [geerlingguy/drupal-vm#1300]
### Issue Type

 - Feature Idea

### Summary

Is there any way to install Drupal in a different language than English right from the start?
That would save me and probably other people a lot of time.
Thank you for all the work you have done so far.

**Comment by geerlingguy** [comment]
@Chameo523 - Yes, you can set the variable `drupal_site_install_extra_args: "--locale=fr"` (for example, for French). You can add any of the extra site-install options (see this list: https://drushcommands.com/drush-8x/core/site-install/) using that variable.

**Comment by geerlingguy** [comment]
Closing as I think the answer should provide a way to do what you're asking. Thanks!
