### ISSUE TITLE
BDD with behat documentation is broken 

### ISSUE THREAD

**Issue by jeff1985** [geerlingguy/drupal-vm#1304]
### Issue Type
 - Bug Report
 - Documentation Report

### Environment

```
Vagrant 1.9.3
VirtualBox 5.1.18r114002
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Oct 11 2016, 05:20:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)]
```

### OS

 - **macOS** 10.12.4

### Summary

Trying to configure [BDD with Behat](http://docs.drupalvm.com/en/latest/extras/selenium/) using Selenium and Chrome. I have a blank install with the default site as per documentation. My installed_extras is set to:
```
 installed_extras:
  - adminer
  - drupalconsole
  - drush
  - mailhog
  - selenium
```

I created behat.yml and logged into VM with `cd /var/www/drupalvm/drupal` then I try to run `behat`. Here i get errors because autoload.php is missing.

### Full console output
```
vagrant@drupalvm:/var/www/drupalvm/drupal$ behat --init
+d features/web - place your *.feature files here
+d features/bootstrap - place your context classes here
+f features/bootstrap/WebContext.php - place your definitions, transformations and hooks here

vagrant@drupalvm:/var/www/drupalvm/drupal$ behat
PHP Warning:  require(/var/www/drupalvm/drupal/autoload.php): failed to open stream: No such file or directory in /home/vagrant/.composer/vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal8.php on line 31

Warning: require(/var/www/drupalvm/drupal/autoload.php): failed to open stream: No such file or directory in /home/vagrant/.composer/vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal8.php on line 31
PHP Fatal error:  require(): Failed opening required '/var/www/drupalvm/drupal/autoload.php' (include_path='.:/usr/share/php') in /home/vagrant/.composer/vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal8.php on line 31

Fatal error: require(): Failed opening required '/var/www/drupalvm/drupal/autoload.php' (include_path='.:/usr/share/php') in /home/vagrant/.composer/vendor/drupal/drupal-driver/src/Drupal/Driver/Cores/Drupal8.php on line 31
```

**Comment by geerlingguy** [comment]
Please see notes here:

  - https://github.com/geerlingguy/drupal-vm/issues/1305

And here:

  - https://github.com/geerlingguy/drupal-vm/issues/1152

Also, for the `Fatal error: require(): Failed opening required '/var/www/drupalvm/drupal/autoload.php'` error, that sounds like something unrelated to Behat setup—did you run `composer install`? PHP isn't finding your autoload class.

**Comment by kondor9** [comment]
I'm pretty sure, that the problem is caused by a wrong drupal_root setting inside behat.yml file. Setting this parameter to '/var/www/drupalvm/drupal/web' solved my problem.

**Comment by geerlingguy** [comment]
@kondor9 - Ah, that would contribute to the confusion, and why the autoloader couldn't be found.

Note that on my own prod test site, I have it set to `/var/www/drupal/web`, so I think you're right (https://github.com/geerlingguy/drupalvm-live/blob/master/tests/behat.yml#L22).

I'll update the path in the docs: http://docs.drupalvm.com/en/latest/extras/selenium/
