### ISSUE TITLE
Add support for Pantheon Terminus

### ISSUE THREAD

**Issue by paulsheldrake** [geerlingguy/drupal-vm#1307]
### Issue Type
 - Feature Idea

### Summary
It would be really handy to have Terminus as one of the tools that is configurable to install through the config.yml file.

**Comment by thom8** [comment]
@paulsheldrake take a look at https://github.com/hashbangcode/ansible-role-pantheon-cli

**Comment by geerlingguy** [comment]
Also, installation looks fairly simple (at least according to that role): https://github.com/hashbangcode/ansible-role-pantheon-cli/blob/master/tasks/main.yml

I would rather not add support directly in Drupal VM's code, but just a recommendation to maybe add on a pre/post-provision script or task file: http://docs.drupalvm.com/en/latest/extending/scripts/

As a script, it would be:

```
#!/bin/bash
wget -O /usr/local/bin/terminus https://github.com/pantheon-systems/cli/releases/download/[VERSION_HERE]/terminus.phar
chmod +x /usr/local/bin/terminus
```

**Comment by attheshow** [comment]
Here's the latest version that we're using:

#!/bin/bash
cd ~
sudo curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install
echo "alias terminus=/home/vagrant/vendor/bin/terminus" >> .profile
