### ISSUE TITLE
Java 8 support for 12.04/14.04

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#1308]
### Issue Type

 - Feature Idea

### Your Environment

```
5.1.6r110634
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.4)

### Summary

I would like to request support for Java 8 on Ubuntu 12.04/14.04. It can be delivered via the repository `ppa:openjdk-r/ppa` and it would open up support for Solr v6 - among other current java applications.

````
__java_packages:
  - openjdk-8-jdk
````

**Comment by thom8** [comment]
@fubarhouse might already be supported -- https://github.com/geerlingguy/ansible-role-java#example-playbook-install-openjdk-8

```
java_packages:
  - openjdk-8-jdk
```

**Comment by fubarhouse** [comment]
Ahh, so I see - exactly what I expected to occur.

Unfortunately there's no integration here with DrupalVM - the task has to be manually added.

I've just added something very similar to a current vagrant instance.

It would be awesome if such a task was integrated via a configurable boolean or some logic determining the version number - which is what this issue is for.

**Comment by thom8** [comment]
Yeah this role is included in DVM -- https://github.com/geerlingguy/drupal-vm/tree/master/provisioning/roles/geerlingguy.java

**Comment by fubarhouse** [comment]
@thom8 Perhaps I'm not clear enough...

The java role has an example playbook which includes a task for this purpose which isn't found in the task list of the java role.

My proposal is to add that task to DrupalVM in `provisioning/tasks/int-debian` based on given logic or a boolean.

Have I made myself clearer?

**Comment by thom8** [comment]
Ahh sorry, would recommend adding it as a pre provisioning task --> http://docs.drupalvm.com/en/latest/extending/scripts/#ansible-task-files

But would suggest it's better placed to be a conditional task of the java role rather than DVM.

**Comment by fubarhouse** [comment]
@thom8 That is exactly what I was searching for before logging a ticket - thanks!

Feel free to close this one 👍

**Comment by thom8** [comment]
No worries.

We created a generic `apt-repos` role so you could easily add any additional repositories.

https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/roles/beetbox-apt-repos/tasks/main.yml

Also, you should be able to close it, I can't.

**Comment by fubarhouse** [comment]
I've just done some basic testing, I am content with the results, so I'm closing it now.
