### ISSUE TITLE
ImportError: No module named ansible.errors

### ISSUE THREAD

**Issue by nielvrom** [geerlingguy/drupal-vm#131]
When I try to run the command
``sudo ansible-galaxy install -r provisioning/requirements.txt --force`` 

I'm getting the following error 
 
> Traceback (most recent call last):
  File "/Users/myusername/ansible/bin/ansible-galaxy", line 38, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named ansible.errors

What could be the problem of this? Google didn't help me much ...

**Comment by geerlingguy** [comment]
@nielvrom - Can you run `ansible --version` and see what version of Ansible you have installed? It seems like either the version is out of date, or it was installed incorrectly. Worst case, maybe try uninstalling (if you used pip, `sudo pip uninstall ansible`), then reinstall with `sudo pip install ansible==1.9.0.1` (1.9.1 is a little off).

**Comment by nielvrom** [comment]
I uninstalled it & installed version 1.9.0.1. Reinstalling worked but when I run the command again I'm now getting this error:

``Traceback (most recent call last):
  File "/Users/nielsvroman/ansible/bin/ansible-galaxy", line 38, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: cannot import name AnsibleOptionsError``

**Comment by geerlingguy** [comment]
I've never seen that error before, but it seems like the ansible-galaxy command is not picking up other Ansible modules properly. It seems Ansible's installed in your local user account directory rather than in a more universal location like `/usr/bin`; is `/Users/myusername/ansible/bin` in your `$PATH`?

**Comment by geerlingguy** [comment]
Also, Ansible 1.9.2 was just released, so it might be best to completely uninstall Ansible, then reinstall with pip or homebrew, so you get the latest version.

**Comment by saeeda** [comment]
I recently cloned the version v2.0.0-0.3.beta1 and before running the env-setup, I was also getting this error.

Traceback (most recent call last):
  File "./ansible", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named ansible.errors

To correctly setup your environment, run these commands in sequence

	$ git clone https://github.com/ansible/ansible.git
	$ cd ansible
	$ git checkout v2.0.0-0.3.beta1
	$ git submodule update --init
	$ . hacking/env-setup

**Comment by ksingh7** [comment]
@saeeda  i followed your steps but still getting errors

```
teeri:ansible ksingh$ git checkout stable-2.0
M	lib/ansible/modules/core
Switched to branch 'stable-2.0'
Your branch is up-to-date with 'origin/stable-2.0'.
teeri:ansible ksingh$
teeri:ansible ksingh$ git status
On branch stable-2.0
Your branch is up-to-date with 'origin/stable-2.0'.
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   lib/ansible/modules/core (new commits)

no changes added to commit (use "git add" and/or "git commit -a")
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$  git submodule update --init
Submodule path 'lib/ansible/modules/core': checked out '273112c56d29e1955848c8706a8ccbd23d62288d'
teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$ . hacking/env-setup
running egg_info
creating lib/ansible.egg-info
writing requirements to lib/ansible.egg-info/requires.txt
writing lib/ansible.egg-info/PKG-INFO
writing top-level names to lib/ansible.egg-info/top_level.txt
writing dependency_links to lib/ansible.egg-info/dependency_links.txt
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest file 'lib/ansible.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
no previously-included directories found matching 'v2'
no previously-included directories found matching 'docsite'
no previously-included directories found matching 'ticket_stubs'
no previously-included directories found matching 'packaging'
no previously-included directories found matching 'test'
no previously-included directories found matching 'hacking'
no previously-included directories found matching 'lib/ansible/modules/core/.git'
no previously-included directories found matching 'lib/ansible/modules/extras/.git'
writing manifest file 'lib/ansible.egg-info/SOURCES.txt'

Setting up Ansible to run out of checkout...

PATH=/Users/ksingh/ansible-2.0/ansible/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/opt/X11/bin
PYTHONPATH=/Users/ksingh/ansible-2.0/ansible/lib:
MANPATH=/Users/ksingh/ansible-2.0/ansible/docs/man:

Remember, you may wish to specify your host file with -i

Done!

teeri:ansible ksingh$
teeri:ansible ksingh$
teeri:ansible ksingh$ ansible --version
Traceback (most recent call last):
  File "/Users/ksingh/ansible-2.0/ansible/bin/ansible", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: cannot import name AnsibleOptionsError
teeri:ansible ksingh$
teeri:ansible ksingh$
```

**Comment by liuyongvs** [comment]
that is problem of python version!
i came cross that problem, which is solved by changing python version!
from 2.6.6 to 2.7.10

**Comment by sunilmchaudhari** [comment]
Hi, 
@saeeda 
About steps you have provided. I have network restrictions on my linux host. How can do it from source? Can I download it from git and upload it to linux host and run some command?
Please tell me commands to run from source to perform steps you provided.

thanks.
Sunil

**Comment by nagulvali** [comment]
Updating setuptools fixed the issue in virtualenv
