### ISSUE TITLE
'vagrant up' - task is running to execute composer require when values are set to false in config.yml

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1312]
This task: 

`TASK [geerlingguy.drupal : Install dependencies with composer require.] ********`

is running even though I have the following in my config.yml:

```
build_composer_project: false
# Toggling this to `true` would invoke `composer install` with the
# projects own `composer.json` successfully.
build_composer: false
drupal_composer_path: false
```

Drupal VM version: 4.4.1
Vagrant 1.9.2
VirtualBox 
5.1.16r113841
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides

All I want to do is provision the VM and nothing else - why is composer trying to install anything?

**Comment by geerlingguy** [comment]
@kevinquillen - In the 4.3.0 release, all the drupal-related variables were namespaced to split off the Drupal stuff into its own Ansible role; see the release notes: https://github.com/geerlingguy/drupal-vm/releases/tag/4.3.0

Basically, you need to set `drupal_build_composer_project` etc. and it should work the same. Apparently my compatibility shim (which was supposed to allow for those vars to work for the time being) didn't work :D

**Comment by kevinquillen** [comment]
I just noticed that was not in my config.yml. I am using Acquia BLT to
build the project, but wanted to bump up to ubuntu/1604 because I am not on
Acquia for hosting. I set them in and set all to false, replaced my
database and I am good to go now.

**Comment by geerlingguy** [comment]
Good to know! Also, BLT changed the defaults it sets as well in a recent release (8.7.something), so after a composer update for Drupal VM and/or BLT it should also have those changes (if you rebuild the VM).
