### ISSUE TITLE
LDAP

### ISSUE THREAD

**Issue by vibanu** [geerlingguy/drupal-vm#1321]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.1

 - **Windows 10

### Summary

Sorry, I submitted this issue initially without explaining the problem. 

On my drupal installation, I have LDAP module that connects to our department's active directory. The website from the vagrant box is unable to connect to the LDAP server. 

I get the following error: 

```
Error: Call to undefined function ldap_connect() in LdapServer->connect() (line 275 of /var/www/compscisbu/docroot/sites/all/modules/ldap/ldap_servers/LdapServer.class.php).
```

How should we resolve this?

Thanks,
Vibha

**Comment by geerlingguy** [comment]
@vibanu - That looks like it's an error coming from Drupal's LDAP module, and I'm not sure how much I'll be able to help, but maybe `ldap_connect()` comes from some specific PHP extension that's not installed?

**Comment by geerlingguy** [comment]
@vibanu - it looks like you need to install PHP's LDAP extension.

If using Drupal VM with PHP 7.1, try this:

```yaml
php_packages_extra:
  - php7.1-ldap
```

Switch the `7.1` to `7.0` or `5.6` if you're using those versions of PHP. Then run `vagrant provision` and it should be installed and available to the LDAP module.

**Comment by vibanu** [comment]
Okay.



Thank you. Will try this and update.



*From:* Jeff Geerling [mailto:notifications@github.com]
*Sent:* Friday, April 21, 2017 11:08 AM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Mention
*Subject:* Re: [geerlingguy/drupal-vm] LDAP (#1321)



@vibanu <https://github.com/vibanu> - it looks like you need to install
PHP's LDAP extension.

If using Drupal VM with PHP 7.1, try this:

php_packages_extra:

  - php7.1-ldap

Switch the 7.1 to 7.0 or 5.6 if you're using those versions of PHP. Then
run vagrant provision and it should be installed and available to the LDAP
module.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1321#issuecomment-296217185>,
or mute the thread

**Comment by vibanu** [comment]
WORKS!



Thank you.



*From:* Jeff Geerling [mailto:notifications@github.com]
*Sent:* Friday, April 21, 2017 11:08 AM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Mention
*Subject:* Re: [geerlingguy/drupal-vm] LDAP (#1321)



@vibanu <https://github.com/vibanu> - it looks like you need to install
PHP's LDAP extension.

If using Drupal VM with PHP 7.1, try this:

php_packages_extra:

  - php7.1-ldap

Switch the 7.1 to 7.0 or 5.6 if you're using those versions of PHP. Then
run vagrant provision and it should be installed and available to the LDAP
module.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1321#issuecomment-296217185>,
or mute the thread

**Comment by geerlingguy** [comment]
Glad I could help!
