### ISSUE TITLE
--ask-pass requires sshpass tool

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/drupal-vm#1322]
### Issue Type

 - Bug Report / Support Request
 - Feature Idea

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.18r114002
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.11 (default, Jun  2 2016, 08:54:31) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

### Your OS

 - **macOS** (10.11.6)

### Full console output

https://gist.github.com/cdmo/0b54e3817c5fcfbbafa8e123689ec577

### Summary

So, you all can tell me if I'm crazy, but here's what I'm trying to do. I'm trying to run a `drush sql-sync` and an `drush rsync` in my `post-provision`. The problem is that I don't have ssh keys and my server administrator will not allow them. So, `--ask-pass`. I added a line to my `Vagrantfile` just to experiment:

```
    ansible.raw_arguments = ENV['DRUPALVM_ANSIBLE_ARGS']
    ansible.raw_arguments = '--ask-pass'
    ansible.tags = ENV['DRUPALVM_ANSIBLE_TAGS']
```

I could probably just add --ask-pass to my `DRUPALVM_ANSIBLE_ARGS` argument too.

So, I re-ran `provision` and it did indeed ask for my ssh password. But then it failed with the error messages you see above in full console output.

Thoughts?

**Comment by geerlingguy** [comment]
Ansible intentionally doesn't make it easy to use passwords for SSH connections :)

But to get around this, you can install the `sshpass` CLI utility using Homebrew:

```
brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb
```

Have you considered finding a new server administrator? 😉

**Comment by cdmo** [comment]
Sigh. `sshpass` install attempt gives me this error:

```
$ brew install https://raw.github.com/eugeneoden/homebrew/eca9de1/Library/Formula/sshpass.rb
######################################################################## 100.0%
Error: Calling Formula.md5 is disabled!
Use Formula.sha256 instead.
/Users/cdm32/Library/Caches/Homebrew/Formula/sshpass.rb:6:in `<class:Sshpass>'
```
And when running a provision I get the same error as before.

Any ideas?

Also, if you have any Go To Arguments to sys admins on using ssh keys over password authentication, please let me know.

**Comment by geerlingguy** [comment]
@cdmo another option is to build sshpass from source: http://www.hashbangcode.com/blog/installing-sshpass-osx-mavericks

In terms of ssh keys over passwords—they're not _inherently_ more secure (keys are better than password-only in some ways, worse in others...), but they're widely accepted as the easiest way to make sure things are automatable, and they're a lot more convenient (in many ways) than passwords, once you get used to them.

**Comment by cdmo** [comment]
I agree wholeheartedly, far more convenient. I think his answer as to "why passwords" is "security." Requiring a password is probably more secure if you're worried about a workstation being compromised, though remote the chances of that happening may be. I may be able to convince him in that the ssh key access is only to our QA instances - we wouldn't access production that way.

Anyway, sorry for the sidebar! I'll look into installing from source, but if it's too much I may just have the syncing-down-from-QA step be a manual step for us.

Thanks!

**Comment by geerlingguy** [comment]
@cdmo - One other thing to note is that you can (and for the best security, you _should_) set a password on your keys, so you have to either enter the password each time you use the key, or load it into memory using `ssh-agent`.

**Comment by cdmo** [comment]
Are you referring to the passphrase option?

**Comment by cdmo** [comment]
And.. I wonder how that would work using DrupalVM.. like when I attempt run some drush command to sql-sync or the like, if I require a passphrase, would vagrant just hang? Crash? Prompt ? Thanks..

**Comment by geerlingguy** [comment]
@cdmo - Most often you'd get a prompt; but using ssh-agent, you could load the key into the agent, and Vagrant would pick it up automatically (if you're using Drupal VM, at least). Some more info on agent by example: https://unix.stackexchange.com/questions/140075/ssh-add-is-not-persistent-between-reboots
