### ISSUE TITLE
Synced folder type doesn't use default if it's not provided

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#1323]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.3
VirtualBox 5.1.18r114002
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS
 - **macOS** Sierra

### Summary
I recently tried to cleanup my `local.config.yml`  because `vagrant_synced_folders` was getting long and it looked like NFS was the default.

But then when I removed those
`type: nfs` lines from each I noticed something really strange.

I was changing a CSS file and the changes where visible to me on disk and inside the vm, but apache was serving stale and truncated versions of that file.  I `touch`ed the css file inside the VM and apache finally picked up the changes. I've not seen this before and that is the only  difference of note to my config.  

Here's a screenshot of what it looked like:
![unit-custom_css](https://cloud.githubusercontent.com/assets/70129/25294467/31a30d3e-2694-11e7-9bdc-15a793b9df35.png)

**Comment by geerlingguy** [comment]
So you're saying you switched to native synced folders (e.g. by removing the `type` option from each synced folder), and now files are doing weird things and look different inside vs. outside the VM?

It's not entirely clear what is shown on the left side—is that the CSS file as served by Apache, or the file outside the VM on your host?

**Comment by joelpittet** [comment]
Working:
```
vagrant_synced_folders:
  - local_path: ~/Sites/cs6/
    destination: /var/www/sites/cs6
    type: nfs
```

Not working:
```
vagrant_synced_folders:
  - local_path: ~/Sites/cs6/
    destination: /var/www/sites/cs6
```

The left image is the output of an old version of that CSS in the browser (on two different browsers and browser cache cleared to make sure those weren't part of the problem), the right side is the CSS file in my editor.

**Comment by geerlingguy** [comment]
@joelpittet - If you set it as `type: ''`, does that work? I've never tried it entirely without an `nfs` key, so I'm not sure whether that would work or not...

**Comment by joelpittet** [comment]
Setting `type: ''` effectively does what removing the key entirely was doing.  Got some new output in there too instead of the truncating but yeah, not a happy place.

![unit-custom_css](https://cloud.githubusercontent.com/assets/70129/25298072/ef29202a-26a6-11e7-8550-2f735428065b.png)

**Comment by joelpittet** [comment]
I was hoping that the default would kick in from this variable:
`vagrant_synced_folder_default_type: nfs`

**Comment by geerlingguy** [comment]
@joelpittet - Currently, that variable is coupled only to the `type` added per-synced-folder: https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L140

It might be nice to use the default_type variable if it's not set.

**Comment by oxyc** [comment]
Fixed the above commit. If the `type` of an item in `vagrant_synced_folders` is omitted, it will default to the value of `vagrant_synced_folder_default_type`. That's way more logical, thanks!

**Comment by joelpittet** [comment]
Thanks both of you for the quick fix!
