### ISSUE TITLE
Errors while running 'vagrant up' when deploying Drupal on Windows

### ISSUE THREAD

**Issue by alex-hsa** [geerlingguy/drupal-vm#1331]
### Issue Type
 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.3
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.

### Your OS
 - **Windows** 7

### Full console output
Command: vagrant up
https://gist.github.com/alex-hsa/16d9b645eed3588c67bb0cba362ba87c

# Summary
The errors are at the very bottom of the script.
Error #1:

```
TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
fatal: [sfhsa]: FAILED! => {"changed": false, "failed": true, "msg": "github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module"}
```

Error #2

```
PLAY RECAP *********************************************************************
sfhsa                      : ok=209  changed=89   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I ran 'vagrant up' but this time without problems.
However, now I am not able to see the dashboard when going to:
http://dashboard.local.sfhsa.com
```

When using the http://192.168.88.25 instead I see the 'Apache2 Debian Default Page' but no dashboard.

Any suggestion on how to get the VM started?

Thank you very much,
Alex

**Comment by alex-hsa** [comment]
I ran 'vagrant provision' as well but got the same two errors.

Thank you, Alex

**Comment by oxyc** [comment]
You can at least fix it by adding this to your `config.yml`

```yaml
drupal_deploy_accept_hostkey: yes
```

But I'm not sure if @geerlingguy has some other suggested workflow

**Comment by alex-hsa** [comment]
Thank you @oxyc for the tip. 

It occurred to me that my Github repo is currently empty so I set the 'drupal_deploy_repo' to:
drupal_deploy_repo: "git@github.com:acquia/blt.git"

After running 'vagrant provision' now I get the following error:
OSError: [Errno 2] No such file or directory: '/var/www/sfhsa/docroot'

- Is the expectation that the code tree in the 'drupal_deploy_repo' has to have the folder 'docroot'?
- Is it assumed that the code tree in Github will be deployed to Acquia Cloud?

Thank you,
Alex

**Comment by oxyc** [comment]
What does your `config.yml` look like? Do you remember which task it was that issued the error?

Git deployment within the VM would be a bit different than it is for actual deployment. I haven't tried it, but I think you would have to do all the code development within the VM as `vagrant_synced_folders` by default points to the same directory as `drupal_deploy_dir`. Thus checking out blt would overwrite your codebase on the host machine.

**Comment by geerlingguy** [comment]
@alex-hsa - If you're using BLT, you wouldn't want to clone `acquia/blt.git`—that is the source repository for the BLT project, and not actually a BLT-built project itself.

Instead, you would want to either clone an existing project that was created by/uses BLT, or generate a new project using BLT, then push that project to a new GitHub repository, then create a Drupal VM instance that deploys that project into the VM following the process outlined here: https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development

**Comment by oxyc** [comment]
Closing this as it's been a while since it had any activity. I'm assuming @geerlingguy's notes cleared things up.

If you have any further questions feel free to comment and we can re-open it.
