### ISSUE TITLE
Build fails at "Check if site is already installed"

### ISSUE THREAD

**Issue by Gugols** [geerlingguy/drupal-vm#1334]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
DrupalVM 4.4.4
Vagrant: 1.9.3
Virtualbox: 5.1.18 r114002 (Qt5.6.2)
Ansible: 2.3.0.0
```

### Your OS

OSX: 10.10.1 (Yosemite)

### Full console output

Full terminal output: https://gist.github.com/Gugols/23946df69a08d5d1d2f40aaf227808dd
Config.yml: https://gist.github.com/Gugols/b4f3eb6033ffa3c9dea3b162ea073475

### Summary

As you can see from the ending of console report, the box fails to build due to the following error:

>TASK [geerlingguy.drupal : Check if site is already installed.] ****************
>fatal: [md7]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "module_stderr": >"Shared connection to 127.0.0.1 closed.\r\n", "module_stdout": "Traceback (most recent call last):\r\n  >File \"/tmp/ansible_lsB3Sf/ansible_module_command.py\", line 220, in <module>\r\n    main()\r\n  File >\"/tmp/ansible_lsB3Sf/ansible_module_command.py\", line 163, in main\r\n    >os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/var/www/drupalvm/drupal/web'\r\n", >"msg": "MODULE FAILURE", "rc": 0}

Also, when I take a look at md7.dev site I got "Welcome to nginx!" message while I still had selected Apache as server. 
P.S. I destroyed the box beforehand.

**Comment by oxyc** [comment]
Are you certain you have [v4.4.4 which was released yesterday](https://github.com/geerlingguy/drupal-vm/releases/tag/4.4.4)?

Regarding the _No such file or directory_, could you paste your `drupal.composer.json` file. It sounds like maybe it's placing Drupal core in eg. `docroot/`, while Drupal VM looks for it in `web/`.
https://gist.github.com/Gugols/b4f3eb6033ffa3c9dea3b162ea073475#file-config-L74

**Comment by Gugols** [comment]
Yeah, I had forgotten to change the _drupal_core_path_ property. Now it works.

As to nginx, I thought that I had provisioned my box. Maybe I hadn't properly. However, now everything seems to work as expected.
