### ISSUE TITLE
Travis fails on geerlingguy.drupal-console : Run Drupal Console init

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1335]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Travis

### Full console output

> TASK [geerlingguy.drupal-console : Run Drupal Console init.] *******************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": "php /usr/local/bin/drupal init", "delta": "0:00:00.062620", "end": "2017-04-24 01:22:32.724793", "failed": true, "rc": 1, "start": "2017-04-24 01:22:32.662173", "stderr": "", "stderr_lines": [], "stdout": "Could not find Drupal in the current path.", "stdout_lines": ["Could not find Drupal in the current path."]}

### Summary

https://travis-ci.org/geerlingguy/drupal-vm/jobs/225029757#L1304

**Comment by oxyc** [comment]
Restarted a travis build for master to check if it's upstream https://travis-ci.org/geerlingguy/drupal-vm/builds/225003977

**Comment by oxyc** [comment]
https://github.com/hechoendrupal/drupal-console/issues/3279

**Comment by geerlingguy** [comment]
https://github.com/hechoendrupal/drupal-console/issues/3280

**Comment by geerlingguy** [comment]
Haha, @oxyc you beat me by a couple minutes!

**Comment by jmolivas** [comment]
@geerlingguy @oxyc `init` command is no longer valid.

**Comment by geerlingguy** [comment]
Opened https://github.com/geerlingguy/ansible-role-drupal-console/issues/11 upstream in the role repo.

@jmolivas - Is there another command that should be substituted? Or do we not need to run any setup command anymore... just place the .phar in the right location and we're done?

**Comment by jmolivas** [comment]
Exactly @geerlingguy no more setup command to run, since DrupalConsole should be installed per site now.

The `phar` is only a launcher tool now.

**Comment by ArtuGit** [comment]
So we should exclude `drupalconsole` from `installed_extras`?

**Comment by oxyc** [comment]
For now yes.

**Comment by geerlingguy** [comment]
@oxyc - So is the solution we just pull `drupalconsole` from installed extras entirely (and drop the role) and then recommend that if someone wants to use it, they should do so via Composer per Drupal project?

I could then mark the `geerlingguy.drupal-console` role as deprecated, if that's the case.

**Comment by oxyc** [comment]
I guess it could still be used as a global using `drupal --root=/var/www/drupalvm/drupal`, or for projects that do not use Composer. In which case the fix is to just drop the `drupal init` task as it's not required anymore.

**Comment by geerlingguy** [comment]
Pushed the fix. Hopefully builds start passing 🤞🏼
