### ISSUE TITLE
Breaking change between 4.3.1 and 4.4.5

### ISSUE THREAD

**Issue by dwkitchen** [geerlingguy/drupal-vm#1341]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.3
VirtualBox 5.1.20r114629
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]

```

### Your OS

 - **macOS** 10.12.4

### Summary

Using 4.3.1 Drupal site works as expected

Using 4.4.5
Tested both

- Update from 4.3.1 and run `vagrant provision`
- `vagrant destroy` then `vagrant up`

Accessing site: "502 Bad Gateway"
`drush @alias status`: `env: '/usr/local/bin/drush': No such file or directory`

**Comment by oxyc** [comment]
Could you post your `config.yml`? And possibly the output form running `vagrant provision`.

**Comment by dwkitchen** [comment]
config.yml:

```
drupal_install_site: false
drupal_build_composer_project: false
drupal_core_path: "/var/www/drupalvm/web"
drupalvm_webserver: nginx
installed_extras:
  - adminer
  - blackfire
  # - drupalconsole
  # - elasticsearch
  - mailhog
  # - memcached
  # - newrelic
  # - nodejs
  - pimpmylog
  - redis
  # - ruby
  - selenium
  # - solr
  - varnish
  - xdebug
  - xhprof
```

My terminal has doesn't have enough scroll back let me re-run

**Comment by oxyc** [comment]
You need to add `drush` to `installed_extras`. This was actually a breaking change back in [4.0.0](https://github.com/geerlingguy/drupal-vm/releases/tag/4.0.0).

**Comment by dwkitchen** [comment]
Explains drush not working, but not why the site gives 502 error. I will test and report back

**Comment by dwkitchen** [comment]
Drush status now reports:

```
bash: line 1: 25621 Segmentation fault      env COLUMNS=268 /usr/local/bin/drush --uri=eprc.dev --root=/var/www/drupalvm/web core-status 2>&1
```

**Comment by oxyc** [comment]
Try removing XHProf as Drupal VM now defaults to PHP 7.1 which XHProf doesn't support. You can use [Tideways](http://docs.drupalvm.com/en/latest/extras/tideways/) instead. Note that simply removing it from the list of `installed_extras` and provisioning won't uninstall it, you need to either run `vagrant destroy && vagrant up` or manually remove the xhprof conf files from `/etc/php/7.1/*`

**Comment by dwkitchen** [comment]
@oxyc Thanks, working now. I will look at Tideways but I'm trying to get a corporate account for Blackfire.

**Comment by oxyc** [comment]
Great! Alright, that's probably better. As long as you're on D8 with the latest XHProf module Tideways works as a drop in replacement of XHProf though (unfortunately D7 version of the XHProf module doesn't support it).
