### ISSUE TITLE
ImageMagick as extra package

### ISSUE THREAD

**Issue by Niklan** [geerlingguy/drupal-vm#1344]
### Issue Type

 - Feature Idea

### Summary

It will be great, if we can specify `imagemagick` package in `installed_extras` by needs. Ubuntu server and CentOS 7 have this package by default (I'm not sure, but i rember on DO droplets they was preinstalled), most, or all hosting providers also have `imagemagick` installed on servers and accesible to everyone.  But default ubuntu box used by Drupal VM is not installed it.

It's great tool for compressing the images as [Google recommend it](https://developers.google.com/speed/docs/insights/OptimizeImages) (`convert` it's cli command from `imagemagick`), instead of default GD2 from core.

There are several modules on drupal.org with many sites using them:

- https://www.drupal.org/project/imagemagick — 23k
- https://www.drupal.org/project/imageapi_optimize — 11k

They don't work together, so it's safe to say is around at least 34k sites using imagemagick library from their OS's. 

Ubuntu installation

```bash
apt-get install imagemagick
```

CentOS 7 installation (without remi repo)

```bash
yum install imagemagick
```

**Comment by thom8** [comment]
@Niklan you can use `extra_packages ` -- https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L216

eg.

```
extra_packages:
  - imagemagick
```

**Comment by Niklan** [comment]
OH! Missed it, thank you.
