### ISSUE TITLE
Nginx response header error when Drupal's new Cache Tags value is large

### ISSUE THREAD

**Issue by pixeldust** [geerlingguy/drupal-vm#1345]
### Issue Type

 - Support Request

### Summary

Nginx throws response header too big error with Drupal 8 pages that produce a large number of Cache Tags in the header.

```
*2 upstream sent too big header while reading response header from upstream
```

The new Cache Tags headers (`X-Drupal-Cache-Tags`) are quite extensive for a site I'm working with. These appear to be overflowing the default buffer size for Nginx and causing a 502/Bad Gateway error.

The problem can be solved by increasing the buffer size in the nginx conf. I've found the following lines work together to do the trick,

```
fastcgi_buffers 16 16k;
fastcgi_buffer_size 32k;
```

I'm wondering if you have come across this issue before and how you addressed it. It looks like these cache tags are causing a certain amount of debate right now.

It's likely I need to automate this additional config to sit on top of drupal-vm so other developers can just start without having to do any manual configuration. I see two possible routes I could use to add these settings to the nginx conf,

1. Use `post_provision_task` to run an additional Ansible script to do the task, or

2. Run a different playbook via `Vagrantfile.local`.

Any feedback you might have could be useful and appreciated. Thanks.

**Comment by oxyc** [comment]
You can also add them to `extra_parameters` for the `nginx_hosts` https://github.com/geerlingguy/drupal-vm/pull/1156#issuecomment-278053767

**Comment by pixeldust** [comment]
@oxyc Thank you for the quick response and also apologies for not searching the issues hard enough myself and seeing the previous post and solution. I'd been looking through the Ansible role but not spotted the `extra_parameters` option.
