### ISSUE TITLE
Use more recent Node.js version

### ISSUE THREAD

**Issue by yannickoo** [geerlingguy/drupal-vm#1348]
### Issue Type

Feature Idea

### Summary

It feels weird that the default Node.js version in [`default.config.yml`](https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L284-L285) says `0.12`. The current LTS version would be `6.x` so I would suggest to stick to a more recent version so you don't need to increase the version manually. Also mentioning `7.x` in the comment could be helpful.

**Comment by geerlingguy** [comment]
This was fixed by #1353 - I didn't realize it was still stuck back on 0.12!

**Comment by yannickoo** [comment]
Cool 💪
