### ISSUE TITLE
Add Yarn to global NPM packages

### ISSUE THREAD

**Issue by yannickoo** [geerlingguy/drupal-vm#1349]
### Issue Type

Feature Idea

### Summary

When using Node.js inside a Drupal VM you want to have a npm package manager available but `npm` is slow so people want to install `yarn` but cannot figure it out how to add it quickly to `nodejs_npm_global_packages` (just guessing because I also forgot the `name` first).

 So what about switching from `nodejs_npm_global_packages: []` to

```
nodejs_npm_global_packages:
  - name: yarn
```

_I can totally understand if this is a customization you don't want to have in `drupal-vm` but I had to do this in every project because themes are using tools `gulp` etc. nowadays so `yarn` and a recent Node.js version (#1348) are always necessary._

**Comment by geerlingguy** [comment]
I think I'd rather not include yarn at this time; every time I've considered adding a front-end library, I've sat and waited on the decision, and 3-6 months later, the tool of choice has changed.

Maybe instead, we could add a link to the node.js role docs, or a page in Drupal VM's docs explaining the variable better? That way no matter what tool(s) are needed per project, they can be added without someone having to figure out it needs to be `name: yarn` as an array item.

**Comment by geerlingguy** [comment]
@yannickoo - Note that I made a change to the upstream role so you can now install packages globally by name or with a structured name/version object:

```yaml
nodejs_npm_global_packages:
  - yarn # this is equivalent to `name: yarn` now!
```

See: https://github.com/geerlingguy/ansible-role-nodejs/issues/67

**Comment by yannickoo** [comment]
This is awesome! <3
