### ISSUE TITLE
Run post-provision scripts after post-provision tasks.

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#1354]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.6
VirtualBox 5.1.14r112924
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.12.4)

### Full console output
````
n/a
````

### Summary
I've been trying to minimize my development environment and integrate as much as possible with DrupalVM, and I've come to the point where I have a custom task to run a post-provision script because the script is configured to run before the post-provision tasks...

So to get this job done, the script runs twice.

Because my post-provision tasks include custom roles there are changes to the file system that aren't present when the post-provision scripts are executed initially.

Would it be considerable to run the custom scripts after the custom tasks, or is this something that would be dismissed?

**Comment by thom8** [comment]
I'd suggest using one or the other rather than both.

You can call scripts in an ansible with the script [module](http://docs.ansible.com/ansible/script_module.html).

Custom tasks are far more flexible + you have access to all the ansible variables :)

**Comment by thom8** [comment]
There's also [pre tasks](https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/playbook.yml#L29) if you need to run anything before the main roles.

**Comment by fubarhouse** [comment]
Fair enough, I might just include the task instead of the configured script.

Is it documented somewhere that the recommended configuration is for one of these two features, but not both for a given reason - or did I miss this information?

**Comment by thom8** [comment]
@fubarhouse I guess in some cases it might be feasible to use both but just to make it easier to manage I suggest just using one.

**Comment by fubarhouse** [comment]
Yeah, I'll close this one off. I don't believe the order is logical but I'm happy here...

**Comment by thom8** [comment]
NW, but if they aren't interdependent it shouldn't matter what order it's run..
