### ISSUE TITLE
Xdebug not enabling for webserver

### ISSUE THREAD

**Issue by welly** [geerlingguy/drupal-vm#1355]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.3
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 18 2016, 07:03:39) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (10.12.4)

### Full console output
config.yml - https://gist.github.com/welly/ea9534e0947972a8f5e145498b91318b
php -i (from cli) - https://gist.github.com/welly/5eea68665c1974ba94202448bdaedd29
phpinfo() (from dashboard) - https://gist.github.com/welly/787fa6db5d2bdc1c991b8f7ff64ad846

### Summary
For some unknown reason, xdebug is not enabled in either Apache or Nginx. Running php -i from the CLI shows it enabled and the 20-xdebug.conf file is showing in /etc/php/7.0/fpm/conf.d

I've just copied/pasted the contents of /etc/php/7.0/fpm/conf.d/20-xdebug.conf into /etc/php/7.0/fpm/php.ini and now xdebug is working.

Very puzzling!

**Comment by thom8** [comment]
@welly if `/etc/php/7.0/fpm/conf.d/20-xdebug.conf` is getting created but not loaded it might be the file permissions/ownership, looks like the other conf files are being picked up.

**Comment by thom8** [comment]
Otherwise the fpm reload is being skipped or failing, would you be able to post a dump of the provisioning output?

**Comment by geerlingguy** [comment]
@welly also, does doing a `vagrant reload --provision` fix it?

**Comment by welly** [comment]
Thanks for the advice guys, something has worked because it appears to be working now! Perhaps the vagrant reload --provision did the trick although I think I ran that before. But anyway, thank you!

**Comment by thom8** [comment]
@welly no worries `vagrant reload --provision` is always a handy one to remember when you run into any issues 😄
