### ISSUE TITLE
Add unique Drupal VM machine name identifier for easier management of multiple instances

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#136]
## Summary

Add a new Drupal VM machine identifier that can be used for multiple purposes:

  - [x] The Vagrant machine name (so it's customizable as requested in #133).
  - [x] The drush aliases file that's generated by Drupal VM (so multiple environments don't overwrite each others' alias files.

## Original Issue Report

Consider adding in a Drupal VM identifier or leveraging the local URL to not overwrite Drush Aliases.

**Comment by frob** [comment]
This could be related to #133

**Comment by geerlingguy** [comment]
@frob - Somewhat, yes... I was thinking of having a `vagrant_machine_name` identifier. For most people, there would be no need to change this, and I would likely default to `drupalvm`. But some use cases (like I know @nerdstein is using Drupal VM in an automated way for multiple projects on one developer workstation) would be able to have multiple instances without any conflict (and in a more logical layout) by using a machine-specific identifier.

**Comment by geerlingguy** [comment]
Updated title to reflect broader scope, and wrap #133 into this issue.

**Comment by geerlingguy** [comment]
Fix incoming...
