### ISSUE TITLE
Drupal console 'undefined method' error on a new drupalvm.

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1360]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

### Your OS
 - **macOS** (version)

### Full console output
https://gist.github.com/betz/7c8f5a794bc4bba46da04d130059b4c7

### Summary
Freshly deployed Drupal VM, drupal console gives a undefined method ::getVendorDir() error.

**Comment by geerlingguy** [comment]
This looks like a problem with Drupal Console, not with Drupal VM:

```
Fatal error: Uncaught Error: Call to undefined method Drupal\Console\Core\Utils\DrupalFinder::getVendorDir()
```

I'd recommend posting an issue there: https://github.com/hechoendrupal/drupal-console/issues

**Comment by geerlingguy** [comment]
And one other note, just looking at the error message, it seems like Drupal Console isn't seeing a vendor directory in your Drupal installation... can you try running `composer install` in your project's root directory and then try again?

**Comment by betz** [comment]
Thanks for the feedback.
About the project root, is this
'/var/www/drupalvm/drupal' or '/var/www/drupalvm/drupal/web' in drupalvm?

following command does not work in the drupal root:
`composer require drupal/console:~1.0`
with error:
> Problem 1
    - The requested package drupal/console ~1.0 is satisfiable by drupal/console[1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.0-rc1, 1.0.0-rc10, 1.0.0-rc11, 1.0.0-rc12, 1.0.0-rc13, 1.0.0-rc14, 1.0.0-rc15, 1.0.0-rc16, 1.0.0-rc17, 1.0.0-rc18, 1.0.0-rc19, 1.0.0-rc2, 1.0.0-rc3, 1.0.0-rc4, 1.0.0-rc5, 1.0.0-rc6, 1.0.0-rc7, 1.0.0-rc8, 1.0.0-rc9] but these conflict with your requirements or minimum-stability.

it works in '/var/www/drupalvm/drupal' though.
But how come this does not work in the drupal root? Confusing.

**Comment by thom8** [comment]
@betz drupal console doesn't have a stable release and therefore you either need to specify `"minimum-stability": "dev"` inside your project `composer.json` or run `composer require drupal/console:@dev`.

Anyhow this should only be run in the root (where you composer.json is) which by default is `/var/www/drupalvm/drupal` not the web directory.

**Comment by thom8** [comment]
Created issue RE: minimum-stability -- https://github.com/hechoendrupal/drupal-console/issues/3303
