### ISSUE TITLE
Debug while tunneling to local VM

### ISSUE THREAD

**Issue by jzavrl** [geerlingguy/drupal-vm#1361]
I've setup tunnelling (ngrok) so I can access my local installation through a public address (need for an external service to work properly).

Now the only thing missing is the debugger. For some reason, PHPstorm doesn't connect to it. I've tried several things from changing the server in PHPstorm, setting the xdebug.remote_host differently. Now I might have been doing this all wrong, but nothing came up.

Has anyone made this work yet and if so how? Or at least what direction should I be looking at?

Thanks

**Comment by geerlingguy** [comment]
I don't personally use PHPStorm much, so haven't tested Xdebug with it for some time, but I know a _lot_ of people do... 

Can you use a local address (and not tunneling through ngrok) for the debug connection? I'd imagine ngrok doesn't allow the debugger to work correctly between an IDE and the site in question, or would take a lot more work to use.

The docs (http://docs.drupalvm.com/en/latest/extras/xdebug/) seem to indicate that, if you're using the defaults, all you need to do is make sure to set `php_xdebug_idekey: PHPSTORM` (which is the default).

**Comment by jzavrl** [comment]
If I'm using the local address (e.g. project.dev or similar that VM has provided me initially) it works.

I've also had to change the Xdebug settings in config.yml to the following:
`php_xdebug_default_enable: 1
php_xdebug_remote_autostart: 1
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256`

With this it connects instantly. Only when I start ngrok it doesn't.

**Comment by jasonawant** [comment]
Hi @jzavrl,

Try disabling the xdebug.remote_connect_back.  I have this following note for myself. see if that helps. You can add php_xdebug_remote_connect_back: 0 to config.yml

> You may experience an issue with the xdebug.remote_connect_back configuration when it redirects to IP address found in $_SERVER['HTTP_X_FORWARDED_FOR'], which is added by ngrok. Typically xdebug connects to 10.0.2.2:9000 per configuration in xdebug.ini. Instead xdebug will use the HTTP_X_FORWARDED_FOR value as observed in the /tmp/xdebug.log file.

Read more about the option, https://xdebug.org/docs/all_settings#remote_connect_back. It's not necessary to use.

**Comment by jzavrl** [comment]
Hi @jasonawant,

I've tried your suggestion, but no luck. If I set `xdebug.remote_connect_back: 0`, Xdebug doesn't work for Ngrok nor for the original VM domain. So I guess this option needs to stay enabled.

**Comment by jasonawant** [comment]
Hi @jzavrl, 

I really think that option needs to be disabled. The docs state
> If enabled, the xdebug.remote_host setting is ignored and Xdebug will try to connect to the client that made the HTTP request. It checks the $_SERVER['HTTP_X_FORWARDED_FOR'] and $_SERVER['REMOTE_ADDR'] variables to find out which IP address to use.

Also, have you reviewed the xdebug log file? Anything there that is helpful? You can find the log file path found in xdebug.remote_log value.

I think in our recent working example using a multi-site setup, we used sites.php to map the ngrok subdomain to the site domain. Not sure if that's something that would be helpful or not, but I thought I'd mention it.

Also, are you using break at first line phpstorm option to see if it breaks, but just not at a breakpoint? This would indicate an issue with file mapping.

**Comment by thom8** [comment]
@jzavrl also make sure the port is open for the xdebug connection, by default xdebug uses `9000`

**Comment by jzavrl** [comment]
Thanks all, I'm still working on this. The ports should be fine since I can debug just fine when not on the Ngrok domain. I've reviewed the logs. This is what I get once I load a page on Ngrok domain:

`I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Remote address found, connecting to 178.216.60.253:9000.
W: Creating socket for '178.216.60.253:9000', poll success, but error: Operation now in progress (29).
E: Could not connect to client. :-(`

And this after using the initial VM domain:

`I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 192.168.20.1:9000.
I: Connected to client. :-)`

It's like you said @jasonawant, Ngrok uses `HTTP_X_FORWARDED_FOR` and the value of `178.216.60.253`. Whereas if using the initial `REMOTE_ADDR` and value of `192.168.20.1` works just fine then. Unfortunately for me, I'm a bit lacking in this department to know what exactly does this mean or what to do :(

**Comment by jzavrl** [comment]
Well, would you look at that. I've used the IP address provided by Ngrok, which was `178.216.60.253` and put that into my `/etc/hosts` inside the VM's initial block and set it to resolve to the initial VM domain. And now Xdebug connects :)

Now the only concern I have is how to make this a bit more flexible. If I restart Ngrok, I'll be assigned a new IP and so I'll have to edit my hosts file again.

And also - how do you get the IP Ngrok is providing, without looking into the xdebug.log? :)

**Comment by jasonawant** [comment]
Hi @jzavrl,

What is the xdebug.remote_host value? I think this value if set, will provide a more consistent connection regardless of the HTTP_X_FORWARDED_FOR value provided by the remote_connect_back option.

I have xdebug.remote_host set to 10.0.2.2.

**Comment by jzavrl** [comment]
@jasonawant, that was it!

Set the xdebug.remote_connect_back to 0 and then xdebug.remote_host to 10.0.2.2. like you suggested and Xdebug is getting picked no matter the domain.

Closing the issue and thank you!

**Comment by geerlingguy** [comment]
Thanks for confirming this worked!
