### ISSUE TITLE
Solr 3.6.2 fails to start

### ISSUE THREAD

**Issue by generalredneck** [geerlingguy/drupal-vm#1362]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.0.32r112930
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** Sierra (10.12.4 (16E195)

### Full console output

https://gist.github.com/generalredneck/5264d5890e15521111a8b1c688fab6bb

![image](https://cloud.githubusercontent.com/assets/526491/25912063/a75a67b6-357b-11e7-9158-05c1ba28a6e6.png)

### Summary

I'm trying to install solr 3.6.2 because to my understanding that is the same version Pantheon uses. By looking at the configuration in default.config.yml and what is in the readme over at ansible-solr... I think I only need to change the version. I've destroyed and rebuilt my vm just in case but I"m still having the problem where solr hasn't seemed to start up and when I try to run `sudo service solr restart` I get the error in the screenshot above. Any suggestions?

**Comment by geerlingguy** [comment]
@generalredneck - The short term workaround would be to use `4.1.10`, as that version is the closest version to 3.6.x that I know should work out of the box.

Note that the tests for the Solr role seem to be passing in isolation for 3.6.2: https://github.com/geerlingguy/ansible-role-solr/blob/master/tests/test-solr-3.yml (most recent test pass: https://travis-ci.org/geerlingguy/ansible-role-solr)

**Comment by geerlingguy** [comment]
Ah, one other thing—can you upgrade to VirtualBox 5.1.x? I noticed you're still on 5.0.x, and I do know that it has caused very strange and inexplicable errors (with other components of Drupal VM) before.

**Comment by generalredneck** [comment]
Did the upgrade to 4.1.10 just to get things going and seems like that did work out. that at least got me unblocked.

When I was looking... it appears that 3.x really didn't have a bin directory and a solr executable in there... but didn't investigate too hard.

**Comment by geerlingguy** [comment]
Yeah, unfortunately it's been more than a year since the last time I was testing things out with 3.x, and right now I'm working on a plan to deprecate 4.1.x and move to 5.x or 6.x for most of my infra.

**Comment by geerlingguy** [comment]
I'm going to close out this ticket, if only for the fact that I'm trying to avoid spending too much time supporting super-old versions of software in my projects... basically if you need a version this old, you're on your own to debug getting it going.

Note, however, that my Solr Docker container supports 3.6.2 (because of this one super old Magento 1.x site I run... ick!): https://hub.docker.com/r/geerlingguy/solr/
