### ISSUE TITLE
Git error on Windows 10

### ISSUE THREAD

**Issue by codeyy** [geerlingguy/drupal-vm#1363]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.4
5.1.22r115126
'ansible' is not recognized as an internal or external command, operable program or batch file.

### Your OS

 - **Windows** 10 Pro 64-bit

### Full console output

https://gist.github.com/codeyy/94bdf6e856e92aae567ac9cab13c9a24

### Summary

I followed the video from mister Jeff Geerling, from the blog post "Drupal VM on Windows - a fast container for BLT project development". That means I'm in a Windows 10 environment, working from Cmder (running as admin). Everything seems to be working fine, just the Git part I can't seem to get to work (see above). 

Since the rest  was provisioning well, I'm assuming the ansible error you can see in the environment specifications is related to the OS?

When you look at the full console output, the weird part in the message is "/usr/bin/git clone --origin origin '' /var/www/oldtimertime", I would have expected to see the Git location between those two quotes? It's a personal (and private) Git environment so I prefer not to paste the details here, but let's say for this example it is "username@git.location.com:subfolder/projectname.git"

I tested out the Git connection manually by making a SSH connection to the host with the username specified, and that works without a login prompt, so my SSH keys and all that are also fine. 
The git folder location that is behind the : works as well, I can do a change directory to the git folder from the folder I am in when I login.

Am I missing something? I'm puzzled...

**Comment by geerlingguy** [comment]
My best guess is that you may not have SSH Agent forwarding fully configured so the SSH/Git commands can use your SSH keys inside the VM.

Did you download and configure Pageant? It has to be running actively in order for Vagrant to use your SSH key inside the VM; if it's not running, you need to get it running, then also run `vagrant halt` and `vagrant up` to bring up the VM with the key loaded next time.

See this section of the guide: https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development#pageant

**Comment by codeyy** [comment]
The man is always right... Thanks a lot, it seems I need to look to autostart it on boot so I don't forget it anymore ;-)

A few more errors to fix, but it's up and running now!

**Comment by geerlingguy** [comment]
Nice, glad I could help!

**Comment by geerlingguy** [comment]
Also, note that the next version of Vagrant might have it fixed so you can just use `start-ssh-agent` inside Cmder—that is much easier for me than launching/configuring Pageant!
