### ISSUE TITLE
Dynamic ip address

### ISSUE THREAD

**Issue by jayusa123** [geerlingguy/drupal-vm#1365]
### Issue Type
 - Feature Idea

### Your Environment
```
Vagrant 1.9.2
VirtualBox 5.1.18r114002
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.12.4)

### Summary
I've seen other implementations of vagrant that dynamically assign an ip address upon provisioning. Has there been any thought about implementing that for DrupalVM instead of the hardcoded 192.168.88.88 address?

Thanks!

**Comment by oxyc** [comment]
You can use the `vagrant-auto_network` plugin if you set `vagrant_ip: 0.0.0.0`.

https://github.com/geerlingguy/drupal-vm#3---configure-your-host-machine-to-access-the-vm

**Comment by geerlingguy** [comment]
@jayusa123 - Exactly as @oxyc says, auto_network is the best option if you'd like it to be dynamic. Otherwise, you can also change the IP to whatever you'd like (as long as it's a private network IP and doesn't conflict with something else on your host machine).

**Comment by geerlingguy** [comment]
Closing this as I think it's been answered; but please let me know if you'd like to keep it open and continue the discussion!

**Comment by jayusa123** [comment]
Thanks for the heads up. I'll check out auto_network.

**Comment by jayusa123** [comment]
@oxyc, your suggestion works perfectly. Thanks!

**Comment by jayusa123** [comment]
Oh, actually. I do see one small issue: 0.0.0.0 is shown in the completion message:
```
==> my_site: * Visit the dashboard for an overview of your site: http://dashboard.my_site.dev (or **http://0.0.0.0**)
==> my_site: * You can SSH into your machine with 'vagrant ssh'.
==> my_site: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com
```

**Comment by oxyc** [comment]
Yeah, I personally felt that it wasn't worth making that message 100% correct under all circumstances. It's even using `vagrant_hostname` which might not actually be mapped to a virtual host. Also can't guarantee that the user uses http, they might be using https only. If someone wants they can override the message and set the correct host/ip.

If it was a very minor code change to improve, I'd say it worth it, but otherwise I personally don't consider it's worth adding complexity.

**Comment by geerlingguy** [comment]
Yeah, it's too complicated to try to find out the IP (AFAICT) when using auto network.

**Comment by jayusa123** [comment]
Makes sense. Thanks
