### ISSUE TITLE
Documentation for phpmyadmin/syslog needs work

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#1367]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 1.8.6
VirtualBox 5.1.14r112924
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.4)

### Full console output

n/a

### Summary

By enabling the syslog module in a Drupal site from a "not installed" installation status, and sending pimpmylog to syslog, the entire file remains unreadable in the page generated by pimpmylog.

I suspect this is due to the format for the messages provided by Drupal's syslog module.

This request is to add the recommended and supported syslog format to DrupalVM's documentation. The following is the default setting after enabling the syslog from a "not installed" state, and it is unreadable by pimpmylog

````
!base_url|!timestamp|!type|!ip|!request_uri|!referer|!uid|!link|!message
````

Note: Permissions on this file are 777 and everything works fine, other than pimpmylog recognising the file as unreadable.

**Comment by geerlingguy** [comment]
To be honest, I haven't used Pimp My Logs in a couple years, so at least it's working :D 

I know there are a few others who do rely on it and have customized it a little more, so I'll leave it to others to help figure out the best way to get PML to parse Drupal's syslog entries.

**Comment by fubarhouse** [comment]
I would love to have more advanced tools for logging, but here I was just using whatever is packaged to see what it could do. If my team was to continue using it we'd need it to work... 

It does however lack basically all forms of filtering for historical information...

Be happy if anybody could fill in the blanks.

**Comment by oxyc** [comment]
I think you need to add PimpMyLog configs telling it how to parse syslog. It's pretty limited out of the box. I toyed around with it at one point trying to make it useful but gave up. Some of my notes are in this PR https://github.com/geerlingguy/ansible-role-pimpmylog/pull/3 and an example adding a MySQL log parser https://github.com/oxyc/ansible-role-pimpmylog/commit/ab4d125352e5037bf9c16c6f0a681227e74aa9a0. It's definitely not a fun software to customize though

**Comment by fubarhouse** [comment]
@oxyc I'll check it out thanks - all signs point to looking at something else here due to limits...

I could close this off, but I get the feeling this should be left open - it comes down to how much support you want to provide here.

**Comment by oxyc** [comment]
Yeah, I would vote for using something else. https://github.com/potsky/PimpMyLog/issues/93 required to parse MySQL slow logs has been open since 2014. I haven't been able to find anything though. If you do, let me know :)

**Comment by geerlingguy** [comment]
Short of using a full-blown open source log aggregator/visualization engine like the ELK stack, or something expensive like SumoLogic, there aren't many good solutions in this area... most of the time it's just "aggregate the raw text in a centralized log".

And owing to the fact that every application on the planet has it's own logging format (and it's annoying to try to generalize things in a system like Drupal VM), almost every centralized logging solution is very custom :(

I tried taking a crack at normalizing all the Drupal VM stuff in PML, and gave up... then @oxyc tried, and gave up...

Which is why I always just hop in via `vagrant ssh` and monitor logs with `tail`/`grep` etc. :)

And on prod infrastructure, where there are multiple servers, I use syslog aggregation and/or ELK.

**Comment by fubarhouse** [comment]
Yeah I do agree, but I was hoping for a nicer and somewhat usable interface for newcomers to my team...

Webserver logs work perfectly - and I suppose as a service that will do, but integration with dblog or syslog is clearly nil...

I'm somewhat happy if somebody wants to close this, or let me know and I will.

**Comment by oxyc** [comment]
@geerlingguy do you feel like we need to add something to the docs on this? Imho it's too complex to even try to document.

**Comment by geerlingguy** [comment]
Yeah, let's close it out for now... there's just no easy way to get generalized log aggregation working across a diverse stack like Drupal VM supports :(
