### ISSUE TITLE
DrupalVM and nginx with multi language private files / image styles

### ISSUE THREAD

**Issue by yobottehg** [geerlingguy/drupal-vm#1368]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.4)

### Summary

DrupalVM with nginx lacks support for private files and / or private multingual image styles. The following nginx rule works for me:

```
location ~ ^(/[a-z\-]+)?/system/files/ {
    try_files $uri /index.php?$query_string;
}
```

Perhaps we could add something like this.
Originally from here : https://github.com/geerlingguy/ansible-role-nginx/issues/104#issuecomment-301122637

**Comment by geerlingguy** [comment]
+1 from me. Would need a PR and maybe someone else manually testing it out to confirm :)
