### ISSUE TITLE
Enhance DrupalVM with Behat testing

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#137]
Look at an Ansible Role that brings in Behat testing.

Composer libraries to consider:

    "behat/behat":                  "3.0.*",
    "behat/mink":                   "1.6@stable",
    "behat/mink-extension":         "*",
    "behat/mink-goutte-driver":     "*",
    "behat/mink-selenium2-driver":  "*",
    "behat/mink-zombie-driver":     "*",
    "behat/mink-browserkit-driver": "*",
    "drupal/drupal-extension":      "*",

**Comment by geerlingguy** [comment]
Can you give a little more background in terms of what Drupal VM should do specifically that would be helpful for all Drupal projects (rather than something that would be run locally for a particular Drupal site inside the VM, e.g. running composer install after provisioning and doing any other required setup).

E.g. are there any particular libraries or packages that Drupal VM should support so that Behat testing configuration is simpler for individual Drupal projects?

**Comment by nerdstein** [comment]
This is a great question. My gut tells me we should just install the infrastructure initially and see how people use it. 

I think there is a lot of discussion happening on how to best leverage it. This is just getting the ball rolling.

**Comment by geerlingguy** [comment]
I would need something more concrete to make it a default configuration for Drupal VM; for now, all the mentioned libraries can be installed globally by adding them to the `composer_global_packages` variable.

**Comment by nerdstein** [comment]
Is this variable within config.yml?  How is this set for DrupalVM?

**Comment by geerlingguy** [comment]
@nerdstein - See https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L119-L120 for an example in the default config (it's commented by default).

**Comment by nerdstein** [comment]
Thanks

**Comment by kevinquillen** [comment]
If you just bring in "drupal/drupal-extension" in composer, it itself pulls in all the required libraries necessary for testing Drupal (it didnt used to in previous versions).

**Comment by kevinquillen** [comment]
Be aware though that the Behat 3.0 docs are not completed and there are notable changes from 2.x.

**Comment by arknoll** [comment]
If you want to actually do selenium tests you need to:

1. Download selenium server: 
curl -o selenium-server-standalone-2.46.0.jar http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar

2. Run selenium server: 
DISPLAY=:1 xvfb-run java -jar selenium-server-standalone-2.46.0.jar

3. Download firefox: 
apt-get install firefox

4. Download xvfb: 
apt-get install xvfb

If we could get some of this rolled into the box that would be nice.

**Comment by kevinquillen** [comment]
Here is how I usually do it, though there may be a better way by now. I create a shell script and add it to the Vagrant up process, so it is executed when I boot up:

```
#!/bin/sh
#set -e

if [ -e /.installed ]; then
  echo 'Already installed.'

else
  echo ''
  echo 'INSTALLING'
  echo '----------'

  # Install Java, Firefox, Xvfb, and unzip
  apt-get -y install openjdk-7-jre-headless firefox xvfb unzip

  wget "http://selenium-release.storage.googleapis.com/2.46/selenium-server-standalone-2.46.0.jar"
  mv selenium-server-standalone-2.46.0.jar /usr/local/bin

  # So that running `vagrant provision` doesn't redownload everything
  touch /.installed
fi

# Release old locks
echo "Releasing old XVFB locks from /tmp..."
cd /tmp
sudo rm -rf .X*-lock

echo "Starting Selenium Server. Default screen resolution: 1280x1024."
cd /usr/local/bin
DISPLAY=:1 xvfb-run --server-args="-screen 0 1280x1024x8" java -jar ./selenium-server-standalone-2.46.0.jar &

echo "Give Selenium Server a few minutes to fireup, then run your BDD tests."
```

You could also add to this script and initialize PhantomJS in headless mode, then you could use @javascript drivers in your test. The latest versions do not require Selenium anymore, I believe.

**Comment by nerdstein** [comment]
Wouldn't this make for a good Ansible recipe? cc: @geerlingguy

**Comment by kevinquillen** [comment]
Yes, I intended on converting it but have not had the requisite time to do
so.

**Comment by geerlingguy** [comment]
@nerdstein / @kevinquillen / @arknoll - Sounds like the perfect solution would be an Ansible role like `drupal-behat` or something like that. It would require:

  - `selenium` - Installed via jar file download, and started.
  - `firefox` - Installed via apt
  - `xvfb` - Installed via apt

I could make behat an optional role (like memcached, solr, etc.), since the majority of Drupal sites likely don't have Behat tests, and wouldn't need selenium/etc. using space/resources.

**Comment by arknoll** [comment]
@geerlingguy I can take a crack at creating an Ansible role for this.

**Comment by geerlingguy** [comment]
Sounds good to me! If possible, try to make it work on CentOS too (I can help if you have any trouble).

-Jeff Geerling

**Comment by geerlingguy** [comment]
This has been merged through #161, and I've added the relevant docs here: http://docs.drupalvm.com/en/latest/extras/behat/

**Comment by kevinquillen** [comment]
Just to double check, are we sure that we are not installing Behat twice? I
thought drupal/drupal-extension was sufficient.

**Comment by geerlingguy** [comment]
It wouldn't install it twice, even if you explicitly include all the dependencies, since Composer will build a dependency graph and download only one copy of each of the required libraries... but if we can simplify the instructions and remove the `behat/mink` lines, that would be nice too.
