### ISSUE TITLE
Windows 10 enterprise vagrant up

### ISSUE THREAD

**Issue by ikit-claw** [geerlingguy/drupal-vm#1371]
### Issue Type

 - Bug Report / Support Request

### Your Environment

The provider 'PROVIDER' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.

When running vagrant up prompted to run vagrant up --provider=PROVIDER
```

### Your OS

Windows 10 enterprise

**Comment by geerlingguy** [comment]
@ikit-claw - Interesting... Do you have VirtualBox installed on Windows? I haven't run into this before.

**Comment by geerlingguy** [comment]
Also, does it say that after you do `vagrant up` alone (without the --provider part)?

See potentially related Vagrant issue: https://github.com/mitchellh/vagrant/issues/5189

**Comment by ikit-claw** [comment]
I'm running VMware12

**Comment by geerlingguy** [comment]
Ah, if you want to use Vagrant with VMware, you also have to buy and install the `vagrant-vmware` plugin—see https://www.vagrantup.com/vmware/

(This is why I've stopped using VMware for my own environments... after three times paying for upgrades to VMware + Vagrant's plugin, I decided it's not worth the effort/price).

Otherwise, if you install VirtualBox, Vagrant will detect it's present and work with it instead of VMware.

**Comment by ikit-claw** [comment]
So if I go back to using VirtualBox it should work?

**Comment by ikit-claw** [comment]
I guess you should put that in the notes.

**Comment by ikit-claw** [comment]
How I get couldn't open base

**Comment by geerlingguy** [comment]
Hmm, what's the exact error message? Is it something like https://github.com/geerlingguy/drupal-vm/issues/672

**Comment by ikit-claw** [comment]
Okay I followed the suggestions in 672 and it worked played with it a little but today it won't load at all. Why do people use windows argh

**Comment by geerlingguy** [comment]
> Why do people use windows argh

Haha... but to that point: [Developing with VirtualBox and Vagrant on Windows](https://www.jeffgeerling.com/blog/2016/developing-virtualbox-and-vagrant-on-windows).

What messages are you getting when it's not loading? Can you grab a screenshot of the console or somehow copy out the text? Also, one other question—what terminal/CLI emulator are you using? I've had the best luck with Cmder or Cygwin, though Powershell and plain old Git Bash may work in some cases too.

**Comment by ikit-claw** [comment]
Sorry I've just uninstalled it for now. It was supposed to be a quick thing for a tutorial I might circle back around to this later when I have time to get into it.
