### ISSUE TITLE
Adding mongodb to the vm along with mysql

### ISSUE THREAD

**Issue by eshadatta** [geerlingguy/drupal-vm#1373]
### Issue Type

 - Question

### Your Environment
```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
```

### Your OS

 - **macOS** (10.9.5)

### Summary

I'm new to vagrant boxes, so please bear with me. I need to have a drupal site that uses mySQL and mongodb. This drupal vm is very comprehensive; however, I also need to load mongodb on to the vm. Can I just install mongodb in the vm like I would any other machine or are there some configurations I need to add to config.yml? I looked through the documentation and didn't see mongodb mentioned anywhere and so I'm asking about it. Thanks in advance!

**Comment by geerlingguy** [comment]
@eshadatta - There are two main ways you can go about getting MongoDB on the VM:

  - Add the required mongodb packages to `extra_packages` in your `config.yml` (see https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L219), then add a post-provision script or task file to configure MongoDB as you need it to be configured (see http://docs.drupalvm.com/en/latest/extending/scripts/).
  - Do everything inside a post-provision shell script or task file (see same link as above).

I'm not planning on adding MongoDB natively to Drupal VM as a role / toggle-able feature any time soon, as it's more of a niche app that relatively few sites require.

**Comment by eshadatta** [comment]
@geerlingguy , awesome, thanks for the really quick response. This is super useful. 

I wasn't intending my question as a feature request since, as you also mentioned, my use case is really specific.

**Comment by geerlingguy** [comment]
No problem! Glad I could help :)

**Comment by chriscalip** [comment]
Dear user/likely my future self when i forget again,

Another way to do this is after creating a fresh drupal-vm install. ie. after `vagrant up`
You can install mongodb see ( https://www.digitalocean.com/community/tutorials/how-to-install-mongodb-on-ubuntu-16-04 ) and configure. For subsequent use of drupal-vm, ie. `vagrant reload` just retype `sudo systemctl start mongodb;sudo systemctl status mongodb` and you got mongodb for drupal-vm :)
