### ISSUE TITLE
Recent 3.x Issues with Drush/PHP/Zend OPCache

### ISSUE THREAD

**Issue by mikemadison13** [geerlingguy/drupal-vm#1374]
### Issue Type

 - Documentation Report

### Your OS

 - **macOS** (10.11.6)

### Summary

Recently my vm began exhibiting a number of odd behaviors (and after a day of putting out fires, they have been resolved). Very few of them were directly tied back to Drupal VM itself, but as it was all happening as a result of running a Drupal VM I wanted to document it here.

**issue 1**: 

```
Cannot load Zend OPcache - extension already loaded
```

While running drush and other commands in the VM  (after recently updating) the console began spitting out the Zend OPcache warning multiple times (up to 10-20 times per command). This had a noticeable impact on performance in the CLI.

Attempting to resolve this by removing opcache files in /etc/php and re-provisioning the VM were largely unsuccessful (see issue 2). 

**issue 2**:

Once the opcache files were removed, the following errors began to appear:

```
$ drush 
[warning] proc_open(): fork failed - Cannot allocate memory exec.inc:243
[warning] proc_get_status() expects parameter 1 to be resource, boolean given exec.inc:244
[warning] proc_close() expects parameter 1 to be resource, boolean given exec.inc:245 

$ drush -v 

Warning: PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/tokenizer.so' - /usr/lib/php/20131226/tokenizer.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0

PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php/20131226/wddx.so' - /usr/lib/php/20131226/wddx.so: failed to map segment from shared object: Cannot allocate memory in Unknown on line 0
```

At this point, i went ahead and did an update to the 4.x line of drupal vm, removing the old vm completely and re-installing from scratch. after that, things worked normally.

**Comment by geerlingguy** [comment]
@mikemadison13 - For the `Cannot load Zend OPcache - extension already loaded` issue, that was a known issue caused by Ubuntu 14.04 and 16.04 having different filenames for the opcache configuration file (and differences also between where the file resided in different installations of PHP... it was truly annoying :P).

That issue was fixed upstream here: https://github.com/geerlingguy/ansible-role-php/issues/127 (and see related Drupal VM issue: https://github.com/geerlingguy/drupal-vm/issues/619). It should be working correctly in any 4.x release.

**Comment by mikemadison13** [comment]
correct @geerlingguy I think at this point this ticket isn't anything that needs to be "fixed" i just wanted to document the issues that cropped up for google fodder just in case anyone else comes across similar issues in the future. feel free to close this issue and we can continue to update as needed today/tomorrow.

**Comment by geerlingguy** [comment]
And for the second issue, I'm guessing it is related to removing the opcache config—it looks like something in PHP's memory allocation might have gotten screwed up (though I'm surprised a full restart of the VM wouldn't fix that—it should reboot PHP's process and reallocate memory... even if opcache is being bypassed.

But who knows! Thanks for posting—hopefully this helps someone else who's run into the same problem in the future :)
