### ISSUE TITLE
drush @drupalvm.dev status doesn't work

### ISSUE THREAD

**Issue by ikit-claw** [geerlingguy/drupal-vm#1376]
### Your OS 

windows 10 enterprise

### Full console output

'drush' is not recognized as an internal or external command,
operable program or batch file.

### Summary

The documents say for drush to use drush @drupalvm.dev status to determine if drush is working.

I tried it from the vmroot which in my opinion should really work. I also tried it from the web root and nothing.

Had to use vagrant ssh to log in first couldn't see that in the documentation.

Composer won't load 

Fix run composer config repositories.drupal composer https://packages.drupal.org/8

Runs but drupal can't find the module.

**Comment by geerlingguy** [comment]
@ikit-claw - For the drush issue; do you have `drush` in your configuration's `installed_extras`? If it's not present, Drush won't be installed systemwide inside the VM.

**Comment by ikit-claw** [comment]
Yes Drush and DrupalConsole are both enabled in the config file.

**Comment by geerlingguy** [comment]
@ikit-claw - I'm assuming when you run a `vagrant provision` there are no errors? Also, how are you logging into the VM to run the commands?

**Comment by ikit-claw** [comment]
vagrant ssh

**Comment by geerlingguy** [comment]
@ikit-claw - I guess the other issue is this issue is a bit vague—can you give some definitive issues with information like:

  1. I was trying to do _x_.
  2. I ran exactly command _y_.
  3. I expected _z_ to happen, and instead _a_ happened.

Some things require you to be in a certain path, other things might be affected by some of the settings in your local environment.

**Comment by oxyc** [comment]
Reading the initial issue it sounds like you're issuing the `drush` command on your Windows computer, correct? Drupal VM doesn't install drush on the host, only on the guest (vm). It's also briefly mentioned in the Drush section of the docs:

> If you have Drush and Ansible installed on your host workstation ...
> http://docs.drupalvm.com/en/latest/extras/drush/

--- 

> Composer won't load
> Fix run composer config repositories.drupal composer https://packages.drupal.org/8
> Runs but drupal can't find the module.

This already exists in both scenarios we use. Are you using https://github.com/geerlingguy/drupal-vm/blob/master/composer.json as your `composer.json`? This one is used for install Drupal VM as a composer dependency, it should not be used for your actual site. Which install method are you attempting to use? We have docs for all of them:

- Default: http://docs.drupalvm.com/en/latest/deployment/composer-package/
- Using `drupal.composer.json` (somewhat discouraged unless Drupal VM is a dependency itself) http://docs.drupalvm.com/en/latest/deployment/composer/
- Drupal VM as a dependency http://docs.drupalvm.com/en/latest/deployment/composer-dependency/

**Comment by oxyc** [comment]
Closing this as there hasn't been any activity for a while. If you're still having issues, we're happy to re-open it and help out as long as you can provide some more information.
