### ISSUE TITLE
Auto-install vagrant-vbguest and vagrant-hostsupdater plugins

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1378]
### Issue Type

 - Feature Idea

### Summary

I noticed in [this example](https://github.com/leighmcculloch/vagrant-docker-compose/blob/master/example/Vagrantfile#L4-L8), a Vagrantfile was automatically installing a required plugin as part of the `vagrant up` routine.

Since there's probably an issue or two a month where someone runs into a version combination that causes issues (e.g. box version 1.0.9 has VB guest additions for 5.1.22, but the user has 5.1.24 installed...), it might be good to at _least_ forcefully install the `vagrant-vbguest` plugin.

Such code would be like:

```ruby
unless Vagrant.has_plugin?("vagrant-vbguest")
  system("vagrant plugin install vagrant-vbguest")
  puts "Dependencies installed, please try the command again."
  exit
end
```

(Not sure if we need to exit—can Vagrant use a plugin that's installed during a Vagrant run?)

Any major downside to this? Some super-vigilant people might not need the plugin... but _I_ have it installed, and I'm the one building these base boxes!

**Comment by geerlingguy** [comment]
This would help clear up on of the few major hurdles that seems to affect people, e.g. https://github.com/geerlingguy/drupal-vm/issues/1378

**Comment by oxyc** [comment]
Also see this PR over at trellis https://github.com/roots/trellis/pull/829

**Comment by geerlingguy** [comment]
Dang, they're all fancy over there in trellis... I would like to basically do as they do, and by default have:

  - `vagrant-vbguest`
  - `vagrant-hostsupdater`

Arguments could be made to also install `vagrant-cachier` by default... but maybe not.

**Comment by oxyc** [comment]
I've had some odd bugs with `vagrant-cachier` (albeit I don't treat my VM's well while testing) so personally I would probably remove it if it was a default.

**Comment by geerlingguy** [comment]
> I've had some odd bugs with `vagrant-cachier`

Good, so it's not just me :) That's a good argument for not including it as default.

**Comment by heddn** [comment]
I've had issues with cachier too. The others are fine to install by default. I'd almost add vagrant-auto_network and/or vagrant-bindfs. And not required, but vagrant-hostmanager is also pretty sweet.

**Comment by frob** [comment]
I would argue vagrant-hostupdater as optional as well. We sometimes need to edit our host files manually and programs, such as gasmask on mac, can be troublesome with hostupdater.

**Comment by oxyc** [comment]
My vote still goes for including `vagrant-hostsupdater` by default. Mostly because it removes another step from the quick start guide. I added it as a separate commit in case we want to drop it though.

Out of curiosity, why use gasmask rather than just editing the file yourself?

**Comment by geerlingguy** [comment]
`hostsupdater` will be a default, as I think the 80% use case (I'd argue for 99+%) requires it for simplicity. But it's easy enough to override by overriding the plugin list in your own `config.yml`, `local.config.yml`, etc.

**Comment by geerlingguy** [comment]
Fixed via merged PR from @oxyc - thanks!

**Comment by frob** [comment]
If it is overwritable then I would also argue for including it. How would it be overwritten?

**Comment by oxyc** [comment]
Add this to your `config.yml`:

```yaml
vagrant_plugins:
  - name: vagrant-vbguest
```

**Comment by frob** [comment]
Okay, so just redefine the vagrant_plugins. I was thinking it might be a black list or something. Thank you. 

We should add that to the docs: PR #1402
