### ISSUE TITLE
There was an error while executing `VBoxManage`

### ISSUE THREAD

**Issue by danielrose28** [geerlingguy/drupal-vm#1379]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.0.40_Ubuntur115130
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

### Your OS
 - **Linux** (Ubuntu 16.04)

### Full console output

![selection_081](https://cloud.githubusercontent.com/assets/12372245/26319895/d8a267e8-3eee-11e7-964f-dfa4b3d4c951.png)

### Summary

Almost immediately after I run vagrant up I see this error (also in screenshot above): 

```
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "59adfd20-18b4-46be-84c0-99c08cc850b8", "--type", "headless"]

Stderr: VBoxManage: error: The VMMR0.r0 module version does not match VBoxVMM.dll/so/dylib. If you just upgraded VirtualBox, please terminate all VMs and make sure that neither VBoxNetDHCP nor VBoxNetNAT is running. Then try again. If this error persists, try re-installing VirtualBox. (VERR_VMM_R0_VERSION_MISMATCH)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component ConsoleWrap, interface IConsole
```

This started happening today after I updated Virtualbox to the latest version. I've tried re-installing virtualbox but still get the error. I'm not sure what to do from here. I've Googled this error but have only seen answers that involved Windows users. So I thought I'd create an issue here to see if anyone has seen it before. I apologize if it's a duplicate, but I did a search before creating it and didn't find anything like it so I thought I'd try. Thanks for your time and help.

**Comment by thom8** [comment]
@danielrose28 it sounds similar to this issue -- https://github.com/geerlingguy/drupal-vm/issues/483#issuecomment-219252571

are you using vbox `5.1`? `VBoxManage -v`

**Comment by danielrose28** [comment]
Hm. It's showing `5.0.40_Ubuntur115130`, but when I try to update it it says it's already up to date. I'll take a look at the other issue. Thanks for the link.

**Comment by thom8** [comment]
Yeah the default Ubuntu repo only has `5.0` you either need to manually download the `5.1` deb or add the virtualbox repo -- https://www.virtualbox.org/wiki/Linux_Downloads

**Comment by danielrose28** [comment]
So the thread you shared had a comment that fixed it for me. #483 ([comment](https://github.com/geerlingguy/drupal-vm/issues/483#issuecomment-221948437)).

Thanks for your help! :+1:

**Comment by thom8** [comment]
No worries, would also recommend using `5.1` as there's many other improvements / bugfixes included.

**Comment by adnavare** [comment]
I am seeing the same issue, with Vagrant 1.8.6 and VBox 5.1.20, what was the issue? I ran killall VBoxHeadless and there is no such process.

**Comment by geerlingguy** [comment]
@adnavare - I'd suggest opening a new issue maybe. Also if you run `VBoxManage -v` what does it say?

**Comment by mjbright** [comment]
I was also having this problem.
This is what fixed it for me.

I installed version 5.1.22 from the Ubuntu-Xenial deb package but still had the same problem.

I performed dpkg -l | grep virtualbox to see the installed virtualbox packages and saw some old 5.0.40 marked as "rc" (meaning they're removed but some configuration is still present).

I performed "dpkg --purge" on those packages and then downloaded and installed the generic virtualbox-5.1.22.run package.

Then everything was fine

**Comment by geerlingguy** [comment]
@mjbright - Thank you so much for posting what worked for you. Future google, bing, and ddg searchers will be happy.

**Comment by nikhilshelke023** [comment]
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "99f04fb5-4a70-4b57-b230-b5ef291b9295", "--type", "headless"]

Stderr: VBoxManage: error: The virtual machine 'local.my-project6.com' has terminated unexpectedly during startup with exit code 1 (0x1)
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component MachineWrap, interface IMachine

**Comment by pwayner** [comment]
Encountered a similar problem using Vagrant on Windows 10. 

`==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["startvm", "7cfc0079-c1ec-448e-ad8d-9bb6478a05a7", "--type", "headless"]

Stderr: VBoxManage.exe: error: Raw-mode is unavailable courtesy of Hyper-V. (VERR_SUPDRV_NO_RAW_MODE_HYPER_V_ROOT)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component ConsoleWrap, interface IConsole`

**Comment by magalhaes-andre** [comment]
I was having the same problem here:
OS: Linux 18.04
Vagrant: 2.0.2 (was using the apt)
Virtual Box: Somewhere under 5.x (was using the apt)

After upgrading into my Vagrant to 2.2.5 and my VB to 5.2 everything went great!
Still not knowing the root cause of the incompatibility of Vagrant 2.0.2 ad VB (apt version here).

VB 5.2 => https://www.virtualbox.org/wiki/Download_Old_Builds_5_2

**Comment by Glideh** [comment]
I have this issue on Ubuntu 18.04 standard package installation (5.2.34_Ubuntur133883)
Exact same message as OP:

> The VMMR0.r0 module version does not match VBoxVMM.dll/so/dylib. If you just upgraded VirtualBox, please terminate all VMs and make sure that neither VBoxNetDHCP nor VBoxNetNAT is running. Then try again. If this error persists, try re-installing VirtualBox. (VERR_VMM_R0_VERSION_MISMATCH).

I tried re-installing and killing VBoxHeadless, no luck.

**Comment by a-recknagel** [comment]
I also needed to kill remaining vagrant processes, either restart your machine or run `ps aux | grep vagrant` and put all PIDs that come up into `sudo kill -9 <vagrant_process_pid>`.
