### ISSUE TITLE
MySQL delays upon install

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#138]
Per Sylvain Delbosc:

install-site.yml

5 - The initialisation of the VM failed in my case on drush site-install due to impossibility to connect to MySQL. While checking on the VM itself, I was given Can't connect to local MySQL server through socket '/var/mysql/mysql.sock' (38) when using localhost and was able to connect when using 127.0.0.1.
Changing the drush site-install command to use 127.0.0.1 allowed to pass this step (I had to hack the Installer to add a pause after the clone of the Drupal VM project to be able to update the provisioning tasks).
I did not investigate on the root cause of this but if more of you faced the same issue it is worth having a look at it.

apparmor.yml

6 - The restart of MySQL post extras tasks was failing. When checking on the VM itself it seemed to be the consequence of a change in the innodb_log_file_size while ib_logfile* exist.
I had to add 3 commands to this yml file (probably not the best place ever) to delete ib_logfile0 and ib_logfile1 and then restart MySQL. This allowed me to complete the installation step.
Again I did not investigate the root cause of this but if more of you faced the same issue it is worth having a look at it.
Note that to be able to initialise the VM like a developer would do, I had to revert the changes I did in this file.

**Comment by geerlingguy** [comment]
@nerdstein - I'm 99% sure this is due to Ansible version on the host machine—do you know if he was running 1.9.1? Ansible 1.9.2 should fix both of these issues—basically 1.9.1 had an issue with the MySQL modules that caused all kinds of annoying issues with MySQL configuration.

To update on a Mac, either use `brew update` / `brew upgrade`,  or if you used pip, `sudo pip uninstall ansible && sudo pip install ansible`.

**Comment by nerdstein** [comment]
We're going to do a version check within our installation routine

**Comment by geerlingguy** [comment]
Good idea! And it seems the only issues with MySQL have been in 1.9.1, and 1.9.2 was only released a few days ago, so this problem should iron itself out over time.

**Comment by sdelbosc** [comment]
I confirm that I am using Ansible 1.9.1

**Comment by geerlingguy** [comment]
@sdelbosc - Can you try upgrading to Ansible 1.9.2 and see if that fixes the issue?

**Comment by sdelbosc** [comment]
Tested with 1.9.2. No issue with MySQL.

The only one I faced was this one:
```TASK: [Ensure configured cron jobs exist in root account's crontab.] **********
fatal: [drupalvm] => with_items expects a list or a set```

I commented the inclusion of cron.yml in the playbook file and it went fine. Maybe the root cause was just the fact that the cron list was empty.

**Comment by nerdstein** [comment]
@geerlingguy is this fixed in 1.9.5?

**Comment by geerlingguy** [comment]
@sdelbosc - I made it so the cron task is more robust in the commit https://github.com/geerlingguy/drupal-vm/commit/213626eeae3c927795685f71a1d42ee0ddbb840e — now even if you don't have the variable defined as an empty set (see `example.config.yml`), the task will not fail.

@nerdstein - This wasn't a problem with Drupal VM, per-se, it was a bug in Ansible 1.9.1 (and I've now documented that Ansible 1.9.2 or later is recommended in the README).

**Comment by sdelbosc** [comment]
Looks good to me.
