### ISSUE TITLE
Consider allowing use of Vagrant with docker provider to run and provision Drupal VM

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1381]
### Issue Type

 - Feature Idea

### Summary

In #1366, we added the ability to use Drupal VM in a monolithic Docker container, completely independent of Vagrant. Vagrant itself allows the use of the [Docker provider](https://www.vagrantup.com/docs/docker/configuration.html) in lieu of other providers (the most commonly used for Drupal VM is currently VirtualBox...).

After we solidify the experimental Docker support, it might be a nice improvement to let Vagrant manage the building/provisioning of Docker containers, especially if it solves some of the more annoying/difficult bits, like managing the hosts file using `vagrant-hostsupdater`.

Tagging @thom8, who was the original suggester of such an integration.

**Comment by oxyc** [comment]
Played around with this a bit during the weekend. A few notes:

- Vagrants synced folders do not work (https://github.com/hashicorp/vagrant/issues/8021). Dockers is the way to go anyways.
- `vagrant-hostsupdater` correctly edits the hostfile while `vagrant-hostmanager` doesn't (https://github.com/devopsgroup-io/vagrant-hostmanager/issues/243)
- Pretty flexible as we can map the current config to docker params ala `d.ports = vconfig['firewall_allowed_tcp_ports'].map { |p| "#{p}:#{p}" }`
- Networking is a pain on macos ofc. Really hoping for an upstream fix here as it's still sort of deal breaker for me.

**Comment by geerlingguy** [comment]
Closing this out; if I go further down the Docker path, I go further down Docker alone since it's faster/easier to manage than Vagrant with Docker inside at this point, for all things but the networking setup.
