### ISSUE TITLE
Setting up Drupal VM by importing the codebase and database into the virtual machine

### ISSUE THREAD

**Issue by jonnycyr** [geerlingguy/drupal-vm#1385]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
sh.exe": vboxmanage: command not found
VirtualBox
sh.exe": ansible: command not found
```

### Your OS

 - **Windows** (10)

### Summary

This question is quite basic and my experience with virtual environments and Drupal is very little. Basically what I've been trying to do is upload my local codebase and database into the virtual environment. I'd like to develop on Linux using Drupal VM, as well as using version control within the virtual environment, hence just putting everything into the VM instead of syncing it with a folder. I've uploaded my .sql file onto adminer, and have edited my settings.php file to this:

 $databases['default']['default'] = array (
    'database' => 'drupal',
    'username' => 'drupal',
    'password' => 'drupal',
    'host' => 'localhost',
    'port' => '3306',
    'driver' => 'mysql',
    'prefix' => '',
    'collation' => 'utf8mb4_general_ci',
 );

But still nothing happens, when I go to drupalvm.dev I just get the message:
The website encountered an unexpected error. Please try again later.

In addition, whenever I upload the .sql file (it's a huge file) I get a 503 error when it's done uploading but then when I go back to the database it shows that the database has been uploaded. 

Thanks in advance for your help!

**Comment by geerlingguy** [comment]
Interesting; usually `The website encountered an unexpected error. Please try again later.` indicates something in PHP isn't happy, and the only way to diagnose what's going on is to look at the log files.

Can you log into the VM (`vagrant ssh`), then go to the log dir (I think `/var/log/apache2/` — you might need to run `sudo su` to switch to the root user first), then `ls` to see the contents of that directory.

Use `tail [logfile-name-here]` on each of the logs in that directory to see the last few lines, then see if there's a PHP Fatal error listed. It might have some more clues as to what's happening.

**Comment by jonnycyr** [comment]
Thank you so much, I think I have a better idea of what's wrong, here's some of my error.log:

[Wed May 24 23:45:53.254241 2017] [ssl:warn] [pid 1137:tid 140206336059200] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Wed May 24 23:45:53.255803 2017] [mpm_event:notice] [pid 1137:tid 140206336059200] AH00489: Apache/2.4.25 (Ubuntu) OpenSSL/1.0.2k configured -- resuming normal operations
[Wed May 24 23:45:53.255832 2017] [core:notice] [pid 1137:tid 140206336059200] AH00094: Command line: '/usr/sbin/apache2'
[Wed May 24 23:48:20.222609 2017] [proxy_fcgi:error] [pid 1140:tid 140206231586560] [client 192.168.88.1:63413] AH01071: Got error 'PHP message: Uncaught PHP Exception Drupal\\Core\\Database\\DatabaseExceptionWrapper: "SQLSTATE[42S22]: Column not found: 1054 Unknown column 'tags' in 'field list': INSERT INTO {cache_bootstrap} (cid, expire, created, tags, checksum, data, serialized) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6) ON DUPLICATE KEY UPDATE cid = VALUES(cid), expire = VALUES(expire), created = VALUES(created), tags = VALUES(tags), checksum = VALUES(checksum), data = VALUES(data), serialized = VALUES(serialized); Array\n(\n    [:db_insert_placeholder_0] => hook_info\n    [:db_insert_placeholder_1] => -1\n    [:db_insert_placeholder_2] => 1495669698.638\n    [:db_insert_placeholder_3] => \n    [:db_insert_placeholder_4] => 0\n    [:db_insert_placeholder_5] => a:39:{s:10:"token_info";a:1:{s:5:"group";s:6:"tokens";}s:16:"token_info_alter";a:1:{s:5:"group";s:6:"tokens";}s:6:"tokens";a:1:{s:5:"group...\n', referer: http://dashboard.drupalvm.dev/
[Thu May 25 12:31:44.043714 2017] [ssl:warn] [pid 1146:tid 140700047136576] AH01873: Init: Session Cache is not configured [hint: SSLSessionCache]
[Thu May 25 12:31:44.045358 2017] [mpm_event:notice] [pid 1146:tid 140700047136576] AH00489: Apache/2.4.25 (Ubuntu) OpenSSL/1.0.2k configured -- resuming normal operations
[Thu May 25 12:31:44.045387 2017] [core:notice] [pid 1146:tid 140700047136576] AH00094: Command line: '/usr/sbin/apache2'

It seems like part of the database is missing, which makes sense since uploading my .sql file results in a 503 error after a while - it seems like it uploads a good part of my database and then stops at a certain point. I'm guessing that this is because of running out of space, would this be a setting that I can configure in php?

**Comment by jonnycyr** [comment]
I've already edited php_upload_max_filesize to be 512M and php_post_max_size to be 2048M in provisioning/roles/geerlingguy.php/defaults/main.yml. For reference my .sql file is 291,092 KB.

**Comment by jonnycyr** [comment]
Hey @geerlingguy, thank you for your help so far, a team member was actually able to help me with my problem. Turns out I was trying to access our database without having our local codebase within the virtual environment.
