### ISSUE TITLE
Clarify documentation for quick start

### ISSUE THREAD

**Issue by jasonglisson** [geerlingguy/drupal-vm#1387]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### Your OS

 - **macOS** (version)

### Summary

Just want to ask a few questions. I'm pretty new to this kind of setup and want to learn more.

_1. Download this project and put it wherever you want._ 
  - Can I really put this anywhere? I've got it in a folder of VMs under /User/jasonglisson/VMs

_2. (Optional) Copy default.config.yml to config.yml and modify it to your liking._
  - I leave this in the Drupal VM folder, right?
  - If the path is given to your project in the next step, why is this optional?

_3. Create a local directory where Drupal will be installed and configure the path to that directory in config.yml(local_path, inside vagrant_synced_folders)._ 
  - I did this, but it's telling me it can't find anything at that path.
  - If I have multiple local sites that I want to setup, do I change this each time to the new location?

_4. Open Terminal, cd to this directory (containing the Vagrantfile and this README file)._ 
  - I get the Vagrantfile from the VM folder that I just cloned, correct?

_5. Type in vagrant up, and let Vagrant do its magic._ 
  - I get the terminal error below when I do this. It seems like it's looking for the VM inside the directory where I want the local site to be.

```
There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /Users/jasonglisson/Sites/drupal8/Vagrantfile
Line number: 0
Message: LoadError: cannot load such file -- /Users/jasonglisson/Sites/drupal8/lib/drupalvm/vagrant
```

**Comment by jasonglisson** [comment]
I watched the video here (http://docs.drupalvm.com/en/latest/getting-started/installation-macos/) and it clarified some things. 

So you run `vagrant up` from the VM folder it seems. 

The path you set obviously is where you want the project to be setup. 
I guess if someone could help clarify the docs, that would be excellent.

**Comment by geerlingguy** [comment]
> (Optional) Copy default.config.yml to config.yml and modify it to your liking.

Yes, put that file inside the Drupal VM directory.

> If the path is given to your project in the next step, why is this optional?

You don't technically need to change the path from the default. By default, Drupal VM will share a 'drupal' directory in Drupal VM's directory into the VM. That's often useful for when you want to quickly build a Drupal 8 site from scratch—Drupal VM does all the work for you, and you don't need to point to a specific directory.

Note that `config.yml` only needs to have the variables you want to override—your config.yml could just be a few lines telling Drupal VM where your codebase is.

> If I have multiple local sites that I want to setup, do I change this each time to the new location?

If you want to have a bunch of sites running in one Drupal VM instance, you can add multiple shared folders, one per codebase. See: http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/

If you have one codebase and a multisite setup, see: http://docs.drupalvm.com/en/latest/deployment/multisite/

> I get the terminal error below when I do this. It seems like it's looking for the VM inside the directory where I want the local site to be.

I'm not quite sure how that error message appeared—did you download Drupal VM, then place Drupal VM inside the folder `lib/drupalvm/vagrant`? Or were you in the directory `/Users/jasonglisson/Sites/drupal8/` and ran `vagrant up`?

For help with debugging, please write up the steps it took to get to the error, e.g.:

  1. I downloaded Drupal VM to `x` directory.
  2. I created a `config.yml` file in `x` directory with the contents linked in this gist: [link].
  3. I ran the command `vagrant up`.
  4. I got the following error: `...`

**Comment by geerlingguy** [comment]
Please let us know if you have any other specific questions.

**Comment by jasonglisson** [comment]
Thank you for the great explanation and all the hard work. This definitely helped me out.
I was downloading the Drupal VM and then moving it or pointing it to another directory, but I see nothing wrong with just pulling it to the directory where I want my site and then installing the VM there. Then I just work out of the web directory. Anything wrong with that in particular?

**Comment by geerlingguy** [comment]
@jasonglisson - No problem with doing that, though I typically recommend nowadays that you use a project layout where the first directory contains Drupal VM (or a 'vendor' directory if using Composer, along with composer.json/lock), a README and documentation, config for the site (if using Drupal 8 configuration management), and then last but not least, a `docroot` or `web` directory, inside which the actual Drupal site codebase is stored (this would be your Apache `docroot`).

That way you aren't mixing things like Drupal VM configuration or configuration dumps with your actual site code (if you do that, there's an increased risk that someone could find a way to get at information or discover things you don't want them to, in all those ancillary directories).

Closing out this issue, but feel free to open a new issue if you find some new problem or question!
