### ISSUE TITLE
Does Docker provision the site?

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#1390]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
nerdstein@Adams-MBP-2 box $ docker-compose up -d
Creating network "box_drupalvm" with driver "bridge"
Pulling drupal-vm (drupal-vm:latest)...
ERROR: repository drupal-vm not found: does not exist or no pull access
nerdstein@Adams-MBP-2 box $ docker-compose up -d
Pulling drupal-vm (geerlingguy/drupal-vm:latest)...
latest: Pulling from geerlingguy/drupal-vm
10a267c67f42: Pull complete
ae6f6d297142: Pull complete
16be1393dfe2: Pull complete
8cb25e93b46b: Pull complete
1b377f976714: Pull complete
67ae8bf6d11e: Pull complete
193fedbf7fe2: Pull complete
ccb23ba7eeba: Pull complete
f9f50c38aabe: Pull complete
2eee2d39d32a: Pull complete
Digest: sha256:3caf5b95aa23686bbb2747bc3e6a935812dc37b55c0946e9d1413c50a21b0e14
Status: Downloaded newer image for geerlingguy/drupal-vm:latest
Creating nerdstein-d8 ... 
Creating nerdstein-d8 ... done
```

### Your OS

 - **macOS** 10.12.5

### Full console output

See above

### Summary

I have a `code` directory at the same level as the DrupalVM directory.

When I ran `docker-compose up -d`, like `vagrant up`, I expected it to build the Drupal code base.

My `code` directory is empty after running that command. Does there need to be additional steps added to the documentation to build the code base in accordance to the settings found in config.yml?

**Comment by nerdstein** [comment]
In addition, like `vagrant up`, I expected it to respect the `install_site` flag found in `config.yml`, which would optionally install the site.

**Comment by geerlingguy** [comment]
At this point, no; as mentioned in #1388, I'm thinking that the two primary use cases are:

  1. Building and sharing a 'pre-baked' custom Drupal VM (fat) docker image with a team (or having one per project working alone). This just makes resetting a local environment, or building a new one from scratch, really fast.
  2. Running a local codebase using `geerlingguy/drupal-vm` from Docker Hub. That image presumes you're managing the build/install/db-copy all by yourself, though. It doesn't include any tooling for automatically running composer commands, running `drush site-install`, etc.

**Comment by geerlingguy** [comment]
I think this is slightly better in the docs now, and since your PR that uses the `geerlingguy/drupal-vm` image in the Compose file by default was merged, it's a little cleaner first-time experience in general.

Closing this, and will hopefully have more options (including 'provision me a new Drupal 8 site in seconds in a new container') in a coming release.
