### ISSUE TITLE
Segmentation fault on composer create-project

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1391]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

### Your OS

 - **macOS** (El Capitan)

### Full console output
TASK [geerlingguy.drupal : Generate Drupal project with composer package.] *****
fatal: [xyzzz]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:01.262332", "end": "2017-05-30 09:08:46.238970", "failed": true, "rc": 139, "start": "2017-05-30 09:08:44.976638", "stderr": "Segmentation fault", "stderr_lines": ["Segmentation fault"], "stdout": "", "stdout_lines": []}

### Summary

A fresh drupalvm, latest release, version 4.5.0
I did a vagrant up, and it always segfault on composer create-project.
Logged in via vagrant ssh and tried following command, which works fine:

composer create-project drupal-composer/drupal-project:8.x-dev --prefer-dist --stability dev --no-interaction

This is my config.yml: https://pastebin.com/theNbZV4

**Comment by betz** [comment]
Very strange, but I can't seem t reproduce the error anymore.
Well, good news, but would be nice to know what was the problem.

I enabled 'installed extras' one by one and rerun everything, but it keeps on working.
Closing the issue...

**Comment by geerlingguy** [comment]
@betz - This usually means something in the universe didn't align correctly for just that critical moment... and you got hit by a cosmic ray or something.

I've seen the same thing happen before—Segfault, then can't reproduce it. I just chalk it up to karma; maybe a segfault here means you don't get one in production sometime down the road :)
