### ISSUE TITLE
File size of new box

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#1396]
### Issue Type
Support Request

### Your OS
Windows 10

### Summary
Starting the Drupal VM with vagrant up I can see a message that there is a new box available.

My question is, why the file size of the new box is much greater than the old box?
Are there more features in it?
New additional files?
Which files in the box have a much greater file size?

**Comment by geerlingguy** [comment]
@webprogrammierer - Are you using `geerlingguy/ubuntu1604`? The box is built using this configuration (https://github.com/geerlingguy/packer-ubuntu-1604), which hasn't changed much since the box was first built a year or so ago. Version-to-version, the boxes are usually only a few MB different, and all changes are due to changes in the upstream OS distribution.

Where are you seeing the size reported? And what is the difference? I haven't really noticed a larger file size, but I don't pay much attention to box sizes when they download, either.

**Comment by webprogrammierer** [comment]
> ==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
> ==> drupalvm: A newer version of the box 'geerlingguy/ubuntu1604' is available! You currently
> ==> drupalvm: have version '1.1.3'. The latest is version '1.1.4'. Run
> ==> drupalvm: `vagrant box update` to update.

I want to know more about the different file size of 1.1.3 and 1.1.4. Thank you.

**Comment by geerlingguy** [comment]
My question, then, is how did you find the box sizes? I checked with `vagrant box list -i` and it doesn't show box sizes either...

It looks like, according to Atlas (Vagrant's box repository), the 1.1.4 version is 751 MB, and the 1.1.3 version is 724 MB, a differences of 27 MB. It seems to be within a typical range for Ubuntu 16.04. Many versions of Ubuntu have a few MB file size difference, and the VirtualBox guest additions themselves can fluctuate a bit too.

So I guess my question is what is the concern over the ~3% file size difference?

Boxes are updated frequently to have the newest VirtualBox Guest additions, the latest apt package data, the latest Linux kernel, etc. to match the minor point releases of the underlying OS (e.g. 16.04.1, 16.04.2, etc.). So I just keep updating my boxes every month or two, and when I update them I also run a `vagrant box update` to make sure my VMs are using the latest version.

**Comment by webprogrammierer** [comment]
Okay, thank you for your explanation. It sounds good that there is a difference of ~3%, exactly what I would have expected.

I think I have mixed up the box files and the Virtual Box VM files. Both seem to have similar file names:

box: packer-ubuntu-16.04-amd64-disk001.vmdk
VM: packer-ubuntu-16.04-amd64-disk1.vmdk

That's the reason why I mixed them. Why similar files names?

And the VM files seem to contain the database and much more files. Is this true? My VM .vmdk have file sizes about 5 GB and 7 GB.  (That's why I want to explore / browse the content in Windows, see other question).

Because of the small difference I will update the box immediately. 
Thank you.

**Comment by geerlingguy** [comment]
Ah, I see; yeah, those `.vmdk` files are the virtual images VirtualBox creates to support the VMs. And VirtualBox uses 'linked clones' to conserve disk space (so the first image contains the base, then another image builds on top of it, and so on), but the disk sizes will vary as your website code/database/installed utilities varies.

For the filenames, I don't know what VirtualBox's reasoning is, but I don't think I've thought about or looked at any of the .vmdk files on my computer in a few years. I treat my VMs as completely disposable, and indeed I'll `vagrant destroy && vagrant up` to rebuild them sometimes multiple times per day. I don't think I've ever had any project VM running/not destroyed for more than two weeks.

I'd suggest opening other questions (e.g. regarding opening vmdk files, or questions about the VirtualBox structure) in the VirtualBox forums, as people in those forums would probably have a lot more background than I do. https://forums.virtualbox.org
