### ISSUE TITLE
How to browse the .vmdk content in Windows

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#1398]
### Issue Type

 Support Request

### Your OS
Windows 10

### Summary
I there any easy tool (like 7-zip) to browse the contents of the .vmdk file located in the 'VirtualBox VMs" directory on Windows 10?

It should be a small tools not a huge software like VMware. I thougt it could be done with 7-zip, but this does not work. 
Is there any other small tool for browsing the .vmdk content on Windows 10? Thank you.

**Comment by geerlingguy** [comment]
Thanks for the question! I think this is a more generic question that would be better answered in either the Vagrant or VirtualBox forums, since it's a pretty specific question surrounding VirtualBox files:

https://forums.virtualbox.org
