### ISSUE TITLE
Drupal instance is reinstalled on provision when default language is not english

### ISSUE THREAD

**Issue by azurams** [geerlingguy/drupal-vm#1399]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.8.6
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### Your OS
 - **Linux** Ubuntu 16.04

### Summary
When doing `vagrant provision` on a drupal-vm  where Drupal instance is already installed and using another default language than english, the Drupal instance is re-installed.

We can find the source of the error in `provisioning/roles/geerlingguy.drupal/tasks/install-site.yml` :
This is because the test `when: "'Successful' not in drupal_site_installed.stdout"` is wrong as the command `drush status bootstrap` does not return "Successful" but the translated corresponding string when english is not the default language of the drupal instance.

**Comment by oxyc** [comment]
Yikes! if no one gets to it before I can have a look during the weekend.

**Comment by geerlingguy** [comment]
Eek, never thought of it, and I'm mildly surprised you're the first person to run into this!

**Comment by azurams** [comment]
Looking at https://github.com/drush-ops/drush/blob/8.1.11/commands/core/core.drush.inc#L592, to update the `drupal_site_installed` check, we may assume that if `drush status bootstrap` does not return any new line then bootstrap failed. If the string "Drupal bootstrap" is present in the output, then bootstrap succeeded ?

**Comment by oxyc** [comment]
Yes, that's apparently the case. I tested your fix locally and opened up a PR upstream.

**Comment by geerlingguy** [comment]
Fixed by pulling in the latest Drupal role. Thanks for reporting, and thanks SO much to @oxyc for knocking out the past five or so bugs :)
