### ISSUE TITLE
SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

### ISSUE THREAD

**Issue by npralhad** [geerlingguy/drupal-vm#1407]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```
### Your OS

 - **Ubuntu** (16.04)

### Full console output

An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

### Summary

*vagrant up* works only till 10 to 15 % of progress for environment setup and after that it gives an error  as in the message above.

**Comment by oxyc** [comment]
Searching for that output in google gives quite a lot of hits, eg:
- http://danielkoop.me/2016/02/17/homestead-wont-update-vagrant-an-error-occurred-while-downloading-the-remote-file/
- https://github.com/Varying-Vagrant-Vagrants/VVV/issues/401

**Comment by geerlingguy** [comment]
And from the first link, it looks like the fix would be something like:

```
rm -rf ~/.vagrant.d/tmp/box*
```

(Run inside your host machine, so it deletes the contents in there).

**Comment by oxyc** [comment]
I'm assuming you got this sorted as there hasn't been any activity for a while. If not, and you're still having issues, I'm happy to re-open it and try and help.
