### ISSUE TITLE
ERROR! 'check_mode' is not a valid attribute for a Task

### ISSUE THREAD

**Issue by SirJohn96** [geerlingguy/drupal-vm#1408]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.1.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **Windows** (10)

### Summary

After updating Drupal VM from 3.5.2 to 4.5.0, when running `vagrant up` or `vagrant reload --provision`, I encounter the following error output:

```
==> drupal-vm: Running provisioner: ansible_local...
    drupal-vm: Running ansible-playbook...
statically included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.firewall/tasks/disable-other-firewalls.yml
statically included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.git/tasks/install-from-source.yml
ERROR! 'check_mode' is not a valid attribute for a Task

The error appears to have been in '/vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.git/tasks/install-from-source.yml': line 27, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Get installed version
  ^ here
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```
Perhaps this is an issue with the version of Ansible being used. `drupalvm_ansible_version_min` is set to `2.2`. As listed above, I am on a Windows machine. Ansible is not setup on the host. Just in case, I set the `force_ansible_local` variable to `true`. I am not sure why the Ansible version is showing up as 2.1.2.0.

**Comment by geerlingguy** [comment]
Ansible 2.2 is required, so the 2.1.2 version is definitely the culprit.

@oxyc to the rescue, though! It looks like this comment (https://github.com/geerlingguy/drupal-vm/issues/1302#issuecomment-295011018) has the key to fixing it on whatever OS version you're using (which base box are you running?).

Create a `Vagrantfile.local`, inside which the following is added:

```ruby
config.vm.provisioners[0].config.install_mode = 'pip'
config.vm.provisioners[0].config.version = '2.3.1.0'
```

(Or any other version > 2.2.0)

**Comment by SirJohn96** [comment]
I am running `geerlingguy/ubuntu1204`.

Thank you. That solution worked. The provision completed successfully and the Ansible version was updated to `2.3.1.0`.

**Comment by oxyc** [comment]
Great! @geerlingguy I guess we should update the docs on this http://docs.drupalvm.com/en/latest/configurations/base-os/#ubuntu-1204-precise-lts

**Comment by geerlingguy** [comment]
@oxyc yeah... and technically 12.04 isn't even supported by Ubuntu anymore. I'm considering pulling all the 12.04 stuff out of roles and docs sooner or later :/

I've already decided I'm not going to build new boxes for 12.04—the latest box is the last one I'll build by hand.
