### ISSUE TITLE
.gitignore errors in latest version

### ISSUE THREAD

**Issue by inversed** [geerlingguy/drupal-vm#1411]
### Issue Type

 - Bug Report / Support Request

### Your Environment
NOTE: I'm running ansible through the GUEST via the `force_ansible_local: true` setting.
```
Vagrant 1.9.2
VirtualBox 5.1.18r114002
bash: ansible: command not found
```

### Your OS

 - **Windows** (10)

### Full console output

https://gist.github.com/inversed/b469c0e64709b2828f95b735a81aa8b4

### Summary

Drupal-VM's .gitignore excludes a required file (provisioning/tasks/config.yml). 
When trying to do a `vagrant up` on a project where Drupal-VM itself has been included in a repo, that file (and `tests/config.yml`) is missing so the spin up operation fails.

This might not be the intended use case (docs specify running this Windows 10's Bash) but this approach does work fine. Seems like this is a minor bug that's easy to fix but I don't know if it's actually an intentional configuration issue.

**Comment by geerlingguy** [comment]
Technically this is how I originally intended it to work, but I see your point. For applications like BLT, the `box/config.yml` is explicitly committed (e.g. `git commit -f box/config.yml`) and then it's part of the repository.

But it should probably only be excluded in the root directory (for testing or using Drupal VM completely standalone), not in subdirectories.

It looks like @oxyc is working on a fix already 😀

**Comment by oxyc** [comment]
Just trying to find the git version when leading / was added :smile:

**Comment by inversed** [comment]
Thanks for the update and great tool, BTW!

**Comment by geerlingguy** [comment]
That change has been merged in, so it will be part of the next minor release... which I hope to push out this week (was going for the weekend, but life got in the way, so it'll be sometime this week).
