### ISSUE TITLE
Cannot bring up vagrant

### ISSUE THREAD

**Issue by vibanu** [geerlingguy/drupal-vm#1414]
Issue Type

Bug Report / Support Request
Your Environment

Vagrant 1.9.1
Windows 10
Summary
### Full console output

vibha@CS264-01 MINGW64 ~/Sites/compscisbu (working)
$ vagrant up
Bringing machine 'compscisbu.localvm' up with 'virtualbox' provider...
==> compscisbu.localvm: Importing base box 'geerlingguy/ubuntu1604'...
==> compscisbu.localvm: Matching MAC address for NAT networking...
==> compscisbu.localvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> compscisbu.localvm: A newer version of the box 'geerlingguy/ubuntu1604' is available! You currently
==> compscisbu.localvm: have version '1.0.4'. The latest is version '1.1.4'. Run
==> compscisbu.localvm: `vagrant box update` to update.
A VirtualBox machine with the name 'compscisbu.localvm.stonybrook.edu' already exists.
Please use another name or delete the machine with the existing
name, and try again.

### Summary

I had to re-clone my local 'compscisbu' setup from the acquia repository. Now I am unable to start vagrant. 'Vagrant up' complains that A VirtualBox machine with the name 'compscisbu.localvm.stonybrook.edu' already exists. What is the best way to fix this?

**Comment by oxyc** [comment]
If you wan't to use the existing machine without deleting it: 

Find the ID of your VM using
> $ vboxmanage list vms
> "my-vm" {c700b8b6-b766-4638-871b-736b44b7db18}

Copy the ID of the desired VM (the c700…db18 string) into the contents of .vagrant/machines/<machine>/virtualbox/id.

https://stackoverflow.com/a/30910282/319855

---

If you want to delete it and start fresh, do the above and then simply `vagrant destroy; vagrant up`

**Comment by vibanu** [comment]
I get bash: vboxmanage: command not found error when I type vboxmanage list
vms



$ vboxmanage list vms

bash: vboxmanage: command not found





*From:* Oskar Schöldström [mailto:notifications@github.com]
*Sent:* Tuesday, June 6, 2017 9:50 AM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Author
*Subject:* Re: [geerlingguy/drupal-vm] Cannot bring up vagrant (#1414)



If you wan't to use the existing machine without deleting it:

Find the ID of your VM using

$ vboxmanage list vms
"my-vm" {c700b8b6-b766-4638-871b-736b44b7db18}

Copy the ID of the desired VM (the c700…db18 string) into the contents of
.vagrant/machines//virtualbox/id.

https://stackoverflow.com/a/30910282/319855
------------------------------

If you want to delete it and start fresh, do the above and then simply vagrant
destroy; vagrant up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1414#issuecomment-306491795>,
or mute the thread

**Comment by oxyc** [comment]
Ah you're on windows, I'm not sure where that command is located.

> C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" list vms

something similar to that

**Comment by vibanu** [comment]
Yes, I am on windows.

On GIT – ‘vagrant global-status’ shows the following and below this is
attached the screen capture from Oracle VM VirtualBox Manager



$ vagrant global-status

id       name               provider   state    directory

------------------------------------------------------------------------------------

6f69dee  drupalvm           virtualbox poweroff C:/DrupalVM

70e87e4  drupalvm           virtualbox running
C:/Users/vibha/Sites/compscisbu

270a643  compscisbu.localvm virtualbox poweroff
C:/users/vibha/Sites/compscisbu







*From:* Oskar Schöldström [mailto:notifications@github.com]
*Sent:* Tuesday, June 6, 2017 9:56 AM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Author
*Subject:* Re: [geerlingguy/drupal-vm] Cannot bring up vagrant (#1414)



Ah you're on windows, I'm not sure where that command is located.

C:\Program Files\Oracle\VirtualBox\VBoxManage.exe" list vms

something similar to that

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1414#issuecomment-306493640>,
or mute the thread

**Comment by oxyc** [comment]
You'll need the full ID which I don't think you can get from something other than `VBoxManage.exe`. Could you search for it?

**Comment by oxyc** [comment]
If you don't care about the old machine, you can also try `vagrant destroy <id>`, that should delete it but if you want to restore the old machine, you'll need to find the ID.

**Comment by vibanu** [comment]
From the stack link you sent to me.. I followed #2 and renamed the box on
Oracle VM; This worked.



‘Sometimes you might not want to delete old box. Yesterday may old Vagrant
has broken, I've updated Vagrant and Virtualbox but folders mapping didn't
work. I wanted to run new box and had this error…..

Thank you for your help that lead me in the right direction.



Regards,

Vibha.

*From:* Oskar Schöldström [mailto:notifications@github.com]
*Sent:* Tuesday, June 6, 2017 10:01 AM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Author
*Subject:* Re: [geerlingguy/drupal-vm] Cannot bring up vagrant (#1414)



You'll need the full ID which I don't think you can get from something
other than VBoxManage.exe. Could you search for it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1414#issuecomment-306495284>,
or mute the thread

**Comment by vibanu** [comment]
I resolved the problem of starting the vagrant but no longer can use drush.
Any lead on this?



Command pm-update needs a higher bootstrap level to run - you will need to
invoke drush from a more [error]

functional Drupal environment to run this command.

The drush command 'pm-update' could not be executed.



*From:* Oskar Schöldström [mailto:notifications@github.com]
*Sent:* Tuesday, June 6, 2017 9:50 AM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Author
*Subject:* Re: [geerlingguy/drupal-vm] Cannot bring up vagrant (#1414)



If you wan't to use the existing machine without deleting it:

Find the ID of your VM using

$ vboxmanage list vms
"my-vm" {c700b8b6-b766-4638-871b-736b44b7db18}

Copy the ID of the desired VM (the c700…db18 string) into the contents of
.vagrant/machines//virtualbox/id.

https://stackoverflow.com/a/30910282/319855
------------------------------

If you want to delete it and start fresh, do the above and then simply vagrant
destroy; vagrant up

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1414#issuecomment-306491795>,
or mute the thread

**Comment by vibanu** [comment]
This was an old issue resolved long time back..



*From:* Oskar Schöldström [mailto:notifications@github.com]
*Sent:* Thursday, June 15, 2017 12:40 PM
*To:* geerlingguy/drupal-vm
*Cc:* vibanu; Author
*Subject:* Re: [geerlingguy/drupal-vm] Cannot bring up vagrant (#1414)



Could you post your config.yml?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/geerlingguy/drupal-vm/issues/1414#issuecomment-308797976>,
or mute the thread
