### ISSUE TITLE
Adminer doesn't install correctly on Ubuntu 12.04

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#142]
Screenshot: https://www.evernote.com/l/AUlj4ho24L5IRY0tz1gLM6kLVU2yaMw2gJk

Output:

TASK: [geerlingguy.adminer | Set the proper Apache configuration directory (Debian).] *** 
ok: [psproject]

*TASK: [geerlingguy.adminer | Add Apache configuration file for Adminer (Debian).] *** 
failed: [psproject] => {"failed": true}
msg: Destination directory /etc/apache2/conf.d does not exist*

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/adam.bergstein/playbook.retry

psproject                  : ok=104  changed=51   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

                                                                       
  [RuntimeException]                                                   
  Ansible failed to complete successfully. Any error output should be  
  visible above. Please fix these errors and try again.                
                                                                       

install [--overwrite] [--temporary]

**Comment by nerdstein** [comment]
using ubuntu1204 box

**Comment by geerlingguy** [comment]
Most likely an upstream bug in the adminer role—has to do with different apache paths on 12.04 vs 14.04.

**Comment by geerlingguy** [comment]
Fixed upstream. Adminer role version 1.0.1 fixes this issue, so please run `ansible-galaxy install -r requirements.txt --force` in the root project directory to get the latest version.
