### ISSUE TITLE
NFS sync not working in 4.5.0?

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#1422]
### Issue Type
 - Documentation Report

### Your Environment
```
Vagrant 1.9.3
VirtualBox 5.1.18r114002
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** 10.12

### Summary
I have a question about nfs sync with the latest release. Following the fairly detailed instructions [here](https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod), I'm unable to get sync working properly. 

Testing against an older version, 4.1.1 for example, works fine, i.e. changes to files on the host are synchronized with changes on the remote vm and vice-versa. Not so with 4.5.0.

In both cases, the log output reads:
```
==> local-example: Setting hostname...
==> local-example: Configuring and enabling network interfaces...
==> local-example: Exporting NFS shared folders...
==> local-example: Preparing to edit /etc/exports. Administrator privileges will be required...
==> local-example: Mounting NFS shared folders...
==> local-example: Checking for bindfs in VM...
        local-example: Package manager detected: apt-get
        local-example: Fuse kernel module is installed
        local-example: Fuse kernel module is loaded
==> local-example: Bindfs seems to not be installed on the virtual machine, installing now
        local-example: Bindfs 1.12.6 is installed
==> local-example: Machine is ready to use bindfs!
==> local-example: Creating bind mounts after synced_folders...
        local-example: /var/nfs/[redacted]/testing => /var/www/drupal
==> local-example: Configuring cache buckets...
```

Relevant vagrant.config.yml stanza block looks like this:
```
vagrant_synced_folders:
  - local_path: .
    destination: /var/www/drupal
    type: nfs
```

/etc/exports on my host looks ok. Note that I'm also using Vagrantfile.local as directed [here](http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors), which is respected in the 4.1.x version and appears to be ignored in the 4.5.0 release.

Not sure how to troubleshoot this or what else I may be missing.

**Comment by oxyc** [comment]
Does it work without `vagrant-bindfs`? If you remove the plugin and `Vagrantfile.local`.

I tested locally and it did work for me using `vagrant-bindfs` v1.0.7 and Vagrant v1.9.4.

**Comment by minorscience** [comment]
I think I may not be understanding the file and directory structure. Reading through the soup-to-nuts post and the DrupalVM as Composer docs, its a little unclear how things should be laid out. 

Can you post a directory skeleton when you have a second? 

Something like this (from the docs) would be super helpful.

```
├── composer.json
├── config/
│   ├── config.yml
│   ├── local.config.yml
│   └── Vagrantfile.local
├── docroot/
│   ├── ...
│   └── index.php
└── vendor/
    ├── ...
    └── geerlingguy/
        └── drupal-vm/
```

**Comment by oxyc** [comment]
If you're using Drupal VM as a composer dependency, then that's correct. Although @geerlingguy uses `vm/` instead of `config/` in that blog post.

The delegating Vagrantfile should be on the same leve as the `composer.json` file:

```
├── Vagrantfile
├── composer.json
├── config/
│   ├── config.yml
│   ├── local.config.yml
│   └── Vagrantfile.local
├── docroot/
│   ├── ...
│   └── index.php
└── vendor/
    ├── ...
    └── geerlingguy/
        └── drupal-vm/
```

**Comment by oxyc** [comment]
For a proper example repo you can have a look at https://github.com/geerlingguy/drupalvm-live which is the source for http://prod.drupalvm.com/

**Comment by minorscience** [comment]
Ok, that's pretty much what I have in terms of structure.

I upgraded vagrant to 1.9.4 and that seems to have resolved the issue, though I don't exactly understand how/why.

Closing. Thanks as always.

**Comment by oxyc** [comment]
`vagrant-bindfs` is also working now?

**Comment by geerlingguy** [comment]
@minorscience - Thanks for following up!
