### ISSUE TITLE
Don't Use .dev For Development

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1427]
### Issue Type

 - Bug Report / Support Request

### Summary

I was getting some browser errors on certain pages for a while, namely ERR_ICANN_NAME_COLLISION.
After searching around it seems the use of the .dev TLD was the culprit.
The IETF released a list of Reserved TLDs, namely:
- test
- example
- invalid
- localhost

Read more about it at https://iyware.com/dont-use-dev-for-development
So my proposition would be to change the default config from .dev to one of the reserved TLDs.
And maybe mention this in the default.config.yml file, so people stop using .dev :)

today i learned...

cheers!
tom

**Comment by oxyc** [comment]
Related https://github.com/geerlingguy/drupal-vm/issues/592

**Comment by geerlingguy** [comment]
Ugh. Google-- for taking over the one root domain that sort-of universally worked without any issues for local development environments.

**Comment by geerlingguy** [comment]
Just a note, though—as long as you have the domain in your hosts file, Chrome _shouldn't_ pop that error.

**Comment by geerlingguy** [comment]
And moving forward, I kept kicking the can down the road, but we should probably bite the bullet and choose some other TLD to use. Some people say `.local` is working better now... but I'm scared of using it since it has caused me issues in the past in a variety of places.

**Comment by oxyc** [comment]
So this will be solved in the next release now that we automatically install it?

**Comment by oxyc** [comment]
Personally I'm worried users wont `drupalvm.localhost` is an actual hostname. I don't think I would... `.local` would definitely be clearer, but if it comes with possible issues....

**Comment by geerlingguy** [comment]
I'm leaning slightly more towards `.test`.

Reasoning:

  1. It's short (almost as short as `.dev`).
  2. It's a default, and in many/most cases would only be used for testing purposes anyways—it's recommended people customize the hostname to be something more like `local.my-project-domain.com`, therefore the whole idea of `.test` being only for testing could technically still be true.

I don't like the linked article's assertions that ".test" is only for test servers and ".example" is for pre-prod, or something weird like that. I'd rather not try to assign semantic meaning to TLDs.

**Comment by betz** [comment]
> Just a note, though—as long as you have the domain in your hosts file, Chrome shouldn't pop that error.

It is in my hosts file, added by using vagrant hostsupdater. So very weird.
Guess it is a chrome thing. The browser that gave me these errors btw.

**Comment by geerlingguy** [comment]
Working on this now, switching to `drupalvm.test` in light of: [Chrome to force .dev domains to HTTPS via preloaded HSTS](https://ma.ttias.be/chrome-force-dev-domains-https-via-preloaded-hsts/)
