### ISSUE TITLE
Can't access virtual machine's webserver

### ISSUE THREAD

**Issue by Kopharex** [geerlingguy/drupal-vm#1429]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 11 2017, 12:22:40) [GCC 6.3.1 20170109]
```

### Your OS

 - **Linux** 4.11.5-1-ARCH

### Full console output

- [**vagrant up --provision --debug**](https://gist.github.com/Kopharex/fd1f62d993d7061e0375d46e909e1c49#file-vagrant_up_provision_debug-log)
- [**vagrant up --debug**](https://gist.github.com/Kopharex/fd1f62d993d7061e0375d46e909e1c49#file-vagrant_up-log)
- [**Debug commands on host**](https://gist.github.com/Kopharex/fd1f62d993d7061e0375d46e909e1c49#file-host_commands-txt)
- [**Debug commands on guest**](https://gist.github.com/Kopharex/fd1f62d993d7061e0375d46e909e1c49#file-guest_commands-txt)

### Summary

When I attempt to connect to my drupalvm, either via host domain or ip, i only get a white page which keeps loading for a few minutes then stops with no error message. I attempted to ping the virtual machine from my host and i get no response whatsoever. What's even stranger is that I can ping both the host and the guest when i ssh into the guest. I have searched on google extensively and I've been struggling with this for the past few days. I never used vagrant or virtualbox before. I have provided console outputs that might be useful for debugging in the links above.

I am using drupalvm 4.5.0.
Here's my [config.yml](https://gist.github.com/Kopharex/fd1f62d993d7061e0375d46e909e1c49#file-config-yml).

Any help is appreciated,
Riccardo

**Comment by geerlingguy** [comment]
@Kopharex - In this case, if the page loads for a while then results in a white page, you might be running into the infamous [white screen of death](https://www.drupal.org/node/158043). To check for this, log into the VM (`vagrant ssh`), then `cd /var/log/apache2` and then use `cat` or `tail` to check out the `errors.log` file. Maybe it's running out of memory or hitting a timeout?

If you create an HTML file in the docroot (`touch /var/www/drupalvm/drupal/web/test.html`), then try loading it (on host, visit drupalvm.local/test.html), does it load right away, or does it still wait for a couple minutes?

Also, do you see an entry for Drupal VM in the /etc/hosts file on your host?

**Comment by oxyc** [comment]
A few other suggestions:

- What do the `vboxnet` interfaces look like if you run `ifconfig`?
- Do you have `net-tools` installed? [Archwiki](https://wiki.archlinux.org/index.php/Vagrant) mentions that it solves a lot of issues

**Comment by Kopharex** [comment]
@oxyc Installing net-tools solved the issue. I can't believe I missed that section on the archlinux wiki. Thank you very much!
