### ISSUE TITLE
Docker Documentation for [OPTIONS]

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#1431]
On the docker documentation it shows you can put optional [OPTIONS] in the front of the composer command.

http://docs.drupalvm.com/en/latest/other/docker/
```
[OPTIONS] composer docker-bake
```

I've never seen this in the front like that, not sure how to write those [OPTIONS], could you add an example?

My guess with limited knowledge would be the following to get it picked up as a bash script variable?
```
DISTRO=centos7;DRUPALVM_IP_ADDRESS=192.168.99.99;composer docker-bake
```

**Comment by geerlingguy** [comment]
Close — you can set those like:

```
DISTRO=centos7 DRUPALVM_IP_ADDRESS=192.168.99.99 composer docker-bake
```

I guess it would be better to have an explicit example so it's more obvious. Doing in this way ensures the environment vars are only set for the duration of the command that follows.

**Comment by joelpittet** [comment]
Thanks, that was so close!

**Comment by geerlingguy** [comment]
Fixed via above commit. New example uses:

    DRUPALVM_IP_ADDRESS='192.168.88.9' DISTRO='debian9' composer docker-bake
