### ISSUE TITLE
vagrant exec pwd is /vagrant by default

### ISSUE THREAD

**Issue by mikemadison13** [geerlingguy/drupal-vm#1432]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:46:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** 10.11.6
### Full console output

```
$ vagrant exec pwd
/vagrant
```

### Summary

This is a cross post from https://github.com/acquia/blt/issues/1681 where running Behat commands with BLT w/in DrupalVM are failing. Digging into this, it seems that my vagrant config is looking in the wrong place (/vagrant vs. /var/www/<project>). As a result, I am getting composer autoload errors. 

It seems like we may need to set the exec pwd path in the VM so that things are running the proper location?

cc @grasmash and @geerlingguy

**Comment by oxyc** [comment]
This isn't configured out of the box, but there's a docs page on it http://docs.drupalvm.com/en/latest/extras/drupal-console/#remote-command-execution-using-vagrant-exec

**Comment by geerlingguy** [comment]
It looks like there's a PR #1435 related to this issue.

I'm still on the fence on whether I want to add explicit conditional config for this as part of Drupal VM. For my own needs, outside of BLT, I've not yet had a use case where vagrant exec was essential... just a nice little tool if you really want to use it. But for most things, using `vagrant ssh` or automating things via Ansible or Drush to work in the VM is easier/faster.

cc @grasmash

**Comment by geerlingguy** [comment]
It looks like this was fixed downstream, in BLT; see https://github.com/acquia/blt/issues/1681 and https://github.com/acquia/blt/commit/1bc9e39e7fef63327d7abfdc1b4acd8905cb4b8c
