### ISSUE TITLE
Having problems installing on my Windows Laptop

### ISSUE THREAD

**Issue by SteveS-CC** [geerlingguy/drupal-vm#1433]
### Issue Type
 - Bug Report / Support Request
### Your Environment
Vagrant 1.9.5
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
### Your OS
 - **Windows** 8.1
### Full console output
https://gist.github.com/SteveS-CC/12e5a2a983a5f2212c7884b35d2dc13e
### Summary
Trying to Install per the Quick Start Guide here - https://github.com/geerlingguy/drupal-vm#quick-start-guide
and the Video here - http://docs.drupalvm.com/en/latest/getting-started/installation-windows/

Getting error messages - stuck - see console output above.

Steve

**Comment by geerlingguy** [comment]
It looks like the key error is:

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.
```

Can you run `vagrant destroy -f` to delete the VM, then reboot your computer and try `vagrant up` again in the Drupal VM directory? Also, do you have any virus scanning software running, or are you on a proxy or VPN? That can sometimes mess up VirtualBox or Vagrant.

There are hundreds of different things that can cause that error, so we need to narrow it down a bit. See, for example:

  - https://discourse.roots.io/t/timed-out-while-waiting-for-the-machine-to-boot/5943
  - https://github.com/Automattic/vip-quickstart/issues/516
  - https://github.com/geerlingguy/drupal-vm/issues/953
  - https://github.com/Automattic/vip-quickstart/issues/502

You can also maybe open up the VirtualBox app GUI and see if the machine looks like it's running okay inside there.

**Comment by SteveS-CC** [comment]
Thanks for responding.  Decided to use a desktop computer to avoid struggling with laptop.  I will look into your suggestions if I change course and go back to laptop.  Good leads if anyone else hits the same snag/s.
