### ISSUE TITLE
Built-in support for bindfs

### ISSUE THREAD

**Issue by kentr** [geerlingguy/drupal-vm#1434]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.18r114002
ansible 2.3.0.0
  config file = /Users/Work/eclipse-workspace/kentrichards.net/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr 23 2017, 16:50:50) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

### Your OS

 - **macOS** (version)

### Summary

Would you consider a PR that automatically uses `vagrant-bindfs` under the right conditions, such as?:

* The plugin exists
* The share type is `nfs`
* `use_bindfs` is true for the synced folder item

**Comment by oxyc** [comment]
I'm curious, what's your use case for `vagrant-bindfs`? Does it solve any issue?

**Comment by oxyc** [comment]
I think a lot of Vagrant tools use it to ensure files are writable but Drupal VM solves this by ensuring a valid uid/gid exist for what NFS uses. https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/roles/drupalvm.www/tasks/main.yml#L12:L79

**Comment by kentr** [comment]
Hmm.  I turned to `vagrant-bindfs` because permissions weren't working for me.  I may have been using an older version of DrupalVM.

Still, it's mentioned in the [DrupalVM docs](http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors) as a solution to permissions problems.

I'll make sure I'm up-to-date and see if the problems are still there.

**Comment by oxyc** [comment]
If there are issues (and it's possible that there are) maybe we can try and fix them in Drupal VM. `vagrant-bindfs` definitely makes it easier for things to _just work_ but would be nice to manage without the extra overhead of `bindfs`

**Comment by geerlingguy** [comment]
Yeah, I think I'd still rather not include support out of the box... it can cause more grief than it's worth if someone has the plugin installed but doesn't really know what they're doing with it.
