### ISSUE TITLE
Error installing Drupal

### ISSUE THREAD

**Issue by Fynkymynky** [geerlingguy/drupal-vm#1439]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
ansible 2.3.1.0
```

### Your OS

 - **macOS** (10.12)

### Full console output

https://gist.github.com/Fynkymynky/7fc356ec35a5704a36829da95a20304e

### Summary

I've downloaded the latest stable build from the website, when I run the build process, Vagrant fails during the Drupal installation stage. I've attempted this out of the box from the website and with using the Drush make method, neither work.

**Comment by geerlingguy** [comment]
It looks like the actual error is:

```
[RuntimeException]                                                                                           
Could not scan for classes inside "web/core/lib/Drupal.php" which does not appear to be a file nor a folder
```

And searching that on Google brought me to https://github.com/drupal-composer/drupal-packagist/issues/66 — it looks like the solution is to update Composer (`composer self-update`), then delete the contents of the drupal directory and run `vagrant provision` again.

Can you see if that works?

**Comment by Fynkymynky** [comment]
Thanks, I downloaded the latest build from git and that worked.

**Comment by davidwhthomas** [comment]
Just want to note, I had this issue and solved it by removing the drupal directory in `rm -rf core` and running `composer install` again

**Comment by imperator99** [comment]
I solved this issue by running `composer self-update`, deleting the `vendor` directory and then running `composer install`.

**Comment by harpreet16** [comment]
deleting core manually and running `composer install` worked for me.

**Comment by TeachHip** [comment]
> Deleting the vendor directory and running `composer install` seems to solve it.

It did solve it! Thank you :-)
