### ISSUE TITLE
Forbidden/403 at docroot

### ISSUE THREAD

**Issue by brentratliff** [geerlingguy/drupal-vm#1440]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
VirtualBox 5.1.18r114002
ansible 2.3.1.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 **(clang-800.0.34)]**
```

### Your OS

 - **macOS** 10.12.5

### Summary

Local codebase via docs.  I get a Forbidden/403 at the docroot.  I even added a 'hello world' index.html with 777 privileges.

**Comment by oxyc** [comment]
Could you post your `config.yml`?

**Comment by brentratliff** [comment]
https://gist.github.com/brentratliff/048ccddcaa85204f151e2ffaf2995829

Thanks

**Comment by oxyc** [comment]
You're missing a leading slash:

```yaml
drupal_core_path: "var/www/jenni"
```

should be:

```yaml
drupal_core_path: "/var/www/jenni"
```

**Comment by brentratliff** [comment]
I did fix that since it was incorrect but I'm getting the same error.  I tried both provision and destroy + up.

**Comment by brentratliff** [comment]
I did a vagrant ssh and noticed that the synced folder went to the drupalvm folder.  I did a destroy, updated vagrant and then vagrant up.  It is now working with 1.9.5.  Thanks for the catch with the /
