### ISSUE TITLE
Some suggestions on how to improve Quick Start Guide 

### ISSUE THREAD

**Issue by SteveS-CC** [geerlingguy/drupal-vm#1448]
### Issue Type
 - Documentation Report
### Your OS
 - **Windows 10

### Summary

I just got a DrupalVM box installed on my machine.  It was a struggle with lots of web searching and guesswork.  The video -installing on a laptop was critical for me.  I don't think I could have succeeded from the written alone.

A couple things that I'm still unclear on even though the drpalvm box is running:  

Hosts File:  It was pretty much dumb luck that led me to edit my hosts file when drupal would not start at http://drupalvm.dev/.  Shouldn't the host plugin that is part of the vm have handled that automatically?  Do I need to install one of the hosts plugins manually?  Or is manual editing of the hosts file the best method. In any case I think the docs should spell this out so people aren't stumped after a successful install like i was.

Mods to drupalvm folder:  Can I make changes to the drupalvm folder on my desktop?  Can I move it to a diff location?  Can I rename it.  Will copies with different names and in different location run ok and play nice together?

This is probably more of a Vagrant/VirtualBox question but:  When I start drupalvm box with Vagrant Up the Oracle VirtualBox app does not open.  If I open it I see drupalvm.dev in it and running though.  Waht is the reccommended procedure for handling the VM when I want to shut down my computer?  Vagrant halt?  Close it in the VirtualBox app?  or just shut down?

I would be willing to help out with improving the Quick start guide and Documentation if you would like.  Since i am so new to this stuff I might be able to help you address simple stuff that you and more experienced users take for granted.

Thanks

**Comment by oxyc** [comment]
> Hosts File: It was pretty much dumb luck that led me to edit my hosts file when drupal would not start at http://drupalvm.dev/. Shouldn't the host plugin that is part of the vm have handled that automatically? Do I need to install one of the hosts plugins manually? Or is manual editing of the hosts file the best method. In any case I think the docs should spell this out so people aren't stumped after a successful install like i was.

Unfortunately the current README reflects the master branch which still isn't available as a stable release. There used to be a section here about editing your hosts file but since https://github.com/geerlingguy/drupal-vm/issues/1378 we auto-install `vagrant-hostsupdater` and the step is no longer needed.

> Mods to drupalvm folder: Can I make changes to the drupalvm folder on my desktop? Can I move it to a diff location? Can I rename it. Will copies with different names and in different location run ok and play nice together?

Unfortunately you can't. If you do want to move it you have to remove the relevant entry from `/etc/exports` and run `vagrant reload`.

> This is probably more of a Vagrant/VirtualBox question but: When I start drupalvm box with Vagrant Up the Oracle VirtualBox app does not open. If I open it I see drupalvm.dev in it and running though. Waht is the reccommended procedure for handling the VM when I want to shut down my computer? Vagrant halt? Close it in the VirtualBox app? or just shut down?

With Vagrant you don't need to use the VirtualBox app at all, even if you can. Yes, you should use `vagrant halt`. I rarely bother though

**Comment by SteveS-CC** [comment]
>  Hosts File: It was pretty much dumb luck that led me to edit my hosts file when drupal would not start at http://drupalvm.dev/. Shouldn't the host plugin that is part of the vm have handled that automatically? Do I need to install one of the hosts plugins manually? Or is manual editing of the hosts file the best method. In any case I think the docs should spell this out so people aren't stumped after a successful install like i was.

Unfortunately the current README reflects the master branch which still isn't available as a stable release. There used to be a section here about editing your hosts file but since #1378 we auto-install vagrant-hostsupdater and the step is no longer needed.

I'm not really clear about your response.  Was the fact that I needed to manually edit my hosts file a sign that something went wrong or expected?  Is manual editing of the hosts file recommended or should I have added a plugin instead?  -  vagrant-hostsupdater or vagrant-hostmanager plugin?

**Comment by oxyc** [comment]
> I'm not really clear about your response. Was the fact that I needed to manually edit my hosts file a sign that something went wrong or expected? Is manual editing of the hosts file recommended or should I have added a plugin instead? - vagrant-hostsupdater or vagrant-hostmanager plugin?

In the next release, `vagrant-hostsupdater` will be installed automatically and after that this shouldn't happen again. For now you can either edit the `/etc/hosts/` file manually like you did, or install `vagrant-hostsupdater` and let Vagrant manage it for you.

**Comment by geerlingguy** [comment]
Yeah, sorry about that—sometimes the docs reflect the master/in-development work and can cause a little confusion. I'll be releasing a new version soon that will automatically install hostsupdater (as @oxyc mentioned), and it should make things a bit simpler.

Also, just be aware that using Drupal VM (or any Vagrant project) on Windows will likely have a few rough spots—it's just the way things are (see my post on the topic: [Developing with VirtualBox and Vagrant on Windows](https://www.jeffgeerling.com/blog/2016/developing-virtualbox-and-vagrant-on-windows).

Closing this issue as I think the main questions have been answered—please let me know if that's not the case!
