### ISSUE TITLE
Windows support?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#145]
Quick question, can this be ran on Windows to provision a linux VM? Last I looked into it, Ansible was not capable of doing this.

**Comment by geerlingguy** [comment]
Yes; it fully supports Windows as a host OS, and simply uses the [JJG-Ansible-Windows](https://github.com/geerlingguy/JJG-Ansible-Windows) script to run Ansible from _within_ the VM on Windows machines.

There are a couple small niceties that you don't get on Windows, like automatic host drush aliases and nice terminal output during provisioning, but everything should work fine.
