### ISSUE TITLE
Add build-drupal-project script for Docker container

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1457]
### Issue Type

 - Feature Idea

### Summary

Similar to the `install-drupal` script, I'm thinking it would be quite convenient to wrap the [Composer template for Drupal projects](https://github.com/drupal-composer/drupal-project) inside a shell script in such a way that a user could do something like:

    docker run -d -p 80:80 -p 443:443 --name=drupalvm --privileged -v /local/project/path:/var/www/drupalvm/ geerlingguy/drupal-vm
    docker exec drupalvm build-drupal-project

And then it would build a Drupal project via the template (using Composer), and then install the site using Drush using all the Drupal VM defaults.

That would be a nice happy medium between the utilitarian `install-drupal` script and the full-fledged Vagrant-based provisioned Drupal VM instance. It would be the quickest way I can think of to generate and flesh out a new Drupal 8 site that you intend to turn into a long-term managed project.

One caveat for Mac users: _until Docker CE includes `delegated` writes (with caching) on macOS, the Composer commands would be exponentially slower on Mac than Linux or Windows, at least when using a volume (`-v`).

**Comment by geerlingguy** [comment]
I gotta quit giving myself more work :P

**Comment by kevinhowbrook** [comment]
I was sort of coming up with the same thought today.
Maybe I'm not as familiar with the process yet but when I run docker-compose up -d I cannot seem to get composer to build a drupal core, either in the container or in the host folder. With vagrant I think this is all fine (using the config.yml).

Does docker compose / docker build read from the default.config.yml and build accordingly?

**Comment by geerlingguy** [comment]
@kevinhowbrook - Yeah, so far that's not supported, and I'm hoping to make that possible through a new `build-drupal-project` script. At this time, I don't want to make it so running docker-compose automatically runs any major provisioning steps (e.g. kick off a playbook), just because that might be a bit heavyweight and/or too 'magic' in terms of what's expected in the Docker world.

**Comment by geerlingguy** [comment]
The install-drupal script has been updated to build a drupal project using Composer now... see https://github.com/geerlingguy/drupal-vm/issues/1692
