### ISSUE TITLE
Deploy prod to Debian stretch

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1459]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.5
VirtualBox 5.1.22r115126
```

### Your OS

 - **macOS** (el capitan)

### Full console output
https://gist.github.com/betz/83056615e7fb84ae677d0424ba7174f2

### Summary
Trying to deploy prod env to debian stretch (9).
First error was the java jdk was version openjdk-7-jdk, after changing this to openjdk-8-jdk i got error displayed on gist above. 
BTW, following this guide:
https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod#build-prod

**Comment by oxyc** [comment]
You'll need the latest Drupal VM 4.6.0 release for Varnish on Debian Stretch. https://github.com/geerlingguy/drupal-vm/issues/1451#issuecomment-312121250

**Comment by geerlingguy** [comment]
@betz - Exactly as @oxyc said—that was a last-minute addition that just started working earlier today, but it requires 4.6.0 or later to work.

**Comment by betz** [comment]
Super, thanks!
