### ISSUE TITLE
Unable to install pecl package

### ISSUE THREAD

**Issue by pminf** [geerlingguy/drupal-vm#1462]
### Issue Type

Bug Report / Support Request

### Your Environment

Drupal-VM 4.6.0
Vagrant 1.9.6
VirtualBox 5.1.22 r115126 (Qt5.6.2)

### Your OS

Microsoft Windows 10 Pro (10.0.14393)

### Full console output

Error during initial `vagrant up` or later `vagrant reload --provision`
```
TASK [geerlingguy.php-pecl : Install PECL libaries.] ***************************
failed: [drupalvm] (item=jsmin) => {"changed": false, "cmd": "yes \"\" | pecl install jsmin", "delta": "0:00:00.003134", "end": "2017-07-03 09:18:31.724070", "failed": true, "failed_when_result": true, "item": "jsmin", "rc": 127, "start": "2017-07-03 09:18:31.720936", "stderr": "/bin/sh: 1: pecl: not found\nyes: standard output: Broken pipe", "stderr_lines": ["/bin/sh: 1: pecl: not found", "yes: standard output: Broken pipe"], "stdout": "", "stdout_lines": []}
```

config.yml (identical to default.cnfig.yml besides the php_pecl_extensions part)
```
# PHP Configuration. Currently-supported versions: 5.6, 7.0, 7.1.
# See version-specific notes: http://docs.drupalvm.com/en/latest/configurations/php/
php_version: "7.1"
php_install_recommends: no
php_memory_limit: "192M"
php_display_errors: "On"
php_display_startup_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/opt/mailhog/mhsendmail"
php_opcache_enabled_in_ini: true
php_opcache_memory_consumption: "192"
php_opcache_max_accelerated_files: 4096
php_max_input_vars: "4000"

# Drupal VM defaults to using PHP-FPM with either Apache or Nginx. If you wish
# to instead use Apache + mod_php with an Ubuntu base box, make sure you add
# libapache2-mod-php7.0 to `extra_packages` elsewhere in this config file.
php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"

php_pecl_extensions:
  - jsmin
```

### Summary
According to [Help installing PHP PECL "jsmin" extension?](https://github.com/geerlingguy/drupal-vm/issues/888) I'm trying to install the php extension `jsmin` via PECL by using `php_pecl_extensions`. I get the error: 

> /bin/sh: 1: pecl: not found\nyes: standard output: Broken pipe

**Comment by pminf** [comment]
This is a general issue with pecl and not specific to jsmin. Installing package `imagick` results the same error.

**Comment by geerlingguy** [comment]
Hmm, `pecl` _should_ be installed, but it may be an upstream bug in the https://github.com/geerlingguy/ansible-role-php-pecl role.

**Comment by geerlingguy** [comment]
It looks like at some point a while back, `php-pecl` was removed from the default packages list in the `php-versions` role.

For `imagick`, Ondrej's PPA for Ubuntu already has the `php-imagick` package available, but it looks like he doesn't package up either `pecl` or `jsmin` in particular.

**Comment by geerlingguy** [comment]
There's also the PHP `pear` module for Ansible... http://docs.ansible.com/ansible/pear_module.html

**Comment by oxyc** [comment]
Seems the package containing pecl is `php-pear`. Unfortunately no `php7.1-pear` is available so I don't think this works with version switching.

**Comment by oxyc** [comment]
fyi the current release of `jsmin` does not support php7+ https://github.com/sqmk/pecl-jsmin/issues/43

**Comment by geerlingguy** [comment]
@oxyc - I may inquire as to whether @oerdnj has any plan on adding `pear` to his repo anymore. I know in the past there's been a lot of discussion around whether many of the standard pear/pecl libraries will be maintained going forward :/

Pear/pecl has always been a bit of an odd duck in the PHP ecosystem (at least IMO).

**Comment by oerdnj** [comment]
`php-pear` is there and it should support version switching if `pecl` accepts php-config option (which I don't know from top of my head).

**Comment by geerlingguy** [comment]
@oerdnj - good to know! I'll do some more testing when I get a chance then. And, for like the zillionth time, thanks so much for your packaging work!

**Comment by geerlingguy** [comment]
It looks like that does the trick on Debian/Ubuntu! I opened up an upstream issue in the php-pecl role repo, and once this ticket is closed, you can add the following to your `config.yml` to successfully install extensions from Pecl:

```yaml
php_pecl_install_pecl: true
php_pecl_extensions:
  - redis
```

Note that some (many?) pecl extensions require other dependencies as well... e.g. `yaml` requires `libyaml-dev`, `imagick` requires `libmagick` or something like that, etc.

If you need to install those dependencies, consider adding them to a list of `php_packages_extra`, so they'll be installed prior to the `pecl install` commands.

**Comment by geerlingguy** [comment]
Note that this feature will only be available in Drupal VM's master branch until the next minor release.
