### ISSUE TITLE
Vagrant up fails with missing libssl1.1 package.

### ISSUE THREAD

**Issue by jiisuominen** [geerlingguy/drupal-vm#1466]
### Issue Type
 - Bug Report / Support Request

### Your Environment
Vagrant 1.8.6
VirtualBox 5.1.22r115126
-bash: ansible: command not found
(Can't get ansible installed, but that has never been an issue before..)

### Your OS
 - **macOS** (10.11.6)

### Full console output
https://gist.github.com/jiisuominen/047065d0a0f497b5fdbba1344a222b2b

### Summary

Just trying to create new VM with latest master branch and updated VirtualBox and the rest. Every time exits with same status, fails with missing libssl1.1. I tried installing that manually, but it seems to be missing from the repo altogether.

So I'm out of options / skills here, can't get any VM's created because of this missing libssl issue.

**Comment by thom8** [comment]
@jiisuominen can you try updating the base box `vagrant box update`, if you have the latest installed please post your `config.yml`

**Comment by jiisuominen** [comment]
Yeah, I've run `vagrant box update`, current version being 1.1.4.

Here's my config.yml: https://gist.github.com/jiisuominen/41def13c38595f23df19920abb7a21e8

**Comment by oxyc** [comment]
Should be fixed as of 2h ago https://github.com/oerdnj/deb.sury.org/issues/639

**Comment by InPhoenity** [comment]
I had the same issue this morning but it's now fixed.

**Comment by oxyc** [comment]
Great, I'll close this as it was fixed upstream.
