### ISSUE TITLE
Latest `nfs-utils` doesn't work out of the box with Vagrant

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1468]
### Issue Type

 - Bug Report / Support Request

### Summary

As of [`nfs-utils-2-1-2-rc2`](http://git.linux-nfs.org/?p=steved/nfs-utils.git;a=commit;h=fbd7623dd8d5e418e7cb369d4026d5368f7c46a6) ([discussion](https://patchwork.kernel.org/patch/9591703/)) UDP is disabled by default thus requiring the user to either:

1.  enable udp in `/etc/nfs.conf`
2. change the nfs options in Drupal VM's `config.yml`

At the moment this only affect Fedora 25+ but we _have had_ issues regarding this before. Not sure what prompted them then as the the repo sources do specify versions that should have udp and nfsv3 support.

Some `nfs-utils` versions across distros.

- [x] Ubuntu 16.04: UDP enabled `nfs-utils v1.2.8` [ref](https://launchpad.net/ubuntu/xenial/+source/nfs-utils)
- [ ] Fedora 25, 26: UDP disabled `nfs-utils v2.1.1-5.rc4+` [ref](https://apps.fedoraproject.org/packages/nfs-utils)
- [x] Arch Linux: UDP enabled `nfs-utils v2.1.1-4` [ref](https://www.archlinux.org/packages/core/i686/nfs-utils/)
- [x] Debian 9: UDP enabled `nfs-utils v 1.3.4-2.1` [ref](https://packages.debian.org/search?searchon=sourcenames&keywords=nfs-utils)

I think it's still fairly safe to default to nfsv4 on Linux hosts as they mention in the commit that it's been supported for a decade. A possible fix:

```rb
   if options[:type] == 'nfs' && !options.key?(:nfs_version) && Vagrant::Util::Platform.linux?
     options[:nfs_version] = 4
     options[:nfs_udp] = false
   end
```

Related:
- https://github.com/geerlingguy/drupal-vm/issues/1040#issuecomment-313215521
- https://github.com/geerlingguy/drupal-vm/issues/245
- https://github.com/geerlingguy/drupal-vm/issues/1425#issuecomment-310796259
- https://github.com/geerlingguy/drupal-vm/issues/1375
- https://github.com/geerlingguy/drupal-vm/issues/893

**Comment by oxyc** [comment]
@yareckon mind sharing why you changed the nfs version? Was it because it didn't work out of the box, or something else?

@quietone1 did you have the default nfs-utils package or had you updated it manually or done other config configurations? I'm wonder why nfsv3 with udp didn't work for you on Debian Jessie.

 @larmedina75 you mentioned you were using nfsv4, was this the default on your distro? Which distro are you using?

**Comment by oxyc** [comment]
I don't think we actually need to specify NFSv4, we could just let the default be used but set it to use TCP rather than UDP. This works on macOS sierra too and even gives a performance improvement for me.

**Comment by oxyc** [comment]
An employee at HashiCorp also recommended my latest suggestion when using intense composer installs https://github.com/mitchellh/vagrant/issues/7799#issuecomment-315909690

**Comment by oxyc** [comment]
Anyone on Linux who has had this issue, would be great if you could check if #1482 solves it.

**Comment by jozzya** [comment]
This looks very similar to the issue I had with Fedora 25. 
https://github.com/geerlingguy/drupal-vm/issues/245#issuecomment-308110394

**Comment by oxyc** [comment]
@jozzya yes that's the same issue. I'm now leaning more towards defaulting to TCP because:
- There's been a ton of random NFS bugs triggered during intense composer operations on Linux lately, all seem to be fixed by switching to TCP
- On my own macOS laptop there's no performance hit by switching to TCP. There's really no reason to use UDP unless it's faster, which it doesnt seem to be.
