### ISSUE TITLE
Error with 'drupal_deploy_updated'

### ISSUE THREAD

**Issue by dylanlawrence** [geerlingguy/drupal-vm#1472]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
$ vagrant --version
Vagrant 1.9.7

$ vboxmanage --version
5.1.4r110228

$ ansible --version
ansible 2.4.0
```

### Your OS
 - **macOS** (version)

### error output

`
TASK [geerlingguy.drupal : Define drupal_deploy_updated] ***********************
fatal: [fbm_vm]: FAILED! => {"failed": true, "msg": "the field 'args' has an invalid value, which appears to include a variable that is undefined.The error was: 'drupal_deploy_repo_updated' is undefined\n\nThe error appears to have been in '/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/main.yml': line 24, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Define drupal_deploy_updated\n  ^ here\n\nexception type: <class 'ansible.errors.AnsibleUndefinedVariable'>\nexception: 'drupal_deploy_repo_updated' is undefined"}
`

### Summary

Fresh install, latest and greatest, I keep running into this error about 'drupal_deploy_updated'

**Comment by geerlingguy** [comment]
It looks like you may be running Ansible 2.4, which is still a pre-release (alpha/beta quality), and there are definitely going to be some weird issues until it's more stable.

Can you switch to a stable version (current is 2.3.1) and see if you get the same error?

Also, probably unrelated, but it looks like you're running an old release of VirtualBox (5.1.4); the latest is 5.1.22: https://www.virtualbox.org/wiki/Downloads

**Comment by oxyc** [comment]
I'll close this as there hasnt been any response since July.

**Comment by wessel-techtribe-nl** [comment]
On macOS High Sierra with ansible 2.4 I had this problem indeed.

`pip3 install ansible==2.3.1` solved it. Thanks.
