### ISSUE TITLE
Drush is slow on my drupalvm

### ISSUE THREAD

**Issue by hmartens** [geerlingguy/drupal-vm#1475]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.4
VirtualBox 5.1.22r115126
ansible 2.3.0.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]

2015 Macbook Pro i7 2.2GHz
16Gb ram
256gb flash harddrive

### Your OS

 - **macOS** Sierra

### Summary

When I run drush cr it takes 58 seconds to run. I have allocated 4gb ram to my virtualbox for this drupalvm. 

My database file I did a dump of is 124mb, if that helps.

Thank you for your help.

**Comment by geerlingguy** [comment]
@hmartens - Can you post your `config.yml` file (if you have one set up)? I'm most interested in how you have your synced folders configured.

Also, if you open Activity Monitor on your Mac, and run `drush cr`, is there a lot of CPU activity?

Finally, assuming you have this same website running elsewhere, is `drush cr` fast in that environment?

**Comment by hmartens** [comment]
Hi Jeff, here's my config.yml. I've removed some of the sensitive info in there.
------------------------
---
# Acquia Cloud uses Ubuntu 12.04 LTS.

vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs

# If you need to run multiple instances of Drupal VM, set a unique hostname,
# machine name, and IP address for each instance.
vagrant_hostname: acsf-mysite-vm.dev
vagrant_machine_name: acsf-mysite-vm.dev
vagrant_ip: 192.myip

# Memory and CPU to use for this VM.
vagrant_memory: 2048
vagrant_cpus: 2


vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: ../../mysite
    destination: /var/www/drupalvm
    type: nfs
    create: true

build_makefile: false
build_composer: false
build_composer_project: false




# Set this to 'false' if you don't need to install drupal (using the drupal_*
# settings below), but instead copy down a database (e.g. using drush sql-sync).
install_site: false

drupal_core_path: "{{ drupal_composer_install_dir }}"
drupal_mysql_user: mysite_local
drupal_mysql_password: mysite_local
drupal_mysql_database: mysite_new

drupal_core_path: "/var/www/drupalvm/docroot"
drupal_domain: "mydomain-vm.dev"




apache_vhosts:
  - servername: "{{ drupal_domain }}"
    serveralias: "www.{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "mysite.dd"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "adminer.{{ vagrant_hostname }}"
    documentroot: "{{ adminer_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ adminer_install_dir }}"

  - servername: "xhprof.{{ vagrant_hostname }}"
    documentroot: "{{ php_xhprof_html_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ php_xhprof_html_dir }}"

  - servername: "pimpmylog.{{ vagrant_hostname }}"
    documentroot: "{{ pimpmylog_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ pimpmylog_install_dir }}"

  - servername: "{{ vagrant_ip }}"
    serveralias: "dashboard.{{ vagrant_hostname }}"
    documentroot: "{{ dashboard_install_dir }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ dashboard_install_dir }}"
          DirectoryIndex index.html

# Acquia Cloud Search defaults to Solr 4.x.

installed_extras:
  - solr
  - drupalconsole
  - xdebug

php_xdebug_default_enable: 1
php_xdebug_idekey: PHPSTORM
------------------------

I have a process called VBoxHeadless that goes to 85% CPU when I run drush cr

We have this same website running on Acquia and it is much faster there.

Thank you for your help.

**Comment by oxyc** [comment]
XDebug being enabled is definitely causing it to be slower.

Try disabling it and running `vagrant provision` again.

```
php_xdebug_default_enable: 0
```

**Comment by hmartens** [comment]
Hi Jeff, thanks for the superfast response :) I disabled the xdebug and and started vagrant again and then ran vagrant provision. At the end I get an error 
-----------
`fatal: [acsf-mysite-vm.dev]: FAILED! => {"failed": true, "msg": "The conditional check ''{{ item }}' not in '{{ solr_cores_current.content }}'' failed. The error was: Invalid conditional detected: EOL while scanning string literal (<unknown>, line 1)\n\nThe error appears to have been in '/Users/myusr/Workspace/dev/mysite/mysite-vm/drupalvm/provisioning/roles/geerlingguy.solr/tasks/cores.yml': line 8, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Ensure Solr conf directories exist.\n  ^ here\n"}`
------------
Should I ignore this as it's just solr that is not on my machine?
Drush cr is much quicker, it's down to 37 seconds ;)

Is there any other way to make it even faster? I'm also runing twig debug. Does this make it slower? 
Then I also found that when I click on any link that drupa hasn't built the cache for it "polls" very long before going to the page. On Chrome the progress circle will turn grey for just over 40seconds and then it will turn blue and go to the page.

**Comment by oxyc** [comment]
You could check `/var/log/mysql/mysql-slow.log` if there were any especially slow database queries

**Comment by geerlingguy** [comment]
And @oxyc is @oxyc, not Jeff ;)

**Comment by hmartens** [comment]
Thanks Oxyc, I appreciate all your help..both you and Jeff ;)

**Comment by oxyc** [comment]
Happy to help. 40s for a page load definitely sounds excessive. You can probably track down what's causing the holdup using [`xhprof`](http://docs.drupalvm.com/en/latest/extras/xhprof/)/[`tideways`](http://docs.drupalvm.com/en/latest/extras/tideways/) or the `mysql-slow.log` I mentioned. Alternatively the `devel` module can help with tracking down slow queries if that's the issue.

If something sticks out, let us know and maybe there's a config option that needs tuning.

**Comment by geerlingguy** [comment]
Closing this issue for now, but please open it back up if you find something that needs further discussion!

**Comment by nishantkumar155** [comment]
agin i am getting slow vagarant drual vm
