### ISSUE TITLE
Adminer CSS

### ISSUE THREAD

**Issue by lionslair** [geerlingguy/drupal-vm#1479]
### Issue Type
 - Feature Idea

### Summary

Would it be possible to either specify a default adminer.css file to be installed either via the config.yml else you pick one and install it. 

I prefer https://raw.githubusercontent.com/vrana/adminer/master/designs/price/adminer.css but they dont have names so you probably need to specify the url. The UI is much better when one is used

**Comment by thom8** [comment]
@lionslair this could be done with a post provisioning script/task -- http://docs.drupalvm.com/en/latest/extending/scripts/

**Comment by geerlingguy** [comment]
@lionslair - as @thom8 said, you can switch things around to customize via a post provisioning task. Additionally, if you'd like to see a feature implemented for switching on the fly or something along those lines, the best place would be in the upstream Ansible role repository: https://github.com/geerlingguy/ansible-role-adminer

Thanks!
