### ISSUE TITLE
Compatibility with Ubuntu 17.04

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1480]
I recently had trouble getting some DrupalVM boxes up and running on Ubuntu 17.04, using the latest versions of vagrant (1.9.7) and virtualbox (5.1.24). The first symptom of the problem was that when I ran `vagrant up`, the process would hang at "Mounting NFS shared folders..." and eventually dump this:

> The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!
mount -o vers=3,udp,vers=3 192.168.135.1:/home/me/sites/my_site /var/www/my_site
Stdout from the command:
Stderr from the command:
mount.nfs: Connection timed out

Turns out the problem was twofold:

1. I also noticed that I couldn't even ping the guest machine from the host. This led me to run ifconfig on the host, and I noticed that there were no vboxnet adapters. I found [this obscure AskUbuntu article](https://askubuntu.com/a/915717) indicating that I should install the virtualbox-dkms package in order to fix this. Unfortunately this required downgrading to the version in the package repositories (5.1.22) but at least it let me ping the guest!
2. The provisioning process continued to hang at the same point, but I noticed in the ufw log that it was dropping packets, so I disabled ufw (`sudo ufw disable`). Obviously I'll need to figure out a better way to fix that, but it at least allowed the machine to boot!

**Comment by danepowell** [comment]
Just wanted to post this problem and solution for posterity in case anyone (myself included!) runs into it again in the future...

**Comment by chadyred** [comment]
Just install`virtualbox-dkms` save my day, thanks !

**Comment by yeongsheng-tan** [comment]
@danepowell @chadyred how did you guys install virtualbox-dkms? For debian-jessie, the latest version avail is 4.3.36 from https://debian.pkgs.org/8/debian-contrib-amd64/virtualbox-dkms_4.3.36-dfsg-1+deb8u1_all.deb.html

Were you guys able to install virtualbox-dkms for debian jessie 8 for VirtualBox 5.1.24?

**Comment by yeongsheng-tan** [comment]
@danepowell @chadyred  installing virtualbox-dkms package for Debian Jessie VirtualBox 5.1.24 equivalent package did not solve the issue for me.

There is a known bug in VirtualBox 5.1.24 filed [here](https://www.virtualbox.org/ticket/16911).

Apparently, you need to manually bring up the vboxnet interface used by your guest OS.

Assuming your NIC interface used by your VM brought up by 'vagrant' is vboxnet0, just run the following to make the nfs mount go through w/o issues:
`ip link set vboxnet0 up`

**Comment by chadyred** [comment]
This is why many timeout when I try to access my VM...I see on [doc ubuntu](https://doc.ubuntu-fr.org/virtualbox#installation_principale_de_virtualbox) (on French) the package to install, as said before this is the solution for Ubuntu 17.04 but not for you...

But, the main problem must be a network issue, so many hours lost...

**Comment by ShaunBrady-007** [comment]
when installing virtualbox-dkms it returns
temporary failure resolving 'gb.archive.ubuntu.com 
E: unable to fetch some archives

**Comment by chadyred** [comment]
Maybe a `sources.list`  issue
