### ISSUE TITLE
Windows 10 64bit failed with error message about configure-solr.sh and stderr/stdout etc

### ISSUE THREAD

**Issue by therobyouknow** [geerlingguy/drupal-vm#1481]
### Issue Type

 - Bug Report / Support Request

### Your Environment
We couldn't get all of the info

```
vboxmanage --version`" && ansible --version`
Vagrant 1.9.7
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found
```

### Your OS

 - **Windows** 10 64bit build 1703

Issue not seen when running with Mac OS.

### Full console output

```
TASK [Run configured post-provision shell scripts.] ****************************
failed: [ourbasebuild] (item=../examples/scripts/configure-solr.sh) => {"changed": true, "failed": true, "item": "../examples/scripts/configure-solr.sh", "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1500551984.28-77979650157545/configure-solr.sh
: not found\n", "stdout": "", "stdout_lines": []}
```

### Summary

```
TASK [Run configured post-provision shell scripts.] ****************************
failed: [ourbasebuild] (item=../examples/scripts/configure-solr.sh) => {"changed": true, "failed": true, "item": "../examples/scripts/configure-solr.sh", "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1500551984.28-77979650157545/configure-solr.sh
: not found\n", "stdout": "", "stdout_lines": []}
```
The file configure-solr.sh does exist, we're not sure why there is problem.

We have changed the structure from the original drupal VM, but given that it works on MacOS, we would not think that this is an issue. Our folder structure looks like:

```
lt-15-25:basebuild robdavis$ ls
Vagrantfile	composer.json	docs		drupal		html		sync		tests		vm-config
lt-15-25:basebuild robdavis$ cd vm-config
lt-15-25:vm-config robdavis$ ls
CHANGELOG.md			default.config.yml		examples			tests
Dockerfile			docs				lib
LICENSE				example.docker-compose.yml	mkdocs.yml
README.md			example.drupal.make.yml		provisioning
lt-15-25:vm-config robdavis$ 
```

Our Vagrantfile looks like:

```
lt-15-25:basebuild robdavis$ cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

require_relative 'vm-config/lib/drupalvm/vagrant'

# Absolute paths on the host machine.
host_drupalvm_dir = File.dirname(File.expand_path(__FILE__)) + '/vm-config'
host_project_dir = ENV['DRUPALVM_PROJECT_ROOT'] || host_drupalvm_dir
host_config_dir = ENV['DRUPALVM_CONFIG_DIR'] ? "#{host_project_dir}/#{ENV['DRUPALVM_CONFIG_DIR']}" : host_project_dir

# Absolute paths on the guest machine.
guest_project_dir = '/vagrant'
guest_drupalvm_dir = ENV['DRUPALVM_DIR'] ? "/vagrant/#{ENV['DRUPALVM_DIR']}" : guest_project_dir
guest_config_dir = ENV['DRUPALVM_CONFIG_DIR'] ? "/vagrant/#{ENV['DRUPALVM_CONFIG_DIR']}" : guest_project_dir

drupalvm_env = ENV['DRUPALVM_ENV'] || 'vagrant'

default_config_file = "#{host_drupalvm_dir}/default.config.yml"
unless File.exist?(default_config_file)
  raise_message "Configuration file not found! Expected in #{default_config_file}"
end

vconfig = load_config([
  default_config_file,
  "#{host_config_dir}/config.yml",
  "#{host_config_dir}/local.config.yml",
  "#{host_config_dir}/#{drupalvm_env}.config.yml"
])

provisioner = vconfig['force_ansible_local'] ? :ansible_local : vagrant_provisioner
if provisioner == :ansible
  playbook = "#{host_drupalvm_dir}/provisioning/playbook.yml"
  config_dir = host_config_dir
else
  playbook = "#{guest_drupalvm_dir}/provisioning/playbook.yml"
  config_dir = guest_config_dir
end

# Verify version requirements.
require_ansible_version ">= #{vconfig['drupalvm_ansible_version_min']}"
Vagrant.require_version ">= #{vconfig['drupalvm_vagrant_version_min']}"

Vagrant.configure('2') do |config|
  # Set the name of the VM. See: http://stackoverflow.com/a/17864388/100134
  config.vm.define vconfig['vagrant_machine_name']

  # Networking configuration.
  config.vm.hostname = vconfig['vagrant_hostname']
  config.vm.network :private_network,
    ip: vconfig['vagrant_ip'],
    auto_network: vconfig['vagrant_ip'] == '0.0.0.0' && Vagrant.has_plugin?('vagrant-auto_network')

  unless vconfig['vagrant_public_ip'].empty?
    config.vm.network :public_network,
      ip: vconfig['vagrant_public_ip'] != '0.0.0.0' ? vconfig['vagrant_public_ip'] : nil
  end

  # SSH options.
  config.ssh.insert_key = false
  config.ssh.forward_agent = true

  # Vagrant box.
  config.vm.box = vconfig['vagrant_box']

  # Display an introduction message after `vagrant up` and `vagrant provision`.
  config.vm.post_up_message = vconfig.fetch('vagrant_post_up_message', get_default_post_up_message(vconfig))

  # If a hostsfile manager plugin is installed, add all server names as aliases.
  aliases = get_vhost_aliases(vconfig) - [config.vm.hostname]
  if Vagrant.has_plugin?('vagrant-hostsupdater')
    config.hostsupdater.aliases = aliases
  elsif Vagrant.has_plugin?('vagrant-hostmanager')
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
    config.hostmanager.aliases = aliases
  end

  # Synced folders.
  vconfig['vagrant_synced_folders'].each do |synced_folder|
    options = {
      type: synced_folder.fetch('type', vconfig['vagrant_synced_folder_default_type']),
      rsync__exclude: synced_folder['excluded_paths'],
      rsync__args: ['--verbose', '--archive', '--delete', '-z', '--copy-links', '--chmod=ugo=rwX'],
      id: synced_folder['id'],
      create: synced_folder.fetch('create', false),
      mount_options: synced_folder.fetch('mount_options', [])
    }
    synced_folder.fetch('options_override', {}).each do |key, value|
      options[key.to_sym] = value
    end
    config.vm.synced_folder synced_folder.fetch('local_path'), synced_folder.fetch('destination'), options
  end

  # Allow override of the default synced folder type.
  config.vm.synced_folder host_project_dir, '/vagrant', type: vconfig['vagrant_synced_folder_default_type']

  config.vm.provision provisioner do |ansible|
    ansible.playbook = playbook
    ansible.extra_vars = {
      config_dir: config_dir,
      drupalvm_env: drupalvm_env
    }
    ansible.raw_arguments = ENV['DRUPALVM_ANSIBLE_ARGS']
    ansible.tags = ENV['DRUPALVM_ANSIBLE_TAGS']
  end

  # VMware Fusion.
  config.vm.provider :vmware_fusion do |v, override|
    # HGFS kernel module currently doesn't load correctly for native shares.
    override.vm.synced_folder host_project_dir, '/vagrant', type: 'nfs'

    v.gui = vconfig['vagrant_gui']
    v.vmx['memsize'] = vconfig['vagrant_memory']
    v.vmx['numvcpus'] = vconfig['vagrant_cpus']
  end

  # VirtualBox.
  config.vm.provider :virtualbox do |v|
    v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
    v.name = vconfig['vagrant_hostname']
    v.memory = vconfig['vagrant_memory']
    v.cpus = vconfig['vagrant_cpus']
    v.customize ['modifyvm', :id, '--natdnshostresolver1', 'on']
    v.customize ['modifyvm', :id, '--ioapic', 'on']
    v.gui = vconfig['vagrant_gui']
  end

  # Parallels.
  config.vm.provider :parallels do |p, override|
    override.vm.box = vconfig['vagrant_box']
    p.name = vconfig['vagrant_hostname']
    p.memory = vconfig['vagrant_memory']
    p.cpus = vconfig['vagrant_cpus']
    p.update_guest_tools = true
  end

  # Cache packages and dependencies if vagrant-cachier plugin is present.
  if Vagrant.has_plugin?('vagrant-cachier')
    config.cache.scope = :box
    config.cache.auto_detect = false
    config.cache.enable :apt
    # Cache the composer directory.
    config.cache.enable :generic, cache_dir: '/home/vagrant/.composer/cache'
    config.cache.synced_folder_opts = {
      type: vconfig['vagrant_synced_folder_default_type']
    }
  end

  # Allow an untracked Vagrantfile to modify the configurations
  [host_config_dir, host_project_dir].uniq.each do |dir|
    eval File.read "#{dir}/Vagrantfile.local" if File.exist?("#{dir}/Vagrantfile.local")
  end
end

```

At the moment the one thing I can think of is that it might be permissions on Windows - I would need to ensure that permissions are at the sufficient level for the scripts to run completely.

**Comment by oxyc** [comment]
Quick fix, you can use the `{{ playbook_dir }}` variable to reference the `provisioning/` directory in Drupal VM. As it's absolute it makes it easier to work with. So change `post_provision_scripts` to:

```yaml
post_provision_scripts:
  - "{{ playbook_dir }}/../examples/scripts/configure-solr.sh"
```

---

Long answer, it's best not to modify the `Vagrantfile`, a lot of things can break if you're trying to do something unsupported.

- Looking at the Vagrantfile it looks like you've moved Drupal VM into a subdirectory? This is better supported with a [_delegating Vagrantfile_](http://docs.drupalvm.com/en/latest/deployment/composer-dependency/#drupal-vm-in-a-subdirectory-without-composer).
- Are you modifying `default.config.yml` directly to make changes? It's preferred to use [`config.yml`](http://docs.drupalvm.com/en/latest/getting-started/configure-drupalvm/#2-configyml).
- Looks like you're using Composer. I would actually suggest installing Drupal VM as a [development dependency](http://docs.drupalvm.com/en/latest/deployment/composer-dependency/).

Basically:

1. `composer require --dev geerlingguy/drupal-vm`
2. Empty out `vm-config/` except for your `config.yml` file
3. Create a delegating Vagrantfile in the root of your project

    ```rb
    # The absolute path to the root directory of the project. Both Drupal VM and
    # the config file need to be contained within this path.
    ENV['DRUPALVM_PROJECT_ROOT'] = "#{__dir__}"
    # The relative path from the project root to the config directory where you
    # placed your config.yml file.
    ENV['DRUPALVM_CONFIG_DIR'] = "vm-config"
    # The relative path from the project root to the directory where Drupal VM is located.
    ENV['DRUPALVM_DIR'] = "vendor/geerlingguy/drupal-vm"

    # Load the real Vagrantfile
    load "#{__dir__}/#{ENV['DRUPALVM_DIR']}/Vagrantfile"
    ```
4. Change the post-provision shell script paths from relative URLs to absolute using some ansible variables

   ```yaml
   post_provision_scripts:
     # This will use the example script bundled with Drupal VM
     - "{{ playbook_dir }}/../examples/scripts/configure-solr.sh"
     # If you want to use a modified version, place it in `vm-config/configure-solr.sh`
     - "{{ config_dir }}/configure-solr.sh"
   ```

**Comment by therobyouknow** [comment]
Thank you very much oxyc I will look into your suggestions and feedback.

**Comment by oxyc** [comment]
Happy to help. Let me know if you get it working or if it's something else that's the problem.

**Comment by geerlingguy** [comment]
Since it's been over a week, I'm going to preemptively close this issue. Let us know if you need it to be reopened!

**Comment by nirmal17346** [comment]
Similar to this, I am getting following error on `vagrant provision` on my Windows 10:

`TASK [Run configured post-provision shell scripts.] ****************************
failed: [myprojectglobal] (item=../../../acquia/blt/scripts/drupal-vm/configure-solr.sh) => {"changed": true, "item": "../../../acquia/blt/scripts/drupal-vm/configure-solr.sh", "msg": "non-zero return code", "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1528374029.59-269360856589720/configure-solr.sh: not found\n", "stdout": "", "stdout_lines": []}
failed: [myprojectglobal] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.php) => {"changed": true, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.php", "msg": "non-zero return code", "rc": 127, "stderr": "/usr/bin/env: 'php\\r': No such file or directory\n", "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/vagrant/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
myprojectglobal                : ok=238  changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by arunavak111** [comment]
Similar to this, I am getting following error on `vagrant provision` on my Windows 10:

`TASK [Run configured post-provision shell scripts.] ****************************
failed: [myprojectglobal] (item=../../../acquia/blt/scripts/drupal-vm/configure-solr.sh) => {"changed": true, "item": "../../../acquia/blt/scripts/drupal-vm/configure-solr.sh", "msg": "non-zero return code", "rc": 127, "stderr": "/bin/sh: 1: /home/vagrant/.ansible/tmp/ansible-tmp-1528374029.59-269360856589720/configure-solr.sh: not found\n", "stdout": "", "stdout_lines": []}
failed: [myprojectglobal] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.php) => {"changed": true, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.php", "msg": "non-zero return code", "rc": 127, "stderr": "/usr/bin/env: 'php\\r': No such file or directory\n", "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/vagrant/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
myprojectglobal                : ok=238  changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by geerlingguy** [comment]
@arun9989 - It looks like you may be using an Acquia BLT project. I would suggest filing an issue in the Acquia BLT project on GitHub for that failure, because that script is not part of Drupal VM.
