### ISSUE TITLE
Windows 7 'vagrant up' does nothing.

### ISSUE THREAD

**Issue by sanjokgrg** [geerlingguy/drupal-vm#1483]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
vagrant --version && vboxmanage --version
Vagrant 1.9.7
'vboxmanage' is not recognized as an internal  or external command
```

### Your OS

 - **Windows** ( 7 ) 64 bit

### Full console output

Command ran 
vagrant up
- No console output 

### Summary

![vagrant](https://user-images.githubusercontent.com/30326939/28439509-2536d7fe-6d9a-11e7-9e51-d9e551966d59.PNG)
vagrant up does nothing . 
I installed Virtualbox, vagrant just like on the quick guides. I extracted the drupal vm to Desktop and changed the default.config.yml to config.yml. 
I tried uninstalling and installing Virtualbox and Vagrant but still after typing vagrant up on cmd or gitbash, it does not throw any error. I am not sure if it is running on the background but, it is just stuck  with blinking cursor.

**Comment by oxyc** [comment]
Seems to be an upstream issue https://github.com/mitchellh/vagrant/issues/8783. Try with downgrading to Vagrant 1.9.6

**Comment by geerlingguy** [comment]
Yeah, definitely a Vagrant bug. For now, install Vagrant 1.9.6 and don't upgrade until the linked issue is fixed.

**Comment by oxyc** [comment]
> Upgrading powershell should resolve the issue. The latest release (1.9.8) includes this PR #8839 that checks the powershell version and raises an error if the minimum is not satisfied. Cheers!

You can find instructions on how to update PowerShell at https://github.com/hashicorp/vagrant/issues/8783#issuecomment-328858234.

I'll close this issue
