### ISSUE TITLE
Add mod_headers to the default apache modes

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#1487]
### Issue Type
 - Feature Idea

### Summary
While debugging some htaccess rules locally I was surprised to noticed that mod_headers wasn't part of the default for drupal VM. Not having this prevented me from debugging till I added it.  Any reason this shouldn't be added?

apache_mods_enabled:
  - expires.load
  - ssl.load
  - rewrite.load
  - proxy.load
  - proxy_fcgi.load
  **- headers.load**

**Comment by oxyc** [comment]
I've been hit by this a few times as well, was always a bit time consuming to debug.

**Comment by geerlingguy** [comment]
Sounds good to me—it's useful enough that I don't worry about the (very) tiny bit of extra overhead it would bring.

**Comment by oxyc** [comment]
I imagine https://github.com/drupal/drupal/blob/8.4.x/.htaccess#L157:L180 already outweighs the overhead.
