### ISSUE TITLE
migrate drupal-project to drupalvm docker support request

### ISSUE THREAD

**Issue by tenken** [geerlingguy/drupal-vm#1488]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Docker
```

### Your OS

 - **Linux** 16.04

### Full console output

n/a

### Summary

I created a D8 project a while ago using [`drupal-project`](https://github.com/drupal-composer/drupal-project). The `/vendor/` directory attempts to autoload outside of the webroot.

If I start up drupalvm and mount a volume as apart of the container configuration:
`   - /some/path/on/server/as/persistant/data/folder:/var/www/drupalvm/drupal/web/:rw,delegated`

Drupal will attempt to load, but tries to load `../vendor` in `autoload.php`.

What's the easiest way to get drupalvm to load up a previously made drupal-project based website? Perhaps, attempt to supply a 2nd volume for `../vendor` and have it be mounted to `/var/www/drupalvm/drupal/` ?

Thanks for your time and any feedback you can provide.

**Comment by geerlingguy** [comment]
Another option would be to share the parent folder into the parent 'drupal' folder on the VM, e.g.:

```
- /some/path/on/server/as/persistant/data:/var/www/drupalvm/drupal:rw,delegated
```

That's how I'm doing a few of my similarly-structured projects and it seems to work fine.

**Comment by tenken** [comment]
Hi Jeff thanks for the prompt reply. So I have added the following to my docker exec and restarted the container:
~~~json
        "Mounts": [
            {
                "Source": "/volume1/drupalvm/dbookmarks/project",
                "Destination": "/var/www/drupalvm/drupal",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            },
            {
                "Source": "/volume1/drupalvm/dbookmarks/project/web",
                "Destination": "/var/www/drupalvm/drupal/web",
                "Mode": "rw",
                "RW": true,
                "Propagation": "rprivate"
            }
        ],
~~~

Hmm, when I visit the site web address I appear to be getting the following error:
~~~txt
Warning: require(/var/www/drupalvm/drupal/web/vendor/composer/../drupal/console-core/src/constants.php):
failed to open stream: No such file or directory in /var/www/drupalvm/drupal/web/vendor/composer/autoload_real.php on line 66

Fatal error: require(): Failed opening required '/var/www/drupalvm/drupal/web/vendor/composer/../drupal/console-core/src/constants.php'
(include_path='.:/usr/share/php') in /var/www/drupalvm/drupal/web/vendor/composer/autoload_real.php on line 66
~~~

The file exists in the correct directory and I made both mounted volumes owned by `vagrant:www-data` I believe applying the usual file permissions to the drupal docroot and sites/files directories from D.org.

For a lark I even 777'd the /vendor directory in /drupal but that didnt appear to help ...

**Comment by tenken** [comment]
As a follow-up, I have this mostly working (or working enough for now) ...

I had to run `composer install` from `/drupal` when logged into the drupalvm and this seemed to resolve the permission issue described above.

I also was unable to use drush via the documented `docker exec drupalvm bash -c "drush ..."` as seen in the documentation, I still got permissions issues detailed above. But, I was able to use drush after logging into the VM and calling drush from within the VM:

~~~sh
docker exec -it drupalvm-bookmarks /bin/bash
# from within container.
php /path/to/drupalvm/drupal/vendor/drush/drush.php \
    --uri=my.uri.here \
    --root=/path/to/drupalvm/drupal/web \
    user-password admin --password=foobarbaz
~~~

Thanks for your time and the great drupalvm and hopefully this thread helps others abit.
