### ISSUE TITLE
Soup to Nuts deployment strategy

### ISSUE THREAD

**Issue by thomasdebruin** [geerlingguy/drupal-vm#1493]
### Issue Type
 - Support Request

### Your Environment
```
Vagrant 1.9.0
VirtualBox 5.1.10r112026
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - Sierra 10.12.6

### Summary
For drupal 7 I user drupal-vm icm deploybot, git with dev/stage/production branches.
Just getting started with drupal 8, so excuse me for the newbie-level of my question: still not sure on the right approach when it comes to deployment. Some questions/assumptions:
1). Using composer and not checking in vendor, modules etc. in git seems a good practise.
2). Using composer in production for updates or intstall to build the codebase is not a good practise (and will run in memory errors).

If i'm right on both assumptions, then i don't see how to deploy with deploybot, it might be better to use the drupal-vm way: https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod

In my case the server is not a VM but clusterhosting with ssh access (but no root access, so config like apache_vhosts probably wont't work). I want to create 2 instances in a single account (production & testing), I also create 2 databases & separate users (probably by hand).
So the next question: in this scenario can I still use (a customised version of)  the drupal-vm deployment soup & nuts?
To localy build the full codebase (vendor/module stuff) and deploy this over ssh, run drupal update hooks etc. If yes, then i need a way to connect the different git branches & separate database-info to the different remote environments.

Just want to check if I'm on the right path, more info/thoughts/pointers are welcome!

**Comment by geerlingguy** [comment]
> In this scenario can I still use (a customised version of) the drupal-vm deployment soup & nuts?

You wouldn't be able to do a lot of the things required to use Drupal VM in this environment (`no root access, so config like apache_vhosts probably won't work`).

Also, if you're trying to control multiple databases and have multiple sites running on this cluster hosting solution, then Drupal VM's setup might not be as helpful for you. It sounds like the hosting you're working with may be more geared to a 'hands off' kind of setup, if you don't manage the server configuration yourself.

Drupal VM may still be a helpful tool for running sites locally for development, but the 'Soup to Nuts' approach is geared toward someone who is running one website and has full control over a cloud server (or some other type of live Internet-facing server).

I'm closing this issue as I don't know if there's much more productive info I can provide, but if you have more questions about the way Drupal VM works with local / prod development that's not covered in that blog post, please ask.
