### ISSUE TITLE
How to make DrupalVM get composer project from external git repo?

### ISSUE THREAD

**Issue by Graloth** [geerlingguy/drupal-vm#1494]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found
```

### Your OS

 - **Windows** (10, build 15063.483, version 1703)

### Summary

I want drupalvm to install drupal from a custom composer file, hosted on a git repository only accessible on the internal network.
I have tried searching on the topic, but haven't been able to find a solution that works.

  - What do I need to set my composer settings to, in my `local.config.yml`, in order for it to get the custom composer project from an external git repository?

The reason I would like to have this configured like this, is that we have a custom composer project that contains all our own tools and theme basics, We maintain the project on an internal git server, and for that reason we want it to pull the latest version when creating a new drupalvm project using our custom drupalvm config.

Any help or suggestions is greatly appreciated, if I need to supply additional information please let me know.

**Comment by oxyc** [comment]
If you have the repo set up as a `composer project` you can use the `--repository-url` flag according to this [stackoverflow answer](https://stackoverflow.com/a/19325683/319855).

```
drupal_composer_project_package: "private/drupal"
drupal_composer_project_options: "--prefer-dist --no-interaction --repository-url=http://repo.yourcomposerrepo.com"
```

**Comment by Graloth** [comment]
@oxyc thanks for the quick answer. Would that clone the contents of the entire repo? Because our composer setup also runs several scripts, which it would need to have access to in order to run.

**Comment by oxyc** [comment]
Basically it clones the repo and runs `composer install` so any install scripts would run.

**Comment by Graloth** [comment]
Awesome, thanks!

Can confirm it working 👍
