### ISSUE TITLE
Connection with xDebug and IDE (netbeans) not working anymore

### ISSUE THREAD

**Issue by lramarojaona** [geerlingguy/drupal-vm#1501]
### Issue Type

 - Bug Report / Support Request

### Your Environment

_The full command "vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version" is not working from my Windows Powershell, so I gathered the infomration myself._
```
Vagrant 1.9.2
Virtualbox 5.0.34r113845
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### Your OS

 - **Windows** (10)

### Summary

I'm pretty sure xdebug was working with Netbeans some time ago. Recently I had to debug a module and when I click debug on Netbeans, it launches the site in my browser (Firefox) but netbeans is stucked (Waiting for connection).
I tried both PHP 5.6 and 7.0.

Here's my xdebug config in config.yml:

> php_xdebug_default_enable: 1
> php_xdebug_coverage_enable: 0
> php_xdebug_cli_enable: 1
> php_xdebug_remote_enable: 1
> php_xdebug_remote_connect_back: 1
> php_xdebug_idekey: netbeans-xdebug
> php_xdebug_max_nesting_level: 256

Could someone help with this?
This would be greatly appreciated! :)

**Comment by lramarojaona** [comment]
Does anyone has the same problem or know to resolve this?

Thanks!

**Comment by geerlingguy** [comment]
@lramarojaona - It looks like you're running `Virtualbox 5.0.34r113845`; the current version (that works a lot better with networking) is 5.1.26 I think. Can you try upgrading VirtualBox (first do a `vagrant destroy` to remove the existing box), and see if that helps?

**Comment by lramarojaona** [comment]
Hi @geerlingguy,

Thanks for help.

I updated to Virtualbox 5.1.28 but unfortunately it ididn't help, Netbans is still "Waiting for connection".
Do you have any idea?

Thanks!

**Comment by lramarojaona** [comment]
Still struggling with this issue.

Here's what I have now:

```
Vagrant 1.9.2
Virtualbox 5.1.28
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

I just started a new VM with the latest version of DrupalVM (4.6.0).

Here's my config: https://gist.github.com/lramarojaona/0f81ad51d8658525c3a01723b4af167d
( 20-xdebug.ini, config.yml and part of the phpinfo output)

**Comment by lramarojaona** [comment]
Back with more information.

I've installed and run following script: https://blogs.oracle.com/netbeansphp/howto-check-xdebug-installation
with following result:
> vagrant@dev2:/var/www/drupalvm/projects/drupal/web$ php xdebug.php
PHP Warning:  socket_bind(): unable to bind address [98]: Address already in use in /var/www/drupalvm/projects/drupal/web/xdebug.php on line 5
PHP Stack trace:
PHP   1. {main}() /var/www/drupalvm/projects/drupal/web/xdebug.php:0
PHP   2. socket_bind() /var/www/drupalvm/projects/drupal/web/xdebug.php:5

> Warning: socket_bind(): unable to bind address [98]: Address already in use in /var/www/drupalvm/projects/drupal/web/xdebug.php on line 5

> Call Stack:
    0.0003     350376   1. {main}() /var/www/drupalvm/projects/drupal/web/xdebug.php:0
    0.0007     350432   2. socket_bind() /var/www/drupalvm/projects/drupal/web/xdebug.php:5

Then I did the following:
> 	vagrant@dev2:/var/www/drupalvm/projects/drupal/web$ netstat -an | grep 9000
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN

Also, I had Cisco AnyConnect VPN software installed which may cause trouble as stated here: https://stackoverflow.com/questions/3955226/debugging-ides-port-connection-to-xdebug-waiting-to-connect
I just uninstalled it, but it didn't solve the problem.

I'm losing hope...

**Comment by oxyc** [comment]
Did the script you mentioned run successfully after you opened up the port?

**Comment by oxyc** [comment]
Worth trying:

```
php_xdebug_remote_host: localhost
```

Also, I think you should run that test script from your host machine, and not from within the VM.

**Comment by lramarojaona** [comment]
I found the issue.

I had Cisco AnyConnect and Pulse Secure running in the background.
Just closing them solved the issue.

Thank you all for the help!
