### ISSUE TITLE
config.ssh.forward_agent ignored during provisioning

### ISSUE THREAD

**Issue by Graloth** [geerlingguy/drupal-vm#1503]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found
```

### Your OS

 - **Windows** (10, build 15063.483, version 1703)

### Full console output

```
TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
fatal: [dds]: FAILED! => {"changed": false, "cmd": "/usr/bin/git clone --origin origin 'ssh:********@-removed_for_privacy-' /var/www/drupalvm/drupal", "failed": true, "msg": "Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.", "rc": 128, "stderr": "Permission denied (publickey).\r\nfatal: Could not read from remote repository.\n\nPlease make sure you have the correct access rights\nand the repository exists.\n", "stderr_lines": ["Permission denied (publickey).", "fatal: Could not read from remote repository.", "", "Please make sure you have the correct access rights", "and the repository exists."], "stdout": "Cloning into '/var/www/drupalvm/drupal'...\n", "stdout_lines": ["Cloning into '/var/www/drupalvm/drupal'..."]}
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
dds                        : ok=228  changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary

We use an internal git server to manage all our custom client modules for drupal, and because of that, we use drupal-vm's functionality to deploy from a git repo. This however does not work, as the insecure key vagrant uses is not allowed access on our git server, and even though `config.ssh.forward_agent` is enabled, as well as `config.ssh.private_key_path` being set.

How to I make drupal-vm's guest OS use specific private and public keys?

Currently my `Vagrantfile.local` looks like this:
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

config.ssh.forward_agent    = true
config.ssh.insert_key       = false
config.ssh.private_key_path =  ["~/.vagrant.d/insecure_private_key","~/.ssh/id_rsa"]

config.vm.provision "file", source: "~/.ssh/id_rsa", destination: "/home/vagrant/.ssh/id_rsa"
  config.vm.provision "shell",
      inline: "chmod 600 /home/vagrant/.ssh/id_rsa"
      
config.vm.provision :shell, privileged: false do |s|
  ssh_pub_key = File.readlines("#{Dir.home}/.ssh/id_rsa.pub").first.strip
  s.inline = <<-SHELL
     echo #{ssh_pub_key} >> /home/$USER/.ssh/authorized_keys
  SHELL
end
```

But it does not look like any files are copied or any changes are made, so I'm unsure if what I am doing in `Vagrantfile.local` is correctly configured.

**Comment by Graloth** [comment]
I solved the problem, by finding a terminal/console that supported agent forwarding, which then made `vagrant up` run without any issue.

It might be worth documenting a way to copy the keys over, in the scenario where a person simply isn't able to allow agent forwarding, yet still need the keys for deployment to work.

**Comment by oxyc** [comment]
Which terminal didn't work and which one did? Might be worth mentioning too.

**Comment by Graloth** [comment]
Windows Powershell didn't work, neither did Command Prompt, but I've read a lot of places where people have those working, so that is likely to do with my configuration.
Git Bash worked as long as I had PuTTY's Pageant client running in the background with my private key added.
PuTTY itself also works, but only to connect to the vm after it's been set up, haven't found a way to run it as a native terminal to run vagrant commands off of.

**Comment by fubarhouse** [comment]
@Graloth you may also want to consider the official linux subsystem for windows.
* https://www.vagrantup.com/docs/other/wsl.html

Optional, but if I were to be pushed back to windows I wouldn't be happy with any other command line application. It's nice to know WSL is supported by Vagrant 👍

**Comment by Graloth** [comment]
@fubarhouse WSL has been nothing but headaches for us, as it turns out that what you have access to on WSL is VERY dependant on how updated your system is, and if you're part of the Windows Inside program.

On a case-by-case basis it is faster for us to use the traditional windows+virtualbox, than try to fix the errors that happen when trying to use WSL on different windows machines.

WSL is very promising, but at it's current state it is too unreliable for our requirements.

**Comment by geerlingguy** [comment]
@Graloth - I covered this a bit in depth in my post [Drupal VM on Windows - a fast container for BLT project development](https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development). Basically, use Cmder (or at a minimum Git Bash or Cygwin... though those two emulators aren't nearly as nice to work with as Cmder IMO), and use Pageant to keep your keys loaded.

WSL still has some caveats and requires a bit of twiddling to get it to work with Vagrant under Windows properly (even though WSL is finally 'not beta' :)).

**Comment by vagu71** [comment]
In a similar situation, unable to have this working even after adding the key to pageant, and have it running while trying to ssh in using CMDER.
