### ISSUE TITLE
Add an option to allow for console output during composer install, to be displayed.

### ISSUE THREAD

**Issue by Graloth** [geerlingguy/drupal-vm#1504]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 1.9.5
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found
```

### Your OS

 - **Windows** (10, build 15063.483, version 1703)

### Full console output

```
TASK [geerlingguy.drupal : Define drupal_site_exists.] *************************
ok: [nytsite]

TASK [geerlingguy.drupal : Ensure drupal_deploy_dir directory exists.] *********
changed: [nytsite]

TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
changed: [nytsite]

TASK [geerlingguy.drupal : Check if a composer.json file is present.] **********
ok: [nytsite]

TASK [geerlingguy.drupal : Run composer install if composer.json is present.] ***
changed: [nytsite]

TASK [geerlingguy.drupal : Define drupal_deploy_updated] ***********************
ok: [nytsite]
```

### Summary

Currently, if you use the deploy via git functionality of drupal-vm, it will automatically run `composer install` if it detects a `composer.json`-file, it does not output the console output of composer.

It is possible to enable verbose output in ansible, but that does it for everything, not just the `composer install` output.

My reason for wanting this is that our `composer install` takes a long time, and to avoid any new developer force-quitting the process, having it output the composer console output, would at least let them know that something *is* happening.

**Comment by oxyc** [comment]
At least I'm not aware of any way to do this but we could at least clarify that it can take a very long time in the task name.

**Comment by oxyc** [comment]
At least I'm not aware of any way to do this but we could at least clarify that it can take a very long time in the task name.

**Comment by fubarhouse** [comment]
It would be possible to send the output of the commands to a log file inside of the vagrant folder.

But yeah piping output asynchronously isn't really an option unless you make the ansible run verbose.

I typically run the builds through Jenkins - but I can appreciate the need for this.

**Comment by geerlingguy** [comment]
I've added `(this may take a while)` to the potentially-long-running tasks as per @oxyc's suggestion.

And while we could consider writing a custom execution plugin for Ansible that _does_ provide streaming output... that's not something I'd like to maintain :)
