### ISSUE TITLE
drush site-install options and arguments support?

### ISSUE THREAD

**Issue by Graloth** [geerlingguy/drupal-vm#1506]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 1.9.5
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found
```

### Your OS

 - **Windows** (10, build 15063.483, version 1703)

### Full console output

none

### Summary

I am working on getting drupal-vm to automatically install the drupal site using a custom installation profile.  

I have been unable to find information on the following questions:

- Are all the `drush site-install` options supported? for example, can I add `drupal_account_mail: example@domain.com` in the same way that the config already has `drupal_account_name` and `drupal_account_pass`, which seems to use the same naming conventions as the `drush site-install` options. (reference: https://drushcommands.com/drush-8x/core/site-install/)
- If I have to pass options in the `drupal_site_install_extra_args`, should they include their starting dashes? For example, should I write it as ` - --account-mail: example@domain.com` or just ` - account-mail: example@domain.com`.
- The `drupal_site_install_extra_args` seems to indicate it's only for arguments (as in, those specific to the installation profile, not the install options), if this is true, how do I specify install options as per the drush documentation? (reference: https://drushcommands.com/drush-8x/core/site-install/) 

I am currently testing this myself, but my laptop is quite slow, and I think that others could benefit from the answers. I will post my findings unless someone who already knows the answers beat me to it :)

**Comment by geerlingguy** [comment]
I've updated the documentation in the `geerlingguy.drupal` role: https://github.com/geerlingguy/ansible-role-drupal#drupal-site-installation-options

Basically, you can add any drush command arguments inside `drupal_site_install_extra_args`, e.g.:

```yaml
drupal_site_install_extra_args:
  - '--account-mail: example@domain.com'
```
