### ISSUE TITLE
IP address in dashboard not IP address of Drupal VM Docker container

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#1509]
### Issue Type

 - Bug Report / Support Request
 
### Your Environment

```
Docker version 17.06.0-ce, build 02c1d87 (Docker for Mac)
```

### Your OS

 - **macOS** (Sierra)

### Dashboard output

```
192.168.88.88 drupalvm.dev
192.168.88.88 www.drupalvm.dev
192.168.88.88 adminer.drupalvm.dev
192.168.88.88 xhprof.drupalvm.dev
192.168.88.88 pimpmylog.drupalvm.dev
192.168.88.88 dashboard.drupalvm.dev
```

### Summary

BUT ... `/etc/hosts` has 

```
192.168.89.89  dashboard.drupalvm.dev
192.168.89.89  adminer.drupalvm.dev
192.168.89.89  pimpmylog.drupalvm.dev
192.168.89.89  drupalvm.dev
```

and `http://192.168.89.89` takes us to  `drupalvm.dev`

**Comment by geerlingguy** [comment]
Yeah, the Dashboard is I think using the vagrant IP, so we need to figure out a better way to get it in the Dashboard, and/or just document the Docker instructions a little better.

**Comment by oxyc** [comment]
Now that the dashboard has PHP enabled, we could just use `echo $_SERVER['SERVER_ADDR']'`

**Comment by Gonzalo2683** [comment]
Hello,
Is it possible to access the dashboard of drupal-vm with the docker version?

**Comment by geerlingguy** [comment]
@Gonzalo2683 - Note that you would need to add `drupalvm.test` to your hosts file manually; see: http://docs.drupalvm.com/en/latest/other/docker/#managing-your-hosts-file
