### ISSUE TITLE
Issue after running 'vagrant provision' in Windows 10 machine

### ISSUE THREAD

**Issue by JuanGongora** [geerlingguy/drupal-vm#1510]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
cmd: 'vboxmanage' is not recognized as an internal or external command,
operable program or batch file.
cmd: 'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (10, build 15063.540, version 1703)

### Full console output

https://gist.github.com/JuanGongora/3b3cba59212adf844ffdc6567f571705

### Summary

I am new to Drupal VM, so I was following the instructions from [this blog post](https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development#install) that was showing how to work with a Windows machine. 

I got stuck after running `vagrant up` and then as the post described, followed up with `vagrant provision` to see if the error would be resolved. Unfortunately the error remained, which was saying that a PHP version higher than 5.6.31 is required for various installations. However the `config.yml` file inside the `drupal-vm` folder states in the blog to use `php_version: "5.6"`.  So I'm not sure what to do.

I currently have this version of PHP installed in my machine:

```λ php -v
PHP 7.1.6 (cli) (built: Jun  8 2017 01:52:52) ( NTS MSVC14 (Visual C++ 2015) x64 )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
```
Do I have to add some sort of additional dependency that will switch it to my current version from within vargrant at a certain point, or some other file in the `drupal-vm` folder?

Thanks for your time,

Juan

**Comment by oxyc** [comment]
> Problem 1 - Installation request for doctrine/cache v1.7.0 -> satisfiable by doctrine/cache[v1.7.0]. - doctrine/cache v1.7.0 requires php ~7.1 -> your PHP version (5.6.31) does not satisfy that requirement.

Seems PHP 7.1 is required so you'll need to set `php_version: "7.1"`

**Comment by JuanGongora** [comment]
Thanks oxyc!
