### ISSUE TITLE
Ansible error when running 'vagrant up' for the first time

### ISSUE THREAD

**Issue by MrPaulDriver** [geerlingguy/drupal-vm#1511]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
VirtualBox 5.1.26r117224
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

### Your OS

 - **Linux** (Mint KDE)

### Full console output

https://gist.github.com/MrPaulDriver/e36c537e936d7e76cc65632c14657a4d

### Summary

New to Linux and using Drupal VM for the first. After running 'vagrant up' I am getting an Ansible error

'Ansible failed to complete successfully'

Same outcome after running vagrant provision

A hint was provided - "to retry, use: --limit @/home/paul/Sites/drupalvm/provisioning/playbook.retry" and I assumed this should be appended to either vagrant up or vagrant up provision but this was invalid.

**Comment by stero** [comment]
Same issue here:
Vagrant 1.8.5
VirtualBox 5.1.26r117224
MacOS

**Comment by oxyc** [comment]
The error is:

> Project directory /var/www/drupalvm/drupal/ is not empty

You'll need to delete the generated `drupal/` directory on your host machine and then try again.

**Comment by geerlingguy** [comment]
Yep, I'm 99% sure it's the issue @oxyc pointed out above. Closing this issue, but please reopen if that was _not_ the case.
