### ISSUE TITLE
Wrong Ansible version being installed.

### ISSUE THREAD

**Issue by SirJohn96** [geerlingguy/drupal-vm#1514]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
VirtualBox 5.1.22r115126
```

### Your OS

 - **Windows** 10

### Full console output

```$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Importing base box 'geerlingguy/debian8'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/debian8' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.dev  # VAGRANT: bd020f5ccbc295a87a280c01e5ebcc54 (drupalvm) / c6125de9-b9d4-495c-91ac-01e67e516c9b
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  192.168.88.88 drupalvm.dev www.drupalvm.dev  # VAGRANT: bd020f5ccbc295a87a280c01e5ebcc54 (drupalvm) / c6125de9-b9d4-495c-91ac-01e67e516c9b
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.dev  # VAGRANT: bd020f5ccbc295a87a280c01e5ebcc54 (drupalvm) / c6125de9-b9d4-495c-91ac-01e67e516c9b
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.dev  # VAGRANT: bd020f5ccbc295a87a280c01e5ebcc54 (drupalvm) / c6125de9-b9d4-495c-91ac-01e67e516c9b
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.dev  # VAGRANT: bd020f5ccbc295a87a280c01e5ebcc54 (drupalvm) / c6125de9-b9d4-495c-91ac-01e67e516c9b
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.dev  # VAGRANT: bd020f5ccbc295a87a280c01e5ebcc54 (drupalvm) / c6125de9-b9d4-495c-91ac-01e67e516c9b
==> drupalvm: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => C:/Projects/drupalvm
    drupalvm: /var/www/drupalvm => C:/Projects/drupalvm
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Running ansible-playbook...
ERROR: become is not a legal parameter at this level in an Ansible Playbook
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary

I am having issues provisioning the VM. I am receiving the Ansible issue above and trying different things such as updating DrupalVM, Vagrant, etc. have not solved the issue.
This seems to be a very similar issue to https://github.com/geerlingguy/drupal-vm/issues/566 a year ago. The version that is installed on the guest machine is 1.7.2. Unfortunately, when trying to update it, it stays at the same version.
Has anyone come across this issue with any success or have any suggestions?

**Comment by kopfduenger** [comment]
Jep, same thing here on my local machine on a Mac. 
What I already tried without success:
- After installing the actual version of VirtualBox (5.1.26), the message disappeared that guest additions and virtualbox versions do not match. But I still get the Ansible issue described above.  
- I installed the actual ansible version locally on my mac as recommended by geerlingguy. Same error as before at the point where the script is 'Running ansible playbook...'.

**Comment by kopfduenger** [comment]
I just checked the ansible versions I am running.

The ansible version of my vagrant installation is 1.7.2
```
vagrant@drupalvm:~$ ansible --version
ansible 1.7.2
```
The version I just installed locally is 2.3.2.0:
```
 ansible --version
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```
Thanks for any hint on how to fix this issue...

**Comment by kopfduenger** [comment]
Hey SirJohn96, I think I at least solved the problem with the ansible version:
- I uninstalled vagrant with the uninstall tool provided by the vagrant installer AND wiped any trace of vagrant off my machine: on my mac, I also had to delete the directories `.vagrant.d`, `/opt/vagrant`.
- I ran into an issue with conflicting gems and cleaned them with `$ gem cleanup`. Afterwards, I reinstalled vagrant again. 
- As mentioned in my post above, I also installed ansible locally (because in vagrant only the version 1.7.2 was installed while drupalvm requires at least version 2.2) and set `force_ansible_local` in the config.yml to `false`.
- Additionally, I compared the config.yml of my previous installation with the one of the actual drupalvm-Version - and realized that there have been some changes. Before, I simply copied the old file in the new drupalvm directory... So I modified the new one with the configuration changes of the old and used it.
- Now the original error is gone, but I am stuck with an permission error at the end of the installation process... 
```
TASK [geerlingguy.drush : Install Drush.] **************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /usr/local/bin not writable"}
```
May this be related to the fact that I am using an local ansible version...? Does anyone knows how to fix this? Thank you!

**Comment by SirJohn96** [comment]
Hi kopfduenger, thanks for the responses.

Unfortunately, I do not believe it is possible to install Ansible locally on Windows. I could be wrong though. I am also still faced with the same error when reinstalling Vagrant.

**Comment by SirJohn96** [comment]
To install the most recent version of Ansible inside the VM, I followed the information in this post here: https://konstantinpavlov.net/blog/2016/09/09/installing-ansible-2.1.1-on-debian-8-jessie/. The VM has now provisioned successfully!

**Comment by kopfduenger** [comment]
Hi SirJohn96,
great, thank you for the link! In the meantime I had successfully installed `geerlingguy/ubuntu1604` instead of debian. But as I need the debian box in vagrant in order to have the same environment as on the server, I will try your solution. 
Thank you!

**Comment by oxyc** [comment]
Ping @geerlingguy this might need docs in http://docs.drupalvm.com/en/latest/configurations/base-os/

**Comment by SirJohn96** [comment]
Wow, forgot about that issue. Thank you!

**Comment by geerlingguy** [comment]
@oxyc - Ah, yes. Will create a ticket for it, might have time to knock that out soon. Glad you guys could help each other get it resolved!!
