### ISSUE TITLE
composer docker-bake command not activated following soup to nuts

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#1515]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
VirtualBox 5.1.26r117224
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Feb 25 2017, 15:14:13) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (Sierra)
 
### Full console output

```
[@iMac misfitstheatre.com]$ DRUPALVM_MACHINE_NAME='misfits-comtainer' composer docker-bake
                                                                
  [Symfony\Component\Console\Exception\CommandNotFoundException]  
  Command "docker-bake" is not defined.                           
```

### Summary

Happily following Jeff's wonderful _Local Soup to Prod Nuts_ blog post and wanted to then combine with *Method 3: 'Bake and Share' a custom Drupal VM Docker image* but can't see how the docker-bake command is activated after `composer require --dev geerlingguy/drupal-vm` and concomitant vendor directory structure and `scripts/composer/ScriptHandler.php` or whatever is supposed to create Symfony Console Commands.

**Comment by iainhouston** [comment]
You have to add the _even:script_name_ pairs to the _root_ `composer.json` file thus:

```
...
"scripts": {
        "docker-bake": "vendor/geerlingguy/drupal-vm/provisioning/docker/bake.sh",
        "docker-save-image": "vendor/geerlingguy/drupal-vm/provisioning/docker/save-image.sh",
        "docker-load-image": "vendor/geerlingguy/drupal-vm/provisioning/docker/load-image.sh",
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
...
```

**Comment by iainhouston** [comment]
The idea is to bake a production container to be pushed to a Docker Server service in the hope that this is cheaper to run than renting a virtual server.

To do that we'd need `/var/www/drupalvm/vendor/geerlingguy/drupal-vm/provisioning/playbook.yml` to use the vars from `/var/www/drupalvm/vm/prod.config.yml` rather than `../default.config.yml` ...

**Comment by geerlingguy** [comment]
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!
