### ISSUE TITLE
Drupalvm jenkins provisioning error

### ISSUE THREAD

**Issue by iijiang** [geerlingguy/drupal-vm#1519]
I just got this issue to jenkins role in drupalvm.

TASK [geerlingguy.jenkins : Get the jenkins-cli jarfile from the Jenkins server.] ***
ok: [drupalvm]

TASK [geerlingguy.jenkins : Remove Jenkins security init scripts after first startup.] ***
ok: [drupalvm]

TASK [geerlingguy.jenkins : Get Jenkins admin password from file.] *************
fatal: [drupalvm]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result"}

can anyone help?

**Comment by geerlingguy** [comment]
@iijiang - Jenkins is not supported out of the box as part of a Drupal VM build. If you're seeing issues with the Jenkins build, can you please file an issue in that Ansible role's repository? https://github.com/geerlingguy/ansible-role-jenkins

Also, you can manually edit the task file and comment out the `no_log` setting temporarily in the Jenkins role to see the output in the command line so you can see what error is occurring.

**Comment by iijiang** [comment]
Thanks Jeff. all good.
