### ISSUE TITLE
Error on vagrant up

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#152]
I am getting this error consistently:

```
==> drupalvm: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key=/Users/kevinquillen/.vagrant.d/insecure_private_key --user=vagrant --connection=ssh --limit='drupalvm' --inventory-file=/Users/kevinquillen/Projects/Hosts/drupalvm/.vagrant/provisioners/ansible/inventory --sudo /Users/kevinquillen/Projects/Hosts/drupalvm/provisioning/playbook.yml
ERROR: cannot find role in /Users/kevinquillen/Projects/Hosts/drupalvm/provisioning/roles/geerlingguy.repo-remi or /Users/kevinquillen/Projects/Hosts/drupalvm/provisioning/geerlingguy.repo-remi or /etc/ansible/roles/geerlingguy.repo-remi
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Followed the walkthrough, not sure what went wrong. OSX Mavericks, latest Vagrant and Ansible.

**Comment by geerlingguy** [comment]
@kevinquillen - Can you run `sudo ansible-galaxy install -r provisioning/requirements.txt --force` again? The requirements file has been updated in the past few releases, and that's a new Ansible Galaxy role that's needed.

**Comment by niccolox** [comment]
after forced update I get this error on ubuntu 14.04 and 15.04 hosts

TASK: [geerlingguy.apache | Ensure Apache is installed.] ********************** 
failed: [drupalvm] => (item=apache2,apache2-mpm-prefork,apache2-utils) => {"failed": true, "item": "apache2,apache2-mpm-prefork,apache2-utils"}
stderr: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

stdout: Reading package lists...
Building dependency tree...
Reading state information...
The following extra packages will be installed:
  apache2-bin apache2-data libaprutil1-dbd-sqlite3 libaprutil1-ldap
  liblua5.1-0
Suggested packages:
  www-browser apache2-doc apache2-suexec-pristine apache2-suexec-custom
The following NEW packages will be installed:
  apache2 apache2-bin apache2-data apache2-mpm-prefork apache2-utils
  libaprutil1-dbd-sqlite3 libaprutil1-ldap liblua5.1-0
0 upgraded, 8 newly installed, 0 to remove and 90 not upgraded.
Need to get 1526 kB of archives.
After this operation, 5661 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main liblua5.1-0 amd64 5.1.5-5ubuntu0.1 [99.9 kB]
Get:2 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main libaprutil1-dbd-sqlite3 amd64 1.5.3-2+deb.sury.org~trusty+1 [16.2 kB]
Get:3 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main libaprutil1-ldap amd64 1.5.3-2+deb.sury.org~trusty+1 [14.3 kB]
Get:4 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-bin amd64 2.4.12-1+deb.sury.org~trusty+5 [949 kB]
Get:5 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-utils amd64 2.4.12-1+deb.sury.org~trusty+5 [137 kB]
Get:6 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-data all 2.4.12-1+deb.sury.org~trusty+5 [162 kB]
Get:7 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2 amd64 2.4.12-1+deb.sury.org~trusty+5 [146 kB]
Get:8 http://ppa.launchpad.net/ondrej/php5/ubuntu/ trusty/main apache2-mpm-prefork amd64 2.4.12-1+deb.sury.org~trusty+5 [1430 B]
Fetched 1526 kB in 5s (266 kB/s)
Selecting previously unselected package liblua5.1-0:amd64.
(Reading database ... 62601 files and directories currently installed.)
Preparing to unpack .../liblua5.1-0_5.1.5-5ubuntu0.1_amd64.deb ...
Unpacking liblua5.1-0:amd64 (5.1.5-5ubuntu0.1) ...
Selecting previously unselected package libaprutil1-dbd-sqlite3:amd64.
Preparing to unpack .../libaprutil1-dbd-sqlite3_1.5.3-2+deb.sury.org~trusty+1_amd64.deb ...
Unpacking libaprutil1-dbd-sqlite3:amd64 (1.5.3-2+deb.sury.org~trusty+1) ...
Selecting previously unselected package libaprutil1-ldap:amd64.
Preparing to unpack .../libaprutil1-ldap_1.5.3-2+deb.sury.org~trusty+1_amd64.deb ...
Unpacking libaprutil1-ldap:amd64 (1.5.3-2+deb.sury.org~trusty+1) ...
Selecting previously unselected package apache2-bin.
Preparing to unpack .../apache2-bin_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2-bin (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2-utils.
Preparing to unpack .../apache2-utils_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2-utils (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2-data.
Preparing to unpack .../apache2-data_2.4.12-1+deb.sury.org~trusty+5_all.deb ...
Unpacking apache2-data (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2.
Preparing to unpack .../apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2 (2.4.12-1+deb.sury.org~trusty+5) ...
Selecting previously unselected package apache2-mpm-prefork.
Preparing to unpack .../apache2-mpm-prefork_2.4.12-1+deb.sury.org~trusty+5_amd64.deb ...
Unpacking apache2-mpm-prefork (2.4.12-1+deb.sury.org~trusty+5) ...
Processing triggers for man-db (2.6.7.1-1ubuntu1) ...
Processing triggers for ureadahead (0.100.0-16) ...

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'apache2' 'apache2-mpm-prefork' 'apache2-utils'' failed: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted
Errors were encountered while processing:
 /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)

**Comment by geerlingguy** [comment]
@niccolox - What Vagrant box are you using for 15.04 (and 14.04, if not the default `geerlingguy/ubuntu1404` box)? That looks like an apt problem, either from another process already locking apt or some other error. Best solution is to usually `vagrant reload` or destroy the box and rebuild it.

**Comment by niccolox** [comment]
vagrant plugin install vagrant-vbguest

that fixed it .. 

https://github.com/mitchellh/vagrant/issues/3341
