### ISSUE TITLE
local.config.yml should be able to override environment.config.yml -- for instance vagrant.config.yml

### ISSUE THREAD

**Issue by yareckon** [geerlingguy/drupal-vm#1520]
### Issue Type
 - Feature Idea
### Summary
I have a team of folks using drupalvm inside vagrant with very different host OS.  We need to share a vagrant.config.yml in our repo to keep our boxes similar.  We also want to allow devs to override settings.  unfortunately, vagrant.config.yml overrides anything we put in local.config.yml because it is read afterwards.  

Our workaround is to move shared vagrant config into config.yml, which we can do because we don't use config.yml to configure a production instance at this time.  Others may not be able to do that if they have conflicting per environment settings that need to be overridable by devs.

The solution would be to load a local.environment.config.yml if it exists to allow futher overriding.  Or if we don't mind sneakily changing behavior on people we could just change the order of loading in the vagrantfile to load local.config.yml last -- this is likely to make bugs of the worst kind though.

**Comment by yareckon** [comment]
just a note, this can't be added to a Vagrantfile.local because Vagrantfile.local is included in too late when things like mounts and plugins are already determined.

**Comment by geerlingguy** [comment]
@yareckon - The way BLT does it is what I think would work best in your case:

 - Team commits a `config.yml` with all the team defaults.
 - Individual developers can add a local-per-developer-environment-specific `local.config.yml` file that is gitignored.

If you also use Drupal VM for prod, then you'd still use `config.yml` for all the shared config, and put into `prod.config.yml` all the prod-specific settings.

I do kind-of agree that in the end, `local.config.yml` should be the overriding top override, so besides adding ansible `--extra-vars` in the command line, it's the ultimate variable definition file... I just want to confirm that the `vagrant.config.yml` file takes precedence over the `local.config.yml` file—is that the case currently?

**Comment by yareckon** [comment]
yes, I believe that's the case currently.
Our workaround was indeed to move all shareable config to the config.yml, including all vagrant config.  we don't use a vagrant.config.yml anymore to allow folks to override stuff on their workstations.

**Comment by geerlingguy** [comment]
Done. Thanks to @oxyc!

**Comment by yareckon** [comment]
Many thanks @oxyc & @geerlingguy !
