### ISSUE TITLE
Update 'Using different base OSes' docs

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1521]
### Issue Type

 - Documentation Report

### Summary

Over in #1514, someone noticed that older base OSes had really old Ansible versions installed if you didn't have Ansible installed locally (which is almost always the case on Windows, and is the case in many other scenarios as well).

So we should update the docs and make the following changes:

  1. Document how to switch from OS ansible install to `pip` for Vagrant (see https://github.com/geerlingguy/drupal-vm/issues/1408#issuecomment-306097981).
  2. Update the list of supported OSes (both on that docs page and in the `default.config.yml` file). We now support Debian 8 and 9 as well, and have dropped official Ubuntu 12.04 support.

@oxyc - What do you think about just defaulting to the pip install so the ansible version that's installed inside the VM is consistent across all builds where Ansible isn't on the host?

**Comment by oxyc** [comment]
I like the idea. Windows users have enough to debug already. This is also what [trellis](https://github.com/roots/trellis/blob/master/Vagrantfile#L99:L101) does.

**Comment by geerlingguy** [comment]
Hmm, just adding `ansible.install_mode = "pip"` to the options seems to _force_ Vagrant to use the `ansible_local` provisioner instead of `ansible`. That's a bit annoying :(

**Comment by geerlingguy** [comment]
Or maybe it's because I had just uninstalled Ansible to do testing :P

**Comment by geerlingguy** [comment]
Still had to add an `if` around it.
