### ISSUE TITLE
Drupal VM php version at odds with drupal-composer/drupal-project dependancy

### ISSUE THREAD

**Issue by MrPaulDriver** [geerlingguy/drupal-vm#1524]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
VirtualBox 5.1.26r117224
ansible 2.3.2.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

```

### Your OS

 - **Linux** (Mint KDE 18.1)

### Full console output
https://gist.github.com/MrPaulDriver/9d198cb7f7e857579053f807d5f8dac7

### Summary

I just got DrupalVM running for the first time, but my first composer based module installation failed becuase of an apparent php version mismatch.

I did wonder whether this was a drupal-composer/drupal-project or composer issue, but given that the php version is down to drupalvm, then I guess this is the place to ask.

What am I doing wrong?

**Comment by MrPaulDriver** [comment]
Possibley related. https://github.com/hechoendrupal/drupal-console/issues/3365

**Comment by oxyc** [comment]
The command fails because it's using the PHP version on your host computer, and not the one on the VM. The VM defaults to 7.1 already. You should either run the command from within the VM or upgrade the PHP on your host machine. I'd recommend the latter :)

**Comment by MrPaulDriver** [comment]
Thank you
