### ISSUE TITLE
How to place two different sites of different versions into one config.yml?

### ISSUE THREAD

**Issue by x-doggy** [geerlingguy/drupal-vm#1525]
### Issue Type

 - Question

### Your Environment

```
Vagrant: Vagrant 1.9.5 
VirtualBox: 5.1.22r115126 
Ansible: ansible 2.3.2.0 config file = /etc/ansible/ansible.cfg configured module search path = Default w/o overrides python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### Your OS

 - **Linux** Ubuntu 16.04

### Summary

Hello, I have one small question.
How to place two different sites into one `config.yml` so that one of them built from composer-project (drupal 8) and the second is from local codebase (drupal 7)?

**Comment by geerlingguy** [comment]
I have many different setups that are similar to this (e.g. a site installed via composer, another just as a git codebase with all the files in it, etc.), and the basic premise is:

  1. If possible, do all the `composer` stuff yourself—turn off Drupal VM's composer-based automation. You get better control over your projects this way.
  2. Add as many site codebases as you need in the `vagrant_synced_folders` listing. E.g. add one item for the Drupal 8 codebase, another for the Drupal 7 codebase.
  3. Add as many virtualhost configurations as you need in the `apache_vhosts`/`nginx_hosts` list.
  4. Add as many databases and database users as you need in the `mysql_databases`/`mysql_users` (or `postgresql_*` if not using MySQL).

I can't get into the weeds, but hopefully that is enough to go on to tweak the appropriate settings to get your two websites running inside one Drupal VM instance. If you make any changes to `config.yml` after `vagrant up`, make sure to run `vagrant provision` again to make those changes appear in the VM (or `vagrant reload --provision` if you change the synced folders list).

**Comment by x-doggy** [comment]
Hello, geerlingguy. Thank you for your advices! It turned out to be useful!
I just create add new synched folder for D7-site, also add apache vhost and mysql user, but D8-site I have built from scratch and left settings as it was. After all, of course, I have done `vagrant reload --provision` and everything reloaded successful!
