### ISSUE TITLE
Unable to start Selenium standalone server on Drupal 8 VM

### ISSUE THREAD

**Issue by sswarupa2017** [geerlingguy/drupal-vm#1529]
Support Request

### Your Environment

```
vagrant@d8:/var/www/xxxx$ ansible --version
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.6 (default, Oct 26 2016, 20:30:19) [GCC 4.8.4]

λ vagrant --version
Vagrant 1.9.5

λ vagrant box list
geerlingguy/ubuntu1404 (virtualbox, 1.2.2)
geerlingguy/ubuntu1604 (virtualbox, 1.1.4)

```

### Your OS
 - Ubuntu Drupal 8 VM

### Full console output
I am unable to copy to https://gist.github.com/ as it is blocked in my company.
I am using PhantomJS to run the tests inside the Drupal VM

```
vagrant@d8:/var/www/xxxxx$ blt tests:behat
blt > setup:behat:
     [copy] example.local.yml omitted, is up to date
blt > test:behat:check:
 [property] Loading /var/www/xxxxx/tests/behat/local.yml
     [echo] Executing Behat tests with configuratoin:
     [echo] drupal_root: /var/www/xxxx/docroot"
     [echo] base_url: http://d8.xxxx.com"
blt > tests:run-server:
     [echo] NOT using `drush runserver' for tests.
blt > tests:behat:
blt > tests:selenium:kill:
     [echo] Killing any selenium processes that are already running.
blt > tests:phantomjs:kill:
     [echo] Killing any PhantomJS processes that are already running.
blt > tests:phantomjs:configure:
blt > tests:phantomjs:launch:
     [echo] Launching PhantomJS GhostDriver.
blt > tests:phantomjs:kill:
     [echo] Killing any PhantomJS processes that are already running.
     [echo] Waiting 10 seconds for PhantomJS (http://127.0.0.1:4444) to become available.
**Possible malformed URL: http://127.0.0.1:4444/wd/hub**
blt > tests:behat:execute:
     [exec] /var/www/xxxxx/tests/behat/features/assets/Accessibility.feature
@smoke @cms-6591
Feature: Modify htaccess for extended path based domain rules
  As a QA Engineer
  I should be able to validate the URI for any path based domain is /xxx/xxxx

  @sprint17 @javascript
  Scenario: Verify URI for path based domains                          # features/websites/xxxx/cms-6591.feature:7
    Given I visit "https://xxx.xxx.xxsitefactory.com" # Drupal\DrupalExtension\Context\MinkContext::assertAtPath()
    Then the url should match "/resource-center/insights"              # Drupal\DrupalExtension\Context\MinkContext::assertUrlRegExp()
      Current page "blank" does not match the regex ""/xxxxx/xxxxx"". (Behat\Mink\Exception\ExpectationException)
    │
    │  This is   selemium2 driver
    │
    └─ @AfterStep # Drupal\FeatureContext::takeScreenshotAfterFailedSteps()


When I am running the command:
blt tests:behat

Then I am seeing an error ->
**Possible malformed URL: http://127.0.0.1:4444/wd/hub**
```

Selenium Standalone server is not starting. When I run Behat tests with @javascript tag then the tests fail

### Summary

Appreciate your help! Pl. let me know how I can fix the issue with Selenium Driver not starting up.
FYI: Due to proxy issues inside my company network I have downloaded phantomJS on my Ubuntu VM.

**Comment by geerlingguy** [comment]
> `**Possible malformed URL: http://127.0.0.1:4444/wd/hub**`

That error is extremely typical, and I'm not sure why Behat likes to whine about it... but it happens on all my BLT projects too. It doesn't indicate any actual failure.

It looks like the tests are actually running perfectly, but the behat test is failing with:

```
Current page "blank" does not match the regex ""/xxxxx/xxxxx"". (Behat\Mink\Exception\ExpectationException)
```

That seems to be an issue with either the site you're testing, or the test case itself (`cms-6591.feature`), not with PhantomJS, Selenium, or Behat. I'll leave this question open in case I'm totally missing the mark here... but it seems like everything's working perfectly based on my experience with BLT. If not, then this should be opened against BLT and not Drupal VM. Note that Drupal VM doesn't have anything to do with the `blt` command line utility that does all this setup work.

**Comment by sswarupa2017** [comment]
Thank you so much for your prompt response. Good to know that the error is not to be concerned about.

I ran the same testcase with @javascript tag and again without the @javascript tag. The 2nd step fails with the @javascript and passes when I do not have the @javas

**Comment by geerlingguy** [comment]
These questions are all more directly related to BLT, and not Drupal VM. The fact that the tests run at all means that all the Drupal VM components seem to be working fine.

The other bits of behat integration and setup (and use of phantomJS, Headless Chrome, etc.) all have to do with how BLT is working with your project, and I know some of the features require BLT to be updated to the latest version.

So I'd rather close this ticket and recommend you ask these questions in the BLT issue queue instead: https://github.com/acquia/blt/issues
