### ISSUE TITLE
Apache error log file not readable by PML

### ISSUE THREAD

**Issue by robdecker** [geerlingguy/drupal-vm#153]
PML is only finding `/var/log/apache2/access.log` during the in-browser config.

Manually entering in `/var/log/apache2/error.log` gives the following error: 
```
Custom files below are not readable, please remove them or verify that they are readable by the webserver user (web server user seems to be www-data):

  • /var/log/apache2/error.log
```

**Comment by geerlingguy** [comment]
Hmm... I'll try to take a look at this soon; do you think it could be something that's answered upstream in PML documentation? To be honest, I rarely use PML myself :)

**Comment by robdecker** [comment]
No, I think it's a permissions issue in drupal-vm. The permissions on the log files are too restrictive. As the `vagrant` user, I cannot even `tail -f /var/log/apache2/error.log` without using `sudo`. I'm not a sysadmin, but can't the permissions be relaxed a bit? The users `vagrant` and `www-data` should be able to read the log files, right?

**Comment by geerlingguy** [comment]
Closing in favor of #197
