### ISSUE TITLE
drupal vm Run Composer installer Failed to decode zlib stream

### ISSUE THREAD

**Issue by harshilm** [geerlingguy/drupal-vm#1531]
I am trying to run vagrant up but its getting failed  while running comnposer 

![image](https://user-images.githubusercontent.com/4558927/29672016-af12e546-891d-11e7-92d9-c0e7983109a3.png)

**Comment by harshilm** [comment]
After installing composer we are facing below issue
![image](https://user-images.githubusercontent.com/4558927/29676483-cbe8b9f4-892a-11e7-86d1-22838480dc2f.png)

**Comment by geerlingguy** [comment]
It sounds like there may be either a networking issue, or a disk I/O issue. When you created this issue, there were a series of questions to help us diagnose your problem better. I am closing this issue—can you please open another new issue and fill out all the information (e.g. what OS, what versions, etc.)?
