### ISSUE TITLE
ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'

### ISSUE THREAD

**Issue by zzedify** [geerlingguy/drupal-vm#1532]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.4
VirtualBox 5.1.26r117224
Ansible ansible 2.3.1.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.9 (default, Jun 29 2016, 13:08:31) [GCC 4.9.2]
```

### Your OS
 - **Windows** (10)

### Full console output
```
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Importing base box 'geerlingguy/debian8'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/debian8' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
[drupalvm] GuestAdditions 5.1.26 running --- OK.
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 cer.drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.cer.drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => C:/Users/vmikolaj/Documents/Projects/VM
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Installing pip... (for Ansible installation)
    drupalvm: Running ansible-playbook...
ERROR! Unexpected Exception: 'module' object has no attribute 'SSL_ST_INIT'
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary
I get this error after upgrading debian8 box [v1.0.4](https://app.vagrantup.com/geerlingguy/boxes/debian8/versions/1.0.4) to [v1.0.5](https://app.vagrantup.com/geerlingguy/boxes/debian8/versions/1.0.5). 
So i'm trying to switch from OS ansible install to pip for Vagrant like described in #1408 comment. Now i'm facing with an SSL_ST_INIT error which comes from pyOpenSSL version. 
Indeed I must force pyOpenSSL version to 16.0.2 by adding 
`config.vm.provisioners[0].config.pip_args = "-r /vagrant/requirements.txt"` in my `Vagrantfile.local` and
`pyOpenSSL==16.2.0` in `requirements.txt`.
I don't know if it's the best solution but it temporarily works.

Has anyone come across this issue have any suggestions?

**Comment by geerlingguy** [comment]
Not sure—though maybe setting `install_mode` to `pip` in the Vagrant configuration  for the ansible_local provisioner could help?

**Comment by geerlingguy** [comment]
Ah, and see related: https://github.com/geerlingguy/drupal-vm/issues/1521 — mentions the pip install method.

**Comment by geerlingguy** [comment]
I just updated the Vagrantfile in the master branch to use `pip` to install Ansible inside the VM, so if you can update your codebase or manually apply this patch (https://github.com/geerlingguy/drupal-vm/commit/3c84e2df4ae4cd7b368c545588f018edfa432891), then do a `vagrant destroy` and then `vagrant up` again, it should start working.

Closing this as I think that should solve your problem. If not, please let me know!

**Comment by vhosakot** [comment]
I saw the `AttributeError: 'module' object has no attribute 'SSL_ST_INIT'` error too and `sudo pip install pyOpenSSL==16.2.0` resolved it for me!
