### ISSUE TITLE
Vagrant up failed, vagrant unable to communicate with guest machine within configured time period

### ISSUE THREAD

**Issue by suesCL** [geerlingguy/drupal-vm#1533]
### Issue Type
can't do "vagrant up"

 - Bug Report / Support Request

### Your Environment
Vagrant 1.9.2
VirtualBox -5.1.22-115126

### Your OS
windows 10  version 1703

### Full console output

https://gist.github.com/suesCL/1ba9713bd23bd76d048d468729937003

### Summary

Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

**Comment by thom8** [comment]
@suesCL It's likely your command line environment doesn't support SSH.

You will need SSH when using vagrant, take a look at this page for more info - http://docs.drupalvm.com/en/latest/getting-started/installation-windows/#command-line-environment

**Comment by suesCL** [comment]
Thanks! I have tried the steps below and used Cmder command line instead of git bash,

Delete ~/.vagrant.d/insecure_private_key
Run vagrant ssh-config
Restart the VM with vagrant reload

It still gives the console output.  Any ideas?

**Comment by thom8** [comment]
You might need to destroy the existing VM and rebuild in Cmder --

```
vagrant destroy
vagrant up
```

**Comment by geerlingguy** [comment]
@suesCL - I'm going to close this issue for now, as I'm hoping @thom8's advice fixed the problem for you. If not, please let us know.

**Comment by suahmed31** [comment]
Getting stuck at the following issue

tamim@LMS:~/fullstack$ vagrant reload
==> default: [vagrant-hostsupdater] Removing hosts
==> default: Attempting graceful shutdown of VM...
    default: Guest communication could not be established! This is usually because
    default: SSH is not running, the authentication information was changed,
    default: or some other networking issue. Vagrant will force halt, if
    default: capable.
==> default: Forcing shutdown of VM...
==> default: Clearing any previously set forwarded ports...
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
    default: Adapter 2: hostonly
==> default: Forwarding ports...
    default: 80 (guest) => 8080 (host) (adapter 1)
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

I have tried using Vagrant destroy and reload, but the issue still persist.

Please provide some help.

**Comment by dziugass** [comment]
suahmed31, Same here, Did you find the solution?

**Comment by suahmed31** [comment]
@dziugass No, till now I didnt have any solution to the above mentioned issue. Waiting for someone to help!!

**Comment by geerlingguy** [comment]
There are many, many reasons that issue can happen—networking issues, VPN issues, proxy issues, etc. Also see: https://github.com/geerlingguy/drupal-vm/issues/1533#issuecomment-325836426 — make sure you're using a command line environment that has SSH available.

**Comment by brandleyzhou** [comment]
U  can   enter the   BIOS , Configuration> Intel Virtual Tech>Enable

**Comment by carlosleonam** [comment]
> ![fghjk](https://user-images.githubusercontent.com/2161604/44835830-be9a2600-ac4e-11e8-838d-e54504b5bc73.png)
> Select your Ubuntu server, click on Settings, go to Network tab and make sure that your Cable Connected option is selected.

On same settings window, I changed network adapter to another with "server" in description, and Vagrant finally run.
![vagrant_ruby](https://user-images.githubusercontent.com/13433793/68602531-43a0e200-0485-11ea-8487-dc9cda9f7fd8.jpg)

**Comment by RistoKaalma** [comment]
Had this issue quite a few times now till I finally noticed a pattern. Every time I am in a place with slow internet speed or bad connection over the WiFi `vagrant up` resulted in timeout.

Today I was once again looking for a solution better than `vagrant destroy` -> `vagrant up` till I just-in-case switched to my phone 4G connection (USB tethering) as it is faster than the current WiFi connection.

Hopefully it helps someone.

**Comment by ronakganatra-multidots** [comment]
vagrant destroy
vagrant up

Worked..!!

Wasted 4 hours in it.

**Comment by mhenden** [comment]
> vagrant destroy
> vagrant up
> 
> Worked..!!
> 
> Wasted 4 hours in it.

Not for me it didn't....

**Comment by geerlingguy** [comment]
@mhenden - If it's a Vagrant-related issue, maybe search through the vagrant issue queue and see if you can find any helpful advice. Otherwise see if the error messages you're seeing have any good search keywords that can help find something. Also consider opening a new issue for what you're seeing.

**Comment by perugan** [comment]
I followed the steps that Carlosleanam had posted here and it worked at the first attempt itself. Thanks to Waheed and Carlosleanam.

**Comment by Soroyesodiq** [comment]
I had the same problem on windows 10 and the solution for me was to enable Intel Virtualization from the BIOS menu. You can visit https://stackoverflow.com/questions/23293071/timed-out-while-waiting-for-the-machine-to-boot-when-vagrant-up for more.

**Comment by caasiremos** [comment]
> vagrant destroy
> vagrant up
> 
> Worked..!!
> 
> Wasted 4 hours in it.

worked like charm

**Comment by khawarsa** [comment]
I have fixed this issue by open Oracle VM VirtualBox Manager go to homestead setting - > network tab - >Adaptor 2 - > promiscuous mode: and select Allow all option
![solution](https://user-images.githubusercontent.com/11063899/108959414-2ef65680-7696-11eb-9829-46269fc96dde.png)

**Comment by renzroque** [comment]
> I have fixed this issue by open Oracle VM VirtualBox Manager go to homestead setting - > network tab - >Adaptor 2 - > promiscuous mode: and select Allow all option
> ![solution](https://user-images.githubusercontent.com/11063899/108959414-2ef65680-7696-11eb-9829-46269fc96dde.png)

works for me! thank you!

**Comment by zareismail** [comment]
> ### Issue Type
> can't do "vagrant up"
> 
> * Bug Report / Support Request
> 
> ### Your Environment
> Vagrant 1.9.2 VirtualBox -5.1.22-115126
> 
> ### Your OS
> windows 10 version 1703
> 
> ### Full console output
> https://gist.github.com/suesCL/1ba9713bd23bd76d048d468729937003
> 
> ### Summary
> Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with the guest machine within the configured ("config.vm.boot_timeout" value) time period.
> 
> If you look above, you should be able to see the error(s) that Vagrant had when attempting to connect to the machine. These errors are usually good hints as to what may be wrong.
> 
> If you're using a custom box, make sure that networking is properly working and you're able to connect to the machine. It is a common problem that networking isn't setup properly in these boxes. Verify that authentication configurations are also setup properly, as well.
> 
> If the box appears to be booting properly, you may want to increase the timeout ("config.vm.boot_timeout") value.

Just run your shell as administrator

**Comment by jithendra-gunuru** [comment]
> 

@suesCL  Thanks! I have tried the steps below and used Cmder command line instead of git bash,

Delete ~/.vagrant.d/insecure_private_key
Run vagrant ssh-config
Restart the VM with vagrant reload


THANKYOU @suesCL 
worked for me, for me it worked in git bash, deleted that file (insecure_private_key) and ran vagrant reload. 

vagrant ssh-config this command shows location of the file

**Comment by mhthaque** [comment]
I've changed the WinRM timeout from 120 seconds to 30 minutes and now the guest completes the boot and machine attempts connect.

config.winrm.timeout =   1800 # 30 minutes
config.vm.boot_timeout = 1800 # 30 minutes

**Comment by Utchaykish** [comment]
vagrant destroy
vagrant up

Worked like crazy... spent less than 5 minutes on it
