### ISSUE TITLE
Select apt mirrors

### ISSUE THREAD

**Issue by tamasd** [geerlingguy/drupal-vm#1534]
### Issue Type

 - Feature Idea

### Summary

I live far from the US, but the Ubuntu virtual machine uses the US mirrors. This makes creating a DrupalVM box very slow. I run the same Ubuntu on my laptop, and the local mirrors are much faster. It would be really nice if either the mirrors would be selected automatically, or if I could specify which mirrors to use in the configuration yaml file.

**Comment by oxyc** [comment]
Related https://github.com/geerlingguy/drupal-vm/issues/738

**Comment by geerlingguy** [comment]
See, specifically: https://github.com/geerlingguy/drupal-vm/issues/738#issuecomment-267384589

@tamasd - What country are you in? And have you in the past noticed an appreciable speedup using other mirrors? I've found what @oxyc said to be very true in many regions (besides some parts of the EU)—regional mirrors can be really buggy and/or out of sync.

**Comment by tamasd** [comment]
@geerlingguy I am from Hungary. I haven't set up mirrors in the past with DrupalVM. As I see (I am new to Ansible, so I might be wrong), it is not something that is easy to change without going into the Ansible configs.

I compared the speed to my host machine, where I could download packages at full speed. Inside the VM, it took 15 mins to download the c++ package update alone. It wasn't this bad before, so I suspect the problem is either with the US mirrors, or some other network issue along the way.

As far as I know, German and Hungarian (the ones I have experience with) Linux mirrors in general are up-to-date. There might be other regional mirrors that are in a worse state. That is why I propose this to be a configuration value, so users could opt-in.

**Comment by oxyc** [comment]
Easiest fix without official support would be to have your own `sources.list` file in the project and add a [pre-provision task](http://docs.drupalvm.com/en/latest/extending/scripts/) that copy it into place.
Add this to your `config.yml`:

```yaml
pre_provision_tasks:
  - "{{ config_dir }}/scripts/set-apt-mirrors.yml"
```

And create a `scripts/set-apt-mirrors.yml` so that the scripts directory is next to your `config.yml`:

```yaml
- name: Copy sources.list into place
  copy:
    src: "{{ config_dir }}/scripts/sources.list"
    dest: "/etc/apt/sources.list"
    mode: 0644
    owner: root
    group: root
```

Now create your custom `scripts/sources.list` file.

**Comment by oxyc** [comment]
I'll close this out as I don't believe @geerlingguy is interested in adding a default option for it and it's quite straightforward to configure it with a preprovision task as I showed above.
