### ISSUE TITLE
Checking out existing project hangs when deploying to prod?

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#1536]
### Issue Type
 - Support Request

### Your Environment
```
Vagrant 1.9.4
VirtualBox 5.1.18r114002
ansible 2.2.2.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** 10.12
 - **Linux** Ubuntu 16.04.3 LTS

### Summary
I'm using the Soup-to-Nuts documentation to deploy to production. I've had success with this with the previous documentation and everything appears fairly straightforward. The only hiccup is that I'm unable to check out an existing project to my web root. The task runner hangs at:

```
TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
```
I can see a .git directory at /var/www/drupal and git remote -v resolves correctly. 

ps aux | grep git shows a few processes running under my admin_user: https://gist.github.com/minorscience/3370eece3fd604f0c8ae2160c35022fe

Are there any additional flags I can make active in order to get a more verbose output for troubleshooting?

**Comment by minorscience** [comment]
I should add that I also changed the following, from:
```
drupal_deploy_repo: "git@github.com:my-account/my-repo.git"
```
to:
```
drupal_deploy_repo: "https://github.com/my-account/my-repo.git"
```

Prior to that change I received the following fatal error:
```
TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
fatal: [34.234.7.54]: FAILED! => {"changed": false, "failed": true, "msg": "github.com has an unknown hostkey. Set accept_hostkey to True or manually add the hostkey prior to running the git module"}
```

**Comment by minorscience** [comment]
You know, I just figured this out. Looks like these docs only work with public repos. Is there an available pattern for working with private repositories?

**Comment by geerlingguy** [comment]
@minorscience - If you need to work with private repos, there are two things you should do:

1. Set `drupal_deploy_accept_hostkey: True` (if it isn't already set that way... I thought it was?)
2. Make sure you've added an SSH key you use with your GitHub account to ssh-agent (e.g. `ssh-add ~/.ssh/id_rsa`).

Then also make sure you tell SSH to use your agent keys with the server's remote connection, e.g. by adding the following inside `~/.ssh/ssh_config`:

```
Host 1.2.3.4 my.drupal.website.com
    ForwardAgent yes
```

**Comment by minorscience** [comment]
Oh duh. I feel dumb now! Sometimes when one is deep in the rabbit hole, one forgets the little things. Thanks, Jeff!

**Comment by minorscience** [comment]
Sorry, I'm not getting anywhere with this. When the playbook reaches the drupal role, I still get: 

```
TASK [geerlingguy.drupal : Check out Drupal to the docroot.] ******************* fatal: [34.234.161.17]: FAILED! => {"changed": false, "cmd": "/usr/bin/git checkout --force master", "failed": true, "msg": "Failed to checkout master", "rc": 1, "stderr": "error: pathspec 'master' did not match any file(s) known to git.\n", "stdout": "", "stdout_lines": []} to retry, use: --limit @/Users/jrl/projects/blah/drupal/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry
```
Relevant prod.config.yml lines:
```
drupal_deploy: true
drupal_deploy_accept_hostkey: True
drupal_deploy_repo: "git@github.com:blah/blah.git"
drupal_deploy_dir: /var/www/drupal
```

ssh-add -l -E md5 shows my local workstation key:
```
4096 MD5:12:34:56:78.... /Users/blah/.ssh/id_rsa (RSA)
```
...which matches the fingerprint on my GitHub account's settings/keys page.

From the remote host, ssh -T git@github.com successfully authenticates and echo "$SSH_AUTH_SOCK" prints out the appropriate variable (shows agent forwarding is working).

I also reviewed the additional documentation on docs.drupalvm.com. This seems like less of a DrupalVM support request than an outright ssh (and/or git) support request. Nevertheless, any insight would be appreciated.
