### ISSUE TITLE
can't write to private files folder 

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1537]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.5
VirtualBox 5.1.26r117224
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

### Your OS

 - **macOS** (el capitan)

### Summary
I created a folder at /var/www/drupalvm/private and added this to my settings.php file.
But for some reason I'm unable to write to this folder from my code.
Has this something to do with the vagrant sync?
And what to do to get this working?

**Comment by oxyc** [comment]
What are the directory permissions on host and guest?

**Comment by betz** [comment]
Ow boy, i noticed i had set the host' directory path to the private folder in settings.php.
Changed it, works like a charm ^^
