### ISSUE TITLE
Destination /usr/local/bin not writable during Drush install on Debian 9

### ISSUE THREAD

**Issue by heigh8** [geerlingguy/drupal-vm#1539]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant: 1.9.1
ansible: 2.2.1.0
vboxmanage : 5.1.26r117224

```

### Your OS

 - **Linux** (debian 9)

### Summary
I get 

TASK [geerlingguy.drush : Install Drush.] **************************************
fatal: [boxname]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /usr/local/bin not writable"}

on vagrant up.
reason is /usr/local/bin does not exist on vm.

**Comment by geerlingguy** [comment]
Strange—the tests passed, at least: https://travis-ci.org/geerlingguy/drupal-vm/builds/269525498

But they're using Docker, and the Docker base image is a little different than the VirtualBox Vagrant base box.

**Comment by geerlingguy** [comment]
I'm testing this now using the following `config.yml`:

```yaml
vagrant_box: geerlingguy/debian9
```

I'll let you know if I can replicate the issue locally.

**Comment by geerlingguy** [comment]
In my environment, the `drush` tasks all completed successfully:

```
TASK [geerlingguy.drush : Check current state.] ********************************
ok: [drupalvm]

TASK [geerlingguy.drush : Perform cleanup of old symlink.] *********************
skipping: [drupalvm]

TASK [geerlingguy.drush : Install Drush.] **************************************
changed: [drupalvm]

TASK [geerlingguy.drush : Ensure Drush is executable.] *************************
changed: [drupalvm]

TASK [geerlingguy.drush : Clone Drush from GitHub.] ****************************
skipping: [drupalvm]

TASK [geerlingguy.drush : Check for composer.json] *****************************
skipping: [drupalvm]

TASK [geerlingguy.drush : Ensure Drush can be installed on Debian Wheezy.] *****
skipping: [drupalvm]

TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
skipping: [drupalvm]

TASK [geerlingguy.drush : Create drush symlink.] *******************************
skipping: [drupalvm]

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
skipping: [drupalvm]
```

Are you using a different base image besides `geerlingguy/debian9`? Any other configuration differences?

**Comment by geerlingguy** [comment]
Ah, just realized—are you _running Debian 9 as your workstation_ and also using debian9 as the base box? Or are you using a different base box? And same question as above still—any other config.yml changes?

**Comment by heigh8** [comment]
debian 9 is the workstation, the base box is debian 8.
and yes - we do have some custom config.yaml, I'll attach it.
[config.yml.txt](https://github.com/geerlingguy/drupal-vm/files/1292327/config.yml.txt)
Thanks!

**Comment by heigh8** [comment]
sorry didn't mean to close..

**Comment by oxyc** [comment]
In the `config.yml` you posted the vagrant hostname is invalid (the `.`), and I saw a few duplicate variables as well.

**Comment by oxyc** [comment]
Looking at your `config.yml` your `vagrant_hostname` is invalid (the `_`), and there's also a few duplicate options.

**Comment by oxyc** [comment]
I can reproduce:

```
TASK [geerlingguy.drush : Install Drush.] **************************************
fatal: [project_name]: FAILED! => {"changed": false, "failed": true, "msg": "Destination /usr/local/bin not writable"}

$ ls -la /usr/local/bin
ls: cannot access /usr/local/bin: No such file or directory
```

**Comment by oxyc** [comment]
@geerlingguy should that be taken care of in the drush role or in Drupal VM?

**Comment by geerlingguy** [comment]
Annoyingly, the default `$PATH` on Debian 8 even includes it:

```
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
```

But it also includes `sbin`, which _does_ exist. So I think I'll make the path an OS default variable and set a default for Debian.

**Comment by geerlingguy** [comment]
Or actually I can just ensure bin exists. That might be simpler.

**Comment by geerlingguy** [comment]
Fixed upstream; will commit the fix in a few minutes.
