### ISSUE TITLE
Make globally-required Composer packages accessible to vagrant user

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#154]
export PATH=/root/.composer/vendor/bin:$PATH

This integrates well with the `composer_global_packages` specification in the config.yml. Then, when users SSH into the machine, they will have access to all of the executables.

**Comment by geerlingguy** [comment]
Does doing that as the `vagrant` user actually include all the bins in that path? It seems we would need to do the following so the composer packages would be accessible to the current user:

  1. Run `composer global require` commands as the `vagrant` user.
  2. Add `~/.composer/vendor/bin` to `vagrant` user's `$PATH`.

Unfortunately, a 'global' install, in composer parlance, is global _only to the user who does the install_. It's not global like PEAR, where the installed packages are available to all users systemwide. That's why for Drush, if you need it installed systemwide, you have to clone Drush to a general location, then run `composer install` just for Drush, then symlink the `drush` binary into a globally accessible bin path.

**Comment by nerdstein** [comment]
Can't we install global packages to somewhere like `/usr/local/bin/composer`?

**Comment by nerdstein** [comment]
And, is there someway we can automate this for the global packages we specify? I hate having manual steps thereafter.

**Comment by geerlingguy** [comment]
> Can't we install global packages to somewhere like /usr/local/bin/composer?

Unfortunately, that's not how Composer works. It's first and foremost a dependency manager, so it's built mainly for installing packages into your particular project (e.g. a specific Drupal site). The `global require` functionality was added on later, and only seems to be supported for _single users_ on a system (not system-wide). So permissions and file locations for the required packages are a mess if you want to try hacking them to work across users.

> And, is there someway we can automate this for the global packages we specify? I hate having manual steps thereafter.

Yes, most likely. But can you give particular use cases—e.g. what exactly would you like to do with the packages (e.g. `behat` or `phpunit`)? The typical pattern is to include the dependencies in your project's `composer.json`, then to set up your project, run `composer install`. Then you can run tests by running something like `./vendor/bin/behat` to run your project's Behat tests.

See, for example, Drupal core's PHPUnit test instructions: https://www.drupal.org/node/2116263

Doing it this way doesn't rely on globally installed packages, and allows for more flexibility in terms of one project having one version of Behat/PHPUnit/etc. and another project having a different version.

**Comment by nerdstein** [comment]
My current use cases are executing `behat` and `phpunit`. These have dependencies, like Drivers, which are also installed by Composer.

I'm open to suggestions on how to get around this in an automated way. As you suggested, maybe the global libraries are added to both root and vagrant users and the paths are added automatically.

**Comment by kevinquillen** [comment]
I usually handle that at the project level, not the server level. I found it easier than dealing with the user/system wide issue mentioned above.

If you use something like PhpStorm, you can install composer libraries on the host machine (again, I do this in the project root), and configure PhpStorm to use the PHP binary on the server as the interpreter, and connect it to Vagrant - with the remote intepreter hooked up, you can point it to run Behat and PhpUnit tests at the library paths which Vagrant believes resides on the server, when it really is just your local machine. This can help from having to ssh into the box and doing composer installs. I haven't really had much issue with this route.

**Comment by geerlingguy** [comment]
Working on a good solution now :)

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-composer/issues/3

**Comment by geerlingguy** [comment]
So... I decided to go [to the moon](http://orig03.deviantart.net/1769/f/2013/356/7/f/if_we_re_going_to_the_moon__our_mission_patch__by_kaelakov-d6yyudb.png), and with the one little variable change in the commit above (and an update to the `geerlingguy.composer` role that's in version 1.2.0—run `ansible-galaxy install -r provisioning/requirements.txt --force` to update), you can now run any of the installed composer packages as the vagrant user.

As an example, want phpunit globally? Add the following to your `config.yml`:

```yaml
composer_global_packages:
  - { name: phpunit/phpunit, release: '@stable' }
```

Then:

```
vagrant@drupalvm:~$ phpunit --version
PHPUnit 4.7.6 by Sebastian Bergmann and contributors.
```

Voila!

**Comment by nerdstein** [comment]
You are the man
