### ISSUE TITLE
VHost configuration for node server?

### ISSUE THREAD

**Issue by Didel** [geerlingguy/drupal-vm#1541]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 1.9.8
VirtualBox 5.1.26r117224
```

### Your OS

 - **macOS** (10.12.6)

### Summary

Hi Jeff! This is more of a question than a bug report or feature request. I'm using DrupalVM currently to get a local Drupal development environment up and running. Some dev-tools require to have another server of some kind running. E.g., I'm trying to use the Patternlab Drupal theme (https://github.com/phase2/pattern-lab-drupal-theme) for this new site. During development, this needs to have a server running (using `npm start`) that watches and compiles code or creates files. When running this command on the DrupalVM, this spans a local server process:
```
[Browsersync] Access URLs:
 -----------------------------------------------------
   Local: http://localhost:3050/pattern-lab/public
External: http://10.0.2.15:3050/pattern-lab/public
```

I have added port 3050 to the list of firewall ports in `config.yml`, but I still can't seem to connect to it from my host machine. I'm almost sure I need to add something to my Apache VHosts-configuration, but I have tried several times but not succeeded yet. What do I need to add to end up with a specific subdomain redirecting to this server (just like e.g. pimpmylog and adminer)? Or is this not possible?

**Comment by geerlingguy** [comment]
@Didel - if the server is running via node.js, then you just need to add a manual entry to your hosts file (`sudo nano /etc/hosts` on your (I presume) Mac in Terminal). You could add it like:

`ip-address-here  patternlab.yoursite.com`

Get the IP address from `dashboard.yoursite.com`

Then access `patternlab.yoursite.com:3050/pattern-lab/public`.

The vhosts file changes would only affect Apache, though you technically _could_ manage a vhost through there (with a valid docroot somewhere)—then you'd have to run `vagrant provision` for changes to take effect.

Have you run `vagrant provision` after changing your fireall rules?

**Comment by Didel** [comment]
d'Oh... I guess I must have been really tired ☕️ 

I managed getting it up and running without even changing the vHost entries (so only adding the ports to the firewall exceptions) and provisioning to the VM. I can now indeed reach pattern lab through `[mysite.dev]:3050/pattern-lab/public/` 👍 

Thanks a lot for your reply!
