### ISSUE TITLE
Ubuntu 12.04 fails to install Apache 2.4

### ISSUE THREAD

**Issue by jonnyeom** [geerlingguy/drupal-vm#1544]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.26r117224

```

### Your OS

 - **Linux** Ubuntu 16.04

### Full console output

https://gist.github.com/jonnyeom/d2871eb18e34105f3a6acce49a284111

### Summary

It seems like apache 2.2 is being used and therefore, this task is failing, similar to #589.

The Task for adding [the ondrej repo](https://launchpad.net/~ondrej/+archive/ubuntu/apache2) works fine.
```
TASK [Add repository for Apache 2.4.9+ (Ubuntu 12/14).] ************************
ok: [barnard]
```

I'm not sure if I am reading this correctly but it looks like the repo no longer has the 2.4 package for Ubuntu 12.04?

Here is a [link](https://gist.github.com/jonnyeom/bf73e48d59fc1f14810ed4277df08206) to my full config.yml

**Comment by oxyc** [comment]
Unfortunately Drupal VM has dropped support for Ubuntu 12.04 a while back. https://github.com/geerlingguy/drupal-vm/issues/1521

**Comment by oxyc** [comment]
You might be able to fix this specific issue by switching to `mod_php` instead. There are some docs on this [here](http://docs.drupalvm.com/en/latest/other/bigpipe/#apache-configuration).

1. Remove `proxy.load` and `proxy_fcgi.load`
2. Delete the `extra_parameters` line from every entry in `apache_vhosts`.
3. Add the following to your `config.yml`:
    ```yaml
    php_packages_extra:
      - "libapache2-mod-php{{ php_version }}"
    ```

**Comment by geerlingguy** [comment]
Yeah, technically you can find ways to get Apache working—though it will require a lot of extra work especially if you want 2.4, since Ondrej's repos no longer contain anything for 12.04.

Closing this as wontfix, since I can't support post-end-of-life software.
