### ISSUE TITLE
php_xdebug_cli_enable: 0 should completely unload xdebug

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1545]
### Issue Type
 - Bug Report / Support Request

### Summary

Currently, if you add the option `php_xdebug_cli_enable: 0` to your config.yml, xdebug will be disabled for the CLI, but the PHP extension will still be loaded.

Having the xdebug extension loaded (even if not enabled) can cause performance issues, as documented here: https://github.com/acquia/blt/pull/1983#issuecomment-328942432

It would be preferable to completely unload the xdebug extension.

**Comment by oxyc** [comment]
`php_xdebug_cli_enable` is no longer used. You can disable XDebug with `php_xdebug_default_enable: 0`

**Comment by oxyc** [comment]
Ah sorry. This was about unloading vs disabling. The issue tracker to post this in would be https://github.com/geerlingguy/ansible-role-php-xdebug

**Comment by danepowell** [comment]
Sorry we actually have both php_xdebug_default_enable and php_xdebug_cli_enable set in our config.yml. But anyway, yes the real issue here is to completely unload the extension. I'll post in ansible-role-php-xdebug.
