### ISSUE TITLE
Support alternatives when auto-installing plugins

### ISSUE THREAD

**Issue by hussainweb** [geerlingguy/drupal-vm#1548]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.24r117012
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** Sierra 10.12.6

### Summary

DrupalVM now auto-installs plugins by default. The problem I face is with `vagrant-hostsupdate` which I don't really need (I use `vagrant-hostmanager` which works well). But since it auto-installs, I need to remember to either remove it from default.config.yml or override it if I am using a composer setup. This is quite irritating.

What is ideal is to allow specifying alternative plugins. I have a PR ready for that. Since Ruby isn't my first language, I would appreciate some code review. I believe it can be done in a much better way than what I have tried. I have tested my changes and they work.

**Comment by geerlingguy** [comment]
This is already supported by the simple case of overriding in your `config.yml` (or `local.config.yml`):

```yaml
vagrant_plugins:
  - name: vagrant-vbguest
  # - name: vagrant-hostsupdater
  - name: vagrant-hostmanager
```

I'd rather not add additional complexity to this part of the configuration, especially since it should be fairly easy to override per-project and/or per-developer.

**Comment by oxyc** [comment]
Hmm just saw this https://github.com/roots/trellis/pull/892 which essentially makes `vagrant-auto_network` unnecessary and multiple boxes work out of the box. It requires `vagrant-hostmanager` though.

**Comment by hussainweb** [comment]
Thanks @geerlingguy. I understand what you mean about complexity. Alternatively, would you consider removing `vagrant-hostsupdate` from the default config? I have to remember to remove this line from every new project or else deal with uninstalling the hostsupdater. It is just really annoying that it checks for specific plugins when DrupalVM actually supports the alternative plugin as well.

**Comment by geerlingguy** [comment]
If there's a compelling technical reason to switch from hostsupdater to hostsmanager, I'm willing to make that change. But I'm 100% behind keeping at least one or the other in the default config. Huge help for first-time users to not have to get all gooky managing hosts file.

**Comment by hussainweb** [comment]
I see your point. The reason I use hostmanager is that it is more feature complete. It manages hosts entries on both host and guest (all guests), and I like how it adds entries in blocks in the hosts file which makes it easier to manage manually if I have to.

But I wouldn't want to force it on other users either. I didn't realise it had auto-installed hostsupdater earlier and my hosts file was filled with duplicate entries.

I can't think of any other ideas. Would you reconsider the original idea of supporting alternatives just once more? I'll respect your decision if you still don't want it. It ensures at least one of the plugins is installed.
