### ISSUE TITLE
ERROR! the role 'drupalvm.hostname' was not found

### ISSUE THREAD

**Issue by stephencross** [geerlingguy/drupal-vm#1550]
### Issue Type

 - Bug Report / Support Request

### Your Environment
Vagrant 1.9.1
VirtualBox 5.1.18r114002
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

```

### Your OS
 - **macOS** 10.12.6

### Full console output

https://gist.github.com/stephencross/a2dbb61096dc2910b861fc46c06d8f80

### Summary

Getting error:

```
ERROR! the role 'drupalvm.hostname' was not found in /Users/stephencross/Documents/dev/atfweb/box/provisioning/roles:/usr/local/etc/ansible/roles:/Users/stephencross/Documents/dev/atfweb/box/provisioning

The error appears to have been in '/Users/stephencross/Documents/dev/atfweb/box/provisioning/playbook.yml': line 35, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat', tags: ['webserver', 'php'] }
    - { role: drupalvm.hostname, when: hostname_configure }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I ran sudo ansible-galaxy install -r provisioning/requirements.yml --force to resolve the issue, but I received the same issue.

**Comment by oxyc** [comment]
How did you install Drupal VM? The roles are bundled with Drupal VM https://github.com/geerlingguy/drupal-vm/tree/master/provisioning/roles/

**Comment by stephencross** [comment]
My .gitignore include /provisioning/roles/*.

Thanks.

**Comment by geerlingguy** [comment]
@stephencross - were you able to resolve the issue, then?

**Comment by stephencross** [comment]
Yes - I was able to resolve.  Thanks
