### ISSUE TITLE
Add support for PHP 7.2

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#1552]
PR for PHP 7.2 support is available https://github.com/geerlingguy/drupal-vm/pull/1551.

Current practical issues:

- [ ] XDebug does not support 7.2 (https://github.com/geerlingguy/ansible-role-php-xdebug/issues/55)
- [ ] Drupal does not support 7.2 (https://www.drupal.org/project/issues/search?issue_tags=PHP%207.2)

**Comment by geerlingguy** [comment]
Drupal, c'mon!

**Comment by geerlingguy** [comment]
I'm going to go ahead and close this ticket, as support has been added, and hopefully Drupal will play nice in 7.2-land soon. We can open a new ticket to default to 7.2 in a month or two, hopefully!

**Comment by calipzo** [comment]
Drupal 8.4.4 is released: (https://www.drupal.org/project/drupal/releases/8.4.4):

> PHP 7.2 is fully supported and recommended for Drupal 8.

**Comment by oxyc** [comment]
remaining task for xdebug support https://github.com/geerlingguy/ansible-role-php-xdebug/issues/55
