### ISSUE TITLE
Connecting to MySQL database using faivorite tool 

### ISSUE THREAD

**Issue by matjes63** [geerlingguy/drupal-vm#1555]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Got errors on some ... as you see. But my Drupal VM is working fine
C:\drupalsites\drupalvm\drupal-onset3-project\drupal-vm>vagrant --version
Vagrant 1.9.7
C:\drupalsites\drupalvm\drupal-onset3-project\drupal-vm>echo "VirtualBox `vboxmanage --version`"
"VirtualBox `vboxmanage --version`"
C:\drupalsites\drupalvm\drupal-onset3-project\drupal-vm>ansible --version
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (version)

### Summary

Want to use my faivorite SQL tool runing from my Windows client. Have problem getting connected with ssh in the first place. Can access the site with Git Bash fine using:
ssh vagrant@192.168.88.93 -i C:/Users/Matthias/.vagrant.d/insecure_private_key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentitiesOnly=yes

Got the info how to do this from here:
http://www.hashbangcode.com/blog/connecting-vagrant-box-without-vagrant-ssh-command

But in DbVisualizer or DBeaver the ssh setup settings do not allow these details. Experimentet with different setups. It may comes down to that it needs a Passphrase for the ssh key which is in \.vagrant.d\insecure_private_key. So it can contact the ssh server with my IP and port 2222. But it fails to connect.

I saw the info how to connect with the mac tool Sequel Pro.
http://docs.drupalvm.com/en/3.5.2/extras/mysql/
But this does not work for me on Windows. And I wonder why this does not require an entry for the SSH passphrase. Leaving it empty did not help me. 

P.S. This is a niche to have as the URL to the adminer SQL works just fine.

**Comment by geerlingguy** [comment]
> It may comes down to that it needs a Passphrase for the ssh key which is in .vagrant.d\insecure_private_key.

On Windows, I think I've seen MySQL Workbench primarily used as a GUI to the database, though many just use Adminer instead.

If DBVisualizer or DBeaver don't allow an SSH key to be selected (there's no password on the `insecure_private_key` key), then I don't think you'd be able to connect using them. You have to be able to set a hostname, username (vagrant) and SSH key, then have it tunnel through that connection to the MySQL host.

Are you able to use these directions to connect?

http://confluence.dbvis.com/display/UG91/Using+an+SSH+Tunnel

If you leave the SSH Password blank, and select the `insecure_private_key` file for the 'Private Key File', I wonder if that would work.

**Comment by oxyc** [comment]
You can also login using the user `vagrant` with the password `vagrant`.

**Comment by matjes63** [comment]
DBVisualizer and DBeaver  allow to set hostname, username and SSH key. But for some reason they do not cooperate then :). As they also have the field for password, I will try using vagrant as the password. Thanks for your advice.

**Comment by thom8** [comment]
@matjes63 for reference you can also use the `insecure_private_key` as the SSH key which is found in `~/.vagrant.d/insecure_private_key`

**Comment by fubarhouse** [comment]
If you wanted to do this, you could open up port 3306 in `config.yml` and change the given user in mysql's mysql database to come from any host.

There are some security problems which might result from this, but it does work.

````
$ curl http://192.168.100.100:3306
curl: (56) Recv failure: Connection reset by peer
a+jH4bL mysql_native_password��Got packets out of order
````

**Comment by matjes63** [comment]
I still could not get DBVisualizer to work. But I got dbeaver working.

After upgrading dbeaver to 4.2.5 I was able to connect with it. It was important to use port 22 and not the default it had 2222. Beside that I was just using:

Connections setting:
server host: localhost
port: 3306
database: drupal
user name: drupal
password: drupal

Network settings:
Host/Ip: IP of my vagrant instance
port: 22
user name: vagrant 
Auth. method: Public key
Private key: C:\user\myusername \.vagrant.d\insecure_private_key
Passphrase: I left this blank

Thanks to all of you.

**Comment by FinBoWa** [comment]
Could you also close the issue as it's solved, no reason to make Jeff to close it. 

Thought did you see this: http://confluence.dbvis.com/display/UG91/Using+an+SSH+Tunnel

There is a way to connect with DBvis through a ssh tunnel according to that documentation.

**Comment by matjes63** [comment]
Yes I saw this:
Thought did you see this: http://confluence.dbvis.com/display/UG91/Using+an+SSH+Tunnel

But could not get it to work. Then tried Dbeaver and got that working.
Will colse this now, as I switched to Dbeaver.

**Comment by mrweiner** [comment]
Just want to leave a note for people to double check their ssh user/password by visiting 192.168.88.88 from your browser. I'd forgotten that my project reqs had required these be changed, so drupal/drupal weren't working, but the creds reflected on 192.168.88.88 worked perfectly.
