### ISSUE TITLE
Unknown SSL protocol error

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1556]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.5
VirtualBox 5.1.26r117224
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

### Your OS

 - **macOS** (el capitan)

### Full console output
https://gist.github.com/betz/0fec2aa1f7687be1c9e1cc6513ddc827

### Summary
I install a fresh drupalvm, with this composer.json file: 
https://gist.github.com/betz/86a23b5d6bd669dcc07c13b8c91ebd52
Regular http works over curl, but in a browser i get redirected to https with an SSL error.

Had this orginally on my working dev drupalvm, but now i tried a fresh drupalvm, copied my composer.json file and started again. Same issue.  
What could cause this?

**Comment by oxyc** [comment]
Are you using `.dev`? https://github.com/geerlingguy/drupal-vm/issues/1427#issuecomment-330317591

**Comment by betz** [comment]
Nope, I stopped doing that ;)
My hostname is local.dashboard.hsbxl.be
not to confuse with the drupalvm dashboard, which is on dashboard.local.dashboard.hsbxl.be

**Comment by oxyc** [comment]
Sounds like the browser might have cached the HTTPS redirect. Does it work if you switch browser?

**Comment by betz** [comment]
ah yes, when i reprovision with another hostname, it works.
We once set this domain name with a reverse proxy, over certbot.
I guess it is a https cache. In firefox i had the same issue, but i guess i opened it once in firefox also, or ssl caching is on OS level?

**Comment by betz** [comment]
thanks for your help

**Comment by oxyc** [comment]
I've definitely managed to clear it on macOS through Chrome directly but it's one of those things when I just press all the buttons imaginable until it suddenly works.

**Comment by betz** [comment]
http://www.reactiongifs.com/r/mgc.gif
