### ISSUE TITLE
Fix Travis CI failures due to "MailHog install fail"

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1558]
### Issue Type

 - Bug Report

### Full console output

```
Running functional tests...
Drupal install pass
Adminer install pass
Pimp my Log install pass
MailHog install fail
Script ./tests/run-tests.sh handling the run-tests event returned with error code 1
```

### Summary

See failing build: https://travis-ci.org/geerlingguy/drupal-vm/jobs/278636353#L2650

It seems that it only fails on Ubuntu 14.04 :(

**Comment by oxyc** [comment]
It passes locally in a VM

**Comment by oxyc** [comment]
> curl: (7) Failed to connect to localhost port 8025: Connection refused

**Comment by oxyc** [comment]
Found it. https://github.com/geerlingguy/ansible-role-daemonize/pull/8

docker exec $CONTAINER_ID /etc/init.d/mailhog start
Starting mailhog.
/etc/init.d/mailhog: 28: /etc/init.d/mailhog: /usr/sbin/daemonize: not found

**Comment by geerlingguy** [comment]
Thanks @oxyc ! Was hoping to get to it yesterday, but decided it would be better to get some sleep after a crazy week leading up to Drupal Camp St. Louis!
