### ISSUE TITLE
No drush alias created in the VM

### ISSUE THREAD

**Issue by sdelbosc** [geerlingguy/drupal-vm#156]
From the content of provisioning/tasks/drush-aliases.yml, I was expecting to find a file in the VM named drupalvm.aliases.drushrc.php. I don't find any.

Below is the output during VM provisioning:
```
TASK: [Check if local Drush configuration folder exists.] ********************* 
ok: [drupaldev -> 127.0.0.1]

TASK: [Create Drush configuration folder if it doesn't exist.] **************** 
skipping: [drupaldev]

TASK: [Configure host machine drush aliases.] ********************************* 
changed: [drupaldev -> 127.0.0.1]
```

**Comment by geerlingguy** [comment]
@sdelbosc - Currently, the task only creates an alias file on the host machine. Would you also like an alias file set up for the `vagrant` user account inside the VM?

**Comment by sdelbosc** [comment]
My bad. I thought this would create inside the VM.
I confirm that it is there on the host.

As I am a new user of Drupal VM, I am not sure yet if having the alias in the VM makes sense. I will try with current setup and let you know on this thread if I think there is a need of an alias within the VM.

Thanks for your prompt reply.

**Comment by geerlingguy** [comment]
No problem! I generally use (and recommend using) Drupal VM to simply contain/run the site; then I do all my work on the host machine (e.g. open my codebase in Sublime or some IDE like PHPStorm, run `compass watch` from my Mac, etc.). That way the VM is more closely emulating my live infrastructure, and doesn't need a bunch of extra development tools installed inside.

I'll close this issue for now; I can reopen if you think you'd like to make the internal alias file a feature request :).
