### ISSUE TITLE
Modules not found after setting up a fresh drupalvm installation.

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1561]
### Issue Type
 - Bug Report / Support Request

### Your OS

 - **macOS** (el capitan)

### Full console output
https://gist.github.com/betz/78be5e0ce21ea0434b942610a91dcce5

Config.yml: https://gist.github.com/betz/28986332503f387d661bb86f99682a42

### Summary
I downloaded a fresh drupalvm and moved the composer.json over from an old drupalvm setup.
Strange is the module are there. On a vagrant provision, it works normally.
Only a fresh vagrant up gives this error.

**Comment by betz** [comment]
composer.json: https://gist.github.com/betz/b426c879e55f7d78045c80fdd8f3f7f6

**Comment by oxyc** [comment]
So the initial `vagrant up` fails, and if you do `vagrant provision` after it works? Could you post the logs from `vagrant up; vagrant provision`

**Comment by betz** [comment]
did run vagrant commands verbose

vagrant up: https://gist.github.com/betz/015318950f8c907126f772aaa4e85914
vagrant provision: https://gist.github.com/betz/7c12cbebc45a342dde1f03a3087395aa

but it seems even after a provision it does not work anymore.
Just the apache default page.

**Comment by oxyc** [comment]
A bit difficult to get an overview with all that data :D 

What version of Drupal VM are you running. 

Even if you have

```
drupal_build_composer_project: true
drupal_build_composer: false
```

> provisioning/roles/geerlingguy.drupal/tasks/build-composer.yml

is included. The config you posted says it should include `build-composer-project.yml`. Are you certain your `config.yml` is being used?

---

Additionally, Drupal VM thinks the site already exists (`index.php` is present). This means Drupal VM is not downloading any modules. It's up to you to make sure they're in the codebase.

**Comment by oxyc** [comment]
The config.yml confuses me based on the ansible output to be honest. Is it the correct one? I'm not certain which build setup you're using.

**Comment by betz** [comment]
closing this issue as it works again after going for a vagrant up on my old vm.
All works. Moving to another vm is for another time. 
Guess I was mixing up stuff.
Thanks and sorry for the confusement. :)

**Comment by oxyc** [comment]
No problem, glad you got it working!
