### ISSUE TITLE
Set file_private_path

### ISSUE THREAD

**Issue by betz** [geerlingguy/drupal-vm#1570]
### Issue Type
 - Bug Report / Support Request

### Summary
Can i define the file_private_path setting from settings.php somewhere so it is ready after a fresh deploy?

**Comment by thom8** [comment]
@beta AFAIK this isn't supported at the moment but you could use a post provisioning task to update the `settings.php` file.

Can be done with a script but would recommend using -- http://docs.ansible.com/ansible/latest/lineinfile_module.html

**Comment by geerlingguy** [comment]
Yeah, it's best to either do what @thom8 suggests, or if it's for one particular project, have things configured in a version-controlled settings.php file or include (like what BLT does with local.settings.php).
