### ISSUE TITLE
Vargant up more 1 hour. It is normal?

### ISSUE THREAD

**Issue by divined** [geerlingguy/drupal-vm#1571]
Download part - 5 minutes.

i7 - 4700
16Gb
SSD - 450MBps

**Comment by geerlingguy** [comment]
@divined - Can you please create a new ticket, and in that new ticket provide all the information requested for a new ticket (e.g. command output, OS/platform, log output, etc.)? Otherwise it's very hard to understand what the problem is or any potential fixes.
