### ISSUE TITLE
Need some help installing Java 8 for Debian 8

### ISSUE THREAD

**Issue by paulcanning** [geerlingguy/drupal-vm#1574]
I have looked up a few search results for installing Java 8, but I simply have no clue what settings I should use and how to implement it.

This github readme, https://github.com/geerlingguy/ansible-role-java#example-playbook-install-openjdk-8, shows config for Ubuntu, not Debian, despite is using the word Debian in the config...

However, I have no idea how to add this into my DVM setup. I get that a playbook is a yml file, but what do i call the file, where does it go, how do i make sure it is used etc?

At the moment, I have the main config.yml, where I am defining the Solr version, so why can't I define the java version here too?

Oddly, I see under installed_extras that Java can be included, and even though I have it commented out, it is being installed anyway.

Sorry for the questions, I'm just struggling to get to grips with this whole DVM and Ansible thing

**Comment by FinBoWa** [comment]
> At the moment, I have the main config.yml, where I am defining the Solr version, so why can't I define the java version here too?

What exactly makes you think you can't do that? Best thing would be to try stuff and then ask questions :). 

Note the the commented out java line under config.yml's installed_extras

  # - java

If you uncomment that line it will use geerllinguys role java role.

**Comment by paulcanning** [comment]
> What exactly makes you think you can't do that?

Can I do that?

> If you uncomment that line it will use geerllinguys role java role.

Can I edit this role?, I don't like the sound of editing stuff that I wouldn't typically have control over, hence asking about the config.yml file

> Then adding the role variables to the yaml file you can override the defaults.

Which file exactly?

**Comment by thom8** [comment]
@paulcanning the role exposes a few variables so you may not need to edit it -- https://github.com/geerlingguy/ansible-role-java

**Comment by paulcanning** [comment]
@thom8 sorry, but I've read that page and I just don't understand where I'm supposed to put those settings (I explained this in my opening post)

**Comment by thom8** [comment]
Any of these variables can go into the `config.yml` file which will override the default in the role, there's a specific list of config files that can be used, each overriding the previous.

So I'll often use the `local.config.yml` for testing then move it into the version controlled `config.yml`

**Comment by FinBoWa** [comment]
> > Then adding the role variables to the yaml file you can override the defaults.

> Which file exactly?

config.yml 

http://docs.drupalvm.com/en/latest/getting-started/configure-drupalvm/#2-configyml . 

```
The main configuration file of a project. Commonly this is a copy of default.config.yml with the values tweaked to your own project. For an easier upgrade path you would only set the values you are actually overriding.
```

**Comment by geerlingguy** [comment]
@paulcanning - Also see: https://github.com/geerlingguy/ansible-role-solr/blob/master/tests/test-solr-6.yml#L11-L29 — that's what I used in my solr role to update to Java 8 on Debian for testing purposes. Some set of tasks like that may help if you add them in a pre-provision script / task file: http://docs.drupalvm.com/en/latest/extending/scripts/

**Comment by oxyc** [comment]
I'll close this as there hasn't been any response in a while and I assume the explanations given helped you sort it out. If you still need help, let us know.
