### ISSUE TITLE
Which Drupal install method should I use?

### ISSUE THREAD

**Issue by paulcanning** [geerlingguy/drupal-vm#1577]
I'm playing around with the Drupal install methods and I'm getting a bit lost by them.

My project is laid out as such:

Drupal Core installed via composer.json
DrupalVM installed via the same composer.json

Composer.json file:

```
{
    "name": "drupal-composer/drupal-project",
    "description": "Project template for Drupal 8 projects with composer",
    "type": "project",
    "license": "GPL-2.0+",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "composer/installers": "^1.2",
        "cweagans/composer-patches": "^1.6",
        "drupal-composer/drupal-scaffold": "^2.2",
        "drupal/console": "^1.0.1",
        "drupal/core": "^8.4",
        "drupal/devel": "1.x-dev",
        "drush/drush": "~8.0",
        "webflo/drupal-finder": "^1.0.0",
        "webmozart/path-util": "^2.3"
    },
    "require-dev": {
        "behat/mink": "~1.7",
        "behat/mink-goutte-driver": "~1.2",
        "geerlingguy/drupal-vm": "^4.7",
        "jcalderonzumba/gastonjs": "~1.0.2",
        "jcalderonzumba/mink-phantomjs-driver": "~0.3.1",
        "mikey179/vfsstream": "~1.2",
        "phpunit/phpunit": ">=4.8.28 <5",
        "symfony/css-selector": "~2.8"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "sort-packages": true
    },
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ]
    },
    "scripts": {
        "drupal-scaffold": "DrupalComposer\\DrupalScaffold\\Plugin::scaffold",
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::createRequiredFiles"
        ]
    },
    "extra": {
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": ["type:drupal-library"],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        }
    }
}
```

Should I be using:

1. drupal_build_composer
2. drupal_build_composer_project
or
3. drupal_install_site

I've tried deciphering the documentation, but it's honestly quite confusing.

**Comment by paulcanning** [comment]
So this is confusing as heck.

I am using Drupal Composer, which needs to run 'composer create-project' to install.

But then the option 'drupal_build_composer_project' also does this - is that the correct method?

**Comment by FinBoWa** [comment]
Would this help line of thought help you: 

If you just run vagrant up without adding your own composer.json would it install drupal or not and what method it would use then? 

You now want explicitly use your own composer.json file to tell the necessary dependencies.

Answer for that should be here http://docs.drupalvm.com/en/latest/deployment/composer/

**Comment by FinBoWa** [comment]
Personally id suggest you follow the struckture here: http://docs.drupalvm.com/en/latest/deployment/composer-dependency/

And keep the "composer.json" in the root of the project for "drupalvm" only and the composer.json for durpal separeate.

**Comment by paulcanning** [comment]
Basically, I need to have Drupal install via composer (using the Drupal composer project from github) and have Drupal VM as a dev dependency, in such a way that a developer could use a different local environment if they choose, such as built in PHP server or Acquia Dev Desktop.

**Comment by oxyc** [comment]
> Personally id suggest you follow the folder structure here: http://docs.drupalvm.com/en/latest/deployment/composer-dependency/
>
> And keep the "composer.json" in the root of the project for "drupalvm" and any other composer installable tools you fancy and your own composer.json for drupal separate.

Like @FinBoWa mentioned is the recommended setup. 

1. Set up your project using [drupal-composer/drupal-project](https://github.com/drupal-composer/drupal-project)
2. Require Drupal VM as a dev dependency: `composer require --dev geerlingguy/drupal-vm`
3. Configure it according to this [documentation page](http://docs.drupalvm.com/en/latest/deployment/composer-dependency/)

In the next major Drupal VM release we'll probably remove some of the set up methods and hopefully make it more understandable.
