### ISSUE TITLE
First time install fails at Ansible playbook whilst attempting ssh connection

### ISSUE THREAD

**Issue by budda** [geerlingguy/drupal-vm#1579]
### Issue Type

 - Bug Report

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.0.12r104815
ansible 2.2.1.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (version)

### Full console output

```
==> drupalvm: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.2.1.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    drupalvm: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
fatal: [drupalvm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}
	to retry, use: --limit @/Users/mike/Code/drupal/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=0    changed=0    unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary

First time installing DrupalVM. The installer / setup failed with above console output.
Re-running vagrantup didn't complain about anything and claimed everything was up and running -- but it's not.

```
==> drupalvm: Machine already provisioned. Run `vagrant provision` or use the `--provision`
==> drupalvm: flag to force provisioning. Provisioners marked to run always will still run.

==> drupalvm: Machine 'drupalvm' has a post `vagrant up` message. This is a message
==> drupalvm: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drupalvm:
==> drupalvm: Your Drupal VM Vagrant box is ready to use!
==> drupalvm: * Visit the dashboard for an overview of your site: http://dashboard.drupalvm.test (or http://192.168.88.88)
==> drupalvm: * You can SSH into your machine with `vagrant ssh`.
==> drupalvm: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com
```

I'm not sure how to recover with the mentioned ```playbook.retry``` file either.

**Comment by geerlingguy** [comment]
@budda I noticed you're running `VirtualBox 5.0.12r104815`; can you please upgrade to the latest version of VirtualBox 5.1.x and try again? 5.0.x has not been supported for a while, due to some major networking differences.

**Comment by rpsu** [comment]
I got rid of this by adding a setting to Vagrantfile:
`config.vm.provider :virtualbox do |v|
  ....
  v.customize ["modifyvm", :id, "--cableconnected1", "on"]
   ....
end`
This setting can be enabled via Virtualbox UI, too, but the 1st attempt to provision the box fails (OS X High Sierra, Virtualbox 5.0.0, Vagrant 2.0.1)

**Comment by rpsu** [comment]
PR 1648 might help with this.

**Comment by rpsu** [comment]
#1648

**Comment by oxyc** [comment]
@budda did you try to updating VirtualBox?

**Comment by budda** [comment]
Yes finally upgraded VirtualBox to 5.2 and Vagrant and re-ran Drupal VM and a D8 install worked fine.

**Comment by oxyc** [comment]
Great! @rpsu please open up a new issue with some more information regarding the PR you opened and I can try to reproduce/test it.
