### ISSUE TITLE
Ansible cannot find role in folder

### ISSUE THREAD

**Issue by applecrusher** [geerlingguy/drupal-vm#158]
Hey,

I keep getting this error when I install. It's looking for a roles folder but that doesn't exist. Do you know what the issue may be?

ERROR: cannot find role in /Users/me/Documents/drupal-vm-master/provisioning/roles/geerlingguy.repo-remi or /Users/me/Documents/drupal-vm-master/provisioning/geerlingguy.repo-remi or /usr/local/etc/ansible/roles/geerlingguy.repo-remi
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Please try running: `ansible-galaxy install -r provisioning/requirements.txt --force` to get all the latest dependencies installed.

**Comment by marleyblakedog** [comment]
For anyone who may search for this error:
If you try the above and get `error: you do not have permission to modify files in /etc/ansible/roles/...`, you'll need to set the install path as well:

`ansible-galaxy install -r provisioning/requirements.txt -p provisioning/roles/`

**Comment by geerlingguy** [comment]
@marleyblakedog - That's one way of doing it; otherwise, use `sudo` for the `ansible-galaxy` command and it will be able to save/update roles in the global role path.

**Comment by dcorb** [comment]
it has changed to yml extension
```sudo ansible-galaxy install -r provisioning/requirements.yml -p provisioning/roles/```

**Comment by geerlingguy** [comment]
@dcorb - Ha, no problem at all! It was a change in 2.1.0 for better forwards compatibility with Ansible 2.0.x and beyond.

**Comment by micheal-cooper** [comment]
I am getting 
`Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()`
(full error feedback below).

Is this an issue, or should it be ignored?

I have not gotten the VM to work fully yet, so I cannot tell.

`sudo ansible-galaxy install -r provisioning/requirements.yml --force
- downloading role 'selenium', owned by arknoll
- downloading role from https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
- extracting arknoll.selenium to /etc/ansible/roles/arknoll.selenium
- arknoll.selenium was installed successfully
- downloading role 'adminer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-adminer/archive/1.1.0.tar.gz
- extracting geerlingguy.adminer to /etc/ansible/roles/geerlingguy.adminer
- geerlingguy.adminer was installed successfully
- downloading role 'apache', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/1.6.0.tar.gz
- extracting geerlingguy.apache to /etc/ansible/roles/geerlingguy.apache
- geerlingguy.apache was installed successfully
- downloading role 'apache-php-fpm', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-apache-php-fpm/archive/1.0.1.tar.gz
- extracting geerlingguy.apache-php-fpm to /etc/ansible/roles/geerlingguy.apache-php-fpm
- geerlingguy.apache-php-fpm was installed successfully
- dependency geerlingguy.apache is already installed, skipping.
- downloading role 'composer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-composer/archive/1.4.0.tar.gz
- extracting geerlingguy.composer to /etc/ansible/roles/geerlingguy.composer
- geerlingguy.composer was installed successfully
- downloading role 'daemonize', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-daemonize/archive/1.1.0.tar.gz
- extracting geerlingguy.daemonize to /etc/ansible/roles/geerlingguy.daemonize
- geerlingguy.daemonize was installed successfully
- downloading role 'drupal-console', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drupal-console/archive/1.0.4.tar.gz
- extracting geerlingguy.drupal-console to /etc/ansible/roles/geerlingguy.drupal-console
- geerlingguy.drupal-console was installed successfully
- dependency geerlingguy.php is already installed, skipping.
- downloading role 'drush', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-drush/archive/1.1.3.tar.gz
- extracting geerlingguy.drush to /etc/ansible/roles/geerlingguy.drush
- geerlingguy.drush was installed successfully
- dependency geerlingguy.composer is already installed, skipping.
- dependency geerlingguy.git is already installed, skipping.
- dependency geerlingguy.php is already installed, skipping.
- downloading role 'firewall', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-firewall/archive/1.0.9.tar.gz
- extracting geerlingguy.firewall to /etc/ansible/roles/geerlingguy.firewall
- geerlingguy.firewall was installed successfully
- downloading role 'git', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-git/archive/1.1.1.tar.gz
- extracting geerlingguy.git to /etc/ansible/roles/geerlingguy.git
- geerlingguy.git was installed successfully
- downloading role 'java', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-java/archive/1.3.0.tar.gz
- extracting geerlingguy.java to /etc/ansible/roles/geerlingguy.java
- geerlingguy.java was installed successfully
- downloading role 'mailhog', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mailhog/archive/1.0.5.tar.gz
- extracting geerlingguy.mailhog to /etc/ansible/roles/geerlingguy.mailhog
- geerlingguy.mailhog was installed successfully
- dependency geerlingguy.daemonize is already installed, skipping.
- downloading role 'memcached', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-memcached/archive/1.0.4.tar.gz
- extracting geerlingguy.memcached to /etc/ansible/roles/geerlingguy.memcached
- geerlingguy.memcached was installed successfully
- downloading role 'mysql', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-mysql/archive/2.0.2.tar.gz
- extracting geerlingguy.mysql to /etc/ansible/roles/geerlingguy.mysql
- geerlingguy.mysql was installed successfully
- downloading role 'nginx', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nginx/archive/1.8.0.tar.gz
- extracting geerlingguy.nginx to /etc/ansible/roles/geerlingguy.nginx
- geerlingguy.nginx was installed successfully
- downloading role 'nodejs', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/2.1.1.tar.gz
- extracting geerlingguy.nodejs to /etc/ansible/roles/geerlingguy.nodejs
- geerlingguy.nodejs was installed successfully
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()
`

**Comment by geerlingguy** [comment]
It looks like this is the issue: `No such file or directory: 'provisioning/requirements.txt'` - you should be using `requirements.yml` in the command and not `.txt`.

**Comment by micheal-cooper** [comment]
I messed up the formatting of the error messages above. The first command

> sudo ansible-galaxy install -r provisioning/requirements.yml --force

ended with 

> Traceback (most recent call last): File "/usr/local/bin/ansible-galaxy", line 959, in main() File "/usr/local/bin/ansible-galaxy", line 953, in main fn(args, options, parser) File "/usr/local/bin/ansible-galaxy", line 819, in execute_install if len(role_versions) > 0: TypeError: object of type 'NoneType' has no len()

so just to be thorough, I tried with .txt

> sudo ansible-galaxy install -r provisioning/requirements.txt --force

which failed with

> Traceback (most recent call last): File "/usr/local/bin/ansible-galaxy", line 959, in main() File "/usr/local/bin/ansible-galaxy", line 953, in main fn(args, options, parser) File "/usr/local/bin/ansible-galaxy", line 765, in execute_install f = open(role_file, 'r') IOError: [Errno 2] No such file or directory: 'provisioning/requirements.txt'`

**Comment by geerlingguy** [comment]
Oh, okay. In that case, can you do an `ansible --version` as well?

**Comment by micheal-cooper** [comment]
Just updated today, along with updating your vagrant to the latest.

ansible --version
ansible 1.9.3
  configured module search path = None

**Comment by geerlingguy** [comment]
Can you upgrade to Ansible 2.0.x? There are a few tasks that now rely on features only in Ansible 2.

**Comment by micheal-cooper** [comment]
Well, that fixed the Ansible errors with roles and got me much farther than before. 

I am still not able to use DrupalVM, but I think I am getting there.

I am now getting  "[Errno 13] Permission denied" errors, but I have yet to fully search for it in your Git Issues discussions. Hopefully, there will be a solution there.

Thank you for the recommendation to move to Ansible 2! This is a big step forward.

Also, I heard your interview on the Drupal podcast. Really enjoyed it, and it convinced me to persist in getting your DrupalVM to work instead of giving up and going back to MAMP or using Homestead or trying Docker.

Micheal


On 2016/04/04 20:22, "Jeff Geerling" <notifications@github.com> wrote:


Can you upgrade to Ansible 2.0.x? There are a few tasks that now rely on features only in Ansible 2.
