### ISSUE TITLE
vagrant up fails due to a denied access in the context of mount.nfs on macosx

### ISSUE THREAD

**Issue by rpkoller** [geerlingguy/drupal-vm#1582]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.0
vagrant-vbguest (0.15.0)
vagrant-hostsupdater (1.0.2)
VirtualBox 5.1.30r118389
ansible 2.4.0.0
  config file = /Users/myuser/.ansible.cfg
  configured module search path = [u'/Users/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.0.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (10.11.6)

### Full console output

https://gist.github.com/rpkoller/61048f9436aae0169a78982f50b19996

### Summary

I have downloaded drupalvm version `4.7.0`. I have duplicated and renamed `example.drupal.composer.json` to `drupal.composer.json` and left it as is. `default.config.yml` i've duplicated and renamed to `config.yml`. i've changed only the following lines in contrast to the default config file:

```
vagrant_ip: 192.168.88.90
drupal_build_composer: true
drupal_build_composer_project: false
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
```
that's it, nothing else altered. when i ran `vagrant up` like shown in the gist i get the following error: 

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.88.1:/Users/myuser/Sites/drupalvm /var/www/drupalvm

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.88.1:/Users/myuser/Sites/drupalvm
```
i've looked into the issue history of the repo and found similar issues. they are marked as closed and seem to be solved, but at least for me the issue persists. :/ haven't used drupalvm in a while and before haven't had that kind of problems. they turned up the first time now. :/ if you need any further informations let me know. best regards ralf

**Comment by rpkoller** [comment]
ok i figured things out. i had a docker based solution for wordpress running alongside which was also placing `exports` inside the `/etc/exports` file. problem was that that particular app set the scope of the export to `/users` instead of a more specific projects based directory. adjusting that fixed the issue. the better error messages in vagrant 2.x helped tracking the root of the problem down.

**Comment by paulcanning** [comment]
How exactly did you fix this issue, as I am experiencing similar issues.

**Comment by rpkoller** [comment]
As i wrote in my followup reply. I took a look at `/etc/exports` and noticed overlaps for the exported paths for DrupalVM and Local by Flywheel. The solution in my case was that Local exported the entire `/users`folder instead of the folder containing the Local projects. So i've changed the lines for Flywheel instead of `users` to `/users/myuser/localsites` so the overlaps in `/etc/exports`were removed. That solved the issue in my case.

**Comment by paulcanning** [comment]
Yea, that makes zero sense to me :(

**Comment by rpkoller** [comment]
There aren't any overlaps in `/etc/exports` in your case?

**Comment by carnnia** [comment]
/etc/exports is auto generated, your manual changes will get over written; so I am confused how that worked for you.
