### ISSUE TITLE
reload --provision fails when switching solr version

### ISSUE THREAD

**Issue by batigolix** [geerlingguy/drupal-vm#1583]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.28r117968
-bash: ansible: command not found
```

### Your OS

 - **macOS** (Sierra 10.12.6)

### Full console output

https://gist.github.com/batigolix/7ed6905660488c6a31b1fd4aa4cc5945

### Summary

If I switch solr version from 5.x to 4.10.4 in the config.yml then Drupalvm fails to provision that change. Somehow the existing solr cannot be replaced.

The error message is:
```
TASK [geerlingguy.solr : Copy Solr into place.] ********************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["cp", "-r", "/root/solr-4.10.4", "/opt/solr"], "delta": "0:00:00.002133", "end": "2017-10-18 08:36:33.428680", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-10-18 08:36:33.426547", "stderr": "cp: cannot stat '/root/solr-4.10.4': No such file or directory", "stderr_lines": ["cp: cannot stat '/root/solr-4.10.4': No such file or directory"], "stdout": "", "stdout_lines": []}

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************
	to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=175  changed=3    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by FinBoWa** [comment]
@batigolix should it actually be able to change a version. 

You are more likely required to either remove the old version with your own task, manually or just deleting the box. 

Not many ansible roles handle removing installed libraries.

**Comment by batigolix** [comment]
Ok, that explains. So changing solr versions in the config file does not replace anything. You must destroy the virtual box and rebuild it.

**Comment by geerlingguy** [comment]
Yeah, sorry about that, but unlike some of my other roles, it's really hard to get solr major version changes automated, so I recommend doing a `vagrant destroy` and `vagrant up` if switching from 4->5, 6->4, etc.

**Comment by batigolix** [comment]
My work around is to have various solr instances (different versions and multiple cores) running on the host machine and call it from Drupal on the ip address 10.0.2.2

@geerlingguy : thanks for the great work on drupal-vm!

**Comment by alex-moreno** [comment]
destroy && up from scratch worked fine to fix this and change solr versions
