### ISSUE TITLE
Configure trusted_host_patterns during `vagrant up`

### ISSUE THREAD

**Issue by blakemorgan** [geerlingguy/drupal-vm#1584]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.28r117968
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/blakemorgan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS** (10.13)

### Summary

In my status report, I get an error telling me that I need to configure trusted_host_patterns in my settings file. Would it be possible to add this code to the settings.php file during setup? The host can be whatever the host is configured to be in config.yml.

```php
$settings['trusted_host_patterns'] = array(
  '^drupalvm\.test$',
  '^.+\.drupalvm\.test$',
);
```

**Comment by oxyc** [comment]
I'll close this as a wont fix with @geerlingguy earlier response on something similar https://github.com/geerlingguy/drupal-vm/issues/1417#issuecomment-307651038

> d rather defer settings.php management to either Drush/Drupal (as is the case when installing a new site), or to your own deployment/provisioning setup
