### ISSUE TITLE
Virtualbox 5.2 not supported by Vagrant? using older hardware

### ISSUE THREAD

**Issue by Shurrir** [geerlingguy/drupal-vm#1587]
### Issue Type

I'm trying to install drupalvm on a newly installed OS.
I did the exact same install yesterday on a new system, it worked perfectly. Today I'm doing the same thing on an older computer and Vagrant is telling me it doesn't support Virtualbox 5.2?

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.2.0r118431
ansible 2.2.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **Linux** (Ubuntu 17.10)

### System Specifications

Memory: 2.9 GiB
Processor: Intel® Core™2 Duo CPU E8400 @ 3.00GHz × 2
Graphics: Gallium 0.4 on NVA5
OS type: 64-bit
Disk: 97,9 GB

### Full console output

**vagrant up**
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V.

The easiest solution to this message is to install VirtualBox, which
is available for free on all major platforms.

If you believe you already have a provider available, make sure it
is properly installed and configured. You can see more details about
why a particular provider isn't working by forcing usage with
`vagrant up --provider=PROVIDER`, which should give you a more specific
error message for that particular provider.

**vagrant up --provider=virtualbox**
The provider 'virtualbox' that was requested to back the machine
'vm-drupal8.dev' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant has detected that you have a version of VirtualBox installed
that is not supported by this version of Vagrant. Please install one of
the supported versions listed below to use Vagrant:

4.0, 4.1, 4.2, 4.3, 5.0, 5.1

A Vagrant update may also be available that adds support for the version
you specified. Please check www.vagrantup.com/downloads.html to download
the latest version.

### Summary

I'm trying to install drupalvm on an older machine.
Did the exact same install yesterday on a newer machine and it worked fine.
For some reason vagrant is telling me it's not supporting VirtualBox 5.2 on this system.

Both Vagrant and VirtualBox are installed correctly.
Tried removing them and re-installing them.

Vagrant: I used the 64 bit Debian version from https://www.vagrantup.com/downloads.html
Virtualbox: I used the Ubuntu 17.04 ("Zesty") AMD64 version from https://www.virtualbox.org/wiki/Linux_Downloads

Installed both with dpkg - got no errors.

**Comment by danepowell** [comment]
Vagrant explicitly does not support VirtualBox 5.2: https://www.vagrantup.com/docs/virtualbox/

> The VirtualBox provider is compatible with VirtualBox versions 4.0.x, 4.1.x, 4.2.x, 4.3.x, 5.0.x, and 5.1.x. Other versions are unsupported and the provider will display an error message.

This seems like a problem with Vagrant, not DrupalVM.

**Comment by rpkoller** [comment]
the support for vb 5.2 will get into the next minor release of vagrant:

https://github.com/hashicorp/vagrant/issues/9075

**Comment by Shurrir** [comment]
There is no older vb version for Ubuntu 17?
I tried installing the vb for Ubuntu 16 but it failed.
This worked on my new system that also runs Ubuntu 17.10

**Comment by geerlingguy** [comment]
@Shurrir Yeah, the difficulty is that Ubuntu 17.10 is pretty much bleeding-edge right now, and there are a lot of growing pains when you're running all the latest and greatest of everything :)

I'm going to close this issue, since there's nothing I can do for Drupal VM to accelerate 5.2 support in Vagrant, but thanks for opening it!

**Comment by geerlingguy** [comment]
Seems like Vagrant 5.2.x is working okay now—at least in my case with my Mac running High Sierra 10.12.3. I updated all my Vagrant base boxes to include the 5.2.4 guest additions by default (sorry about the delay in getting those out and tested!)

**Comment by jenter** [comment]
I tested installing with `5.2.6` and ran into the same issue.
```
No usable default provider could be found for your system.

Vagrant relies on interactions with 3rd party systems, known as
"providers", to provide Vagrant with resources to run development
environments. Examples are VirtualBox, VMware, Hyper-V. 
```

So I downgraded to `5.2.4` and working proper, so the latest version might still cause issues.

**Comment by rwestphal** [comment]
@jenter just checked and Vagrant 2.0.1 is working with VirtualBox 5.2.6 :)

**Comment by monalish** [comment]
@rwestphal Thanks for the solution.
