### ISSUE TITLE
Add a MAMP Pro-like GUI

### ISSUE THREAD

**Issue by damienmckenna** [geerlingguy/drupal-vm#159]
From the POV of making it more accessible to beginners (or people who don't want to spend time learning more command line tools ;) ), it'd be useful if there was a MAMP Pro -like GUI for controlling the different installations and their various options.

**Comment by geerlingguy** [comment]
True... but I would rather not maintain a GUI for this as part of the Drupal VM project itself; if someone would like to work on a cross-platform GUI layer, that would be most welcome, but I don't have the time/inclination to do so myself.

I'll leave this issue open for the time being, so others can chime in with ideas/offers to help, but I'll close it at some point once enough visibility is reached.

**Comment by willvincent** [comment]
Something like [PyGUI](http://www.cosc.canterbury.ac.nz/greg.ewing/python_gui/) would probably be good for this.  If someone familiar with python were so inclined to build such a thing.  

However, the biggest challenge I see to something like this is that since a handful of tools are necessary to make use of VM's though, even a gui may not remove much of the complexity of getting up and running.

**Comment by geerlingguy** [comment]
The other thing that makes this less appealing to me is that many layers of UI abstraction for building Vagrant-based dev environments already exist, like:

  - http://phansible.com/ (Web UI to build PHP dev environments with Vagrant + Ansible)
  - https://puphpet.com/ (Web UI to build PHP dev environments with Vagrant + Puppet)

And then there's MAMP, XAMPP, and ADD2, which all basically do the exact same thing, but have a model of 'one server running locally + a bunch of sites/vhosts on top of it'.

I personally don't like the interference of a UI when I can have one solid config file to manage :)

**Comment by willvincent** [comment]
A GUI for managing that config file could be interesting though

**Comment by geerlingguy** [comment]
@willvincent - Definitely—and something like a simple PHP script/app (or even something all JS/frontend) could do that aspect, and just be the exact same interface as phansible.com, but the output would be a `config.yml` file download.

**Comment by fubarhouse** [comment]
@geerlingguy The idea of downloading a config.yml file actually sounds like a bit of fun... Totally useless in my particular case but fun regardless. No promises, but I might try to put something together if I can find some time.

**Comment by geerlingguy** [comment]
Sounds good! I'd be happy to link to some 'unofficial' projects that help configure Drupal VM. I think the main one I currently have linked in the docs might not even work with the latest versions of Drupal VM anymore...: http://docs.drupalvm.com/en/latest/other/cloning-with-newd/

**Comment by fubarhouse** [comment]
On the newd note Jeff, I'll be in touch later - I'll pass on a copy of one of my install scripts after I take out sensitive information. It may only be a simple bash script, but I get the feeling you'll be quite interested.

The script I made for personal use allows infinite drupalvm builds, different hostnames (generated on run) and can easily be made to suit different IP addresses. On top of this, I maintain a script which builds sites using make files and all compatible with Acquia allowing unlimited drupal sites...

**Comment by geerlingguy** [comment]
:+1: awesome!

**Comment by geerlingguy** [comment]
I'm going to close this out for now; feel free to use the issue for further discussion, but I'm just clearing out some of the issues I'm not planning on working myself.
