### ISSUE TITLE
Define git_install_from_source_dependencies Task gets Skipped

### ISSUE THREAD

**Issue by nehajyoti04** [geerlingguy/drupal-vm#1591]
When i run vagrant up, Define git_install_from_source_dependencies gets skipped and then Ensure git's dependencies are installed gets failed because has not been defined previously.

TASK [geerlingguy.git : Define git_install_from_source_dependencies.] **********
skipping: [drupalvm]

TASK [geerlingguy.git : Ensure git's dependencies are installed (RedHat).] *****
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "'git_install_from_source_dependencies' is undefined"}

**Comment by thom8** [comment]
@nehajyoti04 what version of Drupal VM are you using?

Also, what is the base OS? the var `__git_install_from_source_dependencies ` should be getting defined here -- https://github.com/geerlingguy/ansible-role-git/blob/master/tasks/install-from-source.yml#L3-L15 then this is used as the default value for `git_install_from_source_dependencies `

As a workaround you could also define `git_install_from_source_dependencies` based on the OS you're using from this list -- https://github.com/geerlingguy/ansible-role-git/tree/master/vars

**Comment by fubarhouse** [comment]
@nehajyoti04, could you also provide the output of the previous three tasks?

I'm happy to try to replicate it if you can provide the config.yml and details on anything else.

The task is installing dependencies required for installing git from **source**.

If this isn't really a need or desire, you can set `git_install_from_source` to `false`, and a different set of tasks can continue to run - which is probably more suitable to more people.

**Comment by oxyc** [comment]
I'll close this issue as there's been no response since October. If you're still having issues, please let us know the answers to the questions asked above, and we'll reopen this!
