### ISSUE TITLE
Recent GET and vboxadd.sh Errors

### ISSUE THREAD

**Issue by mgamshad** [geerlingguy/drupal-vm#1592]
### Issue Type
Support Request: running vagrant up is reporting a few GET errors in addition to an error reported from vboxadd.sh.  Wondering if these are to be resolved or expected to not have any impact?  The box does seem to be created and functional, which makes me think the errors are not affecting anything, but trying to get confirmation on that.

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.28r117968
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Feb  6 2017, 23:53:20) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### Your OS
- macOS Sierra (10.12.4)

### Full console output
GET errors:
```
Get:17 http://us.archive.ubuntu.com/ubuntu/ trusty/main libfakeroot amd64 1.20-3ubuntu2 [25.4 kB]
Get:18 http://us.archive.ubuntu.com/ubuntu/ trusty/main fakeroot amd64 1.20-3ubuntu2 [55.0 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libc-dev-bin amd64 2.19-0ubuntu6.13 [69.0 kB]
Err http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main linux-libc-dev amd64 3.13.0-125.174
  404  Not Found [IP: 91.189.91.26 80]
Get:20 http://us.archive.ubuntu.com/ubuntu/ trusty-updates/main libc6-dev amd64 2.19-0ubuntu6.13 [1,914 kB]
Err http://security.ubuntu.com/ubuntu/ trusty-security/main linux-libc-dev amd64 3.13.0-125.174
  404  Not Found [IP: 91.189.88.149 80]
Get:21 http://us.archive.ubuntu.com/ubuntu/ trusty/main manpages-dev all 3.54-1ubuntu1 [1,820 kB]
Fetched 16.4 MB in 6s (2,503 kB/s)
E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/l/linux/linux-libc-dev_3.13.0-125.174_amd64.deb  404  Not Found [IP: 91.189.88.149 80]

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
Ign http://us.archive.ubuntu.com trusty InRelease

```

Errors from vboxadd.sh:

```
Installing additional modules ...
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
An error occurred during installation of VirtualBox Guest Additions 5.1.28. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
vboxadd-service.sh: Starting VirtualBox Guest Addition service.
VBoxService: error: VbglR3Init failed with rc=VERR_FILE_NOT_FOUND
```

### Summary

I am trying to find out if the new set of GET errors and errors reported from vboxadd.sh are expected and will not have any impact, or if they need to be resolved?

**Comment by thom8** [comment]
@mgamshad this looks like a network issue, can you try to access `http://security.ubuntu.com/ubuntu/` via the browser?

It could also be a DNS issue where you're you aren't able to resolve `security.ubuntu.com` try `ping security.ubuntu.com` to check if it resolves to an IP.

**Comment by geerlingguy** [comment]
Also, a lot of times it just takes a little while and things just magically work (pointing again at what @thom8 suggested, a network issue).

Can you try again and see if the problem occurs again? Use `vagrant destroy -f` to destroy the VM entirely, then `vagrant up` again.

**Comment by mgamshad** [comment]
Hi @thom8, yes I can hit that address in the browser.  It shows me an index page:
<img width="420" alt="index" src="https://user-images.githubusercontent.com/22755362/32469210-784f04f4-c306-11e7-8530-2eef7f645dab.png">

@geerlingguy the reported 404s and the vbox errors are consistently happening:

<img width="1052" alt="404s" src="https://user-images.githubusercontent.com/22755362/32469300-de55ad20-c306-11e7-8839-66ccaa8a4d3f.png">


<img width="862" alt="vbox-err" src="https://user-images.githubusercontent.com/22755362/32469306-e25ec88e-c306-11e7-9373-c505fd34f90d.png">

**Comment by mgamshad** [comment]
btw, the GET 404 errors are consistently on the same resources.

**Comment by isaiahnixon** [comment]
@mgamshad Is this still an issue for you?

**Comment by mgamshad** [comment]
Hi, I consistently am seeing the GET errors but it somehow doesn't seem to be affecting anything since the box seems to be functioning after installation.  Still curious as to the reason for the errors?  I wonder if the log is even correct?

**Comment by geerlingguy** [comment]
@mgamshad if everything else is working okay, I'd say ignore the errors—I think I see apt operations display various errors about half the time I do anything with apt... as long as it works in the end, the system is in a good state.

Also, I've recently updated my base boxes with later versions of everything, so VirtualBox 5.2.4 (and lower) are fully supported, and it _should_ work on 5.2.6 as well (though I haven't rebuilt the base boxes for .6 yet.
