### ISSUE TITLE
Unable to update drush

### ISSUE THREAD

**Issue by pminf** [geerlingguy/drupal-vm#1594]
### Issue Type

Bug Report

### Environment

Drupal-VM 4.7.0
Vagrant 1.9.6
VirtualBox 5.1.28 r117968 (Qt5.6.2)

### OS

Microsoft Windows 10 Pro (Version 10.0.14393 Build 14393)

### Full console output

config.yml
```
drush_version: "8.1.14"
```

```
vagrant reload --provision
[...]
TASK [geerlingguy.drush : Check current state.] ********************************
ok: [mydrupalvm]

TASK [geerlingguy.drush : Perform cleanup of old symlink.] *********************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Install Drush.] **************************************
ok: [mydrupalvm]

TASK [geerlingguy.drush : Ensure Drush is executable.] *************************
ok: [mydrupalvm]

TASK [geerlingguy.drush : Clone Drush from GitHub.] ****************************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Check for composer.json] *****************************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Ensure Drush can be installed on Debian Wheezy.] *****
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Create drush symlink.] *******************************
skipping: [mydrupalvm]

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
skipping: [mydrupalvm]

[...]

TASK [Configure host machine drush aliases.] ***********************************
changed: [mydrupalvm -> 127.0.0.1]

TASK [Ensure drush directory exists for vagrant user inside VM.] ***************
ok: [mydrupalvm]

TASK [Configure drush aliases for vagrant user inside VM.] *********************
changed: [mydrupalvm]

TASK [Ensure drush directory exists for root user inside VM.] ******************
ok: [mydrupalvm]

TASK [Configure drush aliases for root user inside VM.] ************************
ok: [mydrupalvm]

[...]
mydrupalvm       : ok=202  changed=2    unreachable=0    failed=0
```

```
vagrant@drupal:/var/www$ drush version
 Drush Version   :  8.1.10
```

### Summary

Although if have set up the vm to use Drush 8.1.14 the current version is still 8.1.10. Of course I've updated my vm via `vagrant reload --provision`. I had to destroy the vm and install again to use 8.1.14.

**Comment by thom8** [comment]
@pminf you'll need to also set `drush_keep_updated: yes` as by default it won't update drush if it's already installed.

see https://github.com/geerlingguy/ansible-role-drush#variables-used-for-source-install-git

**Comment by ashabed** [comment]
@thom8 I had the same issue, adding `drush_keep_updated: yes` did not resolve the issue. I also tried setting `drush_force_update: yes` to no avail

**Comment by ashabed** [comment]
And I had the same issue on both Windows 10 and macOS Sierra. I'll post if I figure anything out.

**Comment by ashabed** [comment]
This information from the CHANGELOG may be helpful:

```
  * Removed now-unneccessary drush_keep_updated and drush_composer_cli_options vars.
  * Default to Drush version 8.1.10 (since we use the Phar-based install by default now).
```

**Comment by ashabed** [comment]
I'm not sure if there's a pure-vagrant-reload way of doing this, but this'll work:

1. Edit config.yml. Change `drush_version:` to the desired version (drush_version: "8.1.14" for this example)
2. vagrant ssh
3. cd /usr/local/bin 
4. sudo wget https://github.com/drush-ops/drush/releases/download/8.1.14/drush.phar
5. php drush.phar core-status # this confirms 'new' drush is working before replacing the old version
6. sudo mv drush.phar drush
7. sudo chmod +x drush
8. cd ~
9. drush --version #confirm new version

**Comment by pminf** [comment]
@thom8 `drush_keep_updated` seem's to have no impact. Drush has not been updated.

**Comment by thom8** [comment]
There's been some upstream changes to drush recently so it might be best to open an issue in the drush role itself -- https://github.com/geerlingguy/ansible-role-drush/issues

**Comment by pminf** [comment]
OK, I've created a new issue: https://github.com/geerlingguy/ansible-role-drush/issues/43 (because I don't know a way to move it)
