### ISSUE TITLE
Hyper-V issue

### ISSUE THREAD

**Issue by jestinijames** [geerlingguy/drupal-vm#1596]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.5
vboxmanage --version
5.1.22r115126
ansible 2.4.0.0

```

### Your OS

 - **Windows**  7

### Full console output

The hyper-v cmdlets for powershell are not available! Vagrant requires these to control Hyper-V. Please enable them in the "windows features" control panel and try again

### Summary

I have been trying to set up 'dupal-VM' on a pc with windows 7. One of the doucumntation that you have provided says that it is possible. 
So, I followed all the instructions until I typed 'Vagrant up'. There i get the above error.

A colleague suggested that I share my vdx or vdi file onto that pc and maually start the virtual box. IS this the right way to go about doing this? Can it be done? And what needs to be done next. Please advise
![untitled](https://user-images.githubusercontent.com/28772215/32213207-5b622ac6-be40-11e7-8235-818cea2da6f6.png)

**Comment by FinBoWa** [comment]
@jestinijames that is a vagrant isseue not a drupal vm issue. 

have you done what this says: 

"The hyper-v cmdlets for powershell are not available! Vagrant requires these to control Hyper-V. Please enable them in the "windows features" control panel and try again"

**Comment by FinBoWa** [comment]
also on the documentation on drupal vm has section on windows 7 http://docs.drupalvm.com/en/latest/getting-started/installation-windows/#windows-7-requires-powershell-upgrade

 have you reviewed all of the windows guides?

**Comment by geerlingguy** [comment]
@jestinijames currently Drupal VM only officially supports running with VirtualBox, and not any other virtualization provider, on Windows. That doesn't mean it can't or won't work, just that most people have the best experience using VirtualBox + Vagrant.

Closing this issue, though, in favor of centralizing any discussion around Hyper-V here: https://github.com/geerlingguy/drupal-vm/issues/1015

**Comment by jestinijames** [comment]
Hey sorry guys. I guess my question was not clear. I don't want to use Hyper-V. I want to disable it and let virtual box run instead. Every time Hyper-V is detected as the default. Is there a way to overwrite the default option?

**Comment by oxyc** [comment]
@jestinijames you should be able to set it using the `VAGRANT_DEFAULT_PROVIDER=virtualbox` environment variable
