### ISSUE TITLE
How do I update Virtualbox Guest Additions (guest version)

### ISSUE THREAD

**Issue by visages** [geerlingguy/drupal-vm#1597]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.30r118389
No Ansible (Windows OS)
```

### Your OS

 - **Windows** (7 SP1)

### Full console output

https://gist.github.com/visages/97fd20b23198171f0d38419a22985ee2#file-gistfile1-txt
### Summary

After my VM began to use very high CPU, I tried first to reboot machine and other basic maintenance tasks. No way.

So I updated Vagrant (2.0.0), VirtualBox (5.1.30), I destroyed existing boxes, updated DrupalVm and plugins. But I coudn't get any Vm mounted correctly (with default config.yml for testing purpose). Install stops with errors, and if I ssh in, only basic Debian is mounted. No Apache or other packages ... 

### Found errors 
_(various tries, at each step of updating)_
```
[drupalvm] GuestAdditions versions on your host (5.1.30) and guest (5.1.26) do not match.
...
vboxadd.sh: Starting the VirtualBox Guest Additions.

Could not find the X.Org or XFree86 Window System, skipping.
Job for vboxadd-service.service failed. See 'systemctl status vboxadd-service.service' and 'journalctl -xn' for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt

...

 drupalvm: Running ansible-playbook...
[DEPRECATION WARNING]: The use of 'include' for tasks has been deprecated. Use
'import_tasks' for static inclusions or 'include_tasks' for dynamic inclusions.
 This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: include is kept for backwards compatibility but usage is
 discouraged. The module documentation details page may explain more about this
 rationale.. This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion.
This feature will be removed in a future release. Deprecation warnings can be
disabled by setting deprecation_warnings=False in ansible.cfg.
 [WARNING]: file /vagrant/provisioning/roles/geerlingguy.apache-php-fpm/tasks
/configure-RedHat.yml is empty and had no tasks to include
ERROR! Unexpected Exception, this is probably a bug: 'module' object has no attribute 'SSL_ST_INIT'
to see the full traceback, use -vvv
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Last I updated to VirtualBox (5.2.0) ( without then without [that image](https://www.virtualbox.org/download/testcase/VBoxGuestAdditions_5.2.1-118447.iso) suggested on [VirtualBow download page](https://www.virtualbox.org/wiki/Downloads). Now the new error is : 

> Vagrant has detected that you have a version of VirtualBox installed
> that is not supported by this version of Vagrant. Please install one of
> the supported versions listed below to use Vagrant:
> 
> 4.0, 4.1, 4.2, 4.3, 5.0, 5.1

### Questions
Could you please recommend a set of Vagrant + VirtualBox + DrupalVM Debian8 box working smoothly together ?
Do the above errors show any other misconfiguration ? I've been used previous config for months and have no idea why it stopped working. 

Thank you

**Comment by visages** [comment]
As a temporary solution, I patched Vagrant as per[ Support for VirtualBox 5.2](https://github.com/hashicorp/vagrant/issues/9090).

So my config is now : 
```
$ vagrant -v
Vagrant 2.0.0

$ vboxmanage --version
5.2.0r118431

$ vagrant plugin list
vagrant-auto_network (1.0.2)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.9, system)
  - Version Constraint: > 0
vagrant-vbguest (0.15.0)

$ vagrant box list -i
geerlingguy/debian8    (virtualbox, 1.0.5)
geerlingguy/ubuntu1604 (virtualbox, 1.1.6)
```
Vagrant doesn't complain anymore for Virtualbox compatibility, but I still run in the same errors, whichever version installed. Errors below, [full output here](https://gist.github.com/visages/ec81e00e1715b3ab380f49e0df09fb68)

```
$ vagrant up --provider virtualbox
...

VirtualBox Guest Additions: Look at /var/log/vboxadd-setup.log to find out what went wrong
VirtualBox Guest Additions: Running kernel modules will not be replaced until the system is restarted
VirtualBox Guest Additions: Starting.
VirtualBox Guest Additions: modprobe vboxsf failed
An error occurred during installation of VirtualBox Guest Additions 5.2.1. Some functionality may not work as intended.
In most cases it is OK that the "Window System drivers" installation failed.
Job for vboxadd-service.service failed because the control process exited with error code. See "systemctl status vboxadd-service.service" and "journalctl -xe" for details.
Unmounting Virtualbox Guest Additions ISO from: /mnt
==> drupalvm: Checking for guest additions in VM...
    drupalvm: The guest additions on this VM do not match the installed version of
    drupalvm: VirtualBox! In most cases this is fine, but in rare cases it can
    drupalvm: prevent things such as shared folders from working properly. If you see
    drupalvm: shared folder errors, please make sure the guest additions within the
    drupalvm: virtual machine match the version of VirtualBox you have installed on
    drupalvm: your host and reload your VM.
    drupalvm:
    drupalvm: Guest Additions Version: 5.1.26
drupalvm: VirtualBox Version: 5.2

...

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=900,gid=900 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

I'm afraid I got lost, and don't know how to proceed. Any tip is warmly welcome ! Thank you.

**Comment by visages** [comment]
**Summary** : I had a working config (Vagrant + VirtualBox + Debian8 box) o two Windows 7 machines. On one of these machines, It stopped working, and I never achieved to get a clean install again. The warning which always comes back behind install errors is that  _GuestAdditions versions on your host (5.2.0) and guest (5.1.26) do not match_ . I won't write down the full story of my tries to get a working config. 

My ultimate config has all components with most recent stable release : 
```
$ vagrant -v
Vagrant 2.0.1
$ VBoxManage -v
5.2.0r118431
$ vagrant plugin list
vagrant-auto_network (1.0.2)
vagrant-hostsupdater (1.0.2)
vagrant-share (1.1.9, system)
vagrant-vbguest (0.15.0)
vagrant-winnfsd (1.3.1)

.Net Framework 4.7 (Win 7 SP1)
```
Install stops on : 
_/sbin/mount.vboxsf: mounting failed with the error: No such device_ 
or :
_An error occurred in the underlying SSH library that Vagrant uses.
The error message is shown below. In many cases, errors from this
library are caused by ssh-agent issues. Try disabling your SSH
agent or removing some keys and try again._

(depending on how many tries to provision before destroying and starting from scratch).

[Full debug output](https://gist.github.com/visages/6af9b61a92190a4eed3161e6e7a15a3b#file-gistfile1-txt)

[Short output](https://gist.github.com/visages/bc56b83004602e5f5831d656fb23f2da#file-gistfile1-txt
)

How do I update Virtualbox Guest Additions (guest version), and would that be enough to get my setup fine again ? At the moment, `Guest Additions Version: 5.1.26` corresponds to the historical Vbox I installed at first glance, while in Oracle folder, the version is `5.2.1-118447`.

Thank you so much.

**Comment by geerlingguy** [comment]
@visages - My best recommendation would be to stick to a known-working version of VirtualBox (5.1.26 is the last version I have been using that I know works and is what my base boxes are built on currently).

I'm going to update my base boxes to work with newer versions, but I've been waiting for a more stable 5.2.x release before doing so.

**Comment by visages** [comment]
@geerlingguy Thank you Jeff. Any idea of your timing to do so ? No commitment of course :) just because I'm about to switch to another environment. 

I'm so f*** tired of Windows as base Os for dev, that I may build a Linux VM with all dev tools, and run nested VM's inside. I believe my hardware would support it.

**Comment by visages** [comment]
@geerlingguy Thank you !
