### ISSUE TITLE
Support Headless Chrome without Selenium/Java

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1598]
### Issue Type
 - Feature Idea

### Summary

Currently, the only convenient way of installing Headless Chrome for automated testing is via the Selenium ansible role. This is a fairly heavy role, since it also pulls down Java, which considerably slows provisioning.

It would be nice if there were a way to install Headless Chrome independently of Selenium and/or Java.

**Comment by thom8** [comment]
@danepowell chrome installed without the java dependency in `beet/box` using this role -- https://github.com/cmprescott/ansible-role-chrome

Was mainly about reducing the size of the base VM -- https://app.vagrantup.com/beet/boxes/box

Java adds a quite a bit of weight..

**Comment by danepowell** [comment]
Sweet, that seemed pretty easy, I just added this to my `config.yml`:
```yaml
installed_extras:
  - chrome
```

I guess the only question is whether to add this to DrupalVM's set of provisioning roles for efficiency's sake.

**Comment by jayappnovation** [comment]
hey @danepowell i put the "chrome" into the installed_extras sections and ran "vagrant provision"...what are the next steps?

**Comment by thom8** [comment]
@jayappnovation it's preinstalled in the `beet/box` base image.

So if you add >>

```
vagrant_box: beet/box
workspace: "/beetbox/workspace/{{ php_version }}"
```

You can actually remove everything from `installed_extras` as it's already there.

**Comment by thom8** [comment]
linking -- https://github.com/acquia/blt/issues/1986

**Comment by danepowell** [comment]
If you want to use Ubuntu, I think it's enough to add chrome to installed_extras and re-run vagrant provision. If that doesn't work, I'm not sure what to tell you :confused:

**Comment by thom8** [comment]
Don't think `chrome` is a valid option for `installed_extras` it's currently installed via the `selenium` role -- https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/playbook.yml#L95

**Comment by thom8** [comment]
Just to explain, the `beet/box` base image is built using the same role so when it's re-run it doesn't need to actually do anything as it was already provisioned when the base box was created.

It's a bit like a prebuilt docker image in that respect.

However, it's important that it does use exactly the same roles as it would potentially cause conflicts.

**Comment by jayappnovation** [comment]
ok thank you guys I will check and let you know ;)

**Comment by geerlingguy** [comment]
It might also be nice to get the upstream `arknoll.selenium` role to allow just installing/configuring Google Chrome / headless. Or we could add an `installed_extra` option to just install google chrome using that Ansible Chrome role https://github.com/cmprescott/ansible-role-chrome ... I'd be willing to accept PRs either way. I haven't been using Selenium on the past couple projects I've been working on, so it hasn't been as pressing over the past 6 months for me (tsk, tsk!).

**Comment by geerlingguy** [comment]
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!
