### ISSUE TITLE
How to increase post_max_size?

### ISSUE THREAD

**Issue by ssteigen** [geerlingguy/drupal-vm#1599]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.7
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (7 Professional)

### Summary

I'm trying to use Adminer to upload a database export that is 70MB. Since the post_max_size is set to 32M, I'm getting the following error when I try to import the file:

```
Too big POST data. Reduce the data or increase the 'post_max_size' configuration directive.
```

*Things I've Tried*

* Adding `php_post_max_size: "100M"` to `config.yml` and re-provisioning
* Modifying line 62 of `provisioning\roles\geerlingguy.php\defaults\main.yml` from `php_post_max_size: "32M"` to `php_post_max_size: "100M"` and re-provisioning
* SSH-ing into the VM and changing `post_max_size: "32M"` to `post_max_size: "100M"` for the following files (and executing `sudo service apache2 restart` to reboot the server):
  * `/etc/php/7.1/apache2/php.ini`
  * `/etc/php/7.1/cli/php.ini`
  * `/etc/php/7.1/fpm/php.ini`

**Comment by ssteigen** [comment]
@thom8 Thanks for the reply.

I did try that, but even after provisioning the box, the old settings were still in effect.

I've discovered that if I destroy and rebuild the box, my settings will take effect.

Any idea how I can get the settings to take effect without destroying the rebuilding the box?

**Comment by thom8** [comment]
you could try `vagrant reload --provision` which basically restarts the VM, then runs the provisioning.

Otherwise something is not right with your setup if the config files aren't updated after a normal provision.

**Comment by FinBoWa** [comment]
Just to note to @ssteigen that by default apache is passing requests to php-fpm so you should restart PHP-FPM service if you manually edit the php.ini file not apache the apache service.

**Comment by geerlingguy** [comment]
@ssteigen and in addition to what @thom8 said, if you update your config.yml (or local.config.yml) file, you can also run `vagrant provision` on a running VM, and it should do all the correct steps to modify php.ini and restart php-fpm automatically.

I'm closing this out as I think between @thom8, @FinBoWa, and this response, you should be covered for making changes more dynamically.
