### ISSUE TITLE
DrupalVM on Windows Host - Ansible Playbook Not Found

### ISSUE THREAD

**Issue by tashbaugh** [geerlingguy/drupal-vm#160]
Whenever I attempt to execute vagrant up, the process fails stating that it "Cannot find Ansible playbook."

I can do the following and can see that playbook.yml exists:
vagrant ssh
cd /vagrant
cd provisioning/
ls

What am I doing wrong?

**Comment by tashbaugh** [comment]
I had previously downloaded a zip of DrupalVM on June 29th and on a hunch, destroyed my vm and used that zip as the source for DrupalVM. This time when I ran vagrant up the error did not occur.

It seems to me that a breaking change may have been introduced between June 29th and today.

Let me know if I can help any further with this error.

**Comment by geerlingguy** [comment]
Interesting... it might be the version of the JJG-Ansible-Windows script that's included with provisioning. I'll take a quick look.

**Comment by geerlingguy** [comment]
Ah, found the issue — it was introduced in #147; I am committing a fix now, please try latest master version of Drupal VM and see if this is fixed (see commit after this comment for the fix).

**Comment by tashbaugh** [comment]
I also noticed that the version of Ansible installed was 1.9.1 whereas the documentation in the readme file suggests that it should be version 1.9.2. I'm not sure if that matters or not.

**Comment by geerlingguy** [comment]
@tashbaugh - For that, I'll need to update my Packer box builds so they have the latest version of Ansible. Haven't had time to do so in the past week or so, but I will soon. But it shouldn't have any negative impact, I don't think.

**Comment by tashbaugh** [comment]
@geerlingguy that fix worked. Thank you for the quick response!

**Comment by geerlingguy** [comment]
@tashbaugh - No problem!
