### ISSUE TITLE
Custom Git config in VM.

### ISSUE THREAD

**Issue by jnettik** [geerlingguy/drupal-vm#1600]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.10r112026
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Apr  4 2017, 08:46:44) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (10.11.6)

### Summary

I didn't see anything in the docs that described how to do this, but I was wondering if there was a built in way to get my global Git config (user info, aliases, etc.) available inside the VM. Currently, the only thing I leave the VM for is to run Git commands. Thank you in advance for any help!

**Comment by fubarhouse** [comment]
You could tack on Jeff's dotfiles role:
* https://github.com/geerlingguy/ansible-role-dotfiles 

Not a practical solution, but it would do the trick.

**Comment by oxyc** [comment]
Currently there's no such feature and I don't think we'll add it either. It's fairly easy to add it with a custom post-provision shell script, task file, or like @fubarhouse suggested, playbook. You can refer to the [documentation](http://docs.drupalvm.com/en/latest/extending/scripts/) for how to set it up.
