### ISSUE TITLE
Initial download and installation of all geerlingguy/ vagrant boxes fail.

### ISSUE THREAD

**Issue by Justin-Lloyd** [geerlingguy/drupal-vm#1605]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.1
VirtualBox 5.2.0r118431
```

### Your OS
 - Windows 10 (version 1703 build 15063.674)

### Full console output
https://gist.github.com/Justin-Lloyd/a1f370a9c0d01cb82c02663329b368e4

### Summary
Initial download and installation of all geerlingguy/ vagrant boxes fail. Download and installation of multiple vagrantcloud boxes from other accounts succeeds.

**Comment by ek9** [comment]
I'm having similar problem with no geerlinguy's boxes being accessible:

```
Vagrant 2.0.1
VirtualBox 5.2.0 r118415
```

```
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/debian9' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
The box 'geerlingguy/debian9' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Vagrant Cloud, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://vagrantcloud.com/geerlingguy/debian9"]
Error: The requested URL returned error: 401 Unauthorized
```

I have tried `geerlingguy/ubuntu1604`, `geerlingguy/debian8`, `geerlingguy/debian9` with same results:

```
Error: The requested URL returned error: 401 Unauthorized
```

I believe there is some problem with accessing the `.box` files where they are stored. This prevents any users from using the project, unless they have cached version of the box downloaded already.

**Comment by ek9** [comment]
I've found a way to solve this. It seems that a login to Vagrant cloud is now necessary (`vagrant login` command). After logging in I was able to access and download the vagrant boxes successfully.

**Comment by geerlingguy** [comment]
@ek9 - Strange, that _shouldn't_ be necessary.

 I wonder, though, if it might be a cert issue on your system, or a proxy/firewall issue on your network? Check out these two issues:

  - https://github.com/hashicorp/vagrant/issues/5391
  - https://github.com/npm/npm/issues/10037

Also, sometimes the server is just not responding correctly. Try again and see if it's still not working.

**Comment by oxyc** [comment]
@ek9 @Justin-Lloyd are you still seeing this issue?

**Comment by geerlingguy** [comment]
Going to close this out now, as there are no more reports of it happening.
