### ISSUE TITLE
Provisioning fails on Fedora 26 with vagrant-cachier installed

### ISSUE THREAD

**Issue by cristiroma** [geerlingguy/drupal-vm#1606]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.1.26r117224
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/cristiroma/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Sep  5 2017, 08:53:59) [GCC 7.1.1 20170622 (Red Hat 7.1.1-3)]

```

### Your OS

 - **Linux** (version)

### Full console output

https://gist.github.com/cristiroma/5d362ef2d12c2d4393689c1ed478fbec

```
Stderr from the command:

mesg: ttyname failed: Inappropriate ioctl for device
mount.nfs: requested NFS version or transport protocol is not supported

```

### Summary

When `vagrant-cachier` plugin in installed on the host, Vagrant is trying to mount the folder inside the system but the mount parameters to the mount (defaults to `vers=3,udp` which do not work on Fedora 26).

I think there should be a documentation to mention this incompatibility or a global option to disable `nfs_udp` option at the global level, not per mount.

**Comment by denics** [comment]
I confirm a similar failure if you are using Ubuntu as guest and OSX as host. I did not find a solution yet, a part from disabling vagrant-cachier plugin.

**Comment by fubarhouse** [comment]
It should be noted that the project is marked as unmaintained.
* https://github.com/fgrehm/vagrant-cachier 

I suspect the problems are coming from more recent MacOS updates.

**Comment by oxyc** [comment]
I guess we could either add a `vagrant_nfs_udp: false` variable that we use for all synced folders as the default. As there's so few `vagrant-cachier` users and it's a bit buggy, maybe we just force it to TCP though.

To fix your build for now I think you can modify the synced folder configs in a `Vagrantfile.local` with something like this as an example https://github.com/geerlingguy/drupal-vm/pull/284#issuecomment-223781829

**Comment by oxyc** [comment]
Fixed
