### ISSUE TITLE
Impossible to install modules with "libraries" folder dependencies

### ISSUE THREAD

**Issue by ludal74** [geerlingguy/drupal-vm#1607]
- Bug Report / Support Request

### My Environment
VirtualBox 5.1.26 
Vagrant 1.9.7
Windows 10

I'm building the VM using composer base (drupal_build_composer_project=true) and adding external libraries like imagesloaded or masonry as composer dependencies but the composer doesn't create the libraries folder.

**Comment by oxyc** [comment]
I don't believe this should be created by Drupal VM, but rather the composer project. There's an issue about it here https://github.com/drupal-composer/drupal-project/issues/228.

I haven't read the issue but I guess this hasn't been entirely established yet https://www.drupal.org/project/drupal/issues/667058
