### ISSUE TITLE
Drupal Console is not getting installed even when set in installed_extras

### ISSUE THREAD

**Issue by rpkoller** [geerlingguy/drupal-vm#1608]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
VirtualBox 5.2.0r118431
ansible 2.4.1.0
  config file = /Users/myuser/.ansible.cfg
  configured module search path = [u'/Users/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.1.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Sep 25 2017, 09:53:17) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS
 - **macOS** (10.11.6 (15G17023))

### Summary
I've used DrupalVM version `4.7.0`. In the `config.yml` file I have changed the `vagrant_ip`, then set `drupal_build_composer`to `true`and changed `drupal_build_composer_project`to `false`and finally removed the comment out for `drupalconsole` in `installed_extras`. But Drupal Console isn't installed right from the start. When I try to call it inside the VM after provisioning is done I get:

```
vagrant@drupalvm:/var/www/drupalvm/drupal/web$ drupal version

 [ERROR] Drupal Console is not installed at:
         /var/www/drupalvm/drupal

You must execute the following composer commands:

 composer require drupal/console:~1.0 --prefer-dist --optimize-autoloader
```
So I have to require and install it subsequently. I've checked the docs http://docs.drupalvm.com/en/latest/extras/drupal-console/ but the only thing stated is to uncomment `drupalconsole`in `installed_extras`, what I did. Have I missed an important detail or is that a misbehavior? Best regards Ralf

**Comment by geerlingguy** [comment]
@rpkoller - Thanks for the report—I'll double-check this as it was at least working the last time I tested a few weeks ago. Note that Drupal Console (along with Drush) recommends installing it as a Composer Dependency of the Drupal project you're building, at least in the ideal scenario.

**Comment by rpkoller** [comment]
Thanks for getting back and sorry for the late reply. So you mean the best practice would be simply adding 

```
"drupal/console": "~1.0"
```

to the `require` section of the Composer file like Drush is in the `extra` section? Thanks r.

**Comment by thom8** [comment]
@rpkoller I understand this is the only supported installation method now see - https://docs.drupalconsole.com/en/getting/composer.html

**Comment by oxyc** [comment]
> Each one of your site projects should have it's own DrupalConsole installed. This is done using Composer.+
>
> Notes: Starting on RC releases DrupalConsole must be installed per site. Install Drupal Console using composer global require is no longer supported.

So we need to update the docs mentioning that each install needs to require it.

**Comment by rpkoller** [comment]
@thom8 oh true, sorry for the late reply

@oxyc would it might make sense to update the Drush part as well? Checked their docs and they recommend to require Drush as a dependency on a per project basis as well as: http://docs.drush.org/en/master/install/

**Comment by Debasish303** [comment]
@rpkoller Are you able to install drupal console with drupal-vm. I have followed the approach like yours but experiencing same issues.

**Comment by rpkoller** [comment]
@Debasish303 sorry for the late reply. well i am stuck with another issue beforehand right now in another thread which prevented me to focus on the last bit with drush and console to understand how things work. but i got it installed by setting it in the `installed-extras`as well as the `composer.json`. that way it gets installed for sure.

**Comment by geerlingguy** [comment]
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!
