### ISSUE TITLE
DrupalVM + NodeSass + Node.js >= 8.0.0 fails to compile

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#1609]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.1
VirtualBox 5.1.30r118389
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS
 - **macOS** (10.13.1)

### Full console output
https://gist.github.com/aweingarten/830f1277ba5b8a56dc85f2742703ef47

### Summary
Node-sass install fails with node8.x and drupalvm.  A node tool that we are using requires node.js 8.x. I updated the version of node js in config.yml:
`nodejs_version: "8.*"`.  

Confirmed that 8.9.1 is installed.
```
node --version
v8.9.1
```

When I attempt to run `yarn install` or `npm install` I get an error in node gyp:
```
  rm -rf "Release/sass.a" && cp -af "Release/obj.target/src/sass.a" "Release/sass.a"
cp: preserving permissions for 'Release/sass.a': Operation not permitted
src/libsass.target.mk:191: recipe for target 'Release/sass.a' failed
make: Leaving directory '/var/www/wfm8/docroot/themes/custom/freerange/node_modules/gulp-sass/node_modules/node-sass/build'
make: *** [Release/sass.a] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/www/wfm8/docroot/themes/custom/freerange/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Linux 4.4.0-62-generic
gyp ERR! command "/home/vagrant/.nvm/versions/node/v8.9.1/bin/node" "/var/www/wfm8/docroot/themes/custom/freerange/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/www/wfm8/docroot/themes/custom/freerange/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.9.1

```

It looks like something changes with the way that permissions are handled, I'm guessing that NFS + node 8.91 + gyp = sadness.

running `sudo -i yarn install` works.  Don't know why though.

**Comment by FinBoWa** [comment]
Could you just build or watch filesystem changes for them on your host not the box. 

Also note that there nfs issues with vagrant and 10.13.1 high sierra see issue https://github.com/geerlingguy/drupal-vm/issues/1547

**Comment by aweingarten** [comment]
@FinBoWa,
The reason we are using drupalVM is to normalize node.js builds for developers.  That way the differences in their env and config don't cause problems.  For that reason we can't build on the host.

I don't think the high-sierra issue is the problem here as it was a problem before high-sierra.  Also I tested node 4 and 6 inside the VM without issue.   There is something unique to 8

**Comment by FinBoWa** [comment]
Have you installed nvm on the box as this refers "/home/vagrant/.nvm/versions/node/v8.9.1/bin/node". 

Didnt frankly see any references to nvm on drupalvm or https://github.com/geerlingguy/ansible-role-nodejs

**Comment by aweingarten** [comment]
@FinBoWa You have sharp eyes!
I was experimenting with the native Node install via the config.yml by setting `nodejs_version: "8.x"
` as well as NVM to see if there was any difference.  There was not.  Using NVM also let me test minor versions of node 8.x.  All versions of 8.x had the same issue.  In both cases version of node < 8 work with node-sass fine.  In both cases node  >= 8 fails.  

I also tested setting `npm_config_unsafe_perm` to true.  No dice.  Going to play with changing the "nodejs_install_npm_user" as well but given that the issue is on yarn/npm install rather than the actual provisioning of the box I am skeptical.  

So far the only work around I have found is to run `sudo -i yarn install` which feels wrong.

**Comment by aweingarten** [comment]
Tested `npm install --unsafe-perm` no luck

**Comment by aweingarten** [comment]
okay I dug in some more it seems like one of the dependencies in my composer.json had a dependency on an older version of node-sass that forced yarn and npm to download and compile the old version of node-sass.  Then when it tried to compile it failed due to NFS.  The clue here was that NPM/yarn should have just downloaded the binary.  The fact that node-gyp was being run at all was a huge clue something was wrong!
