### ISSUE TITLE
What versions to use?

### ISSUE THREAD

**Issue by Bertjuh** [geerlingguy/drupal-vm#1610]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.26
DrupalVM 4.7.0
```

### Your OS

 - **Windows** 7

### Summary
First off I'd like to thank you for this great piece of software. I'm really looking forward to working with this. 

But as I just started yesterday, I ran into some problems. When I downloaded all the latest versions as shown in your quick start guide, the vagrant up throws errors. When googling for a solution to these errors, I learned that using the lastest version is not always the best option. So I stuck with the same environment some guy on some website said that he had no issues with (after installing noumeros combinations.) 

So, is it an idea to keep a record of the latest stable combination of versions of the three (Vagrant, VirtualBox and DrupalVM) in your quick start guide? 

FYI: with my current environment the problems I encountered are solved when I do the following:
- use vagrant-hostmanager instead of vagrant-hostsupdater
- vagrant reload --provision after the first time vagrant up ends in an error: 
TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] fatal: [wiskundeoptui]: FAILED! => {..}

Thanks,
Bart

**Comment by geerlingguy** [comment]
Note that I need to update my base boxes to work better out-of-the-box with VirtualBox 5.2.0 (https://www.virtualbox.org/wiki/Downloads) — however, there are some caveats around the 5.2.0 release so I'm holding off until 5.2.1 is released.

Also, Windows 7 support is difficult at best, so I'd highly recommend upgrading to Windows 8 or 10 for better support across the board (though I have a working build on Windows 7 still, so I do know it works with the combination you're using at least—which you, I think, have proved too :D ).

**Comment by Bertjuh** [comment]
Thans for your response. Unfortunately upgrading Windows is not an option as the University I work for does not allow that. My set up works great now. Perhaps other newbs with Win 7 like me now can find this thread and get started a bit more easily. Thanks! And keep up the good work Jeff.
