### ISSUE TITLE
Drupal VM fails to build on VMWare 10 with geerlingguy's base box

### ISSUE THREAD

**Issue by karudonaldson** [geerlingguy/drupal-vm#1612]
### Issue Type
 - Bug Report / Support Request

### Your Environment
Vagrant 2.0.1
VMWare Fusion 10
(with vagrant vmware plugin latest version released Nov 2017)

### Your OS
Mac OS X High Sierra 10.13.1 17B48

### Full console output
Steps to reproduce:
clone the repo, copy files:
example.config.yml to config.yml
example.drupal.composer.json to drupal.composer.json
Run `vagrant up`

Console output:
https://gist.github.com/karudonaldson/bb80efa2829cab6479b611bbb5bbad7b

I ssh into the vm, correct python installation by running:
`wget https://bootstrap.pypa.io/ez_setup.py -O - | sudo python`

exit from the ssh session and run:
`vagrant provision`

Then I get error output:
https://gist.github.com/karudonaldson/b5930192a4e336d51815542a83c11357

That's about the point I decided not to debug any further and report it :)

**Comment by bulletproofsamples** [comment]
Karu,  Sorry to reach out to you this way, but haven't been able to find your information anywhere else.  Alex from Bulletproof samples gave me your name.  we are the new owners and need to talk with you about the web site.
i can be reached at dale@bulletproofsamples.com

**Comment by thom8** [comment]
@karudonaldson any chance you can try using virtualbox? the `vmware` box might not be up to date.

**Comment by karudonaldson** [comment]
Virtualbox is too slow, VMware is slightly better  you just can’t go past native Linux.  I use laravel valet for OS X and would never look back

**Comment by thom8** [comment]
@karudonaldson have you considered using Docker? It has both speed an isolation.

**Comment by karudonaldson** [comment]
I was using docker in conjunction with Pantheon for a bit.  Just have a preference for "valet" because it's as fast and basic.  Have you used valet?

**Comment by thom8** [comment]
@karudonaldson I haven't to be honest but I have "special" needs and require isolation with the various projects I deal with. Anything that requires a web server on the host just isn't viable in my case.

**Comment by geerlingguy** [comment]
Yeah, the VMware box is hopelessly outdated at this point... I have had _so_ much trouble maintaining it in the past, _and_ I've invested about $500 of my own money continually buying new versions, and the (expensive IMHO) VMware connector plugin for Vagrant, and _I don't even use it myself!_

So unless Vagrant starts making that plugin free, and VMware stops breaking all my builds every new major version—I'm not sure if I'm ever going to build a new version of the VMware base box. It might be more fruitful to find another more up to date base box for VMware.

**Comment by geerlingguy** [comment]
Anyways, looking at the install failure itself, that issue could be caused by at least a dozen different things (including permissions, mysql issues, configuration issues, etc.).

If you do a `vagrant destroy -f` to destroy it completely, then `vagrant up` again, does it error out the same way?

**Comment by karudonaldson** [comment]
Hey Jeff, I did destroy and up the vm several times which progressed a bit further each time for sure but in all fairness, it's really a waste of time to maintain this when the factors out of our control keep changing.

Thanks anyway.
