### ISSUE TITLE
Copy Error: Permission denied at task [geerlingguy.drupal]

### ISSUE THREAD

**Issue by zoig** [geerlingguy/drupal-vm#1614]
### Issue Type

 - Bug Report / Support Request
 
### Your Environment

```
Vagrant 2.0.1
Hyper-V Manager Version: 10.0.16299.15
```

### Your OS

  - **Windows 10 Pro Version 1709 OS Build 16299,64**

### Full console output

  - [PS DrupalVM-Output](https://gist.github.com/zoig/3a1ce41689036600aa8b33962158894b)

### Summary

Changes from default.config.yml to [config.yml](https://gist.github.com/zoig/e9fd299b915847f23fca8079978abf26) as I try to create a dev. environment for an organization with social-template.
The problem seems to be the change of the drupal distribution at line 78, as it reproducibly stops at the copy-process of the .git-directories of the contrib-modules link-css and r40321.
If I copy the directory by logging into the vagrant machine and do the copy process by hand, I can not seem to be able to pick up AFTER the copy process with either
`vagrant reload --provision` or `vagrant provision` 
Sadly I am not proficient enough to interpret 
`--limit @/vagrant/provisioning/playbook.retry`
correctly.
What should I do? All help appreciated.

**Comment by oxyc** [comment]
Currently Drupal VM does not officially support Hyper-V. Did you follow the steps listed here https://github.com/geerlingguy/drupal-vm/issues/1015#issuecomment-263227137?

I'll close this issue in favor of centralizing any discussion around Hyper-V at #1015.
