### ISSUE TITLE
Help to start off with Varnish

### ISSUE THREAD

**Issue by artatum** [geerlingguy/drupal-vm#1621]
### Issue Type
 - Support Request

### Your Environment 
```
Vagrant 2.0.1 (impossible to get more)
```
### Your OS
 - **Windows** (7)

### Summary
Hi
I dont know where I can access the varnish admin page. I tried drupalvm.test:81 but it simply display my website homepage. I searched also for some default.vcl in the VM but couldn't find any. Could you tell me the first steps to begin please ?

**Comment by thom8** [comment]
@artatum Varnish doesn't have and admin console see https://stackoverflow.com/questions/23316454/how-do-i-access-varnish-admin-area

**Comment by artatum** [comment]
Thx for the link. Sorry for the duplicate...
