### ISSUE TITLE
Setup problem (?)

### ISSUE THREAD

**Issue by begrafx** [geerlingguy/drupal-vm#1625]
### Issue Type

 - Bug Report / Support Request
 
### Your Environment
typing results from the other computer --

Vagrant 2.0.1
VirtualBox: 5.2.2r119230
Ansible: "-bash: ansible: command not found"

```

```

### Your OS

 - **macOS** (Sierra)

### Summary

I installed Drupal VM per your video on YouTube, it appeared to have completed the install correctly, however when I go to a new browser tab and attempt to access either "desktop.drupalvm.dev" or "drupalvm.dev" I get a message that says, 

This site can't be reached 
this site on the company, organization or school intranet has the same URL as an external website. 

Try contacting your system administrator. 
ERR_ICANN_NAME_COLLISION

I do also have MAMP 4.2 running on the same machine.

**Comment by begrafx** [comment]
As further information, while I'm not able to access the site/dashboard, from the terminal window, I AM able to see that DRUSH is working, responding that it is version 8.1.15

**Comment by begrafx** [comment]
OK, further update:
Manually installed Ansible
"vagrant destroy"
"vagrant up"
Drupal VM starts
The "play recap" for the Drupal VM Startup states; "OK=219  changed=93  unreachable=0  failed=0"
Attempted to access dashboard.drupalvm.dev and drupalvm.dev
received the same error as above.

**Comment by fubarhouse** [comment]
@begrafx,

Try destroying the box, and renaming all references with `.dev` to `.test` in the config file.

Then, `vagrant up` and report back!

**Comment by thom8** [comment]
'local.drupalvm.com' should also resolve to the default IP if you're still having problems.

**Comment by webprogrammierer** [comment]
local.drupalvm.com works but how can I read adminer.drupalvm.dev and dashboard.drupalvm.dev and so on ...?

**Comment by fubarhouse** [comment]
Try using the `.test` domain suffix.

Like I said previously, make sure you aren't using `.dev` in your `config.yml` file, and if you are you should probably run `vagrant destroy && vagrant up` to rebuild the vm.

**Comment by webprogrammierer** [comment]
How to solve it:

You have to change the Windows hosts file in \Windows\System32\drivers\etc.: Replace all ".dev" with ".test".
You have to change drupalvm.dev to drupalvm.test
You have to change all other projects from .dev to .test
You have to provision the Drupal VM:
  vagrant up
  vagrant provision
Call dashboard.drupalvm.test afterwords. Should work then.

**Comment by fubarhouse** [comment]
@webprogrammierer,

Don't forget about changing your virtual hosts to suit.

Where the files are can change from system to system - I can't vouch for windows but linux you can generally find them in one of the following paths:
* `/etc/nginx/sites-*`
* `/etc/httpd/sites-*`
* `/etc/apache2/sites-*`

**Comment by thom8** [comment]
@fubarhouse this should be taken care of by the provisioning process - `vagrant provision`

**Comment by geerlingguy** [comment]
@thom8 is correct — I'm guessing @begrafx might have been confused by following the older YouTube video instructions, and maybe put the `.dev` domain somewhere causing all those to be set in the hosts file.

Just make sure the `config.yml` file is using the `.test` domain suffix and the do a `vagrant down` and `vagrant up` (or nuke it with `vagrant destroy -f` then `vagrant up` to rebuild). The hostsupdater should set the .test domain correctly then.

Closing this out as I don't see anything in the docs or default configuration that's using `.dev` anymore.
