### ISSUE TITLE
Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by matjes63** [geerlingguy/drupal-vm#1628]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (10 Pro)

### Full console output

```
vagrant up failed with this error:
    drupalvm: /vagrant => C:/drupalsites/drupalvm/drupalvm1/drupal-vm
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=900,gid=900 vagrant /vagrant

The error output from the command was:

/sbin/mount.vboxsf: mounting failed with the error: No such device
```

### Summary

vagrant up fails with this message:

```
/sbin/mount.vboxsf: mounting failed with the error: No such device
```

I found that this error happens only with the latest build of virtual box for windows: 
VirtualBox-5.2.2-119230-Win

I went back to an older version of virtualbox and the error disapeared:
VirtualBox-5.1.30-118389-Win

So this problem happend only with the latest version of virtual box.
Thought I should report this. I did some unisntalls and reinstalls of the version 5.2.2 first, and  only finally another uninstall and then installing 5.1.30. So I am pretty sure this solved my problem.

**Comment by geerlingguy** [comment]
@matjes63 - The temporary fix is to stick with VirtualBox 5.1.x (like you found). I am working on updating my base boxes for 5.2.x, but until then, can you also see if you have all the recommended Vagrant plugins installed—most notably `vagrant-vbguest` (use `vagrant plugin list` to check).

**Comment by geerlingguy** [comment]
I've updated all my boxes to work with VirtualBox 5.2.4+, and have tested them all on my Mac at least, finding no issues.

I haven't been able to build a test VM on my Windows 10 laptop (it's in my office and I'm off this week), but I wonder if you uninstall VirtualBox, reinstall 5.2.4 (latest), and try again, if it might work this time.

**Comment by geerlingguy** [comment]
I'm going to close this since I think the new boxes should help. Let me know if that's not the case!

**Comment by kentr** [comment]
For me, this problem appeared even though `vagrant-vbguest` is installed and the guest additions installed into the box are reportedly the latest version.

Updating the box solved the problem for me (with `vagrant box update`).
