### ISSUE TITLE
RabbitMQ role

### ISSUE THREAD

**Issue by kimkennof** [geerlingguy/drupal-vm#1632]
### Issue Type

 - Support Request
 - Documentation Report

### Your Environment

```
Vagrant 1.9.5
VirtualBox 5.1.28r117968
ansible 2.2.0.0
  config file =
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.6 (16G1036))

### Summary

Hey guys,

I'm required to use a RabbitMQ instance for an application, and I'm trying to figure out how to add a new role to the DrupalVM, which is not in it's own repository...

So I would be required to add it to the `vendor` directory using Composer (preferably) and make DrupalVM include this role upon provisioning.

I have found an example RabbitMQ role in Jeff's repo's, but it's quite limited in provided options, so I prefer the https://github.com/jebovic/ansible-rabbitmq role with more exposed options.

Can someone please guide me in the right direction on how to succeed? I've also flagged this issue as a Documentation request because I feel other people might be interested in this use-case as well.

Thanks in advance.

Kim

**Comment by fubarhouse** [comment]
* Download DrupalVM
* Add your role to `provisioning/jebovic.rabbitmq/`
* include a post provision script with `post_provision_tasks_dir: "./tasks/custom-post.yml"`.
* include a tasks file for the configured script such as at the bottom of this message.
* add `rabbitmq`to `installed_extras`
* add variables to `config.yml` as required.

````
- name: Include jebovic.rabbitmq role
  include_role:
    name: jebovic.rabbitmq
  when: '"rabbitmq" in installed_extras'
````

I've got my own fork which includes a Go role here, if you wanted a peek at a working example: https://github.com/fubarhouse/drupal-vm

**Comment by kimkennof** [comment]
Thanks for clarifying this!

**Comment by geerlingguy** [comment]
@fubarhouse aww, you didn't use my rabbitmq role! https://github.com/geerlingguy/ansible-role-rabbitmq :D

But yes, this would be the preferred way of adding roles that aren't in the central/master Drupal VM config. Right now RabbitMQ isn't used enough in the Drupal world that I'd consider adding it to the core Drupal VM set of roles... but that could change someday!

Thanks for posting, and thanks for the help @fubarhouse !

**Comment by fubarhouse** [comment]
No problems, I only specified that role due to the OP specifying it.

I happen to prefer your roles, unless of course they're not quite what I'm after - then I usually write my own :P
