### ISSUE TITLE
how to setup VM with drupal-multisite (same codebase and different DB),

### ISSUE THREAD

**Issue by jating-appno** [geerlingguy/drupal-vm#1633]
### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** 

### Full console output

failed: [drupalvm2] (item=drupal/devel:1.x-dev) => {"failed": true, "item": "drupal/devel:1.x-dev", "msg": "1/2: https://packages.drupal.org/8/drupal/provider-2016-2$a852048b62ae8fd2187de1f1facf5c2d4dfdc20011f9f237d20ac8b062b22802.json 2/2: https://packages.drupal.org/8/drupal/provider-2017-3$388efe29189d36c6bf50fd8630650abba109830834cb29bd3915cc859a97065a.json Finished: success: 2, skipped: 0, failure: 0, total: 2 1/6: http://packagist.org/p/provider-latest$e92d78902849d96c573c7605b95a5dcca56e0539e69d4453870f4c9e50834de5.json 2/6: http://packagist.org/p/provider-2017-01$09c19a0462cf3cf7049e1558d30d6893caef000a9385fd584a93e879cfac1b60.json 3/6: http://packagist.org/p/provider-2017-04$4302be8285790b536b0864be9750e21171c1f94567afaec776c2c4881dd921ba.json 4/6: http://packagist.org/p/provider-2017-07$92d28ec5111571475c0cdd9bef1a83332b019c8dc9d3f9ff369632cce3e52c0c.json 5/6: http://packagist.org/p/provider-2017-10$29a08b1298c7eac670bc304557632c9d9f3ff40eecf4401d751a33cab733a277.json 6/6: http://packagist.org/p/provider-2016$424857fe605f6e025c78b889d76ec94d93ad4d3f7325892ba5abec0a5b8ca10e.json Finished: success: 6, skipped: 0, failure: 0, total: 6 ./composer.json has been updated 1/6: http://packagist.org/p/provider-latest$e92d78902849d96c573c7605b95a5dcca56e0539e69d4453870f4c9e50834de5.json 2/6: http://packagist.org/p/provider-2017-01$09c19a0462cf3cf7049e1558d30d6893caef000a9385fd584a93e879cfac1b60.json 3/6: http://packagist.org/p/provider-2017-10$29a08b1298c7eac670bc304557632c9d9f3ff40eecf4401d751a33cab733a277.json 4/6: http://packagist.org/p/provider-2017-07$92d28ec5111571475c0cdd9bef1a83332b019c8dc9d3f9ff369632cce3e52c0c.json 5/6: http://packagist.org/p/provider-2017-04$4302be8285790b536b0864be9750e21171c1f94567afaec776c2c4881dd921ba.json 6/6: http://packagist.org/p/provider-2016$424857fe605f6e025c78b889d76ec94d93ad4d3f7325892ba5abec0a5b8ca10e.json Finished: success: 6, skipped: 0, failure: 0, total: 6 > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Package operations: 0 installs, 1 update, 0 removals - Updating drupal/devel dev-1.x (5f4a6c1 => f88d70d): Installation failed, reverting ./composer.json to its original content. The following exception is caused by a lack of memory or swap, or not having swap configured Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details PHP Warning: proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 973 [ErrorException] proc_open(): fork failed - Cannot allocate memory require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", "stdout": "    1/2:\thttps://packages.drupal.org/8/drupal/provider-2016-2$a852048b62ae8fd2187de1f1facf5c2d4dfdc20011f9f237d20ac8b062b22802.json\n    2/2:\thttps://packages.drupal.org/8/drupal/provider-2017-3$388efe29189d36c6bf50fd8630650abba109830834cb29bd3915cc859a97065a.json\n    Finished: success: 2, skipped: 0, failure: 0, total: 2\n    1/6:\thttp://packagist.org/p/provider-latest$e92d78902849d96c573c7605b95a5dcca56e0539e69d4453870f4c9e50834de5.json\n    2/6:\thttp://packagist.org/p/provider-2017-01$09c19a0462cf3cf7049e1558d30d6893caef000a9385fd584a93e879cfac1b60.json\n    3/6:\thttp://packagist.org/p/provider-2017-04$4302be8285790b536b0864be9750e21171c1f94567afaec776c2c4881dd921ba.json\n    4/6:\thttp://packagist.org/p/provider-2017-07$92d28ec5111571475c0cdd9bef1a83332b019c8dc9d3f9ff369632cce3e52c0c.json\n    5/6:\thttp://packagist.org/p/provider-2017-10$29a08b1298c7eac670bc304557632c9d9f3ff40eecf4401d751a33cab733a277.json\n    6/6:\thttp://packagist.org/p/provider-2016$424857fe605f6e025c78b889d76ec94d93ad4d3f7325892ba5abec0a5b8ca10e.json\n    Finished: success: 6, skipped: 0, failure: 0, total: 6\n./composer.json has been updated\n    1/6:\thttp://packagist.org/p/provider-latest$e92d78902849d96c573c7605b95a5dcca56e0539e69d4453870f4c9e50834de5.json\n    2/6:\thttp://packagist.org/p/provider-2017-01$09c19a0462cf3cf7049e1558d30d6893caef000a9385fd584a93e879cfac1b60.json\n    3/6:\thttp://packagist.org/p/provider-2017-10$29a08b1298c7eac670bc304557632c9d9f3ff40eecf4401d751a33cab733a277.json\n    4/6:\thttp://packagist.org/p/provider-2017-07$92d28ec5111571475c0cdd9bef1a83332b019c8dc9d3f9ff369632cce3e52c0c.json\n    5/6:\thttp://packagist.org/p/provider-2017-04$4302be8285790b536b0864be9750e21171c1f94567afaec776c2c4881dd921ba.json\n    6/6:\thttp://packagist.org/p/provider-2016$424857fe605f6e025c78b889d76ec94d93ad4d3f7325892ba5abec0a5b8ca10e.json\n    Finished: success: 6, skipped: 0, failure: 0, total: 6\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nPackage operations: 0 installs, 1 update, 0 removals\n  - Updating drupal/devel dev-1.x (5f4a6c1 => f88d70d): \nInstallation failed, reverting ./composer.json to its original content.\nThe following exception is caused by a lack of memory or swap, or not having swap configured\nCheck https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details\n\nPHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 973\n                                                     \n  [ErrorException]                                   \n  proc_open(): fork failed - Cannot allocate memory  \n                                                     \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...\n\n", "stdout_lines": ["    1/2:\thttps://packages.drupal.org/8/drupal/provider-2016-2$a852048b62ae8fd2187de1f1facf5c2d4dfdc20011f9f237d20ac8b062b22802.json", "    2/2:\thttps://packages.drupal.org/8/drupal/provider-2017-3$388efe29189d36c6bf50fd8630650abba109830834cb29bd3915cc859a97065a.json", "    Finished: success: 2, skipped: 0, failure: 0, total: 2", "    1/6:\thttp://packagist.org/p/provider-latest$e92d78902849d96c573c7605b95a5dcca56e0539e69d4453870f4c9e50834de5.json", "    2/6:\thttp://packagist.org/p/provider-2017-01$09c19a0462cf3cf7049e1558d30d6893caef000a9385fd584a93e879cfac1b60.json", "    3/6:\thttp://packagist.org/p/provider-2017-04$4302be8285790b536b0864be9750e21171c1f94567afaec776c2c4881dd921ba.json", "    4/6:\thttp://packagist.org/p/provider-2017-07$92d28ec5111571475c0cdd9bef1a83332b019c8dc9d3f9ff369632cce3e52c0c.json", "    5/6:\thttp://packagist.org/p/provider-2017-10$29a08b1298c7eac670bc304557632c9d9f3ff40eecf4401d751a33cab733a277.json", "    6/6:\thttp://packagist.org/p/provider-2016$424857fe605f6e025c78b889d76ec94d93ad4d3f7325892ba5abec0a5b8ca10e.json", "    Finished: success: 6, skipped: 0, failure: 0, total: 6", "./composer.json has been updated", "    1/6:\thttp://packagist.org/p/provider-latest$e92d78902849d96c573c7605b95a5dcca56e0539e69d4453870f4c9e50834de5.json", "    2/6:\thttp://packagist.org/p/provider-2017-01$09c19a0462cf3cf7049e1558d30d6893caef000a9385fd584a93e879cfac1b60.json", "    3/6:\thttp://packagist.org/p/provider-2017-10$29a08b1298c7eac670bc304557632c9d9f3ff40eecf4401d751a33cab733a277.json", "    4/6:\thttp://packagist.org/p/provider-2017-07$92d28ec5111571475c0cdd9bef1a83332b019c8dc9d3f9ff369632cce3e52c0c.json", "    5/6:\thttp://packagist.org/p/provider-2017-04$4302be8285790b536b0864be9750e21171c1f94567afaec776c2c4881dd921ba.json", "    6/6:\thttp://packagist.org/p/provider-2016$424857fe605f6e025c78b889d76ec94d93ad4d3f7325892ba5abec0a5b8ca10e.json", "    Finished: success: 6, skipped: 0, failure: 0, total: 6", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Package operations: 0 installs, 1 update, 0 removals", "  - Updating drupal/devel dev-1.x (5f4a6c1 => f88d70d): ", "Installation failed, reverting ./composer.json to its original content.", "The following exception is caused by a lack of memory or swap, or not having swap configured", "Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details", "", "PHP Warning:  proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 973", "                                                     ", "  [ErrorException]                                   ", "  proc_open(): fork failed - Cannot allocate memory  ", "                                                     ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", ""]}

**Comment by fubarhouse** [comment]
Provided DrupalVM supports multisite out of the box, you will firstly need to increase your PHP memory and try again.

Aside from this I don't know if it currently supports it, so somebody else best answer this.

It doesn't stop you from setting it up yourself though, as I do it a lot.

**Comment by jating-appno** [comment]
hey,

can you please let me know how much memory should I assign, currently i have below memory settings.

php_memory_limit: "2048M"
vagrant_memory: 2048

php_version: "5.6" 

Also please let me know how to configure "vagrant_synced_folders" &  "apache_vhosts" for multisite and any other setting I need to take care of.

My multisite structure is like:

site1: <DRUPAL_ROOT_FOLDER>/www/sites/SITE_1
site2: <DRUPAL_ROOT_FOLDER>/www/sites/SITE_2

Thanks in advance

**Comment by fubarhouse** [comment]
@jating-appno, your VM memory matches your PHP memory, and that is far from ideal.

Please reduce your PHP memory by 1024M.

I cannot advise on how to use multisite within the playbook, because the way I work is completely manually controlled. I would in fact recommend setting up a second alias, virtualhost and creating the sites.php file yourself - however that is out of the scope of this project.

After your VM's memory isn't occupied completely by allocated PHP memory, please run it again and provide a copy of the composer.json file if it doesn't exist.

You can also try executing `composer self-update` whilst ssh'ed into the vm before retrying.

I'm not the maintainer of this project - I'm just trying to get enough information that it can be either solved or get more information for the maintainer to provide advice.

**Comment by lramarojaona** [comment]
I guess you need 2 vhosts pointing to the same folder in your config.yml:
  - servername: "site1.local"
    documentroot: "/var/www/drupalvm/www/<DRUPAL_ROOT_FOLDER/www"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
  - servername: "site2.local"
    documentroot: "/var/www/drupalvm/www/<DRUPAL_ROOT_FOLDER/www"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"

Once you've done that, you should read multi-site documentation : https://www.drupal.org/docs/8/multisite-drupal

**Comment by thom8** [comment]
@jating-appno you'll also need a db for each site -- see docs here -- http://docs.drupalvm.com/en/latest/deployment/multisite/

Would also recommend building the codebase from the host machine which is much faster and you can reuse the cache across projects.

**Comment by geerlingguy** [comment]
The above suggestions should help; see also related issue: https://github.com/geerlingguy/drupal-vm/issues/1637
