### ISSUE TITLE
DRUPAL-VM behind corporate proxy. Some issues and workarounds

### ISSUE THREAD

**Issue by MarioMadera** [geerlingguy/drupal-vm#1634]
### Issue Type
 - Bug Report / Support Request

### Your Environment
The command provided had failed (or I).

```
D:\Aplicaciones\cmder
λ vagrant --version
Vagrant 2.0.0

C:\Program Files\Oracle\VirtualBox
λ VBoxManage.exe --version
5.1.30r118389

From vagrant provision command:
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.4.2.0).
```
### Your OS
 - **Windows**  7

### Full console output

Sorry I did not copy the full output. It's related to provisiong task which runs sudo apt-get install <list of packages>

Minimal example is like this

`failed: [drupalvm] (item=[u'curl', u'python-apt', u'python-pycurl', u'sudo', u'unzip', u'make']) => {"cache_update_time": 1512390735, "cache_updated": false, "changed": false, "item": ["curl", "python-apt", "python-pycurl", "sudo", "unzip", "make"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'python-pycurl' 'unzip'' failed: E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-20ubuntu1_amd64.deb  Could not resolve 'us.archive.ubuntu.com'\n\nE: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/p/pycurl/python-pycurl_7.43.0-1ubuntu1_amd64.deb  Could not resolve 'us.archive.ubuntu.com'\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-20ubuntu1_amd64.deb  Could not resolve 'us.archive.ubuntu.com'\n\nE: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/p/pycurl/python-pycurl_7.43.0-1ubuntu1_amd64.deb  Could not resolve 'us.archive.ubuntu.com'\n\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/u/unzip/unzip_6.0-20ubuntu1_amd64.deb  Could not resolve 'us.archive.ubuntu.com'", "", "E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/main/p/pycurl/python-pycurl_7.43.0-1ubuntu1_amd64.deb  Could not resolve 'us.archive.ubuntu.com'", "", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  libyaml-0-2 python-crypto python-ecdsa python-httplib2 python-jinja2\n  python-markupsafe python-paramiko python-pkg-resources python-setuptools\n  python-six python-yaml sshpass\nUse 'sudo apt autoremove' to remove them.\nSuggested packages:\n  libcurl4-gnutls-dev python-pycurl-dbg python-pycurl-doc zip\nThe following NEW packages will be installed:\n  python-pycurl unzip\n0 upgraded, 2 newly installed, 0 to remove and 74 not upgraded.\nNeed to get 202 kB of archives.\nAfter this operation, 708 kB of additional disk space will be used.\nErr:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 unzip amd64 6.0-20ubuntu1\n  Could not resolve 'us.archive.ubuntu.com'\nErr:2 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python-pycurl amd64 7.43.0-1ubuntu1\n  Could not resolve 'us.archive.ubuntu.com'\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  libyaml-0-2 python-crypto python-ecdsa python-httplib2 python-jinja2", "  python-markupsafe python-paramiko python-pkg-resources python-setuptools", "  python-six python-yaml sshpass", "Use 'sudo apt autoremove' to remove them.", "Suggested packages:", "  libcurl4-gnutls-dev python-pycurl-dbg python-pycurl-doc zip", "The following NEW packages will be installed:", "  python-pycurl unzip", "0 upgraded, 2 newly installed, 0 to remove and 74 not upgraded.", "Need to get 202 kB of archives.", "After this operation, 708 kB of additional disk space will be used.", "Err:1 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 unzip amd64 6.0-20ubuntu1", "  Could not resolve 'us.archive.ubuntu.com'", "Err:2 http://us.archive.ubuntu.com/ubuntu xenial/main amd64 python-pycurl amd64 7.43.0-1ubuntu1", "  Could not resolve 'us.archive.ubuntu.com'"]}`

### Summary
This installation is behind a corporate proxy.
I had manage to solve some of the issues by accesing through ssh, and working as root.

_1- DNS resolv issues._
By default drupal-vm is configured to use as DNS the default gateway of the NATed vbox nwetwork. I think it should be sufficient but I had to add a extra nameserver:
    `nameserver 8.8.8.8`

_2- Proxy Server
I had added in /etc/profile this environment variables pointing to a CNTLM instances, local to may windows box, where xxx.xxx.xxx.xxx:yyyy is windows_box_public_ip:CNTLM_port

```
export http_proxy=http://xxx.xxx.xxx.xxx:yyyy
export https_proxy=http://xxx.xxx.xxx.xxx:yyyy
export HTTP_PROXY=http://xxx.xxx.xxx.xxx:yyyy
export HTTPS_PROXY=http://xxx.xxx.xxx.xxx:yyyy
```
_3- problems running sudo apt-get
I had install some packages becoming root without problem but failing using sudo apt-get.
So, I had edited /etc/sudoers and add this line
`Defaults env_keep += http_proxy https_proxy HTTP_PROX HTTPS_PROXY`

**Comment by denics** [comment]
Hi Mario, did you follow instructions [here](http://docs.drupalvm.com/en/latest/extending/vagrantfile/#example-using-drupal-vm-behind-a-corporate-proxy-with-vagrant-proxyconf) ? 
I have installed *vagrant-proxyconf* with ```vagrant plugin install vagrant-proxyconf``` then I've created a file called *Vagrantfile.local* :

```ruby
# Proxy:
if Vagrant.has_plugin?('vagrant-proxyconf')
  config.proxy.http = vconfig['proxy_http']
  config.proxy.https = vconfig['proxy_https']
  config.git_proxy.http = vconfig['proxy_http']
  config.proxy.no_proxy = vconfig['proxy_none']
  config.proxy.ftp = vconfig['proxy_ftp']
end%
```

and I have this in my *local.config.yml* :

```yaml
proxy_http: 'http://proxy.example.com:8080/'
proxy_https: 'http://proxy.example.com:8080/'
proxy_ftp: 'http://proxy.example.com:8080/'
proxy_none: 'localhost,127.0.0.1,.example.com'
```

I hope this helps.

**Comment by MarioMadera** [comment]
I think that is a better solution. Anyways, the problem of keeping that environment variables when running sudo will remain, IMO.
Thanks for the advice.

**Comment by geerlingguy** [comment]
@MarioMadera - The best fix is to use vagrant-proxyconf, which _should_ make it so all vagrant-based actions (provision, update, destroy, up, etc.) always works with the proxy. I believe it also configures the VM to allow commands run inside to use the proxy too.

If not, then it would be good to add the proxy config inside the VM as needed. Some applications and modules also don't play too nice with proxies, and unfortunately, it's up to the end user to work around those issues.
