### ISSUE TITLE
Creating Solr cores (5.x)

### ISSUE THREAD

**Issue by lramarojaona** [geerlingguy/drupal-vm#1635]
### Issue Type
 - Bug Report / Support Request

### Your Environment
_The full command "vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version" is not working from my Windows Powershell, so I gathered the infomration myself._
```
Vagrant 1.9.2
Virtualbox 5.1.28r117968
ansible 2.3.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
```

### Your OS
 - **Windows** (10)

### Summary
Hello,

I'm using Drupal VM (4.6.0) for several projects and managed to install Solr 5.5.3 - there were errors during the provisionning and I had to do manual steps myself to make the insallation succeed.

How can I create one core per project?
I tried adding them in config.yml with 

solr_cores:
  - project1
  - project2
  - ...

without any luck.

Then I tried to create them manually with "/opt/solr/bin/solr create -c new_core" (or similar), I see it in "Cloud" tab from Soilr UI, but not in "Core Admin".

**What's the best/standard way to create cores?
Is the core creation stable within Drupal VM (through config.yml)?**

Thank you!

**Comment by fubarhouse** [comment]
@lramarojaona,

It would be useful to know what the errors you came across were during installation, and it would also be useful for us if you could provide your solr config available in `config.yml`.

Lastly, could you also provide the output of the provision process for the solr role?

Ideally DrupalVM installs the specified cores for v5 and v6, it copies the example files into place and runs the command you've specified. I... have a custom script which replicates this with v6 for use at work. Unfortunately Solr is a temperamental thing to configure.

**So, to tell what's happening we'd need to look at the things mentioned above**.

**Comment by lramarojaona** [comment]
# Errors during installation
I don't remember exactly the output, but I had to download the Solr archive myself and play with permissions so the script was able to install Solr

# config.yml
https://gist.github.com/lramarojaona/1af48116ac326a580ea3f4006eddc0b8

# Provision process output
TASK [geerlingguy.solr : Create configured cores.] *****************************
failed: [dev2] (item=project1) => {"changed": true, "cmd": "/opt/solr/bin/solr create -c project1", "delta": "0:00:00.704669", "end": "2017-12-06 10:06:29.642263", "failed": true, "item": "project1", "msg": "non-zero return code", "rc": 1, "start": "2017-12-06 10:06:28.937594", "stderr": "\nERROR: \nCollection 'project1' already exists!\nChecked collection existence using Collections API command:\nhttp://localhost:8983/solr/admin/collections?action=list", "stderr_lines": ["", "ERROR: ", "Collection 'project1' already exists!", "Checked collection existence using Collections API command:", "http://localhost:8983/solr/admin/collections?action=list"], "stdout": "\nConnecting to ZooKeeper at localhost:9983 ...\nRe-using existing configuration directory project1", "stdout_lines": ["", "Connecting to ZooKeeper at localhost:9983 ...", "Re-using existing configuration directory project1"]}
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

Now I see that it says "Collection 'project1' already exists!", so I'll try by deleting it.

**Comment by lramarojaona** [comment]
Ok, my bad, everything's fine!

I did "bin/solr delete -c collection_name" and "bin/solr restart".
Then I ran vargant provision, the core is created!

Many thanks!
