### ISSUE TITLE
Failed to validate the SSL certificate for xdebug.org:443

### ISSUE THREAD

**Issue by ashabed** [geerlingguy/drupal-vm#1638]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
vagrant@drupalvm:~$ ansible --version
ansible 2.4.1.0
 config file = /etc/ansible/ansible.cfg
 configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
 ansible python module location = /usr/lib/python2.7/dist-packages/ansible
 executable location = /usr/bin/ansible
 python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]
vagrant@drupalvm:~$
```

### Your OS

 - **macOS** sierra 10.12.6

### Full console output

```
vagrant up
vagrant provision
```
```
TASK [geerlingguy.php-xdebug : Untar Xdebug.] **********************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for xdebug.org:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)."}
    to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                : ok=139  changed=2    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```
### Summary
Hello Jeff! Thanks for your great work.

We're using drupalvm for the current semester of debugacademy.com . The good thing about that is we have tested the issue on many machines. Basically, provisioning after uncommenting xdebug in drupalvm worked on 8 machines, but did not work on 1 machine with the same configuration.

A proper fix would be great, but at this point a workaround would be OK. 

I tried this with no luck:
- vagrant up
- vagrant ssh
- cd /vagrant
- `sudo ansible-galaxy install -r provisioning/requirements.yml --force`
- Placed the `/etc/php/7.1/fpm/conf.d/*xdebug*` file from my working VM in the same place in their VM
- `sudo systemctl restart php7.1-fpm && sudo service apache2 restart`

But xdebug is still not installed / at least there's no trace of it using `phpinfo();`. 
I would love it if we could get this thing installed using the config.yml file's settings. *Given the context* (local development for personal site) and time-sensitivity (using this for a live course), *could you point us to how to set "validate_certs=False" temporarily*?

#### Potentially related issues
#844 
#896 

Thank you for any help!

**Comment by geerlingguy** [comment]
This could potentially be an upstream issue; but can I get more info—what base box are you using? And is it possible for you to post a full `config.yml` so I can test and reproduce using your config?

**Comment by oxyc** [comment]
As there's been no response for 3 weeks I'll assume this was a networking error. Let us know if you're still seeing the issue and we can reopen this.
