### ISSUE TITLE
Consider changing default .dev ending URL's because Google now owns the .dev TLD

### ISSUE THREAD

**Issue by TipiT** [geerlingguy/drupal-vm#1644]
My Chromium started redirecting from http to https which was not happening when using any other browser so I stumbled to this [1]. So the problem is obviously [2].

I could also not think of a workaround other than renaming the site names (virtual hosts). 

[1] https://stackoverflow.com/questions/47707124/chrome-63-changing-http-to-https
[2] https://icannwiki.org/.dev

**Comment by FinBoWa** [comment]
Thats allready solved https://github.com/geerlingguy/drupal-vm/issues/1427 with the commit https://github.com/geerlingguy/drupal-vm/commit/dd3bd3f307ab9d45b80954fcb7dd47418a669388

**Comment by thom8** [comment]
Correct this has been addressed in the latest version, closing this one
