### ISSUE TITLE
PHP-Redis repository branch is renamed or deleted.

### ISSUE THREAD

**Issue by kallevu** [geerlingguy/drupal-vm#1658]
### Issue Type
 - Documentation Report

### Summary

On Drupal VM's [Readme](https://github.com/geerlingguy/drupal-vm/tree/master/provisioning/roles/geerlingguy.php-redis) it gives branch examples for repository variable `php_redis_source_version`. However repo in example [https://github.com/phpredis/phpredis.git](https://github.com/phpredis/phpredis.git) does not have `php7` branch anymore, maybe it should just say "Use development branch if you need support for php7" ?

**Comment by oxyc** [comment]
Could you open this issue at https://github.com/geerlingguy/ansible-role-php-redis instead? That role is a dependency of Drupal VM.
