### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by danepowell** [geerlingguy/drupal-vm#1663]
I'm wondering if we can get a new patch release, since it's been a few months since the last one. In particular, I'd love to start taking advantage of the ability to disable xdebug on the guest CLI, which will lead to a significant performance boost and get rid of a whole bunch of annoying warnings in BLT: https://github.com/geerlingguy/drupal-vm/commit/b5789fc39c1e11c8266c717b32cd42ade788c267

**Comment by FinBoWa** [comment]
For xdebug id personally would suggest adding your own bash script to toggle xdebug on/off. 

Using provisioning to toggle that on / off takes too much time as you probably just need to get. 

I have a ubuntu variant somewhere but didn't find it fast enough, so iv go this: 

```
#!/bin/bash
#
# Simple toggle script for Xdebug
#
#     Author : Kevin Hill
#       Date : 2/24/2016
#
#
##################################
# Variables
##################################
#
PHP_DIR="/etc/php.d/"
INI="xdebug.ini"
XDEBUG='zend_extension="\/usr\/lib64\/php\/modules\/xdebug.so"'


##################################
# Script
##################################
#
cd $PHP_DIR

case "$1" in
    on)
        if grep -q "^;$XDEBUG" $INI; then
            echo "Enabling Xdebug"
            cat $INI | sed -i.bak "s/^;$XDEBUG/$XDEBUG/g" $INI
            sudo service php-fpm restart
        else
            echo "Already Enabled"
        fi
        ;;

    off)
        if grep -q "^$XDEBUG" $INI; then
            echo "Disabling Xdebug"
            cat $INI | sed -i.bak "s/^$XDEBUG/;$XDEBUG/g" $INI
            sudo service php-fpm restart
        else
            echo "Already Disabled"
        fi
        ;;

    *)
        echo "Usage: xdebug [on|off]"
        exit 1
        ;;
esac
```

and off and on variant for this: 

```
#/bin/sh
CURRENT_USER=`whoami`
if [ "$CURRENT_USER" == "vagrant" ]; then
  cd /vagrant; ./xdebug.sh off
else
  vagrant ssh -c "cd /vagrant; sudo ./xdebug.sh off"
fi
``

**Comment by geerlingguy** [comment]
Sure thing! Things are pretty stable in dev, so I'm happy to drop a patch release.

**Comment by geerlingguy** [comment]
Done: https://github.com/geerlingguy/drupal-vm/releases/tag/4.7.1

**Comment by danepowell** [comment]
Thanks!
