### ISSUE TITLE
The install of dependencies fails when Drupal VM is used as a Composer dependency

### ISSUE THREAD

**Issue by rpkoller** [geerlingguy/drupal-vm#1664]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
   vagrant-bindfs (1.0.11)
   vagrant-cachier (1.2.1)
   vagrant-disksize (0.1.2)
   vagrant-exec (0.5.2)
   vagrant-ghost (0.2.3) 
   vagrant-hostmanager (1.8.7)
   vagrant-hostsupdater (1.0.2)
   vagrant-share (1.1.9, system)
   vagrant-triggers (0.5.3)
   vagrant-vbguest (0.15.0)
VirtualBox 5.2.6r120293
ansible 2.4.2.0
  config file = /Users/myuser/.ansible.cfg
  configured module search path = [u'/Users/myuser/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.2.0_2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

### Your OS

 - **macOS** (10.11.6 (15G17023))

### Full console output

https://gist.github.com/rpkoller/16ce997970b468c023177599b018290b

### Summary

I tried to follow the setup provided in the soup to nuts article for building a local development environment. With the only slight difference I tried to use `drupal_build_composer` while setting `drupal_composer_dependencies`and choose `docroot` in `drupal_core_path`. My two configuration files placed inside the `vm` directory are the following:

[config.yml](https://gist.github.com/rpkoller/38d30c22d2225afcd98bc96df2a85b03)
[vagrant.config.yml](https://gist.github.com/rpkoller/d3ecc04639f1ec391d96b9541ec991d9)

The idea was that there isn't a composer file required for building the VM inside the `vm` directory and that the dependencies are set with `drupal_composer_dependencies`. By setting `drupal_composer_path` to `false`like recommended in http://docs.drupalvm.com/en/latest/deployment/composer-dependency/ the installation hasn't failed anymore cuz of the required `composer.json` in the `vm` directory but now the installation fails as you can see from the console output. Is there an error of reasoning in my chosen setup? Is it required to use a `composer.json` inside the `vm`directory instead and set the dependencies there?  Best regards Ralf

**Comment by geerlingguy** [comment]
I think you just need to set `drupal_composer_dependencies: []` in your `config.yml`... what's happening is the Drupal ansible role is trying to `composer require` all the modules that are listed in `drupal_composer_dependencies`. It sounds like you want to manage your project yourself and not have Drupal VM try to manage your project dependencies...

**Comment by rpkoller** [comment]
Hmmmmm I've chosen to go with Composer since it was told to be the best practice and go to solution in general in the future. I had the impression the installation and managing of dependencies is more or less the same with Drush Make files and Composer. Thought the default Make file option installs modules by the aid of Drush while `drupal_composer_dependencies` requires modules by adding them to the `composer.json` file. So why is the project dependency management not done by Drupal VM with Composer but with Make files only? That fact I not completely get and understand. Is it cuz you are able to add new modules to the `config.yml` and then provision with Make files? But you are able to do the same with the `composer.json`aren't you?
Hm but guess I had an error in reasoning anyway in regards of Composer. By adding the default `composer.json` into the `vm/` folder, changing the path inside the `composer.json` from `web` to `docroot` like set in the `config.yml` and setting the `drupal_composer_dependencies` made it work again. Just thought Drupal VM would create a clean new `composer.json` when  `drupal_composer_path` is set to `false` and also mind the `drupal_core_path` set to `docroot`. Just a few misconceptions on my side. :/ Still learning and trying to wrap my head around it. But I am slowly getting to it finally. ;)

**Comment by rpkoller** [comment]
Thanks for the clarification and writeup @geerlingguy ! I am going with Drupal 8 only. ...and as I've written up in my initial post I went with Drupal VM as a dependency. So based on your recommendation I have just to eradicate the `drupal_composer_dependencies` from the `config.yml` and move the listed dependencies to the `drupal.composer.json` template instead (including Drush and Drupal Console). So Drupal VM is responsible only for provisioning of the VM while Composer does the provisioning of Drupal and its dependencies. A separation of concerns. ;) Thanks a lot!

**Comment by geerlingguy** [comment]
Yep, exactly! Plus, you're letting Drupal VM do the things it does best (provisioning), and Composer do the things it does best (manage all the code in one file) :)

I'll close this issue; please open up a new one if you find any other roadblocks!

**Comment by rpkoller** [comment]
Thanks a lot for the help Jeff! At the moment I don't see any more roadblocks. You've helped removing them more than well! :) I more and more get the spin with Drupal VM as well as loving and appreciating it. I maybe have a single topic left I am uncertain about but I will give it another try to figure it out on my own first with my new gained understanding. In case I fail I'll open a new issue. But for the moment everything is good and fine! :) Thanks again!
