### ISSUE TITLE
Installation of dependencies fails

### ISSUE THREAD

**Issue by verganis** [geerlingguy/drupal-vm#1665]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Ubuntu installation inside Windows 10 / no vagrant or virtuabox used currently

### Your OS
 - **Windows** (version 10)

### Full console output

https://pastebin.com/byPpbda2

### Summary

when running "btl vm" an error is thrown during installation of dependencies

**Comment by oxyc** [comment]
This is not related to Drupal VM but something in your Composer dependencies. If it's a new BLT project, maybe ask or check their issue queue.
