### ISSUE TITLE
Add a config option to source any file

### ISSUE THREAD

**Issue by benjy** [geerlingguy/drupal-vm#167]
It would be good if you could specify a file in config.yml that is sourced when you ssh into the vagrant VM. This would be useful for:

* Custom bash prompts
* Custom aliases

**Comment by geerlingguy** [comment]
It might be even better if your own .bash_profile or .profile (or other dotfiles) were placed into the `vagrant` user account (maybe, optionally?). I don't normally do much work inside the VM, but many people do, so I'm amenable to this idea.

**Comment by benjy** [comment]
Yeah I don't mind that idea, personally I use ZSH. Just copying the .bash_profile would fail in two scenarios:

* If you wanted to have different setups between the VM and host
* If your ~/.bash_profile depended on other files on the host. Eg, I store my aliases somewhere else and source them from profile.

**Comment by geerlingguy** [comment]
@benjy - For this, I'd rather allow users to source extra tasks that they can use to do whatever they want (including pulling in custom profile files, restarting other things, installing extra software, etc.): https://github.com/geerlingguy/drupal-vm/issues/174

So, I'm going to close this issue, and then I'll hopefully add some documentation in #174 to show how to do something like copy in a custom `.profile` or other dotfiles.
