### ISSUE TITLE
Running Drush in post_provision_scripts scripts

### ISSUE THREAD

**Issue by robiningelbrecht** [geerlingguy/drupal-vm#1681]
### Issue type

Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.1
VirtualBox 5.2.6r120293
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/user/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

### Your OS

**Linux** (Ubuntu 16.04)

### Full console output

https://gist.github.com/robiningelbrecht/8b37f5392faf2d6f467e884b8687f934

### Summary

I configured "post_provision_scripts" in my config.yml. This script executes a few simple drush commands. When testing this using 

```
vagrant ssh
sh drupal-vm/post-provision-drupal.sh
```
all goes as expected. When I run "vagrant provision" and the post provision script is executed, drush renders following output:

```
Command pm-enable needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run this command.                                    [error]
The drush command 'en trololo' could not be executed.                                                                                                                                     [error]
Could not find a Drupal settings.php file at sites/default/settings.php.  
```

Seems like vagrant can't find my Drupal installation. Any suggestions?
Thanks!

**Comment by oxyc** [comment]
Could you post the script?

**Comment by robiningelbrecht** [comment]
```
#!/usr/bin/env bash

cd "/var/www/drupalvm";

# Only execute this when Drupal is not installed yet.
if ! [ "$(drush status | grep Successful)" ]; then
    drush  dis varnish -y;
    drush en diff -y;
    drush en optimizedb -y;
    drush  cc all;
fi
```

Side note: does vagrant provision run as root user? Because when connecting with "vagrant ssh", I'm logged in with the vagrant user. Maybe that could be an issue?

**Comment by oxyc** [comment]
That's correct. You could run the commands with `sudo -u vagrant drush status` but I'm not sure if all the necessary environment variables will be added.

**Comment by robiningelbrecht** [comment]
I'll try your suggestion and will get back to you :)

**Comment by robiningelbrecht** [comment]
All goes as expected now. Thanks :)

**Comment by oxyc** [comment]
Great 👍 I'll go ahead and close this issue then.
