### ISSUE TITLE
geerlingguy/ubuntu1604 not found on atlas.hashicorp.com

### ISSUE THREAD

**Issue by rpkoller** [geerlingguy/drupal-vm#1684]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.4.3.0
```

### Your OS

 - **macOS** (10.11.6 (15G17023))

### Full console output

https://gist.github.com/rpkoller/b78842151225dae594ef8dbe42d48e48

### Summary

When I try to update the box with `vagrant box update` the download fails while trying to check for updates on https://atlas.hashicorp.com/geerlingguy/ubuntu1604 . When I check the link directly in the browser the box is also not found: 

```
404 Not Found

Sorry, the page /geerlingguy/ubuntu1604 could not be found.

This error could mean one of three things:

The resource doesn't exist
The resource exists, but requires proper authorization to access
The resource exists, but its owner organization is delinquent
If someone has linked you to this resource, ensure that they have given you proper permissions to access it.
```
The box got deleted or is an update underway? Best regards r.

**Comment by geerlingguy** [comment]
That's because Atlas is actually now 'Vagrant Cloud' (for Vagrant boxes at least): https://app.vagrantup.com/geerlingguy/boxes/ubuntu1604

It seems like maybe your Drupal VM config might be pointing directly at the full URL or something, maybe? I haven't seen anyone else running Vagrant 2 have any issues getting the box as long as it's just set as `geerlingguy/ubuntu1604`.

Maybe try deleting the box (`vagrant box remove geerlingguy/ubuntu1604`) and see if it downloads after that?

Worst case, try uninstalling Vagrant than reinstalling it. For some reason it's trying to look for the box at a _really_ old location, where it hasn't existed for some time at least.

**Comment by geerlingguy** [comment]
Ah... it has to do with the last time you downloaded a box. This is definitely an upstream issue, though you can fix it by removing the box entirely then downloading it again, I think. See: https://github.com/hashicorp/vagrant/issues/9442

Going to mark this as upstream bug and close it—please continue any further discussion upstream.

**Comment by geerlingguy** [comment]
Reopening this, just to keep some visibility, since I'm guessing others will start running into it. I did, just now, and I recently updated my box!

```
==> f1: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> f1: There was a problem while downloading the metadata for your box
==> f1: to check for updates. This is not an error, since it is usually due
==> f1: to temporary network problems. This is just a warning. The problem
==> f1: encountered was:
==> f1: 
==> f1: The requested URL returned error: 404 Not Found
==> f1: 
==> f1: If you want to check for box updates, verify your network connection
==> f1: is valid and try again.
```

**Comment by geerlingguy** [comment]
Just tested and the fix is definitely:

```
vagrant box remove geerlingguy/ubuntu1604 --all
```

Otherwise you can dig through the Vagrant box folder on your local machine and update the cached download URL stuff, or wait until the next Vagrant release when they hopefully fix this... or hope they add a redirect on atlas.hashicorp.com.

**Comment by rpkoller** [comment]
Thanks for investigating! I can confirm the fix. But destroyed the environments before removing the box as recommended by Vagrant. The box is loading now correctly from: 
```
https://vagrantcloud.com/geerlingguy/boxes/ubuntu1604/versions/1.1.7/providers/virtualbox.box
```
again, instead of 
```
https://atlas.hashicorp.com/geerlingguy/ubuntu1604
```
like before.

**Comment by wizonesolutions** [comment]
a non-destructive workaround is also sed -i -- 's/atlas.hashicorp/vagrantcloud/g' ~/.vagrant.d/boxes/*/metadata_url

**Comment by margyly** [comment]
I have a brand new installation of Vagrant and Drupal VM and have uninstalled and reinstalled everything. I'm still getting an error which downloading the remote file. No boxes are current running "vagrant global-status returns no boxes.)  Here's the command that appears to add the geerlingguy/ubuntu1604 box at its new address:

vagrant box add -name geerlingguy/ubuntu1604 https://vagrantcloud.com/geerlingguy/boxes/ubuntu1604/versions/1.1.7/providers/virtualbox.box

Does that look right?

**Comment by margyly** [comment]
Nope, that didn't do it. Try this:

vagrant init geerlingguy/ubuntu1604  --box-version 1.1.7
vagrant up

**Comment by NSpencer4** [comment]
People still seeing this error before creating a box should try this:
vagrant plugin install vagrant-hostsupdater
Then run:
vagrant up

**Comment by geerlingguy** [comment]
I'm going to close this issue now, since it's been a few months and hopefully the rest of the people who encounter this will find the solution here or in the Vagrant issue queue via Google Search.
