### ISSUE TITLE
ERR_SSL_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by josuevalrob** [geerlingguy/drupal-vm#1685]
### Issue Type
 - Bug Report / Support Request

### Summary
I am new in DrupalVM, so on my first try I followed all the steps, and now is working, but I can access just by the IP: **http://192.168.88.88/**. I can not access by: **https://dashboard.drupalvm.dev/** or **https://drupalvm.dev/** neither in chrome or safari. 

In both cases, it redirects me to an https host. 

### Your Environment
Vagrant 2.0.2
vboxmanage: 5.2.6r120293

### Your OS
 - **macOS** (high sierra)

### Full console output
Current machine states:
drupalvm --> running (virtualbox)

==> drupalvm: Machine 'drupalvm' has a post `vagrant up` message. This is a message
==> drupalvm: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drupalvm: 
==> drupalvm: Your Drupal VM Vagrant box is ready to use!
==> drupalvm: * Visit the dashboard for an overview of your site: http://dashboard.drupalvm.dev (or http://192.168.88.88)
==> drupalvm: * You can SSH into your machine with `vagrant ssh`.
==> drupalvm: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com

**Comment by josuevalrob** [comment]
this is the result of  cat /etc/apache2/sites-available/vhosts.conf


DirectoryIndex index.php index.html

```

<VirtualHost *:80>
  ServerName drupalvm.dev
  ServerAlias www.drupalvm.dev
  DocumentRoot "/var/www/drupalvm/drupal/web"

  <Directory "/var/www/drupalvm/drupal/web">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName adminer.drupalvm.dev
  DocumentRoot "/opt/adminer"

  <Directory "/opt/adminer">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName xhprof.drupalvm.dev
  DocumentRoot "/usr/share/php/xhprof_html"

  <Directory "/usr/share/php/xhprof_html">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName pimpmylog.drupalvm.dev
  DocumentRoot "/usr/share/php/pimpmylog"

  <Directory "/usr/share/php/pimpmylog">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>

<VirtualHost *:80>
  ServerName 192.168.88.88
  ServerAlias dashboard.drupalvm.dev
  DocumentRoot "/var/www/dashboard"

  <Directory "/var/www/dashboard">
    AllowOverride All
    Options -Indexes +FollowSymLinks
    Require all granted
  </Directory>
  <FilesMatch \.php$>
  SetHandler "proxy:fcgi://127.0.0.1:9000"
</FilesMatch>

</VirtualHost>
```

**Comment by josuevalrob** [comment]
I dont know why, but after uninstall and install vagrant and virtual box its working fine...

**Comment by FinBoWa** [comment]
Even you closed I'll add this here: the solution is not to use the dtl .dev .  See #1427
