### ISSUE TITLE
Behat drupal-extension not working when lightning installed from tarball

### ISSUE THREAD

**Issue by Ant63** [geerlingguy/drupal-vm#1686]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.0
VirtualBox 5.1.28r117968
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides

```

### Your OS

 - **macOS** (10.13.3)

### Full console output

  @api
  Scenario: Create a node                                              # features/DrupalFeature.feature:12
    Given I am logged in as a user with the "administrator" role       # Drupal\DrupalExtension\Context\DrupalContext::assertAuthenticatedByRole()
    When I am viewing an "article" content with the title "My article" # Drupal\DrupalExtension\Context\DrupalContext::createNode()
      16384: Interacting directly with the RawDrupalContext::$user property has been deprecated. Use RawDrupalContext::getUserManager->getCurrentUser() instead. in vendor/drupal/drupal-extension/src/Drupal/DrupalExtension/Context/RawDrupalContext.php line 146
    Then I should see the heading "My article" 

### Summary

Behat drupal-extension

Using the drupal-extension having installed lightning from binaries instead of composer results in the error above.

Using the drupal-extension from a composer install works

**Comment by geerlingguy** [comment]
This seems like an issue with a Lightning-based install, and I'd rather any follow-up discussion or questions be sent to the Lightning project's issue queue. It seems like Lightning should be installed via Composer regardless, otherwise there are many different things that would blow up.
