### ISSUE TITLE
Increase default /dev/shm size

### ISSUE THREAD

**Issue by bobbygryzynger** [geerlingguy/drupal-vm#1688]
### Issue Type

 - Bug Report / Support Request

### Summary
Is there currently a configuration value for increasing the default `/dev/shm` size? 

I have been debugging [this issue with the chrome-mink-extension](https://gitlab.com/DMore/chrome-mink-driver/issues/52) and one part of the fix is giving Chrome more shared memory to work with. I am able to do this via the cli, but is there (or could there be) a configuration value that will provide a higher shared memory allotment? 

For anyone wondering how to increase this value manually, FWIW I took the route mentioned [here](https://askubuntu.com/questions/855740/how-do-i-increase-size-of-per-user-tmpfs-partition-run-user-id).

**Comment by geerlingguy** [comment]
I can't think of any built in way of doing this... do you just need more space on the system volume?

**Comment by bobbygryzynger** [comment]
@geerlingguy I can try that out, I'm not sure if it would make any difference. Is there a configuration option for this?

**Comment by geerlingguy** [comment]
Not really, the easiest thing would probably be to create your own base box with a larger default size. Drupal VM's _main_ drive in the `geerlingguy/*` base boxes is capped at like 80 GB currently, but I don't do any other volume configuration.

See related:

  - https://github.com/hashicorp/vagrant/issues/2339
  - https://github.com/sprotheroe/vagrant-disksize

Not sure if anything in there will help with /dev/shm directly though. Can you configure the chrome-mink-extension to use storage other than /dev/shm?

Closing this for now, as I don't think there's anything simple I could do to make it easier to configure via Drupal VM/Vagrant without resorting to a bunch of Ansible tasks that I'd rather not have to maintain for multiple OSes.
