### ISSUE TITLE
Richer values for vagrant_public_ip?

### ISSUE THREAD

**Issue by siliconmeadow** [geerlingguy/drupal-vm#1689]
### Issue Type

 - Feature Idea
### Your Environment
Arch Linux

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.4.3.0
```

### Your OS

 - **Linux** (Arch - rolling release, all up-to-date w/ kernel 4.15.x)

### Summary

When using the `vagrant_public_ip` variable in my config.yml file so others on my company LAN can access my machine, it seems as though it always sets up the interface with `netmask 255.255.255.0` and `broadcast 192.72.0.255`.

Our intranet is a bit bigger and I need to set things up with `netmask 255.255.0.0` and `broadcast 192.72.255.255`.

Is there already a way to do this?

**Comment by siliconmeadow** [comment]
Moments after posting this, I found that I could add this to my `Vagrant.local` file:

```
config.vm.network "public_network", bridge: "enp0s31f6", ip:"192.72.0.153", netmask:"255.255.0.0"
```

Unless there's a more sophisticated way to do this, I'm happy to write this up for the docs.

**Comment by geerlingguy** [comment]
I think this is use-case-specific enough that just having it searchable in the issue queues is enough. I haven't seen enough people have to set a custom netmask that I think it warrants a separate entry in the docs.
