### ISSUE TITLE
Move documentation to Read the Docs

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#169]
GitHub's Wiki is a bit of a pain to use, and doesn't really offer much over just maintaining the documentation inside the project itself. Therefore, I'd like to keep the docs in code, and use Read the Docs to display them at the URL: http://docs.drupalvm.com/

  - [x] Create read the docs account
  - [x] Choose a pattern: docs in current codebase, or new `drupal-vm-docs` git project? (I'm favoring docs-in-main-repo, since I hate messy cross-dependencies and outdated docs). (Picked: putting docs into a `docs` directory).
  - [x] Move the documentation pages from the [Wiki](https://github.com/geerlingguy/drupal-vm/wiki) to the codebase
  - [x] [Set up a cname](https://read-the-docs.readthedocs.org/en/latest/faq.html) for the docs (e.g. `docs.drupalvm.com`)
  - [x] [Set up GitHub webhooks](https://read-the-docs.readthedocs.org/en/latest/webhooks.html) so changes are pushed automatically
  - [x] Redirect each wiki page to the new docs pages.
  - [x] Update project README to point to new documentation pages (and add prominent link to docs.drupalvm.com)
  - [x] Update www.drupalvm.com to point to new documentation pages (and add prominent link to docs.drupalvm.com)
  - [x] Organize the docs similar to organization on the Wiki

For structure/setup, see the [mkdocs build documentation](https://read-the-docs.readthedocs.org/en/latest/builds.html#mkdocs).

**Comment by nerdstein** [comment]
+1 for main repo

**Comment by geerlingguy** [comment]
@nerdstein - Sounds good! Updated the issue summary/checkboxes above.

**Comment by geerlingguy** [comment]
@nerdstein - FYI, I've updated the wiki (https://github.com/geerlingguy/drupal-vm/wiki/PHP-7-on-Drupal-VM), please make sure you pull the latest changes :)

**Comment by geerlingguy** [comment]
@nerdstein added docs to the repo as part of https://github.com/geerlingguy/drupal-vm/pull/172, so onward with this issue!

**Comment by geerlingguy** [comment]
This issue is complete. Yay!
