### ISSUE TITLE
Correct way to update Drush when using drupal-vm Docker image

### ISSUE THREAD

**Issue by gabe-connolly** [geerlingguy/drupal-vm#1690]
### Issue Type
Support Request

### Your Environment
```
Docker container using geerlingguy/drupal-vm
```

### Your OS
 - **macOS** 10.13.3 (17D47)

### Summary
As part of my update process to Drupal Core 8.4.4 and Lightning 2.2.7, I ran into a nasty issue where I could no longer export config from my site using either `drush cex` or `drush csex`.  The error that I was getting was `Error: Undefined class constant &#039;DUMP_EXCEPTION_ON_INVALID_TYPE&#039;`, which I was finally able to track back to some version conflicts with the version of Symfony/Yaml that was being used by Drush 8.1.14, which was the globally installed version in my Docker container.  If I ran `cex` from my project directory (`bin/drush` cex), I was able to export config with no problems.  

My specific question is, in the context of a Docker project what is the prescribed way to update drush in the Docker container?  I went down the path of updating my Dockerfile to replace the drush binary at /usr/local/bin as [described here](https://github.com/geerlingguy/drupal-vm/issues/1594#issuecomment-340454461), but I'm not thrilled with this solution, as I now have to make sure to maintain my Drush versions in both my Dockerfile and separately in my composer.json file, since I am explicitely requiring drush via composer as well.  In the vagrant version of drupal-vm I see that via various config.yml settings it's possible to specify a drush version, but is there an equivalent when working with the Docker image of drupal-vm?

**Comment by geerlingguy** [comment]
@gabe-connolly - The latest versions of Drupal VM's docker image now use the Drush Launcher globally, _instead of_ having Drush installed as a global tool.

This means that inside the container, Drush Launcher will automatically use whatever Drush version you have installed as a dependency of your Drupal project(s).

As of about 3 weeks ago, Drush is no longer installed globally inside the Docker container version of Drupal VM, and that should hopefully help (a) push people more towards having Drush as a project dependency (this is the recommended and now only supported way of using Drush as of 9.x), and (b) not have to worry about the global drush install in Dockerized scenarios anymore.

**Comment by gabe-connolly** [comment]
Awesome, thanks @geerlingguy !
