### ISSUE TITLE
Vagrant up crashes to blue-screen on Windows 10 with Hyper-V

### ISSUE THREAD

**Issue by kdmcguire** [geerlingguy/drupal-vm#1691]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
```

### Your OS

 - **Windows** 10 Pro (version 1709, build 16299.98) with Hyper-V enabled

### Full console output

I'm on a regular office machine so don't have CMDER, and I can't find my normal CMD history since the machine crashed.

I ran the command `vagrant up` it crashed a few minutes into trying to install the box.

### Summary

Running `Vagrant Up` on a Windows 10 Pro machine with Hyper-V enabled causes a hard crash to a blue error screen. After a couple of attempts either the vagrant global or box files corrupted, but I don't know exactly what caused that or why it happened on the second attempt but not the first.

After disabling Hyper-V, the `vagrant up` ran successfully.

There were these logs in the Event Viewer, but they could have been related to workplace DNS restrictions rather than this Hyper-V issue. I'll leave them in for full info anyway!

In Event Viewer, there's this **Error**:

```
The application-specific permission settings do not grant Local Activation permission for the COM Server application with CLSID 
{D63B10C5-BB46-4990-A94F-E40B9D520160}
and APPID 
{9CA88EE3-ACB7-47C8-AFC4-AB702511C276}
to the user [me] from address LocalHost (Using LRPC) running in the application container Unavailable SID (Unavailable). This security permission can be modified using the Component Services administrative tool.
```

And this **Warning**:

```
The system failed to register host (A or AAAA) resource records (RRs) for network adapter
with settings:
[Adapter and DNS info] 

The reason the system could not register these RRs was because the DNS server contacted refused the update request. The reasons for this might be (a) you are not allowed to update the specified DNS domain name, or (b) because the DNS server authoritative for this name does not support the DNS dynamic update protocol.

To register the DNS host (A or AAAA) resource records using the specific DNS domain name and IP addresses for this adapter, contact your DNS server or network systems administrator.
```

**Comment by kdmcguire** [comment]
I've disabled Hyper-V, which seems to have stopped the crashes. I'll keep trying to get the environment info so you can check for yourself.

**Comment by geerlingguy** [comment]
@kdmcguire - Hyper-V is not officially supported by Drupal VM (therefore you'd be on your own when using it); please see: 

  - https://github.com/geerlingguy/drupal-vm/issues/1596
  - https://github.com/geerlingguy/drupal-vm/issues/1015

Others seem to be able to get it working, but as I said, I can't offer any more official support as I can only currently support VirtualBox or Docker on windows.
