### ISSUE TITLE
Problem with vagrant up 

### ISSUE THREAD

**Issue by ronsonmaria** [geerlingguy/drupal-vm#1693]
- Bug Report / Support Request

### Your Environment

vagrant --version
Vagrant 2.0.2
MacBook-Pro-de-Francisco:iinventi-local franciscoluisfernandezsoriano$ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/franciscoluisfernandezsoriano/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

### Your OS

MAC OS Highsierra

### Full console output

sudo vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: NS_ERROR_FAILURE
VBoxManage: error: Failed to create the host-only adapter
VBoxManage: error: VBoxNetAdpCtl: Error while adding new interface: failed to open /dev/vboxnetctl: No such file or directory
VBoxManage: error: Details: code NS_ERROR_FAILURE (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage: error: Context: "RTEXITCODE handleCreate(HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp


### Summary

**Comment by ronsonmaria** [comment]
It's ok

http://matthewpalmer.net/blog/2017/12/10/install-virtualbox-mac-high-sierra/index.html

**Comment by chenrq2005** [comment]
Thanks, Ronsonmaria!
