### ISSUE TITLE
Update Drupal VM Docker Hub image documentation

### ISSUE THREAD

**Issue by hmartens** [geerlingguy/drupal-vm#1694]
Jeff Geerling asked me to log this issue. 

On this page on docker it says you need to install vagrant and virtualbox: https://hub.docker.com/r/geerlingguy/drupal-vm/

All the steps on this page is the exact same as the normal drupalvm installation, not the way it is installed on docker.

Thank you

**Comment by geerlingguy** [comment]
Sorry about that! I'll definitely get the Docker Hub image docs updated soon; was fixing a few other Docker docs today, just didn't get time to finish up the hub docs too.
