### ISSUE TITLE
 Drupal VM 4.7.2 / BLT 9.x-dev give error on vagrant up

### ISSUE THREAD

**Issue by captaindav** [geerlingguy/drupal-vm#1695]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
C:\WINDOWS\system32>vagrant --version
Vagrant 2.0.2
C:\WINDOWS\system32>vboxmanage --version
5.2.6r120293

Ansible show as being uninstalled, but runs when after vagrant up, why is that?

C:\WINDOWS\system32>ansible --version
'ansible' is not recognized as an internal or external command,
operable program or batch file.


```

### Your OS
 - **Windows** 10

### Full console output
skipping: [agency]

TASK [geerlingguy.varnish : Copy varnish secret.] ******************************
skipping: [agency]

TASK [geerlingguy.varnish : Ensure Varnish services are started and enabled on startup.] ***
skipping: [agency] => (item=varnish)

TASK [geerlingguy.varnish : Ensure Varnish services are started enabled on startup (Xenial specific)] ***
skipping: [agency] => (item=varnish)

TASK [geerlingguy.nginx : Include OS-specific variables.] **********************
skipping: [agency]

TASK [geerlingguy.nginx : Define nginx_user.] **********************************
skipping: [agency]

TASK [geerlingguy.nginx : Enable nginx repo.] **********************************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
skipping: [agency]

TASK [geerlingguy.nginx : Add PPA for Nginx.] **********************************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx will reinstall if the PPA was just added.] ***
skipping: [agency]

TASK [geerlingguy.nginx : Update apt cache.] ***********************************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
skipping: [agency]

TASK [geerlingguy.nginx : Update pkg cache.] ***********************************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
skipping: [agency]

TASK [geerlingguy.nginx : Create logs directory.] ******************************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
skipping: [agency]

TASK [geerlingguy.nginx : Create logs directory.] ******************************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx is installed.] **************************
skipping: [agency]

TASK [geerlingguy.nginx : Remove default nginx vhost config file (if configured).] ***
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx_vhost_path exists.] *********************
skipping: [agency]

TASK [geerlingguy.nginx : Add managed vhost config files.] *********************
skipping: [agency] => (item={u'is_php': True, u'root': u'/var/www/agency/docroot', u'server_name': u'agency.local www.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/opt/adminer', u'server_name': u'adminer.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/usr/share/php/xhprof_html', u'server_name': u'xhprof.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/usr/share/php/pimpmylog', u'server_name': u'pimpmylog.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/var/www/dashboard', u'server_name': u'192.168.25.10 dashboard.agency.local'})

TASK [geerlingguy.nginx : Remove managed vhost config files.] ******************
skipping: [agency] => (item={u'is_php': True, u'root': u'/var/www/agency/docroot', u'server_name': u'agency.local www.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/opt/adminer', u'server_name': u'adminer.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/usr/share/php/xhprof_html', u'server_name': u'xhprof.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/usr/share/php/pimpmylog', u'server_name': u'pimpmylog.agency.local'})
skipping: [agency] => (item={u'is_php': True, u'root': u'/var/www/dashboard', u'server_name': u'192.168.25.10 dashboard.agency.local'})

TASK [geerlingguy.nginx : Remove legacy vhosts.conf file.] *********************
skipping: [agency]

TASK [geerlingguy.nginx : Copy nginx configuration in place.] ******************
skipping: [agency]

TASK [geerlingguy.nginx : Ensure nginx is started and enabled to start at boot.] ***
skipping: [agency]

TASK [drupalvm.www : Define drupalvm_webserver_user (Debian).] *****************
ok: [agency]

TASK [drupalvm.www : Define drupalvm_webserver_user (RedHat).] *****************
skipping: [agency]

TASK [drupalvm.www : Register information about the /vagrant directory.] *******
ok: [agency]

TASK [drupalvm.www : Ensure a group with the same GID as used to sync directories exist (Ansible 2.3+).] ***
skipping: [agency]

TASK [drupalvm.www : Ensure the webserver user is in the same group as the owner of synced directories (Ansible 2.3+).] ***
ok: [agency]

TASK [drupalvm.www : Detect if group used to sync directories already exist (Ansible 2.2).] ***
skipping: [agency]

TASK [drupalvm.www : Ensure a group with the same GID as used to sync directories exist (Ansible 2.2).] ***
skipping: [agency]

TASK [drupalvm.www : Ensure the webserver user is in the same group as the owner of synced directories (Ansible 2.2).] ***
skipping: [agency]

TASK [drupalvm.www : Ensure admin group exist.] ********************************
ok: [agency]

TASK [drupalvm.www : Ensure vagrant user is in admin group.] *******************
ok: [agency]

TASK [drupalvm.www : Set nicer permissions on Apache log directory.] ***********
ok: [agency]

TASK [geerlingguy.drupal : Add backwards-compatibility shims.] *****************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.drupal/tasks/backwards-compatibility.yml for agency

TASK [geerlingguy.drupal : build_makefile shim] ********************************
skipping: [agency]

TASK [geerlingguy.drupal : build_composer shim] ********************************
skipping: [agency]

TASK [geerlingguy.drupal : build_composer_project shim] ************************
skipping: [agency]

TASK [geerlingguy.drupal : install_site shim] **********************************
skipping: [agency]

TASK [geerlingguy.drupal : drupalvm_database shim] *****************************
skipping: [agency]

TASK [geerlingguy.drupal : Check if Drupal is already set up.] *****************
ok: [agency]

TASK [geerlingguy.drupal : Define drush_path if it's not already defined.] *****
skipping: [agency]

TASK [geerlingguy.drupal : Define drupal_site_exists.] *************************
ok: [agency]

TASK [geerlingguy.drupal : Ensure drupal_deploy_dir directory exists.] *********
skipping: [agency]

TASK [geerlingguy.drupal : Check out Drupal to the docroot.] *******************
skipping: [agency]

TASK [geerlingguy.drupal : Check if a composer.json file is present.] **********
skipping: [agency]

TASK [geerlingguy.drupal : Run composer install if composer.json is present.] ***
skipping: [agency]

TASK [geerlingguy.drupal : Define drupal_deploy_updated] ***********************
ok: [agency]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [agency]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [agency]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [agency]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [agency]

TASK [geerlingguy.drupal : Check if a project specific Drush binary exists.] ***
ok: [agency]

TASK [geerlingguy.drupal : Use project specific Drush if available.] ***********
ok: [agency]

TASK [geerlingguy.drupal : include] ********************************************
skipping: [agency]

TASK [geerlingguy.security : Include OS-specific variables.] *******************
skipping: [agency]

TASK [geerlingguy.security : Install fail2ban.] ********************************
skipping: [agency]

TASK [geerlingguy.security : Install fail2ban.] ********************************
skipping: [agency]

TASK [geerlingguy.security : Ensure fail2ban is running and enabled on boot.] ***
skipping: [agency]

TASK [geerlingguy.security : Update SSH configuration to be more secure.] ******
skipping: [agency] => (item={u'regexp': u'^PasswordAuthentication', u'line': u'PasswordAuthentication no'})
skipping: [agency] => (item={u'regexp': u'^PermitRootLogin', u'line': u'PermitRootLogin no'})
skipping: [agency] => (item={u'regexp': u'^Port', u'line': u'Port 22'})
skipping: [agency] => (item={u'regexp': u'^UseDNS', u'line': u'UseDNS no'})
skipping: [agency] => (item={u'regexp': u'^PermitEmptyPasswords', u'line': u'PermitEmptyPasswords no'})
skipping: [agency] => (item={u'regexp': u'^ChallengeResponseAuthentication', u'line': u'ChallengeResponseAuthentication no'})
skipping: [agency] => (item={u'regexp': u'^GSSAPIAuthentication', u'line': u'GSSAPIAuthentication no'})
skipping: [agency] => (item={u'regexp': u'^X11Forwarding', u'line': u'X11Forwarding no'})

TASK [geerlingguy.security : Add configured user accounts to passwordless sudoers.] ***

TASK [geerlingguy.security : Add configured user accounts to passworded sudoers.] ***

TASK [geerlingguy.security : Install yum-cron.] ********************************
skipping: [agency]

TASK [geerlingguy.security : Ensure yum-cron is running and enabled on boot.] ***
skipping: [agency]

TASK [geerlingguy.security : Configure autoupdates (RHEL 7).] ******************
skipping: [agency]

TASK [geerlingguy.security : Install unattended upgrades package.] *************
skipping: [agency]

TASK [geerlingguy.security : Copy unattended-upgrades configuration files in place.] ***
skipping: [agency] => (item=10periodic)
skipping: [agency] => (item=50unattended-upgrades)

TASK [Do not accept locale environment variables passed over SSH.] *************
ok: [agency]

TASK [Allow client to pass PHP and XDEBUG environment variables over SSH.] *****
ok: [agency] => (item=PHP_IDE_CONFIG)
ok: [agency] => (item=XDEBUG_CONFIG)
ok: [agency] => (item=PHP_OPTIONS)

TASK [Check if local known_hosts file is present.] *****************************
ok: [agency]

TASK [Copy known_hosts file from host into Drupal VM.] *************************
skipping: [agency]

TASK [Set SSH home directory.] *************************************************
ok: [agency]

TASK [Install extra apt packages (if any are configured).] *********************
ok: [agency] => (item=[u'sqlite'])

TASK [Install extra yum packages (if any are configured).] *********************
skipping: [agency] => (item=[])

TASK [Detect if AppArmor is working.] ******************************************
 [WARNING]: Consider using service module rather than running service
ok: [agency]

TASK [Ensure MySQL AppArmor profile is disabled (for slow query log).] *********
ok: [agency]

TASK [Restart the AppArmor if necessary.] **************************************
skipping: [agency]

TASK [Check if local Drush configuration folder exists.] ***********************
skipping: [agency]

TASK [Create Drush configuration folder if it doesn't exist.] ******************
skipping: [agency]

TASK [Configure host machine drush aliases.] ***********************************
skipping: [agency]

TASK [Ensure drush directory exists for vagrant user inside VM.] ***************
ok: [agency]

TASK [Configure drush aliases for vagrant user inside VM.] *********************
skipping: [agency]

TASK [Ensure drush directory exists for root user inside VM.] ******************
ok: [agency]

TASK [Configure drush aliases for root user inside VM.] ************************
skipping: [agency]

TASK [Ensure configured cron jobs exist in user account's crontab.] ************

TASK [Ensure the dashboard directory exists.] **********************************
ok: [agency]

TASK [Copy dashboard page into place.] *****************************************
ok: [agency]

TASK [Copy phpinfo file into place.] *******************************************
ok: [agency]

TASK [Run configured post-provision shell scripts.] ****************************
failed: [agency] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.sh) => {"changed": false, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.sh", "msg": "Could not find or access '../../../acquia/blt/scripts/drupal-vm/post-provision.sh'\nSearched in:\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/files/../../../acquia/blt/scripts/drupal-vm/post-provision.sh\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/../../../acquia/blt/scripts/drupal-vm/post-provision.sh\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/files/../../../acquia/blt/scripts/drupal-vm/post-provision.sh\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/../../../acquia/blt/scripts/drupal-vm/post-provision.sh"}
        to retry, use: --limit @/vagrant/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
agency                     : ok=208  changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

### Summary

I am trying to upgrade a site to 8.5 and have required the following in composer.json:
        "acquia/blt": "9.x-dev",
        "acquia/lightning": "3.1.x-dev",
         "geerlingguy/drupal-vm": "4.7.2"

Composer builds the site fine (using Windows 10 WSL for that).
But vagrant up fails with the above message.
Perhaps this is a BLT issue rather than a Drupal VM issue?

Note from above, ansible fails to run in the Windows command prompt but vagrant up is able to run ansible, not sure why that is?

C:\WINDOWS\system32>ansible --version
'ansible' is not recognized as an internal or external command,
operable program or batch file.

**Comment by geerlingguy** [comment]
@captaindav - The error message:

```
TASK [Run configured post-provision shell scripts.] ****************************
failed: [agency] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.sh) => {"changed": false, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.sh", "msg": "Could not find or access '../../../acquia/blt/scripts/drupal-vm/post-provision.sh'\nSearched in:\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/files/../../../acquia/blt/scripts/drupal-vm/post-provision.sh\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/../../../acquia/blt/scripts/drupal-vm/post-provision.sh\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/files/../../../acquia/blt/scripts/drupal-vm/post-provision.sh\n\t/vagrant/vendor/geerlingguy/drupal-vm/provisioning/../../../acquia/blt/scripts/drupal-vm/post-provision.sh"}
```

indicates this is a problem with the BLT post provision script (`/acquia/blt/scripts/drupal-vm/post-provision.sh`) and not with Drupal VM.

I would suggest opening an issue in the BLT issue queue to troubleshoot further: https://github.com/acquia/blt

**Comment by captaindav** [comment]
Thanks, will do!  I was able to get around this issue by first running composer to install the dev versions of Core 8.5, BLT, and Lighting (all of which require Drush 9 and  PHP 7.1).  Then I switched the branch back to my 8.4 branch, and I built a VM there, then switched back to the 8.5 branch.  So now the 8.5 branch has a working VM but is hitting other errors.

**Comment by captaindav** [comment]
This issue was continued in the BLT issue queue: https://github.com/acquia/blt/issues/2560
