### ISSUE TITLE
Windows stuck on "Authentication failure" on vagrant up

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#170]
Trying to get this up on Windows for the first time and it is saying Authentication failure... and I can see in the GUI that it is asking for a login. It shouldn't be though, right?

Are there any additional steps needed to setup Windows hosts?

**Comment by geerlingguy** [comment]
Nothing else should be required for windows desktops—however, I've never tried it from a laptop without admin privileges, so maybe there's a UAC problem with Vagrant and/or VirtualBox?

**Comment by geerlingguy** [comment]
@kevinquillen - Also, can you get a screenshot or even copy+paste of the output with the failure? Would be helpful to see the context.

**Comment by kevinquillen** [comment]
![pasted_image_at_2015_07_14_09_04_am](https://cloud.githubusercontent.com/assets/362176/8673802/840cc9d8-2a07-11e5-9c43-5ffb4eb1e265.png)

**Comment by kevinquillen** [comment]
Similar issue: https://teamtreehouse.com/forum/when-i-type-vagrant-up-i-get-an-authentication-error

**Comment by kevinquillen** [comment]
This is what I had to do:

* Delete insecure_private_key in .vagrant.d/
* Run vagrant ssh-config
* vagrant halt
* vagrant up

**Comment by geerlingguy** [comment]
@kevinquillen - I think we can add a note to the Windows documentation page (so others with the same problem can find a solution) and then I'll mark this fixed. I haven't heard the same thing happening to many others, but I'm sure it will happen again, so thanks for posting the solution!
