### ISSUE TITLE
Uninstalling unneeded things in later re-provisioning?

### ISSUE THREAD

**Issue by siliconmeadow** [geerlingguy/drupal-vm#1703]
### Issue Type

 - Bug Report / Support Request

### My Environment

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.4.3.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/rsheppard/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.14 (default, Jan  5 2018, 10:41:29) [GCC 7.2.1 20171224]
```

### My OS

 - **Linux** (Arch 4.15.3-2-ARCH x86_64)

### Summary

In my `config.yml` file, I originally enabled a few things in a fit of enthusiasm, such as Solr and Varnish, but I haven't had any need for them, and Solr in particular is using processor resources unnecessarily.

It would appear that commenting out the items in the `config.yml` file and then doing a `vagrant provision` doesn't set the state to absent. It seems like that would be a cool thing to do. No?

**Comment by FinBoWa** [comment]
Wilt ansible and also with other provision system the idea is that you scrap the provisioned box if you need to do major changes. Or add your own task that removes added libraries
