### ISSUE TITLE
Ansible version check is done on host even when force_ansible_local: true

### ISSUE THREAD

**Issue by stevekeiretsu** [geerlingguy/drupal-vm#1704]
### Issue Type

 - Bug Report / Support Request

An inadequate host ansible version forces `vagrant up` to fail even when the host ansible is irrelevant because `force_ansible_local: true` has been specified.

### Your Environment

```
DrupalVM 4.8.0
Vagrant 2.0.1
```
(the other bits of that command to paste don't seem to work on this setup, not really important anyway)

### Your OS

 - **Windows** (10)
 

### Full console output

vagrant up
You must install an Ansible version >= 2.2 to use this version of Drupal VM.

### Summary

config.yml contains

`force_ansible_local: true` since I am running Win10 host and cannot get up-to-date ansible installed, somehow, I do have an out of date version though (via babun).

The vagrantfile here:

https://github.com/geerlingguy/drupal-vm/blob/2432f60bbc0fc05bc28b05eb05ab137ec771bcea/Vagrantfile#L40

is checking the version outside of the if (host)/else (guest) block above it.  Therefore it refuses to progress even though the inadequate version of ansible detected will never be used given the config.yml setting.  This seems contrary to the expected behaviour of this flag - as per https://github.com/geerlingguy/drupal-vm/issues/1209#issuecomment-285559568 it should force use of ansible within the VM and therefore host version is irrelevant and no reason to fail.

For my own purposes, I fixed this by simply commenting out the version check on line 40, and everything works fine.  For everyone elses, I would hazard this could be fixed by moving line 40 to line 34, I can open a PR doing that, but I wonder if you would know better so I stuck with an issue for now instead.

**Comment by geerlingguy** [comment]
Yikes, you're right! This isn't _too_ commonly encountered, but there are definitely cases where it could happen (like you've seen).

Can you see if the fix in the commit above (https://github.com/geerlingguy/drupal-vm/commit/8c0f5d64e3b785797b8b769466c72eb928dde352) works for you?

**Comment by geerlingguy** [comment]
Seems like it should work okay (just tested locally, but only quickly). I'm going to go ahead and merge that branch. Please let me know if you still have any issues after pulling the latest fix!

**Comment by stevekeiretsu** [comment]
Yup, that works as expected.  Nice one.

(By the way, thanks for this project, very useful, I've used it for a while at work on osx)
