### ISSUE TITLE
Unable to run 'vagrant up' on Mac

### ISSUE THREAD

**Issue by bpenny** [geerlingguy/drupal-vm#1706]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
$ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 2.7.10 (default, Jul 15 2017, 17:16:57) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS** (10.13.3)
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.3
BuildVersion:	17D102
```

### Full console output
https://gist.github.com/bpenny/f56bbeb84b549d32920ddccb7cb0ebf6

### Summary
Followed the instructions as outlined.
- Downloaded files
- renamed yml files
- Ran **vagrant up**

The following error appears:

```
$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["snapshot", "1cde1c6b-3f51-4b52-bd33-29ee6190d00d", "list", "--machinereadable"]

Stderr: VBoxManage: error: The object functionality is limited
VBoxManage: error: Details: code E_ACCESSDENIED (0x80070005), component MachineWrap, interface IMachine, callee nsISupports
VBoxManage: error: Context: "LockMachine(a->session, LockType_Shared)" at line 331 of file VBoxManageSnapshot.cpp
```

I have tried uninstalling and reinstalling both Vagrant and Virtualbox.

What else can I run to help troubleshooting this issue?

**Comment by bpenny** [comment]
I can see from the error **E_ACCESSDENIED** there is likely a permission issue, but I do not know where to look.

**Comment by bpenny** [comment]
I have not changed any permissions on the system.
This worked months ago on this same machine - other than OS updates, not much changed.

The error references VBoxManage 
- This is installed in **/usr/local/bin**
- Has the following permissions:  **-rwxr-xr-x   1 root    wheel        77 Jan 15 10:29 VBoxManage**

Not sure what else I could provide that would be relevant at this stage.

**Comment by bpenny** [comment]
I opened up the VirtualBox GUI and saw a few "older" items in the VirtualBox Manager.
I proceeded to remove these (right click > Remove) and low and behold the "vagrant up" command worked as expected.

I "think" the problem was that the previous directory I used when I first created my virtual environment was removed and left these items orphaned.  Just my guess.

Closing out issue.

**Comment by apparatchiki** [comment]
This just happened to me, thank you for leaving this last comment as that was exactly my problem, an orphaned Image.
