### ISSUE TITLE
Use drush sql-cli < dump.sql inside vagrant with the vagrant user.

### ISSUE THREAD

**Issue by renzit** [geerlingguy/drupal-vm#1707]
- Support Request

### Summary
First, thanks for all the effort and work done in this VM.
Now the little issue i got is a simple question and is how can i manage to have the right permission to make a  drush sql-cli < database.sql and import a database without the sql pro(in mac) , or the workbench(in linux).
So , what would you reccomend for: 
1)How are you doing a Fast sql import?
2) Change permission to use inside vagrant with the vagrant user, the option drush sql-cli < dump.sql 

Thank you

**Comment by geerlingguy** [comment]
@renzit - This is a question better asked somewhere like https://drupal.stackexchange.com — basically there are many different ways to set up Drush inside or outside the VM to achieve the goal of importing databases either locally or even from a remote server directly. Also check out Acquia's BLT project for how they do it using Robo + Drush.
