### ISSUE TITLE
I get "Fatal error: Class '__TwigTemplat..." when opening http://drupalvm.dev/ the first time

### ISSUE THREAD

**Issue by muckinger** [geerlingguy/drupal-vm#171]
I've installed the box with standard-settings on windows 8. "Vagrant up" runs without problems, but when opening the main page "http://drupalvm.dev/" i get the following error: 

*Fatal error: Class '__TwigTemplate_f305a23152ea0b264f4edf7e8dc43a4352e711c39cf4c314aeaa7d21078de7d5' not found in /var/www/drupal/core/lib/Drupal/Core/Template/TwigEnvironment.php on line 141*

Can there be a permission problem?

Best
M.

**Comment by muckinger** [comment]
FYI: Seems to be a known problem. But i've destroyed the box and added the patch like mentioned in https://www.drupal.org/node/2429659#comment-10084004 , but still doesn't work. 

Also adding "mount_options: ['dmode=775,fmode=664']" to config.yml didn't help :-(

**Comment by geerlingguy** [comment]
@muckinger - If you refresh the page again, does that error go away? That issue is the same issue I've been running into when installing Drupal 8 via drush.

**Comment by geerlingguy** [comment]
Also, after you destroy the box, are you also deleting the entire contents of `~/Sites/drupalvm` locally? Otherwise, Drush might not apply the patch correctly from the makefile.

Finally, what is the OS you're using, and are you using the default NFS option for the vagrant share?

**Comment by muckinger** [comment]
Hi @geerlingguy ,

- the error doesn't go away, i can refresh multiple times.
- i've also tried to destroy the box and also deleted the whole content of the shared folder... still the same
- Like mentiond, i use Windows 8 with Virtualbox 4.2.36 and vagrant 1.7.2. So i can't use NFS, vagrant automatically fall back on windows to the standard (and slow) virtualbox-share

**Comment by geerlingguy** [comment]
Hmm... in that case, it might be advantageous to try some of the tips on this page: http://docs.drupalvm.com/en/latest/other/windows/

Could you also try installing the `vagrant-winnfsd` plugin and see if NFS will work for you with that plugin installed?

**Comment by geerlingguy** [comment]
I'm going to close this for now—first, the Twig race condition should hopefully now be solved, and second, other race conditions (which you might also be facing) are currently documented in some of the few remaining 'critical' D8 issues... hopefully once we get to a release candidate these strange and seldom bugs will disappear entirely!

I also wish I knew someone with an old Win 7 or Win 8 device I could have to run tests on Windows. I haven't had access to a Windows device for 2 years now!
