### ISSUE TITLE
Provisioning stuck at 'install required dependencies' task: reinstall nfs server helps

### ISSUE THREAD

**Issue by aranarthtelcontar** [geerlingguy/drupal-vm#1710]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.4.3.0
```

### Your OS

 - **Linux** (17.10)

### Summary

As I could resolve the issue I will spare everyone with error messages.

I am still learning drupal and web design in general and do definitely lack many skills. I am writing this report in order to save someone like me from wasting time, e.g. two days like me. It is more like a reminder as I should have known better much earlier.

I wanted to vagrant destroy and up a vm. As described during provisioning I got stuck at 'install required dependencies'. The thing is that before I had the same problem. At that time, however, I ran an earlier version of the nfs-kernel-server (don't remember the version). Then I could see with <code>service nfs-kernel-server status</code> that the NFS server was down.

After the update to nfs-kernel-server to 1:1.3.4-2.1ubuntu2 when I ran into the same problem, however, it showed an active state. I was assuming that it was a network issue.

In the end I was puzzling when I thought of reinstalling the nfs server. A purge and install, nevertheless, fixed everything.

I have not come across anything on the web about getting stuck at installing required dependencies. I want to rectify this and help the few unlucky fellows who run into the same issue.

**Comment by geerlingguy** [comment]
So I guess, is the gist of what you're saying that uninstalling and reinstalling NFS fixed the issue?

**Comment by aranarthtelcontar** [comment]
Yes, all I'm saying is that if there are problems with provisioning, one of the first things to do is to check the nfs server (if that's what's being used for sync). Of course one of the main issues here is the firewall but even if it seems fine uninstalling and reinstalling the nfs server might help.

**Comment by aranarthtelcontar** [comment]
Yes, all I'm saying is that if there are problems with provisioning, one of the first things to do is to check the nfs server (if that's what's being used for sync). Of course one of the main issues here is the firewall but even if it seems fine uninstalling and reinstalling the nfs server might help.

**Comment by geerlingguy** [comment]
Ah I see! Well, I'll close out the issue for now, but it shall forever be searchable for others who might run into the same issue. Good to know a reinstall may be in order sometimes :O
