### ISSUE TITLE
Adding the MSSQL driver support during Vagrant Up

### ISSUE THREAD

**Issue by kydho** [geerlingguy/drupal-vm#1714]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

### Your OS

 - **macOS** (10.12.6)

### Summary

I am building a Drupal application that needs to connect with a MSSQL database for some data. I'm not quite sure how to tell DrupalVM to install the MSSQL driver according to Microsoft's instructions for Ubuntu at the following URL:

https://www.microsoft.com/en-us/sql-server/developer-get-started/php/ubuntu/

Starting with the section "Step 1.2 Install PHP and other required packages".

Thanks in advance.

**Comment by geerlingguy** [comment]
Wow... uh, that's a lot of steps to get that working. Since Drupal VM doesn't officially support MSSQL, I'm going to close this issue—however, I'd suggest asking any follow-up questions in the Ubuntu stack exchange here: https://askubuntu.com

That community should be able to offer ample assistance in getting you started with this process. As far as Drupal VM goes, you can provision the VM (`vagrant up` or `vagrant provision`) then after that's done `vagrant ssh` in and run all the commands to complete the MSSQL stuff.

Or you could automate it so you can rebuild the VM from scratch whenever if you put all the relevant commands into a shell script or Ansible task file using [post-provision scripts](http://docs.drupalvm.com/en/latest/extending/scripts/). Good luck!

**Comment by kydho** [comment]
For anyone who is interested I added the following to /provisioning/playbook.yml to install MSSQL Server and also the PHP drivers for MSSQL:

`
- name: Install MSSQL Server and the PHP Driver for MSSQL Server
      shell: |
        curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -
        curl https://packages.microsoft.com/config/ubuntu/16.04/mssql-server-2017.list | tee /etc/apt/sources.list.d/mssql-server-2017.list
        curl https://packages.microsoft.com/config/ubuntu/16.04/prod.list | tee /etc/apt/sources.list.d/mssql-tools.list
        apt-get update
        SA_PASSWORD=Yukon900 ACCEPT_EULA=Y apt-get -y install mssql-server mssql-tools unixodbc-dev php-pear gcc g++ make autoconf libc-dev pkg-config unixodbc-dev
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /home/vagrant/.bash_profile
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> /home/vagrant/.bashrc
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bash_profile
        echo 'export PATH="$PATH:/opt/mssql-tools/bin"' >> ~/.bashrc
        source ~/.bashrc
        MSSQL_PID=Express SA_PASSWORD=Yukon900 ACCEPT_EULA=Y /opt/mssql/bin/mssql-conf setup
        sqlcmd -S localhost -U sa -P Yukon900 -Q "CREATE DATABASE SampleDB;"
        pecl install sqlsrv pdo_sqlsrv
        echo "extension=pdo_sqlsrv.so" >> /etc/php/7.1/apache2/php.ini
        echo "extension=sqlsrv.so" >> /etc/php/7.1/apache2/php.ini
        echo "extension=pdo_sqlsrv.so" >> /etc/php/7.1/cli/php.ini
        echo "extension=sqlsrv.so" >> /etc/php/7.1/cli/php.ini
        echo "extension=pdo_sqlsrv.so" >> /etc/php/7.1/fpm/php.ini
        echo "extension=sqlsrv.so" >> /etc/php/7.1/fpm/php.ini
`
Obviously it's a quick and dirty way of doing it, but I'm posting it here to hopefully start a discussion on getting implemented in a better way. But it does work.

**Comment by kartagis** [comment]
Unfortunately, I got the below errors when I did php -v 

```
PHP Warning:  PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: undefined symbol: php_pdo_register_driver), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0

Warning: PHP Startup: Unable to load dynamic library 'pdo_sqlsrv.so' (tried: /usr/lib/php/20190902/pdo_sqlsrv.so (/usr/lib/php/20190902/pdo_sqlsrv.so: undefined symbol: php_pdo_register_driver), /usr/lib/php/20190902/pdo_sqlsrv.so.so (/usr/lib/php/20190902/pdo_sqlsrv.so.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```
