### ISSUE TITLE
Unsure exactly where to customize VM in BLT project

### ISSUE THREAD

**Issue by arisaves** [geerlingguy/drupal-vm#1715]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.2
VirtualBox 5.2.8r121009
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/ahylas/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_1/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  1 2018, 19:26:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### Your OS
 - **macOS** (version)

### Summary
I'm using DrupalVM with BLT and want to add bcmath (for Drupal Commerce) to my build; I see the documentation says to duplicate default.config.yml to config.yml and edit that, but the only config.yml I see [other than the one in my vendor directory] is in my /box directory, which is included in my .gitignore and meant to be generated dynamically. I'm still unclear on where I should really be customizing the installed_extras and other params for my vm.

**Comment by geerlingguy** [comment]
This is a question best suited for the Acquia BLT issue queue: https://github.com/acquia/blt/issues

Off-hand, I don't remember where exactly the customizations go in a BLT project (I'm tempted to say inside a 'vm' folder?). The BLT docs might also have more information there.
