### ISSUE TITLE
I keep getting error message that is Failed to create the host-only adapter

### ISSUE THREAD

**Issue by msaus** [geerlingguy/drupal-vm#1716]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.2
VirtualBox 5.1.30
Windows 10
```

### Your OS
 - **Windows10 

### Full console output
C:\Users\desk62\vagrant\drupal>vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Fixed port collision for 35729 => 35729. Now on port 2201.
==> default: Fixed port collision for 22 => 2222. Now on port 2202.
==> default: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "create"]

Stderr: 0%...
Progress state: E_FAIL
VBoxManage.exe: error: Failed to create the host-only adapter
VBoxManage.exe: error: Querying NetCfgInstanceId failed (0x00000002)
VBoxManage.exe: error: Details: code E_FAIL (0x80004005), component HostNetworkInterfaceWrap, interface IHostNetworkInterface
VBoxManage.exe: error: Context: "enum RTEXITCODE __cdecl handleCreate(struct HandlerArg *)" at line 94 of file VBoxManageHostonly.cpp

### Summary
I kept failing vagrant up and I also try following, but, it dose not work at all.
https://www.virtualbox.org/ticket/14040

Moreover,
I upgraded vagrant from 1.9 to 2.0.2 today, but, dose not work again.

Dose anyone know how to fix this issue?

Best regards,

**Comment by FinBoWa** [comment]
As DV handles only the provision part of a functional box and that requires that vagrant and virtualbox works right so the best location to find help for Vagrant or VirtualBox would be their issue ques.

For example, albeit old issue, https://github.com/docker/machine/issues/2465#issuecomment-164731528 suggests on reinstalling virtualbox.

**Comment by FinBoWa** [comment]
Also are you running multiple virtual boxes with the same IP address? Maybe try to shut down the others and try again.

**Comment by msaus** [comment]
I have 2 vm running on the same machine, but, public ip and private ip address are allocated for each vm.
So, I guess this shouldn't be problem.

**Comment by FinBoWa** [comment]
Possible solution: 

https://stackoverflow.com/questions/33725779/failed-to-open-create-the-internal-network-vagrant-on-windows10

If that doesn't work then the comment 20 on this And this suggests on https://www.virtualbox.org/ticket/14545#comment:20

Doing the following:

> I was able to work around this problem for me with the following steps:
> Open the VirtualBox Manager GUI.
> Go to File -> Preferences -> Network -> Host-only Networks
> Delete all entries in that list
> Run vagrant up again

**Comment by msaus** [comment]
Sorry for late reply.

I figure this out today.

I did not notice that private_network id is defined on line 11.

Where I defined is very bottom.

But, thanks for your help :)

**Comment by waltervanrooyen** [comment]
Hi all,

Im seeing a lot of work around solutions for this. I seemed to have found a much simpler method.

Simply go to user account control setting and pull the slider all the way down (Windows 10 security is so amazing :p)
