### ISSUE TITLE
Create documentation for using xdebug with eclipse

### ISSUE THREAD

**Issue by ashabed** [geerlingguy/drupal-vm#1719]
### Issue Type
 - Documentation Report

### Summary

Students of DebugAcademy.com use the free Eclipse IDE with DrupalVM, and we have recorded steps for integrating the two.

This task is **for an upcoming sprint** on March 11, 2018 (please do not complete this task so it is available for new contributors).

One of the sprint-attendees will submit a pull request with the documentation addition.

**Comment by valeygal1990** [comment]
I completed this task

https://github.com/geerlingguy/drupal-vm/pull/1720

-Valentine S.

**Comment by geerlingguy** [comment]
@valeygal1990 - Thanks!
