### ISSUE TITLE
Vagrant up stuck at TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] ***

### ISSUE THREAD

**Issue by sajalsoni** [geerlingguy/drupal-vm#1722]
### Issue Type

 - Bug Report / Support Request

### Your Environment
Ubuntu 17.10

```
Vagrant 2.0.2

ansible --version
The program 'ansible' is currently not installed. To run 'ansible' please ask your administrator to install the package 'ansible'

VirtualBox `vboxmanage --version`
Qt WARNING: libpng warning: iCCP: known incorrect sRGB profile
```

### Your OS

Ubuntu 17.10

### Full console output

TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] ***
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["cp", "-r", "/tmp/composer-project/.", "/var/www/drupalvm/drupal/"], "delta": "0:27:46.141111", "end": "2018-03-12 05:49:35.892693", "msg": "non-zero return code", "rc": 1, "start": "2018-03-12 05:21:49.751582", "stderr": "cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-48c9cdbe12a3a81828c0383abb8d1bd48d7a8209.pack': Permission denied\ncp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-48c9cdbe12a3a81828c0383abb8d1bd48d7a8209.idx': Permission denied\ncp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/chi-teck/drupal-code-generator/templates/d7/hook/field_formatter_settings_form.twig': Permission denied", "stderr_lines": ["cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-48c9cdbe12a3a81828c0383abb8d1bd48d7a8209.pack': Permission denied", "cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-48c9cdbe12a3a81828c0383abb8d1bd48d7a8209.idx': Permission denied", "cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/chi-teck/drupal-code-generator/templates/d7/hook/field_formatter_settings_form.twig': Permission denied"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=179  changed=2    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by sajalsoni** [comment]
I fixed that by running "vagrant provision".

**Comment by geerlingguy** [comment]
It looks like permission issues:

```
cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-48c9cdbe12a3a81828c0383abb8d1bd48d7a8209.pack': Permission denied
```

Are you saying it worked fine if you ran `vagrant provision` again? Or are you still having some problems?

**Comment by sajalsoni** [comment]
@geerlingguy yeah, it fixed itself when I run "vagrant provision", now e'thing is working good!

**Comment by kiramarch** [comment]
I'm getting a similar error and running "vagrant provision" a few times did NOT help, sadly. Any suggestions? 

I'm on Windows 10, Vagrant 2.2.3, VirtualBox 6.0.2

`
TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a wh ile).] ***                                                                                              fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["cp", "-r", "/tmp/composer-project/.", "/var/ww w/drupalvm/drupal/"], "delta": "0:00:00.004645", "end": "2019-01-21 17:08:20.949210", "msg": "non-zero  return code", "rc": 1, "start": "2019-01-21 17:08:20.944565", "stderr": "cp: cannot create directory '/ var/www/drupalvm/drupal/': Protocol error", "stderr_lines": ["cp: cannot create directory '/var/www/dru palvm/drupal/': Protocol error"], "stdout": "", "stdout_lines": []}                                      [WARNING]: Could not create retry file '/vagrant/provisioning/playbook.retry'.                         [Errno 71] Protocol error: u'/vagrant/provisioning/playbook.retry'                                                                                                                                              PLAY RECAP *********************************************************************                        drupalvm                   : ok=191  changed=2    unreachable=0    failed=1
--
`
