### ISSUE TITLE
Not able to bind custom IP while running Drupal VM with Docker.

### ISSUE THREAD

**Issue by sajalsoni** [geerlingguy/drupal-vm#1723]
I've everything working good when I run following two commands.

docker run -d -p 80:80 -p 443:443 --name=drupalvm --privileged geerlingguy/drupal-vm
docker exec drupalvm install-drupal

Drupal is installed and is available at http://0.0.0.0 and http://localhost. But I was wondering by doing an entry in my hosts file "192.168.88.88  drupalvm.test" it's not working at all! So, I can't access either http://drupalvm.test OR http://192.168.88.88

Any ideas?

**Comment by FinBoWa** [comment]
Hosts file is used to map names to ip address so also that won't per ce bind anything and your docker command does not specify any ip addresses so of course it wont work with 192.168.88.88. 

For docker related questions id suggests on dockers help documentation or Stackoverflow especially this particular answer:

https://stackoverflow.com/a/35450145/1566871

**Comment by sajalsoni** [comment]
How to specify IP in docker command?

**Comment by FinBoWa** [comment]
@sajalsoni the https://stackoverflow.com/a/35450145/1566871 should answer that

**Comment by sajalsoni** [comment]
Ok thanks I will check that, thanks for your reply!!

**Comment by sajalsoni** [comment]
Many thanks @FinBoWa it worked.

**Comment by FinBoWa** [comment]
could you close the issue also so @geerlingguy doesn't have to :D
