### ISSUE TITLE
Error in the playbook: ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

### ISSUE THREAD

**Issue by campbell-t** [geerlingguy/drupal-vm#1724]
### Issue Type
 - Bug Report / Support Request

### My Environment
```
Vagrant 2.0.2
VirtualBox 5.2.0r118431
ansible 2.3.0.0
  config file =
  configured module search path = Default w/o overrides
  python version = 2.7.14 (default, Sep 25 2017, 09:53:22) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.37)]
```

### My OS
 - **macOS** 10.12.6

### Console output
While running `vagrant up`

```
==> project_vm: Running provisioner: ansible...
Vagrant has automatically selected the compatibility mode '2.0'
according to the Ansible version installed (2.3.0.0).

Alternatively, the compatibility mode can be specified in your Vagrantfile:
https://www.vagrantup.com/docs/provisioning/ansible_common.html#compatibility_mode

    project_vm: Running ansible-playbook...
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/path-to-project/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.git/tasks/main.yml': line 22, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

# Install git from source when git_install_from_source is true.
- import_tasks: install-from-source.yml
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary
I've never come across this issue before with drupal-vm. Error occurs after running `vagrant up`. I've tried destroying the environment and rerunning the command but the error still appears.

If someone knows how to fix this error, that would be greatly appreciated.

**Comment by mikeryan776** [comment]
I just hit this as well, after a composer update which bumped Drupal from 8.4.5 to 8.5.0 and DrupalVM from 4.8.0 to 4.8.1. This happened on

`$ DRUPALVM_ENV=prod ansible-playbook -i vm/inventory vendor/geerlingguy/drupal-vm/provisioning/playbook.yml -e "config_dir=$(pwd)/vm" --become --ask-become-pass --ask-vault-pass --tags=drupal`

No such problem last doing this a couple of weeks ago.

**Comment by mikeryan776** [comment]
Knowing that git is indeed installed, commenting out the contents of main.yml permitted me to proceed.

**Comment by campbell-t** [comment]
Hey Mike, I updated ansible to 2.4 lastnight and it seemed to fix the issue for me. Not sure why 2.3 was causing it to fail.
