### ISSUE TITLE
Where to install npm, angular cli and more ?

### ISSUE THREAD

**Issue by josuevalrob** [geerlingguy/drupal-vm#1727]
### Issue Type
 - Documentation Report

 - **macOS** (version)
### Summary
Hi, I am new to Vagrant, so a little help will be fine! thanks and sorry for this question: 

I want to know where to setup different package for my vagrant environment. For be more specific, the npm, node, angular, etc. I am working on an Angular site, that consumes services from Drupal. 

Looking [this ](https://www.vagrantup.com/intro/getting-started/provisioning.html) and I think that we need a bootstra.sh for installation of different packages... Where is that?

**Comment by oxyc** [comment]
To install npm/node, uncomment `nodejs` in the `installed_extras` list.

```yaml
# Comment out any extra utilities you don't want to install. If you don't want
# to install *any* extras, set this value to an empty set, e.g. `[]`.
installed_extras:
  - adminer
  # - blackfire
  # - drupalconsole
  - drush
  # - elasticsearch
  # - java
  - mailhog
  # - memcached
  # - newrelic
  - nodejs
  - pimpmylog
  # - redis
  # - ruby
  # - selenium
  # - solr
  # - tideways
  # - upload-progress
  - varnish
  # - xdebug
  # - xhprof # use `tideways` if you're installing PHP 7+
```

If you want to install other packages or set specific versions you can find more information in the [docs](http://docs.drupalvm.com/en/latest/extras/nodejs/).
