### ISSUE TITLE
vagrant.config.yml values ignored

### ISSUE THREAD

**Issue by jasloe** [geerlingguy/drupal-vm#1728]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 1.9.4
VirtualBox 5.1.18r114002
ansible 2.4.3.0
```
### Your OS
 - **macOS** (version)

### Summary
My build process adheres to the Composer method described in Soup-to-nuts:
<pre>
composer create-project drupal-composer/drupal-project:7.x-dev drupal --stability dev --no-interaction
</pre>

then into the vendor directory:
<pre>
composer require --dev geerlingguy/drupal-vm
</pre>

and finally customizing vagrant.config.yml, e.g.:
<pre>
vagrant_hostname: local.something.test
vagrant_machine_name: local-something
vagrant_ip: 0.0.0.0
ssh_home: "/var/www/drupal"
</pre>

The playbook doesn't respect my vagrant.config.yml values. It builds the machine as follows: 

<pre>
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Cloning VM...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.test
</pre>

Where drupalvm.test should be local.something.test.

Not seeing anything relevant in the commit history. Ideas?

**Comment by jasloe** [comment]
Huh. Jumped the gun. I blew away my Ansible roles and started from scratch and that seems to have fixed it. Leaving this open until I can replicate again in the morning.

**Comment by FinBoWa** [comment]
As a suggestion: 

Use the vagrant.config.yml only if you actually need to override something for vagrant. Generic configuration settings should go to your own config.yml file.
