### ISSUE TITLE
501 dialout Files and Folders

### ISSUE THREAD

**Issue by lquessenberry** [geerlingguy/drupal-vm#1735]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.3
VirtualBox 5.1.10r112026
zsh: command not found: ansible
```

### Your OS

 - **macOS** (version) High Sierra

### Full console output
-rw-rw-r--  1 501 dialout  385 Mar 19 21:00 autoload.php
drwxrwxr-x 40 501 dialout 1280 Mar 19 21:00 core
-rw-rw-r--  1 501 dialout  549 Mar 19 21:00 index.php
drwxrwxr-x 23 501 dialout  736 Mar 19 21:14 libraries
drwxrwxr-x  5 501 dialout  160 Mar 19 21:19 modules
drwxrwxr-x  4 501 dialout  128 Mar 19 21:14 profiles
-rw-rw-r--  1 501 dialout 1596 Mar 19 21:00 robots.txt
drwxrwxr-x  7 501 dialout  224 Mar 19 21:36 sites
drwxrwxr-x  5 501 dialout  160 Mar 19 21:32 themes
-rw-rw-r--  1 501 dialout  848 Mar 19 21:00 update.php
-rw-rw-r--  1 501 dialout 4555 Mar 19 21:00 web.config

### Summary

Seems like permissions and ownership are getting changed to this 501 dialout garbage in Vagrant. I thought I had it fixed, but nyet.

**Comment by FinBoWa** [comment]
They aren't changed to anything. That's the representation of your host computers files group id and user id on the vagrant box tough the NFS. Eg the id matches on some of them. 

Drupal vm does various combat the write issues with these groups but the best way to fix some of them is just to rm -rf and use composer reinstall them back if some update doesnt work. 

Assuming you have the latest version of drupalvm. 

I'v opened another issue on this also https://github.com/geerlingguy/drupal-vm/issues/1671 and that points how to fix one issue with the permisisons.

**Comment by lquessenberry** [comment]
![bitmoji](https://render.bitstrips.com/v2/cpanel/c10864c1-2acd-4397-89d0-3a5667aab6d2-c550f9f8-a8fd-487f-9609-bc173830b1e9-v1.png?transparent=1&palette=1&width=246)

If you have time maybe you could show me exactly what I need to do.

**Comment by FinBoWa** [comment]
Just  `rm -rf vendor`, if the composer installed files have write issues, in host (or with sudo from box, but will probably fail) and run `composer install` again in the box, or stick to running composer install on the host if possible. 

And adding the vagrant user to the group is just matter of running commands under the box https://www.cyberciti.biz/faq/howto-linux-add-user-to-group/ 

```
useradd -G vagrant_group vagrant
```
Just to note: adding the user to the group MIGHT not fix this particular but havent had issues on magento 2 after that.

**Comment by oxyc** [comment]
A quick solution could also be to use [`vagrant-bindfs` (docs)](http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/#using-vagrant-bindfs-to-work-around-permissions-related-errors) although it comes with some performance overhead and _should_ not be needed.

**Comment by geerlingguy** [comment]
I would recommend using `vagrant-bindfs` if this is an ongoing issue; other than that usually deleting the folder that's causing grief is the next best alternative. Often, that's all that's required to get things working again.

Closing this issue for now, but please let us know if it's still broken for you.

**Comment by wdseelig** [comment]
I think I understand what is going on here.  When you create a new account on a Mac, you are, behind the scenes, assigned user and group ids (uid,gid), and the default, for the first user created, is (501,20).  On the Mac, group 20's name is "staff".  In the vagrant box, there is no user 501, but there is a group 20, and it is dialout.  This, I think, is why we see what we see.

I was having great difficulty using drush on my vagrant machine, and also found that I could not ftp in new modules in Drupal, but it occurred to me that I might be able to fix that by editing /etc/passwd.  On the vagrant machine, the user number for www-data is 33, so I changed that to 501.  Voila, the owner name of the files changed to www-data and, even better, drush would now work.

Hope this helps somebody.
