### ISSUE TITLE
Vagrant Up fail on install - "failed: [d85vm] (item=drupal/devel:1.x-dev"

### ISSUE THREAD

**Issue by stephencross** [geerlingguy/drupal-vm#1743]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Vagrant 1.9.1
VirtualBox 5.1.28r117968
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/stephencross/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.4.3.0_4/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar  9 2018, 23:57:12) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

### Your OS

 - **macOS** (10.13.2)

### Full console output

https://gist.github.com/stephencross/a5a7d16b8c2c642b66937570a1b61b66

### Summary

Using DrupalVM with config, as is, only changed vagrant_host and vagrant_machine.   On vagrant up, get error:  

TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***
failed: [d85vm] (item=drupal/devel:1.x-dev) => {"changed": false, "item": "drupal/devel:1.x-dev", "msg": "./composer.json has been updated > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Package operations: 1 install, 0 updates, 0 removals - Installing drupal/devel (dev-1.x 46ca997): Cloning 46ca997758 from cache 46ca997758a9f95b40749b40989d153daefc957e is gone (history was rewritten?) [RuntimeException] Failed to execute git checkout '46ca997758a9f95b40749b40989d153daefc957e' -- && git reset --hard '46ca997758a9f95b40749b40989d153daefc957e' -- fatal: reference is not a tree: 46ca997758a9f95b40749b40989d153daefc957e require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", "stdout": "./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nPackage operations: 1 install, 0 updates, 0 removals\n  - Installing drupal/devel (dev-1.x 46ca997): Cloning 46ca997758 from cache\n    46ca997758a9f95b40749b40989d153daefc957e is gone (history was rewritten?)\n\n                                                                                                                                                  \n  [RuntimeException]                                                                                                                              \n  Failed to execute git checkout '46ca997758a9f95b40749b40989d153daefc957e' -- && git reset --hard '46ca997758a9f95b40749b40989d153daefc957e' --  \n                                                                                                                                                  \n  fatal: reference is not a tree: 46ca997758a9f95b40749b40989d153daefc957e                                                                        \n                                                                                                                                                  \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...\n\n", "stdout_lines": ["./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Package operations: 1 install, 0 updates, 0 removals", "  - Installing drupal/devel (dev-1.x 46ca997): Cloning 46ca997758 from cache", "    46ca997758a9f95b40749b40989d153daefc957e is gone (history was rewritten?)", "", "                                                                                                                                                  ", "  [RuntimeException]                                                                                                                              ", "  Failed to execute git checkout '46ca997758a9f95b40749b40989d153daefc957e' -- && git reset --hard '46ca997758a9f95b40749b40989d153daefc957e' --  ", "                                                                                                                                                  ", "  fatal: reference is not a tree: 46ca997758a9f95b40749b40989d153daefc957e                                                                        ", "                                                                                                                                                  ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", ""]}

**Comment by sajalsoni** [comment]
I too am facing similar issue.

If I run the "vagrant up" command by just checking out Drupal-VM, it goes OK.

But, I want to run two instances of DrupalVM, so I checked out Drupal-VM to some other directory as well and changed following.

vagrant_hostname: drupalvm.test.81
vagrant_machine_name: drupalvm.81
vagrant_ip: 192.168.88.81

And now it stops exactly at above error mentioned by @stephencross!

**Comment by sajalsoni** [comment]
Seems that it ends somewhere at:

Could not delete web/core/.nfs0000000000180e3700000001:  ", "......

**Comment by rootwork** [comment]
@sajalsoni I haven't encountered this error, but I generally use a different hostname at the same TLD. So instead of doing:

> vagrant_hostname: drupalvm.test.81
> vagrant_machine_name: drupalvm.81
> vagrant_ip: 192.168.88.81

Try:

> vagrant_hostname: newname.test
> vagrant_machine_name: newname
> vagrant_ip: 192.168.88.81

There's no requirement that you use "drupalvm" as the host or machine name. I usually change mine to match whatever the URL of the site is that I'm working on.

**Comment by sajalsoni** [comment]
@rootwork Ok thanks, I'll try it!

**Comment by geerlingguy** [comment]
@sajalsoni - How did that work out?

**Comment by sajalsoni** [comment]
@geerlingguy Nope, I halt all the other instances to avoid any conflicts , but still not working. Basically, what I'm trying to do atm is to run it on behalf of Jenkins user.

$sudo su jenkins
$cd /var/lib/jenkins/workspace/Vagrant-DrupalVM
$vagrant up

It stops at:
TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***

and long message that ends with
Could not delete web/core/.nfs0000000000180e3700000001: ", "......

And finally,

PLAY RECAP *********************************************************************
d85vm                      : ok=194  changed=73   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I'm wondering the same if working OK if I run it from my user at "/home/sajal". But, it creates issues while running it on behalf of Jenkins user.

**Comment by imshuffling** [comment]
I'm having the same issue here, anyone managed to replicate and solve it?

Cheers.

**Comment by nickgee** [comment]
Hi all,

I had the same thing happen to me today whilst trying to identify a bug in a Drupal project on a clean install.

Changing: 

`drupal/devel:1.x-dev`

to

`drupal/devel:^1.2`

in config.yml fixed it for me.

Thanks for all the tinkering @geerlingguy !

**Comment by imshuffling** [comment]
Thanks @nickgee - fixed it for me also.

**Comment by geerlingguy** [comment]
Testing that fix in my Drupal role and in this project. I haven't updated that dependency in a very long time!

**Comment by geerlingguy** [comment]
See above commit, which includes the fix for the Drupal role defaults as well. Thanks!
