### ISSUE TITLE
Drupalvm as a composer dependency...different php version on host

### ISSUE THREAD

**Issue by MichaelMallett** [geerlingguy/drupal-vm#1747]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.1
VirtualBox 5.0.8r103449
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/Mike/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 30 2018, 15:55:25) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)
All!

### Summary

I've been working on a base project for our drupal 8 projects that uses drupalvm as a composer dependency. I'm curious how to get this working if there is a conflict with the host machines php versions. 

Because everything in the drupal-composer template exists in the composer.json at the project root, this means that if there is a conflict with PHP versions on the host machine there is a problem with composer install. IE

1. User needs to run composer install to get drupalvm (in the dev dependencies) - has 5.6 on host.
2. User needs to vagrant up and run composer install INSIDE the vm to have the correct composer dependencies installed for the project, which is php 7.1

Without separate composer.json files for the vm and the project, it seems there is a weakness in this flow. Ideally it would be possible to install a single package, drupalvm, then continue to 2, but I can't seem to find a way to do that. And putting drupalvm in separate composer.json kind of nullifies the point of having it as a composer dependency imo, and complicates things.

Does anyone have any thoughts here? Trying to minimise friction on different platforms for our developers and this is one of the last sticking points.

**Comment by joestewart** [comment]
If I understand the questions, set the platform to the minimum php version required:

https://github.com/drupal-composer/drupal-project/blob/8.x/README.md#how-do-i-specify-a-php-version-

**Comment by MichaelMallett** [comment]
I don't think that helps me. Because the minimum php version required will be satisfied by the VM. But the host machine may still only have 5.6 available on it. Usually the solution to this is to have drupalvm installed through git and then run composer install inside the vm, but this isn't much use if you want to have drupalvm as a composer dependency.

It's a bit of a chicken and egg thing, you want the vm so that you have the right environment to run composer install, but you need to run composer install to get that environment in the first place

**Comment by thom8** [comment]
Set the platform config https://getcomposer.org/doc/06-config.md#platform - this way the correct versions will be installed no matter what PHP version composer is using.

**Comment by MichaelMallett** [comment]
Ah right, gotcha. Thanks @thom8, sorry @joestewart I misread your suggestion.

Re upgrading to 7.1, yeah I will absolutely suggest the upgrade this is mainly for ease of use when on-boarding contractors
