### ISSUE TITLE
drupal-vm:4.8.1 Docker image fails to build when php7.1-bz2 is added in

### ISSUE THREAD

**Issue by gabe-connolly** [geerlingguy/drupal-vm#1753]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
Docker version 18.03.0-ce, build 0520e24
```

### Your OS
 - **macOS** (version)

### Full console output
```
Setting up php7.1-bz2 (7.1.16-1+0~20180405085419.16+stretch~1.gbp4937aa) ...

Creating config file /etc/php/7.1/mods-available/bz2.ini with new version
Setting up php7.1-cli (7.1.16-1+0~20180405085419.16+stretch~1.gbp4937aa) ...
Setting up php7.1-dev (7.1.16-1+0~20180405085419.16+stretch~1.gbp4937aa) ...
Setting up php7.1-fpm (7.1.16-1+0~20180405085419.16+stretch~1.gbp4937aa) ...

Configuration file '/etc/php/7.1/fpm/pool.d/www.conf'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
*** www.conf (Y/I/N/O/D/Z) [default=N] ? dpkg: error processing package php7.1-fpm (--configure):
 end of file on stdin at conffile prompt
Errors were encountered while processing:
 php7.1-fpm
E: Sub-process /usr/bin/dpkg returned an error code (1)
ERROR: Service 'myproject' failed to build: The command '/bin/sh -c apt-get update && apt-get install -y php7.1-bz2' returned a non-zero code: 100
```

### Summary
Starting 2018-04-05 my Drupal-VM Docker builds are failing because of a configuration conflict with '/etc/php/7.1/fpm/pool.d/www.conf'.  In my Dockerfile my dependency installation block is as follows:
```
RUN apt-get update && apt-get install -y \
    apt-utils \
    imagemagick \
    jq \
    nano \
    php7.1-bz2 \
    wget \
    && apt-get autoremove
```

When I remove php7.1-bz2 from the dependencies, the build completes without errors, but I am unable to complete a `composer install` on the project since phantomjs requires the bz extension:
`jakoch/phantomjs-installer 2.1.1-p07 requires ext-bz2 * -> the requested PHP extension bz2 is missing from your system`

I have tried calling the bz2 package as both `php7.1-bz2` and `php-bz2`, but without luck in either case.  

I have done some research and it looks like I can override the config issue in the build process by explicitly setting the configuration options to use (`apt-get --yes --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold"`), but this feels like a brute force approach to the issue.  

Is there a cleaner way to make sure that the bz2 extension is available in the drupal-vm docker container?

**Comment by geerlingguy** [comment]
Can you try:

```
RUN apt-get update && apt-get install -o Dpkg::Options::="--force-confold" -y \
    apt-utils \
    imagemagick \
    jq \
    nano \
    php7.1-bz2 \
    wget \
    && apt-get autoremove
```

And see if that works?

**Comment by geerlingguy** [comment]
Also, can you post a complete Dockerfile I can use to reproduce this issue (removing any proprietary bits of course)?

**Comment by geerlingguy** [comment]
Using this Dockerfile worked:

```
FROM geerlingguy/drupal-vm:latest

RUN apt-get update && apt-get install -o Dpkg::Options::="--force-confold" -y \
    php7.1-bz2 \
    && apt-get autoremove
```

So it looks like just adding `-o Dpkg::Options::="--force-confold"` to the install command should get you there. Please re-open if this is not the case!

**Comment by gabe-connolly** [comment]
@geerlingguy confirmed: adding `-o Dpkg::Options::="--force-confold"` allowed my build to complete without errors. Thanks for taking a look!
