### ISSUE TITLE
Test and support Ubuntu 18.04 Bionic Beaver

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1760]
### Issue Type

 - Feature Idea

### Summary

Ubuntu 18.04 Bionic Beaver was officially released today. I have boxes and images:

  - https://app.vagrantup.com/geerlingguy/boxes/ubuntu1804 (for Vagrant)
  - https://hub.docker.com/r/geerlingguy/docker-ubuntu1804-ansible/

At a minimum, test everything on 18.04 and see if it works. Then add it as a suggested option in the config. Then at some point we'll have a discussion about when to switch the default to it (or something else someday!).

**Comment by geerlingguy** [comment]
Added one test in Travis; definitely too early to switch to 18.04 as a default, but we'll give it a few months (maybe half a year?) and reconsider.

Here's the current test run: https://travis-ci.org/geerlingguy/drupal-vm/builds/372191869

**Comment by geerlingguy** [comment]
Aww, the container won't even start currently.

**Comment by kburakozdemir** [comment]
> Aww, the container won't even start currently.

Not sure if this helps... Just a feedback...

I am using 18.04 as my main OS and there seems to be no problem. However, I am trying to install Ubuntu 18.04 (and its variants) with a desktop environment as a virtual machine in VirtualBox and I cannot manage to install one. Installation always crashes.

```
VirtualBox Graphical User Interface
Version 5.2.18 r124319 (Qt5.9.5)
```

**Comment by geerlingguy** [comment]
Most of the roles I'm using are supporting 18.04 just fine now. Might test again.

**Comment by geerlingguy** [comment]
Oh that's fun... `easy_install` is not included in `python-setuptools` in 18.04? https://bugs.launchpad.net/ubuntu/+source/python-setuptools/+bug/1774419

**Comment by geerlingguy** [comment]
Now getting:

```
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["hostname", "--file", "/etc/hostname"], "delta": "0:00:00.035678", "end": "2018-11-21 19:02:25.457368", "msg": "non-zero return code", "rc": 1, "start": "2018-11-21 19:02:25.421690", "stderr": "hostname: you must be root to change the host name", "stderr_lines": ["hostname: you must be root to change the host name"], "stdout": "", "stdout_lines": []}
```

At least there's progress! :)

**Comment by geerlingguy** [comment]
Just realized I didn't have a condition to add `--privileged` to the 18.04 build Docker options... adding that now, and it should allow iptables, hostname, etc.

**Comment by geerlingguy** [comment]
It's a-workin! Merging the tests and will leave off changing the base drupal-vm box to 18.04 until I get ready for a 5.0.0 release.
