### ISSUE TITLE
Docker xdebug php_xdebug_remote_host

### ISSUE THREAD

**Issue by mdance** [geerlingguy/drupal-vm#1767]
### Issue Type

 - Bug Report

### Your Environment

```
Vagrant 2.0.3
VirtualBox 5.2.8r121009
ansible 2.6.0 (devel dabe5e6d07) last updated 2018/04/09 22:03:49 (GMT -600)
  config file = /Users/md/.ansible.cfg
  configured module search path = ['/Users/md/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Users/md/Programs/ansible/lib/ansible
  executable location = /Users/md/Programs/ansible/bin/ansible
  python version = 3.6.5 (default, Apr  9 2018, 21:51:02) [GCC 4.2.1 Compatible Apple LLVM 7.3.0 (clang-703.0.31)]
```

### Your OS

 - **macOS** 10.13.4

### Full console output

N/A

### Summary

I am running docker for mac and after running docker-compose up -d, and attempting an xdebug session it appears as though the container is unable to connect to the phpstorm debugger on port 9000.

In the past, I have gotten this to work by setting the php_xdebug_remote_host to host.docker.internal/docker.for.mac.localhost as suggested at the following link, but this no longer works:

https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds

**Comment by geerlingguy** [comment]
@mdance - Did you add the port (`9000:9000`) to the `ports` list in the docker compose file?

E.g. in this part:

```yaml
  myproject:
    image: geerlingguy/drupal-vm
    container_name: myproject
    ports:
      - 80:80
      - 443:443
      - 9000:9000
```

Otherwise Docker won't expose that port on your host, and your editor/browser won't be able to connect on 9000.

**Comment by geerlingguy** [comment]
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!
