### ISSUE TITLE
Daemonize fails to install on Ubuntu 14.04

### ISSUE THREAD

**Issue by upchuk** [geerlingguy/drupal-vm#1771]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/upchuk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS** (10.13.4)

### Full console output

```
TASK [geerlingguy.daemonize : Download daemonize archive.] *********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: SysCallError: (104, 'Connection reset by peer')
fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "failed to create temporary content file: (104, 'Connection reset by peer')"}
```

### Summary

Hey there, so on a brand new Mac with latest vbox, vagrant and ansible, Mailhog is a nogo due to the dependency on Daemonize which for some reason doesn't install. I checked and the URL it tries to download the package from works so not sure what the issue is.

Initially I used ansible from the box, but then installed it also on the Mac and set the `force_ansible_local` to false. But same issue.

This happens with ubuntu1404 not ubuntu1604.

Any clue @geerlingguy ? Cheers

**Comment by geerlingguy** [comment]
So it only happens if you set the base box to `ubuntu1404`? The error code seems to indicate it could be a temporary networking issue; is this still happening if you try again?

**Comment by upchuk** [comment]
@geerlingguy Yes, tried multiple times, even the next day, no dice. Changed the box, and it worked.

**Comment by geerlingguy** [comment]
This could be an upstream issue, maybe the repo dropped Daemonize for 14.04?

**Comment by geerlingguy** [comment]
At some point, I'm going to replace daemonize with supervisord anyways :P https://github.com/geerlingguy/drupal-vm/issues/1400

**Comment by geerlingguy** [comment]
I also just ran a test install on the upstream role's CI build, and it passed on Ubuntu 14.04: https://travis-ci.org/geerlingguy/ansible-role-daemonize/jobs/380801801

I'm going to test locally with a Drupal VM instance and my ubuntu1404 base box to see if it fails here.

**Comment by geerlingguy** [comment]
Everything seemed to install correctly when I had the following `config.yml` with everything else default:

```yaml
---
vagrant_box: geerlingguy/ubuntu1404
installed_extras:
  - drush
  - mailhog
```

Is there any chance you have a proxy on your network, or a VPN or something that could be blocking the download?

**Comment by upchuk** [comment]
@geerlingguy Seems ok as well with a clean setup. But if I add drupalconsole to the extras, it fails for some reason. I kept removing item by item till i reached this one. 

I thought maybe fails due to some other package that gets installed before, but enabled xdebug (which does install before) but it continues fine. So something off there with drupalconsole.

**Comment by geerlingguy** [comment]
@upchuk weird. I've been thinking about removing Drupal Console from the installed_extras since it's best to install it with your codebase anyways. This is another argument in favor of doing that.

**Comment by upchuk** [comment]
@geerlingguy Indeed. Another one is that if you need Drupal console, you are using D8, which means you should be using 1604 :)

**Comment by geerlingguy** [comment]
At this point, I'm not supporting Ubuntu 14.04 much anymore, so I'd recommend moving off of it to 16.04 or 18.04 ASAP. Going to close this as a 'won't fix'.
