### ISSUE TITLE
Unable to use Acquia's Default VCL file with DrupalVM

### ISSUE THREAD

**Issue by jasonawant** [geerlingguy/drupal-vm#1777]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.0.2
VirtualBox 5.1.14r112924
-bash: ansible: command not found
```

### Your OS
macOS

### Full console output

> > RUNNING HANDLER [geerlingguy.varnish : restart varnish] ************************
> fatal: [project]: FAILED! => {"changed": false, "msg": "Unable to restart service varnish: Job for varnish.service failed because the control process exited with error code. See \"systemctl status varnish.service\" and \"journalctl -xe\" for details.\n"}

The output of `systemctl status varnish.service` is as follows

> * varnish.service - Varnish Cache, a high-performance HTTP accelerator
>    Loaded: loaded (/lib/systemd/system/varnish.service; enabled; vendor preset: enabled)
>    Active: failed (Result: exit-code) since Wed 2018-05-16 16:31:11 UTC; 14min ago
>   Process: 11006 ExecStart=/usr/sbin/varnishd -a :80 -T 127.0.0.1:6082 -P /run/varnishd.pid -f /etc/varnish/default.vcl -S /etc/varnish/secret -s file,/var/lib/varnish/varnish_storage.bin,256M (code=exited, statu
>  Main PID: 814 (code=exited, status=0/SUCCESS) 

When attempting to validate the vcl file, I had to add the version, vcl 4.0. and validating the syntax within the VM using , I get this error. 

> Error:
> Message from VCC-compiler:
> Symbol not found: 'std.tolower' (expected type STRING_LIST):
> ('/etc/varnish/default.vcl' Line 67 Pos 35)
> set req.http.X-Acquia-Purge = std.tolower(req.http.X-Acquia-Purge);
> ----------------------------------###########--------------------------
> 
> Running VCC-compiler failed, exited with 2
> VCL compilation failed

### Summary
When using Acquia's default vcl file, provisioning fails and I'm unable to validate the vcl file. I have set `varnish_default_vcl_template_path` with the vcl file path relative to the playbook.yml  file found in /vendor/geerlingguy/drupal-vm/provisioning. I have verified the contents of the /etc/varnish/default.vcl within the VM.

**Comment by geerlingguy** [comment]
It sounds like `std.tolower` might be unsupported in the version of Varnish installed in Drupal VM. I don't know all the custom things Acquia's default VCL does, nor do I remember the specific version of Varnish Acquia hosting has by default... I would ask Acquia support if you have an Acquia subscription to assist in porting their VCL to something like Drupal VM; I can only support the VCL that ships with Drupal VM or with the `geerlingguy.varnish` role.

**Comment by jasonawant** [comment]
Thanks for the response. I figured I maybe asking too much. Previous attempt with Acquia support results in the same; they didn't support local dev envs :(.
