### ISSUE TITLE
Specific version of Elasticsearch to install

### ISSUE THREAD

**Issue by joshuaboltz** [geerlingguy/drupal-vm#1784]
### Issue Type
 - Feature Idea

### Your Environment
- Drupal VM

### Your OS
 - **macOS** (10.13.4)

### Summary
- During a vagrant provision process, it would be nice to specific the version of Elasticsearch to install, similar to how a specific version of Solr can be configured in the config.yml
- This is important since Drupal Search API doesn't always support the latest versions right away, and maybe other complexities in the way of using the latest version

Since I'm not sure where this issue actually fits, cross-linking to https://github.com/hashicorp/vagrant/issues/9894

**Comment by geerlingguy** [comment]
The Elasticsearch version is now configurable—see https://github.com/geerlingguy/ansible-role-elasticsearch#role-variables

It defaults to 6.x, but I think at least 5.x also works. I haven't tested with any older version than that though.
