### ISSUE TITLE
The boxes cannot be found (404 errors)

### ISSUE THREAD

**Issue by justageek** [geerlingguy/drupal-vm#1785]
### Issue Type

Cannot bring up the box at all

 - Bug Report / Support Request

Mac OS 10.12.6

Vagrant 1.8.6
VirtualBox 5.1.22r115126
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/briansmith/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]

macOS 10.12.6

### Full console output

vagrant up                                
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
The box 'geerlingguy/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1604"]
Error: The requested URL returned error: 404 Not Found

### Summary

The error is above.

**Comment by geerlingguy** [comment]
It is likely this is an error due to the Vagrant version you're running. Please upgrade to the latest version (2.something now) and try again. Thanks!
