### ISSUE TITLE
Configuration error while Vagrant up, plugins installed

### ISSUE THREAD

**Issue by Steelsector** [geerlingguy/drupal-vm#1786]
### Issue Type

- Bug Report / Support Request

### Your Environment

Vagrant 1.9.5, Version 5.1.38 r122592 (Qt5.6.2)

### Your OS

 - **Windows** 10 PRO 64bit

### Full console output

https://gist.github.com/Steelsector/d12834f2c4bb2999454cabf665608cf7

### Summary

Hi,
I'm trying to set up my work environment on a Windows machine, I did it before on my personal laptop with the same vagrant version, everything works fine on that machine but on this new one it's not.
I have all the plugins installed and tried out multiple versions of vagrant and virtualbox as well, from the most up to date one back to this current one, and all of them had the same issue.
I have tried out the solutions I have found here or anywhere else nothing worked.

I really want to have this on this machine as I don't want to work on Mac anymore. 

Thanks

**Comment by arunavak111** [comment]
Could you please verify you have following configuration items in your box.yml files.

- cache
- hostmanager

**Comment by Steelsector** [comment]
You mean in the config.yml?
vagrant_plugins:
  - name: vagrant-hostmanager
  - name: vagrant-vbguest
  - name: vagrant-bindfs
  - name: vagrant-cachier

**Comment by Ornitier** [comment]
Got similar here : #1741

**Comment by geerlingguy** [comment]
Please merge comments with / subscribe to #1741, which is the original issue for this problem. It seems like it may be an upstream bug in Vagrant.
