### ISSUE TITLE
Vagrant provision getting failed with post-provision scripts

### ISSUE THREAD

**Issue by arun9989** [geerlingguy/drupal-vm#1787]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant - 2.0.1
VirtualBox - 5.1.22r115126
BLT - ^9.0.3
Drupal VM - ^4.8
```

### Your OS

 - **Windows** (10 64bit)

### Full console output

https://gist.github.com/arunavak111/d8ea65357f8ab68d2e3b791a158e9a85

### Summary

I am using vagrant and virtual vox in my windows 10 64 bit machine. And trying to setup drupal vm without ubuntu bash. Hence, once the VM is ready I can run blt commands inside vm. I ran 'vagrant up' command using powershell.exe(with Admin rights) and it creates a new virtual machine and its in Running state. But when I run 'vagrant provision' command at the end of the process I am getting following error:

> TASK [Run configured post-provision shell scripts.] ****************************
failed: [myproject] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.php) => {"changed": true, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.php", "msg": "non-zero return code", "rc": 127, "stderr": "/usr/bin/env: 'php\\r': No such file or directory\n", "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/vagrant/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry

>PLAY RECAP *********************************************************************
>myproject                : ok=227  changed=0    unreachable=0    failed=1

>Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

As a result, local site is not loading and blt commands not working inside vm.

**Comment by geerlingguy** [comment]
This is a BLT issue; Drupal VM doesn't ship with any enabled post provision scripts. I would recommend posting this issue to the Acquia BLT issue queue. Thanks!
