### ISSUE TITLE
MySQL Error on re-provision

### ISSUE THREAD

**Issue by ejdunn2001** [geerlingguy/drupal-vm#1788]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible 2.5.4
  config file = None
  configured module search path = [u'/Users/edunn/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Applications/MAMP/Library/lib/python2.7/site-packages/ansible
  executable location = /Applications/MAMP/Library/bin/ansible
  python version = 2.7.13 (default, Nov 27 2017, 14:49:20) [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.54)]
```

### Your OS

 - **macOS** High Sierra
 

### Full console output

https://gist.github.com/ejdunn2001/7267adf41ffff91ce510e364f4c784bb

### Summary

I have had to adjust several settings for php and xdebug since we are still using php5.6. Whenever I try to run `vagrant up --provision` or `vagrant provision` I get this error. I usually have to destroy the vm and start over to test the changes.

**Comment by geerlingguy** [comment]
It looks like the error is thus:

```
{"host": "%", "name": "root", "password": "root", "priv": "dvinci_com.*:ALL"}
  "msg": "(1396, \"Operation CREATE USER failed for '********'@'%'\")"}
```

You seem to have a `root` user defined inside the `mysql_users` config setting. The root user is supposed to _only_ be managed by the MySQL role, and only additional users (e.g. a `dvinci` user or something like that) would be added under `mysql_users`. If you only need a root user account for local development, you can just not set anything under `mysql_users`.
