### ISSUE TITLE
Make a GitLab optimized Docker instance

### ISSUE THREAD

**Issue by cosmicdreams** [geerlingguy/drupal-vm#1789]
So I see how you've added a Docker instance for drupal-vm and it's supposed to do a lot of things.  But when I use it with gitlab-ci it doesn't work because it needs the bz2 php extension.  I don't if that's missing because the docker instance isn't running the ansible playbook.  I certainly don't see in my log that it runs but maybe what is shipped is a docker instance after all the playbook parts is done.

While in the process of getting an instance work properly with gitlab-ci I've run into a lot of problems.  Including writing a proper .gitlab-ci.yml file it would be great if we spent some time trying to optimize the docker instance or create a new one that resolves all the issues a person runs into getting this to work with gitlab.

**Comment by cosmicdreams** [comment]
I've figured out how to install the bz2 library manually but would love to chat about what this docker instance really needs in order to be useful.  Kind of looks like the docker instance would benefit from having blt installed or at least provide an option for getting a docker instance with that installed.

**Comment by cosmicdreams** [comment]
If we want to get gitlab stuff to work the same way as the travis stuff we'll also need to get phpenv to work.

**Comment by cosmicdreams** [comment]
My main issue is that I don't think the ansible is running

**Comment by geerlingguy** [comment]
@cosmicdreams - For now the Docker setup is a bit experimental, and is meant to be used just for quick testing purposes or a simple local environment. Technically you could use it as an upstream image and have a Dockerfile that scaffolds the rest of the stuff you need manually, but at this point that's all a bit unsupported (at least officially speaking).

**Comment by cosmicdreams** [comment]
I've been trying to figure stuff out on my own and have a .gitlab-ci.yml pretty close to being able to build everything.  Is that something you would want to include?  (this is why I was trying to get the Docker stuff to work).

**Comment by geerlingguy** [comment]
Just wondering what would be the primary benefit of having .gitlab-ci.yml in the main repository?

**Comment by cosmicdreams** [comment]
Having that file in the repo would signal to projects that are hosted in a Gitlab repository that it has support for Gitlab's CI/CD process. 

Properly supporting the Ci/CD process will also mean providing proper guidance on how to create a new SSH key and then using that key with your Acquia repo in order to have the proper rights to push artifacts in.  

(that's the part I'm stuck at).

**Comment by geerlingguy** [comment]
Hmm... but if Drupal VM is a dependency of the project, wouldn't the project itself have its own setup for CI/CD? Sort of the model Acquia BLT uses (not sure if it provides a built-in GitLab config, but I know it has a BitBucket pipelines config, Travis CI config, or Acquia pipelines config built into the tool so you can add one to your project.

**Comment by cosmicdreams** [comment]
I have successfully gotten Drupal VM to work with Gitlab's CI .  I had to make the processing single-staged.  and I had to ensure that I properly injected the SSH private key and hashed known host into the docker instance.  Here's my .gitlab-ci.yml:

`image: geerlingguy/drupal-vm

stages:
  - deploy

variables:
  APP_NAME: my_project_name
  COMPOSER_BIN: $CI_PROJECT_DIR/vendor/bin
  BLT_DIR: $CI_PROJECT_DIR/vendor/acquia/blt
  BUILD_DIR: $CI_PROJECT_DIR

before_script:
  - mkdir -p ~/.ssh
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$Acquia_key" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 700 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - echo "$KNOWN_HOSTS" | tr -d '\r' > ~/.ssh/known_hosts

develop:
  stage: deploy
  script:
    - ansible-playbook /etc/ansible/drupal-vm/provisioning/playbook.yml
    - apt-get update -yqq && apt-get install -o Dpkg::Options::="--force-confold" -y php7.1-bz2 libxml2-dev libssl-dev libz-dev libbz2-dev libmcrypt-dev pkg-config bison openssl re2c
    - apt-get autoremove
    - composer validate --no-check-all --ansi
    - composer install
    - source ${BUILD_DIR}/ci/setup_environment
    - source ${BUILD_DIR}/ci/setup_project
    - "${BLT_DIR}/scripts/travis/deploy_branch"
    - echo "Launching develop artifact"
  environment:
    name: develop_artifact
    url: https://$APP_NAMEdev.acquia-sites.com
  artifacts:
    paths:
      - $CI_PROJECT_DIR/deploy
  only:
    - develop

staging:
  stage: deploy
  script:
    - ansible-playbook /etc/ansible/drupal-vm/provisioning/playbook.yml
    - apt-get update -yqq && apt-get install -o Dpkg::Options::="--force-confold" -y php7.1-bz2 libxml2-dev libssl-dev libz-dev libbz2-dev libmcrypt-dev pkg-config bison openssl re2c
    - apt-get autoremove
    - composer validate --no-check-all --ansi
    - composer install
    - source ${BUILD_DIR}/ci/setup_environment
    - source ${BUILD_DIR}/ci/setup_project
    - "${BLT_DIR}/scripts/travis/deploy_branch"
    - echo "Launching staging artifact"
  environment:
    name: staging_artifact
    url: https://$APP_NAMEstg.prod.acquia-sites.com
  only:
    - master
    - /^release.*$/

production:
  stage: deploy
  script:
    - ansible-playbook /etc/ansible/drupal-vm/provisioning/playbook.yml
    - apt-get update -yqq && apt-get install -o Dpkg::Options::="--force-confold" -y php7.1-bz2 libxml2-dev libssl-dev libz-dev libbz2-dev libmcrypt-dev pkg-config bison openssl re2c
    - apt-get autoremove
    - composer validate --no-check-all --ansi
    - composer install
    - source ${BUILD_DIR}/ci/setup_environment
    - source ${BUILD_DIR}/ci/setup_project
    - "${BLT_DIR}/scripts/travis/deploy_tag"
    - echo "Launching production artifact"
  environment:
    name: production_artifact
    url: https://www.$APP_NAME.com
  only:
    - tags
`

Questions that focus on improving this further:
1. It would be most excellent if I didn't have to run ansible / apt-get at all.  That I could just pull an instance with the all the server / library stuff figured out and all I have to do is my project level stuff.

I gather that it would be possible if I created my own docker instance that is based off of drupalvm but this seems like a common problem with getting drupalvm working on gitlab.  We might want to consider providing a better template for folks that want to use gitlab.

2. I couldn't get two-stage gitlab ci processes to work because I would ultimately have to declare what to copy from stage to stage.  Is there a better way?

**Comment by cosmicdreams** [comment]
I could probably combine the develop and staging steps but wanted to have parity to how travis is typically configured.
