### ISSUE TITLE
Error [Configure VM drush aliases for vagrant user.] when using multiple site 

### ISSUE THREAD

**Issue by sanglt** [geerlingguy/drupal-vm#179]
<img width="1337" alt="screen shot 2015-07-17 at 10 47 18 am" src="https://cloud.githubusercontent.com/assets/128535/8740301/6326eb38-2c71-11e5-8f56-7884b23c7a49.png">
The error is: ~/.drush directory does not exist.
After manual add that directory and run: vagrant provision, its work.

So we should make that directory first, before do the task.

**Comment by geerlingguy** [comment]
This wasn't an issue on my local build (OS X 10.10 with Ubuntu 14.04), but I can see how this could error out in some situations, so I think I can fix it by simply adding two tasks to make sure both `~/.drush` directories exist prior to writing the drush alias files. Testing now...
