### ISSUE TITLE
Solr not setup properly

### ISSUE THREAD

**Issue by vaibhavjain-in** [geerlingguy/drupal-vm#1791]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version                                                                                                                    $RPROMPT_PREFIX$(build_right_prompt)
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible 2.5.3
  config file = None
  configured module search path = [u'/Users/vaibhav.jain/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.3/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:37) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### Your OS

 - **macOS** (version)

### Full console output

none

### Summary

I am using Drupal 8 + BLT + Drupal VM + Acquia search. I did the steps mentioned here http://docs.drupalvm.com/en/latest/extras/solr/.
Updated box/config.yml with
```
installed_extras:
 - solr
solr_version: 4.5.1
post_provision_scripts:
    - ../../../acquia/blt/scripts/drupal-vm/configure-solr.sh
```

Ran vagrant provision, and now I see the solr is not working.
`Note that for Drupal 8, this script will create a new search core named d8` - it did not, I still see collection1, and no d8 named core.

**Comment by geerlingguy** [comment]
@vaibhavjain-in - Note that the instructions assume you're using the script in `"../examples/scripts/configure-solr.sh"`. It looks like you may be using Acquia BLT. I would recommend opening an issue in the BLT issue queue, as their setup differs from the Drupal VM defaults.
