### ISSUE TITLE
Duplicate synced folders

### ISSUE THREAD

**Issue by very-random-man** [geerlingguy/drupal-vm#1792]
### Issue Type

 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible: none
```

### Your OS

 - **Windows 10 WSL / Ubuntu**

### Summary

First of all, great work with this project. Thanks for all your effort! :-)

I've recently started experimenting with a dev environment on Win10 WSL and I've been playing around with various file-based synced folders (such as rsync). I've noticed that all the files appear to be duplicated by default. i.e. `/vagrant` and `/var/www/drupalvm`. I guess it's not important with network based things like NFS but I was wondering if it would be worth changing that second directory to a symlink or even eliminating the second directory and changing the web server config to use the `/vagrant` location?

At the moment having two folders slows down syncing as there is double the work and means plugins like vagrant-unison2 don't work easily (it's expecting to sync only one folder). Plus there's the whole size thing too.

**Comment by very-random-man** [comment]
I've had a chance to look at this more closely and I strongly suspect that this duplication is also interferring with plugins like rysnc-back. The default rsync arguments include `--delete` so any changes made in the drupal working directory can then be immediately undone in the same rsync-back as it does all folders, including /vagrant with an identical target but none of the working directory changes.

In the Vagrantfile it'd be handy if we could specify `rsync__args` for a synced folder in config.yml like we can with excluded paths rather than having to override it in Vagrantfile.local as I've currently put all the WSL config changes in a single config file brought into play by setting DRUPALVM_ENV.

**Comment by geerlingguy** [comment]
I am closing issues more than 6 months old which are not approved feature requests or definitively reproducible bugs affecting most users of Drupal VM; if you feel like this is still a reproducible issue with Drupal VM or something that should still be worked on, please open a new issue in the Drupal VM issue queue. I am trying to clean up some older issues which were hard or impossible to reproduce and debug.

Thank you!
