### ISSUE TITLE
Vagrant provision failing with Ensure PHP packages are installed Task

### ISSUE THREAD

**Issue by arun9989** [geerlingguy/drupal-vm#1794]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
```

### Your OS

 - **macOS** (10.13.3)

### Full console output

https://gist.github.com/arunavak111/13e96a0fd27841d769809e6fcc662c2b

### Summary

Everything was working fine in my machine. But I am not sure what is happened now.

Yesterday in one of my project I just tried to downgrade the blt version. But after that I deleted that project and related vm from my machine. But now `vagrant provision` is not working for none of the project in my machine.

**Comment by geerlingguy** [comment]
Can't see the Gist; please reopen or open a new issue if this is still a problem. Also, don't downgrade BLT... really weird and bad things usually seem to happen when BLT is downgraded :)
