### ISSUE TITLE
Trust self-signed certificates added from root directory

### ISSUE THREAD

**Issue by rupl** [geerlingguy/drupal-vm#1797]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
ansible 2.5.2
  config file = None
  configured module search path = [u'/Users/chris/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.2/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, May  1 2018, 16:44:08) [GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.1)]
```

### Your OS

 - **macOS** (version)

### Full console output

```
vagrant@drupal:~$ curl https://d7-pwa.drupal.vm
curl: (60) server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

### Summary

I'm using your totally awesome VM along with a self-signed cert to develop some PWA stuff. PWA and Service Worker require a functioning SSL cert to install. Trusting the cert on my host machine allows me to load the DrupalVM URL and pretend I have a secure website. And leaving the self-signed certs on the root directory of my DrupalVM auto-copies them to the right place when paired with the right entries in my Ansible config.

However... my contrib module works by allowing the user to specify some paths, and **the VM itself makes HTTP requests to the URLs**, parses the response and caches individual assets within the HTML response. I had to manually edit the `/etc/ssl/certs/ca-certificates.crt` file and add my cert manually to get things humming again.

It's very little manual work, I admit. But it would be very cool if this cert, which is copied as part of the existing ansible process, could also be appended to the trusted list.

The D7 status report was what tipped me off, announcing the following:

> Your system or network configuration does not allow Drupal to access web pages, resulting in reduced functionality. This could be due to your webserver configuration or PHP settings, and should be resolved in order to download information about available updates, fetch aggregator feeds, sign in via OpenID, or use other network-dependent services. If you are certain that Drupal can access web pages but you are still seeing this message, you may add `$conf['drupal_http_request_fails'] = FALSE;` to the bottom of your settings.php file.

**Comment by geerlingguy** [comment]
I think the best way to add in custom certs would be to use a pre or post-provision script; the script would copy the cert into the right place and/or run the command to add the cert to the local store: http://docs.drupalvm.com/en/latest/extending/scripts/

**Comment by rupl** [comment]
ah ok that's perfect! thanks for the tip 💯
