### ISSUE TITLE
playbook does not exist on this guest

### ISSUE THREAD

**Issue by monsterreh2b** [geerlingguy/drupal-vm#1798]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.2
VirtualBox 5.2.12r122591
-bash: ansible: command not found
```

### Your OS

 - **macOS** (version)

### Full console output

https://gist.github.com/monsterreh2b/d62520cabbe88a50bd1feb4d9e4a0451

### Summary

vagrant up attempted twice, 
vagrant provision attempted twice
outcome currently is 

`playbook` does not exist on the guest: /vagrant/provisioning/playbook.yml

**Comment by webprogrammierer** [comment]
I have the same problem and can not get running my Drupal VM.

**Comment by jogranda** [comment]
What was the solution to your issue?
