### ISSUE TITLE
How to downgrade varnish version?

### ISSUE THREAD

**Issue by michaellenahan** [geerlingguy/drupal-vm#1801]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.2.6r120293
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/d440377/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb  7 2017, 00:08:15) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
```

### Your OS

 - **macOS** Sierra 10.12.6

### Summary

Out of the box, I have this version of varnish in drupal-vm:

```
vagrant@drupalvm:/var/www/drupalvm/drupal/web$ varnishd -V
varnishd (varnish-5.1.3 revision 05c5ac6b9)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

To test locally some changes I want to make to my vcl on Acquia Cloud, I need to downgrade to version 4.1

I tried changing the version:

```
# provisioning/roles/geerlingguy.varnish/defaults/main.yml
# change version to 4.1
varnish_package_name: "varnish"
varnish_version: "4.1"
```

... and then running:

```
vagrant provision
```

... but I still get the same version of varnish.

Starting again, with a fresh clone of drupal-vm, and changing the ```varnish_version``` value in ```provisioning/roles/geerlingguy.varnish/defaults/main.yml``` to ```4.1```

... this works correctly:

```
vagrant@drupalvm:/var/www/drupalvm/drupal/web$ varnishd -V
varnishd (varnish-4.1.10 revision 1d090c5a08f41c36562644bafcce9d3cb85d824f)
Copyright (c) 2006 Verdens Gang AS
Copyright (c) 2006-2015 Varnish Software AS
```

... so, I guess I've answered my question: it appears that a change in varnish version is not possible without a fresh rebuild of drupal-vm?

**Comment by geerlingguy** [comment]
Yep, that's the case for the Varnish role; it's meant to install a particular version the first time, but not to switch between versions on an already-running server. If that's a feature you might want to see at some time (and especially if you can implement and test it!) please open an issue in the varnish role repository: https://github.com/geerlingguy/ansible-role-varnish
