### ISSUE TITLE
How to avoid writing host configuration to WINDOWS/system32/drivers/etc/hosts?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#1802]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
drupal-vm-4.9.0
```

### Your OS

 - **Windows 10**

### Full console output

**==> drupalvm: [vagrant-hostsupdater] Removing hosts**
vagrant.d/gems/2.2.5/gems/vagrant-hostsupdater-1.1.1.160/lib/vagrant-hostsupdater/HostsUpdater.rb:117:in `initialize': Permission denied @ rb_sysopen - C:/WINDOWS/system32/drivers/etc/hosts (Errno::EACCES)

### Summary

hostname_configure: false 

I set hostname_configure to false but it still writes the host coniguration to my hosts file.
Because the host file is blocked by Avira the Drupal VM aborts with an error on every vagrant up or vagrant halt.

How can I avoid that the host configuration is written to the windows host file (I will do this manually)???

**Comment by geerlingguy** [comment]
The `hostname_configure` option actually just controls whether the `drupalvm.hostname` role is run or not, for now. It doesn't control whether the Vagrant hostsupdater plugin is used—it is always used at this point.

Before considering changing this default behavior, which would be a breaking change... what is the purpose of Avira? I've never heard of it and haven't seen it come up in any other issues before.

**Comment by webprogrammierer** [comment]
The purpose of Avira is to protect the file "hosts" in Windows 10: No authorized access to hosts.
When I manually want to change the contents of hosts file I have to turn off Avira Live Protect before and turn on again afterwards. This is a great and important protection.

I do not understand what the hostname_configure is for? 

We all had to write the IP addresses into hosts file manually before hostname_configure exists. But we needed to do this only once! And there was no need to remove this entries even if one project was not used anymore ...

But now on every vagrant up or on vagrant halt the contents of hosts file is re-written. This is not necessary, it should be possible to turn this off. 

Or this solution would also be good: 'vagrant halt' should not remove anything from hosts file if this project still exists in config.yml of Drupal VM. If it there still exists no removal is necessary.
vagrant/drupal vm should only write into hosts file if the entries do not exists!

And it should be possible to turn off every writing to host file.

**Comment by webprogrammierer** [comment]
When will this problem be solved and how?

**Comment by geerlingguy** [comment]
@webprogrammierer - Drupal VM aims to make local development environment management for Drupal easier for the majority of users, and one of the things we found that really helps in that regard is the automatic management of the user's hosts file.

It might be possible to override/disable the automatic hosts management behavior by creating a custom Vagrantfile, but I'm not going to spend the time trying to figure out how to do it or add a feature to enable or disable it myself, as I like having Vagrant manage the hostsfile for convenience, and for the vast majority of users, it is a worthwhile convenience as well.

I would suggest either configuring Avira to allow Vagrant to manage the hosts file, or working on a custom local Vagrantfile (see http://docs.drupalvm.com/en/latest/extending/vagrantfile/ for some examples) to override the hosts file behavior.

**Comment by Michel-Settembrino** [comment]
Hi @webprogrammierer,
I follow @geerlingguy his point of view.

I'm sure you can configure Avira in a way to allow this. If not, then I suggest you to change your antivirus because this is a normal configuration an antivirus should allow.

**Comment by webprogrammierer** [comment]
But I am using
hostname_configure: false
and it does not work. What is it for?   hostname_configure  means that hosts file is configured, true? 

The only thing that has to be done is, to make hostname_configure = false work. So everybody can decide if he wants to write to the hosts file on every vagrant up and vagrant halt or not.

If "hostname_configure: false" does not work then this should be corrected or hostname_configure should be removed.

**Comment by geerlingguy** [comment]
`hostname_configure: false` only applies to hostname settings inside the VM, it has no bearing on the behavior of the vagrant-hostsupdater plugin.

**Comment by webprogrammierer** [comment]
I still do not understand what is it for?

And is there now any way to stop updating hosts file on every vagrant up/halt?

**Comment by geerlingguy** [comment]
> I still do not understand what is it for?

When you create a Drupal VM instance, you choose a hostname, like "local.mysite.com", and then you can access your Drupal site at that domain. Drupal VM uses Vagrant, and there's a plugin for Vagrant that automatically adds and removes the hostname (and if you want any other hostnames for the VM) to your hosts file, so you don't have to manually go in and add and remove hostnames to your hosts file.

This way you can access your local development site at the address like "local.mysite.com" instead of something like 123.45.67.82.

**Comment by webprogrammierer** [comment]
Thank you. Yes this ist exactly what I thought 'hostname_configure = true' is for.
But why does 'hostname_configure = false' not work?   hostname_configure = false should stop this writing to hosts file, but it does not. So we do not need this option, if it does nothing. We can remove hostname_configure.

3 month ago I have used an older version of Drupal VM which did not write anything to hosts file. I want this behavior back and many other people also want to have the possiblity to decide by themselve if sometihis is written to hosts file oder not.

If you add an hostname_configure then it should work and it should be backward compitible when setting the value to false.  

Otherwise hostname_configure  is nothing for! You can remove hostname_configure option, if it does nothing, if it does not allow disabling (**always ON does not need an option**).

**Comment by geerlingguy** [comment]
`hostname_configure` _is_ used. It is used here: 
https://github.com/geerlingguy/drupal-vm/blob/4123c545723a322f96fe6f0318c76946438ec9a1/provisioning/playbook.yml#L33

It is used to configure the hostname _inside_ the Drupal VM virtual machine.

It has nothing to do with the Vagrant settings for the vagrant-hostsupdater plugin. If you want to disable that plugin, you can either figure out how to do so using a Vagrantfile.local file (as linked in the docs earlier in this issue's comments), or you can fork Drupal VM and remove the hostsupdater integration.

You can continue discussing things in this issue, but I am closing it as I think the conversation has exhausted all relevant avenues of action. My primary recommendation is to configure your antivirus utility to allow Vagrant to update your system's hosts file, otherwise you have to manually edit the file any time you bring up a new Drupal VM instance.

**Comment by webprogrammierer** [comment]
yes, hostname_configure is used here, as you wrote. But you still did not answer why hostname_configure = false does not work.

If I set hostname_configure to false, what happens then and what is the difference to hostname_configure = true?

Again: Some weeks ago I used an older version of Drupal VM which DID NOT write anything to windows hosts file and this behavior was much much better! **There must be a away to get rid of this new behavior and avoid writing to hosts file. How?**

I am using Drupal VM for many years and all my entries to windows hosts file I only wrote once! All entries of many different projects are still in hosts file, maybe I will use it later again. But every entry has to be written to hosts file only once!

There is absolutely no need to write to hosts file the same thing(s) on every "vagrant up" and delete on every "vagrant halt". This is feature that nobody needs, because writing to hosts file on every up/halt is NOT necessary. Only if a new Drupal VM instance is configured (when a news project is started) the hosts file is needed to be written to. 
If it is not possible to write to hosts file only if things have really changed then there must be a way to shut this feature off.

**Comment by webprogrammierer** [comment]
The question was: How to avoid that something is written to hosts file.

I still don't know how to avoid it.

**Comment by geerlingguy** [comment]
Right now, you can't, unless you either:

  1. Implement some logic to disable the hostsupdater updates (by unsetting the variable or something like that) in a `Vagrantfile.local`.
  2. You or someone else creates a PR that allows the hostsupdater functionality to be controlled by a variable.

**Comment by Michel-Settembrino** [comment]
@geerlingguy, @webprogrammierer,

I implemented option 2. See https://github.com/geerlingguy/drupal-vm/pull/1821

I have no experience with Vagrant and Ruby development, so please be indulgent on the code I wrote. I you have suggestions to improve it, please let me know.

**Comment by oxyc** [comment]
Create a `Vagrantfile.local` with:

```rb
config.vm.networks.each_index do |idx|
  config.vm.networks[idx][1][:hostsupdater] = 'skip'
end
```

**Comment by webprogrammierer** [comment]
I tried now to use the Vagrantfile.local and it works!
Thank you very much!

Before that I tried to use 
`disable_hostsupdater: false`
in config.yml file, but it was ignored.
