### ISSUE TITLE
Is the vbguest plugin required?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1803]
I have encountered a lot of issues in the last week when setting up legacy projects on geerlingguy/ubuntu1404 regarding the VirtualBox Guest Additions. It just hangs on the guest additions installation in terminal.

There was a snafu recently that broke the plugin entirely, requiring updating the vagrant plugin to 0.15.2.

I just destroyed the box and changed my config.yml to use the geerlingguy/ubuntu1604 box instead. The box seems to provision, and provision much faster, so I am not sure if these recent changes have impacted the 1404 in some way.

**Comment by geerlingguy** [comment]
Yeah... so Ubuntu 14.04 is really, really wonky now. I have no idea what happened but I'm hitting a lot of walls when trying to get my box updated!

See: https://github.com/geerlingguy/packer-ubuntu-1404/issues/24

**Comment by geerlingguy** [comment]
Let's merge this ticket into #1807.
