### ISSUE TITLE
Installing stats via PECL doesn't actually enable the module.

### ISSUE THREAD

**Issue by ldpm** [geerlingguy/drupal-vm#1804]
### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 2.1.2
VirtualBox 5.2.12r122591
ansible 2.6.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ldpm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.12 (default, Dec  4 2017, 14:50:18) [GCC 5.4.0 20160609]
```

### Your OS

 - **Linux** (Ubuntu 16.04)

### Summary

TL;DR: I would like to figure out how to automate the enabling of new PHP modules that I include via PECL/PEAR so that I don't have to do it for every vm. I assume I will need to clone an existing Ansible role that does something similar (like geerlingguy.php-xdebug), but since I'm new to Ansible, I'd love to know if that's actually the correct thing and/or if there's something easier.

I'm trying to install the php stats package with PHP 7.0. Based on the discussion surrounding issue #1462 , I added "php-pear" to the "extra_packages" section of my config.yml file, along with
```
php_pecl_extensions:
  - stats-2.0.3
```
So far so good; this caused to the stats.so file to be created, according to pecl list:
```
vagrant@drupalvm:/$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
stats   2.0.3   stable
```
However, it wasn't enabled under any SAPI, and checking phpinfo() in a browser showed that php-fpm (really the only SAPI that matters) didn't have it enabled. The .so file was located in /usr/lib/php/20151012, rather than someplace more universal. I copied it to /usr/lib/php/7.0/modules/stats.so, and created simple stats.ini file and added it to /etc/php/7.0/fpm/conf.d, and that worked.

So my question is, how do I best automate these last steps of placing the .so file someplace obvious and enabling it on fpm? Is cloning an existing Ansible Role, like the xdebug one, and tweaking as needed a good approach? I know basically nothing about Ansible. Thanks very much! 

And thank you, Jeff, for this amazing project! It has made my life much easier.

**Comment by geerlingguy** [comment]
Weird... pecl should install it correctly, I wonder if it might be a packaging problem with the stats package itself? Can you see if any other pecl packages work correctly? Last time I had to use one it seemed to work fine on its own.

**Comment by ldpm** [comment]
Great question!

The same thing happens when attempting to include rar as a pecl extention:

In my config.yml:
```
# Any additional packages provided by PECL or PEAR
php_pecl_extensions:
  - stats-2.0.3
  - rar
```

On the vm:
```
vagrant@drupalvm:/$ pecl list
Installed packages, channel pecl.php.net:
=========================================
Package Version State
rar     4.0.0   stable
stats   2.0.3   stable
```
but the phpinfo page doesn't indicate rar is installed, and the .so file is in that same /usr/lib/20151012 directory.

I'm not sure if this is instructive, but I also tried to install imagick and stompas pecl extensions, but installation failed for what appeared to be missing dependency issues, and since I didn't actually want those extensions, I didn't try very hard to chase them down and instead picked a different package.
