### ISSUE TITLE
Working with composer on distributions is slow.

### ISSUE THREAD

**Issue by ndobromirov** [geerlingguy/drupal-vm#1806]
### Issue Type

 - Feature Idea
 - Bug Report (just slow), no errors.

### Your Environment
```
$ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 2.0.3
VirtualBox 5.1.34r121010
ansible 2.5.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ndobromirov/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.6 (default, Nov 23 2017, 15:49:48) [GCC 4.8.4]
```

### Your OS
**Linux** 
- Host: Ubuntu 14.04
- Guest: Ubuntu 16.04

### Summary
Running composer install on BLT related D8 projects is taking too much time. Running the same command through docker or locally executes in fraction of the time (like 5-10 times the difference).

composer install and update are VERY common operations and they are very I/O intensive, as BLT recommendations for deploys are through artifacts (again composer install).

Is it possible to add some of the [options from here](https://www.cyberciti.biz/faq/linux-unix-tuning-nfs-server-client-performance/) to speed-up the NFS mount? Most importantly I think that `noatime` and `nodiratime` will help the most, as they will reduce network I/Os during composer related operations, when the NFS is being trashed while checking and reading / writing the vendor folder .

I know that the current `/vagrant` mount does not have them. 
See the entry I am getting from the VM for the mount:
```
192.168.211.1:/var/www/PROJECT on /vagrant type nfs (rw,relatime,vers=3,rsize=1048576,wsize=1048576,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.211.1,mountvers=3,mountport=37325,mountproto=udp,local_lock=none,addr=192.168.211.1)
```

Another option is to tune the host connection to a higher MTU value from the default `1500` to reduce network round-trips needed for fetching a file.

**Comment by geerlingguy** [comment]
It would be interesting to see if those options make a substantial difference. You can set mount options by adding `mount_options` in the synced folder configuration; see http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/ for some examples of extending it a bit.

**Comment by geerlingguy** [comment]
(Also, personally I either do all composer stuff on my Mac (not inside the VM in a shared folder), or if in a VM or container, inside a native directory. Then if needed I'll move the files into a shared directory. It's like 10x faster even if inside a Docker container (at least on Mac).

**Comment by ndobromirov** [comment]
The thing is mu local PHP (7.1) version differs from the one in VM (7.2), :) so some dependencies fail when the composer is used from outside. And Yeah that's my current workaround. I've installed all PHP versions locally and I am switching when switching projects so I am as well trying to use the composer from local, but it's a pain :)...

Will test that with the mount options and report back on next rebuild of the VM.
