### ISSUE TITLE
Virtualbox 5.2.16 Guest Additions installation hangs on Ubuntu 14.04

### ISSUE THREAD

**Issue by sirkitree** [geerlingguy/drupal-vm#1807]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.1.1
VirtualBox 5.2.12r122591
zsh: command not found: ansible
```

### Your OS
 - **macOS** (10.13.5)

### Full console output
https://gist.github.com/sirkitree/d5cba11e853c58c93c1284cee078ef65

### Summary
After upgrading virtual box from 5.2.12 to 5.2.16 and running `vagrant up` on an existing installation, process hangs indefinitely when trying to upgrade the Virtualbox Guest Additions. I let this run for over 12 hours before killing it. I then downgraded to 5.2.12 and `vagrant up` worked as expected again.

**Comment by Jarvvski** [comment]
Any thoughts @geerlingguy?

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/packer-ubuntu-1404/issues/24 and https://github.com/geerlingguy/drupal-vm/issues/1803. In fact I'm going to merge #1803 into this ticket.

**Comment by geerlingguy** [comment]
Quick fix: Switch to any other base box (I recommend Ubuntu 16.04 for now).

**Comment by geerlingguy** [comment]
I just haven't had time to run the installer manually to see what's failing or hanging.

**Comment by cheeseplus** [comment]
Fwiw, we're seeing this on https://github.com/chef/bento 14.04 as well.

**Comment by geerlingguy** [comment]
@cheeseplus - /me waves — I still haven't had time to dig in and debug the guest additions installer. I'm secretly hoping that whatever gremlin lurks is fixed by the time 5.2.18 rolls around. But I should also probably open an issue in the VirtualBox forums to get this on their radar; I haven't seen anything else on it yet.

**Comment by geerlingguy** [comment]
Here's the tail end of the error in the VirtualBox console:

<img width="640" alt="screen shot 2018-08-14 at 1 13 40 pm" src="https://user-images.githubusercontent.com/481677/44109922-ecece9ee-9fc3-11e8-8c2a-d80ee0720c99.png">

**Comment by geerlingguy** [comment]
And from the vboxadd-setup.log:

<img width="487" alt="screen shot 2018-08-14 at 1 16 24 pm" src="https://user-images.githubusercontent.com/481677/44110040-47a48e82-9fc4-11e8-831b-d18bc504f2fb.png">

**Comment by geerlingguy** [comment]
Apparently the problem was related to the kernel provided by Ubuntu 14.04.1; I updated to 14.04.4 (after closing out https://github.com/geerlingguy/packer-ubuntu-1404/issues/18 since I don't build new VMware boxes anymore so don't need HGFS support to work), and now the build completes.

**Comment by geerlingguy** [comment]
Uploaded a new base box version (1.2.8).

Fix for this issue is: run `vagrant box update` to make sure you're using the latest version of the `geerlingguy/ubuntu1404` box.
