### ISSUE TITLE
Failed to validate the SSL certificate for github.com:443

### ISSUE THREAD

**Issue by seccodingguy** [geerlingguy/drupal-vm#1809]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.2
VirtualBox 5.2.16r123759
ansible 2.6.2
  config file = None
  configured module search path = [u'/Users/mwireman/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]

```

### Your OS

 - **macOS** (10.13.6)
 

### Full console output

FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)."}

### Summary

Tried all of the known workarounds, however, still receiving the error. This is a new MacOS build.

**Comment by geerlingguy** [comment]
@seccodingguy - Can you give any more context? What task did this fail on, do you have any custom settings in config.yml, etc.?

**Comment by seccodingguy** [comment]
Here's a bit more context:

I'm running the script provided by the OWASP DevSecOps project located here (install instructions also provided): https://github.com/teacheraio/DevSecOps-Studio

The exact steps (shown via the output) for the issue when installing Docker is here:

TASK [geerlingguy.docker : Add Docker repository.] *****************************
changed: [DevSecOps-Box]

TASK [geerlingguy.docker : Install Docker.] ************************************
changed: [DevSecOps-Box]

TASK [geerlingguy.docker : Ensure Docker is started and enabled at boot.] ******
ok: [DevSecOps-Box]

RUNNING HANDLER [geerlingguy.docker : restart docker] **************************
changed: [DevSecOps-Box]

TASK [geerlingguy.docker : include_tasks] **************************************
included: /Users/mwireman/DevSecOps-Studio/provisioning/roles/geerlingguy.docker/tasks/docker-compose.yml for DevSecOps-Box

TASK [geerlingguy.docker : Check current docker-compose version.] **************
ok: [DevSecOps-Box]

TASK [geerlingguy.docker : Delete existing docker-compose version if it's different.] ***
skipping: [DevSecOps-Box]

TASK [geerlingguy.docker : Install Docker Compose (if configured).] ************
fatal: [DevSecOps-Box]: FAILED! => {"changed": false, "msg": "Failed to validate the SSL certificate for github.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)."}
	to retry, use: --limit @/.../DevSecOps-Studio/provisioning/devsecops-box.retry

PLAY RECAP *********************************************************************
DevSecOps-Box              : ok=14   changed=7    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Okay, I'm running the test with:

```
$ git clone https://github.com/teacheraio/DevSecOps-Studio.git && cd DevSecOps-Studio
$ vagrant up
```

It looks like this project uses the `bento/ubuntu-16.04` base box. I'll let you know how it goes.

**Comment by geerlingguy** [comment]
It looks like the entire thing worked fine (though there were some GitLab error later during that build process, unrelated to Docker).

Also, since this is for the `DevSecOps-Studio` and the failure occurs with the `geerlingguy.docker` role (which is not being used in Drupal VM at all at this time), I'd recommend opening the issue in the DevSecOps-Studio repository first, to see if there are other users with the same issue.
