### ISSUE TITLE
Multiple document roots AND install from makefile

### ISSUE THREAD

**Issue by joevallender** [geerlingguy/drupal-vm#181]
I want to use this one VM to run a few separate Drupal installs (not multisite)

I believe I can set up multiple document roots by adding to these vars in config.yml

    vagrant_synced_folders
    apache_vhosts
    mysql_databases
    mysql_users

I would like each new site to be installed using the make file, however the makefile seems to be configured with variables starting  `drupal_*`

Is it limitation of the project (deliberate or otherwise) that only the first site can be installed automatically? 

I'm not complaining btw ;-) just wondering if I've missed something. I guess I can change config.yml to create the roots then `vagrant ssh` in run some commands myself, it's just that the rest of it is so slick I wanted to check if there is a better way.

I'd like to point out that I definitely don't have a bug or anything. I am already using this successfully with all the recommended versions of dependencies. 

Thanks

**Comment by geerlingguy** [comment]
It's a limitation—deliberate for now, but hopefully fixed someday to allow multiple sites to be installed via make files (or any other method of your choosing).

The primary use cases currently allows for multiple sites to be managed independently—but you have to do some manual manipulation of the `config.yml` file for each site (see Deployment Strategies section in the [Docs](http://docs.drupalvm.com/en/latest/)). However, only one site can be installed via makefile on initial provision.

One pattern I've seen used in certain places is multiple copies of Drupal VM—one for each site/project. That way it can be tuned for each project individually, and as long as you have a unique IP address and machine name for each, they won't conflict and can be brought up and down whenever you like.

For now, I'm closing this issue. I'm hoping to solve this problem (support as many sites with whatever install methods out of the box) by 3.x, but we'll see :)

**Comment by joevallender** [comment]
Thanks for the reply, that's cool. And I guessed as much - just wanted to check. Thanks for project :)
