### ISSUE TITLE
Using Drupal VM for React Admin project developement

### ISSUE THREAD

**Issue by captaindav** [geerlingguy/drupal-vm#1810]
### Issue Type
- Support Request
### Your Environment
```
Vagrant = 2.1.2
VirtualBox = 5.1.16r123759
Don't show Ansible as installed? am running Windows.
```

### Your OS
 **Windows 10

### Full console output
Drupal development server started: <http://127.0.0.1:8888>
This server is not meant for production use.
One time login url: <http://127.0.0.1:8888/user/reset/1/1533687024/iExckzgQEwZouRUrex5lBMFmzfMv8RRdG0RvV6jWTbg/login>
Press Ctrl-C to quit the Drupal development server.

### Summary
I am trying to get setup to work on the new Drupal React Admin interface, https://github.com/jsdrupal/drupal-admin-ui.   I am able to follow their instructions for installing, using composer and then running 'composer devify' to set up the environment for development.  Then running "composer start" gives the output show above, which indicates that the React app should be available at 127.0.0.1:8888, but instead I get "This site can not be reached".  I tried adding 8888 to the list of ports in firewall_allowed_tcp_ports, and also just turning off the firewall.  Also turned off my Windows firewall. Would you have any idea why this would not work?

Others on the React Admin team use Docker, would it make sense to switch to that?

**Comment by geerlingguy** [comment]
> Others on the React Admin team use Docker, would it make sense to switch to that?

Maybe. If everyone else is using it, it might be the easiest way to make sure you're not the cog that doesn't fit!

> Would you have any idea why this would not work?

Not quite sure, but can you do a `curl --head 127.0.0.1:8888` inside the VM (`vagrant ssh` to get inside) and see if that gives a 200 OK response? If so it's running, it's just not running on a publicly-available interface (e.g. 0.0.0.0 or the ethernet bridge). It might just be available inside the VM only. You'd have to see if there are any config options that tell it 'run anywhere'...

**Comment by captaindav** [comment]
The curl fails....

$curl --head 127.0.0.1:8888
curl: (7) Failed to connect to 127.0.0.1 port 8888: Connection refused
