### ISSUE TITLE
"XDebug could not open the remote debug file '/tmp/xdebug.log'."

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#1813]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.2
VirtualBox 
5.2.16r123759
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/kevinquillen/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct  6 2017, 22:29:07) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.31)]
```

### Your OS

 - **macOS** (High Sierra)

Using the new 4.9.0 release on a new VM, I am getting this error every time I run a Drush command:

"XDebug could not open the remote debug file '/tmp/xdebug.log'."

How can I correct this or make it go away?

**Comment by geerlingguy** [comment]
I haven't been able to reproduce this issue... but maybe it's related to how you have your IDE configured? Where are you getting that message specifically?

**Comment by ThomWilhelm** [comment]
I get the same on my vagrant machine when running any drush command and having xdebug installed:

```
vagrant@meetinnsw-upgrade:/var/www/drupalvm/docroot$ drush --version
Xdebug could not open the remote debug file '/tmp/xdebug.log'.
Xdebug could not open the remote debug file '/tmp/xdebug.log'.
Drush Commandline Tool 9.5.2
```

It comes back every now and again, haven't exactly figured out why. Adding the following to the vagrant machines ~/.bashrc at least makes it go away:

`sudo chmod 766 /tmp/xdebug.log`

**Comment by gregbown** [comment]
In Dockerfile you can append this to a RUN command
```
    # xdebug cannot write to it's log
    && touch /tmp/php5-xdebug.log \
    && chown www-data:www-data /tmp/php5-xdebug.log \
    && chmod 666 /tmp/php5-xdebug.log
```

**Comment by VladSavitsky** [comment]
I have the same problem.
/tmp/php5-xdebug.log not exists until you start debugging session in IDE and reload page in browser. Only then this file will be created.
When I enable xDebug and run any drush command (which is CLI) I got this error.
