### ISSUE TITLE
Changes to my.cnf and apache2.conf to improve performance

### ISSUE THREAD

**Issue by mrweiner** [geerlingguy/drupal-vm#1815]
I got fed up with the slowness I was experiencing with DrupalVM yesterday and went on a bit of a quest to see what I could do to speed things up. In the process, I came across this post on [drupal.org](https://www.drupal.org/project/vdd/issues/2179791#comment-8422857) in the issue queue for [Vagrant Drupal Development](https://www.drupal.org/project/vdd). Here's the post in its entirety:

> After enabling NFS, I was still been facing huge performance issues. Immediately after I booted vagrant box, performance was good, but after loading some pages and visiting some sites on development environment, server was working slower and slower, and after some time it were getting to the point when website stopped reacting at all or constantly throughts mysql time out errors.
> 
> It turned out that server was running too many apache and mysql processes at the same time. On every site visit, new apache process were created and every process consumes RAM, so all these proccesses consumed all my server's RAM memory and started using SWAP space (writing memory to hard drive), so this is the reason why pages were loading slower and slower, and often after few minutes of use, server stopped responding all together, because even all available SWAP were often consumed....
> 
> To solve this performance issues, I changed server configuration files, and now server perfoms great no matter how long I use it.
> 
> /etc/mysql/my.cnf
> key_buffer = 256M -------> 128M
> thread_cache_size = 8 --> 3
> 
> /etc/apache2/apache2.conf
> StartServers 16 ----------> 3
> MinSpareServers 16 ----> 3
> MaxSpareServers 32 ---> 4
> ServerLimit 400 ----------> 4
> MaxClients 400 -----------> 4
> 
> This configuration limits the amount of processes that can be used at the same time, and saves tonnes of RAM. Now SWAP space never gets used and server newer slows down and never hangs :) I suggest improving VDD's configuration files for better perfomance, because we don't need so much proccesses running on local development environment. Also I guess that configuration files could be tweeked even more to enhance performance.

After changing the my.cnf lines and adding the apache2.conf lines (my box didn't have those settings set at all) I've seen a noticeable improvement in performance. Pages are loading more quickly, but more importantly I've noticed that the VM just isn't hogging my machine resources.

Now, I realize that the issues I was experiencing could very well be because of the vagrantfile I was provided with for this project and may have nothing to do with DrupalVM itself, but I thought I'd drop this in here in case these settings are something that could be integrated into DVM in some way. 

If not, then for future googlers -- slow Drupal VM? Try these settings (and maybe [Vagrant Faster](https://github.com/rdsubhas/vagrant-faster), too)!

**Comment by geerlingguy** [comment]
@mrweiner - Thanks for the post! I hope it helps future Googlers who might be looking for performance tips for Drupal VM. Indeed, there are some adjustments for Apache, PHP, MySQL, etc. which can make Drupal VM a bit faster _depending on the sites running within_, but the problem is many of these settings, when changed from their defaults, can also cause other strange performance issues, so I tend to stick to a baseline default when I can.

For _most_ cases (e.g. a stock Drupal 8 site), the defaults are good enough for most people. But it's always a good idea to do a little tuning if you want the best performance, especially if you're RAM or CPU-limited!
