### ISSUE TITLE
How to build Docker environment installing Apache Solr and Varnish?

### ISSUE THREAD

**Issue by pedrofurtado** [geerlingguy/drupal-vm#1816]
@geerlingguy 

I am using DrupalVM project only with Docker, without Vagrant. Because of this, to create the Docker container/environment I execute these commands below:

```bash
$ mkdir my-folder
$ cd my-folder
$ docker container run -d -v $(pwd):/var/www --name=drupalvm --privileged geerlingguy/drupal-vm
$ docker container exec drupalvm install-drupal 7.x

# See the IP of container.
$ echo $(docker container inspect --format='{{.NetworkSettings.IPAddress}}' drupalvm)
```
Then, I access in browser `http://[CONTAINER-IP]`. The whole Docker environment works very well, but Varnish and Apache Solr are not installed by default.

How do I configure in order to create the Docker container with Varnish and Solr installed (inside container)?

**Comment by geerlingguy** [comment]
The default image (`geerlingguy/drupal-vm` on Docker Hub) just adds the default set of software defined in the default config file.

You would need to build your own Docker image using one of two methods:

  1. Build a fully customized Drupal VM Docker image using Drupal VM: http://docs.drupalvm.com/en/latest/other/docker/#method-2-build-a-default-drupal-vm-instance-with-docker
  2. Use the `geerlingguy/drupal-vm` docker image as your FROM image in a custom Dockerfile and then install varnish and solr manually in the Dockerfile (harder to do, but then you can still base on `geerlingguy/drupal-vm`).
