### ISSUE TITLE
Add ability to specify config file name

### ISSUE THREAD

**Issue by TravisCarden** [geerlingguy/drupal-vm#1818]
### Issue Type

 - Feature Idea

### Summary

Drupal VM provides `ENV['DRUPALVM_CONFIG_DIR']` to change the directory where it will look for `config.yml`. I'd like to control the name of the file as well because I want to store it in a generic `config/` directory with other files where that filename does not identify or differentiate it from its neighbors well.

**Comment by oxyc** [comment]
Not ideal but you could always use 

```rb
ENV['DRUPALVM_ENV'] = 'drupalvm'
```

and it would load `drupalvm.config.yml`

**Comment by TravisCarden** [comment]
Thanks, @oxyc! I can live with that as a workaround. I'll leave the issue open for others to determine whether an actual feature addition is warranted.

**Comment by geerlingguy** [comment]
I'd rather not complicate things further—this is an acceptable workaround if you want to make sure Drupal VM's config isn't confusing when mixed with other project resource files. But I don't want to introduce any more complexity to the way config files are named and/or loaded, it's already a little confusing if you're new to the project, how those 'magic' environment vars work.
