### ISSUE TITLE
Locking Drupal VM box_version

### ISSUE THREAD

**Issue by ThomWilhelm** [geerlingguy/drupal-vm#1820]
### Issue Type

 - Feature Idea

### Your Environment

```
Vagrant 2.0.3
VirtualBox 5.2.12r122591
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/thomaswilhelm/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.5.0/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Mar 22 2018, 15:04:47) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### Your OS

 - **macOS** (10.13.6)

### Summary

I'm trying to see if it's possible to lock the box_version of drupal vm. I have drupal vm config that works nicely with box version 1.1.8, but I had some issues when upgrading the box to 1.2.2. Until I've got the time to figure out what's going on, it is possible to lock the box version to 1.1.8 somehow? That way I know when passing my project over to other developers, I'm confident they won't run into the same issues.

I've found that in the Vagrantfile there's a setting config.vm.box_version which is perfect if I could set it, but can't see any way to pass this in from drupal vm config.yml, is it possible?

**Comment by ThomWilhelm** [comment]
I wrote a patch that then allows me to set vagrant_box_version: '1.1.8' in my config.yml for anyone interested. Apply using composer patches.

[lock-box-version.patch.txt](https://github.com/geerlingguy/drupal-vm/files/2338413/lock-box-version.patch.txt)

**Comment by geerlingguy** [comment]
@ThomWilhelm - I generally recommend using the latest, as it's been tested fully with Drupal VM at least in a couple build environments, but I can see a use case of locking a box version.

Note that you could set/override the variable using a `Vagrantfile.local` file inside your project root instead of patching the Drupal VM `Vagrantfile`, but either way is fine.
