### ISSUE TITLE
Is the drupal console available by default from any path?

### ISSUE THREAD

**Issue by meatballcoder** [geerlingguy/drupal-vm#1824]
I am on Windows 10.

Whenever I install with vagrant up, all goes well, and I can get to the Drupal dashboard, and so on.

Whenever I use vagrant ssh it's good, and I type drupal and get drupal: command not found.  I saw some references to this in the issues.  Am I trying to access the drupal console incorrectly?  Should it be available everywhere or should I be in drupalvm directory down to the bin that has drupal (drupal exectuable for console)?

**Comment by geerlingguy** [comment]
@meatballcoder nowadays, Drupal Console is installed as a project dependency, and not as a global CLI utility like it used to be (similar to how Drush has changed its approach in Drush 9 so it's always a project-local dependency).

So the recommended way of using Drupal Console now is to `composer require` it in your Drupal project, then `cd` into the project root and you can run `vendor/bin/drupal` to run it (or alias that to your $PATH for convenience).

Outside of the context of a Drupal codebase/project, Drupal Console won't be able to do anything useful.
