### ISSUE TITLE
Set NginX configuration options from config.yml

### ISSUE THREAD

**Issue by jameshickman** [geerlingguy/drupal-vm#1825]
### Issue Type
 - Feature Idea

### Your Environment
```
Vagrant 2.0.2
VirtualBox 5.2.12r122591
ansible 2.5.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/msk/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Apr 15 2018, 21:51:34) [GCC 7.3.0]

```

### Your OS
 - **Linux** (Ubuntu 18.04)

### Summary
Would like to be able to pass configuration options for nginx.conf from the vm/config.yml file. For example fastcgi_* directives. Appears this is not possible without direct edit of the Ansible files within the Vendor directory and would like to manage custom configuration as part of the project files without custom edits to dependencies.

**Comment by geerlingguy** [comment]
@jameshickman - You can override any of the Nginx role variables in your config.yml file; see https://github.com/geerlingguy/ansible-role-nginx#role-variables for a listing of all the available variables. You should be able to configure Nginx to your heart's content using the available options.

**Comment by jameshickman** [comment]
Thank you for pointing me to the needed information. Much appreciated.
