### ISSUE TITLE
Xdebug won't install for PHP cli

### ISSUE THREAD

**Issue by acha5066** [geerlingguy/drupal-vm#1826]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.9.4
VirtualBox 5.1.34r121010
ansible 2.5.0
  config file = None
  configured module search path = [u'/Users/Chappell/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.14 (default, Apr 11 2018, 09:52:49) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### Your OS

 - **macOS** (10.13.3 High Sierra)

### Full console output

https://gist.github.com/acha5066/dc4ce216885d96c01bf2409cf57ba991

### Summary

I'm having the same problem as this closed issue: #1796 Xdebug works fine from the browser, but even if I have enabled the xdebug cli, xdebug is never installed for cli. In fact "Copy xdebug ini into main extension config folder." is skipped and xdebug is disabled for PHP CLI. (See Gist). `php -i | grep xdebug` shows no xdebug.

My config settings: 

```
# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 0
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
# Use PHPSTORM for PHPStorm, sublime.xdebug for Sublime Text.
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"
```

**Comment by lokeoke** [comment]
Most probably you are using drupal-vm 4.9.0 where `php_xdebug_cli_enable` variable has been replaced with `php_xdebug_cli_disable`.

So in your case, you need to update your config to have `php_xdebug_cli_disable: no`.

See https://github.com/geerlingguy/drupal-vm/releases/tag/4.9.0

**Comment by acha5066** [comment]
Ok. yeah that makes sense. I will update it. Thanks!
