### ISSUE TITLE
No CSS on a clean install; CSS seems to be served with HTML headers

### ISSUE THREAD

**Issue by nonprofitable** [geerlingguy/drupal-vm#1839]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.5
VirtualBox 5.2.18r124319
ansible 2.6.5
  config file = None
  configured module search path = [u'/Users/webadmin/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.5/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Oct  2 2018, 11:42:04) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.2)]
```

### Your OS

 - **macOS** (10.4)

### Summary

The dashboard loaded fine, so I assumed my vagrant up was successful! But the Drupal installation itself has no CSS. 

The error in Chrome's web dev tools: 

"Refused to apply style from 'http://drupalvm.test/?0' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled."

Googling a little suggests Apache's serving CSS with HTML headers; is this something that needs to be fixed in the Ansible provisioning script? If I fix this within the VM, am I right in assuming that any new VMs built with this script would have the same error?

Thanks,

  Dave.

**Comment by geerlingguy** [comment]
I've never seen this happen... does it also happen in FireFox, Safari, Edge, etc.? If it's only Chrome, maybe it's a chrome rendering bug?

Also, `http://drupalvm.test/?0` seems like a very weird URL for a stylesheet. Is there something in your Drupal theme or a module that might be causing invalid URLs to be used for stylesheets? In Drupal stylesheets are generated and output with .css extensions which would then be correctly interpreted/served by Apache or Nginx. If you load any URL which hits Drupal, like `http://drupalvm.test/?0`, then it would serve an HTML page, maybe a 404 (try loading http://drupalvm.test/?0 to see what it outputs).

**Comment by nonprofitable** [comment]
This is a clean install from Drupal-VM; no modules / themes / customizations have been added yet. I spun up the VM for the first time, the dashboard looked like it loaded correctly, but the site itself loads no CSS. 

Checked in Firefox, and it loads no CSS. 
http://drupalvm.test/?0 loads the same homepage with no CSS. 

I'm assuming the ?0 is from the CSS / JS aggregation system?

**Comment by nonprofitable** [comment]
Oh, hmm. In config/performance: 

"External resources can be optimized automatically, which can reduce both the size and number of requests made to your website. Set up the public files directory to make these optimizations available."

Both of these are checked, and I can't uncheck them:

 "Aggregate CSS files
 Aggregate JavaScript files"

Hmm. Is something about the VM setup not setting up the public files directory correctly? Does Drupal think it's in the wrong place, or does it have the wrong perms, etc?

**Comment by geerlingguy** [comment]
I wonder if it's a filesystem issue or something like that.

Do you have anything at all in a `config.yml` or `local.config.yml`? And is this just a plain Drupal VM instance? I just downloaded the project, 4.9.1 release and master, and ran `vagrant up` in the Drupal VM directory, and in both cases the CSS is loading fine in Drupal.

If you go to Drupal's admin status report page, does it have any warnings, e.g. it can't write to the public files directory or something like that?

**Comment by bccox** [comment]
The same thing happens for me on Debian sid with Drupal VM master, Vagrant 2.2.0, Ansible 2.7.0, and VirtualBox 5.2.20. If I use Drupal VM 4.9.1, the Drupal site comes up just fine with all CSS present and available.

One interesting thing to note is that with 4.9.1, the stylesheet links actually have a full path (sans hostname) rather than just referring to http://drupalvm.test/?0.

**Comment by geerlingguy** [comment]
@bccox - So are you saying that Drupal VM `master` is failing, but if you use `4.9.1`, it works?

**Comment by pmagunia** [comment]
This happened to me too. I noticed the `vagrant` user and group owned the files directory so the `www-data` user couldn't write files. I fixed it with:

`sudo chown vagrant:www-data files -R`

This is with a fresh install of ubuntu1804.

**Comment by pkoobs** [comment]
I'm having these same issues except the solution @pmagunia and @grantpestka propose are not working... Drupal VM master, Vagrant 2.2.14, and VirtualBox 6.1.16.
