### ISSUE TITLE
Newbie first install: vagrant up fail

### ISSUE THREAD

**Issue by lanoumet** [geerlingguy/drupal-vm#1840]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
λ vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 2.1.5
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS
 - **Windows** (10 pro version 1803)

### Full console output
https://gist.github.com/lanoumet/21e959a7828164bbcd0997bb601c9491#file-gistfile1-txt
### Summary

I am trying to install drupalvm for the first time following the Quick Start Guide
I've downloaded drupalvm, installed vagrant and virtual box, set local path.
Then cd to the directory and type vagrant up and it fails.

Thanks for your help

**Comment by geerlingguy** [comment]
This looks like a networking issue. A few questions:

  - Are you on a corporate network, using a VPN, or have a proxy server or firewall filtering your traffic?
  - Are you running malware detection or virus scanning software? (It could also filter traffic).
  - Can you try again now, and if so, does it still have the same error?

This is not a Drupal VM specific issue, it seems there's a problem between your computer and rubygems.org, downloading the required Ruby Gems used to manage the Drupal VM installation.

**Comment by lanoumet** [comment]
- I am using a basic wifi connection
- Windows defender is on (Antivirus and Firewall)

I tried again and this time the VM boots. 

When I run vagrant provision I get this error:

TASK [geerlingguy.drupal : Ensure drupal_core_path directory exists.] **********
fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "There was an issue creating /var/www/drupalvm as requested: [Errno 13] Permission denied: '/var/www/drupalvm'", "path": "/var/www/drupalvm/drupal/web", "state": "absent"}
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=189  changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Gist: https://gist.github.com/lanoumet/4236f4529fbc2cf720c4b136e4d2f0e4

I don't know how to handle this: "to retry, use: --limit @/vagrant/provisioning/playbook.retry"

**Comment by geerlingguy** [comment]
You can ignore the Ansible retry message. It looks like maybe your user doesn't have write privileges in the directory you're sharing into Drupal VM? 

Are you overriding `vagrant_synced_folders` in your project, or just using the default as defined in the default config file: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L30-L37

The shared folder needs to be somewhere your Windows user account has write access.

**Comment by lanoumet** [comment]
Thank you so much for your help!
Now it seams I got it working! I can reach http://192.168.88.88/

The local_path in vagrant_synced_folders was mispelled. My bad.

This time II let local_path unconfigured. Does it mean that I don't have sync folder?

**Comment by geerlingguy** [comment]
If you leave it empty, I *think* it defaults to the current working directory.
