### ISSUE TITLE
Install-site.yml -> Stucked on task - name: Install Drupal with drush.

### ISSUE THREAD

**Issue by lostation** [geerlingguy/drupal-vm#1841]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.1.5
VirtualBox 5.2.18r124319
ansible 2.6.5
  config file = None
  configured module search path = ['/Users/laurent/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/ansible
  executable location = /Library/Frameworks/Python.framework/Versions/3.7/bin/ansible
  python version = 3.7.0 (v3.7.0:1bf9cc5093, Jun 26 2018, 23:26:24) [Clang 6.0 (clang-600.0.57)]
```

### Your OS

 - **macOS** (10.13.3)

### Full console output

https://gist.github.com/lostation/9834b256acb11ce3aa0f0578cf496739

### Summary

As you can see in the provided gist url above : 
I'm stucked in the task  - name: Install Drupal with drush. from the install-site.yml file.

- **name**: Install Drupal with drush.
  **command**: >
    {{ drush_path }} site-install {{ drupal_install_profile | default('standard') }} -y
    --site-name="{{ drupal_site_name }}"
    --account-name={{ drupal_account_name }}
    --account-pass={{ drupal_account_pass }}
    --db-url=mysql://{{ drupal_mysql_user }}:{{ drupal_mysql_password }}@localhost/{{ mysql_databases[0].name }}
    {{ drupal_site_install_extra_args | default([]) | join(" ") }}
    chdir={{ drupal_core_path }}
  **notify**: restart webserver
  **when**: "'Successful' not in drupal_site_installed.stdout"
  **become**: no

I'm completely _newbie_ in php and ansible stuffs... So surely I missed something !

For info, I need to restart an old project from 2016 that uses your Drupal-vm project. And I already had to adapt a lot of small things to be able to get until these last task. Whatever...

## Partial **config.yml** file :

vagrant_box: geerlingguy/ubuntu1404
vagrant_user: vagrant
deploy_user: vagrant

build_makefile: false

build_composer: true
drupal_composer_path: "{{ config_dir }}/drupal.composer.json"
drupal_composer_install_dir: "/var/www/drupalvm/drupal/"
drupal_composer_dependencies:
  - "drupal/devel:^1.6"

build_composer_project: false
drupal_composer_project_package: "drupal-composer/drupal-project:7.x-dev"
drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

install_site: true
drupal_install_site: true

drupal_core_path: "{{ drupal_composer_install_dir }}/web"

drupal_major_version: 7
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "MyApp"
drupal_install_profile: standard
## -------------------------

I already tried to erase all the vm stuff and then vagrant up again... Or tried vagrant reload --provision...With or without erasing Drupal files.

It seems to be a stupid thing about permission but I cannot figure it out.
-> The automated script cannot open file stream and copy default.settings.php to settings.php.

Also I'm not sure to understand the  **when**: "'Successful' not in drupal_site_installed.stdout"  command.  In the running shell I only see some ['ok'] in green for any other task but never 'Successful' text... 

The thing a little bit weird is that if I log into the VM with vagrant ssh,
I'm able to run manually the scripted command.

I run :   /usr/local/bin/drush site-install standard -y --site-name=MyApp --account-name=admin --account-pass=admin --db-url=mysql://drupal:drupal@localhost/drupal --account-mail=admin@myapp.com --site-mail=info@myapp.com

And with that, the settings.php file is correctly created. 

So I imagine that it's a user permission issue ?

I tried to add

  become_user: "{{ deploy_user }}"
  become_method : _sudo_ | _yes_

to the task but nothing is better.

Thanks for any help or hint or advices...
Lo.

**Comment by lostation** [comment]
https://gist.github.com/lostation/9834b256acb11ce3aa0f0578cf496739

**Comment by geerlingguy** [comment]
```
copy(sites/default/settings.php): failed to open stream: Permission denied
```

Basically, the `sites/default` directory needs to have permissions which let the `vagrant` user or web user (if installing via UI) write to it. So in your Drupal codebase, maybe try changing the permissions on that directory to something more permissive, at least temporarily.

The easiest/nuclear option is `chmod 777 sites/default`. Before you do that, check what the current permissions are with `ls -lah sites/default`.

**Comment by lostation** [comment]
Ok thanks for your reply.
By the way, changing permission of sites/default/settings.php was not resolving my issue.
I was using a very old copy of your repo with some custom modules made around 2016. 
So there were a lot of small updates problem. I preferred make a fresh copy of drupalvm and re-adapt to my needs. So now it works pretty well ! Thanks for your work on drupalvm projects ... really impressive ! Thanks.

**Comment by geerlingguy** [comment]
That's great! And yeah, if you're more than a few minor versions behind, it's easier to just scrap an older build and create a new one—especially if you can get by with just a config.yml override and Drupal VM as a composer dependency!
