### ISSUE TITLE
Add support for Apache RewriteLog

### ISSUE THREAD

**Issue by acontia** [geerlingguy/drupal-vm#1847]
### Issue Type
Feature Idea

### Your Environment
N/A

### Your OS
N/A

### Summary
I'm trying to debug a RewriteCond/RewriteRule rule that I have set on my docroot .htaccess file and I can't find where the error is, so I'm looking into enabling RewriteLog as suggested here: https://stackoverflow.com/a/9632952/847628

Looks like this needs to be done in the vhosts file (not in the .htaccess file) so I was wondering if is possible to provision the VM with this log enabled?

I am not sure if this feature request needs to go in the [Ansible Role Apache](https://github.com/geerlingguy/ansible-role-apache) project? 

Thanks!

**Comment by acontia** [comment]
As a temporal workaround I managed to see the mod_rewrite logs doing the following:

```
# ssh into VM
vagrant ssh

# edit vhosts file
sudo vim /etc/apache2/sites-enabled/vhosts.conf

# enable mod_rewrite logging by adding the following into the vhosts.conf file (inside a <VirtualHost> entry)
LogLevel alert rewrite:trace6

# restarting apache
sudo apache2ctl restart

# now I can see the log updated for every request to my local site:
sudo tail -f /var/log/apache2/error.log
```
I imagine the change will be lost if I re-provision the machine (I haven't tested it).

**Comment by geerlingguy** [comment]
@acontia - Yeah, that change would be removed once you restart.

Please see the Apache role readme file: https://github.com/geerlingguy/ansible-role-apache

What you should be able to do is override the `apache_global_vhost_settings` variable in your `config.yml` or `local.config.yml`.

This setting allows you to add lines to all vhost entries, like:

apache_global_vhost_settings: |
  DirectoryIndex index.php index.html
  LogLevel alert rewrite:trace6

Then run `vagrant provision` to apply the change (and on subsequent destroy/rebuilds it would still exist in there).

Thanks for filing the issue! If you have any other questions about Apache-specific customizations, please file an issue under the Apache role project: https://github.com/geerlingguy/ansible-role-apache/issues
