### ISSUE TITLE
Unable to composer update Drupal core 8.6.1 -> 8.6.2 in Windows environment

### ISSUE THREAD

**Issue by IgsuMustonen** [geerlingguy/drupal-vm#1848]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.5
VirtualBox 5.2.20
Ansible 2.6.5
```

### Your OS

 - Windows 10 Pro 1803
 
### Full console output

https://gist.github.com/IgsuMustonen/f0fdd85a9f097a552f6db0cdc2d5b32e

### Summary

I am unable to update core using composer in my DrupalVM. It appears to have problems with a temporary compressed file that composer creates at web/core/. I believe composer tried to delete that file but it fails to do so as it appears to be still in use by an unzipping utility. 

I have updated core multiple times in this same environment with no issues, also modules and other dependencies are updated properly. I suspect it might have also something to do with synced folders but it's hard to tell.

**Comment by geerlingguy** [comment]
Can you try manually deleting the `web/core/19bad497c49d8d75449785dd61c26e4a` directory and try again?

Also, are you running the `composer update` command inside Drupal VM, or outside in the Windows or Ubuntu bash environment?

I tend to avoid running any `composer` commands in a shared folder—it's often quicker to copy your codebase somewhere like `/tmp` inside the VM, do Composer stuff, than copy it back once done!

**Comment by IgsuMustonen** [comment]
Manually deleting does not help, since composer creates a new file at `web/core/...` with a different hash and the same error happens again. 

I'm running `composer update` inside Drupal VM, my host machine dosen't have composer installed at all. I also tried manually deleting the file while `composer update` is running and it fails too, I think the file is some kind of compressed file probably containing core stuff from composer's cache.

Copying stuff to a tmp folder sounds like a good idea, I'll give it a try

**Comment by nessunluogo** [comment]
Maybe a low memory problem. I suggest you to stop the VM and restart your host machine, then increase the amount of available memory on vagrant.
Try editing your vagrantfile adding something like this:
```
    config.vm.provider "virtualbox" do |v|
        v.memory = 2048
        v.cpus = 2
    end
```
This worked for me.

**Comment by IgsuMustonen** [comment]
Increasing memory did not help either. Same issue repeats and the worst part is that when composer fails, it leaves `web/core` completely empty with the expection of that one compressed file, meaning the whole site is gone and I have to restore `web/core` from backup everytime. This is getting really weird and I am not sure anymore if I should take this issue to Composer or is it still related to DrupalVM.. Any opinions?

**Comment by geerlingguy** [comment]
@IgsuMustonen - I'm wondering if it might be an issue with how the shared filesystem works, maybe? Can you try doing the same thing on a copy of the codebase somewhere that's not in the shared file path, maybe copy the code into `/tmp` and try there.

**Comment by IgsuMustonen** [comment]
@geerlingguy It is indeed related to the shared filesystem.

I have not found the cause of the problem and therefore there is no solution here, but rather a workaround based on the suggestions above: 

- Copy all files inside `drupalvm/drupal/` to a completely separate directory (in my case, I had to copy them to my host machine, and then upload them using SFTP because `cp` command would just run forever, probably because of the shared filesystem)

- Run `composer update` in that new folder, it should be able update without issues

- Replace the files at `drupalvm/drupal` with the updated ones (Likely using SFTP once more)

- `drush updatedb && drush cache-rebuild` and the site should be back and updated
