### ISSUE TITLE
How to troubleshoot DB connection timeout error?

### ISSUE THREAD

**Issue by scottcale** [geerlingguy/drupal-vm#1850]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
VirtualBox 5.2.20r125813
ansible 2.6.5
  config file = None
  configured module search path = [u'/Users/scott.cale/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.6.5/libexec/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jun 17 2018, 13:05:56) [GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
```

### Your OS
 - **macOS** (version)

```
$ uname -a
Darwin 16.7.0 Darwin Kernel Version 16.7.0: Thu Jun 21 20:07:39 PDT 2018; root:xnu-3789.73.14~1/RELEASE_X86_64 x86_64
```

### Summary

I am trying to clone our live Drupal8 system locally on my laptop as a dev system. When trying to view the site in my local DrupalVM system, I get the following error (via Pimp my Log):

``` 
[pid 12593:tid 140600309442304] [client 192.168.88.1:63586] AH01071: Got error 'PHP message: PDOException: SQLSTATE[HY000] [2002] Connection timed out in /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=dm-d...', 'drupal', 'drupal', Array)

#1 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)
#2 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')
#4 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)
#5 /var/www/intra-devportalz.prod.jp.local/intra/cor...
'
```

_How can I troubleshoot this issue?_

---

#### Step: PROD admin/reports/status

Drupal Version
8.3.5

Web Server
Apache

PHP
Version
7.1.8 (more information)
Memory limit
128M

Database
Version
5.7.18-log
System
MySQL, MariaDB, Percona Server, or equivalent

#### Step: download PROD drupal filesystem

from: `prodserver:/var/www/html/intra-devportalz.prod.jp.local`
to: `~/sites/intra-devportalz.prod.jp.local`

NOTE: Our webserver's document root is `/var/www/html/intra-devportalz.prod.jp.local`
and our Drupal instance is installed in `/var/www/html/intra-devportalz.prod.jp.local/intra`

``` 
$ cd ~/sites/intra-devportalz.prod.jp.local/

$ ls
favicon.ico		healthcheck.html	intra			wwwcheck.html

$ ls intra/
LICENSE.txt		composer.json		example.gitignore	modules			sites			vendor
README.txt		composer.lock		index.php		profiles		themes			web.config
autoload.php		core			libraries		robots.txt		update.php
```

#### Step: backup, gzip, and download PROD database

``` 
$mysqldump -Pxxxx -uxxxxxxxx -p'xxxxxxxx' -h my-db-server drupal > /tmp/drupal-backup_$(date +%FT%H%M).sql
```

#### Step: change drupalvm config.yml

```
$ diff -w default.config.yml config.yml
18,20c18,20
< vagrant_hostname: drupalvm.test
< vagrant_machine_name: drupalvm
< vagrant_ip: 192.168.88.88
---
> vagrant_hostname: drc-i.local
> vagrant_machine_name: drc-i
> vagrant_ip: 192.168.88.90
34,35c34,35
<   - local_path: .
<     destination: /var/www/drupalvm
---
>   - local_path: ~/sites/intra-devportalz.prod.jp.local
>     destination: /var/www/intra-devportalz.prod.jp.local
77c77
< drupal_build_composer_project: true
---
> drupal_build_composer_project: false
83c83
< drupal_install_site: true
---
> drupal_install_site: false
86c86
< drupal_core_path: "{{ drupal_composer_install_dir }}/web"
---
> drupal_core_path: "/var/www/intra-devportalz.prod.jp.local"
230c232
<   - varnish
---
>   # - varnish
262c264
< php_memory_limit: "192M"
---
> php_memory_limit: "500M"
```

#### Step: Run DrupalVM install

```
$ time vagrant up

[output snipped]

PLAY RECAP *********************************************************************
drc-i                      : ok=219  changed=86   unreachable=0    failed=0


==> drc-i: Machine 'drc-i' has a post `vagrant up` message. This is a message
==> drc-i: from the creator of the Vagrantfile, and not from Vagrant itself:
==> drc-i:
==> drc-i: Your Drupal VM Vagrant box is ready to use!
==> drc-i: * Visit the dashboard for an overview of your site: http://dashboard.drc-i.local (or http://192.168.88.90)
==> drc-i: * You can SSH into your machine with `vagrant ssh`.
==> drc-i: * Find out more in the Drupal VM documentation at http://docs.drupalvm.com

real	9m12.009s
user	1m20.203s
sys	0m27.997s
```

#### Step: load http://dashboard.drc-i.local/

Success

``` 
Hostname    Document Root                           Drush alias*
drc-i.local /var/www/intra-devportalz.prod.jp.local drush @drc-i.drc-i.local
```

#### Step: click "pimp my log" -> "open" button

loads http://pimpmylog.drc-i.local/

set up user drupal/drupal
[x] apache is already selected
click "continue"
Apache access and error logs detected
click "continue"
see "Congratulations!" page
click "Pimp my logs now" button

login with drupal/drupal

Date column filled with "ERROR ! Unable to convert this string to date " messages, but otherwise I can see the logs

#### Step: return to dashboard and click "Mailhog" -> "open" button

loads http://drc-i.local:8025/

I see a "connected" green circle in upper left of page and "Inbox (0)" notice

#### Step: return to dashboard and click "adminer" -> "open" button

loads http://adminer.drc-i.local/index.php

login as per notice on dashboard:
user: drupal
password: drupal
database: drupal

verify the database is "drupal" in upper left part of page
see "no tables" message

click "import" link in left-nav
use file upload panel
choose drupal-backup_xxxxxxxx.sql.gz file
click "execute" button

See "1218 queries executed OK" message
See a bunch (50+) of "select xxxxxxxx" links appear in the left-nav

Click "select users" link
Click "Select data" link
See a bunch of rows returned.

So it looks like the database imported ok

#### Step: return to dashboard and click link to http://drc-i.local/

see "Forbidden" error

#### Step: check "Pimp my log"

See:
```
[pid 12592:tid 140600275871488] [client 192.168.88.1:63473] AH01276: Cannot serve directory /var/www/intra-devportalz.prod.jp.local/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm,index.php,index.html) found, and server-generated directory index forbidden by Options directive
```

#### Step: edit URL to http://drc-i.local/healthcheck.html

see PROD server name as expected

So Apache is running

#### Step: change URL to http://drc-i.local/intra

redirected to PROD server 403 error page

#### Step: change URL to http://drc-i.local/intra/ (note trailing slash)

Page spins for a while (20 seconds?) then gives message: `The website encountered an unexpected error. Please try again later.`

#### Step: check pimp my log

See:
``` 
[pid 12593:tid 140600309442304] [client 192.168.88.1:63586] AH01071: Got error 'PHP message: PDOException: SQLSTATE[HY000] [2002] Connection timed out in /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php on line 79 #0 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php(149): PDO->__construct('mysql:host=dm-d...', 'drupal', 'drupal', Array)

#1 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Core/Database/Database.php(376): Drupal\\Core\\Database\\Driver\\mysql\\Connection::open(Array)
#2 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Core/Database/Database.php(166): Drupal\\Core\\Database\\Database::openConnection('default', 'default')
#3 [internal function]: Drupal\\Core\\Database\\Database::getConnection('default')
#4 /var/www/intra-devportalz.prod.jp.local/intra/core/lib/Drupal/Component/DependencyInjection/PhpArrayContainer.php(79): call_user_func_array('Drupal\\\\Core\\\\Dat...', Array)
#5 /var/www/intra-devportalz.prod.jp.local/intra/cor...
'
```

**Comment by geerlingguy** [comment]
In your codebase (probably in `/var/www/intra-devportalz.prod.jp.local/intra/sites/default/settings.php`), what database connection details are being used? It needs to know to connect to localhost, port 3306, username `drupal`, password `drupal`, using the `mysql` driver.

So if your settings.php file is still directing DB requests at the production database server, it's going to time out, because that server URL and username/password are likely not the same as the defaults for Drupal VM!

**Comment by scottcale** [comment]
Thank you so much!

Now I am able to load and login to my site locally!

Someday I'll need to find a way to have both the `dev` and `prod` database settings in the same repo. But for now, that works very well for me. 

(While I have your attention and before I close the ticket, is this article appropriate to transition my current ad-hoc/manual D8 site to DrupalVM?  https://www.jeffgeerling.com/blog/2017/soup-nuts-using-drupal-vm-build-local-and-prod )

For anyone coming to this ticket in the future, the specific change I made was:

``` diff
$ pwd
/Users/scott.cale/sites/intra-devportalz.prod.jp.local

$ git diff -- intra/sites/default/settings.php
diff --git a/intra/sites/default/settings.php b/intra/sites/default/settings.php
--- a/intra/sites/default/settings.php
+++ b/intra/sites/default/settings.php
@@ -771,11 +771,11 @@
 # }
 $databases['default']['default'] = array (
   'database' => 'drupal',
-  'username' => 'xxREDACTEDxx',
-  'password' => 'xxREDACTEDxx',
+  'username' => 'drupal',
+  'password' => 'drupal',
   'prefix' => '',
-  'host' => 'my-db-server',
-  'port' => 'xxxx',
+  'host' => 'localhost',
+  'port' => '',
   'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
   'driver' => 'mysql',
 );
```

**Comment by geerlingguy** [comment]
@scottcale - Glad I could help!

> While I have your attention and before I close the ticket, is this article appropriate to transition my current ad-hoc/manual D8 site to DrupalVM?

If you want to run your Drupal 8 site on a VPS that is managed by Drupal VM, that would be the best way to do it. There are likely some lighter weight options, though (including managed hosting), if you don't necessarily need all the flexibility that Drupal VM gives you :)
