### ISSUE TITLE
ansible remote provisioner: * The following settings shouldn't exist: compatibility_mode

### ISSUE THREAD

**Issue by sandipsmarty** [geerlingguy/drupal-vm#1855]
Vagrant 1.9.4
ansible 2.5.0
OS version: MacOs 10.14 (Mojave)

After upgrading my MacOS version to the latest 10.14 (Mojave) I am getting the below error when running `vagrant up`

> There are errors in the configuration of this machine. Please fix
> the following errors and try again:
> 
> ansible remote provisioner:
> * The following settings shouldn't exist: compatibility_mode

#https://github.com/Exodus-Privacy/exodus/issues/125

**Comment by geerlingguy** [comment]
@sandipsmarty - You will need to upgrade Vagrant to a newer version; 2.2.0 is the current latest version: https://www.vagrantup.com/downloads.html

**Comment by sandipsmarty** [comment]
@geerlingguy : Thanks! 👍
