### ISSUE TITLE
Docker container not working

### ISSUE THREAD

**Issue by adaltavo** [geerlingguy/drupal-vm#1856]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Docker CE  18.09.0-ce-beta1 for MacOS (Edge version)
```

### Your OS

 - **macOS** (10.13.6)

### Full console output

[gist](https://gist.github.com/adaltavo/99b48d5c49108691210864396e372e0c)
### Summary

using docker container with tag "latest", when running the command:
`docker exec drupalvm install-drupal`

after a while shows the following output:
```
In SiteInstallCommands.php line 354:
                                                                               
  Failed to create database: ERROR 2002 (HY000): Can't connect to local MySQL  
   server through socket '/var/run/mysqld/mysqld.sock' (2 "No such file or di  
  rectory")    
```

I tried with container version (tag) 4.8.1 and everything works as intended

**Comment by geerlingguy** [comment]
It sounds like for some reason the MySQL service isn't starting up properly. I'll have to take a look as to why that's the case.

**Comment by bioborg** [comment]
So, it looks like a systemd launch was attempted, but it failed?  dbus isn't running? 

f1c43a15f0b6        geerlingguy/drupal-vm   "/lib/systemd/systemd"   7 minutes ago       Up 7 minutes        0.0.0.0:80->80/tcp, 3306/tcp, 0.0.0.0:443->443/tcp, 8025/tcp   drupalvm
root@DebFang:/home/fang/VMs# docker exec -it f1c43a15f0b6 /bin/bash
root@f1c43a15f0b6:/# /etc/init.d/mysql start
Failed to connect to bus: No such file or directory
[....] Starting mysql (via systemctl): mysql.serviceFailed to connect to bus: No such file or directory
 failed!
root@f1c43a15f0b6:/# systemctl start mysql
Failed to connect to bus: No such file or directory

**Comment by geerlingguy** [comment]
If it's a problem like 'Failed to connect to bus', then that means you might not be starting the container with the right volume mounts—see https://github.com/geerlingguy/drupal-vm/blob/master/example.docker-compose.yml#L30

**Comment by d70rr3s** [comment]
> 
> 
> If it's a problem like 'Failed to connect to bus', then that means you might not be starting the container with the right volume mounts—see https://github.com/geerlingguy/drupal-vm/blob/master/example.docker-compose.yml#L30

Hi @geerlingguy I'm getting this error but when trying to bake a fresh image from the container. I've follow the instructions about the volumes but still not working. In my case I'm getting the error during provitioning when checking that POSTFIX service is started

```bash
TASK [geerlingguy.postfix : Ensure postfix is installed.]
**********************************************************
ok: [localhost]

TASK [geerlingguy.postfix : Update Postfix configuration.]
**********************************************************
ok: [localhost] => (item={u'name': u'inet_interfaces', u'value': u'localhost'})
ok: [localhost] => (item={u'name': u'inet_protocols', u'value': u'all'})

TASK [geerlingguy.postfix : Ensure postfix is started and enabled at boot.]
**********************************************************
fatal: [localhost]: FAILED! => {
"changed": false, 
"cmd": "/bin/systemctl", 
"msg": "Failed to connect to bus: No such file or directory", 
"rc": 1, 
"stderr": "Failed to connect to bus: No such file or directory\n", 
"stderr_lines": ["Failed to connect to bus: No such file or directory"], 
"stdout": "", "stdout_lines": []}
to retry, use: --limit @/etc/ansible/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************
localhost                  : ok=16   changed=0    unreachable=0    failed=1
```
Any advice?

**Comment by pwayner** [comment]
I'm getting a similar error using Docker on Ubuntu. 
```

 // You are about to CREATE the 'drupal' database. Do you want to continue?:    
 // yes.                                                                        


In SiteInstallCommands.php line 367:
                                          
  Failed to drop or create the database:  
                                          

site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...

```

**Comment by poindexterous** [comment]
I have this issue as well, I'm using "method 1" on the drupalvm docker installation docs:
http://docs.drupalvm.com/en/latest/other/docker/

` // You are about to CREATE the 'drupal' database. Do you want to continue?:
 // yes.


In SiteInstallCommands.php line 367:

  Failed to drop or create the database:


site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify] [--xh-link XH-LINK] [--] <command> [<profile>]...`

**Comment by poindexterous** [comment]
I have this issue as well, I'm using "method 1" on the drupalvm docker installation docs:
http://docs.drupalvm.com/en/latest/other/docker/

` // You are about to CREATE the 'drupal' database. Do you want to continue?:
 // yes.


In SiteInstallCommands.php line 367:

  Failed to drop or create the database:


site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify] [--xh-link XH-LINK] [--] <command> [<profile>]...`

I wonder if this might be an issue with drush using site-install, the drush version seems to be 9.6.2. It does not appear as if the database creation step was successful. I'm also on a windows 10 environment.

**Comment by geerlingguy** [comment]
Quick fix is:

> Inside the container (if you do `docker exec -it [docker container name] bash`), you can run `systemctl start mysql` and I believe that will get it running. It's a little bit difficult to figure that out because the Drush message doesn't really indicate the server's not _running_ at all.

(Moved that comment from related issue #1937).

**Comment by gparami** [comment]
"Method 1" on the Drupal VM Docker installation docs will work if you add the volumes to the docker run command.
Use the following Docker run command and Drupal 8 should work:
`docker run -d -v /sys/fs/cgroup:/sys/fs/cgroup:ro -p 80:80 -p 443:443 --name=drupalvm --privileged geerlingguy/drupal-vm`
`docker exec drupalvm install-drupal 8.x-dev`
> you can choose a version using install-drupal [version], using versions like `8.x-dev` or `7.x-dev`
