### ISSUE TITLE
extra_packages are not installed

### ISSUE THREAD

**Issue by denics** [geerlingguy/drupal-vm#1858]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
VirtualBox 5.2.20r125813
ansible 2.7.1
  config file = /Volumes/Denix/git/VM/unescorg/provisioning/ansible.cfg
  configured module search path = ['/Users/denix/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jul 30 2018, 10:36:50) [Clang 9.1.0 (clang-902.0.39.2)]
```

### Your OS

 - **macOS** 10.14

### Summary

Actually extra_packages are not installed. I realized that when trying to use apache + mod_php 7.0 instead than the default apache+php-fpm

**Comment by geerlingguy** [comment]
Can you share your config.yml change to override the extra_packages variable? If it's not working, it may be because you don't have it formatted as a list. It should be like:

```yaml
extra_packages:
  - package_one
  - package_two
  - etc
```

If you have it formatted like:

```yaml
extra_packages: package_one,package_two,etc
```

Then it will not work.

**Comment by denics** [comment]
Thanks @geerlingguy . I think it should be fine like this:

```yaml
# Add any extra apt or yum packages you would like installed.
extra_packages:
  - "sqlite"
  - "libapache2-mod-php7.0"
```

**Comment by denics** [comment]
And I agree with you, this is why my PR is to remove the ```|```

**Comment by geerlingguy** [comment]
Oh, I was reading it as adding it for some reason. I'm going to need to dig through git history and see why it was added in the first place. There might've been a valid reason for backwards compatibility or something.

**Comment by geerlingguy** [comment]
Closed the PR related to this issue, as I can't reproduce the behavior described in this issue; please try with the latest version of everything and see if the behavior is still not what you're expecting, and if so, we can reopen the issue and check into it further.
