### ISSUE TITLE
mod_php not working

### ISSUE THREAD

**Issue by denics** [geerlingguy/drupal-vm#1860]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
VirtualBox 5.2.20r125813
ansible 2.7.1
  config file = None
  configured module search path = ['/Users/denix/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.0 (default, Jul 30 2018, 10:36:50) [Clang 9.1.0 (clang-902.0.39.2)]
```

### Your OS

 - **macOS** 10.14
### Summary

Apache role cannot create link with mod_php7.0.load because mod_php has not been installed yet. solution is to move the ```tasks/extras.yml``` into pre-tasks sections.

**Comment by geerlingguy** [comment]
Can you provide a list of what conditions led to this failure, along with any relevant error messages? I don't know how to debug what you're seeing; also the default version of PHP installed is 7.1, so are you also switching PHP versions?

Are you using this guide to switch to using mod_php? http://docs.drupalvm.com/en/latest/other/bigpipe/#apache-configuration — It was last tested a year or so ago but should still work fine.

**Comment by denics** [comment]
Yep, I am using the guide. The issue is that when activating the option to use mod_php (yes, I am using 7.0, but the same happens with 7.1) the extra packages are installed after the tasks. This is the message I get:

```
TASK [geerlingguy.apache : Enable Apache mods.] ********************************
changed: [drupalvm] => (item=expires.load)
changed: [drupalvm] => (item=headers.load)
changed: [drupalvm] => (item=ssl.load)
changed: [drupalvm] => (item=rewrite.load)
changed: [drupalvm] => (item=proxy.load)
failed: [drupalvm] (item=php7.0.load) => {"changed": false, "item": "php7.0.load", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /etc/apache2/mods-available/php7.0.load", "path": "/etc/apache2/mods-enabled/php7.0.load", "src": "/etc/apache2/mods-available/php7.0.load", "state": "absent"}
```

When moving the extra installation to the *pre_tasks* (I think it makes sense) everything works fine.

**Comment by denics** [comment]
Hi @geerlingguy I can confirm the same issue with, for example, php-zip. Without this patch installing a module with php dependencies using composer will fail. I.e. I want to install gdpr module, so php-zip is a dependence. If the extra packages are not installed in the pre-task or at the beginning of the task session, then the composer command will fail.

**Comment by geerlingguy** [comment]
If you just need `php-zip`, can you add it to the `php_packages_extra` list instead of adding it into wherever you have it currently? (see https://github.com/geerlingguy/ansible-role-php#role-variables)

**Comment by geerlingguy** [comment]
(not sure if this is a bug)
