### ISSUE TITLE
Error with Ansible local: "settings shouldn't exist: compatibility_mode"

### ISSUE THREAD

**Issue by brockfanning** [geerlingguy/drupal-vm#1861]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.6
zsh: command not found: vboxmanage
VirtualBox
zsh: command not found: ansible
```
^^^
I'm in Windows which is probably why these commands aren't recognized? VirtualBox version is 5.1.6, and Ansible is not installed (have been relying on local Ansible inside the VM)

### Your OS

 - **Windows** (version)

### Full console output

```
$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible local provisioner:
* The following settings shouldn't exist: compatibility_mode
```

### Summary

We have been using DrupalVM with this particular setup for a while, but this problem has started recently. I believe it's probably related to this commit? https://github.com/geerlingguy/drupal-vm/commit/1661c3654a2ffb2d8d955f5643e6d6793f983203

If we manually remove the line `ansible.compatibility_mode = "2.0"` then it is able to get past that point. Is it possible that line is not compatible (pun intended) with local Ansible? If so I can probably come up with a PR to wrap that line in a conditional.

**Comment by geerlingguy** [comment]
@brockfanning - You should to upgrade to a newer version of Vagrant; the current version is 2.2.0, and has a number of optimizations for networking and newer OS versions, in addition to a few features (like the compatibility mode setting) which will end up causing more pain if you try to run Drupal VM in an older version.

**Comment by brockfanning** [comment]
Aha, thanks for the info @geerlingguy!
