### ISSUE TITLE
Virtual-disk compaction tutorial requires rebooting VM and accessing GRUB menu

### ISSUE THREAD

**Issue by UTANdev** [geerlingguy/drupal-vm#1863]
### Issue Type

Support Request

### Your Environment

Vagrant 1.8.7
VirtualBox 5.1.18r114002
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
### Your OS

Ubuntu 16.04 LTS

### Summary

* I need to compact my virtual disk and am following the tutorial at https://www.howtogeek.com/312883/how-to-shrink-a-virtualbox-virtual-machine-and-free-up-disk-space/ .
* To use `zerofree` inside the VM, I must reboot and select Advanced Options for Ubuntu in the GRUB menu.

How can I do this in a *guest* OS?

**Comment by UTANdev** [comment]
(And yes, I understand my setup is ancient. I'm just getting back into things after a long absence.)

**Comment by geerlingguy** [comment]
I'm not quite sure how that would be done, but I would recommend asking in the VirtualBox forums, as this is not a Drupal VM-specific action, and there are probably a lot more people familiar with virtual disk management in other forums.

**Comment by UTANdev** [comment]
I was so focused on SSH usage that I temporarily forgot you can control the VM through the main VirtualBox utility. For posterity: do a graceful shutdown of DrupalVM (`sudo -su`, `shutdown now`), then start the VM from VirtualBox (which will display a boot screen) and quickly press ESC to bring up the GRUB menu.

**Comment by geerlingguy** [comment]
@UTANdev - ah, perfect! And thank you so much for posting that here, for the benefit of any future searchers who want to do the same thing.
