### ISSUE TITLE
unable to run drush sql-drop

### ISSUE THREAD

**Issue by anakinjay** [geerlingguy/drupal-vm#1865]
### Issue Type
Bug Report

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment
Vagrant 2.2.1
VirtualBox 5.2.20r125813
ansible 2.7.2
  config file = None
  configured module search path = [u'/Users/aj/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]

```

```

### Your OS
**macOS** (Mojave 10.14)

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

### Full console output
```
Drush Launcher Version: 0.6.0
ROOT: /var/www/wvufs
DRUSH VERSION: 9
DRUPAL ROOT: /var/www/wvufs/docroot
COMPOSER ROOT: /var/www/wvufs
VENDOR ROOT: /var/www/wvufs/vendor
 [preflight] Config paths: /var/www/wvufs/vendor/drush/drush/drush.yml,/var/www/wvufs/drush/drush.yml
 [preflight] Alias paths: /var/www/wvufs/docroot/drush/sites,/var/www/wvufs/drush/sites
 [preflight] Commandfile search paths: /var/www/wvufs/vendor/drush/drush/src
 [bootstrap] Starting bootstrap to max [0.17 sec, 7.87 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.17 sec, 8.06 MB]
 [bootstrap] Change working directory to /var/www/wvufs/docroot [0.17 sec, 8.06 MB]
 [bootstrap] Initialized Drupal 8.6.3 root directory at /var/www/wvufs/docroot [0.17 sec, 8.06 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.18 sec, 8.52 MB]
 [bootstrap] Initialized Drupal site default at sites/default [0.18 sec, 8.52 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.18 sec, 8.52 MB]
 [debug] Add service modifier [0.19 sec, 8.81 MB]
 [info] sql-query: SHOW TABLES; [0.2 sec, 9.09 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_eWArDe --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_khKote [0.2 sec, 9.09 MB]
  wvufs.data_point_entity__widget
 [info] sql-query: DROP TABLE wvufs.data_point_entity__widget [0.22 sec, 9.09 MB]
 [info] Executing: mysql --defaults-file=/tmp/drush_spDB3e --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_KB5tQe [0.22 sec, 9.09 MB]
  ERROR 1051 (42S02) at line 1: Unknown table 'wvufs.data_point_entity__widget'

In SqlCommands.php line 118:

  [Exception]
  Unable to drop database. Rerun with --debug to see any error message.


Exception trace:
 () at /var/www/wvufs/vendor/drush/drush/src/Commands/sql/SqlCommands.php:118
 Drush\Commands\sql\SqlCommands->drop() at n/a:n/a
 call_user_func_array() at /var/www/wvufs/vendor/consolidation/annotated-command/src/CommandProcessor.php:246
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/wvufs/vendor/consolidation/annotated-command/src/CommandProcessor.php:181
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/wvufs/vendor/consolidation/annotated-command/src/CommandProcessor.php:150
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/wvufs/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:404
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/wvufs/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/wvufs/vendor/symfony/console/Application.php:971
 Symfony\Component\Console\Application->doRunCommand() at /var/www/wvufs/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /var/www/wvufs/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /var/www/wvufs/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /var/www/wvufs/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /var/www/wvufs/vendor/drush/drush/drush.php:66
 require() at /var/www/wvufs/vendor/drush/drush/includes/preflight.inc:17
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:141
 require() at /usr/local/bin/drush:10
```

### Summary
I get this error when I try and run drush sql-drop.  This error occurs both when I run sql-drop directly, or when attempting to run a blt dsa operation.   I can manually log into mysql, drop the database, and recreate the database, then the blt dsa op will complete.

but unless I drop the DB manually, the drush sql-drop command always errors out.

**Comment by cosmicdreams** [comment]
From inside the VM?  

It seems to be failing because it expects the table: wvufs.data_point_entity__widget to be present.  I wonder if you have config / a custom entity that is informing Drupal that such a table exists, but it doesn't really exist.

Is that the case?

**Comment by anakinjay** [comment]
Yep from inside the VM. 

If I go into the mysql console and do a show tables, it says that table exists.

**Comment by cosmicdreams** [comment]
Oh, there's one more thing that I don't understand from your log.  Both lines that log mysql query execution refer to the database name being "drupal":

```info] Executing: mysql --defaults-file=/tmp/drush_eWArDe --database=drupal --host=localhost --port=3306 --silent  < /tmp/drush_khKote [0.2 sec, 9.09 MB]```

And yet the table that is having an issue has the syntax of:

```wvufs.data_point_entity__widget```

The "wvufs." part refers to the database and the "data_point_entity___widget" part refers to the table right?

If that's the case, are you really attempting to execute a sql-drop action on the drupal database which should then have a secondary effect of dropping a table from a different database?  Because you've created a custom relationship between these tables from different databases?

And if not, can you post your settings.php / local.settings.php where the database configuration is defined so we can understand how your project's database connections are configured?

**Comment by anakinjay** [comment]
Nope, wvufs.data_point_entity__widget is the name of the table on the drupal database. (see below)

![screenshot 2018-11-27 15 57 23](https://user-images.githubusercontent.com/1062577/49111107-2f0c0f80-f25d-11e8-9ada-fed221619f15.png)



here's my database config, pretty standard:

```$databases = array(
  'default' =>
  array(
    'default' =>
    array(
      'database' => $db_name,
      'username' => 'drupal',
      'password' => 'drupal',
      'host' => 'localhost',
      'port' => '3306',
      'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
      'driver' => 'mysql',
      'prefix' => '',
    ),
  ),
);```

**Comment by cosmicdreams** [comment]
That table does stand out a being the source of problem.  Is there any way it can adopt the snake case formatting of the other tables.  I don't know for certain but I suspect the "." is confusing the script (or rather that the drush script doesn't properly escape that character.

Either way, this isn't a drupal_vm issue.  It's a drush issue. The command is something that Drupal VM uses but is not under code control here.

**Comment by anakinjay** [comment]
Ahh ok thanks for taking the time to check in with it then!  I'll play around with changing the table name, and if that doesn't work I'll log a ticket with drush.

Sorry to bother!

**Comment by vocus-tan** [comment]
is there a solution to this guys? I've been stuck with this error in my CI pipelines for a few days :-)
