### ISSUE TITLE
Unknown interface enp0s8

### ISSUE THREAD

**Issue by Michel-Settembrino** [geerlingguy/drupal-vm#1866]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
VirtualBox 5.2.20r125813
ansible 2.7.0
  config file = None
  configured module search path = [u'/Users/michel/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Aug 17 2018, 17:41:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.0.42)]
```

### Your OS

 - **macOS** (Mojave 10.14.1)

### Full console output

https://gist.github.com/Michel-Settembrino/978b3bb5fa65417774aaa56274d7bc05

### Summary

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

/sbin/ifdown 'enp0s8' || true
/sbin/ip addr flush dev 'enp0s8'
# Remove any previous network modifications from the interfaces file
sed -e '/^#VAGRANT-BEGIN/,$ d' /etc/network/interfaces > /tmp/vagrant-network-interfaces.pre
sed -ne '/^#VAGRANT-END/,$ p' /etc/network/interfaces | tac | sed -e '/^#VAGRANT-END/,$ d' | tac > /tmp/vagrant-network-interfaces.post
cat \
  /tmp/vagrant-network-interfaces.pre \
  /tmp/vagrant-network-entry \
  /tmp/vagrant-network-interfaces.post \
  > /etc/network/interfaces
rm -f /tmp/vagrant-network-interfaces.pre
rm -f /tmp/vagrant-network-entry
rm -f /tmp/vagrant-network-interfaces.post

/sbin/ifup 'enp0s8'

Stdout from the command:

Failed to bring up enp0s8.


Stderr from the command:

Unknown interface enp0s8
run-parts: /etc/network/if-up.d/postfix exited with return code 75
```

**Comment by geerlingguy** [comment]
The problem could also be related to the VirtualBox version in use. I think my boxes were most recently built with VirtualBox 5.2.20; it could be an issue with the guest addition installation for 5.2.22.

**Comment by geerlingguy** [comment]
Actually, they were built with 5.2.22. Can you upgrade VirtualBox on your computer to 5.2.22 and then try doing a new `vagrant up` again?

**Comment by Michel-Settembrino** [comment]
I upgraded VirtualBox but still same issue.

**Comment by Michel-Settembrino** [comment]
I was using version 2.2.0 of Vagrant. So I upgraded to the latest version 2.2.2
Still same issue.

And now, I have some warning:

> Vagrant has detected a configuration issue which exposes a
> vulnerability with the installed version of VirtualBox. The
> current guest is configured to use an E1000 NIC type for a
> network adapter which is vulnerable in this version of VirtualBox.
> Ensure the guest is trusted to use this configuration or update
> the NIC type using one of the methods below:
> 
> https://www.vagrantup.com/docs/virtualbox/configuration.html#default-nic-type
> https://www.vagrantup.com/docs/virtualbox/networking.html#virtualbox-nic-type

**Comment by geerlingguy** [comment]
For that warning, see https://github.com/geerlingguy/drupal-vm/issues/1869

And I'm still not sure what's causing that `enp0s8` issue... can you post your full `config.yml` file? Are you using a different base box?

**Comment by Michel-Settembrino** [comment]
Yes for sure. 
[config.txt](https://github.com/geerlingguy/drupal-vm/files/2647630/config.txt)

No I'm using the default base box.
```
vagrant box list
geerlingguy/drupal-vm  (virtualbox, 1.0.2)
geerlingguy/ubuntu1604 (virtualbox, 1.2.2)
geerlingguy/ubuntu1604 (virtualbox, 1.2.3)
geerlingguy/ubuntu1604 (virtualbox, 1.2.4)
vccw-team/xenial64     (virtualbox, 20180107)
```

What is very strange is that this exact same config with an older version of Drupal-vm works! See https://github.com/geerlingguy/drupal-vm/issues/1866#issuecomment-443243770

**Comment by geerlingguy** [comment]
Can you try running `vagrant up --debug` and see the exact commands being run which seem to be failing?

**Comment by Michel-Settembrino** [comment]
After this error I did next things:
1. vagrant up
That went fine but when I sshed into the box, the destination 'drupalvm' didn't exist in '/var/www/'.
1. vagrant provision
That went fine but when I sshed into the box, the destination 'drupalvm' didn't exist in '/var/www/'.
1. vagrant reload
That went fine and folder 'drupalvm' got created. So the box is running fine now.

Do you know what's going wrong?

**Comment by geerlingguy** [comment]
So it sounds like this is definitely `vagrant` or VirtualBox-related, as vagrant up/provision is not good, but after reloading it is working... I would suggest asking further questions in the Vagrant project issue queue, as I don't know how much more I could help as I've only seen this error a couple times (and never on my own computer) :(
