### ISSUE TITLE
Invalid Mutex directory in argument file:${APACHE_LOCK_DIR}

### ISSUE THREAD

**Issue by kartagis** [geerlingguy/drupal-vm#1871]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.2
VirtualBox 5.2.22r126460
ansible 2.7.2
```

### Your OS

 - **macOS** 14

### Full console output

https://gist.github.com/kartagis/6d5d4b5cf3484f152f32e78688b3c77f

### Summary

I typed apache2 -t and I got back Invalid Mutex directory in argument file:${APACHE_LOCK_DIR}```. The offending line in apache.conf is ```Mutex file:${APACHE_LOCK_DIR} default```

**Comment by geerlingguy** [comment]
@kartagis - This is expected. You wouldn't typically run `apache2` commands outside of the init scripts or systemd unit files, which also include extra environment variables necessary to start/control Apache correctly.

See: https://serverfault.com/a/558296/15673

If you run instead:

```
$ source /etc/apache2/envvars
$ apache2 -t
Syntax OK
```

That should work. See: https://askubuntu.com/a/932059/88829
