### ISSUE TITLE
Provision hangs at "TASK [Run configured post-provision shell scripts.]"

### ISSUE THREAD

**Issue by UTANdev** [geerlingguy/drupal-vm#1873]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 1.8.7
VirtualBox 5.1.18r114002
ansible 2.2.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

### Your OS

 - **Linux** (Ubuntu 16.04.3 LTS)

### Full console output

https://gist.github.com/UTANdev/339b31788adde16059a1611c6540a089

### Summary

My first try at a post-provisioning script. `config.yml` excerpt:

```
pre_provision_scripts: []
post_provision_scripts:
  - "../scripts/post-provision.sh"
```

post-provision.sh: (with debugging statements)

```
#!/bin/bash
echo "starting post-provision.sh…"
set -x
OPTIONS=`vagrant ssh-config | tail -n +2 | awk -v ORS=' ' '{print "-o " $1 "=" $2}'`
scp ${OPTIONS} /home/monkey/.gitconfig kpuc.local:/home/vagrant/.gitconfig
```

-rwxrwxr-x 1 monkey monkey 216 Dec  5 10:32 scripts/post-provision.sh*

I can run it fine from bash:

```
monkey@Sonic ~/sites/VMs/kpuc $ scripts/post-provision.sh
starting post-provision.sh…
++ vagrant ssh-config
++ tail -n +2
++ awk -v 'ORS= ' '{print "-o " $1 "=" $2}'
+ OPTIONS='-o HostName=127.0.0.1 -o User=vagrant -o Port=2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentityFile=/home/monkey/.vagrant.d/insecure_private_key -o IdentitiesOnly=yes -o LogLevel=FATAL -o ForwardAgent=yes -o = '
+ scp -o HostName=127.0.0.1 -o User=vagrant -o Port=2222 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o PasswordAuthentication=no -o IdentityFile=/home/monkey/.vagrant.d/insecure_private_key -o IdentitiesOnly=yes -o LogLevel=FATAL -o ForwardAgent=yes -o = /home/monkey/.gitconfig kpuc.local:/home/vagrant/.gitconfig
.gitconfig                                    100% 2078     2.0KB/s   00:00
```

but when provisioning, Vagrant just hangs at the "TASK [Run configured post-provision shell scripts.] ****************************" step. What's wrong? Thanks for your help.

**Comment by geerlingguy** [comment]
Yeah, I would try @BWPanda's suggestion first, and see if that helps.

The strange thing is, that task shouldn't get stuck/hang unless it does find something at the path you're giving it.

Also, to do some testing/debugging, I would try changing your script to something super duper simple like:

```
#!/bin/bash
echo "Test"
```

Then see if that works. It could be that the environment in which the script is being run is different than you expect, so one of the commands either fails or waits for a prompt (usually the latter situation leads to Ansible playbooks hanging).

**Comment by frob** [comment]
@UTANdev,  Looking at your script, it looks like your script is made to run on the host. Remember, the `post_provision_scripts` run from inside DrupalVM.
