### ISSUE TITLE
Default to PHP 7.2, add option of 7.3

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1874]
PHP 7.3.0 has been released: http://php.net/releases/7_3_0.php

We should update the default version for Drupal VM to 7.2, update all the docs, and also support/test 7.3. Hopefully should "just work" with the PHP versions role.

**Comment by geerlingguy** [comment]
See previous ticket adding support for 7.2: https://github.com/geerlingguy/drupal-vm/issues/1552

**Comment by geerlingguy** [comment]
Working on completing the addition of 7.3 support here: https://github.com/geerlingguy/ansible-role-php-versions/issues/28

Also dropping the mcrypt extension from default support... if you want to still use it (against the PHP community's recommendation), it's up to you to get the right packages/PECL install configuration to get it added to 7.2 or 7.3.

**Comment by geerlingguy** [comment]
I think this could be the next major Drupal VM release... it's nothing huge/major, but it is a big enough change that I want people to double-check their configs, especially if they're building Drupal 7 sites on Drupal VM!

Or even Drupal 6... though those users will likely have so many little customizations to keep old stuff hanging around, it makes me shudder.

**Comment by geerlingguy** [comment]
Also, 5.6 support is done in < 3 days. So maybe drop official 5.6 support too? It will be harder/impossible to install 5.6 on modern OSes after the 3rd party repos drop support... which will be very soon.

As bane says, "it would be extremely painful" ... "for [those who haven't upgraded from 5.x]"

https://www.youtube.com/watch?v=w9wi0cPrU4U

**Comment by joelpittet** [comment]
I would like to keep 5.x support. Discussions in Drupal are here as to not repeat my pity plea. https://www.drupal.org/project/drupal/issues/2581193#comment-12922394

**Comment by joelpittet** [comment]
And more on topic, I'm trying to upgrade to PHP 7.2 from  `"geerlingguy/drupal-vm": "^4.9"` and using CentOS 7 and after reprovisioning a few times by changing to `php_version: "7.2"` . the installed version seems to be still `php.x86_64                            7.1.26-1.el7.remi              @remi-php71`, shall I open a ticket?

**Comment by joelpittet** [comment]
I think I just needed to remove the old packages before reprovisioning.  Some small issues with xdebug package not working but pecl compiled one working with 7.2.

**Comment by geerlingguy** [comment]
Note that xdebug (especially if you use BLT which defaults to an older version) needs to have its version updated in your config.yml if it's causing issues. Drupal VM defaults to a newer version that should be compatible out of the box.

**Comment by geerlingguy** [comment]
And regarding PHP 5.6 support... the problem is upstream packaging maintainers will stop maintaining their 5.6 repos. Once that happens it will literally be impossible to install PHP 5.6 without either compiling from source (takes forever, but you can get Drupal VM to do that with the default roles), or maintaining your own apt/yum package repositories (eek!).

The best option IMO would be to use debian9, debian8, or centos7 base box and not use the remi repos (switch back to standard centos) if you need older versions of PHP... it's not ideal and you get a lot less control, but it's doable.

I just don't want to spend a huge amount of time trying to support ancient PHP versions that have already been deprecated and _removed_ from most web hosting platforms already. You have to expect that if you're running on really old versions of software, you'll have to do a lot more work to be able to do that. I'm not going to block that work, but I'm not going to assist with it either.

**Comment by geerlingguy** [comment]
The PR above passed with flying colors except for the drush make test (ha, I forgot I even support .make files still!). The problem there is due to this Drupal core issue: [Lazy started sessions with session data are not saved with symfony/http-foundation 3.4.24](https://www.drupal.org/project/drupal/issues/3045349)

And the error is:

```
TASK [geerlingguy.drupal : Install Drupal with drush.] *************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["drush", "site-install", "standard", "-y", "--root=/var/www/drupalvm/drupal", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:26.850450", "end": "2019-04-04 20:56:01.561065", "msg": "non-zero return code", "rc": 1, "start": "2019-04-04 20:55:34.710615", "stderr": "Starting Drupal installation. This takes a while. Consider using the \u001b[1;32;40m\u001b[1m[ok]\u001b[0m
--notify global option.
ini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m
module's ini settings at this time DrupalKernel.php:979
ini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m
module's ini settings at this time DrupalKernel.php:980
ini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m
module's ini settings at this time DrupalKernel.php:981
ini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m
module's ini settings at this time DrupalKernel.php:984
ini_set(): Headers already sent. You cannot change the session       \u001b[1;33;40m\u001b[1m[warning]\u001b[0m
module's ini settings at this time DrupalKernel.php:986
Failed to log error: Deprecated function: assert(): Calling assert() with a string argument is deprecated in Drupal\\Core\\Cache\\DatabaseBackend->doSetMultiple() (line 225 of /var/www/drupalvm/drupal/core/lib/Drupal/Core/Cache/DatabaseBackend.php).
```

**Comment by geerlingguy** [comment]
Dropping that test for now, because it won't work until a new version of Drupal 8 is tagged and released.
