### ISSUE TITLE
`git clone [REPO]` in post-provision script not working

### ISSUE THREAD

**Issue by BWPanda** [geerlingguy/drupal-vm#1876]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.2
VirtualBox 5.2.22r126460
ansible 2.7.4
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/panda/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.15rc1 (default, Nov 12 2018, 14:31:15) [GCC 7.3.0]
```

### Your OS

 - **Linux** (Linux Mint 19 Cinnamon)

### Full console output

`$ vagrant up`
https://gist.github.com/BWPanda/088fa0f58eddcd5d1f99bdd27f20d36a

### Summary

My 'websites.sh' script tries to clone a git repository into the VM, but nothing is there when I ssh into it...

The script firstly adds the 'vagrant' user to the 'www-data' group, then it changes the group of the '/var/www' dir to 'www-data' and adds write permission for the group. It then adds the key for the git repository to the SSH known_hosts file (to avoid the interactive prompt to do so), and finally clones the repository into '/var/www': `sudo -u vagrant git clone [REPO_URL]` (well, tries to).

When I run `vagrant ssh` (which takes me straight to '/var/www'), only the 'dashboard' directory is there, no repository directory (my 'html_dir.sh' script removes the '/var/www/html' dir).

I've tried debugging this, but am not really sure how to (e.g. even running `echo "test"` in the script doesn't show anything when I ssh into the VM, but I know it runs as the SETUP_COMPLETE_FILE (copied from the example script) is present in '/etc'). How do I know what the issue is and how to fix it?

**Comment by BWPanda** [comment]
I should mention that running the same `git clone ...` command after SSHing into the VM works fine...

**Comment by geerlingguy** [comment]
@BWPanda - If you run the script from within the VM, does _that_ work? E.g. call `/vagrant/scripts/websites.sh` (if it's in your vagrant shared directory—otherwise copy it somewhere in the VM, make it executable (`chmod +x`) then run it).

**Comment by BWPanda** [comment]
@geerlingguy No, it doesn't. I then worked out that the following, run from within the VM, works:

`git clone [REPO]`

While this doesn't:

`sudo -u vagrant git clone [REPO]`

That second line is what the script uses, as the script is run as the 'root' user, whereas I need it to be run by the 'vagrant' user.
That gives the following error:

> Permission denied (publickey,keyboard-interactive).
fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
and the repository exists.

**Comment by BWPanda** [comment]
I've created a new SSH key on my host machine, added its public key to the remote git repository, then updated my scripts to copy that key onto the VM. So it should have access...

Because I can clone the repo. normally in the VM, then I'm guessing the issue has to do with trying to do it as the 'vagrant' user. Any ideas on how to do that?

**Comment by BWPanda** [comment]
Fixed it. Had to name the SSH keys 'id_rsa(.pub)' (they had different names on my host) and change the owner & group to 'vagrant'. After that, cloning the git repo. as 'vagrant' user works from the script.
