### ISSUE TITLE
Does 'extra_security_enabled' turn on Unattended-Upgrades, or is there an extra step?

### ISSUE THREAD

**Issue by chumkui** [geerlingguy/drupal-vm#1884]
### Issue Type

 - Question

### Your Environment

```
Vagrant 2.1.2
Virtualbox Version 5.2.18 r124319 (Qt5.6.2)

```

### Your OS

  - **Windows** (10.0.1734)

### Summary

We use DrupalVM for all our local dev so I have been experimenting with using DrupalVM to provision a production  server (Ubuntu 18.04) machine using a production config. Turning on `extra_security_enabled` all works really well, including locking down the firewall,  root access to SQL etc etc.  This is a huge time saver, so thank you for a great contribution.

I am trying to work out exactly what is happening with the state of Unattended Upgrades for security patches.  All looks OK config wise - I have looked through the security role and checked the deployed server itself - I can see that the `unattended-upgrades` package is installed,  `/etc/apt/apt.conf.d/50unattended-upgrades` has only security patches enabled and that a `/etc/apt/apt.conf.d/10periodic` has been enabled (although I normally use `20auto-upgrades`).  However I cannot see that it is actually runs - there is nothing in the logs.

I've read through the documentation and cannot see anything further I need to do, so am I missing the obvious?!

Many thanks

Martin

**Comment by geerlingguy** [comment]
No problem—yes, if the config is there, it should be running happily in the background. You _should_ be able to see the logs in `/var/logs/unattended-upgrades/*` (see this stack exchange answer: https://unix.stackexchange.com/q/331840/16194).

I don't think any logs would be written until a full day has passed, though. You can also check on the automated job itself by looking at the following file:

```
$ cat /etc/cron.daily/apt-compat
[should contain a script to call another file]
$ cat /usr/lib/apt/apt.systemd.daily
[has the actual unattended upgrades stuff]
```

**Comment by chumkui** [comment]
Many thanks - I have been through your link and also found this which was useful [https://askubuntu.com/questions/934807/unattended-upgrades-status?rq=1](url)

It looks like the issue is that it is failing to complete due to errors, which is a bit of a surpise as it is faily minimal install wise, so I need to get to the bottom of that first.

Thanks again for a great contribution

Martin
