### ISSUE TITLE
Vagrant Up failing at mounting NTFS drives.

### ISSUE THREAD

**Issue by LewisNmma** [geerlingguy/drupal-vm#1887]
First of all thanks for all the effort into Drupal VM it's pretty awesome. I'm struggling trying to setup a co-worker's machine and am stuck. I have my local setup, but can't get this other laptop online.

### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.2
VirtualBox 5.2.22r126460
ansible 2.7.5
  config file = None
  configured module search path = ['/Users/maccoder2/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.1 (default, Nov 28 2018, 11:51:47) [Clang 10.0.0 (clang-1000.11.45.5)]
```

### Your OS
 - **macOS** (version)

### Full console output
https://gist.github.com/LewisNmma/88b1685474760bc61985b5caf3553f03

### Summary
I am unable to setup this machine with Drupal VM and our Acquia based project. On my work machine everything is running smoothly. However, on this other machine (both MacOS), I've nuked and started over twice now and still have failures at different points. Sometimes `solr` doesn't install or can't connect. Before it was the BLT alias on the host machine. I got that working, but now inside the VM blt isn't in the path and isn't in a bash profile as a function.

On my machine vagrant provisioned files to /var/www/project but on my co-workers machine /var/www/project is empty. 

Now, it looks like it's a BLT problem in the guest machine. The console output from above is inside the guest machine. I was running `vagrant provision`.

I can `vagrant ssh` into the machine but BLT isn't operable inside. The only difference between my local and my co-worker's local is I have more RAM. We both have Mojave but for some reason I've just not been able to get that one up and running.

Any help would be appreciated.

**Comment by geerlingguy** [comment]
Error:

```
TASK [Run configured post-provision shell scripts.] ****************************
changed: [discoverboat] => (item=../../../acquia/blt/scripts/drupal-vm/configure-solr.sh)
failed: [discoverboat] (item=../../../acquia/blt/scripts/drupal-vm/post-provision.php) => {"changed": true, "item": "../../../acquia/blt/scripts/drupal-vm/post-provision.php", "msg": "non-zero return code", "rc": 1, "stderr": "Shared connection to 127.0.0.1 closed.\r\n", "stderr_lines": ["Shared connection to 127.0.0.1 closed."], "stdout": "\r\nCannot find BLT alias to install.", "stdout_lines": ["", "Cannot find BLT alias to install."]}
changed: [discoverboat] => (item=../../../../box/scripts/post-provision.php)
```

It looks like that's failing on this line in the BLT project's script: https://github.com/acquia/blt/blob/10.0.x/scripts/drupal-vm/post-provision.php#L12

```
    $bashrc_file = "/home/vagrant/.bashrc";
```

If you look inside the `/home/vagrant` directory is there anything else in there? To check contents:

```
vagrant ssh # to log into the VM
ls -lah /home/vagrant
```

Maybe that file doesn't exist for some reason... also you mentioned that `/var/www/project` is empty on his machine... that could be due to NFS issues. Is he using iTerm by chance? https://github.com/geerlingguy/drupal-vm/issues/1828
