### ISSUE TITLE
Warning for Windows users

### ISSUE THREAD

**Issue by lexsoft00** [geerlingguy/drupal-vm#1889]
### Issue Type
 - Documentation Report

### Your OS
 - **Windows** (version)

### Summary

Could you please highlight a warning for Windows users( http://docs.drupalvm.com/en/latest/getting-started/installation-windows/ ) that if they run the box( after installation, the next day, i've run vagrant up without admin rights and got my vagrant box destroyed) without administrator rights the box will fail and will be destroyed.

The problem relates to these issues
* How to avoid writing host configuration to WINDOWS/system32/drivers/etc/hosts?
https://github.com/geerlingguy/drupal-vm/issues/1802

* Issue #1802, by Michel Settembrino: Make possible to avoid updating the local hosts file.
https://github.com/geerlingguy/drupal-vm/pull/1821

**Comment by geerlingguy** [comment]
So are you saying that if you:

  1. Run `vagrant up` as admin
  2. Verify the box is working fine.
  3. Run `vagrant down` to shut down the VM.
  4. Run `vagrant up` again (but forget to use admin)

Then the VM is completely destroyed? If so, that sounds like an upstream Vagrant bug, and a pretty serious one at that...

**Comment by lexsoft00** [comment]
Hi @geerlingguy,

Yes. Note that I have 2 users on my computer, 1 with admin rights and 1 without.
Run vagrant up as admin.
Run vagrant down to shut down the VM.
Run vagrant up again with no admin rights and the box will not be able to write the IP in the WINDOWS/system32/drivers/etc/hosts. The box then will fail and be destroyed. 

I've used the information into the issues above and created Vagrantfile.local with:
```
config.vm.networks.each_index do |idx|
  config.vm.networks[idx][1][:hostsupdater] = 'skip'
end
```

**Comment by geerlingguy** [comment]
Wow, I have not seen that happen—in my testing the box is not destroyed, I just have to do it again as admin. It might be because of the two separate users though. That's not something that Drupal VM has any control over, however, and it sounds like a bug with Vagrant. I would consider raising an issue in the Vagrant issue queue.
