### ISSUE TITLE
rsync__args and guest generated files

### ISSUE THREAD

**Issue by sidneygijzen** [geerlingguy/drupal-vm#189]
hello,

As I work a lot with Zen subthemes, I use a.o. Bundler, SASS and Compass to generate my CSS files on the guest VM. At some point I sync back the files to the host, for which I use the [vagrant rsync-back plugin](https://github.com/smerrill/vagrant-rsync-back). However I noticed that all files were 666 and all folders 777 after rsync'ing (back). This is caused by the last argument in ```rsync__args``` parameter: ```"--chmod=ugo=rwX" ```. Once I removed that argument all permissions are kept intact, and thus I don't have to reset all permissions after rsyncing back from guest to host.

Up til now I haven't run into any troubles (e.g. I can run ```bundle exec compass compile``` without sudo'ing). However, I do use [some extra settings](http://docs.drupalvm.com/en/latest/extras/syncing-folders/#permissions-related-errors) as mentioned in the Drupal VM docs. My synced_folder config (Vagrantfile) is as follows:
```ruby
for synced_folder in vconfig['vagrant_synced_folders'];
    config.vm.synced_folder synced_folder['local_path'], synced_folder['destination'],
      type: synced_folder['type'],
      rsync__auto: "true",
      rsync__exclude: synced_folder['excluded_paths'],
      rsync__args: ["--verbose", "--archive", "--delete", "-z"],
      id: synced_folder['id'],
      create: synced_folder.include?('create') ? synced_folder['create'] : false,
      owner: "vagrant",
      group: "www-data",
      mount_options: synced_folder.include?('mount_options') ? synced_folder['mount_options'] : ["dmode=775,fmode=664"]
  end
```
I haven't tried all possible file generating actions on the guest VM yet, but I figured I would report it to see if more users have run into this. I'm also of course curious about how other users are solving this! :)

**Comment by oxyc** [comment]
I've been using the following for a while and seems to work as well.

- I've also removed rsync compression (should be faster when it's local network)
- Set it to use `--numeric-ids` but I doubt it has any difference in performance even if I read someone mention it.
- Further I removed vagrants recursive chown (as it chowned the files folder as well).

I agree that this should either be configurable with `synced_folder['rsync_args']` or set to a saner default.

```rb
  for synced_folder in vconfig['vagrant_synced_folders'];
    config.vm.synced_folder synced_folder['local_path'], synced_folder['destination'],
      type: synced_folder['type'],
      rsync__auto: "true",
      rsync__exclude: synced_folder['excluded_paths'],
      rsync__args: [
        "--verbose", "--archive", "--delete",
        "--chmod=Du=rwx,Dgo=rx,Fu=rw,Fgo=r", # 644 for files, 755 for directories
        "--numeric-ids", # performance tuning
        "--owner", "--group",
        "--usermap=*:900", "--groupmap=*:900", # chown everything to vagrant:vagrant
      ],
      rsync__chown: false,
      rsync__verbose: true,
      id: synced_folder['id'],
      create: synced_folder.include?('create') ? synced_folder['create'] : false,
      mount_options: synced_folder.include?('mount_options') ? synced_folder['mount_options'] : []
  end
```

**Comment by sidneygijzen** [comment]
Awesome! Thank you for sharing.

**Comment by geerlingguy** [comment]
I think it would be good to get some of this info incorporated into the docs for synced folders, so added a label to that effect. Also, someone may be able to figure out a simpler way of configuring things through `config.yml`... we'll see.

**Comment by oxyc** [comment]
How about something like:

```ruby
  for synced_folder in vconfig['vagrant_synced_folders'];
    options = {
      type: synced_folder['type'],
      rsync__auto: "true",
      rsync__exclude: synced_folder['excluded_paths'],
      rsync__args: ["--verbose", "--archive", "--delete", "-z", "--chmod=ugo=rwX"],
      id: synced_folder['id'],
      create: synced_folder.include?('create') ? synced_folder['create'] : false,
      mount_options: synced_folder.include?('mount_options') ? synced_folder['mount_options'] : []
    }
    if synced_folder.include?('options_override');
      options = options.merge(synced_folder['options_override'])
    end
    config.vm.synced_folder synced_folder['local_path'], synced_folder['destination'], options
  end
```

**Comment by oxyc** [comment]
@geerlingguy what do you think about the idea to only set the synced_folders options as defaults, and let anything be overridden like in my example? If you're interested in the idea I can open up a pull request to further improve it.

**Comment by geerlingguy** [comment]
Closing for now—there are a few changes that make working with rsync easier (you can override anything from config.yml now), and also see notes in #261 .
