### ISSUE TITLE
Ansible script to install java

### ISSUE THREAD

**Issue by antra13** [geerlingguy/drupal-vm#1896]
### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

**Comment by antra13** [comment]
issue type : Support Request
OS : Linux (centos 6)

---
- hosts: localhost
  tasks:
  - name: Download Java JRE
    get_url:
      url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm
      dest: /opt/jre-8u60-linux-x64.rpm
      headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
  - name: install Java JRE rpm from a local file
    yum:
      name: /opt/jre-8u60-linux-x64.rpm
      state: present
  - name: Download Java JDK
    get_url:
      url: http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jdk-8u60-linux-x64.rpm
      dest: /opt/jdk-8u60-linux-x64.rpm
      headers: 'Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F; oraclelicense=accept-securebackup-cookie'
  - name: Install Java JDK rpm from a local file
    yum:
      name: /opt/jdk-8u60-linux-x64.rpm
      state: present
...


I'm new to Ansible...when I execute this ..I'm getting this error..

fatal: [localhost]: FAILED! => {"changed": false, "dest": "/opt/jre-8u60-linux-x64.rpm", "msg": "Request failed", "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url":
 "http://download.oracle.com/otn-pub/java/jdk/8u60-b27/jre-8u60-linux-x64.rpm"}

**Comment by geerlingguy** [comment]
Note that Drupal VM includes the `geerlingguy.java` role by default, and you can use that role to install many different flavors of Java just by changing some variables in your `config.yml` (so you don't have to try building your own set of tasks to do it).

See documentation: https://github.com/geerlingguy/ansible-role-java

And just add 'java' to the `installed_extras` list in your `config.yml` to make sure the role is run.
