### ISSUE TITLE
Installing another distribution - WxT

### ISSUE THREAD

**Issue by AlexCreamer** [geerlingguy/drupal-vm#1898]
### Issue Type

Support Request

### Your Environment

```
vagrant 2.2.3
```

### Your OS

 - **Windows** 10

### Full console output
https://gist.github.com/AlexCreamer/279aa11bb1a11ae94467688cde9e74e0

### Summary
I have the following config file: 
https://gist.github.com/AlexCreamer/5c6038ac5f29deceecb8662b15618c10
and I'm trying to install Drupal 8 WxT. But, when I try to install to get it installed by running `vagrant up`, WxT isn't installed and instead regular Drupal is installed.

**Comment by lexsoft00** [comment]
Hi @AlexCreamer,

You probably get a standard Drupal installed because of the settings:

```
# Settings for installing a Drupal site if 'drupal_install_site:' is 'true'.
drupal_install_profile: standard
```
You need to specify the profile which in your case could be 'wxt' .

**Comment by AlexCreamer** [comment]
Thanks! :)
