### ISSUE TITLE
[Solved] Centos 7 Failure talking to yum, could not resolve host, no more mirrors to try

### ISSUE THREAD

**Issue by jndevbc** [geerlingguy/drupal-vm#1899]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.3
vboxmanage: 5.2.26r128414
ansible 2.5.0
```

### Your OS

 - **macOS** 10.14.3

### Full console output

Console output:

https://gist.github.com/jndevbc/765561d6a197d15133d5272b0b75cb12#file-02_vagrant_up

Error text:

https://gist.github.com/jndevbc/765561d6a197d15133d5272b0b75cb12#file-03_errors

default.config.yml:

https://gist.github.com/jndevbc/765561d6a197d15133d5272b0b75cb12#file-01

### Summary

- Downloaded drupalvm master branch
- changed default.config.yml to use `vagrant_box: geerlingguy/centos7`
- composer install
- vagrant up
- Gets to the `TASK [geerlingguy.git : Ensure git is installed (RedHat).]` task, the first part of the error: (see link to full error text above)

```
Failure talking to yum: failure: repodata/repomd.xml from epel: [Errno 256] No more mirrors to try.\nhttps://mirror.steadfastnet.com/epel/7/x86_64/repodata/repomd.xm
```

### Additional Things Tried/Looked At

- Opened another terminal and vagrant ssh into this same box while it is going through all those mirrors 

- `ping 8.8.8.8` gets a reply
- `curl example-domain.com` does not resolve
- look at /etc/resolv.conf file

```
[vagrant@drupalvm-master-centos ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
search test
nameserver 10.0.2.3
options single-request-reopen
```

- did try installing default drupalvm (ubuntu) and it worked fine

What am I missing, is there a network setting I need to configure? I've tried this multiple times and it won't resolve.

TIA

**Comment by jndevbc** [comment]
Continuing from above...

`vagrant ssh` into the box and `php -v` and `git --version` -- they aren't installed.

`sudo yum install git`results in:

```
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
Could not get metalink https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=x86_64 error was
14: curl#6 - "Could not resolve host: mirrors.fedoraproject.org; Unknown error"
```

So then, do this:

```
sudo vi /etc/resolv.conf
```

The file is managed, so it will get overwritten ... but for now, add your own nameserver(s).

Now, you can `sudo yum install git` and install everything else you need for your server.

**Comment by jndevbc** [comment]
continuing…

- I ran into other issues, mysql wasn’t installed, etc. 

So remove/clean it out:

- removed all boxes `vagrant box list` and `vagrant box remove <boxname>`
- looked at virtualbox GUI and removed anything left there (delete all files)
- did a complete uninstall of vagrant and virtual box
- for virtualbox, used the tool that comes in the *.dmg file, it runs a script and removes a lot of hidden files/folders
- then I went and look through /Library and ~/Library and deleted a few other things

Fresh Install: 

- Fresh install of VirtualBox 6 (caveat… see below)
- Fresh install of vagrant
- Fresh install of centos7 vm from geerlingguy
- **Again:** `vagrant up` **works right up to the same spot where it** “Ensures git is instsalled” and then the **long error message of “Could not resolve host” for all the different mirrors that it tries**

Then:
- `vagrant ssh` into the box, `sudo vi /etc/resolv.conf` and added my nameservers
- `vagrant up —provision`
- And this time it went through the whole thing
- And it installed mysql and everything else that I needed

_Caveat: VirtualBox 6 seems to load my sites really really slowly. Much slower than when I had all my sites working and on 5.x previously._

**Comment by geerlingguy** [comment]
Very strange behavior indeed! So at this point is it installing everything correctly?

**Comment by jndevbc** [comment]
If I need to do a `vagrant reload --provision`, then it will still have issues finding mirrors. I tried this a week ago, and had to go and edit the /etc/resolv.conf file again.

**Comment by geerlingguy** [comment]
On a fresh install, what are the contents of your `/etc/resolv.conf`?

I don't think I've ever had to tweak mine inside VirtualBox (though I have had to mess with DNS all the time in Docker environments, go figure). In a box I just spun up I'm seeing:

```
$ cat /etc/resolv.conf
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 10.0.2.3
```

I believe that is a part of the bridge network VirtualBox creates for you. Is it possible you have some proxy, virus scanner, corporate network tool installed by IT, or otherwise something that could be intercepting traffic and/or causing DNS failures?

**Comment by jndevbc** [comment]
On the fresh install, [I commented above](https://github.com/geerlingguy/drupal-vm/issues/1899#issuecomment-464168100), it got stuck at the same spot, and when I looked at /etc/resolv.conf (after it was stuck), the file looked like this:

```
[vagrant@drupalvm-master-centos ~]$ cat /etc/resolv.conf
# Generated by NetworkManager
search test
nameserver 10.0.2.3
options single-request-reopen
```

Your default drupalvm which uses Ubuntu worked/loaded fine. But something about the Centos version… 

I also see that your resolv.conf file looks different from mine. 

Hmm, yes, very strange.

**Comment by jndevbc** [comment]
Changed DNS on my own machine from corporate's to another one. `vagrant reload --provision` now works without getting stuck.

If anyone gets "could not resolve host" and "no more mirrors to try", the first thing you can try is change your computer's DNS to something like [OpenDNS](https://www.opendns.com). ([Instructions](https://use.opendns.com))

**Comment by geerlingguy** [comment]
Glad you could get it resolved! Thanks for posting back to here, and I'll go ahead and close out the issue.

**Comment by nickva** [comment]
I think the artifactory at apache.jfrog.io had a minor issue. I verified as well deb and rpm packages could be installed. Everything seems to be back up now.
