### ISSUE TITLE
Intellij idea & PHPStorm - Setting up Xdebug

### ISSUE THREAD

**Issue by lexsoft00** [geerlingguy/drupal-vm#1900]
### Issue Type
 -  Support Request

### Your Environment
```
Vagrant 2.2.2
VirtualBox 5.2.18
```

### Your OS
 - **Windows** (version)

### Summary
Hi,
I'm trying to have Xdebug enabled with [intellij idea](https://www.jetbrains.com/idea/) but seems to fail at connection: "Waiting for incoming connection with ide key 'PHPSTORM'"

I could not find a tutorial to set up this from beginning to the end. 

Xdebug Settings
```
# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_max_nesting_level: 256
php_xdebug_remote_host: "{{ ansible_default_ipv4.gateway }}"
```
Intelij Idea:
- Added PHP Remote Debug configuration with DrupalVM server and IDE key "PHPSTORM"
- Enabled the Chrome Xdebug helper on the website

I've disabled the firewall on the config.yml but no success:
`firewall_enabled: false`

I've followed this [Tutorial](http://justinlevi.github.io/blog/2016/12/21/setting-up-twig-xdebug-phpstorm-drupal8-acquia-blt) still no success.

**Comment by lexsoft00** [comment]
Xdebug log output:
```
I: Checking remote connect back address.
I: Checking header 'HTTP_X_FORWARDED_FOR'.
I: Checking header 'REMOTE_ADDR'.
I: Remote address found, connecting to 192.168.88.1:10000.
E: Time-out connecting to client (Waited: 10000 ms). :-(
Log closed at 2019-02-19 11:12:39
```
I've changed to port 10000 to exclude any conflicts with php-fpm. 
I can see on windows that I'm listening:
`TCP    0.0.0.0:10000          0.0.0.0:0              LISTENING       9508`

I've found a better tutorial for this: https://danemacmillan.com/how-to-configure-xdebug-in-phpstorm-through-vagrant/

Still don't understand why is not working with drupal-vm, I've got it working on a custom vagrant box.

**Comment by lexsoft00** [comment]
Got it working!
The following settings for Xdebug:
```
[XDebug]
zend_extension="/usr/lib/php/7.2/modules/xdebug-2.6.0.so"

xdebug.default_enable=1

xdebug.remote_enable=1
xdebug.remote_connect_back=0
xdebug.remote_host=10.0.2.2
xdebug.remote_handler: dbgp
xdebug.remote_port=10000
xdebug.remote_log=/tmp/xdebug.log
xdebug.remote_autostart=0

xdebug.idekey="PHPSTORM"

xdebug.max_nesting_level=256
```

**Comment by geerlingguy** [comment]
Glad you could figure this out! I'm going to close but thank you so much for posting the solution for the benefit of those Googling this problem in the future.
