### ISSUE TITLE
getting 403 forbidden after cloning my own drupal on windows 10

### ISSUE THREAD

**Issue by pratt1305** [geerlingguy/drupal-vm#1905]
### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

**Comment by geerlingguy** [comment]
There seems to be no data about what is going wrong, error messages, configuration changes, etc., so closing this ticket.
