### ISSUE TITLE
TASK [geerlingguy.drupal : Install Drupal with drush.] fails

### ISSUE THREAD

**Issue by jonathan-selormey** [geerlingguy/drupal-vm#1906]
I seem to be failing at this task on my VM. Thoughts?

Running this on Ubuntu 18.04

TASK [geerlingguy.drupal : Install Drupal with drush.] ***********************************************************************************************************************************************************************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": ["/var/www/drupal/vendor/bin/drush", "site-install", "standard", "-y", "--root=/var/www/drupal/web", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@127.0.0.1/drupal"], "delta": "0:00:00.216574", "end": "2019-03-01 16:22:40.770426", "msg": "non-zero return code", "rc": 1, "start": "2019-03-01 16:22:40.553852", "stderr": "\nIn SiteInstallCommands.php line 354:\n                                                                               \n  Failed to create database: ERROR 1045 (28000): Access denied for user 'drup  \n  al'@'localhost' (using password: YES)                                        \n                                                                               \n\nsite:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--xh-link XH-LINK] [--druplicon] [--] <command> [<profile>]...", "stderr_lines": ["", "In SiteInstallCommands.php line 354:", "                                                                               ", "  Failed to create database: ERROR 1045 (28000): Access denied for user 'drup  ", "  al'@'localhost' (using password: YES)                                        ", "                                                                               ", "", "site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--xh-link XH-LINK] [--druplicon] [--] <command> [<profile>]..."], "stdout": "\n // You are about to CREATE the 'drupal' database. Do you want to continue?:    \n // yes.                                                                        ", "stdout_lines": ["", " // You are about to CREATE the 'drupal' database. Do you want to continue?:    ", " // yes.                                                                        "]}
	to retry, use: --limit @/root/.ansible/drupal.retry

**Comment by geerlingguy** [comment]
@jonathan-selormey - It looks like the problem is:

```
Failed to create database: ERROR 1045 (28000): Access denied for user 'drup \n al'@'localhost'
```

It would seem that in your `config.yml` a newline and some extra spaces somehow slipped into the drupal database username? Can you check your config.yml and see?
