### ISSUE TITLE
When using a composer package, PHP Fatal error: Allowed memory exhausted

### ISSUE THREAD

**Issue by bisonbleu** [geerlingguy/drupal-vm#1907]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.0.2
VirtualBox 5.2.16r123759
ansible 2.4.3.0
  config file = None
  configured module search path = [u'/Users/username/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Oct 23 2015, 19:19:21) [GCC 4.2.1 Compatible Apple LLVM 7.0.0 (clang-700.0.59.5)]
```

### Your OS

 - **macOS** (version)

### Full console output

https://gist.github.com/bisonbleu/f61ee4eadeb60d770594e24e1efc08f4

### Summary

I'm following the instructions here (http://docs.drupalvm.com/en/latest/deployment/composer-package/) and trying to build the codebase using a composer package (acquia_lightning). I copy and pasted the suggested settings into config.yml. But when I run `vagrant up` it takes a while and then I run into `PHP Fatal error: Allowed memory size of 1610612736 bytes exhausted`.

Any suggestions?

p.s. I use DrupalVM most of the time, the work you're doing is simply awesome.

**Comment by bisonbleu** [comment]
**Update**: I boosted vagrant_memory to 4096 and that appears to fix the memory issue. Now I'm getting `cp: cannot create regular file`.

```
TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] ***
fatal: [drupalvm2]: FAILED! => {"changed": true, "cmd": ["cp", "-r", "/tmp/composer-project/.", "/var/www/drupalvm/drupal/"], "delta": "0:00:29.181035", "end": "2019-03-05 17:34:02.955245", "msg": "non-zero return code", "rc": 1, "start": "2019-03-05 17:33:33.774210", "stderr": "cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-27f6156aec834696b81d2cecb1081d033ec36f22.pack': Permission denied\ncp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-27f6156aec834696b81d2cecb1081d033ec36f22.idx': Permission denied", "stderr_lines": ["cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-27f6156aec834696b81d2cecb1081d033ec36f22.pack': Permission denied", "cp: cannot create regular file '/var/www/drupalvm/drupal/./vendor/drupal/coder/.git/objects/pack/pack-27f6156aec834696b81d2cecb1081d033ec36f22.idx': Permission denied"], "stdout": "", "stdout_lines": []}
```

**Comment by bisonbleu** [comment]
**Update-2**: Went for a walk. Upon returning I thought I'd try `vagrant reload` just for kicks and... _lo and behold_ the Installation screen appeared, allowing me to choose the **Lightning** profile and manually complete the installation process.

Lucky or not, that's good news - hey I've now got a working environment and can proceed to do what I wanted to do.

But it's definitely convoluted and counter-intuitive. Something more proper would be nice :)

**Comment by bisonbleu** [comment]
Back on d.o @phenaproxima suggested bumping memory_limit to 2 GB in php.ini. So I set `php_memory_limit` to 2048MB and I made it through the installation process. With a few more tweaks in config.yml Acquia Lightning is properly installed.

The Drupal installation now runs on 2048MB of memory, which is a bit excessive, is there a trick to set it back to 192MB or 512MB post-installation ?

**Comment by geerlingguy** [comment]
Holy cow... what kind of Drupal site is this? I have not had to increase my memory_limit beyond 512MB for any Drupal 8 site I've worked on (most of the time I keep it at 128 or 256 MB max though).

Granted, I haven't installed a Lightning-based site in a year or two... but I can't believe it would need that much RAM to do a clean install?

Closing this as it seems it was just a memory limit issue, but yikes! If this were Magento or something, I would understand :D

**Comment by bisonbleu** [comment]
Hey Jeff, you did the right thing in closing this ticket which I meant to update.

In the end, the issue was me confusing the VM's php memory allocation with my Macbook's global php. When running `composer` commands outside of `vagrant ssh`, it is of course my Macbook's php that is used, and it was set to 128M - not enough for Composer I suppose. I'm now using `memory_limit = 256M`.

Although I have not tested this new memory setting with a Lightning installation, I'm pretty confident that that was the source of my memory problems - i.e. not the VM.

Cheers!

**Comment by geerlingguy** [comment]
@bisonbleu ah, that would definitely do it. For composer operations, it can sometimes use even more RAM (e.g. when first building a Lightning project via Composer, I've seen Composer use up to 1.2 or 1.3 GB of RAM sometimes!).

**Comment by Tom-Stermitz** [comment]
On my Mac, vagrant up never ran into memory_limit problems until now. I increased my local mac php memory_limit all the way up to -1, and it still failed.  I updated the drupal vm config.yml php_memory_limit to 2G, and now vagrant up succeeded.

I'm not sure what changed in my system or in drupal vm, or in composer to require such large settings.

**Comment by geerlingguy** [comment]
@Tom-Stermitz - Note that something upstream in Drupal seems to have caused this issue. I ran into the same issue in a lot of other environments (not just Drupal VM) where now installing Drupal from Composer requires more than 1.5 GB of RAM (Composer's default). Related Twitter thread: https://twitter.com/geerlingguy/status/1221145294567591938 — also discussed on Reddit: https://www.reddit.com/r/drupal/comments/euv38x/new_composer_memory_errors/

**Comment by sbreese** [comment]
Thank you @Tom-Stermitz! Adding the following to config/config.yml resolved the memory error:
`php_memory_limit: 2G`
