### ISSUE TITLE
newbie first: i specify 7.2 but dashboard shows 7.1

### ISSUE THREAD

**Issue by neoginn** [geerlingguy/drupal-vm#1908]
In a completely fresh install win10, I specify php 7.2, but the dashboard says 7.1. Then when I SSH into the vm it says 7.2. What am i missing here?

**Comment by geerlingguy** [comment]
Not quite sure; if you install Drupal and go into the Drupal site's site report section, what version of PHP does it indicate there? Is there a chance you're running two copies of Drupal VM? Any other customizations in your `config.yml` file besides `php_version: "7.2"`?
