### ISSUE TITLE
Drupal VM mod_alias alias

### ISSUE THREAD

**Issue by monymirza** [geerlingguy/drupal-vm#1913]
How could it possible to setup Alias in Drupal VM? for example
https://httpd.apache.org/docs/2.4/mod/mod_alias.html#alias

**Comment by geerlingguy** [comment]
Just add it to the `apache_mods_enabled` list in your override config.yml file; see https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L153-L159
