### ISSUE TITLE
Xdebug problem with VS Code on Windows 10

### ISSUE THREAD

**Issue by tomo-dev-2018** [geerlingguy/drupal-vm#1914]
Issue Type

 - Bug Report / Support Request

Your Environment

```
Vagrant 2.2.4 VirtualBox 6.0.4r128413
```

Your OS

 - Windows 10 Pro Version 1803 (OS Build 17134.648)

Summary

I have provisioned the VM with Xdebug to work with VS Code as described in the docs and the installation works ok but when I tried using Xdebug with VS Code by adding ?XDEBUG_SESSION_START to the url I first got the error about the .env file missing (which I created from .env.example without changing its contents) and then I got the following error:

```
Exception has occurred.
Symfony\Component\Process\Exception\ProcessFailedException: The command "git log -1 --pretty=format:'%H - %s (%ci)' --abbrev-commit" failed.

Exit Code: 128(Invalid exit argument)

Working directory: /var/www/drupalvm/drupal/web

================
fatal: Not a git repository (or any parent up to mount point /var/www/drupalvm)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

I have configured my lauch.json file in VS Code in the following way:

```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Listen for XDebug",
            "type": "php",
            "request": "launch",
            "port": 9000,
            "pathMappings": {
                "/var/www/drupalvm": "D:/test_bazy_sql/drupal/drupal_sites/drupal-vm/"
              },
        },
        {
            "name": "Launch currently open script",
            "type": "php",
            "request": "launch",
            "program": "${file}",
            "cwd": "${fileDirname}",
            "port": 9000
        }
    ]
}
```
Is there a way to work around this?

**Comment by geerlingguy** [comment]
It looks like the error is not related to Xdebug in any way, but instead:

```
Symfony\Component\Process\Exception\ProcessFailedException: The command "git log -1 --pretty=format:'%H - %s (%ci)' --abbrev-commit" failed.
```

It looks like it's running a `git` command inside the working directory (`/var/www/drupalvm/drupal/web`), and then it realizes that directory is not a git repository (nor is `/var/www/drupalvm/drupal` or any other directory), and then it fails.

I do not use VSCode and also am not sure how you have your site configured (not sure what that `ProcessFailedException` is coming from? Maybe a VSCode plugin for Git?), but I would start by investigating that particular error message.

This doesn't seem to have anything to do with Drupal VM or its configuration, however. I'd suggest asking in VSCode forums/help areas, or on Stack Exchange or Drupal Answers.
