### ISSUE TITLE
vagrant_memory and php_memory_limit overrides not applying

### ISSUE THREAD

**Issue by yorkshire-pudding** [geerlingguy/drupal-vm#1915]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.4
"VirtualBox `vboxmanage --version`"
'ansible' is not recognizes as an internal or external command, operable program or batch file.
```

### Your OS
- **Windows** (Version	10.0.17134 Build 17134)

### Full console output

N/A

### Summary

Attempted to change the vagrant_memory and php_memory_limit in both config.yml and local.config.yml.
I haven't worked a reliable way to check the vagrant memory, but the php_memory is not changing
I have done `vagrant reload` and it remains at 192MB

**Comment by geerlingguy** [comment]
You have to use `vagrant reload --provision` to both restart Vagrant (so the vagrant VM memory is increased) _and_ re-run the Ansible provisioner (so the php memory limit is increased).
