### ISSUE TITLE
Selenium/Behat Chrome browser not opening when running tests

### ISSUE THREAD

**Issue by fpoirier1** [geerlingguy/drupal-vm#1916]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.2
VirtualBox 5.2.22r126460
ansible 2.7.9
  config file = None
  configured module search path = [u'/Users/francispoirier/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Jan 24 2019, 22:33:28) [GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]
```

### Your OS
 - **macOS** (MOJAVE)

#### DrupalVM config
https://gist.github.com/fpoirier1/cd7f08e1aa8691ca32ef5e99d4936873#file-drupalvm-config-yml
#### Vagrant provision
https://gist.github.com/fpoirier1/cd7f08e1aa8691ca32ef5e99d4936873#file-vagrant-provision-log
#### Behat config
https://gist.github.com/fpoirier1/cd7f08e1aa8691ca32ef5e99d4936873#file-behat-yml

### Summary

Hello,

I have a behat test that runs fine except that I am not able to see the action executed in chomre. I would expect to have a tab opening in the browser and see the task simulation running, right ?

I know there is quite a few thread on this topic but I still couldn't resolve my issue.

Thanks in advance !

**Comment by geerlingguy** [comment]
@fpoirier1 - If you run the Behat test inside the VM, then it is using an instance of Google Chrome that is running inside the VM—it won't use Google Chrome running on your host machine. Unfortunately, this means there's no way to run Behat inside the VM and control the browser on your host (though there might be a way to hack that together); but you can do things like add a behat screenshot plugin to get screenshots on failed tests.
