### ISSUE TITLE
having trouble with `vagrant provision` on MacOSX

### ISSUE THREAD

**Issue by TristanTheKnightAway** [geerlingguy/drupal-vm#1917]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.4
VirtualBox 5.2.20r125813
-bash: ansible: command not found
```

### Your OS

 - **macOS** (10.14)

### Full console output

https://gist.github.com/TristanTheKnightAway/09249f5b6a5cf9a8d8dcf5602ce58db4

### Summary

 I'm trying to install a local dev env for the migrations training at DrupalCon Seattle. Seems like I'm almost there... but here's where I tripped up.

💦  tpeery d8mig (master) ➢ vagrant provision
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.test
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.test
==> drupalvm: Running provisioner: drupalvm (ansible_local)...
`playbook` does not exist on the guest: /vagrant/provisioning/playbook.yml

**Comment by TristanTheKnightAway** [comment]
I installed Ansible after I posted this, then ran `vagrant halt` and `vagrant up --provision` as this seemed to work for some other similar posts, but I still have this issue:

`
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
NFS is reporting that your exports file is invalid. Vagrant does
this check before making any changes to the file. Please correct
the issues below and execute "vagrant reload":

exports:6: /Users/tpeery/drupalroot/migrations/drupal-vm conflicts with existing export /Users
`

I am swimming in unfamiliar waters...

**Comment by geerlingguy** [comment]
@TristanTheKnightAway - If you've used many other kinds of local environments before, that's where those conflicts could be coming from. Run `sudo nano /etc/exports`. Then go to any line where there is an export with `drupal-vm` in it, and delete that line. Then press `Ctrl-O` to save the file and `Ctrl-X` to exit nano. Then try `vagrant up --provision` again.

**Comment by TristanTheKnightAway** [comment]
Thanks for the quick response. I performed your recommendation, here's the new error...

https://gist.github.com/TristanTheKnightAway/c677f773f9a72e638b2f23a2ae02bf9f

Just the error for quick ref is below. I'll also mention that after I received this error the first time I ran `vagrant destroy` then `vagrant up` and ended up in the same place. I have verified the precision of my error I guess. Now to work on target accuracy.... =]

`==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
The nfsd service does not appear to be running.
Starting the nfsd service
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.88.1:/Users/tpeery/drupalroot/migrations/drupal-vm/d8mig /var/www/drupalvm

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.88.1:/Users/tpeery/drupalroot/migrations/drupal-vm/d8mig

💦  tpeery drupal-vm (master) ➢ 
`

**Comment by geerlingguy** [comment]
It seems like maybe you don't have an admin account? Or maybe are you using iTerm2?

**Comment by TristanTheKnightAway** [comment]
Ah thanks for sleuthing, neither of those is true unfortunately. I'm running Terminal v2.9 and I have admin rights - although who knows what goofiness my university IT department put in between my admin rights and the root user. I also have another VM instance running on my machine for... Docksal I believe? Docker? Not entirely sure but it looks like it won't be necessary for me to have the Drupal-VM installed for this upcoming training session, so I'll just spin up a composer instance the old-fashioned way. I appreciate you being so responsive, please consider this issue closed.

**Comment by tommym9** [comment]
I'm seeing this same issue, I've recently installed ddev for a bit of testing, but I'm not sure if that has any bearing.

What I did clock is that as Tristan saw I'm getting a fail on NFS mount and I can see an IP mismatch in the command. In my `config.yml` I've set the IP to `192.168.88.88` but the IP used by the command run by the mount is `192.168.88.1`

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.88.1:/<local-path> /var/www/drupalvm

Stdout from the command:



Stderr from the command:

mount.nfs: Connection timed out
```

This could be a red herring of course, but thought I would post just in case it helps anyone along.

I'm going to try and re-provision now and see what happens.

Cheers

Tom

**Comment by tommym9** [comment]
Do you know what this was a red herring. Destroyed by box and updated Vagrant and VirtualBox and this is now working

**Comment by lorenswendsen** [comment]
I just got a new iMac (running Catalina) at work and was having the same problems mentioned above. For me the solution(s) was to go into system preferences --> Security & Privacy --> Privacy tab and give 'sh' and 'smbd' Full Disk Access and to give the Terminal app more permissions in the Developer Tools category. Just check that whole section of system preferences. I think the problem all comes down to these newish beefed up security measures that come with Catalina etc.

**Comment by shirgoldbird** [comment]
I had this issue as well with Catalina and none of the solutions here worked for me. I had to move my repo using Drupal VM out of my Documents folder and into a new folder I created in my home directory. Seems like more issues with the Catalina security measures.

**Comment by davision** [comment]
Great tip! Moving drupal-vm out of /Documents folder resolved all the issues!
