### ISSUE TITLE
Choose new soundtrack for minor release version names

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#1919]
I have run out of songs from the original Tron soundtrack—with the exception of 'End Titles'. But I don't want to use 'End Titles' because that sounds like a way to scare a bunch of people into thinking Drupal VM is finished, which it is _not_!

So... considering making it the [Tron: Legacy soundtrack](https://en.wikipedia.org/wiki/Tron:_Legacy_(soundtrack)).

**Comment by geerlingguy** [comment]
5.0.0 shall be "Flynn Lives".

**Comment by danepowell** [comment]
You are amazing, sir.
