### ISSUE TITLE
Latest DrupaVM 5.0 and Basebox 2.0 - MariaDB packages won't install anymore

### ISSUE THREAD

**Issue by yobottehg** [geerlingguy/drupal-vm#1922]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.4
VirtualBox 6.0.4r128413
ansible 2.7.9
DrupalVM 5.0
```

### Your OS
 - **macOS** (10.14.4)

### Full console output

```
: FAILED! => {"cache_update_time": 1555413689, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'mariadb-client' 'mariadb-server'' failed: E: Unable to correct problems, you have held broken packages.\n", "rc": 100, "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stderr_lines": ["E: Unable to correct problems, you have held broken packages."], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n mariadb-server : Depends: mariadb-server-10.1 (>= 1:10.1.38-0ubuntu0.18.04.1) but it is not going to be installed\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " mariadb-server : Depends: mariadb-server-10.1 (>= 1:10.1.38-0ubuntu0.18.04.1) but it is not going to be installed"]}
```

### Summary

We use MariaDB instead of mysql and the configs [here](http://docs.drupalvm.com/en/latest/configurations/databases-mariadb/) don't work anymore after updating from DrupalVM 4.9 to 5.0

We have the following in our local configs:
```
# Use mariaDB instead of mysql
mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb
```

I think this belongs to the update from 16.04 to 18.04 and the dupalvm basebox 2.0. Any idea how to archive the same with the latest of all tools?

**Comment by geerlingguy** [comment]
Looks like the main issue is:

```
mariadb-server : Depends: mariadb-server-10.1 (>= 1:10.1.38-0ubuntu0.18.04.1) but it is not going to be installed
```

Strange, though, because the `mariadb-server` package _should_ install correctly :-/

I haven't personally switched an Ubuntu machine to mariadb from the MySQL packages though.

**Comment by geerlingguy** [comment]
All I can find is this: https://mariadb.com/kb/en/library/unable-to-install-mariadb-101-on-ubuntu-1804-after-apt-remove-purge-mysql/

But the actual answer on that post is completely unrelated to the question :P

**Comment by geerlingguy** [comment]
Ah one other thing that might be the case—if mysql was previously installed, you would have to purge it before switching to mariadb. I believe the base box already installs mysql by default (since that's the default package).

```
sudo apt-get remove mariadb-server mariadb-client mysql-server mysql-client
```

Once you've done that try `vagrant provision` again.

You might want to switch to the `geerlingguy/ubuntu1804` base box instead, if this fixes your problem, because that's better if you're switching many defaults from the main base box.

**Comment by yobottehg** [comment]
Just as a feedback:
`sudo apt-get remove mariadb-server mariadb-client mysql-server mysql-client` and `vagrant provision` works.

also setting `vagrant_box: geerlingguy/ubuntu1804` works. 

Sad that this is not working with the `vagrant_box: geerlingguy/drupal-vm` as MariaDB is the only overwrite and it's twice as fast.

**Comment by geerlingguy** [comment]
Twice as fast? I have not encountered that in any of my D8 sites, most are a wash in terms of db access across MySQL and MariaDB, but maybe MySQL's defaults are poorly configured for your particular use case.

**Comment by yobottehg** [comment]
> Twice as fast
Was meant in terms of booting time for drupalvm base box instead of ubuntu 18.04

**Comment by jatorresdev** [comment]
This worked for me https://github.com/geerlingguy/drupal-vm/issues/1922#issuecomment-484596227 with vagrant_box: geerlingguy/drupal-vm.
