### ISSUE TITLE
bash: line 5: setup: command not found

### ISSUE THREAD

**Issue by Tominator89** [geerlingguy/drupal-vm#1924]
### Issue Type

 - Bug Report / Support Request
 

### Your Environment

Vagrant version 2.2.4 
Virtualbox 6.0

### Your OS

 - **Windows** (10)

### Full console output

Normal output:
https://gist.github.com/Tominator89/5b4ff953391b7d159e9d158e47c89466

Debug output:
https://gist.github.com/Tominator89/ef64b7b4ed22fb225a4352bb5ba3de95

### Relevant modifications to config.yml

**Settings for nfs**

vagrant_synced_folders:
  - local_path: c:\vagrant\d8
    destination: /var/www/drupalvm
    type: nfs
    mount_options: ["rw","vers=3","udp","nolock"]
    create: true

**But it also happens when i use vboxfs through the settings**

vagrant_synced_folder_default_type: ""

vagrant_synced_folders:
  - local_path: c:\vagrant\d8
    destination: /var/www/drupalvm
    type: 
   create: true

### Summary

I setup a drupalvm with winnfsd successfully. I have checked the mount inside the vm and confirmed "vagrant ssh drupalvm" is working. The files landing corretly inside my sync folder and drupal is running. 

When i do a vagrant reload directly after the initial provisioning i get the output above 
bash: line 5: setup: command not found
This is seems to be the step where vagrant tries to start the vagrant-winnfsd process and mount the folder but i aborts so i can confirm that the folders are not mounted inside the vm.

I also tried manually rebooting the following option, which does not change anything.
 - vagrant halt
 - vagrant up --provision

What am i doing wrong?

**Comment by phizev** [comment]
I've run into what appears to be a related error on a Ubuntu 16.04 machine (using an updated version of Vagrant):
```

==> box: Machine booted and ready!
[box] GuestAdditions seems to be installed (6.0.6) correctly, but not running.
bash: line 5: setup: command not found

...

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 5: setup: command not found

```
A coworker has picked up the same on a Mac. My Windows 10 environment has not given me this error as of yet.

**Comment by agoradesign** [comment]
I'm having exactly the same problem on Windows 10, using nfs shared folder and geerlingguy/drupal-vm box. I've updated yesterday to Virtualbox 6.0.6 (from 5.2.x), also using Drupal VM 5.0.0 for the first time. The initial start works, but the second time it fails. The only thing that helps is destroying the VM and re-create it

**Comment by agoradesign** [comment]
it seems to be related to VirtualBox version. I've downgraded to 6.0.4 and it seems to work at first glance

**Comment by Tominator89** [comment]
> it seems to be related to VirtualBox version. I've downgraded to 6.0.4 and it seems to work at first glance

Did the downgrade and it works. Nothing else has changed. Not sure if it was the reinstallation of vbox or the downgrade to 6.0.4

Thanks a lot!!!

**Comment by phizev** [comment]
To follow up, on my Ubuntu 16.04 host, downgrading to VirtualBox 6.0.4 seems to have resolved this issue. I will follow up when my coworker has had a chance to test this on his Mac, though I think it will likely be the same story there.

**Comment by phizev** [comment]
> I will follow up when my coworker has had a chance to test this on his Mac, though I think it will likely be the same story there.

I believe his was also resolved by downgrading to VirtualBox 6.0.4

**Comment by cleverhoods** [comment]
I got this error while trying to enable SOLR to an already provisioned machine (VirtualBox 6.0.8) on Mac (Mojave).
Downgrading to 6.0.4 solved the issue.

**Comment by danepowell** [comment]
Upstream issue: https://github.com/dotless-de/vagrant-vbguest/issues/278

**Comment by phizev** [comment]
For anyone whom ends up here from searching/googling the issue, see https://github.com/geerlingguy/drupal-vm/issues/1927

**Comment by gupta-ashutosh5** [comment]
hi @geerlingguy I also faced this issue on Mac OS Mojave with VB version 6.0.12. After downgrading to 6.0.4, it worked fine... So should we not upgrade VB to 6.0.12

**Comment by vivmagarwal** [comment]
**Update**: The better option is to upgrade VirtualBox to VirtualBox-6.0.18-136238-OSX than downgrading it.

https://download.virtualbox.org/virtualbox/6.0.18/
