### ISSUE TITLE
DrupalVM base image: Use SATA controller instead of IDE

### ISSUE THREAD

**Issue by phizev** [geerlingguy/drupal-vm#1925]
### Issue Type

 - Feature Idea

### Your Environment

```
N/A
```

### Your OS

N/A

### Full console output

N/A

### Summary

When using VirtualBox, the virtual machines are using IDE storage controllers, would it be possible to have this switched to SATA?

This may improve performance and/or reduce host system load, as per [VirtualBox documentation](https://www.virtualbox.org/manual/ch05.html#harddiskcontrollers):
> Like a real SATA controller, Oracle VM VirtualBox's virtual SATA controller operates faster and also consumes fewer CPU resources than the virtual IDE controller.

The more technical/gritty details of the differences can be found elsewhere in the virtualBox documentation. I think the biggest difference would be seen in database operations, and disabling the use of the host I/O cache without a performance hit.

I wasn't sure if this was the correct place to submit this, it might have been better logged against one of the images directly.

**Comment by geerlingguy** [comment]
Is this something that can be switched via the `Vagrantfile`, or does it have to be an image build-time change?

**Comment by phizev** [comment]
I think it could be switched via the vagrant file with https://www.virtualbox.org/manual/ch08.html#vboxmanage-storagectl to attach a SATA controller, then https://www.virtualbox.org/manual/ch08.html#vboxmanage-storageattach to detach the drive, and attach it to the SATA controller.

I have altered the base image locally, but I still needed to alter the controller on the cloned box after provisioning.

So while it may be possible to switch it via the vagrant file, I'm not sure if it's the correct place to switch it?

**Comment by phizev** [comment]
After some experimentation, I've only managed to get as far as attaching a SATA controller, and detaching the IDE controller. For the attaching the disk to the SATA controller, I'm at a bit of a loss as to how to get the information needed in a programmatic manner. It appears that I'd need to try to parse that information from the output of one of the Virtualbox commands, but I'm not comfortable with that at all. I feel I _have_ to be missing something.

Additionally, it seems I'd have to be relying on the name of the IDE controller remaining "IDE Controller" in order to avoid having to parse further info, doing it from the Vagrant file is starting to seem prone to error.

I'm far from a Vagrant expert, so I hope that I'm missing something in regards to a more robust manner of making such a change.
