### ISSUE TITLE
VirtualBox 6.0.6 and 6.0.8 fail on subsequent boots with 'setup: command not found'

### ISSUE THREAD

**Issue by meestyle** [geerlingguy/drupal-vm#1927]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.4
VirtualBox 6.0.6r130049
ansible 2.7.10
  config file = None
```

### Your OS

 - **macOSMojave (10.14.4)

### Summary

I cloned the [repo](https://github.com/geerlingguy/drupal-vm) and did `vagrant up`. After first time `vagrant up` everything was fine and Drupal was installed correctly. 

I made two instances (I cloned two times the repo, made two different directories and for the second instance I changed in `config.yml` the `vagrant_ip` to `vagrant_ip: 192.168.88.89`.

After `vagrant halt` and `vagrant up` again I get this error:

```
==> drupalvm: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.

The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

 setup

Stdout from the command:



Stderr from the command:

bash: line 5: setup: command not found
```

I am not able to get my environment working again? What do I have to do?

**Comment by meestyle** [comment]
As suggest at issue [#1924](https://github.com/geerlingguy/drupal-vm/issues/1924), I downgraded Virtualbox from `6.0.6` to `6.0.4 `. After downgrade everything works as expected.

**Comment by ayalon** [comment]
See https://github.com/geerlingguy/drupal-vm/issues/1926

**Comment by danepowell** [comment]
Upstream issue: https://github.com/dotless-de/vagrant-vbguest/issues/278

**Comment by geerlingguy** [comment]
And upstream-upstream issue: https://www.virtualbox.org/ticket/18598

**Comment by danepowell** [comment]
Looks like this may be fixed imminently by vbguest: https://github.com/dotless-de/vagrant-vbguest/pull/334

> I'm going to test this with VirtualBox 5.2 on the weekend. If it also works there, I'm going to merge and release it right away.

**Comment by phizev** [comment]
Per @danepowell 
> Looks like this may be fixed imminently by vbguest: [dotless-de/vagrant-vbguest#334](https://github.com/dotless-de/vagrant-vbguest/pull/334)
> 
> > I'm going to test this with VirtualBox 5.2 on the weekend. If it also works there, I'm going to merge and release it right away.

After updating VirtualBox to 6.0.8, I updated my vagrant plugins to get the latest vagrant-vbguest release which was released in the last 2 days:
```
$ vagrant plugin update
Updating installed plugins...
Fetching: vagrant-vbguest-0.18.0.gem (100%)
Successfully uninstalled vagrant-vbguest-0.17.2
Updated 'vagrant-vbguest' to version '0.18.0'!
```
So far, this has worked for 2 boxen on the same machine, previously both of these failed on VirtualBox 6.0.6, and 6.0.8.
```
Box 1
$ vagrant destroy
$ vagrant up
$ vagrant halt
$ vagrant up
$ vagrant ssh
// All seems good so far.

Version details:
Ubuntu 16.04 (HWE kernel)
Ansible 2.8.0
Vagrant 2.2.4
VirtualBox 6.0.8
Drupal VM 4.9.2
geerlingguy/ubuntu1804 1.0.7
```

```
Box 2
$ vagrant destroy
$ vagrant up
$ vagrant halt
$ vagrant up
$ vagrant ssh
// All seems good so far.

Version details:
Ubuntu 16.04 (HWE kernel)
Ansible 2.8.0
Vagrant 2.2.4
VirtualBox 6.0.8
Drupal VM 5.0.0
geerlingguy/drupal-vm 2.0.0
```
I haven't done any testing on any other platforms at present.

**Comment by phizev** [comment]
Box 1 on Windows 10 with Virtualbox 6.0.8, and the updated vagrant-vbguest seems good to go too.
```
Version details:
Windows 10 1809
Vagrant 2.2.4
vagrant-vbguest-0.18.0
VirtualBox 6.0.8
Drupal VM 4.9.2
geerlingguy/ubuntu1804 1.0.7
```

**Comment by geerlingguy** [comment]
Good to know! Sounds like it's time for me to release a new VirtualBox 6.0.8 base box set for all my VMs.

**Comment by phizev** [comment]
With the boxes above, on Windows 10, and Ubuntu 18.04, all is working well with Virtual Box 6.0.8.

**Comment by geerlingguy** [comment]
Wonderful! I've released new boxes for all my Vagrant boxes now, so I'm going to go ahead and close out this issue.
