### ISSUE TITLE
Getting error "No package matching 'php7.1' is available"

### ISSUE THREAD

**Issue by himan5050** [geerlingguy/drupal-vm#1928]
### Issue Type
 - Bug Report / Support Request

### Your Environment

Vagrant 2.2.0
VirtualBox 5.2.28r130011
ansible 2.7.10
  config file = None
  configured module search path = [u'/Users/himanshusharma/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:17:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```

```

### Your OS
 - **macOS Mojave** (10.14.4)

Not sure why I am getting error "No package matching 'php7.1' is available", while running command "vagrant up --provision", while it was working fine earlier.

I  removed and re download vagrant box, and start getting error.

### Summary

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: '{{ php_packages }}'` 
and remove the loop. This feature will be removed in version 2.11. Deprecation 
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
failed: [unicefplatform] (item=[u'php7.1', u'php7.1-apcu', u'php7.1-cli', u'php7.1-common', u'php7.1-curl', u'php7.1-dev', u'php7.1-fpm', u'php7.1-gd', u'php7.1-imap', u'php7.1-json', u'php7.1-mbstring', u'php7.1-mcrypt', u'php7.1-opcache', u'php7.1-sqlite3', u'php7.1-xml', u'php7.1-yaml', u'php7.1-bz2', u'php7.1-imagick', u'php7.1-yaml', u'imagemagick']) => {"changed": false, "item": ["php7.1", "php7.1-apcu", "php7.1-cli", "php7.1-common", "php7.1-curl", "php7.1-dev", "php7.1-fpm", "php7.1-gd", "php7.1-imap", "php7.1-json", "php7.1-mbstring", "php7.1-mcrypt", "php7.1-opcache", "php7.1-sqlite3", "php7.1-xml", "php7.1-yaml", "php7.1-bz2", "php7.1-imagick", "php7.1-yaml", "imagemagick"], "msg": "No package matching 'php7.1' is available"}
	to retry, use: --limit @/Users/himanshusharma/Sites/unicef/unicef-drupal-base/vendor/geerlingguy/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
unicefplatform             : ok=73   changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by geerlingguy** [comment]
What version of base box are you using? Also, that deprecation warning was fixed a few versions of Drupal VM ago, maybe it's just an old Drupal VM instance? Drupal VM is now at 5.0.0, in case you are able to upgrade; the latest 4.x version also fixed that warning.

**Comment by Drew-Kimberly** [comment]
Started observing this error this weekend in our CI builds. Looks like an issue with the PHP Ansible role, so opened up https://github.com/geerlingguy/ansible-role-php/issues/264.

**Comment by geerlingguy** [comment]
@Drew-Kimberly and @himan5050 - Can you please give more steps to reproduce? I am not seeing this issue on any of my builds (with 7.2 or 7.1).
