### ISSUE TITLE
wrun vagrant up not found on Windows WSL 

### ISSUE THREAD

**Issue by mikebernal** [geerlingguy/drupal-vm#1929]
Setting up the environment using Windows WSL Problem
Support Request
DrupalVM 3, Windows WSL, Oracle VirtualBox 6
Windows 10 Student 64bit

Full console output

wrun vagrant up
Command 'wrun' not found, did you mean:
  command 'srun' from deb slurm-client
  command 'zrun' from deb moreutils
  command 'grun' from deb grun
Try: sudo apt install <deb name>
 vagrant up
Command 'vagrant' not found, but can be installed with:
sudo apt install vagrant

Summary

Hi there, I am trying to set up a virtual machine for Drupal 8 using Windows WSL based on the Drupal VM Documentation for Windows installation. I just want to understand clearly if I should install Vagrant, VirtualBox and other software using WSL? 

I had no problems setting up drupalvm environment using Git Bash.

Any advice would be great. Thanks

**Comment by geerlingguy** [comment]
I'm guessing you're looking at the directions here: http://docs.drupalvm.com/en/latest/getting-started/installation-windows/#windows-subsystem-for-linux-ubuntu-bash

I don't think `wrun` is used anymore, but I'm not sure... it's been a few months since I used WSL.

**Comment by mikebernal** [comment]
I skipped the WSL and followed your blog to use cmder as admin instead and it works. https://www.jeffgeerling.com/blog/2019/developing-virtualbox-and-vagrant-on-windows.
Thanks.

**Comment by carlos-garcia** [comment]
googling this problem brought me here.... after research, turns out you dont need to use wrun anymor... just type the command..

like `vagrant.exe up`

but atfer that, the nfsd error is triggered....
