### ISSUE TITLE
Getting Drush to work with local Drupal 8 site

### ISSUE THREAD

**Issue by smustgrave** [geerlingguy/drupal-vm#1936]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.4
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

```

### Your OS

 - **Windows** (version) 

### Summary

Currently I'm running a local Drupal 8 site and the site is up and the database is working.  No issues there but I'm trying to get drush to work on the site and I can't get drush to connect to the drupalVM database.  Drush cr will give SQLSTATE[HY000] [2002] No connection could be made because the target machine actively refused it.  Also noticed there is no drush alias I can use.  Any assistance would be greatly appreciated.

**Comment by tomo-dev-2018** [comment]
I've got the same issue after having resolved issue: https://github.com/geerlingguy/drupal-vm/issues/1944 My exact environment data (Win10) can be found at the above link.

**Comment by phizev** [comment]
@smustgrave / @tomo-dev-2018 are you running the drush command on the Windows host, or from within the guest machine?

**Comment by tomo-dev-2018** [comment]
@phizev thanks to you again!! When you are on Windows host you have to use 'vagrant ssh' first to get into the guest Ubuntu 18.04 and from within there drush and drupal console work fine. Now I'm just wondering how install phpmyadmin and other stuff on guest ;-)
