### ISSUE TITLE
Connection to Solr refused

### ISSUE THREAD

**Issue by cotterpinx** [geerlingguy/drupal-vm#1938]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 2.2.2
VirtualBox 6.0.0r127566
ansible 2.4.0.0
  config file = None
  configured module search path = [u'/Users/lisa/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.11 (default, Mar 11 2016, 09:34:23) [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)]
```

### Your OS

 - **macOS** (10.14.3)

### Full console output

https://gist.github.com/cotterpinx/43ed5203e42c6e807ca6ec92a6c8179c

### Summary

I'm attempting to add Solr. (Default values from config, v5.5.5) The process appears to be running (I see references to Solr in the output) but when it tries to access the solr server it fails.  

My default.config.yml : https://gist.github.com/cotterpinx/4eba5d3f0cb686da54fa47e9041a4cb4

I also modified the 
 /provisioning/roles/geerlingguy.java/defaults/main.yml file to add the specification for Java 8 (instead of Java 7):

```
---
# Set java_packages if you would like to use a different version than the
# default (OpenJDK 1.7).
java_packages: 
  - openjdk-8-jdk

java_home: ""
```

What am I missing? The port is listed in the config so should be available, what else do I need here?

thanks

**Comment by psebborn** [comment]
I was having the same problem, and for me adding the following to my config file worked (specifically the solr version) :

```
solr_version: "8.0.0"
java_packages:
  - openjdk-8-jdk
solr_cores:
  - d8core
```
Hope that helps!

**Comment by tomo-dev-2018** [comment]
This is what made it work for me:
- in config.yml, under 'installed extras' I enabled solr AND java and put the following(under solr configuration):
```
# Solr Configuration (if enabled above).
solr_version: "8.3.1"
solr_xms: "256M"
solr_xmx: "512M"
```
- I changed my /provisioning/roles/geerlingguy.java/defaults/main.yml file to look like this:
```
# Set java_packages if you would like to use a different version than the
# default (OpenJDK 1.7).
# java_packages: []

java_packages: 
  - openjdk-11-jdk

java_home: ""
```
- and finally I changed my /provisioning/roles/geerlingguy.solr/defaults/main.yml to look like this:
```
---
solr_workspace: /root

solr_create_user: true
solr_user: solr

solr_version: "8.3.1"
solr_mirror: "https://archive.apache.org/dist"
solr_remove_cruft: false

solr_service_manage: true
solr_service_name: solr
solr_service_state: started

solr_install_dir: /opt
solr_install_path: "/opt/{{ solr_service_name }}"
solr_home: "/var/{{ solr_service_name }}"
solr_connect_host: localhost
solr_port: "8983"

solr_xms: "256M"
solr_xmx: "512M"

solr_timezone: "UTC"

solr_cores:
  - d8core

solr_config_file: /etc/default/{{ solr_service_name }}.in.sh

# Enable restart solr handler
solr_restart_handler_enabled: true

# Used only for Solr < 5.
solr_log_file_path: /var/log/solr.log
solr_host: "0.0.0.0"

```
As you can see the values for solr configuration in config.yml and /provisioning/roles/geerlingguy.solr/defaults/main.yml are the same. I don't know if it helped, buy it works for me.
