### ISSUE TITLE
Cannot find examples/prod/prod.config.yml

### ISSUE THREAD

**Issue by donbrae** [geerlingguy/drupal-vm#1948]
### Question

 - Documentation Report

### Your Environment

```
Vagrant 2.2.4
VirtualBox 6.0.4r128413
ansible 2.7.10
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.7.10/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Apr 18 2019, 11:43:43) [Clang 10.0.0 (clang-1000.11.45.5)]

```

### Your OS

 - **macOS** (version)

### Summary

I'm attempting a test deployment of DrupalVM to a production environment as per [documentation](http://docs.drupalvm.com/en/latest/other/production/#example-drupal-vm-on-digitalocean). Reference is made [here](http://docs.drupalvm.com/en/latest/other/production/#customize-configyml-for-production) to `examples/prod/prod.config.yml`. However, I cannot find this file, nor a `prod` directory. Could you advise? Cheers.

**Comment by phizev** [comment]
This was removed in "Drop 'official-ish' support for using Drupal VM to run production servers" #1883
The exact commit: https://github.com/geerlingguy/drupal-vm/commit/f4c74c116b0503813e1f409487a3063bf567b4ea

**Comment by donbrae** [comment]
Thanks, @phizev.
