### ISSUE TITLE
add Xdebug 2.7.2 support to drupal-vm when php 7.2 enabled [Adding xdebug to installed_extras causes failed build with php 7.2]

### ISSUE THREAD

**Issue by glassdimly** [geerlingguy/drupal-vm#1949]
### Issue Type

- Bug Report / Support Request
 

### Your Environment

```
vagrant --version && echo "VirtualBox `vboxmanage --version`" && ansible --version
Vagrant 2.2.5
VirtualBox 5.2.30r130521
ansible 2.8.1
  config file = None
  configured module search path = ['/Users/jeremy/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.1_1/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.3 (default, Jun 19 2019, 07:38:49) [Clang 10.0.1 (clang-1001.0.46.4)]

$ vagrant ssh
$ php --version
PHP 7.3.7 (cli) (built: Jul  3 2019 11:30:22) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.7, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.7, Copyright (c) 1999-2018, by Zend Technologies
[vagrant@drupalvm web]$
```

### Your OS

 - **macOS** 10.14

### Full console output

https://gist.github.com/glassdimly/d1ed6a0b676e49f5e87d35b2e9628ba9

### Summary

I'm attempting to add xdebug to this vm, and I have changed only the following (pseudo-diff 😄 ):
```
installed_extras:
+ - xdebug
```

Then run `vagrant provision` as from the [docs](http://docs.drupalvm.com/en/latest/extras/xdebug/).

**Comment by tomo-dev-2018** [comment]
I had a similar problem and changed the following lines in config.yml:

# XDebug configuration. XDebug is disabled by default for better performance.
php_xdebug_default_enable: 1
php_xdebug_coverage_enable: 1
php_xdebug_cli_disable: no
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1

**Comment by jnettik** [comment]
I ran into this too. The issue seems to be with xdebug and php7.3. Going back to 7.2 works for me.

**Comment by jonnyeom** [comment]
I am experiencing this as well.
I will try using a lower php version. Thanks!

**Comment by phizev** [comment]
It may help to set a newer version of Xdebug, I think the default is 2.6.0, and 7.3 support was only added in [Xdebug 2.7.0beta1](https://xdebug.org/updates.php), I use 2.7.2 (with PHP 7.2) as it is the latest stable version:
```
php_xdebug_version: 2.7.2
```

**Comment by glassdimly** [comment]
I have tested this workaround from @phizev and it works.
```
installed_extras:
  - xdebug

php_xdebug_version: "2.7.2"
```

and then whatever config may be desired. In my case:
```
php_xdebug_default_enable: 1
php_xdebug_remote_enable: 1
php_xdebug_remote_connect_back: 1
php_xdebug_idekey: PHPSTORM
php_xdebug_remote_port: "9003"
```

Re-titling this bug report to: "add Xdebug 2.7.2 support to drupal-vm when php 7.2 enabled."

**Comment by phizev** [comment]
@glassdimly I do have a [pull request](https://github.com/geerlingguy/ansible-role-php-xdebug/pull/61) open on the Ansible role. (Which is what is used by DrupalVM, and has the same author.) It's a minor change from the code perspective, but no idea if a bump in the default version there is acceptable.
