### ISSUE TITLE
Unable to restart service apache2: Job for apache2.service failed because

### ISSUE THREAD

**Issue by vidit-anjaria** [geerlingguy/drupal-vm#1951]
- Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VBox -  5.2.30r130521
Ansible - 2.8.2
```

### Your OS
 - **macOS** (10.14.5)

### Full console output

vagrant up

### Summary

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************
fatal: [example]: FAILED! => {"changed": false, "msg": "Unable to restart service apache2: Job for apache2.service failed because the control process exited with error code.\nSee \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\n"}

**Comment by phizev** [comment]
From within the VM, what is the output of:
```
systemctl status apache2.service
journalctl -xe
```

**Comment by vidit-anjaria** [comment]
@phizev

https://gist.github.com/vidit-anjaria/6dc3481b2aaa38996ae2adeb9e4b0ec7

`systemctl status apache2.service

* apache2.service - The Apache HTTP Server
   Loaded: loaded (/lib/systemd/system/apache2.service; enabled; vendor preset: enabled)
  Drop-In: /lib/systemd/system/apache2.service.d
           `-apache2-systemd.conf
   Active: failed (Result: exit-code) since Mon 2019-07-22 12:46:35 UTC; 9min ago
  Process: 14625 ExecStop=/usr/sbin/apachectl stop (code=exited, status=0/SUCCESS)
  Process: 14630 ExecStart=/usr/sbin/apachectl start (code=exited, status=1/FAILURE)
 Main PID: 682 (code=exited, status=0/SUCCESS)`

`journalctl -xe

Hint: You are currently not seeing messages from other users and the system.
      Users in groups 'adm', 'systemd-journal' can see all messages.
      Pass -q to turn off this notice.
No journal files were opened due to insufficient permissions.`

**Comment by phizev** [comment]
@vidit-anjaria journalctl -xe needs to be run with sudo.

I can't see anything blatantly obvious from the console output, finding out why Apache is failing to restart is necessary.
I don't have access to a mac, and Virtualbox 5.2 is quite old now, can you reproduce this issue with a default copy of DrupalVM? Can you provide your config.yml?

(Unless you own drupal.com, you're likely better off using something else as the domain name.)

**Comment by vidit-anjaria** [comment]
yes, it worked with DrupalVM. 

config.yml -  https://gist.github.com/vidit-anjaria/4e55c5e47fc8fc589a7b01f533637de1

**Comment by mayelaatf** [comment]
Hi, I am getting the following error, when I run vagrant provision:
`TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
fatal: [myapp]: FAILED! => {"changed": false, "msg": "Unable to start service apache2: Job for apache2.service failed because the control process exited with error code.\nSee \"systemctl status apache2.service\" and \"journalctl -xe\" for details.\n"}`

I am running MAC 10.15.6
ansible 2.9.11
Vagrant 2.2.10
VirtualBox6.1.12 r139181 (Qt5.6.3)

Any ideas how to solve this error? thanks in advance

**Comment by mayelaatf** [comment]
I solved it by removing all the VMs that were running except the one for the app I am using ( I did that in VirtualBox application) , then I stopped the VM for myapp and ran vagrant up and vagrant provision - this time everything ran without errors

**Comment by wahid14k** [comment]
Job for apache2.service failed because the control process exited with error code.
See "systemctl status apache2.service" and "journalctl -xe" for details.


what should i do now???
