### ISSUE TITLE
SSH Login broken when using vagrant_box: geerlingguy/drupal-vm 

### ISSUE THREAD

**Issue by vouza** [geerlingguy/drupal-vm#1956]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VirtualBox 6.0.10r132072
ansible 2.8.3
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.3/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]

```

### Your OS

 - **macOS** (MOJAVE)

After successful installation "up --provision" I try to log into the server via ssh "vagrant ssh".
By doing so I log in but the console does not show a blinging cursor... nor I am able to enter any command. 

When using "vagrant_box: geerlingguy/ubuntu1604" I am able to login.

**Comment by ndouglas** [comment]
Possible explanation: Check to see if `ifconfig` includes an entry for `vboxnet0`.  Occasionally, in my experience, Virtualbox will fail to set up that network driver.  You can open Virtualbox and open the Host Network Manager and you should see `vboxnet0` listed.  If you update it in some way (change the IP address, for instance) and then save, and then change it back, Virtualbox will remove and re-add the network driver, at which point things should start working.
