### ISSUE TITLE
Document hanging on ansible task: installing drush dependencies with composer.

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#196]
"Install Drush dependencies with Composer" is hanging with no timeout, status, progress until process is cancelled.

This is only being affected on protected networks which is understandable, but it would be great to document a process around this, perhaps even just report an error on hang or provide network requirements to open it up for each protected network.

I'm constantly building DrupalVM, and this is one of those things that I keep running into...
I might even look into the anible task to make any notable suggestions.

**Comment by fubarhouse** [comment]
Recent test has proven this has since been fixed... I'm not sure if that's the network I'm on or the server so I'll close this off.

**Comment by geerlingguy** [comment]
@fubarhouse - I did change the composer install method to use cached downloads recently; it should speed things up normally. The only risk is that if there are a lot of people doing composer installs at the same time on the same network, you can hit GitHub API rate limiting.
