### ISSUE TITLE
Error when checking for Solr cores.

### ISSUE THREAD

**Issue by jnettik** [geerlingguy/drupal-vm#1960]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VirtualBox 5.2.18r124319
ansible 2.8.4
  config file = None
  configured module search path = ['/Users/jnettik/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.4/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

### Your OS

 - **macOS** (version)

### Full console output

Some of the output was cut off, but here's the part that relates to Solr: https://gist.github.com/jnettik/2e86c24fde6ee530b4724356351112e6

### Summary

After updating to the latest version of the DrupalVM box (2.0.3), any new provision errors out at the same step:

```
TASK [geerlingguy.solr : Check current list of Solr cores.] ********************
fatal: [dvm-50]: FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://localhost:8983/solr/admin/cores"}
```

**Comment by attheshow** [comment]
I'm running into the same issue today when trying to update.

**Comment by attheshow** [comment]
I was able to get around this by switching it to install:
solr_version: "4.10.4"

Maybe it has to do with the Java 8+ note in the documentation here?:
http://docs.drupalvm.com/en/latest/extras/solr/

**Comment by adriadrop** [comment]
having very similar problem out of the box, get the

`FAILED! => {"changed": false, "content": "", "elapsed": 0, "msg": "Status code was -1 and not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://localhost:8983/solr/admin/cores"}`

using 
solr_version: "5.5.5"

**Comment by denisciglaric** [comment]
Same with me. Anybody has any idea how to fix this?

**Comment by joestewart** [comment]
Does it help to destroy and add this java version to config.yml?
```java_packages:
  - openjdk-8-jdk```

**Comment by krinajoshi** [comment]
@joestewart - It spent 2 days trying different solutions to fix this issue. Adding java_packages worked for me. Thank you so much.

**Comment by chrissnyder2337** [comment]
@joestewart - Adding java_packages worked for me too!

**Comment by geerlingguy** [comment]
This issue is not stale. Adding `java_packages` to the default config, along with updating the Solr version variable, should be done to make sure Solr is installable and usable out of the box with Drupal VM.

**Comment by geerlingguy** [comment]
Waiting on the above build to complete; it specifies a Java 8 version on both Debian/Ubuntu and Red Hat/CentOS. Note that for Debian 10, I haven't tested it (it's hard to get Java 8 on Debian 10) but the number of users of Drupal VM on Debian 10 is small enough that I'll worry about that at some other time. Hopefully when Solr 10 or 11 is out and finally supports a newer Java version :D
