### ISSUE TITLE
bionic Release' no longer has a Release file.

### ISSUE THREAD

**Issue by Fynkymynky** [geerlingguy/drupal-vm#1965]
### Issue Type
 - Bug Report / Support Request

### Your Environment

Vagrant 2.2.5
VBox Version 6.0.6 r130049 (Qt5.6.2)
```

```

### Your OS

 - **Windows** (10)

### Full console output

==> drupalvm: Running provisioner: drupalvm (ansible_local)...
    drupalvm: Installing Ansible...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

apt-get update -y -qq

Stdout from the command:

Stderr from the command:

E: The repository 'https://packagecloud.io/varnishcache/varnish61/ubuntu bionic Release' no longer has a Release file.

### Summary

When running vagrant up provision the process ends with the above error. Latest release from the drupalvm website.

**Comment by geerlingguy** [comment]
Have you tried running `vagrant destroy -f` (to delete the VM) and then `vagrant up` again after that (to recreate it fresh)?
