### ISSUE TITLE
Make PimpMyLog work better with access logs

### ISSUE THREAD

**Issue by sarahjean** [geerlingguy/drupal-vm#197]
Was trying to get Pimp My Log to read the logfiles for my local site, it was accessible at http://pimpmylog.drupalvm.dev/ but the configurator couldn't find the logfile the vhost was actually using. I had to create the config.user.php with the configurator and then edit it manually to add this entry below Apache #2:

```
                "apache3": {
                        "display"   : "Apache Access #3",
                        "path"      : "\/var\/log\/apache2\/other_vhosts_access.log",
                        "refresh"   : 0,
                        "max"       : 10,
                        "notify"    : false,
                        "multiline" : "",
                        "format"    : {
                                "regex"        : " |^(.*) (.*) (.*) \\[(.*)\\] \"(.*) (.*) (.*)\" ([0-9]*) (.*) \"(.*)\" \"(.*)\"( [0-9]*\/([0-9]*))*$|U",
                                "export_title" : "URL",
                                "match"        : {
                                        "Date"    : 4,
                                        "IP"      : 1,
                                        "CMD"     : 5,
                                        "URL"     : 6,
                                        "Code"    : 8,
                                        "Size"    : 9,
                                        "Referer" : 10,
                                        "UA"      : 11,
                                        "User"    : 3,
                                        "\u03bcs" : 13
                                },
                                "types": {
                                        "Date"    : "date:H:i:s",
                                        "IP"      : "ip:geo",
                                        "URL"     : "txt",
                                        "Code"    : "badge:http",
                                        "Size"    : "numeral:0b",
                                        "Referer" : "link",
                                        "UA"      : "ua:{os.name} {os.version} | {browser.name} {browser.version}\/100",
                                        "\u03bcs" : "numeral:0,0"
                                },
                                "exclude": {
                                        "URL": ["\/favicon.ico\/", "\/\\.pml\\.php.*$\/"],
                                        "CMD": ["\/OPTIONS\/"]
                                }
                        }
                }
```

Could probably have just edited apache #2 to point to this instead, its looking at `/var/log/apache2/access.log` which is completely empty.

These were the only settings I could find for pimpmylog so I wasn't sure if this could be changed in the provisioning:

```
# Pimp my Log settings.
pimpmylog_install_dir: /usr/share/php/pimpmylog
pimpmylog_grant_all_privs: true
```

**Comment by geerlingguy** [comment]
I'd like to get this fixed so PML is much more useful out of the box. As you've noticed, the normal access log gets nothing, since all requests go through configured virtualhosts. There isn't a simpler way to configure this upstream through the PML role, so either I can make that role (`geerlingguy.pimpmylog`) a little more configurable, or I could include more config/templates in this project. I'm going 50/50 right now, will try to come up with something soon.

**Comment by geerlingguy** [comment]
Closing https://github.com/geerlingguy/drupal-vm/issues/153 in favor of this issue. I'll treat the logs more comprehensively here.

**Comment by oxyc** [comment]
Started a PR upstream for helping out with this issue: https://github.com/geerlingguy/ansible-role-pimpmylog/pull/3

**Comment by oxyc** [comment]
I vote for removing the milestone on this one as well. I've slightly given up on a good way to solve this.

**Comment by geerlingguy** [comment]
Yeah... it's a bit too complex and I don't want to hold up the release on it. Maybe there's some other log display software that's easier to get configured with correct logs/permissions (and still super-light on resources)? I'm not married to PML :)

**Comment by geerlingguy** [comment]
For now, I'm going to kill this issue... fwiw, it seems most devs don't end up using PML, and if they do, they'll spend the time manually configuring it for the logs they need access to.

With the way PML is currently structured, it's painful to try to get it to _automatically_ work for common scenarios we use, like Apache, Nginx, Varnish, MySQL, etc.—especially for multiple OSes.

**Comment by geerlingguy** [comment]
(I'll still welcome any docs changes for this, in the form of PRs, or to the upstream role's docs in an example section).
