### ISSUE TITLE
Provision doesn't work on Windows due to symlink issues

### ISSUE THREAD

**Issue by codebymikey** [geerlingguy/drupal-vm#1970]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VMware Workstation 15 Pro: 15.1.0 build-13591040
Ansible local: 
ansible 2.8.5
  config file = None
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vagrant/.local/lib/python2.7/site-packages/ansible
  executable location = /home/vagrant/.local/bin/ansible
  python version = 2.7.15+ (default, Jul  9 2019, 16:51:35) [GCC 7.4.0]
```

### Your OS

 - **Windows** (Version	10.0.18362 Build 18362)

### Full console output

https://gist.github.com/codebymikey/148ad637125fd2afa94dd2fe275c8875

### Summary

The error occurs because the initial composer install creates vendor binaries with symlinks, visible by calling `ls -al /tmp/composer-project/vendor/bin/`:
![image](https://user-images.githubusercontent.com/9484406/64850648-b0c30300-d60d-11e9-8095-155e584a50d2.png)

So it fails when it tries to copy it into the host.

I believe the `composer install` needs to set `bin-compat: full` so that it works on all platforms.

Composer references:
https://github.com/composer/composer/blob/5633a68/src/Composer/Config.php#L282
https://github.com/composer/composer/blob/5633a68/src/Composer/Installer/BinaryInstaller.php#L90

**Comment by very-random-man** [comment]
I solved this by enabling symlinks in the Win10 local security policy. I was lazy and added 'Everyone' to the policy for creating symlinks. It seemed reasonable enough but I'm not 100% sure what the security implications of that are in windows. ;-)

This article has more details.
https://community.perforce.com/s/article/3472

**Comment by JasonWeakley** [comment]
Can confirm I am also seeing the symlinks.
https://imgur.com/a/euQhfpa
