### ISSUE TITLE
ansible error, pip: command not found on vagrant up

### ISSUE THREAD

**Issue by laurens94** [geerlingguy/drupal-vm#1972]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VirtualBox 6.0.12r133076
```

### Your OS

 - **macOS** (10.14.6)

### Full console output

https://gist.github.com/laurens94/82b50a8c62cee005446815830570b8bd

### Summary

On running `vagrant up` I get the following error:

```
    drupal7: Installing pip... (for Ansible installation)
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

pip install  --upgrade ansible

Stdout from the command:



Stderr from the command:

bash: line 5: pip: command not found
```

**Comment by phizev** [comment]
This is a know issue with Vagrant: https://github.com/hashicorp/vagrant/issues/10950
A solution is to downgrade to Ansible 2.2.4, or look through #1944 for alternative workarounds.

**Comment by geerlingguy** [comment]
Yeah, the best bet is to downgrade to 2.2.4 until that upstream issue is fixed.

**Comment by PuspaRaj-Subedi** [comment]
> Yeah, the best bet is to downgrade to 2.2.4 until that upstream issue is fixed.

i have downgrade but also it not works
