### ISSUE TITLE
Did not know it existed

### ISSUE THREAD

**Issue by ugintl** [geerlingguy/drupal-vm#1974]
I have been learning and developing on drupal for more than 2 years now. I found your project today and I am very happy about it. This also leaves me with a curiosity that what else is out there I do not know.

Can I make my VM or website publicly available so that clients can test it?

How is it different than Virtual Box or Hyper-V?

**Comment by geerlingguy** [comment]
Drupal VM _uses_ VirtualBox (or even HyperV) to run a VM and install and configure everything necessary for running a Drupal site, locally.

Drupal VM used to support running in production (e.g. using Drupal VM on a live web server), but as that feature was not used that much, it was abandoned (though you could probably still get it working if you tried hard enough :P).

You could use https://ngrok.com to allow someone to 'tunnel' to your local machine somewhat securely, but I generally don't like doing that as I think all my local services should remain local :)
