### ISSUE TITLE
NFS mounts and Catalina

### ISSUE THREAD

**Issue by karlshea** [geerlingguy/drupal-vm#1978]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VirtualBox 6.0.12r133076
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/karl/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.5/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep  7 2019, 18:27:02) [Clang 10.0.1 (clang-1001.0.46.4)]
```

### Your OS

 - **macOS** (10.15)

### Summary

Catalina's NFS exports work a little differently, root isn't root anymore. I was able to fix `vagrant_synced_folders` by changing `local_path` from `/Users/karl/Sites` to `/System/Volumes/Data/Users/karl/Sites/`, but the NFS synced vagrant directory is set in the Vagrantfile using `File.dirname(File.expand_path(__FILE__))` which when NFS-mounted is no longer the correct path. On Catalina `/System/Volumes/Data` should be prepended to `host_project_dir`.

If I run `DRUPALVM_PROJECT_ROOT=/System/Volumes/Data/Users/karl/Vagrant/php72 vagrant up` it all works, but it would be nice to not have to set that var each time.

It would also be nice to have `vagrant_synced_folders` corrected automatically, but I don't have to "hack core" to fix that.

**Comment by danepowell** [comment]
Upstream issue, although this still might need to be fixed in DrupalVM, not sure: https://github.com/hashicorp/vagrant/issues/10961

**Comment by gideoncresswell** [comment]
I don't know how old my version of this I am running but my Vagrantfile is 

```# The absolute path to the root directory of the project. Both Drupal VM and
# the config file need to be contained within this path.
ENV['DRUPALVM_PROJECT_ROOT'] = "#{__dir__}"

# The relative path from the project root to the config directory where you
# placed your config.yml file.
ENV['DRUPALVM_CONFIG_DIR'] = "config"

# The relative path from the project root to the directory where Drupal VM is located.
ENV['DRUPALVM_DIR'] = "vendor/geerlingguy/drupal-vm"

# Load the real Vagrantfile
load "#{__dir__}/#{ENV['DRUPALVM_DIR']}/Vagrantfile"
```

and I have a config.yml inside a config folder. 

These are the vagrant_synced_folders lines I have -

```
vagrant_synced_folders:
  # The first synced folder will be used for the default Drupal installation, if
  # any of the build_* settings are 'true'. By default the folder is set to
  # the drupal-vm folder.
  - local_path: .
    destination: /var/www/drupalvm
    type: nfs
    create: true
```

Any ideas where I need to add the `/System/Volumes/Data` text?

**Comment by charlieartist** [comment]
@karlshea I did some more checking, and tried your method. I could get Drupal VM stood up, but the Web root in the VM was blank (but no errors reported). Am doing more checking on this.

**Comment by K3vinF** [comment]
@karlshea I was able to get DrupalVM working again with your steps.
However what initially confused me was `Vagrant/php72` in your command, but I guess this is your local folder for DrupalVM.

@gideoncresswell I had to make sure all entries in  /etc/exports pointed to `/System/Volumes/Data`.

**Comment by gideoncresswell** [comment]
Unfortunately as soon as I run `vagrant reload` all my `/etc/export` lines change and it breaks. I need a way of making the change to that file persistent.

**Comment by charlieartist** [comment]
@gideoncresswell Yes. If I understand correctly, part of the security updates in Catalina directly address access to system files such as this.

**Comment by warmwaterkruik** [comment]
NFS mount seems broken for now and needs a fix upstream _I guess_. The workaround of mine is basically not using NFS shares but native Virtualbox shares by altering the Drupalvm config.yml. On OSX the steps are

1. shut down drupalvm with `vagrant halt`
2. check exports with `cat /etc/exports` and remove the defective Virtualbox entries that do not have /System/Volumes/Data - In my case I could just set an empty /etc/exports file. Not clearing the invalid entries will disrupt the Vagrant init of the vm.
3. Alter the Drupalvm config.yml to use native shares instead of nfs and do not forget to update the local_path entry with the added /System/Volumes/Data/Users/{username}
```yaml
vagrant_synced_folders:
  - local_path: /System/Volumes/Data/Users/daniel/Documents/Sites/natarch
    destination: /var/www/natarch
    # Instead of nfs, use an empty string to indicate native shares. This is considerably slower however.
    type: ""
    create: true
```
4. Alter the Drupalvm Vagrantfile to not share the vagrant project with the Virtualbox. Not doing this will halt the sharing process. I just commented out the lines under   # Sync the project root directory to /vagrant.
```ruby
  # Sync the project root directory to /vagrant
  # unless vconfig['vagrant_synced_folders'].any? { |synced_folder| synced_folder['destination'] == '/vagrant' }
  #   vconfig['vagrant_synced_folders'].push(
  #     'local_path' => host_project_dir,
  #     'destination' => '/vagrant'
  #   )
  # end
```
5. Do `vagrant up` and check your shares.

**Comment by cristian100** [comment]
Tried the workaround without success, I get the same error as gideoncresswell, where mounting fails.
I'm using as well OS X Catalina.

**Comment by charlieartist** [comment]
I've been doing more digging. Also, to confirm, have cloned the current Drupal VM, and ran `vagrant up`. Am getting the same errors.

Now, tracing it down, as well as looking at other solutions, have found something that looks promising:

```
if Dir.exist?("/System/Volumes/Data")
    [Some Alias] = "/System/Volumes/Data" + [Path in VM] # absolute path to Drupal VM directory on host machine for macos Catalina
else
    [Some Alias] = [Path in VM] # absolute path to Drupal VM directory on host machine
end
```

This should work in the Vagrantfile for the project. At the moment, I'm doing trial-and-error to see where it will work. If it's successful, it will work for users on Catalina and previous.

**Comment by dasginganinja** [comment]
I saw this on the original issue. Does this seem to help?

> Add /sbin/nfsd in System Preferences > Security & Privacy > Full Disk Access
> https://github.com/hashicorp/vagrant/issues/10961#issuecomment-541070382

**Comment by charlieartist** [comment]
@dasginganinja Thanks—that solution may work, if the permissions can be accessed (can't see the file to add in System Preferences). I find that if I edit the /private/etc/exports file, it is overwritten on vagrant up.

**Comment by karlshea** [comment]
I don't think this has anything to do with an upstream fix. When you mount an NFS folder you have to tell it the path you want mounted, which on Catalina includes /System/Volumes/Data.

Adding this to my Vagrantfile (along with fixing `local_path` in `vagrant_synced_folders`) fixed the issue: (Thanks, @charlieartist)

```
# Add after this line
host_project_dir = ENV['DRUPALVM_PROJECT_ROOT'] || host_drupalvm_dir

if Dir.exist?('/System/Volumes/Data')
    host_project_dir  = '/System/Volumes/Data' + host_project_dir
end
```

A similar solution is being used by ddev (drud/ddev#1869)

**Comment by karlshea** [comment]
Also, you can't edit /etc/exports other than *removing* items, because Vagrant still needs to map things correctly, as you're discovering when `vagrant up` breaks. The path in /etc/exports needs to match the path Vagrant is trying to mount.

**Comment by charlieartist** [comment]
@karlshea Thanks—tried adding that in, but got errors. I probably need to change `host_drupalvm_dir` to my specific needs. Also, it appears there is [Vagrant fix](https://github.com/hashicorp/vagrant/issues/10961#issuecomment-541175288) on the way.

**Comment by iainhouston** [comment]
Can confirm @karlshea solution above worked for me. 

To be absolutely clear: 

1. The Vagrantfile I edited was not the one in the project folder but was the one in `vendor/geerlingguy/drupal-vm/` ... obviously not good in the long-term

2. In my `config.yml` I updated `vagrant_synced_folders` thus: 

```
    vagrant_synced_folders:
      - local_path:  /System/Volumes/Data/Users/iain/misfitstheatre.test
        destination: /var/www/drupal
        type: nfs
```


3. I deleted `~/.vagrant.d` as it had cached previous export directory names

4. I updated to latest Vagrant and VirtualBox

**Comment by charlieartist** [comment]
@iainhouston Thanks—just tried this, and from the CLI looks good, no warnings, but site wasn't installed at web root in the VM. I'll do some more checking and testing.

**Comment by vijaymayekar** [comment]
Thanks @iainhouston your solution worked for me.

**Vagrantfile file changes:**
```
# Add after this line
host_project_dir = ENV['DRUPALVM_PROJECT_ROOT'] || host_drupalvm_dir

if Dir.exist?('/System/Volumes/Data')
    host_project_dir  = '/System/Volumes/Data' + host_project_dir
end
```

**config.yml file changes**

```
vagrant_synced_folders:
      - local_path:  /System/Volumes/Data/Users/username/vagrant/drupalvm
        destination: /var/www/drupal
        type: nfs
```

vagrant version : 2.2.5
Virtual Machine : 6.0
DrupalVM : 5.0.1

**Comment by gideoncresswell** [comment]
I upgraded my vagrant to 2.2.6 today and vagrant up and reload both worked now. I also had to do a vagrant plugin update for VBGuest.

I can log into the server using vagrant ssh but I can't access my site in a browser anymore. I wonder what other protective measures Catalina has introduced.

**Comment by charlieartist** [comment]
@gideoncresswell I have updated as well. On the first round, the build was stood up in the VM where it should be, but nothing in the browser. So, tried `vagrant reload`, and first got the same NFS errors as before.

So, did some testing/trial-and-error.

Got it fixed by updating the VBGuest and Hostsupdater plugins, then by deleting the VM, as well as the ~/.vagrant.d and ~/Vagrant folders. After this, builds stood up fine.

Hope this helps!

**Comment by charlieartist** [comment]
@markahrens If you have updated Drupal VM, Vagrant, and VirtualBox, you should be able to stand up your build with the same file settings you used before the Catalina update.

I deleted the ~/.vagrant.d and VMs, as well as the /private/etc/exports file to be sure there wasn't any cruft left over, then `vagrant plugin update` then `vagrant up`.

**Comment by markahrens** [comment]
@charlieartist I ran through those steps as well and am still receiving the `Stale file handle` error. This happens on a brand new instance as well as my previous site. I can `cd` into what should be the site folder when ssh-ed into the VM, however I get this:
```
vagrant@drupalvm:/var/www/drupalvm$ ls -la
ls: cannot open directory '.': Stale file handle
```
I then checked the permissions on the `drupalvm` folder and it showed the following from within the VM: `drwxr-xr-x 23  502 dialout  736 Oct 15 17:26 drupalvm`

I tried doing this in both iTerm and Terminal to see if the new folder permissions might be an issue, but it was the same result in both.

**Comment by markahrens** [comment]
@charlieartist I figured out the issue, the sites I was testing this out on were in in the Documents and Downloads folders. Both of these folders have new protections on them which appears to block accessing anything inside them. When i cloned the drupal-vm project in my Users folder directly, then `vagrant up` ran just fine and the site worked perfectly.

It looks like moving any sites folders that are in Documents or Downloads to the user folder instead should resolve the issue.

**Comment by gideoncresswell** [comment]
@charlieartist I'll take your advice and delete the folders. Although I don't appear to have a `~/Vagrant` folder? Is that your default machine folder inside Virtual Box? I have a different folder set so I'd delete that if that's what it is. Thanks.

**Comment by gideoncresswell** [comment]
I did delete everything and got the VM working again. Except it still refuses to connect in the browser or using curl.

I'm guessing it's some kind of firewall issue? Unfortunately that's not my speciality.

I'll try the supplemental Catalina update today.

**Comment by naveenvalecha** [comment]
I faced the same issue today. I followed the following steps to resolve it:

- Halt the VM `vagrant halt`
- Upgraded the vagrant to 2.2.6
- Upgraded the vagrant plugins `vagrant plugin update`
- Remove the VM information from the /etc/exports file
- vagrant up

**Comment by gideoncresswell** [comment]
OK something happened and it's all working now. Definitely the advice by @charlieartist has helped by removing those folders. I did a `vagrant up --provision` last of all and it is now working fine.

**Comment by charlieartist** [comment]
@karlshea Is anyone else still having trouble? If not, should we close this issue?

**Comment by karlshea** [comment]
I updated to the latest Vagrant release and it does seem like they implemented an upstream fix. After destroying the Vagrant instance and reverting my changes, `vagrant up` succeeds just fine. Looks like this can be closed.

**Comment by amitsharma334** [comment]
I tried all the solutions given here. But no luck for me.

I have below configurations.

Mac Catalina 
version10.15.7 (19H2)

Vagrant: 2.2.14
VirtualBox: 6.1
Ansible 2.10.3

config.yml

vagrant_synced_folders:
  - local_path: . 
    destination: /var/www/8world
    type: "nfs"
    create: true

I cleaned the /etc/exports and /private/etc/exports

I restarted the nfsd service then vagrant reload but still facing the same issue.

==> 8world: Mounting NFS shared folders...

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.56.1:/System/Volumes/Data/Users/amit.sharma/Sites/mediacorp/8world/8world-drupal /var/www/8world

Stdout from the command:

Stderr from the command:

mount.nfs: Connection timed out
```
