### ISSUE TITLE
Stale file handle on macOS Catalina NFS mount

### ISSUE THREAD

**Issue by claudioafelix** [geerlingguy/drupal-vm#1980]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.6
VirtualBox 6.0.14r133895
ansible 2.8.5
  config file = None
  configured module search path = ['/Users/henriquemoura/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Sep 28 2019, 16:39:19) [Clang 11.0.0 (clang-1100.0.33.8)]
```

### Your OS

 - **macOS** (10.15 - Catalina)

### Full console output

```
vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/drupal-vm' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/drupal-vm'
    drupalvm: URL: https://vagrantcloud.com/geerlingguy/drupal-vm
==> drupalvm: Adding box 'geerlingguy/drupal-vm' (v2.0.5) for provider: virtualbox
    drupalvm: Downloading: https://vagrantcloud.com/geerlingguy/boxes/drupal-vm/versions/2.0.5/providers/virtualbox.box
    drupalvm: Download redirected to host: vagrantcloud-files-production.s3.amazonaws.com
==> drupalvm: Successfully added box 'geerlingguy/drupal-vm' (v2.0.5) for 'virtualbox'!
==> drupalvm: Preparing master VM for linked clones...
    drupalvm: This is a one time operation. Once the master VM is prepared,
    drupalvm: it will be used as a base for linked clones, making the creation
    drupalvm: of new VMs take milliseconds on a modern system.
==> drupalvm: Importing base box 'geerlingguy/drupal-vm'...
==> drupalvm: Cloning VM...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/drupal-vm' version '2.0.5' is up to date...
==> drupalvm: Setting the name of the VM: equalizi.test
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...

...

TASK [geerlingguy.nginx : Remove legacy vhosts.conf file.] *********************
skipping: [drupalvm]

TASK [geerlingguy.nginx : Copy nginx configuration in place.] ******************
skipping: [drupalvm]

TASK [geerlingguy.nginx : Ensure nginx service is running as configured.] ******
skipping: [drupalvm]

TASK [drupalvm.www : Define drupalvm_webserver_user (Debian).] *****************
ok: [drupalvm]

TASK [drupalvm.www : Define drupalvm_webserver_user (RedHat).] *****************
skipping: [drupalvm]

TASK [drupalvm.www : Register information about the /vagrant directory.] *******
fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "Stale file handle"}

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

PLAY RECAP *********************************************************************
drupalvm                   : ok=176  changed=4    unreachable=0    failed=1    skipped=335  rescued=0    ignored=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

### Summary

After upgrade to Catalina I am unable to start my drupalvm machine in this user (uid=506), vagrant up finish with the error below:

```
TASK [drupalvm.www : Register information about the /vagrant directory.] *******
fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "Stale file handle"}
```

This is a shared computer and user (uid=501) drupalvm works fine.

**Comment by geerlingguy** [comment]
It looks like this is the related upstream issue: https://github.com/hashicorp/vagrant/issues/11134

Also related: #1984 — in that issue, @vouza recommends the following workaround:

  1. Update [Vagrant](https://www.vagrantup.com/docs/installation/upgrading.html)
  2. Update [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
  3. Update Ansible (if installed)
  4. Replace your Vagrantfile with follwing code-snippet:

     ```
     // Line 111
     if Dir.exist?("/System/Volumes/Data")
       nfsPath = "/System/Volumes/Data" + Dir.pwd
     else
       nfsPath =  synced_folder.fetch('local_path')
     end
     config.vm.synced_folder nfsPath, synced_folder.fetch('destination'), options
     ```

  5. Backup and delete your `/etc/exports` file: `sudo rm /etc/exports`
  6. Start Vagrant: `vagrant up --provision`

**Comment by geerlingguy** [comment]
(Just noting that I am not yet running Catalina for a couple other reasons... waiting on a .2 release and for one app I use to be updated from 32-bit; so my testing on this will be minimal for now.)

**Comment by nathan-fiscaletti** [comment]
I resolved this issue by granting `/etc/nfsd` full disk access on my MacOS host machine. 

See https://github.com/laravel/homestead/issues/1304#issuecomment-545391163

**Comment by claudioafelix** [comment]
Thank you for the replies!

This error is related how Catalina handles the ~/Documents directory. To access this directory you must provide full disk access to the application.

So you have to create your VM in other directory or gives permission to nfsd as suggested by @nathan-fiscaletti above!

**Comment by geerlingguy** [comment]
Marking as open; I just updated to Catalina and will be testing this with my default location in the Sites folder on my Mac, too. Might still need to make a change here.

**Comment by geerlingguy** [comment]
Weird, in my case the share seems okay, but I'm getting a drush site-install failure:

```
TASK [geerlingguy.drupal : Install Drupal with drush.] *************************
fatal: [drupalvm]: FAILED! => changed=true 
  cmd:
  - /var/www/drupalvm/drupal/vendor/bin/drush
  - site-install
  - standard
  - -y
  - --root=/var/www/drupalvm/drupal/web
  - --site-name=Drupal
  - --account-name=admin
  - --account-pass=admin
  - --db-url=mysql://drupal:drupal@localhost/drupal
  delta: '0:02:02.088839'
  end: '2019-11-04 15:43:31.197396'
  msg: non-zero return code
  rc: 1
  start: '2019-11-04 15:41:29.108557'
  stderr: |2-
     [notice] Starting Drupal installation. This takes a while.
  
    In install.core.inc line 529:
  
      <ul>
      <li>To start over, you must empty your existing database and copy <em>defau
      lt.settings.php</em> over <em>settings.php</em>.</li>
      <li>To upgrade an existing installation, proceed to the <a href="/update.ph
      p">update script</a>.</li>
      <li>View your <a href="http://default">existing site</a>.</li>
      </ul>
  
  
    site:install [--db-url DB-URL] [--db-prefix DB-PREFIX] [--db-su DB-SU] [--db-su-pw DB-SU-PW] [--account-name [ACCOUNT-NAME]] [--account-mail [ACCOUNT-MAIL]] [--site-mail [SITE-MAIL]] [--account-pass ACCOUNT-PASS] [--locale [LOCALE]] [--site-name [SITE-NAME]] [--site-pass SITE-PASS] [--sites-subdir SITES-SUBDIR] [--config-dir CONFIG-DIR] [--existing-config] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--notify [NOTIFY]] [--druplicon] [--xh-link XH-LINK] [--] <command> [<profile>]...
  stderr_lines: <omitted>
  stdout: |2-
  
     // You are about to DROP all tables in your 'drupal' database. Do you want to
     // continue?: yes.
  stdout_lines: <omitted>
```

Might just be some remnant of an old install.

**Comment by geerlingguy** [comment]
Nevermind, reinstalling after deleting the local Drupal installation that was there worked great, inside the `~/Sites` directory. So no issues, and this issue is only a concern if you store your shared codebase in a directory like Documents, Desktop, or Downloads (one of the 'protected' dirs).

**Comment by jmann6** [comment]
> Nevermind, reinstalling after deleting the local Drupal installation that was there worked great, inside the `~/Sites` directory. So no issues, and this issue is only a concern if you store your shared codebase in a directory like Documents, Desktop, or Downloads (one of the 'protected' dirs).

This same solution worked for me.  👍

**Comment by paoga87** [comment]
> It looks like this is the related upstream issue: [hashicorp/vagrant#11134](https://github.com/hashicorp/vagrant/issues/11134)
> 
> Also related: #1984 — in that issue, @vouza recommends the following workaround:
> 
> 1. Update [Vagrant](https://www.vagrantup.com/docs/installation/upgrading.html)
> 2. Update [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
> 3. Update Ansible (if installed)
> 4. Replace your Vagrantfile with follwing code-snippet:
>    ```
>    // Line 111
>    if Dir.exist?("/System/Volumes/Data")
>      nfsPath = "/System/Volumes/Data" + Dir.pwd
>    else
>      nfsPath =  synced_folder.fetch('local_path')
>    end
>    config.vm.synced_folder nfsPath, synced_folder.fetch('destination'), options
>    ```
> 5. Backup and delete your `/etc/exports` file: `sudo rm /etc/exports`
> 6. Start Vagrant: `vagrant up --provision`

@geerlingguy: I feel like I've done EVERYTHING I could and still not working for me. I followed your steps as well. Wiped out my repo, and reinstalled everything (including an update to Catalina 10.15.1). I am now getting the following error:

```
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3 192.168.136.1:/System/Volumes/Data/Users/[myUser]/Documents/[folder_name] /var/www/[folder_name]

Stdout from the command:



Stderr from the command:

mount.nfs: access denied by server while mounting 192.168.136.1:/System/Volumes/Data/Users/[myUser]/Documents/[folder_name]

**Comment by hmartens** [comment]
> It looks like this is the related upstream issue: [hashicorp/vagrant#11134](https://github.com/hashicorp/vagrant/issues/11134)
> 
> Also related: #1984 — in that issue, @vouza recommends the following workaround:
> 
> 1. Update [Vagrant](https://www.vagrantup.com/docs/installation/upgrading.html)
> 2. Update [VirtualBox](https://www.virtualbox.org/wiki/Downloads)
> 3. Update Ansible (if installed)
> 4. Replace your Vagrantfile with follwing code-snippet:
>    ```
>    // Line 111
>    if Dir.exist?("/System/Volumes/Data")
>      nfsPath = "/System/Volumes/Data" + Dir.pwd
>    else
>      nfsPath =  synced_folder.fetch('local_path')
>    end
>    config.vm.synced_folder nfsPath, synced_folder.fetch('destination'), options
>    ```
> 5. Backup and delete your `/etc/exports` file: `sudo rm /etc/exports`
> 6. Start Vagrant: `vagrant up --provision`

Is this step still necessary Jeff?

**Comment by seanr** [comment]
I have the same issue as @paoga87 and am getting nowhere. I feel like I've tried _everything_. @geerlingguy maybe this should be reopened?

**Comment by geerlingguy** [comment]
Anyone still having this issue, please see https://github.com/hashicorp/vagrant/issues/11134
