### ISSUE TITLE
Update needed: new OSX "Catalina" incompatible 

### ISSUE THREAD

**Issue by vouza** [geerlingguy/drupal-vm#1984]
Due to the new osx's internal handling of the system file structure, vagrant  / nfs loses its ability to modify the file structure.

A fix should be included in drupal-vm soon.

We were able to fix this issue which is also documented here:
https://github.com/hashicorp/vagrant/issues/10961#issuecomment-539952810

.. by doing the following:

1. - Update vagrant (https://www.vagrantup.com/docs/installation/upgrading.html)
2. - Update VirtualBox (https://www.virtualbox.org/wiki/Downloads)
3. - Update ansible
4. - Replace your Vagrantfile with follwing code-snippet:
```
// Line 111
if Dir.exist?("/System/Volumes/Data")

      nfsPath = "/System/Volumes/Data" + Dir.pwd

    else

      nfsPath =  synced_folder.fetch('local_path')

    end

    config.vm.synced_folder nfsPath, synced_folder.fetch('destination'), options
```

5. - Backup and delete your etc/exports file sudo rm /etc/exports
6. - Start Vagrant vagrant up --provision

Cheers

**Comment by geerlingguy** [comment]
@vouza - is this related to #1980? It seems like it could be...

What's the actual error message you encountered that led you to work on the changes?

**Comment by geerlingguy** [comment]
Moving this issue's discussion to #1980 since it's the same issue AFAICT.
