### ISSUE TITLE
Question on PHP-FPM Configuration Again and 503 Error

### ISSUE THREAD

**Issue by deeplfo** [geerlingguy/drupal-vm#1990]
On my last round of building via Drupal-VM I got the same errors as mentioned in this [issue](https://github.com/geerlingguy/drupal-vm/issues/542).  

The solution was to modify the PHP-FPM's www-conf file to have the FCGI listener be on 127.0.0.1:9000, instead of its default socket file.

Questions: 1) any reason why I would suddenly be seeing that and not before?  and 2) is there a more general manner of addressing this, as performing that step after each box build is not really ideal.

Thanks,
mohsen

**Comment by geerlingguy** [comment]
All of the PHP-FPM settings are configurable (e.g. see https://github.com/geerlingguy/ansible-role-php#php-fpm); and the default is indeed to use port 9000 on TCP, and not the unix socket (see: https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L276). So maybe something in your own configuration is overriding this and causing it to use the socket?
