### ISSUE TITLE
Seems to be an issue opening any PHP service after BLT VM completes

### ISSUE THREAD

**Issue by ejanus** [geerlingguy/drupal-vm#1999]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.1
VirtualBox 6.0.14r133895
ansible 2.9.2
  config file = None
  configured module search path = ['/Users/erekj/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.5 (default, Nov  1 2019, 02:16:23) [Clang 11.0.0 (clang-1100.0.33.8)]
```

### Your OS

 - **macOS** (10.15.1 catalina)

### Full console output

Output from guest apache config test:
`$>apachectl configtest`
```
AH00112: Warning: DocumentRoot [/usr/share/php/xhprof_html] does not exist
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 127.0.0.1. Set the 'ServerName' directive globally to suppress this message
Syntax OK
```
Solr and MailHog services are available. Seems isolated to PHP services

`>tail -f `on apache error log when trying to access Adminer: 
```
[Tue Dec 10 20:55:48.864470 2019] [proxy:error] [pid 14936:tid 140267684308736] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (*) failed
[Tue Dec 10 20:55:48.864677 2019] [proxy_fcgi:error] [pid 14936:tid 140267684308736] [client 192.168.117.1:59899] AH01079: failed to make connection to backend: 127.0.0.1, referer: http://dashboard.local.projblt.com/
```

### Summary

I've also created an issue in the Acquia BLT issue queue here in the event it is more related to the BLT usage of DrupalVM: https://github.com/acquia/blt/issues/3948

There seems to be an issue opening any PHP service after BLT VM completes. So, Adminer, PimpMyLog, and the site are not running.
I’ve re-installed VirtualBox, completely destroyed the VM (vagrant destroy) then, followed through with normal composer install, BLT VM. Same thing I've been doing for the last year every so often on our project. My coworker has almost the exact same Mac / Setup and is able to run through the BLT VM, blt setup, through to the BLT sync, no issues. This issue began for me about a month ago.

**Comment by danepowell** [comment]
This appears to be a dupe of https://github.com/geerlingguy/drupal-vm/issues/1996

It would probably be better to centralize discussion there.
