### ISSUE TITLE
Additional uncaught exception thrown while handling exception.

### ISSUE THREAD

**Issue by abdulgaffar78** [geerlingguy/drupal-vm#2000]
Since last week I am going through this issue while setting up Drupal8. When I am going to URL where the d8 is installed it redirects me to /core/install.php and throwing following error. I have tried several other vagrant boxes but all is throwing the same error.

### _Additional uncaught exception thrown while handling exception_.
Original
TypeError: Argument 1 passed to Drupal\Core\Extension\ThemeHandler::addTheme() must be an instance of Drupal\Core\Extension\Extension, null given, called in /var/www/html/drupal8/core/includes/theme.maintenance.inc on line 72 in Drupal\Core\Extension\ThemeHandler->addTheme() (line 115 of /var/www/html/drupal8/core/lib/Drupal/Core/Extension/ThemeHandler.php).

Drupal\Core\Extension\ThemeHandler->addTheme(NULL) (Line: 72)
_drupal_maintenance_theme() (Line: 745)
drupal_maintenance_theme() (Line: 518)
install_begin_request(Object, Array) (Line: 115)
install_drupal(Object) (Line: 44)
Additional
TypeError: Argument 1 passed to Drupal\Core\Extension\ThemeHandler::addTheme() must be an instance of Drupal\Core\Extension\Extension, null given, called in /var/www/html/drupal8/core/includes/theme.maintenance.inc on line 72 in Drupal\Core\Extension\ThemeHandler->addTheme() (line 115 of /var/www/html/drupal8/core/lib/Drupal/Core/Extension/ThemeHandler.php).

Drupal\Core\Extension\ThemeHandler->addTheme(NULL) (Line: 72)
_drupal_maintenance_theme() (Line: 745)
drupal_maintenance_theme() (Line: 1027)
install_display_output(Array, Array, Array) (Line: 260)
_drupal_log_error(Array, 1) (Line: 605)
_drupal_exception_handler(Object)

#### Issue Type

 - Support Request 

#### Your Environment
`drupal-vm`,`geerlingguy/drupal-vm`, `vagrant version 2.0.6` , `VirtualBox 5.2.34`

#### Your OS
 - **Windows** (10)

**Comment by charlyox** [comment]
Hello, I am facing the same issue, but with another vagrant box : hashicorp/bionic64, and several drupal installation types. 
Did you find a solution ?

**Comment by charlyox** [comment]
Your setup made me find the solution : upgrade VirtualBox to 6.0.14. Works for me now.
