### ISSUE TITLE
Ansible post-provision task file does not seem to be working correctly

### ISSUE THREAD

**Issue by pyrello** [geerlingguy/drupal-vm#2005]
### Issue Type

Support Request

### Your Environment

```
Vagrant 2.2.5
VirtualBox 6.0.12r133076
ansible 2.9.2
  config file = None
  configured module search path = ['/Users/username/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.9.2/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.6 (default, Dec 30 2019, 19:38:28) [Clang 11.0.0 (clang-1100.0.33.16)]
```

### Your OS

**macOS** (Mojave - 10.14.6)

### Full console output

Output from `vagrant provision`: https://gist.github.com/pyrello/ea5ea8f42a63f2d3670347a167a2ffd3

```
vagrant@uiowa01:/var/www/uiowa01$ nvm

Command 'nvm' not found, did you mean:

  command 'nam' from deb nam
  command 'num' from deb quickcal
  command 'nm' from deb binutils
  command 'vm' from deb mgetty-voice
  command 'nvme' from deb nvme-cli
  command 'lvm' from deb lvm2
  command 'nim' from deb nim
  command 'npm' from deb npm
  command 'kvm' from deb qemu-kvm
  command 'pvm' from deb pvm
  command 'nvim' from deb neovim
  command 'nvi' from deb nvi

Try: sudo apt install <deb name>
```

### Summary

I am attempting to add an Ansible task file to Drupal VM per these instructions: http://docs.drupalvm.com/en/latest/extending/scripts/#ansible-task-files

My Ansible task file is stored at scripts/nvm.yml and is based on this link: https://github.com/nvm-sh/nvm#ansible
```yml
- name: nvm
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  args:
    creates: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
```

I have added the following to my box/config.yml file to try to get this working:
```yml
post_provision_tasks_dir:
  - ../../../../scripts/nvm.yml
```

It seems that the task file runs, but the expected addition is not made to the /home/vagrant/.bashrc file. Is there anything you can see that I'm doing wrong?

**Comment by hugronaphor** [comment]
I also failed to make it work with an Ansible task so I wrote a bash script triggered at `post_provision_scripts` step.

config.yml
```
post_provision_scripts:
  - "../../../../box/scripts/provision-node.sh"
```
provision-node.sh
https://gist.github.com/hugronaphor/7d346eba90730517bc1985811e7a1098

**Comment by YDH95** [comment]
{
  "open-in-browser.default": "chrome"
}
