### ISSUE TITLE
Running Drupal on SQLite does not work.

### ISSUE THREAD

**Issue by drupal-daffie** [geerlingguy/drupal-vm#2007]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.1.5
VirtualBox 5.2.34_Ubuntur133883
ansible 2.9.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/daffie/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 7.4.0]

```

### Your OS

 - **Linux** (Ubuntu 18.04)

### Full console output

php core/scripts/run-tests.sh --url http://drupal90dev.test/ --dburl sqlite://localhost/sites/default/files/drupal.sqlite --sqlite '/tmp/db.sqlite' --verbose --class 'Drupal\Tests\Scripts\TestSiteApplicationTest'

### Summary

I am using DrupalVM to work on Drupal core. Working with a PostgreSQL and/or MySQL database is great, only I am unable to get it to work with SQLite. I think that I am doing something wrong with directory/file permissions. I am not a Linux guru. I like to place the SQLite database in the sites/default/files directory. Any other location is for me also fine. An empty SQLite database is created, but that is it.

**Comment by geerlingguy** [comment]
Good question; last time I dug into this it was working okay for me, but it is likely something to do with permissions. A few issues you can look at to see if there's anything helpful from the past:

  - https://github.com/geerlingguy/drupal-vm/issues/1793
  - https://github.com/geerlingguy/drupal-vm/issues/1491
  - https://github.com/geerlingguy/drupal-vm/issues/198

**Comment by drupal-daffie** [comment]
I could not get it to work in '/var/www/drupalvm/drupal' directory or in any sub-directory. It works for me to place the SQLite datbase files in the home directory of the vagrant user. Like:
php core/scripts/run-tests.sh --url http://drupal90dev.test/ --dburl 'sqlite://localhost//home/vagrant/drupal.sqlite' --sqlite '/tmp/db.sqlite' --verbose --class 'Drupal\Tests\Scripts\TestSiteApplicationTest'

**Comment by drupal-daffie** [comment]
@geerlingguy: Almost forgot, thank you for your help!

**Comment by drupal-daffie** [comment]
If I try to run functionaltests with the following setting in phpunit.xml: <code><env name="SIMPLETEST_DB" value="mysql://drupal:drupal@localhost/drupal"/></code>, everything runs as it should. If I change that setting to: <code><env name="SIMPLETEST_DB" value="mysql://drupal:drupal@localhost/drupal"/></code>, the tests fail. They fail because I only have read access from the SQLite database.
I reviewed the three issue that you mentioned and they could not help me with my problem.

**Comment by geerlingguy** [comment]
I'm not quite sure; usually when I'm running simpletest, I just let simpletest handle the database stuff for me.

Note that the type of shared filesystem you use may have some effect, if you're sharing in your Drupal codebase and the files directory is in there. Maybe try switching the type to NFS or rsync and see if that makes any difference (http://docs.drupalvm.com/en/latest/getting-started/syncing-folders/).
