### ISSUE TITLE
Ansible Failed to complete - Windows 7

### ISSUE THREAD

**Issue by AGreenCoSA** [geerlingguy/drupal-vm#2009]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.2.7
bash: vboxmanage: command not found
VirtualBox
bash: ansible: command not found

```

### Your OS

 - **Windows** (version)

### Full console output

https://gist.github.com/AGreenCoSA/4fd2d639631aa8f9904d2e905d58ff15

### Summary

PHP Fatal error:  Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223"], "stdout": "\nFatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223\n\nCheck https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.", "stdout_lines": ["", "Fatal error: Allowed memory size of 1610612736 bytes exhausted (tried to allocate 67108864 bytes) in phar:///usr/bin/composer/src/Composer/DependencyResolver/Solver.php on line 223", "", "Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors."]}

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Note that for composer installs, it seems that Drupal now requires more than 1.5 GB of RAM allocated to Composer to install correctly. That setting can be modified via the php_memory_limit variable (set it to `-1` to allow all the memory).

See https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on setting COMPOSER_MEMORY_LIMIT or other options too.

Note that Windows 7 is no longer supported by Microsoft, nor by this project :(
