### ISSUE TITLE
Improve general MySQL performance through better config defaults

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#201]
I was experiencing some long response times (couldn't really narrow down why) even with Memcache enabled.

I took a look at some of my old Vlad settings (where I also tweaked MySQL conf) and set them in config.yaml. I have noticed marked improvements when dealing with VM response times while logged in (front end and back end). YMMV

```
# MySQL Configuration.
mysql_slow_query_log_enabled: false
mysql_slow_query_time: 2
adminer_add_apache_config: false
mysql_max_allowed_packet: 128M
innodb_buffer_pool_size: 64M
innodb_file_per_table: true
innodb_log_file_size: 64M
mysql_character_set_server: utf8
mysql_collation_server: utf8_general_ci
skip_name_resolve: false
mysql_allow_all_hosts: true
mysql_log_queries_not_using_indexes: false
```

I also set the natdnshostresolver1 resolve flag for Virtualbox to OFF instead of ON in the Vagrantfile.

**Comment by geerlingguy** [comment]
I've been meaning to do a little work making MySQL and Apache configuration a little more robust/reliable in limited memory environments, but haven't had the time to add the changes to the default config. The current MySQL defaults (in the `geerlingguy.mysql` role) are configured for a _dedicated_ database server with ~512MB RAM. They should definitely be adjusted somewhat for Drupal VM.

**Comment by geerlingguy** [comment]
Glancing through this list, most of the settings should have a more minimal impact on performance, and I've also run through the current defaults with PHP 7 + MySQL 5.7, and the speed differences were not easily measured... though there is still room for improvement.

I'm going to close this issue, and we can take a look at individual settings changes (preferably with a reproducible before/after diff so we can decide if we need to change things on a setting-by-setting basis).
