### ISSUE TITLE
ERROR : You are not using an encrypted connection, so your password will be sent in plain text

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2010]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.5
VirtualBox 6.0.10
```

### Your OS
 - **Windows** (version)

### Full console output

ERROR : You are not using an encrypted connection, so your password will be sent in plain text

### Summary

I can not install new modules in Drupal 8. This error message occurs:
"ERROR : You are not using an encrypted connection, so your password will be sent in plain text"
Same problem as [described here](https://medium.com/@jangid.hitesh2112/error-you-are-not-using-an-encrypted-connection-so-your-password-will-be-sent-in-plain-text-b74599430b35).

The "chown www-data:www-data .." command did not solve the problem.

Do I have to enable https still on development envirenment?
How can I enable https in Drupal VM running under Windows 10?
Isn't there any way not to use https (only on local development environment)? How?

Thank you.

**Comment by geerlingguy** [comment]
I'm not sure why this would prevent you from installing new modules. If you're using Chrome, Safari, or FireFox, it might show a warning, but you should still be able to log in, go to the Modules/Extend page, select some modules, and install them.

Are there any error messages when you try installing the modules, or can you not even get to the 'Extend' page at all?

I have done a lot of development work locally, and never have HTTPS/SSL enabled on the local environments.

**Comment by geerlingguy** [comment]
Ah, you might be trying to install modules via FTP/HTTP inside of the Drupal site; I have never tried doing that, and have no idea how that works. It still should work, but I'm not sure if there's something internally in Drupal that would block it if the site's not loading over https.

I rather install and update modules using either Drush (for Drupal 7 sites) or Composer (for Drupal 8 sites) in the codebase, and don't use Drupal's UI for it.

**Comment by webprogrammierer** [comment]
It ist not possible to install modules over the extend menu, it is not only a warning, it is an error and it prevents from installing modules!

I do not want to install modules in another way (ftp, composer, ...), I want to SOLVE this problem within the Drupal VM.

If you don't believe it, install Drupal locally and try to extend moduls, you will see the error and you will see, we NEED an solution.

Thank you.

**Comment by webprogrammierer** [comment]
How can I set the right access rights (permissions) in Ubuntu for the browser (in Windows 10!!!) to let the browser access all the files in /drupal8/sites directory ...

Something [like here](https://medium.com/@jangid.hitesh2112/error-you-are-not-using-an-encrypted-connection-so-your-password-will-be-sent-in-plain-text-b74599430b35), but it does not work in my Drupal VM environment.  Can somebody help?

**Comment by webprogrammierer** [comment]
I tried this so set the right permissions for the drupal 8 modules directory:

```
sudo chown -Rh $LOGNAME:www-data modules
sudo chmod -R 775 modules
```

But the sudo chown command does nothing! Nothing changes and there is no error on the sudo chown command. 

I am in the right (!) directory. With la -la I get the info for the modules dir:
drwxrwxrwx  1 vagrant vagrant      0 Feb 11 19:05 modules

After the 2 chown commands nothing has changed:
drwxrwxrwx  1 vagrant vagrant      0 Feb 11 19:05 modules

WHY does the chown command (with sudo) not work in the Durpal VM?
Is there any solution to get the chown command work?

**Comment by webprogrammierer** [comment]
Is the NTFS file system used in Drupal VM?  This could be the reason why chown is not working ....

But how can it be solved?

**Comment by webprogrammierer** [comment]
sudo df -Th shows:

```
Filesystem                   Type      Size  Used Avail Use% Mounted on
udev                         devtmpfs  968M     0  968M   0% /dev
tmpfs                        tmpfs     200M  576K  199M   1% /run
/dev/mapper/vagrant--vg-root ext4       78G  6.7G   67G  10% /
tmpfs                        tmpfs     997M     0  997M   0% /dev/shm
tmpfs                        tmpfs     5.0M     0  5.0M   0% /run/lock
tmpfs                        tmpfs     997M     0  997M   0% /sys/fs/cgroup
vagrant                      vboxsf    1.8T  206G  1.6T  12% /vagrant
var_www_drupal8              vboxsf    1.8T  206G  1.6T  12% /var/www/drupal8
var_www_drupalvm             vboxsf    1.8T  206G  1.6T  12% /var/www/drupalvm
tmpfs                        tmpfs     200M     0  200M   0% /run/user/900
```

So we don't have a ntfs but a vboxsf file system.

The question is how to set the right persmissions or how to add the right owner to the shared folders like /var/www/drupal8 in order to allow the windows browser (chrome) to have write access to the /modules folder.

Is this the right question?
If so is somebody here who can help to solve this?
Thank you.

**Comment by webprogrammierer** [comment]
We can not use any / some chown commands in Drupal VM and nobody cares?

**Comment by geerlingguy** [comment]
Note that it is very rare for people to use the module install functionality via the Drupal UI, and there are also proportionally fewer users on Windows than macOS or Linux, so this issue is not probably run into by many others.

**Comment by webprogrammierer** [comment]
I don't think you. Hundreds of Drupal users have this problem:

Search "You are not using an encrypted connection, so your password will be sent in plain text" with google.

**Comment by geerlingguy** [comment]
@webprogrammierer - If it's a more general Drupal problem, I'd search around and ask about it on Drupal Answers: https://drupal.stackexchange.com

**Comment by geerlingguy** [comment]
And in Drupal.org's forums: https://www.drupal.org/forum/support/installing-drupal/2010-10-28/module-install-new-module-both-methods-fail

Note that I've never used Drupal's UI to upload a module and do not plan to, so I can probably not offer much help here.

**Comment by webprogrammierer** [comment]
> And in Drupal.org's forums: https://www.drupal.org/forum/support/installing-drupal/2010-10-28/module-install-new-module-both-methods-fail
> 
> Note that I've never used Drupal's UI to upload a module and do not plan to, so I can probably not offer much help here.

The solution there is the chown command:
sudo chown www-data:www-data -R /var/www/drupal8

BUT the chown command can not be used in Drupal VM as discussed above. There are a lot of solutions, but all of them use the chown command.

That's why we need a solution for the chown command in Drupal VM.

Please read this posting above:


> sudo df -Th shows:
> 
> ```
> Filesystem                   Type      Size  Used Avail Use% Mounted on
> udev                         devtmpfs  968M     0  968M   0% /dev
> tmpfs                        tmpfs     200M  576K  199M   1% /run
> /dev/mapper/vagrant--vg-root ext4       78G  6.7G   67G  10% /
> tmpfs                        tmpfs     997M     0  997M   0% /dev/shm
> tmpfs                        tmpfs     5.0M     0  5.0M   0% /run/lock
> tmpfs                        tmpfs     997M     0  997M   0% /sys/fs/cgroup
> vagrant                      vboxsf    1.8T  206G  1.6T  12% /vagrant
> var_www_drupal8              vboxsf    1.8T  206G  1.6T  12% /var/www/drupal8
> var_www_drupalvm             vboxsf    1.8T  206G  1.6T  12% /var/www/drupalvm
> tmpfs                        tmpfs     200M     0  200M   0% /run/user/900
> ```
> 
> So we don't have a ntfs but a vboxsf file system.
> 
> The question is how to set the right persmissions or how to add the right owner to the shared folders like /var/www/drupal8 in order to allow the windows browser (chrome) to have write access to the /modules folder.
> 
> Is this the right question?
> If so is somebody here who can help to solve this?
> Thank you.


How wen can use a chown command in Drupal VM or similar sulution?

**Comment by webprogrammierer** [comment]
This is a dirty solution:

In   core/modules/system.module 
add this code to function system_filetransfer_info()

```
  $backends['lcoal'] = [
    'title' => t('Local'),
    'class' => 'Drupal\Core\FileTransfer\Local',
    'weight' => -10,
  ];
```

The result is, that we can install modules with "local" method.

If somebody finds a better solution please post it here.
