### ISSUE TITLE
DrupalVM 5.1.1 SOLR 6.6.6 does not start

### ISSUE THREAD

**Issue by lexsoft00** [geerlingguy/drupal-vm#2016]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.7
DrupalVM 5.1.1
# Latest version of the pre-provisioned box
vagrant_box: geerlingguy/drupal-vm
# Solr Configuration
solr_version: "6.6.6"
solr_xms: "256M"
solr_xmx: "512M"
```

### Your OS
- **Windows** (version)

### Full console output
https://gist.github.com/lexsoft00/1074a8fe7bf17c9d6749ee4916125ab5

### Summary
I get an error when I'm trying to install DrupalVM with SOLR 6.6.6 also MySQL gets a flag with `no_log: true` option. I've added 'ignore_errors: true' to bypass that.

**Comment by geerlingguy** [comment]
It looks like this is the problem:

> Please install latest version of Java 1.8 or set JAVA_HOME properly.

You need to make sure you have Java 8.x available on your VM, so you might need to set:

```yaml
java_packages:
  - openjdk-8-jdk
```

In your `config.yml` file, and re-provision the instance.

**Comment by lexsoft00** [comment]
Thank you,
I have changed to 7.7.2 and it seems to install fine.

I have a different issue now that I passed the SOLR task. The dashboard task fails:
`fatal: [drupalvm93]: FAILED! => {"changed": false, "msg": "AnsibleError: Unexpected templating type error occurred on (<!DOCTYPE html>\r\n  <head>\r\n    <title>Drupal VM<`

**Full console output**
https://gist.github.com/lexsoft00/90b38369bb799b06497008ba7b3d20b8

**Comment by lexsoft00** [comment]
Have reinstalled it with just the default.config with no extras and it installed without any issues. 

It might be related to some extras, I will conduct some more tests to see if I can find the reason for the above issue.

**Comment by lexsoft00** [comment]
For some weird reason it works now.

I've installed under a new name and IP address with only the default settings first and after I've added all the changes to the config file and provision again. It works great.

**Comment by geerlingguy** [comment]
Great! Glad you could get it worked out.
