### ISSUE TITLE
Solr is not able setup with default config settins.

### ISSUE THREAD

**Issue by shamsher327** [geerlingguy/drupal-vm#2021]
### Issue Type

 - Bug Report / Support Request
 - Feature Idea
 - Documentation Report

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

**Comment by shamsher327** [comment]
Hi @geerlingguy,

I am continuously facing issues while setup apache solr with default durpalvm settings. I have followed complete steups but still not able to run properly. Could you please help or suggest me any steps to fix it.


![image](https://user-images.githubusercontent.com/7940616/76159027-53ce8280-6142-11ea-9ab2-d9ed0059fea1.png)

**Comment by shamsher327** [comment]
@geerlingguy i appreciate it if you help on the same.

**Comment by geerlingguy** [comment]
Yeah, it definitely needs to be updated in `default.config.yml`. It should be on a 7.x version at least.

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/drupal-vm/issues/2017#issuecomment-594431881

**Comment by geerlingguy** [comment]
Also related: https://github.com/geerlingguy/drupal-vm/issues/1960

**Comment by geerlingguy** [comment]
Closing and directing attention to #1960
