### ISSUE TITLE
SSL handshaking

### ISSUE THREAD

**Issue by lexsoft00** [geerlingguy/drupal-vm#2023]
### Issue Type 

 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.7
```

### Your OS

 - **Windows** (version)

### Full console output
`2020/03/12 14:19:06 [info] 28762#28762: *54 SSL_do_handshake() failed (SSL: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown:SSL alert number 46) while SSL handshaking, client: 192.168.96.1, server: 0.0.0.0:443`

### Summary

I have self-sign certificate done with:
`openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout commerce.key -out commerce.crt`
 I keep getting this error on Nginx error logs.

The setup for nginx is the following:
```
nginx_hosts:
 - server_name: "local.commerce-web.local"
    root: "/var/www/commerce-web/web"
    is_php: true
    extra_parameters: |
        listen 443 ssl;
        ssl_certificate     /home/vagrant/commerce-web.crt;
        ssl_certificate_key /home/vagrant/commerce-web.key;
        ssl_protocols        SSLv3 TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
        ssl_prefer_server_ciphers on;
        ssl_verify_client off;
        ssl_session_cache    shared:SSL:10m;
        ssl_session_timeout  30m;
        proxy_ssl_server_name on;
        proxy_ssl_session_reuse off;
        proxy_buffering on;
        fastcgi_buffers 8 16k;
        fastcgi_buffer_size 32k;
        fastcgi_connect_timeout 300;
        fastcgi_send_timeout 300;
        fastcgi_read_timeout 300; 

```

**Comment by pminf** [comment]
I'm expieriencing a similiar issue (not sure if is related to yours). Installation of xdebug fails:
```
Failure downloading https://xdebug.org/files/xdebug-2.9.0.tgz, Request failed: <urlopen error [SSL_ALERT_HANDSHAKE_FAILURE] sslv3 handshake failure (_ssl.c:720)
```
