### ISSUE TITLE
Provide MariaDB 10.4 out-of-the-box via config.yml

### ISSUE THREAD

**Issue by dercheffe** [geerlingguy/drupal-vm#2027]
### Issue Type

 - Feature Idea

### Your Environment

```
VirtualBox 6.1.4r136177
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/philipp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 9.2.1 20191008]
```

### Your OS

 - **Linux** (Ubuntu 19.10)

### Summary
Per default Ubuntu 18.04 provides only MariaDB 10.1 out of the box.

There should be a configuration option in config.yml to get MariaDB 10.4 also for Ubuntu 18.4

[https://downloads.mariadb.org/mariadb/repositories/#distro=Ubuntu&distro_release=bionic--ubuntu_bionic&mirror=one&version=10.4](https://downloads.mariadb.org/mariadb/repositories/#distro=Ubuntu&distro_release=bionic--ubuntu_bionic&mirror=one&version=10.4)

Perhaps its even possible to add additional Ubuntu (or other Linux distro) PPA's to get newer packages in general.

**Comment by geerlingguy** [comment]
This is a good suggestion, though it's something that I would recommend inquiring about over on the role issue queue: https://github.com/geerlingguy/ansible-role-mysql/issues

Note that MariaDB 10.3 and later may have issues out of the box with the configuration provided by the role; see https://github.com/geerlingguy/ansible-role-mysql/issues/272
