### ISSUE TITLE
Weird issue "Unmet dependency with apache2-mpm-prefork" expecting trusty5, but using trusty1

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#203]
Downloaded drupalvm to a new Macbook. Upon vagrant up, I kept getting an error about a version mismatch in the apache2 version being installed and the one it is told to use. I have only changed the VM memory limit in the config.yml. I also deleted the machine and tried from scratch, this error is hit consistently. Vagrant 1.7.4, VirtualBox 4.30.x

**Comment by geerlingguy** [comment]
@kevinquillen - Sounds strange... can you paste the actual error message here? Also, could you update to VirtualBox 5.x and then do a `vagrant box update` to make sure you're on the latest box version too?

**Comment by scott82anderson** [comment]
I'm getting the same error. http://i.imgur.com/xc4hZuf.png

Vagrant 1.7.4
Virtual Box 5.0.1
Host: Win 10

I have other Vagrant machines running ok.

**Comment by zrpnr** [comment]
Here's more detail on the error message:

```
TASK: [geerlingguy.apache | Ensure Apache is installed.] **********************
failed: [dvm] => (item=apache2,apache2-mpm-prefork,apache2-utils) => {"failed": true, "item": "apache2,apache2-mpm-prefork,apache2-utils"}
stderr: E: Unable to correct problems, you have held broken packages.

stdout: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 apache2-mpm-prefork : Depends: apache2 (= 2.4.12-1+deb.sury.org~trusty+5) but 2.4.16-3+deb.sury.org~trusty+1 is to be installed

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'apache2' 'apache2-mpm-prefork' 'apache2-utils'' failed: E: Unable to correct problems, you have held broken packages.
```

**Comment by rmcleay** [comment]
I can confirm that I can also reproduce that problem with the same message as @zrpnr. I'm running: 

- Debian Jessie 
- Vagrant 1.7.2 
- VirtualBox 4.3.18_Debianr96516. 

Currently running head of master for drupal-vm (c3baf7e).

**Comment by kevinquillen** [comment]
That's the error.

**Comment by a-hjelm** [comment]
Throwing the same error.

* Ubuntu 14.04 LTS 
* Vagrant 1.7.4
* VirtualBox 5.0.2 r102096

**Comment by afbrogneaux** [comment]
Same problem here. It appears yesterday, around 4 PM CET, with VirtualBox 4.3.30 on Windows 8.1, box version 1.0.4. Before that, I had no problem. 

I did a `vagrant box update` so I now use version 1.0.5 and the problem still remains.

**Comment by andreiashu** [comment]
same issue here. Started showing up today

**Comment by afbrogneaux** [comment]
I updated to VirtualBox 5.0.2, same issue with exactly the same messages as @scott82anderson and @a-hjelm during provisioning. 
* Windows 8.1
* VirtualBox 5.0.2 r102096
* Vagrant 1.7.4
* Box 1.0.5

**Comment by davidlukac** [comment]
Same issue here - appeared to two members of the team, one on fresh install, one on re-build. First occurrence yesterday.

/cc @Kolin @miromichalicka

**Comment by geerlingguy** [comment]
Yikes! This sounds like an Ubuntu packaging problem. I'm going to do some more digging and see if there's a workaround, since it sounds like it's happening to pretty much everyone all the sudden.

**Comment by geerlingguy** [comment]
It looks like it may be related to a change in Ondřej's PHP 5.5 repository for Ubuntu 14.04.

@davidlukac, @afbrogneaux, @andreiashu, @a-hjelm, @rmcleay, @zrpnr, @scott82anderson, @kevinquillen - Thanks for reporting this and providing the extra detail. Can one (or all) of you check out this PR: #205 —it only uses the Ondřej repo if PHP 5.6+ is installed, and could be a good workaround in general, since Ubuntu 14.04 includes PHP 5.5.x support out of the box (granted, not the bleeding-edge version).

**Comment by geerlingguy** [comment]
See upstream issue: https://github.com/oerdnj/deb.sury.org/issues/101

**Comment by afbrogneaux** [comment]
It doesn't work for me, still same error. 

In fact, in my config.yml file (copied from example.config.yml), it's already php 5.6 : `php_version: "5.6"`

**Comment by andreiashu** [comment]
I'm on php 5.6 as well. So I wonder whether this happens only for PHP 5.6 instances

**Comment by sgrichards** [comment]
Tested PR #205 and that works for me with the config below:

`php_version: "5.5"`
`vagrant_box: geerlingguy/ubuntu1404`

The logic is that the Onřej repo only kicks in if your using 5.6 so given that the issue is with the upstream repo provision only works with the above config i believe.

**Comment by geerlingguy** [comment]
Current workaround: if you're using Ubuntu (which is the default OS/box), add the following to `config.yml`:

```yaml
apache_packages:
  - apache2
  - apache2-utils
```

**Comment by benkoren** [comment]
Thank you for posting this workaround. I've confirmed that it works under the following environment:
 - OS X 10.10.4
 - VirtualBox 4.3.30
 - Vagrant 1.6.5
 - Drupal-VM c3baf7e

**Comment by geerlingguy** [comment]
@benkoren (et all) — I just added a fix upstream in the `geerlingguy.apache` role. It no longer installs `-prefork` by default, and the PHP installation on Ubuntu automatically uses the proper packages, so this is no longer an issue (and never was on CentOS, go figure...).

To update the version of the role to the latest, please run `sudo ansible-galaxy install --force geerlingguy.apache` (on your host, if Ansible is installed there, otherwise, run it inside the VM).

**Comment by danharper83** [comment]
I seem to be getting this error after updating to current master version, I've tried all of the above steps but it still won't provision.

I'm using the default geerlingguy/ubuntu1604

I've ssh'd in and tried to manually install apache2-bin aand get the following message
```
The following packages have unmet dependencies:
 apache2-bin : Depends: libaprutil1-dbd-sqlite3 but it is not going to be installed or
                        libaprutil1-dbd-mysql but it is not going to be installed or
                        libaprutil1-dbd-odbc but it is not going to be installed or
                        libaprutil1-dbd-pgsql but it is not going to be installed or
                        libaprutil1-dbd-freetds but it is not installable
               Depends: libaprutil1-ldap but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by geerlingguy** [comment]
@danharper83 - Are you on the latest version of Drupal VM? If the install fails inside the VM too (when run manually), it seems like it might be an apt/packaging/cache issue.

**Comment by danharper83** [comment]
Yeah I'm on the latest version, I'm just running off the Master branch.

When I run `sudo apt-get update` I do get a few 404's while it's processing.

**Comment by geerlingguy** [comment]
Strange. After the apt-get update, does the install work?

**Comment by danharper83** [comment]
still never installs, I'm just going to setup a new version of it and double check the sources list.

**Comment by geerlingguy** [comment]
@danharper83 - Okay. And if you can get a set of replicable steps, please feel free to open a new issue and we can see what's going on there.
