### ISSUE TITLE
Docker: Ports are not available: listen tcp 0.0.0.0:3306

### ISSUE THREAD

**Issue by web-assistant** [geerlingguy/drupal-vm#2031]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Docker

### Your OS

 - **Windows** 10

### Full console output

PS C:\Web Assistant\docker\drupal> docker-compose up -d
Creating network "drupal_drupalvm" with driver "bridge"
Pulling drupal-vm (geerlingguy/drupal-vm:)...
latest: Pulling from geerlingguy/drupal-vm
c0c53f743a40: Pull complete                                                                                             89a5820f964c: Pull complete                                                                                             d75d6776e5de: Pull complete                                                                                             33fad86ddb08: Pull complete                                                                                             91af1f51d8d4: Pull complete                                                                                             0d799ba432a5: Pull complete                                                                                             d082413417c6: Pull complete                                                                                             b56dea51d11a: Pull complete                                                                                             58bf17d29add: Pull complete                                                                                             0a3512a5f458: Pull complete                                                                                             541a27e67610: Pull complete                                                                                             8f796b6baf85: Pull complete                                                                                             Digest: sha256:e1d37f71739121f86e63dcadd9ee66eac94ba1b9b407517908ad3a572d1e3f2e
Status: Downloaded newer image for geerlingguy/drupal-vm:latest
Creating drupal-vm ... error                                                                                            
ERROR: for drupal-vm  Cannot start service drupal-vm: Ports are not available: listen tcp 0.0.0.0:3306: bind: An attempt was made to access a socket in a way forbidden by its access permissions.

ERROR: for drupal-vm  Cannot start service drupal-vm: Ports are not available: listen tcp 0.0.0.0:3306: bind: An attempt was made to access a socket in a way forbidden by its access permissions.
ERROR: Encountered errors while bringing up the project.

### Summary

I'm trying to get Drupal VM using Docker to work. I get the error above. Any ideas?

**Comment by geerlingguy** [comment]
You're likely running into something related to https://github.com/docker/for-win/issues/3171 — you can also run `netstat -aon | findstr :3306` to see if something else is using that port already.

The easiest fix is to edit your `docker-compose.yml` file and remove that port entirely (if you don't need to connect to MySQL from your PC at all), or change it to a higher/different port.

**Comment by web-assistant** [comment]
I'm closing as this is probably related to my computer. I've also got dev sites up and running using Lando now (via your Getting Started with Lando blog page). Thanks for all your help/work.

**Comment by geerlingguy** [comment]
No problem!

**Comment by iamAmirrezaSaki** [comment]
I had change the /etc/resolve.conf from the linux VM to `nameserver 8.8.8.8` and it works. @web-assistant
