### ISSUE TITLE
'chgrp failed' on task "Ensure the default pool directory exists."

### ISSUE THREAD

**Issue by Knepini** [geerlingguy/drupal-vm#2032]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 6.0.18r136238
-bash: ansible: command not found
```

### Your OS

 - **macOS** (Mojave 10.14.6)

### Full console output

Kevins-MBP:navair kevin******$ vagrant up
Bringing machine 'navair' up with 'virtualbox' provider...
==> navair: Preparing master VM for linked clones...
    navair: This is a one time operation. Once the master VM is prepared,
    navair: it will be used as a base for linked clones, making the creation
    navair: of new VMs take milliseconds on a modern system.
==> navair: Importing base box 'geerlingguy/ubuntu1604'...
==> navair: Cloning VM...
==> navair: Matching MAC address for NAT networking...
==> navair: Checking if box 'geerlingguy/ubuntu1604' version '1.3.3' is up to date...
==> navair: Setting the name of the VM: local.navair.com
==> navair: Pruning invalid NFS exports. Administrator privileges will be required...
Enter PIN for 'Certificate For PIV Authentication (NEPINI.KEVIN.J.1247050791)': 
==> navair: Clearing any previously set network interfaces...
==> navair: Preparing network interfaces based on configuration...
    navair: Adapter 1: nat
    navair: Adapter 2: hostonly
==> navair: Forwarding ports...
    navair: 22 (guest) => 2222 (host) (adapter 1)
==> navair: Running 'pre-boot' VM customizations...
==> navair: Booting VM...
==> navair: Waiting for machine to boot. This may take a few minutes...
    navair: SSH address: 127.0.0.1:2222
    navair: SSH username: vagrant
    navair: SSH auth method: private key
==> navair: Machine booted and ready!
GuestAdditions are newer than your host but, downgrades are disabled. Skipping.
==> navair: Checking for guest additions in VM...
    navair: The guest additions on this VM do not match the installed version of
    navair: VirtualBox! In most cases this is fine, but in rare cases it can
    navair: prevent things such as shared folders from working properly. If you see
    navair: shared folder errors, please make sure the guest additions within the
    navair: virtual machine match the version of VirtualBox you have installed on
    navair: your host and reload your VM.
    navair: 
    navair: Guest Additions Version: 6.1.4
    navair: VirtualBox Version: 6.0
==> navair: [vagrant-hostsupdater] Checking for host entries
==> navair: [vagrant-hostsupdater]   found entry for: 192.168.88.115 local.navair.com
==> navair: [vagrant-hostsupdater]   found entry for: 192.168.88.115 www.local.navair.com
==> navair: [vagrant-hostsupdater]   found entry for: 192.168.88.115 dashboard.local.navair.com
==> navair: [vagrant-hostsupdater]   found entry for: 192.168.88.115 www.dashboard.local.navair.com
==> navair: Setting hostname...
==> navair: Configuring and enabling network interfaces...
==> navair: Exporting NFS shared folders...
==> navair: Preparing to edit /etc/exports. Administrator privileges will be required...
==> navair: Mounting NFS shared folders...
==> navair: Running provisioner: drupalvm (ansible_local)...
    navair: Installing Ansible...
    navair: Installing pip... (for Ansible installation)
    navair: Running ansible-playbook...

PLAY [all] *********************************************************************

TASK [Gathering Facts] *********************************************************
[DEPRECATION WARNING]: Distribution Ubuntu 16.04 on host navair should use 
/usr/bin/python3, but is using /usr/bin/python for backward compatibility with 
prior Ansible releases. A future Ansible release will default to using the 
discovered platform python for this host. See https://docs.ansible.com/ansible/
2.9/reference_appendices/interpreter_discovery.html for more information. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
ok: [navair]

TASK [include_tasks] ***********************************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/tasks/config.yml for navair

TASK [Include OS-specific variables.] ******************************************
ok: [navair]

TASK [Define config_dir.] ******************************************************
skipping: [navair]

TASK [Include optional configuration files.] ***********************************
ok: [navair] => (item=/vagrant/box/config.yml)

TASK [include_tasks] ***********************************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/tasks/backwards-compatibility.yml for navair

TASK [nginx_hosts shim] ********************************************************
ok: [navair]

TASK [include_tasks] ***********************************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/tasks/init-Debian.yml for navair

TASK [Update apt cache if needed.] *********************************************
ok: [navair]

TASK [Install required dependencies.] ******************************************
changed: [navair]

TASK [Add repository for Apache 2.4.9+ (Ubuntu 12/14).] ************************
skipping: [navair]

TASK [Define php_xhprof_html_dir.] *********************************************
skipping: [navair]

TASK [Run configured pre-provision shell scripts.] *****************************

TASK [Run configured pre-provision ansible task files.] ************************

TASK [Set the PHP webserver daemon correctly when nginx is in use.] ************
skipping: [navair]

TASK [Ensure PHP version-specific workspace directory exists.] *****************
changed: [navair]

TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
skipping: [navair]

TASK [geerlingguy.repo-remi : Import remi GPG key.] ****************************
skipping: [navair]

TASK [drupalvm.hostname : Configure /etc/mailname (Debian).] *******************
ok: [navair]

TASK [drupalvm.hostname : Add hostname to /etc/hosts.] *************************
changed: [navair]

TASK [drupalvm.hostname : Configure hostname.] *********************************
ok: [navair]

TASK [drupalvm.hostname : Set the hostname for current session.] ***************
skipping: [navair]

TASK [geerlingguy.firewall : Ensure iptables is present.] **********************
ok: [navair]

TASK [geerlingguy.firewall : Flush iptables the first time playbook runs.] *****
changed: [navair]

TASK [geerlingguy.firewall : Copy firewall script into place.] *****************
changed: [navair]

TASK [geerlingguy.firewall : Copy firewall init script into place.] ************
skipping: [navair]

TASK [geerlingguy.firewall : Copy firewall systemd unit file into place (for systemd systems).] ***
changed: [navair]

TASK [geerlingguy.firewall : Configure the firewall service.] ******************
changed: [navair]

TASK [geerlingguy.firewall : Check if firewalld package is installed (on RHEL).] ***
skipping: [navair]

TASK [geerlingguy.firewall : Disable the firewalld service (on RHEL, if configured).] ***
skipping: [navair]

TASK [geerlingguy.firewall : Check if ufw package is installed (on Ubuntu).] ***
ok: [navair]

TASK [geerlingguy.firewall : Disable the ufw firewall (on Ubuntu, if configured).] ***
changed: [navair]

TASK [geerlingguy.firewall : Check if ufw package is installed (on Archlinux).] ***
skipping: [navair]

TASK [geerlingguy.firewall : Disable the ufw firewall (on Archlinux, if configured).] ***
skipping: [navair]

TASK [geerlingguy.git : Ensure git is installed (RedHat).] *********************
skipping: [navair]

TASK [geerlingguy.git : Update apt cache (Debian).] ****************************
ok: [navair]

TASK [geerlingguy.git : Ensure git is installed (Debian).] *********************
changed: [navair]

TASK [geerlingguy.git : Include OS-specific variables (RedHat).] ***************
skipping: [navair]

TASK [geerlingguy.git : Include OS-specific variables (Fedora).] ***************
skipping: [navair]

TASK [geerlingguy.git : Include OS-specific variables (Debian).] ***************
skipping: [navair]

TASK [geerlingguy.git : Define git_install_from_source_dependencies.] **********
skipping: [navair]

TASK [geerlingguy.git : Ensure git's dependencies are installed (RedHat).] *****
skipping: [navair]

TASK [geerlingguy.git : Ensure git's dependencies are installed (Debian).] *****
skipping: [navair]

TASK [geerlingguy.git : Get installed version.] ********************************
skipping: [navair]

TASK [geerlingguy.git : Force git install if the version numbers do not match.] ***
skipping: [navair]

TASK [geerlingguy.git : Download git.] *****************************************
skipping: [navair]

TASK [geerlingguy.git : Expand git archive.] ***********************************
skipping: [navair]

TASK [geerlingguy.git : Build git.] ********************************************
skipping: [navair] => (item=all) 
skipping: [navair] => (item=install) 

TASK [geerlingguy.postfix : Ensure postfix is installed.] **********************
changed: [navair]

TASK [geerlingguy.postfix : Update Postfix configuration.] *********************
changed: [navair] => (item={u'name': u'inet_interfaces', u'value': u'localhost'})
ok: [navair] => (item={u'name': u'inet_protocols', u'value': u'all'})

TASK [geerlingguy.postfix : Ensure postfix is started and enabled at boot.] ****
ok: [navair]

TASK [geerlingguy.apache : Include OS-specific variables.] *********************
ok: [navair]

TASK [geerlingguy.apache : Include variables for Amazon Linux.] ****************
skipping: [navair]

TASK [geerlingguy.apache : Define apache_packages.] ****************************
ok: [navair]

TASK [geerlingguy.apache : include_tasks] **************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.apache/tasks/setup-Debian.yml for navair

TASK [geerlingguy.apache : Update apt cache.] **********************************
ok: [navair]

TASK [geerlingguy.apache : Ensure Apache is installed on Debian.] **************
changed: [navair]

TASK [geerlingguy.apache : Get installed version of Apache.] *******************
ok: [navair]

TASK [geerlingguy.apache : Create apache_version variable.] ********************
ok: [navair]

TASK [geerlingguy.apache : Include Apache 2.2 variables.] **********************
skipping: [navair]

TASK [geerlingguy.apache : Include Apache 2.4 variables.] **********************
ok: [navair]

TASK [geerlingguy.apache : Configure Apache.] **********************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.apache/tasks/configure-Debian.yml for navair

TASK [geerlingguy.apache : Configure Apache.] **********************************
ok: [navair] => (item={u'regexp': u'^Listen ', u'line': u'Listen 80'})

TASK [geerlingguy.apache : Enable Apache mods.] ********************************
changed: [navair] => (item=expires.load)
changed: [navair] => (item=headers.load)
changed: [navair] => (item=ssl.load)
changed: [navair] => (item=rewrite.load)
changed: [navair] => (item=proxy.load)
changed: [navair] => (item=proxy_fcgi.load)

TASK [geerlingguy.apache : Disable Apache mods.] *******************************

TASK [geerlingguy.apache : Check whether certificates defined in vhosts exist.] ***

TASK [geerlingguy.apache : Add apache vhosts configuration.] *******************
changed: [navair]

TASK [geerlingguy.apache : Add vhost symlink in sites-enabled.] ****************
changed: [navair]

TASK [geerlingguy.apache : Remove default vhost in sites-enabled.] *************
changed: [navair]

TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
ok: [navair]

TASK [geerlingguy.apache : Include OS-specific variables.] *********************
ok: [navair]

TASK [geerlingguy.apache : Include variables for Amazon Linux.] ****************
skipping: [navair]

TASK [geerlingguy.apache : Define apache_packages.] ****************************
skipping: [navair]

TASK [geerlingguy.apache : include_tasks] **************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.apache/tasks/setup-Debian.yml for navair

TASK [geerlingguy.apache : Update apt cache.] **********************************
ok: [navair]

TASK [geerlingguy.apache : Ensure Apache is installed on Debian.] **************
ok: [navair]

TASK [geerlingguy.apache : Get installed version of Apache.] *******************
ok: [navair]

TASK [geerlingguy.apache : Create apache_version variable.] ********************
ok: [navair]

TASK [geerlingguy.apache : Include Apache 2.2 variables.] **********************
skipping: [navair]

TASK [geerlingguy.apache : Include Apache 2.4 variables.] **********************
ok: [navair]

TASK [geerlingguy.apache : Configure Apache.] **********************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.apache/tasks/configure-Debian.yml for navair

TASK [geerlingguy.apache : Configure Apache.] **********************************
ok: [navair] => (item={u'regexp': u'^Listen ', u'line': u'Listen 80'})

TASK [geerlingguy.apache : Enable Apache mods.] ********************************
ok: [navair] => (item=expires.load)
ok: [navair] => (item=headers.load)
ok: [navair] => (item=ssl.load)
ok: [navair] => (item=rewrite.load)
ok: [navair] => (item=proxy.load)
ok: [navair] => (item=proxy_fcgi.load)

TASK [geerlingguy.apache : Disable Apache mods.] *******************************

TASK [geerlingguy.apache : Check whether certificates defined in vhosts exist.] ***

TASK [geerlingguy.apache : Add apache vhosts configuration.] *******************
ok: [navair]

TASK [geerlingguy.apache : Add vhost symlink in sites-enabled.] ****************
ok: [navair]

TASK [geerlingguy.apache : Remove default vhost in sites-enabled.] *************
ok: [navair]

TASK [geerlingguy.apache : Ensure Apache has selected state and enabled on boot.] ***
ok: [navair]

TASK [geerlingguy.apache-php-fpm : Enable mod_proxy_fcgi.] *********************
ok: [navair] => (item=proxy.load)
ok: [navair] => (item=proxy_fcgi.load)

TASK [geerlingguy.nginx : Include OS-specific variables.] **********************
skipping: [navair]

TASK [geerlingguy.nginx : Define nginx_user.] **********************************
skipping: [navair]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [navair]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [navair]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [navair]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [navair]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [navair]

TASK [geerlingguy.nginx : include_tasks] ***************************************
skipping: [navair]

TASK [geerlingguy.nginx : Remove default nginx vhost config file (if configured).] ***
skipping: [navair]

TASK [geerlingguy.nginx : Ensure nginx_vhost_path exists.] *********************
skipping: [navair]

TASK [geerlingguy.nginx : Add managed vhost config files.] *********************
skipping: [navair] => (item={u'is_php': True, u'root': u'/var/www/navair/docroot', u'server_name': u'local.navair.com www.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/opt/adminer', u'server_name': u'adminer.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/usr/share/php/xhprof_html', u'server_name': u'xhprof.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/usr/share/php/pimpmylog', u'server_name': u'pimpmylog.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/var/www/dashboard', u'server_name': u'192.168.88.115 dashboard.local.navair.com'}) 

TASK [geerlingguy.nginx : Remove managed vhost config files.] ******************
skipping: [navair] => (item={u'is_php': True, u'root': u'/var/www/navair/docroot', u'server_name': u'local.navair.com www.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/opt/adminer', u'server_name': u'adminer.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/usr/share/php/xhprof_html', u'server_name': u'xhprof.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/usr/share/php/pimpmylog', u'server_name': u'pimpmylog.local.navair.com'}) 
skipping: [navair] => (item={u'is_php': True, u'root': u'/var/www/dashboard', u'server_name': u'192.168.88.115 dashboard.local.navair.com'}) 

TASK [geerlingguy.nginx : Remove legacy vhosts.conf file.] *********************
skipping: [navair]

TASK [geerlingguy.nginx : Copy nginx configuration in place.] ******************
skipping: [navair]

TASK [geerlingguy.nginx : Ensure nginx is started and enabled to start at boot.] ***
skipping: [navair]

TASK [geerlingguy.php-versions : Include OS-specific variables.] ***************
ok: [navair] => (item=/vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php-versions/vars/Debian.yml)
ok: [navair] => (item=/vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php-versions/vars/Debian-php7.2.yml)

TASK [geerlingguy.php-versions : Define PHP variables.] ************************
ok: [navair] => (item={'value': u'__php_extension_conf_paths', 'key': u'php_extension_conf_paths'})
ok: [navair] => (item={'value': u'__php_fpm_daemon', 'key': u'php_fpm_daemon'})
ok: [navair] => (item={'value': u'__php_uploadprogress_module_path', 'key': u'php_uploadprogress_module_path'})
ok: [navair] => (item={'value': u'__php_xhprof_module_path', 'key': u'php_xhprof_module_path'})
ok: [navair] => (item={'value': u'__php_fpm_pool_conf_path', 'key': u'php_fpm_pool_conf_path'})
ok: [navair] => (item={'value': u'__php_conf_paths', 'key': u'php_conf_paths'})
ok: [navair] => (item={'value': u'__php_xdebug_module_path', 'key': u'php_xdebug_module_path'})
ok: [navair] => (item={'value': u'__php_pgsql_package', 'key': u'php_pgsql_package'})
ok: [navair] => (item={'value': u'__php_packages', 'key': u'php_packages'})
ok: [navair] => (item={'value': u'__php_mysql_package', 'key': u'php_mysql_package'})
ok: [navair] => (item={'value': u'__php_memcached_package', 'key': u'php_memcached_package'})
ok: [navair] => (item={'value': u'__php_fpm_conf_path', 'key': u'php_fpm_conf_path'})
ok: [navair] => (item={'value': u'__php_tideways_module_path', 'key': u'php_tideways_module_path'})
ok: [navair] => (item={'value': u'__php_redis_package', 'key': u'php_redis_package'})

TASK [geerlingguy.php-versions : Define php_install_recommends variable.] ******
ok: [navair]

TASK [geerlingguy.php-versions : include_tasks] ********************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php-versions/tasks/setup-Debian.yml for navair

TASK [geerlingguy.php-versions : Set the correct opcache filename (Ubuntu/Debian).] ***
ok: [navair]

TASK [geerlingguy.php-versions : Add repository for PHP versions (Ubuntu).] ****
changed: [navair]

TASK [geerlingguy.php-versions : Add repository for PHP 5 compatibility packages (Ubuntu).] ***
skipping: [navair]

TASK [geerlingguy.php-versions : Add dependencies for PHP versions (Debian).] ***
skipping: [navair]

TASK [geerlingguy.php-versions : Add Ondrej Sury's apt key (Debian).] **********
skipping: [navair]

TASK [geerlingguy.php-versions : Add Ondrej Sury's repo (Debian).] *************
skipping: [navair]

TASK [geerlingguy.php-versions : Update apt caches after repo is added (Debian).] ***
skipping: [navair]

TASK [geerlingguy.php-versions : Purge PHP version packages.] ******************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['php5.6-common', 
'php7.0-common', 'php7.1-common', 'php7.2-common']` and remove the loop. This 
feature will be removed in version 2.11. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
ok: [navair] => (item=[u'php5.6-common', u'php7.0-common', u'php7.1-common'])

TASK [geerlingguy.php-versions : Set the correct XHProf package when PHP 5.6 is used.] ***
skipping: [navair]

TASK [geerlingguy.php : Include OS-specific variables.] ************************
ok: [navair]

TASK [geerlingguy.php : Define php_packages.] **********************************
skipping: [navair]

TASK [geerlingguy.php : Define extra php_packages.] ****************************
ok: [navair]

TASK [geerlingguy.php : Define php_webserver_daemon.] **************************
ok: [navair]

TASK [geerlingguy.php : Define php_conf_paths.] ********************************
skipping: [navair]

TASK [geerlingguy.php : Define php_extension_conf_paths.] **********************
skipping: [navair]

TASK [geerlingguy.php : Define php_apc_conf_filename.] *************************
ok: [navair]

TASK [geerlingguy.php : Define php_opcache_conf_filename (Ubuntu 16.04).] ******
skipping: [navair]

TASK [geerlingguy.php : Define php_opcache_conf_filename.] *********************
skipping: [navair]

TASK [geerlingguy.php : Define php_fpm_conf_path.] *****************************
skipping: [navair]

TASK [geerlingguy.php : include_tasks] *****************************************
skipping: [navair]

TASK [geerlingguy.php : include_tasks] *****************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php/tasks/setup-Debian.yml for navair

TASK [geerlingguy.php : Update apt cache.] *************************************
ok: [navair]

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
changed: [navair]

TASK [geerlingguy.php : Delete APCu configuration file if this role will provide one.] ***
changed: [navair] => (item=/etc/php/7.2/fpm/conf.d)
ok: [navair] => (item=/etc/php/7.2/apache2/conf.d)
changed: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : Delete OpCache configuration file if this role will provide one.] ***
changed: [navair] => (item=/etc/php/7.2/fpm/conf.d)
ok: [navair] => (item=/etc/php/7.2/apache2/conf.d)
changed: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : include_tasks] *****************************************
skipping: [navair]

TASK [geerlingguy.php : include_tasks] *****************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php/tasks/configure.yml for navair

TASK [geerlingguy.php : Ensure configuration directories exist.] ***************
ok: [navair] => (item=/etc/php/7.2/fpm)
changed: [navair] => (item=/etc/php/7.2/apache2)
ok: [navair] => (item=/etc/php/7.2/cli)
ok: [navair] => (item=/etc/php/7.2/fpm/conf.d)
changed: [navair] => (item=/etc/php/7.2/apache2/conf.d)
ok: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : Place PHP configuration file in place.] ****************
changed: [navair] => (item=/etc/php/7.2/fpm)
changed: [navair] => (item=/etc/php/7.2/apache2)
changed: [navair] => (item=/etc/php/7.2/cli)

TASK [geerlingguy.php : include_tasks] *****************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php/tasks/configure-apcu.yml for navair

TASK [geerlingguy.php : Check for existing APCu config files.] *****************
ok: [navair] => (item=/etc/php/7.2/fpm/conf.d)
ok: [navair] => (item=/etc/php/7.2/apache2/conf.d)
ok: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : Remove any non-role-supplied APCu config files.] *******

TASK [geerlingguy.php : Ensure APCu config file is present.] *******************
changed: [navair] => (item=/etc/php/7.2/fpm/conf.d)
changed: [navair] => (item=/etc/php/7.2/apache2/conf.d)
changed: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : Remove APCu config file if APC is disabled.] ***********
skipping: [navair] => (item=/etc/php/7.2/fpm/conf.d) 
skipping: [navair] => (item=/etc/php/7.2/apache2/conf.d) 
skipping: [navair] => (item=/etc/php/7.2/cli/conf.d) 

TASK [geerlingguy.php : include_tasks] *****************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php/tasks/configure-opcache.yml for navair

TASK [geerlingguy.php : Check for existing OpCache config files.] **************
ok: [navair] => (item=/etc/php/7.2/fpm/conf.d)
ok: [navair] => (item=/etc/php/7.2/apache2/conf.d)
ok: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : Remove any non-role-supplied OpCache config files.] ****

TASK [geerlingguy.php : Ensure OpCache config file is present.] ****************
[DEPRECATION WARNING]: evaluating u'php_opcache_enable' as a bare variable, 
this behaviour will go away and you might need to add |bool to the expression 
in the future. Also see CONDITIONAL_BARE_VARS configuration toggle. This 
feature will be removed in version 2.12. Deprecation warnings can be disabled 
by setting deprecation_warnings=False in ansible.cfg.
changed: [navair] => (item=/etc/php/7.2/fpm/conf.d)
changed: [navair] => (item=/etc/php/7.2/apache2/conf.d)
changed: [navair] => (item=/etc/php/7.2/cli/conf.d)

TASK [geerlingguy.php : Remove OpCache config file if OpCache is disabled.] ****
skipping: [navair] => (item=/etc/php/7.2/fpm/conf.d) 
skipping: [navair] => (item=/etc/php/7.2/apache2/conf.d) 
skipping: [navair] => (item=/etc/php/7.2/cli/conf.d) 

TASK [geerlingguy.php : include_tasks] *****************************************
included: /vagrant/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.php/tasks/configure-fpm.yml for navair

TASK [geerlingguy.php : Define php_fpm_daemon.] ********************************
skipping: [navair]

TASK [geerlingguy.php : Define php_fpm_pool_conf_path.] ************************
skipping: [navair]

TASK [geerlingguy.php : Define php_fpm_pool_user.] *****************************
ok: [navair]

TASK [geerlingguy.php : Define php_fpm_pool_group.] ****************************
ok: [navair]

TASK [geerlingguy.php : Stat php_fpm_pool_conf_path] ***************************
ok: [navair]

TASK [geerlingguy.php : Ensure the default pool directory exists.] *************
fatal: [navair]: FAILED! => {"changed": false, "gid": 20, "group": "dialout", "mode": "0755", "msg": "chgrp failed", "owner": "501", "path": "{{ php_fpm_conf_path }}", "size": 64, "state": "directory", "uid": 501}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.postfix : restart postfix] ************************

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

PLAY RECAP *********************************************************************
navair                     : ok=84   changed=24   unreachable=0    failed=1    skipped=70   rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

### Summary

I am trying to migrate to a new Mac. The current configuration works on my old MacBook (High Sierra 10.13.6), but I am getting this error on the new Mac.

**Comment by geerlingguy** [comment]
Just a couple quick notes:

  - VirtualBox Version: 6.0 — 6.1.x is the latest version, that may help (probably not but worth upgrading)
  - It seems you're on an older version of Drupal VM (and using ubuntu 16.04); it might be best if you upgrade to a newer version of Drupal VM as this issue may already be resolved in the later 5.x series.

**Comment by Knepini** [comment]
Drupal VM 5.2.0
Vagrant 2.2.7
VirtualBox 6.1.4r136177
Ubuntu 18.04.4

Seems to have resolved the issue. Thanks!
