### ISSUE TITLE
User can only log in sporadically at the site when running on DrupalVM/session cookie is set sporadically.

### ISSUE THREAD

**Issue by dercheffe** [geerlingguy/drupal-vm#2033]
### Issue Type

 - Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 6.1.4r136177
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/philipp/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Nov  7 2019, 10:07:09) [GCC 9.2.1 20191008]

```

### Your OS

 - **Linux** (Ubuntu 19.10)

### Full console output
No console output

### Summary

At one of my Drupal sites a user can only login sporadically because the session cookie is not always set. Watchdog says session is opened, but my browser (tested it under Firefox and Chromium in Ubuntu) can't remember the session id because of a missing session cookie.

When I try to log in with different user accounts behind each other then sometimes it works. Then the session cookie persists until user logs out.

I have no imagination where there could be the needle in the haystack. I guess it has something to do with setting a adequate session cookie.

In production environment the same site works as it should.

No console output or php errors appearing.

Any Ideas where I can search for further information?

**Comment by geerlingguy** [comment]
Note that the default session lifetime used by Drupal VM is `0`, meaning sessions would persist indefinitely. That setting is from the PHP role used by Drupal VM: https://github.com/geerlingguy/ansible-role-php

I've never encountered this issue on any of my projects, and I wonder if maybe something in your local Drupal configuration or maybe an override set in the PHP configuration could be setting a different cookie lifetime or expiring cookies either immediately or after some short time frame?
