### ISSUE TITLE
When setting multiple serveralias in config only the last one is generated

### ISSUE THREAD

**Issue by agence-tuesday** [geerlingguy/drupal-vm#2035]
### Issue Type
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 5.2.22r126460
ansible 2.6.3
  config file = None
  configured module search path = [u'/Users/production/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.15 (default, Aug 17 2018, 22:42:59) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

### Your OS

 - **macOS** (version)

### Summary

Hi while working on multisite drupal 8 instance i wanted to set multiple server aliases for my vhost.
When i set multiple serverailas in default.config.yml only the last one is processed when provisioning.

eg with this config : 
```
- servername: "profile.vbox.local"
    serveralias: "profile1.vbox.local"
    serveralias: "profile2.vbox.local"
    documentroot: "/var/www/drupalvm/d8vm/profile.vbox.local/public_html/web"
    extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
```
only profile.vbox.local and profile2.vbox.local are set in vhost and host updater only create rules for those while serveralias: "profile1.vbox.local" is discarded

```
==> drupalvm: [vagrant-hostsupdater]   192.168.2.27  profile.vbox.local  # VAGRANT: 823504acb7deec376443d2fed70a1faa (drupalvm) / 1136af15-7c8f-4a7f-b5c0-57fda15a9943
==> drupalvm: [vagrant-hostsupdater]   192.168.2.27  profile2.vbox.local  # VAGRANT: 823504acb7deec376443d2fed70a1faa (drupalvm) / 1136af15-7c8f-4a7f-b5c0-57fda15a9943

```
I managed to have it by creating new vhost instead of aliases, but imho it would be convenient and more efficient to be able to set multiple aliases instead of multiple vhosts.

Br
Eric

**Comment by geerlingguy** [comment]
@agence-tuesday - ServerAlias can take a string with one or more hostnames, separated by a space; see the documentation here: https://httpd.apache.org/docs/2.4/mod/core.html#serveralias

```yaml
- servername: "profile.vbox.local"
  serveralias: "profile1.vbox.local profile2.vbox.local"
  documentroot: "/var/www/drupalvm/d8vm/profile.vbox.local/public_html/web"
  extra_parameters: "{{ apache_vhost_php_fpm_parameters }}"
```

So that should work out for you.

**Comment by agence-tuesday** [comment]
Lighting fast answer, yes it works perfectly, thanks a lots.
