### ISSUE TITLE
Zip Package currently not supported in drupal vm

### ISSUE THREAD

**Issue by manojbisht891** [geerlingguy/drupal-vm#2036]
Was using class ArchiveManager to extract content from zip file., but it fail to download as it doesnot have any zip module installed on vm.

used:  sudo apt-get install php7.2-zip

fixed the issue.

php -m

**Comment by geerlingguy** [comment]
There is a `php_packages_extra` variable you can use to add additional PHP packages specific functionality you use might rely on; see https://github.com/geerlingguy/ansible-role-php#role-variables

In your config.yml add:

```yaml
php_packages_extra:
  - php7.2-zip
```
