### ISSUE TITLE
Unable to install DrupalVM on Windows 10

### ISSUE THREAD

**Issue by dyeesurrey** [geerlingguy/drupal-vm#2037]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** 10 Version = "10.0.18362.628"

### Full console output

https://gist.github.com/dyeesurrey/d18031b6dabd3e4606dbbf6aa99de892
### Summary

Ran `vagrant up` and appears the VirtualBox VM is created but shuts down and cannot continue.  Attempt to run `vagrant provision` but receive the message `==> drupalvm: VM not created. Moving on....`

**Comment by dyeesurrey** [comment]
It turns out the issue is that I have Hyper-V installed on my machine.  I believe since Hyper-V is a Type 1 hypervisor, Oracle Virtualbox will not function correctly on my Windows 10 machine.  Uninstalling Hyper-V allowed me to successfully build DrupalVM.

**Comment by geerlingguy** [comment]
@dyeesurrey - Thanks for leaving the follow up!

**Comment by geerlingguy** [comment]
Noting also that it seems in VirtualBox 6.0.x, Hyper-V support may be possible (e.g. https://forums.virtualbox.org/viewtopic.php?t=90853).
