### ISSUE TITLE
Error when enabling xdebug together with 7.3

### ISSUE THREAD

**Issue by vouza** [geerlingguy/drupal-vm#2038]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 6.0.10r132072
ansible 2.8.3
  config file = None
  configured module search path = ['/Users/xxx/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.8.3/libexec/lib/python3.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.7.4 (default, Jul  9 2019, 18:13:23) [Clang 10.0.1 (clang-1001.0.46.4)]
```

### Your OS

 - **macOS** (10.15.4)

### Summary

When enabling "xdebug" together with php 7.3 in the default.config.yml when running "vagrant provision" I receive the below error:

When using 7.2 or when I disable the use of xdebug (installed_extras:xdebug) I have no issues to provision vagrant. 

`TASK [geerlingguy.php-xdebug : Build Xdebug.] **********************************
changed: [www8-php7-3] => (item=phpize)
changed: [www8-php7-3] => (item=./configure)
failed: [www8-php7-3] (item=make) => {"ansible_loop_var": "item", "changed": true, "cmd": ["make"], "delta": "0:00:00.121138", "end": "2020-04-17 16:26:54.026156", "item": "make", "msg": "non-zero return code", "rc": 2, "start": "2020-04-17 16:26:53.905018", "stderr": "/root/php7.3/xdebug-2.6.0/xdebug_compat.c: In function 'xdebug_zval_ptr':\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:27: warning: passing argument 1 of 'zend_get_zval_ptr' makes pointer from integer without a cast [-Wint-conversion]\n  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);\n                           ^~~~~~~\nIn file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,\n                 from /usr/include/php/20180731/main/php.h:38,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:\n/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'const zend_op * {aka const struct _zend_op *}' but argument is of type 'int'\n ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);\n                ^~~~~~~~~~~~~~~~~\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:36: warning: passing argument 2 of 'zend_get_zval_ptr' makes integer from pointer without a cast [-Wint-conversion]\n  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);\n                                    ^~~~\nIn file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,\n                 from /usr/include/php/20180731/main/php.h:38,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:\n/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'int' but argument is of type 'const znode_op * {aka const union _znode_op *}'\n ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);\n                ^~~~~~~~~~~~~~~~~\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:42: warning: passing argument 3 of 'zend_get_zval_ptr' from incompatible pointer type [-Wincompatible-pointer-types]\n  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);\n                                          ^~~~~\nIn file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,\n                 from /usr/include/php/20180731/main/php.h:38,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:\n/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'const znode_op * {aka const union _znode_op *}' but argument is of type 'zend_execute_data * {aka struct _zend_execute_data *}'\n ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);\n                ^~~~~~~~~~~~~~~~~\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:49: warning: passing argument 4 of 'zend_get_zval_ptr' from incompatible pointer type [-Wincompatible-pointer-types]\n  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);\n                                                 ^\nIn file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,\n                 from /usr/include/php/20180731/main/php.h:38,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:\n/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'const zend_execute_data * {aka const struct _zend_execute_data *}' but argument is of type 'zval ** {aka struct _zval_struct **}'\n ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);\n                ^~~~~~~~~~~~~~~~~\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:9: error: too few arguments to function 'zend_get_zval_ptr'\n  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);\n         ^~~~~~~~~~~~~~~~~\nIn file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,\n                 from /usr/include/php/20180731/main/php.h:38,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:\n/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: declared here\n ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);\n                ^~~~~~~~~~~~~~~~~\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c: In function 'xdebug_setcookie':\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:194:80: warning: passing argument 8 of 'php_setcookie' makes pointer from integer without a cast [-Wint-conversion]\n  php_setcookie(name_s, value_s, expires, path_s, domain_s, secure, url_encode, httponly);\n                                                                                ^~~~~~~~\nIn file included from /root/php7.3/xdebug-2.6.0/xdebug_compat.h:25:0,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:45:\n/usr/include/php/20180731/ext/standard/head.h:40:12: note: expected 'zend_string * {aka struct _zend_string *}' but argument is of type 'int'\n PHPAPI int php_setcookie(zend_string *name, zend_string *value, time_t expires, zend_string *path, zend_string *domain, int secure, int httponly, zend_string *samesite, int url_encode);\n            ^~~~~~~~~~~~~\n/root/php7.3/xdebug-2.6.0/xdebug_compat.c:194:2: error: too few arguments to function 'php_setcookie'\n  php_setcookie(name_s, value_s, expires, path_s, domain_s, secure, url_encode, httponly);\n  ^~~~~~~~~~~~~\nIn file included from /root/php7.3/xdebug-2.6.0/xdebug_compat.h:25:0,\n                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:45:\n/usr/include/php/20180731/ext/standard/head.h:40:12: note: declared here\n PHPAPI int php_setcookie(zend_string *name, zend_string *value, time_t expires, zend_string *path, zend_string *domain, int secure, int httponly, zend_string *samesite, int url_encode);\n            ^~~~~~~~~~~~~\nmake: *** [xdebug_compat.lo] Error 1", "stderr_lines": ["/root/php7.3/xdebug-2.6.0/xdebug_compat.c: In function 'xdebug_zval_ptr':", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:27: warning: passing argument 1 of 'zend_get_zval_ptr' makes pointer from integer without a cast [-Wint-conversion]", "  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);", "                           ^~~~~~~", "In file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,", "                 from /usr/include/php/20180731/main/php.h:38,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:", "/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'const zend_op * {aka const struct _zend_op *}' but argument is of type 'int'", " ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);", "                ^~~~~~~~~~~~~~~~~", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:36: warning: passing argument 2 of 'zend_get_zval_ptr' makes integer from pointer without a cast [-Wint-conversion]", "  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);", "                                    ^~~~", "In file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,", "                 from /usr/include/php/20180731/main/php.h:38,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:", "/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'int' but argument is of type 'const znode_op * {aka const union _znode_op *}'", " ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);", "                ^~~~~~~~~~~~~~~~~", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:42: warning: passing argument 3 of 'zend_get_zval_ptr' from incompatible pointer type [-Wincompatible-pointer-types]", "  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);", "                                          ^~~~~", "In file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,", "                 from /usr/include/php/20180731/main/php.h:38,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:", "/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'const znode_op * {aka const union _znode_op *}' but argument is of type 'zend_execute_data * {aka struct _zend_execute_data *}'", " ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);", "                ^~~~~~~~~~~~~~~~~", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:49: warning: passing argument 4 of 'zend_get_zval_ptr' from incompatible pointer type [-Wincompatible-pointer-types]", "  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);", "                                                 ^", "In file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,", "                 from /usr/include/php/20180731/main/php.h:38,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:", "/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: expected 'const zend_execute_data * {aka const struct _zend_execute_data *}' but argument is of type 'zval ** {aka struct _zval_struct **}'", " ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);", "                ^~~~~~~~~~~~~~~~~", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:56:9: error: too few arguments to function 'zend_get_zval_ptr'", "  return zend_get_zval_ptr(op_type, node, zdata, &should_free, BP_VAR_R);", "         ^~~~~~~~~~~~~~~~~", "In file included from /usr/include/php/20180731/Zend/zend_API.h:29:0,", "                 from /usr/include/php/20180731/main/php.h:38,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:43:", "/usr/include/php/20180731/Zend/zend_execute.h:331:16: note: declared here", " ZEND_API zval *zend_get_zval_ptr(const zend_op *opline, int op_type, const znode_op *node, const zend_execute_data *execute_data, zend_free_op *should_free, int type);", "                ^~~~~~~~~~~~~~~~~", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c: In function 'xdebug_setcookie':", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:194:80: warning: passing argument 8 of 'php_setcookie' makes pointer from integer without a cast [-Wint-conversion]", "  php_setcookie(name_s, value_s, expires, path_s, domain_s, secure, url_encode, httponly);", "                                                                                ^~~~~~~~", "In file included from /root/php7.3/xdebug-2.6.0/xdebug_compat.h:25:0,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:45:", "/usr/include/php/20180731/ext/standard/head.h:40:12: note: expected 'zend_string * {aka struct _zend_string *}' but argument is of type 'int'", " PHPAPI int php_setcookie(zend_string *name, zend_string *value, time_t expires, zend_string *path, zend_string *domain, int secure, int httponly, zend_string *samesite, int url_encode);", "            ^~~~~~~~~~~~~", "/root/php7.3/xdebug-2.6.0/xdebug_compat.c:194:2: error: too few arguments to function 'php_setcookie'", "  php_setcookie(name_s, value_s, expires, path_s, domain_s, secure, url_encode, httponly);", "  ^~~~~~~~~~~~~", "In file included from /root/php7.3/xdebug-2.6.0/xdebug_compat.h:25:0,", "                 from /root/php7.3/xdebug-2.6.0/xdebug_compat.c:45:", "/usr/include/php/20180731/ext/standard/head.h:40:12: note: declared here", " PHPAPI int php_setcookie(zend_string *name, zend_string *value, time_t expires, zend_string *path, zend_string *domain, int secure, int httponly, zend_string *samesite, int url_encode);", "            ^~~~~~~~~~~~~", "make: *** [xdebug_compat.lo] Error 1"], "stdout": "/bin/bash /root/php7.3/xdebug-2.6.0/libtool --mode=compile cc   -I. -I/root/php7.3/xdebug-2.6.0 -DPHP_ATOM_INC -I/root/php7.3/xdebug-2.6.0/include -I/root/php7.3/xdebug-2.6.0/main -I/root/php7.3/xdebug-2.6.0 -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php7.3/xdebug-2.6.0/xdebug_compat.c -o xdebug_compat.lo \nlibtool: compile:  cc -I. -I/root/php7.3/xdebug-2.6.0 -DPHP_ATOM_INC -I/root/php7.3/xdebug-2.6.0/include -I/root/php7.3/xdebug-2.6.0/main -I/root/php7.3/xdebug-2.6.0 -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php7.3/xdebug-2.6.0/xdebug_compat.c  -fPIC -DPIC -o .libs/xdebug_compat.o\nMakefile:234: recipe for target 'xdebug_compat.lo' failed", "stdout_lines": ["/bin/bash /root/php7.3/xdebug-2.6.0/libtool --mode=compile cc   -I. -I/root/php7.3/xdebug-2.6.0 -DPHP_ATOM_INC -I/root/php7.3/xdebug-2.6.0/include -I/root/php7.3/xdebug-2.6.0/main -I/root/php7.3/xdebug-2.6.0 -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /root/php7.3/xdebug-2.6.0/xdebug_compat.c -o xdebug_compat.lo ", "libtool: compile:  cc -I. -I/root/php7.3/xdebug-2.6.0 -DPHP_ATOM_INC -I/root/php7.3/xdebug-2.6.0/include -I/root/php7.3/xdebug-2.6.0/main -I/root/php7.3/xdebug-2.6.0 -I/usr/include/php/20180731 -I/usr/include/php/20180731/main -I/usr/include/php/20180731/TSRM -I/usr/include/php/20180731/Zend -I/usr/include/php/20180731/ext -I/usr/include/php/20180731/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /root/php7.3/xdebug-2.6.0/xdebug_compat.c  -fPIC -DPIC -o .libs/xdebug_compat.o", "Makefile:234: recipe for target 'xdebug_compat.lo' failed"]}`

**Comment by phizev** [comment]
PHP 7.3 support was only added to [Xdebug 2.7.0beta1](https://xdebug.org/updates#x_2_7_0beta1). You are trying to install Xdebug 2.6.0, either update DrupalVM, or try setting [php_xdebug_version](https://github.com/geerlingguy/ansible-role-php-xdebug#role-variables) in config.yml to a more [recent release of Xdebug](https://xdebug.org/updates).

**Comment by geerlingguy** [comment]
@vouza - FYI the default in the xdebug role is currently `2.9.0` (see https://github.com/geerlingguy/ansible-role-php-xdebug). If you have `php_xdebug_version` defined in your `config.yml` make sure you update that version or remove the key to use the default version from the role.

**Comment by jfitzsimmons2** [comment]
FWIW - I had this same issue, I ran `vagrant box update` then commented out the `php_xdebug_version` key and it still failed, but once I explicitly set the xdebug version to `2.9.0` in config.yml and re-provisioned, the error resolved.
