### ISSUE TITLE
Cannot provision Vagrant

### ISSUE THREAD

**Issue by vouza** [geerlingguy/drupal-vm#2039]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 6.1.4r136177
ansible 2.9.7
  config file = None
  configured module search path = [u'/Users/mogio/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Dec 13 2019, 18:00:32) [GCC 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.32.4) (-macos10.15-objc-s
```

### Your OS

 - **macOS** (10.15.3)

### Full console output

https://gist.github.com/vouza/94f2573e3c632d297354b55132dafd85

### Summary

Since OSX Catalina I am not able to provision my "drupal-vm"-vagrant machines. 
I tried also different linux versions:
vagrant_box: geerlingguy/ubuntu1804
vagrant_box: geerlingguy/drupal-vm 

I can install the machine fine, but as soon as I run vagrant provision, or vagrant up --provision I get this error. It seems that the script stops each time at a different position. 
This output shows the drupal console as issue... when I comment out the drupal console it is the next "installed_extra". The error stays the same: "Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again."

I can't even count how often I had to destroy the machine to add anything that cannot be imported via provision.

I am quite lost. 

Thanks for any help. 
```
TASK [geerlingguy.drupal-console : Install Drupal Console.] ********************
fatal: [www8-php7-3]: FAILED! => {"changed": false, "dest": "/usr/local/bin/drupal", "elapsed": 10, "gid": 0, "group": "root", "mode": "0755", "msg": "Request failed: <urlopen error [Errno -3] Temporary failure in name resolution>", "owner": "root", "size": 831267, "state": "file", "uid": 0, "url": "https://drupalconsole.com/installer"}

PLAY RECAP *********************************************************************
www8-php7-3                : ok=138  changed=0    unreachable=0    failed=1    skipped=151  rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
@vouza - It looks like you may be trying to install the `drupal-console` addon, but it's best to add that to your project directly via `composer require` instead of using the installed extra.

See the `Temporary failure in name resolution` error—it seems like your VM isn't able to reach the URL https://drupalconsole.com/installer for whatever reason.

**Comment by vouza** [comment]
Hi. It has nothing to do with the drupal-console.
Like mentioned in the top:
`This output shows the drupal console as issue... when I comment out the drupal console it is the next "installed_extra". The error stays the same: "Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again."`

Also ... when installing the machine ... (not provisioning) all is installed correctly.

**Comment by vouza** [comment]
I just downloaded the latest drupal-vm and ran a "vagrant up" with no issues. Again when trying to run "vagrant provision" I receive this ansible error. Important: I made absolutely NO changes to the config or the files. I must be a general issue with the latest version of ansible and / or the latest version of OSX.

`TASK [geerlingguy.drupal : Install dependencies with composer require (this may take a while).] ***
failed: [drupalvm] (item=drupal/devel:^1.2) => {"ansible_loop_var": "item", "changed": false, "item": "drupal/devel:^1.2", "msg": "1/2: http://repo.packagist.org/p/provider-2020-04$48cbe0a352dc51e6f7505eaa360b354af7d1aed322cd6be4980b2033658e7dab.json 2/2: http://repo.packagist.org/p/provider-latest$019e8fe3cfe02226d13027724d4d66666f968a40022035fd9154d0f7e441a44d.json Finished: success: 2, skipped: 0, failure: 0, total: 2 ./composer.json has been updated > DrupalProject\\composer\\ScriptHandler::checkComposerVersion Loading composer repositories with package information Updating dependencies (including require-dev) Nothing to install or update Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead. Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead. Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead. Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead. Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead. Generating optimized autoload files Installation failed, reverting ./composer.json to its original content. [RuntimeException] Could not delete /var/www/drupalvm/drupal/web/sites/default/default.services.yml: require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", "stdout": "    1/2:\thttp://repo.packagist.org/p/provider-2020-04$48cbe0a352dc51e6f7505eaa360b354af7d1aed322cd6be4980b2033658e7dab.json\n    2/2:\thttp://repo.packagist.org/p/provider-latest$019e8fe3cfe02226d13027724d4d66666f968a40022035fd9154d0f7e441a44d.json\n    Finished: success: 2, skipped: 0, failure: 0, total: 2\n./composer.json has been updated\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nNothing to install or update\nPackage container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.\nPackage zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.\nPackage zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.\nPackage zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.\nPackage zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.\nGenerating optimized autoload files\n\nInstallation failed, reverting ./composer.json to its original content.\n\n                                                                                     \n  [RuntimeException]                                                                 \n  Could not delete /var/www/drupalvm/drupal/web/sites/default/default.services.yml:  \n                                                                                     \n\nrequire [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...\n\n", "stdout_lines": ["    1/2:\thttp://repo.packagist.org/p/provider-2020-04$48cbe0a352dc51e6f7505eaa360b354af7d1aed322cd6be4980b2033658e7dab.json", "    2/2:\thttp://repo.packagist.org/p/provider-latest$019e8fe3cfe02226d13027724d4d66666f968a40022035fd9154d0f7e441a44d.json", "    Finished: success: 2, skipped: 0, failure: 0, total: 2", "./composer.json has been updated", "> DrupalProject\\composer\\ScriptHandler::checkComposerVersion", "Loading composer repositories with package information", "Updating dependencies (including require-dev)", "Nothing to install or update", "Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.", "Package zendframework/zend-diactoros is abandoned, you should avoid using it. Use laminas/laminas-diactoros instead.", "Package zendframework/zend-escaper is abandoned, you should avoid using it. Use laminas/laminas-escaper instead.", "Package zendframework/zend-feed is abandoned, you should avoid using it. Use laminas/laminas-feed instead.", "Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.", "Generating optimized autoload files", "", "Installation failed, reverting ./composer.json to its original content.", "", "                                                                                     ", "  [RuntimeException]                                                                 ", "  Could not delete /var/www/drupalvm/drupal/web/sites/default/default.services.yml:  ", "                                                                                     ", "", "require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...", ""]}

PLAY RECAP *********************************************************************
drupalvm                   : ok=185  changed=0    unreachable=0    failed=1    skipped=348  rescued=0    ignored=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
`

**Comment by vouza** [comment]
I also tried to reinstall Ansible - no success! Error stays the same. I believe somehow that the problem is related to the changes Apple did to the file system.

**Comment by vouza** [comment]
Ok I updated virtualBox. Ansible does run now without issues. I can provisoin drupal vm.

**Comment by geerlingguy** [comment]
@vouza - Ah, nice! And yeah, there are a number of issues (most now closed) where people were running into various problems with filesystem permissions and Vagrant and VirtualBox after the Catalina upgrade, looks like that might've been the case for you too :(
