### ISSUE TITLE
Failure when trying to install Ansible Galaxy

### ISSUE THREAD

**Issue by henlfern** [geerlingguy/drupal-vm#204]
When I follow the guide you've written, trying to install Ansible Galaxy throws the following error message:

Traceback (most recent call last):
  File "/Users/adam/ansible/bin/ansible-galaxy", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named ansible.errors

Any idea what's wrong here?

Kind regards,
Adam

**Comment by geerlingguy** [comment]
@henlfern - What platform are you using, and how did you install (with brew, pip, apt, yum?)

**Comment by henlfern** [comment]
Using Mac, and followed your instructions one by one. It all went well until I came to #5, Install Ansible Galaxy.

**Comment by geerlingguy** [comment]
If you're installing from source, you may need to either run the environment setup, or run make install; please see: https://github.com/ansible/ansible/issues/275#issuecomment-5418953

Otherwise, you could remove what you've added so far, then install via brew or pip instead.

**Comment by michaelocana** [comment]
you execute

sudo make install
