### ISSUE TITLE
bind-mount issue with box version 2.0.9?

### ISSUE THREAD

**Issue by jasloe** [geerlingguy/drupal-vm#2040]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 6.1.4r136177
ansible 2.9.6
```

### Your OS

 - **macOS** Mojave

### Summary
Spinning up a brand new box today and encounter the following:

```
==> local-d8: Creating bind mounts after synced_folders...
==> local-d8: Cannot create bind mount from '/var/nfs/Users/jasloe/projects/drupal' to '/var/www/drupal': User 'www-datacom' doesn't exist
```

```
TASK [geerlingguy.drupal : Ensure drupal_composer_install_dir directory exists.] ***
fatal: [local-d8]: FAILED! => {"changed": false, "msg": "There was an issue creating /var/www/drupalvm as requested: [Errno 13] Permission denied: b'/var/www/drupalvm'", "path": "/var/www/drupalvm/drupal"}
```

Instances running <= geerlingguy/drupal-vm 2.0.8 are working fine. According to the machine index, the new box is using 2.0.9, released just yesterday. Any known issues? is there a quick way to pin a vagrant box version as a temporary workaround?

**Comment by jasloe** [comment]
Just confirmed that provisioning with 2.0.8 worked without a hitch. Not sure it means anything; just wanted to provide another data point.

**Comment by geerlingguy** [comment]
2.0.9 was released two days ago and was built for VirtualBox 6.1.6 (see https://app.vagrantup.com/geerlingguy/boxes/drupal-vm). Can you make sure you're running the latest version of VirtualBox and see if that might be the issue?

Also, I believe the virtualbox guest additions vagrant plugin should correct for a mismatch but maybe it didn't in this case (assuming that's the issue).
