### ISSUE TITLE
Port forward sites in drupalvm

### ISSUE THREAD

**Issue by INirandjan** [geerlingguy/drupal-vm#2042]
## Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.5
VirtualBox 6.0.10r132072
WARNING: Executing a script that is loading libcrypto in an unsafe way. This will fail in a future version of macOS. Set the LIBRESSL_REDIRECT_STUB_ABORT=1 in the environment to force this into an error.
ansible 2.8.4
  config file = None
  configured module search path = [u'/Users/Inirandjan/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.16 (default, Feb 29 2020, 01:55:37) [GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.29.20) (-macos10.15-objc-
```

### Your OS
 - **macOS** (version)

### Summary
I already asked it here: https://stackoverflow.com/questions/61467436/how-can-i-port-forward-a-site-in-drupalvm-that-is-using-vagrant But since you are the creators i can ask it here ;).

For example my, /etc/hosts is looking like this;

192.168.88.88 newsite1.test
192.168.88.88 newsite2.test
192.168.88.88 newsite3.test

Now i want to portforward every site. How do i do that? 
I also tried 'vagrant_public_ip', but that just sends you the information of 192.168.88.88. 

So how can i send information of '192.168.88.88 newsite1.test' to a IP to portfoward?

Thanks already! :)

**Comment by INirandjan** [comment]
So i tried vagrant_public_ip and changed the /etc/hosts on my other PC. Also
Example;
192.168.88.88 newsite1.test

And on my other PC newsite1.test worked.

But what do i need to do to avoid changing al the time in /etc/hosts? That i just can directly port forward the newsite1.test?

**Comment by geerlingguy** [comment]
This is something you'd control through a delegated Vagrantfile, or in your main Vagrantfile, following instructions on these pages:

  - https://www.vagrantup.com/docs/networking/forwarded_ports.html
  - https://www.vagrantup.com/docs/networking/basic_usage.html

I don't think I'd be able to help in terms of trying to forward different ports to different hostnames, though, you'd still need to manage your hosts file to do anything too specific.

If you have the vagrant_hostsupdater plugin installed, though, and set hostnames for all your virtualhosts in Drupal VM's settings, then Vagrant will manage the hosts file entries for you.

**Comment by INirandjan** [comment]
Isn't there a way ot disable the NFS and only send 1 file through the ip?
