### ISSUE TITLE
Default to Drupal 9

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#2050]
### Issue Type

 - Feature Idea

### Summary

Drupal 9 is here: https://www.drupal.org/about/9

Let's default to it. Related upstream issue: https://github.com/geerlingguy/ansible-role-drupal/issues/79

**Comment by phizev** [comment]
Can the default be adjusted to using the [Drupal recommended project](https://github.com/drupal/recommended-project) at the same time? Instead of the current default in config.yml?

**Comment by geerlingguy** [comment]
@phizev - Oh wow, I didn't realize the default config.yml still had https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L80 in it! I fixed that in the upstream Drupal role but forget to ever switch it in Drupal VM itself!

Yes, that should be corrected too.

**Comment by axroth** [comment]
Hi Jeff,

upgrade_status module throws a warning with current mariadb version. Would be perfect if you could update that role with the next release as well.

> "Minimum version is 10.3.7"

Cheers, 
Axel

**Comment by geerlingguy** [comment]
@axroth - What OS box are you using? The latest one should work with Drupal 9, I believe (based on Ubuntu 18.04).

**Comment by axroth** [comment]
according to the dockerfile (using drupalvm with docker and not vagrant), this is:
> geerlingguy/docker-debian9-ansible:latest

**Comment by geerlingguy** [comment]
@axroth yeah it looks like I'll need to do that too. I'm going to test it out and see if it works.

**Comment by geerlingguy** [comment]
This _seems_ to all be fixed now. I'm going to do a little more testing before releasing a new version again.
