### ISSUE TITLE
Imagemagick path?

### ISSUE THREAD

**Issue by jsidigital** [geerlingguy/drupal-vm#2051]
### Issue Type 
 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.9
```

### Your OS
 - **Windows** 10 Pro

### Summary
Just ran 'vagrant up --provision' using:

vagrant_box: geerlingguy/centos7
php_version: "7.3"
php_packages_extra:
  - "php-bcmath.x86_64"
  - "php-imagick"

phpinfo shows imagick ini here: /etc/php.d/40-imagick.ini

Website working great (Drupal 8.9.0), went on to enable imagemagick module v3.1.
Then went to configure it in admin/config/media/image-toolkit

There it asks for the path to the package executables. Where do I find this in DrupalVM?
I tried /usr/bin/convert and that is not correct. So how can I find the path to enter here?

Sorry for the newbie question.

Thank you.

**Comment by rubenvarela** [comment]
While you installed the PHP extension`php-imagick`, you didn't install `imagemagick` itself. 

On your `config.yml`, you need to install it. Find the `extra_packages` line with `sqlite` under it. Under that, add `imagemagick`,

```
extra_packages:
  - sqlite
  - imagemagick
```

**Comment by geerlingguy** [comment]
What @rubenvarela says is correct—you also need to install the `imagemagick` package itself, in addition to the PHP library for it. Once you do that, it should be available in `/usr/bin/convert`.

Thanks!
