### ISSUE TITLE
Update drupalvm.com intro text

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#2056]
### Issue Type

 - Documentation Report

### Summary

Over on https://www.drupalvm.com it still shows PHP 7.2 (we default to 7.3 now), and some other things that are outdated. Run through that docs page, as well as the README for Drupal VM itself, and update everything that needs updating.

**Comment by acrollet** [comment]
hmm, https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L261 says otherwise? (re: php 7.3)

**Comment by geerlingguy** [comment]
@acrollet - Right you are... that should be done separately then (updating to 7.3). There are still a few other things that are outdated though.

**Comment by geerlingguy** [comment]
Did https://github.com/geerlingguy/drupalvm.github.io/commit/658398d9efd29c45f466c8bbabccc063b237b5c6
