### ISSUE TITLE
The timeout specified has expired

### ISSUE THREAD

**Issue by jsidigital** [geerlingguy/drupal-vm#2058]
### Issue Type
 - Bug Report / Support Request

### Your Environment
```
Vagrant 2.2.9
VirtualBox 6.1.10 r138449
ansible 2.9.10
```

### Your OS
 - **Windows** Pro

### Full console output
```
[Tue Jun 30 07:50:25.788400 2020] [proxy_fcgi:error] [pid 17046] (70007)The timeout specified has expired: [client 192.168.88.1:53907] AH01075: Error dispatching request to :, referer: http://mydev.test/en/admin/config/development/performance
[Tue Jun 30 07:52:11.775434 2020] [proxy_fcgi:error] [pid 17552] (70007)The timeout specified has expired: [client 192.168.88.1:53938] AH01075: Error dispatching request to :, referer: http://mydev.test/en/admin/modules/uninstall
```

### Summary
Using default install except that I am using centos7 with php 7.3

Everytime I try to clear cache or uninstall a module, the pages timeout and I get a Service Unavailable error page after about 60 seconds. Something somewhere is causing these pages to timeout and never load. Any idea what setting is causing this? I have never seen that error before.

I tried increasing the memory to 4G (previously 3G) and also added this to my config: php_max_execution_time: "300"
Nothing has worked.

Any idea what is causing this and how I can fix it?

**Comment by jsidigital** [comment]
So I figured this out... I had two problems at the same time. After I solved one, the second was easier to spot.
First one was coming from trying to uninstall commerce. That was causing the white pages of death in many different pages showing me this: 
`AH01071: Got error 'PHP message: Uncaught PHP Exception Drupal\\Component\\Plugin\\Exception\\PluginNotFoundException: "The "commerce_product" entity type does not exist." at /var/www/mysites/columbanos/docroot/core/lib/Drupal/Core/Entity/EntityTypeManager.php line 150'`

So deleting the entity definition from the key_value table fixed it 
`DELETE FROM key_value WHERE name LIKE '%commerce_product%';`

Next problem... my pages kept timing out thinking it was the php_max_execution_time...
However, it ended up being the FPM PHP handler.
So I created the following file /etc/httpd/conf.modules.d/00-proxy_timeout.conf
Then added this to it:
`Timeout 600
ProxyTimeout 600`

And that was it. No more white pages of death when clearing cache or when visiting the uninstall tab.

Life is good once again.
Although I am left with this question...

Is there a way to apply these two settings on the config file to avoid having to create this file everytime I start a new VM on a large site?

**Comment by geerlingguy** [comment]
THere's https://github.com/geerlingguy/ansible-role-php#phpini-settings for `php_max_execution_time`, but at this time there's no handler for ProxyTimeout or Timeout — for that your best bet is to use a [post-provision script](http://docs.drupalvm.com/en/latest/extending/scripts/) and write the 00-proxy_timeout.conf file to the VM using that script.
