### ISSUE TITLE
Minor error/change in the video that took a long time to find

### ISSUE THREAD

**Issue by oceanpro-zz** [geerlingguy/drupal-vm#2059]
First off, thanks for the work on drupalvm.

I just set up drupalvm for the first time. I tried to follow the guide here: http://docs.drupalvm.com/en/latest/getting-started/installation-windows/

I followed the video. In the video it says and shows to type in the URL **drupalvm.dev** to see your new Drupal 8 site. I finally found that it is changed to **drupalvm.test**

### Issue Type

 - Documentation Report

### Your Environment

```
Vagrant 2.2.9
"VirtualBox `vboxmanage --version`"
'ansible' is not recognized as an internal or external command,
operable program or batch file.
```

### Your OS

 - **Windows** (10 version 1903)

### Summary
Please add a unmissable comment below the video to help newbies that they should type in **drupalvm.test** to see the new build.

That`s it :)

**Comment by geerlingguy** [comment]
Good point. I've added a pinned comment on YouTube as well as an expanded note in the documentation page under the video embed. Thanks!
