### ISSUE TITLE
VirtualBox is not yet compatible with Windows 10

### ISSUE THREAD

**Issue by tashbaugh** [geerlingguy/drupal-vm#206]
I'm adding this issue more as an FYI for Windows users. Do not upgrade to Windows 10 if you rely on VirtualBox. Oracle has not released a version of VB yet that officially supports Windows 10. 

When I attempt to run 'vagrant up' I get the following error: 

>There was an error while executing `VBoxManage`, a CLI used by Vagrant
>for controlling VirtualBox. The command and stderr is shown below.

>Command: ["hostonlyif", "create"]

>Stderr: 0%...
>Progress state: E_FAIL
>VBoxManage.exe: error: Failed to create the host-only adapter
>VBoxManage.exe: error: Code E_FAIL (0x80004005) - Unspecified error (extended in
>fo not available)
>VBoxManage.exe: error: Context: "int __cdecl handleCreate(struct HandlerArg *,in
>t,int *)" at line 66 of file VBoxManageHostonly.cpp

**Comment by geerlingguy** [comment]
See related: https://github.com/mitchellh/vagrant/issues/6068

If anyone here could try building Drupal VM with Windows 10 and VirtualBox 5.0.4 (latest release) or later, please let me know if it works!

**Comment by frob** [comment]
There are currently still issues with host only adapters on Windows 10. Completely stock install failed.

*log*:
```
D:\Users\Frank\Documents\GitHub\drupal-vm [master]> vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1404' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/ubuntu1404'
    drupalvm: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1404
==> drupalvm: Adding box 'geerlingguy/ubuntu1404' (v1.0.6) for provider: virtualbox
    drupalvm: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1404/versions/1.0.6/providers/virtualbox.
box
    drupalvm: Progress: 100% (Rate: 2816k/s, Estimated time remaining: --:--:--)
==> drupalvm: Successfully added box 'geerlingguy/ubuntu1404' (v1.0.6) for 'virtualbox'!
==> drupalvm: Importing base box 'geerlingguy/ubuntu1404'...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #2", "--ip", "192.168.88.1", "--netmask", "25
5.255.255.0"]

Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component HostWrap, interface IHost, callee IUnknown
VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(Bstr(pszName).raw(), hif.asOutParam())" at line 205 of f
ile VBoxManageHostonly.cpp

```

**Comment by frob** [comment]
After following some of the advice on that other issue, I deleted and re-added my host only adapter, I was able to get vagrant to do its thing. 

I had an error during the provisioning. 

*log*:

```
==> drupalvm: TASK: [Configure drush aliases for root user inside VM.] **********************
==> drupalvm: ok: [localhost]
==> drupalvm:
==> drupalvm: TASK: [Check if local Drush configuration folder exists.] *********************
==> drupalvm: ok: [localhost -> 127.0.0.1]
==> drupalvm:
==> drupalvm: TASK: [Create Drush configuration folder if it doesn't exist.] ****************
==> drupalvm: skipping: [localhost]
==> drupalvm:
==> drupalvm: TASK: [Configure host machine drush aliases.] *
==> drupalvm: ********************************
==> drupalvm: fatal: [localhost -> 127.0.0.1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'a
sible_ssh_port' is undefined", 'failed': True}
==> drupalvm: fatal: [localhost -> 127.0.0.1] => {'msg': "AnsibleUndefinedVariable: One or more undefined variables: 'a
sible_ssh_port' is undefined", 'failed': True}
==> drupalvm:
==> drupalvm: FATAL: all hosts have already failed -- aborting
==> drupalvm:
==> drupalvm: PLAY RECAP ********************************************************************
==> drupalvm:            to retry, use: --limit @/root/playbook.retry
==> drupalvm:
==> drupalvm: localhost                  : ok=157  changed=85   unreachable=1    failed=0
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
```

As a note, I am using github's gitshell to access powershell. Since this project is hosted on github it seemed like the correct tool to use.

**Comment by frob** [comment]
In the end, so far, when I use putty to ssh into my vm, I can use drush and drush reports a successfully booted drupal.

After changing my hosts file to do this, I get a white screen of death. This could be anything at this point. I will not be looking at logs tonight.

**Comment by geerlingguy** [comment]
Stock Windows 10 and VirtualBox 5.0.8 are working great with Drupal VM, though I recommend you also install the `vagrant-vbguest` plugin.

I finally have a Windows 10 laptop of my own (also running Ubuntu 15.10, Fedora 22, Debian 8, and Arch), so I'm going to continue doing more testing on Windows and popular Linux flavors to make sure the default OOTB experience is as good as I can possibly make it.
