### ISSUE TITLE
Perfomance issue when acces /var/www/projectnamedir

### ISSUE THREAD

**Issue by amine-betari** [geerlingguy/drupal-vm#2069]
I have an issue when i connect to drupal vm via vagrant ssh .
my project is on /var/www/projectname when i type cd /var/www/projectName  or cd /var/www  then ls  it does not do anything it like a perfomance issue . Here is my config of config.yml:

vagrant_synced_folders:
  - local_path: .
    destination: /var/www/projectname
    type: "nfs"

![image](https://user-images.githubusercontent.com/19977336/87657591-f206d080-c752-11ea-81c6-9f6d721d0372.png)

**Comment by geerlingguy** [comment]
I'm not quite sure what you mean—is the issue that you have a synced folder configured, but it does not appear to be mounted inside the VM?

And are you using Windows, Mac, or Linux?

Can you please file a new issue and fill out the entire issue template, as there's no way for me to see what else might be wrong or how to reproduce this issue if you don't supply all the details.
