### ISSUE TITLE
Local tasks fail with fixed value for ansible_python_interpreter 

### ISSUE THREAD

**Issue by benjifisher** [geerlingguy/drupal-vm#2072]
### Issue Type

 - Bug Report / Support Request

### Your Environment

This may not be useful because I am trying to solve a problem that my colleagues have but I do not.

```
Vagrant 2.2.9
VirtualBox 6.1.10r138449
ansible 2.9.10
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/benji/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/linuxbrew/.linuxbrew/Cellar/ansible/2.9.10/libexec/lib/python3.8/site-packages/ansible
  executable location = /home/linuxbrew/.linuxbrew/bin/ansible
  python version = 3.8.3 (default, Jul  9 2020, 19:37:58) [GCC 5.4.0 20160609]
```

### Your OS

 - **Linux** (version)

### Other OS

 - **macOS** (version)

### Full console output

Copied from Issue #2034:

```
TASK [Check if local known_hosts file is present.] *****************************
fatal: [agm]: FAILED! => {"changed": false, "module_stderr": "/bin/sh: /usr/bin/python3: No such file or directory\n", "module_stdout": "", "msg": "The module failed to execute correctly, you probably need to set the interpreter.\nSee stdout/stderr for the exact error", "rc": 127}

PLAY RECAP *********************************************************************
agm                        : ok=166  changed=13   unreachable=0    failed=1    skipped=362  rescued=0    ignored=1
```

### Summary

The source of the problem is this line in `default.config.yml`:

```yaml
ansible_python_interpreter: /usr/bin/python3
```

That setting works fine on the VM, where Python 3 is installed at that path. The problem is that there are some tasks (in `tasks/sshd.yml` and `tasks/drush-aliases.yml`) that are run on the host instead of the VM.

The work-around in Issue #2034 is

1. Make a symbolic link on the VM so that Python 3 can be found at the same location (e.g., `/usr/local/bin/python3`) on the VM as on the host.
1. Change the setting of `ansible_python_interpreter` to the path on the host computer.

This work-around runs into trouble if you are sharing a project with colleagues who have different host environments.

**Comment by benjifisher** [comment]
While looking into this, I noticed that `tasks/sshd.yml` uses `connection: local`, but `tasks/drush-aliases.yml` uses `delegate_to: 127.0.0.1`. These have a similar effect, but are not exactly the same, according to [this blog post](http://willthames.github.io/2018/07/01/connection-local-vs-delegate_to-localhost.html). My testing suggests that the differences do not affect this issue, but I think it would be clearer to be consistent.

**Comment by benjifisher** [comment]
In theory, using `ansible_python_interpreter: auto` instead of hard-coding the path should fix the problem. According to [Interpreter Discovery](https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html) in the Ansible docs, this is forward-compatible, since it will be the default in Ansible 2.12. That same page recommends setting `ansible_python_interpreter` "for individual hosts and groups".

Unfortunately, a colleague of mine with a Mac reports that the `auto` setting does not fix the problem for him.

I tried using host- and group-level variables. Setting one value of `ansible_python_interpreter` in `group_vars/all.yml` and overriding it in `group_vars/local.yml` or `host_vars/drupalvm.yml` works as expected. (In all cases, the `.yml` is optional. I like to include it so that Vim knows to use YAML syntax highlighting.) Using `host_vars/localhost.yml` and variants did not seem to have any effect.

The problem is that I do not see a way to override the group- or host-level variables. Anything in Drupal VM's `default.config.yml` or a project-specific `config.yml` is added using `include_vars`, so it will override group- and host-specific variables. And variables defined in `default.config.yml` and `config.yml` are not available at the time the `group_vars` and `host_vars` files are read, so something like `ansible_python_interpreter: "{{ local_python_interpreter | default(...) }}"` in those files will not work.

The best option I can think of is

1. Create symlinks on the VM to accommodate all developers on the project.
1. Set `ansible_python_interpreter` in `config.yml` to make the majority happy.
1. The rest can override that value in `local.config.yml`, which should be git-ignored.

**Comment by geerlingguy** [comment]
Maybe setting `ansible_python_interpreter: /usr/bin/env python3` would be better? That way it's not a hardcoded path and would be able to work with python 3 installed in various locations...
