### ISSUE TITLE
Vagrant provision fails

### ISSUE THREAD

**Issue by bobita4u** [geerlingguy/drupal-vm#2077]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.9
VirtualBox 5.2.18

```

### Your OS

 - **Windows** 10 pro

### Full console output
TASK [geerlingguy.drupal : Delete old /tmp/composer-project] *******************
changed: [drupalvm]

TASK [geerlingguy.drupal : Generate Drupal project with composer package in /tmp/composer-project (this may take a while).] ***
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal/recommended-project:^9@dev", "/tmp/composer-project", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:08.096619", "end": "2020-08-20 03:06:01.427358", "msg": "non-zero return code", "rc": 1, "start": "2020-08-20 03:05:53.330739", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nCreating a \"drupal/recommended-project:^9@dev\" project at \"/tmp/composer-project\"\nInstalling drupal/recommended-project (9.1.x-dev ecdcc9e305469bbfd5556e03cd81dec8243b044a)\n  - Installing drupal/recommended-project (9.1.x-dev ecdcc9e): Loading from cache\nCreated project in /tmp/composer-project\n\n                                                                                                                                      \n  [InvalidArgumentException]                                                                                                          \n  Composer could not find a composer.json file in /tmp/composer-project                                                               \n  To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section  \n                                                                                                                                      \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stderr_lines": ["Do not run Composer as root/super user! See https://getcomposer.org/root for details", "Creating a \"drupal/recommended-project:^9@dev\" project at \"/tmp/composer-project\"", "Installing drupal/recommended-project (9.1.x-dev ecdcc9e305469bbfd5556e03cd81dec8243b044a)", "  - Installing drupal/recommended-project (9.1.x-dev ecdcc9e): Loading from cache", "Created project in /tmp/composer-project", "", "                                                                                                                                      ", "  [InvalidArgumentException]                                                                                                          ", "  Composer could not find a composer.json file in /tmp/composer-project                                                               ", "  To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ \"Getting Started\" section  ", "                                                                                                                                      ", "", "create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]"], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
drupalvm                   : ok=187  changed=1    unreachable=0    failed=1    skipped=347  rescued=0    ignored=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
It looks like the error is:

```
Composer could not find a composer.json file in /tmp/composer-project
```

What settings have you overridden in your `config.yml` file?
