### ISSUE TITLE
Embedded geerlingguy.repo-remi role is four years old and has an issue validating gpg keys on RHEL8

### ISSUE THREAD

**Issue by GitBytes** [geerlingguy/drupal-vm#2087]
### Issue Type

 - Bug Report / Support Request

### Your Environment

Enterprise VMWare Virtual Machine Infrastructure

### Your OS

- RHEL8

### Full console output

```
"fatal: [localhost]: FAILED! => {\"changed\": false, \"msg\": \"Failed to validate GPG signature for remi-release-8.1-2.el8.remi.noarch\"}"
```

### Summary

We are using DrupalVM version `6.0.0` and we are executing the repo-remi role via DrupalVM which seems to be about four years out of date at this point. This ticket is being created in response to geerlingguy/ansible-role-repo-remi/issues/23

**Comment by geerlingguy** [comment]
Yikes! Sorry about that—I've fixed this in https://github.com/geerlingguy/drupal-vm/commit/42e1253396866924f1319451847779f81fd6fde5 — I was updating the roles, but in the wrong branch in this repository. I've moved all the updates back into master, and maybe it's time to tag a 6.0.1 :)

**Comment by GitBytes** [comment]
Thanks @geerlingguy! Have a great day!
