### ISSUE TITLE
Use virtio (Paravirtualized Network) if it's simple and offers discernible performance boost

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#209]
For VirtualBox, a `virtio-net` adapter (which is _not_ the default, AFAICT) can help speed up the native network adapter, and may be fast enough to make the raw network performance more closely match up to VMware's (see http://www.midwesternmac.com/blogs/jeff-geerling/vagrant-vmware-7-vs-virtualbox-5-benchmarks).

See related:

  - [Ability to set type of nic for bridged network](https://github.com/mitchellh/vagrant/issues/690)
  - [Speed up VirtualBox](http://datasift.github.io/storyplayer/v2/tips/vagrant/speed-up-virtualbox.html)
  - [theevilsharpie's comment on this Reddit post](https://www.reddit.com/r/sysadmin/comments/3hus1y/vagrant_web_development_is_vmware_better_than/cuavnf8)

**Comment by geerlingguy** [comment]
Testing Results:

  - Network (`iperf`)
    - With virtio: .83 Gbps
    - Without virtio (Intel PRO/1000 MT): .94 Gbps

I reran the test twice in each configuration, both times with a freshly-built VM (from scratch), and _one_ time the virtio configuration (confirmed in the VirtualBox GUI) reached about 950 Mbps. But every other time it hovered around 830 Mbps. The default Intel card stayed squarely in the 940-960 Mbps range during these test runs.

I'm not going to add any docs about virtio at this time, since it seems to have a negligible impact on performance, and the baseline is already fast enough for 99% of the work people do with Drupal VM. But it's good to know :)

**Comment by njbooher** [comment]
I think you should reconsider adding a note about this somewhere. I've been sporadically messing around with DrupalVM and before today DrupalVM builds on my Mac Pro were taking 30 - 50 minutes because of what of appeared to be stalling at the 'Preparing Python control' and git checkout steps. Today I finally added -vvv to the ansible arguments setting and discovered that most of that was spent downloading packages at <100kb/s rates even though I have a gigabit internet connection. Adding the virtio setting as suggested at http://datasift.github.io/storyplayer/v2/tips/vagrant/speed-up-virtualbox.html brought the build times down to the advertised 5 minutes.

**Comment by geerlingguy** [comment]
@njbooher - I only tested on two network connections (both Gigabit, both really good networks/Cat6 cabling/switches), and in both cases the performance was close to the same (not really different enough to make me want to add virtio support), and would only make a difference when doing things like load-testing a reverse proxy.

Obviously, speed is speed and more is better... but can you do any speed tests from within the VM to get more data (besides the 100kb/s rates during a provision) so I can make a more informed opinion on this? It would be good to get more samples, especially if it's quite so dramatic as going from 100 kbps to 100+ Mbps... it could also be something else in the networking stack, and the more data the better.

**Comment by njbooher** [comment]
That's odd. I did some more testing and this seems to only be an issue during provisioning. Logging in and doing a speed test after the VM provisioned shows a normal throughput of 100Mbps+.

**Comment by geerlingguy** [comment]
@njbooher - I'm wondering if Vagrant might have a setting/flag flipped during initial provision, then :/
