### ISSUE TITLE
Ansible failing on "Ensure composer directory exists"

### ISSUE THREAD

**Issue by jpdw** [geerlingguy/drupal-vm#2092]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.10
Parallels
vagrant-parallels (2.0.1, global)
```

### Your OS

 - **macOS** (Catalina - 10.15.6)

### Full console output

https://gist.github.com/jpdw/250df088fa538945393a11c5f7c84a58

### Summary

'vagrant up' has stopped completing successfully - it appears to be failing running the Ansible task 'Ensure composer directory exists'. The exact same rebuild has run successfully many times, only changes I've been making were to drupal composer.json and various other drupal code/config (pulled from repos defined in the composer file) -- but ansible is halting before it "gets" to that stage.

```
TASK [geerlingguy.composer : Ensure composer directory exists.] ****************
fatal: [edas-d8-7]: FAILED! => {"changed": false, "gid": 0, "group": "root", "mode": "0755", "msg": "chown failed: [Errno 1] Operation not permitted: b'/home/vagrant/.composer'", "owner": "root", "path": "/home/vagrant/.composer", "size": 4096, "state": "directory", "uid": 0}
```

Looking at the directory mentioned ( /home/vagrant/.composer ) :

```
vagrant@edas-d8-7:~$ ls -al
total 36
drwxr-xr-x 6 vagrant vagrant 4096 Oct  1 16:43 .
drwxr-xr-x 3 root    root    4096 Sep 12 01:02 ..
drwx------ 3 vagrant vagrant 4096 Oct  1 16:43 .ansible
-rw-r--r-- 1 vagrant vagrant  220 Sep 12 01:02 .bash_logout
-rw-r--r-- 1 vagrant vagrant 3771 Sep 12 01:02 .bashrc
drwxr-xr-x 2 vagrant vagrant 4096 Sep 12 01:09 .cache
drwxr-xr-x 2 root    root    4096 Oct  1 16:42 .composer
-rw-r--r-- 1 vagrant vagrant  807 Sep 12 01:02 .profile
drwx------ 2 vagrant vagrant 4096 Oct  1 16:44 .ssh
```
I've found that if I `vagrant-ssh` in before the "Ensure composer directory exists" is reached and manually `sudo chown vagrant:vagrant .composer` then the task complete successfully and the build finishes as normal.

**Comment by geerlingguy** [comment]
The one difference is you are using Parallels, and I'm wondering if there's a possibility of something going wrong with the file permissions in that directory because of it. Probably not, but that's the first thing that came to mind.

**Comment by jpdw** [comment]
If not Parallels, then perhaps the box that I'm using. I had to find another one for the parallels support. Maybe that's the cause of the wrong permissions. I don't remember the reason I moved from 1804 to 2004 but that seemed to be fine for many rebuilds. 

I'll try rolling backwards to see if that make the problem 'go away', which would narrow things down a bit.

**Comment by jpdw** [comment]
I've run this again but this time ssh in before Ansible was run -- ie during the "Installing Ansible" and "Installing pip" stages.:

```
==> edas-d8-9: Running provisioner: drupalvm (ansible_local)...
    edas-d8-9: Installing Ansible...
    edas-d8-9: Installing pip... (for Ansible installation)
    edas-d8-9: Running ansible-playbook...
```

The .composer directory owned by root was already in /home/vagrant so I renamed it out of the way and left the build to run -- it completed fine with "Ensure composer directory exists" creating a new one owned by vagrant:vagrant. 

The original (renamed) .composer has a `cache` directory (containing d/l repos) in it that is mounted from the host 
`10.211.55.2:/System/Volumes/Data/Users/<my macOS username>/.vagrant.d/cache/generic/ubuntu2004`

So still hunting what/where this is mounted to see if I change the owner of creation of the parent directory.
(Likely I've done something wrong in a config file some time ago)

**Comment by jpdw** [comment]
The root:root .composer directory seems to appear during either "Running provisioner" or "Installing Ansible"
```==> edas-d8-7: Configuring cache buckets...
==> edas-d8-7: Running provisioner: drupalvm (ansible_local)...
    edas-d8-7: Installing Ansible...
```
At this point the .composer has a subdir symlinked to the host and looks to contain cached composer or ansible data (currently all black-magic to me).

For now, I've bodged around the issue with a pre-provision script to 'sudo chown' the .composer directory to vagrant:vagrant so the ansible composer tasks are happy. It's not pretty but it (now) works so I can continue my main task and try to figure out the root cause in the background.
