### ISSUE TITLE
Our site is almost finished, now we need to migrate to an actual server...are there step by step instructions for newbies?

### ISSUE THREAD

**Issue by NYCdude2** [geerlingguy/drupal-vm#2096]
### Issue Type
Support Request

Our Drupal8 site is almost finished, now we need to migrate to an actual server...are there step by step instructions for newbies?
Server OS will be Linux of some type; & current drupalVM environment is on Ubuntu 20
We want to see the instructions before we choose who we would host with & what parameters are necessary.
Are there certain things that are necessary versus recommended (eg, cPanel, etc).
Thanks in advance.

**Comment by geerlingguy** [comment]
Not really; in the end, with Drupal as with any LAMP-style application, you need to migrate your PHP code (the Drupal codebase), the database (usually a MySQL database), and any files (e.g. in Drupal's public files directory) to the new server.

You can find help with those operations elsewhere, and to get them out of Drupal VM, I recommend storing your codebase in Git, downloading your Database using Sequel Pro or mysqldump on the command line, and getting your files using SFTP or grabbing them from an NFS share in Drupal VM.
