### ISSUE TITLE
Updating to composer 2.0.0-RC2

### ISSUE THREAD

**Issue by eugenz3rr-arocom** [geerlingguy/drupal-vm#2097]
### Issue Type

 - Support Request

### Your OS

Operating System: Ubuntu 18.04.5 LTS
Kernel: Linux 5.4.0-52-generic
Architecture: x86-64

### Summary

Hi Everyone!
As composer released 2.0.0-RC2 I tried to install our dependencies using the newer composer, which I needed to update manually before I could test it properly.
Now we want to update drupalvm to use composer 2.0.0-RC2 per default on the system but we don't know how to this.
It would be nice if someone could help me with this.

**Comment by oxyc** [comment]
Try adding this to your config.yml:

```yml
composer_version: '2.0.0-RC2'
```

**Comment by eugenz3rr-arocom** [comment]
```
drush --version 
» 10.3.5

composer --version
» Composer version 2.0.0-RC2 2020-10-14 21:34:07
```

After I updated mysql wasn't usable.

**Comment by geerlingguy** [comment]
Since Composer 2 is out now, it should be installed by default. For existing instances, you can upgrade using `composer self-update --2`. Note that some projects may need other updates to make the `composer.lock` file and dependencies work correctly in Composer 2!
