### ISSUE TITLE
I am getting issue with drupal VM while running blt vm command on my mac terminal getting the below issue, Can any one please give me solution for this issue 

### ISSUE THREAD

**Issue by SaiSravanthich** [geerlingguy/drupal-vm#2104]
TASK [geerlingguy.composer : Add GitHub OAuth token for Composer (if configured).] ***
skipping: [novartis-dolphin]

TASK [geerlingguy.composer : include_tasks] ************************************
included: /Users/challsaa/novartis-dolphin/vendor/geerlingguy/drupal-vm/provisioning/roles/geerlingguy.composer/tasks/global-require.yml for novartis-dolphin

TASK [geerlingguy.composer : Install configured globally-required packages.] ***
failed: [novartis-dolphin] (item={'name': 'hirak/prestissimo', 'release': '^0.3'}) => {"ansible_loop_var": "item", "changed": true, "cmd": ["/usr/bin/composer", "global", "require", "hirak/prestissimo:^0.3", "--no-progress"], "delta": "0:00:00.395660", "end": "2020-11-10 08:41:28.064471", "item": {"name": "hirak/prestissimo", "release": "^0.3"}, "msg": "non-zero return code", "rc": 1, "start": "2020-11-10 08:41:27.668811", "stderr": "Changed current directory to /home/vagrant/.composer\n\n                                                                                                                                           \n  [InvalidArgumentException]                                                                                                               \n  Package hirak/prestissimo at version ^0.3 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  \n                                                                                                                                           \n\nrequire [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...", "stderr_lines": ["Changed current directory to /home/vagrant/.composer", "", "                                                                                                                                           ", "  [InvalidArgumentException]                                                                                                               ", "  Package hirak/prestissimo at version ^0.3 has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version  ", "                                                                                                                                           ", "", "require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]..."], "stdout": "", "stdout_lines": []}

PLAY RECAP *********************************************************************
novartis-dolphin           : ok=108  changed=1    unreachable=0    failed=1    skipped=109  rescued=0    ignored=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by SaiSravanthich** [comment]
Hello am attaching screenshot as well 
<img width="1792" alt="Screenshot 2020-11-10 at 3 32 10 PM" src="https://user-images.githubusercontent.com/74237026/98659336-01490400-236a-11eb-82d9-bb3b3f4c1542.png">

while running blt vm command on terminal i observed some depreciation warning 
TASK [geerlingguy.php-versions : Purge PHP version packages.] ******************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['php5.6-common', 
'php7.0-common', 'php7.1-common', 'php7.2-common', 'php7.3-common']` and remove
 the loop. This feature will be removed from ansible-base in version 2.11. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
ok: [novartis-dolphin] => (item=['php5.6-common', 'php7.0-common', 'php7.1-common', 'php7.2-common'])

Thanks in advance

**Comment by oxyc** [comment]
You need to remove hirak/prestissimo now that Composer v2 is used. https://github.com/geerlingguy/drupal-vm/pull/2100/files

**Comment by SaiSravanthich** [comment]
Hello for blt vm above fix is working for me Thank you!
while running blt setup in vagrant getting the below issue
Setting up local environment for site default.
Using drush alias @self
> source:build
> tests:behat:init:config
> source:build:composer
The "dealerdirect/phpcodesniffer-composer-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "ocramius/package-versions" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "cweagans/composer-patches" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "simplesamlphp/composer-module-installer" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "oomphinc/composer-installers-extender" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "zaporylie/composer-drupal-optimizations" plugin was skipped because it requires a Plugin API version ("^1.1") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "grasmash/drupal-security-warning" plugin was skipped because it requires a Plugin API version ("^1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "acquia/blt" plugin was skipped because it requires a Plugin API version ("^1.1.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
The "drupal-composer/drupal-scaffold" plugin was skipped because it requires a Plugin API version ("^1.0.0") that does not match your Composer installation ("2.0.0"). You may need to run composer update with the "--no-plugins" option.
Installing dependencies from lock file (including require-dev)
Verifying lock file contents can be installed on current platform.
Your lock file does not contain a compatible set of packages. Please run composer update.

  Problem 1
    - acquia/blt is locked to version 11.0.1 and an update of this package was not requested.
    - acquia/blt 11.0.1 requires composer-plugin-api ^1.1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 2
    - cweagans/composer-patches is locked to version 1.6.7 and an update of this package was not requested.
    - cweagans/composer-patches 1.6.7 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 3
    - dealerdirect/phpcodesniffer-composer-installer is locked to version v0.5.0 and an update of this package was not requested.
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 4
    - drupal-composer/drupal-scaffold is locked to version 2.6.1 and an update of this package was not requested.
    - drupal-composer/drupal-scaffold 2.6.1 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 5
    - grasmash/drupal-security-warning is locked to version 1.1.1 and an update of this package was not requested.
    - grasmash/drupal-security-warning 1.1.1 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 6
    - ocramius/package-versions is locked to version 1.4.0 and an update of this package was not requested.
    - ocramius/package-versions 1.4.0 requires composer-plugin-api ^1.0.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 7
    - oomphinc/composer-installers-extender is locked to version v1.1.2 and an update of this package was not requested.
    - oomphinc/composer-installers-extender v1.1.2 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 8
    - simplesamlphp/composer-module-installer is locked to version v1.1.6 and an update of this package was not requested.
    - simplesamlphp/composer-module-installer v1.1.6 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 9
    - zaporylie/composer-drupal-optimizations is locked to version 1.1.1 and an update of this package was not requested.
    - zaporylie/composer-drupal-optimizations 1.1.1 requires composer-plugin-api ^1.1 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
  Problem 10
    - acquia/blt 11.0.1 requires composer-plugin-api ^1.1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.
    - /nvs_core 1.1.1 requires acquia/blt 11.0.1 -> satisfiable by acquia/blt[11.0.1].
    - /nvs_core is locked to version 1.1.1 and an update of this package was not requested.

ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
> source:build:simplesamlphp-config
Copying config files to the appropriate place in simplesamlphp library...
[error]  Command `source:build:composer ` exited with code 2. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/ 
[error]  Command `source:build ` exited with code 1. This most likely indicates a problem with your configuration, and is not a BLT bug.
For troubleshooting guidance and support, see https://docs.acquia.com/blt/support/

**Comment by oxyc** [comment]
> ocramius/package-versions only provides support for Composer 2 in 1.8+, which requires PHP 7.4.
If you can not upgrade PHP you can require composer/package-versions-deprecated to resolve this with PHP 7.0+.
>
> You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 

So you can either update the dependency (and maybe others), and use PHP 7.4 or you can lock Composer to v1 by adding this to your config.yml: `composer_version: 1.10.16` (in which case prestissimo mentioned earlier can be kept)

**Comment by geerlingguy** [comment]
This sounds like an issue where BLT will need to do some updates to their code to make sure it's not installing outdated packages.

**Comment by SaiSravanthich** [comment]
Hello, My blt issue got resolved by downgrading the composer version to 1+ (composer self-update 1.10.8) .. Now working fine 

Thanks for the support
