### ISSUE TITLE
MariaDB version installed is too low for the default Drupal 9 installation

### ISSUE THREAD

**Issue by vaccinemedia** [geerlingguy/drupal-vm#2111]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.0
ansible 2.10.3
  config file = None
  configured module search path = ['/Users/grahambrown/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/2.10.3_1/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.0 (default, Nov 21 2020, 14:01:55) [Clang 11.0.0 (clang-1100.0.33.17)]
the box is the parallels Bento Ubuntu 18 one
```

### Your OS

 - **macOS** (Mojave 10.14.6)

### Full console output

https://gist.github.com/vaccinemedia/0211b79b9b5ea56ca01ad6fd594e5540

### Summary

By adding:

mysql_packages:
  - mariadb-client
  - mariadb-server
  - python-mysqldb

in config.yaml and keeping the Drupal version at 9 fails at the end of vagrant up / provision due to MariaDB being at 10.1.47-MariaDB-0ubuntu0.18.04.1 and needing to be at least 10.3.7

**Comment by geerlingguy** [comment]
@vaccinemedia - It looks like you're using a different base box ("the box is the parallels Bento Ubuntu 18 one")—the base drupal-vm box is built on 18.04 as well (https://github.com/geerlingguy/packer-drupal-vm), but I haven't encountered any issues with the defaults set up in the latest version of Drupal VM (6.0.2 currently).

What version of Drupal VM are you using?

**Comment by vaccinemedia** [comment]
I'm using the latest Drupal VM downloaded this morning and to be more specific the box I was using was:
vagrant_box: bento/ubuntu-18.04

Ubuntu 18.04 installs MariaDB 10.1 by default:
https://computingforgeeks.com/install-mariadb-10-on-ubuntu-18-04-and-centos-7/

You have to add the MariaDB repo which then allows you to install MariaDB 10.4

I managed to fix my own personal issue by using:
vagrant_box: bento/ubuntu-20.04

And:
mysql_packages:
  - mariadb-client
  - mariadb-server

i.e. I removed the line
  - python-mysqldb

As python-mysqldb is no longer available in Ubuntu 20.04. This allowed me to provision fully.

**Comment by geerlingguy** [comment]
@vaccinemedia - I guess maybe there are some other changes I'm not seeing that you may have made?

I just brought up the default Drupal VM locally, and Drupal installs without issue and shows in the status report:

```
Database Version
5.7.31-0ubuntu0.18.04.1-log
System
MySQL, Percona Server, or equivalent
```

Are you making other modifications to your `config.yml` to try to switch it to MariaDB?

**Comment by vaccinemedia** [comment]
The only changes I have made are to get it to work are the Ubuntu version -> 20.04 and to use MariaDB. It looks from your status you're not using MariaDB? Here's my status:
Database Version
5.5.5-10.3.25-MariaDB-0ubuntu0.20.04.1-log
System
MySQL, MariaDB, Percona Server, or equivalent

**Comment by geerlingguy** [comment]
Ah, you're on 20.04. I haven't yet updated all of Drupal VM's defaults to work on 20.04 (it defaults to 18.04 currently), so that's where the disconnect is.

At some point I should probably upgrade defaults to 20.04...

**Comment by vaccinemedia** [comment]
True. Funny thing is - when I was younger I always wanted the latest and greatest when it came to software. Since becoming a Drupal site builder especially since Drupal 7 or more likely 8 using composer, I've actually been much more reserved when t comes to server setups. I think my main cloud is still Ubuntu 16 (but I've recently bought a new one which is 18). This is because backwards compatibility isn't really a thing when it comes to server side apps.

You could certainly make Ubuntu 20.04 the default but I'm wondering... is there a way to make the provisioning scripts install the latest version of MariaDB on Ubuntu 18.04 as per this article for people who want to use Ubuntu 18.04 AND MariaDB with Drupal 9?
https://computingforgeeks.com/install-mariadb-10-on-ubuntu-18-04-and-centos-7/

The reason I even installed (or wanted to install) MariaDB instead of MySQL is that when importing a database on the default Drupal VM install it was taking waaaaay much longer than I'm used to on my previous setup which was provisioned using the now gone (but not forgotten) puphpet - like go and make a brew and you're still waiting longer - whereas with MariaDB (on Drupal VM too) it's approx 1 minute to import a 1GB database. Much much quicker.

**Comment by geerlingguy** [comment]
@vaccinemedia - For now I'm not planning on changing the default for 18.04, but for those who want to make the switch, it's not too difficult (though it's also not too well documented either!).
