### ISSUE TITLE
Xdebug is not working in drush commad in DrupalVM (Drush+xdebug+VScode+vagrant)

### ISSUE THREAD

**Issue by naresh-qed42** [geerlingguy/drupal-vm#2116]
I have installed Drupal 9 in DrupalVM,
For Drush commands (migrate:import) xdebug is not triggering in VScode, but xdebug is working fine for browser requests

### Environment
```
Vagrant 2.2.1
macOS Catalina 10.15.7
Visual studio code 1.15.1
```

### OS

 - **macOS** (10.15.7)

### Summary

config.yml file
```

installed_extras: [adminer, selenium, drush, mailhog, memcached, nodejs, solr, xdebug]

# XDebug configuration.
php_xdebug_version: 2.7.1
# Change this value to 1 in order to enable xdebug by default.
php_xdebug_default_enable: 1
php_xdebug_cli_disable: no
php_xdebug_remote_port: "9000"
php_memory_limit: "512M"
```

configured vscode with configuration,
```
       "port": 9000,
      "pathMappings": {
        "/var/www/drupal9/docroot" : "/Users/user_name/vagrant-projects/drupal9/docroot"
      }
    },
    {
      "name": "Launch currently open script",
      "type": "php",
      "request": "launch",
      "program": "${file}",
      "cwd": "${fileDirname}",
      "port": 9000
    }
```
Also tried like this 
``` PHP_OPTIONS="-d xdebug.default_enable=1" drush @drupalvm.drupalvm migrate-import ```

**Comment by kekkis** [comment]
Have you tried invoking the project-specific drush instead of the launcher? It's probably located somewhere like `/var/www/drupal9/vendor/drush/drush/drush`.

**Comment by naresh-qed42** [comment]
Now I have removed VScode and installed phpstrom, but still not able to install xdebug+drush+phpstorm

I have tried it with `/var/www/mwn/vendor/drush/drush/drush migrate:import my_commnad`
but no luck

thanks @kekkis for looking into it

**Comment by kekkis** [comment]
For me xdebug + drush + phpstorm works at least when using commands like `/var/www/drupal9/vendor/drush/drush/drush` or `/var/www/drupal9/vendor/bin/drush`, but for the connection to be established I need to have the environment variable `XDEBUG_CONFIG` set correctly. In my case the complete command becomes:

```
XDEBUG_CONFIG="idekey=PHPSTORM" /var/www/drupal9/vendor/bin/drush
```

Let's hope you will be able to figure yours out. The idekey value equals the one set up in PhpStorm's debug config.
