### ISSUE TITLE
 no implicit conversion of nil into String

### ISSUE THREAD

**Issue by compagnat** [geerlingguy/drupal-vm#2117]
### Issue Type
 - Bug Report / Support Request

### Your Environment
Vagrant 2.2.14
VirtualBox 6.1.16 r140961 (Qt5.6.2)

### Your OS

 - **Windows** Microsoft Windows 10 Entreprise - 10.0.18363 N/A version 18363

### Full console output

PS C:\dev\workspace\drupal\drup-t2\drupal-vm> git status
On branch master
Your branch is up to date with 'origin/master'.

nothing to commit, working tree clean

PS C:\dev\workspace\drupal\drup-t2\drupal-vm> vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  www.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
Traceback (most recent call last):
        26: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        25: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
        24: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
        23: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
        22: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
        21: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
        20: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        19: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        18: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        17: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
        16: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        15: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        14: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        13: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:43:in `call'
        12: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        11: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        10: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
         9: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
         8: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         7: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/created.rb:15:in `call'
         6: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         5: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/commands/up/middleware/store_box_metadata.rb:33:in `call'
         4: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         3: from C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
         2: from C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:99:in `addHostEntries'
         1: from C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `addToHosts'
C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `+': no implicit conversion of nil into String (TypeError)

```

**With the debug mode, I've receive the following error :**

```

 INFO interface: info: Bringing machine 'drupalvm' up with 'virtualbox' provider...
Bringing machine 'drupalvm' up with 'virtualbox' provider...
 INFO batch_action: Enabling parallelization by default.
 INFO batch_action: Disabling parallelization because provider doesn't support it: virtualbox
 INFO batch_action: Batch action will parallelize: false
 INFO batch_action: Starting action: #<Vagrant::Machine:0x00000000074b7c68> up {:destroy_on_error=>true, :install_provider=>false, :parallel=>true, :provision_ignore_sentinel=>false, :provision_types=>nil, :provider=>"virtualbox"}
 INFO machine: Calling action: up on provider VirtualBox (new VM)
DEBUG environment: Attempting to acquire process-lock: machine-action-032caa5db9252d24eb27c670c70b3608
DEBUG environment: Attempting to acquire process-lock: dotlock
 INFO environment: Acquired process lock: dotlock
 INFO environment: Released process lock: dotlock
 INFO environment: Acquired process lock: machine-action-032caa5db9252d24eb27c670c70b3608
 INFO interface: Machine: action ["up", "start", {:target=>:drupalvm}]
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x00000000074099b0>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::CheckVirtualbox:0x0000000007edc590>
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\dev\tools\VirtualBox\
 INFO base: VBoxManage path: C:\dev\tools\VirtualBox\VBoxManage.exe
DEBUG meta: Finding driver for VirtualBox version: 6.1.16
 INFO meta: Using VirtualBox driver: VagrantPlugins::ProviderVirtualBox::Driver::Version_6_1
DEBUG base: Windows, checking for VBoxManage on PATH first
DEBUG base: Windows. Trying VBOX_INSTALL_PATH for VBoxManage
DEBUG base: VBOX_INSTALL_PATH value: C:\dev\tools\VirtualBox\
 INFO base: VBoxManage path: C:\dev\tools\VirtualBox\VBoxManage.exe
 INFO subprocess: Starting process: ["C:\\dev\\tools\\VirtualBox\\VBoxManage.exe", "list", "hostonlyifs"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: Name:            VirtualBox Host-Only Ethernet Adapter
GUID:            29072b4d-0eb2-4be5-b0f7-c6adc7e408e8
DHCP:            Disabled
IPAddress:       192.168.56.1
NetworkMask:     255.255.255.0
IPV6Address:     fe80::7083:f172:c993:cb05
IPV6NetworkMaskPrefixLength: 64
HardwareAddress: 0a:00:27:00:00:04
MediumType:      Ethernet
Wireless:        No
Status:          Up
VBoxNetworkName: HostInterfaceNetworking-VirtualBox Host-Only Ethernet Adapter

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "Write-Output $PSVersionTable.PSVersion.Major"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stdout: 5
DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 30
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-WindowsOptionalFeature : Le jeu de paramètres ne peut pas être résolu à l'aide des paramètres nommés spécifiés.
Au caractère Ligne:1 : 3
+ $(Get-WindowsOptionalFeature -FeatureName Microsoft-Hyper-V-Hyperviso ...
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument : (:) [Get-WindowsOptionalFeature], ParameterBindingException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO subprocess: Starting process: ["C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\/powershell.EXE", "-NoLogo", "-NoProfile", "-NonInteractive", "-ExecutionPolicy", "Bypass", "-Command", "$(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State"]
 INFO subprocess: Command not in installer, restoring original environment...
DEBUG subprocess: Selecting on IO
DEBUG subprocess: stderr: Get-WindowsFeature : Le terme «Get-WindowsFeature» n'est pas reconnu comme nom d'applet de commande, fonction, fichier
de script ou programme exécutable. Vérifiez l'orthographe du nom, ou si un chemin d'accès existe, vérifiez que le
chemin d'accès est correct et réessayez.
Au caractère Ligne:1 : 3
+ $(Get-WindowsFeature -FeatureName Microsoft-Hyper-V-Hypervisor).State
+   ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-WindowsFeature:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
DEBUG subprocess: Exit status: 0
 INFO warden: Calling IN action: #<Vagrant::Action::Builtin::Call:0x0000000007f06250>
 INFO runner: Running action: machine_action_up #<Vagrant::Action::Builder:0x0000000007f06c28>
 INFO warden: Calling IN action: #<VagrantPlugins::ProviderVirtualBox::Action::Created:0x0000000007f7fa88>
 INFO warden: Calling IN action: #<VagrantPlugins::CommandUp::StoreBoxMetadata:0x0000000007f7fa60>
DEBUG storeboxmetadata: Writing box metadata file to C:/dev/workspace/drupal/drup-t2/drupal-vm/.vagrant/machines/drupalvm/virtualbox/box_meta
 INFO warden: Calling IN action: #<VagrantPlugins::HostsUpdater::Action::UpdateHosts:0x0000000007f9ca70>
 INFO interface: info: [vagrant-hostsupdater] Checking for host entries
 INFO interface: info: ==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
 INFO interface: info: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
 INFO interface: info: ==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (C:/WINDOWS/system32/drivers/etc/hosts)
 INFO interface: info: [vagrant-hostsupdater]   192.168.88.88  drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
[vagrant-hostsupdater]   192.168.88.88  www.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
[vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
[vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
[vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
[vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
 INFO interface: info: ==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  www.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  www.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.test  # VAGRANT: d41d8cd98f00b204e9800998ecf8427e (drupalvm) /
ERROR warden: Error occurred: no implicit conversion of nil into String
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: no implicit conversion of nil into String
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x0000000007f06250>
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-032caa5db9252d24eb27c670c70b3608
 INFO environment: Running hook: environment_unload
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x0000000007fff990>
Traceback (most recent call last):
        26: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/batch_action.rb:86:in `block (2 levels) in run'
        25: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `action'
        24: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:201:in `call'
        23: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/environment.rb:613:in `lock'
        22: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:215:in `block in action'
        21: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/machine.rb:246:in `action_raw'
        20: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        19: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        18: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
        17: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
        16: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        15: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/check_virtualbox.rb:26:in `call'
        14: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
        13: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builtin/call.rb:43:in `call'
        12: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `run'
        11: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/util/busy.rb:19:in `busy'
        10: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/runner.rb:89:in `block in run'
         9: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/builder.rb:149:in `call'
         8: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         7: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/providers/virtualbox/action/created.rb:15:in `call'
         6: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         5: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/plugins/commands/up/middleware/store_box_metadata.rb:33:in `call'
         4: from C:/dev/tools/Vagrant/embedded/gems/2.2.14/gems/vagrant-2.2.14/lib/vagrant/action/warden.rb:48:in `call'
         3: from C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:17:in `call'
         2: from C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:99:in `addHostEntries'
         1: from C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `addToHosts'
C:/Users/ads12759/.vagrant.d/gems/2.6.6/gems/vagrant-hostsupdater-1.2.0/lib/vagrant-hostsupdater/HostsUpdater.rb:152:in `+': no implicit conversion of nil into String (TypeError)

### Summary

I follow the quick setup guide : vagrant up with no modification in any file.

**Comment by geerlingguy** [comment]
Please see: https://github.com/geerlingguy/drupal-vm/issues/2112

**Comment by compagnat** [comment]
Thanks, I didn't look properly...
You're too fast
