### ISSUE TITLE
Replace unused php_opcache_enabled_in_ini with php_opcache_enable

### ISSUE THREAD

**Issue by phizev** [geerlingguy/drupal-vm#2122]
### Issue Type

 - Bug Report

### Your OS
 - **OS Agnostic**

### Full console output
N/A

### Summary

The php_opcache_enabled_in_ini was removed from ansible-role-php in commit b9f0a61.

This means that within Drupal VM, the only place I can find php_opcache_enabled_in_ini is in default.config.yml. Switching this out for the php_opcache_enable will allow toggling the state of the opcache. #2121 is a PR for this minor issue.

**Comment by geerlingguy** [comment]
Fixed in PR!
