### ISSUE TITLE
VM hangs every 10-15 minutes on Windows with winnfsd, requires reload

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2126]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.14
VirtualBox 6.1
```

### Your OS
Windows 10

### Summary

I have an old Drupal project where it is not possible to update the Drupal VM version. That's okay, it is working with an older Drupal VM.

But now I started to develop Drupal 9 projects. Therefore I have installed a new/second Drupal VM on my Windows 10 computer.

After updating Vagrant to 2.2.14 I found out that the winnfsd vagrant plugin had to be installed. After installation of winnfsd everything seemed to be okay, but some file permission problems occurred (had to edit and save settings.php and .htaccess in Windows, this seems to solve the problem).

After using the new Drupal VM for a white I found out, it hangs up every 10-15 minutes. I did a lot of research on this. Nobody seems to have a solution for this problem.
Restarting the VM with vagrant reload takes a long time. 

I do NOT want to have a VM that hangs up every 10 or 15 minutes, sometimes earlier!

I did everything to find a solution.
I uninstalled winnfsd plugin. The result is that composer throws a lot of errors like "could not delete file" and similar problems. This is unsolvable. Composer is NOT working in the VM without problems not even Composer 2. The main problems are caused by the Synced folders.

Working with Drupal 9 it is unthinkable not to use composer. And I do NOT want to use composer in Windows. If there is a VM then it must also work with composer.

I tried a lot, tried to solve the composer problems (without winnfs), tried to find a solution for the periodical hangups, but I failed. 

**I think there is no solution and therefore one could argue the Drupal VM is dead!**

Is it not?
**Is there any solution that really works sustainably?**
Which?

What does the future of Drupal VM look life if these seemingly unsolvable problems can not be solved?

**Comment by geerlingguy** [comment]
> After using the new Drupal VM for a white I found out, it hangs up every 10-15 minutes. I did a lot of research on this.
> Nobody seems to have a solution for this problem.
> Restarting the VM with vagrant reload takes a long time.

I've never heard of this issue (this is the first report I've seen in the Drupal VM issue queue), but it sounds like something that, if it were happening to everyone, would be more widely reported. Just from the fact that it's not something I've seen elsewhere, I wonder if there could be some sort of virus scanner, networking proxy, or VPN installed on your computer that could cause some conflict?

Anyways, Drupal VM is certainly not 'dead', but it is currently in a mostly-maintenance-only mode.

**Comment by webprogrammierer** [comment]
The new title does not contain all the problems:
- synced folders problems
- composer not working within synced folders without winnfsd
- winnfsd hangs up every 10-15 minutes
- Invest an infinite amount of time to get it running, in the end there is no solution to the problem

**Comment by webprogrammierer** [comment]
Is there a chance to find the reasons why it hangs up periodically? How?

**Comment by geerlingguy** [comment]
@webprogrammierer - If you're using winnfsd, I'd imagine trying to follow logs on Windows somewhere would help. But note that in that other thread, it was recommended to _not_ use NFS on windows for the reason that it seemed to sometimes just lock up randomly :(

SMB might work better, and it's what I've used successfully in the past developing on Windows 7, 8, and 10.

**Comment by webprogrammierer** [comment]
SMB isn't to slow?

**Comment by webprogrammierer** [comment]
SMB isn't too slow?

I used the standard config.yml of Drupal VM for years and it was not so slow. Using vagrant 2.2.9.

Now with vagrant 2.2.14 it is not possible to use standard config.yml anymore without a lot of problems?

**Comment by webprogrammierer** [comment]
If it hangs up in the shared folders the following command do not work (no reaction, no command prompt):
ls
ls -la
cd ..

**Comment by webprogrammierer** [comment]
When I am working in the shell (using ubuntu commands or using composer ...) then it does not hang up as early. 
If the shell is not used it hangs up much earlier.

**Comment by webprogrammierer** [comment]
The generell problem of this thread are the synced folders and composer.

This has been discussed for four years and more:
https://github.com/geerlingguy/drupal-vm/issues/1262
https://github.com/geerlingguy/drupal-vm/issues/733

Is there any solution to get Drupal VM work again or should we develop Drupal 9 projects without a Drupal VM (Xampp etc. on Windows instead)?

**Comment by webprogrammierer** [comment]
> If you're using winnfsd, I'd imagine trying to follow logs on Windows somewhere would help.

I can not find any logs on Windows for this.

**Comment by daje4197** [comment]
Im new to Ubuntu but to solve the problem i need to replace the NFS with SMB. am i right? 
how can i remove NFS and replace it with SMB correctly without destroying my current Projekt?

**Comment by webprogrammierer** [comment]
Do you also have the same problem? 
Hangs your VM if using winnfsd plugin? How often?

I think you have to change the settings in config.yml file and do a vagrant provision (maybe vagrant halt, vagrant up before).

**Comment by cf74** [comment]
I have the same problem: Drupal VM hangs up after some time.
Any solution?

**Comment by cf74** [comment]
solution : removed VPN

**Comment by webprogrammierer** [comment]
You removed the VPN?
In default.config.yml file the vpn is not active:
`vagrant_public_ip: ""`

How and where did you remove the vpn? Which changed did you make in which file?
Does it really never hang up?
Thank you.

**Comment by cf74** [comment]
I removed the latest "Cisco AnyConnect software client" from macos big sur.
It really never hand up now.

**Comment by webprogrammierer** [comment]
I don't have a Mac. I am using Windows 10.
As far as I know I have no VPN enabled.

**How did you find out** that you have to remove this AnnyConnect client?

**Comment by webprogrammierer** [comment]
Please do not forget to answer. It is important.

**Comment by eigentor** [comment]
The NFS share appears to be a big source of problems. 
So trying to use Samba may be more stable.
Blog post from Jeff Geerling how to do that here, it is quite detailed:
https://www.jeffgeerling.com/blog/2017/drupal-vm-on-windows-fast-container-blt-project-development

**Comment by webprogrammierer** [comment]
All these solutions are too complicated.
I only want to do some configuration in config.yml followed by a vagrant up.

Otherwise we do not need the Drupal VM if so much has to be done manually.

I do not understand, why nobody is interested in solving the problem by removing the hangups instead of using another solution.

So please help to find out WHY it hangs up and what to do against the hang ups.

**Comment by daje4197** [comment]
@webprogrammierer your Problem resulting in the NFS plugin. 
if you go in idle for 5 Minutes the VM will close the connection.
but anyway to apply changes in the config.yml just type:
vagrant provision

**Comment by webprogrammierer** [comment]
Thank you. @daje4197 @eigentor @geerlingguy @cf74 

> but anyway to apply changes in the config.yml just type:
> vagrant provision

This is not related to the question here. This is something that everybody knows.


> if you go in idle for 5 Minutes the VM will close the connection.

**I think this could be a real hint**: Is it really true that the VM closes a connection after 5 minutes of doing nothing?

What connection is closed?
Why it is closed?
I have been using Drupal VM (**without winnfsd**) for many many years but never really never the VM closed the connection (still not if running idle 10 hours long).

So why should this problem occur now if using winnfsd plugin?
If this is really correct, there must be a simple solution (for example making a patch for winnfsd plugin software).

How could the solution look like?
