### ISSUE TITLE
Where can I find the rsync folder with my virtual machine?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2127]
### Issue Type
Support Request

### Your Environment
Vagrant 2.2.14
VirtualBox 6.1

### Your OS
Windows 10

I tried rsync synced folders in my drupal VM (enabled in config.yml).

After vagrant up all my Drupal folders have been synced / copied to an internal path within the VM.
cygdrive ?
cygwin ?

But I think after vagrant halt all the thousands of files within my VM where not deleted.

I do not want all the files to have within my VM because I will not use rsynced folders.

How can I find the path to the rsynced folders of my Drupal files? Where they are located within my VM? How can I delete them?

Thank you.

**Comment by geerlingguy** [comment]
Check your `config.yml` file—the default path is the `destination` (see https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L27-L34). You can override that destination to change the path where files are synced to.

**Comment by webprogrammierer** [comment]
On vagrant up I saw folders like /cygwin/c/.... or ../cygdrive/d/ ... I can not remember.
