### ISSUE TITLE
Many output lines from [vagrant-hostsupdater] on vagrant up

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2128]
### Issue Type
- Support Request

### Your Environment
Vagrant 2.2.14
VirtualBox 6.1

### Your OS
Windows 10

### Full console output

λ vagrant up
Bringing machine 'drupalvm2' up with 'virtualbox' provider...
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> drupalvm2: Checking if box 'geerlingguy/drupal-vm' version '2.0.10' is up to date...
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)
==> drupalvm2: Setting the name of the VM: drupalvm2.test
==> drupalvm2: Clearing any previously set network interfaces...
==> drupalvm2: Preparing network interfaces based on configuration...
    drupalvm2: Adapter 1: nat                                                                                                     
    drupalvm2: Adapter 2: hostonly                                                                                                
==> drupalvm2: Forwarding ports...                                                                                                
    drupalvm2: 22 (guest) => 2222 (host) (adapter 1)                                                                              
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: Running 'pre-boot' VM customizations...                                                                            
==> drupalvm2: Booting VM...                                                                                                      
==> drupalvm2: Waiting for machine to boot. This may take a few minutes...                                                        
    drupalvm2: SSH address: 127.0.0.1:2222                                                                                        
    drupalvm2: SSH username: vagrant                                                                                              
    drupalvm2: SSH auth method: private key                                                                                       
==> drupalvm2: Machine booted and ready!                                                                                          
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
[drupalvm2] GuestAdditions 6.1.12 running --- OK.                                                                                 
==> drupalvm2: Checking for guest additions in VM...                                                                              
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                
==> drupalvm2: [vagrant-hostsupdater] Checking for host entries                                                                   
==> drupalvm2: [vagrant-hostsupdater] Skipping adding host entries (config.vm.network hostsupdater: "skip" is set)                

### Summary

There are a lot of lines from hotsupdater. Is this okay?
Why so many hostsupdater lines? When is such a line printed? On any synced folder?

Additionally to the existing drupal project I added two further drupal projects with two new synced folders.

Is there a way to check if this outpout is okay?

**Comment by geerlingguy** [comment]
This is a problem that was introduced in one of the latest versions of Vagrant, so there's nothing I can do in Drupal VM to make it any better. It's definitely annoying.

See: https://github.com/agiledivider/vagrant-hostsupdater/issues/187#issuecomment-734939967

**Comment by webprogrammierer** [comment]
I agree with you.

That's one reason why I change back from vagrant 2.2.14 to 2.2.9. 
2.2.9 is really good :-)
