### ISSUE TITLE
Not able to send mails

### ISSUE THREAD

**Issue by subhojit777** [geerlingguy/drupal-vm#213]
I was trying to send mail using `drupal_mail()` and I got this message:

> WD mail: Error sending e-mail (from no-reply@mail.com to name@mail.com).                                                               [error]
> Unable to send e-mail. Contact the site administrator if the problem persists.

I checked mail logs and found this:

> Aug 27 09:09:04 drupalvm sSMTP[4260]: Unable to connect to "localhost" port 1025.
> Aug 27 09:09:04 drupalvm sSMTP[4260]: Cannot open localhost:1025

In the documentation its written to access http://drupaltest.dev:8025/ to check mails. I think the port should be 1025, and domain should be drupalvm.dev (as per domain in `config.yml`). Also I was trying to access http://drupalvm.dev:1025 and http://drupalvm.dev:8025 but everytime it got timed out. I was hoping that I will see the mail UI.

**Comment by subhojit777** [comment]
I tried adding 1025 in `firewall_allowed_tcp_ports` and then did `vagrant reload`, but its not working.

**Comment by geerlingguy** [comment]
It soun like maillog isn't started correctly. Is it in your list of installed_extras?

**Comment by subhojit777** [comment]
Its there

```
installed_extras:
  - adminer
  - mailhog
  - memcached
  - pimpmylog
  # - selenium
  # - solr
  - varnish
  - xdebug
  - xhprof
```

**Comment by geerlingguy** [comment]
Can you log in and do a `sudo service mailhog status` and see what's going on? It might need a manual restart for some reason.

**Comment by subhojit777** [comment]
It says "MailHog not running"

On Thu, Aug 27, 2015 at 6:40 PM, Jeff Geerling <notifications@github.com>
wrote:

> Can you log in and do a sudo service mailhog status and see what's going
> on? It might need a manual restart for some reason.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geerlingguy/drupal-vm/issues/213#issuecomment-135420634>
> .
>



-- 
Regards,
Subhojit Paul
*Number:* +919836315593
*Skype:* subhojit.paul21

**Comment by geerlingguy** [comment]
Please try manually starting it with `sudo service mailhog start`, then visit the mailhog interface on port 8025, and see if it loads.

**Comment by subhojit777** [comment]
I executed the command and then it returned message "Starting mailhog" (pretty quickly). The interface is not loading.

**Comment by geerlingguy** [comment]
The start is pretty quick (it takes a couple seconds after it reports "Starting mailhog." to actually start, but once that's done, you should be able to visit http://drupalvm.dev:8025/ in your browser and see the MailHog UI. If that's not happening, MailHog seems to not be starting up on your VM.

You may need to rebuild the VM, but can you also try running the following and see what happens?

```
/opt/mailhog/mailhog
```

When I run that command (if MailHog is not running), I get:

```
$ /opt/mailhog/mailhog
2015/08/27 15:12:24 Using in-memory storage
[HTTP] Binding to address: 0.0.0.0:8025
2015/08/27 15:12:24 [SMTP] Binding to address: 0.0.0.0:1025
Creating API v1
Creating API v2
```

**Comment by subhojit777** [comment]
Now its loading. Actually earlier I was trying with port 1025, now I tried with the link you gave and it worked.

BTW, the Mailhog service is not starting automatically. I have to manually start it using command `sudo service mailhog start`. Is there anything I have to add this in `config.yml`. Also in enabled port settings in `config.yml` do I have to specify the allowed port numbers, mine has 1025 added.

**Comment by subhojit777** [comment]
BTW thanks man :smile: I have shifted from MAMP to VM. This thing is awesome and truly appreciate your quick responses :+1:

**Comment by geerlingguy** [comment]
@subhojit777 - Port 1025 is only used for sending mail, so it doesn't need to be open in the firewall's allowed TCP ports (since that's only for external traffic into the VM). Only port 8025 is required for loading the UI from outside the VM.

And yeah, I've noticed Mailhog doesn't start at system boot, so I'm going to look into that.

**Comment by geerlingguy** [comment]
@subhojit777 - Thanks for the kind words! I'm moving the bugfix portion of this over to #215.
