### ISSUE TITLE
How to setup Drupal VM with SMB synced folders

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2130]
### Issue Type
Support Request

### Your Environment
Vagrant 2.2.14
VirtualBox 6.1

### Your OS
Windows 10

### Summary

How to setup/configure SMB on windows?
How to get login data (user password) which are needed on vagrant up (with smb synced folders)?
How to get get Drupal VM run with SMB synced folder, what steps have to be done before vagrant up?

Thank you very much.

**Comment by geerlingguy** [comment]
See: http://docs.drupalvm.com/en/latest/other/performance/#improving-performance-on-windows

You would change the `type` of a shared directory in your configuration to `smb`, and then `vagrant halt` and `vagrant up`. Vagrant should take care of all the other details for you.

**Comment by webprogrammierer** [comment]
Yes, this part is not the problem.

My question was how to setup SMB on windows. After vagrant up (with smb in config.yml) I am asked for a SMB password.   What is this for? Where can I get this password? And further on?

**Comment by geerlingguy** [comment]
@webprogrammierer - I believe that password is just the same as your user account (or an administrator account).

Note that most of these things are documented through Vagrant's documentation: https://www.vagrantup.com/docs/synced-folders/smb

**Comment by webprogrammierer** [comment]
Yes maybe. But user account from what??? User account from windows computer?  If so there should be a text that tells me what kind of user account password I need for SMB. 
There are user accounts everywhere, I can not guess the right one.

Somebody knows what kind of user account is needed for SMB?
