### ISSUE TITLE
Comparison of Drupal VM, DDEV-Local and WSL (Windows Subsystem for Linux)

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#2133]
### Issue Type
Diskussion to find out more about the possibilities in web development with Drupal VM 

### Your Environment
Vagrant 2.2.9 (not 2.2.14!)
VirtualBox

### Your OS
Windows 10

### Summary

I am wondering if there are other methods of Drupal 9 development similar to Drupal VM and want to find out the differences and benefits of these 3:

- Ubuntu VM (Drupal VM)
- DDEV local (running in Docker?)
- WSL (Windows Subsystem for Linux)

I am using Drupal VM for many years on my Windows 10 computer.
I have never used DDEV and never used WSL.  But I really want to test DDEV local.

Would be great to discuss the differences between these 3 methods and which of them is better more suitable in which situation.

Starting from my Window 10 computer .... 
Will DDEV local run on Windows? Does it use Linux? Full web dev environment (apache, mysql, mailhog, adminer, ...)?
Not much to configure in DDEV local?

WSL uses Linux (comparable to a webhosting environment), but I have to install and configure my Linux by myself and have to know much about Linux? Is this correct? Much to config and a lot of command line ..?

Ubuntu VM (Drupal VM) is still in 2021 a good concept for web development or not anymore? Also comparable to webhosting/webserver environment. No container, all projects in one VM. The shared folder Composer problem is very annoying. But still good/better than developing in DDEV local or WSL?

And are there any other similar methods to the 3 listed above?

**Comment by geerlingguy** [comment]
These kind of questions would be better suited for a forum like [Drupal Answers](https://drupal.stackexchange.com) or the official [Drupal Slack](https://www.drupal.org/community/contributor-guide/reference-information/talk/tools/slack)—I like to keep this issue queue focused on things that are relevant to the maintenance/bugs/installation of Drupal VM itself.

And many of the users of something like DDEV would probably not be monitoring this issue queue, so if you want some good opinions there you'll need to go elsewhere.
