### ISSUE TITLE
geerlingguy/drupal-vm (virtualbox, 2.0.10) with PHP 7.3 fails to provision

### ISSUE THREAD

**Issue by beanjammin** [geerlingguy/drupal-vm#2134]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.14
VirtualBox 6.1.16r140961

Command 'ansible' not found, but can be installed with:

sudo apt install ansible
```

### Your OS

 - **Linux** (ubuntu 20.04)

### Full console output

https://gist.github.com/beanjammin/7a84b6ef59fb11b320d4396a206ad704

### Summary

When attempting to use geerlingguy/drupal-vm (virtualbox, 2.0.10) with PHP 7.3 the initial provisioning step fails with the following error:

Starting The PHP 7.3 FastCGI Process Manager...\r\nJan 20 00:02:18 test-local php-fpm7.3[11514]: [20-Jan-2021 00:02:18] ERROR: unable to bind listening socket for address '127.0.0.1:9000': Address already in use

SSHing into the vagrant box and running `dpkg -l | grep php` shows php packages from php 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, and 8.0 are installed:

ii  php-apcu                               5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php-common                             2:76+ubuntu18.04.1+deb.sury.org+9                      all          Common files for PHP packages
ii  php-yaml                               2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php5.6-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php5.6-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php7.0-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php7.0-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php7.1-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php7.1-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php7.2-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php7.2-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php7.3                                 7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.3-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php7.3-bz2                             7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        bzip2 module for PHP
ii  php7.3-cli                             7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        command-line interpreter for the PHP scripting language
ii  php7.3-common                          7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        documentation, examples and common module for PHP
ii  php7.3-curl                            7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        CURL module for PHP
ii  php7.3-dev                             7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        Files for PHP7.3 module development
iF  php7.3-fpm                             7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.3-gd                              7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        GD module for PHP
ii  php7.3-imagick                         3.4.4+php8.0+3.4.4-1+ubuntu18.04.1+deb.sury.org+1      amd64        Provides a wrapper to the ImageMagick library
ii  php7.3-imap                            7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        IMAP module for PHP
ii  php7.3-json                            7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        JSON module for PHP
ii  php7.3-mbstring                        7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        MBSTRING module for PHP
ii  php7.3-mysql                           7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        MySQL module for PHP
ii  php7.3-opcache                         7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        Zend OpCache module for PHP
ii  php7.3-readline                        7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        readline module for PHP
ii  php7.3-sqlite3                         7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        SQLite3 module for PHP
ii  php7.3-xml                             7.3.26-1+ubuntu18.04.1+deb.sury.org+1                  amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.3-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php7.4                                 7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   all          server-side, HTML-embedded scripting language (metapackage)
ii  php7.4-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php7.4-cli                             7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        command-line interpreter for the PHP scripting language
ii  php7.4-common                          7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        documentation, examples and common module for PHP
ii  php7.4-curl                            7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        CURL module for PHP
ii  php7.4-dev                             7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        Files for PHP7.4 module development
ii  php7.4-fpm                             7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        server-side, HTML-embedded scripting language (FPM-CGI binary)
ii  php7.4-gd                              7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        GD module for PHP
ii  php7.4-imap                            7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        IMAP module for PHP
ii  php7.4-json                            7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        JSON module for PHP
ii  php7.4-mbstring                        7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        MBSTRING module for PHP
ii  php7.4-mysql                           7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        MySQL module for PHP
ii  php7.4-opcache                         7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        Zend OpCache module for PHP
ii  php7.4-readline                        7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        readline module for PHP
ii  php7.4-sqlite3                         7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        SQLite3 module for PHP
ii  php7.4-xml                             7.4.9-1+ubuntu18.04.1+deb.sury.org+1                   amd64        DOM, SimpleXML, XML, and XSL module for PHP
ii  php7.4-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP
ii  php8.0-apcu                            5.1.19+4.0.11-2+ubuntu18.04.1+deb.sury.org+4           amd64        APC User Cache for PHP
ii  php8.0-yaml                            2.2.1+2.1.0+2.0.4+1.3.2-1+ubuntu18.04.1+deb.sury.org+1 amd64        YAML-1.1 parser and emitter for PHP

It looks like the ansible task to remove packages from other versions of PHP is not working.

If I remove version 2.0.10 and use 2.0.9 then vagrant provisions properly and only PHP 7.3 packages are installed.  Alternatively, if I specify PHP 7.4 then 2.0.10 works as expected.

**Comment by AshwinParmar** [comment]
As default PHP version is 7.4 in drupal-VM. for that either you can do the following to work with PHP 7.3 version:

The default installed PHP version is 7.3 and when you check `services --status-all` you can see `PHP-7.4-fpm` is running and that will prevent you to run service `PHP-7.3-fpm` from your `box/config.yml`

**Comment by beanjammin** [comment]
This change makes it so that PHP 7.4 is purged if it is not the version being used:

https://github.com/oxyc/drupal-vm/commit/cec3dd6487a7ab5f2b1d315044e512b3695070d1

**Comment by geerlingguy** [comment]
@beanjammin - That was merged in, right?
