### ISSUE TITLE
on geerlingguy/centos8 Installing Ansible... no match for python-crypto python-devel python-setuptools

### ISSUE THREAD

**Issue by arso-italy** [geerlingguy/drupal-vm#2142]
### Issue Type
 - Bug Report / Support Request

### Settings
Use **Centos8**
Use **Drupal8**
vagrant_box: geerlingguy/centos8

vagrant_synced_folder_default_type: smb

vagrant_ip: 192.168.56.2

vagrant_synced_folders:
   ...
    type: smb
   ...

drupal_composer_project_package: "drupal/recommended-project:^8@dev"

### Your Environment
Vagrant 2.2.14
VirtualBox 6.1.16

### Your OS
 - **Windows** (10) build 1909

### Full console output
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting SMB shared folders...
    drupalvm: D:/Vagrant/drupalvm-6.0.2 => /var/www/drupalvm
    drupalvm: D:/Vagrant/drupalvm-6.0.2 => /vagrant
==> drupalvm: Running provisioner: drupalvm (ansible_local)...
    drupalvm: Installing Ansible...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

dnf -y install curl gcc libffi-devel openssl-devel python-crypto python-devel python-setuptools

Stdout from the command:

CentOS-8 - AppStream                            329 kB/s | 6.3 MB     00:19
CentOS-8 - Base                                 2.8 MB/s | 2.3 MB     00:00
CentOS-8 - Extras                                33 kB/s | 8.6 kB     00:00
Last metadata expiration check: 0:00:01 ago on Sat 30 Jan 2021 05:01:30 PM UTC.
Package curl-7.61.1-12.el8.x86_64 is already installed.
Package openssl-devel-1:1.1.1c-15.el8.x86_64 is already installed.
No match for argument: python-crypto
No match for argument: python-devel
No match for argument: python-setuptools

Stderr from the command:

Error: Unable to find a match: python-crypto python-devel python-setuptools

### Summary

The vm is created but on ansible installation the process end due to missing python packages

**Comment by jsidigital** [comment]
I can confirm same issue. Cannot make DrupalVM work with Centos8.

Before upgrading VM, Centos7 has no issues.

Has anyone found a fix for the missing packages?
