### ISSUE TITLE
Mailhog doesn't start on vagrant up or reload

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#215]
When bringing up or rebooting the VM, Mailhog doesn't start. This may be an upstream problem, but I'd like to check it out here and see what's causing it to not start. In #213, we had to start it manually to get it running :(

**Comment by alsar** [comment]
`/var/log/boot.log` says: 

```
Starting mailhog.
/etc/rc2.d/S20mailhog: 27: /etc/rc2.d/S20mailhog: daemonize: not found
```

But starting it manually works.

**Comment by geerlingguy** [comment]
@alsar - Thanks for the helpful note. The problem was that daemonize was not compiled in a location accessible to the root user (it was in `/usr/local/sbin`) by default. To fix that, I opened https://github.com/geerlingguy/ansible-role-mailhog/issues/7 and fixed it upstream.

To get MailHog working correctly for system boot (and initial provision), please update the Ansible roles (`sudo ansible-galaxy install -r provisioning/requirements.txt --force`) and then do a `vagrant provision` (and/or destroy and rebuild).

**Comment by alsar** [comment]
@geerlingguy thanks for the fix. :+1:
