### ISSUE TITLE
Python error on running vagrant up on custom site

### ISSUE THREAD

**Issue by jmevalentin** [geerlingguy/drupal-vm#2153]
### Issue Type
 - Bug Report / Support Request

### Your Environment

NOTE: Running from git bash
```
$ `vagrant nt --version && echo "VirtualBox `vboxmanage --version`" && ansible --version`
bash: command substitution: line 1: unexpected EOF while looking for matching `"'
bash: command substitution: line 2: syntax error: unexpected end of file
bash: command substitution: line 1: unexpected EOF while looking for matching `"'
bash: command substitution: line 2: syntax error: unexpected end of file
bash: vboxmanage: command not found

```

### Your OS
 - **Windows** (version)

### Full console output
https://gist.github.com/jmevalentin/2f6a4d0887ecfb6bece090adca71cbf4

### Summary

When the vagrant up gets to the Ansible install I get an error that appears to be related to the python version, so I installed Python 3.9 and added it to the system path so that it would use it, and in git bash, running `which python` points to the correct python but this still happens.

**Comment by chumkui** [comment]
I get the same on Windows10 Pro on an older version of drupalvm, just pulled and all seems OK now?
