### ISSUE TITLE
TASK [geerlingguy.php : Ensure the default pool exists.] *********************** fatal: [drupalvm]: FAILED! =>

### ISSUE THREAD

**Issue by RalfEisler** [geerlingguy/drupal-vm#2158]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.7
VirtualBox 6.1.18r142142
```

### Your OS

 - **macOS** (10.14.6)

### Full console output

[console-output--vagrant-up.txt](https://github.com/geerlingguy/drupal-vm/files/6281059/console-output--vagrant-up.txt)

### Summary

For an update of an old Drupal project I want to install PHP 7.0. The installation of DrupalVM 4.9.2 fails with the following message:

TASK [geerlingguy.php : Ensure the default pool exists.] ***********************
fatal: [drupalvm]: FAILED! => {"changed": false, "checksum": "565ef20c1a260db1be9e8e0b1b057e84a1952ea1", "gid": 80, "group": "80", "mode": "0644", "msg": "chgrp failed", "owner": "502", "path": "{{ php_fpm_conf_path }}/pool.d/www.conf", "size": 226, "state": "file", "uid": 502}

There is a full console output in the attached file.

Is there a solution for this or is it possible to install PHP 7.0 on a current version of DrupalVM?

**Comment by geerlingguy** [comment]
Unfortunately, PHP 7.0 is no longer supported, and while you may be able to get it working with a lot of configuration changes, I won't be able to spend time helping with that.
