### ISSUE TITLE
Run Composer installer skipping

### ISSUE THREAD

**Issue by humour-picasso** [geerlingguy/drupal-vm#2161]
### Issue Type

 - Feature Idea
 
### Your Environment

```
Vagrant 2.2.15
VirtualBox 6.1.16_Ubuntur140961
ansible 2.9.6
```

### Your OS

 - **Linux** (version)

### Full console output
TASK [geerlingguy.composer : Run Composer installer.] **************************
skipping: [xxxx]

### Summary

I add `composer_version: '2.0.12'` in config.yml but skipped the task Run Composer install.
How can I make my config.yml take effect and install composer 2.0.12

**Comment by geerlingguy** [comment]
That will be skipped if Composer is already installed; see: https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L7-L9

If you want to update an existing composer installation you'd need to set the variable to keep it updated: https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L38-L43

**Comment by humour-picasso** [comment]
> That will be skipped if Composer is already installed; see: https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L7-L9
> 
> If you want to update an existing composer installation you'd need to set the variable to keep it updated: https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L38-L43

Thank you very much for your reply, I tried configuring `composer_keep_updated: true` and now it`s working

**Comment by humour-picasso** [comment]
> That will be skipped if Composer is already installed; see: https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L7-L9
> 
> If you want to update an existing composer installation you'd need to set the variable to keep it updated: https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/main.yml#L38-L43

Thank you very much for your reply, I tried configuring `composer_keep_updated: true` and now it`s working

**Comment by BatXie** [comment]
I met the same issue, but for me, I want to install a composer of version 1.x. And it seems that drupal-vm will install a composer of version 2.x by default. Due to that the installation of composer is skipped.

Here is my question, does there have a way to specify the version of composer?

**Comment by webprogrammierer** [comment]
I get the same error on vagrant provision:

`"stderr": "Warning from https://repo.packagist.org: Support for Composer 1 is deprecated and some packages will not be available. You should upgrade to Composer 2.`

Is there a solution in the meantime?

**Comment by webprogrammierer** [comment]
After adding
`composer_keep_updated: true`
i get this error:


` "stderr": "The \"hirak/prestissimo\" plugin (installed globally) was skipped because it requires a Plugin API version (\"^1.0.0\") that does not match your Composer installation (\"2.1.0\"). You may need to run composer update with the \"--no-plugins\" option.\n\n`

**Comment by webprogrammierer** [comment]
On second run I get this error:

TASK [geerlingguy.drupal : Move Drupal project files to drupal_composer_install_dir (this may take a while).] ***
fatal: [drupalvm3]: FAILED! => {"changed": true, "cmd": ["cp", "-r", "/tmp/composer-project/.", "/var/www/drupalvm/drupal/"], "delta": "0:01:08.630048", "end": "2021-12-18 11:22:49.660347", "msg": "non-zero return code", "rc": 1, "start": "2021-12-18 11:21:41.030299", "stderr": "cp: cannot create symbolic link '/var/www/drupalvm/drupal/./vendor/bin/var-dump-server': Protocol error", "stderr_lines": ["cp: cannot create symbolic link '/var/www/drupalvm/drupal/./vendor/bin/var-dump-server': Protocol error"], "stdout": "", "stdout_lines": []}

Ist this symbolic link necessary?
