### ISSUE TITLE
503 Service Unavailable No package matching 'php7.4' is available"

### ISSUE THREAD

**Issue by drfuzetto** [geerlingguy/drupal-vm#2168]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.14
VirtualBox 6.1.22r144080
ansible 2.10.9
  config file = None
  configured module search path = ['/Users/deborahfuzetto/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/Cellar/ansible/3.4.0/libexec/lib/python3.9/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.9.5 (default, May  4 2021, 03:36:27) [Clang 12.0.0 (clang-1200.0.32.29)]
```

### Your OS

 - **macOS** (version)

### Full console output

TASK [geerlingguy.firewall : Check if ufw package is installed (on Ubuntu).] ***
fatal: [nidcr]: FAILED! => {"changed": false, "cmd": ["service", "ufw", "status"], "delta": "0:00:00.010523", "end": "2021-06-07 23:55:34.423076", "msg": "non-zero return code", "rc": 3, "start": "2021-06-07 23:55:34.412553", "stderr": "", "stderr_lines": [], "stdout": "* ufw.service - Uncomplicated firewall\n   Loaded: loaded (/lib/systemd/system/ufw.service; disabled; vendor preset: enabled)\n   Active: inactive (dead)", "stdout_lines": ["* ufw.service - Uncomplicated firewall", "   Loaded: loaded (/lib/systemd/system/ufw.service; disabled; vendor preset: enabled)", "   Active: inactive (dead)"]}
...ignoring

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [nidcr]: FAILED! => {"changed": false, "msg": "No package matching 'php7.4' is available"}

### Summary

BLT 12.8.2.0
Vagrant 2.2.14
Virtual Box 6.1.22
drupal-vm 6.0.4
composer 2.1.2

I'm getting 503 Service Unavailable most likely since it cannot install php.

**Comment by adgjakemoreland** [comment]
Hi there,

I was getting this for the past 2 days and i found that updating my ubuntu to 18.04 (from 16.04) fixed this, I am not sure about a fix for 16.04 though unfortunately

vagrant_box: geerlingguy/ubuntu1804 in my config.yml

**Comment by drfuzetto** [comment]
That got me a litter farther.  After destroying and rebuilding, I got past the php error but now getting this error:
```
TASK [geerlingguy.adminer : Download Adminer to configured directory.] *********
fatal: [nidcr]: FAILED! => {"changed": false, "dest": "/opt/adminer/index.php", "elapsed": 0, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://www.adminer.org/latest.php"}
```

**Comment by oxyc** [comment]
Seems https://www.adminer.org/latest.php is down or removed. https://github.com/geerlingguy/ansible-role-adminer/issues/15

There's no variable to change the download url but personally for now I just edited line 18 in `drupal-vm/provisioning/roles/geerlingguy.adminer/tasks/main.yml`:
```
url: https://github.com/vrana/adminer/releases/download/v4.7.7/adminer-4.7.7-mysql-en.php
```

**Comment by drfuzetto** [comment]
I just removed adminer from installed_extras for now.  It appeared to be successful except when I visit from the browser I get the Apache2 Ubuntu Default Page so it still seems like something didn't complete.

Also, not sure if this is related but I'm still getting the Uncomplicated firewall error:
```
TASK [geerlingguy.firewall : Check if ufw package is installed (on Ubuntu).] ***
fatal: [nidcr]: FAILED! => {"changed": false, "cmd": ["service", "ufw", "status"], "delta": "0:00:00.013970", "end": "2021-06-08 13:25:53.379676", "msg": "non-zero return code", "rc": 3, "start": "2021-06-08 13:25:53.365706", "stderr": "", "stderr_lines": [], "stdout": "● ufw.service - Uncomplicated firewall\n   Loaded: loaded (/lib/systemd/system/ufw.service; disabled; vendor preset: enabled)\n   Active: inactive (dead)\n     Docs: man:ufw(8)\n\nJun 08 12:34:31 local systemd[1]: Stopping Uncomplicated firewall...\nJun 08 12:34:31 local ufw-init[2593]: Skip stopping firewall: ufw (not enabled)\nJun 08 12:34:31 local systemd[1]: Stopped Uncomplicated firewall.", "stdout_lines": ["● ufw.service - Uncomplicated firewall", "   Loaded: loaded (/lib/systemd/system/ufw.service; disabled; vendor preset: enabled)", "   Active: inactive (dead)", "     Docs: man:ufw(8)", "", "Jun 08 12:34:31 local systemd[1]: Stopping Uncomplicated firewall...", "Jun 08 12:34:31 local ufw-init[2593]: Skip stopping firewall: ufw (not enabled)", "Jun 08 12:34:31 local systemd[1]: Stopped Uncomplicated firewall."]}
...ignoring
```

**Comment by cainaru** [comment]
I'm running into the same issue as @oxyc regarding adminer this morning

```
TASK [geerlingguy.adminer : Download Adminer to configured directory.] *********
fatal: [xyz]: FAILED! => {"changed": false, "dest": "/opt/adminer/index.php", "elapsed": 1, "msg": "Request failed", "response": "HTTP Error 404: Not Found", "status_code": 404, "url": "https://www.adminer.org/latest.php"}
```

**Comment by geerlingguy** [comment]
@cainaru - I just updated Drupal VM to use the latest version of the adminer role which uses the new variable adminer_download_url — if you update to the latest version of Drupal VM (master branch, not the latest tag), then you can set that variable to the URL @oxyc mentioned above and override the URL.

**Comment by cainaru** [comment]
@geerlingguy Great, looks like that worked! Thank you!!

**Comment by geerlingguy** [comment]
I'm going to close this issue and merge follow-up discussion into new issue #2169.

**Comment by drfuzetto** [comment]
Fixed most of my issues: `vagrant destroy && vagrant up`
Still having trouble with Adminer.

Thank you for all of the help!
