### ISSUE TITLE
Adminer latest.php download URL fails Ansible 

### ISSUE THREAD

**Issue by UTCGilligan** [geerlingguy/drupal-vm#2169]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
N/A
```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

### Full console output

N/A

### Summary

[https://www.adminer.org/latest.php](https://www.adminer.org/latest.php) is 404: Not Found. Ansible fails to complete. 

```
TASK [geerlingguy.adminer : Download Adminer to configured directory.] *********
fatal: [utccloud]: FAILED! => {"changed": false, "dest": "/opt/adminer/index.php", "elapsed": 1, "gid": 0, "group": "root", "mode": "0644", "msg": "Request failed", "owner": "root", "response": "HTTP Error 404: Not Found", "size": 475877, "state": "file", "status_code": 404, "uid": 0, "url": "https://www.adminer.org/latest.php"}

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************

RUNNING HANDLER [geerlingguy.memcached : restart memcached] ********************

PLAY RECAP *********************************************************************
utccloud                   : ok=174  changed=25   unreachable=0    failed=1    skipped=192  rescued=0    ignored=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by geerlingguy** [comment]
Thanks for reporting this! It was actually first identified in https://github.com/geerlingguy/drupal-vm/issues/2168, but since this issue is focused on the Adminer problem, I'll post the current workaround here:

I just updated Drupal VM to use the latest version of the adminer role which uses the new variable `adminer_download_url` — if you update to the latest version of Drupal VM (master branch, not the latest tag), then you can set that variable to the URL @oxyc mentioned in the linked issue (https://github.com/vrana/adminer/releases/download/v4.7.7/adminer-4.7.7-mysql-en.php) and override the URL.

**Comment by mwaabaikatik** [comment]
Stuck with the same issue. Tried to update to the latest version 6.0.4 but no luck.  Please let me know if I am missing anything.

Gathering patches for dependencies. This might take a minute.
  - Updating geerlingguy/drupal-vm (6.0.2 => 6.0.4): Downloading (100%)

Any help would be really appriciated!
<img width="1829" alt="Screen Shot 2021-06-09 at 4 37 45 PM" src="https://user-images.githubusercontent.com/63673174/121426011-135f4500-c941-11eb-95b7-e59412a75364.png">

**Comment by mwaabaikatik** [comment]
I have to make the changes (https://github.com/geerlingguy/ansible-role-adminer ) manually inside the vagrant and update the URL.   Now it's working! 

Please let me know which version has the latest changes.

**Comment by oxyc** [comment]
You'll need to use the `master` branch, there hasn't been any new release yet.

**Comment by oxyc** [comment]
It's now back live again https://sourceforge.net/p/adminer/bugs-and-features/803/#5959

**Comment by geerlingguy** [comment]
Thanks for the help and patience, everyone!
