### ISSUE TITLE
Vagrant failed to initialize at a very early stage:  There was an error loading a Vagrantfile. The file being loaded and the error message are shown below.

### ISSUE THREAD

**Issue by chunesh** [geerlingguy/drupal-vm#2171]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
vagrant --version: Vagrant 2.2.10
vboxmanage --version: 6.1.16r140961
ansible --version: ansible [core 2.11.0] 

```

### Your OS

 - **macOS** (version)

### Full console output

**vagrant up --provision**
Vagrant failed to initialize at a very early stage:

There was an error loading a Vagrantfile. The file being loaded
and the error message are shown below. This is usually caused by
a syntax error.

Path: /drupal/Vagrantfile
Line number: 0
Message: ArgumentError: Malformed version number string [core

### Summary

vagrant up --provision is failing and throwing the above error. 

**Vagrantfile content:**
`
### The absolute path to the root directory of the project. Both Drupal VM and the config file need to be contained within this path.
ENV['DRUPALVM_PROJECT_ROOT'] = "#{__dir__}"

### The relative path from the project root to the config directory where you placed your config.yml file.
ENV['DRUPALVM_CONFIG_DIR'] = "box"

### The relative path from the project root to the directory where Drupal VM is located.
ENV['DRUPALVM_DIR'] = "vendor/geerlingguy/drupal-vm"

### Load the real Vagrantfile
load "#{__dir__}/#{ENV['DRUPALVM_DIR']}/Vagrantfile"
`

**Comment by phizev** [comment]
This is a duplicate of #2166, and has been fixed in the latest release of DrupalVM ([6.0.4](https://github.com/geerlingguy/drupal-vm/commit/01545c37d96d4973b57ec6e842e54c40d0988207) at time of writing).

**Comment by chunesh** [comment]
Thanks,

I have updated my Drupal VM from 5.0 to 6.0.4 and the **vagrant up --provision** is working.

I am upgrading the PHP version from 7.3 to 7.4 and now **vagrant up --provision** is failing and throwing the below error 

fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "No package matching 'php7.4' is available"}

PLAY RECAP *********************************************************************
drupalvm                   : ok=73   changed=19   unreachable=0    failed=1    skipped=69   rescued=0    ignored=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by riteshgurung** [comment]
@chunesh Can you try changing the following regex in the file vagrant.rb located under vendor/geerlingguy/drupal-vm/lib/drupalvm directory

Line 57

from 
`/^[^\s]+ ([^\s]+)/.match(`#{ansible_bin} --version`) { |match| return match[1] }`

to 

`/^[^\s]+ ([^\s]+) ([0-9.]+)/.match(`#{ansible_bin} --version`) { |match| return match[2] }`

**Comment by crasx** [comment]
@chunesh if you are changing php versions you should run  `vagrant destroy` before vagrant up. Note this will delete all your data.  The changing of PHP versions can be pretty complicated so its usually easier to start from scratch in that case

**Comment by gabe-connolly** [comment]
For anyone else that comes here with the error below:
```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [drupalvm]: FAILED! => {"changed": false, "msg": "No package matching 'php7.4' is available"}
```

I was having the same issue re-provisioning my local VM to use php7.4, and even trying to re-prevision after a `vagrant destroy` just using php7.3.  Some digging revealed that this was due to the dropping of support for Ubuntu 16.04:

https://www.patreon.com/posts/ubuntu-16-04-lts-52120358

To resolve this I had to make the following adjustments in my `box/config.yml` file:
```
# Old version
vagrant_box: geerlingguy/ubuntu1604
php_version: "7.3"
php_xdebug_version: 2.7.0
```

```
# After changes
vagrant_box: geerlingguy/ubuntu1804
php_version: "7.4"
php_xdebug_version: 3.0.4
```

Depending on what additional extras you have installed you may need to bump some additional versions on those extras to be compatible with php7.4, but based on the experience I had the errors presented in provisioning give good enough bread crumbs to identify those relatively easily.

**Comment by pundhir1111** [comment]
D:\Workpractice\kubernetes\cluster>vagrant up
Vagrant failed to initialize at a very early stage:

The executable 'cmd.exe' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.

**Comment by pundhir1111** [comment]
facing this error, please help to resolve this issue. using win 11.
