### ISSUE TITLE
Vagrant woes with MacOS Monterey … and my solution

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#2182]
### Issue Type

 - Documentation Report

### Your OS

 - **macOS** (Monterey)

### Summary

I have finally  lost patience with VirtualBox with niggles for months and finally total failure with Monterey, and, since I had Parallels Desktop already on my Mac, I changed my `vagrant.config.yml` to specify `vagrant_box: bento/ubuntu-18.04`; I did `vagrant plugin install vagrant-parallels` and  `vagrant up provider=parallels` and that was pretty much it.
Every other aspect of the development setup remains unchanged. Wish I’d done this years ago. Genuinely very grateful for free use of VirtualBox for many years but my loyalty finally evaporated this month.

**Comment by frob** [comment]
I thought there was a directive in the `vagrant.config.yml` that allowed us to specify a provider.
