### ISSUE TITLE
Re-wording of the recipe

### ISSUE THREAD

**Issue by kartagis** [geerlingguy/drupal-vm#2185]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```

```

### Your OS

 - **macOS** (version)
 - **Windows** (version)
 - **Linux** (version)

### Summary

The recipe for adminer reads `Ensure paths to place symlinks exist` which is poor wording. It should be `Determine paths to place existing symlinks.` I also put a full stop at the end for consistency. Patch along with PR is following.

**Comment by geerlingguy** [comment]
See note in PR.
