### ISSUE TITLE
Box 'geerlingguy/drupal-vm' could not be found. Attempting to find and install...

### ISSUE THREAD

**Issue by atta-ur-rehman6685** [geerlingguy/drupal-vm#2189]
### Issue Type

 - Bug Report / Support Request

### Your Environment

 $ vagrant up
==> drupalvm: Box 'geerlingguy/drupal-vm' could not be found. Attempting to find and install...
    drupalvm: Box Provider: hyperv
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/drupal-vm'
    drupalvm: URL: https://vagrantcloud.com/geerlingguy/drupal-vm
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: geerlingguy/drupal-vm
Address: https://vagrantcloud.com/geerlingguy/drupal-vm
Requested provider: [:hyperv]
bash: $: command not found

```

```

### Your OS

 - **Windows** (10 pro)

### Full console output

 $ vagrant up
==> drupalvm: Box 'geerlingguy/drupal-vm' could not be found. Attempting to find and install...
    drupalvm: Box Provider: hyperv
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/drupal-vm'
    drupalvm: URL: https://vagrantcloud.com/geerlingguy/drupal-vm
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: geerlingguy/drupal-vm
Address: https://vagrantcloud.com/geerlingguy/drupal-vm
Requested provider: [:hyperv]
bash: $: command not found

### Summary

i have posted full console result please guide me how to resolve this issue, i am trying to resolve it from two days

**Comment by geerlingguy** [comment]
I don't have any boxes supporting the HyperV platform; you'd have to install VirtualBox and use that instead. Otherwise you can change the box name in the config.yml file and use a box for Debian 10 or Ubuntu 18 or 20 from Vagrant Cloud that is built for HyperV.

**Comment by atta-ur-rehman6685** [comment]
by installing virtual box, it's installed successfully and accessible by ip http://192.168.88.90/
but Adminer, MailHog, PimpMyLog links are not working

**Comment by atta-ur-rehman6685** [comment]
> by installing virtual box, it's installed successfully and accessible by ip http://192.168.88.90/ but Adminer, MailHog, PimpMyLog links are not working

i have added below lines in etc/hosts file.

192.168.88.90 drupalvmsetup.local
192.168.88.90 www.drupalvmsetup.local
192.168.88.90 adminer.drupalvmsetup.local
192.168.88.90 xhprof.drupalvmsetup.local
192.168.88.90 pimpmylog.drupalvmsetup.local
192.168.88.90 dashboard.drupalvmsetup.local

all links are working else main site link
http://drupalvmsetup.local/

**Comment by atta-ur-rehman6685** [comment]
> > by installing virtual box, it's installed successfully and accessible by ip http://192.168.88.90/ but Adminer, MailHog, PimpMyLog links are not working
> 
> i have added below lines in etc/hosts file.
> 
> 192.168.88.90 drupalvmsetup.local 192.168.88.90 [www.drupalvmsetup.local](http://www.drupalvmsetup.local) 192.168.88.90 adminer.drupalvmsetup.local 192.168.88.90 xhprof.drupalvmsetup.local 192.168.88.90 pimpmylog.drupalvmsetup.local 192.168.88.90 dashboard.drupalvmsetup.local
> 
> all links are working else main site link http://drupalvmsetup.local/

browser's output
Not Found
The requested URL was not found on this server.

Apache/2.4.29 (Ubuntu) Server at drupalvmsetup.local Port 80

**Comment by atta-ur-rehman6685** [comment]
Guest hangs after 5 minutes of inactivity on  windows resolved:
Open Config.yml file
Under
vagrant_synced_folders
type: nfs
changes to
type: virtualbox
