### ISSUE TITLE
Does DrupalVM work with Xdebug v3 installed on host?

### ISSUE THREAD

**Issue by emb03** [geerlingguy/drupal-vm#2193]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.19
VirtualBox 2.1.26
```

### Your OS

 - **macOS** (Big Sur)

### Summary
Xdebug does not work at all. Is there a way to make DrupalVM upgrade to Xdebug v3 or do I have to downgrade my version of xdebug on my host machine?

**Comment by D41137171** [comment]
Yes, have a way to upgrade but you will need to create a patch for that.

in drupal-vm/provisioning/roles/geerlingguy.php-xdebug/templates/xdebug.ini.j2 you will need to update the fields that you will use according to the xdebug upgrading documentation (https://xdebug.org/docs/upgrade_guide). After that in your box config file you will fill with the variables that you update in xdebug.ini.j2

**Comment by mnovbaalen** [comment]
I managed to get xdebug 3.1.0 working with Drupal-vm & Phpstorm by adding these lines to the xdebug.ini.j2 file, as Guilherme Barbosa suggests:

```
xdebug.mode={{ php_xdebug_mode }}
xdebug.client_host={{ php_xdebug_client_host }}
xdebug.client_port={{ php_xdebug_client_port }}
```

Then in config.yml of drupal-vm, append these lines to your other xdebug settings:

```
php_xdebug_version: 3.1.0
php_xdebug_mode: debug
php_xdebug_client_host: 192.168.99.1
php_xdebug_client_port: 9003
```
