### ISSUE TITLE
Drush fails after fresh spinup: Class "DOMDocument" does not exist

### ISSUE THREAD

**Issue by dbperf** [geerlingguy/drupal-vm#2196]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.14
VirtualBox 6.1.16r140961
ansible 2.9.27
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/vagrant/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.17 (default, Jul 20 2020, 15:37:01) [GCC 7.5.0]
```

### Your OS
 - **Linux** (version)

### Summary

Spinning up a new project using DrupalVM with Acquia BLT and Acquia CMS. The box provisions correctly, but all drush commands fail when I ssh into the box. The error is:

```
 [preflight] Class "DOMDocument" does not exist
 [warning] Drush command terminated abnormally.
```

Some initial debugging shows that this can be caused by the absence of the php-xml extension. I modified box/config.yml to include this:

```
php_version: "7.4"
php_packages_extra:
  - "php{{ php_version }}-bz2"
  - "php{{ php_version }}-imagick"
  - "php{{ php_version }}-zip"
  - "php{{ php_version }}-intl"
  - "php{{ php_version }}-bcmath"
  - "php{{ php_version }}-xml"
  - imagemagick
```

And re-provisioned the box, but no success. phpinfo confirms the extension is present. Restarted PHP after re-provisioning just to be certain., but the issue still persists.

**Comment by dbperf** [comment]
Updating with some more info: the cause for this turns out to be a PHP version mismatch. Even though 7.4 is explicitly declared in the box/config.yml, the VM spins up with 8.1. Apparently, php-xml is not installed for 8.1. Manually switching to 7.4 in the VM resolves the issue: 

`sudo update-alternatives --set php /usr/bin/php7.4`

So the bug appears to be that the VM is not respecting the PHP version set in the box/config.yml when provisioning.

**Comment by geerlingguy** [comment]
I've been having this happen on a number of Ubuntu servers lately, even after running upgrades. It looks like the CLI gets updated to PHP 8.1, while the web UI still runs PHP 7.3 or 7.4 (whatever version is set with `php_version`)... hmm...

**Comment by geerlingguy** [comment]
Related: https://github.com/geerlingguy/ansible-for-devops/issues/451

**Comment by geerlingguy** [comment]
Can you see if maybe `php-apcu` is in your configuration anywhere? If so, it needs to be changed to `php7.4-apcu`.

**Comment by dbperf** [comment]
Nope...not setting that anywhere in the configuration  :(

**Comment by geerlingguy** [comment]
Weird, it should be fixed, though I might also need to update Drupal VM to latest role versions soon to make sure that's not the issue.

**Comment by acha5066** [comment]
Just reporting that I also experienced issues after cloning the latest `master`, not touching anything in `config.yml` and running `vagrant up`. The VM installed `php 8.1` even though `7.4` was specified. I also got return type error messages similar to this:

```php
PHP Deprecated: Return type of Symfony\Component\Console\Helper\HelperSet::getIterator()
should either be compatible with IteratorAggregate::getIterator(): Traversable,
or the #[ReturnTypeWillChange] attribute should be used to temporarily suppress the notice
```

**Comment by sms20** [comment]
Thanks helped a million.

**Comment by 58bits** [comment]
> Can you see if maybe `php-apcu` is in your configuration anywhere? If so, it needs to be changed to `php7.4-apcu`.

Live saver. Thanks you.
