### ISSUE TITLE
DrupalVM won't spin up on MacBook using M1 chip

### ISSUE THREAD

**Issue by dbperf** [geerlingguy/drupal-vm#2198]
### Issue Type

 - Bug Report / Support Request

### Your Environment

```
Vagrant 2.2.18
```

### Your OS

 - **macOS** (version)

### Full console output

```
$vagrant up
Bringing machine 'myproject' up with 'vmware_fusion' provider...
==> myproject: Box 'geerlingguy/drupal-vm' could not be found. Attempting to find and install...
    myproject: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    myproject: Box Version: >= 0
==> myproject: Loading metadata for box 'geerlingguy/drupal-vm'
    myproject: URL: https://vagrantcloud.com/geerlingguy/drupal-vm
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Vagrant Cloud, make sure the box is
released.

Name: geerlingguy/drupal-vm
Address: https://vagrantcloud.com/geerlingguy/drupal-vm
Requested provider: ["vmware_desktop", "vmware_fusion", "vmware_workstation"]
```

### Summary
Trying to get existing Acquia BLT/DrupalVM projects running on a new MacBook Pro using the M1 chip (Apple silicon). As Virtual Box won't run on an M1, I'm using VMWare Fusion as a provider. I've added the plugin to box/config.yml:
```
vagrant_plugins:
  - name: vagrant-vmware-desktop
```
All relevant dependencies should be met: Vagrant, vmware-desktop plugin. When running vagrant up, I'm met with the above error. Note that these projects were all working on previous (Intel-based) Macs, and were cloned from the same repo, so are in a known good state. The docs for this project seem to indicate that DrupalVM supports VMWare Fusion, but I'm obviously missing something somewhere.

Thanks!

**Comment by geerlingguy** [comment]
A few years back I stopped building boxes for VMware and Parallels because of the extra licensing requirements (it requires *two* paid licenses to build for those platforms).

So I standardized on VirtualBox. But now that VirtualBox won't run on M1, I'm not really interested in adapting this project, which is already mostly unmaintained, to work on M1. I would recommend switching to a Docker environment if you need M1 support (that's what I use—in my case a custom one, but I think Docksal or DDEV is good too).

**Comment by geerlingguy** [comment]
See related: https://github.com/geerlingguy/ansible-for-devops/issues/404

**Comment by cecrs** [comment]
Just dropping a comment to say that I'm moving to an M1 mac soon, and in preparation, have switched to ddev+colima+mutagen (https://ddev.com/ddev-local/docker-desktop-and-colima-benchmarking-on-macos/) for local dev. I have been very happy with it so far.  

Also wanted to say a huge thank you to you Jeff (@geerlingguy) for having built/maintained drupalVM all these years. Your contributions are so appreciated!

🙇‍♀️
