### ISSUE TITLE
How to install additional packages other than apt-get?

### ISSUE THREAD

**Issue by caschbre** [geerlingguy/drupal-vm#221]
I had a couple of questions on how to install additional packages that are not a simple apt-get.  Three different examples are below. 

I'd like to install nodejs from a different repository.
```
$ sudo apt-get install python-software-properties
$ sudo apt-add-repository ppa:chris-lea/node.js
$ sudo apt-get update
$ sudo apt-get install nodejs
```

Or install the bundler gem.
```
gem install bundler
```

Or install Grunt using npm.
```
sudo npm install -g grunt-cli
```

**Comment by frob** [comment]
I am somewhat curios as to why any of those things are necessary. However, I use this as a base vm, not an end-all infinitely configurable development platform for what ever you need.

My suggestion would be to fork it and add anisble roles to the playbook that do those things.

**Comment by caschbre** [comment]
My end goal is to have a project specific dev environment.  I'm learning vagrant + ansible and trying to figure out how to go about certain things like this.  One project I have has a grunt build task so after cloning a repo we kick off the grunt task.  

I'm ok forking the repo and pulling in changes from upstream as drupal-vm gets updates... I just noticed the config.yml file had an option to include additional packages.  I still need to figure out how to create roles.  I haven't gotten to that part of Jeff's book yet.

**Comment by oxyc** [comment]
Currently this is not supported during the VM build. There's already an issue for it though https://github.com/geerlingguy/drupal-vm/issues/174

**Comment by geerlingguy** [comment]
Ha, @oxyc I was literally typing the exact same comment at the time you posted yours. I'm working on finishing my book right now, but once that's done, I'm back to focusing on Drupal VM a bit more, and I hope to have a solution in place for this.

One note: most devs using Drupal VM (myself included) have tools like SASS compilers and asset pipelines running locally (on the host), and the VM itself just runs the site and backend tools. However, enough people have asked for support for things like grunt, gulp broccoli, spaghetti, gasp, linguini, and all the other thousand JS build frameworks are out there, so I think #174 is one of my highest priority improvements for a 2.x minor release.
