### ISSUE TITLE
PDO extension not activated (Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY')

### ISSUE THREAD

**Issue by TravisCarden** [geerlingguy/drupal-vm#226]
I get the following PHP error from my Drupal 8 site on a freshly provisioned instance of drupal-vm:

> Fatal error: Undefined class constant 'MYSQL_ATTR_USE_BUFFERED_QUERY' in /var/www/core/lib/Drupal/Core/Database/Driver/mysql/Connection.php on line 107

This appears to be because PDO is not activated [per Drupal 8's system requirements](https://www.drupal.org/requirements/php#8). The problem is solved with the addition of two lines to `php.ini`:

```ini
extension=pdo.so
extension=pdo_mysql.so
```

e.g.:

```bash
echo -e "\nextension=pdo.so\nextension=pdo_mysql.so" | sudo tee -a /etc/php5/apache2/php.ini
sudo service apache2 reload
```

That eliminates the error for me. I'm just getting started with this project and don't know enough to fix the cause yet.

**Comment by geerlingguy** [comment]
I've never noticed this issue before—the only time this should really happen is if an initial provisioning never completed (if there was an error mid-provision), and Apache never restarted, picking up all the proper config.

Do you happen to be running a non-standard base box (e.g. not one of the geerlingguy/* base boxes)?

**Comment by TravisCarden** [comment]
Well, that's strange... No, I'm using the default box. Provisioning _was_ failing consistently on a Drush Composer issue with `psysh`, which I assume was the issue and was going to reproduce and paste here. But, though `vagrant destroy -f && vagrant up` has failed the same way several times today, I just did it again and it succeeded. Everything appears to be running fine. I guess this is "cannot reproduce". ::shrugs:: Thanks! :p

**Comment by joshrickert** [comment]
I just encountered this issue as well. I'll try capturing some data for debugging and then destroying/reprovisioning the vm.

**Comment by teglia** [comment]
Yes, interestingly I can't get past this, even with the fixes mentioned above. I can do a drush sqlc < db.sql but then every drush command thereafter dies with this error.

Any clue what I can do? 

PHP 5.6, Drush 7.x

**Comment by geerlingguy** [comment]
Ha, I just ran into this fun error today on a docker-compose setup that is running Drupal. Not sure what's going on there, as it works locally, but not on a Raspberry Pi 4. Might be an issue with one of the Docker images :(
