### ISSUE TITLE
composer not found while runing sudo ansible-galaxy install -r provisioning/requirements.txt --force   

### ISSUE THREAD

**Issue by dwaghmare** [geerlingguy/drupal-vm#228]
I followed steps and before runing step 5 I did following as per given note.
It   
`
$ sudo ansible-galaxy install -r provisioning/requirements.txt --force
- downloading role 'selenium', owned by arknoll
- downloading role from https://github.com/arknoll/ansible-role-selenium/archive/master.tar.gz
- extracting arknoll.selenium to /etc/ansible/roles/arknoll.selenium
- arknoll.selenium was installed successfully
- downloading role 'adminer', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-adminer/archive/1.0.1.tar.gz
- extracting geerlingguy.adminer to /etc/ansible/roles/geerlingguy.adminer
- geerlingguy.adminer was installed successfully
- downloading role 'apache', owned by geerlingguy
- downloading role from https://github.com/geerlingguy/ansible-role-apache/archive/1.4.1.tar.gz
- extracting geerlingguy.apache to /etc/ansible/roles/geerlingguy.apache
- geerlingguy.apache was installed successfully
- downloading role 'composer', owned by geerlingguy
`
and then terminal keeps waiting for next thing...

I did control+x

terminal shows below and back to command line with below message
`
sorry, geerlingguy.composer was not found on galaxy.ansible.com.
- you can use --ignore-errors to skip failed roles.
`

**Comment by geerlingguy** [comment]
My best guess is there was a momentary outage or other issue with Ansible Galaxy. Can you please try again and see what happens now? That role is definitely on Galaxy, and I can download it from here.
