### ISSUE TITLE
Improve git permissions guidance in docs/other/windows.md

### ISSUE THREAD

**Issue by rhuffstedtler** [geerlingguy/drupal-vm#235]
I disagree with your suggested approach regarding workflow on windows. I figured it would be better to start with an issue rather than submitting a PR.

There are a number of advantages to being able to work directly in the VM rather than through the shared folder (speed, consistency when it comes to deployment, etc.). Because we always use a fix permissions script as part of the build process, we don't worry too much about the permissions in the repo, so anytime windows is in the picture we have git ignore file mode changes:
```
git config core.fileMode false
```

It seems to me that would be better guidance to give people as it would make their use of drupalvm more flexible.

**Comment by geerlingguy** [comment]
And to be clear, are you suggesting setting that as a global inside the VM, or recommending it for Windows users on the host? (Or both?)

**Comment by rhuffstedtler** [comment]
I usually do it in both places if I think I'm going to be touching the files from the host at all.
