### ISSUE TITLE
Issue with ssh 

### ISSUE THREAD

**Issue by m1n0** [geerlingguy/drupal-vm#236]
Hi, I have been using drupalvm for quite long, but I started having issues with ssh recently. 
The issue:
```
$ vagrant up
Bringing machine 'drupal8' up with 'virtualbox' provider...
==> drupal8: Importing base box 'geerlingguy/ubuntu1404'...
==> drupal8: Matching MAC address for NAT networking...
==> drupal8: Checking if box 'geerlingguy/ubuntu1404' is up to date...
==> drupal8: Setting the name of the VM: drupal8.local
==> drupal8: Clearing any previously set network interfaces...
==> drupal8: Preparing network interfaces based on configuration...
    drupal8: Adapter 1: nat
    drupal8: Adapter 2: hostonly
==> drupal8: Forwarding ports...
    drupal8: 22 => 2222 (adapter 1)
==> drupal8: Running 'pre-boot' VM customizations...
==> drupal8: Booting VM...
==> drupal8: Waiting for machine to boot. This may take a few minutes...
    drupal8: SSH address: 127.0.0.1:2222
    drupal8: SSH username: vagrant
    drupal8: SSH auth method: private key
    drupal8: Warning: Connection timeout. Retrying...
==> drupal8: Machine booted and ready!
==> drupal8: Checking for guest additions in VM...
==> drupal8: Checking for host entries
==> drupal8: adding to (/etc/hosts) : 192.168.88.88  drupal8.local  # VAGRANT: 69efb7a8f9dfab90b787dcbf94086c8f (drupal8) / 237eba57-f977-4a0e-964b-775eadc5f7f8
==> drupal8: adding to (/etc/hosts) : 192.168.88.88  xhprof.drupal8.local  # VAGRANT: 69efb7a8f9dfab90b787dcbf94086c8f (drupal8) / 237eba57-f977-4a0e-964b-775eadc5f7f8
==> drupal8: adding to (/etc/hosts) : 192.168.88.88  pimpmylog.drupal8.local  # VAGRANT: 69efb7a8f9dfab90b787dcbf94086c8f (drupal8) / 237eba57-f977-4a0e-964b-775eadc5f7f8
Password:
==> drupal8: Setting hostname...
Vagrant timed out while attempting to connect via SSH. This usually
means that the VM booted, but there are issues with the SSH configuration
or network connectivity issues. Please try to `vagrant reload` or
`vagrant up` again.
```

When I run `vagrant ssh` I get the same time out, `vagrant ssh-config` returns this:

```
$ vagrant ssh-config
Host drupal8
  HostName 127.0.0.1
  User vagrant
  Port 2222
  UserKnownHostsFile /dev/null
  StrictHostKeyChecking no
  PasswordAuthentication no
  IdentityFile /Users/m1n0/.vagrant.d/insecure_private_key
  IdentitiesOnly yes
  LogLevel FATAL
  ForwardAgent yes
```

I tried modifying the vagrantfile so that Virtualbox uses GUI, when I do that, same thing happens on the console and the VM command line is stuck on asking for username and password - obviously the ssh login does not work.

I tried swapping for `ubuntu/trusty64` with the same result.

My environment:
geerlingguy/ubuntu1404 box version 1.0.5
VirtualBox 5.0.2
Vagrant 1.7.4
Ansible 1.9.3

Any hints please?

**Comment by m1n0** [comment]
Update:

After this timeout, I am able to `vagrant ssh` in. Also, I tried running `vagrant provision`, getting this:
```
$ vagrant provision
==> drupal8: Running provisioner: ansible...
PLAY [all] ********************************************************************
GATHERING FACTS ***************************************************************
fatal: [drupal8] => SSH Error: Shared connection to 127.0.0.1 closed.
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [Update apt cache if needed.] *******************************************
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/m1n0/playbook.retry

drupal8                    : ok=0    changed=0    unreachable=1    failed=0

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
It could be a few different things, but one small thing I noticed—if you use a domain ending in `.local`, that can cause weird networking issues on Mac OS X (`==> drupal8: Setting the name of the VM: drupal8.local`).

Vagrant shouldn't be using the DNS entry for connection, so it's strange the error occurs there, but I've seen stranger things happen.

Another question: do you have any kind of corporate proxy of a VPN running? Some of these can break localhost connections (none of the good ones do... but there are a lot that play fun games with your hosts entries and local networking).

**Comment by m1n0** [comment]
Thanks for your insight - but the .local name was not it.
After lots of trying and comparing old versions and browsing the issue queue I found out the `config.ssh.forward_agent` (https://github.com/geerlingguy/acquia-cloud-vm/pull/10) setting caused this - I simply turned that to `false` and now everything is working.

**Comment by geerlingguy** [comment]
@m1n0 - Thanks for reporting back the fix. I think I should make that a configurable option, since it could cause issues depending on local/host SSH config!

That was introduced in #141 .

**Comment by m1n0** [comment]
The thing is, I dont know what local/host SSH config is causing the issue - I dont know/remember any special ssh config I would set anywhere :)

**Comment by geerlingguy** [comment]
@m1n0 - Can you check the contents of `~/.ssh/config` and see if there's anything funky in that file?

**Comment by m1n0** [comment]
@geerlingguy only this:
```
Host *
    ServerAliveInterval 30
    serveralivecountmax 20
```

and two Hosts settings (which I wont show here of course) with Hostname, User, Port and IdentityFile params set.

**Comment by geerlingguy** [comment]
@m1n0 - And I assume the two hosts are not wildcards using IP addresses in the same range as 192.168.88.x or whatever IP you're using for Drupal VM?
