### ISSUE TITLE
include_once(): Failed opening '/usr/share/php/xhprof_html/xhprof_lib/utils/xhprof_runs.php' for inclusion

### ISSUE THREAD

**Issue by sdemi** [geerlingguy/drupal-vm#238]
* I have provisioned my system with no changes to xhprof.
* I am running Drupal 7 with stable devel.
* I am receiving errors:

Warning: include_once(/usr/share/php/xhprof_html/xhprof_lib/utils/xhprof_lib.php): failed to open stream: No such file or directory in devel_xhprof_enable() (line 610 of /var/www/pegapdn/sites/all/modules/contrib/devel/devel.module).

Warning: include_once(): Failed opening '/usr/share/php/xhprof_html/xhprof_lib/utils/xhprof_lib.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in devel_xhprof_enable() (line 610 of /var/www/pegapdn/sites/all/modules/contrib/devel/devel.module).

Warning: include_once(/usr/share/php/xhprof_html/xhprof_lib/utils/xhprof_runs.php): failed to open stream: No such file or directory in devel_xhprof_enable() (line 611 of /var/www/pegapdn/sites/all/modules/contrib/devel/devel.module).

Warning: include_once(): Failed opening '/usr/share/php/xhprof_html/xhprof_lib/utils/xhprof_runs.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in devel_xhprof_enable() (line 611 of /var/www/pegapdn/sites/all/modules/contrib/devel/devel.module).

It looks like the utils directory is missing. Looks like these files are required for xhprof to work with devel 7.x

Why are these files not part of the provision?

**Comment by oxyc** [comment]
They are part of it but you have the wrong path `devel_xhprof_directory` path, seems you have it as `/usr/share/php/xhprof_html` while it should be `/usr/share/php`.

You can set it either at `admin/config/development/devel` or in your `settings.php` using:
```php
$conf['devel_xhprof_directory'] = '/usr/share/php';
```

**Comment by sdemi** [comment]
Ah thanks. xhprof is now running. However, I am not getting any results from it. And there are some php errors from xhprof. See below.




Warning: Invalid argument supplied for foreach() in /usr/share/php/xhprof_lib/utils/xhprof_lib.php on line 579

Warning: Invalid argument supplied for foreach() in /usr/share/php/xhprof_lib/utils/xhprof_lib.php on line 494
View Top Level Run Report

Run Report
Run #55f6f8a8914f4: Invalid Run Id = 55f6f8a8914f4
Tip
Click a function name below to drill down.

Warning: Invalid argument supplied for foreach() in /usr/share/php/xhprof_lib/display/xhprof.php on line 854
Overall Summary	

[View Full Callgraph]


Displaying top 100 functions: Sorted by Incl. Samples [ display all ]


Function Name
[ display all ]

**Comment by geerlingguy** [comment]
Just a quick note that Devel's xhprof support will be gone in its next stable release (it's already gone in the dev release). You should try switching to the xhprof module (https://www.drupal.org/project/xhprof) and see if you have any better luck with it.

**Comment by sdemi** [comment]
Thanks. xhprof module is way better.

**Comment by shashwatpurav** [comment]
I had faced the same issue in one of my projects. I got it resolved by following pointers:

> Created "xhprof" directory in the /tmp folder.
> "xhprof_lib" and "xhprof_html" folders should be at same level. At "/usr/share/php" in my case.

Set the following at "admin/config/development/devel":

xhprof directory: /usr/share/php
xhprof URL: /xhprof_html

Flush cache and it works. :)
