### ISSUE TITLE
Provision fails on [geerlingguy.drush | Clone Drush from GitHub.]

### ISSUE THREAD

**Issue by robdecker** [geerlingguy/drupal-vm#239]
Running `vagrant provision` on an existing VM fails.

```
TASK: [geerlingguy.drush | Clone Drush from GitHub.] **************************
failed: [8x8] => {"failed": true}
msg: Local modifications exist in repository (force=no).

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/rob/playbook.retry

8x8                        : ok=75   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
@robdecker - can you please run `sudo ansible-galaxy install -r provisioning/requirements.txt --force` (on your host machine, in same folder as Vagrantfile), and then provision again? There's an update to the Drush role, I think, which should have resolved this problem.

**Comment by robdecker** [comment]
I had already run that command. I did run it again, and tried provisioning again, with the same error results.

**Comment by geerlingguy** [comment]
@robdecker - Can you run that command once more (so you get the new version of the drush role I just updated), and then add the following line of configuration to your `config.yml`:

```yaml
drush_force_update: yes
```

Then run `vagrant provision` again and see if it completes?

**Comment by robdecker** [comment]
Yay, we have success.

**Comment by geerlingguy** [comment]
Nice! I'll close this out and hopefully people will find this issue in the future and can dig up the workaround :)
