### ISSUE TITLE
Multiple PHP versions per vhost

### ISSUE THREAD

**Issue by peterlavelle** [geerlingguy/drupal-vm#241]
Hi,

Are there any plans to implement a feature to allow users to run each vhost under a different version of PHP?

Regards

Peter Lavelle

**Comment by geerlingguy** [comment]
@peterlavelle thanks for the question, but no, not at this time. I typically recommend an instance per version of PHP (I generally have two or three active instances of Drupal VM on my computer, and about 15 different versions that are customized for particular Drupal projects or for different core/module hacking).

**Comment by budda** [comment]
Is it something that would be considered @geerlingguy if a patch was offered?

Being able to have one VM up and switching between many local sites using different Drupal and PHP versions is handy for a service desk / support role.
