### ISSUE TITLE
Remove special setting for KVM virtualization

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#249]
...since I just built a new version of all four boxes, and they all have KVM virtualization enabled by default for VirtualBox, I can remove the line `v.customize ["modifyvm", :id, "--paravirtprovider", "kvm"]` that was added in Issue #212

**Comment by joestewart** [comment]
Sorry for commenting on a closed issue.  Is there documentation now for "vagrant box update" to use the new boxes? I do see it mentioned at http://docs.drupalvm.com/en/latest/other/vagrant-virtualbox/

**Comment by geerlingguy** [comment]
@joestewart - I might consider adding a special section "Updating Drupal VM", because there are a few steps to it and it's better to document it than keep answering it in individual issues when people need to update either the Ansible roles, Drupal VM itself, or Vagrant/VirtualBox.
