### ISSUE TITLE
Mac OSX vagrant up fails at flushing iptables

### ISSUE THREAD

**Issue by dannyacquia** [geerlingguy/drupal-vm#252]
```
TASK: [geerlingguy.firewall | Flush iptables the first time playbook runs.] *** 
failed: [drupalvm] => {"failed": true}
msg: this module requires key=value arguments (['iptables', '-F', 'creates=/etc/init.d/firewall'])

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/danny.wilford/playbook.retry

drupalvm                   : ok=6    changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Ansible was giving all sorts of errors before I could even get to this point.  After trying multiple versions i finally got 1.9.2 to work.  But after that was resolved, the vagrant up keeps failing at the above task.

**Comment by dannyacquia** [comment]
I had to run a submodule update within ansible after I changed the version to 1.9.2

Seems to be working know.

**Comment by geerlingguy** [comment]
@dannyacquia - Just FYI, unless you're actively hacking on the Ansible project (working on Ansible bugs or features), it's generally a bit easier to install Ansible via `brew` or `pip` instead of from source :)
