### ISSUE TITLE
Vagrantfile:33:in `block in <top (required)>': undefined method `empty?' for nil:NilClass (NoMethodError)

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#253]
Sorry, I'm not quite sure what's going on here. I'm running `vagrant up` and seeing:

```
/home/kosta/src/drupal-vm/Vagrantfile:33:in `block in <top (required)>': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/v2/loader.rb:37:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:103:in `block (2 levels) in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:97:in `block in load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/config/loader.rb:94:in `load'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/vagrantfile.rb:28:in `initialize'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `new'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:689:in `vagrantfile'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:441:in `host'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:207:in `block in action_runner'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:33:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:428:in `hook'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:671:in `unload'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `ensure in <main>'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:177:in `<main>'
```
---
``` yaml
ruby: ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-linux]
vagrant: Vagrant 1.7.4
virtualbox: 5.0.4r102546
os: fedora 22
```

I've got other Vagrant boxes running on my laptop. Is this a Ruby language version issue?

**Comment by geerlingguy** [comment]
@kostajh - Do you have a `vagrant_public_ip` configured in your `config.yml`? It should be set to `""` if you're not using it. If it's not defined, that error would occur.

**Comment by kostajh** [comment]
Ok, disregard. I was using an older config file from a few months ago with the latest HEAD from this project. `vagrant up` is churning away now!

**Comment by geerlingguy** [comment]
@kostajh - No problem! I try to write up decent release notes each tagged version, but I should probably also be a little better about notifying of new variables in config.yml each release!

**Comment by weitzman** [comment]
Bit me too. Wish the error message was more approachable.

**Comment by geerlingguy** [comment]
:( sorry about that!

**Comment by dmheer08** [comment]
@geerlingguy I'm encountering this same issue while trying to vagrant up a ubuntu/trusty64 box. Where is the config.yml file located? I'm looking in all of the system folders and also doing a global search and cannot find it. Only can find "config-example.yml"

**Comment by dmheer08** [comment]
/Vagrantfile:20:in `block in <top (required)>': undefined local variable or method `"\u201Cubuntu"' for main:Object (NameError)
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/v2/loader.rb:37:in `load'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:125:in `block (2 levels) in load'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `each'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:119:in `block in load'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `each'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/config/loader.rb:116:in `load'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/vagrantfile.rb:28:in `initialize'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `new'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:810:in `vagrantfile'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:556:in `host'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:214:in `block in action_runner'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/action/runner.rb:33:in `run'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:543:in `hook'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/lib/vagrant/environment.rb:792:in `unload'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `ensure in <main>'
        from E:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-2.0.0/bin/vagrant:141:in `<main>'
