### ISSUE TITLE
drush aliases generated with wrong ssh port?

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#259]
`drupalvm.aliases.drushrc.php.j2` uses variable `ansible_ssh_port` which evaluates to  the mapped target  (e.g. '2222') rather than the source (e.g. '22').
So `drush` commands time out whilst waiting for port 2222 but succeed when the ssh port number in the  generated alias file is changed to 22.
Not quite sure what the intention was in using a non-standard ssh port was in this case.

**Comment by geerlingguy** [comment]
@iainhouston - The rationale is posted in the PR https://github.com/geerlingguy/drupal-vm/pull/202; however, looking at the logic, I can see how this could quickly mess someone up if they have multiple VMs on their laptop, bringing them up and down changing the port numbers (via Vagrant) automatically, but without updating the drush aliases file.

So I'm going to revert that patch, and simply recommend that anyone using Drupal VM and expecting all the Drush aliases to work will either be using the hostsupdater plugin, or have added the hosts aliases to their local hosts file.
