### ISSUE TITLE
Using drush when directories are synced with rsync

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#261]
I'm wondering what strategy is recommended for using drush to update/download code when directories are synced using `rsync`. `drush up {module}`, `drush features-export` and `drush up --security-only` are all pretty important, but if we use rsync as the sync method, then the code only gets updated in the VM, and not on the host.

Any ideas? How are others getting around this issue?

**Comment by oxyc** [comment]
Would be intrested in a smoother workflow for this too.

At the moment I'm using some make tasks to pull in changes

```make
rsync-pull-custom: rsync-check
	vagrant ssh-config --host default > vagrant-ssh-config
	@echo -e "${CSTART} Running dry run to display file changes ${CEND}"
	rsync --dry-run --verbose --recursive -e 'ssh -F vagrant-ssh-config' default:${DRUPAL_ROOT}/sites/all/modules/${PULL_CUSTOM}/ sites/all/modules/${PULL_CUSTOM}
	read -p "Are you sure you want to run this command? [y/N]" -n 1 -r; \
		echo; \
		if [[ $$REPLY =~ ^[Yy]$$ ]]; then \
			rsync --recursive --verbose -e 'ssh -F vagrant-ssh-config' default:${DRUPAL_ROOT}/sites/all/modules/${PULL_CUSTOM}/ sites/all/modules/${PULL_CUSTOM}; \
		fi
	rm vagrant-ssh-config

rsync-pull-contrib:
	PULL_CUSTOM=contrib make rsync-pull-custom

rsync-pull-features:
	PULL_CUSTOM=features make rsync-pull-custom
```

**Comment by kostajh** [comment]
thanks for sharing that @oxyc. Another idea I just had was to set up an SSH tunnel so that I can connect directly to MySQL from the host machine; then I can adjust my Drush alias to use the SSH tunnel, and run `drush updb / dl / etc` from the host, and have the files updated on the host (& rsynced over to the VM).

It would be cool to have an option in the config for Drupal VM to open up an SSH tunnel on `vagrant up`

**Comment by oxyc** [comment]
Sounds brilliant!

**Comment by kostajh** [comment]
Actually thinking about this a bit more, I'm not sure what I want to do will be possible. Basically, you'd have to define a Drush alias that (1) knows the docroot is in the VM, (2) that implies that you need to set remote-host and remote-user, in which case (3) any MySQL connection that we define in the alias would be used from *within* the guest, and not on the host.

As an awkward alternative I suppose you could have a second alias where the docroot is the path on the host, and the SQL connection uses an SSH tunnel to connect to the VM. But yeah, that's not ideal.

**Comment by geerlingguy** [comment]
Closing this for now; good ideas in the comments, but I don't see any actionable changes I can make to improve the experience. If someone can propose some documentation additions to a section on file sync methods and/or rsync in particular, open a PR or an issue with some suggested language.
