### ISSUE TITLE
Connect pantheon db to drupal-vm

### ISSUE THREAD

**Issue by cromosom** [geerlingguy/drupal-vm#262]
Hi,
is it possible to connect the db of the vm to a remote db on pantheon?

**Comment by geerlingguy** [comment]
Sort-of; you can have Drupal point to a database anywhere, as long as the database configuration in settings.php can point to that database over the active network connection on your computer.

However, what most people would do is grab a copy of the database off pantheon, or use Drush sql-sync to sync the database from Pantheon to your Drupal VM instance; this way you don't have to deal with the tremendous latency of using a database over the Internet.
