### ISSUE TITLE
Parallels Support:  Box needed for Parallels provider

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#263]
Attempted to get DrupalVm working with Parallels on El-Capitain.  When I do vagrant up I get the following error
```
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: geerlingguy/ubuntu1404
Address: https://atlas.hashicorp.com/geerlingguy/ubuntu1404
```

When I visit that URL it appears that there is no box for the parallels provider .

**Comment by aweingarten** [comment]
Update I got parallels to work:

### Config.yml
I had to change `vagrant_box` since there is no geerlingguy/ubuntu1204 box for parallels.    Searched here: 
https://atlas.hashicorp.com/boxes/search?provider=parallels

Ended up picking:  `parallels/ubuntu-14.04`  although `puphpet/ubuntu1404-x64 ` also seemed like a reasonable choice.

Parallels choked on the default ip address in `vagrant_ip` I changed it to ` 192.168.1.200` I need to experiment looking for a better IP though.  

### vagrantfile
Since I have virtual box AND parallels installed out of the box I had trouble telling vagrant to use parallels instead of virtual box.  I found that I could simply move the parallels section above the virtualbox section:

```
  # Parallels.
  config.vm.provider :parallels do |p, override|
    override.vm.box = vconfig['vagrant_box']
    p.name = vconfig['vagrant_hostname']
    p.memory = vconfig['vagrant_memory']
    p.cpus = vconfig['vagrant_cpus']
  end


# VirtualBox.
  config.vm.provider :virtualbox do |v|
    v.name = vconfig['vagrant_hostname']
    v.memory = vconfig['vagrant_memory']
    v.cpus = vconfig['vagrant_cpus']
    v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    v.customize ["modifyvm", :id, "--ioapic", "on"]
  end
```

After that I had a fully functioning DrupalVM!

**Comment by geerlingguy** [comment]
@aweingarten - One other note—even though the Parallels config is by default later than the VirtualBox config, you can tell vagrant at runtime which provider to use (since I have VMware and VirtualBox I have to do this a lot):

```
# Build the VM with the VirtualBox provider, even if others are present/higher in Vagrantfile.
vagrant up --provider=virtualbox

# Same, but with VMware Fusion
vagrant up --provider=vmware_fusion

# Same, but with Parallels.
vagrant up --provider=parallels
```

Also, I just made sure `example.config.yml` contains a listing of boxes that can be used:

```
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1404
```

I hope that's sufficient for now. I've only had a few people report using Parallels, so I don't want to spend too much time/documentation on using Drupal VM with Parallels, especially since I don't have a license or an official minimal box that I manage for it.

**Comment by heihachi88** [comment]
Any updates on Parallels?

**Comment by geerlingguy** [comment]
Parallels' boxes are controlled by Parallels, and since I don't have a licensed copy of Parallels, I'm unable to provide anything better than 'hopefully it works'-levels of support for Parallels boxes.
