### ISSUE TITLE
Support Composer Installs

### ISSUE THREAD

**Issue by nateswart** [geerlingguy/drupal-vm#265]
With Drupal 8 leveraging composer more and more, it would be great to be able to specify sites to be installable via composer as well (currently DrupalVM appears to support just drush make?).

**Comment by geerlingguy** [comment]
@nateswart - So, as someone who has never installed _Drupal_ using Composer before, but has installed plenty of other PHP apps, what would this process even look like. AFAICT, there's still an open debate over whether Drupal.org will support Packagist or build/host it's own Drupal-specific packagist.

**Comment by webflo** [comment]
_Shameless Plug:_ https://github.com/drupal-composer/drupal-project provides a good template if you want to user composer with D8.

**Comment by nateswart** [comment]
Thanks @webflo - we're actually already using that. Nice work!

@geerlingguy The more I think about it, the less I think this is required. Having composer installed on the VM by default is enough. Closing.

**Comment by emarchak** [comment]
@nateswart is there any documentation on how to use a composer workflow instead of drush make in a VM build? There isn't anything immediately available in the docs.

**Comment by geerlingguy** [comment]
@emarchak - Please follow the discussion in #506; we'll be switching Drupal VM to use Composer by default soon (hopefully!), and there may be some fruitful discussion in that issue.
