### ISSUE TITLE
Integrate Drulenium visual regression testing

### ISSUE THREAD

**Issue by devekko** [geerlingguy/drupal-vm#266]
https://www.drupal.org/project/drulenium

Visual/CSS regression testing
The sub module drulenium_visual_regression helps in Automating Visual/CSS regression testing.
Concept:

The system takes Image screenshots of web pages, before you make changes like site upgrades to your site.
The system takes another set of Image screenshots of web pages, after you make changes
The system calculates the difference of image pixels that changed and generates an animated GIF to look at
Video Demo: https://www.youtube.com/watch?v=8D4SpfspNbU

**Comment by geerlingguy** [comment]
Drulenium looks like it would be best suited as an installed dependency within a Drupal site; you could edit the default drupal.make.yml file to add it in during installation, or if you have your own site being installed inside the VM, you can add the module to that site. AFAICT, there's no need to have it installed separate from a Drupal site in the VM.

**Comment by devekko** [comment]
it actually has a significant server component and would be suitable for installation on the VM itself

it does visual regression testing and is used at edx.org

**Comment by geerlingguy** [comment]
Interestingly, Edx is a major Ansible user: https://speakerdeck.com/jarv/how-edx-uses-ansible

**Comment by devekko** [comment]
I message TechNik with links to this thread. 

You are halfway there, with Selenium already installed

its really, very good and could save huge amounts of time and money in testing

**Comment by devekko** [comment]
https://www.drupal.org/node/2284921
http://drulenium.technikh.com/installation

**Comment by devekko** [comment]
I should add, its uses in the Drupal part of edx.org ... the mooc system is a python / django app I think
