### ISSUE TITLE
Vagrant up fails at " Move Drupal Console into globally-accessible location."

### ISSUE THREAD

**Issue by Canutza** [geerlingguy/drupal-vm#271]
I get an error when I run `vagrant up`:

```
==> drupalvm: TASK: [geerlingguy.drupal-console | Move Drupal Console into globally-accessible location.] ***
==> drupalvm: failed: [localhost] => {"changed": true, "cmd": "mv console.phar /usr/local/bin/drupal", "delta": "0:00:00.004267", "end": "2015-10-15 12:49:02.188809", "rc": 1, "start": "2015-10-15 12:49:02.184542", "warnings": []}
==> drupalvm: stderr: mv: cannot stat ???console.phar???: No such file or directory
==> drupalvm:
==> drupalvm: FATAL: all hosts have already failed -- aborting
==> drupalvm:
==> drupalvm: PLAY RECAP ********************************************************************
==> drupalvm:            to retry, use: --limit @/root/playbook.retry
==> drupalvm:
==> drupalvm: localhost                  : ok=85   changed=2    unreachable=0    failed=1
```

I just changed the `local_path` in config.yml config file, the rest is the intact. I run vagrant under Windows 7, if this matters. I tried destroying the machine and running it again, but no luck.

Thank you.

**Comment by geerlingguy** [comment]
Strange; I haven't heard any reports of this happening elsewhere, and I just re-provisioned a few VMs and can't reproduce the error. Are you maybe behind a proxy, or can you run `vagrant provision` and have it reprovision the VM to see if it fixes itself?

**Comment by Canutza** [comment]
I run `vagrant up` and it fails with the error above and then I tried `vagrant provision` and the same error occurs. 
As far as I know, I'm not behind any proxy.

**Comment by geerlingguy** [comment]
I reinstalled Drupal VM locally without Ansible (so it ran inside the VM) and still can't get this error to be reproducible. Have you tried running `vagrant destroy` to completely remove the VM, then `vagrant up` again? I'm guessing you might be running into some sort of permissions issue or some gremlin.

**Comment by Canutza** [comment]
Yes, I tried `vagrant destroy` and then `vagrant up` again, I even removed everything and re-cloned the whole repository, still no luck. I will try this again on my personal laptop.

**Comment by geerlingguy** [comment]
FYI I just purchased a Windows laptop so I can start testing these things out. Hopefully I'll be able to reproduce the error somehow so I can see how to fix it!

**Comment by geerlingguy** [comment]
I am still not able to reproduce this error on either Windows 7 or Windows 10 :(

**Comment by Canutza** [comment]
Ok then, maybe there is some sort of strange configuration on my laptop since this is a work one. Thank you anyway, really appreciate your effort for this task and for the vm.

**Comment by joevallender** [comment]
Just for anyone else searching this: I'm having the same issue but can see that the http://drupalconsole.com/installer address used in the Ansible role https://github.com/geerlingguy/ansible-role-drupal-console/blob/master/tasks/main.yml is giving me 'Connection refused' so just have to wait for the site to come back I guess.

**Comment by martinmenge** [comment]
@joevallender Thank you
