### ISSUE TITLE
Unclear ruby_install_gems syntax

### ISSUE THREAD

**Issue by NiklasBr** [geerlingguy/drupal-vm#272]
Apologies in advance for what might be a question better suited for Ansible, it might also be because I am not very experienced with Vagrant + Ansible. Anyway, to the point, I have been unable to properly configure the `ruby_install_gems` section to install `sass`. It feels like I have tried every permutation of [the documentation](http://docs.ansible.com/ansible/gem_module.html).

None of these works when editing `config.yml`:
```
ruby_install_gems:
  - gem: name=sass
```
```
ruby_install_gems:
  - { name: sass, release: '@stable' }
```
```
ruby_install_gems:
  - name: sass
```
```
ruby_install_gems:
  - sass
```
```
ruby_install_gems:
  - name: sass
  ```
```
ruby_install_gems:
  - {name: sass, release: stable}
```
```
ruby_install_gems:
  - gem: 'name=sass'
```
```
ruby_install_gems:
  - gem: name="{{ sass }}"
```
```
ruby_install_gems:
  - gem: "{{name=sass}}"
```

Any pointers would be very appreciated! Everything else runs smooth with this VM, logging in with `vagrant ssh` and then running `sudo gem install sass` is all I need to do though.

**Comment by geerlingguy** [comment]
Sorry about that—the syntax is very simplistic right now, and it's just a list of gems; you can only install the latest version:

```
ruby_install_gems:
  - sass
```

See role documentation: https://github.com/geerlingguy/ansible-role-ruby

**Comment by NiklasBr** [comment]
````
ruby_install_gems:
  - sass
````
Unfortunately I can't get the above to work. [See terminal output](https://gist.github.com/NiklasBr/0e873ae91ddc90b47ba4#file-gistfile1-txt-L1311) where it looks like it installs sass, but once logged into the VM `gem list` does not include `sass` (scroll down to line 1571).

**Comment by geerlingguy** [comment]
@NiklasBr - If you log in and enter `sudo su`, then `gem list`, does it work properly?

**Comment by NiklasBr** [comment]
It does!

I wonder though how I can get `npm` modules such as `grunt` to automatically acknowledge `sass` under a different user… But maybe that's a different question?

**Comment by geerlingguy** [comment]
@NiklasBr - I think it's something I can improve upstream in the Ruby role; ability to install gems as a different user.

**Comment by NiklasBr** [comment]
@geerlingguy thanks!

geerlingguy/ansible-role-ruby/issues/11 seems related

**Comment by oxyc** [comment]
This was fixed upstream https://github.com/geerlingguy/ansible-role-ruby/commit/bb51fc58844830cf3bc605b924236f438efc2d83.

As of https://github.com/geerlingguy/drupal-vm/commit/5f0d89010d52cbffe067abfbc135278cb06d9e8f the user defaults to `vagrant` on Drupal VM as well.

**Comment by fb-multimedia** [comment]
First, I want thank you Geerlingguy for this project ! I'm a beginner on linux vm and I was  before working with wamp for my drupal theming projects. It's really help me to introduce linux environment.
So I've a little issue ruby gems installer. When I add to my config.yml:
```
ruby_install_gems:
  - compass
  - sass
  - less
```
After vagrant ssh, gems are present in the gem list and it show good gem versions. But I can't use them, the console say there is no program compass installed. 
To make gems work I have to install them in a .sh file with :
```
yes | sudo apt install ruby-compass
yes | sudo apt install ruby-sass
```
did I miss something to make it work simply with ruby install gem ?
Thanks

**Comment by oxyc** [comment]
@fb-multimedia would you mind posting this as a new issue report?

> But I can't use them, the console say there is no program compass installed.

Just to clarify, when exactly does it say there's no such progarm? Are you running a `compass` command in the shell, or is it some preprocessor?

**Comment by fb-multimedia** [comment]
Yes It could be a new issue, can you move this ? or I have to repost as new one ?

**Comment by oxyc** [comment]
Better if you repost it and fill out all the questions in the issue template.

**Comment by fb-multimedia** [comment]
ok
