### ISSUE TITLE
Issue with Memcache

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#275]
I had memcache commented out in the "extras" section and got this:

TASK: [geerlingguy.memcached | Include OS-specific variables.] **************** 
fatal: [viola] => Failed to template {% if "memcached" in installed_extras %} True {% else %} False {% endif %}: an unexpected type error occurred. Error was argument of type 'NoneType' is not iterable

**Comment by geerlingguy** [comment]
Can you post what you have currently for the `installed_extras` variable?

**Comment by nerdstein** [comment]
its set to null

**Comment by geerlingguy** [comment]
Ah, try `installed_extras: []` instead.
