### ISSUE TITLE
Documentation: code blocks in lists not rendering properly

### ISSUE THREAD

**Issue by scottreese** [geerlingguy/drupal-vm#280]
There are a couple of code blocks on this page: http://docs.drupalvm.com/en/latest/extras/behat/ that are not rendering properly - most likely due to them being in a list.

As discussed in #279 for reference.

**Comment by geerlingguy** [comment]
Looks like I got this cleaned up. No idea how, but it's working now :D

**Comment by scottreese** [comment]
The behat.yml file looks OK but the test snippet in list item number 3 is still not rendering at all.

**Comment by geerlingguy** [comment]
Oops! Looking into it.

**Comment by geerlingguy** [comment]
Working now.
