### ISSUE TITLE
user VMachines doesn't exist (ArgumentError)

### ISSUE THREAD

**Issue by justaserr** [geerlingguy/drupal-vm#283]
Hello,

I am following guide on https://github.com/geerlingguy/drupal-vm#quick-start-guide and running **vagrant up** gives error */usr/share/vagrant/plugins/kernel_v2/config/vm.rb:553:in `expand_path': user VMachines doesn't exist (ArgumentError)*.

And also further notes:
	from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:553:in `expand_path'
	from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:553:in `block in validate'
	from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:548:in `each'
	from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:548:in `validate'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/root.rb:68:in `block in validate'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/root.rb:64:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/root.rb:64:in `validate'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/config_validate.rb:15:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/handle_box.rb:56:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builtin/call.rb:53:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/share/vagrant/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/warden.rb:34:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/builder.rb:116:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `block in run'
	from /usr/lib/ruby/vendor_ruby/vagrant/util/busy.rb:19:in `busy'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:66:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:196:in `action_raw'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:173:in `block in action'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:440:in `lock'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/machine.rb:161:in `action'
	from /usr/lib/ruby/vendor_ruby/vagrant/batch_action.rb:82:in `block (2 levels) in run'

What is the problem?
Thanks.

**Comment by geerlingguy** [comment]
Can you check the versions of everything on your host machine—`vagrant --version` (should be 1.7.4+), `vboxmanage --version` (should be 5.0.0+)?

**Comment by justaserr** [comment]
Vagrant version 1.6.5
Vboxmanage version 4.3.26
I simply created new user called VMachines and it all worked. But anyway, should I update?

**Comment by geerlingguy** [comment]
Yes, those versions are pretty far behind what the current box and configuration is built and tested on. I think the latest version of VirtualBox creates whatever user it needs automatically.
