### ISSUE TITLE
Shared/team configuration setup

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#285]
Hi @geerlingguy,

I'm wondering if it would be possible for Drupal VM to support an `imports` directive in the `config.yml`, that could load a user's `config.yml` to override the default values in `config.yml` (much like how Behat supports doing so).

The scenario I'm thinking of is:

- A team has a shared Drupal VM configuration tracked in version control which contains configuration for that team's websites, tools, etc
- Each team member can adjust parameters of that config (e.g. the directories where they store their code on the host, the memory allocated to the VM, etc) in a `local.config.yml` that's not tracked in version control

I'd love to be able to say to my team: do a `git pull` on our shared configuration repo, clone X drupal site repository to your code directory, run `vagrant up`, and you've got your local environment set for that site.

At the moment, this involves sharing snippets of `config.yml` code (vhost, SSL vhost, database, directory mappings) with others.

Thanks for considering!

**Comment by geerlingguy** [comment]
Yeah, true... when I originally built Drupal VM, it was pretty much a "use for individual projects by one or two devs" thing, but more and more dev teams are standardizing on it, so something like this is definitely desirable.

My favored approach would be to do this the same way you can do a `local.settings.php` with Drupal through the settings.php conditional include, but it might not be very simple to do it until Ansible 2.0 is released—see highly related issue #174 !

**Comment by geerlingguy** [comment]
I'm going to merge this issue into #305 — rather than push towards one specific use case, I'd like to get a good survey of how different teams are building and sharing Drupal VM configurations, and then see if there are some common and simple ways to make that more standardized or efficient.
