### ISSUE TITLE
Add Redis as optional install

### ISSUE THREAD

**Issue by jiv-e** [geerlingguy/drupal-vm#289]
Add feature: Redis as optional install.

See https://github.com/geerlingguy/drupal-vm/issues/287

**Comment by chasingmaxwell** [comment]
I'd love to see this too!

**Comment by odavies-cti** [comment]
+1

**Comment by odavies-cti** [comment]
I've got this to work following the steps in #287.

**Comment by geerlingguy** [comment]
Sorry for the lack of fanfare here; this issue's been on my mind for months now, and I finally got some time this weekend to test a new Ansible role which makes sure the PhpRedis extension works and is installable on Ubuntu 12/14, CentOS 6/7, and even Debian flavors—with either PHP 5.5, 5.6, or even 7.0! (you have to flip around some vars to get that to work, so it's still not officially supported with 7.0 ;).

Just add `redis` as one of the `installed_extras`, set up your drupal site to point at 127.0.0.1, and away you go!
