### ISSUE TITLE
ERROR: cannot find role in geerlingguy.repo-remi

### ISSUE THREAD

**Issue by rihards** [geerlingguy/drupal-vm#294]
Hey,

just cloned a fresh copy of the project, edited the two yml files and created the local_path directory as instructed. Then I tried running vagrant up (and vagrant provision after that failed) and both times it was the same error:

ERROR: cannot find role in /Users/rihards/VMs/drupal-vm/provisioning/roles/geerlingguy.repo-remi or /Users/rihards/VMs/drupal-vm/provisioning/geerlingguy.repo-remi or /usr/local/etc/ansible/roles/geerlingguy.repo-remi
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Please make sure you have installed all the required roles if you have Ansible installed on your workstation: `sudo ansible-galaxy install -r provisioning/requirements.yml --force`.

**Comment by rihards** [comment]
My bad, didn't notice that bit in the documentation at first. Thanks.
