### ISSUE TITLE
Provisioning failure on Linux with ansible

### ISSUE THREAD

**Issue by bithead42** [geerlingguy/drupal-vm#296]
First, I'm new to drupal and had never heard of vagrant until trying to get a drupal system online.  I initially tried to get a vdd installation up and running, but never succeeded.  And so looking around I happened upon drupal-vm, and learned there is something called ansible.  I've tried to install vdd and drupal-vm on Linux and Windows platforms, with 0 success to date.  This issue is about my Linux installation of drupal-vm.

Host: Debain Jessie, all updates installed to date
Vagrant v1.6.5
VirtualBox v4.3.32

I know these are not the recommended versions of vagrant and virtualbox, but they are the latest available from official Debian sources.  If my issue requires upgrading to the more recent .deb files, I will consider it, but I'm trying to keep the box as "pure" as possible with officially sanctioned packages.  FWIW, I did try installing drupal-vm on a VM running in the host, since I had license to install anything I wanted on it - for those who haven't been there, a VM can't provide the HW-based AMD-V support required for a 64-bit VM running inside of it (yeah, I know... my head hurts too).  Anyway, onto the current problem...

The provisioning process mounts the nfs shared folder successfully, then dies with:

`==> drupalvm: Running provisioner: ansible...`
`Traceback (most recent call last):`
`  File "/usr/local/bin/ansible-playbook", line 4, in <module>
    import pkg_resources`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2876, in <module>
    working_set = WorkingSet._build_master()`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 451, in _build_master
    return cls._build_from_requirements(__requires__)`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 464, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())`
`  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 639, in resolve
    raise DistributionNotFound(req)`
`pkg_resources.DistributionNotFound: ansible==2.0.0`
`Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

This was without ansible installed on the host, but isn't the ansible command running in a `vagrant ssh` session, in which case installation on the host isn't relevant?  Even so, with ansible 1.7.2 installed on the host, I get the same results during provisioning.  In fact, with ansible installed, I get the same result as above when executing `sudo ansible-galaxy install -r provisioning/requirements.yml --force`.

And finally, when in a `vagrant ssh` session, `dpkg -l | grep ansible` comes up empty.  Presuming it wasn't installed from a debian source, is there another way to verify its installation in the VM?  Thanks!

**Comment by bithead42** [comment]
Thanks everyone for your thoughts about this, even though none of them seemed to make it here.  While you've been racking your brains, I've managed to get a vagrant-free installation of drupal 8 up and running.  For some reason this turned out to be much easier for me to do than using a preconfigured distribution.  I'll be considering this closed since I won't be pursuing it further.

**Comment by geerlingguy** [comment]
@bithead42 - If you're trying to install Drupal VM, you need at least Vagrant 1.7.x, and Virtualbox 5.x.x, so you would need to install them from different sources (or if in the UI, from a download via the web). The ancient versions in the debian apt repos or in yum (on RHEL systems) are missing a ton of features required for Drupal VM to operate.

On top of that, Ansible's latest stable release is 1.9.x (2.0.0 is still in RC status), so nothing is guaranteed to work with the latest `devel` version if you install Ansible via source.

It's good that you can install Drupal directly on your system, but hopefully you will get to do some more work with Vagrant/VMs sometime and see how they can be really helpful! Thanks.

**Comment by bithead42** [comment]
Thank you. �It looks like I'll need an additional Linux box in order to work with Drupal VM then, as I need to keep this one clear of unapproved packages. �Nevertheless, I appreciate the comments and clarification.

________________________________
