### ISSUE TITLE
Add notes about Windows performance improvements for VirtualBox and Vagrant

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#297]
Now that I have a Windows laptop (Lenovo ThinkPad T420 with 8GB RAM and upgraded SSD), I am doing some preliminary work testing different configurations, synced folder methods, etc. I'd like to document some tips and tricks specific to Windows users in the docs, so I'm leaving this issue open until I feel I've added as much as I can.

I don't want the poor Windows users to have to suffer through page loads 2x+ longer than Mac/Linux!

**Comment by geerlingguy** [comment]
Did some initial informal testing with SMB vs. native shared folders in VirtualBox, and my results were a bit inconclusive. I'll need to do a bit more work to find some meaningful benchmark data.

Also, I had some trouble using NFS with the `vagrant-winnfsd` plugin and Windows 10, but I've since rebuilt the PC with a fresh copy of Windows 10, and I'd like to take another stab and see if NFS is more stable than SMB or native.

**Comment by kevinquillen** [comment]
The winnfsd plugin has had some ups and downs. There was a point where it worked well, then a bug was introduced where it wasn't syncing right, and now it feels hit or miss..

**Comment by geerlingguy** [comment]
I've added what I could think of so far. Other than that, if I (or anyone else) can think of more performance enhancements or gotchas to document, please open specific issues.
