### ISSUE TITLE
Need to run vagrant reload frequently after sleep w/ Fedora host

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#298]
I'm not sure if this is a general vagrant issue, or something specific to Fedora, but thought I'd throw it out here to see if others are having this issue. `vagrant up` works great, I can access sites, no issues. If I put my computer to sleep and wake it up, I need to run `vagrant reload` to reset network interfaces. This isn't a huge problem but it is annoying. Does anyone know of workarounds for this issue? Do mac users experience this issue?

**Comment by geerlingguy** [comment]
I haven't had a problem with sleep/wake on my Mac or on a Windows 10 environment, but I'm guessing this is an upstream issue with VirtualBox and Fedora.

I'm trying to get a Fedora 23 environment up for testing, and may be able to give you some more feedback later.

**Comment by kostajh** [comment]
OK, thanks for the notes Jeff!

Jeff Geerling writes:

> I haven't had a problem with sleep/wake on my Mac or on a Windows 10 environment, but I'm guessing this is an upstream issue with VirtualBox and Fedora.
>
> I'm trying to get a Fedora 23 environment up for testing, and may be able to give you some more feedback later.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/geerlingguy/drupal-vm/issues/298#issuecomment-153454242

-- 
@kostajh | kosta@kostaharlan.net

**Comment by geerlingguy** [comment]
Just waiting on a hard drive bracket in the mail so I can install a separate drive on my PC for Fedora... I could do everything over USB 2.0 but it would be unbearably slow :P

**Comment by kostajh** [comment]
One thing I've tried may have fixed it. If I open up VirtualBox, click on the VM, go to the Settings -> Network, and click on "Adapter 2", there is an option for "Promiscuous Mode". The default setting was "Deny", if I change it to "Allow All" then I'm able to access the VM over HTTP again.

**Comment by kostajh** [comment]
Hmm. I think I was overly optimistic. That's not working now.

**Comment by geerlingguy** [comment]
D'oh! I completely forgot to do some testing with my new laptop and Fedora 22... I have everything set up, but I don't know if I'll have time to get to it this weekend. It might be a few more days before I can give some more data points and we can figure out what's going on.

**Comment by kostajh** [comment]
@geerlingguy I should note that my colleague @annetee is running into the same issue on an older Mac (latest OS and VirtualBox versions, though, I believe)

**Comment by AnneTee** [comment]
Not sure if @kostajh is still having this issue, but I'm now on an early 2015 Macbook Pro running El Capitan and no longer have to reload the VM after my computer goes to sleep. :octocat:

**Comment by geerlingguy** [comment]
Ditto the no-issues-on-OS X from @AnneTee; I've had a few people test with Macs, and the following didn't have sleep issues:

  - MacBook Air 13" i7 2013, 10.11
  - MacBook Air 11" i5 2012, 10.11
  - MacBook Air 13" Core 2 Duo 2010, 10.10
  - Retina MacBook Pro 13" i7 2014, 10.11

If anyone else runs into these issues, please post model of your computer as well as the OS and version. I'll try to get back to testing this on my Fedora laptop too (Lenovo T420).

**Comment by kostajh** [comment]
One thing I noticed. I now have a repo-specific VM based on Drupal VM, and a general box based on Drupal VM with a collection of sites. After the laptop wakes up from sleep, neither box is accessible. But if I run `vagrant reload` on one of them, the sites on the other come back online. I'm guessing this is due to the `resetting network interfaces` message that Vagrant gives in the up/reload process. Either way, doesn't seem like a problem for Drupal VM.

**Comment by geerlingguy** [comment]
@kostajh - Yeah, I'm going to close this issue and then just let people comment if they have any other issues—I haven't had an issue with it on Fedora 22 on my Lenovo, but I'm only running one instance at a time. Maybe it's some other weird thing in the system, who knows :(

**Comment by vinaymor002** [comment]
sudo vim /etc/NetworkManager/NetworkManager.conf
Added the following lines

> [keyfile]
> unmanaged-devices=interface-name:vboxnet0
> 

Do vargrant reload

**Comment by ryancwalsh** [comment]
@geerlingguy I'm not using drupal-vm (I'm running Laravel Homestead on Vagrant), but I haven't found much via Google (other than this issue!) that describes what I experience: every time my Win 10 machine wakes up, I need to run `homestead.bat reload --provision`.

@vinaymor002 Can you please explain what you're doing there and maybe point to some documentation?

Thanks for any tips, everyone. :-)

**Comment by oxyc** [comment]
> Can you please explain what you're doing there and maybe point to some documentation?

Here's the [source](https://www.virtualbox.org/ticket/13873) but unfortunately it's linux specific.

I saw your comment here but listing for future reference:
- https://www.virtualbox.org/ticket/14374
- https://www.virtualbox.org/ticket/14484
