### ISSUE TITLE
vagrant up not working after powershell update

### ISSUE THREAD

**Issue by bithead42** [geerlingguy/drupal-vm#299]
My host machine is Windows 7 Pro SP1 64-bit.  I'm running Vagrant 1.7.4 and VirtualBox 5.08.  Drupal 8 was up, but gawd-awful slow, so I changed the synced folders to smb.  `vagant up` hung, I did some more reading and found that powershell needs to be updated.  I installed Windows Management Framework 4.0, updating powershell in the process, and rebooted.  `vagrant up` barely got started before it crashed here:

`D:\HashiCorp\Vagrant\Sites\insweb>vagrant up`
`Bringing machine 'insvm' up with 'virtualbox' provider...`
`==> insvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...`
`D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in 'mkdir': No such file or directory - L: (Errno::ENOENT)`

I've no idea why L: is being referenced.  It is a mapped drive on my network, but there is no reason that vagrant should care about it.  I uninstalled vagrant, rebooted, reinstalled vagrant, rebooted, and get the same as above.  Below is the entire output of the errors generated (the above is just the beginning).  I'm at a loss.  Please advise...

`D:\HashiCorp\Vagrant\Sites\insweb>vagrant up`
`Bringing machine 'insvm' up with 'virtualbox' provider...`
`==> insvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...`
`D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in ‘mkdir': No such file or directory - L: (Errno::ENOENT)`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:245:in ‘fu_mkdir'`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:219:in ‘block (2 levels) in mkdir_p'`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:217:in ‘reverse_each'`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:217:in ‘block in mkdir_p'`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:203:in ‘each'`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/fileutils.rb:203:in ‘mkdir_p'`
`        from D:/HashiCorp/Vagrant/embedded/lib/ruby/2.0.0/pathname.rb:559:in ‘mkpath'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:56:in ‘block (2 levels) in call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:41:in ‘each'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:41:in ‘block in call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:40:in ‘each'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folders.rb:40:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/synced_folder_cleanup.rb:28:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/synced_folders/nfs/action_cleanup.rb:19:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_nfs_valid_ids.rb:12:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:160:in ‘handle'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:42:in ‘block in call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in ‘lock'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:41:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/prepare_forwarded_port_collision_params.rb:30:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/env_set.rb:19:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/provision.rb:80:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clear_forwarded_ports.rb:15:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/set_name.rb:50:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/clean_machine_folder.rb:17:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_accessible.rb:18:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘block in run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in ‘busy'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘block in run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in ‘busy'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘block in run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in ‘busy'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/box_check_outdated.rb:68:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘block in run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in ‘busy'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/config_validate.rb:25:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:95:in ‘block in finalize_action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘block in run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in ‘busy'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builtin/call.rb:53:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/warden.rb:34:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/builder.rb:116:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘block in run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/util/busy.rb:19:in ‘busy'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/action/runner.rb:66:in ‘run'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:214:in ‘action_raw'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:191:in ‘block in action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/environment.rb:516:in ‘lock'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in ‘call'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/machine.rb:178:in ‘action'`
`        from D:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/lib/vagrant/batch_action.rb:82:in ‘block (2 levels) in run'`

**Comment by bithead42** [comment]
Thanks everyone for your thoughts about this, even though none of them seemed to make it here. While you've been racking your brains, I've managed to get a vagrant-free installation of drupal 8 up and running. For some reason this turned out to be much easier for me to do than using a preconfigured distribution. I'll be considering this closed since I won't be pursuing it further.

**Comment by geerlingguy** [comment]
@bithead42 - Thanks for posting the issue, and I would definitely recommend taking a glance through the Windows documentation in the Drupal VM documentation: http://docs.drupalvm.com/en/latest/other/windows/

It has some notes about SMB, Vagrant on windows, performance, etc.; though I'm actually _just_ now able to test things on Windows myself (I just received a used Windows laptop with Win 10 for testing... I haven't owned a PC that runs Windows for about 7 years, but needed a physical PC so I could do VM testing on it (can't emulate it on my Mac inside another emulator)). So hopefully I can make the documentation even better, and I'll also be posting some blog posts on the topic as well.

> Thanks everyone for your thoughts about this, even though none of them seemed to make it here. While you've been racking your brains

I'm going to presume this was meant in a positive way, but if not, realize that I'm currently the only maintainer of this project, and have limited bandwidth to respond to every individual issue that arises in a short time frame; I generally run through issues on this project every couple weeks, and sometimes others do the same, so not getting an immediate response should be par for the course. Such is the nature of work in an OSS community :)

Just note that comments like that may be construed as off-putting, so if you can say it in a different way (like maybe ditch the first sentence entirely and just point out that you're doing something different and don't need to leave this issue open anymore).

**Comment by bithead42** [comment]
Thanks for the reply. I did read the Windows specific info - that's how I knew to use smb instead of nfs, and how I knew to upgrade PowerShell. Unfortunately these led me to the current dilemma.

And yes, I presume folks were reading my post and thinking about it some. Guess I didn't express that all too well. Admittedly I was also frustrated having hit one brick wall after another with vagrant-based drupal distributions over the last couple of weeks - perhaps that influenced my choice of words to a degree. �In any event, thanks for the benefit of the doubt and not assuming it was meant to be off-putting.

If I do get back to it and find a solution, I'll be sure to post back here.�

________________________________
