### ISSUE TITLE
Error provisioning

### ISSUE THREAD

**Issue by qwilf** [geerlingguy/drupal-vm#302]
Hi,

Have you seen the below output before?  I can't seem to provision on mac osx:

$ vagrant --version
Vagrant 1.7.4
$ ansible --version
ansible 2.0.0

$ vagrant provision
==> drupalvm: Running provisioner: ansible...
ERROR! The requested action was not found in configured module paths. Additionally, core modules are missing. If this is a checkout, run 'git submodule update --init --recursive' to correct this problem.

The error appears to have been in '/private/etc/ansible/roles/geerlingguy.repo-remi/tasks/main.yml': line 2, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

---
- name: Install remi repo.
  ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Since you're running Ansible 2.0.0 from a local git checkout you need to complete Ansible installation using the command in the error message; otherwise I recommend installing via either pip or home brew, and sticking with the latest stable version, 1.9.4.

**Comment by qwilf** [comment]
Thanks, I think my environment was confused with having installed ansible with pip and from source.

pip uninstall ansible
cd ~/dev/ansible && sudo make clean
pip install ansible==1.9.4

seemed to do the trick nicely.  Thanks for the help geerlingguy
