### ISSUE TITLE
Memory allocation goes crazy - results in 'No data received ERR_EMPTY_RESPONSE'

### ISSUE THREAD

**Issue by mixplex** [geerlingguy/drupal-vm#306]
This happened after I did a new clean install.  Using D7, Ubuntu14

		server reports no response - log says

		[Wed Nov 11 15:37:35.412195 2015] [:error] [pid 8423] [client 10.0.1.1:50834] PHP Fatal error:  Allowed memory size of 201326592 bytes exhausted (tried to allocate 139740144122352 bytes) in Unknown on line 0

Pages will then reload when refreshed.  Occurs in all browsers.

Also occurs from page 'manual check for updates' with this warning:

		An AJAX HTTP request terminated abnormally. Debugging information follows. Path: /batch?id=6&op=do StatusText: error ResponseText: ReadyState: 0

**Comment by geerlingguy** [comment]
What do you mean by 'clean' install? Is this a brand new Drupal 7 site, with just Drupal core, or is this a site that's using an existing codebase and/or database? If the latter, it could be that your site requires a large deal of memory when rebuilding caches or loading the first time (thus why it would work after a refresh).

You can tweak the `php_memory_limit: "192M"` variable inside your `config.yml` and see if making that `256M` or even more (for some exceptionally memory-hungry Drupal sites) helps. Change the value then run `vagrant provision` to update PHP's configuration.

If things work after increasing that to `256M` or `512M`, then you're probably just running a hugely memory-hungry Drupal site, and you'll need that extra process memory.

If you're running Drupal core alone, or with just a few contrib modules, and getting this error, then we can keep debugging.

**Comment by mixplex** [comment]
I increased php_memory_limit: "512M" but it still chokes.  I'm attaching the callgraph for the dev site but its my first look at one.  I'm developing a map content type with location and gmap and after enabling those modules, it started choking.  This has happened before so I rebuilt the drupalvm.  It does not happen with just a few modules enabled.  It also does not happen on either my staging or production server which have similar configurations for memory.  Thanks much.
![callgraph-iaujc-mixplex](https://cloud.githubusercontent.com/assets/2119408/11106347/7a31574e-88a3-11e5-9171-8157ee37eb26.jpg)

**Comment by mixplex** [comment]
Sorry, I didn't mean to close it.

**Comment by mixplex** [comment]
I switched to Leaflet and its associated modules and it happens less.  Still occurs mainly in making a content type and editing views.

**Comment by geerlingguy** [comment]
@mixplex - Can you also look at your `installed_extras` list and consider maybe disabling/removing xdebug and xhprof if enabled? Having those running can also use up a little extra RAM per PHP process. You can remove them from the list then destroy and rebuild the VM to test.

Unfortunately, every environment's RAM usage is different, even depending on whether you're using Apache vs. Nginx + PHP-fpm, so I'm guessing your site is using a large amount of RAM, but on the development/local side it's just hitting the upper limit of php's `memory_limit`, while it's not hitting that limit on your other servers.

Please let me know if you find any other interesting information about reducing memory usage on your site!

**Comment by jatingarg1989** [comment]
I change php_memory_limit, getting below error:

fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/var/www/drupalvm/drupal/vendor/drush/drush/drush", "site-install", "standard", "-y", "--root=/var/www/drupalvm/drupal/web", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@127.0.0.1/drupal"], "delta": "0:00:00.078591", "end": "2017-08-02 03:50:32.533538", "failed": true, "rc": 255, "start": "2017-08-02 03:50:32.454947", "stderr": "PHP:  syntax error, unexpected '=' in /etc/php/7.1/cli/php.ini on line 204\nPHP:  syntax error, unexpected '=' in /etc/php/7.1/cli/php.ini on line 204", "stderr_lines": ["PHP:  syntax error, unexpected '=' in /etc/php/7.1/cli/php.ini on line 204", "PHP:  syntax error, unexpected '=' in /etc/php/7.1/cli/php.ini on line 204"], "stdout": "\nFatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 36864 bytes) in /var/www/drupalvm/drupal/vendor/composer/autoload_static.php on line 4063", "stdout_lines": ["", "Fatal error: Allowed memory size of 2097152 bytes exhausted (tried to allocate 36864 bytes) in /var/www/drupalvm/drupal/vendor/composer/autoload_static.php on line 4063"]}
