### ISSUE TITLE
Allow for re-provisioning/reloading without internet connection

### ISSUE THREAD

**Issue by chrisarusso** [geerlingguy/drupal-vm#307]
It would be great to be able to re-provision without an internet access. Having an option in which one could rebuild from cached downloads of all necessary libraries might be a way to do this.

**Comment by geerlingguy** [comment]
@chrisarusso - Unfortunately, at this time I don't think I can make this a priority for the project. There are ways you can set up parts of the playbook which don't require a connection (e.g. configuration file updates and service restarts) to run on their own without running the entire provisioning process, but that's out of scope for the simple setup I would like to maintain for the base drupal-vm install.

If you fork Drupal VM, it may be a very helpful thing to have a few different playbooks you can run to just do things like add a new docroot, install a new site, etc. without having to run the full playbook. But for simplicity's sake, I have to say no to this feature request :)
