### ISSUE TITLE
Sync global gitignore to drupal-vm

### ISSUE THREAD

**Issue by chrisarusso** [geerlingguy/drupal-vm#308]
It would be a nice feature either as part of config or in an automated way to sync the global gitignore file (often at `~/.gitignore_global`) from the host machine to the vm. If you're using PHPStorm on a project for example, and you've configured your host machine's global gitignore file to ignore `.idea/` you'll see that a `git status` in the projec on the drupal-vm asks you if you want to add the gitignore file

**Comment by geerlingguy** [comment]
I'd be happy to just add `.idea` to https://github.com/geerlingguy/drupal-vm/blob/master/.gitignore :)

**Comment by chrisarusso** [comment]
That'll do for this specific scenario. I'm happy to submit a PR for it if you'd like. I'm also happy to look into a more robust solution that would either allow you to define it in configuration, or would port over your host global git config file :+1:
