### ISSUE TITLE
Run command on vagrant up/reload

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#314]
@geerlingguy, is there  a way to specify a command or set of commands that should be run every time the VM is booted? In my case, I'd like to launch `phantomjs --webdriver=4444` every time the VM comes online.

**Comment by kevinquillen** [comment]
The way I had done this in the past was setting a shell script to fire when Vagrant was done booting. Probably not the best way to do it.

**Comment by geerlingguy** [comment]
Closing this in favor of #174 - that issue will be possible very soon, once Ansible 2.0.0 is released :)
