### ISSUE TITLE
Install new module on 'vagrant provision'

### ISSUE THREAD

**Issue by sshrestha-navarts** [geerlingguy/drupal-vm#315]
If I've already done `vagrant up` and change modules/moduleversion in drupal.make.yml, is there a way I can install the newly added modules without having to destroy the vm and recreating it?

EG, I add:

rules: "2.7" 

to drupal.make.yml. 

If I do a 'vagrant provision' `rules` does not get downloaded to my vm. I have to do a `vagrant destroy` then `vagrant up` to get that module.

Thanks!

**Comment by geerlingguy** [comment]
There are some ways to do this; currently Drupal VM doesn't try to be a site deployment manager (e.g. like Ansible itself, Capistrano, Jenkins, etc.), but just a development environment.

What many people will do is, after the initial provision, and after extra edits are made to drupal.make.yml, is regenerate the codebase based on the changed make file again. However, this is a little outside the purview of Drupal VM, and I think it might be better to discuss this in another forum, maybe on [Drupal Answers](http://drupal.stackexchange.com/)?

After you rebuild the codebase with the new module added, then you'd also need to have a deployment step to enable the module (e.g. inside an custom module's .install file, or via drush (`drush en -y [modulename]`).

**Comment by sshrestha-navarts** [comment]
@geerlingguy Thanks for taking the time to explain that.

I did solve my problem by writing an ansible task:
````---
  - name: Generate Drupal site with drush makefile.
    command: >
            {{ drush_path }} make -y {{ drush_makefile_path }} --no-gitinfofile
            chdir={{ drupal_core_path }}
    when: drupal_site.stat.exists == true
    sudo: yes

  - name: Enable the following modules (download if not present)
    command: drush en -y {{ drupal_enable_modules | join(" ") }}

    args:
            chdir: "{{ drupal_core_path }}"

  - name: Revert all site features (forced)
    command: drush fra -y --force

    args:
            chdir: "{{ drupal_core_path }}"
  

````


And enable that task in the playbook.yml. Its not the most efficient way (since it redownloads the components listed in the drush make file) but it works for the interim.
