### ISSUE TITLE
Only Drupal 8 is loading upon "vagrant up" even when I edit my config.yml and drupal.make.yml

### ISSUE THREAD

**Issue by wah22** [geerlingguy/drupal-vm#316]
I have attached the yml files as text files

[drupal.make.txt](https://github.com/geerlingguy/drupal-vm/files/36049/drupal.make.txt)
[config.txt](https://github.com/geerlingguy/drupal-vm/files/36050/config.txt)

**Comment by geerlingguy** [comment]
Inside `~/Sites/drupalvm`, make sure you delete any existing `drupal` folder, then run `vagrant up --provision` again and it should reinstall a D7 site.

**Comment by wah22** [comment]
Thanks.
