### ISSUE TITLE
Apache isn't restarted when new vhosts are added

### ISSUE THREAD

**Issue by nateswart** [geerlingguy/drupal-vm#318]
_I'm open to alternate workflow suggestions as well_

Steps to reproduce:
1. Have DrupalVM running
2. Add new site in apache_vhosts of config.yml
3. Run vagrant provision
4. Try to access site

Expected behavior: vhost will work
Actual behavior: "Not found" error (note: not 404, or 'Forbidden')

If I ssh into the VM and restart Apache, the new vhost works which seems to indicate that if Apache could be restarted at the end of a provision the problem would be solved?

**Comment by geerlingguy** [comment]
This should be working if you run `vagrant provision` after adding or changing a vhost: see https://github.com/geerlingguy/ansible-role-apache/blob/master/tasks/configure-Debian.yml#L33

Can you reproduce this reliably, and are there any other errors that occur during provision?

**Comment by geerlingguy** [comment]
I'm going to close this for now; if it's still an issue, please see if you can reproduce the problem, and also maybe paste in the contents of the playbook run output. Also, this might be best filed against the `geerlingguy.apache` role upstream.
