### ISSUE TITLE
Request: Info/home page like in VDD

### ISSUE THREAD

**Issue by robdecker** [geerlingguy/drupal-vm#320]
VDD (https://www.drupal.org/project/vdd) has a really useful info/home page that gets displayed if you go to the VM's IP address. I like this idea much better than just displaying the default site.

See https://vimeo.com/95936124 at about 3:01 for a demo of VDD's info page.

**Comment by geerlingguy** [comment]
I like this idea. Could be a pleasant landing page with all inline styling that just directs people to the documentation site and maybe also links to installed sections of the VM, e.g. Adminer, PimpMyLog, etc.

**Comment by geerlingguy** [comment]
Related: #143

**Comment by robdecker** [comment]
Additional ideas:
- a list of sites (with links) installed in the VM, along with their local_path on the host OS
- a generated list of entries to add to the hosts file
- db connection info for external tools like Sequel Pro

**Comment by Derimagia** [comment]
I used Dashbrew for a while and it had a pretty decent dashboard. Take a look here (There are screenshots):

https://github.com/mdkholy/dashbrew

**Comment by oxyc** [comment]
I started up a PR for this. Feel free to comment or make suggestions about #404

**Comment by oxyc** [comment]
It's merged this task can now be closed :) There's a follow up here https://github.com/geerlingguy/drupal-vm/issues/451
