### ISSUE TITLE
Ability to define and use custom variables

### ISSUE THREAD

**Issue by aweingarten** [geerlingguy/drupal-vm#322]
I have a DrupalVM setup with half a dozen different SSL hosts.  They use the same SSL cert.  I want to be able to use two custom variables to define `certificate_file` and `certificate_key_file` which I can then reuse.  

I am using the word custom variable because I can see this being useful for other applications.  For example I might define custom variables in a my.overrides.yml.  .Git ignore it and allow users of my vm to override specific settings.  For example:  you might name a repo _myrepo and I might call it _repo.  Overrides could allow it to be managed nicely.

Is this even possible?

**Comment by geerlingguy** [comment]
This seems to be another instance of the discussion over how to best use Drupal VM in a team-based workflow: https://github.com/geerlingguy/drupal-vm/issues/305

Closing this in favor of continued conversation in that issue. It might be that there should be an _additional_ optional vars file like `local.config.yml` or something like that, but there might be other solutions too.
