### ISSUE TITLE
Apache problem

### ISSUE THREAD

**Issue by MgsGH** [geerlingguy/drupal-vm#323]
Hi,

---
I have problem when building the virtual machine. I get this:

    TASK: [geerlingguy.apache | Ensure Apache is installed.] ********************** 
failed: [drupalvm] => (item=apache2,apache2-utils) => {"failed": true, "item": "apache2,apache2-utils"}
stderr: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'apache2' 'apache2-utils'' failed: E: dpkg was interrupted, you must manually run 'sudo dpkg --configure -a' to correct the problem. 

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/magnus/playbook.retry

drupalvm                   : ok=17   changed=1    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

Everything in the set up is standard, "out-of-the-box", except a configuration change for the shared folder:  
      - local_path:  /var/Sites/drupalvm
    destination: /var/www/
    type: nfs
    create: true

I have been digging/Googling in avail. Any suggestion would be much appreciated.

/Mgs

**Comment by geerlingguy** [comment]
Can you try rebuilding the VM from scratch, or if you see this error again, do a `vagrant ssh` to log in, then run `sudo dpkg --configure -a` inside the VM, then log out and run `vagrant provision` again?

**Comment by geerlingguy** [comment]
Closing for now; let me know if you're still running into this error anymore.
