### ISSUE TITLE
ansible fails to provision on 'vagrant up'

### ISSUE THREAD

**Issue by vierlex** [geerlingguy/drupal-vm#325]
hello, newbie here,

I tried following the install guide and on my final ```vagrant up``` i got an ```ErrorNo8``` on an autogenerated inventory file called ```vagrant_ansible_inventory```..
sadly i dont have the exact message because of a system crash.

I managed fix it with setting the rights to the file this way: http://stackoverflow.com/questions/18385925/error-when-running-ansible-playbook 

did that happen due to my inexperience setting things up or was there soomething else the cause?

**Comment by frob** [comment]
What OS and versions of everything are you running?
Versions of:
Vagrant
Ansible
VirtualBox
OS

**Comment by geerlingguy** [comment]
What @frob said... I haven't seen that issue before on either OS X 10.10/10.11, Windows 7/8/10, Fedora 22/23, or Ubuntu 15.10, so it might've been some weird file issue on your local machine... I'm going to close this ticket out, but please post back if you can reproduce the error or give additional info that we can diagnose the issue with.

**Comment by vierlex** [comment]
ubuntu x64 15.10, virtualbox 5.0.4 (not sure about that but will update if i am sure) ansible 1.9.4 and vagrant 1.7.4, at the point i was writing that issue, i setup dualboot system with windows 7 and ubuntu.

now that zou mention file issues.. during my first attempt i did have those files on my ntfs partition, so i can share stuff between th 2 os'.

nonetheless i tried it also with having everything in my homefolder and i still got the same error. its the same error message as described in that stackoverflow post:

```ERROR: problem running ansible_hosts --list ([Errno 8] Exec format error)```
