### ISSUE TITLE
provision fails: no autload.php for drush but composer is installed

### ISSUE THREAD

**Issue by vierlex** [geerlingguy/drupal-vm#326]
Hi, i fixed my previous issue but still provisioning fails.

This times drush is the culprit which reports:
```
failed: [drupalvm] => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.051482", "end": "2015-11-29 14:09:42.143576", "rc": 1, "start": "2015-11-29 14:09:42.092094", "stdout_lines": [], "warnings": []}
stderr: Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes. Please see README.md

FATAL: all hosts have already failed -- aborting
```

I ssh'd into the vm and can confirm that composer is there but drush cant seem to find it.

update: was able to fix this with ssh'ing into the box, and doing a 
```sudo composer install``` inside ```/usr/local/share/drush```

**Comment by geerlingguy** [comment]
It seems you may have an old version of Drush, or maybe an old copy of one of the Ansible roles required by Drupal VM?

Try running (inside the base Drupal VM directory) `sudo ansible-galaxy install -r provisioning/requirements.yml --force` and see if that gives you any updates.

**Comment by vierlex** [comment]
at the point of writing that issue i did everything step by step fromt the quickstart, including the ansible-galaxy command.

i am using ubuntu x64 15.10, virtualbox 5.0.4 (not sure about that but will update if i am sure) ansible 1.9.4 and the drush version which came with the provisioning (didnt install it any other way)

**Comment by geerlingguy** [comment]
@vierlex - One quick note - the boxes this VM uses are built for VirtualBox 5.0.10, so that can cause weird issues if there's a version mismatch. You might want to install `vagrant-vbguest` (`vagrant plugin install vagrant-vbguest`) to see if that helps.
