### ISSUE TITLE
use Drush make provisioning for full git repo i.e. Aegir/Gitlab, Pantheon, Acquia Cloud? 

### ISSUE THREAD

**Issue by devekko** [geerlingguy/drupal-vm#327]
is it possible to use the Drush make provisioning strategy to provision an existing Drupal custom codebase? 

I've found examples with profiles

i.e https://github.com/GetValkyrie/rune/blob/master/makefiles/stubs/build.make.yml

what I want is to be able to use a make file in Drupal VM and point to a private github/gitlab repo of an existing site that is hosted in Aegir/Pantheon as a full repo

devshop and Aegir3 allow git provisioning, the ability to check-out tags and branches, its kind of suprising this is not possible with Drupal VM

I guess I am missing something here

**Comment by devekko** [comment]
in other words

how do you use Drupal VM with an existing Acquia Cloud git repo? 

how do you configure make? 
how do you use git remotes vs make? 
once you've provisioned a site, how do you then turn that off and use git pull and git push to the git repo?

**Comment by geerlingguy** [comment]
There are a bunch of different ways to do this, and many are being actively discussed in #305 (so I'm closing this issue in favor of that.

One quick note: Drupal VM does not and will not be positioned as a 'Drupal deployment' or 'Drupal project management' system; there are a thousand better tools out there for that. Rather Drupal VM is focused solely on being a great local development environment.

Please see #305 for discussion about the best way to integrate it into a repository, to share it with a team, etc.
