### ISSUE TITLE
PHP7 causes fpm error

### ISSUE THREAD

**Issue by illepic** [geerlingguy/drupal-vm#332]
PHP7 is new and we've been warned, but in case this is something straightforward to update:

````shell
==> drupalvm: TASK: [geerlingguy.php | Ensure php-fpm is started and enabled at boot (if configured).] ***
==> drupalvm: failed: [localhost] => {"failed": true}
==> drupalvm: msg: no service or tool found for: php5-fpm
````

The above happens when the only config changes I've made to the default config.yml are [those listed in the docs for configuring PHP7](http://docs.drupalvm.com/en/latest/other/php-7/):

````
php_version: "7.0"
php_packages:
  - libapache2-mod-php7.0
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php-gd
  - php-curl
  - php-imap
  - php-json
  - php-opcache
php_mysql_package: php-mysql
````

**Comment by kevinquillen** [comment]
I also want to try PHP7. Would be great to get this working in DrupalVM in a consistent manner.

**Comment by geerlingguy** [comment]
Sorry, I've been swamped for a couple weeks, so I haven't updated the docs to outline the specific changes required for PHP 7.0.0+; and the repos were only just updated. I'll try to get things working this week. And then I'll likely default to PHP 7 after there's been a couple months for things to settle!

**Comment by illepic** [comment]
Thank you so much for this. Being able to spin up a PHP7 Drupal VM this easily is going to be spectacular.

**Comment by illepic** [comment]
In case you were looking for testing on the commits from 12/7, here is my new failed provision output:

```
==> downfalldev: NOTIFIED: [geerlingguy.nginx | restart nginx] *********************************
==> downfalldev: changed: [localhost]
==> downfalldev:
==> downfalldev: NOTIFIED: [geerlingguy.mysql | restart mysql] *********************************
==> downfalldev: changed: [localhost]
==> downfalldev:
==> downfalldev: NOTIFIED: [geerlingguy.php | restart webserver] *******************************
==> downfalldev: failed: [localhost] => {"failed": true}
==> downfalldev: msg: (98)Address already in use: AH00072: make_sock: could not bind to address [::]:80
==> downfalldev: (98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
==> downfalldev: no listening sockets available, shutting down
==> downfalldev: AH00015: Unable to open logs
==> downfalldev:
==> downfalldev:
==> downfalldev: FATAL: all hosts have already failed -- aborting
==> downfalldev:
==> downfalldev: NOTIFIED: [geerlingguy.php | restart webserver] *******************************
==> downfalldev: FATAL: no hosts matched or all hosts have already failed -- aborting
```

**Comment by geerlingguy** [comment]
@illepic - Are you using Ubuntu or CentOS? Also, did you completely destroy the VM (`vagrant destroy`) then do a new `vagrant up`? I've fully tested Ubuntu 14.04, but am working through a couple small issues with CentOS before updating the docs.

**Comment by illepic** [comment]
This was Ubuntu 14.04, and fresh off of a `vagrant destroy` and then `vagrant up`. However, this is via nginx NOT apache. Let me try apache now and see what happens.

**Comment by joestewart** [comment]
Nginx won't need the libapache2-mod-php7.0 line at least.

I've tested with Apache but not Nginx yet.

**Comment by illepic** [comment]
TA DA! That was the key: Apache works! So the current situation is that nginx does not work with PHP7 as currently configured.

**Comment by geerlingguy** [comment]
@illepic can you open a new issue with those notes—I haven't done extensive PHP 7 testing with either Nginx + Ubuntu or Nginx + CentOS yet, though I have made a few other adjustments to the PHP role to support all the different scenarios (with 5.x or 7.x) a bit better too.

**Comment by illepic** [comment]
Will do, I'm firing up Ubuntu + nginx + PHP7 with libapache2-mod-php7.0 commented out of extras as I type this. And just for posterity the PHP7 scenario that worked for me is:

Ubuntu +Apache + this configuration:

```yaml
php_version: "7.0"
php_packages:
#  - libapache2-mod-php7.0
  - php7.0-common
  - php7.0-cli
  - php7.0-dev
  - php7.0-fpm
  - libpcre3-dev
  - php-gd
  - php-curl
  - php-imap
  - php-json
  - php-opcache
php_mysql_package: php-mysql
php_fpm_daemon: php7.0-fpm
```

**Comment by geerlingguy** [comment]
Thanks! Let me know how it goes in that new issue. We'll get those docs golden :)

**Comment by illepic** [comment]
^^ Issues created. Thank you so much for all your help @geerlingguy!
