### ISSUE TITLE
Search does not work on docs site

### ISSUE THREAD

**Issue by illepic** [geerlingguy/drupal-vm#333]
Searching for any words at the docs site results in nothing found. For example:

https://readthedocs.org//search/?q=vagrant&type=file&project=drupal-vm&version=latest

**Comment by geerlingguy** [comment]
See upstream issue: https://github.com/rtfd/readthedocs.org/issues/1487

Unfortunately, it doesn't seem search is a major priority for RTD right now, so it might be a while before that's fixed. Google search or even search within the GitHub repo might be a better bet for now :(

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/pull/998
