### ISSUE TITLE
Use docker-selenium for Selenium provider

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#338]
@geerlingguy how do you feel about using https://github.com/elgalu/docker-selenium for Selenium in Drupal VM? Some benefits:

- We'd get latest Firefox/Chrome drivers out of the box
- VNC (#246)
- Video recording ability

**Comment by geerlingguy** [comment]
At this time I don't want to add in Docker as a dependency—_especially_ if it involves using multiple layers of a base image over which I have little control/insight. For now, I would rather look at how we can improve the arknoll selenium role which Drupal VM uses.
