### ISSUE TITLE
Setup Drupal VM not working in Windows 7 64 bit !

### ISSUE THREAD

**Issue by henrytran9x** [geerlingguy/drupal-vm#340]
hi ! i used vagrant and drupal-vm on Window 7 64 bit , i followed step guide when i input "vagrant up" , this make me waiting too long time , but not download libraries ! This my screenshot http://prntscr.com/9ci7bg

**Comment by geerlingguy** [comment]
I don't support the hyperv provider; you need to make sure to install VirtualBox separately, so Vagrant can bring up the VirtualBox VM.

**Comment by henrytran9x** [comment]
I forgot install VirtualBox . Would try install VirtualBox !  thank you so much
