### ISSUE TITLE
Drupal 6 doesn't seem to install

### ISSUE THREAD

**Issue by wah22** [geerlingguy/drupal-vm#342]
I couldn't install Drupal 6 with the same settings, besides changing the version number to 6 instead of 7, that I installed with for Drupal 7. Is it a problem with drush maybe? Here is the error:

 failed: [localhost] => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal6", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal6:drupal6@localhost/drupal6"], "delta": "0:00:00.815566", "end": "2015-12-10 19:58:24.522766", "rc": 255, "start": "2015-12-10 19:58:23.707200", "warnings": []}
==> drupalvm62: stderr: Starting Drupal installation. This takes a few seconds ...                  [ok]
==> drupalvm62: PHP Fatal error:  Call to undefined function db_result() in /usr/local/share/drush/commands/core/drupal/site_install_6.inc on line 136
==> drupalvm62: Drush command terminated abnormally due to an unrecoverable error.       [error]

**Comment by geerlingguy** [comment]
Please see the [Drupal 6 Notes](http://docs.drupalvm.com/en/latest/other/drupal-6/) in the documentation; you will need to reformat the makefile and change the install profile variable in config.yml to `default` instead of `standard`.

**Comment by wah22** [comment]
Thanks for your kind and quick response.

On Thu, Dec 10, 2015 at 1:57 PM, Jeff Geerling <notifications@github.com>
wrote:

> Please see the Drupal 6 Notes
> <http://docs.drupalvm.com/en/latest/other/drupal-6/> in the
> documentation; you will need to reformat the makefile and change the
> install profile variable in config.yml to default instead of standard.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geerlingguy/drupal-vm/issues/342#issuecomment-163747071>
> .
>



-- 
-Willard
