### ISSUE TITLE
Errors with Drush versions less than 7 due to Console_Table library

### ISSUE THREAD

**Issue by ba66e77** [geerlingguy/drupal-vm#345]
Versions of Drush prior to 7 depend upon a version of the Console_Table package which is longer available.  Changing to Drush 7 or Drush 8 solves the problem because they [changed the way they handle dependencies](https://www.drupal.org/node/563170#comment-10622266), but for sites bound to earlier versions of Drush, provisioning fails with the message
```
TASK: [geerlingguy.drush | Run drush to finish setting it up.] ****************
failed: [local_dev] => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:13:00.011645", "end": "2015-11-30 20:06:13.905764", "rc": 1, "start": "2015-11-30 19:53:13.894119", "stdout_lines": [], "warnings": []}
stderr: The drush command 'help' could not be found.  Run `drush cache-clear [error]
drush` to clear the commandfile cache if you have installed new
extensions.
Drush needs a copy of the PEAR Console_Table library in order to     [error]
function, and the attempt to download this file automatically failed.
To continue you will need to download the 1.1.3 package from
http://pear.php.net/package/Console_Table, extract it into
/usr/local/share/drush/lib directory, such that Table.php exists at
/usr/local/share/drush/lib/Console_Table-1.1.3/Table.php.

FATAL: all hosts have already failed -- aborting
```

Fortunately, [another commenter on the same d.o issue](https://www.drupal.org/node/563170#comment-10622962) provided a work around that I've been able to verify resolves the problem: after provisioning the new VM, ssh to it (`vagrant ssh`), run `sudo pear install Console_Table`.

Would it be feasible to add a conditional to the drush role to force install Console_Table for older versions of Drush?

**Comment by geerlingguy** [comment]
Maybe... I'll have to look into what's necessary to support this. Note that I don't have any particular fondness for supporting n-2 or more versions of software, so I might not get to this soon.

**Comment by geerlingguy** [comment]
Closing in favor of upstream issue https://github.com/geerlingguy/ansible-role-drush/issues/20
