### ISSUE TITLE
vagrant up removes host from /etc/hosts

### ISSUE THREAD

**Issue by JhovaniC** [geerlingguy/drupal-vm#348]
When you do a `vagrant suspend` and then a `vagrant up` the hosts file it's not updated. If you set the hostupdater to not remove the hosts on suspend `config.hostsupdater.remove_on_suspend = false` this will work as expected on suspend but when doing `vagrant up` it will remove the hosts again as this happens every time you bring the vm up.

<img width="513" alt="screen shot 2015-12-15 at 10 52 38" src="https://cloud.githubusercontent.com/assets/1193673/11815506/03c8360e-a31a-11e5-925b-588eaac6c2a1.png">
 
If you do a `vagrant reload` the hosts file will be updated again.

<img width="437" alt="screen shot 2015-12-15 at 10 54 48" src="https://cloud.githubusercontent.com/assets/1193673/11815595/5efd9f1e-a31a-11e5-8f51-3e512b1a654c.png">

**Comment by geerlingguy** [comment]
This is an upstream issue: https://github.com/cogitatio/vagrant-hostsupdater/issues/88 — can you leave a comment there and hopefully they'll get it fixed in the plugin?

**Comment by JhovaniC** [comment]
@geerlingguy sure
