### ISSUE TITLE
Document projects which 'front' Drupal VM

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#352]
Tools like:

  - https://github.com/LunchboxDevTools/lunchbox (Node.js-based desktop app)
  - https://github.com/kevinquillen/generator-drupalvm (Yeoman generator)
  - Something already in the docs somewhere—move that into this new docs page

Basically raise awareness that there are tools which preconfigure Drupal VM for teams in different ways. Also goes back to discussion in #305

**Comment by kevinquillen** [comment]
I think a tool like Lunchbox actually has a lot of promise as far as getting more adoption of DrupalVM. I would even sunset the yeoman plugin in favor of a GUI that makes set up quick and easy. If I have time I will try to help out there.
