### ISSUE TITLE
Add HHVM as optional replacement for PHP?

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#359]
See notes for setup: http://www.midwesternmac.com/blogs/jeff-geerling/benchmarking-drupal-8-php-7-vs-hhvm

Basically, this would be a nice-to-have for benchmarking purposes mainly... but there are a lot of things that might need little tweaks, and some of the tooling wouldn't even run properly on HHVM.

**Comment by jackbravo** [comment]
Have you considered making nginx listen for por 9000 instead of a socket for PHP. That would simplify the configuration differences between php5, php7 and HHVM.

On some forums is also mentioned that fpm is more stable listening on a port than a socket.

**Comment by geerlingguy** [comment]
@jackbravo - As part of #346, and in my `geerlingguy.apache` role, I've switched the default to port 9000 instead of the socket. So yes :)

**Comment by jackbravo** [comment]
Great! I guess this one can be closed then =).

**Comment by geerlingguy** [comment]
Not quite, yet; I want it to be an easy-to-configure option in config.yml, which entails a little more work on my part.

**Comment by geerlingguy** [comment]
I'm waffling as to whether I want to include official support as part of Drupal VM or not... there's been very little noise over this issue, and I'd rather devote the extra role and resources to something more people have been asking for, like Postgres or SQLite.

I'm going to close this issue now, and will only reopen if more people start asking for HHVM. Honestly, since PHP 7.x was released, there's little reason to switch for most people (whereas performance was a huge reason prior!).

**Comment by oxyc** [comment]
I second that. Before PHP7 I would have been interested in trying it out at least, but now not so much.
