### ISSUE TITLE
vagrant up fails for recommended CentOS7 on Vagrant 1.8 on Windows

### ISSUE THREAD

**Issue by illepic** [geerlingguy/drupal-vm#360]
On Windows, I just upgraded Vagrant to 1.8 and VirtualBox to 5.0.12 (December 23, 2015).

1. Using the updated config.yml and applying changes as outlined [here](http://www.midwesternmac.com/blogs/jeff-geerling/drupal-8-redis-php-7-nginx-and).
1. I then did a full `vagrant destroy` **and** deletion of any folder within {home}/VirtualBox VMs
1. `vagrant up --provision` results in the following:

![vagrant up results](https://dl.dropbox.com/s/p1eui6dropbtysh/OnPaste.20151223-205049.png?dl=0)

I'll be experimenting with the default config.yml with no modifications next.

**Comment by geerlingguy** [comment]
There are a few minor (and major) issues with Vagrant 1.8.0 on Windows; see [this list](https://github.com/mitchellh/vagrant/milestones/1.8.1), and consider opening an issue in the Vagrant issues with the same error information, as it's likely you're not the only one who's run into the issue. For now, I'd recommend switching back to 1.7.x until 1.8.1 is released.

**Comment by geerlingguy** [comment]
Ick... actually, try installing the `vagrant-vbguest` plugin (`vagrant plugin install vagrant-vbguest`) and then destroy and re-up the environment. My base boxes are currently built with the 5.0.10 guest additions.

**Comment by illepic** [comment]
Already rocking `vagrant-vbguest` and no dice. I'll roll back to 1.7.4.

However, with the removal of the Ansible scripts depending on Vagrant 1.8's Ansible support, Vagrant 1.7.4 should now fail on the latest commits to drupal-vm right (this commit: https://github.com/geerlingguy/drupal-vm/commit/283614aca52342d654d5dd72f0a11f01e928be2b)?

**Comment by geerlingguy** [comment]
Ah, correct; you'll need to use the last point release of Drupal VM instead of master; click on releases or tags under the code tab above to get it.

**Comment by illepic** [comment]
Following up here that ALL Vagrant projects are failing with 1.8.1 on Windows 10: https://github.com/mitchellh/vagrant/issues/6733 so this has nothing to do with Drupal VM specifically (in case anyone Google'd their way to this issue).

**Comment by geerlingguy** [comment]
@illepic - Thanks so much for the feedback! I'm moving further discussion to #361; hopefully we'll get Vagrant 1.8.x running well on Windows 10 soon—until then, stick with the last (2.1.2) tagged release of Drupal VM and Vagrant 1.7.x if you need to make sure Windows support is rock solid.
