### ISSUE TITLE
How to send mail?

### ISSUE THREAD

**Issue by Benjen** [geerlingguy/drupal-vm#364]
I have just started using Drupal VM.  I love the way Mailhog is already integrated into the VM.  However, I would like to be able to send emails generated by Drupal webform module to the actual recipient rather than having it captured by Mailhog. 

I have stopped the mailhog service on the VM; however, when I submit the webform, I receive the following message: `Unable to send e-mail. Contact the site administrator if the problem persists.`

Any suggestions on what needs to be done to be able to send emails to the desired recipient from the VM?

**Comment by geerlingguy** [comment]
You also need to update PHP's sendmail_path by setting the following variable inside `config.yml`:

```
php_sendmail_path: "/usr/sbin/sendmail -t -i"
```

And then run `vagrant provision` to make sure it gets updated in PHP (and PHP is restarted); at that point, if the email provider accepts the emails from your IP address, the email should go through :)
