### ISSUE TITLE
Error downloading MailHog on Ubuntu?

### ISSUE THREAD

**Issue by itsgreggmarshall** [geerlingguy/drupal-vm#365]
Now that I have drupal-vm working on my Windows 10 machine, I decided to try Ubuntu 14.04.

It took awhile to read the whole local Ansible install instructions to notice the additional PPA required to get the current version of Ansible.

Then I had issues with the roles, which were solved with

    sudo ansible-galaxy install -r provisioning/requirements.yml --force

Now I am running into an issue during the provisioning, the error that causes the failure is:

    TASK: [geerlingguy.mailhog | Download MailHog binary.] ************************ 
    failed: [drupalvm] => {"failed": true}
    msg: failed to create temporary content file: The read operation timed out

    FATAL: all hosts have already failed -- aborting

Google doesn't seem to find a solution, any ideas?  (I'm not as strong in Linux as I am in Windows)

**Comment by geerlingguy** [comment]
As a first step, I'd just try `vagrant provision` again. It's almost always a temporary issue with connectivity, or GitHub, something like that.

**Comment by itsgreggmarshall** [comment]
That solved the problem to the point the provision ran to completion.  

Now when I visit the site I see a 500 error, and putting 

    error_reporting(E_ALL);
    ini_set(‘display_errors’, TRUE);
    ini_set(‘display_startup_errors’, TRUE

in settings.php isn't showing anything.

I'll need to poke at it a bit and see if I can figure out why.

**Comment by geerlingguy** [comment]
Sounds good. Check in `/var/log/apache2` and read through the errors and other_vhosts_access logfiles (`cat [logfilename]`), and see if they give any hints.

**Comment by itsgreggmarshall** [comment]
As a follow up, the logs gave me no hints (they were almost empty), so I tried re-provisioning and the site works.  Not sure what was wrong at each step and it will be interesting to see if the process can now be repeated for additional sites.

**Comment by npralhad** [comment]
I faced a same problem for 2.5.1 version 

![mailhog - prob - read operation timed out](https://cloud.githubusercontent.com/assets/3069896/15592995/c0f18952-23c5-11e6-80ab-928b1a6b1ffc.PNG)

```
vagrant provision
```
Provisioning resolved the problem.

![mailhog successfull](https://cloud.githubusercontent.com/assets/3069896/15593016/f873fc5c-23c5-11e6-9fde-bf35d0f712ea.PNG)

**Comment by geerlingguy** [comment]
@npralhad - Usually that just indicates the download URL was temporarily inaccessible. It seems to be working for me now too.
