### ISSUE TITLE
HOWTO use with Distributions - Lightning

### ISSUE THREAD

**Issue by leowmjw** [geerlingguy/drupal-vm#366]
- Just wanted to try out Drupal-VM with the Lightning distribution; but did not see any documentation on specifying the installation profile
- It seems to have Drush makefiles inside "lightning-8.x-1.0-beta1/profiles/lightning"; so should Drush Makefile path be pointed inside the profile?

Sorry; Drupal newbie here :)

Thanks for taking time to answer!

**Comment by panickervinod** [comment]
Did you try updating the config.yml and get it to point to the required drush makefile ?

**Comment by geerlingguy** [comment]
@leowmjw - There are a few changes you'd need to make inside `config.yml` (to use a [Makefile deployment strategy](http://docs.drupalvm.com/en/latest/deployment/drush-make/):

  1. As @panickervinod mentioned, update the `drush_makefile_path` to point to the Lightning distro makefile.
  2. Update the `drupal_install_profile` to `lightning` (or whatever install profile is required).
  3. Update `drupal_enable_modules` and set it to `[]` if you don't want to install/enable any additional modules besides what Lightning provides.

Another way you could do it, if you have drush running locally (on your host machine) is to build the site locally, then use the [Local Drupal codebase](http://docs.drupalvm.com/en/latest/deployment/local-codebase/) deployment strategy.

**Comment by leowmjw** [comment]
Thanks for clarifying @geerlingguy; it helped!  Added some docs to help out others with the same question in the future --> #370
