### ISSUE TITLE
Remi repo has no mysql-server anymore

### ISSUE THREAD

**Issue by krisdante** [geerlingguy/drupal-vm#369]
I have not found any info about dropping support for mysql in remi, but:

```
yum --enablerepo=remi search mysql-server
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: ftp.icm.edu.pl
 * epel: mirror.onet.pl
 * extras: ftp.agh.edu.pl
 * remi: remi.mirrors.cu.be
 * remi-safe: remi.mirrors.cu.be
 * updates: ftp.agh.edu.pl
=========================================================== Matched: mysql-server ===========================================================
akonadi-mysql.x86_64 : Akonadi MySQL backend support
```

Because of that installation with CentOS 7 fails. Perhaps it need to be reconfigured to use MariaDB.

**Comment by krisdante** [comment]
mysql_packages:
  - mariadb
  - mariadb-server

**Comment by geerlingguy** [comment]
Please see the "using a different base OS" directions in the docs at docs.drupalvm.com

**Comment by krisdante** [comment]
I dont get you comment.
First line of config is:

`vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,

Whan you use Centos7 - there is no mysql and your playbook fails.

**Comment by krisdante** [comment]
Ah now I see... Lame me

**Comment by geerlingguy** [comment]
@krisdante - Ha, sorry about that, earlier I was on mobile so couldn't link directly, but for the benefit of anyone else seeing this issue, here's the specific documentation: http://docs.drupalvm.com/en/latest/other/base-os/#redhat-enterprise-linux-centos-7

**Comment by krisdante** [comment]
Yes sorry. Thank you!
