### ISSUE TITLE
WebDriver failing on CentOS 6

### ISSUE THREAD

**Issue by kostajh** [geerlingguy/drupal-vm#374]
I'm getting these errors with the stock Firefox 38 on CentOS 6 (with the Selenium role enabled), and with Firefox 42.

```
exception 'WebDriver\Exception\UnknownError' with message 'Unable to connect to host 127.0.0.1 on port 7055 after 45000 ms. Firefox console output:

process 20424: D-Bus library appears to be incorrectly set up; failed to read machine uuid: Failed to open "/var/lib/dbus/machine-id": No such file or directory
See the manual page for dbus-uuidgen to correct this issue.
D-Bus not built with -rdynamic so unable to print a backtrace
 in /var/www/example/vendor/instaclick/php-webdriver/lib/WebDriver/Exception.php:15
```

Has anyone gotten Selenium/Behat working with CentOS 6 and DrupalVM?

**Comment by geerlingguy** [comment]
@kostajh - This is an upstream issue that might need to be reported against https://github.com/arknoll/ansible-role-selenium; also, I haven't seen anyone using DrupalVM + Behat/Selenium with CentOS 6 yet, so you might be the first person encountering this issue.
