### ISSUE TITLE
Install stalls on generating Drupal Site with drush makefile

### ISSUE THREAD

**Issue by aangelinsf** [geerlingguy/drupal-vm#375]
I received the same error as in #372, went back to install Ansible and continued with "vagrant provision" on OS X 10.11.2.

The install continued but has now been stuck on "TASK [Generate Drupal site with drush makefile.]" for about 15 minutes with no disk activity or other signs of activity occurring.

I stopped the process and re-executed "vagrant provision" and it stalls again.

Can you suggest how to proceed from here?

**Comment by geerlingguy** [comment]
Are you using the built-in drupal make file, or one from a distribution/custom site?

**Comment by geerlingguy** [comment]
You can try setting `working-copy: false` if you want a slightly quicker download of Drupal core (and/or using `8.0.2` or another tagged release).

**Comment by aangelinsf** [comment]
Ok, I thought there was no network activity but it appears that it was just taking a long time to download. Thanks for the quick response.
