### ISSUE TITLE
Set ssh config to use a username for a remote host

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#380]
Is there a role that we can add that allows for setting up ssh config rules for remote hosts? 

I was thinking something like:

```yaml
ssh_config:
 "github.com"
    - "USER git"
  "*.dev.remote.com"
    - "USER localusername"
```

**Comment by frob** [comment]
Of corse, some of this could be done by changing the vagrant username to something else, but that wouldn't be as flexible.

**Comment by geerlingguy** [comment]
I wouldn't want to add things inside the VM for this, but if you have the default Vagrantfile, you'll have SSH agent forwarding enabled by default: https://github.com/geerlingguy/drupal-vm/blob/2b94f2858ccf57a2f1fae6cb017fde3ec823dabe/Vagrantfile#L43

Therefore if you `vagrant ssh` in, the same host config should be available for you while logged in...

**Comment by frob** [comment]
The issue is that I have a different usename on the remote dev than on the vagrant box.

**Comment by geerlingguy** [comment]
In that case you can just prefix things with the username, right? e.g. `myname@server` instead of just `server`? Or does the key only apply without a named access?

**Comment by oxyc** [comment]
Could always add a post provisioning script that copies over your `.ssh/config` to the vm.

**Comment by frob** [comment]
@geerlingguy the issue is more of this would be shared in the repo and I am not the only developer. We all have unique usernames on the server.

@oxyc I think that is the best suggestion. We already have the bit about host forwarding, this might work just as well. Are there permission issues when dealing with sharing a ssh config like there is with sharing ssh keys?

**Comment by geerlingguy** [comment]
Yeah, I'd go with @oxyc's recommendation; in your shell script, you could have it copy the ssh config from the `~/.ssh/config` which would work on anyone's host (as long as they're on Mac/Linux), and if you need to set a specific username anywhere, just put in `$USER`.
