### ISSUE TITLE
Notes from getting xhprof running

### ISSUE THREAD

**Issue by aangelinsf** [geerlingguy/drupal-vm#381]
Drupal VM is great...thank you for the work you put into this project. 

Here are few of my notes on setting up xhprof to work with Drupal VM:
* the default ini file is /etc/php5/apache2/conf.d/xhprof.ini
* output directory is set in there and is xhprof.output_dir="/tmp/xhprof"
* virtual machine setup: it does not create the directory above; create it and set permissions to 777
* there is no warning that the destination directory doesn't exist or isn't writable (but there are several patches in various states of readiness about this)
* download and enable https://www.drupal.org/project/xhprof; turn it on in the configuration page for a bit more UI w/r to the runs. 
* see the runs at /admin/reports/xhprof; this mimics xhprof.domain.dev 
* No runs were generated until I disabled xdebug (/etc/php5/apache2/conf.d/xhprof.ini) and restarted apache
* I disabled xdebug because it will skew the results...and happily xhprofs runs started showing up

I'm curious about the runs not appearing until I turned off xdebug. I had spent a couple hours trying to get them to show up when I stumbled across this. Is this known behavior?

If the above sounds correct, I'm happy to add to the documentation.

**Comment by geerlingguy** [comment]
Not sure why xdebug breaks XHProf exactly, but I have heard from others that they can't have both enabled at the same time anyways. Do you think we need to update the [Using XHProf with DrupalVM](http://docs.drupalvm.com/en/latest/extras/xhprof/) docs page a bit?

**Comment by aangelinsf** [comment]
If I'm not the first to see this behavior then, yes, I would definitely update the docs. I get that profiling shouldn't be done with xdebug on (hence why I was turning it off) but in my case I was just trying to set up a machine for the first time attempting to get everything working. I think it could save others some frustration wondering why their profile runs aren't showing up.

Is it possible to create the /tmp/xhprof directory as well? That definitely seems missing from the playbook.

Also, those other bits, like where the various .ini's are located, would be handy for others, too, I think.

**Comment by oxyc** [comment]
The issue with the tmp folder not existing is that distros clean out the `/tmp` folder now and then. So I'm using the following in all my `settings.php` files.

```php
if (extension_loaded('xhprof') && !is_dir('/tmp/xhprof')) {
  @mkdir('/tmp/xhprof');
}
```

better yet

```php
if (extension_loaded('xhprof')) {
  if ($xhprof_output_dir = ini_get("xhprof.output_dir") && !is_dir($xhprof_output_dir)) {
    @mkdir($xhprof_output_dir);
  }
}
```

Maybe we should move the default path out of the `/tmp` directory though?

**Comment by geerlingguy** [comment]
@oxyc - I'm game for that... but would want a path that works with CentOS/Ubuntu at least, and wouldn't require special permissions (that was why `/tmp` was an easy choice when I set it up originally :) ).

**Comment by oxyc** [comment]
I've seen a lot of setups using `/var/tmp/` instead, and apparently [that one is persistent](http://superuser.com/a/168126/143294) across reboots.

You already have a task the sets the permission to 777 in the [ansible role](https://github.com/geerlingguy/ansible-role-php-xhprof/blob/master/tasks/main.yml#L32:L36) so that shouldn't be an issue across distros right?

Prefer fixing it upstream or adding the variable to the example config?

**Comment by geerlingguy** [comment]
Yeah, that makes sense (fixing upstream).

**Comment by oxyc** [comment]
The output directory issue is now fixed upstream in https://github.com/geerlingguy/ansible-role-php-xhprof/commit/b096612a79c9633cb61bd8a2a141f44cc1200d22.

@aangelinsf maybe you can update the docs regarding the xhprof + xdebug issue?

**Comment by aangelinsf** [comment]
Yep, will move that forward today.

**Comment by geerlingguy** [comment]
@aangelinsf - I've made some docs updates; let me know if you think any others would be helpful.

**Comment by timstallmann** [comment]
Hi y'all -- I've followed these steps and am getting `Could not open /var/tmp/xhprof/56ddcc8518d20.Sitename.xhprof` errors in the Drupal status log. `var/tmp/xhprof` exists and has permissions set to `777`. Is there some other magic step I'm missing?

**Comment by chrisarusso** [comment]
I'm also getting the same error as @timstallmann through the Drupal interface. The only success I've had so far is running the `drush xhprof-list` command which _does_ generate output in the `/var/tmp/xhprof` directory, but nothing that is helpful.

**Comment by kostajh** [comment]
I'm able to get XHProf working on the latest Drupal VM 2.3.1 — the issues above may be due to an older version of Drupal VM being used.

**Comment by geerlingguy** [comment]
Also make sure to refer to the latest docs for XHProf here: http://docs.drupalvm.com/en/latest/extras/xhprof/ – things should be working for latest D7 and D8 with Drupal VM 2.4.0+ now.
