### ISSUE TITLE
Deploy as Tor Hidden Service

### ISSUE THREAD

**Issue by stevepurkiss** [geerlingguy/drupal-vm#383]
Thanks for all your work on this! I've just watched a #32c3 video on Tor hidden services - didn't really know what they were before but just another way of accessing your site but more secure - even facebook has one!

In the Q&A they mention it would be a really good idea if there was an easy way to click a button to set up a blog as it's a bit tricky at the moment so I immediately thought "drupalvm!", so this issue is as much for myself as for anyone else - this could be an extremely useful service especially now that Drupal8 is super-easy to use out-of-the-box, along with drupalvm we could help ensure those who need to use the tools we produce have easy and simple ways to do so.

https://media.ccc.de/v/32c3-7322-tor_onion_services_more_useful_than_you_think#video

https://www.torproject.org/docs/tor-hidden-service.html.en

**Comment by geerlingguy** [comment]
@stevepurkiss - This would be a cool feature, but it's not something I'm interested in supporting at this time. If someone could set up a simple Ansible role that is easy to integrate for the different platforms, and wouldn't require any additional maintenance burden for this project, I'd consider adding it in, but this is a very niche use case (at least today... maybe in the future more common folk will use something like Tor), and I don't have a personal desire to use it at this time, so I wouldn't be able to put any effort into it.
