### ISSUE TITLE
`vagrant up` fails at `restart php-fpm`

### ISSUE THREAD

**Issue by ctorgalson** [geerlingguy/drupal-vm#384]
Hi there,

I'm just trying out the project, but spinning up vagrant fails when restarting php-fpm (I'm using Apache).

I'm not positive what information might be useful for you with this report, but here're the basic details:

- Host OS: Ubuntu 15.10
- Virtualbox: 5.0.10_Ubuntur104061 (latest guest additions)
- Vagrant: 1.7.4
- Ansible: 1.9.1

Aside from simple customizations to a few of the available options, I've made the following changes to the stock `config.yml` file:

- Add a virtua lhost.
- Add a mysql database.
- Add a mysql user.
- Add a cron job.

Please let me know if I can provide any further or more helpful information.

```
TASK: [Run configured post-provision shell scripts.] ************************** 
skipping: [BHD8]

NOTIFIED: [geerlingguy.firewall | restart firewall] *************************** 
changed: [BHD8]

NOTIFIED: [geerlingguy.apache | restart apache] ******************************* 
changed: [BHD8]

NOTIFIED: [geerlingguy.mysql | restart mysql] ********************************* 
changed: [BHD8]

NOTIFIED: [geerlingguy.php | restart webserver] ******************************* 
changed: [BHD8]

NOTIFIED: [geerlingguy.php | restart php-fpm] ********************************* 
failed: [BHD8] => {"failed": true}

FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart php-fpm] ********************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart php-fpm] ********************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/ctorgalson/playbook.retry

BHD8                       : ok=190  changed=95   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by geerlingguy** [comment]
Can you please try updating all dependencies (Vagrant, VirtualBox, and Ansible), then try again?

-Jeff Geerling

**Comment by ctorgalson** [comment]
Thanks. I've confirmed that the versions were already latest (these are latest versions for wily-updates / wily-proposed):

```
$ ansible --version
ansible 1.9.1
  configured module search path = None
$ vagrant -v
Vagrant 1.7.4
$ VBoxManage --version
5.0.10_Ubuntur104061

$ sudo apt-get upgrade ansible vagrant virtualbox
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... ansible is already the newest version.
vagrant is already the newest version.
virtualbox is already the newest version.
Done
```

**Comment by FinBoWa** [comment]
I'm presuming that you tweaked php configuration values or similar. Could you ssh to the box and run `restart php5-fpm`  see whats appear there. 

But also the issue might be from the fact that you are running old versions. They should be different as noted in the README.md:

> Note on versions: Please make sure you're running the latest stable version of Vagrant, VirtualBox, and Ansible, as the current version of Drupal VM is tested with the latest releases. As of August  2015: Vagrant 1.8.0, VirtualBox 5.0.12, and Ansible 2.0.0.

Ps. sorry @geerlingguy if I stepped on your toes but I just couldn't help my self :)

**Comment by geerlingguy** [comment]
@FinBoWa - No problem! One of the reasons I host the issues here is so anyone can help out :)

**Comment by FinBoWa** [comment]
@geerlingguy cheers :).. Do you remember have anything ansible 2.0 specific there that could break the php.ini template if run on 1.9 ?

**Comment by geerlingguy** [comment]
@FinBoWa - No, I'm still on 1.9.4 on one of my laptops, and this is working fine there. If you have an old version of the PHP role then that could be an issue; there was another update just yesterday or two days ago, so please run the galaxy/--force command again.

**Comment by ctorgalson** [comment]
Thanks @geerlingguy & @FinBoWa. My major issue was apparently a broken Ansible installation (parts of two different versions resident on the same system).

I've fixed that and updated vagrant and Virtualbox as well, but I think something is still not right with php-fpm.

Starting from scratch with `vagrant destroy`, and the galaxy/--force command, followed by vagrant up, the provisioning completes fully, and I find that apache, mysql, and php-fpm are running on the box. But, when I access a site PHP files are not interpreted.

**Comment by geerlingguy** [comment]
@ctorgalson - have you updated your config.yml to add the extra_parameters to your apache_vhosts? Check example.config.yml for an example; this is due to the change to use FPM with Apache in 2.2.0

**Comment by ctorgalson** [comment]
@geerlingguy: noted, and that resolves this. User error all the way, thanks for your patience (you too @FinBoWa). I'm really excited by this tool.

I didn't catch on that the `extra_parameters` option was required for each of the `apache_vhosts` partly because it's not present for the pre-configured vhosts (e.g. adminer, xhprof etc) in `example.config.yml. I'd suggest they be set up as the `drupal_domain` one (with the ProxyPassMatch line), or that they have an extra comment in `example.config.yml`.

Is that worth filing an issue for, and would a patch for one of those options be helpful?

**Comment by geerlingguy** [comment]
@ctorgalson - We could do a quick fix against this issue, or if someone wants to file a PR, we can work from there too.

**Comment by ctorgalson** [comment]
[Here's a gist containing a patch](https://gist.github.com/ctorgalson/9ce031b2c50bb2eebd59).

**Comment by FinBoWa** [comment]
@ctorgalson The best way to submit patches is to fork this repo and create a branch on the forked one and add the fix there and then do a pull request from github back to this repo.

Most, if not all, can be done directly on the github's web interface. 

The PR then gets automatically tested with travis, that builds a virtual machine using this, and report any errors the patch might introduce > that you could fix or get suggestions from @geerlingguy.

**Comment by ctorgalson** [comment]
Thanks @FinBoWa. Thought I'd upload the patch for discussion first. Anyhow, PR created: https://github.com/geerlingguy/drupal-vm/pull/391
