### ISSUE TITLE
"The Ansible software could not be found!" - Win7x64

### ISSUE THREAD

**Issue by robdonn** [geerlingguy/drupal-vm#386]
Hi guys, complete newbie here. Having issues trying to get this up and running on Windows 7 x64 with a fresh clone of Drupal VM.

When I `vagrant up` everything goes fine until it gets to `Installing Ansible...` and then I receive the following:

> The Ansible software could not be found! Please verify
> that Ansible is correctly installed on your guest system.
> 
> If you haven't installed Ansible yet, please install Ansible
> on your Vagrant basebox, or enable the automated setup with the
> 'install' option of this provisioner. Please check
> http://docs.vagrantup.com/v2/provisioning/ansible_local.html
> for more information.

I have no idea what to do now.

**Comment by geerlingguy** [comment]
Please see #372 for more info and how to proceed for now.
