### ISSUE TITLE
Cannot provision after drupal-vm 2.2.0 - PHP 'Segmentation fault'

### ISSUE THREAD

**Issue by sshrestha-navarts** [geerlingguy/drupal-vm#388]
I'm having trouble provisioning my machine. It errors out with:

```ASK: [geerlingguy.php | Check the installed version of PHP.] *****************
failed: [nyfw] => {"changed": false, "cmd": "php -r \"echo php_installed_version;\"", "delta": "0:00:00.032038", "end": "2016-01-20 17:56:25.119732", "rc": 139, "start": "2016-01-20 17:56:25.087694", "stdout_lines": [], "warnings": []}
stderr: Segmentation fault

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/sshrestha/playbook.retry

nyfw                       : ok=58   changed=3    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
==> nyfw: The previous process exited with exit code 

I have found that ssh'ing and executing ```sudo apt-get install libapache2-mod-php5``` works sometimes (but not always).

**Comment by geerlingguy** [comment]
Interesting... it looks like the PHP installation itself is broken, and the switch to FPM doesn't seem to be the culprit (it was installed before 2.2.0, just not used by default).

Can you log into the VM and run the command being run via Ansible? `php -r "echo php_installed_version;"`

Also, are you using memcached and/or redis? And have you changed any of the default `php_*` config options in your `config.yml`?

**Comment by sshrestha-navarts** [comment]
@geerlingguy running php -r "echo php_installed_version;" from inside the vm gives me a "Segmentation Fault".

Here is my php_* variables:

**Comment by sshrestha-navarts** [comment]
I must add that this segmentation fault only shows up (sometimes) when I do `vagrant reload --provision`.

If I `vagrant destroy` and `vagrant up` I'm all set.

**Comment by geerlingguy** [comment]
I wonder if it could be something memory-related. Some Drupal sites and/or configurations are more prone to segfaults than others... is the site you're running relatively large?

Also, are you using xdebug and/or memcached with this site? Another thing to try is to increase the `php_memory_limit` to maybe `256MB` and `vagrant_memory` to `2048` instead of the default of 1GB. Maybe it's running out of memory, and this will help...

**Comment by sshrestha-navarts** [comment]
I have xdebug uncommented but memcached in commented in my config.yml
Also increased memory on PHP and vagrant machine.
That did not work unfortunately. However I can confine this problem to reprovisioning. First time vagrant up works like it should. The 'vagrant reload --provision' fails with segmentation fault. For now I think its fine as it is at least creating the environment. I dont mind spending extra time destroying and recreating the vm. Better for testing anyways :)

Thanks for all the help!
