### ISSUE TITLE
Bash command to clone and run

### ISSUE THREAD

**Issue by rgoodie** [geerlingguy/drupal-vm#39]
In my alias.sh script (that auto-loads through my bash profile), I've added a function called `newd` clones this repo, uses sed to change configuration to Drupal 7 if desired, renames the VM to something other than drupaltest.dev, and starts `vagrant up`. Nothing to ground breaking but I thought I would share it since I use this all of the time to spin up new sites. I also don't need to remember the exact repo name. 

Such as `$ newd 7 test-fieldformatter` or `$ newd 8 drupal8test`

https://gist.github.com/rgoodie/9966f30b404a4daa59e1

**Comment by geerlingguy** [comment]
@rgoodie - Nice! I might have to try the script out a couple times and offer some suggestions for improvment (especially to make sure it doesn't need modifications when certain things (like the drush make file) is changed.

I may add a link to it in the README as well, as an option for managing instances of the dev vm :)

**Comment by rgoodie** [comment]
Use as you see fit. Any suggestions welcomed.

**Comment by geerlingguy** [comment]
I've added a page to the Wiki for `newd` specifically, but I'm planning on expanding that page to include a few other demonstration scripts and extensions to help people with a Drupal VM-based workflow.
