### ISSUE TITLE
Doesn't provision with ansible on host machine

### ISSUE THREAD

**Issue by smmccabe** [geerlingguy/drupal-vm#390]
Since vagrant doesn't currently work with Ansible 2.x I switched to installing ansible on my host instead, but it can't seem to find any of the roles. I believe this is because the requirements file isn't included if not using the ansible_local provisioning. I added that line in and everything seemed to work correctly, but I am no ansible pro.

**Comment by geerlingguy** [comment]
Make sure you follow the step in the quick start guide to install all the Ansible roles manually; otherwise the roles won't be available on your host machine.
