### ISSUE TITLE
Question:

### ISSUE THREAD

**Issue by scottalan** [geerlingguy/drupal-vm#392]
@geerlingguy

What actually creates: /etc/php5/fpm/pool.d/www.conf?

Can this easily be edited? I want to change something that persists when running vagrant provision.

**Comment by geerlingguy** [comment]
@scottalan - That file is managed by https://github.com/geerlingguy/ansible-role-php (the `geerlingguy.php` role), and is originally created by the `php5-fpm` package installation.

See: https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/configure-fpm.yml
