### ISSUE TITLE
Should pimpmylog work out of the box?

### ISSUE THREAD

**Issue by cameronbell** [geerlingguy/drupal-vm#399]
I installed drupalvm and am able to access a drupal site at drupalvm.dev. I also installed the vagrant-hostsupdater and vagrant-auto_network plugins. Hostsupdater adds the following to my hosts file: 

    10.20.1.2  drupalvm.dev  # VAGRANT: ad0124d1c856b9ba755844be5b85144f (drupalvm) / 833aa501-9f13-47c9-9663-0e6a89633145
    10.20.1.2  adminer.drupalvm.dev  # VAGRANT: ad0124d1c856b9ba755844be5b85144f (drupalvm) / 833aa501-9f13-47c9-9663-0e6a89633145
    10.20.1.2  xhprof.drupalvm.dev  # VAGRANT: ad0124d1c856b9ba755844be5b85144f (drupalvm) / 833aa501-9f13-47c9-9663-0e6a89633145
    10.20.1.2  pimpmylog.drupalvm.dev  # VAGRANT: ad0124d1c856b9ba755844be5b85144f (drupalvm) / 833aa501-9f13-47c9-9663-0e6a89633145

When I go to http://pimpmylog.drupalvm.dev, I get a 503 Service Unavailable apache message.

Is there something else I need to be doing to make pimpmylog work? Thanks.

**Comment by oxyc** [comment]
Sounds the same as https://github.com/geerlingguy/drupal-vm/issues/394#issuecomment-175219343.

Have you incorporated the recent changes in https://github.com/geerlingguy/drupal-vm/commit/c1fa34e1904cf7051d144cf871c88b7305539443?

**Comment by geerlingguy** [comment]
Yes, forgot to reply here, but it's the same issue as #394
