### ISSUE TITLE
Use Vagrant 1.8 linked clones feature for VirtualBox

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#400]
I just stumbled upon this new feature:

> By default new machines are created by importing the base box. For large boxes this produces a large overhead in terms of time (the import operation) and space (the new machine contains a copy of the base box's image). Using linked clones can drastically reduce this overhead.

> Linked clones are based on a master VM, which is generated by importing the base box only once the first time it is required. For the linked clones only differencing disk images are created where the parent disk image belongs to the master VM.

https://www.vagrantup.com/docs/virtualbox/configuration.html

As I'm currently on a laptop with 256GB disk space, and I've had to start deleting the less used boxes I imagine this would help me out a lot. Probably others too.

Is there any reason for not using it by default? Otherwise I'll for sure add it as a use case in the docs for allowing a local `Vagrantfile` to be sourced.

**Comment by geerlingguy** [comment]
Looks like all we need to do to enable this feature is add this in the Virtualbox configuration (even allowing backward compatibility:

```
v.linked_clone = true if Vagrant::VERSION =~ /^1.8/
```

I'm perfectly happy doing this... will commit once I'm finished testing the PR I just merged :)

**Comment by geerlingguy** [comment]
BTW, linked clones are enabled by default if you use VMware Fusion 8.x+ Pro: https://www.vagrantup.com/docs/vmware/boxes.html

**Comment by oxyc** [comment]
Sweet
