### ISSUE TITLE
Support Drupal 8 REST out of the box

### ISSUE THREAD

**Issue by mikebell** [geerlingguy/drupal-vm#402]
On a default provision you can't enable the REST module in D8 because ```always_populate_raw_post_data``` should be set to ```-1``` in php.ini

It'd be nice if this was set by default.

**Comment by geerlingguy** [comment]
I can get behind this. The variable should be configurable in my upstream [php role](https://github.com/geerlingguy/ansible-role-php) first, so could you open a ticket there requesting this variable be configurable?

**Comment by mikebell** [comment]
Yup will do!
