### ISSUE TITLE
Windows 7, SSH issue

### ISSUE THREAD

**Issue by itsgreggmarshall** [geerlingguy/drupal-vm#403]
Sometimes after a rebuild or two I start getting the following error.  So far the only solution I have found is uninstall Vagrant and Virtualbox and reinstall them.  Not exactly fun.

     An error occurred in the underlying SSH library that Vagrant uses.
     The error message is shown below. In many cases, errors from this
     library are caused by ssh-agent issues. Try disabling your SSH
     agent or removing some keys and try again.

     If the problem persists, please report a bug to the net-ssh project.

     timeout during server version negotiating

And the net-ssh project has this in the readme.md

     Net::SSH 3.x
     Please note: this project is in maintenance mode. It is not under active development but pull requests are very much welcome. Just be sure to include tests! – delano

I've tried various solutions found via Google, but none seem to work.  Any ideas?

**Comment by geerlingguy** [comment]
@itsgreggmarshall - This is something I won't be able to do anything about in this project... it's an issue with windows and Vagrant specifically.

My best advice is to use [Cygwin](https://www.cygwin.com/) and make sure you install cygwin's openssh package. This seems to be much more reliable for Vagrant usage than PowerShell and/or Git Shell/Git Bash.

**Comment by itsgreggmarshall** [comment]
A coworker suggested changing from cmd/console-Z to cmder and at first blush, it might have solved the problem (there's an issue in cmder that appears to have attempted to resolve the ssh-agent issue).

At least I am running again, I'll report if it is an effective solution.

**Comment by geerlingguy** [comment]
@itsgreggmarshall - I haven't tried cmder, but I do usually have more success using Cygwin than standard prompt, PowerShell, Git Shell, etc.

**Comment by itsgreggmarshall** [comment]
I think this is the key:  https://gist.github.com/Shoozza/8fe8b0c85fa89cd3b1c4

**Comment by itsgreggmarshall** [comment]
My problem with Cygwin is both Git for Windows and Acquia Dev Desktop have installed 2 copies of msys so having a third linux emulator gets really hard to debug.  And I have 40+ sites on DD2 so I am stuck with it for the near term.

**Comment by geerlingguy** [comment]
@itsgreggmarshall - Geica! Sounds like you should just buy a few more laptops :)

**Comment by itsgreggmarshall** [comment]
or switch to a better environment (although technically an issue for the state issued machines)...

**Comment by geerlingguy** [comment]
@itsgreggmarshall - Haha, yes, there's always that. Sadly not an option with many people :(
