### ISSUE TITLE
Nginx and PHP-fpm provision fails first time.

### ISSUE THREAD

**Issue by mikebell** [geerlingguy/drupal-vm#407]
When provisions a new box using nginx and php5.6 it fails the first time looking for apache2.

```
NOTIFIED: [geerlingguy.php | restart webserver] *******************************
failed: [drupalvm] => {"failed": true}
msg: no service or tool found for: apache2

FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart webserver] *******************************
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart webserver] *******************************
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/digital/playbook.retry

drupalvm                   : ok=156  changed=81   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

All ansible playbooks are up to date as of 29th Jan, virtualbox image is 1.0.8

Here is my config.yml - https://gist.github.com/mikebell/42f183d811686c3ffc76

If I then re-provision it completes successfully. However no vhosts work with PHP erroring on:

```
2016/01/30 11:34:09 [crit] 26993#0: *1 connect() to unix:/var/run/php5-fpm.sock failed (2: No such file or directory) while connecting to upstream, client: 192.168.88.1, server: pimpmylog.drupalvm.dev, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "pimpmylog.drupalvm.dev"
```
/var/run/php5-fpm.sock doesn't exist.

I'm a bit stuck on where to go debugging and fixing this issue.

**Comment by mikebell** [comment]
In ```/etc/php5/fpm/pool.d/www.conf``` its looking at ```127.0.0.1:9000``` where as all the vhosts are set to ```unix:/var/run/php5-fpm.sock``` changing this in the vhosts works but will be overridden after every provision.

As a temporary fix I've update the nginx template to switch to 127.0.0.1 but this could probably be extracted out into a variable and set in config.yml

**Comment by oxyc** [comment]
Based on your `config.yml` it seems your drupal vm playbook is out of date.

I believe this is the critical commit in your case https://github.com/geerlingguy/drupal-vm/commit/e99ae7150adb9efb6c9dc3ea9c02447043da164a

Could you pull in the latest Drupal VM changes form 2.2.1 https://github.com/geerlingguy/drupal-vm/releases/tag/2.2.1 (everything within the `provisioning` directory at least).

**Comment by mikebell** [comment]
Sorry! For some reason my git repo thought it was up to date with all the changes. Running git pull didn't have any new updates so I assumed (wrongly) I was at the latest version.
