### ISSUE TITLE
Stumped setting up on Ubuntu 14.04.

### ISSUE THREAD

**Issue by bryanhirsch** [geerlingguy/drupal-vm#409]
I'm getting tripped up trying to get drupalvm working on Ubuntu. If anyone has tips to get me over the next hurdle, I'd really appreciate it.

First I ran into this issue (which I only include here now to help the next person looking for Ubuntu / drupalvm troubleshooting): When I would run `vagrant up`, VirtualBox seemed to be failing and reporting 'VT-x is disabled in the BIOS'. Disabling PAE/NX in the VM Settings (per comment [here](https://forums.xamarin.com/discussion/comment/162161/#Comment_162161) seemed to resolve this issue.

Now I get a little further. But `vagrant up` still fails and I'm not sure where to try debugging next. Vagrant times out while waiting for the machine to boot. Here's the full output:

```
$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...
==> drupalvm: Clearing any previously set forwarded ports...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

**Comment by geerlingguy** [comment]
This is almost always due to VT-x not being enabled in BIOS. Do you have an Intel Core processor? Unless it's an Atom or M, I think, it should be able to support virtualization. Otherwise there's another workaround, but your VM will run about 20-30% slower without CPU virtualization support.

**Comment by geerlingguy** [comment]
See also: http://docs.drupalvm.com/en/latest/other/linux/

**Comment by geerlingguy** [comment]
Closing for now; please let me know if this is still an issue and we can reopen and go from there.

**Comment by bryanhirsch** [comment]
@geerlingguy sorry for the radio silence here. I was taking a detour. I finally circled back this morning on a new machine with a fresh install to try again. Now I'm working my way through other VirtualBox issues. I'll reopen if your suggestions above don't get me through my obstacles. Thanks!

**Comment by geerlingguy** [comment]
Sounds good!

**Comment by bryanhirsch** [comment]
Here's an update for anyone reading this later trying to get unstuck on their own Ubuntu setup:

I'm on a different machine than I was during my original post. Unlike above, I needed to go into BIOS to enable virtualization (even though this looked in the VirtualBox GUI like it was already enabled). I enabled virtualization here:
BIOS >> Security >> Virtualization

On the next restart everything except my NFS (file sharing with my virtual box) worked. (Note: In my Virtual Box GUI, now I see PAE/NX is unchecked. Unchecking this manually before my BIOS update never saved.)

**Comment by geerlingguy** [comment]
@bryanhirsch - Ah yes, that bites many people using certain flavors of Lenovo hardware (and some other vendors) who decided it's best to disable VT-x by default :(

I had to do that on my Lenovo T420 when I first set it up, and typically the setting is somewhere in the BIOS configuration.

**Comment by tharga8616** [comment]
I had the same issue after doing yum update. 
I activated the gui to see what was happening into the Vagrantfile:

  config.vm.provider :virtualbox do |v|
    v.gui = true

The grub had changed and the new kernel version were not loading correctly. 
I had to change the default option to boot the 3rd option.
CentOS Linux (3.10.0-327.el.x86_64) 7 (Core)

You can change it with: grub2-set-default [number option]

**Comment by geerlingguy** [comment]
@tharga8616 - Hmm... are you trying to use Ubuntu 14.04? The original issue is for that—if you have a different issue (or with a different OS), please open a new issue and put the details there. Thanks!
