### ISSUE TITLE
Ubuntu 14.04 (and OSX) Ansible failing

### ISSUE THREAD

**Issue by itsgreggmarshall** [geerlingguy/drupal-vm#414]
Running Vagrant 1.7.4 and Virtualbox 4.3 (after downgrading from Vagrant 1.8.1 and Virtualbox 5.10 thinking that was the issue):

During vagrant up I'm failing at this point
````
==> Web NY: Mounting NFS shared folders...
==> Web NY: Mounting shared folders...
    Web NY: /vagrant => /home/gregg/webnydist/box
==> Web NY: Running provisioner: ansible...
ERROR: /home/gregg/webnydist/box/.vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory:3: Invalid ini entry: NY - need more than 1 value to unpack
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
````

**Comment by itsgreggmarshall** [comment]
Ok we found the problem.

config.yml line 10 we had a space in the vagrant_machine_name: value

**Comment by geerlingguy** [comment]
@itsgreggmarshall - That'll do it! Glad you could figure it out, hopefully this helps others in the future who run into the error message.
