### ISSUE TITLE
Why does drush_makefile_path include '/vagrant'?

### ISSUE THREAD

**Issue by scottatdrake** [geerlingguy/drupal-vm#416]
In example.config.yml, the `drush_makefile_path` variable is set to `/vagrant/drupal.make.yml`. But where is `/vagrant`? I don't see that directory anywhere.

I had trouble referencing my own Drupal 7 make file until I prepended the relative path with this phantom directory. Seems odd.

**Comment by geerlingguy** [comment]
That directory is shared into the VM as a default share; it is the directory in which the Vagrantfile resides, and is a convenient way for you to share config files into the VM without adding an extra synced folder definition.
