### ISSUE TITLE
Specifying Version Number in nodejs_npm_global_packages

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#419]
I tried a few variations but I can't seem to get this to work:

```yaml
nodejs_npm_global_packages:
  - { name: phantomjs, version: 1.9.8 }
```

I'm sure I just have something funky in my syntax here. I've also tried running `vagrant provision` and `vagrant reload` after each change. 

What's the correct syntax for specifying specific versions or ranges in the config.yml file like you would installing via the command line
`npm install -g phantomjs@">=1.9.7 <2.0"`

This would probably be a good addition to the documentation.

**Comment by justinlevi** [comment]
Nevermind... I think I asked this before my final `vagrant provision` finished working

This seems to have done the trick:

```
nodejs_npm_global_packages:
  - { name: phantomjs, version: 1.9.8 }
```

**Comment by geerlingguy** [comment]
That was it - glad you could get it going!
