### ISSUE TITLE
Run drush to finish setting it up Fails

### ISSUE THREAD

**Issue by cameronbell** [geerlingguy/drupal-vm#420]
Hi, I'm getting the following error while the machine is provisioning. 
```
TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.044444", "end": "2016-02-06 14:08:31.632630", "failed": true, "rc": 1, "start": "2016-02-06 14:08:31.588186", "stderr": "Unable to load autoload.php. Run composer install to fetch dependencies and write this file (http://docs.drush.org/en/master/install-alternative/). Or if you prefer, use the drush.phar which already has depdencies included (http://docs.drush.org/en/master/install).", "stdout": "", "stdout_lines": [], "warnings": []}

PLAY RECAP *********************************************************************
drupalvm                   : ok=113  changed=1    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by oxyc** [comment]
I saw this the other day as well. Re-running the provisioning fixed it and then it didn't happen during the next rebuild either.

**Comment by cameronbell** [comment]
Re-running isn't fixing it for me.

**Comment by cameronbell** [comment]
I was able to get around that provisioning task by going to `/usr/local/share` and running `sudo composer install` and then running provision again, however now the `TASK [Generate Drupal site with drush makefile.]` hangs.

**Comment by geerlingguy** [comment]
@cameronbell - that task can take a while depending on many factors... Sometimes it take up to 5-10 minutes on slower connections.

**Comment by cameronbell** [comment]
Sorry, I updated my comment above, it did eventually fail.

**Comment by mooru** [comment]
Also getting this error
TASK [Ensure drupal_core_path directory exists.] *******************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "There was an issue creating /var/www/drupalvm as requested: 'module' object has no attribute 'EEXISTS'", "path": "/var/www/drupalvm/drupal", "state": "absent"}

PLAY RECAP *********************************************************************
drupalvm                   : ok=170  changed=3    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
@mooru - that's a bug in Ansible 2.0, will be fixed in 2.0.1: https://github.com/ansible/ansible-modules-core/issues/2473

**Comment by mooru** [comment]
So should i use ansible 1.9 since 2.1 is not yet available

**Comment by geerlingguy** [comment]
@mooru - Another option is to manually go into the VM, and run `sudo mkdir /var/www/drupalvm/drupal`

**Comment by geerlingguy** [comment]
Going to close out this issue for now; please let me know if you got things working or not.

**Comment by mooru** [comment]
Thanks so much. I tried again with ansible 2.0.0.2 and it worked

**Comment by aliyakhan** [comment]
vagrant ssh
php --version
It should be 
PHP 5.6.28-1+deb.sury.org~precise+1 (cli) , if not, Run 
sudo update-alternatives --set php /usr/bin/php5.6
php --version

Run composer install again
exit 
vagrant provision

**Comment by geerlingguy** [comment]
I also ran into this one time:

```
TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [default]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.052107", "end": "2017-02-25 16:35:35.078985", "failed": true, "rc": 1, "start": "2017-02-25 16:35:35.026878", "stderr": "Unable to load autoload.php. Run composer install to fetch dependencies and write this file (http://docs.drush.org/en/master/install-alternative/). Or if you prefer, use the drush.phar which already has dependencies included (http://docs.drush.org/en/master/install).", "stdout": "", "stdout_lines": [], "warnings": []}
```

In my case, it turns out that the install failed because of a missing tag in the Drush repo—the first clone failed, but mostly worked... then the second provision saw no changes in the 'clone the drush repo' task, and ended up _not_ running the `composer install`, which precipitated this error message. I'm going to add a `drush_force_composer_install` variable you can use in that case.
