### ISSUE TITLE
role 'geerlingguy.drupal-console' was not found

### ISSUE THREAD

**Issue by zan0416** [geerlingguy/drupal-vm#422]
I did the "sudo ansible-galaxy install -r provisioning/requirements.yml --force" step without any errors but when vagrant provisioning I get the following error:

------------------------------------------------------------------
**ERROR! the role 'geerlingguy.drupal-console' was not found in /home/darbogast/Sites/gene-tools-store/drupalvm/provisioning/roles:/home/darbogast/Sites/gene-tools-store/drupalvm/provisioning:/etc/ansible/roles

The error appears to have been in '/home/darbogast/Sites/gene-tools-store/drupalvm/provisioning/playbook.yml': line 37, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Conditionally-installed roles.
    - { role: geerlingguy.drupal-console, when: 'drupal_major_version > 7 and "drupalconsole" in installed_extras' }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.**
---------------------------------------------------------------------

Sure enough, geerlingguy.drupal-console is not in /etc/ansible/roles/.  Where does that come from?  What am I missing?
I'm trying to run drupal core 7.x and drupal.make.yml has been corrected to reflect the proper drupal version.
Ansible version 2.0.0.2,  Vagrant version 1.8.1,  Ubuntu 15.10

**Comment by geerlingguy** [comment]
Are all the other roles present in /etc/ansible/roles? Seems odd that just the console role went up and missing... I haven't changed anything with that role in a while (nor with requirements.yml).

Maybe just a fluke—can you try running `sudo ansible-galaxy install -r provisioning/requirements.yml --force` once more then see if the role is found?

**Comment by zan0416** [comment]
I ran the ansible-galaxy install again but still no drupal-console.  No errors reported except a deprecation warning on geerlingguy.daemonize.

Here is what is in /etc/ansible/roles/:

arknoll.selenium            
geerlingguy.drush      
geerlingguy.mysql         
geerlingguy.php-pecl    
geerlingguy.redis
geerlingguy.adminer        
geerlingguy.firewall   
geerlingguy.nginx          
geerlingguy.php-redis   
geerlingguy.repo-remi
geerlingguy.apache          
geerlingguy.git        
geerlingguy.nodejs         
geerlingguy.php-xdebug  
geerlingguy.ruby
geerlingguy.apache-php-fpm  
geerlingguy.java       
geerlingguy.php            
geerlingguy.php-xhprof  
geerlingguy.security
geerlingguy.composer        
geerlingguy.mailhog    
geerlingguy.php-memcached  
geerlingguy.pimpmylog   
geerlingguy.solr
geerlingguy.daemonize       
geerlingguy.memcached  
geerlingguy.php-mysql      
geerlingguy.postfix     
geerlingguy.varnish

**Comment by zan0416** [comment]
I figured out the problem.  The line for geerlingguy.drupal-console in the requirements.yml file was commented out for some reason, I apologize for not checking that out sooner.  The project I am working on is from someone who has been dinking with it to get behat testing working and I suspect he commented out the line for some reason.  I'll ask him about it, but for now we can close this issue.  Thanks geerlingguy!

**Comment by geerlingguy** [comment]
Sounds good!
