### ISSUE TITLE
Provision specific task

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#431]
Is there a way to provision a specific task? 

I want to run `vagrant provision --provision-with post_provision_scripts` instead of having to go through the entire provisioning but it's not working for me.

**Comment by oxyc** [comment]
I think not as the `vagrant` provisioner is still the same, `ansible`.

If you're on the master branch (or have commit 8a05b75dcf51eb) you could get it to work by not using Drupal VMs own `post_provisioning_scripts` variable but instead extend vagrant with a shell provisioner. To do that you create a `Vagrantfile.local` with the following contents:
```ruby
config.vm.provision "shell", path: "my-post-provisinoing-script.sh"
```
Then you can run `vagrant provision --provision-with shell` and it should work.

**Comment by geerlingguy** [comment]
Technically you can also do this if you use Ansible outside Vagrant, or if Vagrant had a way to pass through `tags` to Ansible.

I don't use them in Drupal VM, but it's easy enough to add them, and if Vagrant supports them via CLI sometime (not just through the Vagrantfile config), I will add them.

With Ansible, you can just do something like `ansible-playbook -i provisioning/inventory provisioning/playbook.yml --tags=post` or something along those lines.

**Comment by geerlingguy** [comment]
And yes, for now, the workaround would be to add what `oxyc` mentioned. I'll be tagging a new release once I get a few other upstream issues worked out, but for now that feature is available in `master`.

**Comment by justinlevi** [comment]
Thanks for the information guys.

**Comment by geerlingguy** [comment]
See @joestewart's PR above for a nice approach here.
