### ISSUE TITLE
Add documentation on potentially-less-painful Windows NFS mounts

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#433]
http://www.hollyit.net/blog/windowsvagrantwinnfsd-without-file-update-problems

It describes a relatively simple configuration that might work well in a Windows 8/10 environment for NFS instead of native or SMB shares (both of which are sad, sad sad):

> 1. Uninstall the vagrant-winnfsd plugin.
> 1. Create a folder on your system for your new WinNFSD service files.
> 1. Grab winnfsd.exe and put it in that folder (download from here)
> 1. Grab the nfsservice.bat file and put it in that folder (get it here)
> 1. Create a text file in that folder. For this example, we'll name it exports.txt.
> 1. Copy the share folders from your vagrant files and place in that text file, one share per line.

Using [WinNFSd](https://github.com/winnfsd/winnfsd) directly instead of the `vagrant-winnfsd` plugin.

**Comment by dpagini** [comment]
Just for some feedback, I tried the above steps out on Windows 7. I see your issue is created to reference Windows 8/10, but I didn't notice any specs in the article, so I thought I would try it.

Anyways, I'm unsure of what's supposed to be in my C:\winnfs\exports.txt file (format?), but before I get there, I'm getting an error when trying to run the `$ nfsstart.bat` command. (Note: linked .bat file is named _nfsservice.bat_, but I renamed to _nfsstart.bat_)
![image](https://cloud.githubusercontent.com/assets/1724163/13164865/6cdffb46-d686-11e5-82af-a94e15a24cce.png)

**Comment by geerlingguy** [comment]
@dpagini - It looks like that might just be a case of that file not being in your current $PATH; also, you might want to try running that command within PowerShell instead of in Git Shell/Git Bash.

**Comment by T2L** [comment]
As far as I understand, Vagrant will disable NFS on Windows and replace it (silently) with VirtualBox folder sync. 

One thing that vagrant-winnfsd plugin does is switching NFS on Windows back on. So, without plugin **it does not work**. 

I've spent some time last week trying to figure out what to do with that. Seems like vagrant plugin needs fixes as well as WinNFSD daemon.

**Comment by ibuildit** [comment]
What do you think about simply commenting out the type and adding "type: 'nfs'" ?


# Synced folders.
  vconfig['vagrant_synced_folders'].each do |synced_folder|
    options = {
      #type: synced_folder.fetch('type', vconfig['vagrant_synced_folder_default_type']),
      type: 'nfs',
      rsync__exclude: synced_folder['excluded_paths'],
      rsync__args: ['--verbose', '--archive', '--delete', '-z', '--copy-links', '--chmod=ugo=rwX'],
      id: synced_folder['id'],
      create: synced_folder.fetch('create', false),
      mount_options: synced_folder.fetch('mount_options', []),
      nfs_udp: synced_folder.fetch('nfs_udp', false)
    }
    synced_folder.fetch('options_override', {}).each do |key, value|
      options[key.to_sym] = value
    end
    config.vm.synced_folder synced_folder.fetch('local_path'), synced_folder.fetch('destination'), options
  
  end
