### ISSUE TITLE
Either get CentOS 6 test build faster, or ditch it

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#434]
In #412 a CentOS 6 Docker build was added to test everything in Drupal VM... and it works, but it's really really slow. Like 4-6x slower than the other environment builds.

I wonder if something in that Docker base image is screwy (a network setting?), or if it's just something crazy-slow that we won't be able to fix. So that we can get CI feedback in < 10 minutes, I vote to either disable it or fix it, and if it takes more than a couple hours' effort and we're getting nowhere, we just disable it and give everyone the caveat that only the latest OS releases have full automated test coverage.

**Comment by geerlingguy** [comment]
cc @oxyc who originally mentioned the issue.

**Comment by oxyc** [comment]
Wondering if this is what's going on:

- https://www.reddit.com/r/devops/comments/3omkvm/anyone_else_have_slow_docker_builds_on_centos/
- https://github.com/docker/docker/issues/10248#issuecomment-71690895

**Comment by oxyc** [comment]
I also feel like the build started quicker when we defined `python` as our language. Now there's a long delay before the tests even get started. Do they have a set amount of ruby boxes (we always get a ruby box now), and a set amount of python boxes? Or maybe it's just some travis free-account limit...

**Comment by geerlingguy** [comment]
Not sure... it's hard sometimes to gauge, because free accounts for OSS are always in a pool with no particular guarantees, so sometimes I've waited up to an hour for a particular instance to get going.

**Comment by oxyc** [comment]
I vote for ditching it and merging #456. Testing it on the latest versions is good enough imo. If we decide to ditch centos 6, we need to change Ubuntu 14.04 to test the nginx scenario though.

**Comment by geerlingguy** [comment]
Sounds good to me... maybe have ubuntu 14.04 (and moving forward, whatever the default is inside `example.config.yml`) run both the `nginx` and `apache`. Otherwise we could do both for both of the latest supported versions, but it's more important to me to make sure the defaults run across CentOS and Ubuntu.

**Comment by geerlingguy** [comment]
Working on this now.
