### ISSUE TITLE
Installing MariaDB?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#436]
The docs mention you can use MariaDB, but I don't see a way to trigger that in config.yml. Can it be done, and is it version 10.10.x+?

**Comment by geerlingguy** [comment]
See: http://docs.drupalvm.com/en/latest/extras/mariadb/

It will use whatever packages are available via yum, and it's currently only _officially_ supported in CentOS 7 on Drupal VM, though you can use the `geerlingguy.mysql` role with any supported OS and change the packages list to work with any mariadb packages as long as you have a repo with the packages added via apt/yum.

**Comment by kevinquillen** [comment]
What version of MariaDB would it be? Do you know?

Still looking for an easy way to install either MySQL 5.7.7+ or MariaDB 10.10+

**Comment by oxyc** [comment]
I don't believe those are in the default package repositories yet.

You could add a `post_provision_script` that does an upgrade. There's an example shell script that configures solr. https://github.com/geerlingguy/drupal-vm/blob/master/examples/scripts/configure-solr.sh

https://downloads.mariadb.org/mariadb/repositories/

**Comment by kevinquillen** [comment]
I was kind of hoping it was a var that you could set in config.yml to dictate which version to download. It looks like MySQL 5.7.11 is available for Ubuntu 14.04 for example, but it still installs 5.5.46.

Is there any way to know when it will be available?

**Comment by geerlingguy** [comment]
@kevinquillen - Currently the `geerlingguy.mysql` role only uses the core ubuntu repository, not the official [MySQL apt repo](https://dev.mysql.com/downloads/repo/apt/). Note that my MySQL role is probably in some ways one of the most complex (touch one thing and MySQL has a hissy fit), and also the most widely used—see https://github.com/geerlingguy/ansible-role-mysql/issues

So I would be more than willing to work on a simple way of switching to the official MySQL repo (or using a MariaDB repo instead) if it were made in a backwards compatible way, were as stable as using the general OS repository, and didn't break things too badly...

That would be an upstream issue though, and Drupal VM officially sticks to MySQL (system packages) or MariaDB (only 5.x and only on CentOS at this time). Again—that's all I'm officially willing to support... you may be able to get other things working depending on how you reconfigure stuff or post-provision.

**Comment by kevinquillen** [comment]
Okay. Don't mean to be a pain about it, because while it looks like a
slight version upgrade, the reason is that 5.7.7 (+ MariaDB 10.10.x)
introduced the JSON data type field. PostgresSQL has supported it since 9.2.

On a VM setup I don't use anymore, I installed Postgres explicitly for the
purpose of developing this module:

https://www.drupal.org/project/jsonb

Although now, I can't work on it. I don't want to use anything but
DrupalVM. I guess yeah, databases are probably the most tedious part. It
looks as if Acquia is still running 5.5 as well, so.

A shortcut to this would be simply installing Postgres 9.2+, is there an
ansible role that could do this within DrupalVM?

**Comment by geerlingguy** [comment]
@kevinquillen - No problem! Also, see: https://github.com/geerlingguy/drupal-vm/issues/146
