### ISSUE TITLE
VBoxManage.exe: error: Could not find a registered machine with UUID.. VBOX_E_OBJECT_NOT_FOUND (Windows 10)

### ISSUE THREAD

**Issue by ashabed** [geerlingguy/drupal-vm#439]
One DebugAcademy.com student (using Windows 10) has been unable to get DrupalVM to work. It is working for another student using Windows 7. 

We are essentially using Vagrant 1.8.2 (I copied the dev version from github, and changed the version numbers from 1.8.2 back to 1.8.1, and it worked with the latest virtualbox on windows). That fixed the issue for the Windows 7 users, allowing them to successfully install using the latest DrupalVM and Virtualbox.

However, another student who is using Windows 10, the latest virtualbox, Vagrant 1.8.2, and latest DrupalVM continues to get errors. 

Initially, he was receiving the following error:
"The guest machine entered an invalid state while waiting for it to boot. Valid states are 'starting, running'. The machine is in the 'poweroff' state. Please verify everything is configured properly and try again."

We then found this discussion ( https://github.com/mitchellh/vagrant/issues/2157 ) and "Went to the C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv directory, right clicked on VBoxDrv.inf and selected Install. I then went back to my console and typed 'sc start vboxdrv'." We did this as an administrator, in case that is significant.

When opening the VirtualBox GUI after running Vagrant up, no machine is listed on the left. Prior to doing the above ^ steps, we did see a machine in the 'offline' state.

Afterwards, we keep receiving the error: VBoxManage.exe: error: Could not find a registered machine with UUID.. VBOX_E_OBJECT_NOT_FOUND (picture attached)
![pasted_image_at_2016_02_15_11_28_pm 1](https://cloud.githubusercontent.com/assets/1713958/13077164/2366814a-d485-11e5-9bbc-5fc2022f2212.png)

I installed the extension pack from virtualbox.org, and later uninstalled it. Downgraded virtualbox to the latest 4.* release, let vagrant download virtualbox, etc. No matter what I do I can't get any change in the error message we're seeing. Do you have any advice in terms of what to try next? Maybe VBoxManage is looking in the wrong place for the machine? Also, is VBoxManage.exe always used as part of the set up, or is that something that can be uninstalled? Part of me wants to just get back to the original error message we were seeing so I can try other solutions I was finding for that.

Thank you for any help you can provide. The upside is 9 out of 11 students were able to set up using DrupalVM within about 1 hour, and 1 more student (the Windows 7 one) was able to get set up within 2 additional hours (I wanted to use the latest version of virtualbox/drupalvm).

**Comment by oxyc** [comment]
You could try this: http://stackoverflow.com/a/25516777

**Comment by ashabed** [comment]
Thank you @oxyc , I'll walk the student through that as soon as he's available. When he opens virtualbox no machines are listed - not even a failed or inactive one. Does that suggestion still apply?

**Comment by oxyc** [comment]
Ah then probably not.

**Comment by itsgreggmarshall** [comment]
Actually it might.  I noticed on one of my Windows 10 machines that I can have the drupal-vm machine running and not see it in the VirtualBox GUI.  There's an option you can set in vagrant inside config.vm.provider
```` v.gui = true
to force the machine to appear

**Comment by ashabed** [comment]
@itsgreggmarshall interesting, will see if that makes it appear. Thank you. More suggestions are welcome - unfortunately it is not my computer, and I'll be working with the student to go through all proposed solutions over chat tonight, and in-person tomorrow night.

**Comment by ashabed** [comment]
Unfortunately setting that to true did not make the box appear in the GUI. Looks like it doesn't get that far. 

Any advice on how to undo this?: "Went to the C:\Program Files\Oracle\VirtualBox\drivers\vboxdrv directory, right clicked on VBoxDrv.inf and selected Install. I then went back to my console and typed 'sc start vboxdrv'." 

It seems like that change made the process fail earlier than it had been previously.

**Comment by ashabed** [comment]
It seems like the computer's i3 processor may be incompatible based on further research. We got it back to the original error, and upon digging into the message from virtualbox that's what we found. Closing the issue, thanks for the help!

**Comment by geerlingguy** [comment]
I ran into this on my Windows 10 laptop (which was working until this week)... oddly, I had to delete my `~/.vagrant.d/` directory before Vagrant started working correctly again. No idea what caused it (probably some botched vagrant config file in there), but after deleting the directory, this error went away.

**Comment by joestewart** [comment]
I guess we're waiting on vagrant 1.8.2 still.  
https://github.com/mitchellh/vagrant/pull/7126

**Comment by geerlingguy** [comment]
@joestewart - Yeah... they seem to be playing release jeopardy 1.8.2 went AWOL, 1.8.3 isn't showing when I download via Windows, and 1.8.4 was just tagged but isn't showing on my Mac at vagrantup.com :P

**Comment by rpsu** [comment]
Had the same issue, and upgrading to (now visible) Vagrant 1.8.4 solved the issue.

**Comment by josephdpurcell** [comment]
I'm on Fedora 24 but was getting the `Stderr: VBoxManage: error: Could not find a registered machine with UUID` problem.

Upgrading from 18.1. to 18.5 resolved this issue for me.

**Comment by arukulka** [comment]
@josephdpurcell how to upgrade it ?

**Comment by josephdpurcell** [comment]
@arukulka If you're using the downloadable packages, simply go to the Download page and then download and install the latest version for your system: https://www.virtualbox.org/wiki/Downloads

If you installed it with apt/dnf/yum, I've had better luck uninstalling that version and then using the downloadable packages.

**Comment by ningfc** [comment]
This issue may be helpful.
https://github.com/rexray/rexray/issues/1218
