### ISSUE TITLE
Add the Drupal VM Config Generator

### ISSUE THREAD

**Issue by opdavies** [geerlingguy/drupal-vm#440]
Add the [Drupal VM Config Generator](https://github.com/opdavies/drupal-vm-config-generator) as a project that extends Drupal VM.

I'm not sure where this should be added.

**Comment by oxyc** [comment]
:+1: cool

There's a task for creating such a docs page https://github.com/geerlingguy/drupal-vm/issues/352.

Currently the outdated page that @geerlingguy talks about is https://github.com/geerlingguy/drupal-vm/blob/master/docs/other/cloning-with-newd.md

**Comment by geerlingguy** [comment]
Working on the docs update now.
