### ISSUE TITLE
ERROR! the role 'geerlingguy.repo-remi' was not found in ...

### ISSUE THREAD

**Issue by bergstar** [geerlingguy/drupal-vm#442]
- OS X 10.11.3
- Latest drupal-vm-master (stock config files)
- Installed xcode
- virtualbox 5.0.14 r105127
- vagrant 1.8.1

- sudo easy_install pip
- sudo pip install ansible --quiet
- vagrant up

Got this error:
```
==> drupal1: Running provisioner: ansible...
    drupal1: Running ansible-playbook...
ERROR! the role 'geerlingguy.repo-remi' was not found in /Users/user/Downloads/drupal-vm1/provisioning/roles:/Users/user/Downloads/drupal-vm1/provisioning:/etc/ansible/roles

The error appears to have been in '/Users/user/Downloads/drupal-vm1/provisioning/playbook.yml': line 21, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Essential roles.
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by oxyc** [comment]
You missed one step before `vagrant up`:
```sh
sudo ansible-galaxy install -r provisioning/requirements.yml --force
```

**Comment by mgifford** [comment]
The nfsd service does not appear to be running.
Starting the nfsd service
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => /Users/mikegifford/drupal-vm-master
==> drupalvm: Running provisioner: ansible...
    drupalvm: Running ansible-playbook...
ERROR! the role 'geerlingguy.repo-remi' was not found in /Users/mikegifford/drupal-vm-master/provisioning/roles:/Users/mikegifford/drupal-vm-master/provisioning:/etc/ansible/roles

The error appears to have been in '/Users/mikegifford/drupal-vm-master/provisioning/playbook.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Essential roles.
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
Mikes-MBP:drupal-vm-master mikegifford$ sudo ansible-galaxy install -r provisioning/requirements.yml --force
Password:
Traceback (most recent call last):
  File "/Users/mikegifford/ansible/bin/ansible-galaxy", line 39, in <module>
    from ansible.errors import AnsibleError, AnsibleOptionsError, AnsibleParserError
ImportError: No module named ansible.errors


But then....


Mikes-MBP:drupal-vm-master mikegifford$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...
==> drupalvm: VirtualBox VM is already running.

**Comment by geerlingguy** [comment]
It looks like your Ansible install might have an issue (see the errors you get when you run the --force Galaxy install); if you run `ansible-galaxy --help`, do you get an error?

**Comment by geerlingguy** [comment]
Also after the VM boots the first time, run `vagrant provision` to run the provisioner again.

**Comment by mgifford** [comment]
With `ansible-galaxy --help` I get:
ERROR! Missing required action

**Comment by geerlingguy** [comment]
@mgifford - Yeah, something's definitely wrong with your Ansible installation; how did you install? Pip is usually the most reliable, but brew (if on Mac) is okay too.

**Comment by mgifford** [comment]
I had used homebrew to install it the first time.  Uninstalled it, installed it with pip and seem to have ansible-2.0.0.2 installed. Still get the same problem. 

Maybe it's a problem there. What version are you using?
  https://github.com/ansible/ansible/issues/12004

On on a mac.

**Comment by geerlingguy** [comment]
I'm on a Mac, running 2.0.0.2 installed via pip:

```
$ ansible --version
ansible 2.0.0.2
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
```

Also, the `--help` does show the missing required action warning on my Mac too—that is the bug you mentioned.

I wonder if you're running into the problem mentioned here: https://github.com/geerlingguy/drupal-vm/issues/131

Did you ever try installing Ansible from source? That would cause errors like this to happen, if all your submodules aren't up to date. Maybe even if the brew install isn't installing the right compiled version or something like that :/

See also: https://github.com/geerlingguy/drupal-vm/issues/204

**Comment by mgifford** [comment]
Where should my config file be?

$ ansible --version
ansible 2.0.0.2
  config file = 
  configured module search path = Default w/o overrides

I don't think #131 is an error because, it just worked. Didn't see any problem at all:

$  sudo ansible-galaxy install -r provisioning/requirements.yml --force 
- downloading role 'selenium', owned by arknoll
...

There was a long stream of successful runs, and only this warning (which sounded just fine):

- geerlingguy.drupal-console was installed successfully
[DEPRECATION WARNING]: The comma separated role spec format, use the 
yaml/explicit format instead.. This feature will be removed in a future release.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

I haven't tried running this from source. 

I see /etc/ansible/roles/ but not /etc/ansible/hosts or /etc/ansible/ansible.cfg for that matter.

**Comment by geerlingguy** [comment]
@mgifford - Can you look inside `/etc/ansible/roles` on your Mac and make sure all the roles are in there? It seems they're installing successfully at least :/

And it seems that path is in the ansible roles path (default) being used by Vagrant when trying to provision the machine. If you don't have a defined `ansible.cfg` file, then Ansible just uses all it's (pretty sane) defaults.

**Comment by mgifford** [comment]
This looks like most of them:

$ ls /etc/ansible/roles/
arknoll.selenium		geerlingguy.php
geerlingguy.adminer		geerlingguy.php-memcached
geerlingguy.apache		geerlingguy.php-mysql
geerlingguy.apache-php-fpm	geerlingguy.php-pecl
geerlingguy.composer		geerlingguy.php-redis
geerlingguy.daemonize		geerlingguy.php-xdebug
geerlingguy.drupal-console	geerlingguy.php-xhprof
geerlingguy.drush		geerlingguy.pimpmylog
geerlingguy.firewall		geerlingguy.postfix
geerlingguy.git			geerlingguy.redis
geerlingguy.java		geerlingguy.repo-remi
geerlingguy.mailhog		geerlingguy.ruby
geerlingguy.memcached		geerlingguy.security
geerlingguy.mysql		geerlingguy.solr
geerlingguy.nginx		geerlingguy.varnish
geerlingguy.nodejs

**Comment by geerlingguy** [comment]
Yeah... so I guess next step - can you do:

  1. `vagrant destroy -f` to destroy the VM.
  2. `which ansible` to make sure you can see ansible in your current $PATH
  3. `vagrant up` to build the VM.

Also, can you confirm that you're on the latest version (e.g. 2.3.0 or master) of Drupal VM?

**Comment by mgifford** [comment]
Where do you store the version number anyways?  I just started this yesterday and downloaded it from your site then.

$ which ansible
/usr/local/bin/ansible

But it looks like I got passed the error I first reported 18hrs ago and got to:

TASK [Ensure drupal_core_path directory is owned by ssh user.] *****************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "dialout", "mode": "0775", "msg": "chown failed", "owner": "501", "path": "/var/www/drupalvm/drupal", "size": 68, "state": "directory", "uid": 501}

Unfortunately that wasn't good enough it seems:

PLAY RECAP *********************************************************************
drupalvm                   : ok=197  changed=89   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
Ah, looks like everything's running happily now — you've run into https://github.com/geerlingguy/drupal-vm/issues/464, which I _just_ fixed a few minutes ago.

**Comment by geerlingguy** [comment]
It depends on how you installed drupal-vm—if you download from http://www.drupalvm.com/, then the download gives you the current `master` (latest) version, but it's not a git clone, so to update, you have to download again, then replace the non-customized files (just like with a standard Drupal core upgrade).

But if you clone Drupal VM with git, you can do a `git pull` or `git checkout 2.3.0` (etc.) to get to the proper version.

**Comment by mgifford** [comment]
I re-did it via git and now it's working just great. Really nice job!

I had to change the IP address (that error message could be clearer), but changed that:
vagrant_ip: 10.0.0.x

And now it's great! Thanks.

**Comment by geerlingguy** [comment]
Excellent! Sorry about the little bugs... it seems one or two little things get broken on every major release :(

**Comment by mgifford** [comment]
Really couldn't get a faster response though.  Hope some of my issues help out others.

**Comment by brentratliff** [comment]
I just ran into this same error today. 
"sudo ansible-galaxy install -r provisioning/requirements.yml --force" led to this:

......
- extracting geerlingguy.nodejs to /etc/ansible/roles/geerlingguy.nodejs
- geerlingguy.nodejs was installed successfully
- downloading role 'php', owned by geerlingguy
ERROR! Unexpected Exception: object of type 'NoneType' has no len()
to see the full traceback, use -vvv

"vagrant up" then failed with this:

.......
==> drupalvm: Running provisioner: ansible...
    drupalvm: Running ansible-playbook...
ERROR! the role 'geerlingguy.repo-remi' was not found in /Volumes/Data/Dropbox/Dropbox/Sites/usna97-drupalvm/drupal-vm-master/provisioning/roles:/Volumes/Data/Dropbox/Dropbox/Sites/usna97-drupalvm/drupal-vm-master/provisioning:/etc/ansible/roles

The error appears to have been in '/Volumes/Data/Dropbox/Dropbox/Sites/usna97-drupalvm/drupal-vm-master/provisioning/playbook.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Essential roles.
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by oxyc** [comment]
@brentratliff see https://github.com/geerlingguy/drupal-vm/issues/482

**Comment by brentratliff** [comment]
Thanks

**Comment by amidia** [comment]
i download the newest drupal-vm
i already download all roles and when i type 
vagrant up
i got this

Bringing machine 'drupalvm' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner:
* The following settings shouldn't exist: galaxy_role_file

**Comment by opdavies** [comment]
It sounds to me like you need to update to the latest version of Vagrant and/or VirtualBox.

**Comment by amidia** [comment]
i just update virtualbox. to Version 5.0.20 r106931. not the vagrant too thougt

**Comment by amidia** [comment]
yes you are right @opdavies . i upgrade vagrant to 1.8.1 and good to go. 
i got some error for some plugins, but with reinstall and uninstall it's fix.
thanks

**Comment by opdavies** [comment]
No problem. :)
