### ISSUE TITLE
Apache PHP mod not present in older Drupal VM release

### ISSUE THREAD

**Issue by banezaka** [geerlingguy/drupal-vm#443]
OS X El Capitan
Virtualbox 5.0.14
Vagrant 1.81

* Cloned the repo
* Checked out tag 2.1.2 
 (because of https://github.com/geerlingguy/drupal-vm/issues/357) 
* Edited drupal.make.yml and config.yml
* Created directory on my local system 
* Ran vagrant 

When the build is done I only see below code when I visit http://drupalvm.dev/

```
<?php

/**
 * @file
 * The PHP page that serves all page requests on a Drupal installation.
 *
 * All Drupal code is released under the GNU General Public License.
 * See COPYRIGHT.txt and LICENSE.txt files in the "core" directory.
 */

use Drupal\Core\DrupalKernel;
use Symfony\Component\HttpFoundation\Request;

$autoloader = require_once 'autoload.php';

$kernel = new DrupalKernel('prod', $autoloader);

$request = Request::createFromGlobals();
$response = $kernel->handle($request);
$response->send();

$kernel->terminate($request, $response);
```

Looks like php isn't running? 
When I ssh into the box I can run 

`$ php --version`
and it gives

`PHP 5.6.18-1+deb.sury.org~trusty+1 (cli)`

**Comment by banezaka** [comment]
Seems like php module for apache is not running 
I did 
`vagrant@drupalvm:~$ a2query -m php5
No module matches php5`

And I can't find it on the list when 
`apache2ctl -M`

**Comment by geerlingguy** [comment]
If you're using an older version of Drupal VM and want to use PHP with mod_php, you need to explicitly add the package for it in extra installs or in the php_packages list. On mobile so can't easily grab the package name.

**Comment by banezaka** [comment]
It doesn't really make any difference for me if mod_php is used or something else that does the same. But my box isn't working when I follow the instructions right now. If this change always is needed, maybe add it to the repo?

Or am I missing something? =)

**Comment by geerlingguy** [comment]
If you use the latest version or master of Drupal VM, then PHP-FPM is used by default (for better performance, memory management, easier configuration across Apache or Nginx, etc.).

I have abandoned using mod_php and recommend the same for anyone else :)

Are you on Mac, Linux, or Windows?

**Comment by banezaka** [comment]
Mac, OS X El Capitan

**Comment by geerlingguy** [comment]
Okay; and do you have Ansible installed? If so, you can run master or the latest tag and it should work properly. Make sure your vhosts are configured with the proxy pass definition as seen in example.config.yml

**Comment by banezaka** [comment]
No I hadn't, so 

I installed Ansible
Deleted my old repo for drupal-vm and cloned a new one 
Emptied the local storage folder
Ran the setup as instructed on the Quick Start Guide drupal-vm page

The setup worked this time, though
TASK [Generate Drupal site with drush makefile.]
Took a very very long time.

**Comment by geerlingguy** [comment]
Yeah, that task can take a while the first time you run it :)

Also, I just updated Drupal VM to use its own local provisioner so you don't have to have Ansible installed and you can use master/latest version now.

**Comment by banezaka** [comment]
Thank you for the help!

**Comment by geerlingguy** [comment]
@banezaka - No problem!
