### ISSUE TITLE
Switch back to JJG-Ansible-Windows to stop the bleeding

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#445]
Vagrant 1.8.2 might never happen :P /s

Basically, Vagrant 1.8.1 is broken for anyone without Ansible installed for Drupal VM usage. And I have no idea when 1.8.2 will be released. So to stop the bleeding for now, I can switch back to JJG-Ansible-Windows so people can use the latest version of Drupal VM successfully on Windows or in other environments where they don't have Ansible installed locally.

I have been holding off doing this for so long because I hate intentionally regressing and stopping the use of awesome new features like `ansible_local`, but I think the bleeding has gone on long enough.

**Comment by geerlingguy** [comment]
See:

  - https://github.com/geerlingguy/drupal-vm/commit/283614aca52342d654d5dd72f0a11f01e928be2b
  - http://www.jeffgeerling.com/blog/use-vagrant-18s-new-ansiblelocal-provisioner

**Comment by geerlingguy** [comment]
Testing this now.

**Comment by bkosborne** [comment]
FYI - Vagrant 1.8.4 is out now. I was testing with ansible-local provisioner and it seems to work fine. There's some stuff in the changelog related to ansible: https://github.com/mitchellh/vagrant/blob/master/CHANGELOG.md

**Comment by geerlingguy** [comment]
@bkosborne - Nice, I had forgotten about this! See: #450
