### ISSUE TITLE
Unable to update PHP using vagrant provision

### ISSUE THREAD

**Issue by sdemi** [geerlingguy/drupal-vm#446]
Hi,

I am trying to upgrade PHP 5.5 to 5.6. I have made the update in my config.yml and ran vagrant provision. However the new version of PHP is not set. I am running:

vagrant_box: parallels/ubuntu-12.04
php_version: "5.6"

Here is the some output from vagrant provision:

TASK: [Add repository for PHP 5.5.] ******************************************* 
skipping: [drupalvm-pegapdn]

TASK: [Add repository for PHP 5.6.] ******************************************* 
ok: [drupalvm-pegapdn]

TASK: [Add repository for PHP 7.0.] ******************************************* 
skipping: [drupalvm-pegapdn]

And here is the version being reported:

vagrant@pdn-local:~$ php -v
PHP 5.5.30-1+deb.sury.org~precise+1 (cli) (built: Oct  4 2015 16:14:34)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

Am I missing something on how to upgrade PHP?

**Comment by geerlingguy** [comment]
@sdemi - The version of PHP you set when you build the VM is 'locked in' more or less, unless you log in via `vagrant ssh` and uninstall all the PHP packages—or you manually update all the PHP packages to use the other apt repo that is used for 5.6.

I typically `vagrant destroy` then `vagrant up` when changing almost any environment configuration, as that makes for a fresh/clean slate. Drupal VM doesn't support things like on-the-fly PHP/MySQL/Apache/Nginx version upgrades or on-the-fly switching between different software (in most cases). Instead, you have to destroy the VM and rebuild it.

**Comment by sdemi** [comment]
Thanks for the quick reply. To upgrade to PHP 5.6 on ubuntu-12.04 VM I was able to:
1. vagrant ssh
2. sudo apt-get upgrade
3. sudo apt-get install php5
4. vagrant reload

**Comment by geerlingguy** [comment]
@sdemi - Perfect! That worked since you had reprovisioned with `php_version: 5.6`—it installed the correct repository so the upgrade would upgrade to the 5.6 repo versions.
