### ISSUE TITLE
Need to reconfigure nginx after provision

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#448]
I expect this will need to be an upstream change.

After a clean install I needed to change the way nginx communicates with php. The sock connection was failing to connect.

I had to change the fastcfi_pass parameter to:
fastcgi_pass 127.0.0.1:9000;

I haven't been able to really look into why the sock connection was failing.

**Comment by geerlingguy** [comment]
@frob what version of Drupal VM are you using? In master this is correct so Nginx's template uses `php_fpm_listen`, which is configured in `example.config.yml` to default to the TCP port: https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L208

**Comment by frob** [comment]
I am on commit 3e981e3208716e40a25b6b077d11086a40377978

It is possible I accidentally removed that line when editing config. 

-- Edit --

yup, that is what I did. I copied that whole block out of my old config. Could we use a default() for this in the role?
