### ISSUE TITLE
Switch back to Vagrant's ansible_local provisioner when 1.8.2 is released

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#450]
In #445 I switched Drupal VM back to using the [JJG-Ansible-Windows](https://github.com/geerlingguy/JJG-Ansible-Windows) provisioning shell script because so many users have been affected by https://github.com/mitchellh/vagrant/issues/6793.

I'd love to switch back to `ansible_local`, but I'm waiting on a Vagrant 1.8.2 release for that. It looks like it's being held up by a couple other bugs with the `ansible_local` provisioner.

**Comment by geerlingguy** [comment]
It's time to switch back to `ansible_local`, methinks.

**Comment by fubarhouse** [comment]
I'm curious as to when you're expecting this one to be complete?

**Comment by geerlingguy** [comment]
Bumping this one back up to the fore—it looks like Vagrant 1.8.5 resolves the NFS issues that have been plaguing so many Mac OS X users, and that was the main thing I was waiting for some resolution on since 1.8.2, 1.8.3, and 1.8.4 all seemed to create as many little quirks as they resolved.

I think the time for this has come, especially since #814, an improvement I dearly want to make now, would require hacking my own upstream JJG-Ansible-Windows project, but if we use the `ansible_local` provisioner, no problem at all since we can just not specify the galaxy file :)

I'll also need to bump the version recommendation in the README when I re-do this.
