### ISSUE TITLE
Drupal-VM vagrant Error

### ISSUE THREAD

**Issue by simonscientist** [geerlingguy/drupal-vm#457]
Hi,

While using vagrant to build the vm I receive the following error:

> ERROR:become is not a legal parameter in an Ansible Playbook
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Any help would be greatly appreciated thank you!

**Comment by oxyc** [comment]
You are using an old version of `ansible` (< 1.9). Try upgrading it.

**Comment by geerlingguy** [comment]
@oxyc is correct; if you installed with pip, run `pip install ansible --upgrade`. If brew, use `brew upgrade`. Etc.

If you used a package manager (`apt` or `yum`), and it doesn't have 1.9.x or greater, you should uninstall and switch to using pip or a source install.
