### ISSUE TITLE
Document best practice for building Drupal distributions

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#458]
See https://github.com/geerlingguy/drupal-vm/pull/370#issuecomment-186042789
Section: Drupal Deployment Strategies

**Comment by cfont** [comment]
Just read that blog post and really like this idea and am very willing to help with documenting this idea for Drupal VM. I'm wanting to work with OpenChurch and Drupal VM specifically so i can either help test your documentation or contribute or both.

**Comment by oxyc** [comment]
I think this would be a nice addition to the docs for sure. @geerlingguy still think it's suited for the docs or do you prefer blog posts?

@cfont If you have time to contribute that would be great! Lately I haven't been able to put much time into projects other than planning for an upcoming 4 month hike :smile:

**Comment by oxyc** [comment]
This should probably be postponed by https://github.com/geerlingguy/drupal-vm/issues/506

**Comment by geerlingguy** [comment]
Yes; in fact, I think I'm going to simply close this issue for now, as I think the outcome of #506 and the direction we start moving as a community by 8.2/8.3 will probably make that issue much more relevant here.

I'm not planning on spending a lot of time working on docs/improvements geared solely towards Drupal < 8 distribution installation; those distros usually have good enough docs, and make files are well supported already. If we can bake in best-in-class Composer support for everything, I think we'll kill two birds with one stone.
