### ISSUE TITLE
I have installed everything ok with no error codes, but the website only displays php text.

### ISSUE THREAD

**Issue by wah22** [geerlingguy/drupal-vm#460]
How can I fix my Drupal 7 vagrant site that only displays php code in the browser?

**Comment by oxyc** [comment]
You most likely have an outdated `config.yml` where you rely on `mod_php` which is not installed the default any longer. It has been switched to PHP FPM instead. Here are some issues where people had the same issue and solved it: #393, #443.

Here are the release notes for the update https://github.com/geerlingguy/drupal-vm/releases/tag/2.2.1

**Comment by wah22** [comment]
Thanks.
