### ISSUE TITLE
Dashboard doesn't appear if using 0.0.0.0 to assign IP

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#463]
Using vagrant autonetwork plugin, I am assigned an IP of 10.20.1.2 however vagrant_ip is set to 0.0.0.0 in config.yml, and the dashboard is assigned to that IP. That results in the vhost on the VM having 'ServerName: 0.0.0.0' instead of a public IP when _not_ using this plugin.

Visiting 10.20.1.2 takes me to the Drupal site instead of the dashboard.

I think we should change it to default to:

```
  - servername: "dashboard.{{ drupal_domain }}"
    documentroot: "{{ dashboard_install_dir }}"
```

That way it is consistent with the other vhosts that are created, and sidesteps this issue. When I made this change and restarted, I could visit the dashboard.

**Comment by geerlingguy** [comment]
That's a great idea! And to go further, we could also set that as serveralias in the Apache vhosts, and as another server directive in Nginx, so you could access via IP normally, or the dashboard URL otherwise.

**Comment by geerlingguy** [comment]
Working on this now...

**Comment by geerlingguy** [comment]
Works with normal IPs, testing with 0.0.0.0 now... (and on Nginx/Apache)

**Comment by geerlingguy** [comment]
Works, fix incoming!

**Comment by oxyc** [comment]
Nice! If someone has come to the stage when they use autonetwork I guess they dont need the hosts entries anyways :)

Might need to look into what happens with multiple hosts for nginx. I wasnt aware that you could just delimit them with space. I'll have a look and make sure it works later today.
