### ISSUE TITLE
Ensure drupal_core_path directory is owned by ssh user fails

### ISSUE THREAD

**Issue by back-2-95** [geerlingguy/drupal-vm#464]
This task fails, even if the folder is normal folder owned by me.

TASK [Ensure drupal_core_path directory is owned by ssh user.] *****************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "games", "mode": "0775", "msg": "chown failed", "owner": "501", "path": "/var/www/drupalvm/drupal", "secontext": "system_u:object_r:nfs_t:s0", "size": 68, "state": "directory", "uid": 501}

Tested with geerlingguy/ubuntu1404 and geerlingguy/centos7.

Could not find any solution on the documentation or from the closed issues.

Synced folder is configured as in the examples:
vagrant_synced_folders:
```
  # The first synced folder will be used for the default Drupal installation, if
  # build_makefile: is 'true'.
  - local_path: ~/Sites/drupalvm
    destination: /var/www/drupalvm
    type: nfs
    create: true
```

**Comment by geerlingguy** [comment]
Hmm... in this case, are you on Mac, Windows, or Linux? This is a recent change in support of allowing Drupal VM to be provisioned on DigitalOcean and other VPSes besides local VMs.

**Comment by back-2-95** [comment]
Oh yes, sorry, I'm on OSX El Capitan.

**Comment by geerlingguy** [comment]
Trying to reproduce; I tried with a pre-existing `~/Sites/drupalvm` folder. I'll try deleting that folder and see if I can get this to fail.

**Comment by back-2-95** [comment]
I went to ~ and `mkdir -p Sites/drupalvm`

folder is created as 755 privileges and owned by me and belonging to group staff.

**Comment by geerlingguy** [comment]
Got this too if I delete my `drupalvm` folder then bring up the VM... will look into a fix:

```
TASK [Ensure drupal_core_path directory is owned by ssh user.] *****************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "dialout", "mode": "0775", "msg": "chown failed", "owner": "502", "path": "/var/www/drupalvm/drupal", "size": 68, "state": "directory", "uid": 502}
```

**Comment by geerlingguy** [comment]
Commit in question is https://github.com/geerlingguy/drupal-vm/commit/e9c5cefd32cdff73e021c21929e38591294e8759

I'm willing to sacrifice DigitalOcean provisioning for the time being in favor of getting this back to normal again :)

**Comment by geerlingguy** [comment]
@back-2-95 - Can you see if the commit above (in `master`) fixes the issue for you? I'll have to look further into a way for DigitalOcean provisioning to work correctly with permissions, but I think this will fix it for local provisioning.

**Comment by back-2-95** [comment]
Yes, I'll check this today.

**Comment by back-2-95** [comment]
I used default settings with geerlingguy/ubuntu1404 and it works out of the box.

**Comment by GMartinez2** [comment]
Everything was building fine for me until this morning.  I went to create a brand new instance (on MacOSX el Capitan) and I'm getting the exact error as above.  I created a brand new folder inside my Documents folder with a fresh copy of DrupalVM.  Here is the full error from start to finish...


TASK [Ensure drupal_composer_install_dir directory has proper permissions.] ****
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "gid": 20, "group": "dialout", "mode": "0755", "msg": "chown failed", "owner": "501", "path": "/var/www/drupalvm/drupal", "size": 68, "state": "directory", "uid": 501}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************

RUNNING HANDLER [geerlingguy.varnish : reload systemd] *************************

RUNNING HANDLER [geerlingguy.varnish : restart varnish] ************************
	to retry, use: --limit @/Users/***/newSite/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=171  changed=76   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
