### ISSUE TITLE
Use of nginx throws errors at end of provisioning script

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#465]
Pulled down the latest, upgraded box, etc.

I switched my webserver from apache to nginx (due to an obscure issue where the Apache was returning the PHP source -- i'll make another issue for this).

nginx works (yay!) but throws the errors below.

```
NOTIFIED: [geerlingguy.php | restart webserver] ******************************* 
failed: [dvm] => {"failed": true}
msg: no service or tool found for: apache2

FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart webserver] ******************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

NOTIFIED: [geerlingguy.php | restart webserver] ******************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/nerdstein/playbook.retry

dvm                : ok=176  changed=89   unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

```

**Comment by geerlingguy** [comment]
Have you run `sudo ansible-galaxy install -r provisioning/requirements.yml --force` recently, too? The PHP role just underwent some refactoring to fix bugs like this...

But you can also explicitly set:

```yaml
php_webserver_daemon: "nginx"
```

**Comment by oxyc** [comment]
@nerdstein for reference here's someone else who ran into the issue about apache showing php source. Check the issues I linked to https://github.com/geerlingguy/drupal-vm/issues/460#issuecomment-187390303.

**Comment by nerdstein** [comment]
@geerlingguy, @oxyc what is the proper configuration needed to use Apache?

I tried both 'httpd' and 'apache2' as the php ansible role demonstrated.

This is the config changes I tried but to no avail:

```
# The web server software to use. Can be either 'apache' or 'nginx'.
drupalvm_webserver: apache
php_enable_webserver: true
php_webserver_daemon: "apache2"
```

**Comment by oxyc** [comment]
If you want to use `PHP FPM`, it works out of the box with the latest Drupal VM. To add it on top of an older `config.yml`, in addition to the ones you have set you need:
```yaml
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"
  ....

apache_mods_enabled:
  - ...
  - proxy.load
  - proxy_fcgi.load

php_enable_php_fpm: true
php_fpm_listen: "127.0.0.1:9000"
```
You do not need to set `php_webserver_daemon` though. You dont need to set this for `mod_php` either.

---

If you want to use `mod_php` you need:
```yaml
apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"

php_enable_php_fpm: false

extra_packages:
 - libapache2-mod-php5
```

**Comment by nerdstein** [comment]
thanks @oxyc
