### ISSUE TITLE
ansible-plyabook command not found

### ISSUE THREAD

**Issue by sinasalek** [geerlingguy/drupal-vm#466]
To fix this, i followed the instruction here https://thornelabs.net/2014/03/08/install-ansible-create-your-inventory-file-and-run-an-ansible-playbook-and-some-ansible-commands.html

But i think it should be added the vagrant profile

**Comment by oxyc** [comment]
Hmm which version of Drupal VM do you have? If `ansible-playbook` is not available Vagrant should opt for a shell script that provisions on the machine itself instead of from the host machine.

What's the exact message you get and at what stage of the process?

**Comment by geerlingguy** [comment]
Yeah; are you running Drupal VM 2.3.0, 2.3.1, or master? If so, we've stopped using the `ansible_local` provisioner which currently results in that error. If you're on 2.2.x, then that error will pop up.
