### ISSUE TITLE
/etc/hosts formatting from dashboard output

### ISSUE THREAD

**Issue by owenzoocha** [geerlingguy/drupal-vm#469]
Hi there, I set up the VM, all worked fine - I copied/pasted the following output from the dashboard page (as I haven't got the `vagrant-hostsupdater` or `vagrant-hostmanager` add on.
```
drupalvm.dev 33.33.33.40
adminer.drupalvm.dev 33.33.33.40
xhprof.drupalvm.dev 33.33.33.40
pimpmylog.drupalvm.dev 33.33.33.40
```
Updated my local hosts - but I couldn't access any of the urls above^.  Was scratching my head for an hour or so! Until I realised to switch the ip's to the leftmost side.  This then worked - just letting you guys know - thanks

**Comment by geerlingguy** [comment]
Thanks for reporting, you're quite right!
