### ISSUE TITLE
Front-end toolchain within the VM

### ISSUE THREAD

**Issue by a-fro** [geerlingguy/drupal-vm#470]
Hey Jeff. I'm a huge fan of DrupalVM for local development. I'm also responsible for my team's development infrastructure, for which we're using a fork of DrupalVM. We're also developing with Sass and compiling it with Compass, as well as enabling LiveReload with the guard-livereload ruby gem. The workflow is great on our current OSX infrastructure. 

However, I'm also starting some work with a developer who only has access to a Windows machine. I love that DrupalVM is still an option for him, but I'm also thinking about how to solve the front-end pipeline on windows. I've been able to get the toolchain working on Windows in the past, but it was slow and a bit buggy. Would you consider accepting a PR that would move the Sass/Compass/LiveReload tooling within the VM? I'm thinking that may be more flexible and performant, not to mention useful for the wider community. If you are willing to consider it, I'd love some suggestions for a pattern to look at for the implementation. For example, would you think of it as an "extra" for the installed_extras section? Or an additional configuration option? 

Thanks for your consideration, and even more for all the awesome work!

**Comment by oxyc** [comment]
You can do most of this at the moment already.

To install ruby gems (`guard-livereload` etc) you can add it to the `ruby_install_gems`:

```yaml
ruby_install_gems:
  - sass
  - guard-livereload 
```

For NPM pacakges you can use `nodejs_npm_global_packages`

```yaml
nodejs_npm_global_packages:
  - name: phantomjs
```

To enable port forwarding (I think you need this for livereload no?) you can create a `Vagrantfile.local` next to the regular `Vagrantfile` with the following:
```ruby
config.vm.network "forwarded_port",
  guest: 35729,
  host: 35729,
  protocol: tcp
```

**Comment by geerlingguy** [comment]
Yes, and to follow up on what @oxyc said, I don't want to add in a particular front end tool chain, but leave it up to the user/team to choose what they want and install the appropriate gems/npm modules.

Some teams use Ruby, some Node, and within both ecosystems there are dozens if not hundreds of different combos of preferred tools for Sass, optimization, compilation, live reload, browser preview, etc. for different themes and theme systems, and I don't want to pigeonhole Drupal VM into one over all the others.

**Comment by a-fro** [comment]
Great, thanks! I'll give @oxyc's suggestions a try.
