### ISSUE TITLE
Add Bios enabled Virtualisation to requirements

### ISSUE THREAD

**Issue by antonyanimator** [geerlingguy/drupal-vm#471]
I was working on a new pc today and took a while to figure out why vagrant up wasn't working, it was because I hadn't enabled virtualisation tech in the bios. I think its mainly because you don't need to open up virtualbox gui. But if you do it tells you that bios virtualisation isn't enabled. Might be handy to have in the requirements Thanks

http://www.howtogeek.com/213795/how-to-enable-intel-vt-x-in-your-computers-bios-or-uefi-firmware/

**Comment by antonyanimator** [comment]
Oops sorry saw it says it already in the requirements.

**Comment by geerlingguy** [comment]
Yep! There's also a note on the Windows docs page, since that's most often where this problem arises.
