### ISSUE TITLE
Unable to install new themes or modules

### ISSUE THREAD

**Issue by wwweeds** [geerlingguy/drupal-vm#474]
I have been using the centos7/php7 blog post, and finally it working after fixing [drupal.make.yml](https://github.com/wwweeds/Weedies/blob/master/drupal-vm-master/drupal.make.yml) from [issue 362](https://github.com/geerlingguy/drupal-vm/issues/362), and my [provisioning/tasks/build-makefile.yml](https://github.com/wwweeds/Weedies/blob/master/drupal-vm-master/provisioning/tasks/build-makefile.yml). Unfortunately, it isn't working properly.

I think that something to do with ownership is causing read/write issues, but even after changing folders to 777 I still can't upload new themes or modules. I am really new to drupal and DrupalVM, so it may be something I simple that I haven't encountered yet. Any ideas?

**Comment by oxyc** [comment]
At what point does the process fail exactly? After you run `vagrant provision` (or `vagrant up` for the first time), or just when using `drush`? Do you have any error messages you could post?

**Comment by wwweeds** [comment]
Currently everything on my drupal 8 install is working, except for installing new moodules or themes. For example I can create new users and roles, new content, etc... but when I try to extend by either linking to urls or uploading them locally from the 'drupalvm.dev/admin/modules/install' screen it will give me this error `The website encountered an unexpected error. Please try again later.`

**Comment by geerlingguy** [comment]
Hmm... have you tried downloading the modules using Drush (`drush dl [modulename|themename]`) or downloading them and placing them directly in the `modules` or `themes` folder in your Drupal 8 site folder? This is often much more reliable (and secure) than trying to install through Drupal's module user interface.

**Comment by wwweeds** [comment]
Well, I get a `command not found` when I try to `drush dl module`. I am ssh'ing into the drupal install directory, but it appears I don't already have drush and dependancies installed on the host machine? I figured it would work since the site is built with drush. I guess that's only in the vbox?

I can indeed unpack and move the folder locally, and install from there. I was hoping for a bit simpler way to do this, but my novice skillset with drupal and drupalvm is what's limiting me.

**Comment by geerlingguy** [comment]
Are you on a Windows, Mac, or Linux host? If you want to run the drush commands from your host machine, you will need to install Drush on the host (though the aliases won't be generated for you automatically if you don't have Ansible installed on the host).

If you `vagrant ssh` into the VM, run `drush sa` to see what aliases are available. You can use the `@drupalvm.drupalvm.dev` alias for the default site.

For file permissions, this can vary depending on your OS/synced folder type (NFS works best on Mac/Linux, but you might need to shift permissions and/or install a plugin like vagrant-bindfs to make permissions work a little better). Search around on Google for some common solutions to the permissions issues, but one thing that I don't recommend/support is the use of the Drupal UI for module uploading/installing (you can use it to enable/disable modules, but for the best security and also for convenience, it's quicker to either:

  - Use `drush @alias dl [module]`
  - Put the modules/themes in your site make file (Drupal VM includes `drupal.make.yml`, with the `devel` module as an example)
  - Download the module zip file/tarball and manually expand it and place it in `modules` or `themes`.

**Comment by wwweeds** [comment]
So I eventually just ended up using `drush dl [module]` for downloading and installing manually form the site interface. Which works fine for me.

However, I still face issues with uploading image files. I can upload user pictures, but no images in the image_field for any content type. Again, this is with 777 for any pertaining file directories.

In [Issue 99](https://github.com/geerlingguy/drupal-vm/issues/99) you mention that your solution wouldn't work for debian or redhat installs (I'm following your centos7/php7 install for this site), would you mind explaining what changes in `vagrant` uid you mentioned in issue 99 would be needed for me please?
