### ISSUE TITLE
vagrant and drupal vm: host or guest?

### ISSUE THREAD

**Issue by alisonjo2786** [geerlingguy/drupal-vm#475]
Hi, I have a major n00b question!

I'm trying to follow the [quick start guide](https://github.com/geerlingguy/drupal-vm#quick-start-guide), but I'm stuck.

My host machine is Windows 7.  I have VirtualBox installed, I created a VM, and installed Ubuntu 14.04 on that VM.

Do I install Vagrant on my host machine or guest machine....?  Do I download and configure Drupal VM on my host machine or guest machine?

(I haven't done anything in my guest environment other than installing Ubuntu 14.04, but was I supposed to wait to do that until after installing and configuring Vagrant and Drupal VM, or?)

Thank you for the help!

**Comment by oxyc** [comment]
Hey,

Drupal VM supports Windows so you should download Drupal VM and install Vagrant on your host machine. Vagrant will then create the VM and provision it for you from the host.

**Comment by alisonjo2786** [comment]
Thank you @oxyc .

> Vagrant will then create the VM and provision it for you from the host.

I guess I don't understand that part.  Looking at [Step 2](https://github.com/geerlingguy/drupal-vm#2---build-the-virtual-machine) in the quick start guide, it says "Create a local directory where Drupal will be installed..." (etc.) -- but I want to install Drupal in my guest Ubuntu 14.04 environment.  Does that mean I need Vagrant and Drupal VM in my guest VM, or?  (How can I create and reference the directory in which I want to install Drupal if the VM doesn't exist yet because Vagrant will be creating it...?)

Thank you very much for your help, I'm sure I'm just missing something that's right in front of me.

**Comment by oxyc** [comment]
The directory that the quick start guide refers to will be synced between the VM and your host. So you can edit the files locally (or checkout from version control), and then on each change they will be synced to the VM.

If you want to create an entirely new project and you dont have any code from before, just set the `local_path` variable to point to an empty directory. Once `vagrant up` has completed, that directory will be populated with Drupal and all modules you have defined in your `drupal.make.yml`

**Comment by alisonjo2786** [comment]
Ohhhhh so Drupal will be installed in a shared directory -- or at least that's where the codebase will be, but I can run Drupal elsewhere in my VM by cloning the repo that's in the shared directory.  Do I have that correct?

**Comment by oxyc** [comment]
Yes it will be downloaded and installed in a shared directory. You never really have to enter the VM to do any work (unless you want to). You can have the directory tracked on your host.

Once you've completed the `vagrant up` part of the quick start, Drupal will be installed and running as well. You just need to add the hosts entry described in [step 3](https://github.com/geerlingguy/drupal-vm#3---configure-your-host-machine-to-access-the-vm) so you can access it. If you visit the VM IP at http://192.168.88.88 you will also see a dashboard with what you should add to your hosts file.

**Comment by oxyc** [comment]
There's also a docs section on some caveats when running Drupal VM on Windows that you should probably be aware of http://docs.drupalvm.com/en/latest/other/windows/.

**Comment by alisonjo2786** [comment]
Okay, thank you!  To be honest, I'd been ignoring the Windows documentation until now because I thought I needed to proceed as a Linux user, b/c that's where I'm going to use Drupal -- but I think I'm clear now.  I'm waiting on vagrant up -- as soon as it gets through, I will close out this issue.  Thank you very much!!

**Comment by oxyc** [comment]
No problem, hope you get it running okay! I'll be around for a few hours today in case anything comes up.

**Comment by alisonjo2786** [comment]
I got a permission error, so I tried running cmd as an administrator (which seems like it might create its own problems), and I got all the way to "Successfully added box ....!" and then I got a permission error:

```
==> drupal7playground: Destroying VM and associated drives...
C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:163:in `open': Permission denied @ dir_initialize - C:/Users/ajm524/My Documents (Errno::EACCES)
```
(and then it listed a ton of Vagrant files in Program Files/path/to/Vagrant, like...
`    from C:/Program Files (x86)/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.1/lib/vagrant/util/platform.rb:163:in `entries'`
...and dozens more lines like that)

I need to stop for the day, I'll pick it up over the weekend -- but you've definitely answered my initial question, thank you so much!  (Closing seems like the right thing to do, but I also kinda want to be able to ask for more help later -- will it be a bother if I leave it open until I'm "done"?)

**Comment by geerlingguy** [comment]
@alisonjo2786 - I think we can close this particular issue; feel free to open another as the need arises. The first time you do setup it can be a little daunting on Windows. I'm going to hopefully record a quick video of the process and post to YouTube soon.

**Comment by alisonjo2786** [comment]
It looks like it actually worked, I'm wondering if it may have actually just not been able to clean up some of the crap it wanted to clean up at the end of the process.  Thank you!!
