### ISSUE TITLE
vagrant up fails on Mac OS X

### ISSUE THREAD

**Issue by brentratliff** [geerlingguy/drupal-vm#476]
TASK [geerlingguy.apache : include_vars] ***************************************
ERROR! failed to combine variables, expected dicts but got a 'AnsibleSequence' and a 'AnsibleSequence': 
[{"regexp": "^Listen ", "line": "Listen {{ apache_listen_port }}"}]
[{"regexp": "^Listen ", "line": "Listen {{ apache_listen_port }}"}]
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

When I go to drupalvm.dev I get the Apache2 Debian default page. I am a Vagrant noob.

**Comment by oxyc** [comment]
Which version of Ansible are you using?

**Comment by geerlingguy** [comment]
I'm wondering; can you run `ansible --version` and see what version of Ansible you're running?

**Comment by brentratliff** [comment]
ansible 2.1.0 (devel 3518a05db6) last updated 2016/02/26 10:06:40 (GMT -700)
  lib/ansible/modules/core: (detached HEAD 132b8e8f51) last updated 2016/02/26 10:06:53 (GMT -700)
  lib/ansible/modules/extras: (detached HEAD 479f99678b) last updated 2016/02/26 10:07:04 (GMT -700)
  config file = 
  configured module search path = Default w/o overrides

**Comment by brentratliff** [comment]
I originally installed it with source and then again with pip after reading that's preferred.  I'm wondering if I have a corrupted ansible install.

**Comment by brentratliff** [comment]
I was running ansible from bash source.  I think that was my problem.  I closed the session and am running it again.

**Comment by geerlingguy** [comment]
Ah, sounds good - let me know how it goes!

**Comment by brentratliff** [comment]
Worked. Thanks for the quick reply.

**Comment by geerlingguy** [comment]
Great!
