### ISSUE TITLE
Ansible 2.0.1.0 breaks PHP 7.0 with HTTP Error 404

### ISSUE THREAD

**Issue by ccjjmartin** [geerlingguy/drupal-vm#491]
**ANSWER:** 
My temporary fix was to downgrade back to PHP 5.6 which was able to finish provisioning.

**PROBLEM:**
After upgrading to everything I could think of to the lastest versions:

ansible 2.0.1.0
DrupalVM : commit 4efd654
geerlingguy/ubuntu1404 : 1.0.9
Vagrant : 1.8.1

I get this error:

TASK [Add repository for PHP 7.0.] *********************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 404: Not Found"}

I am thinking it is related to the ansible update but not sure how to fix the 404.

As a side note once I use PHP 5.6 I am receiving the following deprecation warnings which I am guessing are related to the ansible upgrade and not my MariaDB preference:

TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mysql_packages}}'). This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

TASK [geerlingguy.mysql : Delete innodb log files created by apt package after initial install.] ***
changed: [drupalvm]
 [WARNING]: Consider using file module with state=absent rather than running rm

TASK [geerlingguy.mysql : Copy my.cnf override files into include directory.] **
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mysql_config_include_files}}'). This feature will be removed in a future
release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

TASK [geerlingguy.mysql : Update MySQL root password for localhost root account.] ***
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mysql_root_hosts.stdout_lines}}'). This feature will be removed in a future
 release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

TASK [geerlingguy.mysql : Remove anonymous MySQL users.] ***********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mysql_anonymous_hosts.stdout_lines}}'). This feature will be removed in a
future release. Deprecation warnings can be disabled by setting
deprecation_warnings=False in ansible.cfg.

TASK [geerlingguy.mysql : Ensure MySQL databases are present.] *****************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mysql_databases}}'). This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

TASK [geerlingguy.mysql : Ensure MySQL users are present.] *********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your
playbooks so that the environment value uses the full variable syntax
('{{mysql_users}}'). This feature will be removed in a future release.
Deprecation warnings can be disabled by setting deprecation_warnings=False in
ansible.cfg.

**Comment by thom8** [comment]
@ccjjmartin you can also add the patch in the PR above as a current workaround until it's merged.

**Comment by ccjjmartin** [comment]
@thom8 First attempt seemed like it was going to succeed until it hit:

TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": "/usr/bin/composer install --prefer-dist --no-interaction", "delta": "0:00:00.274512", "end": "2016-03-02 05:53:33.998736", "failed": true, "rc": 2, "start": "2016-03-02 05:53:33.724224", "stderr": "Loading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for phpunit/phpunit 4.8.23 -> satisfiable by phpunit/phpunit[4.8.23].\n    - phpunit/phpunit 4.8.23 requires ext-dom * -> the requested PHP extension dom is missing from your system.\n\n  To enable extensions, verify that they are enabled in those .ini files:\n    - /etc/php/7.0/cli/php.ini\n    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini\n    - /etc/php/7.0/cli/conf.d/10-opcache.ini\n    - /etc/php/7.0/cli/conf.d/10-pdo.ini\n    - /etc/php/7.0/cli/conf.d/20-calendar.ini\n    - /etc/php/7.0/cli/conf.d/20-ctype.ini\n    - /etc/php/7.0/cli/conf.d/20-curl.ini\n    - /etc/php/7.0/cli/conf.d/20-exif.ini\n    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.0/cli/conf.d/20-ftp.ini\n    - /etc/php/7.0/cli/conf.d/20-gd.ini\n    - /etc/php/7.0/cli/conf.d/20-gettext.ini\n    - /etc/php/7.0/cli/conf.d/20-iconv.ini\n    - /etc/php/7.0/cli/conf.d/20-imap.ini\n    - /etc/php/7.0/cli/conf.d/20-json.ini\n    - /etc/php/7.0/cli/conf.d/20-mysqli.ini\n    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini\n    - /etc/php/7.0/cli/conf.d/20-phar.ini\n    - /etc/php/7.0/cli/conf.d/20-posix.ini\n    - /etc/php/7.0/cli/conf.d/20-readline.ini\n    - /etc/php/7.0/cli/conf.d/20-shmop.ini\n    - /etc/php/7.0/cli/conf.d/20-sockets.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini\n    - /etc/php/7.0/cli/conf.d/20-zlib.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.", "stdout": "", "stdout_lines": [], "warnings": []}

I am going to run:
`sudo ansible-galaxy install -r provisioning/requirements.yml --force` and try it again

**Comment by thom8** [comment]
`phpunit/phpunit 4.8.23 requires ext-dom`
Has this worked before?

Looks like you might have a dependancy on the PHP ext-dom extension (or php7.0-xml) which unfortunately is not available for ubuntu 14.04 when using this PPA  -- https://launchpad.net/~ondrej/+archive/ubuntu/php

**Comment by ccjjmartin** [comment]
@thom8 I ran the command above plus `vagrant provision` and got a little further to:

TASK [geerlingguy.drush : Run drush to finish setting it up.] ******************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush"], "delta": "0:00:00.392928", "end": "2016-03-02 05:59:36.721539", "failed": true, "rc": 1, "start": "2016-03-02 05:59:36.328611", "stderr": "Unable to load autoload.php. Run composer install to fetch dependencies and write this file (http://docs.drush.org/en/master/install-alternative/). Or if you prefer, use the drush.phar which already has depdencies included (http://docs.drush.org/en/master/install).", "stdout": "", "stdout_lines": [], "warnings": []}

Trying provision again:

`vagrant provision`

Resulted in the same error above, now trying:

`vagrant destroy`
`vagrant up`

Resulted in same Drush dependencies error:

TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": "/usr/bin/composer install --prefer-dist --no-interaction", "delta": "0:00:00.272052", "end": "2016-03-02 06:18:05.931650", "failed": true, "rc": 2, "start": "2016-03-02 06:18:05.659598", "stderr": "Loading composer repositories with package information\nInstalling dependencies (including require-dev) from lock file\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - Installation request for phpunit/phpunit 4.8.23 -> satisfiable by phpunit/phpunit[4.8.23].\n    - phpunit/phpunit 4.8.23 requires ext-dom * -> the requested PHP extension dom is missing from your system.\n\n  To enable extensions, verify that they are enabled in those .ini files:\n    - /etc/php/7.0/cli/php.ini\n    - /etc/php/7.0/cli/conf.d/10-mysqlnd.ini\n    - /etc/php/7.0/cli/conf.d/10-opcache.ini\n    - /etc/php/7.0/cli/conf.d/10-pdo.ini\n    - /etc/php/7.0/cli/conf.d/20-calendar.ini\n    - /etc/php/7.0/cli/conf.d/20-ctype.ini\n    - /etc/php/7.0/cli/conf.d/20-curl.ini\n    - /etc/php/7.0/cli/conf.d/20-exif.ini\n    - /etc/php/7.0/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.0/cli/conf.d/20-ftp.ini\n    - /etc/php/7.0/cli/conf.d/20-gd.ini\n    - /etc/php/7.0/cli/conf.d/20-gettext.ini\n    - /etc/php/7.0/cli/conf.d/20-iconv.ini\n    - /etc/php/7.0/cli/conf.d/20-imap.ini\n    - /etc/php/7.0/cli/conf.d/20-json.ini\n    - /etc/php/7.0/cli/conf.d/20-mysqli.ini\n    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini\n    - /etc/php/7.0/cli/conf.d/20-phar.ini\n    - /etc/php/7.0/cli/conf.d/20-posix.ini\n    - /etc/php/7.0/cli/conf.d/20-readline.ini\n    - /etc/php/7.0/cli/conf.d/20-shmop.ini\n    - /etc/php/7.0/cli/conf.d/20-sockets.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini\n    - /etc/php/7.0/cli/conf.d/20-zlib.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.", "stdout": "", "stdout_lines": [], "warnings": []}

**Comment by thom8** [comment]
again `the requested PHP extension dom is missing from your system.` it may have skipped over the last  task but it you'll still likely have ongoing issues.

Maybe try installing PHP7 from source or using another base box -- https://atlas.hashicorp.com/ubuntu/boxes/ubuntu-15.04-snappy-core-edge-amd64

+ add `php7.0-xml` to your php_packages .

**Comment by thom8** [comment]
@ccjjmartin I've just fixed this issue on another project and this PPA does work so all you need to do is add the following to you config.yml >>

```
php_version: "7.0"
php_packages
  - php7.0
  - libapache2-mod-php7.0
  - php7.0-cli
  - php7.0-common
  - php7.0-curl
  - php7.0-dev
  - php7.0-fpm
  - php7.0-gd
  - php7.0-mbstring
  - php7.0-json
  - php7.0-opcache
  - php7.0-xml
  - libpcre3-dev
```

**Comment by geerlingguy** [comment]
See docs: http://docs.drupalvm.com/en/latest/other/php-7/

Working on testing @thom8's PR now.

**Comment by geerlingguy** [comment]
See updated docs; after @thom8's PR, you also need to make sure to make the changes in `config.yml` suggested for Ubuntu (or whatever OS you're running).
