### ISSUE TITLE
PHP FPM , drupal module extlink, and target="_blank"

### ISSUE THREAD

**Issue by ccjjmartin** [geerlingguy/drupal-vm#493]
**Background:**
When I switched from using mod_php (apache) to php fpm I noticed all of my a tags had an attribute of target="_blank". This was not directly caused by DrupalVM it was caused by the contrib module extlink.

**Questions:**
Does something related to the proxy pass in the apache configuration make extlink think that every link is external?

Should this be fixed by DrupalVM or the contrib module?

**Temporary Solution:**
Disable the contrib module and links are normal again

I posted the question additionally in the contrib module issue queue:
https://www.drupal.org/node/2679977

**Comment by oxyc** [comment]
Doesn't seem likely. For debugging purposes what domain do you use and what does the following return if you run in the browser console:
```js
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4})*)(:[0-9]{1,5})?$/;
console.log(window.location.host.replace(pattern, '$3$4'));
console.log(window.location.host.replace(pattern, '$1'));
```

**Comment by ccjjmartin** [comment]
@oxyc : The above code returned the exact same domain (with extlink disabled):
drupalvm.dev
drupalvm.dev

Do you think I need to reenable the broken module or it shouldn't matter?

**Comment by oxyc** [comment]
the exact same? That's odd, the first one should be `drupalvm.dev` while the second should be empty (or `www`).

**Comment by ccjjmartin** [comment]
"drupalvm.dev"

**Comment by ccjjmartin** [comment]
I am using google chrome

**Comment by oxyc** [comment]
Well that's just very strange. If i'm on http://drupalvm.dev and run
```js
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4})*)(:[0-9]{1,5})?$/;
console.log("host: " + window.location.host.replace(pattern, '$3$4'));
console.log("sub: " + window.location.host.replace(pattern, '$1'));
```
It returns
```
host: drupalvm.dev                                                     VM730:3
sub:                                                                   VM730:4 
```

Earlier did the second console.log return drupalvm.dev or did you mean the domain you were using?

If that's what you meant the only way I can see this happening based on the code is if right-hand condition `(extInclude && url.match(extInclude)` evaluates to true at http://cgit.drupalcode.org/extlink/tree/extlink.js#n69.

This only evaluates to true if you've set a regex value for `'Include links matching the pattern'` in the settings.

**Comment by ccjjmartin** [comment]
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4})*)(:[0-9]{1,5})?$/;
console.log("host: " + window.location.host.replace(pattern, '$3$4'));
console.log("sub: " + window.location.host.replace(pattern, '$1'));
VM16165:3 host: drupalvm.dev
VM16165:4 sub: drupalvm.dev

**Comment by oxyc** [comment]
How about
```js
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4}))(:[0-9]{1,5})?$/;
console.log("host: " + window.location.host.replace(pattern, '$3$4'));
console.log("sub: " + window.location.host.replace(pattern, '$1'));
```

**Comment by ccjjmartin** [comment]
```
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4}))(:[0-9]{1,5})?$/;
console.log("host: " + window.location.host.replace(pattern, '$3$4'));
console.log("sub: " + window.location.host.replace(pattern, '$1'));
VM16250:3 host: drupalvm.dev
VM16250:4 sub: drupalvm.dev
```

**Comment by oxyc** [comment]
So the issue is that the regex match fails and replaces nothing. Why this is the case I do not know :/ Looks correct to me.

**Comment by ccjjmartin** [comment]
@oxyc Thanks for your help, seems we know something about the issue now.

**Comment by oxyc** [comment]
Which operating system and chrome version are you using? I could test it in browserstack.

**Comment by ccjjmartin** [comment]
OSX Version 10.9.5
Chrome Version 48.0.2564.116 (64-bit) - Which is actively updating itself as we speak

**Comment by oxyc** [comment]
Test on Mavericks with Chrome 48 and still unable to reproduce :/ You might try disabling extensions or trying some other browser. I'm out of ideas otherwise. Sorry, hope you get it working.

**Comment by ccjjmartin** [comment]
@oxyc Thanks again for your help.  To give further information I don't think it is the browser or the JS or the regex.  Here is a test from the same OS and browser against www.google.com and another test against drushcommands.com

var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4})*)(:[0-9]{1,5})?$/;
console.log(window.location.host.replace(pattern, '$3$4'));
console.log(window.location.host.replace(pattern, '$1'));
VM192:3 google.com
VM192:4 www.

var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4}))(:[0-9]{1,5})?$/;
console.log("host: " + window.location.host.replace(pattern, '$3$4'));
console.log("sub: " + window.location.host.replace(pattern, '$1'));
VM121:3 host: drushcommands.com
VM121:4 sub: 

I am thinking there is something that changed in the configuration of the server causing this because this site wasn't having any problems with DrupalVM before.  The only change that I can isolate is mod_php versus php fpm.

**Comment by ccjjmartin** [comment]
I don't know if it helps diagnose the problem but when I go to the local IP address (versus the domain name) of the VM I am getting a plain text return of index.php

My guess is the problem is here:

ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

**Comment by oxyc** [comment]
Because I'm bored of regular work and miss regexes I wanted to walk through it :)

```js
// Assuming
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4})*)(:[0-9]{1,5})?$/;
console.log("full host: " + window.location.host); // drupalvm.dev
console.log("host: " + window.location.host.replace(pattern, '$3$4')); // drupalvm.dev
console.log("sub: " + window.location.host.replace(pattern, '$1')); // drupalvm.dev

// Which is equal to:
var pattern = /^(([^\/:]+?\.)*)([^\.:]{4,})((\.[a-z]{1,4})*)(:[0-9]{1,5})?$/;
console.log("full host: drupalvm.dev"); // drupalvm.dev
console.log("host: " + "drupalvm.dev".replace(pattern, '$3$4')); // drupalvm.dev
console.log("sub: " + "drupalvm.dev".replace(pattern, '$1')); // drupalvm.dev

// As `drupalvm.dev".replace(pattern, '$3$4')` and `"drupalvm.dev".replace(pattern, '$1')`
// return the same even with the different subgroups, it means the regex failed to match
// and no replacement has been done.

// Breaking down the regex:
^ // beginning of string
(([^\/:]+?\.)*) // arbitrary amount of subdomains, optional
([^\.:]{4,}) // domain without TLD
((\.[a-z]{1,4})*) // arbitrary amount of TLDs, optional
(:[0-9]{1,5})? // optional port
$ // end of string

// Because regexes are greedy this will be read from right to left
// So let's begin
$6. (:[0-9]{1,5})? // Optional port, Matches nothing

// The inner group, a set of characters between 1-4 chars, prefixed by a dot and
// limited to a-z. Required.
$5. (\.[a-z]{1,4}) // Matches `.dev`

// The combination of all inner groups, will try to match as much as possible, but
// limits itself to a successful regex. As there's only one `.` character in the host it
// only matches one inner group.
$4. ((\.[a-z]{1,4})*) // Matches: `.dev`

// A character set of 4 or more characters prefixed by `.` or `:`
// Sidenote this is a bug in their regex. My own domain has 3 chars :P
$3. ([^\.:]{4,}) // Matches: `drupalvm`

// The inner group, any set of characters more than 1 that's not `.` or `:` and then
// ends with a `.`. Optional and non-greedy.
$2. ([^\/:]+?\.) // Matches: nothing
// Combination of all inner groups, will try to match as much as possible, but limits itself to a successful regex. Optional.
$1. (([^\/:]+?\.)*) // Matches: nothing

$6 === ''
$5 === '.dev'
$4 === '.dev'
$3 === 'drupalvm'
$2 === ''
$1 === ''
```

Why this fails in your case is not part of this exercise. No clue. Maybe some weird character encoding?

I'm probably entirely incorrect about all my assumptions here, and the problem is probably something entirely else as you say. But to humour me could you paste the result of:
```js
window.location.host.split('').reduce(function(a, b) {
 return a + '\\' + b.charCodeAt(0);
}, '');
```

**Comment by ccjjmartin** [comment]
@oxyc Congratulations, you found the bug!!!  Nothing to do with DrupalVM so we can close the issue here.

`Sidenote this is a bug in their regex. My own domain has 3 chars`

I am so sorry for failing to mention this sooner but I was replacing the client's 3 character domain name with drupalvm when posting it here publicly (for privacy reasons - didn't think it made a difference but it does).  You are amazing for finding it!

Are you going to post a patch to the contrib module?

**Comment by oxyc** [comment]
Woohoo awesome! Do you mind posting it?

**Comment by ccjjmartin** [comment]
Posted a proposed patch to fix this in the extlink issue queue:
https://www.drupal.org/node/2679977

**Comment by geerlingguy** [comment]
@ccjjmartin - Awesome!
