### ISSUE TITLE
Ansible Role Error

### ISSUE THREAD

**Issue by McFateM** [geerlingguy/drupal-vm#494]
I'm an old Puppet user looking to begin using Ansible, but thus far it is kicking my butt with the following error...   I'm trying to provision an Ubuntu VM but no matter what I do to the offending line of code, I still end up with similar errors on other lines.   

```
==> drupalvm: Running provisioner: ansible...
ERROR! the role 'geerlingguy.repo-remi' was not found in /Users/markmcfate/Dev/Vagrant/drupal-vm/provisioning/roles:/Users/markmcfate/Dev/Vagrant/drupal-vm/provisioning:/etc/ansible/roles

The error appears to have been in '/Users/markmcfate/Dev/Vagrant/drupal-vm/provisioning/playbook.yml': line 22, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    # Essential roles.
    - { role: geerlingguy.repo-remi, when: ansible_os_family == 'RedHat' }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by oxyc** [comment]
You need to run `$ sudo ansible-galaxy install -r provisioning/requirements.yml --force.`

**Comment by McFateM** [comment]
Thanks, but I have.  It returns the following error...  
`ERROR! - please specify a user/role name, or a roles file, but not both
`

**Comment by oxyc** [comment]
Are you running it the root of the project? So that `provisoning/requirements.yml` actually is in the CWD. Which ansible version are you using?

**Comment by McFateM** [comment]
Yes. 

```
ma7053:drupal-vm markmcfate$ ansible --version
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides
ma7053:drupal-vm markmcfate$ pwd
/Users/markmcfate/Dev/Vagrant/drupal-vm
ma7053:drupal-vm markmcfate$ ls
LICENSE			config.yml		example.config.yml	mkdocs.yml
README.md		docs			example.drupal.make.yml	provisioning
Vagrantfile		drupal.make.yml		examples		tests
```

**Comment by oxyc** [comment]
Hm not sure what could be wrong. Only way I can get that message is if i add an argument to the end of the command.

**Comment by McFateM** [comment]
Thanks oxyc, that helped.  I've taken the --force argument off the end and it appears to be working.

**Comment by oxyc** [comment]
`--force` works for me though. It's just happens if I add something other than a flag. But if it works it works hehe. Can I close this?

**Comment by itsgreggmarshall** [comment]
Actually I was seeing it to.  When I SSH'd in, navigated to the right directory it started building the requirements and gave an error:
```
- downloading role from https://github.com/geerlingguy/ansible-role-nodejs/archive/2.1.1.tar.gz
- extracting geerlingguy.nodejs to /etc/ansible/roles/geerlingguy.nodejs
- geerlingguy.nodejs was installed successfully
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()
```

**Comment by oxyc** [comment]
@itsgreggmarshall you need to update your ansible installation. https://github.com/geerlingguy/drupal-vm/issues/482

**Comment by itsgreggmarshall** [comment]
Ahhh
