### ISSUE TITLE
Composer is owned by root, provisioning scripts that overwrite package conf (like Coder) fail

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#495]
I am trying to provision a VM with the drupal/coder package installed as a global package, so I added it to the config.yml. That worked just fine. 

The second step that I wanted to do was add a provisioning script to auto set the coder profile for me. So I created a basic script:

```
#!/usr/bin/env bash
phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
```

It fails with "phpcs command not found" - even though if I ssh into the box and type phpcs, the command runs.

So, I changed the script to this:

```
#!/usr/bin/env bash
cd /home/vagrant/.composer/vendor/bin
./phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
```

No error, no warning, but PHPStorm reported a config error with the tool when trying to select a profile.

I SSH'ed into the box again and navigated to /home/vagrant. I noticed that .composer is owned by root, so the command has no permission to overwrite the default conf file in the squizlabs codesniffer package.

```
vagrant@local:~$ phpcs --config-set installed_paths ~/.composer/vendor/drupal/coder/coder_sniffer
Config file /home/vagrant/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.conf is not writable
```

At this point the only thing I knew to do to get around it was ```sudo chown -Rf vagrant:vagrant .composer```, and running the phpcs command correctly installed the Drupal coder profile configuration.

Should the .composer folder be owned by root, or be owned by vagrant?

**Comment by joestewart** [comment]
Kevin, the composer role now allows you to set the owner and group.

composer_home_owner: vagrant
composer_home_group: vagrant

I think these should be used in DrupalVM.

**Comment by kevinquillen** [comment]
Ah, thanks. I keep forgetting to check the roles to see the possible config options.

**Comment by oxyc** [comment]
++ for setting a better default. The ruby role defaults to the `ansible_ssh_user` variable, maybe use that in the composer role instead of defaulting to root?

**Comment by geerlingguy** [comment]
I'm good with that.

**Comment by oxyc** [comment]
https://github.com/geerlingguy/ansible-role-composer/issues/17 found a few issues though. @geerlingguy would be great to get your input.
