### ISSUE TITLE
Is AWS Provider required?

### ISSUE THREAD

**Issue by arttus** [geerlingguy/drupal-vm#496]
I'm getting this error from a fresh checkout of origin/master. After a successful Ansible build, i then run "vagrant up" results in the following error.

There are errors in the configuration of this machine. Please fix
the following errors and try again:

AWS Provider:
* An access key ID must be specified via "access_key_id"
* A secret access key is required via "secret_access_key"
* vagrant_aws.config.ami_required

**Comment by arttus** [comment]
Did some searching, i needed to update Virtualbox

vagrant up --provider virtualbox

**Comment by geerlingguy** [comment]
Glad you found the fix!
