### ISSUE TITLE
Errors on initial ansible-galaxy install

### ISSUE THREAD

**Issue by ys2n** [geerlingguy/drupal-vm#498]
New user.   On the initial install I see this error:

```
$ sudo ansible-galaxy install -r provisioning/requirements.yml --force
- downloading role 'selenium', owned by arknoll
- downloading role from https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
 [ERROR]: failed to download the file: HTTP Error 302: Found

 [WARNING]: - arknoll.selenium was NOT installed successfully.

ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
```

Investigating further, it seems that https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz redirects https://codeload.github.com/arknoll/ansible-role-selenium/tar.gz/1.2.0  and whatever is doing the downloading doesn't follow the redirect.

If I ignore-errors, ALL of the downloads look like they have similar problems.

I've poke around a bit, but can't seem to find where the uri for the role is specified or derived....?

Any quick workaround?

**Comment by geerlingguy** [comment]
Can you run `ansible --version` and make sure you're running 2.0.1 or later?

**Comment by ys2n** [comment]
Additional config info:
```
$ ansible --version
ansible 2.1.0
  config file = 
  configured module search path = Default w/o overrides
```

**Comment by ys2n** [comment]
```
$ vagrant --version
Vagrant 1.8.1
```

**Comment by geerlingguy** [comment]
Strange, maybe one of the dependencies (pycurl?) might not be working correctly; it seems to work elsewhere. And you're correct, the URL gets a 302, which should be followed by `ansible-galaxy`:

```
$ curl --head https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
HTTP/1.1 302 Found
```

Can you see if you can get a later version of pycurl with:

```
pip install --upgrade pycurl
```

**Comment by geerlingguy** [comment]
I'm going to close this for now; please leave an update if this is still not working—and as a last-ditch alternative, you can also try downloading the roles manually and placing them inside `/etc/ansible/roles` or inside a `roles` folder inside Drupal VM's playbooks folder.

**Comment by ys2n** [comment]
Will do.  I’ll return to this when I get a chance.  Thanks for your help so far.

yuji
----


On Mar 20, 2016, at 9:49 PM, Jeff Geerling <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm going to close this for now; please leave an update if this is still not working—and as a last-ditch alternative, you can also try downloading the roles manually and placing them inside /etc/ansible/roles or inside a roles folder inside Drupal VM's playbooks folder.

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub<https://github.com/geerlingguy/drupal-vm/issues/498#issuecomment-199082541>

Yuji Shinozaki
----
"Computers are useless.  They only give you answers."  --Pablo Picasso

**Comment by ardnet** [comment]
hi all, can we re-open this issue again? i still got the same problem over and over again, and i'm clueless on how to solve this, been destroy and up again, but to no avail, please advise? this is what i got... thx

```
[WARNING]: - arknoll.selenium was NOT installed successfully: The API server
(https://galaxy.ansible.com/api/) is not responding, please try again later
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
@ardnet - Is it always failing on that task, or does it fail on different roles each time.

Usually if you get the 'API server not responding' error, that means either the network connection is acting unreliably, or the API server itself is either down or rate limiting (which usually only happens when there are a bunch of requests—e.g. hundreds within a few minutes—from the same IP address).

**Comment by ardnet** [comment]
@geerlingguy as far as i can see, seems it's always fail on that task.

if it's network problem, lemme check what i can do from my side, thx!

**Comment by geerlingguy** [comment]
@ardnet - Can you also run `ansible --version` and see what version is installed?

Make sure you're running latest VirtualBox and Vagrant as well... it could affect the galaxy install.

**Comment by johnny5th** [comment]
Also getting this error this morning. I've been using drupalvm for the past couple months and just now having issues.

`==> dcbeer: Running provisioner: ansible...
    dcbeer: Running ansible-galaxy...
 [WARNING]: - arknoll.selenium was NOT installed successfully: The API server
(https://galaxy.ansible.com/api/) is not responding, please try again later.
ERROR! - you can use --ignore-errors to skip failed roles and finish processing the list.`

Running Ansible 2.0.2.0, Virtualbox 5.0.24 r108355, Vagrant 1.8.1 on OSX 10.11.5 with a Centos 7 Guest OS running GuestAdditions 5.0.24

**Comment by johnny5th** [comment]
And now it works. Must be something funky with Ansible Galaxy.

**Comment by geerlingguy** [comment]
@johnny5th - I'm not sure... it's networking, so it could be the API server, rate limiting, something in between... who knows :(

**Comment by johnny5th** [comment]
Yeah who knows. Thanks for all this hard work by the way. Much better than the stack that I duct taped together.

**Comment by Aslan** [comment]
i am still seeing this problem:
```
❯❯❯ curl --head https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
HTTP/1.1 302 Found
Date: Sun, 30 Jul 2017 01:06:21 GMT
Content-Type: text/html; charset=utf-8
Server: GitHub.com
Status: 302 Found
Cache-Control: no-cache
Vary: X-PJAX
Location: https://codeload.github.com/arknoll/ansible-role-selenium/tar.gz/1.2.0
X-UA-Compatible: IE=Edge,chrome=1
Set-Cookie: logged_in=no; domain=.github.com; path=/; expires=Thu, 30 Jul 2037 01:06:21 -0000; secure; HttpOnly
Set-Cookie: _gh_sess=eyJzZXNzaW9uX2lkIjoiYWYzYjY3NjA1YmUwY2Y1NzFlOWExYTRlZDVjNzc3M2QiLCJsYXN0X3JlYWRfZnJvbV9yZXBsaWNhcyI6MTUwMTM3Njc4MTU5Nywic3B5X3JlcG8iOiJhcmtub2xsL2Fuc2libGUtcm9sZS1zZWxlbml1bSIsInNweV9yZXBvX2F0IjoxNTAxMzc2NzgxfQ%3D%3D--b011dfb3a6bd1ef30a1a4cc60266c600c0341e46; path=/; secure; HttpOnly
X-Request-Id: 0381d22fc9ad248bacdc0f43de50ab4e
X-Runtime: 0.024046
Content-Security-Policy: default-src 'none'; base-uri 'self'; block-all-mixed-content; child-src render.githubusercontent.com; connect-src 'self' uploads.github.com status.github.com collector.githubapp.com api.github.com www.google-analytics.com github-cloud.s3.amazonaws.com github-production-repository-file-5c1aeb.s3.amazonaws.com github-production-upload-manifest-file-7fdce7.s3.amazonaws.com github-production-user-asset-6210df.s3.amazonaws.com wss://live.github.com; font-src assets-cdn.github.com; form-action 'self' github.com gist.github.com; frame-ancestors 'none'; img-src 'self' data: assets-cdn.github.com identicons.github.com collector.githubapp.com github-cloud.s3.amazonaws.com *.githubusercontent.com; media-src 'none'; script-src assets-cdn.github.com; style-src 'unsafe-inline' assets-cdn.github.com
Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
Public-Key-Pins: max-age=5184000; pin-sha256="WoiWRyIOVNa9ihaBciRSC7XHjliYS9VwUGOIud4PB18="; pin-sha256="RRM1dGqnDFsCJXBTHky16vi1obOlCgFFn/yOhI/y+ho="; pin-sha256="k2v657xBsOVe1PQRwOsHsw3bsGT2VzIqz5K+59sNQws="; pin-sha256="K87oWBWM9UZfyddvDfoxL+8lpNyoUB2ptGtn0fv6G2Q="; pin-sha256="IQBnNBEiFuhj+8x6X8XLgh01V9Ic5/V3IRQLNFFc7v4="; pin-sha256="iie1VXtL7HzAMF+/PVPR9xzT80kQxdZeJ+zduCB3uj0="; pin-sha256="LvRiGEjRqfzurezaWuj8Wie2gyHMrW5Q06LspMnox7A="; includeSubDomains
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-Runtime-rack: 0.030058
Vary: Accept-Encoding
X-GitHub-Request-Id: E575:2756E:26216F:3A8B0B:597D310D
```

```
❯❯❯ ansible --version
ansible 2.1.0.0
```

**Comment by geerlingguy** [comment]
@Aslan - Can you try upgrading to Ansible 2.3.x (latest version)?
