### ISSUE TITLE
Allow Drupal VM to work on Debian base boxes

### ISSUE THREAD

**Issue by girod** [geerlingguy/drupal-vm#499]
Hi,

I installed drupalvm on ubuntu virtual box, everything works great ! Nice !

After, I tried to install drupalvm on a debian virtual box (wheezy or jessie) and I have 2 pbs when vagrant up:

TASK [Disable the ufw firewall (since we use a simple iptables firewall).] *****
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: ufw"}

TASK [Add repository for PHP 5.6.] *********************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Invalid repository string: ppa:ondrej/php5-5.6"}

I'll appreciate any help.

Thks,

Franck

**Comment by geerlingguy** [comment]
Thanks for the report! For the repo, it technically only works with Ubuntu (PPAs), so if I add full-fledged Debian support, I'll need to find a more robust way to define repos for 5.6, 7.x, etc.

For `ufw`, that doesn't exist on Debian (it's another crazy Ubuntu innovation that I'm not a fan of regardless), so that task should only technically run on Ubuntu distros.

**Comment by geerlingguy** [comment]
@girod - Can you also tell me which base box you were using? That way I can do a couple builds with it and see if I can get it working nicely out of the box.

**Comment by girod** [comment]
I tried with debian/jessie64 and debian/wheezy64

Regards,

**Comment by geerlingguy** [comment]
Working on this now.

**Comment by geerlingguy** [comment]
Note that PHP versions in Debian are currently pinned to whatever version is in the Debian repos... the apt PPAs only work for Ubuntu and I haven't added a different setup so PHP 5.5/7.0 can be installed on Debian in this fix. This just makes sure everything works with the defaults in Debian Jessie, at least.
