### ISSUE TITLE
Drupal Install Failed

### ISSUE THREAD

**Issue by McFateM** [geerlingguy/drupal-vm#500]
I've searched the previous issues and found nothing that looks like this error so I'm posting it here. The error message during Ansible provisioning is...

```
TASK [Install Drupal with drush.] **********************************************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "The conditional check ''Successful' not in drupal_site_installed.stdout' failed. The error was: error while evaluating conditional ('Successful' not in drupal_site_installed.stdout): Unable to look up a name or access an attribute in template string. Make sure your variable name does not contain invalid characters like '-'.\n\nThe error appears to have been in '/Users/markmcfate/Dev/Vagrant/drupal-vm/provisioning/tasks/install-site.yml': line 11, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: Install Drupal with drush.\n  ^ here\n"}
```

The VM is running with Apache serving a status page, and drush is working (see below), but Drupal is not installed.

```
root@drupalvm:/var/www# drush --version
 Drush Version   :  8.1-dev 
```

I've never used Ansible before, although I intend to learn more as soon as I can get this VM working, so I'm stumped here again.

**Comment by geerlingguy** [comment]
What version of Ansible are you running? Can you check with `ansible --version`?

**Comment by McFateM** [comment]
ansible 2.0.1.0
  config file = 
  configured module search path = Default w/o overrides

**Comment by ccjjmartin** [comment]
The error message appears to point to this line in your config.yml file:
```
drupal_site_name: "Drupal"
```
Based on the error message I would make sure that everything was quoted properly.
The message also says make sure your name doesn't contain a dash (-)

Here is the section of the example.config.yml file to focus on for reference as to what should be quoted and what shouldn't:

drupal_major_version: 8
drupal_core_path: "/var/www/drupalvm/drupal"
drupal_domain: "{{ vagrant_hostname }}"
drupal_site_name: "Drupal"
drupal_install_profile: standard
drupal_enable_modules: [ 'devel' ]
drupal_account_name: admin
drupal_account_pass: admin
drupal_mysql_user: drupal
drupal_mysql_password: drupal
drupal_mysql_database: drupal

For the command being run see:
https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/install-site.yml#L15

If that doesn't fix it I would also check:

What version of Drupal were your trying to install?

Did you copy the example.drupal.make.yml to drupal.make.yml and customize that new file.

**Comment by McFateM** [comment]
I've been working from the instructions at http://justdrupal.com/dev-environment-drupal-vagrant-phpstorm-part2/, trying to work that to-the-letter.  The differences between example.config.yml and my config.yml (copied from the former) are:

```
ma7053:drupal-vm markmcfate$ diff config.yml example.config.yml 
2,4d1
< # Numerous modifications made here by MAM on 29-Feb-2016 per 
< # http://justdrupal.com/dev-environment-drupal-vagrant-phpstorm-part2/
< 
28,30c25,26
<   - local_path: ~/Dev/Vagrant/www
<     destination: /var/www
<     id: drupal
---
>   - local_path: ~/Sites/drupalvm
>     destination: /var/www/drupalvm
43c39
< build_makefile: false
---
> build_makefile: true
52,54c48,49
< drupal_major_version: 7
< # drupal_core_path: "/var/www/drupalvm/drupal"
< drupal_core_path: "/var/www/drupal"
---
> drupal_major_version: 8
> drupal_core_path: "/var/www/drupalvm/drupal"
85,88d79
< 
<   - {servername: "drupal.drupalvm.dev", 
<      documentroot: "/var/www/drupal" }
< 
207d197
<   - "9000"
212c202
< php_memory_limit: "512M"
---
> php_memory_limit: "192M"
276,277d265
< 
```

Unlike the documented install, I am trying to get Drupal 7 up and running, rather than version 8.

**Comment by geerlingguy** [comment]
Did you also make the proper changes to the drupal.make.yml file? Or are you working with an existing Drupal 7 site/code base? I noticed your build_makefile looks like it's set to `false`.

**Comment by McFateM** [comment]
Not working with an existing code base, but I would like to eventually.  I set build_makefile to false because that's what it says to do in http://justdrupal.com/dev-environment-drupal-vagrant-phpstorm-part2/.

**Comment by McFateM** [comment]
OK, I rewound everything, largely ignoring what's in http://justdrupal.com/dev-environment-drupal-vagrant-phpstorm-part2/, changed only the Drupal version variable from 8 to 7 in config.yml, and now I have a working Drupal VM, a very nice looking on indeed.  However, it is a Drupal 8 VM.  

I'll do some more checking of the Ansible logs to see what might be up with that. 

Great support!  Thanks.

**Comment by McFateM** [comment]
Hmmm, still confused.  I changed the Drupal major version to 7 in config.yml, and made the following changes to  drupal.make.yml...

```
ma7053:drupal-vm markmcfate$ cat drupal.make.yml 
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "7.x"

projects:

  # Core.
  drupal:
    type: "core"
    download:
      # Drupal core branch (e.g. "6.x", "7.x", "8.0.x").
      branch: "7.0.x"
      working-copy: true

  # Other modules.
  devel: "1.x-dev"
```

But I am still getting a Drupal 8 build?   When I ssh in and do a 'drush pm-list' it reports all 8.0.6-dev components.

**Comment by oxyc** [comment]
Did you already install it once with v8 first? Drupal VM wont reinstall an existing site. You need to delete the database and the codebase if you want to change versions.

**Comment by McFateM** [comment]
Yes I have installed Drupal 8 before (not intending too) but I have been doing 'vagrant destroy' before each 'vagrant up'.  Won't that do the trick?  If not, how/where do I clear the version 8 parts from?  Thanks.

**Comment by oxyc** [comment]
Ah you've set an incorrect branch: `branch: "7.0.x"`. 7 doesn't have semver.

**Comment by McFateM** [comment]
Yes, I saw that and changed it to read "7.x" but I still get a v8 server.

**Comment by oxyc** [comment]
Hmm would you mind destroying it and provisioning again? Could you then paste the provisioning output. Specifically the task: `Generate Drupal site with drush makefile.`

**Comment by McFateM** [comment]
Yes, doing that now.  I wonder... I had to remove the --force flag from my provisioning statement in order to overcome an earlier issue.  See https://github.com/geerlingguy/drupal-vm/issues/494.

**Comment by McFateM** [comment]
So it looks like pertinent steps are being skipped?

```
TASK [include] *****************************************************************
included: /Users/markmcfate/Dev/Vagrant/drupal-vm/provisioning/tasks/build-makefile.yml for drupalvm

TASK [Copy drush makefile into place.] *****************************************
skipping: [drupalvm]

TASK [Ensure drupal_core_path directory exists.] *******************************
skipping: [drupalvm]

TASK [Generate Drupal site with drush makefile.] *******************************
skipping: [drupalvm]

TASK [include] *****************************************************************
included: /Users/markmcfate/Dev/Vagrant/drupal-vm/provisioning/tasks/install-site.yml for drupalvm

TASK [Check if site is already installed.] *************************************
ok: [drupalvm]

TASK [Install Drupal with drush.] **********************************************
changed: [drupalvm]

TASK [Install configured modules with drush.] **********************************
changed: [drupalvm]
```

**Comment by geerlingguy** [comment]
Can you delete the drupalvm directory on your host machine? I'm guessing the makefile is seeing Drupal core there already and not writing a D7 site over it.

**Comment by McFateM** [comment]
Yes, I just saw that too.  I didn't delete drupalvm, but moved the subordinate Sites folder out of the way.  Trying that now.  If that does not work I'll blow away drupalvm (might do this even if it does appear to work) and try again.  Thanks.

**Comment by geerlingguy** [comment]
Always best to start with a clean slate :D

Whenever I'm reprovisioning or switching Drupal core versions, and using a make file to build the site, I delete the existing/created drupal site folder on the host, then provision. It takes a couple extra minutes for Drush to build the file, but it keeps me from having these weird install issues.

**Comment by McFateM** [comment]
I still didn't get the results I was looking for.  'vagrant up' did build a new ~/Sites/drupalvm/drupal directory but Ansible seemed to hang (like for more than 7 minutes) on `TASK [Generate Drupal site with drush makefile.] *******************************`.  I was checking that new directory from a different command window and it never put anything there.

I've since removed ~/Sites entirely, did a destroy and am trying it again.

**Comment by oxyc** [comment]
That command can take quite a long time depending on your connection. It probably didn't hang just took a very long time to complete.

**Comment by McFateM** [comment]
OK, after deleting ~/Sites entirely, then a destroy, and a vagrant up... it works!   Perhaps I was just impatient with the last attempt, but this one took much less time.   

Thanks for all the help gentlemen!

Next step for me is to buy the book (the least I can do given all the great support here) and start learning Ansible so I can customize successfully.  Take care.

**Comment by geerlingguy** [comment]
@McFateM - Glad you could get it working! Also, as the book benefits _me_ financially, but none of the others in this thread, be sure to buy one of them a beer next time you see them if you want :D

Also, if you're going to buy the book, the best place to purchase is through LeanPub, as it will always have the latest updates (the Kindle/paperback editions are usually a few months behind).
