### ISSUE TITLE
www.adminer.org is down, provisioning fails

### ISSUE THREAD

**Issue by timwood** [geerlingguy/drupal-vm#501]
Maybe consider sourcing adminer zip from Github releases?
```

TASK [geerlingguy.adminer : Download Adminer to configured directory.] *********
fatal: [mysite]: FAILED! => {"changed": false, "dest": "/opt/adminer/index.php", "failed": true, "msg": "Request failed", "response": "HTTP Error 500: Internal Server Error", "state": "absent", "status_code": 500, "url": "http://www.adminer.org/latest.php"}

```

**Comment by geerlingguy** [comment]
Of course, no particular service guarantees 100% uptime, but GitHub would be a better option if possible. The problem here is that I'm following Adminer's recommended install method in the `geerlingguy.adminer

**Comment by timwood** [comment]
Thanks, that's what I ended up doing. Of course 10 minutes later the Adminer website came back up.

**Comment by geerlingguy** [comment]
See also (just for future reference): https://github.com/vrana/adminer/pull/116#issuecomment-191331166

Even if unmaintained, I'm still much happier with Adminer than I ever was with phpMyAdmin :/

**Comment by rbrenton** [comment]
The certificate for www.adminer.org has expired.  This is blocking provisioning again.

**Comment by geerlingguy** [comment]
@rbrenton - Looks like it's back again. Note that you can always remove it from installed_extras to get provisioning running again.
