### ISSUE TITLE
Provisioning failing during TASK [Get software for Python-based control.]

### ISSUE THREAD

**Issue by itsgreggmarshall** [geerlingguy/drupal-vm#503]
I have one Windows 7 machine that is giving me problems getting Drupal VM running.

I've updated the box via vagrant box update
I've updated Ansible inside the VM using
`sudo pip install ansible --upgrade
sudo ansible-galaxy install -r provisioning/requirements.yml --force`

I destroyed the VM and tried again and continue to get hung up at during vagrant provision:
`==> WebNY: TASK [Get software for Python-based control.] **********************************
==> WebNY: An exception occurred during task execution. To see the full traceback, use -vvv. The error was: AttributeError: 'list' object has no attribute 'split'
==> WebNY: failed: [localhost] => (item=[u'curl', u'python-apt', u'python-pycurl', u'build-essential']) => {"failed": true, "item": ["curl", "python-apt", "python-pycurl", "build-essential"], "parsed": false}
==> WebNY:      to retry, use: --limit @/vagrant//provisioning/playbook.retry
==> WebNY:`

Not sure what to try next to solve the issue.

**Comment by geerlingguy** [comment]
I seem to remember seeing this error once before, but no clue when it happened or how it was fixed (probably just a `destroy` and `up` again)... have you been able to try that?

Also, what version of ansible is installed? 2.0.1 or something else? And maybe make sure Drupal VM itself is up to date if everything else is up to date as well.

**Comment by geerlingguy** [comment]
Have you been able to get past this particular issue? It sounds like either one of the roles is out of date, or Ansible is out of date.

**Comment by scottatdrake** [comment]
I'm getting this issue right now. 

Ansible: 2.0.1.0
Vagrant: 1.8.1
Virtualbox: 5.0.16
drupal-vm: master branch just pulled

**Comment by geerlingguy** [comment]
@scottatdrake - Are you on windows as well, or on a different platform?

Also, have you run: `sudo ansible-galaxy install -r provisioning/requirements.yml --force` ?

**Comment by scottatdrake** [comment]
@geerlingguy I'm on OS X and yes, have run `sudo ansible-galaxy install -r provisioning/requirements.yml --force`. Doing a `vagrant destroy` and `vagrant up` hasn't seemed to help.

**Comment by scottatdrake** [comment]
Okay, I just got by the point that was hanging. It seemed like the previous task (apt cache update) was taking a long time, as well. So, I did a `vagrant ssh` followed by `sudo apt-get update`, exited, then tried `vagrant provision` again. I have no idea if that fixed the issue, or if perhaps there was just some sort of connectivity problem, but it seems to be working now. ¯\_(ツ)_/¯

**Comment by chrisrikli** [comment]
Had the same issue and did what @scottatdrake did with one minor variation/addition:
1. `vagrant ssh` into the box
2. `sudo apt-get update` revealed a need to run `sudo dpkg --configure -a`.
3.  so, ran `sudo dpkg --configure -a`
4. `exit` VM
5. `vagrant provision`
7. Success!

**Comment by geerlingguy** [comment]
Odd... I guess we'll just keep that as the official answer to whatever this problem may be. I'm guessing networking, something with the repos, who knows!

Thanks for posting what worked!

**Comment by joelrotelli** [comment]
Hi,

I have the exaclty same problem on Ubuntu 14.4. I tried to do what @chrisrikli said, but I still have the problem.

Vagrant 1.8.1
ansible 2.0.1.0
drupalvm : up to date

`failed: [d8vm] => (item=[u'curl', u'python-apt', u'python-pycurl', u'build-essential', u'sudo', u'unzip']) => {"failed": true, "item": ["curl", "python-apt", "python-pycurl", "build-essential", "sudo", "unzip"], "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1467205106.47-165261602526287/apt\", line 2432, in <module>\r\n    main()\r\n  File \"/home/vagrant/.ansible/tmp/ansible-tmp-1467205106.47-165261602526287/apt\", line 448, in main\r\n    packages = p['package'].split(',')\r\nAttributeError: 'list' object has no attribute 'split'\r\n", "msg": "MODULE FAILURE", "parsed": false}
	to retry, use: --limit @/media/hdd/Developpement/vagrant/d8vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
d8vm                       : ok=4    changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
`

**Comment by geerlingguy** [comment]
@joelrotelli - Can you update to the latest version of Ansible (I believe 2.1.0)?

**Comment by joelrotelli** [comment]
Indeed, by 2.0.1.0 I read 2.1.0.0. :)))

So now I have the latest version but I have this error : 

> TASK [Install extra apt packages (if any are configured).] *********************
fatal: [d8vm]: FAILED! => {"failed": true, "msg": "Unexpected templating type error occurred on ({{ extra_packages | list }}): 'NoneType' object is not iterable"}
	to retry, use: --limit @/media/hdd/Developpement/vagrant/d8vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
d8vm                       : ok=158  changed=3    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by geerlingguy** [comment]
@joelrotelli - What do you have `extra_packages` set to? If you don't want any packages, it has to be set to an empty set:

```yaml
extra_packages: []
```

If you just comment out all the lines below, then it will be an empty string instead of an array, and the `| list` call fails on it, causing that iterable error.

**Comment by joelrotelli** [comment]
You're right,  thanks a lot !

**Comment by jrossol** [comment]
I'm having this same issue.  I'm trying to use a Parallels VM box (parallels/ubuntu-14.04) though.  Not sure if the matters.

**Comment by geerlingguy** [comment]
@jrossol - What versions of VirtualBox and Vagrant are you running?

**Comment by geerlingguy** [comment]
@nehajyoti04 - In your config.yml, make sure you set `extra_packages: []` for that variable (if you don't want any extra packages installed.

Also, make sure you have Ansible 2.2 or later.

**Comment by aadiRamakrishna** [comment]
am getting this issue :

TASK [Install required dependencies.] ******************************************
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['curl', 'python-apt', 
'python-pycurl', 'sudo', 'unzip', 'make']` and remove the loop. This feature 
will be removed in version 2.11. Deprecation warnings can be disabled by 
setting deprecation_warnings=False in ansible.cfg.
failed: [project] (item=[u'curl', u'python-apt', u'python-pycurl', u'sudo', u'unzip', u'make']) => {"ansible_loop_var": "item", "changed": false, "item": ["curl", "python-apt", "python-pycurl", "sudo", "unzip", "make"], "msg": "value of state must be one of: absent, build-dep, fixed, latest, present, got: installed"}

PLAY RECAP *********************************************************************
project              : ok=6    changed=0    unreachable=0    failed=1    skipped=2    rescued=0    ignored=0 

** please tel me some solution 

 ansible --version
ansible 2.9.0
  config file = None
  configured module search path = [u'/Users/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:17:52) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
latest Drupal VM
