### ISSUE TITLE
Consider adding `ansible.cfg` and set roles path to the Drupal VM directory

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#505]
...this would allow for a few different things:

  - Users would not need to use `sudo` to install roles, since they would be installed inside a `roles` directory inside the Drupal VM directory (if we set `roles_path` in the config file).
  - Users could modify their `requirements.yml` file to lock down a specific version (albeit manually for now, since Galaxy doesn't have any true 'lockfile' like PHP's Composer or Rubygems, see: https://github.com/ansible/ansible/issues/13496).
  - We could set a couple other custom settings if needed.

A few references for further reading:

  - http://docs.ansible.com/ansible/galaxy.html#roles-path
  - http://leucos.github.io/ansible-files-layout/

I'd also like to take a stab at improving the Galaxy documentation page linked above to include better/more comprehensive examples in the [role requirements files documentation](http://docs.ansible.com/ansible/galaxy.html#advanced-control-over-role-requirements-files).

**Comment by geerlingguy** [comment]
This would also allow me to do local testing on the current _released_ versions of all the roles more easily, which would be a slight win for stability. Sometimes I release a new version/tag and it takes a couple days before I realize it didn't get auto-deployed to Galaxy.

**Comment by oxyc** [comment]
Also a good alternative place for https://github.com/geerlingguy/drupal-vm/pull/557

**Comment by joestewart** [comment]
Would like to discuss this at the Drupalcon BoF too.  Adding versions to requirements.yml and/or per project role installation should reduce maintenance issues with role updates changing config requirements.

**Comment by geerlingguy** [comment]
Added the milestone :)

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/pull/601

Testing this now, and it looks like it will work nicely.

The last thing that would be nice to have is some sort of 'major version locking' ala Composer...

**Comment by geerlingguy** [comment]
I'm thinking this would be a good thing to hold off until the 3.0.0 release, since it's a fairly large structural change.
