### ISSUE TITLE
Document how to setup drupalvm to be used for core tests

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#508]
I was just thinking about how awesome this project is for core development. It would be great if there was a default test.config.yml or some documentation that can be used for the sole purpose of a local core drupal testbot for drupal contribution.

**Comment by geerlingguy** [comment]
@frob - I generally do core dev within Drupal VM (it's especially handy to bring up a fresh new instance, hack on a patch, run tests, then destroy the instance as needed), and I fully support the practice.

However, there's already a fairly well-documented (though dauntingly complex) way to build the exact testbot infrastructure locally: https://www.drupal.org/automated-testing

I'd rather not try to divert people who want to do that away, but rather leave people to do their own configuration and figure out their own optimal workflow for tests, whether it be a container to run the tests in, using drupal.org's issue queues, or doing it all inside Drupal VM.

**Comment by geerlingguy** [comment]
See also:

  - https://www.drupal.org/project/testbot
  - https://www.drupal.org/project/drupalci
  - https://www.drupal.org/node/2463169
