### ISSUE TITLE
Fake acquia cloud settings.php

### ISSUE THREAD

**Issue by jamesrward** [geerlingguy/drupal-vm#510]
This may be a bad idea but I am trying to avoid usual settings.php gyrations by faking the structure acquia uses to inject database settings in each cloud environment.

My settings.php includes the following provided by acquia cloud:
```php
if (file_exists('/var/www/site-php')) {
  require('/var/www/site-php/sitename/sitename-settings.inc');
}
```

I've recreated that folder and file structure and added my database settings to the file but I continue to get  fatal Failed opening required errors such as:
```
Fatal error: require(): Failed opening required '/var/www/site-php/sitename/sitename-settings.inc' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/sitename/docroot/sites/default/settings.php on line 34
```

I did a chown -R 501:dialout on the site-php directory and chmod 775 on the sitename.settings.inc but that has had no effect.

Any other suggestions would be much appreciated.  Once I get this working I hope to create a provisioning script to automate this part of settings up an acquia-cloud VM.

**Comment by geerlingguy** [comment]
I find it is typically a much better approach to include something like a `local.settings.php` file, and manually define the proper settings in there. Just add this to the bottom of the main `settings.php`:

```php
/**
 * Load local development override configuration, if available.
 *
 * Use local.settings.php to override variables on secondary (staging,
 * development, etc) installations of this site. Typically used to disable
 * caching, JavaScript/CSS compression, re-routing of outgoing emails, and
 * other things that should not happen on development and testing sites.
 *
 * Keep this code block at the end of this file to take full effect.
 */
if ($is_local_env && file_exists(DRUPAL_ROOT . '/sites/all/settings/local.settings.php')) {
  require DRUPAL_ROOT . '/sites/all/settings/local.settings.php';
}
```

That snippet is tailored for a particular Acquia Cloud project's configuration which earlier sets up the `$is_local_env` variable... you might want to use the more generic snippet that's used for many other projects; see the following documentation for more info:

  - [Using a local.settings.php file - Acquia Cloud](https://docs.acquia.com/articles/using-localsettingsphp-file)
  - [Add inclusion of a settings.local.php file in settings.php](https://www.drupal.org/node/1118520)
