### ISSUE TITLE
"Preparing to edit /etc/exports. Administrator privileges will be required"

### ISSUE THREAD

**Issue by paperscissors** [geerlingguy/drupal-vm#511]
Had a weird thing happen to me first time I ran vagrant up. I've got the latest versions of vagrant, ansible, and virtualbox installed on my 10.10.5 yosemite machine as of today. I follow the instructions to the T, ansible runs, vagrant up starts to provision the box, but then it hangs here, and asks me for a password:

> ==> drupalvm: Setting hostname...
> ==> drupalvm: Configuring and enabling network interfaces...
> ==> drupalvm: Exporting NFS shared folders...
> ==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...

There doesn't seem to be what I assume is a sudo password set for the user, and I tried all varieties of ones I could think of related to the project, vagrant, drupal, etc, etc.

When I run vagrant provision afterwards it fails at this point in the tasks:

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [drupalvm] => (item=[u'php5', u'php5-mcrypt', u'php5-cli', u'php5-common', u'php5-curl', u'php5-dev', u'php5-fpm', u'php5-gd', u'php-pear', u'php-apc', u'libpcre3-dev']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["php5", "php5-mcrypt", "php5-cli", "php5-common", "php5-curl", "php5-dev", "php5-fpm", "php5-gd", "php-pear", "php-apc", "libpcre3-dev"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"   install 'php5' 'php5-mcrypt' 'php5-cli' 'php5-common' 'php5-curl' 'php5-dev' 'php5-fpm' 'php5-gd' 'php-pear' 'php-apc' 'libpcre3-dev'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n php-pear : Depends: php-cli\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " php-pear : Depends: php-cli"]}

**Comment by paperscissors** [comment]
I'm able to sudo apt-get php-cli and then php-pear manually, for what it's worth--- but if I run vagrant provision again there's just more apt-get issues down the chain, for this same task.

**Comment by geerlingguy** [comment]
The two issues seem unrelated; for the second issue, what `vagrant_box` are you using, and do you have any overridden php settings in your config.yml (different than what's in `example.config.yml`)? Also, are you on the latest versions of everything and latest Ansible roles (e.g. use the ansible-galaxy command in the README to update everything)?

**Comment by webbj74** [comment]
Also seeing this prompt for a pwd. This is on a project which was working back in feb. I ran `vagrant box update` to update `geerlingguy/ubuntu1404` from '1.0.9' to '1.1.0' , but I still get the issue.

```
$ vagrant up
Bringing machine 'foo' up with 'virtualbox' provider...
==> supportcomm: Checking if box 'geerlingguy/ubuntu1404' is up to date...
==> supportcomm: Clearing any previously set forwarded ports...
==> supportcomm: Clearing any previously set network interfaces...
==> supportcomm: Preparing network interfaces based on configuration...
    supportcomm: Adapter 1: nat
    supportcomm: Adapter 2: hostonly
==> supportcomm: Forwarding ports...
    supportcomm: 22 (guest) => 2222 (host) (adapter 1)
==> supportcomm: Running 'pre-boot' VM customizations...
==> supportcomm: Booting VM...
==> supportcomm: Waiting for machine to boot. This may take a few minutes...
    supportcomm: SSH address: 127.0.0.1:2222
    supportcomm: SSH username: vagrant
    supportcomm: SSH auth method: private key
==> supportcomm: Machine booted and ready!
==> supportcomm: Checking for guest additions in VM...
==> supportcomm: Setting hostname...
==> supportcomm: Configuring and enabling network interfaces...
==> supportcomm: Exporting NFS shared folders...
==> supportcomm: Preparing to edit /etc/exports. Administrator privileges will be required...
Password:
```

PHP Changes:
```
@@ -167,6 +167,7 @@
 # Add any extra apt or yum packages you would like installed.
 extra_packages:
   - unzip
+  - php5-xsl
```

Not using Ansible locally.

**Comment by geerlingguy** [comment]
Did you enter your sudo password (should be same as user account password if you're on a Mac)?

**Comment by geerlingguy** [comment]
For the password, you need to enter your Mac admin account password, as Vagrant is asking for permission to modify the NFS exports file on your Mac in `/etc/exports`.

**Comment by stephang** [comment]
I had the same problem. It turned out that I had still some old options in my `config.yml` in the php section that ensured installation of php 5.6 instead of 7.0. My problem was fixed once I had removed them and used the examples given in `default.config.yml`.

**Comment by geerlingguy** [comment]
@stephang - Thanks for the report!
