### ISSUE TITLE
Dashboard drush alias incorrect?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#514]
My dashboard is reporting that my drush alias is ```@local.domain.com.local.domain.com``` when it should only be ```@local.domain.com```.

This appears to be a display error, as the alias that the Dashboard lists does not exist.

**Comment by kevinquillen** [comment]
I believe this bit of code has an extra var in it:

```
{%- macro printSite(servername, docroot) -%}
      {%- if docroot not in _devtool_docroots -%}
        <tr>
          <td><a href="http://{{ servername }}">{{ servername }}</a></td>
          <td><code>{{ docroot }}</code></td>
        {% if configure_local_drush_aliases %}
          <td><code>drush @{{ vagrant_machine_name }}.{{ servername }}</code></td>
        {% endif %}
        </tr>
      {% endif %}
    {%- endmacro %}
```

No need for ```@{{ vagrant_machine_name }}.``` here, I believe.

**Comment by geerlingguy** [comment]
Technically speaking, the machine name can be prefixed on there, I think. Will need to do a bit of testing, but if you have many Drupal sites on one Drupal VM instance, it's necessary to prefix the `{{servername}}` with the alias file name, which is named after the `vagrant_machine_name`...

**Comment by oxyc** [comment]
Before when we generated aliases for pimpmylog/xhprof/adminer using only `drush @{{ servername }}` would have caused the drush command to run on all of them. Now that we dont generated them anymore I guess we could change the alias example but that would also require a conditional for the case when there are more than 1 custom vhost.

**Comment by kevinquillen** [comment]
Oh, I see the reasoning now. I use one VM per client project.

**Comment by geerlingguy** [comment]
Yeah; looking deeper at it, I'd rather leave it as-is, since it's simpler this way and works in all cases; I usually alias things easier (e.g. `@jg.local` for my local site) for projects where I have more customized configurations (e.g. 1 VM per site) anyways; I'd recommend that if it's more the succinctness you're after.
