### ISSUE TITLE
"Install Drupal with Drush" task failed 

### ISSUE THREAD

**Issue by epieters** [geerlingguy/drupal-vm#515]
Fresh install of DrupalVM on Macbook Pro (OS X 10.11.3) with standard config.

Ansible failed to complete successfully.
```
TASK [Install Drupal with drush.] **********************************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", 
"standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-
url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:00.198932", "end": "2016-03-15
 20:55:11.885536", "failed": true, "rc": 255, "start": "2016-03-15 20:55:11.686604", "stderr": 
"require(/var/www/drupalvm/drupal/vendor/autoload.php): failed to 
open\u001b[1;33;40m\u001b[1m[warning]\u001b[0m\nstream: No such file or directory 
autoload.php:14\nPHP Fatal error:  require(): Failed opening required 
'/var/www/drupalvm/drupal/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in 
/var/www/drupalvm/drupal/autoload.php on line 14\nDrush command terminated abnormally due to an 
unrecoverable error.   \u001b[31;40m\u001b[1m[error]\u001b[0m\nError: require(): Failed opening 
required\n'/var/www/drupalvm/drupal/vendor/autoload.php'\n(include_path='.:/usr/share/php:/usr/share/
pear') in\n/var/www/drupalvm/drupal/autoload.php, line 14", "stdout": "\nFatal error: require(): Failed 
opening required '/var/www/drupalvm/drupal/vendor/autoload.php' 
(include_path='.:/usr/share/php:/usr/share/pear') in /var/www/drupalvm/drupal/autoload.php on line 14",
 "stdout_lines": ["", "Fatal error: require(): Failed opening required 
'/var/www/drupalvm/drupal/vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in
 /var/www/drupalvm/drupal/autoload.php on line 14"], "warnings": []}
```
I can ssh into the virtualbox.
PHP looks good:
```
vagrant@drupalvm:/var/www/drupalvm/drupal$ php -v
PHP 5.6.19-1+deb.sury.org~trusty+1 (cli)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

I however do not have the vendor directory:
```
vagrant@drupalvm:/var/www/drupalvm/drupal$ ls
autoload.php  composer.json  composer.lock  core  example.gitignore  index.php  modules  profiles  README.txt  robots.txt  sites  themes  update.php  web.config
vagrant@drupalvm:/var/www/drupalvm/drupal$ cd vendor
-bash: cd: vendor: No such file or directory
vagrant@drupalvm:/var/www/drupalvm/drupal$
```

**Comment by rjewson** [comment]
Ah snap I just came here to log the exact same issue.  Head revision, OSX, standard config.

**Comment by rjewson** [comment]
I fixed it with:

`vagrant ssh`
`cd /var/www/drupalvm/drupal`
`composer install`
`exit`
`vagrant provision`

**Comment by geerlingguy** [comment]
Ah, this is a result of: https://groups.drupal.org/node/509719

A few options:

  - Go back to 8.0.x dev with the complete local git checkout.
  - Add a step to run `composer install` inside the docroot after make file is built (this needs to be disable-able).
  - Switch the make file to not use a working copy by default.

**Comment by epieters** [comment]
running 

> composer install

 inside the docroot worked for me.

Thanks.

**Comment by cfont** [comment]
I had the same problem with the ZIP download of DrupalVM this evening, 16 March, and followed @rjewson fix above which resolved the problem and resulted in a successful deployment. 

```
PLAY RECAP *********************************************************************
drupalvm                   : ok=198  changed=15   unreachable=0    failed=0   
```

As for the question about which option to go with, I like the idea of adding a step to run composer install that is disable-able rather than going back to a previous release of 8.0.x dev. At the same time I think it might be a good idea to cut a release of DrupalVM that is available to download from the site that will work for the person not-yet-comfortable with searching the Internets and especially Github issues for ways to fix their brand new shiny toy they downloaded. Meaning maybe master shouldn't pull from the latest release of Drupal and instead pull a known good tag. 

I'm new to this project and hope to play around and help out where needed so I don't know if y'all have already addressed those kind of questions before but wanted to give my $0.02

**Comment by geerlingguy** [comment]
Working on a fix now... might be as simple as adding the following to `build-makefile.yml`:

```yaml
- name: Check if a composer.json file is present.
  stat: "{{ drupal_core_path }}/composer.json"
  register: drupal_core_composer_file

- name: Run composer install if composer.json is present.
  command: >
    composer install
    chdir={{ drupal_core_path }}
  when: drupal_core_composer_file.stat.exists == true
  become: no
```

**Comment by geerlingguy** [comment]
Testing with a Drupal 8.0.5 download; it works for 8.1.x or 8.2.x working Git copies now, at least. Composer install's a pain.

**Comment by heddn** [comment]
The location of the composer.json needs to be configurable. If we use the composer template option, then the composer.json is one above the web/docroot.
