### ISSUE TITLE
Drush make and Drupal 8 Lightning distro

### ISSUE THREAD

**Issue by humansky** [geerlingguy/drupal-vm#516]
I'm trying to set up a DrupalVM local environment for my team to work on a new Drupal 8 project. We decided to use the Lightning D8 distro. Every on DVM runs fines, up until I get to the drush make part. I get the following error:

> fatal: [pucore]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "lightning", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:04.366782", "end": "2016-03-16 01:07:46.924964", "failed": true, "rc": 1, "start": "2016-03-16 01:07:42.558182", "stderr": "Starting Drupal installation. This takes a while. Consider using the \u001b[1;32;40m\u001b[1m[ok]\u001b[0m\n--notify global option.\nexception 'Drupal\\Core\\Extension\\InfoParserException' with message   \u001b[31;40m\u001b[1m[error]\u001b[0m\n'Unable to parse\nprofiles/lightning/modules/contrib/metatag/metatag_open_graph/metatag_open_graph.info.yml\nA colon cannot be used in an unquoted mapping value at line 1 (near\n\"name: Metatag: Open Graph\").' in\n/var/www/drupalvm/drupal/core/lib/Drupal/Core/Extension/InfoParserDynamic.php:30\nStack trace:\n#0\n/var/www/drupalvm/drupal/core/lib/Drupal/Core/Extension/InfoParser.php(27):\nDrupal\\Core\\Extension\\InfoParserDynamic->parse('profiles/lightn...')\n#1 /var/www/drupalvm/drupal/core/includes/module.inc(159):\nDrupal\\Core\\Extension\\InfoParser->parse('profiles/lightn...')\n#2 /var/www/drupalvm/drupal/core/includes/install.inc(1071):\ndrupal_required_modules()\n#3 /var/www/drupalvm/drupal/core/includes/install.core.inc(1454):\ninstall_profile_info('lightning', 'en')\n#4 /var/www/drupalvm/drupal/core/includes/install.core.inc(440):\ninstall_load_profile(Array)\n#5 /var/www/drupalvm/drupal/core/includes/install.core.inc(113):\ninstall_begin_request(Object(Composer\\Autoload\\ClassLoader), Array)\n#6 /usr/local/share/drush/includes/drush.inc(726):\ninstall_drupal(Object(Composer\\Autoload\\ClassLoader), Array)\n#7 /usr/local/share/drush/includes/drush.inc(711):\ndrush_call_user_func_array('install_drupal', Array)\n#8 /usr/local/share/drush/commands/core/drupal/site_install.inc(80):\ndrush_op('install_drupal', Object(Composer\\Autoload\\ClassLoader),\nArray)\n#9 /usr/local/share/drush/commands/core/site_install.drush.inc(247):\ndrush_core_site_install_version('lightning', Array)\n#10 [internal function]: drush_core_site_install('lightning')\n#11 /usr/local/share/drush/includes/command.inc(366):\ncall_user_func_array('drush_core_site...', Array)\n#12 /usr/local/share/drush/includes/command.inc(217):\n_drush_invoke_hooks(Array, Array)\n#13 [internal function]: drush_command('lightning')\n#14 /usr/local/share/drush/includes/command.inc(185):\ncall_user_func_array('drush_command', Array)\n#15 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(72):\ndrush_dispatch(Array)\n#16 /usr/local/share/drush/includes/preflight.inc(68):\nDrush\\Boot\\BaseBoot->bootstrap_and_dispatch()\n#17 /usr/local/share/drush/drush.php(12): drush_main()\n#18 {main}", "stdout": "You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y", "stdout_lines": ["You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y"], "warnings": []}

When I attempt to install Lightning outside of DVM, I get no errors. Any idea what it could be?

**Comment by geerlingguy** [comment]
It looks like the error is:

```
exception 'Drupal\Core\Extension\InfoParserException' with message 'Unable to parse
profiles/lightning/modules/contrib/metatag/metatag_open_graph/metatag_open_graph.info.yml
A colon cannot be used in an unquoted mapping value at line 1 (near
"name: Metatag: Open Graph").' 

metatag_open_graph needs to define the name like so, to make it valid YAML:

```yaml
name: "Metatag: Open Graph"
```

**Comment by geerlingguy** [comment]
See: https://www.drupal.org/node/2563623

Looks like it's a matter of the Lightning make file needing to update to the `8.x-1.0-beta5` release, which I think contains that fix.

**Comment by humansky** [comment]
Excellent, I'll wait for beta5 to be released. It's strange how it works fine locally, but DVM uses drush v9 and it chokes.

Thank you for all that you do.
