### ISSUE TITLE
Ensure Java is installed Fatal Error!

### ISSUE THREAD

**Issue by TheNugg** [geerlingguy/drupal-vm#517]
I have been using DrupalVM since the beginning, but recently did an update and now I am getting the following errors:

------------------

TASK: [geerlingguy.java | Ensure Java is installed.] ************************** 
fatal: [nodely] => with_items expects a list or a set

FATAL: all hosts have already failed -- aborting

------------------

I have Solr and Selenium commented out, so not sure why it is ensuring Java is installed to begin with.

Please HELP!

**Comment by geerlingguy** [comment]
@TheNugg - What version of Ansible do you have installed on your computer? (`ansible --version`)

You will need to have at least 1.9.x; 2.0.1 (latest release) is preferred.

**Comment by TheNugg** [comment]
@geerlingguy I was using 1.9.x when I was getting the error.  I upgraded to 2.0.1 and it is now working.

Thanks for pointing that out.  You may need to test further with 1.9.x if that version is intended to be supported.

**Comment by TheNugg** [comment]
@geerlingguy Everything seemed to prevision this time around, but now when I try to navigate to my site I get a 503 error.  Everything looks good and Apache2 is running.  Any thoughts?

**Comment by geerlingguy** [comment]
1.9.x support will be flaky at best, moving forward; 2.0 gives a lot of new functionality that will make most of the Ansible roles more efficient/compact/reliable, and the recommendations at any given point (in the project readme) are updated to account for the current recommended versions.
