### ISSUE TITLE
Ensure Parallels guest tools are installed and up to date

### ISSUE THREAD

**Issue by epieters** [geerlingguy/drupal-vm#519]
Out of the box with parallels as the vagrant provider and parallels/ubuntu-14.04 as the vagrant_box you get the following warning:

```
==> drupalvm: Checking for Parallels Tools installed on the VM...
==> drupalvm: Parallels Tools were not detected on this VM! They are required
==> drupalvm: for shared folders, time sync and more. If shared folders are not
==> drupalvm: working on this machine, please install Parallels Tools within the
==> drupalvm: virtual machine and reload your VM.
```
Before you can (re)install the parallels tools via the VM's action menu you need to run this command:

`> sudo apt-get install linux-headers-$(uname -r) build-essential`
(see also http://kb.parallels.com/en/113394)

You can now continue with `vagrant provision`

**Comment by geerlingguy** [comment]
Parallels isn't _officially_ supported by Drupal VM... it works with it, but since I don't have a license, and very few others I know do, I can't give any more support besides what people who use it and have Parallels can provide :)

Is there any official Vagrant box that has the Parallels Tools preinstalled? You'd think the box from the vendor itself would come with the vendor's tools installed :P

**Comment by geerlingguy** [comment]
See also: https://github.com/Parallels/vagrant-parallels/issues/127

If you create a new VM with the following added to the Vagrantfile in the parallels section, does it work automatically?

```
  config.vm.provider :parallels do |p|
    ... other stuff here ...
    p.update_guest_tools = true
  end
```

**Comment by epieters** [comment]
Thanks Jeff, that works.

```
==> drupalvm: Checking for Parallels Tools installed on the VM...
==> drupalvm: Parallels Tools were not detected on this VM! They are required
==> drupalvm: for shared folders, time sync and more. If shared folders are not
==> drupalvm: working on this machine, please install Parallels Tools within the
==> drupalvm: virtual machine and reload your VM.
==> drupalvm: Installing the proper version of Parallels Tools. This may take a few minutes...
==> drupalvm: Parallels Tools have been installed. Rebooting the VM...
==> drupalvm: Attempting graceful shutdown of VM...
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
```
