### ISSUE TITLE
Provisioning the centos7 vagrant box fails

### ISSUE THREAD

**Issue by aleksijohansson** [geerlingguy/drupal-vm#520]
TASK [geerlingguy.mysql : Ensure MySQL packages are installed.] ****************
failed: [drupalvm] => (item=[u'mysql', u'mysql-server']) => {"changed": false, "failed": true, "item": ["mysql", "mysql-server"], "msg": "No Package matching 'mysql-server' found available, installed or updated", "rc": 0, "results": []}

**Comment by geerlingguy** [comment]
Please see the notes under 'Using Different Base OSes': http://docs.drupalvm.com/en/latest/other/base-os/#redhat-enterprise-linux-centos-7

You will need to add/change a few variables in `config.yml`.

**Comment by aleksijohansson** [comment]
@geerlingguy Thanks for the reply! The documentation seems solid.
