### ISSUE TITLE
Add SQLite to DrupalVM 

### ISSUE THREAD

**Issue by humansky** [geerlingguy/drupal-vm#522]
Drupal Console, Drupal 8 tests, and other various components utilize SQLite. Should we add SQLite by default? Perhaps at the very least add this line to the "extra_packages" section of the config.yml file:

```
extra_packages:
  - unzip
  #- php5-sqlite
```

**Comment by humansky** [comment]
If you want drush to work as well, we'll also need to install sqlite3

**Comment by geerlingguy** [comment]
This is one more package, though, that (because Debian/Ubuntu are crazy) would require more tweaking/changing in a switch between PHP 7 and PHP 5.x... I'm thinking I might postpone this until I make the final decision to default everything to PHP 7. Which may be fairly soon!

**Comment by geerlingguy** [comment]
One upstream issue here: https://github.com/geerlingguy/ansible-role-php/issues/126

For installation of SQLite itself, since the package name differs between RedHat and Ubuntu, we might need to use a role :(

Otherwise, two tasks maybe.

**Comment by geerlingguy** [comment]
Looks like we can simply add:

```
extra_packages:
  - sqlite
```

The package name _is_ the same across at least CentOS 7 and Ubuntu 16.04 :)
