### ISSUE TITLE
drupal/drupal-extension started failing due to mink dependency

### ISSUE THREAD

**Issue by michaelpporter** [geerlingguy/drupal-vm#523]
bhat docs create issues docs/extras/behat.md 

composer_global_packages:
{ name: behat/mink, release: '1.5.*@stable' }
{ name: behat/mink-goutte-driver, release: '*' }
{ name: behat/mink-selenium2-driver, release: '*' }
{ name: drupal/drupal-extension, release: '~3.0' }

This morning while running Drupal-VM - vagrant provision I started getting an error on "drupal/drupal-extension".

{ name: drupal/drupal-extension, release: '*' }
The raw out put is in at https://gist.github.com/michaelpporter/2656f9f0990f16e05f06

Changing mink to 1.4 has not solved the issue yet.

composer_global_packages:
  - { name: behat/mink, release: '1.4@stable' }
  - { name: behat/mink-goutte-driver, release: '*' }
  - { name: behat/mink-selenium2-driver, release: '*' }
  - { name: drupal/drupal-extension, release: '~3.0' }

https://gist.github.com/michaelpporter/6414174a3b599c8f71c0

**Comment by michaelpporter** [comment]
For existing boxes I cleaned up Composer

**Comment by michaelpporter** [comment]
I changed everything to "*". This worked on a clean 'vagrant up'. For an existing VM I removed the dependencies for composer in the VM then ran "provision"

**Comment by kevinquillen** [comment]
Doesn't Drupal extension pull the required dependencies without having to specify them as above?

**Comment by geerlingguy** [comment]
So is this basically a documentation issue? We need to update the Drupal VM docs to make sure they're correct?

**Comment by jamesrward** [comment]
@kevinquillen quite right.  Works great on DrupalVM for me with the following:

```yml
composer_global_packages:
  - { name: drupal/drupal-extension, release: '*' }
```

@geerlingguy documentation update is likely all that's needed here.
