### ISSUE TITLE
Support for blackfire

### ISSUE THREAD

**Issue by AshishThakur** [geerlingguy/drupal-vm#526]
Have been using drupal-vm for last couple of months and works like a charm..thanks for the great stuff!

I was wondering if blackfire would be supported in future releases?

Thanks,
Ashish.

**Comment by oxyc** [comment]
@geerlingguy has mentioned interest in this https://github.com/geerlingguy/drupal-vm/issues/91#issuecomment-101407606.

For whatever reason I never managed to get blackfire working when I tried it myself. Would be a nice to have as a reference point as well :+1:

**Comment by geerlingguy** [comment]
This is one of those things I'd like to do... but just never had the time to do, and honestly since I'm more familiar with XHProf and it meets my needs, I've never felt a _need_ to do.

But I would like to support it, so I'm going to leave this issue open but with no hard milestone.

**Comment by AshishThakur** [comment]
Thanks @geerlingguy @oxyc for the updates, though i am not that familiar with ansible, will try to get hands dirty and raise a PR, currently I am manually sshing into the box and installing blackfire with apt-get

**Comment by oxyc** [comment]
There's also this role https://github.com/AbdoulNdiaye/ansible-role-blackfire. It has a few commits for Centos but seem to be rather unmaintained with at least one centos bug https://github.com/AbdoulNdiaye/ansible-role-blackfire/issues/11

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/pull/603
