### ISSUE TITLE
ansible-galaxy install throws error

### ISSUE THREAD

**Issue by AndyRead** [geerlingguy/drupal-vm#528]
I'm getting the error in #158 and have tried the "sudo ansible-galaxy install ..." solution, which installs lots of useful looking roles, but then bombs out with:
```
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()
```
Any idea what's going wrong with this?

**Comment by opdavies** [comment]
What version of Ansible are you using (you can check by typing `ansible --version` into your Terminal)?

If it's less than 2.0, you'll need to update it.

**Comment by AndyRead** [comment]
OK, it's ansible 1.9.4

**Comment by opdavies** [comment]
Yeah, update it so that it's 2.0 or greater. I'm currently running 2.0.1.0 that I've installed via pip.

Then try the `ansible-galaxy` command again. :)

**Comment by AndyRead** [comment]
Thanks - this seems to have cleaned everything up:
```
sudo pip install --upgrade pip
sudo pip install --upgrade ansible
sudo ansible-galaxy install -r provisioning/requirements.yml --force
```
There was just one warning between drupal console and php.  Not sure which it was referring to:
```
[DEPRECATION WARNING]: The comma separated role spec format, use the yaml/explicit format instead.. This feature will be removed in a future release. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

**Comment by geerlingguy** [comment]
That deprecation notice will be fixed after the next drupal-console release. Just some old YAML syntax hanging around in the meta file in that role :)

**Comment by kostajh** [comment]
Unfortunately I'm still seeing the same error reported above (`TypeError: object of type 'NoneType' has no len()` for the php package), on Ansible 2.0.1.0.

**Comment by geerlingguy** [comment]
Hmm, not sure why it's happening. I'll have to try to test as well—can you let me know what system/environment you're running the command on?
