### ISSUE TITLE
How to SSH and Drush

### ISSUE THREAD

**Issue by oskarrough** [geerlingguy/drupal-vm#53]
Hi, thank you for this project. Really excited to get it all running. Being new to VirtualBox/Vagrant etc. I'm having a hard time figuring out how it's supposed to work.

I've got a Sites/drupalvm/drupal (8) installation which appears on 192.168.88.88 and I've succesfully connected to the DB using Sequel Pro as per your instructions.

How do you use Drush? I assume I have to ssh vagrant@192.168.88.88 locally and then Drush will be available? If so, what's the default password?

Is there a default admin user I can log in to the Drupal installation with?

**Comment by oskarrough** [comment]
Aaand answering one part of my own question; To SSH you have to `cd` into your directory where the Vagrantfile is and run `vagrant ssh`

**Comment by geerlingguy** [comment]
Yep! Also, I will be documenting how to use drush soon, just haven't had the time in the past week. Eventually I will be adding an optional task that will create a drush alias file for all the configured sites in the VM, so you could do commands like `drush @drupaltest.dev status` without having to set up any extra configuration yourself!

**Comment by geerlingguy** [comment]
Just for you: https://github.com/geerlingguy/drupal-vm/wiki/Use-Drush-with-Drupal-VM

I've also added a link to that Wiki page from the README and the main http://www.drupalvm.com/ site.
