### ISSUE TITLE
 fatal: [localhost]: FAILED! => {"failed": true, "msg": "'drupalvm_user' is undefined"}

### ISSUE THREAD

**Issue by wah22** [geerlingguy/drupal-vm#533]
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'drupalvm_user' is undefined"}

I am guessing I need to define drupalvm_user, but where do I do this?
I am running Windows 7

**Comment by geerlingguy** [comment]
@wah22 - This should be set automatically during provisioning if you're using a recent version/master of Drupal VM: https://github.com/geerlingguy/drupal-vm/blob/ef50cba994e43f40ad4bfe76ee69ab1b73d02f57/provisioning/vars/main.yml#L8

**Comment by wah22** [comment]
That seemed to do it.

**Comment by scottatdrake** [comment]
I was on 2.3.1. Switching to master appears to have fixed it. Thank you!

**Comment by geerlingguy** [comment]
I think I need to make a new tag :)

**Comment by mdyoung3** [comment]
Hi all,

I am still having this issue after downloading the latest from Git and provisioning it again (and again and again and etc...). I think it might be because I am using CentOS box, as I did not have a user issue with the Ubuntu box.

Here is the error message:

> fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "the field 'become_user' has an invalid value, which appears to include a variable that is undefined. The error was: {{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}

I am running vagrant on a Mac.

**Comment by oxyc** [comment]
@mdyoung3 which version of ansible are you running?

**Comment by oxyc** [comment]
Centos6? https://github.com/geerlingguy/drupal-vm/issues/838#issuecomment-236475772

**Comment by mdyoung3** [comment]
Correct. CentOS 6. Also, it appears to be running Ansible 2.2.1.0. 

But I have even less luck getting CentOS 7 to work.

**Comment by oxyc** [comment]
Wonder why that happens. Does it work if you set

```yaml
drupalvm_user: vagrant
```

in your config.yml?

**Comment by mdyoung3** [comment]
Unfortunately, that seems to create other problems. It seems like, though, CentOS is not very well supported within Drupal VM--and will not be maintained in the future. Not sure if it's worth pursuing.

**Comment by oxyc** [comment]
@geerlingguy has mentioned intentions of dropping centos6 support a few times already yes.

What errors are you getting? As it still is supported (but not out of the box) we would definitely help debug and improve http://docs.drupalvm.com/en/latest/configurations/base-os/#redhat-enterprise-linux-centos-6

**Comment by geerlingguy** [comment]
> CentOS is not very well supported within Drupal VM

_CentOS 6_ is not as well-supported—mostly because one-by-one, almost every single package that's used in the core install has become way outdated, and even 3rd party yum repos are dropping support left and right. EOL for full support is already nearing, and the OS is quite old at this point...

CentOS 7, on the other-hand, is well-supported, and I have most of my own servers running on that OS, so support for CentOS 7 is much better :)

**Comment by mdyoung3** [comment]
Thanks for the update, @geerlingguy. I will focus on getting CentOS 7 operational for our organization.

**Comment by bbdata** [comment]
I'm encountering this error as well. I can get everything up and running when using the default yml. But when I change the following lines per instructions here: http://docs.drupalvm.com/en/latest/deployment/local-codebase/#disable-the-composer-project-build-and-site-install

> drupal_build_makefile: false
> drupal_build_composer: false
> drupal_build_composer_project: false
> drupal_install_site: false

I would get the following error:
`TASK [geerlingguy.composer : Install configured globally-required
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "the field
s undefined. The error was: {{ drupalvm_user }}: {{ ansible_ssh_u
 default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}`

**Comment by geerlingguy** [comment]
@bbdata - What version of Drupal VM are you using, and what OS are you running (host and in VM).

**Comment by bbdata** [comment]
@geerlingguy I was using 4.4.1 that I downloaded straight from drupalvm.com. I'm running Windows 10, using VritualBox 5.1.18 and ubuntu1604

**Comment by geerlingguy** [comment]
@bbdata - Can you open a new issue for this? I wonder if it could be related to something else.
