### ISSUE TITLE
ProxyPassMatch fails when "clean url" option is enabled

### ISSUE THREAD

**Issue by d70rr3s** [geerlingguy/drupal-vm#535]
Hello, I've recently create a new VM  with the latest version of DVM configure everything as usual, go over the dashboard and navigate to my Drupal site and also ok but when I tried to login or anything further than the homepage I get a 404 page from Apache.
I thought maybe was an error in my config file but the extra tools (Adminer, PimpMyLog, etc) were working perfectly and then I realize that none of these tools were using "clean urls", so when I deactivated the option on my Drupal site everything worked as expected. Also I'm only getting this issue with my Ubuntu 15.10 host machine, I got the same environment on Windows 7 and is running fine. If someone can shed some light it would be great.

**Comment by geerlingguy** [comment]
Interesting... I can't replicate on my Mac with either Ubuntu 14 or CentOS 7; what OS are you using, and are there any other things that might be changed from the defaults in your `config.yml`?

**Comment by geerlingguy** [comment]
Also, if you go to the Reports > Status, does it say anything particular about the problem?

**Comment by d70rr3s** [comment]
Later I'll upload my config file but theres no much diference from base file. I'm currently using Ubuntu 15.10 on my host machine and Ubuntu 14 for the VM. I'll take a look to the Reports as you suggest but as I refer in the issue the problem seems to occur even before Drupal has the chance to grab the URL, Apache  thinks for example /user/login is a directory and try to serve it that way.

**Comment by geerlingguy** [comment]
@d70rr3s - I wonder; it could be that provisioning failed the first run, and all that needs to happen is an Apache restart; can you run `sudo service apache2 restart` inside the VM (`vagrant ssh`)?

Also, check the current mods enabled—`ls -lah /etc/apache2/mods-enabled/`

**Comment by d70rr3s** [comment]
Well I didn't see any errors in the provisioning output and also I tried restarting Apache and FPM services but still not working. The list of mods and config file are attached
[apache_mods.txt](https://github.com/geerlingguy/drupal-vm/files/197660/apache_mods.txt)

[config.yml.txt](https://github.com/geerlingguy/drupal-vm/files/197662/config.yml.txt)

**Comment by d70rr3s** [comment]
Sorry I found the problem, when I moved my project to my current machine I most forgot the .htaccess :smile:

**Comment by geerlingguy** [comment]
Ah, that'll do it! Good catch :)
