### ISSUE TITLE
[Question]: How to incorporate the changes made in new releases?

### ISSUE THREAD

**Issue by AshishThakur** [geerlingguy/drupal-vm#536]
In case there is a new release which has some bug fixes or new features, what would be the procedure to upgrade from a old release to a newer one.

Would just pulling the new changes and executing ```vagrant reload``` work?

Thanks,
Ashish.

**Comment by geerlingguy** [comment]
Typically I do the following (if not completely destroying and rebuilding the VM):

  1. Look at release notes and make sure to add new variables mentioned there, and make sure I know the other changes between releases (this is helpful if updating from point release to point release).
  2. Do a diff of my `config.yml` with the updated `example.config.yml` and make sure I'm not missing any major changes there.
  3. If Ansible is installed, update all roles locally (with `--force`).
  3. Run `vagrant provision` to provision the VM again.

**Comment by geerlingguy** [comment]
This might be worthy of addition to docs somewhere.

**Comment by oxyc** [comment]
For a copy pasteable one-liner I use:

```sh
curl https://raw.githubusercontent.com/geerlingguy/drupal-vm/master/example.config.yml | git diff --no-index config.yml -
```

**Comment by AshishThakur** [comment]
Thanks @geerlingguy for quick response, yes looks like this should move to docs as well :)

**Comment by jamesrward** [comment]
What does the command look like for 3 on OSX?

> If Ansible is installed, update all roles locally (with --force).

**Comment by oxyc** [comment]
```bash
sudo ansible-galaxy install -r provisioning/requirements.yml --force
```
