### ISSUE TITLE
Drush site-install currently broken due to upstream issue

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#537]
See: https://travis-ci.org/geerlingguy/drupal-vm/builds/119706131

Builds are currently failing when using `drush_version: master` (Drupal VM's default). Maybe it's finally time to switch to a tag release instead of `master` :/

See upstream drush issue: https://github.com/drush-ops/drush/issues/2110

**Comment by scottatdrake** [comment]
Oh, I was fighting this yesterday. Thanks for the info, @geerlingguy!

**Comment by geerlingguy** [comment]
Fixed via https://github.com/drush-ops/drush/commit/7ca83efe9039209dc5e3f3d43d36b34d31c46641
