### ISSUE TITLE
Support Caddy webserver

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#539]
Might be doable... https://caddyserver.com/ — it looks like an interesting new server that I'd at least like to test/poke/prod with Drupal a bit.

**Comment by ArtuGit** [comment]
it's interesting.

**Comment by geerlingguy** [comment]
Going to drop this for now... Caddy is still interesting, but it seems like uptake in the Drupal community has been pretty weak, meaning if I do anything with it, it'll be mostly on me. It's not a big enough improvement (from what I've seen) over Apache and Nginx especially to make me want to spend the time to build it up yet.

We'll see where it goes, but for now, Apache + Nginx is good enough for me.

**Comment by fubarhouse** [comment]
I might drop this one here, as I would love to see this in the future.
* https://caddy.community/t/drupal-caddyfile/808/2

This may also help me, should I ever need to refer to it.
