### ISSUE TITLE
Question about PHP-FPM configuration

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#542]
Brand new installation and was getting connection errors in Apache log and 503 in browser. Looking at logs:

```
[Sun Apr 03 22:57:29.963981 2016] [proxy:error] [pid 2840] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (127.0.0.1) failed
[Sun Apr 03 22:57:29.964214 2016] [proxy:error] [pid 2840] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Sun Apr 03 22:57:29.964508 2016] [proxy_fcgi:error] [pid 2840] [client 192.168.88.1:58993] AH01079: failed to make connection to backend: 127.0.0.1
```

netstat -tulpn | grep 9000 returned nothing. Looking at /etc/php5/fpm/pool.d/www.conf and it appears there's no listener on the loopback as defined in the ProxyPassMatch directive in the Apache host file. Added listen = 127.0.0.1:9000 to the conf file and all is well now. 

I'm new to PHP-FPM but Is there something missing in the conf file? Or am I missing something in the VM or playbook documentation?

**Comment by geerlingguy** [comment]
Can you do a diff of the config.yml file and see if there are any differences in PHP settings? Also, have you run the ansible-galaxy install command again to make sure all roles are at the latest version? The PHP role defaults to listening on port 9000.

**Comment by minorscience** [comment]
Seems like updating the ansible-galaxy roles did the trick. Thanks for the help!
