### ISSUE TITLE
Composer install fails without proper swap

### ISSUE THREAD

**Issue by wroxbox** [geerlingguy/drupal-vm#547]
```
vagrant@drupalvm:/var/www$ composer create-project acquia/lightning-project:8.1.* MY_PROJECT --no-interaction --stability rc
Cannot load Xdebug - extension already loaded
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Installing acquia/lightning-project (8.1.00-rc1)
  - Installing acquia/lightning-project (8.1.00-rc1)
    Downloading: 100%

Created project in MY_PROJECT
Loading composer repositories with package information
Installing dependencies (including require-dev)
  - Installing composer/installers (v1.0.24)
    Downloading: 100%
The following exception is caused by a lack of memory and not having swap configured
Check https://getcomposer.org/doc/articles/troubleshooting.md#proc-open-fork-failed-errors for details

PHP Fatal error:  Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/bin/composer/vendor/symfony/console/Application.php:954
Stack trace:
#0 [internal function]: Composer\Util\ErrorHandler::handle(2, 'proc_open(): fo...', 'phar:///usr/bin...', 954, Array)
#1 phar:///usr/bin/composer/vendor/symfony/console/Application.php(954): proc_open('stty -a | grep ...', Array, NULL, NULL, NULL, Array)
#2 phar:///usr/bin/composer/vendor/symfony/console/Application.php(754): Symfony\Component\Console\Application->getSttyColumns()
#3 phar:///usr/bin/composer/vendor/symfony/console/Application.php(715): Symfony\Component\Console\Application->getTerminalDimensions()
#4 phar:///usr/bin/composer/vendor/symfony/console/Application.php(648): Symfony\Component\Console\Application->getTerminalWidth()
#5 phar:///usr/bin/composer/vendor/symfony/console/Application.php(130): Symfony\Component\Console\Application->renderException(Object(ErrorException), Object(Symfony\Component\Console\Out in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 954

Fatal error: Uncaught exception 'ErrorException' with message 'proc_open(): fork failed - Cannot allocate memory' in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 954

ErrorException: proc_open(): fork failed - Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Application.php on line 954

Call Stack:
    0.0003     221096   1. {main}() /usr/bin/composer:0
    0.0061     406224   2. require('phar:///usr/bin/composer/bin/composer') /usr/bin/composer:25
    0.0467    1399848   3. Composer\Console\Application->run() phar:///usr/bin/composer/bin/composer:43
    0.0508    1485592   4. Symfony\Component\Console\Application->run() phar:///usr/bin/composer/src/Composer/Console/Application.php:99
  147.5839  280431376   5. Symfony\Component\Console\Application->renderException() phar:///usr/bin/composer/vendor/symfony/console/Application.php:130
  147.5861  280431864   6. Symfony\Component\Console\Application->getTerminalWidth() phar:///usr/bin/composer/vendor/symfony/console/Application.php:648
  147.5862  280431968   7. Symfony\Component\Console\Application->getTerminalDimensions() phar:///usr/bin/composer/vendor/symfony/console/Application.php:715
  147.5862  280432048   8. Symfony\Component\Console\Application->getSttyColumns() phar:///usr/bin/composer/vendor/symfony/console/Application.php:754
  147.5862  280434008   9. proc_open() phar:///usr/bin/composer/vendor/symfony/console/Application.php:954
  147.5863  280435136  10. Composer\Util\ErrorHandler::handle() phar:///usr/bin/composer/vendor/symfony/console/Application.php:954
```

To fix this I had to write:
```
vagrant@drupalvm:/var/www$ sudo /bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
1024+0 records in
1024+0 records out
1073741824 bytes (1.1 GB) copied, 1.33238 s, 806 MB/s
```

```
vagrant@drupalvm:/var/www$ sudo /sbin/mkswap /var/swap.1
Setting up swapspace version 1, size = 1048572 KiB
no label, UUID=af9d7f7e-2ec0-4dc1-b19c-2b7caee11459
```

```
vagrant@drupalvm:/var/www$ sudo /sbin/swapon /var/swap.1
```

Now the Composer install works.

**Comment by oxyc** [comment]
For reference: https://github.com/composer/composer/issues/945

It does sound this could be useful if people actually run into it... I think it should be disabled by default though as I'm already at my drives capacity limit.. But maybe I'm the exception.

**Comment by geerlingguy** [comment]
An even better option, especially if the composer setup is huge (some distributions are a bit loaded), is to increase the VM's memory allotment entirely, so you have more _physical_ memory available to the VM. For most large sites I work on, I set `vagrant_memory: 2048`, as this allows MySQL and PHP both to have a little more room to stretch out, and would solve the memory problem without adding swap space to the disk.

Hopefully Composer can get that bloat under control some other way, but until then, I'd say the two options are:

  1. Increase `vagrant_memory` in your `config.yml`.
  2. Manually create swap space inside the VM.

For simplicity's sake (and for trimming the fat off the VM/box when it's running), I'd rather not add swap to my boxes by default, but if this particular problem crops up often, I may just increase the default `vagrant_memory` limit to `1536` or `2048`. I would do it now, but many people don't have 8+ GB of RAM on their development machines (sadly).

**Comment by kentr** [comment]
For me, PHP `memory_limit = 1792M` allows `composer update` to complete successfully (for a single contrib project update).

`memory_limit = 1536M` did not.

**Comment by geerlingguy** [comment]
I don't know whether to 🤣 or to 😢.

**Comment by vaibhavjain-in** [comment]
I too ran into this problem today, and thanks @wroxbox, the fix you stated above worked well for me. However, @geerlingguy, I tried increasing the VM memory limit didnt worked for me. I updated it to 4gigs, and still faced the issue. I went ahead and tried the fix stated above, and it worked well.

**Comment by bea-alec** [comment]
I concur with @vaibhavjain-in, increasing VM memory to 4096 did nothing and I had to perform the tasks outlined by @wroxbox.

**Comment by swarad07** [comment]
I also ran with this problem, I tried increasing the vagrant memory to 2.5gigs still no luck. Tried the solution mentioned by @wroxbox and it worked for me. :)

**Comment by geerlingguy** [comment]
@vaibhavjain-in / @swarad07 - After increasing the memory did you run a `vagrant reload`? If not, the change doesn't take effect until the next time you reload the VM.

**Comment by cdmo** [comment]
This is still happening for what it's worth. I upped to `2048` and changed `php_memory` to `-1` as a default way of handling this when it happens and then just reverting back to the regular settings when it's resolved.

**Comment by romulogarofalo** [comment]
or you can create a swap file 

`sudo fallocate -l 2G /swapfile`
`sudo chmod 600 /swapfile`
`sudo mkswap /swapfile`
`sudo swapon /swapfile`

**Comment by ANetHead** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thanks romulogarofalo

**Comment by vintprox** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

You are my life's savior! 😂☺👍

**Comment by Deaniell61** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thanks

**Comment by pandesantos** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thank you !!

**Comment by TimothyGolding** [comment]
My solution was do htop. check which process is using too much RAM. It was mysql so i restart mysql then retry composer require. It worked

**Comment by RishiRanjan21** [comment]
free -m

total used free shared buffers cached
Mem: 2048 357 1690 0 0 237
-/+ buffers/cache: 119 1928
Swap: 0 0 0

To enable the swap you can use for example:

/bin/dd if=/dev/zero of=/var/swap.1 bs=1M count=1024
/sbin/mkswap /var/swap.1
/sbin/swapon /var/swap.1

**Comment by jeffrey-kroonen** [comment]
After setting memory_limit to 1024M in php.ini file and restarting the apache2 service I didn't got the error anymore.

**Comment by nicorch** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Works fine for me ! Thanks god

**Comment by kennyalmendral** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thanks!

**Comment by ZixasisMC** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thanks! Eres un genio

**Comment by shopnaill** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thank You

**Comment by thazinmyint** [comment]
I can't solve this problem

**Comment by obnux** [comment]
> or you can create a swap file
> 
> `sudo fallocate -l 2G /swapfile`
> `sudo chmod 600 /swapfile`
> `sudo mkswap /swapfile`
> `sudo swapon /swapfile`

Thank you

**Comment by sms20** [comment]
I find I need to add the swap file every time I want to run composer, so can you make the swap file permanent with a DrupalVM as documented:
https://www.digitalocean.com/community/tutorials/how-to-add-swap-on-ubuntu-14-04#make-the-swap-file-permanent

**Comment by thazinmyint** [comment]
Ok thank you☺️
