### ISSUE TITLE
How best to adjust MySQL max_allowed_packet value?

### ISSUE THREAD

**Issue by philwolstenholme** [geerlingguy/drupal-vm#554]
Thanks for all your work on this project Jeff and the other contributers.

I'm getting a lot of 'MySQL server has gone away' errors with the default set up. 

> PDOException: SQLSTATE[HY000]: General error: 2006 MySQL server has gone away

I understand that bumping up the `max_allowed_packet` value in MySQL config should help with this. What would be the best way to do this in a way that would ideally persist between destroying and reloading the VM?

**Comment by opdavies** [comment]
You can add `mysql_max_allowed_packet: "64M"` into config.yml as it's an variable within the upstream `geerlingguy.mysql` role, and update the value as needed.

**Comment by philwolstenholme** [comment]
That's worked great, thanks @opdavies

**Comment by geerlingguy** [comment]
See also: #201
