### ISSUE TITLE
Drupal 8 extremely slow in Drupal VM on Windows

### ISSUE THREAD

**Issue by smallela1** [geerlingguy/drupal-vm#555]
![image](https://cloud.githubusercontent.com/assets/12515109/14388159/d7ccb140-fd7a-11e5-8fbe-eb083f92bfa9.png)

When I click on Configuration it's taking almost 8 seconds to load up. It's a new site.

**I ran htop in Drupal VM :**

![image](https://cloud.githubusercontent.com/assets/12515109/14388234/303b0b56-fd7b-11e5-8137-010b5489aabd.png)

Any thoughts on why Drupal is slow when using Vagrant in Virtual box?

**Update:**
php-fpm process is eating up lots of resources

**Comment by geerlingguy** [comment]
Are you running in a windows environment? If so, the synced codebase may be using VirtualBox's native shared folders, which are (especially for D8) _excruciatingly_ slow.

See the following for more information:

  - [Windows notes](http://docs.drupalvm.com/en/latest/other/windows/)
  - [Developing with Vagrant and VirtualBox on Windows](http://www.jeffgeerling.com/blog/2016/developing-virtualbox-and-vagrant-on-windows)

**Comment by geerlingguy** [comment]
Also, if you can run some XHProf benchmarks, you should be able to see where PHP is spending the most time... likely with things like file_get_contents() and stat()... See: http://docs.drupalvm.com/en/latest/extras/xhprof/

**Comment by geerlingguy** [comment]
Closing this issue for now; please try to do some XHProf benchmark runs to get further data. It will help a ton in terms of seeing if it's file access that's slow (most likely) or something else... or if it's even site-specific.
