### ISSUE TITLE
Build fails on Windows: "ValueError: A 0.7-series setuptools cannot be installed with distribute"

### ISSUE THREAD

**Issue by agoradesign** [geerlingguy/drupal-vm#562]
We experienced a huge problem today. First my colleague ran into it, and afterwards when I tried, the same thing happened to me. We have a working DrupalVM configuration, based on version 2.3.1, which we already successfully used several times, on different Windows machines - both Windows 7 and Windows 10. But today the build failed, without having changed anything on the config or any other file belonging to DrupalVM.

I've tried to update to 2.4.0, but this didn't change anything. I'm getting the following error message: `ValueError: A 0.7-series setuptools cannot be installed with distribute. Found one at /usr/local/lib/python2.7/dist-packages`

My setup:

- Windows 7
- VirtualBox 5.0.16
- Vagrant 1.8.1
- DrupalVM 2.4.0

I'm attaching the full log, copied from the console window.
[vagrant-log.txt](https://github.com/geerlingguy/drupal-vm/files/213434/vagrant-log.txt)

As far as I can understand the log, it seems that first a 0.6 version of setuptools is used, but later uninstalled and replaced by a more recent "20.7.0" version, but never a 0.7 version.... oooooooooooohhhhhh now I guess, what happened: whatever checks the version of setuptools, does it wrong! Because the version "2**0.7.0**" is incorrectly identified as "0.7.0". What do you think????

**Comment by agoradesign** [comment]
[Setuptools 20.7.0 was released yesterday](https://pypi.python.org/pypi/setuptools) -> that's even one more clue, that back ups my assumption...

**Comment by geerlingguy** [comment]
Hmm... I'll try to take a look at this later—hopefully someone else can chime in if they find a quick fix. Worst case, I may be able to do some sort of workaround in JJG-Ansible-Windows.

**Comment by brockfanning** [comment]
@agoradesign @geerlingguy I ran into it as well, and this quick fix is working for me. In provisioning/JJG-Ansible-Windows/windows.sh, add this line below line 53:

```
rm -fr /usr/local/lib/python2.7/dist-packages/distribute*
```

So, with the line above it:

```
echo "Installing required python modules."
rm -fr /usr/local/lib/python2.7/dist-packages/distribute*
```

**Comment by InPhoenity** [comment]
Thanks for the quick fix @brockfanning , worked for me.

**Comment by kburakozdemir** [comment]
thanks very much for this quick fix @brockfanning , worked for me, too.

**Comment by oxyc** [comment]
Also see https://github.com/geerlingguy/JJG-Ansible-Windows/issues/24

**Comment by agoradesign** [comment]
I've tested the quick fix from @brockfanning  today - worked for me too

**Comment by geerlingguy** [comment]
@agoradesign / @kburakozdemir / @brockfanning / @InPhoenity - Can you please download the latest Drupal VM master release (with the commit referenced just above this comment) and see if that gets pip installed correctly without requiring the manual fix mentioned above?

**Comment by brockfanning** [comment]
@geerlingguy Works for me, thank you.

**Comment by kburakozdemir** [comment]
@geerlingguy  works for me, too. thanks a lot.

**Comment by geerlingguy** [comment]
Perfect! I'll close out this issue then; it should be good to go.

**Comment by TeddyHC** [comment]
@geerlingguy works for me, too. thanks a lot. :)
