### ISSUE TITLE
Fails to install SOLR

### ISSUE THREAD

**Issue by danharper83** [geerlingguy/drupal-vm#563]
I seem to be getting an error message when I add solr into the config and run vagrant provision I get the following.

`fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find handler for \"/root/solr-4.10.4.tgz\". Make sure the required command to extract the file is installed.", "stat": {"exists": false}}`

It seems that it can't uncompress the solr archive.

Cheers Dan

**Comment by geerlingguy** [comment]
Interesting, it looks like you might not have untar installed—can you log into the VM (`vagrant ssh`) and run `sudo apt-get install -y untar`, then do another `vagrant provision` to see if it works?

**Comment by danharper83** [comment]
Thanks Jeff,

I get this error message

`E: Unable to locate package untar`

If I try sudo-apt-get install -y unzip it already thinks it's installed, I also tried sudo apt-get update and then running the command again but got the same message.

Cheers Dan

**Comment by oxyc** [comment]
Could you try logging into the VM (`vagrant ssh`) and then run:

```sh
sudo tar -tzf /root/solr-4.10.4.tgz
```

Seems that's the command where ansible fails

**Comment by danharper83** [comment]
It wouldn't untar so I manually deleted the solr archive downloaded a fresh copy ran untar and finally ran provision and that seemed to work.

Must have been a corrupt solr archive.

Thanks for the help.

**Comment by oxyc** [comment]
Great, glad you got it working!

**Comment by fubarhouse** [comment]
For anybody who finds themselves in this situation, I've got around this very problem which I wasn't expecting to run into.

I've had to download the full 150MB zip instead of the tar.gz and extract it to /root

````
sudo apt-get install -y unzip
wget http://apache.mirror.digitalpacific.com.au/lucene/solr/4.10.4/solr-4.10.4.zip
sudo unzip solr-4.10.4.zip -d /root
````

It seems the available preferred archive is corrupt.

**Comment by geerlingguy** [comment]
@fubarhouse strange; I just provisioned another instance this morning, and the tar.gz worked for me... maybe one of the mirrors is broken?

**Comment by attheshow** [comment]
I just ran into this today when trying to recreate my machine on the latest version of Drupal VM. Using an older version of Solr to match what's on our hosting environment. Here's the error:

`fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to find handler for \"/root/apache-solr-3.6.2.tgz\". Make sure the required command to extract the file is installed.", "stat": {"exists": false}}`

**Comment by attheshow** [comment]
Strange... After destroying and rebuilding it didn't happen again.

**Comment by geerlingguy** [comment]
@attheshow - I blame cosmic rays.
