### ISSUE TITLE
Support request: How do I change the install version of ruby?

### ISSUE THREAD

**Issue by pierremarcelio** [geerlingguy/drupal-vm#564]
I'm trying to change Ruby version form 1.9.3p484 to 2.x. How do I do that?

I see a node config version option nodejs_version:, but I don't see a way to change Ruby version.

Thanks!

**Comment by opdavies** [comment]
There's a `ruby_version` variable within the upstream role.

https://github.com/geerlingguy/ansible-role-ruby/blob/master/defaults/main.yml#L14

Adding that to your `config.yml` file, adjusting the value and re-running `vagrant provision` should work.

**Comment by geerlingguy** [comment]
Exactly as @opdavies said; though you also need to make sure to set `ruby_install_from_source` to `true` and make sure the `ruby_download_url` downloads the right version too; see https://github.com/geerlingguy/ansible-role-ruby

You will need to run `vagrant provision` after configuring that.

**Comment by pierremarcelio** [comment]
Thanks guys! We figured out another way, but this way is much easier. We are at the Drupal Toronto Camp and we were running a BOF on testing speed on Sass preprocessing within the VM so when we share the DrupalVM files, all developers would have everything installed within the VM.

Compile time was a bit slow comparing to compiling within the host machine. I'll keep testing and see how we can improve that.

Thanks!
