### ISSUE TITLE
ERROR: become is not a legal parameter at this level in an Ansible Playbook

### ISSUE THREAD

**Issue by mewfla** [geerlingguy/drupal-vm#566]
Here is the error (after vagrant up & vagrant provision)
    drupalvm: Running provisioner: ansible...
    drupalvm: Running ansible-playbook...
ERROR: become is not a legal parameter at this level in an Ansible Playbook
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Didn't install Ansible locally. Latest Vagrant & VirtualBox

**Comment by oxyc** [comment]
Hmm seems it somehow installed an older version of ansible on the VM. Not sure how that is possible. Could log into the VM (`vagrant ssh`) and check the ansible version with `ansible --version`. This is an entirely new VM?

**Comment by mewfla** [comment]
I actually installed Ansible and all problems went away. Not sure where if found an old copy, but I just installed a fresh copy and all is good.

Thanks for your help.

**Comment by geerlingguy** [comment]
@mewfla - Glad you got it working, @oxyc thanks for the help!
