### ISSUE TITLE
How to install Midnight Commander using 'extra_packages' or by another way

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#569]
Could you give a example?
Thank you for your products.
I bought your Ansible book.

Regards, Artu.

**Comment by oxyc** [comment]
Change this line

```yaml
extra_packages: []
```

To

```yaml
extra_packages:
  - mc
```

and you should be good to go

**Comment by oxyc** [comment]
I'll close this as I assume you got it working. Please re-open the issue if that's not the case.
