### ISSUE TITLE
The website works very slowly

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#570]
I deployed the second website (the first one is empty). But it is works very slowly.

devel7_core_path: "/var/www/drupalvm/devel7"
devel7_domain: "devel7.drupalvm.dev"
devel7_mysql_user: devel7
devel7_mysql_password: devel7
devel7_mysql_database: devel7

apache_vhosts:
  - servername: "{{ drupal_domain }}"
    documentroot: "{{ drupal_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ drupal_core_path }}"

  - servername: "{{ devel7_domain }}"
    documentroot: "{{ devel7_core_path }}"
    extra_parameters: |
          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ devel7_core_path }}"

nginx_hosts:
  - server_name: "{{ drupal_domain }}"
    root: "{{ drupal_core_path }}"
    is_php: true

  - server_name: "{{ devel7_domain }}"
    root: "{{ devel7_core_path }}"
    is_php: true

mysql_databases:
  - name: "{{ drupal_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci

  - name: "{{ devel7_mysql_database }}"
    encoding: utf8
    collation: utf8_general_ci    

mysql_users:
  - name: "{{ drupal_mysql_user }}"
    host: "%"
    password: "{{ drupal_mysql_password }}"
    priv: "{{ drupal_mysql_database }}.*:ALL"
    
  - name: "{{ devel7_mysql_user }}"
    host: "%"
    password: "{{ devel7_mysql_password }}"
    priv: "{{ devel7_mysql_database }}.*:ALL"

# Memory and CPU to use for this VM.
vagrant_memory: 4096
vagrant_cpus: 2

I have free RAM 8GB of 16G total on my Windows host OS.
Why?

**Comment by oxyc** [comment]
Unfortunately the default native share is incredibly slow on Windows. Have a look at this issue and the resources @geerlingguy mentioned https://github.com/geerlingguy/drupal-vm/issues/555#issuecomment-207487193

I'll close this in favour of #555
