### ISSUE TITLE
Search returns no results when searching using search box on http://docs.drupalvm.com/en/latest/

### ISSUE THREAD

**Issue by therobyouknow** [geerlingguy/drupal-vm#572]
For example:

Consider the page:
http://docs.drupalvm.com/en/latest/other/php-7/

Which mentions PHP 7.0
Now, on this same page,  http://docs.drupalvm.com/en/latest/other/php-7/,  if I put PHP 7.0 in the Search box on the left, beneath the title "Drupal VM Documentation" then I get NO results. I should get results because the page I was on, http://docs.drupalvm.com/en/latest/other/php-7/ actually contains PHP 7.0

Google works though, if I enter the following in the Google Search box
site:docs.drupalvm.com php 7.0

https://www.google.co.uk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=site:docs.drupalvm.com+php+7.0

I would therefore suggest the easiest option would be to replace the current search with a Google Custom search.

**Comment by geerlingguy** [comment]
Unfortunately this is an upstream bug with ReadTheDocs, and it might be a while before it's fixed: https://github.com/rtfd/readthedocs.org/issues/1487

For now, to search, I'd either search within the GitHub repository (on GitHub), or search using a `site:` modifier on Google.

**Comment by therobyouknow** [comment]
Thanks for responding geerlingguy and advising on the root cause.

Would it be worth removing the search box so that other folks aren't misled about the search results returning nothing for what they searched for?

**Comment by geerlingguy** [comment]
@therobyouknow - I'm not sure if that's possible with read the docs :/

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/pull/998
