### ISSUE TITLE
Support Ubuntu 16.04 LTS Xenial

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#573]
I've built a minimal base box: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604/

And most roles should _Just Work_, especially since all of them are also compatible with CentOS 7, which uses systemd (the largest change between Ubuntu < 15.10 and now). But I may need to fix a few roles so they're compatible with Xenial. And add xenial to the list of supported Ubuntu versions as needed.

**Comment by geerlingguy** [comment]
First failure, from `geerlingguy.mysql`:

```
TASK [geerlingguy.mysql : Ensure MySQL is started and enabled on boot.] ********
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Job for mysql.service failed because the control process exited with error code. See \"systemctl status mysql.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by oxyc** [comment]
Will you drop support for 12.04 or are you waiting for end of life next year?

**Comment by geerlingguy** [comment]
Currently waiting for EOL. Unfortunately, there are some hosting companies (cough—_Acquia_—cough) who are still _just finished_ transitioning from 10.04 to 12.04. So even 14.04 would be considered _bleeding edge_ :)

**Comment by geerlingguy** [comment]
MySQL bug should be squashed after https://github.com/geerlingguy/ansible-role-mysql/pull/108 passes tests.

Next up, Varnish:

```
The repository 'http://repo.varnish-cache.org/ubuntu xenial Release' does not have a Release file.
```

Might just have to mark Varnish as being unsupported until the upstream repo adds a release channel for Xenial. Will skip it and see what else fails.

**Comment by geerlingguy** [comment]
For Varnish: https://github.com/varnishcache/pkg-varnish-cache/issues/23

**Comment by geerlingguy** [comment]
Upstream MySQL issue was fixed and changes are in 2.1.0 version of that role.

**Comment by geerlingguy** [comment]
Without `vagrant`, everything completes successfully with the default `example.config.yml` settings. Of course, PHP is 7.x no matter what—I don't think I want to try supporting older versions on 16.04.

**Comment by geerlingguy** [comment]
Also, `memcached` won't currently work (at least the PHP extension) since `php5-memcached` doesn't work with 7, and `php7-memcached` doesn't yet exist.

**Comment by geerlingguy** [comment]
Node.js was failing on the `forever` installation, so I think I'm just going to ditch that default in the Node.js role entirely. See: https://github.com/geerlingguy/ansible-role-nodejs/issues/26

**Comment by geerlingguy** [comment]
If installing Redis, you need to also override the PHP Redis package name, setting it to: `php_redis_package: php-redis`.

**Comment by geerlingguy** [comment]
Selenium install fails with:

```
selenium.service is not a native service, redirecting to systemd-sysv-install
Executing /lib/systemd/systemd-sysv-install enable selenium
insserv: warning: script 'selenium' missing LSB tags and overrides
update-rc.d: error: selenium Default-Start contains no runlevels, aborting.
```

**Comment by geerlingguy** [comment]
It looks like everything else works! Working on docs now.

**Comment by geerlingguy** [comment]
@oxyc see, in particular: https://github.com/geerlingguy/drupal-vm/issues/376

**Comment by geerlingguy** [comment]
XHProf is also not working, at least with the way that role is currently configured, due to PHP 7 being the default.
