### ISSUE TITLE
 Bare variables are deprecated

### ISSUE THREAD

**Issue by martinfrances107** [geerlingguy/drupal-vm#576]
ansible 2.2.0

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your 
playbooks so that the environment value uses the full variable syntax 
('{{php_packages}}').
This feature will be removed in a future release. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.
skipping: [drupalvm] => (item=[])

**Comment by geerlingguy** [comment]
This has been fixed in one of the newer versions of the `geerlingguy.php` roles (`with_items: "{{ php_packages }}"`); please make sure to update all your roles using the command `sudo ansible-galaxy install -r provisioning/requirements.yml --force`

**Comment by martinfrances107** [comment]
Ah thank you for the update, and sorry for the noise!
