### ISSUE TITLE
Can XDebug work as a profiler here?

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#577]
or only  for "debugging your code"?

Thank you.

**Comment by ArtuGit** [comment]
Can I use Xdebug with kcachegrind or qcachegrind?

**Comment by geerlingguy** [comment]
I've never used XDebug for profiling, so I wouldn't be the best to answer. I currently use XHProf and will hopefully get Blackfire integrated sooner or later (see: https://github.com/geerlingguy/drupal-vm/issues/526).

**Comment by ArtuGit** [comment]
XDedug can work as profiler here. I have checked.
