### ISSUE TITLE
Where is memcached memory in the config files?

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#578]
Each time when I do --provision for turn on/off  'installed_extras' or on an other reason the 'memcached -m' setting is reset to '-m 64'.
I need restore this settings in the memcahed.conf file.
How Can I install it in the config files?

**Comment by joestewart** [comment]
You can see the variables that can be used for the memcached configuration here:  https://github.com/geerlingguy/ansible-role-memcached

`memcached_memory_limit: 64`

**Comment by ArtuGit** [comment]
Excuse me for a lame question.
How to install it on Drupal VM?

**Comment by geerlingguy** [comment]
@ArtuGit not lame at all :)

Just make sure you have `memcached` in the list of `installed_extras` in `config.yml`; if it's in that list, the `geerlingguy.memcached` role is used, and all those variables are available to you.

**Comment by ArtuGit** [comment]
Thank you,)
