### ISSUE TITLE
Centos6: 500 errors on index.php

### ISSUE THREAD

**Issue by nijk** [geerlingguy/drupal-vm#579]
The install seems to go fine and the dashboard displays as expected but when trying to visit `drupalvm.dev` or any of the development tools Apache throws a 500 error.

From Apache's `error_log`:
```
[warn] proxy: No protocol handler was valid for the URL /index.php. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule.
```

As far as I can see `httpd.conf` is loading the modules correctly:
```
LoadModule proxy_module modules/mod_proxy.so
LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
LoadModule proxy_ftp_module modules/mod_proxy_ftp.so
LoadModule proxy_http_module modules/mod_proxy_http.so
LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
LoadModule proxy_connect_module modules/mod_proxy_connect.so
```

**Comment by oxyc** [comment]
Haven't really used CentOS 6 in a while but with the defaults it apparently doesn't work.

http://docs.drupalvm.com/en/latest/other/base-os/#redhat-enterprise-linux-centos-6
https://github.com/geerlingguy/drupal-vm/issues/346#issuecomment-171869866

So your choices are either to switch to `nginx` or use apache with `mod_php`. The docs I linked to have more information.

**Comment by nijk** [comment]
Thanks, I hadn't spotted that. Running with nginx now and all seems good.

**Comment by oxyc** [comment]
Great!
