### ISSUE TITLE
custom make file

### ISSUE THREAD

**Issue by attiks** [geerlingguy/drupal-vm#58]
Since drush.make.yml uses a different syntax, what is the best way to use an existing make file?

We use make files to build the platform, so converting them to another syntax would be time consuming.

PS: some of the custom modules require an ssh key for the cloning, so it would be great if we could specify one while building the project.

**Comment by geerlingguy** [comment]
@attiks - You can use whatever kind of makefile you'd like by setting `drush_makefile_path` to something different, for example, to use the old ini-style makefile:

```yaml
drush_makefile_path: /path/to/my-drupal-site.make
```

For the custom SSH key, this might be a little more complicated; I've always worked with drush make files pulling in public repositories only (so no need for auth). Does one of the following posts help?

  - [Using Drush Make with private git repositories on github](http://www.systemseed.com/blog/drush-make-private-git-repository-github)
  - [Clone Private Git Repo via Drush Make file fails using ssh authentication](http://drupal.stackexchange.com/q/102822/26)

**Comment by attiks** [comment]
@geerlingguy Good to know I can still use the old format.

The question about SSH was more about how to get an SSH key pair inside the VM, because I guess the cloning is done inside the VM. So I see 2 possibilities:

1/ Configure a predefined key pair and inject it into the VM
2/ Pass the SSH credentials from the host into the VM so it can be used for cloning

So the difficulty is not really the cloning, but how to get a key pair in the right place (and the right user on the VM)

Thanks

**Comment by ravbaba** [comment]
Has anyone managed to use ssh keys from host and be able clone repositories using make file from private sources? I was trying copy key from host to VM but I still need to confirm that I want to add it to authorized_keys so ansible get stuck on it. BTW, the first link doesn't work.

**Comment by caschbre** [comment]
@ravbaba  I haven't tried this yet, but you might try SSH Agent Forwarding. I've been meaning to but haven't had a chance.
https://www.phase2technology.com/blog/running-an-ssh-agent-with-vagrant/

**Comment by geerlingguy** [comment]
@ravbaba @caschbre - This has been enabled by default since the end of June, see: https://github.com/geerlingguy/drupal-vm/commit/c2c3ae0ae983066a2e86ab67cb163d607ce0ddf3

You should be able to use your SSH keys and configuration inside the VM if you login with `vagrant ssh`.

**Comment by ravbaba** [comment]
Hi @geerlingguy,
I know that I am able to use SSH keys when I am inside VM but when you try connect first time to a specific host from the ssh keys then you get a message where you agree add it to known_host file or not.
What it is fine if you do it manually but when you are trying using drupal.make.yml file where I download modules from my custom repos so then script it's getting stuck because of the massage. The PR which I created solve the problem.

https://github.com/geerlingguy/drupal-vm/pull/234

I think there are many ways to do it but than one is more secure I think.

Please let me know what you think.
