### ISSUE TITLE
'Copy drush makefile into place' task failing on new provision

### ISSUE THREAD

**Issue by philwolstenholme** [geerlingguy/drupal-vm#581]
`TASK [Copy drush makefile into place.] *****************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "could not find src=/vagrant/drupal.make.yml"}`

Hi, I'm getting the error above when trying to provision a new VM and install a new site with the makefile.

I'm using the same name and settings as a previous VM, but I've deleted that VM through the VirtualBox UI.

The `/vagrant/drupal.make.yml` file exists, and the permissions are as follows:

![screen shot 2016-04-30 at 7 08 pm](https://cloud.githubusercontent.com/assets/6339853/14937674/11f8dc66-0f07-11e6-891f-5e3bed93d6e2.png)

I'm using OS X El Capitan / 10.11.4 and the latest version of this project from the master branch.

**Comment by oxyc** [comment]
The way the makefile is used was changed a while ago. You need to update your `config.yml` by setting `drush_makefile_path: ../../drupal.make.yml`. https://github.com/geerlingguy/drupal-vm/commit/e11b685f591a397824d8e2a2de0bcc995f0cde35

**Comment by philwolstenholme** [comment]
Ah wonderful, thank you very much @oxyc . My fault for not spotting that when I compared the `example.config.yml` from the repo with my previous `config.yml`.
