### ISSUE TITLE
notify-send-http

### ISSUE THREAD

**Issue by martinmenge** [geerlingguy/drupal-vm#582]
I realise you want to keep the tool-belt lean, but I believe this might be a generic enough feature request... Can you please add [https://github.com/fgrehm/notify-send-http](url)

[https://github.com/fgrehm/notify-send-http#vagrant](url)

**Comment by geerlingguy** [comment]
I'd rather not add it by default; the use case isn't in the 80%+ range, I don't think... however, using a local Vagrantfile, you could add that in yourself, I'm pretty sure (following their instructions).

See the documentation here: http://docs.drupalvm.com/en/latest/other/local-vagrantfile/
