### ISSUE TITLE
Can't get Varnish configuration working

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#584]
I used this instruction - http://docs.drupalvm.com/en/latest/extras/varnish/

Additionally I installed the https://www.drupal.org/project/varnish module.
I added these lines:
$conf['cache_backends'][] = 'sites/all/modules/contrib/varnish/varnish.cache.inc';
$conf['cache_class_cache_page'] = 'VarnishCache';
into a seetings,php according a readme.txt of module.

I have set up the settings on the module settings page.
I see a 'Drupal running' message. http://prntscr.com/azuj6p

But an ESI module (https://www.drupal.org/project/esi) does not work.

I suspect that the Varnish does not work properly.
I checked according this instruction - https://uk.godaddy.com/help/how-to-test-varnish-using-curl-12388 .
I tried:
curl -I http://127.0.0.1/
curl -I mysite.drupal-vm.dev
curl -I mysite.drupal-vm.dev/path/to/image.png
But I do not see any signs of Varnish according the instruction.

What can be wrong?

**Comment by geerlingguy** [comment]
So... in this particular case, Varnish is working fine (at least inside the VM), but the configuration, the use with ESI (which can be extremely difficult to get working correctly)... those things may not be working.

By default, Varnish listens on port 81 (not 80), so you would need to curl that port:

```
curl -I mysite.drupal-vm.dev:81
```

ESI may require additional configuration for the VCL, depending on how you're using it.

**Comment by ArtuGit** [comment]
Thank you.
At least I know that Varnish runs on port 81.
I think it is a good idea that ESI can work out of the box.
