### ISSUE TITLE
Drupalvm / vagrant up does not works for me

### ISSUE THREAD

**Issue by tmac14** [geerlingguy/drupal-vm#585]
Hello guys.
vagrant up command freeze with this message: SSH - drupalvm: Warning: Remote connection disconnect. Retrying ...
Then i exec vagrant provision command and I get this msg: "Failed to connect to the host via ssh" : "unreachable" : true
Can someone help me ? thanks

**Comment by oxyc** [comment]
Hmm wondering if it could be the usual VT-x. http://docs.drupalvm.com/en/latest/other/linux/#intel-vt-x-virtualization-support

Otherwise you could try starting the virtual machine through the regular VirtualBox GUI to see if there's something that's halting it from booting.

Also, which OS are you using?

**Comment by tmac14** [comment]
I have enabled VT-x on BIOS settings but my CPU is not Intel.
Im using Linux, Antergos distribution. My CPU is AMD.

**Comment by oxyc** [comment]
Hmm, does running it directly through the VirtualBox GUI give any clues?

Unfortunately I haven't personally experienced this but maybe someone else reading this issue queue can help. Googling around and it seems like a somewhat common problem for Vagrant users. There's too many entirely different solutions for me to give any suggestions though...

**Comment by oxyc** [comment]
Also make sure you're using the latest versions of Vagrant and VirtualBox.

**Comment by geerlingguy** [comment]
I've never seen someone try it on Antergos, but there are definitely users with Arch Linux that have Drupal VM working fine. I personally don't have access to a computer with an AMD processor, though, so maybe there's something on _that_ layer that's causing an issue...

**Comment by geerlingguy** [comment]
Going to close for now; please let me know if you get it working, or find any more debugging notes/error messages that might be helpful. Unfortunately, I'm not able to help too much if it's an Antergos-specific or AMD-specific issue.

**Comment by timellemeet** [comment]
I have the same issue. I am on windows 10 with an intel i7 amd graphics. This is what happens:

` drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
    drupalvm: Warning: Remote connection disconnect. Retrying...
`

**Comment by geerlingguy** [comment]
@timellemeet - Can you try using a different VM, e.g. create a new folder somewhere, and in powershell (or whatever CLI you're using), run `vagrant init`, then run `vagrant up` and see if that works with a vanilla Vagrant box?

**Comment by jmevalentin** [comment]
I'm experiencing the same. I've recreated the drupalvm directory with a fresh download of drupalvm, updated vagrant to the latest but now when I try vagrant up I get the error:  

` Couldn't open file /Library/WebServer/Documents/drupalvm/base`

**Comment by geerlingguy** [comment]
@jmevalentin - Hmm... that sounds like a synced folder issue maybe; where does that error come into play (can you give more context?).

**Comment by jmevalentin** [comment]
@geerlingguy Hi, sorry I'm not sure what you mean, but I decided to copy the maser files into a drupalvm2 directory and try again. This time, after a long pause (perhaps 5-10 minutes), I got the following error:

> The box 'geerlingguy/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

>URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1604"]
Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes receive
> 
 
I tried vagrant login, which of course asks for an Atlas Username, which I don't have, so I don't know what to do next. Any thoughts?

**Comment by geerlingguy** [comment]
@jmevalentin - If you visit https://atlas.hashicorp.com/geerlingguy/ubuntu1604 in a web browser, what do you get? It sounds like you might have a network issue or be behind a corporate proxy, something like that...

**Comment by jmevalentin** [comment]
I am able to visit the site, no problem there. However, I can't ping it for some reason. Could that be a router issue?

**Comment by geerlingguy** [comment]
@jmevalentin - maybe. Can you check `vagrant --version`, and also run `vagrant box add geerlingguy/ubuntu1604` to see what happens?

**Comment by jmevalentin** [comment]
I have Vagrant 1.8.6, just downloaded/upgraded this morning. I ran that second command and it takes another several minutes, then I got these messages:  

> The box 'geerlingguy/ubuntu1604' could not be found or
could not be accessed in the remote catalog. If this is a private
box on HashiCorp's Atlas, please verify you're logged in via
`vagrant login`. Also, please double-check the name. The expanded
URL and error message are shown below:

>URL: ["https://atlas.hashicorp.com/geerlingguy/ubuntu1604"]
Error: Operation timed out after 0 milliseconds with 0 out of 0 bytes received

I tried pinging https://atlas.hashicorp.com/geerlingguy/ubuntu1604 from my local network and get 
> ping: cannot resolve https://atlas.hashicorp.com/geerlingguy/ubuntu1604: Unknown host

I ssh into a remote box and tried again and get a similar message. Any chance that site's locking out unknown connections and only serving the site since it's a local request?

To get me working for now, can I download the full installation and point to a local directory for the vagrant up process, or is there an alternative server I can point to for the process?

**Comment by geerlingguy** [comment]
You can only ping servers, not full URLs (so you could ping `atlas.hashicorp.com`).

If I do so, I get:

```
$ ping atlas.hashicorp.com
PING atlas.hashi.co (52.206.86.0): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
...
```

What happens if you run `curl --head https://atlas.hashicorp.com/geerlingguy/ubuntu1604`? It should show a 301 to the location `https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604`. If it gives some other output, I'm guessing you're behind a network route that is blocking access to Hashicorp's servers or something.

You can also download the boxes manually from http://files.midwesternmac.com/, then use them with a path to the box instead of the box alias.

**Comment by jmevalentin** [comment]
Dang it, I know that, sorry, sleep depravation. I also get the timeout, which appears to be the whole issue. On the remote machine, it just hangs, never returning an error, so I break out and it shows 100% packet loss, time 1086693ms. Running the curl command causes a hang as well and eventually times out. 

I was able to do a vagrant up yesterday without an issue, so I'm not sure what changed, although I did comment out all previous references to vagrant which I had from previous projects.

If I download the boxes, where do set this path? Or are you stating just add them to virtualbox manually? In that case I still don't know what to change to refer to that instance.

**Comment by jmevalentin** [comment]
Btw, on that midwesternmac.com page, the url I think I need is https://vagrantcloud.com/geerlingguy/boxes/ubuntu1604, correct? If so, can we get the manual add to use that path?

**Comment by geerlingguy** [comment]
I think you can do a `vagrant add http://files.midwesternmac.com/boxes/ubuntu1604/virtualbox-105.box`... and then set `vagrant_box` to `file:///local/path/to/virtualbox-105.box`

**Comment by jmevalentin** [comment]
Can I assume you mean line 4 of the config.yml file?  So it would change from: 

> vagrant_box: geerlingguy/ubuntu1604

to

> vagrant_box: file:///local/path/to/virtualbox-105.box

Correct?

**Comment by geerlingguy** [comment]
Yes.

**Comment by jmevalentin** [comment]
I've tried the vagrant box add command and added the --debug option. At first it runs a bunch of commands, then it gets to the "DEBUG subprocess: stderr:  " and runs several dozen lines of 0 in all column (except for the time counter), and it's still going after about 1.5 hours. What am I doing wrong?

**Comment by geerlingguy** [comment]
@jmevalentin - It sounds like something might be messed up in your workstation's install of Vagrant or Virtualbox, maybe... can you try on another computer and see if you get the same problems?

**Comment by jmevalentin** [comment]
You may be right, I've got a couple of systems I can try this on. I'll get back to you once I'm able to. Thanks!

**Comment by geerlingguy** [comment]
@jmevalentin - also try downgrading to Vagrant 1.8.6 - see this bug: https://github.com/mitchellh/vagrant/issues/7969

**Comment by jmevalentin** [comment]
I deleted the embedded/bin/curl directory per a couple of the suggestions and it seems to have helped. However, I now get the error: 

> Couldn't open file /Library/WebServer/Documents/drupalvm/base

I tried setting 777 recursively on the directory to avoid permission issues, but that doesn't seem to help. Should I force create that directory?

**Comment by geerlingguy** [comment]
@jmevalentin - Is this related to https://github.com/geerlingguy/drupal-vm/issues/672 ? It seems you had the same issue there.
