### ISSUE TITLE
Ubuntu 12.04 installs Apache 2.2 by default, without mod_fcgi

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#589]
When doing `vagrant up` with `geerlingguy/ubuntu1204` as the base box and default config, I get the following error:

```
TASK [geerlingguy.apache : Enable Apache mods.] ********************************
changed: [chn1] => (item=expires.load)
changed: [chn1] => (item=ssl.load)
changed: [chn1] => (item=rewrite.load)
changed: [chn1] => (item=proxy.load)
failed: [chn1] => (item=proxy_fcgi.load) => {"failed": true, "item": "proxy_fcgi.load", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /etc/apache2/mods-available/proxy_fcgi.load", "path": "/etc/apache2/mods-enabled/proxy_fcgi.load", "src": "/etc/apache2/mods-available/proxy_fcgi.load", "state": "absent"}
```

It looks like `ppa:ondrej/apache2` could be used to get 2.4 and proxy_fcgi... but that would need to be added in with `apt-add-repository ppa:ondrej/apache2` prior to the roles being configured.

I hate supporting ancient LTS releases... could this be the straw that breaks the camel's back?

**Comment by geerlingguy** [comment]
Adding docs label since documentation doesn't mention any differences for Ubuntu 12.04 support...

**Comment by xaviemirmon** [comment]
Hi @geerlingguy

Thanks so much for this VM.  We've been using this setup to mimic as much as possible the Acquia cloud setup.  As much as it is annoying to support LTS, the main deciding factor to use Drupal VM is the AC replication in instances when DevDesktop doesn't cut it.  So IMHO a necessary evil until Acquia move their servers to 16.04 LTS.  Is there anything I can do to help move this along but my boxes have now also broken :(   How do you add `apt-add-repository ppa:ondrej/apache2` to the provisioning?

**Comment by geerlingguy** [comment]
@xaviemirmon - For now, the simplest way would be to 'hack' the `provisioning/tasks/init-debian.yml` file and add the following task:

```yaml
- name: Add repository for Apache 2.4 on Ubuntu 12.
  apt_repository: repo='ppa:ondrej/apache2'
  when: ansible_distribution_release == "precise" and ansible_distribution == "Ubuntu"
```

I'm going to test this locally and if it works, I'll commit it to Drupal VM so everything works with 12.04 out of the box.

**Comment by geerlingguy** [comment]
@xaviemirmon - Please see if the latest commit helps; it requires a full rebuild (or you can log in with `vagrant ssh` and uninstall apache2 packages entirely, the run provision again).

**Comment by xaviemirmon** [comment]
Hi @geerlingguy that works for me thanks!

**Comment by manarth** [comment]
12.04 Precise reached EOL in April 2017, and it looks like the Precise packages are no longer available in the PPA. As a result, DrupalVM now falls back to the original Precise Apache release, 2.2.

![screen shot 2017-06-08 at 13 21 00](https://user-images.githubusercontent.com/271171/26928314-99739508-4c4d-11e7-9e4f-f8aa6faaea99.png)

**Comment by geerlingguy** [comment]
@manarth - Good catch. With 12.04 officially unsupported now, I'm planning on slowly decommissioning support and removing anything that was added specifically for 12.04. All of my roles work equally well with 14.04 and 16.04 (though 16.04 brings along systemd, which is a bit of a change for some things), so I'm just recommending people still on 12.04 move to 14.04 ASAP.
