### ISSUE TITLE
Drupal Theme not displaying after clean build

### ISSUE THREAD

**Issue by whanrott** [geerlingguy/drupal-vm#591]
Host: Ubuntu 14.04 Trusty + Ansible 2.0.2.0 (from Launchpad) + Virtualbox 5.0.20 + Vagrant 1.8.1 + VBoxAdditions 5.0.20
Guest: geerlingguy/ubuntu1404

I've built the VM and the Drupal site has installed. It doesn't display the theme. The permissions in the /tmp/ directory on the guest may be preventing it displaying. The theme is definitely installed and set as default.

Example error:

> The specified file temporary://file3shVT7 could not be copied because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

This error was displayed in the page messages__list as a messages__item

I changed the permissions on the /tmp/ directory within the guest, following the advice in http://unix.stackexchange.com/questions/71622/ but it still didn't work.

**Comment by oxyc** [comment]
I think you need to `chmod` the files directory:

```sh
vagrant ssh
...
sudo chmod -R 777 /var/www/drupalvm/drupal/sites/default/files`

**Comment by whanrott** [comment]
@oxyc Thanks, I've checked the permissions as you suggested. The folder already has 777 permissions. I applied the chmod in case there was anything else in the tree but it didn't fix the problem. 

I also checked the .htaccess in /var/www/drupalvm/drupal/sites/default/files: 
`# Turn off all options we don't need.
Options -Indexes -ExecCGI -Includes -MultiViews

# Set the catch-all handler to prevent scripts from being executed.
SetHandler Drupal_Security_Do_Not_Remove_See_SA_2006_006
<Files *>
  # Override the handler again if we're run later in the evaluation list.
  SetHandler Drupal_Security_Do_Not_Remove_See_SA_2013_003
</Files>

# If we know how to do it safely, disable the PHP engine entirely.
<IfModule mod_php5.c>
  php_flag engine off
</IfModule>`

I'm not familiar with these directives but I don't see a problem with the .htaccess. I removed the file and restarted but it didn't fix.

**Comment by oxyc** [comment]
Hm some other things to look at:

- `http://drupalvm.dev/admin/reports/status` any listed errors?
- `http://drupalvm.dev/admin/config/media/file-system` what are the paths for public and temporary files?
- `/var/log/apache2/error.log`
- Are you using Drupal 7 or 8? Which theme?

**Comment by whanrott** [comment]
Drupal version: 8.1.2-dev (built from default script in this repo)
web server was Nginx but I rebuilt with Apache and got the same problem. No relevant errors in the /var/log/nginx/errors.log or /var/log/apache2/errors.log

This error in http://drupalvm.dev/admin/reports/status:  

> Error File system 	Not writable
The directory sites/default/files/config_p8nsQifgeqqKvzghauPJ3JkRt-l163TizMNfGOE-Fs3Qtctz2VIdznMXW7csXxmYLlZpvziUfQ/sync does not exist. You may need to set the correct directory at the file system settings page or change the current directory's permissions so that it is writable.

The directory has these permissions:

> drwxrwxr-x 1 vagrant vagrant 4096 May  5 09:02 config_p8nsQifgeqqKvzghauPJ3JkRt-l163TizMNfGOE-Fs3Qtctz2VIdznMXW7csXxmYLlZpvziUfQ/

The owner vagrant but www-data is writing to the /tmp directory.

I'm not sure whether it's significant but Chef is throwing errors

> [2016-05-06T13:22:38+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
Chef Client failed. 0 resources updated
[2016-05-06T13:22:38+00:00] ERROR: I cannot read /etc/chef/validation.pem, which you told me to use to sign requests!
[2016-05-06T13:22:39+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)

the only file in  /etc/chef/ is client.rb and that is 0 bytes long

**Comment by oxyc** [comment]
Hmm, how did you get Chef there? Drupal VM doesn't use or install Chef.

**Comment by whanrott** [comment]
chef > yes, it's odd. I didn't stray outside the build script except to enable/disable some of the optional bits. Chef isn't installed on my local machine, so it isn't a problem with the host.

I've deleted the entire VM. I'm now rebuilding from the Latest commit ([fba9a18](https://github.com/geerlingguy/drupal-vm/commit/fba9a188f3e891622d78a10d8554aa9286425086)). I'll let you know what happens.

**Comment by whanrott** [comment]
@oxyc the rebuild worked but I'm not sure why. I'd had difficulty with NFS on Linux. I've a suspicion that disabling that may have caused a problem. I was also running vagrant plugin vbguest which rebuilt the kernel. It left a number of updates to apply. I wonder whether chef went in as a dependency of that? I can't get back to that state because I destroyed the VM in which it was done. Thanks for your help.

**Comment by oxyc** [comment]
No problem, glad you got it working.
