### ISSUE TITLE
the role 'franklinkim.newrelic' was not found

### ISSUE THREAD

**Issue by tashbaugh** [geerlingguy/drupal-vm#594]
Hi,

I cloned the DrupalVM project today and during vagrant up I received the following error:

>MacBookPro-TylerAshbaugh:DrupalVM tyler.ashbaugh$ vagrant up
> Bringing machine 'drupalvm' up with 'virtualbox' provider...
> ==> drupalvm: Checking if box 'geerlingguy/ubuntu1404' is up to date...
> ==> drupalvm: VirtualBox VM is already running.
> MacBookPro-TylerAshbaugh:DrupalVM tyler.ashbaugh$ sudo nano /private/etc/hosts
> MacBookPro-TylerAshbaugh:DrupalVM tyler.ashbaugh$ vagrant provision
> ==> drupalvm: Running provisioner: ansible...
>     drupalvm: Running ansible-playbook...

> ERROR! the role 'franklinkim.newrelic' was not found in /Users/tyler.ashbaugh/Sites/utilities/DrupalVM/provisioning/roles:/Users/tyler.ashbaugh/Sites/utilities/DrupalVM/provisioning:/usr/local/etc/ansible/roles
> 
> The error appears to have been in '/Users/tyler.ashbaugh/Sites/utilities/DrupalVM/provisioning/playbook.yml': line 46, column 7, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
>     - { role: geerlingguy.mailhog, when: '"mailhog" in installed_extras' }
>     - { role: franklinkim.newrelic, when: '"newrelic" in installed_extras' }
>       ^ here
> 
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

**Comment by oxyc** [comment]
This role was recently added and you have to install it locally:

```sh
sudo ansible-galaxy install -r provisioning/requirements.yml --force
```

**Comment by tashbaugh** [comment]
Thanks @oxyc for the quick reply!

If Ansible had not been installed on my host machine, would I have had to ssh into the VM and issue that command from inside of the VM?

**Comment by oxyc** [comment]
Ah yes, it's only done on the first provision unforunately

```sh
vagrant ssh
sudo ansible-galaxy install -r /vagrant/provisioning/requirements.yml --force
```

**Comment by oxyc** [comment]
@geerlingguy that's a bit awkward no? `ansible_local` will run it with `--force` it seems (https://www.vagrantup.com/docs/provisioning/ansible_common.html)

**Comment by geerlingguy** [comment]
@oxyc yeah, true... still waiting for Hashicorp to someday release Vagrant 1.8.2... it has about 8 fixes I'm waiting on now :(

But we could maybe add that in to the JJG-Ansible-Windows script for now, maybe?
