### ISSUE TITLE
Git clone from remote custom codebase during vm provision

### ISSUE THREAD

**Issue by richierampage** [geerlingguy/drupal-vm#595]
Is there a way to use a custom codebase for the Drupal install on provision by defining a remote git repo and branch? I have searched but can't find a solution. Thanks in advance.

**Comment by oxyc** [comment]
You can add a post [provision script](https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L229:L232), but that would run after the site install tasks.

Personally I have a one VM per project setup and integrate Drupal VM into every project repo we have at work. In each `config.yml` I've set `local_path` in `vagrant_synced_folders` to a relative folder within the repo.

**Comment by richierampage** [comment]
Thanks @oxyc I looked a the post provision script but as you say, will be run too late. Don't really want to integrate Drupalvm into project codebase would rather integrate codebase into drupalvm for local dev. I might look at a role to pull code from repo instead of drush makefile. Good to confirm that it's not possible right now. :-)

**Comment by oxyc** [comment]
There's been talk about fixing up the `geerlingguy.drupal` role and integrate it with Drupal VM. That role is a bit outdated but currently supports cloning from git, not sure exactly what @geerlingguy is planning for it in the future though.

https://github.com/geerlingguy/ansible-role-drupal/issues/18

@geerlingguy even if Drupal VM eventually supports cloning repos from git, it could still be a useful addition to add `pre_provisiong` scripts. That would help with this issue and probably other scenarios as well.

**Comment by geerlingguy** [comment]
@oxyc true... Can you open an issue requesting `pre_provision_scripts`?

And this is definitely one of the use cases I'm hoping `geerlingguy.drupal` will solve well when I get around to a full new version of it. That's well overdue at this point :P

**Comment by oxyc** [comment]
Sure #598
