### ISSUE TITLE
Add support for `pre_provision_scripts`

### ISSUE THREAD

**Issue by oxyc** [geerlingguy/drupal-vm#598]
I suppose it should be run after all the roles are installed, but before the custom tasks run. I assume most scenarios where this is useful is after the basics are already installed (git for example).

**Comment by geerlingguy** [comment]
@oxyc et all - please see #600 and let me know what you think about putting it pre-role-install or post-role-install.

With a caveat: At some point, the Drupal configuration/installation steps will be wrapped into the `geerlingguy.drupal` role, and that role will run with all the other roles...
