### ISSUE TITLE
Documentation search does not work

### ISSUE THREAD

**Issue by Soundvessel** [geerlingguy/drupal-vm#599]
Steps to replicate:
1. Go to http://docs.drupalvm.com/
2. Enter "git" in search input, hit enter, resulting page load claims there are no results

**Comment by oxyc** [comment]
Unfortunately this is an upstream :/, https://github.com/geerlingguy/drupal-vm/issues/572#issuecomment-213466063

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/pull/998
