### ISSUE TITLE
Cant bootstrap Drupal using Drush from host

### ISSUE THREAD

**Issue by mixplex** [geerlingguy/drupal-vm#60]
I have installed the Drupal-VM  - with a clone of the repo at: https://github.com/geerlingguy/drupal-vm   

I am using the box you provide in the example and did a clean vagrant install.  I first deleted from my host computer /etc/exports;  ~/.vagrant.d and the .vagrant file in the root directory of the vm.  I then built the vagrant box and updated it using ssh.

I cannot get into MySQL via SSH.  I get:  ERROR 1045 (28000): Access denied for user 'vagrant'@'localhost' (using password: NO)

I cannot bootstrap Drupal using Drush when I call Drush on my host machine.   I am able to install Drupal on the default address as well as the sub-domains.  I am able to turn modules on and off in the Drupal UI, but cannot use Drush from the host.  I can use Drush from inside the VM.

I also find that manually checking for updates inside Drupal takes a very long time compared to the actual server or other vagrant hosts I have used.

I don't know if these issues are related.  I have used Drush on my host before, not inside the client.  I have not added a a Drush configuration or alias file to the client.

**Comment by geerlingguy** [comment]
Thanks for the details! I'll hopefully get some more time to respond later (if nobody else does first); but first, please make sure you're glanced through the following Wiki page: [Use Drush with Drupal VM](https://github.com/geerlingguy/drupal-vm/wiki/Use-Drush-with-Drupal-VM).

**Comment by mixplex** [comment]
Thank you Jeff.  I will add the part about the remote host and user and
ssh-config to my aliases.drushrc.php file and try again.  Might have to
wait till tomorrow morning.

Thanks much.



On Mon, Mar 30, 2015 at 3:12 PM, Jeff Geerling <notifications@github.com>
wrote:

> Thanks for the details! I'll hopefully get some more time to respond later
> (if nobody else does first); but first, please make sure you're glanced
> through the following Wiki page: Use Drush with Drupal VM
> <https://github.com/geerlingguy/drupal-vm/wiki/Use-Drush-with-Drupal-VM>.
>
> --
> Reply to this email directly or view it on GitHub
> <https://github.com/geerlingguy/drupal-vm/issues/60#issuecomment-87795525>
> .
>



-- 
Neil Zusman
(607) 262-6583

**Comment by geerlingguy** [comment]
I'm going to close this issue and redirect attention to #55; after that issue is complete, Drush usage from the host to the VM should be much simpler!
