### ISSUE TITLE
'ansible_ssh_user' is undefined

### ISSUE THREAD

**Issue by theneonlobster** [geerlingguy/drupal-vm#602]
Running `vagrant up` on Windows machines and a Mac that doesn't have Ansible installed returns the following error:

TASK [geerlingguy.composer : Ensure composer directory exists.]
fatal: [localhost]: FAILED! => {"failed": true, "msg": "'ansible_ssh_user is' undefined"}

**Comment by geerlingguy** [comment]
I'm going to do a provision without ansible installed on my Mac and see if I can reproduce the issue.

**Comment by geerlingguy** [comment]
I can't reproduce this behavior, but I wonder if it might be a problem with the version of Drupal VM or something else related...

Can you log into the VM after it fails provisioning and run `ansible --version` and let me know what it outputs (should be 2.0.2).

Also, can you make sure the Drupal VM version is the latest? And maybe try destroying and rebuilding the VM.

**Comment by theneonlobster** [comment]
The problem seems to be related to using geerlingguy/ubuntu1204. First, I updated Drupal VM, but had the same problem. Once I updated the existing config.yml to use geerlingguy/ubuntu1404, the problem went away.

**Comment by geerlingguy** [comment]
Hmm... I will check it out as well. I don't know how much longer I'm going to be able to support 12.04, though—it's honestly like the IE7 of OSes to me, and I don't run it on any of my own servers any more, so I have little vested interest in supporting it :(

**Comment by theneonlobster** [comment]
Upgrading to 14.04 wasn't an issue, but it took a little while to debug. Hopefully this issue will point others towards the solution.
