### ISSUE TITLE
Vagrant up can't find 'geerlingguy.blackfire' role, and fails.

### ISSUE THREAD

**Issue by kirbpowell** [geerlingguy/drupal-vm#607]
I gave the issues queue a look over, but couldn't find anything quite like this. I installed drupal-vm without incident, but when I run `vagrant up` it gets as far as the ansible provisioning step before I get the following error:

```
==> supportcomm: Running provisioner: ansible...
    supportcomm: Running ansible-playbook...
ERROR! the role 'geerlingguy.blackfire' was not found in /Users/kirby.powell/supcom/drupal-vm/provisioning/roles:/Users/kirby.powell/supcom/drupal-vm/provisioning:/etc/ansible/roles

The error appears to have been in '/Users/kirby.powell/supcom/drupal-vm/provisioning/playbook.yml': line 47, column 7, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

    - { role: geerlingguy.php-xhprof, when: '"xhprof" in installed_extras' }
    - { role: geerlingguy.blackfire, when: '"blackfire" in installed_extras' }
      ^ here

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

I'm running Vagrant 1.8.1 and I just downloaded and installed drupal-vm today. Any ideas on what might be causing this?

**Comment by oxyc** [comment]
I think you need to install the ansible roles first, this particular role was added just 19h ago.

You can re-install all ansible roles with:

```
sudo ansible-galaxy install -r provisioning/requirements.yml --force
```

**Comment by geerlingguy** [comment]
Yep; after you run the command `oxyc` mentions, you should be good to go.

This will be even more optimized soon :)

**Comment by kirbpowell** [comment]
Yup, that fixed it. Thanks to both of you!

**Comment by geerlingguy** [comment]
Awesome, glad we (well, mostly @oxyc) could help!
