### ISSUE TITLE
Lock Ansible role versions to a specific release

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#608]
Since Ansible doesn't support a syntax like `3.*` or `3.x-stable`, the next best option for favoring stability over maintainability is to specify the version of each role in requirements.yml.

While there is a maintenance burden to doing this, I think the stability and formality will help reduce the number of issues opened up in the queue for people who update Drupal VM but don't update roles, because we can always automatically point people to the simple 'if you update drupal vm, run this command' documentation.

I'm testing this now, to make sure that specifying specific versions works like I think it will...

**Comment by geerlingguy** [comment]
Relates to / follows https://github.com/geerlingguy/drupal-vm/issues/505

**Comment by geerlingguy** [comment]
Added a fix for this—the other thing this will empower me to do is to do a major 'break-all-the-things' PHP role revision that will switch the default to PHP 7.0, drop support for PHP < 5.5, drop CentOS 6 and Ubuntu 12.04 support—all while still supporting any users who need those things by letting them continue to use the 2.x Drupal VM branch.

I don't know just how long the 2.x branch will continue to work, but with the roles locked down to these versions, I feel a _lot_ more comfortable literally _breaking all the things_ to trim a lot of the annoying Drupal VM fat that's accumulated!

![1400jf](https://cloud.githubusercontent.com/assets/481677/15202989/f1eecdba-17c4-11e6-85a6-ce88e92d870c.jpg)

**Comment by oxyc** [comment]
How do you feel about running the galaxy install step directly through Vagrant with the `ansible.galaxy_role_file`? That would remove another step from the quick start guide and people would never have missing roles after upgrading. The downside is provisioning will take a bit longer (maybe a way to turn it off?)

**Comment by geerlingguy** [comment]
> How do you feel about running the galaxy install step directly through Vagrant with the `ansible.galaxy_role_file`?

Makes sense to me—that's something that we could do now, without 1.8.2, right? But I might not want to make it default... maybe some way of having users enable it only if Drupal VM is updated... or maybe some sort of a lock file that could be used to indicate when that option needs to be set, then the lock file is deleted as part of the Vagrantfile/provision process... (I'm just thinking of how we could make it automatic but not waste an extra 5-10 min of time for every provisoning run).

**Comment by oxyc** [comment]
I opened a PR with some of my thoughts https://github.com/geerlingguy/drupal-vm/pull/611
