### ISSUE TITLE
Break all the things!

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#609]
Here are some things I'm going to do now that I'm committing to dropping some cruft and updating all the things—especially since 2.5.1 locks in role dependencies at specific versions:

  - [x] Switch all out-of-the-box defaults to assume PHP 7.0
  - [x] Drop all extensions that don't work with PHP 7.0 (or mark them 'experimental' until they do)
  - [x] Switch default OS to Ubuntu 16.04 LTS
  - [x] Remove any support / visible sign of PHP < 5.5
  - [x] Work on some of the other things that will help with local.config.yml etc.
  - [ ] ??? (TBD)

**Comment by geerlingguy** [comment]
I'm running through all the different addons to see what I can get working easily, what is partially-broken, and what just plain won't install. Surprisingly, 16.04 includes a working Memcached PHP extension!

**Comment by geerlingguy** [comment]
And php-redis. Nice! http://packages.ubuntu.com/xenial/php/php-redis

**Comment by geerlingguy** [comment]
Xdebug works with no changes required.

**Comment by geerlingguy** [comment]
Working on XHProf here: https://github.com/geerlingguy/ansible-role-php-xhprof/issues/14

**Comment by chumkui** [comment]
Have you already made changes re the PHP role then?  I have been building fine and suddenly today I get this:

==> dpsubsvm: TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
==> dpsubsvm: failed: [localhost] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', u'libpcre3-dev',
 u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'php7.0-xml', u'php7.0-mbstring', u'p
hp7.0-apcu']) => {"failed": true, "item": ["php7.0-common", "php7.0-cli", "php7.0-dev", "php7.0-fpm", "libpcre3-dev", "p
hp7.0-gd", "php7.0-curl", "php7.0-imap", "php7.0-json", "php7.0-opcache", "php7.0-xml", "php7.0-mbstring", "php7.0-apcu"
], "msg": "No package matching 'php7.0-common' is available"}
==> dpsubsvm:   to retry, use: --limit @/vagrant//provisioning/playbook.retry

Running under Windows 8.1 (yes Windows!), latest version of DrupalVM, latest version of Vagrant and VirtualBox (although I don't think it is anything to do with Vagrant or VB)

Problem is, it breaks everything downstream, including my own post provisioning playbook!

I took a look at the geerlingguy.php role and I can see see recent changes, but not proficient enough to work out what I can change to get it to run through (without removing the check) not sure what effect that would have further on.

**Comment by chumkui** [comment]
Sorry running under PHP5.6 as prod site uses that for the moment.

**Comment by oxyc** [comment]
To get back the previous versions of the roles you need the latest commit to Drupal VM.

Make sure you have these two commits:
https://github.com/geerlingguy/drupal-vm/commit/a04c0d0e8ef993832e4627bdf581f24efcade352
https://github.com/geerlingguy/drupal-vm/commit/4534ca8a250e7278cf0035ff2de33dfbc267c87c

Then run (note that `sudo` is not required anymore):
```
ansible-galaxy install -r provisioning/requirements.yml --force
```

Once you've done that it should work as before for you.

**Comment by chumkui** [comment]
Mmmm - thanks for that.  I am on Windows and therefore the provisioning is being done 'In VM'.  I'll update and take a look!

**Comment by oxyc** [comment]
I just realized! Sorry for my hasty response. I edited my previous comment with a third commit which you need. Probably easiest just to update Drupal VM to the current master and everything should work.

With those 3 commits the following things will happen:
- The roles will never receive upgrades until you upgade your Drupal VM version.
- When you run `vagrant provision` all roles will be re-installed.

**Comment by chumkui** [comment]
Many thanks - I can confirm all is good.  

I was a too complacent anyway - I should have kept more of an eye on this from a config management point of view as it affects the team (of 3 of us).  Trouble is there are multiple dependencies - the DrupalVM repo, the role repos and also, the Box itself updates.

It is a huge time saver though, so the efforts are much appreciated!  It has made our lives much easier as we were managing individual build envs before. Nightmare

My longer term aim is to get this all working natively for HyperV for us Windies, rather than use VirtualBox - now there is a challenge...

Thanks again guys

**Comment by oxyc** [comment]
Glad you solved it!

Good news it that from now on all versions are locked in. So unless you upgrade Drupal VM things shouldn't break. And once you do upgrade, you will receive the roles locked to that particular Drupal VM version.

**Comment by chumkui** [comment]
That is good news indeed.  You realise just how important these dev envs are when they break. I'll let you know how I get on with HyperV in the future :-)

**Comment by geerlingguy** [comment]
> My longer term aim is to get this all working natively for HyperV for us Windies, rather than use VirtualBox - now there is a challenge...

This is interesting... please let me know if there's anything I can do to help you work towards this goal, or if you find anything that can make Drupal VM potentially work inside HyperV more easily.

**Comment by chumkui** [comment]
Will do.  I think there are quite a few people that just use Virtual Box because of the effort, but I think it is worth a go.  I'll let you know for sure.  Thanks for a great project - it works really well for us and I suspect many others as well.

**Comment by condor616** [comment]
I get the following error after merged the latest commits: 
fatal: [condor616]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'php-redis' is available"}

I'm running Drupal VM on my mac. 
Have already installed all the requirements (with --force). 

Note: I'm still running php 5.6.

Thank you in advance for your help.

**Comment by geerlingguy** [comment]
For redis in 5.6, you need to install `php5-redis`—set `php_redis_package: php-redis` in config.yml. I'll update the docs.

**Comment by condor616** [comment]
Thank you for your quick reply. 
I've added the _php_redis_package: php-redis_ in my config.yaml file but the issue still exists. 

I've also added "php_redis_install_from_source == false" (to meet the condition in #32 [here](https://github.com/geerlingguy/ansible-role-php-redis/blob/master/tasks/main.yml#L27))....not sure this is needed.

Attaching the config.yaml file in case it helps.
[config.yml.zip](https://github.com/geerlingguy/drupal-vm/files/269290/config.yml.zip)

Thank you
