### ISSUE TITLE
How does one restart a failed run?

### ISSUE THREAD

**Issue by mikeohara** [geerlingguy/drupal-vm#61]
(OSX) I have a failed vagrant run, I have fixed the issue in question and wish to resume.

I see this: 

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/mike/playbook.retry

but I am not sure what to run ahead of the --limit switch. 

Thanks

**Comment by geerlingguy** [comment]
You don't necessarily need to do the 'retry'/'limit'—instead, just run `vagrant provision` and it will run it again and pick up where it left off.

**Comment by mikeohara** [comment]
ah makes much more sense, thanks.
