### ISSUE TITLE
Configuring Shorter Drush Aliases?

### ISSUE THREAD

**Issue by attheshow** [geerlingguy/drupal-vm#610]
Is there any way in the config.xml to adjust the aliases that are built for each hostname? I'd like to make them super-short so that I have to do less typing to interact with the site. It looks like I could manually edit the generated ~/.drush/drupalvm.aliases.drushrc.php file and tweak the auto-generated aliases, but I'm wondering if there's a way to have it work correctly during the build process. Thanks!

**Comment by oxyc** [comment]
Unfortunately this is not supported at the moment.

**Comment by attheshow** [comment]
I'm keeping a list of Drupal VM installation steps for me. For this particular issue I added the following terminal commands to shorten the aliases produced during the install. Just sharing for others.

`sed -i '.bak' "s/\$aliases\['localvm\.mysite\.com'\]/\$aliases\['SHORTNAME'\]/g" ~/.drush/drupalvm.aliases.drushrc.php`
`rm *.bak`
`mv ~/.drush/drupalvm.aliases.drushrc.php ~/.drush/aliases.drushrc.php`

The above code would produce an alias that looks like **@SHORTNAME**. Also be sure in the first line to replace the alias with the current alias name. In the third line I renamed the aliases file in order to shorten it even further and remove the "drupalvm." prefix on the alias.

**Comment by oxyc** [comment]
You can also add a `drush/aliases.drushrc.php` directory within your project and drush will use that. I have my aliases bundled with every repo. Here's where drush looks for alias files https://github.com/drush-ops/drush/blob/5a1328d6e9cb919a286e70360df159d1b4b15d3e/examples/example.aliases.drushrc.php#L43:L51
