### ISSUE TITLE
Drupal 8 AJAX error 200 and corrupted exports from VM but not Pantheon

### ISSUE THREAD

**Issue by Soundvessel** [geerlingguy/drupal-vm#612]
Front-end developer here so be gentile ;)

DrupalVM 2.5.0
Windows 10 Pro
Virtual Box 5.0.20
Vagrant 1.8.1

1. Installed new Drupal 8 site on Pantheon.
2. Git cloned to local directory and followed [Local Drupal codebase instructions](http://docs.drupalvm.com/en/latest/deployment/local-codebase/) from documentation, vagrant up!
3. Exported db from Pantheon and imported via Adminer

Base install D8 from Pantheon cloned to DrupalVM seemed to work fine until I tried any admin UI action that required AJAX (Views UI, using UI on single item Configuration export) which results in AJAX errors 200 in console. No issues with the original site in Pantheon. Nothing but core and standard admin theme is used.

The AJAX error is thrown from line `965` in `/core/misc/ajax.js?v=8.1.1` which is a `Handler for the form redirection error.`

```
Uncaught AjaxError: 
An AJAX HTTP error occurred.
HTTP Result Code: 200
Debugging information follows.
Path: /admin/config/development/configuration/single/export?ajax_form=1
StatusText: OK
ResponseText: ​[{"command":"settings","settings":{"ajaxPageState":{"theme":"seven","libraries":"classy\/base,classy\/messages,contextual\/drupal.contextual-links,contextual\/drupal.contextual-toolbar,core\/drupal.active-link,core\/html5shiv,core\/jquery.form,core\/jquery.form,core\/normalize,seven\/drupal.nav-tabs,seven\/global-styling,shortcut\/drupal.shortcut,toolbar\/toolbar,toolbar\/toolbar.escapeAdmin,tour\/tour,user\/drupal.user.icons","theme_token":"ZZV68Ks46yPjXRxbzGeSEwtexleLHeUaT84tP51At9I"},"ajax":{"edit-config-name--SvzGnFghLGE":{"callback":"::updateExport","wrapper":"edit-export-wrapper","event":"change","url":"\/admin\/config\/development\/configuration\/single\/export?ajax_form=1\u0026_wrapper_format=drupal_ajax","dialogType":"ajax","submit":{"_triggering_element_name":"config_name"}}},"ajaxTrustedUrl":{"\/admin\/config\/development\/configuration\/single\/export?ajax_form=1\u0026_wrapper_format=drupal_ajax":true},"pluralDelimiter":"\u0003","user":{"uid":"1","permissionsHash":"ab2b69806bce8a3c2de5c7449fc0c4ae34dca4b1273db41c5ea504db13d8918e"}},"merge":true},{"command":"update_build_id","old":"form-lAJxQiTZfriaW-hVsk33J9PtdfmLw1Frguh551gzkRQ","new":"form-EU8FnyTdvz_F9piQxkyCowLXtjxZ2jErU3SF4Dvvne4"},{"command":"insert","method":null,"selector":null,"data":"\u003Cdiv id=\u0022edit-config-type-wrapper\u0022\u003E\u003Cdiv class=\u0022js-form-item form-item js-form-type-select form-type-select js-form-item-config-name form-item-config-name\u0022\u003E\n      \u003Clabel for=\u0022edit-config-name--SvzGnFghLGE\u0022\u003EConfiguration name\u003C\/label\u003E\n        \u003Cselect data-drupal-selector=\u0022edit-config-name\u0022 id=\u0022edit-config-name--SvzGnFghLGE\u0022 name=\u0022config_name\u0022 class=\u0022form-select\u0022\u003E\u003Coption value=\u0022\u0022\u003E- Select -\u003C\/option\u003E\u003Coption value=\u0022comment_publish_action\u0022\u003EPublish comment (comment_publish_action)\u003C\/option\u003E\u003Coption value=\u0022comment_save_action\u0022\u003ESave comment (comment_save_action)\u003C\/option\u003E\u003Coption value=\u0022comment_unpublish_action\u0022\u003EUnpublish comment (comment_unpublish_action)\u003C\/option\u003E\u003Coption value=\u0022node_delete_action\u0022\u003EDelete content (node_delete_action)\u003C\/option\u003E\u003Coption value=\u0022node_make_sticky_action\u0022\u003EMake content sticky (node_make_sticky_action)\u003C\/option\u003E\u003Coption value=\u0022node_make_unsticky_action\u0022\u003EMake content unsticky (node_make_unsticky_action)\u003C\/option\u003E\u003Coption value=\u0022node_promote_action\u0022\u003EPromote content to front page (node_promote_action)\u003C\/option\u003E\u003Coption value=\u0022node_publish_action\u0022\u003EPublish content (node_publish_action)\u003C\/option\u003E\u003Coption value=\u0022node_save_action\u0022\u003ESave content (node_save_action)\u003C\/option\u003E\u003Coption value=\u0022node_unpromote_action\u0022\u003ERemove content from front page (node_unpromote_action)\u003C\/option\u003E\u003Coption value=\u0022node_unpublish_action\u0022\u003EUnpublish content (node_unpublish_action)\u003C\/option\u003E\u003Coption value=\u0022user_add_role_action.administrator\u0022\u003EAdd the Administrator role to the selected users (user_add_role_action.administrator)\u003C\/option\u003E\u003Coption value=\u0022user_block_user_action\u0022\u003EBlock the selected user(s) (user_block_user_action)\u003C\/option\u003E\u003Coption value=\u0022user_cancel_user_action\u0022\u003ECancel the selected user account(s) (user_cancel_user_action)\u003C\/option\u003E\u003Coption value=\u0022user_remove_role_action.administrator\u0022\u003ERemove the Administrator role from the selected users (user_remove_role_action.administrator)\u003C\/option\u003E\u003Coption value=\u0022user_unblock_user_action\u0022\u003EUnblock the selected user(s) (user_unblock_user_action)\u003C\/option\u003E\u003C\/select\u003E\n        \u003C\/div\u003E\n\u003C\/div\u003E","settings":null},{"command":"insert","method":"prepend","selector":null,"data":"\n","settings":null}]
```

In addition to the AJAX errors when I used the full archive export option in admin from Configuration synchronization it produced an apache error in pimpmylog `AH01071: Got error 'PHP message: Uncaught PHP Exception Exception: "Unable to open in write mode '/var/www/tmp/config.tar.gz'" at /var/www/utla/core/lib/Drupal/Core/Archiver/ArchiveTar.php line 785
'`. I ssh'd into Vagrant and `sudo chmod 777` the `/var/www/tmp` directory which I hoped would fix the issue but instead now it completes without error but the tar file given downloaded can not be opened by 7zip. Export feature and tar file from the site on Pantheon work file. The `config.tar.gz` file produced in `/tmp` in the DrupalVM server is also fine.

Any insight to what may be causing this or how to pin point?

**Comment by geerlingguy** [comment]
> Front-end developer here so be gentile ;)

No worries!

One thing to take a look at: does the admin/reports/status page (status report) show any warnings/errors? It sounds like it could be a files directory or general filesystem permissions issue.

**Comment by Soundvessel** [comment]
Nothing that I thought would cause the issues I am seeing. They are mostly related to security recommendations that I thought could be ignored on local development. We lock everything tight on Patheon before deployment.

- Warning - Configuration files: Not protected
- Error - Public files directory: Not fully protected
- Error - Rebuild access: Enabled
- Error - Trusted Host Settings: Not enabled

**Comment by oxyc** [comment]
Is it a completely new site? Meaning no sensitive data? If it's not a security issue, you could email me (public@oxy.fi) the tar file and I can take a look to see if there are any clues as to why it's corrupt.

**Comment by Soundvessel** [comment]
Thanks for the help @oxyc . You should have in your email from me now. Attached is both the working archive produced from the Pantheon dev site and the non-working archive from my local Drupal VM instance.

**Comment by oxyc** [comment]
Well it's definitely a very minor corruption. It seems the first 3 bytes (`e2 80 8b`) are invalid, if I simply remove them I can extract all but 1 file from the archive.

As it's such a minor corruption, maybe worth deleting everything and trying again. Otherwise I'm not sure what could be the cause for it. I think we need some greater minds on it. For fun I'll email you back the mostly recovered file.

**Comment by Soundvessel** [comment]
Thanks @oxyc. If I had to guess I think that same corruption is why all AJAX requests error out. HTTP Result Code: 200 means the request succeeds but it is the corruption preventing the data from then being parsed and used for views UI, conditional select fields with exporting single configurations from configurations sync etc... Perhaps something server side screwing up json requests?

**Comment by oxyc** [comment]
Yes you are probably correct. I looked it up and `e2 80 8b` is a [zero width space](http://www.fileformat.info/info/unicode/char/200B/index.htm).

**Comment by oxyc** [comment]
If you sign into the VM `vagrant ssh`, and run
```
grep -rl $'\xE2\x80\x8B' /var/www/ulta
```

Which files does it list?

**Comment by Soundvessel** [comment]
nada unless I did something wrong here

![terminal](https://cloud.githubusercontent.com/assets/3443548/15234363/aa4a53d4-1865-11e6-931e-ca0f297e182d.png)

**Comment by oxyc** [comment]
Whops `/var/www/ulta`. Point is to run it where you have `drupal_core_path` set.

**Comment by Soundvessel** [comment]
I have to leave for a bit but from these results I am willing to bet a copy/paste into my `settings.local.php` might be the culprit :)

![terminal](https://cloud.githubusercontent.com/assets/3443548/15234405/587ab822-1866-11e6-9232-d0034be754ba.png)

**Comment by oxyc** [comment]
Your `settings.local.php` seem to have some encoding issues. This can happen when you open a UNIX file on Windows. Could you try and re-save it with UNIX line-endings and UTF8 in your editor? Also verify that the grep command you just ran doesn't detect the file.

**Comment by oxyc** [comment]
You could also run the following within the VM:

```sh
sed -i 's/\xe2\x80\x8b//g' /var/www/utla/sites/default/settings.local.php
```

But for the problem not to come up again you should set your editor to always use UNIX line endings and UTF-8 encoding.

**Comment by Soundvessel** [comment]
Yup it was an extra space before the `<?php` in `settings.local.php`. Now I wonder if I should of gotten PHPStorm over Webstorm for the PHP debugging. Thanks a ton for helping me track this down :)

**Comment by oxyc** [comment]
Glad I could help, it was a fun debugging challenge :)
