### ISSUE TITLE
Fix all the things!

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#616]
Well, at least the small things that I had to leave slightly-disjointed after #609:

  - [x] Need to re-enable the XHProf integration test in `.travis.yml`
  - [x] Need to pass through docs and make sure everything is updated to reflect 
  - [x] Need to update www.drupalvm.com with correct/latest information
  - [x] Need to switch main installation Travis tests to use Ubuntu 16.04 instead of 14.04 Docker.

**Comment by oxyc** [comment]
Do you have an ETA on the next release? I need to upgrade a bunch of VMs and would rather wait until 3.0 unless it's far off.

**Comment by geerlingguy** [comment]
++ to @oxyc for helping push this through!

**Comment by geerlingguy** [comment]
@oxyc - As far as the next release goes, I was hoping to do it yesterday or today, but my energy level is down to like -5... so it will hopefully be either tomorrow by EOD, or very early in the week.

Thank you SO much for your help with all these last-minute hurdles! The last two things I want to get in are tagged in the 3.0.0 milestone, and then I want to work on one more test run pass on my Macs and PCs to make sure the 3.0.0 release is as smooth as possible.
