### ISSUE TITLE
Ansible error

### ISSUE THREAD

**Issue by mooru** [geerlingguy/drupal-vm#627]
I get this error when i run vagrant provision 

ERROR! Unexpected Exception: [Errno 13] Permission denied: '/Users/martinoru/.ansible_galaxy'
to see the full traceback, use -vvv

**Comment by oxyc** [comment]
Run `sudo chown martinoru:staff /Users/martinoru/.ansible_galaxy` and then re-run the provision step.

**Comment by mooru** [comment]
Getting this error


TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [drupalvm] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', u'libpcre3-dev', u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'php7.0-xml', u'php7.0-mbstring', u'php-apcu']) => {"failed": true, "item": ["php7.0-common", "php7.0-cli", "php7.0-dev", "php7.0-fpm", "libpcre3-dev", "php7.0-gd", "php7.0-curl", "php7.0-imap", "php7.0-json", "php7.0-opcache", "php7.0-xml", "php7.0-mbstring", "php-apcu"], "msg": "No package matching 'php7.0-common' is available"}

**Comment by oxyc** [comment]
You will need to update your Drupal VM version. I gave some instructions in my comment on this issue https://github.com/geerlingguy/drupal-vm/issues/621#issuecomment-219176988.

**Comment by geerlingguy** [comment]
@mooru - What @oxyc said is correct—also, you may want to download Drupal VM 2.5.1 and use it for the time being until 3.0.0 (or a later release) comes out. That will make sure your role dependencies (which can cause errors like the one you saw above) are locked in and don't change unless you want them to.

**Comment by mooru** [comment]
I am using version 2.5.1 but still getting tis error

**Comment by oxyc** [comment]
Did you run this step?

```sh
ansible-galaxy install -r provisioning/requirements.yml --force
```

**Comment by mooru** [comment]
It works but now when i run vagrant provision it gets stuck at

TASK [Install Drupal with drush.] **********************************************

**Comment by oxyc** [comment]
How long does it get stuck? Does it eventually fail or do you cancel it?

**Comment by mooru** [comment]
Stuck for Over 35 minutes. That's wierd

**Comment by mooru** [comment]
Solved. 
I had to do vagrant plugin install vagrant-auto_network 
For some reason it was making it not work

**Comment by oxyc** [comment]
Did you have `vagrant_ip: 0.0.0.0` in your `config.yml`?

**Comment by mooru** [comment]
No. I had to execute vagrant plugin install vagrant-auto_network to get it to work
