### ISSUE TITLE
Vagrant Automatically Changes Hosts File

### ISSUE THREAD

**Issue by alexfinnarn** [geerlingguy/drupal-vm#63]
I don't think this is a bug/issue and was just going to update the quick start guide text, but for me, I didn't have to do step #3 under the quick start guide. 

My hosts file had the "# Vagrant hostname and IP configuration." in config.yml after I ran "vagrant up".

Rather than updating the text to delete/modify step #3, I thought I'd post this issue in case the hosts file wasn't supposed to be automatically configured, although I think it is a normal thing Vagrant project do...sorry, I'm newer to working with Vagrant.  

If this is supposed to happen, then step #3 needs some rewording.

**Comment by geerlingguy** [comment]
@alexfinnarn - If you have the `vagrant-hostsupdater` plugin installed, it will automatically add and remove the hosts entries. Most people don't have this installed by default, so I wrote the instructions targeting a user who just installed a fresh copy of Vagrant :)
