### ISSUE TITLE
The following settings shouldn't exist: galaxy_role_file

### ISSUE THREAD

**Issue by minorscience** [geerlingguy/drupal-vm#634]
Testing latest commits. 

Receiving following error on vagrant up.

<code>
There are errors in the configuration of this machine. Please fix
the following errors and try again:

ansible provisioner: The following settings shouldn't exist: galaxy_role_file
</code>

I've force updated requirements. Not sure if this is a Vagrant issue?

**Comment by minorscience** [comment]
Never mind. Was a dot release behind on vagrant.

**Comment by mikecrittenden** [comment]
👍 Thanks, I hit this same issue. Vagrant upgrade fixed it.
