### ISSUE TITLE
Documentation for PHP 5.6 does not have php_fpm_pool_conf_path

### ISSUE THREAD

**Issue by rodrigoeg** [geerlingguy/drupal-vm#635]
I was trying to configure PHP 5.6 with the latest version of Drupal VM with the documentation provided: http://docs.drupalvm.com/en/latest/other/php-56/, but the the variable php_fpm_listen was not being applied. 
I was receiving this error after the VM provision:
```
[Mon May 16 20:02:20.907207 2016] [proxy:error] [pid 1381:tid 140614544914176] (111)Connection refused: AH00957: FCGI: attempt to connect to 127.0.0.1:9000 (127.0.0.1) failed
[Mon May 16 20:02:20.907584 2016] [proxy:error] [pid 1381:tid 140614544914176] AH00959: ap_proxy_connect_backend disabling worker for (127.0.0.1) for 60s
[Mon May 16 20:02:20.907893 2016] [proxy_fcgi:error] [pid 1381:tid 140614544914176] [client 192.168.88.1:64648] AH01079: failed to make connection to backend: 127.0.0.1, referer: http://dashboard.drupalvm.dev/
```

I have to add the following configuration for the "listen = 127.0.0.1:9000" to be applied in www.conf:
`php_fpm_pool_conf_path: "/etc/php5/fpm/pool.d/www.conf"`

**Comment by geerlingguy** [comment]
Fixed via #636.
