### ISSUE TITLE
Error during Drupal installation using Drush

### ISSUE THREAD

**Issue by subhojit777** [geerlingguy/drupal-vm#637]
I am having this error during Dupal installation using Drush.

> [warning] require(/var/www/drupalvm/drupal/vendor/autoload.php): failed to open stream: No such file or directory autoload.php
> PHP fatal error:  require() Failed  opening required '/var/www/drupalvm/drupal/vendor/autoload.php' (include _path='.:/usr/share/php') in /var/www/drupalvm/drupal/vendor/autoload.php on line 14
> [error] Drush command terminated abnormally  due to an unrecoverable error

I think this is due to https://www.drupal.org/node/2718229

**Comment by subhojit777** [comment]
#638

**Comment by subhojit777** [comment]
And yes this is for Drupal 8

**Comment by geerlingguy** [comment]
The errors in #638 will be tracked there; since they're not fatal (just annoying), and only occur on the CLI right now, it's on the backburner until 3.0.0 is released.
