### ISSUE TITLE
Redhat Provisioning failing with Centos7 + PHP 5.5

### ISSUE THREAD

**Issue by joelpittet** [geerlingguy/drupal-vm#647]
During provisioning it looks to be trying to use Debian some times and or defaults to PHP7. Then when checking PHP packages it fails when it can't find the PHP7 packages because it downloaded the correct PHP 5.5 ones...

Relevant config lines:
```
vagrant_box: geerlingguy/centos7
php_version: "5.5"

```
```
TASK [geerlingguy.php : include] ***********************************************
included: /Users/pittet/Boxes/drupal-vm/provisioning/roles/geerlingguy.php/tasks/setup-Debian.yml for drupalvm

TASK [geerlingguy.php : Update apt cache.] *************************************
ok: [drupalvm]

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [drupalvm] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', u'libpcre3-dev', u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'php7.0-xml', u'php7.0-mbstring', u'php-sqlite3', u'php-apcu']) => {"failed": true, "item": ["php7.0-common", "php7.0-cli", "php7.0-dev", "php7.0-fpm", "libpcre3-dev", "php7.0-gd", "php7.0-curl", "php7.0-imap", "php7.0-json", "php7.0-opcache", "php7.0-xml", "php7.0-mbstring", "php-sqlite3", "php-apcu"], "msg": "No package matching 'php7.0-common' is available"}
	to retry, use: --limit @/Users/pittet/Boxes/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=84   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by oxyc** [comment]
Just to make sure, you're not re-provisioning a box that was previously created with Debian? If you're switching the `vagrant_box` you need to re-create the box with `vagrant destroy -f` and `vagrant up`

If that's not the issue I'll see if can reproduce it. Which version of Drupal VM are you using?

https://github.com/geerlingguy/ansible-role-php/blob/master/tasks/main.yml#L42:L46

**Comment by joelpittet** [comment]
Oh maybe I did do that, though I thought I did the destroy (likely without the `-f` flag), can remember, but I did the destroy -f this time and got a different issue so. Closing this and will investigate that issue further.

`failed: [drupalvm] (item=[u'curl', u'python-pycurl', u'@development', u'unzip']) => {"failed": true, "item": ["curl", "python-pycurl", "@development", "unzip"], "msg": "Failure talking to yum: Cannot retrieve metalink for repository: epel/x86_64. Please verify its path and try again"}`
