### ISSUE TITLE
Ansible roles re-downloaded on each provision

### ISSUE THREAD

**Issue by opdavies** [geerlingguy/drupal-vm#655]
Since 3.0.0, the Ansible roles are being re-downloaded each time `vagrant provision` is run.

**Comment by oxyc** [comment]
It's a feature https://github.com/geerlingguy/drupal-vm/pull/611. My main reason for standing behind that commit was that we had suggested the `ansible-galaxy install` command ~29 times here in the issue queue. Also I believe that the common user _does_ want to re-install the roles whenever they re-provision the VM.

There's a fairly easy workaround for _power users_ though. Add a `Vagrantfile.local` with the following content:

```rb
# Disable the galaxy role re-installation during provisions.
config.vm.provisioners[0].config.galaxy_role_file = nil
```

@geerlingguy maybe this should be brought up for more debate though? Or we could add some way to toggle it of. I still feel it should be the default for the common case though.

**Comment by opdavies** [comment]
OK, cool. I was just wondering if it was intentional or not.

I was assuming that it would download the roles once unless told to do so, sort of how `vagrant reload --provision` works, but I can see why it would be useful to automatically download them each time when provisioning to ensure that everyone has the latest specified versions.

**Comment by thom8** [comment]
If only there was an galaxy update option -- https://github.com/ansible/ansible/issues/6466

**Comment by danbohea** [comment]
https://github.com/ansible/galaxy-issues/issues/49

**Comment by thom8** [comment]
Nice! I ended up using ansible to install roles so it could be idempotent --
https://github.com/beetboxvm/beetbox/blob/master/provisioning/ansible/playbook-roles.yml

However, it also clones the roles from github in debug mode to make it easier to push PR's which would also be a nice feature for galaxy...

**Comment by geerlingguy** [comment]
Yeah, it's the lesser of two evils. An extra minute or two each provision by default, but a lot of extra issues not opened up in here. It's what the Vagrant Ansible (built in) provisioner does, and it's also what the `windows.sh` script does (in JJG-Ansible-Windows), so now it's consistent.

Power users (or people like me who provision all day long) can override, so it's not a huge issue.

It also helps boost my download counts :D https://galaxy.ansible.com/explore#/

**Comment by danbohea** [comment]
> It also helps boost my download counts :D

LOL
