### ISSUE TITLE
How to access ngrok traffic inspector from the host machine

### ISSUE THREAD

**Issue by tripper54** [geerlingguy/drupal-vm#656]
I'm trying to use https://ngrok.com to test an API, specifically to capture, inspect and replay requests via ngrok's built in web interface.

I installed ngrok via npm and it works great, except for the inspector interface.

The interface runs at localhost:4040 . From within the VM, I can curl http://127.0.0.1:4040 and see the HTML output of the inspector.

But when I try to access http://192.168.88.88:4040/ from my host machine, chrome says 192.168.88.88 refused to connect. 

I added port 4040 to firewall_allowed_tcp_ports , and reprovisioned. I also tried disabling ufw from within the vm , to no avail.

Can anyone help me to get this working?

**Comment by joestewart** [comment]
I think I had to add a line like this  in ~/.ngrok2/ngrok.yml
```
web_addr: 0.0.0.0:4040
```

**Comment by tripper54** [comment]
Thanks @joestewart , that did the trick. I'll add it to a post-provision script.

**Comment by felipsmartins** [comment]
@joestewart Thank you!!!

**Comment by sivanesh121** [comment]
![](http://602199ca.ngrok.io/Firefox_wallpaper.png)

**Comment by sivanesh121** [comment]
![](https://2e69c987.ngrok.io/image.jpg)
