### ISSUE TITLE
VirtualBox downloaded even though Parallels Desktop is installed

### ISSUE THREAD

**Issue by danbohea** [geerlingguy/drupal-vm#657]
Just gave 3.0.0 a whirl. The only provider I had pre-installed on my Mac was Parallels Desktop (already in use with Vagrant). On running `vagrant up` Drupal VM downloaded & installed VirtualBox which worked but was unnecessary.

**Comment by danbohea** [comment]
The plot thickens. Running the following:

```
vagrant up --provider parallels
```

results in:

```
Bringing machine 'drupalvm' up with 'parallels' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    drupalvm: Box Provider: parallels
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/ubuntu1604'
    drupalvm: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1604
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: geerlingguy/ubuntu1604
Address: https://atlas.hashicorp.com/geerlingguy/ubuntu1604
Requested provider: [:parallels]
```

**Comment by thom8** [comment]
The default base box doesn't currently have a parallels version -- https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1404

But it should work with the official ubuntu 14.04 box

**Comment by thom8** [comment]
Sorry it's now 16.04 and Ubuntu don't have a parallels box -- https://atlas.hashicorp.com/ubuntu/boxes/xenial64

**Comment by geerlingguy** [comment]
@danbohea - Yeah, I don't have Parallels, and there are generally fewer base boxes to choose from—you'll either have to use Ubuntu 14.04 (as listed in the comments in `config.yml`) or find a working Parallels 16.04 base box elsewhere. Since I don't have it, I can't build/host base boxes for it.

**Comment by danbohea** [comment]
Sorry, missed the comment in config.yml. That explains it, thanks :)

@geerlingguy Parallels feels way faster than VirtualBox in my limited experience with it. Consider grabbing a license. It also make OS X virtualisation comparatively easy.

**Comment by geerlingguy** [comment]
@danbohea - True, and since VMware basically fired it's desktop virtualization team, I may switch once VMware 8 becomes oldish.
