### ISSUE TITLE
PHP 5.6 doesn't install

### ISSUE THREAD

**Issue by heddn** [geerlingguy/drupal-vm#658]
Not sure why, but with something in a recent update I'm no longer able to designate to install PHP 5.6. I need that old version because I'm porting a D6 site and want to run the old site in one VM and the new site in another VM.

config.yml: http://sprunge.us/HJFE

**Comment by geerlingguy** [comment]
Did you completely rebuild the VM (or build from scratch?). Also, have you made all the changes listed on this docs page? http://docs.drupalvm.com/en/latest/other/php-56/

Where is it failing?

**Comment by heddn** [comment]
Brand new VM after a destroy. And yes, the config.yml has the php5.6 stuff in it. See attached config.yml

It is failing in that it always defaults to PHP 7.0 even though I ask it to install 5.6. And 7.0 doesn't work for D6. I also tried removing cachier from the mix. And that didn't seem to help anything.

**Comment by geerlingguy** [comment]
Hmm... Is this task being run?

https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/init-debian.yml#L31-L33

**Comment by heddn** [comment]
Yes: http://sprunge.us/WBEL

**Comment by oxyc** [comment]
You have a typo `php_packges`.

**Comment by heddn** [comment]
That fixed it. Sorry for the noise.

**Comment by oxyc** [comment]
No worries, I've been there! Glad you got it working.
