### ISSUE TITLE
Drush aliases not read from sites/all/drush/site-aliases/whatever.aliases.drushrc.php

### ISSUE THREAD

**Issue by danbohea** [geerlingguy/drupal-vm#661]
Drush aliases stored in the project at sites/all/drush/site-aliases/whatever.aliases.drushrc.php should get automatically picked up by Drush but they don't. It doesn't appear to be an issue with Drush itself as this is working fine in Vlad with Drush 8.1.0.

Tested with Drupal VM 3.0.0, drush `master`, `8.x`, & `8.1.0`. Setting `configure_local_drush_aliases` to `true` or `false` makes no difference.

**Comment by danbohea** [comment]
Just tested storing an aliases file at drush/site-aliases/whatever.aliases.drushrc.php too and that also doesn't work. From the sound of [this comment](https://github.com/geerlingguy/drupal-vm/issues/610#issuecomment-218811420) that did work very recently.

**Comment by oxyc** [comment]
What directory are you running the drush command from? Are you using the default structure of:

```
.
├── Vagrantfile
├── config.yml
├── docroot
│   ├── index.php
│   ├── sites/all/drush/site-aliases/whatever.aliases.drushrc.php
```

**Comment by danbohea** [comment]
Currently, the structure I'm using looks more like:

```
.
├── docroot
│   ├── index.php
│   ├── sites/all/drush/site-aliases/whatever.aliases.drushrc.php
│   └── other D7 project stuff...
└── drupal-vm
    ├── Vagrantfile
    ├── config.yml
    ├── provisioning
    └── other Drupal VM repo stuff...
```

- `local_path` is configured with the full path to that docroot location.
- `destination` has been left as the default value `/var/www/drupalvm`.
- I'm testing this by running `drush sa` once I've SSHd into the guest so the path would be /home/vagrant.
- I've just noticed that if I try to `cd` to /var/www/drupalvm the shell just hangs - not sure if related but doesn't seem right.

**Comment by oxyc** [comment]
If you use site specific aliases they are only available within that project dir. So you can only see them if you `cd /var/www/drupalvm/docroot/`

**Comment by danbohea** [comment]
That would explain it, I wasn't aware of that restriction and I'm likely too used to Vlad cd-ing me into the web root as soon as I ssh into the guest.

Now I just need to figure out why `cd /var/www/drupalvm/docroot/` hangs...

**Comment by danbohea** [comment]
So I re-provisioned and the shell no longer hangs when I try to `cd` any deeper than `/var/`. Now that I can finally `cd` to /var/www/drupalvm/docroot/ I can confirm that my site aliases *are* indeed available when I run `drush sa` - no need for a .drush-wrapper script as mentioned above.

**Comment by oxyc** [comment]
Glad you got it working! The wrapper is only needed if you want to issue drush commands outside of `docroot/`.

**Comment by danbohea** [comment]
Aaah, gotcha now. Thanks for your help :)
