### ISSUE TITLE
How to add your own ansible roles, tasks and other "the right way"

### ISSUE THREAD

**Issue by timwood** [geerlingguy/drupal-vm#666]
Is there documentation I may have missed which explains how to add other ansible roles, tasks (or other thing...sorry I'm not very familiar with ansible) without directly editing the DrupalVM playbook.yml? I would like to add one I found for [ClamAV](https://github.com/verygood-ops/verygood.clamav). I found [this documentation](https://github.com/geerlingguy/drupal-vm/blob/master/docs/other/overriding-configurations.md) for locally overriding config.yml and the Vagrantfile, but wasn't sure if or how to add this role through those two local override options. 

Thanks!

**Comment by geerlingguy** [comment]
So far we have http://docs.drupalvm.com/en/latest/extras/scripts/ — it explains how to add shell scripts and Ansible task files to run before/after the main setup is done... but as of this time there's no way to inject additional _roles_ into Drupal VM...

**Comment by oxyc** [comment]
Should we add `local.requirements.yml`? :) It could also be useful if something is fixed upstream and Drupal VM still hasn't updated the version.

At the moment JJG-Ansible-Windows doesn't support a custom requirements path, so maybe wait until Vagrant 1.8.2 comes out (I'm still hopeful).

**Comment by timwood** [comment]
Thanks for getting back so quick @geerlingguy! Any examples of a script that calls and runs an additional Ansible role inside the VM?

Also, the pre_provision_tasks_dir and post_provision_tasks_dir config options aren't in the example.config.yml that shipped with 3.0, should they be and left empty (with an example) like the post/pre_provision_scripts options?

**Comment by thom8** [comment]
@timwood currently ansible doesn't allow running a role from within an included task, so it would need be to referenced by the playbook -- https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/playbook.yml#L41

You could potentially create a new provisioning task in your `Vagrantfile.local` that calls a custom playbook referencing this role, but there couldn't be any interdependencies.

Otherwise you could extract the tasks from the role to a directory referenced by `post/pre_provision_tasks_dir`- https://github.com/verygood-ops/verygood.clamav/blob/master/tasks/main.yml

**Comment by danbohea** [comment]
Theoretically `pre_provision_scripts` and/or `post_provision_scripts` could point to further playbooks which in turn could run any roles. I guess it depends on how much access you need to values within config.yml or any of the defaults set within provisioning/roles.

In Vlad we had the Vagrantfile run a secondary "custom" playbook for this purpose but only if it existed at the user-configured path.

**Comment by timwood** [comment]
Thanks for the advice, everyone. I've extracted the task from the role, tweaked it for our needs and referenced it via `post_provision_tasks_dir`.

@geerlingguy Should a separate task be opened for future improvement to accomplish this with some ".local" override way? Also, should a separate task be opened to add a comment and example to example.config.yml for `pre/post_provision_tasks_dir`?

**Comment by thom8** [comment]
@danbohea can you provide an example of how you could call another playbook from within a playbook?

**Comment by danbohea** [comment]
> can you provide an example of how you could call another playbook from within a playbook?

@thom8 Sorry, I can't. In my previous comment I was talking about optionally calling a further playbook from the *Vagrantfile* (but first testing to see if it exists where it's supposed to or I think it fails).

**Comment by geerlingguy** [comment]
@danbohea - That could work; basically add an additional provisioner iff a specific file exists (or var is set). Technically this could be done via a `Vagrantfile.local`, and maybe it's enough to just add documentation for how to do this (e.g. Add another provisioner inside your own `Vagrantfile.local` that is an Ansible playbook calling its own roles).

**Comment by geerlingguy** [comment]
Fixed via above PR.
