### ISSUE TITLE
Windows synched folders

### ISSUE THREAD

**Issue by tgroff** [geerlingguy/drupal-vm#67]
Hi Jeff, I have been using drupal-vm for a few weeks now with great success, I can't tell you how much time this has saved me in spinning up quick dev sites for testing patches, debugging, etc! I wanted to make one suggestion about Windows shared folders, perhaps a documentation update in `example.config.yml` for Windows users?

I have had no problems with Windows + Virtualbox native file sharing, it has been very fast and reliable. The only thing I have changed for file sharing on Windows is the `- local_path: ` on line 12 of `config.yml`. For Windows it works best to create a new system folder within the drupal-vm folder with your preferred name such as `docroot` and change the config to:

`  - local_path: docroot`

This way the VM happily puts the `html` and `drupal` folders and files in the newly created `V:\drupal-vm\docroot\` and shares the directory with vboxfs! That's the only tweak I've had to make to get everything running smoothly on Windows 7 x64. Thanks!

[updated] I just realized I don't actually have to create the `docroot` first, it seems `vagrant up` will create the folder for me! :+1:

**Comment by geerlingguy** [comment]
I've added docs in https://github.com/geerlingguy/drupal-vm/wiki/Synced-Folders, and will also be committing a small tweak to the yaml file's documentation about this (and some other file sync troubleshooting tips).
