### ISSUE TITLE
Setting Correct Timezone on New Machine

### ISSUE THREAD

**Issue by attheshow** [geerlingguy/drupal-vm#670]
Is there any way to set the timezone for the new machine that's being built from the config.yml file? It looks like mine was set to UTC by default.

**Comment by geerlingguy** [comment]
I don't have the `geerlingguy.ntp` role added to Drupal VM at this time, so the default remains UTC... however, you could add a script or Ansible task file that updates the timezone like so: https://github.com/geerlingguy/ansible-role-ntp/blob/master/tasks/main.yml#L5-L10

See this doc for help adding scripts or task files to run pre/post provisioning: http://docs.drupalvm.com/en/latest/extras/scripts/

**Comment by attheshow** [comment]
I'm still having issues with this on my VM. Every day I log into it the timezone is way off. Not sure what's going on. I've tried installing NTP using apt-get install ntp but today it says "Wed Jul 20 18:27:41 EDT 2016". It's currently "Wed Jul 20 10:26:41 EDT 2016". I'm not sure why it keeps changing the time after I manually correct it. Any ideas?

**Comment by attheshow** [comment]
The main reason it's a problem for me is that one of my primary sites handshakes with an API and has to send a timestamp. If the timestamp is off by more than a few minutes all of the API calls fail.

**Comment by attheshow** [comment]
I'm going to try adding the "virtualbox-guest-additions-iso" package to see if this helps at all.

**Comment by geerlingguy** [comment]
@attheshow - The guest additions should already be installed and running.

I'm wondering if there's some other timezone or networking issue on your local machine—I've just checked on two of my Macs, and with Ubuntu 14 and 16, and otherwise default configs, all the times are correct and in sync (I just leave all the VMs default to UTC, and in PHP I set a site timezone as needed).

**Comment by jimmyko** [comment]
The time in my VMs is not sync too. I noticed that it happens every time after I leave the VM running and close its lid before sleep.

**Comment by oxyc** [comment]
See https://github.com/geerlingguy/drupal-vm/issues/1097

**Comment by josephdpurcell** [comment]
Thanks @oxyc. I believe following https://github.com/geerlingguy/drupal-vm/issues/1097#issuecomment-271213478 has solved the issue for me.
