### ISSUE TITLE
drush sql-dump @alias | drush sql-cli @alias no longer works

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#671]
Cannot run this command to sync down a remote database anymore (Drupal VM 3.0.0). Here is the output:

```
drush sql-dump @yccyi.dev | drush sql-cli @local.yalecore
Unable to load class Drush\Sql\Sql                                                                                   [error]
Unable to load class Drush\Sql\Sql                                                                                   [error]
exception 'Drush\Sql\SqlException' with message 'Unable to find a matching SQL Class. Drush cannot find your database[error]
connection details.'
```

Looks like my vm is running Drush 9, the remote server has Drush 8 - if that is a factor.

Other commands, like `status` and `cc all`, work.

**Comment by oxyc** [comment]
If you run the commands separately which is it that fails? Could you then post the `drush sa` configurations for that alias.

```sh
drush sql-dump @yccyi.dev > foo.sql
cat foo.sql | drush sql-cli @local.yalecore

drush sa @whichever
```

**Comment by kevinquillen** [comment]
Output:

```
drush sql-dump @yccyi.dev > test.sql
sh: mysqldump: command not found
Database dump failed
```

**Comment by kevinquillen** [comment]
That was executed against an Acquia server, by the way.

**Comment by oxyc** [comment]
Seems `mysqldump` is not in the users `$PATH` on the remote. I've never tried using Acquia services so not sure what the setup should be.

**Comment by kevinquillen** [comment]
Thats odd... it worked the last time I did it. Granted, that might have been a few weeks or more.

**Comment by oxyc** [comment]
If you run `drush @yccyi.dev ssh`, is `mysqldump` available or can you find it somewhere?

**Comment by kevinquillen** [comment]
Output from that:

```
drush @yccyi.dev ssh
yccyi@srv-4399:/var/www/html/yccyi.dev/docroot$ mysqldump
Usage: mysqldump [OPTIONS] database [tables]
OR     mysqldump [OPTIONS] --databases [OPTIONS] DB1 [DB2 DB3...]
OR     mysqldump [OPTIONS] --all-databases [OPTIONS]
For more options, use mysqldump --help
```

**Comment by kevinquillen** [comment]
Weeeeeeeelp looks like it is time for me to eat lunch - I just realized my arguments are backwards from reading a previous comment.

Should be `drush @yccyi.dev sql-dump | drush @local sql-cli`

**Comment by oxyc** [comment]
Oh! Haha nice catch I entirely missed it as well.
