### ISSUE TITLE
Can't start vagrant

### ISSUE THREAD

**Issue by jmevalentin** [geerlingguy/drupal-vm#672]
My system crashed and upon rebooting, I tried to vagrant up this box. I was getting the message "No usable default provider could be found for your system", it wouldn't start and I found the Vagrant file was missing. I searched and found that vagrant init might fix it, but it didn't.  Other advice included upgrading Virtualbox and vagrant, which I did, but after running vagrant up again, I get the following:

`
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'base' could not be found. Attempting to find and install...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Box file was not detected as metadata. Adding it directly...
==> default: Adding box 'base' (v0) for provider: virtualbox
    default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

Couldn't open file /Library/WebServer/Documents/d8d.jv/base
`

Please advise on what I should do next, and thank you.

**Comment by jmevalentin** [comment]
I just downloaded the repo again to another directory and replaced missing files, seems to be fine now.

**Comment by Sagarmadu** [comment]
lol
