### ISSUE TITLE
Startup error 'sshd.yml does not exist'

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#674]
Site seems to be fine, but I get this every time I start up.

```
TASK [include] *****************************************************************
fatal: [yalecore]: FAILED! => {"failed": true, "reason": "the file_name '/Users/kevinquillen/Servers/yalecore/tools/drupalvm/provisioning/tasks/sshd.yml' does not exist, or is not readable"}
```

**Comment by geerlingguy** [comment]
Hmm... is that file present in your filesystem? It should be part of Drupal VM (for some time now):

https://github.com/geerlingguy/drupal-vm/blob/master/provisioning/tasks/sshd.yml

**Comment by kevinquillen** [comment]
Oddly enough it isn't there. I might have fudged the upgrade.

**Comment by kevinquillen** [comment]
Yep. The directory doesn't have all the files. Weird.

**Comment by geerlingguy** [comment]
(Assuming the problem is fixed :)
