### ISSUE TITLE
Remove PHP-FPM and use old plain CGI

### ISSUE THREAD

**Issue by condor616** [geerlingguy/drupal-vm#676]
Hello,
I'm working on a Drupal 7 project and I'm having some issue with the [Shield](https://www.drupal.org/project/shield) module. Seems like it doesn't work when using php-fpm.

Is there a way to provision the VM without FPM, but with the mod_php only?
Thank you in advance for your help and ... your VM rocks :)

**Comment by condor616** [comment]
I managed to solve it by remooving the ProxyMatch directive in the apache config var.
Hope this is the right way :)

**Comment by geerlingguy** [comment]
@condor616 - Depending on the version of Apache installed, OS, etc., just removing that directive and reprovisioning may switching things to `mod_php`, but the default/expected configuration is only using FPM at this point (for either Apache or Nginx, or any future webserver that we'll incorporate).

A lot of modules in Drupal-land assume only Apache/mod PHP for all webservers in the world, but there are a huge number of Nginx, IIS, Caddy, and Apache/FPM servers, so this smells like a bug with the Shield module to me ;)

Anyways, marking as closed for now.
