### ISSUE TITLE
Drush aliases not being created

### ISSUE THREAD

**Issue by richardrobinsonx** [geerlingguy/drupal-vm#677]
Hello!

I'm not sure what it is I'm doing wrong, but for some reason when I fire up the VM my Drush aliases are not being created on my host machine. I've ensured that **configure_local_drush_aliases** is set to **true**.

It says in the documentation that it checks if Drush is installed on the host, and I know it is. I've tried looking through the provisioning scripts to see where it checks, but couldn't find it. I've tried making various changes, destroying the VM, and brining it back up again with no luck

I'm not sure where to go and can't seem to get the aliases working on my own either. Here is what I've changed in my config.yml:

```
vagrant_hostname: MYSITE.dev 
vagrant_machine_name: MYSITE 
local_path: /Users/richardrobinson/projects/MYSITE
build_makefile: false
drupal_core_path: /var/www/drupalvm
```

I'm running Vagrant 1.8.1 on OSX 10.11.5.

Thanks!

**Comment by richardrobinsonx** [comment]
I just noticed something.

When I visited 192.168.88.88 it says this: 

> *Note: On Windows or when you don't have Ansible installed on your host, Drush aliases are only created inside the VM.

Do I just have to install Ansible on my host machine to get this working?

**Comment by oxyc** [comment]
Correct, currently it only works if you have it installed on your host machine.

**Comment by richardrobinsonx** [comment]
Awesome. So I need Ansible. I'll give that a whirl. Thank you very much!
