### ISSUE TITLE
Windows + Cygwin + Vagrant SSHFS

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#679]
WinNFS vagrant plugin does not seem to be getting rectified anytime soon. If you are on a team who has a mix of Windows and OSX host OSes, it is a nightmare getting the Windows people up and running under the same config.yml.

I updated to 3.0 in hopes of using local.config.yml to help those folks override the sync type as smb because nfs simply does not work (Win 7- 10, tried them each, debugged common 'fixes' and none of that worked either).

There appears to be another sync type on the block that can be used under Windows, OSX and Linux, sshfs:

- https://github.com/dustymabe/vagrant-sshfs

Windows users will need Cygwin with openssh (for sftp), git and a few other common terminal packages but these appear to be the minimum.

After swapping in 'sshfs' as the sync type in config.yml, vagrant booted up the VM without issue or error. Although, it didn't install Drupal or even download it, which may have been an error on my part just doing the bare minimum config to boot a VM.

The drawbacks to this can be similar to rsync, where if you generate or download files remotely (via drush) the host file system may not get them. Also, it seemed that directory changes did not seem to replicate for about 6-10 seconds.

Although, the advantage of working under any host OS without needing different config.yml is very appealing, and someone out there may want to be aware of this Windows option.

- https://fedoramagazine.org/vagrant-sharing-folders-vagrant-sshfs/

**Comment by oxyc** [comment]
Thanks! I was actually about to start looking into this as well so you saved me a lot of work. Can I ask why rsync isn't an option for you? I haven't tried it but just imagined it might've worked well.

**Comment by kevinquillen** [comment]
I tried rsync on my Mac as a test. It was kind of tedious to setup deployment/ftp in PHPStorm (auto deploy changes) and there were some weird things like the sites/default folder randomly disappearing due to file permissions. Also it got confusing when the sync went out of sync (like generating Feature changes or updating modules) when you are executing git from the host, who hasn't synced back the changes. 

I don't use Windows very often, but this was the least painless sync option I have tried without error so far. The SSHFS changes would just 'go' without any setup. I did not try the inverse (dl to VM, see on host), I should try that next.

**Comment by geerlingguy** [comment]
@kevinquillen - One note—the default configuration will work with a typical Windows computer as long as it _doesn't already have the winnfs_ plugin installed for Vagrant. If you take a typical PC and follow the quick start guide, Vagrant will just ignore the `nfs` setting for synced folders and the VM will boot as normal.

I typically tell developers to override with SMB on their own in a `local.config.yml` file for the shares, that way the team can standardize on NFS but individuals who want better speed (than native) on Windows can use SMB or rsync (with it's special limitations).

**Comment by kevinquillen** [comment]
Native share did not work on the Windows machine we tried at work. It fails on the dashboard steps, for some reason.

The only difference between my machine and the one at work is the users are lower level AD users where the permissions are likely very different than my admin level one at home, though, I can't pinpoint what that would be. It is very weird.

**Comment by geerlingguy** [comment]
@kevinquillen maybe try again—I've made a few tweaks to make sure all the different deployment/install scenarios work correctly on my Windows 10 laptop, and nothing (at this point at least) requires admin rights afaict.

**Comment by geerlingguy** [comment]
At this point, though, I don't think I would be adding any specific configs to Drupal VM to support this, since it's just another sync type... but I am open to someone writing up docs in the windows section or in the Syncing Folders section on how to set this up.

**Comment by geerlingguy** [comment]
I'm going to close this issue for now; if someone wants to do the testing, verification, etc. and post a PR with specific instructions for it, I'll consider merging that in, but it's not a priority for me at this point.
