### ISSUE TITLE
Error enabling sub-modules

### ISSUE THREAD

**Issue by tgroff** [geerlingguy/drupal-vm#68]
I have begun to customize my `drupal.yml` make file to add in the standard modules I like to have on every default site. I've even added a `drupal_disable_modules` task to get rid of the few modules I don't like (we're looking at you *overlay*! :) ). 

I'm wondering if I have the syntax wrong perhaps? I've tried the module list with CSV, and space separated, both work fine.  The problem I'm having is that this set of modules works fine, and enables properly on install:

```drupal_enable_modules: [ 'devel admin_menu module_filter' ]```

but this set of modules, specifically with `admin_menu_toolbar`, fails

```drupal_enable_modules: [ 'devel admin_menu module_filter admin_menu_toolbar' ]```

with the following errors. The only thing I can see that is different is that `admin_menu_toolbar` is a sub-module of `admin_menu`.

```
==> drupaldev: TASK: [Generate Drupal site with drush makefile.] *****************************
==> drupaldev: changed: [localhost]
==> drupaldev:
==> drupaldev: TASK: [Install Drupal (standard profile) with drush.] *************************
==> drupaldev: changed: [localhost]
==> drupaldev:
==> drupaldev: TASK: [Install configured modules with drush.] ********************************
==> drupaldev: failed: [localhost] => {"changed": true, "cmd": ["drush", "en", "-y", "devel", "admin_menu", "module_filter", "admin_menu_toolbar"], "delta": "0:00:05.507379", "end": "2015-04-08 05:56:29.088433", "rc": 1, "start": "2015-04-08 05:56:23.581054", "warnings": []}
==> drupaldev: stderr: admin_menu was not found.                                              [warning]
==> drupaldev: module_filter was not found.                                           [warning]
==> drupaldev: admin_menu_toolbar was not found.                                      [warning]
==> drupaldev: No release history was found for the requested project                   [error]
==> drupaldev: (admin_menu_toolbar).
==> drupaldev: The following projects provide some or all of the extensions not            [ok]
==> drupaldev: found:
==> drupaldev: admin_menu
==> drupaldev: module_filter
==> drupaldev: stdout: Would you like to download them? (y/n): y
==> drupaldev: Project admin_menu (7.x-3.0-rc5) downloaded to                         [success]
==> drupaldev: /var/www/drupal/sites/all/modules/contrib/admin_menu.
==> drupaldev: Project admin_menu contains 3 modules: admin_menu_toolbar, admin_devel, admin_menu.
==> drupaldev: Project module_filter (7.x-2.0) downloaded to                          [success]
==> drupaldev: /var/www/drupal/sites/all/modules/contrib/module_filter.
==> drupaldev:
==> drupaldev: FATAL: all hosts have already failed -- aborting
==> drupaldev:
==> drupaldev: PLAY RECAP ********************************************************************
==> drupaldev:            to retry, use: --limit @/root/playbook.retry
==> drupaldev:
==> drupaldev: localhost                  : ok=134  changed=7    unreachable=0    failed=1
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```

**Comment by geerlingguy** [comment]
@tgroff - The best way to get around that (since drush will spit out an error whenever you try enabling a submodule that's not yet present in the codebase—`drush en` isn't very intelligent about downloading extra dependencies) is to make sure you have all the modules you will need in your `make` file.

For example, for your site, you will probably want to set your `drupal.make.yml` file like so:

```yaml
---
api: 2
core: 7.x

projects:

  drupal:
    type: core
    version: 7.x

  devel: 1.x-dev
  admin_menu: 3.x-dev
  module_filter: 2.x-dev
```

Then, in `config.yml`, for the `drupal_enable_modules` variable:

```yaml
drupal_enable_modules: [ 'devel', 'admin_menu', 'module_filter', 'admin_menu_toolbar' ]
```

**Comment by tgroff** [comment]
Thanks! That did the trick! This is a D7 site I'm messing with. I am just now learning about `drupal.make.yml` as a make file, very cool that we can use yml with D7.  My `drupal.make.yml` was as such:

```
---
api: 2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core: "7.x"

defaults:
  projects:
    subdir: "contrib"

projects:

  drupal:
    type: "core"
    version: ~

  devel: "1.x-dev"
  module_filter: ~
  admin_menu: ~

```

... so it seems the `~` is what caused the problem. I thought `~` could be used to get the latest stable release... but as I see it now `admin_menu` has never had a stable D7 release!? It's still at `7.x-3.0-rc5`!. When I used version numbers as you suggested everything worked fine. Thanks!

**Comment by geerlingguy** [comment]
Yeah, `admin_menu` should add a stable release sometime :P
