### ISSUE TITLE
php7.0-common is not available

### ISSUE THREAD

**Issue by philippelabat** [geerlingguy/drupal-vm#680]
Hello,

I selected PHP 5.6 in my config.yml and i get the following on a fresh vagrant up

`TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [drupalvm] (item=[u'php7.0-common', u'php7.0-cli', u'php7.0-dev', u'php7.0-fpm', u'libpcre3-dev', u'php7.0-gd', u'php7.0-curl', u'php7.0-imap', u'php7.0-json', u'php7.0-opcache', u'php7.0-xml', u'php7.0-mbstring', u'php-sqlite3', u'php-apcu']) => {"failed": true, "item": ["php7.0-common", "php7.0-cli", "php7.0-dev", "php7.0-fpm", "libpcre3-dev", "php7.0-gd", "php7.0-curl", "php7.0-imap", "php7.0-json", "php7.0-opcache", "php7.0-xml", "php7.0-mbstring", "php-sqlite3", "php-apcu"], "msg": "No package matching 'php7.0-common' is available"}`

**Comment by philippelabat** [comment]
Closed after viewing this page, sorry: [](http://docs.drupalvm.com/en/latest/other/php-56/)

**Comment by attheshow** [comment]
Same issue here. Thanks for helping me find the solution by posting this!
