### ISSUE TITLE
Annoying Message /w Provisioners in Ubuntu 16.04: Inappropriate ioctl for device

### ISSUE THREAD

**Issue by ericpulvino** [geerlingguy/drupal-vm#681]
After doing some digging on this message that I had been seeing:

==> server1: Machine booted and ready!
==> server1: Checking for guest additions in VM...
==> server1: Setting hostname...
==> server1: Running provisioner: shell...
    server1: Running: inline script
==> server1: mesg: 
==> server1: ttyname failed
==> server1: : 
==> server1: Inappropriate ioctl for device

I determined it had a similar cause as Issue 1673 --> https://github.com/mitchellh/vagrant/issues/1673 and a similar potential fix. I've started adding this line to my Vagrantfiles. There may be security ramifications for this fix as it essentially removes a built-in protection and allows other users to write to a root terminal but that is not a concern for my simulations /w Vagrant.

`
    # Fixes "stdin: is not a tty" and "mesg: ttyname failed : Inappropriate ioctl for device"  messages --> https://github.com/mitchellh/vagrant/issues/1673
    device.vm.provision :shell , inline: "(grep -q 'mesg n' /root/.profile && sed -i '/mesg n/d' /root/.profile && echo 'Ignore the previous error, fixing this now...') || exit 0;"

`

Not sure if this is the right place to put this... but putting it here for google-able awareness.

**Comment by geerlingguy** [comment]
Since this is an upstream issue with Vagrant, and I'd rather not put fixes for specific providers/bugs/versions into Drupal VM, I'm going to close the issue, but thank you for posting it—we can point others to this issue when they notice the same errors.
