### ISSUE TITLE
Update acquia cloud overrides for PHP 5.6 support

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#682]
The Acquia Cloud overrides file needs to be updated to account for the new instructions for installing PHP 5.6 instead of 7.0 on Ubuntu 12.04: http://docs.drupalvm.com/en/latest/other/php-56/

**Comment by oxyc** [comment]
In my haste to _change all the things_, I updated this in an entirely unrelated PR hehe https://github.com/geerlingguy/drupal-vm/pull/648/commits/82b932ecdf3e7363f1894d13740384efa9800f34. I can remove that part from the PR if you fix it here.

**Comment by geerlingguy** [comment]
Fixed by merging the above PR.
