### ISSUE TITLE
Bad permission when attempting to ssh into vm

### ISSUE THREAD

**Issue by aangelinsf** [geerlingguy/drupal-vm#684]
I'm installing on a Windows 7 and the vm launches. Through Cygwin I am attempting to ssh with:
`vagrant ssh -- -v`
am receiving the following error:
```
Permissions 0644 for 'C:/Users/andang01/.vagrant.d/insecure_private_key' are too open.
It is recommended that your private key files are NOT accessible by others.
This private key will be ignored.
bad permissions: ignore key: C:/Users/andang01/.vagrant.d/insecure_private_key

```

I have used chmod 600 on the file but the 644 value doesn't change in the error message even though on the file system it shows just read and write for the file.

I can log in via the windows terminal (i.e. not Cygwin). It asks for the passphrase of insecure_private_key (leave blank) then the vagrant account password ("vagrant") and I get in fine.

Any suggestions?

**Comment by geerlingguy** [comment]
It seems like it could be a permissions issue with cygwin — see https://groups.google.com/forum/#!topic/vagrant-up/DRcr5gTLH9w

Have you tried running cygwin using admin mode and also trying to change ownership to 0400? I normally use Cmder now, but Cygwin still seems to work okay in most cases as well :/

**Comment by aangelinsf** [comment]
Ah, yes, someone else seems to be experiencing a similar quirk (chmod not actually helping):
"chmod from cygwin has no effect at all"

That's unfortunate. But at least Cmder and/or Putty is a backup.

**Comment by geerlingguy** [comment]
I'm going to close this as a 'strange windows bug with cygwin' for now... but please feel free to leave any more info that you can find about fixes/workarounds!
