### ISSUE TITLE
Drush alias not working

### ISSUE THREAD

**Issue by expressionstech** [geerlingguy/drupal-vm#686]
Help!

Not sure where to begin....

I recently upgraded to 1404 and my aliases no longer work. I am receiving the following error:

```
vagrant@drupalvm:~$ drush sql-sync @expressionstech.hoeningfh-dev @local.hoeningfh
The external command could not be executed due to an application error.
Illegal string offset 'site' backend.inc:1035
, code: 255)
The external command could not be executed due to an application error. 
Error: no database record could be found for source @expressionstech.hoeningfh-dev 
```

**Comment by expressionstech** [comment]
vagrant@drupalvm:~$ drush sql-sync @expressionstech.hoeningfh-dev @local.hoeningfh --debug
Starting Drush preflight. [0 sec, 2.75 MB]                                                                                                                                                            [preflight]
Cache HIT cid: 7.0.0-commandfiles-0-5dc4fbaf427bf807a5de99ccd303e8fb [0.01 sec, 2.82 MB]                                                                                                                  [debug]
Bootstrap to phase 0. [0.08 sec, 7.22 MB]                                                                                                                                                             [bootstrap]
Bootstrap to phase -1. [0.08 sec, 7.22 MB]                                                                                                                                                            [bootstrap]
Found command: sql-sync (commandfile=sqlsync) [0.08 sec, 7.23 MB]                                                                                                                                     [bootstrap]
Bootstrap to phase -1. [0.08 sec, 7.23 MB]                                                                                                                                                            [bootstrap]
Calling drush command init function: drush_sql_sync_init [0.09 sec, 7.24 MB]                                                                                                                          [bootstrap]
Using deprecated 'parent' element '@expressions' in 'local.hoeningfh'. [0.09 sec, 7.24 MB]                                                                                                                [debug]
Loaded alias @expressions from file /home/vagrant/.drush/local.aliases.drushrc.php [0.09 sec, 7.25 MB]                                                                                                   [notice]
Loaded alias @local.hoeningfh from file /home/vagrant/.drush/local.aliases.drushrc.php [0.09 sec, 7.25 MB]                                                                                               [notice]
Loaded alias @expressionstech.hoeningfh-dev from file /home/vagrant/.drush/expressionstech.aliases.drushrc.php [0.1 sec, 7.25 MB]                                                                        [notice]
Calling hook drush_sqlsync_sql_sync_validate [0.1 sec, 7.27 MB]                                                                                                                                           [debug]
Backend invoke: ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'env COLUMNS=209 drush7  --backend=2 --verbose --debug                                        [command]
--root=/var/www/html/expressionstech.dev/docroot --uri=hoeningfh  sql-conf   --all 2>&1' 2>&1 [0.1 sec, 7.28 MB]
ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'env COLUMNS=209 drush7  --backend=2 --verbose --debug --root=/var/www/html/expressionstech.dev/docroot        [notice]
--uri=hoeningfh  sql-conf   --all 2>&1' 2>&1 [0.11 sec, 7.29 MB]
The external command could not be executed due to an application error. [0.57 sec, 7.29 MB]                                                                                                           [error]
Illegal string offset 'site' backend.inc:1030 [0.57 sec, 7.29 MB]                                                                                                                                     [warning]
                                                                                                             [error]
, code: 255) [0.57 sec, 7.29 MB]
Backend invoke: /usr/bin/php /usr/local/share/drush/drush.php --php=/usr/bin/php  --backend=2 --verbose --debug --root=/var/www/docroot --uri=hoeningfh  sql-conf   --all 2>&1 [0.57 sec, 7.29 MB]      [command]
/usr/bin/php /usr/local/share/drush/drush.php --php=/usr/bin/php  --backend=2 --verbose --debug --root=/var/www/docroot --uri=hoeningfh  sql-conf   --all 2>&1 [0.57 sec, 7.3 MB]                        [notice]
Error: no database record could be found for source @expressionstech.hoeningfh-dev [0.74 sec, 7.31 MB]                                                                                                [error]
Returned from hook drush_sqlsync_sql_sync_validate [0.74 sec, 7.31 MB]                                                                                                                                    [debug]
Command dispatch complete [0.74 sec, 7.29 MB]

**Comment by geerlingguy** [comment]
Have you looked at this option? http://docs.drupalvm.com/en/latest/extras/drush/#using-sql-sync

**Comment by expressionstech** [comment]
Yes, not working. I currently have this set up on my macbook pro laptop which works fine.
1404
host drush version - 7.0.0
drupalvm drush version - 8.0-dev

My local and server alias files (~/.drush/local.aliases.drushrc.php, ~/.drush/expressionstech.aliases.drushrc.php) are both under the vagrant folder.

This all works fine.

I've created the same set up on my iMac with the following exception:
drupalvm drush version - 7.0.0. I've tried with 8.01 and master. same error occurs.

**Comment by oxyc** [comment]
Seems the problem is with the remote (acquia)

What does `drush @expressionstech.hoeningfh-dev status` say?

**Comment by expressionstech** [comment]
vagrant@drupalvm:~$ drush @expressionstech.hoeningfh-dev status
env: drush9: No such file or directory
vagrant@drupalvm:~$ drush sa
@drupalvm
@drupalvm.expressions.dev
@expressionstech
@expressionstech.hoeningfh-dev
@expressionstech.hoeningfh-prod
@expressionstech.hoeningfh-prod.livedev
@expressionstech.hoeningfh-stg
@expressionstech.hoeningfh-stg.livedev
@expressionstech.hoeningfh.livedev
@local
@local.expressions
@local.hoeningfh
@none
vagrant@drupalvm:~$

**Comment by oxyc** [comment]
Hups I had it in the wrong order :)

```
drush sa @expressionstech.hoeningfh-dev
```

Wonder why it complains about drush9.. Your earlier debug message said it was using drush7...

It's possible that drush can't find the path to the drush binary. Do you know the path or can you `ssh` into the server and check the path with `which drush7` and manually set that using `%drush-script` in your `expressionstech.aliases.drushrc.php` as per https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php#L328

**Comment by expressionstech** [comment]
I just did vagrant destroy -f, vagrant up after I changed the drush version back to master. It was on 7 when I started this thread...


vagrant@drupalvm:~$ drush @expressionstech.hoeningfh-dev ssh
expressionstech@srv-4287:/var/www/html/expressionstech.dev/docroot$ which drush
/usr/local/drush8/drush

My server alias file - 

<?php
// ********************************************************* Site hoeningfh---DEV
if (!isset($drush_major_version)) {
  $drush_version_components = explode('.', DRUSH_VERSION);
  $drush_major_version = $drush_version_components[0];
}

$aliases['hoeningfh-dev'] = array(
  'root' => '/var/www/html/expressionstech.dev/docroot',
  'ac-site' => 'expressionstech',
  'ac-env' => 'dev',
  'ac-realm' => 'devcloud',
  'uri' => 'hoeningfh',
  'remote-host' => 'srv-4287.devcloud.hosting.acquia.com',
  'remote-user' => 'expressionstech.dev',
  'path-aliases' => array(
    '%drush-script' => 'drush' . $drush_major_version,
  )
);
$aliases['hoeningfh.livedev'] = array(
  'parent' => '@acquia.hoeningfh-dev',
  'root' => '/mnt/gfs/expressionstech.dev/livedev/docroot',
);



and the local alias file:

<?php
$local_sites = '/var/www/docroot';
// ****************************************************acreedavisfh

// Expressions Local
$aliases[expressions] = array(
  'root' => $local_sites,
);

$aliases[hoeningfh] = array(
  'parent' => '@expressions',
  'uri' => 'hoeningfh',
  'path-aliases' => array(
    '%dump-dir' => $local_sites,
    '%files' => $local_sites . '/sites/hoeningfh/files',
  ),
);


This works fine on my laptop.

**Comment by oxyc** [comment]
From your debug output earlier

> Backend invoke: ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'env COLUMNS=209 drush7  --backend=2 --verbose --debug                                        [command]
--root=/var/www/html/expressionstech.dev/docroot --uri=hoeningfh  sql-conf   --all 2>&1' 2>&1 [0.1 sec, 7.28 MB]
ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'env COLUMNS=209 drush7  --backend=2 --verbose --debug --root=/var/www/html/expressionstech.dev/docroot        [notice]
--uri=hoeningfh  sql-conf   --all 2>&1' 2>&1 [0.11 sec, 7.29 MB]
The external command could not be executed due to an application error. [0.57 sec, 7.29 MB]                                                                                                           [error]
Illegal string offset 'site' backend.inc:1030 [0.57 sec, 7.29 MB]

This means the problem is somewhere between your host machine and the acquia site. It doesn't look like it's connecting through or to Drupal VM yet. That happens after the sql dump has completed.

https://github.com/drush-ops/drush/issues/496#issuecomment-43854434 suggests this message can happen when the drush script is not within the users path on the remote host (acquia).

I've given up on letting drush find the drush script manually myself. I always hardcode the path in my aliases as it's solved a lot of my headaches.

I havent used acquia servers but to me this looks fragile at minimum:

```
  'path-aliases' => array(
    '%drush-script' => 'drush' . $drush_major_version,
  )
```

What I would try is:

```
$ drush @expressionstech.hoeningfh-dev ssh

$ drush7 status
 Drupal version         :  7.43                                                                                                                                                      
 Site URI               :  expressionstech.hoeningfh-dev                                                                                                                                         
 PHP executable         :  /usr/bin/php                                                                                                                                              
 PHP configuration      :  /etc/php5/cli/php.ini                                                                                                                                     
 PHP OS                 :  Linux                                                                                                                                                     
 Drush script           :  <copy this path>
....
```

Copy the path for _Drush script_ and use that in the `%drush-script` setting so that it's absolute

```
  'path-aliases' => array(
    '%drush-script' => '/usr/local/drush' . $drush_major_version,
  )
```
Or something similar.

**Comment by oxyc** [comment]
Aah I just realized you are on your VM when you ran your commands, I assumed you were on your host machine. Sorry, I might have to revise my comments!

**Comment by oxyc** [comment]
Do any of these fail?

```
$ drush @expressionstech.hoeningfh-dev sql-conf
$ drush @expressionstech.hoeningfh-dev ssh 'drush7 sql-conf'
$ drush @expressionstech.hoeningfh-dev ssh 'drush sql-conf'

$ ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'drush7 --root=/var/www/html/expressionstech.dev/docroot --uri=hoeningfh sql-conf'
$ ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'drush --root=/var/www/html/expressionstech.dev/docroot --uri=hoeningfh sql-conf'
```

Don't post the output if it works obviously, only if it fails.

**Comment by expressionstech** [comment]
vagrant@drupalvm:~$ drush @expressionstech.hoeningfh-dev sql-conf
env: drush9: No such file or directory


vagrant@drupalvm:~$ drush @expressionstech.hoeningfh-dev ssh 'drush7 sql-conf'
exception 'Drush\Sql\SqlException' with message 'Unable to find a        [error]
matching SQL Class. Drush cannot find your database connection
details.' in
/usr/local/drush7/vendor/drush/drush/commands/sql/sql.drush.inc:597
Stack trace:
#0
/usr/local/drush7/vendor/drush/drush/commands/sql/sql.drush.inc(233):
drush_sql_get_class()
#1 [internal function]: drush_sql_conf()
#2 /usr/local/drush7/vendor/drush/drush/includes/command.inc(359):
call_user_func_array('drush_sql_conf', Array)
#3 /usr/local/drush7/vendor/drush/drush/includes/command.inc(210):
_drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /usr/local/drush7/vendor/drush/drush/includes/command.inc(178):
call_user_func_array('drush_command', Array)
#6
/usr/local/drush7/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(62):
drush_dispatch(Array)
#7 /usr/local/drush7/vendor/drush/drush/drush.php(70):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /usr/local/drush7/vendor/drush/drush/drush.php(11): drush_main()
#9 {main}
 [error]  An error 1 occurred while running the command `ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'cd /var/www/html/expressionstech.dev/docroot && drush7 sql-conf'` 


vagrant@drupalvm:~$ drush @expressionstech.hoeningfh-dev ssh 'drush sql-conf'
exception 'Drush\Sql\SqlException' with message 'Unable to find a        [error]
matching SQL Class. Drush cannot find your database connection
details.' in
/usr/local/drush8/vendor/drush/drush/commands/sql/sql.drush.inc:587
Stack trace:
#0
/usr/local/drush8/vendor/drush/drush/commands/sql/sql.drush.inc(223):
drush_sql_get_class()
#1 [internal function]: drush_sql_conf()
#2 /usr/local/drush8/vendor/drush/drush/includes/command.inc(364):
call_user_func_array('drush_sql_conf', Array)
#3 /usr/local/drush8/vendor/drush/drush/includes/command.inc(215):
_drush_invoke_hooks(Array, Array)
#4 [internal function]: drush_command()
#5 /usr/local/drush8/vendor/drush/drush/includes/command.inc(183):
call_user_func_array('drush_command', Array)
#6
/usr/local/drush8/vendor/drush/drush/lib/Drush/Boot/BaseBoot.php(65):
drush_dispatch(Array)
#7 /usr/local/drush8/vendor/drush/drush/includes/preflight.inc(64):
Drush\Boot\BaseBoot->bootstrap_and_dispatch()
#8 /usr/local/drush8/vendor/drush/drush/drush.php(12): drush_main()
#9 {main}
 [error]  An error 1 occurred while running the command `ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'cd /var/www/html/expressionstech.dev/docroot && drush sql-conf'` 


vagrant@drupalvm:~$ ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'drush7 --root=/var/www/html/expressionstech.dev/docroot --uri=hoeningfh sql-conf'
Array
(
    [driver] => mysql
    [database] => REDACTED
    [username] => REDACTED
    [host] => srv-4287
    [port] => 3306
    [prefix] => 
)



vagrant@drupalvm:~$ ssh -o PasswordAuthentication=no expressionstech.dev@srv-4287.devcloud.hosting.acquia.com 'drush --root=/var/www/html/expressionstech.dev/docroot --uri=hoeningfh sql-conf'
Array
(
    [driver] => mysql
    [database] => REDACTED
    [username] => REDACTED
    [host] => srv-4287
    [port] => 3306
    [prefix] => 
)

**Comment by oxyc** [comment]
Odd, I'm running out of ideas of what could cause this.

Any chance this works?

```sh
drush @expressionstech.hoeningfh-dev ssh 'drush --uri=hoeningfh sql-conf'
```

**Comment by expressionstech** [comment]
I think i got it....

from your previous comment, change the '%drush-script' to the absolute path as listed on the server:
/usr/local/drush8/vendor/drush/drush/drush.php

I am able to sql-sync now.

Questions -
my config.yml for drush version is master. Should I change this to "8.0.0", destroy then up?

my laptop has the same setup as the computer that is having issues. I would prefer to have the same environment/setup on both machines, utilizing the same 'template' for alias files. Hard coding the drush-script seems awkward in that it's hard coded making future changes very tedious (I've got 300+ aliases).

**Comment by oxyc** [comment]
If you add:

```
drush_version: "master"
drush_keep_updated: true
drush_force_update: true
```

One `vagrant provision` should be enough.

---

I don't see how Drupal VM could be the cause of these issues. Could there be something else that's different between your machines? I really need to get a site hosted on acquia so I can try these things out. Are these alias files automatically generated somehow?

Also, to support multiple drush version the `%drush-script` would be:

```
  'path-aliases' => array(
    '%drush-script' => '/usr/local/drush' . $drush_major_version . '/vendor/drush/drush/drush.php',
  )
```

Maybe it even works with:

```
  'path-aliases' => array(
    '%drush-script' => '/usr/local/drush' . $drush_major_version . '/drush',
  )
```

Not sure.

**Comment by expressionstech** [comment]
If I use drush_version: "master" drupalvm will use drush9. Once ssh'd into acquia, I can see that it only has up to version 8. 

I just provisioned with drush_version: "8.0.0" and changed the %drush-script to your suggestion;

  'path-aliases' => array(
    '%drush-script' => '/usr/local/drush' . $drush_major_version . '/vendor/drush/drush/drush.php',
  )

this works as well. 

It looks like when drupalvm is using drush9, my acquia aliases are failing because the $drush_major_version is referencing 9. That path in acquia, /usr/local/drush9/vendor/drush/drush/drush.php, does not exist. So... if I set drupalvm to drush_version: 8.0.0" then it will use 8, /usr/local/drush8/vendor/drush/drush/drush.php, which works. 

Very odd. You're right though, there must be something different I'm not seeing between my laptop and desktop config/settings. 

Thank  you so much for your help! I've been at this for almost 10 hours. lol.

**Comment by oxyc** [comment]
Glad I could help! Yes, drush aliases are always quite annoying, there's always something.

@geerlingguy as you're an insider. Are these alias files automatically generated somehow? If they are and it tries to find the currently used `drush` version on production, should we maybe provide docs somewhere that acquia cloud users should set the drush version to 8? Or maybe even move away from `master` and use the `8.x` branch?

**Comment by expressionstech** [comment]
Acquia does allow you download your alias files however I use my own. I've always done it that way however I am open to doing it the right way. If I should be using the ones from acquia I will, just not sure how to configure everything.

**Comment by oxyc** [comment]
I think we've had some issues with those alias files too... But if you could post an example from their generated example, maybe I can spot something.

**Comment by expressionstech** [comment]
The README from the download:

> This folder contains two hidden folders named .acquia and .drush. Both of these
folders should be placed in the $HOME directory on your system. The .acquia
folder contains your Acquia Cloud API credentials and the .drush folder
contains your Drush aliases for the sites you currently have access to on
Acquia Cloud

Refer to "About Drush on Acquia Cloud" (https://docs.acquia.com/cloud/drush) for
more information.


aliases file:

<?php

if (!isset($drush_major_version)) {
  $drush_version_components = explode('.', DRUSH_VERSION);
  $drush_major_version = $drush_version_components[0];
}
// Site expressionstech, environment dev
$aliases['dev'] = array(
  'root' => '/var/www/html/expressionstech.dev/docroot',
  'ac-site' => 'expressionstech',
  'ac-env' => 'dev',
  'ac-realm' => 'devcloud',
  'uri' => 'expressionstechREDACTED.devcloud.acquia-sites.com',
  'remote-host' => 'srv-4287.devcloud.hosting.acquia.com',
  'remote-user' => 'REDACTED',
  'path-aliases' => array(
    '%drush-script' => 'drush' . $drush_major_version,
  )
);
$aliases['dev.livedev'] = array(
  'parent' => '@expressionstech.dev',
  'root' => '/mnt/gfs/expressionstech.dev/livedev/docroot',
);

**Comment by oxyc** [comment]
Well looks like you have everything correct. Guess one requirement at the moment is to change the drush version to 8.x like you did. Why the drush binary isn't in the users path I don't know though :/

**Comment by geerlingguy** [comment]
> Are these alias files automatically generated somehow? If they are and it tries to find the currently used drush version on production, should we maybe provide docs somewhere that acquia cloud users should set the drush version to 8?

@oxyc  - Yeah... the way they're generated makes some weird things happen sometimes, too... I just blogged about an issue I was having with them recently: http://www.jeffgeerling.com/blog/2016/ensuring-drush-commands-run-properly-using-drush-8x-acquia-cloud-hooks

But yeah, we should probably switch to the 8.x branch instead of master for Drush.
