### ISSUE TITLE
Best way to get PHP 5.3?

### ISSUE THREAD

**Issue by mgp-novicell** [geerlingguy/drupal-vm#689]
I know PHP 5.3 is not supported and probably never will, but what would be the best way to achieve this? Is there a way to just use the default PHP in ubuntu and use ubuntu 12.04?

**Comment by geerlingguy** [comment]
@mgp-novicell - You can use Ubuntu 12.04, and set the `php_version` to `5.3`, and also override the `php_packages` list and all the other related vars [exactly the same as you would for 5.6](http://docs.drupalvm.com/en/latest/other/php-56/) (excepting the version, of course!), and it should use the default system packages.
