### ISSUE TITLE
Freedombox + drupal-vm

### ISSUE THREAD

**Issue by stevepurkiss** [geerlingguy/drupal-vm#697]
I'm looking for a way to work with Drupal on the Freedombox distro & was wondering how best to approach integrating with drupal-vm now I'm happy (a.k.a. 'can just about do by the skin of my teeth but that is enough') using this way of setting up digitalocean instances as then I can try it out on some single board computers.

At first I thought just swapping image references would work but then of course I decided to actually investigate it and I think there's lots of differences in the system setup which means it's not as easy as I'm thinking it maybe so just posting here in case anyone has pointers/opinions. The goal is a piece of kit I can plug in & serve in order to redecentralise ;)

https://wiki.debian.org/FreedomBox/Download

TIA

Steve

**Comment by geerlingguy** [comment]
For single board computers, I use most of the same roles, but a radically different config: https://github.com/geerlingguy/drupal-pi

Or for multi-host setups: https://github.com/geerlingguy/raspberry-pi-dramble

FreedomBox isn't really meant to coexist alongside a monolithic LEMP/LAMP install, especially with really limited resources like that on most sub-$200 single-board computers.

Also, Drupal VM itself supports deployment to DO droplets as well: https://github.com/geerlingguy/drupal-vm/tree/master/examples/prod

**Comment by geerlingguy** [comment]
The drupal-pi project works on Raspberry Pi (any model, but 2 or 3 are the only ones reasonably fast enough for Drupal 8), Orange Pi, and ODROID-C2.

**Comment by stevepurkiss** [comment]
Thanks - yes, I've managed to follow the great instructions you set out to get drupal-vm up on digitalocean! 

Sounds like I need to consider initial requirements as to which approach I take, the end goal is to have an AGPL-licensed stack I can package virtually and in hardware so hence the FreedomBox concept.

Thinking of hardware as cattle I can handle single-use versions, so perhaps the multi-host is the most promising of those links.

Will go play, thanks again!

**Comment by geerlingguy** [comment]
Playing is the best way to find a good solution :)

And be sure to blog about it so others can learn from it too—or at least post back some more info here. Thanks for the info, and I'll keep an eye on what you're working on!

**Comment by stevepurkiss** [comment]
Really? You *really* want to know update? ;) 

OK - well I think the best way I've seen people implement their ideas so far is to be able to communicate them, so with DrupalCamp Brighton in two weeks and session submission closing in <24h and a session already on drupal-vm & many others by many others FAR better than me on the subject I am currently contemplating writing a short scifi scenario based on a true story about Brighton post-Brexit as the vote to leave the EU is just a few days after the camp.

It's where I get evicted so have to leave Brighton & as a result I miss my vote & Britain brexits.

All trade deals are off and the UK finds itself on its own, and down in Brighton The People's Republic of Brighton & Hove end up taking over the administration of the now defunct Brighton & Hove City Council. It happens the only thing left they own that's working is the website which runs Drupal. 

All the existing local groups used Facebook and Twitter and snapchat and whatsapp but since they went they've been roaming the streets amongst the growing homeless people who've been setting up mini housing estates along many parts of the city centre. 

They start discovering other places are using Drupal to communicate and they discover projects like the social api and the social distribution and the mutual_credit suite of community accounting and suddenly the entire city is powered by Drupal and people of all abilities have work helping to grow the project using whatever skills they have and want. 

It worked particularly well in Brighton because of the close-knitness of the city & over 1,000 digital companies & 16k freelancers & hackspaces & 1,000s of community groups but the current gaps between local connections caused by outside effects, brought together once a local mesh network was set up in order to provide local connectivity to everyone.

The city is back on track and the current 10 year life expectancy gap between parts of the city has vanished and due to someone remembering to license it under the AGPL their work spread throughout the world and just as that happened YCombinator figured out basic income and everyone lived happily ever after.

Anyway, it's all part of https://www.edocr.com/v/b6er548l/steve4/organicopen-source-cafecoworking-concept which I wrote a wee while back, I'll get there at some point, I'm just trying out different things and looking at what I have (nothing but my lovely x200 box of freedom technology!) and seeing where I can take it, cos I don't do 9-5 very well.

/ends rant

**Comment by stevepurkiss** [comment]
OK I'll stop using this as evernote but simple fact it's now here I need to add I'm working on rewriting the first bit: "It's where I get evicted so have to leave Brighton" to something a little more cheery, it's late & tempus fugit!

Thanks for your continued awesome tooling talent!

**Comment by geerlingguy** [comment]
That's actually some great background! And no problem having good ways to solve problems caused by potential scenarios. That's why I basically have all my infrastructure backed up in my home (in addition to multiple cloud tenants)—I don't want my digital contributions to go away in the (unlikely, but plausible) event that some of the servers I'm using are seized for some purpose or another.

It's also another good reason to be sure that every aspect of your infrastructure—[down to your personal workstation!](https://github.com/geerlingguy/mac-dev-playbook)—can be automatically recreated from scratch using a tool like Ansible.

**Comment by stevepurkiss** [comment]
Excellent! I submitted my session, using the scenario as a set-up. Will be writing it anyway even if doesn't get accepted as need to crowdfund ;)

http://www.drupalcampbrighton.co.uk/sessions/vbrighton-a-drupal-powered-crowdfunded-coworking-neworking-cafe-bar

thx for the encouragement!
