### ISSUE TITLE
Too many authentication failures for vagrant

### ISSUE THREAD

**Issue by alimac** [geerlingguy/drupal-vm#70]
I might be missing something very basic. I cloned drupal-vm, and when I run `vagrant up` I get this error. Has anyone encountered it before?

```
GATHERING FACTS *************************************************************** 
fatal: [drupaldev] => SSH Error: Received disconnect from 127.0.0.1: 2: Too many authentication failures for vagrant
    while connecting to 127.0.0.1:2222
It is sometimes useful to re-run the command using -vvvv, which prints SSH debug output to help diagnose the issue.

TASK: [Update apt cache if needed.] ******************************************* 
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/alimac/playbook.retry

drupaldev                  : ok=0    changed=0    unreachable=1    failed=0   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
@alimac - That looks like an issue with Vagrant and/or VirtualBox configuration/networking. Please take a look at the following issues to see if they offer any helpful hints:

  - https://github.com/CenturyLinkLabs/panamax-coreos/issues/23
  - https://github.com/mitchellh/vagrant/issues/391
  - http://stackoverflow.com/questions/22575261/vagrant-stuck-connection-timeout-retrying

Specifically, see if you can use `vagrant ssh` after the machine is up; if not, it sounds like there might be some SSH configuration error on your user account.

**Comment by alimac** [comment]
Thanks for the suggestions. I found the solution in http://serverfault.com/questions/580753/ssh-aborts-with-too-many-authentication-failures:

Specifically, http://serverfault.com/a/580860:
> To check you have this problem: Run `ssh-add -l` 
> if this list is > 5 you need to remove keys or disable the agent.
>
> To fix: Run `ssh-add -d ~/.ssh/X` where X is the key you want to remove.

After removing 2 keys from ssh-agent `vagrant provision` ran without problems.

**Comment by geerlingguy** [comment]
Ha, I just ran into this today after having used `ssh-add` to stick a bunch of AWS keys in the agent.

**Comment by alimac** [comment]
Oh wow. A blast from the past!

Something I learned since then is that the number of keys that a server will try accepting during authentication is controlled by `MaxAuthTries` value in `/etc/ssh/sshd_config`.

**Comment by brian2-sans** [comment]
I also had this issue recently. I could run "vagrant ssh" but connecting to the box through ssh with drush failed.

To fix I added an entry to my .ssh/config

Host [LOCAL HOST NAME]
        Protocol 2
        Port [PORT USING FOR SSH... STANDARD IS 22]
        User vagrant
        IdentityFile [PATH TO KEY]/.vagrant.d/insecure_private_key
        IdentitiesOnly yes

The IdentitiesOnly option was the key option to make it work for me.

**Comment by damagingzebra** [comment]
I also had this issue recently. I could run "vagrant ssh" but connecting to the box through ssh with drush failed.

To fix I added an entry to my .ssh/config

Host [LOCAL HOST NAME]
Protocol 2
Port [PORT USING FOR SSH... STANDARD IS 22]
User vagrant
IdentityFile [PATH TO KEY]/.vagrant.d/insecure_private_key
IdentitiesOnly yes

The IdentitiesOnly option was the key option to make it work for me.

**Comment by sebastiaanluca** [comment]
September 2018 called and it wants the last 4 hours back 😑 I could not figure out why I could (manually) SSH into my vagrant machine just fine yesterday, but not today. Turns out it was trying all old keys before it could get to the right one, even if I specified it with the `-i` option or any other method. Jeez.

**Comment by PetrusKiendys** [comment]
Simply adding the SSH keys to the ssh-agent did it for me:

```
petrus@DD-XPS-15-9550:~/dev/work/some/project$ find . -iname "private_key"
./.vagrant/machines/vm1/virtualbox/private_key
./.vagrant/machines/vm2/virtualbox/private_key
./.vagrant/machines/vm3/virtualbox/private_key
./.vagrant/machines/vm4/virtualbox/private_key

petrus@DD-XPS-15-9550:~/dev/work/some/project$ find . -iname "private_key" | xargs ssh-add
Identity added: ./.vagrant/machines/vm1/virtualbox/private_key (./.vagrant/machines/vm1/virtualbox/private_key)
Identity added: ./.vagrant/machines/vm2/virtualbox/private_key (./.vagrant/machines/vm2/virtualbox/private_key)
Identity added: ./.vagrant/machines/vm3/virtualbox/private_key (./.vagrant/machines/vm3/virtualbox/private_key)
Identity added: ./.vagrant/machines/vm4/virtualbox/private_key (./.vagrant/machines/vm4/virtualbox/private_key)
```
