### ISSUE TITLE
Include default vagrant-cachier configuration

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#702]
Especially in light of #699—I'd like to add a default configuration so people who install `vagrant-cachier` don't also have to add in extra bits to a `Vagrantfile.local` to get some cache benefits.

By default, I'd like to add `:apt` and `:generic` (so the composer dir is cached). The yum cache has a few caveats, so I might not enable it by default, and there's nothing for dnf yet. I also need to test and make sure there are no issues if using a CentOS base box while the `:apt` cache is enabled.

Here's the current config I'm testing:

```
if Vagrant.has_plugin?("vagrant-cachier")
  # Share cache among instances of the same base box.
  config.cache.scope = :box

  # Set cache buckets manually.
  config.cache.auto_detect = false

  # Cache apt data.
  config.cache.enable :apt

  # Cache the composer directory.
  config.cache.enable :generic, { :cache_dir => "/home/vagrant/.composer/cache"  }

  # Cache via NFS shares.
  config.cache.synced_folder_opts = {
    type: :nfs,
    mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  }
end

```

**Comment by geerlingguy** [comment]
Looks like cachier works fine with just `:apt` on a yum-based distro:

```
==> drupalvm: Skipping APT cache bucket as the guest machine does not support it
```

So I'm going to pull this in for 3.1.0.

**Comment by CashWilliams** [comment]
I was coming to open this exact issue 👍

**Comment by geerlingguy** [comment]
@CashWilliams - Why, of course :D

**Comment by geerlingguy** [comment]
Just a note; with some versions of my boxes, which are running into issues with VMware's latest openvm-tools not working correctly for native synced folders, I'm getting the following error when `vagrant-cachier` is installed:

```
...
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Waiting for HGFS to become available...
==> drupalvm: Enabling and configuring shared folders...
    drupalvm: -- /Users/jgeerling/.vagrant.d/cache/geerlingguy/ubuntu1604: /tmp/vagrant-cache
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

vmhgfs-fuse -o uid=`id -u vagrant`,gid=1000,allow_other '.host:/vagrant-cache' /tmp/vagrant-cache

Stdout from the command:
Stderr from the command:
```

To fix, I've added the following to my `Vagrantfile.local` so it explicitly uses NFS for the cache volume:

```ruby
if Vagrant.has_plugin?("vagrant-cachier")
  # Cache via NFS shares.
  config.cache.synced_folder_opts = {
    type: :nfs,
    mount_options: ['rw', 'vers=3', 'tcp', 'nolock']
  }
end
```
