### ISSUE TITLE
PHPMyAdmin requires configuration

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#71]
PHPMyAdmin continues to throw a message about accessing it's own configuration database when none exists.

Guessing this needs to be a configuration change in the config.inc.php file or load the bundled SQL file into it's own database

**Comment by geerlingguy** [comment]
@nerdstein - I don't use PHPMyAdmin much, but this issue should probably be filed against the upstream project, https://github.com/geerlingguy/ansible-role-phpmyadmin - Could it be related to https://github.com/geerlingguy/ansible-role-phpmyadmin/issues/1?

**Comment by nerdstein** [comment]
Yep - that would be it!

**Comment by nerdstein** [comment]
Thanks for the prompt response

**Comment by geerlingguy** [comment]
@nerdstein - Cool! Can you post over to that issue (linked above) just to give it a little more weight? I typically triage my GH issues every week or two, and give a little more weight to those with more than one person weighing in :)
