### ISSUE TITLE
[documentation] Installing git subtree on Drupal VM

### ISSUE THREAD

**Issue by fubarhouse** [geerlingguy/drupal-vm#712]
I'm exploring the usage of git subtree with my agency's Acquia account and wish to do some testing on the usage and in general to get some experience before looking into proper subtree CI procedures on a production/development server.

As subtree is a module which ships from git's repository, could anybody enlighten me on how to get started on the setup specific to Drupal VM?

**Comment by geerlingguy** [comment]
Git subtrees just allow you to add a Git repository as a 'child' of another Git repository—see the following articles for help:

  - http://blogs.atlassian.com/2013/05/alternatives-to-git-submodule-git-subtree/
  - https://gist.github.com/kvnsmth/4688345

But a lot of projects take another approach, using Composer to manage Drupal VM as a dependency. For example, see how BLT is going to integrate Drupal VM: https://github.com/acquia/blt/pull/105

This isn't really something that would be Drupal VM-specific, so I'm going to close the issue; but anyone else who uses Drupal VM as a subtree or submodule, please chime in with benefits/drawbacks/gotchas here.

**Comment by oxyc** [comment]
I used Drupal VM as a submodule since a year ago or so, up until 3.0.0 (yey). There's a section on how to set it up in the [docs](http://docs.drupalvm.com/en/latest/other/drupalvm-composer-dependency/#drupal-vm-without-composer). I didn't really find any drawbacks besides the usual submodule drawbacks.

**Comment by fubarhouse** [comment]
I feel my question was misunderstood, but I'm going to just create some tasks to implement https://github.com/travis-ci/travis-ci/issues/2002#issuecomment-43331703

**Comment by thom8** [comment]
@fubarhouse is there a specific reason for using a subtree over a submodule? Whilst [Acquia don't support submodules](https://docs.acquia.com/articles/using-git-subtrees-instead-git-submodules) you can still use it for something like Drupal VM as you never need to checkout the submodule on an Acquia environment and the submodule can still be checked out on travis/jenkins etc.

Wouldn't recommend using a subtree in this case as you probably don't want to track the whole DVM project only your custom config.

**Comment by fubarhouse** [comment]
Let's just say I have a niche which has a far bigger scope than just Drupal VM.
Drupal VM is fantastic, but our setup has far more built onto it and subtrees fits the bill for what we're trying to achieve.

I've attempted to work with submodules as it was my preference until I actually started working with it, and I've basically built a preference for this alternative - which is also officially supported by git.

**Comment by thom8** [comment]
Sounds interesting we currently reuse our local (YAML) VM config for our CI environment, which means we can effectively branch and test our infrastructure changes alongside normal project features.

It obviously adds a bit of time to each test as it needs to provision first but it also gives us the flexibility quickly test the impact of any infrastructure changes. We're also working towards implementing [LXD](http://www.ubuntu.com/cloud/lxd) to cache the provisioning step to speed up builds and only rebuild if config changes are found.

**Comment by geerlingguy** [comment]
@thom8 - You need to blog some about these things, and get your posts on Drupal Planet... it sounds like you're doing some amazing work! :)

**Comment by thom8** [comment]
@geerlingguy if only there were more hours in a day! 2 contracts & 2 kids keep me pretty busy ATM.

**Comment by geerlingguy** [comment]
@thom8 you can always sacrifice sleep. _Sponsored by Coca-Cola® and Red Bull®_

/s
