### ISSUE TITLE
Error reporting

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#72]
Two potential design considerations to consider:

1. Since this is a local, turn on PHP error reporting by default

2. Give permissions to the default vagrant ssh user to /var/log/apache2/*

**Comment by geerlingguy** [comment]
@nerdstein - Regarding #1, PHP error reporting _is_ enabled by default, at least if you're using the example configuration (see `php_display_errors: "On"`). However, Drupal might not have all errors display to screen by default if you're using the default Drupal 8 makefile. That's something that needs to be set within whatever Drupal site you're running in the VM :)

I'll test a quick fix for point 2 so you can tail the logs without `sudo`.

**Comment by geerlingguy** [comment]
Fixed with the above commit. If you rebuild the VM or run `vagrant provision` again, you should be able to view/tail the logs as the `vagrant` user (or any user, now).
