### ISSUE TITLE
SSH identity not passed from host to guest

### ISSUE THREAD

**Issue by danbohea** [geerlingguy/drupal-vm#722]
I just reprovisioned a box (`master` 2016/06/08), SSHd in and started getting error 255 all over the place whenever I tried to do anything with remote site aliases (e.g. sql-sync). It's as though my guest doesn't have permission to access any remote servers. I ran `ssh-add -L` in the guest and sure enough it seems that my host's ssh identity has not been passed to the guest by Vagrant. The following lines from DVM's Vagrantfile should handle this by default no?

```
# SSH options.
config.ssh.insert_key = false
config.ssh.forward_agent = true
```

Any help would be greatly appreciated.

**Comment by geerlingguy** [comment]
@danbohea did you use `vagrant ssh` to log in, or ssh directly?

**Comment by danbohea** [comment]
Sorry, should have said. I used `vagrant ssh`.

**Comment by geerlingguy** [comment]
Hmm. The forward_agent line should pass in the config... maybe there's some other bit of your SSH configuration that's blocking it?

And did you triple-check these steps? http://stackoverflow.com/a/16127657/100134

**Comment by thom8** [comment]
@danbohea do you have `ForwardAgent` set in your SSH config?

```
~/.ssh/config >
Host 127.0.0.1
  ForwardAgent yes
```

This can also be added to the drush alias SSH options, but would only work with `drush ssh`

```
...
'ssh-options' => '-i /path/to/insecure_private_key -o ForwardAgent=yes'
...
```

**Comment by danbohea** [comment]
@thom8 I've always used the following since Vlad which should still work with DVM now (I'm still using *.local for hostnames):

```
Host *.local
  ForwardAgent yes
```

@geerlingguy Yep, steps checked:

1. `config.ssh.private_key_path` isn't used in DVM AFAIK so not sure about that one. I guess Vagrant just assume a default path (I'm using the default key path on OS X).
2. Yep, `ssh-add -L` returns my key as expected.
3. "add your public key to ~/.ssh/authorized_keys on the Vagrant VM" - never had to do that with Vlad, is that a required step in DVM?

**Comment by danbohea** [comment]
Aaah, FFS. I just pulled latest master, reprovisioned the box again and now it's working. `ssh-add -L` from within the guest returns my key as expected. Not sure what that was all about. Sorry for the noise. Hopefully that's the end of that. Thanks for all your input.

**Comment by geerlingguy** [comment]
@danbohea - Ha, well, as usual, [hit it a few times](https://en.wiktionary.org/wiki/percussive_maintenance), and everything works :P

**Comment by thom8** [comment]
@danbohea the custom SSH conf is no longer required if using `vagrant ssh`

**Comment by danbohea** [comment]
Balls. Just had this very same issue happen again on a different system. Once again all _appears_ to be in order and Vlad setups on the same system are passing keys to the guest just fine. Sorry to have to re-open but this no longer looks like a one-time-wobble.

**Comment by thom8** [comment]
@danbohea can you confirm the OS and post the output of `vagrant ssh-config`?

Also confirm that `ssh-agent` is running and `ssh-add -L` on the host returns the correct key.

**Comment by danbohea** [comment]
@thom8 Thanks for the help. Major muppetry on my part as I was working on a newly provisioned host system and had still yet to add an existing key to the agent with `ssh-add ~/.ssh/id_rsa`. Again, apologies for the noise.

**Comment by thom8** [comment]
@danbohea I'd be lying if I said I hadn't done the same 😄
