### ISSUE TITLE
XHProf cannot be enabled (solved)

### ISSUE THREAD

**Issue by alimac** [geerlingguy/drupal-vm#73]
I was trying to get XHProf to work on Drupal VM and after installing the module, the option to enable profiling was disabled (greyed out):

![screen shot 2015-04-14 at 4 38 03 pm](https://cloud.githubusercontent.com/assets/1930627/7139958/3ff9f61a-e2c9-11e4-9c34-f9a7ac796bd1.png)

It looks like PHP was not seeing that XHProf was installed, even though it was. The solution was to create a symlink:
```
cd /etc/php5/apache2/conf.d
ln -s /etc/php5/conf.d/xhprof.ini
sudo service apache2 restart
```
After this, the option was not disabled anymore, and I could enable profiling:

![screen shot 2015-04-14 at 4 39 42 pm](https://cloud.githubusercontent.com/assets/1930627/7140339/02bea08c-e2cb-11e4-8661-c3669c661cfb.png)

Is this something that can be addressed in the XHProf ansible role?

**Comment by geerlingguy** [comment]
@alimac - I just fixed this upstream in the `geerlingguy.php` role. When you are able, please update that role by either deleting it from your Ansible roles folder and then running the galaxy requirements installation step again, or run the command:

```
ansible-galaxy install geerlingguy.php,1.4.4 --force
```
