### ISSUE TITLE
Support recursive merge of settings from *.config.yml

### ISSUE THREAD

**Issue by derekderaps** [geerlingguy/drupal-vm#731]
The call to [`Hash#merge!()`](http://docs.ruby-lang.org/en/2.0.0/Hash.html#method-i-merge-21) in [Vagrantfile:44](https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L44) means that arrays of settings defined in subsequent files (`config.yml` and `local.config.yml`) replace the initial set defined in `default.config.yml`. This is okay for some use-cases but presents a problem when maintaining a set of pre-defined sites for a team.

Here's the scenario:

1.  I [forked Drupal VM](https://github.com/derekderaps/drupal-vm) and updated `default.config.yml` with my team's default sites. I could also have just added my settings to `config.yml` and force-committed it to override the .gitignore.
1.  A team member using my fork wants to add a site just for herself and not the whole team.
1.  She copies `default.config.yml` to either `config.yml` or `local.config.yml` and defines her site's synced folder, host, and other settings.
1.  She reprovisions and all's well at first, but then the team adds a new site to the pre-defined set in `default.config.yml`.
1.  She pulls in the changes but can't see the new site! Why? Because her settings in `[local.]config.yml` override those in `default.config.yml`

If [Vagrantfile:44](https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L44) used a recursive merge, such as [`Hash#deep_merge()`](https://github.com/danielsdeleo/deep_merge) or a lighter, custom implementation, the local-only settings would simply add to the existing ones from `default.config.yml`. What do you think about this?

**Comment by oxyc** [comment]
I guess the main problem if we had a deep merge that also merges arrays is that you cant remove items from `installed_extras`, which I think is pretty common.

**Comment by geerlingguy** [comment]
To @oxyc - same thing with node packages, composer global packages, ruby gems, vhosts, etc.

While it may be more convenient in some circumstances, I think merging instead of overriding would make many behaviors more confusing and potentially harder to debug.
