### ISSUE TITLE
Windows 10 VirtualBox synced folders don't like Composer

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#733]
Windows 10, Vagrant 1.8.1, VirtualBox 5.0.20

I get the error:

```
Failed to download drupal/core from dist: Could not delete web/core/6154c8a03a58e79151b32c248b8ce96d
```

Full log of the failed task:

```
==> drupalvm: TASK [Generate Drupal project with composer package.] **************************
==> drupalvm: fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:08:23.956900", "end": "2016-06-13 20:09:37.197460", "failed": true, "rc": 1, "start": "2016-06-13 20:01:13.240560", "stderr": "Running composer as root/super user is highly discouraged as packages, plugins and scripts cannot always be trusted
Installing drupal-composer/drupal-project (8.x-dev 544ba79cd95cb4fca599cba586498aaf0faf2885)
  - Installing drupal-composer/drupal-project (8.x-dev 544ba79)
    Loading from cache

Created project in /var/www/drupalvm/drupal
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing drupal-composer/drupal-scaffold (2.0.1)

 Loading from cache

  - Installing cweagans/composer-patches (1.5.0)
    Loading from cache

...

  - Installing symfony/polyfill-apcu (v1.2.0)
    Loading from cache

  - Installing symfony/class-loader (v2.8.7)
    Loading from cache

  - Installing drupal/core (8.1.2)

    Downloading: Connecting...\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 0%
         \b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 5%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 10%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 15%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 20%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 25%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 30%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 35%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 40%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 45%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 50%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b
    Downloading: 55%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 60%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 65%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 70%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 75%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 80%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 85%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 90%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 95%\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b\b    Downloading: 100%
    Failed to download drupal/core from dist: Could not delete web/core/6154c8a03a58e79151b32c248b8ce96d: 
    Now trying to download from source
  - Installing drupal/core (8.1.2)



  [RuntimeException]                                            
  Could not delete web/core/6154c8a03a58e79151b32c248b8ce96d:   



create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}
```

See upstream/related:

  - https://github.com/drupal-composer/drupal-project/issues/126
  - http://stackoverflow.com/a/26216954/100134

I'm not sure if I'm hitting the Composer timeout (the task does hang for a long time), or if it's a symlink/similar issue. I don't hit this on Fedora or Mac OS X, so it seems to be a Windows/VirtualBox thing.

**Comment by geerlingguy** [comment]
Testing with a `composer.json` build instead of `drupal-project`, following [these instructions](http://docs.drupalvm.com/en/latest/deployment/composer/#using-composerjson)—basically set the following variables in `config.yml` after copying the example composer file to `drupal.composer.json`:

```yaml
build_composer_project: false
build_composer: true
drupal_core_path: "{{ drupal_composer_install_dir }}/docroot"
```

**Comment by geerlingguy** [comment]
Now I'm hitting https://github.com/ansible/ansible/issues/9526

**Comment by geerlingguy** [comment]
I'm going to try setting `vagrant_synced_folder_default_type` to `smb` to see if that helps. This also requires me to run Cmder/Cygwin64 as administrator, so not ideal, but just testing to see if it works out.

**Comment by geerlingguy** [comment]
Now I'm hitting a bug in our composer.json :)

**Comment by geerlingguy** [comment]
Getting the same issue, "Could not delete docroot/core/cifs8b2c" now, at the end of the "Run composer install." task :P

Looks like for Windows, we might need to recommend the makefile approach for now (or any setup that doesn't require Drupal VM building a composer-based codebase itself inside a shared directory), until I can figure out a more stable way of doing Composer stuff in a shared directory.

**Comment by geerlingguy** [comment]
Testing with the following config (after creating `drupal.make.yml` from the example):

```yaml
build_makefile: true
build_composer: false
build_composer_project: false
drupal_core_path: "/var/www/drupalvm/drupal"
```

**Comment by geerlingguy** [comment]
The makefile configuration seems to have worked. `drupalvm.dev` is up and running.

**Comment by geerlingguy** [comment]
Better title ^^

**Comment by geerlingguy** [comment]
I'm back to the default configuration. Going to try to see if there's a way to make Composer happy on Windows inside a VirtualBox synced folder.

**Comment by oxyc** [comment]
Hmm. Does it work if you change the location of `vendor` to somewhere outside of the shared folder?

```
{
    "name": "custom-project/drupal-vm",
    "description": "",
    "type": "project",
    "license": "MIT",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        }
    ],
    "require": {
        "composer/installers": "^1.0.20",
        "drupal-composer/drupal-scaffold": "^2.0.1",
        "drupal/core": "~8.0",
        "drupal/devel": "1.0.x-dev"
    },
    "replace": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "vendor-dir": "/home/vagrant/vendor"
    },
    "extra": {
        "installer-paths": {
            "docroot/core": ["type:drupal-core"],
            "docroot/modules/contrib/{$name}": ["type:drupal-module"],
            "docroot/profiles/contrib/{$name}": ["type:drupal-profile"],
            "docroot/themes/contrib/{$name}": ["type:drupal-theme"],
            "drush/contrib/{$name}": ["type:drupal-drush"]
        }
    }
}
```

**Comment by geerlingguy** [comment]
This looks highly related to #741 as well (just tagging that reference).

**Comment by geerlingguy** [comment]
I'm testing using a longer composer timeout (as suggested [here](https://github.com/geerlingguy/drupal-vm/issues/741#issuecomment-226424713)), and also for Windows VirtualBox compatibility, I've switched the task that moves composer.json into place (inside `build-composer.yml`) to two tasks; one to copy it into a non-shared-directory location, then a second to use `mv` to move the file (because of the upstream Ansible issue on VirtualBox synced dirs and the `copy` module).

**Comment by geerlingguy** [comment]
This seems to have worked. (the longer timeout)

**Comment by geerlingguy** [comment]
Hmm... it worked without the timeout this time, so maybe it's just when things are slow. I'd still like to add some config to make it more reliable/stable of course...

**Comment by geerlingguy** [comment]
Now trying composer project with:

```yaml
- name: Generate Drupal project with composer package.
  command: >
    {{ composer_path }} create-project
    {{ drupal_composer_project_package }} {{ drupal_composer_install_dir }}
    {{ drupal_composer_project_options|default('--prefer-dist --no-interaction') }}
  when: not drupal_site_exists
  become: no
  environment:
	COMPOSER_PROCESS_TIMEOUT: 1200
```

**Comment by geerlingguy** [comment]
And docs for process-timeout: https://getcomposer.org/doc/06-config.md#process-timeout

**Comment by geerlingguy** [comment]
It is _crazy_ slow... but it's working. I can't imagine using VirtualBox native synced folders for daily use. Just the 'Install configured modules with drush' task is taking like 30 min :P

**Comment by geerlingguy** [comment]
Testing, and if it works (even if it's crazy-slow), I'll tag a bugfix release and hopefully solve this plus #741 in one shot.

**Comment by geerlingguy** [comment]
Works! And was way faster this time, even though I don't have `vagrant-cachier` installed on the laptop.

**Comment by ibuildit** [comment]
Increasing timeout works for me as well on drupalvm  / windows 10

**Comment by armyofda12mnkeys** [comment]
Note: increasing timeout in my composer.json also worked for me

**Comment by webprogrammierer** [comment]
I did not find any solution for this problem.

Is there any?
