### ISSUE TITLE
Solr gives httplib2 error on provision

### ISSUE THREAD

**Issue by smithyco** [geerlingguy/drupal-vm#735]
```
TASK [geerlingguy.solr : Check current list of Solr cores.] ********************
fatal: [forcebrands]: FAILED! => {"changed": false, "failed": true, "msg": "httplib2 >= 0.7 is not installed"}
```
Getting this error when trying to include a Solr instance using the newest config.yml file from (https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml)

Tried to run provision a couple times, no luck. Some dependency is not being included, perhaps?

**Comment by fubarhouse** [comment]
@smithyco You might want to check the version of ansible you're using.

I ran into this one a while back, but I can't remember exactly how I fixed it.

This should get you some info in the interim:

https://github.com/ansible/ansible-modules-core/issues/2921

**Comment by smithyco** [comment]
That fixed it, thanks!
