### ISSUE TITLE
Windows and vagrant-cachier

### ISSUE THREAD

**Issue by morsok** [geerlingguy/drupal-vm#736]
Hello,

If you have vagrant-cachier, the Vagrantfile totally ignores the synced folder type and tries to use NFS.

However it will not work since you are on windows !

I think there is two solutions here, either use the provided type (by config.yml) if possible, or ignore the vagrant-cachier configuration if the provided type is not 'nfs'

I had to delete the vagrant-cachier plugin as a workaround on the windows hosts to make the vm work.

**Comment by geerlingguy** [comment]
Hmm... I hadn't thought about that when adding the config. I'm testing a fix now that will simply use the same sync type as the default folder—e.g. `vagrant_synced_folder_default_type`. So if you have cachier on Windows, you can change that setting to `` or to `smb`.

**Comment by geerlingguy** [comment]
Though for compatibility, we could just drop the entire `config.cache.synced_folder_opts` setting...

See: https://github.com/fgrehm/vagrant-cachier/blob/master/docs/usage.md#custom-cache-buckets-synced-folders-options

**Comment by geerlingguy** [comment]
I'm going to drop the config for now—trying to change the `mount_options` in addition to the default type based on whether it's set to `'nfs'` or `''` is making the code a little uglier, and the performance benefit for this particular directory (the apt/composer/etc. cache) is minimal at best. Plus, if you really want to eke out a tiny bit better performance, you can still add in the `config.cache.synced_folder_opts` in a `Vagrantfile.local`.

Testing, then will push this up.

**Comment by geerlingguy** [comment]
@morsok - Can you see if the latest `master` version of Drupal VM works for you?

**Comment by morsok** [comment]
Yeah I agree that the performance isn't really significant here.

Thank you for your diligence !

I'll try to bother my team mate to test the master on his windows machine (I don't know if I can get a license key to test it myself ? any idea ?)

**Comment by salecharohit** [comment]
i used this plugin https://github.com/winnfsd/vagrant-winnfsd and now cachier works like a charm on Windows 10 WSL
