### ISSUE TITLE
"TASK [Get software for Python-based control.]" takes a very long time

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#738]
Not sure if this is just me or not, but when I create a new project and do vagrant up, this task seems to take 5-10 minutes before anything else happens in the console. I feel like it used to be faster, or I could be mis-remembering.

What occurs during this step that takes that long to progress?

**Comment by thom8** [comment]
@kevinquillen would recommend the `vagrant-cachier` plugin, conf has recently been added to Vagrantfile -- https://github.com/geerlingguy/drupal-vm/blob/master/Vagrantfile#L179-L186

`vagrant plugin install vagrant-cachier`

It caches by base box so all projects that share the same box will share the cache.

**Comment by kevinquillen** [comment]
I do have that installed, but the second machine I provisioned still took a while.

**Comment by geerlingguy** [comment]
Can you open up activity monitor during that time and see if it's network or other activity that might be slow? Usually that task only takes 10-20 seconds for me (with or without cachier).

**Comment by thom8** [comment]
Wonder if it could help if we added the ability to use a local mirror -- https://wiki.ubuntu.com/Mirrors

**Comment by oxyc** [comment]
I tried http://askubuntu.com/a/37754/56258 while I was in ecuador but in my case it didn't really improve anything.

**Comment by aweingarten** [comment]
@geerlingguy I saw this yesterday when setting up a new Dev.  Dunno if it helps but the VM was 2.5.1.  Going to update to 3.x.

**Comment by geerlingguy** [comment]
Interesting... Let's keep this open and see if anyone else notices it. I haven't on the `master` branch from a couple computers but only trying over my home internet connection. Maybe it's a regional thing with Ubuntu's repos?

**Comment by illepic** [comment]
Drupal-VM 3.1.2 running on an Ubuntu 16.04 host with vagrant-cachier installed. Running `vagrant up` after a freshly `vagrant destroy`'d box:

    TASK [Get software for Python-based control.] **********************************

That hung out from 6:05 pm until 6:22 pm for a total of about 17 minutes before blasting through the rest of the provision quickly.

**Comment by illepic** [comment]
Aaaaaand an arbitrarily `vagrant destroy` of this same box and `vagrant up --provision`ing it again and the build was snappy. I don't know what's real.

**Comment by geerlingguy** [comment]
@illepic - Honestly it puzzles me... I do remember hanging on this task once or twice (but rarely). I wonder if it's something with the apt packages themselves...

**Comment by geerlingguy** [comment]
Tested again from STL today, and that step took like 8 seconds.

**Comment by geerlingguy** [comment]
I'm going to chalk this one up to cosmic rays and network funkiness. Please leave more feedback here and if we can find a pattern or some way to workaround/fix this sporadic issue, I'll reopen. But for now, for lack of being able to reliably reproduce the issue, I'm going to close it.

**Comment by geerlingguy** [comment]
So... for the first time I hit this today. It's just sitting... and sitting... and sitting. Very slow install. I'm going to dig and see exactly what's happening (if I can get it to happen twice).

**Comment by geerlingguy** [comment]
Update: After waiting about 5 min and Ctrl-C'ing out of the `vagrant provision` process while stuck on this task, I did a `vagrant reload` then logged in with `vagrant ssh`.

Running the `apt-get` install manually, it went through the install very fast (it must've already downloaded all the deps), and then at the end I got one warning:

```
Setting up manpages-dev (4.04-2) ...
Setting up unzip (6.0-20ubuntu1) ...
Setting up python-pycurl (7.43.0-1ubuntu1) ...
Processing triggers for libc-bin (2.23-0ubuntu3) ...
W: chown to _apt:root of directory /var/cache/apt/archives/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)
```

But if I ran the install command again, it then said everything was installed/latest:

```
vagrant@drupalvm:~$ sudo apt-get install -y curl python-apt python-pycurl build-essential sudo unzip
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.1ubuntu2).
curl is already the newest version (7.47.0-1ubuntu2).
python-apt is already the newest version (1.1.0~beta1build1).
python-pycurl is already the newest version (7.43.0-1ubuntu1).
unzip is already the newest version (6.0-20ubuntu1).
sudo is already the newest version (1.8.16-0ubuntu1.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
```

So... I'll try to replicate again, but this is definitely puzzling. I wonder what Ansible's hanging on? Or if it _is_ truly random chance / cosmic rays?

**Comment by thom8** [comment]
@geerlingguy you could try adding `force: yes` to the task -- http://docs.ansible.com/ansible/apt_module.html

**Comment by grasmash** [comment]
I also just hit this issue.

**Comment by geerlingguy** [comment]
@grasmash - I'm still standing by the following statement:

```
I'm going to chalk this one up to cosmic rays and network funkiness.
```

Please let me know if it happens again or if it's a one-time thing.

**Comment by shivaray** [comment]
@geerlingguy I wasn't seeing this happen just yesterday, but it's consistently blocking my `vagrant provison` today :(

**Comment by carlos-garcia** [comment]
definitively is a connection issue... but not our internet.. its ubuntu packages servers.. downloads are like 90Kbps... is there a way to make change of not going to main server but instead a mirror server?

thanks

**Comment by oxyc** [comment]
@carlos-garcia you'd have to add a pre-provision task to modify the `/etc/apt/sources.list` file and run `apt-get update`. [Docs: Add Pre- and Post-Provision Scripts](http://docs.drupalvm.com/en/latest/extras/scripts/)

I tried using http://askubuntu.com/a/37754/56258 for a while. But it kept suggestion crappy mirrors so I'm just using the defaults again.

**Comment by minorscience** [comment]
Seeing this issue from Brooklyn, NY. Just staggered 4 separate builds and 3 of them failed.
