### ISSUE TITLE
PostGRE SQL Support?

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#74]
Does this stack support PostGRE?

**Comment by geerlingguy** [comment]
At this point, no... I'm focusing on stability/flexibility in other areas first, but will eventually move to support:

  - Either Apache or Nginx for webserver layer
  - Either MariaDB or MySQL for DB layer
  - (and after all that... and when Drupal finally works fully with Postgres) Either MariaDB, MySQL, or PostgreSQL

I'll close this ticket for now, as it's going to be at least a couple months before I think we'll get to supporting Postgres.

**Comment by geerlingguy** [comment]
Now it does, as of 3.3.0 :)
