### ISSUE TITLE
unable to get zen's browsersync to work with drupalvm

### ISSUE THREAD

**Issue by frob** [geerlingguy/drupal-vm#740]
I was digging into the latest zen release and I was unable to get the browser sync option to work with drupalvm.

I was working locally and syncing files via nfs

This is drupal7 running on ubuntu1404/nignx/php5.6

I read there was a bug with the _sendfile_ paramater and virtualbox. But even after disabling it, it still doesn't work.

**Comment by oxyc** [comment]
Did you configure `options.drupalURL = 'http://drupalvm.dev';`?

**Comment by kevinquillen** [comment]
Not sure how it works in Zen, but it works for me with my theme. Same setup (except apache vs nginx). How is your Browser Sync configured?

**Comment by geerlingguy** [comment]
I'm wondering if this is something that should be approached in the Zen project—I know there was significant refactoring in the latest release, and maybe it's just something that needs fixing/docs upstream?

**Comment by frob** [comment]
There is an issue in d.o https://www.drupal.org/node/2742965

All my googling has told me about issues using varios configurations of vagrant as causing problems with browsersync so I wanted to post here as well to see if there is something configuration wise I could do.

I have the options.drupalURL set.

**Comment by oxyc** [comment]
I'm using browsersync with rsync on most of our projects. Haven't had any issues.

**Comment by frob** [comment]
The drupalvm default is nfs, does anyone have it working with nfs?

**Comment by oxyc** [comment]
Ah apparently zen doesn't convert `@import` to `<link>`-tags. BrowserSync doesn't work with `@import` afaik. There's https://www.drupal.org/project/link_css at least.

**Comment by kevinquillen** [comment]
That would be correct. You need the Link CSS module.

On Thu, Jun 16, 2016 at 3:23 PM, Oskar Schöldström <notifications@github.com

**Comment by frob** [comment]
I tried installing that and it still isn't working.

**Comment by oxyc** [comment]
Can you confirm that the HTML output, if you view source, use `<link>` elements instead of `@import` or aggregated versions.

**Comment by oxyc** [comment]
Works for me with Link CSS.

**Comment by frob** [comment]
I can verify that they are using links and not @import. I have tried apace, nginx, nfs, and rsync. This is just not working. I can even see the polling failing when I cancel the gulp watch in the inspector. But when I change files nothing happens.

**Comment by oxyc** [comment]
Could you try and see if it works with node 0.12? That's what I'm using. Except for taking enormous amounts of time it works out of the box with all defaults. Steps I did:

```
vagrant up # build new vm
composer require drupal/zen:8.7.0-alpha14
composer require drupal/components:8.1.0
composer require drupal/link_css:8.1.x-dev

drush en components link_css zen -y
drush zen zomg_amazing "Amazing name"

... disable all caching ...
... switch to the new theme

gulp watch
# editing files streams the css versions to the browser through browsersync.
```

Do you see these types of events in the watch output?

> [BS] 34 files changed (base.css, layouts.css, chroma-kss-styles.css, kss-only.css, autocomplete.css, collapsible-fieldset.css, form-item.css, form-table.css, progress-bar.css, progress-throbber.css, resizable-textarea.css, table-drag.css, breadcrumb.css, more-link.css, nav-menu.css, navbar.css, pager.css, skip-link.css, tabs.css, box.css, clearfix.css, comment.css, footer.css, header.css, hidden.css, highlight-mark.css, inline-links.css, inline-sibling.css, messages.css, print-none.css, responsive-video.css, visually-hidden.css, watermark.css, wireframe.css)

**Comment by frob** [comment]
I am using zen 6 for drupal 7

**Comment by frob** [comment]
Are you sure you are using node v0.12? kss shouldn't be able to run in that version. I have just used nvm to switch to 0.12 and it indeed does fail on kss.

```bash
✔ ~/repos/drupal/drupal7/vagrant/drupal/web/sites/all/themes/finished_turkey [7.x ↓·2|…44126]
09:51 $ gulp watch
/Users/fanderson/repos/drupal/drupal7/vagrant/drupal/web/sites/all/themes/finished_turkey/node_modules/kss/lib/kss.js:47
const KssBuilderBase = require('../builder'),
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/fanderson/repos/drupal/drupal7/vagrant/drupal/web/sites/all/themes/finished_turkey/node_modules/kss/index.js:3:18)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by oxyc** [comment]
Oh, you are correct, I'm running 0.5.6! I wonder when I upgraded hehe.

Ah I didn't try the d7 version of zen, but the gulpfile looks pretty much identical so it should work. I don't see how Vagrant or NFS could cause problems (rsync on the other hand would cause problems out of the box). Our team has been using browsersync/livereload without problems since we adopted Drupal VM a year ago.

Maybe try with debug logging to see if it mentions where it fails. https://www.browsersync.io/docs/options/#option-logLevel

**Comment by frob** [comment]
0.5.6? you mean 5.6?

Yeah, I commented out the kss and still a no go. Switching back to v5.

I found this thread https://github.com/BrowserSync/browser-sync/issues/955

Looks like this is a permissions issue. I have no idea why this is a permission issue, if someone could explain it to me, that would be great. 

I ran this command:

```bash
sudo chown -R $(whoami):admin /usr/local
```

I know what it does, but I don't know why it fixed the issue. Seeing as how I just changed the ownership of ```/usr/local``` and that could have far reaching consequences I would like to know more about why this was the fix.

**Comment by oxyc** [comment]
Guessing it's something similiar as the homebrew chaos that happened when El Capitan came out: https://news.ycombinator.com/item?id=10309576. I haven't seen that issue since I installed it while in beta though (on my third laptop since then).

**Comment by frob** [comment]
The odd thing is that broswersync worked, except in this case and I am using Yosemite.

**Comment by geerlingguy** [comment]
One note is that there have seemingly been myriad issues with not using the latest OS X release (10.11) with some versions of Vagrant; NFS mounts seem to have weird issues in that case.

Things _should_ be better with NFS/Mac OS X 10.9/10.10/Vagrant 1.8.5 now... but even if not, this looks like it could be a rabbit hole of an issue, and since other versions of browsersync/Zen/etc. seem to work okay, I'm going to close this issue and refer people upstream—it sounds like an issue where if the upstream project could upgrade it's dependencies, things could just fix themselves.

**Comment by geerlingguy** [comment]
(Also closing since I don't personally use browsersync so I can't begin to offer any depth of support for it; upstream project issue trackers are probably the best channels for further support, unless an issue can be tracked specifically to Drupal VM's configuration).
