### ISSUE TITLE
provide a token of some type to indicate to running processes this is a VM

### ISSUE THREAD

**Issue by CashWilliams** [geerlingguy/drupal-vm#743]
Use case: 
Trying to create a drush alias that works on both the host and inside the VM, php needs to have a way of identifying where it is running dynamically. This can be done with `php_uname` but that changes from machine to machine and isn't very elegant.

**Comment by oxyc** [comment]
I do something similar and always check if it's the `vagrant` user running the process.

**Comment by geerlingguy** [comment]
@oxyc - That's a good point. I've never seen a `vagrant` user on a non-Vagrant VM before, so I'm inclined to close this with the suggestion you use an alias like (in this case, specifically for a BLT-like project):

```php
$aliases['local'] = array(
  'root' => '/var/www/project/docroot',
  'uri' => 'local.project.com',
);
if (exec('whoami') != 'vagrant') {
  $aliases['local']['remote-host'] = 'local.project.com';
  $aliases['local']['remote-user'] = 'vagrant';
  $aliases['local']['ssh-options'] = '-o PasswordAuthentication=no -i ' . drush_server_home() . '/.vagrant.d/insecure_private_key';
}
```

Something along those lines.

**Comment by geerlingguy** [comment]
Tested, and this should work fine!
