### ISSUE TITLE
Adding the possibility to access the mysql server from host

### ISSUE THREAD

**Issue by tweevick** [geerlingguy/drupal-vm#745]
With the configuration files it is not possible to access the mysql server from host because of the ansible firewall role (/etc/ansible/roles/geerlingguy.firewall).

A workaround is: 
on the drupal-vm:
iptables -I INPUT -p tcp --dport 3306 -j ACCEPT
OR
adding in the file "3306":
/etc/ansible/roles/geerlingguy.firewall/defaults/main.yml
`- "3306"`

**Comment by geerlingguy** [comment]
I highly recommend against opening up port 3306 to anything more than a specific IP/range in any situation (just as a general best practice), like [this](https://github.com/geerlingguy/raspberry-pi-dramble/blob/4d6826a9da546b5a35ccaec336369d0a354b4709/playbooks/database/vars.yml#L7-L8); rather, use an SSH tunnel to connect to the MySQL server.

See instructions for doing this here:

http://docs.drupalvm.com/en/latest/extras/mysql/
