### ISSUE TITLE
Drupal JS module does not work with nginx

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#746]
I have
`drupalvm_webserver: apache`
But .htaccess is not taking into an account.

I need to use a https://www.drupal.org/project/js module.

Where should I add the nginx configuration?

My production server has this configuration for nginx:
```
    - location ^~ /js/ {
      location ~* ^/js/ {
      rewrite ^/(.*)$ /js.php?q=$1 last;}
      }
```

I tried to add these lines into nginx-vhost.conf.j2 
```
      location ^~ /js/ {
      location ~* ^/js/ {
      rewrite ^/(.*)$ /js.php?q=$1 last;}
      }
```

,but I have no result. JS callbacks do not work.

**Comment by opdavies** [comment]
If you have `drupalvm_webserver: apache`, why are you editing an Nginx configuration?

Nginx won't work with `.htaccess` files.

**Comment by geerlingguy** [comment]
You have to change the web server to nginx for nginx to be in use on Drupal VM, then reprovision. To add those lines to the vhost, you have to add it following the formatting in the Nginx role read me: https://github.com/geerlingguy/ansible-role-nginx#role-variables (see the 'extra parameters' option).
