### ISSUE TITLE
Using Drupal VM installed by composer, but provision downloads ansible-galaxy roles?

### ISSUE THREAD

**Issue by fluxsauce** [geerlingguy/drupal-vm#748]
This is almost certainly self-inflicted, but I'd like to know how to get this workflow to work.

```bash
vagrant provision
...
==> REMOVED.local: Running provisioner: ansible...
    REMOVED.local: Running ansible-galaxy...
- downloading role 'selenium', owned by arknoll
- downloading role from https://github.com/arknoll/ansible-role-selenium/archive/1.2.0.tar.gz
- extracting arknoll.selenium to /Users/jon/projects/REMOVED/build/vendor/geerlingguy/drupal-vm/provisioning/roles/arknoll.selenium
- arknoll.selenium was installed successfully
- downloading role 'newrelic', owned by franklinkim
```

and so forth.

We've got a composer-based workflow that installs Drupal to `build` and vendor to `build/vendor`. To allow `vagrant` to be executed from the project root, I've got the following `Vagrantfile`:

```rb
dir = File.dirname(__FILE__) + '/'
load dir + "build/vendor/geerlingguy/drupal-vm/Vagrantfile"
```

Provisioning succeeds; the only problem is Ansible Galaxy doesn't seem to realize that those roles exist locally and it downloads them all every time I `vagrant up` or `vagrant provision`.

Thoughts?

**Comment by joestewart** [comment]
Jon, it's by design.  see #655

**Comment by fluxsauce** [comment]
Ah. Ok, thanks for the prompt response!

**Comment by geerlingguy** [comment]
@fluxsauce - also, you can (if you're careful to disable the option during upgrades so you get the updated role versions, and if you have Ansible installed locally) follow the guide in the docs for 'overriding configurations', and use a Vagrantfile.local option to disable the install of the roles on every provision. This saves a couple minutes of time.
