### ISSUE TITLE
Can't connect to mysql after vagrant up

### ISSUE THREAD

**Issue by brentratliff** [geerlingguy/drupal-vm#749]
I have several vm's but I only have one up at a time.  My newest ones no longer allow me to connect to the db via the instructions in the docs.  I can still connect to my older vm's.  Here's the output from Sequel Pro: The SSH Tunnel has unexpectedly closed.

Used command:  /usr/bin/ssh -v -N -S none -o ControlMaster=no -o ExitOnForwardFailure=yes -o ConnectTimeout=10 -o NumberOfPasswordPrompts=3 -i /Users/brentratliff/.vagrant.d/insecure_private_key -o TCPKeepAlive=no -o ServerAliveInterval=60 -o ServerAliveCountMax=1 vagrant@192.168.88.88 -L 58118:127.0.0.1:3306

OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: Control socket " none" does not exist
debug1: Connecting to 192.168.88.88 [192.168.88.88] port 22.
debug1: fd 3 clearing O_NONBLOCK
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /Users/brentratliff/.vagrant.d/insecure_private_key type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/brentratliff/.vagrant.d/insecure_private_key-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.7 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to 192.168.88.88:22 as 'vagrant'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: server->client chacha20-poly1305@openssh.com <implicit> none
debug1: kex: client->server chacha20-poly1305@openssh.com <implicit> none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:i5ulGQSaClBuMlPY7WWiycJA6WN8XqlTQZDmLkqImSs
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
SHA256:i5ulGQSaClBuMlPY7WWiycJA6WN8XqlTQZDmLkqImSs.
Please contact your system administrator.
Add correct host key in /Users/brentratliff/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /Users/brentratliff/.ssh/known_hosts:3
ECDSA host key for 192.168.88.88 has changed and you have requested strict checking.
Host key verification failed.

**Comment by geerlingguy** [comment]
@brentratliff - "Host key verification failed." in this case just means that you're trying to connect to the same IP address (192.168.88.88) but the VM has been recreated, and has a new host key. This is a security measure used to help protect against MITM attacks, but in this case, since you know you recreated the VM, you can ignore it. You just need to delete the offending key.

See this article for how I do it: http://www.jeffgeerling.com/blog/2016/fastest-way-reset-host-key-when-rebuilding-servers-on-same-ip-or-hostname-frequently
