### ISSUE TITLE
On linux mint rebecca could not execute vagrant up

### ISSUE THREAD

**Issue by artem0793** [geerlingguy/drupal-vm#75]
I see

There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The box 'geerlingguy/ubuntu1404' could not be found.

After execute: vagrant box add geerlingguy/ubuntu1404 http://old-releases.ubuntu.com/releases/trusty/ubuntu-14.04-server-i386.iso

error reproduced.

**Comment by geerlingguy** [comment]
@artem0793 - I'm guessing that the version of Vagrant may be too old to use the new box system. Can you run the command `vagrant --version` and see what version you're running? If it's < 1.7.0, you will need to install a newer version of Vagrant to make sure it downloads the box successfully.

**Comment by artem0793** [comment]
Thank
