### ISSUE TITLE
Drupal VM - Failed Setup

### ISSUE THREAD

**Issue by amstaker** [geerlingguy/drupal-vm#757]
Drupal VM install clean windows 7 install, running virtualbox 5.022 r108108.  Vagrant 1.8.4.

drupalvm: /tmp/vagrant-shell: line 79: ansible-playbook: command not found
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. 

Rerunning `vagrant provision` the box then appears to walk through configuration and setup and brings the box up.

I am using the `vagrant-hostsupdate` and the `vagrant-auto_network plugins`.   `config.yml` is set to default with the exception of the required 0.0.0.0 change to the vagrant ip.

`{ drupal-vm } master » vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Box 'geerlingguy/ubuntu1604' could not be found. Attempting to find and install...
    drupalvm: Box Provider: virtualbox
    drupalvm: Box Version: >= 0
==> drupalvm: Loading metadata for box 'geerlingguy/ubuntu1604'
    drupalvm: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1604
==> drupalvm: Adding box 'geerlingguy/ubuntu1604' (v1.0.2) for provider: virtualbox
    drupalvm: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604/versions/1.0.2/providers/virtualbox.box
    drupalvm:
==> drupalvm: Successfully added box 'geerlingguy/ubuntu1604' (v1.0.2) for 'virtualbox'!
==> drupalvm: Preparing master VM for linked clones...
    drupalvm: This is a one time operation. Once the master VM is prepared,
    drupalvm: it will be used as a base for linked clones, making the creation
    drupalvm: of new VMs take milliseconds on a modern system.
==> drupalvm: Importing base box 'geerlingguy/ubuntu1604'...
==> drupalvm: Cloning VM...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Mounting shared folders...
    drupalvm: /vagrant => C:/Users/astaker/drupal-vm
    drupalvm: /var/www/drupalvm => C:/Users/astaker/drupal-vm
==> drupalvm: Running provisioner: shell...
    drupalvm: Running: C:/Users/astaker/.babun/cygwin/tmp/vagrant-shell20160624-5116-ccumzk.sh
==> drupalvm: mesg: ttyname failed: Inappropriate ioctl for device
==> drupalvm: Installing Ansible dependencies and Git.
==> drupalvm: Hit:1 http://security.ubuntu.com/ubuntu xenial-security InRelease
==> drupalvm: Hit:2 http://us.archive.ubuntu.com/ubuntu xenial InRelease
==> drupalvm: Hit:3 http://us.archive.ubuntu.com/ubuntu xenial-updates InRelease
==> drupalvm: Hit:4 http://ppa.launchpad.net/ansible/ansible/ubuntu xenial InRelease
==> drupalvm: Hit:5 http://us.archive.ubuntu.com/ubuntu xenial-backports InRelease
==> drupalvm: E
==> drupalvm: :
==> drupalvm: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> drupalvm: E
==> drupalvm: :
==> drupalvm: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
==> drupalvm: E
==> drupalvm: :
==> drupalvm: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> drupalvm: E
==> drupalvm: :
==> drupalvm: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
==> drupalvm: Installing pip.
==> drupalvm: --2016-06-24 18:18:57--  https://bootstrap.pypa.io/get-pip.py
==> drupalvm: Resolving bootstrap.pypa.io (bootstrap.pypa.io)...
==> drupalvm: 23.235.44.175
==> drupalvm: Connecting to bootstrap.pypa.io (bootstrap.pypa.io)|23.235.44.175|:443...
==> drupalvm: connected.
==> drupalvm: HTTP request sent, awaiting response...
==> drupalvm: 200 OK
==> drupalvm: Length:
==> drupalvm: 1524722
==> drupalvm:  (1.5M)
==> drupalvm:  [text/x-python]
==> drupalvm: Saving to: 'get-pip.py'
==> drupalvm:
==> drupalvm:      0K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:   3%
==> drupalvm:   746K
==> drupalvm:  2s
==> drupalvm:
==> drupalvm:     50K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:   6%
==> drupalvm:  1.47M
==> drupalvm:  1s
==> drupalvm:
==> drupalvm:    100K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  10%
==> drupalvm:  1.53M
==> drupalvm:  1s
==> drupalvm:
==> drupalvm:    150K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  13%
==> drupalvm:  23.0M
==> drupalvm:  1s
==> drupalvm:
==> drupalvm:    200K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  16%
==> drupalvm:  47.9M
==> drupalvm:  1s
==> drupalvm:
==> drupalvm:    250K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  20%
==> drupalvm:  1.49M
==> drupalvm:  1s
==> drupalvm:
==> drupalvm:    300K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  23%
==> drupalvm:  29.2M
==> drupalvm:  1s
==> drupalvm:
==> drupalvm:    350K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  26%
==> drupalvm:  42.5M
==> drupalvm:  0s
==> drupalvm:
==> drupalvm:    400K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: ...... .......... .......... .......... .......... 30%  131M 0s
==> drupalvm:    450K .......... .......... .......... .......... .......... 33%  633M 0s
==> drupalvm:    500K .......... .......... .......... .......... .......... 36%  557M 0s
==> drupalvm:    550K .......... .......... .....
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .... 40% 1.71M 0s
==> drupalvm:    600K .......... .......... .......... .......... .......... 43%  509M 0s
==> drupalvm:    650K .....
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  .......... .......... .......... 47% 65.5M 0s
==> drupalvm:    700K .......... .........
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .... .......... .......... 50% 21.2M 0s
==> drupalvm:    750K .......... .......... .......... ...
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  53%
==> drupalvm:   117M
==> drupalvm:  0s
==> drupalvm:
==> drupalvm:    800K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .......... .......... .......... 57%  161M 0s
==> drupalvm:    850K .......... .......... .......... .......... .....
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  60%
==> drupalvm:   163M
==> drupalvm:  0s
==> drupalvm:
==> drupalvm:    900K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .... .......... .......... 63%  102M 0s
==> drupalvm:    950K .......... .......... .......... .......... .......... 67%  597M 0s
==> drupalvm:   1000K .......... .......... .......... .........
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:  70%
==> drupalvm:   164M
==> drupalvm:  0s
==> drupalvm:
==> drupalvm:   1050K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .. .......... .......... .......... .......... 73% 93.4M 0s
==> drupalvm:   1100K .......... .......... .......... .....
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: ....... 77% 1.83M 0s
==> drupalvm:   1150K .......... .......
==> drupalvm: ... .......... .......... .........
==> drupalvm: .
==> drupalvm:  80%
==> drupalvm:  35.7M
==> drupalvm:  0s
==> drupalvm:
==> drupalvm:   1200K
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: ..... .......... .......... .......... .......... 83%  142M 0s
==> drupalvm:   1250K .......... ...
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: ......... .......... 87% 24.2M 0s
==> drupalvm:   1300K .......... .......... .......... .......... .......... 90%  488M 0s
==> drupalvm:   1350K .......... .......... .......... .......... .......... 94%  588M 0s
==> drupalvm:   1400K .......... .......... .......... .......... .......... 97%  580M 0s
==> drupalvm:   1450K .....
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm: .
==> drupalvm:
==> drupalvm: .......... ........             100% 60.5M=0.2s
==> drupalvm:
==> drupalvm: 2016-06-24 18:18:57 (6.14 MB/s) - 'get-pip.py' saved [1524722/1524722]
==> drupalvm: /tmp/tmpw64ssN/pip.zip/pip/req/req_install.py:999: UserWarning: Module pip was already imported from /tmp/tmpw64ssN/pip.zip/pip/__init__.py, but /usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg is being added to sys.path
==> drupalvm: Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages/pip-8.1.2-py2.7.egg
==> drupalvm: Collecting setuptools
==> drupalvm:   Downloading setuptools-23.1.0-py2.py3-none-any.whl (435kB)
==> drupalvm: Collecting wheel
==> drupalvm:   Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
==> drupalvm: Installing collected packages: setuptools, wheel
==> drupalvm: Successfully installed setuptools-23.1.0 wheel-0.29.0
==> drupalvm: Installing required build tools.
==> drupalvm: E
==> drupalvm: :
==> drupalvm: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
==> drupalvm: E
==> drupalvm: :
==> drupalvm: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?
==> drupalvm: Installing required python modules.
==> drupalvm: Collecting paramiko
==> drupalvm:   Downloading paramiko-2.0.1-py2.py3-none-any.whl (171kB)
==> drupalvm: Collecting pyyaml
==> drupalvm:   Downloading PyYAML-3.11.zip (371kB)
==> drupalvm: Collecting jinja2
==> drupalvm:   Downloading Jinja2-2.8-py2.py3-none-any.whl (263kB)
==> drupalvm: Collecting markupsafe
==> drupalvm:   Downloading MarkupSafe-0.23.tar.gz
==> drupalvm: Collecting pyasn1>=0.1.7 (from paramiko)
==> drupalvm:   Downloading pyasn1-0.1.9-py2.py3-none-any.whl
==> drupalvm: Collecting cryptography>=1.1 (from paramiko)
==> drupalvm:   Downloading cryptography-1.4.tar.gz (399kB)
==> drupalvm: Collecting idna>=2.0 (from cryptography>=1.1->paramiko)
==> drupalvm:   Downloading idna-2.1-py2.py3-none-any.whl (54kB)
==> drupalvm: Collecting six>=1.4.1 (from cryptography>=1.1->paramiko)
==> drupalvm:   Downloading six-1.10.0-py2.py3-none-any.whl
==> drupalvm: Requirement already satisfied (use --upgrade to upgrade): setuptools>=11.3 in /usr/local/lib/python2.7/dist-packages (from cryptography>=1.1->paramiko)
==> drupalvm: Collecting enum34 (from cryptography>=1.1->paramiko)
==> drupalvm:   Downloading enum34-1.1.6-py2-none-any.whl
==> drupalvm: Collecting ipaddress (from cryptography>=1.1->paramiko)
==> drupalvm:   Downloading ipaddress-1.0.16-py27-none-any.whl
==> drupalvm: Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko)
==> drupalvm:   Downloading cffi-1.7.0.tar.gz (400kB)
==> drupalvm:     Complete output from command python setup.py egg_info:
==> drupalvm:     unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
==> drupalvm:     unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
==> drupalvm:
==> drupalvm:         No working compiler found, or bogus compiler options
==> drupalvm:         passed to the compiler from Python's distutils module.
==> drupalvm:         See the error messages above.
==> drupalvm:         (If they are about -mno-fused-madd and you are on OS/X 10.8,
==> drupalvm:         see http://stackoverflow.com/questions/22313407/ .)
==> drupalvm:
==> drupalvm:     ----------------------------------------
==> drupalvm: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2z2Grb/cffi/
==> drupalvm: Installing Ansible.
==> drupalvm: Collecting ansible
==> drupalvm:   Downloading ansible-2.1.0.0.tar.gz (1.9MB)
==> drupalvm: Collecting paramiko (from ansible)
==> drupalvm:   Using cached paramiko-2.0.1-py2.py3-none-any.whl
==> drupalvm: Collecting jinja2 (from ansible)
==> drupalvm:   Using cached Jinja2-2.8-py2.py3-none-any.whl
==> drupalvm: Collecting PyYAML (from ansible)
==> drupalvm:   Using cached PyYAML-3.11.zip
==> drupalvm: Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/local/lib/python2.7/dist-packages (from ansible)
==> drupalvm: Collecting pycrypto>=2.6 (from ansible)
==> drupalvm:   Downloading pycrypto-2.6.1.tar.gz (446kB)
==> drupalvm: Collecting pyasn1>=0.1.7 (from paramiko->ansible)
==> drupalvm:   Using cached pyasn1-0.1.9-py2.py3-none-any.whl
==> drupalvm: Collecting cryptography>=1.1 (from paramiko->ansible)
==> drupalvm:   Using cached cryptography-1.4.tar.gz
==> drupalvm: Collecting MarkupSafe (from jinja2->ansible)
==> drupalvm:   Using cached MarkupSafe-0.23.tar.gz
==> drupalvm: Collecting idna>=2.0 (from cryptography>=1.1->paramiko->ansible)
==> drupalvm:   Using cached idna-2.1-py2.py3-none-any.whl
==> drupalvm: Collecting six>=1.4.1 (from cryptography>=1.1->paramiko->ansible)
==> drupalvm:   Using cached six-1.10.0-py2.py3-none-any.whl
==> drupalvm: Collecting enum34 (from cryptography>=1.1->paramiko->ansible)
==> drupalvm:   Using cached enum34-1.1.6-py2-none-any.whl
==> drupalvm: Collecting ipaddress (from cryptography>=1.1->paramiko->ansible)
==> drupalvm:   Using cached ipaddress-1.0.16-py27-none-any.whl
==> drupalvm: Collecting cffi>=1.4.1 (from cryptography>=1.1->paramiko->ansible)
==> drupalvm:   Using cached cffi-1.7.0.tar.gz
==> drupalvm:     Complete output from command python setup.py egg_info:
==> drupalvm:     unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
==> drupalvm:     unable to execute 'x86_64-linux-gnu-gcc': No such file or directory
==> drupalvm:
==> drupalvm:         No working compiler found, or bogus compiler options
==> drupalvm:         passed to the compiler from Python's distutils module.
==> drupalvm:         See the error messages above.
==> drupalvm:         (If they are about -mno-fused-madd and you are on OS/X 10.8,
==> drupalvm:         see http://stackoverflow.com/questions/22313407/ .)
==> drupalvm:
==> drupalvm:     ----------------------------------------
==> drupalvm: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-BBM9FM/cffi/
==> drupalvm: Installing Ansible roles from requirements file, if available.
==> drupalvm: sudo
==> drupalvm: :
==> drupalvm: ansible-galaxy: command not found
==> drupalvm: Running Ansible provisioner defined in Vagrantfile.

**Comment by geerlingguy** [comment]
It looks like the problem stems from the box not allowing the right apt dependencies to be installed because the latest version of the Ubuntu 16.04 box might have an issue with apt auto updates running right away.

I'm going to look into this issue upstream. The reason it works after this initial failure is the auto updates that lock out apt are completed by the time you run the second provision.

**Comment by geerlingguy** [comment]
See upstream issue: https://github.com/geerlingguy/packer-ubuntu-1604/issues/7

**Comment by geerlingguy** [comment]
I'm uploading a new base box version (1.0.3) now. Once that's up (sometime later today... someday St. Louis will get good upstream bandwidth!), you can do a `vagrant destroy` then `vagrant box update` to get the latest version.

**Comment by geerlingguy** [comment]
(But I won't close this issue until I get that new box version up).

**Comment by geerlingguy** [comment]
This should be fixed. Tested with 1.0.3. Please see if it fixes the issue for you!

**Comment by amstaker** [comment]
Cool, I'm going to do some testing on this.  I'll let you know how this works out, thanks for all your help on this...
