### ISSUE TITLE
Synced Folders not always mounting with Vagrant 1.8.4

### ISSUE THREAD

**Issue by maxasus123** [geerlingguy/drupal-vm#759]
I ues "vagrant_synced_folders  type: nfs" it's not work.
Folder is not mount Folder.

**Comment by geerlingguy** [comment]
Hmm... can you give more information about what led to this error, maybe paste the full log in your terminal, and also what your `config.yml` has set up for synced folders?

Also, what OS are you using on your host computer?

**Comment by maxasus123** [comment]
@geerlingguy I use Mac OSX. I use drpualvm laste version. And not show error.
 vagrant_synced_folders not mount folder on my computer. 
Now, I fix "sudo mount -o '' 192.168.88.1:'/Users/Mac/MyWork/Server/web' /var/www/html"  on vm.

**Comment by geerlingguy** [comment]
@maxasus123 - If you use the latest Drupal VM version and then run `vagrant reload` does the folder mount correctly? Are there any other errors when you run `reload` or `up`?

**Comment by maxasus123** [comment]
@geerlingguy I try vagrant reload many time not work.

**Comment by joestewart** [comment]
Is it vagrant 1.8.4?  We're still seeing nfs mount issues with 1.8.4.  Related upstream issue: https://github.com/mitchellh/vagrant/pull/7492

**Comment by maxasus123** [comment]
@joestewart Yes, I use vagrant 1.8.4.

**Comment by mark-casias** [comment]
I can confirm that downgrading to 1.8.1 corrected my NFS mounting issue.

**Comment by geerlingguy** [comment]
To all following this issue—it may be related to https://github.com/geerlingguy/drupal-vm/issues/734 — can you make sure you're also running the latest version of Drupal VM (at least tag 3.1.2) or apply this change manually to see if it resolves the error (requires `vagrant reload` to remount): https://github.com/geerlingguy/drupal-vm/pull/737/files

**Comment by geerlingguy** [comment]
Other than that, follow the upstream Vagrant issue. Hopefully 1.8.5 will fix this and other small issues encountered as a result of the 1.8.4 release!

**Comment by geerlingguy** [comment]
Since there doesn't seem to be anything else I can do to make this work better (besides recommend using 1.8.4 and latest Drupal VM 3.x release, or applying https://github.com/geerlingguy/drupal-vm/commit/fdd347e6b27e3f754d131722959a5eca85317a46 manually to an older version), I'm going to mark this closed, and cross my fingers in hopes that Vagrant 1.8.5 fixes this issue without causing others :P

**Comment by shrop** [comment]
Drupal VM 3.1.2 + Vagrant 1.8.4 is a fix for this?

**Comment by mark-casias** [comment]
DrupalVM 3.1.2 + Vagrant 1.8.1 works.

**Comment by geerlingguy** [comment]
Right now the path forward for this is:

- Run Drupal VM 3.1.2 with Vagrant 1.8.1
- Run Drupal VM 3.1.2 with Vagrant 1.8.4 and VMware or Parallels instead of VirtualBox
- Monkey patch Vagrant 1.8.4 with https://github.com/mitchellh/vagrant/pull/7492

Vagrant 1.8.5 should fix the issue in VirtualBox whenever it's released; and I can't seem to reproduce the issue in VMware Fusion on my Mac currently.

I'll also be releasing a small patch version of Drupal VM to fix a couple other tiny setup bugs that some people have encountered.

**Comment by marikomay** [comment]
I have tried three different configurations with no success.

1) Drupal 7 with CentOS 7 using drush make. The build failed:

fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "There was an issue creating /var/www/drupalvm/drupal as requested: [Errno 13] Permission denied: '/var/www/drupalvm/drupal'", "path": "/var/www/drupalvm/drupal", "state": "absent”

I did ‘vagrant destroy’, deleted the shared folder /Users/UserName/d7 (which was created but empty), and tried a new configuration:

2)  Default configuration with no customization.

The VM was created and the site successfully installed (accessible at http://drupalvm.dev/). However, the shared folder was not created. No sign of it in the drupal-vm folder as expected. Finally, I tried:

3) Default config but with local_path set to /Users/UserName/d8.

As before, the site was installed. However, this time the shared folder was created but it was empty.

My system:
OS X Yosemite (version 10.10)
Drupal VM 3.13
Vagrant 1.8.4
VirtualBox 5.0.24
Ansible 2.1.0

**Comment by geerlingguy** [comment]
@marikomay - It looks like the share is simply not working correctly. Can you log into the VM (with `vagrant ssh`) and run `sudo mount` to list all the mounted volumes, then paste that list here?

**Comment by marikomay** [comment]
Here is the return for sudo mount:

sysfs on /sys type sysfs (rw,nosuid,nodev,noexec,relatime)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
udev on /dev type devtmpfs (rw,nosuid,relatime,size=490136k,nr_inodes=122534,mode=755)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=5,mode=620,ptmxmode=000)
tmpfs on /run type tmpfs (rw,nosuid,noexec,relatime,size=101620k,mode=755)
/dev/mapper/vagrant--vg-root on / type ext4 (rw,relatime,errors=remount-ro,data=ordered)
securityfs on /sys/kernel/security type securityfs (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
tmpfs on /run/lock type tmpfs (rw,nosuid,nodev,noexec,relatime,size=5120k)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,mode=755)
cgroup on /sys/fs/cgroup/systemd type cgroup (rw,nosuid,nodev,noexec,relatime,xattr,release_agent=/lib/systemd/systemd-cgroups-agent,name=systemd,nsroot=/)
pstore on /sys/fs/pstore type pstore (rw,nosuid,nodev,noexec,relatime)
cgroup on /sys/fs/cgroup/freezer type cgroup (rw,nosuid,nodev,noexec,relatime,freezer,nsroot=/)
cgroup on /sys/fs/cgroup/pids type cgroup (rw,nosuid,nodev,noexec,relatime,pids,nsroot=/)
cgroup on /sys/fs/cgroup/memory type cgroup (rw,nosuid,nodev,noexec,relatime,memory,nsroot=/)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (rw,nosuid,nodev,noexec,relatime,cpu,cpuacct,nsroot=/)
cgroup on /sys/fs/cgroup/blkio type cgroup (rw,nosuid,nodev,noexec,relatime,blkio,nsroot=/)
cgroup on /sys/fs/cgroup/perf_event type cgroup (rw,nosuid,nodev,noexec,relatime,perf_event,nsroot=/)
cgroup on /sys/fs/cgroup/cpuset type cgroup (rw,nosuid,nodev,noexec,relatime,cpuset,nsroot=/)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (rw,nosuid,nodev,noexec,relatime,net_cls,net_prio,nsroot=/)
cgroup on /sys/fs/cgroup/devices type cgroup (rw,nosuid,nodev,noexec,relatime,devices,nsroot=/)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb,nsroot=/)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)
debugfs on /sys/kernel/debug type debugfs (rw,relatime)
mqueue on /dev/mqueue type mqueue (rw,relatime)
systemd-1 on /proc/sys/fs/binfmt_misc type autofs (rw,relatime,fd=36,pgrp=1,timeout=0,minproto=5,maxproto=5,direct)
sunrpc on /run/rpc_pipefs type rpc_pipefs (rw,relatime)
nfsd on /proc/fs/nfsd type nfsd (rw,relatime)
fusectl on /sys/fs/fuse/connections type fusectl (rw,relatime)
/dev/sda1 on /boot type ext2 (rw,relatime,block_validity,barrier,user_xattr,acl)
tmpfs on /run/user/900 type tmpfs (rw,nosuid,nodev,relatime,size=101620k,mode=700,uid=900,gid=900)

**Comment by geerlingguy** [comment]
@marikomay - It looks like the mount isn't being created—when you do a `vagrant reload`, is there any error around the time when it mentions the NFS setup?

**Comment by marikomay** [comment]
@geerlingguy - Hmm. When I run vagrant reload, this is the only part that mentions NFS:

==> drupalvm: Machine booted and ready!
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
Passxxxxx
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Machine already provisioned.

This sharing folders business seems to be an ongoing problem. Do you happen to know if VMware Fusion is better in this area? I may try upgrading to El Capitan, though I don't how much help that would be.

**Comment by marikomay** [comment]
So I upgraded from OS X 10.10 to OS X 10.11 and that fixed the problem. My shared folder mounts and everything is working. Yay. Thank you @geerlingguy for all your work on this super cool project.

**Comment by geerlingguy** [comment]
@marikomay - Strange! I hadn't heard of people having issues on 10.10... but maybe something in Vagrant 1.8.4 changed something that broke NFS mounts on VirtualBox in 10.10 only? Who knows, but glad you could get it working!
