### ISSUE TITLE
Add xhgui 

### ISSUE THREAD

**Issue by mikecrittenden** [geerlingguy/drupal-vm#76]
XHGUI is a graphical interface for xhprof built on with MongoDB. 

Thoughts on adding it to drupal-vm? Would the Mongo dependency add too much cruft you think?

**Comment by geerlingguy** [comment]
I think that might be a little too much for my liking; I typically either use the built-in XHProf UI (which uses GraphViz to build nice visual callgraphs), or the one included with the Drupal XHProf module (which isn't as fully-featured, but works in a pinch).

Check out @alimac's post for more info: [XHProf and Drupal|http://alim.ac/writes/xhprof-and-drupal-in-two-flavors/#xhprof-native-output-1]

(I'll try to make it more clear in the README/docs how to set this up easily, too.)

**Comment by mikecrittenden** [comment]
Sure thing, thanks for the response Jeff.

**Comment by jamesrward** [comment]
@mikecrittenden I made a quick and dirty post-provisioning script that adds xhgui and has it run on every page request.  I'm only using ubuntu so it would need to be modified for centos:

https://gist.github.com/jamesrward/6a9b4f9ec44fbddfed4dbafe167374fa

This puts xhgui at xhgui.yourdomain.dev.
