### ISSUE TITLE
php 7 and mcrypt

### ISSUE THREAD

**Issue by cdmo** [geerlingguy/drupal-vm#760]
A bit new to DrupalVM, so I'm probably missing something obvious, but I can't seem to get `mcrypt` to work on my CentOS 7 PHP 7 box. I've tried adding the remi repo for mcrypt (`php70-php-mcrypt.x86_64`) but PHP doesn't see it after restarting apache. Any idea what's going on? mcrypt is an option in the ldap suite of Drupal modules.

Thanks.

**Comment by geerlingguy** [comment]
I know a few other people were asking about this as well. I haven't had a chance to test getting mcrypt on CentOS 7—but if you just set your list of PHP packages inside `config.yml` to the following, then `vagrant provision` again, does that work?

```yaml
php_packages:
  - php
  - php-cli
  - php-common
  - php-devel
  - php-fpm
  - php-gd
  - php-imap
  - php-ldap
  - php-mbstring
  - php-opcache
  - php-pdo
  - php-pear
  - php-pecl-apcu
  - php-xml
  - php-xmlrpc
  - php-mcrypt
```

**Comment by cdmo** [comment]
Yes, that worked. Awesome, thanks for the very fast working fix!

**Comment by geerlingguy** [comment]
No problem!
