### ISSUE TITLE
PHP 5.6 needs to state that you need to load ubuntu1404 box

### ISSUE THREAD

**Issue by esteinborn** [geerlingguy/drupal-vm#765]
On page: http://docs.drupalvm.com/en/latest/other/php-56/

It provides all the settings to load PHP 5.6 but fails to include the very important `vagrant_box` setting that needs to be set to ubuntu 1404, not 1604.

I'm proving a PR to add this to the list of variables in your config.yml.

**Comment by geerlingguy** [comment]
Correct, good catch... I think I've tripped up a few people with that.

Hopefully we can pull that change back out again once we get https://github.com/geerlingguy/drupal-vm/pull/714 in.
