### ISSUE TITLE
Failing to Copy Nginx vhosts into place

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#769]
What could be the source of this do you think?  Something in my `config.yml`? Worked a few days ago with same `config.yml`but ansible-galaxy downloaded updated tasks today. Can't remember how to temporarily turn this off. ansible-galaxy download adds 15 mins each failure here :-(

    TASK [Copy Nginx vhosts into place.] *******************************************
    fatal: [dbapc]: FAILED! => \
    {"failed": true, "msg": "ERROR! failed to resolve remote temporary directory from \
    ansible-tmp-1467216529.41-44739228166008:  \
    `( umask 22 && mkdir -p \"$( echo $HOME/.ansible/tmp/ansible-tmp-1467216529.41-44739228166008 )\" \
    && echo \"$( echo $HOME/.ansible/tmp/ansible-tmp-1467216529.41-44739228166008 )\" )` \
     returned empty string"}

**Comment by geerlingguy** [comment]
@iainhouston - usually this is some weird temporary issue. If you provision again, does it work on the second try?

**Comment by iainhouston** [comment]
You're quite right. second provisioning worked fine. thanks.

**Comment by geerlingguy** [comment]
I blame cosmic rays :)
