### ISSUE TITLE
Ansible error

### ISSUE THREAD

**Issue by jordanmaslyn** [geerlingguy/drupal-vm#771]
```ERROR: [DEPRECATED]: include + with_items is a removed deprecated feature.  Please update your playbooks.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.```

I get this error when provisioning and it seems to be keeping me from being able to boot up my vm. Any thoughts?

**Comment by geerlingguy** [comment]
@jordanmaslyn - Hmm... I'm not getting that error locally—also that should just be a notice, not something that would fail the build. Can you give any other lines from the output, or is that all that's returned?

Also, please run `ansible --version` to see what version you're running; latest is 2.1.0, though 2.0.1 should work too.

**Comment by geerlingguy** [comment]
And finally, are you running Drupal VM latest, or an older version?

**Comment by enzolutions** [comment]
I have the same issue but as @geerlingguy said I I had ansible 1.9.x and after update that error was gone.

**Comment by geerlingguy** [comment]
Going to close this issue, as I'm pretty sure it's a version issue; just make sure you've upgraded to 2.x and things should work.
