### ISSUE TITLE
How to add and apply a php.ini setting?

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#772]
For example: I would like to add the 'xdebug.profiler_enable_trigger = 1' setting.
Regards, Artu.

**Comment by geerlingguy** [comment]
The options that are easily configurable for Xdebug are listed in the Xdebug role's documentation: https://github.com/geerlingguy/ansible-role-php-xdebug

If there's a setting you think should be included, please file an issue in that upstream repository (it's used across a bunch of different projects besides Drupal VM). Also, for a quick fix, you could add a script or post provision task file to copy over a settings file into the right PHP config directory with any extra custom settings.
