### ISSUE TITLE
Provisioning Fails with Solr 6.1.0

### ISSUE THREAD

**Issue by attheshow** [geerlingguy/drupal-vm#777]
I'm trying to add the latest version of Solr (6.1.0) to my machine. I've changed the config.yml file to:

`solr_version: "6.1.0"`

...but it fails each time with the error:

> TASK [geerlingguy.solr : Check current list of Solr cores.] ********************
fatal: [drupalvm]: FAILED! => {"changed": false, "content": "", "failed": true, "msg": "Status code was not [200]: Request failed: <urlopen error [Errno 111] Connection refused>", "redirected": false, "status": -1, "url": "http://localhost:8983/solr/admin/cores"}

**Comment by attheshow** [comment]
I noticed that the geerlinguy.solr role README.md file mentions the ability to explicitly name your `solr_cores`. I'm trying to do that now to see if it might be a required option for 6.1.0.

**Comment by geerlingguy** [comment]
@attheshow - does vagrant up (on a fresh VM) work with the normal/default 5.x version of Solr? I know I have the role working with 6.x outside of Drupal VM, but I haven't explicitly tested 6.1 with Drupal VM yet.

**Comment by attheshow** [comment]
@geerlingguy I'm going to try building it one more time with 6.1.0 then I'll switch to 5.5.2 and report back.

**Comment by attheshow** [comment]
I'm getting a different error after adding values for `solr_cores` and `solr_mirror`. This is still on 6.1.0. I'll try 5.5.2 now.

> TASK [geerlingguy.solr : Expand Solr.] *****************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_7x2Nua/ansible_module_unarchive.py\", line 751, in <module>\r\n    main()\r\n  File \"/tmp/ansible_7x2Nua/ansible_module_unarchive.py\", line 706, in main\r\n    handler = pick_handler(src, dest, file_args, module)\r\n  File \"/tmp/ansible_7x2Nua/ansible_module_unarchive.py\", line 637, in pick_handler\r\n    if obj.can_handle_archive():\r\n  File \"/tmp/ansible_7x2Nua/ansible_module_unarchive.py\", line 584, in can_handle_archive\r\n    if self.files_in_archive:\r\n  File \"/tmp/ansible_7x2Nua/ansible_module_unarchive.py\", line 515, in files_in_archive\r\n    for filename in tf.getnames():\r\n  File \"/usr/lib/python2.7/tarfile.py\", line 1817, in getnames\r\n    return [tarinfo.name for tarinfo in self.getmembers()]\r\n  File \"/usr/lib/python2.7/tarfile.py\", line 1809, in getmembers\r\n    self._load()        # all members, we first have to\r\n  File \"/usr/lib/python2.7/tarfile.py\", line 2384, in _load\r\n    tarinfo = self.next()\r\n  File \"/usr/lib/python2.7/tarfile.py\", line 2319, in next\r\n    self.fileobj.seek(self.offset)\r\n  File \"/usr/lib/python2.7/gzip.py\", line 434, in seek\r\n    self.read(1024)\r\n  File \"/usr/lib/python2.7/gzip.py\", line 261, in read\r\n    self._read(readsize)\r\n  File \"/usr/lib/python2.7/gzip.py\", line 308, in _read\r\n    self._read_eof()\r\n  File \"/usr/lib/python2.7/gzip.py\", line 347, in _read_eof\r\n    hex(self.crc)))\r\nIOError: CRC check failed 0x2b070218 != 0xe8183b60L\r\n", "msg": "MODULE FAILURE", "parsed": false, "stat": {"exists": false}}

NO MORE HOSTS LEFT *************************************************************

**Comment by attheshow** [comment]
Same issue on 5.5.2.

**Comment by attheshow** [comment]
Just a quick update:

5.5.2 is operating correctly after I ran `chmod -r 777 ~/.ansible` on my Mac (and also specified the solr_cores and solr_mirror in the config.yml file). So I think the last error I posted was coming from the fact that I had recently updated Ansible and the permissions on that directory somehow changed. I wasn't able to get 6.1.0 working.

**Comment by fubarhouse** [comment]
Is there a recommended upgrade path for Solr - I'm curious and interested to get off version 4.x.

**Comment by geerlingguy** [comment]
@fubarhouse - The easiest way is to just uninstall it (e.g. nuke the VM) and then set the newer version you want.

Last time I tried (which was before @attheshow's attempt above), I was able to use both 6.x and 5.x, but 6.x works standalone right now regardless (the tests are passing in the upstream role).

**Comment by geerlingguy** [comment]
It looks like it could just be a Java version issue; by default any of the supported guest OSes (besides Ubuntu 16.04) install Java 7 or earlier. You need Java 8 for Solr 6, and this could be the issue... I'm testing the fix and will document this requirement/required changes if this turns out to be the culprit.

**Comment by geerlingguy** [comment]
So it is definitely because of Java 7... see notes here for switching version to Java 8 (requires a reprovision): https://github.com/geerlingguy/ansible-role-java#example-playbook-install-openjdk-8

**Comment by geerlingguy** [comment]
@fubarhouse - Yeah, Ubuntu 12.04 is quickly becoming the 'RHEL 5' of the Ubuntu world... so few people on the bleeding edge are using it anymore, so I'd expect more and more packages to stop supporting it (at least easily) as they release newer major versions.

**Comment by fubarhouse** [comment]
I'm interested in getting off it, but unfortunately my agency's Acquia servers still run on 12.04 - I won't be able to change until that changes...

I'm actually using 16.04 as my laptop OS now, and in terms of performance it's significantly better than 12.04. I like it!
