### ISSUE TITLE
Unreachable server

### ISSUE THREAD

**Issue by enzolutions** [geerlingguy/drupal-vm#778]
I am trying to follow the guide [https://github.com/geerlingguy/drupal-vm/tree/master/examples/prod](https://github.com/geerlingguy/drupal-vm/tree/master/examples/prod)

 After executing the command

```
ansible-playbook -i examples/prod/inventory examples/prod/bootstrap/init.yml -e "ansible_ssh_user=root"
```

I got the following error

<img width="1186" alt="ansible-unreachable" src="https://cloud.githubusercontent.com/assets/907914/16609093/443bc932-430e-11e6-8475-b0264eeae36b.png">

I am confused about what I need to put in SUDO my local machine password? or the encrypted password I did following the instructions, the problem is in my Digital Ocean Droplet I didn't do anything release to that password, there is a missing step?

**Comment by geerlingguy** [comment]
@enzolutions - I'm presuming you're trying to run this on the DigitalOcean droplet? If you use `--ask-sudo-pass` and set the prod inventory to point to that Droplet's IP address or domain name, then that sudo password would be the sudo password you choose to set up on the DigitalOcean droplet.

See:

> Ansible will prompt you for your admin account's sudo password (the same as the password you encrypted and saved as `admin_password`). Enter it and press return.

**Comment by geerlingguy** [comment]
Closing for now; please let me know if the above information doesn't help resolve the issue.
