### ISSUE TITLE
Intermittent "connection refused on port 80" errors

### ISSUE THREAD

**Issue by mikecrittenden** [geerlingguy/drupal-vm#78]
Every few minutes or so, sites on drupal-vm will stop responding for me. and curl'ing them returns: 

    curl: (7) Failed to connect to sitename.vm port 80: Connection refused

Then about 30 seconds later things start working again. Also, restarting apache manually fixes it.

I can still ping the IP just fine, and sitename.vm URL resolves to the correct IP while it's broken, and iptables looks good, and I can still SSH in, it's just that apache seems to stop accepting requests. Apache still says it's running during this time though.

Have you seen this before? Any tips on where I might go to debug?

**Comment by geerlingguy** [comment]
I haven't seen this behavior, but it sounds more like a routing issue than necessarily something with Apache... Is the URL actually `sitename.vm`?

Also, for your internal DNS routing, are you using a symlinked `hosts` file, or the standard one? I know you can end up with weird behaviors like this depending on how that's configured.

**Comment by mikecrittenden** [comment]
Thanks @geerlingguy -- if it's not behavior that you've seen before then I won't waste your time trying to help me track it down. Just wanted to make sure it was just me.

**Comment by mikecrittenden** [comment]
For anyone who may see this in the future, I spent a good bit of time on this and never could figure it out, but sysadmin isn't really my expertise so it may have been obvious still. 

I saw the same issue with Vlad, but not with puphpet VMs or Dashbrew (which is what I ended up sticking with). If anyone comes along and sees this issue and is able to figure it out, please do comment here, but it's no longer relevant for me.

**Comment by sethprime** [comment]
I'm seeing this same error, albeit consistently, on a fresh install of Kubuntu 15.10.

**Comment by helit** [comment]
I have the same issue running a 'geerlingguy/ubuntu1604' 1.1.6 vagrant vm using winnfsd from on Windows 10.

My box works fine for a while after running vagrant up, but after about 15 minutes, the site will stop responding. More specifically when reloading the page in chrome the tab never stops loading.

My workaround is to close the winnfsd.exe cmd (the window that pops up when running vagrant up) and run a vagrant halt followed by a vagrant up and the site will work for another 15 minutes.

This is very frustrating and makes developing very tedious.

Here are my versions of the software I use:
Vagrantbox: Version 5.2.4 r119785 (Qt5.6.2)
Vagrant: 2.0.1
Drupal: 7
GuestAdditions: 5.2.4

**Comment by AntoninSlejska** [comment]
@helit I have identical problem as you. See: https://github.com/geerlingguy/drupal-vm/issues/1661

**Comment by webprogrammierer** [comment]
I have the same problem now.
Is there any solution in the meantime?
