### ISSUE TITLE
DV Favicon for Dashboard?

### ISSUE THREAD

**Issue by attheshow** [geerlingguy/drupal-vm#782]
This is a super minor issue, but I wonder if we could possibly include the DV favicon with the dashboard page? I use these in Chrome to quickly identify which resource I want to load up in a tab and it would make the bookmark for the Dashboard look better. Anyway, just a thought. Thanks so much for this project. It's all amazing work!

**Comment by geerlingguy** [comment]
Makes sense. Maybe just the star icon used on the website/logo/elsewhere as a transparent ico or png?

**Comment by attheshow** [comment]
Sure, I think that would be fine.

**Comment by geerlingguy** [comment]
Here's that icon: https://raw.githubusercontent.com/geerlingguy/drupalvm.github.io/master/favicon.ico

I'm going to link directly to it over GitHub's CDN, so we don't have to add the file to this repo and have a dupe.

**Comment by attheshow** [comment]
Awesome news. Thanks!
