### ISSUE TITLE
NFS share not mounting in VM causing trouble during Site install check

### ISSUE THREAD

**Issue by daddymacnrei** [geerlingguy/drupal-vm#783]
I've come across a perplexing issue with  _vagrant up_ not mounting my drupal site folder inside the VM when using a custom config.yml file (see attached).   I' m running the command in a dedicated vm directory, (e.g. box), using our local drupal code base, with the latest DrupalVM build (3.1.3) and it always fails at the same point during the install with this error:

TASK [Check if site is already installed.] *************************************
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "failed_when_result": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Nye9QI/ansible_module_command.py\", line 250, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Nye9QI/ansible_module_command.py\", line 186, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/var/www/docdrupal7/docroot'\r\n", "msg": "MODULE FAILURE", "parsed": false}

My colleague is using the same versions of DrupalVM (3.1.3), Vagrant (1.8.4), VirturalBox (5.0.24), and HAS BEEN successful with the install.  So there must be something going on in my environment that's causing this error with the custom config.yml file.

Even more perplexing is I AM ABLE to install Drupal VM without the mounting issue using the default.config.yml file per the instructions on DrupalVM.com in the root drupal-vm directory after a clone of the project.  

My full environment details:

OS: Mac OS X Yosemite 10.10.5
DrupalVM 3.1.3
Vagrant 1.8.4
Ansible 2.1.0.0
VirtualBox 5.0.24
DrupalVM Box:  geerlingguy/ubuntu1404 (virtualbox, 1.1.3)

I also tried one of the solutions I read on in your issue queue, with no luck, regarding adding:

mount_options: ['vers=3', 'udp'] 

to the end of the _vagrant_synched_folders_ section of config.yml file.

Any insight into this issue would be greatly appreciated.  A few of us have tried to wrap our heads around it trying many different solutions (opening the permissions up on the local drupal code directory, removing Ansible, the mount code above, etc) with no success.  Please help!!

[config.txt](https://github.com/geerlingguy/drupal-vm/files/352820/config.txt)

**Comment by timwood** [comment]
I'm the colleague referenced and the only major difference in our versions is that I'm running OSX 10.11.5 and an older version of ansible, 2.0.1.0.

**Comment by geerlingguy** [comment]
Hmm... I've also noticed a couple people running OS X 10.10.x had issues. The version of Ansible, while it's not latest/current (so it would be good to upgrade), definitely wouldn't cause the NFS mount issue.

I've been hearing reports from a few other people having the exact same issue—some people's Macs can mount the NFS volumes... while others can't. Always with the same configuration. And it usually works if you use stock Drupal VM (e.g. download it straight from drupalvm.com and run it without a custom config file).

So I guess for troubleshooting purposes, can you:

  1. Update to latest version of everything (looks like just Ansible in your case).
  2. Can you halt the machine (`vagrant halt`) then bring it up with debug mode (`vagrant up --debug`) and see if there are any messages around the NFS exports time?
  3. Can you set the `type` to `''` and see if things work correctly (after halt/up or reload) in that case (to confirm it's NFS)?
  4. Can you log into the VM and run `sudo mount` to list the mounts, and see if the NFS folder isn't appearing?

**Comment by daddymacnrei** [comment]
Thanks for the speedy response Jeff.  I had just installed Ansible via the instructions linked from your VM Quick Start Guide and the latest Mac OS install here: http://docs.ansible.com/ansible/intro_installation.html#latest-releases-on-mac-osx.  Is 2.1.0.0. not the latest release?

**Comment by geerlingguy** [comment]
@daddymacnrei - Another question—are you running Drupal VM standalone (e.g. it's own clone, or downloaded and modified), or is it installed as part of something else (e.g. BLT or Lunchbox?).

See related: https://github.com/acquia/blt/issues/214

**Comment by daddymacnrei** [comment]
So just walking thru your recommended troubleshooting steps.

1. I believe I have the latest version of Ansible (2.1.0.0)

2. After a failed _vagrant up_ attempt, I went ahead and did a _vagrant halt_ and then a _vagrant up --debug_ as suggested.  It spits back quite a bit of info but by searching on "NFS" the only thing that stood out to me as a possible issue was this reference, _"DEBUG ssh: stderr: mount.nfs: requested NFS version or transport protocol is not supported"_, towards the end of the output (screenshot attached).  But that wasn't in the actual NFS exports time output area.

3.  I changed the _vagrant_synced_folder_default_type_ type from "NFS" to '' as you suggested (that was just single quote, single quote correct?).  Then ran vagrant halt, up and reload with no obvious changes to the short output I would normally get on those commands after the initial vagrant up and install error.   Not sure this is exactly what you were asking though.

4.  I see no reference to the NFS folder after a _sudo mount_ in the VM (screenshot attached).

5.  My /etc/hosts file does appear to have my local host entry at the top in addition to the default drupalvm.dev host ip listed from my failed install.

**Working on 6. and 7. next.**

In response to your latest question about my copy of Drupal VM.  It's from a fresh download of DrupalVM 3.1.3 from the project site.  So standalone.


<img width="839" alt="screen shot 2016-07-07 at 4 34 27 pm" src="https://cloud.githubusercontent.com/assets/14016658/16668952/14fcdec8-4461-11e6-9a75-8f48e0688835.png">

<img width="818" alt="screen shot 2016-07-07 at 4 53 40 pm" src="https://cloud.githubusercontent.com/assets/14016658/16669426/7e23eff2-4463-11e6-8e93-6c8680af9809.png">

**Comment by daddymacnrei** [comment]
**Update** - I skipped 6. and went right to suggestion 7. Upgraded to Mac OS X 10.11.5 (El Capitan) and the NFS share has mounted in the VM.  Woohoo!

**Comment by geerlingguy** [comment]
@daddymacnrei - So it seems there's definitely an issue with Mac OS X 10.10 and Vagrant 1.8.4. I'm guessing/hoping that issue will be resolved in Vagrant 1.8.5, but it's good to know two workarounds seem to be the best bets right now:

  1. Downgrade Vagrant to 1.8.1
  2. Upgrade Mac OS X to 10.11.5+

**Comment by daddymacnrei** [comment]
Yes.  I didn't downgrade to Vagrant 1.8.1, but as mentioned, I can confirm that upgrading my Mac OS X to 10.11.5 fixed the issue.  Thanks you for your help and guidance.  I think I can speak for all of us that your attention to these issues are greatly appreciated.

**Comment by entendu** [comment]
Downgrading Vagrant to 1.8.1 worked for me on 10.9.5.

**Comment by shrop** [comment]
I am seeing good NFS file mounts with Virtuabox 1.8.5, Drupal VM 3.1.2 and Vagrant 1.8.5 with OS X 10.11.6.

**Comment by geerlingguy** [comment]
It looks like updating to 1.8.5 will also help with this.

Now that there are many solutions for those on older versions, and in addition the fact that updating to all the latest versions of non-system software will fix this, I'm closing the issue :)

**Comment by mgamshad** [comment]
Had same issue on OSX 10.11.6 (El Capitan).  Here is what worked for me.  I created a local.config.yml file in the project/box folder.  Its content was:

vagrant_synced_folder_default_type: ""

vagrant_synced_folders:
   - local_path: .
     destination: /var/www/projectname
     type: ""

And that resolved it.  Doing the same, i.e. setting "type" to "", in the box/config.yml did not seem to work.

**Comment by aaneto18** [comment]
thanks @mgamshad, this solution worked fine for me.
