### ISSUE TITLE
Composer failure even 

### ISSUE THREAD

**Issue by micheal-cooper** [geerlingguy/drupal-vm#790]
I am setting up a VM with an existing codebase, so I have my YML file set to false for makefiles and false for build_composer, but when I vagrant up, I get an error that Composer was not able to install dependencies:

TASK [Generate Drupal project with composer package.] **************************
skipping: [wwwdev]

TASK [Install dependencies with composer require.] *****************************
failed: [wwwdev] (item=drupal/devel:8.*) => {"failed": true, "item": "drupal/devel:8.*", "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_9IemE3/ansible_module_command.py\", line 250, in <module>\r\n    main()\r\n  File \"/tmp/ansible_9IemE3/ansible_module_command.py\", line 186, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/var/www/drupalvm/drupal'\r\n", "msg": "MODULE FAILURE", "parsed": false}

I think this is an erroneous error message, but it might put people off, so I am posting.

**Comment by micheal-cooper** [comment]
Here is the final error block:

TASK [Install dependencies with composer require.] *****************************
failed: [wwwdev] (item=) => {"failed": true, "item": "", "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_Ryp7w3/ansible_module_command.py\", line 250, in <module>\r\n    main()\r\n  File \"/tmp/ansible_Ryp7w3/ansible_module_command.py\", line 186, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/var/www/drupalvm/drupal'\r\n", "msg": "MODULE FAILURE", "parsed": false}
	to retry, use: --limit @/Users/michealcooper/Dev/wwwdvm/provisioning/playbook.retry

**Comment by joestewart** [comment]
This `build_composer_project` variable default is truel.
```
 `build_composer_project: true`
```
I think if you set to false, behavior will be correct.

**Comment by geerlingguy** [comment]
Yeah; that variable should be set to `false`, otherwise the project build is attempted.

See this part of the 'Local Drupal codebase' documentation: http://docs.drupalvm.com/en/latest/deployment/local-codebase/#disable-the-composer-project-build-and-site-install

Closing—please reopen if setting `build_composer_project: false` doesn't help.

**Comment by micheal-cooper** [comment]
Yes, build_composer_project: false fixed it. Thank you.
