### ISSUE TITLE
Update URLs to https (yay for Let's Encrypt!)

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#791]
I finally had time to update the `certbot` role and get the server www.drupalvm.com resides on fully-SSL-powered, so now I need to update all the URLs.

**Comment by JakeDEvans** [comment]
mix content warnings
![image](https://cloud.githubusercontent.com/assets/5014348/16806563/f5e5043a-48e2-11e6-9eec-6579eab7f970.png)

**Comment by geerlingguy** [comment]
@JakeDEvans - Good catch! I'll update here: https://github.com/geerlingguy/drupalvm.github.io/issues/1
