### ISSUE TITLE
Devel module dependency undocumented in "Add Drupal VM as a Composer dependency"

### ISSUE THREAD

**Issue by ctorgalson** [geerlingguy/drupal-vm#792]
When [adding Drupal VM as a composer dependency](http://docs.drupalvm.com/en/latest/other/drupalvm-composer-dependency/#add-drupal-vm-as-a-composer-dependency), the docs don't mention the [Devel dependency in `default.config.yml`](https://github.com/geerlingguy/drupal-vm/blob/master/default.config.yml#L49).

If you follow the docs as-is, the process hangs at `TASK [Install configured modules with drush.]`.

The docs should mention this dependency and specify that either

1. Devel should be added to `composer.json` file in the user's own project, or
2. `drupal_enable_modules` should be altered in the user's own `config.yml` file.

**Comment by geerlingguy** [comment]
Fixed in #793
