### ISSUE TITLE
Dashboard "your sites" link broken w/nginx

### ISSUE THREAD

**Issue by entendu** [geerlingguy/drupal-vm#795]
nginx's format of placing multiple host names on one line is breaking the "Your Sites" links on the dashboard:

![screen shot 2016-07-11 at 10 51 02 am](https://cloud.githubusercontent.com/assets/276273/16740783/77803fd0-4755-11e6-80ee-0ef6e526de9d.png)

![screen shot 2016-07-11 at 10 52 04 am](https://cloud.githubusercontent.com/assets/276273/16740804/8b783b82-4755-11e6-99e6-6051a4b90cbf.png)

**Comment by geerlingguy** [comment]
Nice work, thanks!
