### ISSUE TITLE
Clone Drush from Github Very Slow

### ISSUE THREAD

**Issue by smmccabe** [geerlingguy/drupal-vm#797]
I will often get stuck on this step for a very long time, everything else runs quickly but this is very slow.  Is there something I can do for debugging? I don't know if it is the download or some task afterwards.

**Comment by geerlingguy** [comment]
@smmccabe - If you do a clone from github to your local computer directly, how long does it take (e.g. `time git clone https://github.com/drush-ops/drush.git`)? The process takes about 2-3s on my Mac, but it _is_ 13 MB or so, so a really slow internet connection or somewhere far from GitHub CDN endpoints could make it slower.

**Comment by smmccabe** [comment]
I get between 8-9 seconds, but when it runs through vagrant up, I will get probably 2-3 minutes at least

**Comment by geerlingguy** [comment]
Interesting. Are you on Mac or another platform, and I'm presuming you have VirtualBox, and not VMware or Parallels?

**Comment by smmccabe** [comment]
Ubuntu and VirtualBox

**Comment by geerlingguy** [comment]
And I presume you're using NFS for the synced folder too? That's the only other quick thing I could think of. Maybe the virtual networking has an issue. Can you `vagrant ssh` in, then run a speed test like `wget --output-document=/dev/null http://speedtest.wdc01.softlayer.com/downloads/test500.zip` (or a cli speedtest tool), and see what you get? I got about 10.5 MB/s (for reference) both inside and outside the VM.

**Comment by smmccabe** [comment]
Runs right about the same at 1.5MB/s both in and out of VM

**Comment by geerlingguy** [comment]
Interesting, I wonder why the Ansible task would take any longer then... it's basically running `git clone https://github.com/drush-ops/drush.git {{ drush_install_path }}`, and it shouldn't take any longer.

I'm running some tests locally, will see if I can figure out any possible reason it could take longer.

**Comment by geerlingguy** [comment]
I've tested on three different computers—two on my home network, and one remote on a slower connection, and I also made sure the latest runs in Travis were the same—the `Clone Drush from GitHub.` task only takes maybe 5-10 seconds on faster connections/Travis, and 15-20 seconds on my slower connection.

I repeated twice on my personal computer with a fresh VM and completely empty cachier cache.

I'm guessing it's something to do with either the network or your local network on the machine, which makes it really hard for me to debug any further.

I'm going to close the issue, but here are some things you could check:

  1. While provisioning, log into the VM (`vagrant ssh`) and run `iftop` to monitor the network traffic. Maybe do the same on your host to see what's up there.
  2. See if you might be using a VPN or proxied network connection that could slow things down or be doing traffic sniffing/shaping.
  3. Try the same config on a different computer or on a different network and see if there's any difference.

Also, does this happen every time (on the same task, `Clone Drush from GitHub.`), or did this just happen one time?
