### ISSUE TITLE
Error installing Drupal 7 on newest version of DrupalVM

### ISSUE THREAD

**Issue by smmccabe** [geerlingguy/drupal-vm#799]
When provisioning with d7 setup as per README

I get an MBString Error:

`Exception: Unicode library: Error\n\nMultibyte string input conversion in PHP is active and must be disabled. Check the php.ini <em>mbstring.http_input</em> setting`

Full dump below:
`fatal: [drupalvm7]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:00.482048", "end": "2016-07-11 22:44:26.020412", "failed": true, "rc": 1, "start": "2016-07-11 22:44:25.538364", "stderr": " [notice] Starting Drupal installation. This takes a while. Consider using the --notify global option.\n [error]  Exception: Unicode library: Error\n\nMultibyte string input conversion in PHP is active and must be disabled. Check the php.ini <em>mbstring.http_input</em> setting. Please refer to the <a href=\"http://www.php.net/mbstring\">PHP mbstring documentation</a> for more information. in /var/www/drupalvm/drupal/web/includes/install.core.inc:742\nStack trace:\n#0 /var/www/drupalvm/drupal/web/includes/install.core.inc(474): install_verify_requirements(Array)\n#1 /var/www/drupalvm/drupal/web/includes/install.core.inc(343): install_run_task(Array, Array)\n#2 /var/www/drupalvm/drupal/web/includes/install.core.inc(80): install_run_tasks(Array)\n#3 /usr/local/share/drush/includes/drush.inc(725): install_drupal(Array)\n#4 /usr/local/share/drush/includes/drush.inc(711): drush_call_user_func_array('install_drupal', Array)\n#5 /usr/local/share/drush/commands/core/drupal/site_install_7.inc(82): drush_op('install_drupal', Array)\n#6 /usr/local/share/drush/commands/core/site_install.drush.inc(243): drush_core_site_install_version('standard', Array)\n#7 /usr/local/share/drush/includes/command.inc(366): drush_core_site_install('standard')\n#8 /usr/local/share/drush/includes/command.inc(217): _drush_invoke_hooks(Array, Array)\n#9 /usr/local/share/drush/includes/command.inc(185): drush_command('standard')\n#10 /usr/local/share/drush/lib/Drush/Boot/BaseBoot.php(73): drush_dispatch(Array)\n#11 /usr/local/share/drush/includes/preflight.inc(88): Drush\\Boot\\BaseBoot->bootstrap_and_dispatch()\n#12 /usr/local/share/drush/drush.php(12): drush_main()\n#13 {main} ", "stdout": "You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y", "stdout_lines": ["You are about to DROP all tables in your 'drupal' database. Do you want to continue? (y/n): y"], "warnings": []}`

**Comment by geerlingguy** [comment]
I'm testing now, with the changed default make file and the following settings inside my `config.yml`:

```yaml
drupal_major_version: 7
build_composer_project: false
build_makefile: true
drupal_core_path: "/var/www/drupalvm/drupal"
```

**Comment by geerlingguy** [comment]
I tested with the above config in my `config.yml`, as well as the exact following make file, and a Drupal 7 site was bootstrapped and running at the end of the build process:

```yaml
---
api: 2
core: "7.x"

projects:
  drupal:
    version: 7.50
  devel: "1.x-dev"
```

One thing to note—if you had a build failure at all the first time you `provisioned`, depending on when it happened, Apache might never have restarted, so some of the old settings could still be in place. You may need to `vagrant destroy` and `vagrant up` again, or you could `vagrant ssh` in and directly restart Apache with `sudo service apache2 restart`.

**Comment by jprasmussen** [comment]
I had this same error and in case it helps anyone else this is what was happening for me. It turned out that Drupal 7.5 was being downloaded instead of Drupal 7.50. In the make file I wrapped the version in quotes and it installed just fine after that.

```
---
api: 2
core: "7.x"

projects:
  drupal:
    version: "7.50"
  devel: "1.x-dev"
```

**Comment by geerlingguy** [comment]
Eek! We might want to make that a default in the example... doing that now :)
