### ISSUE TITLE
Initial file ownership 

### ISSUE THREAD

**Issue by rgoodie** [geerlingguy/drupal-vm#8]
(This was also reported in #7 but wanted to separate it out for clarity)

After modifying the drupal.make to get d8 and executing `vagrant provision`, I got the white screen of death. A bit of exploration showed that all files in /var/www/drupal were owned by the vagrant user. I changed ownership (`sudo chown www-data -R *`) and everything worked after that.

**Comment by theodorosploumis** [comment]
Is this been committed to master? I have some folder permission issues since all folders in the guest vm are owned by **vagrant**. But there is no drupal.yml file at all under provisioning/tasks.
