### ISSUE TITLE
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/apcu.so'

### ISSUE THREAD

**Issue by KuterginVictor** [geerlingguy/drupal-vm#800]
Ubuntu 12.04
VirtualBox 5.0.24
Ansible 2.1.0.0

I use acquia.config.yml to override some configuration. (use Ubuntu 12.04 LTS with PHP 5.6)
But using drush, I always got the warning in the console: 
`PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/apcu.so' - /usr/lib/php5/20131226/apcu.so: cannot open shared object file: No such file or directory in Unknown on line 0`
![image](https://cloud.githubusercontent.com/assets/1299351/16757033/2fecf3da-482b-11e6-98de-57f988b4b57b.png)

I added "php5-apcu" to the list of "php_packages" and it solved the problem.

I think we should add "php5-apcu" to the acquia example file acquia.config.yml.

**Comment by geerlingguy** [comment]
Done!
