### ISSUE TITLE
Vagrant acting weird during 'vagrant up'

### ISSUE THREAD

**Issue by ardnet** [geerlingguy/drupal-vm#801]
Sometimes i got this when I do 'vagrant up':
![screen shot 2016-07-12 at 15 15 33](https://cloud.githubusercontent.com/assets/8396306/16759946/a87a9f92-4843-11e6-9181-56f83ce34e1e.png)

And sometimes it just got stuck like this below for some times, and I had to Ctrl+C to cancel the process:
![screen shot 2016-07-12 at 15 15 48](https://cloud.githubusercontent.com/assets/8396306/16759960/b98efdbe-4843-11e6-991c-78e0f07965f7.png)

Been doing vagrant destroy and vagrant up several times but to no avail, and I still didn't have my vagrant setup properly until now, please advise.

**Comment by geerlingguy** [comment]
It's almost always a network issue; see https://groups.google.com/forum/#!msg/ansible-project/l909HDg9Oo8/MSdOVfZjWhQJ and http://stackoverflow.com/questions/36138983/ansible-galaxy-error-api-server-not-found (among others)—however, one other thing you can check is to see what version of `ansible` you're running (with `ansible --version`).

Also, if you have a Mac or linux host, and you don't want to reinstall all the roles every time the machine is provisioned, you can use this method (see last line in the example) to tell Vagrant not to run `ansible-galaxy install` every time provisioning is run: http://docs.drupalvm.com/en/latest/other/overriding-configurations/#extending-the-vagrantfile-with-vagrantfilelocal

**Comment by ardnet** [comment]
@geerlingguy thx for the pointer!
lemme see what i can do from my end for that, thx!
