### ISSUE TITLE
Pimp my Log: the empty access logs

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#805]
Hello,

I would like to see access.log, but '/var/log/apache2/access.log' is empty (zero length).
And '/var/log/apache2/other_vhosts_access.log' which has been added to Pimp my Log is probably unrecognizable.
no new log found in 4ms with 763B of logs, 0 skipped line(s), 1 unreadable line(s).

Regards, Artu.

**Comment by geerlingguy** [comment]
See older issue: https://github.com/geerlingguy/drupal-vm/issues/197

There was some work to get this working more nicely, I just haven't had time to work on it (since I don't personally use PML...).
