### ISSUE TITLE
After vagrant destroy, drush aliases not removed from host machine

### ISSUE THREAD

**Issue by jayusa123** [geerlingguy/drupal-vm#806]
I have drush and ansible installed on my machine. When create a new dev environment with `vagrant up` drush aliases are created on my machine; however, after removing the dev machine with `vagrant destroy`, the drush alias file created on my machine (in ~/.drush) still remains and the aliases it defines can still be seen by running `drush site-alias`.

**Comment by geerlingguy** [comment]
Hmm... we basically need an extra task to delete the managed drush alias file (if the variable is set) during a `vagrant destroy`, like is outlined here: https://github.com/mitchellh/vagrant/issues/1302 (`cleanup` task, here: https://github.com/mitchellh/vagrant/blob/v1.8.4/lib/vagrant/plugin/v2/provisioner.rb#L48).

There's an issue to add support for the shell provisioner here: https://github.com/mitchellh/vagrant/issues/2538 — but looking around in the code for the Ansible provisioner, it looks like it's not implemented in either shell or ansible.

So besides using something like `vagrant-trigger`, I don't think it's possible to do this (and I don't want to add `vagrant-trigger` support at this time)... so for now, I'm going to close this issue, point people towards the upstream issues in Vagrant, and once they're resolved, maybe we could add a `cleanup` playbook that just undoes anything that was done (like Drush alias file creation) during Drupal VM provisioning on the host.

**Comment by jayusa123** [comment]
Sounds good. Thanks.
