### ISSUE TITLE
"Cannot find Ansible playbook"

### ISSUE THREAD

**Issue by darby3** [geerlingguy/drupal-vm#809]
Hoping for an assist; having trouble with a fresh drupal-vm install on OSX 10.9.5. Fresh clone and vagrant up results in a "Cannot Find Ansible Playbook" error:

`==> drupalvm: Checking for guest additions in VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.dev  # VAGRANT: efecaa9c01b4c1d253e74df2294dc4c0 (drupalvm) / 03652c28-e199-4a54-b1d6-d813ad25f53d
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  www.drupalvm.dev  # VAGRANT: efecaa9c01b4c1d253e74df2294dc4c0 (drupalvm) / 03652c28-e199-4a54-b1d6-d813ad25f53d
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.dev  # VAGRANT: efecaa9c01b4c1d253e74df2294dc4c0 (drupalvm) / 03652c28-e199-4a54-b1d6-d813ad25f53d
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.dev  # VAGRANT: efecaa9c01b4c1d253e74df2294dc4c0 (drupalvm) / 03652c28-e199-4a54-b1d6-d813ad25f53d
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.dev  # VAGRANT: efecaa9c01b4c1d253e74df2294dc4c0 (drupalvm) / 03652c28-e199-4a54-b1d6-d813ad25f53d
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.dev  # VAGRANT: efecaa9c01b4c1d253e74df2294dc4c0 (drupalvm) / 03652c28-e199-4a54-b1d6-d813ad25f53d
==> drupalvm: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
Password:
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Mounting shared folders...
    drupalvm: /tmp/vagrant-cache => /Users/darby3/.vagrant.d/cache/geerlingguy/ubuntu1604
==> drupalvm: Configuring cache buckets...
==> drupalvm: Running provisioner: shell...
    drupalvm: Running: /var/folders/yr/cvwv0tfs0pq3wtcj4dt5ccyw0000gn/T/vagrant-shell20160718-19724-1gfdl0p.sh
==> drupalvm: mesg: ttyname failed: 
==> drupalvm: Inappropriate ioctl for device
==> drupalvm: Cannot find Ansible playbook.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
`

I'm running other instances of Drupal VM on the machine, though probably some number of versions earlier than a fresh install. I'd tried doing custom config files so everything would play nice together and separately but ran into the above issue. I think I tried switching the box from 1604 to 1404 and no dice (happy to try again if the data is useful). Fell back to trying the default install, figuring I was breaking something. Same results after vagrant destroy and vagrant up multiple times.

Happy to supply more detail or the debug log if it's useful. I've seen a couple similar looking reported issues but none seemed to result in solutions that I could try to implement.

**Comment by geerlingguy** [comment]
Please either upgrade to Mac OS X 10.11, or downgrade Vagrant to 1.8.1; it seems the latest version of Vagrant doesn't play well with older versions of Mac OS X, and this and other problems seem to crop up regularly.

**Comment by darby3** [comment]
Thanks!

FWIW (for anyone else dealing with this kind of thing) I may have just had luck bumping from Vagrant 1.8.4 to 1.8.5; it did find the playbook at least, but there was some amount of red in the log output. I didn't test the results; I destroyed and bumped back down to 1.8.1 and am re-upping now. I think I'm seeing the same amount of red in the log output this time as well. (Same "==> drupalvm: mesg: ttyname failed: Inappropriate ioctl for device" error at least.)
