### ISSUE TITLE
SASS with DrupalVM Local changes not recognized

### ISSUE THREAD

**Issue by ubun2Junky** [geerlingguy/drupal-vm#810]
I've created my drupalvm environment, installed compass and sass on my virtual machine.  However when I make local changes on my mac using sublime sass on the virtual machine does not recognize the changes made to the files.  It's not until I 'vagrant ssh' into my virtual machine and nano into my css, make changes and save the file, that sass recognizes the changes and updates the css accordingly. 

Am I supposed to install compass and sass on my mac instead of the virtual machine?

**Comment by geerlingguy** [comment]
I typically run node-sass or compass on my Mac, and do all code-related work there (thus I install `nvm` on my Mac and all the required dependencies); if you run it inside the VM, it will run a lot slower, and it also can't monitor file changes in the synced folder if you do the actual changes on the Mac.

**Comment by geerlingguy** [comment]
(Note: This is also the model projects like [BLT](https://github.com/acquia/blt) use; all frontend code monitoring/compilation happens on the host, and the VM just uses the compiled assets.
