### ISSUE TITLE
DrupalVM with parallels OS X

### ISSUE THREAD

**Issue by heihachi88** [geerlingguy/drupal-vm#811]
Hello, why it is installing VirtualBox when i have Parallels already? How can i disable VirtualBox in a config file, so it won't install it?

**Comment by geerlingguy** [comment]
When you run `vagrant` commands, you can specify that you have and want to use parallels with the `--provider=parallels` option (see: https://www.vagrantup.com/docs/providers/basic_usage.html).

See the 'Default Provider' section on that page for instructions for setting it as your default so you don't have to pass in CLI options when using `up`.
