### ISSUE TITLE
TIP: Disable -force for ansible-galaxy command.

### ISSUE THREAD

**Issue by vladdancer** [geerlingguy/drupal-vm#812]
If someone want to skip ansible roles re-download  while running `vagrant provision --reload` you can change a bit Vagrantfile like so:

```diff
config.vm.provision 'ansible' do |ansible|
+  ansible.galaxy_command = "ansible-galaxy install --role-file=%{role_file} --roles-path=%
{roles_path}"
    ....
```

**Comment by geerlingguy** [comment]
See also #814 — which will make everything oh-so-much-better/faster :)

**Comment by vladdancer** [comment]
Thanks, Jeff. This is awesome!
