### ISSUE TITLE
vagrant up fails while downloading role php

### ISSUE THREAD

**Issue by naveenvalecha** [geerlingguy/drupal-vm#813]
- downloading role 'php', owned by geerlingguy
https://galaxy.ansible.com/roles/432/versions/?page=2&page_size=50
Traceback (most recent call last):
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-galaxy", line 959, in <module>
    main()
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-galaxy", line 953, in main
    fn(args, options, parser)
  File "/usr/local/Cellar/ansible/1.9.4/libexec/bin/ansible-galaxy", line 819, in execute_install
    if len(role_versions) > 0:
TypeError: object of type 'NoneType' has no len()
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

Steps to Reproduce :

Download drupalvm 3.1.4
extract the zip file and run the vagrant up into it.
The box will takes few minutes to download then at the time of installation of packages the error will come up.

**Comment by geerlingguy** [comment]
You'll need to either upgrade to Ansible 1.9.5 or the latest 2.x version; this is a bug that was present in Ansible < 1.9.5 with the number of PHP versions that are available through Galaxy.
