### ISSUE TITLE
Support for Parallels

### ISSUE THREAD

**Issue by heihachi88** [geerlingguy/drupal-vm#817]
parallels/ubuntu-14.04 box is outdated. Could you please make it with ubuntu 16.04?

**Comment by geerlingguy** [comment]
@heihachi88 - I don't have Parallels, and don't maintain the official `parallels` boxes; it looks like Parallels doesn't yet support a 16.04 box, and that would be something to address upstream with Parallels: http://parallels.github.io/vagrant-parallels/docs/boxes/
