### ISSUE TITLE
How to make a version for production server (without a VM)?

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#818]
Drupal VM is the great thing.

I am surprised why there is not supply and demand for a production version.
How to move the customized dev configuration to a production server?

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/tree/master/examples/prod

This is currently an 'unofficially not-100%-supported' feature, though. I use Drupal VM as a base for many one-off Drupal site servers, though, and can vouch for how well it holds up if you follow the guide in that example (similar for any cloud provider, but the example is for DigitalOcean).
