### ISSUE TITLE
Question: Allow other platforms?

### ISSUE THREAD

**Issue by louim** [geerlingguy/drupal-vm#82]
Hello!

First: thank you very much for all the work you do on Ansible Roles, I feel like 75% of the roles I use come from you! :smiley: 

I would like to suggest something: would it be possible to separate the base provisioning with all the good defaults you have in there from the Drupal-specific configurations? I'm asking this since I forked this project in hope of providing a Magento VM to allow the same kind of "easy start". I feel like all the things I changed could easily be packaged and just added on top of your awesome base setup. This would save a lot of duplication, and user would benefit from this. 

Do you think it would be possible? If so, would you be interested in doing it?

Thanks again!

**Comment by geerlingguy** [comment]
My main focus for this project is to be a really focused Drupal development environment. Many settings (MySQL/PHP defaults, choices of extra software to install, and certain parts of the setup process) are set specifically for Drupal development and may or may not be useful for other types of PHP-based projects.

That being said, if someone wants to maintain a fork for a specific project (e.g. Wordpress, Magneto, MediaWiki, etc.), I have no problem with that—the majority of the work I do is to make the underlying roles (like `geerlingguy.php` and `geerlingguy.apache`) to be robust and flexible, able to work with local environments and production as well, for many different purposes.

I'm not going to try to convert Drupal VM into a flexible VM-for-any-PHP-project setup... but I would recommend anyone who wants to play with it as a base for other PHP projects do so, and also check out neat projects like [Phansible](http://phansible.com/), which is a little more generic, but follows many of the  same principles.
