### ISSUE TITLE
Questions about ansible nginx and nfs

### ISSUE THREAD

**Issue by heihachi88** [geerlingguy/drupal-vm#822]
It is possible to use this box without ansible and nginx?

How can i completely remove nginx and ansible from config?

Also in order to disable NFS i have to do in config.yml following changes:
```
vagrant_synced_folder_default_type:
type:
```

Is it right? I just set them empty because i want to use default sync method.

**Comment by geerlingguy** [comment]
@heihachi88 - I'm not quite sure what you mean by "How can i completely remove nginx and ansible from config?" — by default, neither will be installed if you have Ansible installed on your host computer and you leave the default webserver setting intact (only Apache is installed by default).

For disabling NFS, you should just set those to `''` (empty string), and that will use the default synced folder type.

**Comment by geerlingguy** [comment]
Closing out the question as answered (also, Vagrant now manages Ansible inside the guest VM on its own if you don't have it installed on your computer).
