### ISSUE TITLE
Vagrant up timeout while waiting for machine to boot.

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#824]
I have followed the instructions at http://docs.drupalvm.com/en/latest/deployment/local-codebase/ as best I can. I am getting the following timeout error with vagrant up. I've attached all the messages. I've also attached the config.yml with my changes.

I'm sure I've made a mistake somewhere since I'm still learning. What did I do wrong?

[config.zip](https://github.com/geerlingguy/drupal-vm/files/382661/config.zip)

C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.4/lib/vagrant/batch_action.
rb:82:in `block (2 levels) in run'
 INFO interface: error: Timed out while waiting for the machine to boot. This 
means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

[PS C.docx](https://github.com/geerlingguy/drupal-vm/files/382653/PS.C.docx)

**Comment by ColumbiaBlooms** [comment]
Update. I ran "vagrant up" again and did not get the message.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Sometimes... Vagrant can just be strange :)
