### ISSUE TITLE
Single user multiple mysql permissions

### ISSUE THREAD

**Issue by designvoid** [geerlingguy/drupal-vm#826]
I have 2 databases that I need creating and a single user with permissions on both:

    mysql_databases:
      - name: "db1"
        encoding: utf8
        collation: utf8_general_ci
      - name: "db2"
        encoding: utf8
        collation: utf8_general_ci

    mysql_users:
      - name: "user_xx"
        host: "%"
        password: "xxxxxx"
        priv: 
          - "db1.*:ALL"
          - "db2.*:ALL"

This is what I have but I think it's causing errors...? Any suggestions?

**Comment by designvoid** [comment]
Never mind, I've figured it!

For anyone else, you specify the permissions like this:

        mysql_users:
          - name: "user_xx"
            host: "%"
            password: "xxxxx"
            priv: "db1.*:ALL/db2.*:ALL"

**Comment by geerlingguy** [comment]
Ha, was just about to write that, but you got it. :)
