### ISSUE TITLE
Building existing DrupalVM with Lightning distro

### ISSUE THREAD

**Issue by kshamsuddin** [geerlingguy/drupal-vm#828]
Hi,
I have a DrupalVM box built with custom composer.json. I have been trying to rebuild the box with lightning distro. So,
 
1. I updated the composer.json file as below:

      "require": {
	    "composer-plugin-api": "^1.0.0",
	    "composer/installers": "~1.0",
	    "cweagans/composer-patches": "~1.0",

	    "drupal/console": "~1.0.0-alpha1",
	    "acquia/lightning-project": "^8.1.0",
	    "drush/drush": "~8.0",

	    "drupal/admin_toolbar": "8.x-1.x-dev",
	    "drupal/adminimal_theme": "~8.1.1",
	    "drupal/config_installer": "~8.1.2",
	    "drupal/entity_browser": "8.x-1.x-dev",
	    "drupal/entity_embed": "~8.1.0-alpha2",
	    "drupal/file_browser": "8.x-1.x-dev",
	    "drupal/field_group": "~8.1.0-rc4",
	    "drupal/geofield": "8.x-1.x-dev",
	    "drupal/google_analytics": "~8.2.0-rc1",
	    "drupal/inline_entity_form": "8.1.0-alpha6",
	    "drupal/media_entity": "~8.1.2",
	    "drupal/media_entity_twitter": "~8.1.0",
	    "drupal/memcache": "~8.2.0-alpha1",
	    "drupal/metatag": "~8.1.0-beta4",
	    "drupal/pathauto": "~8.1.0-alpha3",
	    "drupal/scheduler": "~8.1.0-alpha1",
	    "drupal/smart_trim": "~8.1.0",
	    "drupal/xmlsitemap": "~8.1.0-alpha2",

	    "rippleffect/capistrano-php": "~1.0",
	    "rippleffect/comms-html": "dev-master",
	    "rippleffect/ripple_base": "dev-8.x-1.x",
	    "rippleffect/ripple_promo": "dev-8.x-2.x",
	    "rippleffect/ripple_socialshare": "dev-8.x-1.x",
	    "rippleffect/ripple_twig": "dev-8.x-1.x",

	    "communicatorcorp/client-php": "~1.0",
	    "desandro/imagesloaded": "4.1.0",
	    "desandro/masonry": "4.1.0",
	    "enyo/dropzone": "4.3.0"
	  },

2. run composer update
3. vagrant up

But, I can't see the lightning package using drush pml or even drupal admin area. Can anybody please advise what I'm doing wrong. 

Below is my config.yml:

    build_makefile: false
	drush_makefile_path: "{{ config_dir }}/drupal.make.yml"

	# Set 'build_makefile' to 'false' and this to 'true' if you are using a
	# composer based site deployment strategy.
	build_composer: true
	drupal_composer_path: false
	drupal_composer_install_dir: "/vagrant"
	drupal_composer_dependencies: []

	# Set this to 'true' and 'build_makefile', 'build_composer' to 'false' if you
	# are using Composer's create-project as a site deployment strategy.
	build_composer_project: false
	drupal_composer_project_package: "drupal-composer/drupal-project:8.x-dev"
	drupal_composer_project_options: "--prefer-dist --stability dev --no-interaction"

    # Set this to 'false' if you don't need to install drupal (using the drupal_*
    # settings below), but instead copy down a database (e.g. using drush sql-sync).
    install_site: false

    # Required Drupal settings.
    drupal_core_path: "{{ drupal_composer_install_dir }}/web"

Many Thanks.
Kollol

**Comment by geerlingguy** [comment]
@kshamsuddin - I think the best bet would be to ask this question in Lightning's issue queue (e.g. 'how do I use lightning with composer?').

Also, see BLT's composer.json template, which AFAICT also uses Lightning: https://github.com/acquia/blt/blob/e4788eaf2abadd5a2607682e5dc60947b8086654/template/composer.json

**Comment by kshamsuddin** [comment]
Thanks @geerlingguy
