### ISSUE TITLE
ansible-galaxy install -> AttributeError: 'module' object has no attribute 'role_spec_parse'

### ISSUE THREAD

**Issue by tweevick** [geerlingguy/drupal-vm#83]
sudo ansible-galaxy install -r requirements.txt gives me the following error:
Traceback (most recent call last):
  File "/usr/local/bin/ansible-galaxy", line 954, in <module>
    main()
  File "/usr/local/bin/ansible-galaxy", line 948, in main
    fn(args, options, parser)
  File "/usr/local/bin/ansible-galaxy", line 767, in execute_install
    roles_left = map(ansible.utils.role_spec_parse, f.readlines())
AttributeError: 'module' object has no attribute 'role_spec_parse'

**Comment by geerlingguy** [comment]
This looks like an issue with your Ansible installation; how did you install Ansible, and if you run `ansible --version`, what version do you get?

See also: https://github.com/ansible/ansible/issues/9731
