### ISSUE TITLE
Documentation update for newbies

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#831]
Could you add a sentence or two at the beginning of the Updating Drupal VM section at https://github.com/geerlingguy/drupal-vm#updating-drupal-vm that says something like "Copy config.yml to savedconfig.yml. Download update. Copy files in update to DrupalVM folder."

I'm assuming that the above is a correct procedure?

This addition would really help newbies like myself.

**Comment by geerlingguy** [comment]
That's mostly it; but in general, there are two ways to update:

1. Use git clone to clone the entire project. Manage local files (e.g. `config.yml`, `drupal.make.yml` etc.) however you like, and for updates, `git pull` — this is preferred, as you don't need to do any extra work to update besides pulling new changes.
2. Download the project (always download a point release—the website points to the latest release, 3.2.0 right now), and when updating, preserve local files (e.g. `config.yml`, `drupal.make.yml`, etc.).

There's a third way now, too, where you could manage Drupal VM as part of a larger project using Composer, and including specific versions or series of Drupal VM in the `composer.json` file. That method is a little more involved (especially for beginners), but it's a nice stable option for teams especially.

For now, I think I'll leave the documentation in the Quick Start Guide as is. I think as time goes on, the process and best practices evolve enough that I don't want to document one method as canonical. And technically, if you always use all the Drupal VM defaults, there's no need to manage any local files or copy anything anywhere—just download the updated version and you're done!
