### ISSUE TITLE
Firewall template in Windows format

### ISSUE THREAD

**Issue by vdbemden** [geerlingguy/drupal-vm#832]
Hi, 
deploying the last drupal VM, i faced this old issue 
https://github.com/geerlingguy/ansible-role-mailhog/issues/5
but for the firewall role.
I fixed it the same way, converting the file "templates/firewall.j2" in Unix format.
Could this be reported in your code?
Thanks

**Comment by geerlingguy** [comment]
Interesting... can you paste the full error output, and also, what version of Windows (or other OS) you're running on your host, along with what version of Drupal VM you're running?

**Comment by vdbemden** [comment]
**Settings :** 
Windows 8.1
Vagrant 1.8.5
VirtualBox 5.1.2
DrupalVM : Last commit (so we can say it's the 3.2.0)

**Output (since ansible part):** 
==> drupalvm: Running provisioner: ansible_local...
drupalvm: Installing Ansible...
drupalvm:` Running `ansible-playbook...
[DEPRECATION WARNING]: Included file '/vagrant/provisioning/config.yml' not
found, however since this include is not explicitly marked as 'static: yes', we
 will try and include it dynamically later. In the future, this will be an
error unless 'static: no' is used on the include task. If you do not want
missing includes to be considered dynamic, use 'static: yes' on the include or
set the global ansible.cfg options to make all inclues static for tasks and/or
handlers.
This feature will be removed in a future release. Deprecation
warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [drupalvm]

TASK [Define config_dir.] ******************************************************
skipping: [drupalvm]

TASK [include_vars] ************************************************************
ok: [drupalvm] => (item=/vagrant/config.yml)

TASK [Update apt cache if needed.] *********************************************
ok: [drupalvm]

TASK [Get software for Python-based control.] **********************************
changed: [drupalvm] => (item=[u'curl', u'python-apt', u'python-pycurl', u'build-essential', u'sudo', u'unzip'])

TASK [Disable the ufw firewall (since we use a simple iptables firewall).] *****
changed: [drupalvm]

TASK [Add repository for Apache 2.4 on Ubuntu 12.] *****************************
skipping: [drupalvm]

TASK [Add repository for PHP 5.5.] *********************************************
skipping: [drupalvm]

TASK [Add repository for PHP 5.6.] *********************************************
changed: [drupalvm]

TASK [Add repository for PHP 7.0.] *********************************************
skipping: [drupalvm]

TASK [Define php_xhprof_html_dir.] *********************************************
skipping: [drupalvm]

TASK [Get software for Python-based control.] **********************************
skipping: [drupalvm] => (item=[])

TASK [Enable remi repo for MySQL.] *********************************************
skipping: [drupalvm]

TASK [Enable remi repo for PHP 5.5.] *******************************************
skipping: [drupalvm]

TASK [Enable remi repo for PHP 5.6.] *******************************************
skipping: [drupalvm]

TASK [Enable remi repo for PHP 7.0.] *******************************************
skipping: [drupalvm]

TASK [Define php_xhprof_html_dir.] *********************************************
skipping: [drupalvm]

TASK [Run configured pre-provision shell scripts.] *****************************

TASK [Run configured pre-provision ansible task files.] ************************

TASK [Set the PHP webserver daemon correctly when nginx is in use.] ************
skipping: [drupalvm]

TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
skipping: [drupalvm]

TASK [geerlingguy.repo-remi : Import remi GPG key.] ****************************
skipping: [drupalvm]

TASK [geerlingguy.firewall : Ensure iptables is installed (RedHat).] ***********
skipping: [drupalvm]

TASK [geerlingguy.firewall : Ensure iptables is installed (Debian).] ***********
ok: [drupalvm]

TASK [geerlingguy.firewall : Flush iptables the first time playbook runs.] *****
changed: [drupalvm]

TASK [geerlingguy.firewall : Copy firewall script into place.] *****************
changed: [drupalvm]

TASK [geerlingguy.firewall : Copy firewall init script into place.] ************
changed: [drupalvm]

TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "failed determining service state, possible typo of service name?"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm          : ok=20   changed=15   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Resolved by :**
Find /drupalvm/provisioning/roles/geerlingguy.firewall/templates/firewall.j2
Edit it in notepad++ and convert it to Unix format (LF)
(Previously the format was Dos\Windows (CR+LF)

**Comment by daviuezono** [comment]
I was facing the same issue above.
Your solution worked for me. Thanks!

**Comment by geerlingguy** [comment]
It looks like the problem, then, is that something (either in git bash, or in the software being used to expand the zip or tar file from GitHub) is storing the files in CRLF line ending format. The files in the repo itself are all unix (LF), and if I use cygwin or cmder on Windows 10 to either curl or git clone Drupal VM, and don't touch the files within Windows, I don't see this issue.

Going to close the issue, as I don't think there's anything I can do to help make this situation better (line endings and Windows are always fun to deal with!), but thanks for posting the issue and solution!

**Comment by vdbemden** [comment]
Well, let's document the problem a bit more so :)
I'm using git-for-windows 2.9.0 

searching about crlf problem, i found this topic : 
https://help.github.com/articles/dealing-with-line-endings/
which talk about the core.autocrlf variable.

Searching a bit more, this variable has 3 values : 
true : when pulling to Windows, convert LF to CRLF, when pushing convert CRLF to LF
false : do nothing
input : when pulling to OSX or Linux, convert CRLF to LF

And it is set by default to true.

So, when I clone the repository, this option converts all the files in CRLF format which leads to my problem.

In the above link, a solution is proposed in the 'per-repository settings' section : 
add a .gitattributes file containing
* text eol=lf
this way, git on Windows will understand it should use the LF ending format.

**Comment by geerlingguy** [comment]
I see; I documented a while back http://docs.drupalvm.com/en/latest/other/windows/#git-and-file-permissions, which recommends:

```
git config core.fileMode false
```

And I usually recommend it globally unless you do a lot of work on projects that are Windows-only, just because this problem hits like 80% of OSS devs who are working on Windows.

**Comment by vdbemden** [comment]
yep, I can see this option set to false in the config file but seems like it isn't enough :/
