### ISSUE TITLE
How to maintain updated / configured Drupal projects with DrupalVM?

### ISSUE THREAD

**Issue by hidace** [geerlingguy/drupal-vm#833]
Hi, 

New to Drupal and using DrupalVM, so apologies if this question is obvious. I started with cloning the latest DrupalVM. I updated the config to work with PHP 5.6 on Ubuntu 14.04 and built the box on my system. I've now pushed up to my repo and I'd like my team to be able to clone that repo and maintain any changes and configuration I've already set up. However, it seems to want to build the project all over again from scratch when they pull from my repo and run vagrant up. Guessing this is all done through config.yml and drupal.make.yml, so I could gitignore those and be fine, as long as the Vagrantfile is present (?), but am not sure. Also seems like I would have to use the backup and manage module to save my database and make it available to them. 

Any and all help / suggestions are greatly appreciated. Thanks!!

**Comment by jayusa123** [comment]
Hi hidace,

Here's how I've implemented Drupal VM in our environment to allow:

- Maximum customizability 
- Code separation of our concerns from Drupal VM's
- Usage of `vagrant` commands anywhere in the project tree

Hope it helps!
Jay

Our repo layout:

>├── Vagrantfile (See below for contents)
├── config.yml (overrides default.config.yml in drupal-vm folder)
├── dev.make (Drush make file, loads Drupal core and pulls in my installation profile)
├── drupal (Drupal root, .gitignored, created by vagrant provisioning) 
├── drupal-vm (git submodule -> drupal-vm repo)
│   ├── Vagrantfile
│   ├── composer.json
│   ├── default.config.yml
│   ├── ...
├── example.local.config.yml (Assists new developers configuring their environment)
└── local.config.yml (Configures local debugging settings, .gitignored, unique to each developer)

The root Vagrantfile serves to allow `vagrant` command usage anywhere in the project tree, including anywhere in the Drupal installation. It assigns some Environment variables that Drupal VM looks for, ensures the Drupal VM submodule has been updated (cloned) and then hands off all further execution to the drupal-vm/Vagrantfile.


```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  Don't use this file to override the Drupal VM Vagrantfile  #
#                Use Vagrantfile.local instead                #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# The main purpose of this file is to establish the repository
# root directory as the Drupal VM project root. This allows
# the use of the vagrant command anywhere in the project tree
# and more importantly, allows us to keep our overriding configuration
# files out of the drupal-vm folder. This keeps the Drupal VM
# project at arms length and allows us to update/rollback/delete it
# without fear of losing any of our own work.

dir = File.dirname(File.expand_path(__FILE__))

# Drupal VM looks for a couple of environment variables to configure paths
ENV['DRUPALVM_PROJECT_ROOT'] = dir

# The config directory is relative to the project root.
# Comment out to store config files in the project root.
# ENV['DRUPALVM_CONFIG_DIR'] = "config"

# Update the Drupal VM submodule if empty
# This allows developers to omit the --recursive option when git cloning this repo and still obtain the drupal-vm submodule before it's needed for vagrant activities.
if Dir['drupal-vm/*'].empty?
  `git submodule init;git submodule update`
end

# Hand over further execution to the actual drupalvm Vagrantfile
load dir + "/drupal-vm/Vagrantfile"
```

**Comment by dwkitchen** [comment]
I wanted to do something similar but I am including drupal-vm in the dev section of my project's composer.json so I have a Vagrant file like this in the root:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
#  Don't use this file to override the Drupal VM Vagrantfile  #
#                Use Vagrantfile.local instead                #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# The main purpose of this file is to establish the repository
# root directory as the Drupal VM project root. This allows
# the use of the vagrant command anywhere in the project tree
# and more importantly, allows us to keep our overriding configuration
# files out of the drupal-vm folder. This keeps the Drupal VM
# project at arms length and allows us to update/rollback/delete it
# without fear of losing any of our own work.

dir = File.dirname(File.expand_path(__FILE__))

# Drupal VM looks for a couple of environment variables to configure paths
ENV['DRUPALVM_PROJECT_ROOT'] = dir

# Hand over further execution to the actual drupalvm Vagrantfile
load dir + "/vendor/geerlingguy/drupal-vm/Vagrantfile"
```

**Comment by geerlingguy** [comment]
For another example, check out BLT's integration: https://github.com/acquia/blt/blob/8.x/scripts/drupal-vm/Vagrantfile

I think there are enough examples to give some good ideas here, so I'm going to close the issue, thanks everyone!
