### ISSUE TITLE
add PECL uploadprogress

### ISSUE THREAD

**Issue by heihachi88** [geerlingguy/drupal-vm#834]
Add PECL uploadprogress with mod_php

**Comment by geerlingguy** [comment]
I won't be adding mod_php again (it's supported, and you can get it working with a certain set of variables, but I don't recommend it and won't default to it). However, there is an open PR for this purpose: https://github.com/geerlingguy/drupal-vm/pull/788

I hope to incorporate it soon, hopefully for the next minor release.

Closing this issue to direct attention to the PR.
