### ISSUE TITLE
ansible_ssh_user is undefined error message on CentOS 6

### ISSUE THREAD

**Issue by ColumbiaBlooms** [geerlingguy/drupal-vm#838]
I'm getting the same error message as https://github.com/geerlingguy/drupal-vm/issues/602. It happens with vagrant_box: geerlingguy/centos6. 

Is there a fix or work-around?

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Is it possible for you to test with `centos7`? Or run `vagrant provision` again a couple times and make sure it's the exact same error message again?

Finally, can you copy out the entire error message with context so I can see which task(s) are failing?

**Comment by ColumbiaBlooms** [comment]
I'm running your latest version of DrupalVM along with VirtualBox 5.1.2 and Vagrant 1.8.5 on Windows 10.

Updated config.yml vagrant_box to geerlingguy/centos6.

Ran vagrant destroy.

Ran vagrant up and got 


TASK [geerlingguy.composer : Update Composer to latest version (if configured).] ***
skipping: [drupalvm]

TASK [geerlingguy.composer : Ensure composer directory exists.] ****************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "{{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.apache : restart apache] **************************

Ran vagrant provision --debug and got

INFO interface: info: skipping: [drupalvm]

skipping: [drupalvm]
DEBUG ssh: stdout:
TASK [geerlingguy.composer : Ensure composer directory exists.] ****************

 INFO interface: info:
TASK [geerlingguy.composer : Ensure composer directory exists.] ****************


TASK [geerlingguy.composer : Ensure composer directory exists.] ****************
DEBUG ssh: stdout: fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "{{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}

 INFO interface: info: fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "{{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}

fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "{{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}
DEBUG ssh: stdout:
NO MORE HOSTS LEFT *************************************************************

 INFO interface: info:
NO MORE HOSTS LEFT *************************************************************


NO MORE HOSTS LEFT *************************************************************
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: stdout:      to retry, use: --limit @/vagrant/provisioning/playbook.retry

 INFO interface: info:  to retry, use: --limit @/vagrant/provisioning/playbook.retry

        to retry, use: --limit @/vagrant/provisioning/playbook.retry
DEBUG ssh: stdout:
PLAY RECAP *********************************************************************

 INFO interface: info:
PLAY RECAP *********************************************************************


PLAY RECAP *********************************************************************
DEBUG ssh: stdout: drupalvm                   : ok=96   changed=0    unreachable=0    failed=1

 INFO interface: info: drupalvm                   : ok=96   changed=0    unreachable=0    failed=1

drupalvm                   : ok=96   changed=0    unreachable=0    failed=1
DEBUG ssh: stdout:

 INFO interface: info:


DEBUG ssh: Exit status: 2
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x4881e70>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
ERROR warden: Error occurred: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO warden: Beginning recovery process...
 INFO warden: Calling recover: #<Vagrant::Action::Builtin::Call:0x455b758>
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO warden: Beginning recovery process...
 INFO warden: Recovery complete.
 INFO environment: Released process lock: machine-action-ebe11103b1fe542c7427f4cc626cc5ab
 INFO environment: Running hook: environment_unload
 INFO runner: Preparing hooks for middleware sequence...
 INFO runner: 2 hooks defined.
 INFO runner: Running action: environment_unload #<Vagrant::Action::Builder:0x4870908>
ERROR vagrant: Vagrant experienced an error! Details:
ERROR vagrant: #<VagrantPlugins::Ansible::Errors::AnsibleCommandFailed: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.>
ERROR vagrant: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
ERROR vagrant: C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/provisioners/ansible/provisioner/guest.rb:98:in `execute_ansible_command_on_guest'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/provisioners/ansible/provisioner/guest.rb:89:in `execute_ansible_playbook_on_guest'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/provisioners/ansible/provisioner/guest.rb:20:in `provision'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/provision.rb:133:in `run_provisioner'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:473:in `hook'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/provision.rb:121:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/provision.rb:121:in `block in call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/provision.rb:103:in `each'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/provision.rb:103:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/Users/samst/.vagrant.d/gems/gems/vagrant-hostsupdater-1.0.2/lib/vagrant-hostsupdater/Action/UpdateHosts.rb:18:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/check_accessible.rb:18:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/call.rb:53:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/Users/samst/.vagrant.d/gems/gems/vagrant-auto_network-1.0.2/lib/auto_network/action/request.rb:24:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/providers/virtualbox/action/check_virtualbox.rb:17:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/warden.rb:34:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/builder.rb:116:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `block in run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/util/busy.rb:19:in `busy'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/action/runner.rb:66:in `run'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:225:in `action_raw'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:200:in `block in action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:561:in `lock'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `call'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/machine.rb:186:in `action'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/provision/command.rb:30:in `block in execute'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `each'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/plugins/commands/provision/command.rb:29:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/cli.rb:42:in `execute'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/lib/vagrant/environment.rb:302:in `cli'
C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.8.5/bin/vagrant:174:in `<main>'
 INFO interface: error: Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
 INFO interface: Machine: error-exit ["VagrantPlugins::Ansible::Errors::AnsibleCommandFailed", "Ansible failed to complete successfully. Any error output should be\nvisible above. Please fix these errors and try again."]

Ran vagrant provision and got 

TASK [geerlingguy.composer : Update Composer to latest version (if configured).] ***
skipping: [drupalvm]

TASK [geerlingguy.composer : Ensure composer directory exists.] ****************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "{{ drupalvm_user }}: {{ ansible_ssh_user | default(ansible_env.SUDO_USER, true) | default(ansible_env.USER, true) | default(ansible_user_id) }}: 'ansible_ssh_user' is undefined"}

NO MORE HOSTS LEFT *************************************************************
        to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=96   changed=0    unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I hope the above helps. I'm in the process of trying CentOS7.

Is there any relationship between this problem and https://github.com/ansible/ansible/issues/13669?

**Comment by ColumbiaBlooms** [comment]
Ran vagrant destroy.

Ran vagrant up. No error messages with CentOS7, but got "This site can’t be reached. drupalvm.dev took too long to respond." from Chrome. 

Ran vagrant provision with the same results.

**Comment by geerlingguy** [comment]
With CentOS 6, can you try setting:

```
drupalvm_user: vagrant
```

Or if that doesn't work, try the following:

```
composer_home_path: "/home/vagrant/.composer"
composer_home_owner: "vagrant"
composer_home_group: "vagrant"
```

**Comment by ColumbiaBlooms** [comment]
After adding drupalvm_user: vagrant to config.yml the error message disappears, but when I type drupalvm.dev into Chrome I get "Internal Server Error. The server encountered an internal error or misconfiguration and was unable to complete your request. Please contact the server administrator, root@localhost and inform them of the time the error occurred, and anything you might have done that may have caused the error. More information about this error may be available in the server error log. Apache/2.2.15 (CentOS) Server at drupalvm.dev Port 80".

After changing the composer values (and leaving drupalvm_user: vagrant as-is I get the same result. 

After running vagrant provision  after vagrant up I get the same results.

Would you like to connect to my computer tomorrow using TeamViewer https://www.teamviewer.com/? I will be away for a large part of the day, but I can leave my computer running for you. I will need some secure method to give you the logon credentials.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Ah, now you're running into some issues with CentOS 6 itself. Basically, the way Drupal VM is architected, it expects a modern version of Apache or Nginx, and CentOS 6 defaults to 2.2, which has a lot of small differences...

It _is_ possible to use Drupal VM with CentOS 6 (and I do, for a couple old projects), but it _can_ require a _lot_ of changes to the `php_` variables, the `apache_vhosts`, and some other things besides, and I'd say it's only for power users.

See: http://docs.drupalvm.com/en/latest/other/base-os/#redhat-enterprise-linux-centos-6

See related:

  - https://github.com/geerlingguy/drupal-vm/issues/579
  - https://github.com/geerlingguy/drupal-vm/issues/434
  - https://github.com/geerlingguy/drupal-vm/issues/376

**Comment by geerlingguy** [comment]
I'm likely going to deprecate support for CentOS 6 at some point, as so few people use it in Drupal VM, and it creates way more problems than supporting it solves... especially since tests run so slow on it that I've decided to disable automated CentOS 6 tests.

**Comment by ColumbiaBlooms** [comment]
Thanks for the help. 

I would love to use current versions of all software, but I'm trying to track a subtle bug in Drupal which apparently relates to the particular version of OS, MySQL, PHP, etc between my local site and my live site on bluehost. Bluehost runs CentOS6 so in order rule out a problem with it and the other major pieces of software I have to mirror the bluehost site locally. I had my local site on Bitnami, but the versions of system software are different and I didn't get the error message from Drupal. If I migrate it to bluehost the error pops up. Some aspects of Drupal seem to be very sensitive to the various release levels ...

The advertised beauty of Vagrant is that one can create an environment locally that is highly customized. That's why I'm headed in this direction.

I'll post again if I'm still having problems with CentOS6.

**Comment by ColumbiaBlooms** [comment]
This may be a dumb question ...

When removing the ProxyPassMatch parameters I found one split on three lines.

#    extra_parameters: |
#          ProxyPassMatch ^/(.*\.php(/.*)?)$ "fcgi://127.0.0.1:9000{{ dashboard_install_dir }}"
#          DirectoryIndex index.html

Did I do it right to comment out all three?

**Comment by ColumbiaBlooms** [comment]
Update -

I made all the changes to config.yml that you suggested as best I could, but they do not fix the problem. In fact, vagrant up and vagrant provision fail.

I guess I'll go back to using  ubuntu1604 and try to change the versions of PHP, MySQL, etc. and hope that the OS is not the problem.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - What version of PHP is Bluehost running? CentOS 6 support is going away in early 2017... and PHP < 5.6 is already not supported, technically... just FYI :)

Ubuntu 16.04 only works with PHP > 7, and 14.04 does 5.4 and later. CentOS 7 does 5.4 by default (make sure you have `php_version: 5.4` of course, if you want to try this). But anything older than PHP 5.5 will be extremely hard to get working correctly unless you switch way back to Drupal VM 2.5.1.

**Comment by ColumbiaBlooms** [comment]
Gee.

This gets much more complicated than I had hoped. I'm just a lowly newbie trying to get my Drupal site to work.

Here are the versions of the various components at my live site at bluehost. Can you recommend a strategy to utilize DrupalVM to get my local site as close as possible to bluehost so I can get back to tracking down the problem in Drupal?

![image](https://cloud.githubusercontent.com/assets/12977583/17308382/47acdc90-57ff-11e6-833a-4fac03319b17.png)

I've not been able to verify that the version of Apache is correct.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - The simplest thing would be to use CentOS 7, with all the other defaults, and set `php_version` to `5.6`. That will give you Apache 2.4, PHP 5.6, and MySQL 5.5.

However, maybe I can help a tiny bit on the error side of things... what kind of errors are you seeing on Bluehost? There are a ton of other things that could be much different than a typical local environment (e.g. I believe Bluehost hosts databases on separate servers from the web hosts... which can cause some issues in certain situations).

**Comment by ColumbiaBlooms** [comment]
It will take me a while to upload to bluehost & recreate the problem.

I've been working with ostraining.com on these issues. Their take is that I need to set up a mirror image of the live site locally.

I will try CentOS7 with PHP 5.6 and see what happens. If you have the time and are interested in poking around on my machine we can connect with TeamViewer so that you can run stuff from my machine. If you're interested I need some way to securely send the TeamView credentials to you.

**Comment by ColumbiaBlooms** [comment]
Hmmm.

I get "This site can’t be reached. drupalvm.dev took too long to respond." from Chrome after running vagrant up with CentOS7 & php_version at 5.6.

vagrant status shows running. 

VirtualBox manager shows DrupalVM.dev powered off.

When I power on I get "Callee RC: E_FAIL (0x80004005)" and it stays powered off.

What's happening?

**Comment by geerlingguy** [comment]
It looks like you're having some weird VirtualBox issues... it might be time to nuke the VirtualBox directory and try over from scratch (see https://forums.virtualbox.org/viewtopic.php?f=6&t=53016).

Basically, do a `vagrant destroy -f`, then go into your user directory, and find your .VirtualBox directory and your .vagrant.d directory, and delete both. Then try `vagrant up` again.

Also, can you confirm the versions of Vagrant and VirtualBox you're running? (`vagrant --version` and `vboxmanage --version`).

**Comment by ColumbiaBlooms** [comment]
Vagrant is at 1.8.5. I get command not found for the vboxmanage --version command.

Deleting files & doing a destroy eliminated the error message, but I'm getting a timeout when I type drupalvm.dev into Chrome.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Okay, next up—if you're getting a timeout with `drupalvm.dev` in Chrome, that may mean your hosts file isn't set to point at the VM.

Can you run the command `vagrant plugin install vagrant-hostsupdater`, then run `vagrant halt`, then `vagrant up`? After that, the hosts file on your Windows machine should have an entry for http://drupalvm.dev/ and you could access it.

**Comment by ColumbiaBlooms** [comment]
Yea!

That fixed the problem.

Now I'll change PHP version to 5.6.

**Comment by ColumbiaBlooms** [comment]
OK. This is getting very frustrating. Vagrant/DrupalVM was my last hope to get my local site back up, but the code seems to be brittle.

The only change I made was to change the PHP version to 5.6. Now I'm back to the timeout screen in Chrome when I type drupalvm.dev.

Please explain why this is happening. Also, if there are logs somewhere that will help please tell me where they are located.

Thanks!

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Did you do a `vagrant destroy` then `vagrant up` after changing the PHP version? Currently switching versions on the fly isn't supported, though that feature should be coming soon.

The logs for the VM are stored inside the VM itself. There's an ability to view some logs through a log viewer interface, but otherwise, you have to `vagrant ssh` to log into the VM, then `cd` into the `/var/log/apache2` directory, and then you can use `cat` or `tail` to view the contents of the log files inside (e.g. 'other_vhosts_access' log).

**Comment by ColumbiaBlooms** [comment]
I ran vagrant destroy then vagrant up. I get no error messages, but the site refuses to load in Chrome. I get the usual timeout message noted above.

When I ssh into the VM to get error logs I get

$ vagrant ssh
[vagrant@drupalvm ~]$ cd /var/log/apache2
-bash: cd: /var/log/apache2: No such file or directory
[vagrant@drupalvm ~]$ cd var/log/apache2
-bash: cd: var/log/apache2: No such file or directory

This situation should be very easy for you to duplicate at your location. If not, I'll make my offer again for you to connect to my computer using TeamViewer.

**Comment by geerlingguy** [comment]
@ColumbiaBlooms - Sorry, forgot that you're running CentOS instead of Ubuntu, so the logs are somewhere in `/var/log`, but I don't remember which file exactly (should be like php, or php-fpm, or apache, or httpd).

You've gotten me in a very busy time (baby on the way soon, one big project wrapping up this month), I only have time to spot-reply here and there, can't join on TeamViewer (please realize that Drupal VM is an open source project, I'm paid nothing to work on it, and every time I help in the issue queue, it's basically a donation of personal time — I really hope I can help you get up and running, but it's not possible to devote more than a few minutes here and there.)

**Comment by ColumbiaBlooms** [comment]
I understand your situation. 

Given your availability I'm wondering what direction I should go in at this point. I've thought about going to D8, but I may run into a similar, weird error message as I'm dealing with in D7 unless I can exactly mirror the versions on the server locally. 

Vagrant seems to be the ideal tool for creating a very specific server environment if I could just learn how to do it. Little did I know a year ago when I started teaching myself Drupal that I'd also have to learn all this server stuff! I've been programming since 1970 and have a couple of degrees in Computer Science, but this business of building web pages is daunting!

Could you recommend another pre-defined box I could download that would be a good starting point or should I just start building a box from scratch? I'm currently reading "Creating Development Environments With Vagrant" and "Pro Vagrant". Both seem to be pretty good books.

**Comment by geerlingguy** [comment]
In terms of general learning/background, one of the best resources I like to recommend is [Vagrant Cookbook](https://leanpub.com/vagrantcookbook). And of course, if you want to get into the nitty-gritty of how Drupal VM is constructed, [Ansible for DevOps](https://www.ansiblefordevops.com/) is the best guide I know :D

**Comment by geerlingguy** [comment]
I'm going to close out this particular issue as it turned out to be a number of small things related to CentOS 6 usage (which is supported, but only _just so_ for now, like with Ubuntu 12.04). Please open any related follow-up problems/questions in their own new issues.
