### ISSUE TITLE
Add bcmath support for PHP to support commerceguys/intl

### ISSUE THREAD

**Issue by enzolutions** [geerlingguy/drupal-vm#840]
The default PHP bin on Drupal VM does not include bcmath support. Adding it would require compiling PHP with bcmath support, as it is not included by default. See http://php.net/manual/en/bc.installation.php

This is currently required for use of https://github.com/commerceguys/intl

There is a way to enable PHP extensions in config.yml

This is the error I got

```
Your requirements could not be resolved to an installable set of packages.
Problem 1
- commerceguys/intl dev-master requires ext-bcmath * -> the requested PHP extension bcmath is missing from your system.    
- drupal/commerce 8.2.x-dev requires commerceguys/intl dev-master -> satisfiable by commerceguys/intl[dev-master].    
- Installation request for drupal/commerce 8.2.x-dev -> satisfiable by drupal/commerce[8.2.x-dev].
To enable extensions, verify that they are enabled in those .ini files:    
- /etc/php/7.0/cli/php.ini\n    
- /etc/php/7.0/cli/conf.d/10-mysqlnd.ini\n    - /etc/php/7.0/cli/conf.d/10-opcache.ini\n    
- /etc/php/7.0/cli/conf.d/10-pdo.ini\n    - /etc/php/7.0/cli/conf.d/15-xml.ini\n    
- /etc/php/7.0/cli/conf.d/20-apcu.ini\n    - /etc/php/7.0/cli/conf.d/20-calendar.ini\n    
- /etc/php/7.0/cli/conf.d/20-ctype.ini\n    - /etc/php/7.0/cli/conf.d/20-curl.ini\n    
- /etc/php/7.0/cli/conf.d/20-dom.ini\n    - /etc/php/7.0/cli/conf.d/20-exif.ini\n    
- /etc/php/7.0/cli/conf.d/20-fileinfo.ini\n    - /etc/php/7.0/cli/conf.d/20-ftp.ini\n    
- /etc/php/7.0/cli/conf.d/20-gd.ini\n    - /etc/php/7.0/cli/conf.d/20-gettext.ini\n    
- /etc/php/7.0/cli/conf.d/20-iconv.ini\n    - /etc/php/7.0/cli/conf.d/20-imap.ini\n    
- /etc/php/7.0/cli/conf.d/20-json.ini\n    - /etc/php/7.0/cli/conf.d/20-mbstring.ini\n    
- /etc/php/7.0/cli/conf.d/20-mysqli.ini\n    - /etc/php/7.0/cli/conf.d/20-pdo_mysql.ini\n    
- /etc/php/7.0/cli/conf.d/20-pdo_sqlite.ini\n    - /etc/php/7.0/cli/conf.d/20-phar.ini\n    
- /etc/php/7.0/cli/conf.d/20-posix.ini\n    - /etc/php/7.0/cli/conf.d/20-readline.ini\n    
- /etc/php/7.0/cli/conf.d/20-shmop.ini\n    - /etc/php/7.0/cli/conf.d/20-simplexml.ini\n    
- /etc/php/7.0/cli/conf.d/20-sockets.ini\n    - /etc/php/7.0/cli/conf.d/20-sqlite3.ini\n    
- /etc/php/7.0/cli/conf.d/20-sysvmsg.ini\n    - /etc/php/7.0/cli/conf.d/20-sysvsem.ini\n    
- /etc/php/7.0/cli/conf.d/20-sysvshm.ini\n    - /etc/php/7.0/cli/conf.d/20-tokenizer.ini\n    
- /etc/php/7.0/cli/conf.d/20-wddx.ini\n    - /etc/php/7.0/cli/conf.d/20-xmlreader.ini\n    
- /etc/php/7.0/cli/conf.d/20-xmlwriter.ini\n    
- /etc/php/7.0/cli/conf.d/20-xsl.ini\n  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.", "stdout": "", "stdout_lines": [], "warnings": []}
```

**Comment by illepic** [comment]
Noting here that `bcmath` will make installing OpenSocial less painful as well:

https://www.drupal.org/node/2755643

**Comment by enzolutions** [comment]
I just resolve my issues adding bcmath as extra packages in my cofig.yml

```
extra_packages:
  - sqlite
  - php-bcmath
```

**Comment by geerlingguy** [comment]
@illepic / @enzolutions - The best way to do this would be to override the `php_packages` in `config.yml` or `local.config.yml`. This way all the required packages are stored/listed in the same place, and PHP version upgrades should go more smoothly.

See: https://github.com/geerlingguy/ansible-role-php/pull/144

**Comment by mglaman** [comment]
So I know this was closed. But, @geerlingguy, we're getting a lot of users of Drupal Commerce asking us w/ install woes and DrupalVM. Adding bcmath would fix this, echoing @illepic

**Comment by twerthmueller** [comment]
@geerlingguy it would be great to have it enabled by default or maybe you can add it in the example config.yml.

**Comment by thom8** [comment]
Default php packages are defined in the [PHP role](https://github.com/geerlingguy/ansible-role-php) - https://github.com/geerlingguy/ansible-role-php/tree/master/vars

I prefer to always define PHP packages for each project as I don't want upstream changes to ever affect these.

**Comment by geerlingguy** [comment]
Also linking https://github.com/acquia/blt/pull/503

**Comment by nadavoid** [comment]
Noting here that the simplest way to add bcmath support is adding this to the `config.yml`:

```yaml
php_packages_exra:
  - php7.0-bcmath
```

and run `vagrant provision`.

**Comment by JohnatasJMO** [comment]
I can see that
`php_packages_extra: `
is not included into config.yml file, can it be added?

**Comment by geerlingguy** [comment]
@JohnatasJMO - You can add it into your own `config.yml` or `local.config.yml` file as needed.

**Comment by karimsmartica** [comment]
Thx @nadavoid You save my day. 

For the others, don't forget the version number of PHP.  If you are with PHP 7.1 just put this in your config.yml

php_packages_extra:
  - php7.1-bcmath

save and then run: vagrant provision

**Comment by jtphelan** [comment]
I'm having no luck with this with geerlingguy/centos7.

with php7.1-bcmath i get:

> failed: [commercevm] (item=[u'sqlite', u'php7.1-bcmath']) => {"changed": false, "item": ["sqlite", "php7.1-bcmath"], "msg": "No package matching 'php7.1-bcmath' found available, installed or updated", "rc": 126, "results": ["sqlite-3.7.17-8.el7.x86_64 providing sqlite is already installed", "No package matching 'php7.1-bcmath' found available, installed or updated"]}

with php-bcmath I get 

> failed: [commercevm] (item=[u'sqlite', u'php-bcmath']) => {"changed": false, "item": ["sqlite", "php-bcmath"], "msg": "Error: Package: php-bcmath-5.4.16-45.el7.x86_64 (base)\n           Requires: php-common(x86-64) = 5.4.16-45.el7\n           Installed: php-common-7.1.17-1.el7.remi.x86_64 (@remi-php71)\n               php-common(x86-64) =7.1.17-1.el7.remi\n           Available: php-common-5.4.16-45.el7.x86_64 (base)\n               php-common(x86-64) = 5.4.16-45.el7\n", "rc": 1, "results": ["sqlite-3.7.17-8.el7.x86_64 providing sqlite is already installed", "Loaded plugins: fastestmirror\nLoading mirror speeds from cached hostfile\n * base: www.gtlib.gatech.edu\n * epel: mirror.redsox.cc\n * extras: mirror.teklinks.com\n * remi-safe: repo1.ash.innoscale.net\n * updates: repo1.ash.innoscale.net\nResolving Dependencies\n--> Running transaction check\n---> Package php-bcmath.x86_64 0:5.4.16-45.el7 will be installed\n--> Processing Dependency: php-common(x86-64) = 5.4.16-45.el7 for package: php-bcmath-5.4.16-45.el7.x86_64\n--> Finished Dependency Resolution\n You could try using --skip-broken to work around the problem\n You could try running: rpm -Va --nofiles --nodigest\n"]}

I did `yum search bcmath` and I see

> php-bcmath.x86_64 : A module for PHP applications for using the bcmath library
> php54-php-bcmath.x86_64 : A module for PHP applications for using the bcmath library
> php55-php-bcmath.x86_64 : A module for PHP applications for using the bcmath library
> php56-php-bcmath.x86_64 : A module for PHP applications for using the bcmath library
> php70-php-bcmath.x86_64 : A module for PHP applications for using the bcmath library
> php71-php-bcmath.x86_64 : A module for PHP applications for using the bcmath library
> php72-php-bcmath.x86_64 : A module for PHP applications for using the bcmath library

so I tried php71-php-bcmath and I get
failed: [labstrongvm] (item=[u'sqlite', u'php7.1-php-bcmath']) => {"changed": false, "item": ["sqlite", "php7.1-php-bcmath"], "msg": "No package matching 'php7.1-php-bcmath' found available, installed or updated", "rc": 126, "results": ["sqlite-3.7.17-8.el7.x86_64 providing sqlite is already installed", "No package matching 'php7.1-php-bcmath' found available, installed or updated"]}

**Comment by geerlingguy** [comment]
@jtphelan - For your last attempt, maybe you didn't save the file? The error shows:

```
failed: [labstrongvm] (item=[u'sqlite', u'php7.1-php-bcmath'])
```

But you said you tried `php71-php-bcmath`... without the `.`

**Comment by jtphelan** [comment]
Good catch. I changed it to `php71-php-bcmath` and the vm installed without error, however, if I try the site again I still get. 

`Error: Call to undefined function Drupal\commerce_price\bcadd() in /var/www/drupal8/web/modules/contrib/commerce/modules/price/src/Calculator.php on line 33 #0 /var/www/drupal8/web/modules/contrib/commerce/modules/price/src/Price.php(109): Drupal\commerce_price\Calculator::add('133.000000', '141.000000')`

and if I do a `yum list installed | grep remi` I see it is installed
gd-last.x86_64                       2.2.5-2.el7.remi                @remi      
php.x86_64                           7.1.17-1.el7.remi               @remi-php71
php-cli.x86_64                       7.1.17-1.el7.remi               @remi-php71
php-common.x86_64                    7.1.17-1.el7.remi               @remi-php71
php-devel.x86_64                     7.1.17-1.el7.remi               @remi-php71
php-fedora-autoloader.noarch         1.0.0-1.el7.remi                @remi      
php-fpm.x86_64                       7.1.17-1.el7.remi               @remi-php71
php-gd.x86_64                        7.1.17-1.el7.remi               @remi-php71
php-imap.x86_64                      7.1.17-1.el7.remi               @remi-php71
php-json.x86_64                      7.1.17-1.el7.remi               @remi-php71
php-ldap.x86_64                      7.1.17-1.el7.remi               @remi-php71
php-mbstring.x86_64                  7.1.17-1.el7.remi               @remi-php71
php-mcrypt.x86_64                    7.1.17-1.el7.remi               @remi-php71
php-mysqlnd.x86_64                   7.1.17-1.el7.remi               @remi-php71
php-opcache.x86_64                   7.1.17-1.el7.remi               @remi-php71
php-pdo.x86_64                       7.1.17-1.el7.remi               @remi-php71
php-pear.noarch                      1:1.10.5-6.el7.remi             @remi      
php-pecl-apcu.x86_64                 5.1.11-1.el7.remi.7.1           @remi-php71
php-pecl-yaml.x86_64                 2.0.2-1.el7.remi.7.1            @remi-php71
php-process.x86_64                   7.1.17-1.el7.remi               @remi-php71
php-xml.x86_64                       7.1.17-1.el7.remi               @remi-php71
php-xmlrpc.x86_64                    7.1.17-1.el7.remi               @remi-php71
php71-php-bcmath.x86_64              7.1.17-1.el7.remi               @remi-safe 
php71-php-common.x86_64              7.1.17-1.el7.remi               @remi-safe 
php71-php-json.x86_64                7.1.17-1.el7.remi               @remi-safe 
php71-runtime.x86_64                 1.0-1.el7.remi                  @remi-safe 
remi-release.noarch                  7.4-2.el7.remi                  installed

**Comment by geerlingguy** [comment]
That's odd, it looks like a problem with caches or with Commerce:

```
Error: Call to undefined function Drupal\commerce_price\bcadd()
```

**Comment by arun9989** [comment]
I am getting this 

`TASK [geerlingguy.php : Update apt cache.] *************************************
ok: [mystore]

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
fatal: [mystore]: FAILED! => {"changed": false, "msg": "No package matching 'php71-php-bcmath' is available"}

PLAY RECAP *********************************************************************
mystore                    : ok=68   changed=0    unreachable=0    failed=1    skipped=65   rescued=0    ignored=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`
