### ISSUE TITLE
ERROR! Syntax error while loading YAML.

### ISSUE THREAD

**Issue by ividyon** [geerlingguy/drupal-vm#841]
```
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit nfs mounting file.
[NFS] Status: running
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Running ansible-playbook...
ERROR! Syntax Error while loading YAML.


The error appears to have been in '<string>': line 1, column 12, but may
be elsewhere in the file depending on the exact syntax problem.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

This occurs on a Windows 10 host, using DrupalVM 3.2.0, trying to `vagrant up` the base config without any changes.

**Comment by geerlingguy** [comment]
It seems like it might be related to line endings, based on a quick glance; see http://docs.drupalvm.com/en/latest/other/windows/#git-and-file-permissions

Did you clone Drupal VM using git, and if so, with what client? Otherwise, if you downloaded it with the zip file or tarball, how did you expand the file?

**Comment by ividyon** [comment]
Hmm, let's see. I had downloaded "geerlingguy-drupal-vm-3.2.0-0-gbfb50bb.zip" via Chrome and extracted it with 7Zip (http://www.7-zip.org/). Which approach would be the most recommendable? I have some kind of windows version of Git on hand (GIT Bash, GIT Gui, or PowerShell/cmd versions).

**Comment by geerlingguy** [comment]
Hmm... I can't seem to reproduce the error; what version of Vagrant are you running? (`vagrant --version`)? Vagrant 1.8.5 seems to be the best option on Windows right now; there were some issues with 1.8.2-1.8.4, and the local provisioner won't work at all on any older versions.

**Comment by drummerman375** [comment]
I've been having this same issue to on my Ubuntu 16.04 host and using the VM version 1.8.1. I even ran `vagrant provision` multiple times and the same issue occurs.

**Comment by geerlingguy** [comment]
@drummerman375 - Can you run `vagrant --version` to confirm the version you're running? Drupal VM now only supports Vagrant 1.8.2 or higher on Windows, and 1.8.5 is the recommended release.

**Comment by epopas** [comment]
Had the same problem with Vagrant 1.8.1 on Linux. Updated to 1.8.5 and everything works OK

**Comment by ividyon** [comment]
Can confirm! Updating Vagrant to 1.8.5 fixed the problem.

**Comment by geerlingguy** [comment]
Awesome! Glad I could help; I'm guessing this is triggered if you don't have Ansible installed on the host, because this uses the `ansible_local` provisioner which, IIRC, had a bug on 1.8.1 that caused us to wait to use it until 1.8.2 was released.
