### ISSUE TITLE
Error d/l

### ISSUE THREAD

**Issue by jminker** [geerlingguy/drupal-vm#842]
seems to always be getting the issue below when running "vagrant up"

 drupalvm: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604/versions/1.0.4/providers/virtualbox.box
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x Vagrantfile
x box.ovf
x metadata.json
x packer-ubuntu-16.04-amd64-disk1.vmdk: gzip decompression failed
bsdtar: Error exit delayed from previous errors.

**Comment by geerlingguy** [comment]
@jminker - Can you run the following command and see if it works?

```
$ vagrant box add geerlingguy/ubuntu1604
```

**Comment by geerlingguy** [comment]
Also, what is your host OS/environment, and if Windows, what CLI tool are you using?

**Comment by jminker** [comment]
That worked;

vagrant box add geerlingguy/ubuntu1604
==> box: Loading metadata for box 'geerlingguy/ubuntu1604'
    box: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1604
==> box: Adding box 'geerlingguy/ubuntu1604' (v1.0.4) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604/versions/1.0.4/providers/virtualbox.box
==> box: Successfully added box 'geerlingguy/ubuntu1604' (v1.0.4) for 'virtualbox'!

Version;
uname -a
Linux Ubuntu-JDM 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux


Where should I now pick up from with vagrant ?

Thanks for your help!!

**Comment by geerlingguy** [comment]
Sure thing! Try `vagrant up` again, and I think it'll work.

It was likely a network issue... happens from time to time, for mysterious reasons.

**Comment by jminker** [comment]
you must hate people like me..

vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Preparing master VM for linked clones...
    drupalvm: This is a one time operation. Once the master VM is prepared,
    drupalvm: it will be used as a base for linked clones, making the creation
    drupalvm: of new VMs take milliseconds on a modern system.
==> drupalvm: Importing base box 'geerlingguy/ubuntu1604'...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/john/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1604/1.0.4/virtualbox/box.ovf", "--vsys", "0", "--vmname", "packer-ubuntu-16.04-amd64_1470073131288_38049", "--vsys", "0", "--unit", "7", "--disk", "/home/john/VirtualBox VMs/packer-ubuntu-16.04-amd64_1470073131288_38049/packer-ubuntu-16.04-amd64-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/john/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1604/1.0.4/virtualbox/box.ovf...
OK.
0%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/home/john/VirtualBox VMs/packer-ubuntu-16.04-amd64_1470073131288_38049/packer-ubuntu-16.04-amd64-disk1.vmdk'.
VBoxManage: error: VMDK: Compressed image is corrupted '/home/john/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1604/1.0.4/virtualbox/packer-ubuntu-16.04-amd64-disk1.vmdk' (VERR_ZIP_CORRUPTED)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 877 of file VBoxManageAppliance.cpp

**Comment by geerlingguy** [comment]
> you must hate people like me..

Not at all! You give detailed information, so it's easier to debug :)

Next try:

```
$ vagrant box remove geerlingguy/ubuntu1604
... wait for it to finish ...
$ vagrant box add geerlingguy/ubuntu1604 --box-version 1.0.3
```

For some reason your download of 1.0.4 was corrupted... see if 1.0.3 works—if so, maybe I can do some extra checking on the integrity of the file on my server. If it doesn't, maybe there's some strange network issue.

**Comment by jminker** [comment]
same under the 1.0.3 version...

john@Ubuntu-JDM:~/VirtualBox VMs/geerlingguy-drupal-vm-bfb50bb$ vagrant box remove geerlingguy/ubuntu1604
Removing box 'geerlingguy/ubuntu1604' (v1.0.4) with provider 'virtualbox'...
john@Ubuntu-JDM:~/VirtualBox VMs/geerlingguy-drupal-vm-bfb50bb$ vagrant box add geerlingguy/ubuntu1604 --box-version 1.0.3
==> box: Loading metadata for box 'geerlingguy/ubuntu1604'
    box: URL: https://atlas.hashicorp.com/geerlingguy/ubuntu1604
This box can work with multiple providers! The providers that it
can work with are listed below. Please review the list and choose
the provider you will be working with.

1) virtualbox
2) vmware_desktop

Enter your choice: 1
==> box: Adding box 'geerlingguy/ubuntu1604' (v1.0.3) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/geerlingguy/boxes/ubuntu1604/versions/1.0.3/providers/virtualbox.box
==> box: Successfully added box 'geerlingguy/ubuntu1604' (v1.0.3) for 'virtualbox'!
john@Ubuntu-JDM:~/VirtualBox VMs/geerlingguy-drupal-vm-bfb50bb$ vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Preparing master VM for linked clones...
    drupalvm: This is a one time operation. Once the master VM is prepared,
    drupalvm: it will be used as a base for linked clones, making the creation
    drupalvm: of new VMs take milliseconds on a modern system.
==> drupalvm: Importing base box 'geerlingguy/ubuntu1604'...
Progress: 50%There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["import", "/home/john/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1604/1.0.3/virtualbox/box.ovf", "--vsys", "0", "--vmname", "packer-ubuntu-16.04-amd64_1470073685332_74754", "--vsys", "0", "--unit", "7", "--disk", "/home/john/VirtualBox VMs/packer-ubuntu-16.04-amd64_1470073685332_74754/packer-ubuntu-16.04-amd64-disk1.vmdk"]

Stderr: 0%...10%...20%...30%...40%...50%...60%...70%...80%...90%...100%
Interpreting /home/john/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1604/1.0.3/virtualbox/box.ovf...
OK.
0%...10%...20%...30%...40%...50%...
Progress state: VBOX_E_FILE_ERROR
VBoxManage: error: Appliance import failed
VBoxManage: error: Could not create the imported medium '/home/john/VirtualBox VMs/packer-ubuntu-16.04-amd64_1470073685332_74754/packer-ubuntu-16.04-amd64-disk1.vmdk'.
VBoxManage: error: VMDK: Compressed image is corrupted '/home/john/.vagrant.d/boxes/geerlingguy-VAGRANTSLASH-ubuntu1604/1.0.3/virtualbox/packer-ubuntu-16.04-amd64-disk1.vmdk' (VERR_ZIP_CORRUPTED)
VBoxManage: error: Details: code VBOX_E_FILE_ERROR (0x80bb0004), component ApplianceWrap, interface IAppliance
VBoxManage: error: Context: "RTEXITCODE handleImportAppliance(HandlerArg*)" at line 877 of file VBoxManageAppliance.cpp

**Comment by geerlingguy** [comment]
All right, I guess one other thing: can you list the version of `vagrant --version`, and `vboxmanage --version`?

I'm pretty certain nobody else has reported this issue with those box files, and I tested both just now downloading from files.midwesternmac.com, so I know they're not corrupt on the server itself.

**Comment by geerlingguy** [comment]
Also, another thing to try (if you don't have any other vagrant boxes on your computer you care about) is deleting the entire `.vagrant.d` directory: `$ rm -rf ~/.vagrant.d`

It's the nuclear option, but if there's a funky file in there, that can help.

**Comment by jminker** [comment]
sometimes the only option that seems to work...script is into 10mins of running...thanks for your help!!

![nuclearoption](https://cloud.githubusercontent.com/assets/19754796/17304278/7d03e876-57ea-11e6-9fe6-eea094c31242.jpg)

**Comment by geerlingguy** [comment]
Well, they aren't pretty, but nuclear solutions do sometimes work!
