### ISSUE TITLE
Failed to validate the SSL certificate for deb.nodesource.com:443

### ISSUE THREAD

**Issue by naveenvalecha** [geerlingguy/drupal-vm#844]
fatal: [comcast-ch]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for deb.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}

**Solution**

I found couple of solution by adding 3rd party repository
https://github.com/ansible/ansible/issues/12161#issuecomment-157325689

**Comment by geerlingguy** [comment]
Thanks for posting this! I haven't seen this error on Ubuntu 16.04/14.04 or CentOS 7, so I'm wondering if it might be an out of date set of CA certs on older Ubuntu 12.04 installs (is that the `vagrant_box` version you're running?).

**Comment by naveenvalecha** [comment]
I'm using `vagrant_box: geerlingguy/ubuntu1604`

**Comment by geerlingguy** [comment]
Strange... I wonder if nodesource is using some new untrusted CA or something...? I haven't run into this issue lately, but it seems to crop up every 6-12 months for someone. It could also be a regional thing, maybe, not sure.

I'll leave this open in case anyone else runs into it, but I can't reproduce the problem right now in my local environment.

**Comment by vyasamit2007** [comment]
Same issue with me as well here is the error message I got:
`fatal: [some-name]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for drupalconsole.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}`

**Comment by geerlingguy** [comment]
@vyasamit2007 - Hmm... in this case it's for drupalconsole. I'm guessing they're using LetsEncrypt, or maybe some other certificate authority which might not be in the trusted store on Ubuntu 16.04 default? HTTPS is a blessing and a curse :)

**Comment by vyasamit2007** [comment]
I've followed these steps to fix this:
`sudo ansible-galaxy install -rgeerlingguy/drupal-vm/provisioning/requirements.yml --force`
after it successfully completes all the required installations, I've then run:
`vagrant up`.

Hope it helps to someone, but I'm unsure why that fatal error related to SSL certificate came in.

Thanks!!
~Amit

**Comment by geerlingguy** [comment]
Interesting, maybe the version of Drupal VM you were running was a few point versions behind—the past two releases include all the roles at the current version with Drupal VM itself, so there should be no need for installing required roles again—though thanks for posting that solution, as I'm guessing it'll help with others!

**Comment by fluxsauce** [comment]
Nope, not Drupal Console, it's the `installed_extras` `npm` with `ansible_local` on `3.2.1` using `geerlingguy/ubuntu1404`. 

```
TASK [geerlingguy.nodejs : Add Nodesource apt key.] ****************************
fatal: [nyu-wagner.local]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to validate the SSL certificate for deb.nodesource.com:443. Make sure your managed systems have a valid CA certificate installed. If the website serving the url uses SNI you need python >= 2.7.9 on your managed machine or you can install the `urllib3`, `pyopenssl`, `ndg-httpsclient`, and `pyasn1` python modules to perform SNI verification in python >= 2.6. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible"}
```

```bash
python --version
Python 2.7.6
```

My workaround was to add:

```yml
extra_packages:
  - npm
```

**Comment by jorgegc** [comment]
Hey Jeff, this is still an issue for me and neither of the solutions above worked. I am using ubuntu1404 too.

**Comment by mfergus1** [comment]
I'm also seeing this error. Grabbing the key was working fine and has suddenly stopped succeeding because the cert cannot be validated.

**Comment by geerlingguy** [comment]
I'm working on fixes in upstream role https://github.com/geerlingguy/ansible-role-nodejs — apparently nodesource moved to Cloudfront and new SSL setup, which broke older distros.

**Comment by geerlingguy** [comment]
Moving further discussion to #896

**Comment by ningxiaogu** [comment]
Hi,geerlingguy, I got the same issue.
 I went to https://galaxy.ansbibe.com   and found some wonderful playbook-role wrote by you. 
My environment is centos 6.8 and python 2.6.7 .
found this:"[Error]: failed to validate the ssl certificate  https://galaxy.ansbibe.com:443" and so on.
Can you give me some solution???
THX @geerlingguy

**Comment by WilhelmErasmus** [comment]
I'm getting
`"msg": "Failed to validate the SSL certificate for drupalconsole.com:443. Make sure your managed systems have a valid CA certificate installed. You can use validate_certs=False if you do not need to confirm the servers identity but this is unsafe and not recommended. Paths checked for this platform: /etc/ssl/certs, /etc/pki/ca-trust/extracted/pem, /etc/pki/tls/certs, /usr/share/ca-certificates/cacert.org, /etc/ansible. The exception msg was: (\"bad handshake: Error([('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')],)\",)."
}`
