### ISSUE TITLE
Integrate with vagrant-proxyconf

### ISSUE THREAD

**Issue by morsok** [geerlingguy/drupal-vm#847]
For those of us behing corporate proxy it would be awesome if DrupalVM can integrate with this plugin !

[vagrant-proxyconf github](https://github.com/tmatilai/vagrant-proxyconf)

A PR should follow soon.

**Comment by geerlingguy** [comment]
Thanks for the issue/PR; I'll have to poke and prod a little more to see how this would work... note that you can currently configure the proxy using a `Vagrantfile.local` or delegated Vagrantfile. See relevant docs here: http://docs.drupalvm.com/en/latest/other/overriding-configurations/

**Comment by theodoreb** [comment]
No problems with using a Vagrantfile.local file for this.
