### ISSUE TITLE
Build Lightning Drupal with composer????

### ISSUE THREAD

**Issue by haynescw** [geerlingguy/drupal-vm#849]
Is there a way using drupal vm to buildout a drupal site using the lightning profile with composer?

**Comment by thom8** [comment]
Take a look @ BLT -- https://github.com/acquia/blt 

or you could try -- https://github.com/thom8/beetbox/tree/lightning

**Comment by geerlingguy** [comment]
+1 to @thom8's suggestion; using/installing drupal profiles is supported by Drupal VM, and specific install profile examples are maintained elsewhere (BLT being one simple-ish example). I'd rather not add any particular profile example as canonical, but if you can think of anything we can add/change in the docs to help with this, let me know in a new issue!
