### ISSUE TITLE
vagrant up fails - on apache2 install  `/var/www/html.dpkg-new': Operation not permitted

### ISSUE THREAD

**Issue by tweevick** [geerlingguy/drupal-vm#85]
msg: 'apt-get install 'apache2' 'apache2-mpm-prefork' 'apache2-utils' ' failed: dpkg: error processing archive /var/cache/apt/archives/apache2_2.4.12-1+deb.sury.org~trusty+5_amd64.deb (--unpack):
 error setting ownership of `/var/www/html.dpkg-new': Operation not permitted

**Comment by geerlingguy** [comment]
@tweevick - What kind of synced folder are you using? This looks like a potential permissions issue, and might be because of incorrect settings with `smb` or `rsync` shares.

**Comment by geerlingguy** [comment]
If you're still having an issue, please feel free to comment on this issue again; I will reopen if needed.

**Comment by geerlingguy** [comment]
More notes to anyone else experiencing similar issues:

  - https://github.com/puphpet/puphpet/issues/990
  - https://github.com/puphpet/puphpet/wiki/Shared-Folder:-Permission-Denied
  - https://github.com/puphpet/puphpet/issues/810

It looks like it's a permissions issue, likely only occurring in VirtualBox with certain settings. One thing you might want to try is setting the synced folder to something other than `/var/www` (maybe try a subdirectory in there instead?).

**Comment by lmeurs** [comment]
Setting the `vagrant_synced_folders` > `destination` argument to ie. `/var/www/drupalvm` did the trick on Ubuntu 14.04, latest DrupalVM using NFS and VirtualBox 5.0.2. Many thanks!

**Comment by andriyun** [comment]
In my case problem was in apache install folder.
By default apache create /var/www/html folder.
After create this folder manualy and change proper path in config.yml file installation process go no the next step

**Comment by miloskroulik** [comment]
https://github.com/geerlingguy/drupal-vm/issues/85#issuecomment-134315326 also worked for me

**Comment by kporras07** [comment]
Same issue for me.
I did the workaround proposed in https://github.com/geerlingguy/drupal-vm/issues/85#issuecomment-134315326 but I'd love to see a real solution to this.

**Comment by geerlingguy** [comment]
See related: #247 — and please move discussion over to that issue.
