### ISSUE TITLE
PHP 5.6

### ISSUE THREAD

**Issue by kurtsalsa** [geerlingguy/drupal-vm#851]
I changed the _ php_version_ to 5.6 in config.yml, however php 7.0 is still installed for both web and cli? 

I have a site that won't work on 7.0, so what other changes do I need to make to only install 5.6?

**Comment by thom8** [comment]
http://docs.drupalvm.com/en/latest/other/php-56/

**Comment by geerlingguy** [comment]
@kurtsalsa - Also, note that currently you can't change the PHP version on the fly (hopefully coming in https://github.com/geerlingguy/drupal-vm/pull/714), so if you have 7, and you want to switch to 5.6, you'll have to make the changes in the docs (e.g. change OS to Ubuntu 14.04 as well), then run `vagrant destroy` to destroy the VM, then `vagrant up` to bring it back up.
