### ISSUE TITLE
Error during install

### ISSUE THREAD

**Issue by kalinchernev** [geerlingguy/drupal-vm#854]
Hi, I just cloned the repo and ran the `vagrant up` without any customization.
I got this error close to the end of the process:
```
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
[sudo] password for kalin: 
nfsd running
exportfs: duplicated export entries:
exportfs: 	192.168.88.88:/home/kalin/projects/drupal-vm
exportfs: 	192.168.88.88:/home/kalin/projects/drupal-vm
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Running ansible-playbook...
ERROR! Syntax Error while loading YAML.


The error appears to have been in '<string>': line 1, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by geerlingguy** [comment]
@kalinchernev - Can you check what version of Vagrant you have installed? You need at least 1.8.4, preferably 1.8.5, to work with the latest version of Drupal VM. (You can check with `vagrant --version`).

I'm going to preemptively close this issue as I'm fairly certain that's the problem, but let me know if it's not, and we can reopen the issue and dig further. Thanks!

**Comment by kalinchernev** [comment]
Issue solved with the update.

**Comment by geerlingguy** [comment]
Great!

**Comment by hidace** [comment]
Yes, had the exact same issue. Upgrading Vagrant version solved it. Thanks!!
