### ISSUE TITLE
NGINX 120 second hard PHP timeout

### ISSUE THREAD

**Issue by codycraven** [geerlingguy/drupal-vm#856]
While debugging scripts in PHP we at times exceed 120 seconds of execution time. I found the availability of the php_max_execution_time configuration in #93 and was able to set that to a high number of seconds without issue.

However I run into a problem with NGINX's fastcgi_read_timeout setting of 120 in provisioning/templates/nginx-vhost.conf.j2.

Is there a way to override this setting without hacking the template file or hacking provisioning/tasks/www.yml?

Or would it make sense to just increase this value to something high enough to allow complex debugging (such as 600)?

**Comment by geerlingguy** [comment]
What I should _probably_ do is set that timeout to the same value as you would have set in your `php_max_execution_time` variable. And, in fact, I'm going to do that now :)

**Comment by geerlingguy** [comment]
This change is in master; please either cherry pick it or wait for a new tagged release (I'll hold off until there are a few more changes).
