### ISSUE TITLE
xhprof module: Class `XHProfRequestMatcher` not found - Fixed but why??

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#857]
For the last couple of days I've been struggling with an issue related to the xhprof module which was ultimately fixed by doing a `vagrant reload --provision`. I posted a question on drupal.stackexchange here: http://drupal.stackexchange.com/questions/210988/how-can-i-fix-or-troubleshoot-fatal-error-class-not-found-with-xhprof-module

Here's the error I was seeing: 

```
Class 'Drupal\xhprof\RequestMatcher\XHProfRequestMatcher' not found in /var/www/mysite/docroot/core/lib/Drupal/Component/DependencyInjection/Container.php on line 272
```

I'm essentially running a BLT site with Drupal-VM and got xhprof to work no problem. Then after making some git changes so I could cherry-pick a commit back to a forked origin repo, I started to get the PHP fatal error above. 

Everything points to the error being some sort of Autoload issue but why on earth would `vagrant reload --provision` somehow fix this? Things I tried prior to this that did not work at all

- clearing cache with drush and drupal console
- reverting my database to the previous working state
- reinstalling drupal with the BLT phing tasks
- and probably a few other things I'm not remembering now...

Are there some autoload cache files that get stored in /tmp or something that could possibly be related? I realize I'm on a bit of a "wild goose chase" here but just trying to understand how the fix fixed things.

**Comment by geerlingguy** [comment]
Did you try restarting `php5-fpm` and/or the entire instance prior to trying the `vagrant reload --provision`? I can see PHP's own caches getting gummed up and the `reload` itself (aside from the provision) might've been enough to shake out the problem.

It's a classic case of [percussive maintenance](https://en.wiktionary.org/wiki/percussive_maintenance).

**Comment by justinlevi** [comment]
Jeff, thanks for the response. Yeah, in retrospect I should have definitely tried a php restart before doing the vagrant reload --provision. I need to come up with a checklist for debugging in times like this. I tend to reach for the biggest hammer when a screw driver may do the job a bit more efficiently. 

Cheers.

**Comment by geerlingguy** [comment]
Well, if the biggest hammer works :P

**Comment by justinlevi** [comment]
:) agreed. 

Hey @geerlingguy - I tried to add a few more xdebug config options upstream and I noticed a few PRs that go back a while on your `ansible-role-php-xdebug`. Any chance you could merge those when you get a chance or is there a reason we wouldn't want to include those with this project? 

https://github.com/geerlingguy/ansible-role-php-xdebug/pulls

Cheers.
