### ISSUE TITLE
Add Drupal Console for Drupal 8+

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#86]
http://drupalconsole.com/

**Comment by geerlingguy** [comment]
Definitely something I'd like to do/consider. In #55 I made it so Drupal VM can create a set of Drush aliases for configured Drupal sites (based on the configured vhosts); for Drupal Console, how do you tell the console where your drupal sites live?

Is it based on the current working directory only, or is there some sort of aliasing system?

I noticed https://github.com/hechoendrupal/DrupalConsole/issues/515 mentions a `~/.console/config.yml` file (yay YAML!), but there's no mention in the docs of how to run arbitrary console commands on different Drupal installations...?

**Comment by jmolivas** [comment]
@geerlingguy DrupalConsole does not support site aliases out of the box now, but I spent a couple of days working with Greg Anderson on a console/drush integration the result was several updates to Console and this PR to drush:

https://github.com/drush-ops/drush/pull/1337

Once this is completed and merged, console commands will be discoverable by drush and can be used like:

```
$ drush @mysite.dev console:command
```

**Comment by geerlingguy** [comment]
I've added a new Ansible Galaxy role, [`geerlingguy.drupal-console`](https://galaxy.ansible.com/list#/roles/3734), which installs Drupal Console and aliases it properly. Local testing seems good to go, so I'm going to push out an update soon, and then you can ssh into the VM (with `vagrant ssh`) and `drupal` away!

The only thing that's not working yet is self-updating Drupal Console, but hopefully that will get resolved upstream in https://github.com/hechoendrupal/DrupalConsole/issues/615 soon.
