### ISSUE TITLE
Add a new site - apply changes in config.yml

### ISSUE THREAD

**Issue by K3vinF** [geerlingguy/drupal-vm#860]
I usually have multiple sites running inside a single instance.
When I add a new site, I add new entry to vagrant_synced_folders and a new entry to apache_vhosts in the config.yml file.
To get the new changes to apply I aways run a 'vagrant halt' and 'vagrant provision' command. But this feels like a bit overkill. 
Is there an easier way to get the changes to apply?

**Comment by thom8** [comment]
You can run `vagrant reload --provision` but it's effectively the same.

A reload is required to setup the new synced folders & a provision is required to set the new vhosts.

**Comment by geerlingguy** [comment]
@thom8 is correct; you have to reload Vagrant to get synced folders working. If it's just a vhosts change/addition, you can just run `vagrant --provision` on a running instance.

Someday, I may have a faster method for certain kinds of config changes, but for now it does a full provision any time you want to change anything.

**Comment by K3vinF** [comment]
Thanks for the help! It felt a little heavy to do a provision, but good to know that it is actually needed for the changes to apply.

**Comment by thom8** [comment]
@geerlingguy we're working on a similar issue atm, it's mainly to support a new docker build but might provide some useful functionality to target specific roles/tasks.

https://github.com/beetboxvm/beetbox/pull/298
https://github.com/beetboxvm/beetbox/pull/308

Still a WIP but will look out to push anything useful upstream.
