### ISSUE TITLE
Cannot access database with Adminer

### ISSUE THREAD

**Issue by janetrimmer** [geerlingguy/drupal-vm#861]
I've successfully setup drupalvm on Windows 10, using default settings. The page 'Drupal VM' looks ok.

However, when I enter http://adminer.drupalvm.dev/, I get 'This site can’t be reached'. Any ideas?
![drupalvm-screenshot](https://cloud.githubusercontent.com/assets/831988/17601299/4dfd21a6-5fff-11e6-8b87-671daa676f13.png)

**Comment by janetrimmer** [comment]
I've fixed this now! Didn't realise you have to add '192.168.88.88 adminer.drupalvm.dev' to hosts file. Perhaps you could put this in your documentation for frontend devs like me?

**Comment by thom8** [comment]
@janetrimmer it's there in the screenshot on the top right.

**Comment by geerlingguy** [comment]
@janetrimmer - What @thom8 said—but also, I'd recommend installing `vagrant plugin install vagrant-hostsupdater`—it manages all the hosts entries for you, without you having to go in and manually make changes to your hosts file.
