### ISSUE TITLE
Install hook not running on enabled module from config.yml settings

### ISSUE THREAD

**Issue by daddymacnrei** [geerlingguy/drupal-vm#862]
I'm not sure if this is an issue with the Drupal VM install but we set a feature module to be enabled on install of our VM and for some reason the module does get enabled, but the install hook added to it's .install file to enable additional modules doesn't seem to run properly.  Those additional modules are not enabled.  Even stranger is after a db check the schema_version table was showing the correct sequential number from additional update hooks in that .install file as well.   Any similar issues like this get submitted?

**Comment by thom8** [comment]
@daddymacnrei this is unrelated to Drupal VM however why not just add these modules as dependencies of the feature module?

D7: https://www.drupal.org/node/542202
D8: https://www.drupal.org/node/2000204

**Comment by daddymacnrei** [comment]
Sure.  Makes total sense.   We just had it set up like that for other reasons.  I guess my next question to help troubleshoot this issue on our end is to get a better understanding of where in the process of the VM install does that initial module get enabled that we've set in the "drupal_enable_modules:" setting of the config.yml file?  We're hoping to dig deeper to understand why the hooks did not run.

**Comment by thom8** [comment]
@daddymacnrei can you replicate the issue with just enabling the module with drush because this is what `drupal_enable_modules` uses.

https://github.com/geerlingguy/drupal-vm/blob/f12b93b0e76b855abb56c7ef4863463dadc34d78/provisioning/tasks/install-site.yml#L26

**Comment by geerlingguy** [comment]
@daddymacnrei - As @thom8 says, the module install is done with `drush pm-enable` after the site is installed with `drush site-install`.

When a module is first installed, it is installed directly to whatever the latest hook_update schema is, so if you have a bunch of hook_updates in the .install file, none of them will be run. If a module should be installed fresh on a new site _and_ update existing sites, you need to make sure that _all_ necessary setup is done both in `hook_update_n()` hooks _and_ in the module's main `hook_install()` hook. (At least in Drupal 7... in Drupal 8 there may be subtle differences depending on how you manage config/other things).

**Comment by geerlingguy** [comment]
I would suggest opening a question on the topic on [Drupal Answers](http://drupal.stackexchange.com/) if you would like to explore the topic further—it's a more generic architectural question, and it will pay dividends to really understand how modules/profiles/installation works in detail :)

**Comment by daddymacnrei** [comment]
Thanks @thom8 and @geerlingguy.  I appreciate the insight and we will look further into this issue on other Drupal specific forums.  I'm using sites run by Acquia DevDesktop as well and when use drush to enable that module on one of those fresh sites, it runs the expected hook_install() as expected to enable those additional site specific modules and the the hook_update's to uninstall and disable some other modules.   So why it only enables the module itself in the Drupal VM and not the others in the install hook is what we'll have to keep working at.  Obviously not  Drupal VM issue.
