### ISSUE TITLE
Old-style make files for D7

### ISSUE THREAD

**Issue by lsolesen** [geerlingguy/drupal-vm#863]
Is it possible to use old style make files - like provided here https://github.com/vih/vih-build - and have that automatically setup. 

Or should I rewrite those to the new .yml-format (which I guess works with the newest drush versions)?

**Comment by geerlingguy** [comment]
You can use either style—as long as the entire file is in the same style (you can't mix old ini-style and yml-style in one make file), and as long as you name the file accordingly (e.g. `something.make` vs. `something.make.yml`) and update the appropriate variable in your Drupal VM `config.yml`.
