### ISSUE TITLE
Failed task: Clone Drush from Github.

### ISSUE THREAD

**Issue by fabianderijk** [geerlingguy/drupal-vm#864]
I have just started looking into Drupal VM. When running `vagrant up` in my local drupal 8 site, everything runs normal until it gets to the task where it clone drush. After that it fails.

I see the following error (changed my site name and user name for privacy):
`TASK [geerlingguy.drush : Clone Drush from GitHub.] ****************************
fatal: [my-site]: FAILED! => {"changed": false, "failed": true, "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_C6584A/ansible_module_git.py\", line 209, in <module>\r\n    from ansible.utils.path import unfrackpath\r\nImportError: No module named utils.path\r\n", "msg": "MODULE FAILURE", "parsed": false}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

RUNNING HANDLER [geerlingguy.nginx : reload nginx] *****************************

RUNNING HANDLER [geerlingguy.mysql : restart mysql] ****************************

RUNNING HANDLER [geerlingguy.php : restart webserver] **************************

RUNNING HANDLER [geerlingguy.php : restart php-fpm] ****************************
       	to retry, use: --limit @/Users/my-user/Sites/my-site/vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
my-site                     : ok=89   changed=43   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

I've tried searching the issues and google, but to no avail.

I'm running Mac OSX 10.12, vagrant 1.8.5, ansible 2.2

**Comment by fabianderijk** [comment]
I've just downgraded to ansible 2.1 and everything runs perfectly....

**Comment by geerlingguy** [comment]
Thanks for the update! Hopefully this is fixed by the time 2.2 is released!
