### ISSUE TITLE
Confused - help a novice spin up

### ISSUE THREAD

**Issue by arlinsandbulte** [geerlingguy/drupal-vm#865]
I did the 3 simple Quickstart steps:
1. Install Vagrant and VirtualBox.
2. Download or clone this project to your workstation.
3. cd into this project directory and run vagrant up.

Seems to have worked.  
I can open http://192.168.88.88/ to the the DrupalVM dashboard.
**BUT, how do I access the real Drupal site?**  http://drupalvm.dev/ does not work.  And the hosts information at the top right of the dashboard page has all the SAME ip information anyway.  Shouldn't each 'site' have a different ip?
See attached screenshot.
![capture](https://cloud.githubusercontent.com/assets/20544649/17644808/ecfc8406-6156-11e6-8e2d-0ea9787a467e.PNG)

**Comment by arlinsandbulte** [comment]
Never mind.  I think I got it after digging a little further and installing hostupdater plugin and working on my hosts file permissions.

**Comment by geerlingguy** [comment]
@arlinsandbulte - Glad you could get it working!
