### ISSUE TITLE
Option to create settings.local.php rather than editing settings.php

### ISSUE THREAD

**Issue by dwkitchen** [geerlingguy/drupal-vm#867]
Loving working with Drupal VM, one issue I am having is that when provisioning the DB settings are added to the settings.php file; but I don't want to commit these changes for deployment to production.

I would like these settings to go in to a settings.local.php file which is in .gitignore and won't get committed.

If I get chance I will have a look at the provisioning code to do this; but if anyone else is looking at it it would be a great improvement.

**Comment by thom8** [comment]
@dwkitchen I looked into automating this but ended up with this solution --

```
// Add environment specific settings.
$env_settings = DRUPAL_ROOT . '/' . conf_path() . '/settings/environments/' . get_environment() . '.inc';
if (is_readable($env_settings)) {
  require_once $env_settings;
}
```

`get_environment()` returns the current environment label based on ENV settings or defaults to `local` so `settings/environments/local.inc` contains the VM database info.

We also have a `settings.local.php` but this is for personal overrides and is not tracked.

**Comment by geerlingguy** [comment]
Unfortunately, this is one of those "there are a dozen ways of doing it, and I'd rather not try to adopt/prefer one of them for Drupal VM" situations—each project/team will need to pick a method of setting environment-specific settings and gitignoring/version controlling the relevant parts.

For another example, check out the way Acquia's BLT lays out settings files (prior to site install): https://github.com/acquia/blt/tree/8.x/template/docroot/sites/default/settings
