### ISSUE TITLE
How to use Drupal Bootstrap Theme with Sass on Drupal VM?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#868]
On Windows 10 I have successfully installed Drupal VM (Vagrant, VirtualBox).

I want to start theming and installed:

- The Drupal Bootstrap Theme: www.drupal.org/project/bootstrap
- The Drupal Bootstrap Library Module: www.drupal.org/project/bootstrap_library
- Bootstrap from getbootstrap.com
- The CompassApp locally installed on Windows 10, compass.kkbox.com
- A subtheme of the Drupal Bootstrap Theme, generated and active

How can I start using and modifying this Drupal subtheme "Bootrap subtheme" using SASS, compiling the SASS files (maybe using the Compass App)?

What is the best way to start and make my own theme changes using SASS? Thank you.

**Comment by thom8** [comment]
@webprogrammierer the code base should be available to your host as defined in `vagrant_synced_folders` you can use any development tools directly on the host machine.

This is no different to using a local stack like ADD or WAMP.

**Comment by webprogrammierer** [comment]
Thank you. The vagrant_synced_folders  is /var/www/drupalvm like default. 

There is no SASS installed. How can I install SASS on Drupal VM? How can I install SASS using Vagrant?

Are there many ways to compile Sass files on Drupal VM? Which?

**Comment by thom8** [comment]
@webprogrammierer I'd recommend doing this on the host machine (Windows) rather than inside the VM.

The codebase will be available inside windows, how have you done it in the past?

**Comment by webprogrammierer** [comment]
Okay, I can understand. 
Why is it better to do this on the host machine (Windows)?

I am new to Drupal VM and I am new to Bootstrap Theme with SASS.

Maybe there is a good tutorial starting with Bootstrap Theme using SASS on a dev environment with a virtual machine (Ubuntu, Drupal VM).

**Comment by thom8** [comment]
Drupal VM should support any theme so there's nothing specifically required to use the Bootstrap Theme and/or SASS, maybe look for a Windows tutorial for setting up SASS.

**Comment by webprogrammierer** [comment]
Looking for tutorials for setting up SASS you can always find solutions to setup Sass on the linux based server (in our case inside the VM) rather than on Windows.

So I am still not sure what the better way is to do.

**Comment by thom8** [comment]
Maybe someone else can help, it's been almost 10 years since I last used Windows for dev.

**Comment by webprogrammierer** [comment]
Yes, it would be great, if somebody else can help to get different solutions.

**Comment by geerlingguy** [comment]
@webprogrammierer - I know @sarahjean has done something like this in the past (installing the tooling inside the VM), but I generally do all my dev work/tooling on the host, and just use the VM to run the site/display the artifacts built by SASS/other tools installed on my host, so I can't be too much help here.

I'll leave this ticket open a little longer, but this is a more general question that might be better to ask in a place like [Drupal Answers](http://drupal.stackexchange.com/).

**Comment by webprogrammierer** [comment]
In the meantime I successfully installed SASS and Compass within the Drupal VM:

I installed SASS like this (or similar): http://sass-lang.com/install
I installt Compass like this: http://thesassway.com/beginner/getting-started-with-sass-and-compass

Both, SASS and Compass work fine within the Drupal VM (using Vagrant SSH).
The only thing is, that you have to use the --poll option if you are watching files or directories:

`sass --watch --poll scss:styles`
or
`compass watch --poll`

Whithout the --poll option changes are not recognized.
Great - it works.

**Comment by heddn** [comment]
We do this right now with drupalvm with a gulp (or grunt, pick your poison) task that get's fired off in a post provision script. Just make sure that nodejs is installed, then add a `package.json` and run: `node_modules\.bin\gulp`

package.json:
```
{
  "name": "mtech_custom_theme",
  "version": "1.0.0",
  "description": "Theme for Mtech Custom",
  "main": "gulpfile.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "MTech LLC",
  "license": "ISC",
  "devDependencies": {
    "gulp": "^3.9.1",
    "gulp-sass": "^2.3.2"
  }
}
```

gulpfile.js
```
var gulp = require('gulp');
var sass = require('gulp-sass');

gulp.task('sass', function () {
	return gulp.src('./assets/sass/**/*.scss')
		.pipe(sass())
		.pipe(gulp.dest('./css'));
});

gulp.task('watch', function () {
	gulp.watch('./assets/sass/**/*.scss', ['sass']);
});

gulp.task('default', ['watch']);
```

**Comment by geerlingguy** [comment]
I think there's enough information in this thread to get someone moving in the right direction—thanks for all the help everyone!
