### ISSUE TITLE
Is it possible to increase memory and cpu's on existing vagrant machine?

### ISSUE THREAD

**Issue by heihachi88** [geerlingguy/drupal-vm#869]
Hello, is it possible to increase memory on existing machine? Don't i have to delete it and re-enable in order to get more memory?

**Comment by geerlingguy** [comment]
@heihachi88 - Yep, just increase the `vagrant_memory` value in `config.yml` or `local.config.yml`, then run `vagrant reload`. It will restart the VM with the new memory setting.

**Comment by daje4197** [comment]
Hey edited the 
vagrant_memory: 2048
vagrant_cpus: 1
but when i reload vagrant and and load 

vagrant@drupalvm:/var/www/drupalvm/drupal$ php -r "echo ini_get('memory_limit').PHP_EOL;"
192M

still got the 192M

**Comment by siliconmeadow** [comment]
> Hey edited the
> vagrant_memory: 2048
> vagrant_cpus: 1
> but when i reload vagrant and and load
> 
> vagrant@drupalvm:/var/www/drupalvm/drupal$ php -r "echo ini_get('memory_limit').PHP_EOL;"
> 192M
> 
> still got the 192M

You're talking about different memory here. Adding more memory by using `vagrant_memory` in the config.yml file increases the amount of RAM in the machine.

When doing `php -r "echo ini_get('memory_limit').PHP_EOL;" you're checking the maximum amount of memory PHP can use. To change that, find out which php.ini file you're using for php cli and change the `memory_limit` value in that. I'll let you search the best way to find out how to do that - it's not really a Drupal VM issue.

HTH.
