### ISSUE TITLE
Same issue as Issue #548. Drupalvm cannot connect with Windows 10

### ISSUE THREAD

**Issue by wonderflul** [geerlingguy/drupal-vm#873]
I would like to thank Jeff for the good work on helping Windows users with DrupalVM.  I did the following:
1.  ping drupalvm.dev with good response. However, IP address is different from 192.168.88.88 as given in docs that I came across.
2. Added 
192.168.88.88 to hosts file but did not work.
3. Messages from Chrome and firefox - server not found.
4. Added plugin vagrant hostupgrader- did not work with browser
5. Deleted plugin -did not work with browser.

Appreciate guidance.  Thanks

**Comment by geerlingguy** [comment]
What is the IP address that you're given? Maybe the configuration that you're using has an overridden/changed `vagrant_ip`? (Is there a `config.yml` file in your copy of Drupal VM?)

**Comment by geerlingguy** [comment]
For reference, #548
