### ISSUE TITLE
Create public domain for DVM

### ISSUE THREAD

**Issue by thom8** [geerlingguy/drupal-vm#875]
It seems that there's a lot of issues relating to Windows users and updating of hosts.
eg. https://github.com/geerlingguy/drupal-vm/issues/873

Perhaps you could create an A record for `local.drupalvm.com` pointing to `192.168.88.88`?

You could possibly also add entries for all the other subdomains.

Whilst most will likely use a custom domain at least this will be available for troubleshooting DNS issues.

**Comment by geerlingguy** [comment]
Hmm... that's not a bad idea.

**Comment by geerlingguy** [comment]
Done!

```
$ dig local.drupalvm.com

; <<>> DiG 9.8.3-P1 <<>> local.drupalvm.com
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 45349
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0

;; QUESTION SECTION:
;local.drupalvm.com.		IN	A

;; ANSWER SECTION:
local.drupalvm.com.	299	IN	A	192.168.88.88

;; Query time: 119 msec
;; SERVER: 10.0.1.1#53(10.0.1.1)
;; WHEN: Fri Aug 26 22:01:35 2016
;; MSG SIZE  rcvd: 52
```

**Comment by geerlingguy** [comment]
@thom8 - We should probably add a note in the docs somewhere too, on the Windows page, about debugging connection issues... sorry I've been AWOL a bit—major project wrapping up, new baby on the way, was on vacation, among other things :D
