### ISSUE TITLE
PHP-FPM doesn't respond to .html paths, only .php

### ISSUE THREAD

**Issue by bhasselbeck** [geerlingguy/drupal-vm#876]
When trying to reach an .html asset located in the Drupal filesystem for Drupal 8.  I'm receiving a File Not Found error.  Error is similar to https://forums.cpanel.net/threads/php-fpm-directory-index-index-html-file-not-found-problem.529701/

We should allow for config settings on config.yml that allows for phpfpm to listen to a configurable array of filetypes.

**Comment by geerlingguy** [comment]
Yeah, similar issue with Apache here: https://github.com/geerlingguy/drupal-vm/issues/617

**Comment by geerlingguy** [comment]
(Note that for my other infra, my Nginx server config does route .html files appropriately, so maybe there's a clue in there for a simple fix.)

**Comment by geerlingguy** [comment]
Closing in favor of #617, merging to there.

**Comment by oxyc** [comment]
Fixed in #1086.
