### ISSUE TITLE
Cannot wget or use phantomjs on DrupalVM to local site

### ISSUE THREAD

**Issue by kevinquillen** [geerlingguy/drupal-vm#877]
I am trying to use PhantomJS via http://jonnnnyw.github.io/php-phantomjs/ on a Drupal 7 / PHP 5.6 / Ubuntu 1404 box.

If I specify a remote URL to the PHP PhantomJS API, I can get a screen grab or PDF. However, if I specify my site in the VM instance, I get a 408 timeout.

I also ssh'd in and tried doing "wget http://local.mysite", which produces nothing, even though pinging it returns 127.0.1.1.

I noticed that if I pushed this code to a dev environment on Acquia, the same issue persists - trying to capture a page on the same machine results in a 408 timeout, even when set to 15 seconds. Along with that, it causes my VBox resources to spike hard and produce dozens of php5-fpm and PhantomJS threads that I have to killall or reboot the vagrant machine.

What am I missing on the server/network config that would permit this to work?

**Comment by thom8** [comment]
Try `localhost` -- `wget http://localhost`

otherwise you might need a custom task to set the hostname of the vm

```
- name: Set hostname.
  hostname:
    name: "local.mysite"
```

http://docs.drupalvm.com/en/latest/extras/scripts/#ansible-task-files

Definitely keen to checkout the phantom composer package, we're currently using a role to install phantomjs and setup a daemonized ghost driver -- https://github.com/beetboxvm/ansible-role-beetbox-phantomjs

**Comment by thom8** [comment]
Another option would be to use -- https://github.com/devopsgroup-io/vagrant-hostmanager

which also updates the hosts file of the VM.

**Comment by kevinquillen** [comment]
I am sure it is likely something I am doing, but others seem to have ran into the same thing (albeit not DrupalVM):

http://stackoverflow.com/questions/35739174/phantomjs-408-error-socket-operation-timed-out

Although, I switched to this, and it worked without fuss:

https://www.drupal.org/project/phantomjs_capture

I believe the underlying phantomjs package is also what the new testing framework changes use in Drupal 8.2.x+, I also got a timeout error when trying to make one a week or two ago if I recall.

My hosts file in the VM lists 127.0.1.1 for my local site - is that not the same as the value fetched from `vagrant_hostname`?

**Comment by kevinquillen** [comment]
This seems to be an issue with PhantomJS itself.
