### ISSUE TITLE
How to connect multisites with their corresponding databases?

### ISSUE THREAD

**Issue by hidace** [geerlingguy/drupal-vm#878]
Hi, 

I was able to successfully add in multiple sites and create their databases, however it looks as though they are all pulling from the main database, rather than their corresponding ones that were created. How do you link up  each multi-site to its corresponding database. Is there a file where this is setup / configured to point each multisite to a database? Thanks!

**Comment by thom8** [comment]
@hidace you'll need to configure each sites `settings.php` with the relevant database config.

**Comment by hidace** [comment]
@thom8 I've created directories for each multisite (for example: `.../sites/<site_name>/`) and updated each site's corresponding settings.php file, but when I run vagrant up to get the box up and running, they are still pulling from the same default database. Am I missing something else here? Thanks.

**Comment by thom8** [comment]
You need to make sure the right settings file is being invoked - either via the domain name or with `sites.php`-- https://api.drupal.org/api/drupal/sites%21example.sites.php/8.2.x

Try putting a print statement and exit in both to help debug which one is being invoked on which domain.

**Comment by geerlingguy** [comment]
@hidace - It might be better to ask about this particular issue on a forum like Drupal Answers (e.g. http://drupal.stackexchange.com/questions/80145/sites-php-setup).
