### ISSUE TITLE
Keep Databases on VM destroy

### ISSUE THREAD

**Issue by Leeroy204** [geerlingguy/drupal-vm#883]
It would be a great addition to add the ability to keep the databases when vagrant destroy is run.

I would suggest using: https://github.com/kusnier/vagrant-persistent-storage

**Comment by geerlingguy** [comment]
@Leeroy204 - I don't want to add support for this in Drupal VM itself (IMO, local dev environments should be completely epemeral and able to be rebuilt easily—at least most of the time—including databases, files, etc.), but if you use a `Vagrantfile.local` or a delegating Vagrantfile, you can provide the configuration yourself for your own VMs. See the documentation here: http://docs.drupalvm.com/en/2.5.1/other/local-vagrantfile/
