### ISSUE TITLE
Quickstart Guide Question:  correct format for local_path

### ISSUE THREAD

**Issue by darwinIcesurfer** [geerlingguy/drupal-vm#885]
What is the correct format for the local_path variable under vagrant_synced_folders on a Windows 8 machine?  I entered **F:\Users\myuser\drupalVM** but when I run **vagrant  up** I get the error:
Message: 
    `Psych::SyntaxError: (F:/Users/myuser/drupal-vm-master/config.yml): **mapping values are not allowed in this context at line 6 column 13**`

**Comment by tripox** [comment]
Did you use quotation marks?
Like this: "F:\Users\myuser\drupalVM"

**Comment by geerlingguy** [comment]
@tripox is correct, you will need quotation marks for windows paths which include a colon (otherwise YAML parsers will think you're trying to define a new value for 'F').
