### ISSUE TITLE
Help installing PHP PECL "jsmin" extension?

### ISSUE THREAD

**Issue by attheshow** [geerlingguy/drupal-vm#888]
I'm struggling to figure out how to install a PECL extension called jsmin. At first I thought it went into post_provision_scripts: [], then I tried php_pecl_extensions: [] but neither of them is working correctly for me. Does anyone have any tips on the best way to do this? Thanks!

**Comment by attheshow** [comment]
According to the super popular AdvAgg module, installing JSMin on the server is the fastest way to compress Javascript files currently. This is the main reason I'm pursuing this.

![screen shot 2016-09-07 at 7 43 15 am](https://cloud.githubusercontent.com/assets/191008/18310832/c946cafe-74ce-11e6-8745-70d4e3e38a1f.png)

**Comment by geerlingguy** [comment]
@attheshow - Have you tried:

```
php_pecl_extensions:
  - jsmin
```

Then run `vagrant provsion`? (see docs: https://github.com/geerlingguy/ansible-role-php-pecl#role-variables)

**Comment by attheshow** [comment]
After trying this on Drupal VM 3.2.2 it appears at first to install correctly.

`TASK [geerlingguy.php-pecl : Install PECL libaries.] ***************************
ok: [drupalvm] => (item=jsmin)`

But when viewing the AdvAgg configuration screen above, there is no change. I tried checking the list of php modules using `php5-fpm -m` but jsmin is not in the list.

**Comment by geerlingguy** [comment]
@attheshow - can you try running `vagrant reload` and see if that helps?

**Comment by attheshow** [comment]
Sure. Still no change. :(

**Comment by geerlingguy** [comment]
@attheshow - Ah, you might still need to add some config to an .ini file for the module to get loaded. If you `vagrant ssh` in, then run `php -m` I'm guessing it's not in that list either. You would need to add a .ini file like `/etc/php7.0/fpm/conf.d/20-jsmin.ini` and enable the module there, with:

```
extension="jsmin.so"
```

Same thing in a file `/etc/php7.0/cli/conf.d/20-jsmin.ini` for CLI. Then it should show up with `php -m` in the VM.

Also make sure you restart FPM after this (`sudo service php7.0-fpm restart`).

Assuming you're on PHP 7.

**Comment by geerlingguy** [comment]
(Funny aside, I was just helping @danmontgomery install the PECL `ssh2` extension, and that's what prompted me to remember adding the ini config).

**Comment by attheshow** [comment]
Yes!!! Thanks so much! This is working for me on PHP 5.6. Just for documentation purposes, I ended up adding this into config.yml:

`post_provision_scripts:
  - "../scripts/configure-jsmin.sh"`

And the I added a "configure-jsmin.sh" bash script with the following commands:

`#!/bin/bash
#
# Helps with adding JSMin PECL PHP Extension for PHP 5.
# See: https://github.com/geerlingguy/drupal-vm/issues/888

sudo touch /etc/php5/fpm/conf.d/20-jsmin.ini
sudo bash -c 'echo "extension=\"jsmin.so\"" >> /etc/php5/fpm/conf.d/20-jsmin.ini'`

After running `vagrant provision`, it's showing up!

![screen shot 2016-09-14 at 8 31 02 am](https://cloud.githubusercontent.com/assets/191008/18512164/c4fb9dda-7a55-11e6-8cee-50c0ff7cb8ee.png)
![screen shot 2016-09-14 at 8 31 39 am](https://cloud.githubusercontent.com/assets/191008/18512163/c4fa3c38-7a55-11e6-94aa-36bf3f70bdee.png)

**Comment by geerlingguy** [comment]
Glad I could help :)
