### ISSUE TITLE
Error building virtual machine

### ISSUE THREAD

**Issue by mtoconne** [geerlingguy/drupal-vm#892]
Hi,
I am attempting to build a Drupal 7 VM but am running into the same error over and over.  I have configured config.yml for Drupal Make and drupal.make.yml for Drupal 7.4.4.  But when I attempt to run vagrant up, it always fails towards the end of the build.  I've tried running vagrant provision, but keep running into the same error.

Thanks for any help!

Here are the last few lines of the build:

`TASK [Do not accept locale environment variables passed over SSH.] *************
ok: [drupalvm]

TASK [Check if local known_hosts file is present.] *****************************
ok: [drupalvm]

TASK [Copy known_hosts file from host into Drupal VM.] *************************
ok: [drupalvm]

TASK [Set SSH home directory.] *************************************************
skipping: [drupalvm]

TASK [Install extra apt packages (if any are configured).] *********************
ok: [drupalvm] => (item=[u'sqlite'])

TASK [Install extra yum packages (if any are configured).] *********************
skipping: [drupalvm] => (item=[]) 

TASK [Ensure necessary groups exist.] ******************************************
ok: [drupalvm] => (item=admin)
ok: [drupalvm] => (item=dialout)

TASK [Ensure vagrant user is in admin group.] **********************************
ok: [drupalvm]

TASK [Ensure www-data user is in dialout group (Debian).] **********************
ok: [drupalvm]

TASK [Set nicer permissions on Apache log directory.] **************************
ok: [drupalvm]

TASK [Copy Nginx vhosts into place.] *******************************************
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/var/www/drupalvm/drupal/web', u'server_name': u'drupalvm.dev www.drupalvm.dev'}) 
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/opt/adminer', u'server_name': u'adminer.drupalvm.dev'}) 
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/usr/share/php/xhprof_html', u'server_name': u'xhprof.drupalvm.dev'}) 
skipping: [drupalvm] => (item={u'is_php': True, u'root': u'/usr/share/php/pimpmylog', u'server_name': u'pimpmylog.drupalvm.dev'}) 
skipping: [drupalvm] => (item={u'root': u'/var/www/dashboard', u'server_name': u'192.168.88.88 dashboard.drupalvm.dev'}) 

TASK [Detect if AppArmor is working.] ******************************************
ok: [drupalvm]
 [WARNING]: Consider using service module rather than running service

TASK [Ensure MySQL AppArmor profile is disabled (for slow query log).] *********
ok: [drupalvm]

TASK [Restart the AppArmor if necessary.] **************************************
skipping: [drupalvm]

TASK [Copy drush makefile into place.] *****************************************
ok: [drupalvm]

TASK [Ensure drupal_core_path directory exists.] *******************************
ok: [drupalvm]

TASK [Generate Drupal site with drush makefile.] *******************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "make", "-y", "/tmp/drupal.make.yml", "--no-gitinfofile"], "delta": "0:00:00.159306", "end": "2016-09-07 13:06:34.569779", "failed": true, "rc": 1, "start": "2016-09-07 13:06:34.410473", "stderr": " [ok] Beginning to build /tmp/drupal.make.yml.\n [error]  Could not locate drupal version 7.4.4. \n [error]  Drush Make failed to download all projects. See the log above for the specific errors. ", "stdout": "Make new site in the current directory? (y/n): y", "stdout_lines": ["Make new site in the current directory? (y/n): y"], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Users/mtoconne/Documents/ncsu-web/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=131  changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.`

**Comment by mdrmike** [comment]
check your Drupal version... Drupal 7.x only has two point versioning,,, no such thing as 7.4.4.  I think you mean version 7.44.  I'd also suggest using the latest stable, which is 7.50

**Comment by geerlingguy** [comment]
Yep, looks like it's just the version:

```
Error: could not locate drupal version 7.4.4.
```

You should set it to `7.44` or `7.50` (or whatever's latest).
