### ISSUE TITLE
Setup fails using default composer + NFS: "Could not delete web/core/.nfs"

### ISSUE THREAD

**Issue by mdrmike** [geerlingguy/drupal-vm#893]
When running `vagrant up` -- build fails.  I'm not sure how to debug?  Is there a verbose flag/mode I could login to watch build?

I've tried installing 5-7 times with varied configurations -- including totally vanilla *without any* custom config.  

**Failure message**
This is the failure message, or some similar variation.
```
  Failed to download drupal/core from dist: Could not delete web/core/.nfs0000000000743e0000000001:
```
**Note:** Seems related to #741 and #733 (but both are closed).  I also ran into #837 on one variation of the build, but couldn't reproduce. *(might have been a flag related to drush/composer)*

**Build-out does work on Drupal 8 & Drupal 7 if using `drupal.drush.yml` instead of composer:**

## Host Machine Setup
- Ubuntu-Gnome 16.04.1 LTS 64-bit  (Kernel: 4.4.0-36-**lowlatency**)
- Vagrant 1.8.5 (was originally 1.8.1)
- Ansible 2.1.1.0
- VirtualBox 5.0.24_Ubuntu r108355 {also upgraded/downgraded VirtualBox 5.1.4 r110228 (Qt5.5.1)}
- drupal-vm: 7cd44a700f95797e57e334ab8cba97f09e2b448d   (originally tried 9930333f2314fc642b827dc00d7a857e08c64e0e)
- I do not have Composer, PHP, Drush, or any other web related packages installed on my desktop host.

**Vagrant Plugins**
- vagrant-auto_network (1.0.2)
- vagrant-bindfs (0.4.9)
- vagrant-hostsupdater (1.0.2)
- vagrant-share (1.1.5, system)
- vagrant-vbguest (0.13.0)

## Suggestions?

**Comment by geerlingguy** [comment]
@mdrmike - Hmm... you have all the right versions, AFAICT. I can't think of anything else to try, besides completely deleting the Drupal VM checkout and cloning again.

**Comment by mdrmike** [comment]
Thanks for feedback.  Ya, re-cloning is actually where I started ... in fact, it had been working under 14.04 and I've had a problem since migrating to 16.04 (I did not run an upgrade)... and I just put off looking into.  I'll continue to mess with it to see if I can isolate what's going on.

**Comment by jonnyeom** [comment]
I actually got this error as well.
I was updating Drupal Core (8.1.8->8.1.10)
```
Update failed (Could not delete web/core/.nfs000000000000002000000001:
```
I have never seen this error before. Very Strange.
Is there any additional info I could provide to help solve this?

**Comment by jonnyeom** [comment]
Actually, I only ran into this issue when I ran `compose update drupal/core` while I was in the `vagrant ssh` state. Once I ran the update command outside of the ssh state, drupal updated successfully!

**Comment by daceves** [comment]
I've ran into this exact issue on other machines (AWS) outside of DrupalVM, when having the code base on a mounted drive. This seems potentially like not a DrupalVM issue.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/issues/741

Specifically: https://github.com/geerlingguy/drupal-vm/issues/741#issuecomment-226436054

> I killed the unzipping of drupal/core from cache, and now (after 15+ minutes) it's going through the next steps.

It looks like it's some sort of timeout issue with large number of file operations through Composer. I typically recommend (if at all possible) running any composer operations outside the VM, because performance is usually better and these types of errors don't occur as often.

**Comment by apina-globant** [comment]
If You use drupalvm, On Vagrantfile modifiy this line:

**config.vm.synced_folder synced_folder['local_path'], synced_folder['destination'], options**

by:

**config.vm.synced_folder synced_folder['local_path'], synced_folder['destination'], :nfs => 'nfs', :mount_options => ['rw', 'vers=3', 'tcp', 'fsc' ,'actimeo=2'], :linux__nfs_options => ['rw','no_subtree_check','all_squash','async']**

This allow, to make the NFS share asynchronous.

**Comment by kentr** [comment]
This appears to have solved the problem in my case.

Add a `~/.composer/config.json` file with this content:

```
{
    "config": {
        "process-timeout":      600,
        "preferred-install":    "dist",
        "github-protocols":     ["https"]
    }
}
```

Source: https://stackoverflow.com/a/26216954

**Comment by benjamin-dk** [comment]
I had to up the `process-timeout` to 6000, then it worked (I also restarted the VM and upped the `php_memory_limit` to 2G).

**Comment by webprogrammierer** [comment]
I have the same problem. Setting process-timeout to 6000 does not solve the problem: 

```
- Removing composer/installers (v1.10.0)                                   
    Update of composer/installers failed                                     
                                                                             
                                                                             
  [RuntimeException]                                                         
  Could not delete /var/www/xxx/vendor/composer/installers/.github
```
