### ISSUE TITLE
PHPUnit

### ISSUE THREAD

**Issue by joshbrown81** [geerlingguy/drupal-vm#898]
Hi!

I've installed PHPUnit onto my DrupalVM and I can see and use it in ~/vendor/phpunit/phpunit when the composer segment in config.yml looks like this:

```
composer_global_packages:
  - { name: phpunit/phpunit, release: '5.*' }
```

I've made it globally usable by symlinking the executable into /usr/bin...
```
cd /usr/bin
sudo ln -s /home/vagrant/vendor/phpunit/phpunit/phpunit phpunit
```
 But, is there anyway this could be done when the box is first booted?

Many thanks!

**Comment by fubarhouse** [comment]
@joshbrown81 @geerlingguy has added the ability to run post-execution scripts.

I would be creating a new ansible role instead of a script for compatibility reasons, but the functionality is baked in should you need it.

http://docs.drupalvm.com/en/latest/extras/scripts/

Instead, I would however write it as follows to prevent an error:

````
sudo rm -f /usr/bin/phpunit
sudo ln -s ~/vendor/phpunit/phpunit/phpunit /usr/bin/phpunit
````

**Comment by joshbrown81** [comment]
@fubarhouse Ahh good point! Thanks!

**Comment by thom8** [comment]
@joshbrown81 by default the global composer bin directory is added to the PATH, which should contain a symlink to `phpunit`

https://github.com/geerlingguy/ansible-role-composer/blob/master/defaults/main.yml#L17
https://github.com/geerlingguy/ansible-role-composer/blob/master/tasks/global-require.yml#L12

**Comment by geerlingguy** [comment]
This seems to have an adequate answer in the form of creating the symlinks; and since the composer bin directory is added to the $PATH, it _should_ be accessible inside the VM by default.

If something's broken with the composer role's functionality, please open a ticket upstream.
