### ISSUE TITLE
YAML syntax error after changing settings in config.yml on Windows.

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#900]
I just renamed identity to
`vagrant_hostname: drupalvm8.dev
vagrant_machine_name: drupalvm8
`
and ran vagrant up.
I have this error:

`Installing additional modules ...
Removing existing VirtualBox DKMS kernel modules ...done.
Removing existing VirtualBox non-DKMS kernel modules ...done.
Building the VirtualBox Guest Additions kernel modules ...done.
Doing non-kernel setup of the Guest Additions ...done.
You should restart your guest to make sure the new modules are actually used

mesg: ttyname failed: Inappropriate ioctl for device
==> drupalvm8: Checking for guest additions in VM...
==> drupalvm8: Setting hostname...
==> drupalvm8: Configuring and enabling network interfaces...
==> drupalvm8: Mounting shared folders...
    drupalvm8: /vagrant => E:/VM/drupal-vm8
    drupalvm8: /var/www/drupalvm => E:/VM/drupal-vm8
==> drupalvm8: Updating /etc/hosts file on active guest machines...
==> drupalvm8: Updating /etc/hosts file on host machine (password may be required)...
==> drupalvm8: Running provisioner: ansible_local...
    drupalvm8: Installing Ansible...
    drupalvm8: Running ansible-playbook...
ERROR! Syntax Error while loading YAML.

The error appears to have been in '<string>': line 1, column 12, but may
be elsewhere in the file depending on the exact syntax problem.
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
`

**Comment by geerlingguy** [comment]
@ArtuGit - If you're on windows, what editor did you use to save the YML file? You need to make sure you use an editor that can preserve line endings, like Notepad++, Sublime Text, or Atom, then also make sure the line endings are set to Unix, not Windows.

**Comment by ArtuGit** [comment]
I have checked it.
http://screenpresso.com/=VCFje

**Comment by welly** [comment]
I'm actually having the same problem on OSX.

I cloned the repo, then ran cp default.config.yml config.yml and then vagrant up. Oddly enough, when I did this same thing last night on my home Macbook, it seemed to work fine so I'm not sure what has happened between then and now.

```
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater] Writing the following entries to (/etc/hosts)
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  drupalvm.dev  # VAGRANT: 940a2291760556f379671ffc2e351e02 (drupalvm) / 1808c2d7-5320-47cb-8172-a4f13dddf633
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  www.drupalvm.dev  # VAGRANT: 940a2291760556f379671ffc2e351e02 (drupalvm) / 1808c2d7-5320-47cb-8172-a4f13dddf633
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  adminer.drupalvm.dev  # VAGRANT: 940a2291760556f379671ffc2e351e02 (drupalvm) / 1808c2d7-5320-47cb-8172-a4f13dddf633
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  xhprof.drupalvm.dev  # VAGRANT: 940a2291760556f379671ffc2e351e02 (drupalvm) / 1808c2d7-5320-47cb-8172-a4f13dddf633
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  pimpmylog.drupalvm.dev  # VAGRANT: 940a2291760556f379671ffc2e351e02 (drupalvm) / 1808c2d7-5320-47cb-8172-a4f13dddf633
==> drupalvm: [vagrant-hostsupdater]   192.168.88.88  dashboard.drupalvm.dev  # VAGRANT: 940a2291760556f379671ffc2e351e02 (drupalvm) / 1808c2d7-5320-47cb-8172-a4f13dddf633
==> drupalvm: [vagrant-hostsupdater] This operation requires administrative access. You may skip it by manually adding equivalent entries to the hosts file.
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
==> drupalvm: Mounting NFS shared folders...
==> drupalvm: Running provisioner: ansible_local...
    drupalvm: Installing Ansible...
    drupalvm: Running ansible-playbook...
ERROR! Syntax Error while loading YAML.

The error appears to have been in '<string>': line 1, column 12, but may
be elsewhere in the file depending on the exact syntax problem.

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by welly** [comment]
I just tried reproducing this by removing the geerlingguy/ubuntu1604 box, deleting my cloned repository and basically starting again. I did the same thing as above, clone, copy default.config.yml to config.yml and then vagrant up. Same problem. I'm puzzled because as I say on another machine I ran this on last night, it worked fine. Peculiar!

**Comment by welly** [comment]
Just checked my vagrant version and it's at 1.8.1 which may well be the cause. I'm upgrading it now to the latest version and hopefully that might fix it. Perhaps @ArtuGit might want to check this too.

**Comment by thom8** [comment]
```
The error appears to have been in '<string>': line 1, column 12, but may
be elsewhere in the file depending on the exact syntax problem.
```

@welly this error is most likely a YAML syntax issue, try test it here -- http://www.yamllint.com/

**Comment by welly** [comment]
@thom8 thanks for your suggestion, but it's all cleared up now after updating Vagrant.

**Comment by ArtuGit** [comment]
I updated Vagrant, this problem disappeared.

**Comment by ArtuGit** [comment]
Thank you all.
