### ISSUE TITLE
PHP packages failed to installed during vm install using vagrant up

### ISSUE THREAD

**Issue by akmamidi** [geerlingguy/drupal-vm#902]
i am getting below error while installing vm using vagrantup, i did see only this error. all other components are installed successfully.

TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [syscointranet] (item=[u'libapache2-mod-php5', u'php5', u'php5-mcrypt', u'php5-cli', u'php5-common', u'php5-curl', u'php5-dev', u'php5-fpm', u'php5-gd', u'php-pear', u'php-apc', u'libpcre3-dev']) => {"cache_update_time": 0, "cache_updated": false, "failed": true, "item": ["libapache2-mod-php5", "php5", "php5-mcrypt", "php5-cli", "php5-common", "php5-curl", "php5-dev", "php5-fpm", "php5-gd", "php-pear", "php-apc", "libpcre3-dev"], "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'libapache2-mod-php5' 'php5' 'php5-mcrypt' 'php5-cli' 'php5-common' 'php5-curl' 'php5-dev' 'php5-fpm' 'php5-gd' 'php-pear' 'php-apc' 'libpcre3-dev'' failed: E: Unable to correct problems, you have held broken packages.\n", "stderr": "E: Unable to correct problems, you have held broken packages.\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nSome packages could not be installed. This may mean that you have\nrequested an impossible situation or if you are using the unstable\ndistribution that some required packages have not yet been created\nor been moved out of Incoming.\nThe following information may help to resolve the situation:\n\nThe following packages have unmet dependencies:\n libapache2-mod-php5 : Depends: apache2-api-20120211 but it is not installable\n                       Depends: apache2 (>= 2.4)\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "Some packages could not be installed. This may mean that you have", "requested an impossible situation or if you are using the unstable", "distribution that some required packages have not yet been created", "or been moved out of Incoming.", "The following information may help to resolve the situation:", "", "The following packages have unmet dependencies:", " libapache2-mod-php5 : Depends: apache2-api-20120211 but it is not installable", "                       Depends: apache2 (>= 2.4)"]}

**Comment by geerlingguy** [comment]
It looks like you may have switched up some variables in config.yml on an existing Drupal VM instance. You should do `vagrant destroy` to delete the VM entirely, then run `vagrant up` again to build the VM from scratch with all the correct versions.

**Comment by akmamidi** [comment]
Thanks Jeff. we have not changed the config file past 8 months. I have tried this. somehow i got the same error again and again. 
we are trying to pull vagrant_box: geerlingguy/ubuntu1204, is this still valid? or do we have to use 1404?

Thanks for your input.

**Comment by akmamidi** [comment]
i got same error. something got changed. something got changed.

apache2-mod-php5 : Depends: apache2-api-20120211 but it is not installable\n                       Depends: apache2 (>= 2.4)\n"

**Comment by geerlingguy** [comment]
@akmamidi - Hmm, if the config is 8 months old, a lot has changed since then.

What version of Drupal VM are you using? Also, what's your `php_version`? (And also if you run `php -v` inside the VM, what version is listed?)

PHP < 5.5 is definitely not supported anymore, and PHP 5.5 is less-supported than 5.6 or 7...

**Comment by geerlingguy** [comment]
See also: [libapache2-mod-php5 uninstalled after update impossible to put back](http://serverfault.com/a/527815/15673)

**Comment by akmamidi** [comment]
Please find attached config.yml file. Configuration has php 5.6 and VM 12.04. i am not sure where it is going wrong. it is always failing to install php 5.6


[config.yml.txt](https://github.com/geerlingguy/drupal-vm/files/491994/config.yml.txt)

**Comment by akmamidi** [comment]
after failed with php error, i have checked the apache version(apache2 -v), it is showing it as 2.2 instead of 2.4, i believe somewhere it is trying to install older version? could you please let me know where to change this version on the config files.

**Comment by aweingarten** [comment]
@geerlingguy, I started seeing a strange issue provisioning php 5.6 as well:

````
TASK [Add repository for PHP 5.6.] *********************************************
fatal: [atfweb]: FAILED! => {"changed": false, "failed": true, "msg": "failed to fetch PPA information, error was: HTTP Error 503: Service Unavailable"}
	to retry, use: --limit @/Users/me/box/provisioning/playbook.retry

````

**Comment by chrisrikli** [comment]
@geerlingguy @aweingarten I'm seeing the same thing.  Hope this is just a temporary issue because it wasn't doing this earlier this AM.

**Comment by geerlingguy** [comment]
@aweingarten / @chrisrikli - Yeah, it seems Ondrej's PPA might be having momentary issues, just give it a little time — see https://twitter.com/geerlingguy/status/780412238632849408

**Comment by akmamidi** [comment]
do you know why it is provisioning apache 2.2 instead of 2.4 . this was causing an error while installing php 5.6 libapache2-mod-php5 .

i am using MAC.

**Comment by chrisrikli** [comment]
Looks like Ondrej's PPA is back up and working.

Jeff as always thank you for being so fast to respond.

**Comment by akmamidi** [comment]
i have resolved PHP provision error. Now i am getting below error. Any idea?

TASK [geerlingguy.php : Ensure php-fpm is started and enabled at boot (if configured).] ***
fatal: [syscointranet]: FAILED! => {"changed": false, "failed": true, "msg": "no service or tool found for: php7.0-fpm"}

**Comment by geerlingguy** [comment]
@akmamidi - Did you make all the overrides in your config file that are listed here? http://docs.drupalvm.com/en/latest/other/php-56/

Especially:

```
php_fpm_daemon: php5-fpm
```

**Comment by akmamidi** [comment]
Thank You Jeff. I have updated this in config.yml and it is installing now. i will update if i find any more issues.
