### ISSUE TITLE
Drush does not work invoking the local Drush (D8 Composer Installation)

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#904]
Hello.

I have installed new D8 on a remote server using this way https://github.com/drupal-composer/drupal-project .
I have pulled files from GitHub and I have run 'composer install' for getting the all vendor files include the local Drush (/vendor/drush/drush/)
When I run 'drush status' or  'drush core-status' on the root (or '/web') website directory I have:
```
vagrant@drupalvm8:/var/www/drupalvm/test8$ drush core-status
PHP Warning:  pcntl_exec(): Error has occurred: (errno 8) Exec format error in /usr/local/share/drush/includes/startup.inc on line 412

Warning: pcntl_exec(): Error has occurred: (errno 8) Exec format error in /usr/local/share/drush/includes/startup.inc on line 412
Error has occurred executing the Drush script found at /var/www/drupalvm/test8/vendor/bin/drush.launcher
(errno 8) Exec format error
```

**Comment by geerlingguy** [comment]
I've never seen an error like that before, but it sounds like something's funky with the drush install or the composer setup. See this answer for potential help: http://drupal.stackexchange.com/a/201094/26

Does drush work on your host machine, outside the VM?

And if you're outside the /var/www/drupalvm/test8 folder, does `drush core-status` work (using the globally-installed drush)?

I don't think this is a Drupal VM issue, it sounds more like the installation is missing something or drush file permissions are wrong, something along those lines.

**Comment by ArtuGit** [comment]
I do not have this problem on my VPS where the Drush8 is installed.
DVM has Drush9.0dev.

I wanted to reduce the Drush version, but I could not uninstall it, neither 'sudo apt-get --purge remove drush', nor 'composer global remove drush/drush'.

How was Drush installed?
How to change Drush version?

**Comment by ArtuGit** [comment]
'drush core-status' works outside the website folder.

**Comment by geerlingguy** [comment]
@ArtuGit - If drush works outside the website folder, then the global Drupal VM drush install seems to work okay. It seems that the drush version installed as part of the site codebase may have an issue (either permissions-related or install-related), but I don't think I'll be able to offer any more advice/help without working from the same codebase.

**Comment by ArtuGit** [comment]
It was some my error. The problem disappeared after repeating: 
'
git pull
composer install
'
from scratch.

**Comment by geerlingguy** [comment]
@ArtuGit - Ah, sounds like maybe composer had a problem the first time you ran it... it happens sometimes!
