### ISSUE TITLE
Firewall role causes problems on Windows 7

### ISSUE THREAD

**Issue by benjifisher** [geerlingguy/drupal-vm#905]
Sorry for posting this before investigating, but I want to capture some output now before it goes away.

I am trying to get Drupal VM running on a Windows machine.  Normally I use a Mac, but I volunteered to help get people set up at NEDCamp next weekend, and we need to be prepared for Windows.

I am using
- Windows 7
- VirtualBox 5.1.6 r110634
- Vagrant 1.8.5
- Bash installed by Git for Windows 2.10.0

I copied `default.config.yml` to `config.yml` and made just one change (which should not affect the `firewall` role):  `build_composer: true`.  (This also causes problems when we get to the `composer install` step:  it chokes on the `devel` module.  I may switch to downloading the Drupal codebase separately.)

When Ansible gets to the `firewall` role, I get the error message (typing into a Mac while looking at the Windows screen, so there may be typos)

```
TASK [geerligguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Error when
trying to enable firewall: rc=1 firewall is not a native service, redirecting to
systemd-sysv-install\nExecuting /lib/systemd/systemd-sysv-install enable
firewall\nupate-rc.d: error: firewall Default-Start contains no runlevels, aborting.\n"}
```

After `vagrant provision` or `vagrant halt && vagrant up --provision` I get an error at the same point, but with a different error message:

```
TASK [geerligguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Job for
firewall.service failed because the control process exited with error code.
See \"systemctl status firewall.service\" and \"journalctl -xe\" for details.\n"}
```

**Comment by geerlingguy** [comment]
@benjifisher - Please see the fix outlined in https://github.com/geerlingguy/drupal-vm/issues/829 — I'm guessing its the same line ending issue.

**Comment by geerlingguy** [comment]
I'm going to close in favor of #829 for now; let me know if that wasn't the issue and I'll re-open.

**Comment by benjifisher** [comment]
Yes, that was the problem.  Sorry for not confirming earlier.

As I said, I do not use the Windows machine often.  The problem is that I had ~~`autocrlf = true`~~ in my `.gitconfig` from when I originally installed Git Bash.  That was a long time ago, and I know better now.

For the sake of anyone else with the same problem, I fixed by adding

```gitconfig
[core]
autocrlf = false
```

to `~/.gitconfig` and then, from the shell installed by Git Bash,

```bash
$ rm *
$ git checkout -- .
```

**Comment by geerlingguy** [comment]
@benjifisher - Thanks for the update!
