### ISSUE TITLE
XHProf UI at local.xhprof.com needs improvement

### ISSUE THREAD

**Issue by bt-eric** [geerlingguy/drupal-vm#91]
I noticed that after adding 192.168.88.88 local.xhprof.com in my hosts file to try and use the xhprof ui, the styling was not correct and the autocomplete box was not working. This is due to /usr/share/php/xhprof_html missing css, jquery, and js folders that exist when you download the tgz from https://pecl.php.net/package/xhprof. Locally, I ran the pecl command line to install xhprof and noticed the same behavior. That is, the xhprof_html css, jquery, and js folders were not created.

I added the folders to /usr/share/php/xhprof_html which solved the CSS problem and autocomplete tried to work, but ran into php errors. The errors are due to xhprof_lib replacing the space in the site name with %20, and the file was not found. Changing the site name to "Drupal Test Site" to a name without spaces solved that issue.

**Comment by YesCT** [comment]
We can find the location of the xhprof_html in https://github.com/geerlingguy/drupal-vm/blob/master/example.config.yml#L50
which says it is /usr/share/php/xhprof_html
(after doing vagrant ssh)
cd /usr/share/php/xhprof_html
 ls
I get:
callgraph.php  index.php  typeahead.php

@bt-eric says they looked at the output of the pecl install, it seemed to do a make and make install, but maybe not the ./configure that I had to do when I got xhprof from the facebook repo to work, not in the vm. (See http://yesct.net/xhprof )

**Comment by YesCT** [comment]
oops. checking the output better, it does do a configure
(search for "running:" in the output

**Comment by geerlingguy** [comment]
So it seems the `pecl`-based installation might not be up to snuff; I'll look into this in the upstream [`geerlingguy.php-xhprof`](https://github.com/geerlingguy/ansible-role-php-xhprof) project.

**Comment by geerlingguy** [comment]
Updating the title a bit... it seems there are two problems:

  - Missing `xhprof_html` css, jquery, and js folders
  - `xhprof_lib` doesn't like space in Drupal site name.

I've fixed the latter (at least with the default install), and for the former, I'll take a look upstream, later, to see if we can get the layout to look a little nicer.

**Comment by geerlingguy** [comment]
This seems to be an upstream bug in the pecl repository for XHProf: [Bug #65992 - xhprof_html is incomplete](https://bugs.php.net/bug.php?id=65992).

Rather than change the method of installation (for now, at least), I'm going to mark this as postponed, pending any further action upstream...

**Comment by geerlingguy** [comment]
Just wanted to leave a note here, too; I might want to add [Blackfire](https://blackfire.io/) to Drupal VM at some point (thanks for reminding me, @afraazali!).

**Comment by JorisVanEijden** [comment]
Created pull request upstream:  https://github.com/phacility/xhprof/pull/66

**Comment by oxyc** [comment]
This is fixed upstream in the xhprof role https://github.com/geerlingguy/ansible-role-php-xhprof/issues/11.

**Comment by geerlingguy** [comment]
Thanks for your work, @oxyc !

**Comment by oxyc** [comment]
No problem, I was hoping for an additional css file with some styling though :D Does the role need to be tagged or something btw? I noticed it wasnt used on travis.

**Comment by geerlingguy** [comment]
Yeah, I'll be tagging later tonight; was away getting supplies for home projects, and then working on said projects. Busy week!
