### ISSUE TITLE
New install fails at Drupal Console init

### ISSUE THREAD

**Issue by brentratliff** [geerlingguy/drupal-vm#910]
TASK [geerlingguy.drupal-console : Run Drupal Console init.] 

Command has been running for 2h:15m.  Mac Sierra, Drupal 8.1.10, and VB 5.1.6.  I updated drupalvm and Vagrant yesterday to the latest versions.  This is a new site provision with makefile set to true.

**Comment by chrisrikli** [comment]
@brentratliff this may provide some insight:
https://github.com/geerlingguy/drupal-vm/issues/909

**Comment by geerlingguy** [comment]
Closing in favor of #909 — I couldn't replicate in a fresh environment, but if there are still issues, I'm 99% sure it's an upstream issue with Console.
