### ISSUE TITLE
Drupal 7 installation fails without mailhog

### ISSUE THREAD

**Issue by nesreb** [geerlingguy/drupal-vm#911]
Hi Jeff!  First, thanks so much for this awesome tool.  Unfortunately, the first vagrant up fails if we set this in our custom config.yml:
installed_extras: []

I've only verified this is an issue when Drupal 7 is selected (haven't checked with Drupal 8 yet).  It looks like mailhog must be selected in installed_extras.

**Here's a little of the console output:**

TASK [Install Drupal with drush.] **********************************************
`fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal"
`
...

**And this looks like the important part of the output:**
`WD user: Session opened for admin.\nsh: 1: /opt/mailhog/mhsendmail: not found\n [error]  WD mail: Error sending e-mail (from admin@example.com to admin@example.com). \n [notice] WD cron: Cron run completed.\n [ok] Installation complete.`

Please let me know if you need more details.  Once we enable mailhog in config.yml, everything seems to install just fine, so at least we have a workaround.

Thanks again,

-Nes

**Comment by geerlingguy** [comment]
@nesreb - Aha! You're quite correct. If you drop mailhog, you will also need to override Drupal VM's built-in `php_sendmail_path` setting by defaulting back to the PHP role's default in your own `config.yml`:

```yaml
php_sendmail_path: "/usr/sbin/sendmail -t -i"
```

I'll update the docs page (http://docs.drupalvm.com/en/latest/extras/mailhog/) with this info, then close this issue.

**Comment by nesreb** [comment]
Holy cow that was a quick response!  Thanks Jeff, we are good to go then.
