### ISSUE TITLE
Help!!  Having problems running Drupal-VM on Windows 7

### ISSUE THREAD

**Issue by s-rowe** [geerlingguy/drupal-vm#914]
I just started a Drupal Development for Beginners class last week and the train has already jumped the track.  I'm falling behind in the classwork and need some expedited assistance in getting Drupal-VM to run properly on my Win 7 computer.

I've watched Jeff Geerling's installation video numerous times and did exactly as he did, but cannot get Vagrant, VirtualBox and Drupal-VM to work together.  Installation of all three programs went fine.  But when I cd to the Drupal-VM folder and input the 'vagrant up' command, the program begins to run but crashes after 30 secs. or so.

The VirtualBox interface shows packer-ubuntu-16.0 is running and the drupalvm.dev indicator also appears as Vagrant begins to run (screenshot1), but disappears just before Vagrant stops.  Just after the  the display says 'Configuring and enabling network interfaces' and 'Mounting shared folders' I see lines saying 'Forcing shutdown of VM...' and then 'Destroying VM and associated drives' (screenshot2).  I've also included a screenshot of the display after Vagrant has stopped running (screenshot3).

Any help would be most gratefully appreciated.  I'm not a code fiend or back-end developer, so please speak slowly and use small, easily understood words in your explanation.  I've got to get this local development environment running in the next few days or my class grades will suffer greatly.

Thank you, in advance, for your time and knowledge.

![screenshot1](https://cloud.githubusercontent.com/assets/22641589/19122225/70066e7e-8af7-11e6-8986-fafa61bd8ba6.PNG)
![screenshot2](https://cloud.githubusercontent.com/assets/22641589/19122226/7007c85a-8af7-11e6-877a-d0f8886a6bae.PNG)
![screenshot3](https://cloud.githubusercontent.com/assets/22641589/19122227/7009c4c0-8af7-11e6-8459-e91a9984594d.PNG)

**Comment by fubarhouse** [comment]
Subscribing, having this same issue in Windows 10 - as much as I don't really care personally it would be fantastic to fix to have another testing environment.

**Comment by geerlingguy** [comment]
This looks like the exact same issue as #912 — can you try uninstalling Vagrant and installing 1.8.5 instead for now? I need to see why 1.8.6 started breaking with an empty string passed in for the synced folder type...

Closing this issue and moving discussion to 912.
