### ISSUE TITLE
Provisioning fails with composer error

### ISSUE THREAD

**Issue by MarcoDeJong** [geerlingguy/drupal-vm#918]
First of all: great project. Thanks for your work!

Issue seems related to change due to #913. Keep getting devel package problems on default clean install.
 
`TASK [Install dependencies with composer require.] *****************************
failed: [drupalvm] (item=drupal/devel:1.x-dev) => {"changed": true, "cmd": ["/usr/bin/composer", "require", "drupal/devel:1.x-dev"], "delta": "0:00:28.938957", "end": "2016-10-10 18:50:16.017676", "failed": true, "item": "drupal/devel:1.x-dev", "rc": 2, "start": "2016-10-10 18:49:47.078719", "stderr": "    2/9:\thttps://packagist.drupal-composer.org/p/provider-2014$5d5fb9e050a0dcaadb8dc0e3a2273a5e1f92c52d9f6972cde74954fd90c1d7e4.json\n    2/9:\thttps://packagist.drupal-composer.org/p/provider-2013$a2c5f40e6e380742c49b58d25f213a022519601facb91fe79103aba1d6b4a740.json\n    3/9:\thttps://packagist.drupal-composer.org/p/provider-2015$c7f8024f8197fe0110f4ef4d6691257af56628a1f27b8bc3b70ea4a6da908dd0.json\n    4/9:\thttps://packagist.drupal-composer.org/p/provider-archived$232b1ed3e1d0fc5f4d5468cc5754de5bb1725088311d4e73af828c258acb00d1.json\n    5/9:\thttps://packagist.drupal-composer.org/p/provider-2016-10$4ad8af3b453b3e6468a25506dcf802e8aeff862d6e2dfb7c3306e3d5b6c05888.json\n    6/9:\thttps://packagist.drupal-composer.org/p/provider-2016-04$c02f69ca9e0af374de4a76b18b40c39d615cf74b0eeea1d10dc66a1d3af14e27.json\n    7/9:\thttps://packagist.drupal-composer.org/p/provider-latest$d14d2087ad12514054f5b591c6230b6175ae2b306d157e53d2253dcdbf5b3365.json\n    8/9:\thttps://packagist.drupal-composer.org/p/provider-2016-01$da6c09618373a4718012923e147673ff01f89b09dba70992756277ca081a9c6d.json\n    9/9:\thttps://packagist.drupal-composer.org/p/provider-2016-07$1d3e3a268394dd1e2055f815587c503d678e5039eddfa143bef950c41a45ef0a.json\n    Finished: success: 9, skipped: 0, failure: 0, total: 9\n    1/8:\thttp://packagist.org/p/provider-2016-10$ba40131b91cda2b5d80777c0309ecfc2a309690e6222cbf3a085b658a0c883cd.json\n    2/8:\thttp://packagist.org/p/provider-latest$8e7692716bfeaac025670ca5990aff9605c681e7d55fec8dd00a3e700537d255.json\n    3/8:\thttp://packagist.org/p/provider-2013$4d1d6905ee67f9411f9633e9435bd96d5a91de373a5e7e0cd2e7e30efa8c0b5f.json\n    5/8:\thttp://packagist.org/p/provider-2016-04$c88b4c6bbdd8308e1443020abc2d023d094d164eeddc8ae21c596f2d7a1594a9.json\n    5/8:\thttp://packagist.org/p/provider-2014$aabb3c6e45e342c470b3d200a5dbb8c7b0bf8630716486b19cad7f4cff45144b.json\n    6/8:\thttp://packagist.org/p/provider-2016-01$411a5094459e013f216fdc91c79114b32452861d3e4e3e6100426f9561cefcce.json\n    7/8:\thttp://packagist.org/p/provider-2016-07$ffbbaaf1cdce9910e54a105c687e6d6b097d8e84464d68335da0a17bbdc559e1.json\n    8/8:\thttp://packagist.org/p/provider-2015$e785be4ae57159bdd8b4eae01b3c51ef61b7aa9a72a9aa5a5a59fcb48b59da44.json\n    Finished: success: 8, skipped: 0, failure: 0, total: 8\n./composer.json has been updated\n    1/8:\thttp://packagist.org/p/provider-2016-10$ba40131b91cda2b5d80777c0309ecfc2a309690e6222cbf3a085b658a0c883cd.json\n    2/8:\thttp://packagist.org/p/provider-latest$8e7692716bfeaac025670ca5990aff9605c681e7d55fec8dd00a3e700537d255.json\n    3/8:\thttp://packagist.org/p/provider-2013$4d1d6905ee67f9411f9633e9435bd96d5a91de373a5e7e0cd2e7e30efa8c0b5f.json\n    4/8:\thttp://packagist.org/p/provider-2016-04$c88b4c6bbdd8308e1443020abc2d023d094d164eeddc8ae21c596f2d7a1594a9.json\n    5/8:\thttp://packagist.org/p/provider-2014$aabb3c6e45e342c470b3d200a5dbb8c7b0bf8630716486b19cad7f4cff45144b.json\n    6/8:\thttp://packagist.org/p/provider-2016-01$411a5094459e013f216fdc91c79114b32452861d3e4e3e6100426f9561cefcce.json\n    7/8:\thttp://packagist.org/p/provider-2016-07$ffbbaaf1cdce9910e54a105c687e6d6b097d8e84464d68335da0a17bbdc559e1.json\n    8/8:\thttp://packagist.org/p/provider-2015$e785be4ae57159bdd8b4eae01b3c51ef61b7aa9a72a9aa5a5a59fcb48b59da44.json\n    Finished: success: 8, skipped: 0, failure: 0, total: 8\n> DrupalProject\\composer\\ScriptHandler::checkComposerVersion\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - The requested package drupal/devel 1.x-dev exists as drupal/devel[7.1.0, 7.1.0-alpha1, 7.1.0-beta1, 7.1.0-beta2, 7.1.0-rc1, 7.1.1, 7.1.2, 7.1.3, 7.1.4, 7.1.5, 8.1.0-alpha1, dev-7.x-1.x, 7.1.x-dev, dev-8.x-1.x, 8.1.x-dev, dev-8.x-1.x-kint] but these are rejected by your constraint.\n\n\nInstallation failed, reverting ./composer.json to its original content.", "stdout": "", "stdout_lines": [], "warnings": []}`

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/drupal-vm/commit/81812990a5a4ca704c0f3012a6fcb988f07d8a95

This will happen if you build a new VM with an existing Drupal codebase that was set up using an older version of Drupal VM that used the old `https://packagist.drupal-composer.org/` endpoint (which was used by drupal-project up until 8 days ago—see this commit: https://github.com/drupal-composer/drupal-project/commit/49184d678ff0de7f0cda0b597a7b170c6e5261e6).

Now that drupal-project uses the official Drupal.org packagist repository, the versioning should be consistent moving forward.

(The fix, in your case, is to remove the Drupal codebase that's synced into Drupal VM (by default, in the Drupal VM folder, in a `drupal/` directory), then run `vagrant up` or `vagrant provision` again.)

**Comment by petiar** [comment]
Hi there,

I am experiencing the same problem even though I removed `drupal` and `html` directories (Drupal code base) within the DrupalVM as you suggested.

**Comment by adamtyoung** [comment]
I am also now experiencing this problem,

**Comment by yorchperaza** [comment]
I'm tried to install with Drupal 7 and have the same issue.

`failed: [elam] (item=drupal/devel:1.x-dev) => {"changed": false, "item": "drupal/devel:1.x-dev", "msg": "1/28: https://packages.drupal.org/8/drupal/provider-2011-2$b8aed369e63913ef1e4e932797ccb69650c2aca5f9baac026390b4ec873bef71.json`
