### ISSUE TITLE
OAuth for PHP 5.6?

### ISSUE THREAD

**Issue by codexmas** [geerlingguy/drupal-vm#920]
I have a config for PHP 5.6 using ubuntu1204 and another for PHP 7 with ubuntu1404.

With the PHP 7 config I was able to install OAuth with this:
```
vagrant_box: geerlingguy/ubuntu1404
php_version: "7.0"
php_packages:
  - php-oauth
```

However, for PHP 5.6 I have been unable to install it with quite a number of variations found online.

From what I understand OAuth 1.2.3 is the latest version that works with PHP 5.6:
http://stackoverflow.com/questions/27074310/ubuntu-14-04-php-pecl-oauth-error
I see the same errors in that first example in the ansible output when it fails.

None of the above work within vagrant ssh either even with sudo.

Any ideas or suggestions?

**Comment by oxyc** [comment]
The 5.6 version of the package is called `php5.6-oauth` (https://github.com/oerdnj/deb.sury.org/issues/441#issuecomment-241842971):

```yaml
php_packages:
  - php5.6
  - php5.6-apcu
  - php5.6-mcrypt
  - php5.6-cli
  - php5.6-common
  - php5.6-curl
  - php5.6-dev
  - php5.6-fpm
  - php5.6-gd
  - php5.6-sqlite3
  - php5.6-xml
  - php5.6-mbstring
  - php5.6-oauth
  - php-pear
  - libpcre3-dev
```

**Comment by geerlingguy** [comment]
@oxyc - Thanks! And welcome back :)
