### ISSUE TITLE
Drupal vm with php 5.6 increase memory - change docs?

### ISSUE THREAD

**Issue by Bertjuh** [geerlingguy/drupal-vm#922]
Hi,

First off: many thanks for this great piece of software! I wanted to leave my experience with an issue here and suggest that perhaps you could change the docs on the issue that I've encountered today?

The out of the box install of Ubuntu 16 and PHP7 works beautifully. But when I try to change the php version to 5.6 as per the instructions: http://docs.drupalvm.com/en/latest/other/php-56/ the `vagrant up` fails on `TASK [Generate Drupal project with composer package.]`

With error message: 

```
Installing drupal-composer/drupal-scaffold (2.1.0) Loading from cache 
The following exception is caused by a lack of memory or swap, or not having swap configured

Check https://getcomposer.org/doc/articles/troubleshooting.md#proc
-open-fork-failed-errors for details PHP Warning:  proc_open(): fork failed -
 Cannot allocate memory in phar:///usr/bin/composer/vendor/symfony/console/Appli
cation.php on line 957 proc_open(): fork failed - Cannot allocate memory
```

What fixed it for me was the suggestion by Jeff in https://github.com/geerlingguy/drupal-vm/issues/547 to increase `vagrant_memory` in your `config.yml`. I've set it to `2048` and now the `vagrant up` succeeds.

Could you add this to the docs page? http://docs.drupalvm.com/en/latest/other/php-56/
That might save some people a lot of time and googling?

Best,
Bart

**Comment by geerlingguy** [comment]
I think it's high time to bump the default memory usage—almost all devs I've talked to have 4GB+ on their laptops, and most have 8. If you don't, Drupal VM (even with it's saner defaults) can be a bit too much. Add in Solr, Varnish, etc., and things get pretty tight with only 1024 MB!
