### ISSUE TITLE
Can't generate VM using PHP 5.6

### ISSUE THREAD

**Issue by UTANdev** [geerlingguy/drupal-vm#929]
I believe I've followed the [documentation](http://docs.drupalvm.com/en/latest/other/php-56/), but when I `vagrant destroy` and `vagrant up`, I get the following error:

```
TASK [geerlingguy.php : Ensure PHP packages are installed.] ********************
failed: [drupalvm] (item=[u'php5.6', u'php5.6-apcu', u'php5.6-mcrypt', u'php5.6-cli', u'php5.6-common', u'php5.6-curl', u'php5.6-dev', u'php5.6-fpm', u'php5.6-gd', u'php5.6-sqlite3', u'php5.6-xml', u'php5.6-mbstring', u'php-pear', u'libpcre3-dev']) => {"failed": true, "item": ["php5.6", "php5.6-apcu", "php5.6-mcrypt", "php5.6-cli", "php5.6-common", "php5.6-curl", "php5.6-dev", "php5.6-fpm", "php5.6-gd", "php5.6-sqlite3", "php5.6-xml", "php5.6-mbstring", "php-pear", "libpcre3-dev"], "msg": "No package matching 'php5.6' is available"}
```

Here's my [config.yml](http://pastebin.com/gecC8hTy).

Thanks for your help. I'm very impressed with Drupal VM and especially its documentation; bravo!

**Comment by geerlingguy** [comment]
@UTANdev - One note—it seems like the first item in any of the list variables you have only has one space (not two); though that shouldn't cause the issue above (namely, `No package matching 'php5.6' is available`).

I wonder if maybe you're running a version older than 3.3.0 of Drupal VM?

Otherwise, if you run `vagrant destroy` to delete the VM and then `vagrant up` to rebuild it from scratch, do you still get this error?

**Comment by aweingarten** [comment]
@geerlingguy,  I am seeing similar issues with DruaplVM 3.4 and php5.6.  I took a brand new fresh blt install ran `blt:vm`.  When I ssh into the VM I get:

```
vagrant@mysite:/var/www/mysite$ php --version
PHP 7.0.12-1+deb.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.12-1+deb.sury.org~trusty+1, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by geerlingguy** [comment]
@aweingarten - If you're using BLT, the VM it generates may not be up to snuff—there was a commit to master for the `config.yml` that I don't think is part of a stable build yet.

Can you reproduce by building a fresh VM straight from Drupal VM 3.4.0 using the docs? I'll try doing that now.

**Comment by geerlingguy** [comment]
@aweingarten / @UTANdev - I just built a VM from 3.4.0 with a config.yml that only had these changes: http://docs.drupalvm.com/en/latest/other/php-56/#ubuntu-1404-ubuntu-1204

Everything seems to have worked correctly... are you sure you have 3.4.0 locally? And did you start from a clean build, or are you upgrading an existing VM?

**Comment by aweingarten** [comment]
@geerlingguy, I just confirmed my issues have something to do with BLT integration!

**Comment by UTANdev** [comment]
Jeff, you were right. I was running an outdated version of Drupal VM. After updating and making the required changes to my `config.yml` file, the VM came up just fine. Thanks!

**Comment by geerlingguy** [comment]
Sounds good, thanks for following up!
