### ISSUE TITLE
Maximum execution time of 60 seconds exceeded

### ISSUE THREAD

**Issue by Luukyb** [geerlingguy/drupal-vm#93]
Thanks for the great work !

I am running through this classic php issue "Maximum execution time of 60 seconds exceeded". I changed it manually on the php.ini but it's removed every time I provision the VM.
I was wondering if this time option could be added in the config.yml file ? Like : 
php_execution_time: "60"

Many thanks,

Luc

**Comment by geerlingguy** [comment]
Since that setting is configurable through the `geerlingguy.php` role this VM uses, you can simply add the following line inside your `config.yml` file:

```
php_max_execution_time: "120"
```

(or however long you want).

**Comment by Luukyb** [comment]
Works great, thanks!
