### ISSUE TITLE
How to determine vagrant_machine_name from within VM

### ISSUE THREAD

**Issue by grasmash** [geerlingguy/drupal-vm#931]
I'd like to get the value of vagrant_machine_name while in the VM. Since I don't know what it may be for a given vm, I do not the path of the config.yml file (which I would otherwise parse for the value). I also cannot use `hostname` given the variability of domain name structure.

Is there an environmental variable or other means to determine this and other such ansible configuration values from within the VM?

**Comment by geerlingguy** [comment]
@grasmash - A few things that _should_ be helpful:

  1. The root folder should always be mounted at `/vagrant` by default.
  2. You could add a shell provisioner in a `Vagrantfile.local` or overriding Vagrantfile that runs inside the guest and stores the machine name in a file somewhere (see [this answer](http://stackoverflow.com/a/28909819/100134)).
  3. IIRC, the `hostname` (determined by running `hostname` in the VM) should be the machine name...

**Comment by geerlingguy** [comment]
Also, you can check if `/home/vagrant` exists, or if `vagrant` is in `/etc/passwd`.

**Comment by grasmash** [comment]
Ah, knowing that the mount point is always at `/vagrant` is good enough!

`VAGRANT_MACHINE_NAME=$(grep vagrant_machine_name: /vagrant/box/config.yml | cut -d' ' -f 2)`. 

Thanks!

**Comment by geerlingguy** [comment]
99% of the time—you can technically override it and not mount it, but people rarely do that :)

**Comment by geerlingguy** [comment]
> 99% of the time—you can technically override it and not mount it, but people rarely do that :)

Heh, /me slaps self after https://github.com/acquia/blt/issues/1264
