### ISSUE TITLE
post-provision script doesn't run

### ISSUE THREAD

**Issue by grasmash** [geerlingguy/drupal-vm#932]
Drupal VM's output indicates that the specified post-provision script has run, but the expected result of the script is absent.

I have the following post-provision.sh script specified:
```
#!/usr/bin/env bash

set -x
VAGRANT_MACHINE_NAME=$(grep vagrant_machine_name: /vagrant/box/config.yml | cut -d' ' -f 2)
REPO_ROOT=/var/www/${VAGRANT_MACHINE_NAME}
cd ${REPO_ROOT}

# Add blt alias to front of .bashrc
grep -q -F 'blt' ~/.bashrc || (cat ./vendor/acquia/blt/scripts/blt/alias ~/.bashrc > temp && mv temp ~/.bashrc)

```

If I SSH into the machine and execute this script, either as a file or directly on CLI as pasted commands, they behave as expected and prepend lines to ~/.bashrc. However, when this script is executed as a post_provision script, no change to ~./bashrc occurs.

There are no errors, just:
```
TASK [Run configured post-provision shell scripts.] *****************************
changed: [blted8] => (item=../../../acquia/blt/scripts/drupal-vm/post-provision.sh)
```

Am I missing something?

**Comment by oxyc** [comment]
The ansible task runs as `root` so `~` expands to the root users home directory.

**Comment by grasmash** [comment]
You're absolutely right. Thank you!
