### ISSUE TITLE
DrupalVM does not download a base Ubuntu box.

### ISSUE THREAD

**Issue by cdesautels** [geerlingguy/drupal-vm#933]
I suspect that this is because I have Parallels installed on the machine. But I can't find a way around it. It's parallels 12 which doesn't support Parallels provider.

**Comment by fubarhouse** [comment]
Normally the provider is specified at the top of `config.yml`.
It'd be helpful to know if yours matches up with what's below.

````
# `vagrant_box` can also be set to geerlingguy/centos6, geerlingguy/centos7,
# geerlingguy/ubuntu1404, geerlingguy/ubuntu1204, parallels/ubuntu-14.04, etc.
vagrant_box: geerlingguy/ubuntu1604
vagrant_user: vagrant
vagrant_synced_folder_default_type: nfs
````

Beyond this, I cannot be of help - not being familiar with Parallels.

**Comment by geerlingguy** [comment]
@cdesautels - I don't have Parallels so can't offer any support there—older versions seemed to work fine with Vagrant, but if Vagrant doesn't integrate with Parallels 12 yet, then there's nothing I can do to help.

**Comment by thom8** [comment]
Parallels 12 should work but now only Pro and Business editions of Parallels Desktop for Mac are compatible with the Vagrant Parallels Provider. - https://github.com/Parallels/vagrant-parallels#requirements
