### ISSUE TITLE
Attempting to build with the latest DrupalVM fails on Devel install

### ISSUE THREAD

**Issue by mikeohara-bsc** [geerlingguy/drupal-vm#934]
> TASK [Install dependencies with composer require.] *****************************
> failed: [sy-----anet] (item=drupal/devel:1.x-dev) => {"failed": true, "item": "drupal/devel:1.x-dev", "module_stderr": "", "module_stdout": "Traceback (most recent call last):\r\n  File \"/tmp/ansible_KztFe0/ansible_module_command.py\", line 250, in <module>\r\n    main()\r\n  File \"/tmp/ansible_KztFe0/ansible_module_command.py\", line 186, in main\r\n    os.chdir(chdir)\r\nOSError: [Errno 2] No such file or directory: '/var/www/drupalvm/drupal'\r\n", "msg": "MODULE FAILURE"}

The odd thing is it is trying to install to `/var/www/drupalvm/drupal` but, I have explicitly defined a different directory in `vagrant_synced_folders:` When that didn't work, i changed it in `default.config.yml` and it still threw this error.

**Comment by oxyc** [comment]
Would you mind posting your `config.yml`.

**Comment by mikeohara-bsc** [comment]
[Here](https://gist.github.com/mikeohara-bsc/577f7a5eb8e226b0293ae13113e0dced) you are.

**Comment by oxyc** [comment]
It seems your `config.yml` is somewhat outdated and a few options from `default.config.yml` are being used. The variable you haven't configured is `drupal_composer_install_dir`.

To fix this particular error you need to add:

```
drupal_composer_install_dir: "/var/www/sy-----anet"
```

**Comment by mikeohara-bsc** [comment]
That worked!
