### ISSUE TITLE
DrupalVM and BLT Docroot Issues

### ISSUE THREAD

**Issue by mikemadison13** [geerlingguy/drupal-vm#935]
I've run into an issue recently using the blt vm script that is funky. Loading up the <project>.localhost url "works" in the sense that I can access Apache inside of my VM. However, it isn't actually loading the <project>/docroot and Drupal install as expected. If I run a $ vagrant suspend and $vagrant up and refresh the <project>.localhost url, the Drupal site comes up as expected.

**Comment by geerlingguy** [comment]
@mikemadison13 - Using `.localhost` can have a lot of weird issues—I recently recommended the default be changed to `local.[project].com` instead, as this doesn't seem to have these weird DNS issues (especially on Windows and Linux, though sometimes on Mac too).

Can you try changing the URL and see if that helps? I think the default was changed in BLT 8.5.0.

**Comment by mikemadison13** [comment]
Let me branch the project and re-provision a vm to see if it works. Will post results back. Thanks!

**Comment by mikemadison13** [comment]
I changed this in both the project.yml file (BLT) and config.yml (DrupalVM) to be local.[project].com and all worked as expected this time. Thanks!

**Comment by geerlingguy** [comment]
@mikemadison13 - Perfect! Good to have confirmation.
