### ISSUE TITLE
OOTB Xdebug support for PhpStorm

### ISSUE THREAD

**Issue by phenaproxima** [geerlingguy/drupal-vm#94]
I'm not sure if Drupal VM already supports this, but I had to do a bit of work in order to get Xdebug talking to PhpStorm.

I had to alter my /etc/php5/apache2/conf.d/xdebug.ini as follows:

```
xdebug.default_enable = 1 ; Was 0
xdebug.remote_enable = true ; Was false
xdebug.remote_connect_back = true ; Was false
xdebug.remote_host = 10.0.2.2 ; Was localhost
xdebug.idekey = "vagrant" ; Was sublime
```

Is there any chance of having this be Drupal VM's default configuration, or somehow make it very easy to configure Xdebug this way in config.yml?

**Comment by geerlingguy** [comment]
All of these variables can easily be overridden inside your `config.yml` file. See https://github.com/geerlingguy/ansible-role-php-xdebug (the README) for examples of variables you can set. For example:

```
php_xdebug_default_enable: 1
php_xdebug_remote_enable: "true"
php_xdebug_remote_connect_back: "true"
php_xdebug_remote_host: 10.0.2.2.
php_xdebug_idekey: vagrant
```

**Comment by phenaproxima** [comment]
Brilliant. Thank you!

**Comment by kevinquillen** [comment]
Why wouldn't xdebug just be enabled by default?

**Comment by geerlingguy** [comment]
@kevinquillen - Because Xdebug incurs a non-trival amount of overhead, and I (and many others) like to develop without it enabled most of the time, and only enable it as-needed. The two reasons for this (for me) are:

  1. Performance overhead—memory and resource usage are more like real-world when xdebug is disabled.
  2. 99% of the time, I don't need all the extra information Xdebug outputs in error logs, and don't need any extra information beyond what I can git dumping a variable by hand.

**Comment by geerlingguy** [comment]
@kevinquillen - I've updated the documentation here: http://docs.drupalvm.com/en/latest/extras/xdebug/

**Comment by kostajh** [comment]
@geerlingguy with the out of the box configuration provided by Drupal VM, have you gotten PhpStorm to debug Behat scripts running in the VM? I have a [remote Behat configuration set up](https://www.jetbrains.com/phpstorm/help/using-behat-framework.html#d353357e676), and it's using Drupal VM's php binary, so I have no issues running Behat tests from within Drupal VM using PhpStorm. But debugging said configuration doesn't work. 

According to [this](http://stackoverflow.com/questions/27522054/enable-xdebug-in-behat), `xdebug_autostart` should be 1 and `connect_back` should be `false`, these are different values than the VM provides. I've tried changing those myself within the VM, though, without success.

**Comment by geerlingguy** [comment]
@kostajh - I, personally, have not, as I don't use PhpStorm :(

But I'm guessing someone has, and hopefully you can find that person to help; did anything in the docs.drupalvm.com section on xdebug help?

**Comment by kostajh** [comment]
@geerlingguy no, unfortunately. The same would apply for Sublime Text though. Are you able to execute a PHP script from the command line within the VM, and have Sublime Text's XDebug client connect?

**Comment by geerlingguy** [comment]
@kostajh - Last time I did was at least a few months ago, but when I did, I did it using the instructions in the docs (http://docs.drupalvm.com/en/latest/extras/xdebug/)... so something may have changed, or a port might not be open that's required... something like that.
