### ISSUE TITLE
'Install Drupal with drush' step fails

### ISSUE THREAD

**Issue by adamtyoung** [geerlingguy/drupal-vm#943]
First install, running fine until above step, where I get a 'need to invoke Drush from a more functional environment' error.

**Comment by geerlingguy** [comment]
I can't reproduce this on Mac or Windows with 3.4.0 or master—and the automated tests seem to be running fine as well; what kind of things have you customized in your `config.yml`? And are you on Mac or Windows? And what kind of project are you working on (plain Drupal VM, or did you use another tool like BLT to set it up?).

**Comment by adamtyoung** [comment]
Seems to be fine now---I think it might have been because I needed to chmod the drupal-vm files to execute. Ha although now I am getting another error:
`fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Failure downloading http://rpms.remirepo.net/enterprise/remi-release-7.rpm, [Errno 104] Connection reset by peer"}`
when trying to build a CentOS 7 box.

**Comment by cdmo** [comment]
I'm getting the above error too, fwiw

**Comment by geerlingguy** [comment]
I'm assuming you're both trying to build CentOS 7?

`[Errno 104] Connection reset by peer` sounds like a networking issue—I can get the RPM fine from my location right now, but it could've either been down for a time, or be unreachable through your ISP/region... can you try again and make sure this still happens?

**Comment by cdmo** [comment]
Yeah, still getting that this morning

**Comment by joelpittet** [comment]
Looks related to #850

**Comment by joelpittet** [comment]
@cdmo I don't think it's just you, but I'm also at a university, though going between hardline and wifi didn't help.

**Comment by joelpittet** [comment]
With -vvv added here's the result.

```
TASK [geerlingguy.repo-remi : Install remi repo.] ******************************
task path: /Users/me/Servers/drupal-vm/provisioning/roles/geerlingguy.repo-remi/tasks/main.yml:2
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -q -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/Users/me/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'( umask 77 && mkdir -p "` echo $HOME/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868 `" && echo ansible-tmp-1478209265.32-164235558573868="` echo $HOME/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868 `" ) && sleep 0'"'"''
<127.0.0.1> PUT /var/folders/v3/29p3_k7n5ts6n900d778qjxc0000gn/T/tmp7m8lBl TO /home/vagrant/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868/yum
<127.0.0.1> SSH: EXEC sftp -b - -C -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/Users/me/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r '[127.0.0.1]'
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -q -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/Users/me/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r 127.0.0.1 '/bin/sh -c '"'"'chmod u+x /home/vagrant/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868/ /home/vagrant/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868/yum && sleep 0'"'"''
<127.0.0.1> ESTABLISH SSH CONNECTION FOR USER: vagrant
<127.0.0.1> SSH: EXEC ssh -C -q -o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ForwardAgent=yes -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=2222 -o 'IdentityFile="/Users/me/.vagrant.d/insecure_private_key"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=30 -o ControlPath=/Users/me/.ansible/cp/ansible-ssh-%h-%p-%r -tt 127.0.0.1 '/bin/sh -c '"'"'sudo -H -S -n -u root /bin/sh -c '"'"'"'"'"'"'"'"'echo BECOME-SUCCESS-bfwvnrnjvbqcxwgzjlhxskdaaxddtsjt; LANG=en_US LC_ALL=en_US LC_MESSAGES=en_US /usr/bin/python /home/vagrant/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868/yum; rm -rf "/home/vagrant/.ansible/tmp/ansible-tmp-1478209265.32-164235558573868/" > /dev/null 2>&1'"'"'"'"'"'"'"'"' && sleep 0'"'"''
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "invocation": {"module_args": {"conf_file": null, "disable_gpg_check": false, "disablerepo": null, "enablerepo": null, "exclude": null, "install_repoquery": true, "list": null, "name": ["http://rpms.remirepo.net/enterprise/remi-release-7.rpm"], "state": "present", "update_cache": false, "validate_certs": true}, "module_name": "yum"}, "msg": "Failure downloading http://rpms.remirepo.net/enterprise/remi-release-7.rpm, [Errno 104] Connection reset by peer"}
```

**Comment by adamtyoung** [comment]
Well, now it is failing on the 'Install Drush dependencies with Composer step'

`TASK [geerlingguy.drush : Install Drush dependencies with Composer.] ***********
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": "/usr/bin/composer install --prefer-dist --no-interaction", "delta": "0:00:29.552338", "end": "2016-11-03 22:04:37.118763", "failed": true, "rc": 1, "start": "2016-11-03 22:04:07.566425", "stderr": "Do not run Composer as root/super user! See https://getcomposer.org/root for details\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nFailed to decode response: zlib_decode(): data error\nRetrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info\n\n                             \n  [ErrorException]           \n  zlib_decode(): data error  \n                             \n\ninstall [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...", "stdout": "", "stdout_lines": [], "warnings": []}
`

Could this be because of some conflict with my global Composer?

**Comment by joelpittet** [comment]
Interesting I ssh'd in and ran
`curl http://rpms.remirepo.net/enterprise/remi-release-7.rpm`

And it returned:

```
Cfrremi-release7.21.el7.remiYUM configuration for remi repositoryConfiguration de YUM pour le dépôt remiThis package contains yum configuration for the Remi's RPM Repository,
as well as the public GPG keys used to sign them.

Only the "remi-safe" repository is enabled after installation.



For PHP 5.5 you must enable the remi-php55 repository:
    yum-config-manager --enable remi-php55

For PHP 5.6 you must enable the remi-php56 repository:
    yum-config-manager --enable remi-php56

For PHP 7.0 you must enable the remi-php70 repository:
    yum-config-manager --enable remi-php70

For PHP 7.1 you must enable the remi-php71 repository:
    yum-config-manager --enable remi-php71


Software Collections are in the "remi-safe" repository.

FAQ:   http://blog.remirepo.net/pages/English-FAQ
Forum: http://forum.remirepo.net/Ce paquetage contient le fichier de configuration de YUM pour utiliser
les RPM du dépôt de Remi ainsi que la clé GPG utilisée pour les signer.

Seul le dépôt "remi-safe" est activé après l'installation.



Pour PHP 5.5 vous devez activer le dépôt remi-php55
    yum-config-manager --enable remi-php55

curl: (56) Recv failure: Connection reset by peer
```

**Comment by adamtyoung** [comment]
Sigh---another try, another error: `Unable to load autoload.php. Drush now requires Composer in order to install its dependencies and autoload classes.`
Why is Drush acquired via git when it is not possible to do this anymore? (see https://github.com/drush-ops/drush/issues/1538)

**Comment by joelpittet** [comment]
FYI, tried to destroy the box and create it again but still getting the 

> Connection reset by peer

Wondering if I should split that error with @cdmo to a separate issue because @adamtyoung's original issue was on Drush and I may be going off topic due to the 

> Seems to be fine now ... `Connection reset by peer`
Comment above

**Comment by joelpittet** [comment]
I think mine is due to a regression with NAT in VirtualBox
https://www.virtualbox.org/ticket/16084
Found through the bottom of: https://www.virtualbox.org/ticket/13156

**Comment by joelpittet** [comment]
OSX sierra: reverted Virtualbox from `5.1.8` back to `5.1.6` fixed the `Connection reset by peer` issue.

**Comment by adamtyoung** [comment]
Thanks @joelpittet ! Reverting to VBox 5.1.6 fixed my issues too.

**Comment by cdmo** [comment]
I'm El Capitan and upgrading to `5.1.8` from `5.0.28` didn't change the problem, reverting down to `5.1.6` did. Thanks for figuring this out and sharing back @joelpittet

**Comment by joelpittet** [comment]
I wonder if `5.1.10` resolves this, has anybody tried?  I had issues on windows and osx with `5.1.8`.

**Comment by geerlingguy** [comment]
@joelpittet - From what I've heard elsewhere, 5.1.10 does resolve this and many other networking issues.

**Comment by joelpittet** [comment]
Thanks I'll give it a try on both tomorrow!

**Comment by cdmo** [comment]
I just tried `5.1.10` and was able to spin up just fine, no errors.

**Comment by adamtyoung** [comment]
Me too. 5.1.10 FTW

**Comment by joelpittet** [comment]
Yup other issues arose but `5.1.10` didn't seem to be the culprit
