### ISSUE TITLE
Samba server option

### ISSUE THREAD

**Issue by edwinpopham** [geerlingguy/drupal-vm#944]
To avoid the problems with shared folders on Windows, I was trying to enable Samba server on the guest. Don't seem to be able to mount shared drives on the host however. What is the method for enabling Samba server on this configuration? Thanks

**Comment by geerlingguy** [comment]
@edwinpopham - if you set the mount type for a synced folder to `"smb"`, Vagrant does the rest for you automatically; no need to install anything separate in the guest. See: http://docs.drupalvm.com/en/latest/other/windows/#performance

**Comment by edwinpopham** [comment]
Thanks for that but I was meaning using Samba server on the guest machine. So as not to have files on the host machine. I find it faster and more reliable this way on a windows machine. I have got it working by opening ports and installing Samba server on the vm, but is there an easier way to script this into the vm?

**Comment by geerlingguy** [comment]
@edwinpopham - You could use pre-provision and/or post-provision scripts to do this. I also have a [samba role](https://galaxy.ansible.com/geerlingguy/samba/) for Ansible that does this too, but you couldn't run that along with the base provisioning unless you have a custom Vagrantfile.local that adds in another Ansible provisioner to run just that role.

See:

  - http://docs.drupalvm.com/en/latest/other/overriding-configurations/
  - http://docs.drupalvm.com/en/latest/extras/scripts/
