### ISSUE TITLE
Unexpected templating type error occurred

### ISSUE THREAD

**Issue by gilcarroll** [geerlingguy/drupal-vm#946]
a few late nights of errors. This is the most stubborn error (using geerlingguy-drupal-vm-3.4.0-0-gac56269). My VM works and I can ssh into it, but never a drupal instance but rather a  fatal error.

fatal: [drupaldd]: FAILED! => {"failed": true, "msg": "The conditional check 'drupal_major_version > 7 and \"drupalconsole\" in installed_extras' failed. The error was: Unexpected templating type error occurred on ({% if drupal_major_version > 7 and \"drupalconsole\" in installed_extras %} True {% else %} False {% endif %}): argument of type 'NoneType' is not iterable"}

(FYI with drupal-vm-master I get a different error at the same point, roughly, that the directory for Drupal is not empty)

Any thoughts?

**Comment by geerlingguy** [comment]
What version of Ansible do you have installed (`ansible --version`)? If it's < 2.1, then this error (and many others) can occur. You'll need to update your Ansible installation.

**Comment by gilcarroll** [comment]
It is 2.1..2.0 (I should have included that).

**Comment by geerlingguy** [comment]
Oh, another thing to check—how do you have `installed_extras` formatted? If it's empty (e.g. everything below is commented out, you need to set it like this:

```
installed_extras: []
```

Without the `[]` it doesn't register as an empty array, but as an empty string/false.

**Comment by gilcarroll** [comment]
I have tried both with installed_extras: [] or with one still commented in. Both fail. I am using a few of your tutorials, notably http://www.jeffgeerling.com/blog/2016/drupal-vm-quick-introduction-video and one in Drupal cookbook. These are a bit different, but both fail in their own way. I think I may have tried another turorial also. I still succeed on everything until installing drupal, when I get:


TASK [Generate Drupal project with composer package.] **************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/bin/composer", "create-project", "drupal-composer/drupal-project:8.x-dev", "/var/www/drupalvm/drupal", "--prefer-dist", "--stability", "dev", "--no-interaction"], "delta": "0:00:03.980892", "end": "2016-10-30 23:18:11.031062", "failed": true, "rc": 1, "start": "2016-10-30 23:18:07.050170", "stderr": "    1/1:\thttp://packagist.org/p/provider-latest$797f7aca916013b3249cc398c8071227bd572e81b68824ae9197ec09d093b290.json\n    Finished: success: 1, skipped: 0, failure: 0, total: 1\nInstalling drupal-composer/drupal-project (8.x-dev f6099e3597d82691e16364ab5a5b7edd05d8bf5c)\n\n                                                             \n  [InvalidArgumentException]                                 \n  Project directory /var/www/drupalvm/drupal/ is not empty.  \n                                                             \n\ncreate-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @/Users/gilcarroll/code/sandbox/drupal-vm-master/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=121  changed=0    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

**Comment by gilcarroll** [comment]
Here is a bit of observation...drupal appears to fail after installing part way. Then, I run vagrant provision, and it fails with a more simple error, not being able to pick back up since my drupal directory is now not empty.

**Comment by gilcarroll** [comment]
GOT IT! I think I had to 1) empty out the /var/www/drupal directory. then vagrant reload, then vagrant provision...

**Comment by geerlingguy** [comment]
Awesome, glad you got it figured out!
