### ISSUE TITLE
Varnish Cache issue

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#947]
Removing this comment about 3.x installation because it's probably a different issue

**Comment by justinlevi** [comment]
Also, for the life of me, I can't figure out how to clear Varnish cache from within an ssh session to the VM. 

None of these seem to be working: 

```
curl -v -X PURGE -H 'Host: localhost' 127.0.0.1
  225  curl -v -X BAN -H 'Host: webny.dev' 127.0.0.1
  226  curl -v -X BAN -H 'Purge-Cache-Tags: webny.dev' 127.0.0.1
  227  curl -v -X PURGE -H 'Purge-Cache-Tags: webny.dev' 127.0.0.1
  228  curl -v -X PURGE -H 'Purge-Cache-Tags: 127.0.0.1' 127.0.0.1
  229  curl -v -X PURGE -H 'Purge-Cache-Tags: http://webny.dev' 127.0.0.1
  230  curl -v -X PURGE -H 'Purge-Cache-Tags: http://webny.dev' 127.0.0.1:81
  231  curl -v -X PURGE -H 'Purge-Cache-Tags: http://webny.dev' http://webny.dev
  232  curl -v -X PURGE -H 'Purge-Cache-Tags: http://webny.dev' localhost
  233  curl -v -X PURGE -H 'Purge-Cache-Tags: http://webny.dev' 127.0.0.1
  234  curl -v -X PURGE -H 'Purge-Cache-Tags: webny.dev' 127.0.0.1
  235  curl -v -X PURGE -H 'Purge-Cache-Tags: node_list' 127.0.0.1
  236  curl --insecure -I -H "Host: localhost" https://localhost -X PURGE
  237  curl --insecure -I -H "Host: localhost" http://localhost -X PURGE
  238  curl --insecure -I -H "Host: localhost" http://127.0.0.1 -X PURGE
  239  curl --insecure -I -H "Host: http://webny.dev" http://127.0.0.1 -X PURGE
  240  curl -I -H "Host: http://webny.dev" http://127.0.0.1 -X PURGE
  241  curl -I -H "Host: webny.dev" http://127.0.0.1 -X PURGE
  242  curl -I -H "Host: webny.dev" http://127.0.0.1 -X BAN
```

**Comment by justinlevi** [comment]
I'm struggling to get just get my Varnish cache cleared even via curl. 

Here's what my config looks like: 

```
apache_listen_port: "81"
# Varnish Configuration (if enabled above).
varnish_listen_port: "80"
varnish_default_vcl_template_path: templates/drupalvm.vcl.j2
varnish_default_backend_host: "127.0.0.1"
varnish_default_backend_port: "81"
```
Source: http://docs.drupalvm.com/en/latest/extras/varnish/

Are the above ports correct? I'm second guessing myself because when I run:
`curl -X BAN http://127.0.0.1:81/ -H "X-Drupal-Cache-Tags: block_view"` 

I see the following error:

```
The website encountered an unexpected error. Please try again later.</br></br><em class="placeholder">Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException</em>: No route found for &quot;BAN /&quot;: Method Not Allowed (Allow: GET, POST, DELETE) in <em class="placeholder">Symfony\Component\HttpKernel\EventListener\RouterListener-&gt;onKernelRequest()</em> (line <em class="placeholder">180</em> of <em class="placeholder">/var/www/webny/vendor/symfony/http-kernel/EventListener/RouterListener.php</em>). <pre class="backtrace">Drupal\Core\Routing\UrlMatcher-&gt;finalMatch(Object, Object) (Line: 152)
```

My assumption is that I'd want varnish listening on port 80 and apache would be on 81, I'm not sure exactly what the `varnish_default_backend_port` is. I'm assuming it's to access the varnish data store. 

I've also got my the following `settings.php` changes added:

```
$settings['reverse_proxy'] = TRUE;
$settings['reverse_proxy_addresses'] = array('127.0.0.1');
```

I've read through this thread which was super informative 
https://github.com/geerlingguy/drupal-vm/issues/397

Unfortunately I still seem to be running into issues when trying to simply clear the cache via curl. 

When I run the following, 
`curl -X BAN http://127.0.0.1/ -H "X-Cache-Tags: block_view"`

I see the following error
```
<!DOCTYPE html>
<html>
  <head>
    <title>403 Purge-Cache-Tags header missing.</title>
  </head>
  <body>
    <h1>Error 403 Purge-Cache-Tags header missing.</h1>
    <p>Purge-Cache-Tags header missing.</p>
    <h3>Guru Meditation:</h3>
    <p>XID: 229633</p>
    <hr>
    <p>Varnish cache server</p>
  </body>
</html>
```

So my first goal is just to just be able to manually clear my varnish cache, so I know I've got things setup correctly. Then I'm hoping to clear using tags, but honestly, that's not even that important. 

Any help is greatly appreciated.

**Comment by justinlevi** [comment]
So after digging into the VCL file closer, I'm seeing 

```
    # Only allow PURGE requests from IP addresses in the 'purge' ACL.
    if (req.method == "PURGE") {
        if (!client.ip ~ purge) {
            return (synth(405, "Not allowed."));
        }
        return (hash);
    }
```

I'm wondering why we're returning (hash) here? 

From the varnish documentation: https://www.varnish-cache.org/docs/4.0/users-guide/purging.html it seems like we'd want to return (purge) no? 

Here's a bit more about how I got to this point: 

First, I finally was able to figure out how to access the CLI  via `varnishadm`

$ `varnishadm "ban req.http.host == amber.dev"`

This did in fact clear my varnish cache, in that I'd see a `X-Varnish-Cache: MISS` if I did curl request or inspected the headers via my browser . A few of the other varnishadm commands confirmed that varnish seemed to be up and running for me. 

To simplify my testing, I ended up just creating a simple html page (varnish.html) so I could monitor the varnish log via $ `varnishlog` and not have to deal with all of the other requests showing up with a full drupal page. 

Regardless though, with the PURGE request returning (hash), when I would run: 

$ `curl -I -v -X PURGE -H 'host: amber.dev' amber.dev/varnish.html`
The cache would not be cleared, I would see a HIT if I inspected the headers through the browser, and I would see the following headers via curl:

```
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to amber.dev (127.0.0.1) port 80 (#0)
> PURGE /varnish.html HTTP/1.1
> User-Agent: curl/7.35.0
> Accept: */*
> host: amber.dev
> 
< HTTP/1.1 200 OK
HTTP/1.1 200 OK
< Date: Fri, 28 Oct 2016 15:48:04 GMT
Date: Fri, 28 Oct 2016 15:48:04 GMT
* Server Apache/2.4.7 (Ubuntu) is not blacklisted
< Server: Apache/2.4.7 (Ubuntu)
Server: Apache/2.4.7 (Ubuntu)
< Last-Modified: Fri, 28 Oct 2016 15:47:46 GMT
Last-Modified: Fri, 28 Oct 2016 15:47:46 GMT
< Vary: Accept-Encoding
Vary: Accept-Encoding
< Cache-Control: max-age=1209600
Cache-Control: max-age=1209600
< Expires: Fri, 11 Nov 2016 15:48:04 GMT
Expires: Fri, 11 Nov 2016 15:48:04 GMT
< Content-Type: text/html
Content-Type: text/html
< X-Varnish: 10 3
X-Varnish: 10 3
< Age: 18
Age: 18
< Via: 1.1 varnish-v4
Via: 1.1 varnish-v4
< ETag: W/"97-53feec7898c80-gzip"
ETag: W/"97-53feec7898c80-gzip"
< X-Varnish-Cache: HIT
X-Varnish-Cache: HIT
< Transfer-Encoding: chunked
Transfer-Encoding: chunked
< Connection: keep-alive
Connection: keep-alive
< Accept-Ranges: bytes
Accept-Ranges: bytes

< 
* Excess found in a non pipelined read: excess = 164 url = /varnish.html (zero-length body)
* Connection #0 to host amber.dev left intact
```

From everything I was reading, I should see `HTTP/1.1 200 PURGE` returned if the purge actually succeeded. 

I then changed the `/etc/varnish/default.vcl` to the following: 

```
    # Only allow PURGE requests from IP addresses in the 'purge' ACL.
    if (req.method == "PURGE") {
        if (!client.ip ~ purge) {
            return (synth(405, "Not allowed."));
        }
        return (purge);
    }
```

And restarted Varnish with: 

$ `sudo service varnish restart` - I think you might also be able to run $  `sudo /etc/init.d/varnish reload`

I immediately noticed a difference when running :

$ `curl -I -v -X PURGE -H 'host: amber.dev' amber.dev/varnish.html`

Because I saw the following returned:

`HTTP/1.1 200 Purged`

I then confirmed that the cache was getting cleared via my browser as well. 

source: 
* https://www.varnish-cache.org/docs/4.0/users-guide/purging.html
* http://book.varnish-software.com/4.0/chapters/VCL_Basics.html

**Comment by geerlingguy** [comment]
I'll try to take a look soon... I was fairly certain this was working as-is earlier, at least with Varnish 4.x, but maybe I didn't commit a fix I though I had or something :/

**Comment by geerlingguy** [comment]
Hmm... is this happening using the default Varnish version (4.x, I believe), or only when you're trying to switch to 3.x? At this time, Drupal VM's defaults are only guaranteed to work with 4.x, and purging/banning changed a _lot_ between the two versions. The 3.x style PURGE request is a bit different than BANs in 4.x.

**Comment by justinlevi** [comment]
This is with the latest Varnish 4.x - I could be totally wrong with the vcl though as I really don't know what I'm doing with Varnish or the VCL file.

**Comment by justinlevi** [comment]
Another potential issue with `provisioning/templates/drupalvm.vcl.j2` file is that since Purge 8-x.1.4 the header is now `Cache-Tags` vs the older `Purge-Cache-Tags` which means the VCL file would need to be updated to: 

```
# Only allow BAN requests from IP addresses in the 'purge' ACL.
    if (req.method == "BAN") {
        # Same ACL check as above:
        if (!client.ip ~ purge) {
            return (synth(403, "Not allowed."));
        }

        # Logic for the ban, using the Cache-Tags header. For more info
        # see https://github.com/geerlingguy/drupal-vm/issues/397.
        if (req.http.Cache-Tags) {
            ban("obj.http.Cache-Tags ~ " + req.http.Cache-Tags);
        }
        else {
            return (synth(403, "Cache-Tags header missing."));
        }

        # Throw a synthetic page so the request won't go to the backend.
        return (synth(200, "Ban added."));
    }
```

source: https://wunderkraut.se/blogg/varnish-purge-8x14-out
           : https://gitlab.wklive.net/snippets/32

**Comment by oxyc** [comment]
[drupal.org docs](https://www.drupal.org/docs/7/caching-to-improve-performance/varnish-4x-configuration) also uses `return (purge)`.

**Comment by geerlingguy** [comment]
Sounds good enough for me, merging the PR for now, will try to get some more time to retest later. Also linking http://www.jeffgeerling.com/blog/2016/use-drupal-8-cache-tags-varnish-and-purge for posterity (that was when I was initially adding this support... I notice in the blog post I never mentioned returning the hash).
