### ISSUE TITLE
Vagrant provision is blocking when running task -> [Update apt cache if needed]

### ISSUE THREAD

**Issue by ivanovf** [geerlingguy/drupal-vm#949]
Hi,
When I run the vagrant provision command it is stopped in "Update apt cache if needed" task, and don't finish to provide the MV.

My local machine is an Ubuntu 14.

**Comment by geerlingguy** [comment]
Can you try running `vagrant destroy -f` to remove the VM, then `vagrant box update` to update the downloaded box, and try `vagrant up` again.

Also, it can sometimes take 3-5 minutes for the Update apt cache task to complete—especially over slower Internet connections.
