### ISSUE TITLE
Vagrant cachier uses default sync folder type, which is not available

### ISSUE THREAD

**Issue by hussainweb** [geerlingguy/drupal-vm#950]
When running `vagrant up` with vagrant cachier installed, I get this error:

> Vagrant was unable to mount VirtualBox shared folders. This is usually
> because the filesystem "vboxsf" is not available. This filesystem is
> made available via the VirtualBox Guest Additions and kernel module.
> Please verify that these guest additions are properly installed in the
> guest. This is not a bug in Vagrant and is usually caused by a faulty
> Vagrant box. For context, the command attempted was:
> 
> mount -t vboxsf -o uid=900,gid=900 vagrant-cache /tmp/vagrant-cache
> 
> The error output from the command was:
> 
> /sbin/mount.vboxsf: mounting failed with the error: No such device

I am using geerlingguy/ubuntu1404 box and apparently it does not have VirtualBox guest extensions installed (I get a message saying that earlier as well). I can live with that if cachier can use a different sharing type. Pull Request coming up with changes for that.

**Comment by geerlingguy** [comment]
@hussainweb - I'm guessing you have the 1.0.3 (I think? maybe 1.0.4) version of that box, which has outdated guest additions. You should also make sure to install the `vbguest` plugin too: `vagrant plugin install vagrant-vbguest`, so the guest additions are always up to date.

I just published a new version of the box today, with Guest Additions for 5.1.8.

Closing this issue, will track the PR to still allow the customization to be set for cachier (see my comment there).

**Comment by hussainweb** [comment]
I have the latest version of that box (1.1.3). I have used boxes with outdated guest extensions before and sharing still works. Here, it says the guest extensions are entirely missing. Maybe it was an older version of your box itself because the error just appeared recently, after I updated the boxes.

Thanks for the tip on plugin. I'll check it out.

**Comment by hussainweb** [comment]
I checked the plugin and see that it installs VB Guest additions if not present. I guess you removed Guest additions from your boxes and relied on the plugin to install it. I remember not seeing this error earlier (but that could also be as I was not using cachier earlier, which means everything was on NFS).

Was this plugin required to use DrupalVM? I didn't see any documentation suggesting this.

**Comment by geerlingguy** [comment]
> I guess you removed Guest additions from your boxes and relied on the plugin to install it.

In this case, the boxes were just a couple months out of date, and had 5.0.24 guest additions—because of a myriad of problems with Vagrant 1.8.4/5 and VirtualBox 5.1.x, I had held off updating the boxes until things were stale.

So the additions are/were present, they were just out of date. And in that case, Vagrant and VirtualBox don't always get along unless you have the vbguest plugin automatically installing the _correct_ version of additions :)

**Comment by hussainweb** [comment]
For the record, VB Guest additions are present on `geerlingguy/ubuntu1604` box but not on `geerlingguy/ubuntu1404`. It is 5.0.24 guest additions (on `geerlingguy/ubuntu1604`) but it works fine. I remember it worked with guest additions 4.x as well (some other box). I remember seeing the warning but it worked. That is why I am so sure that the box is missing the guest additions somehow because I get an error (unless I set it to NFS). I have never faced issues with mismatched VBox and guest addition versions, even differences in major versions.

I haven't tried the vbguest plugin yet, will do soon. In any case, the PR will help in enabling NFS which is useful regardless of default sharing.

**Comment by geerlingguy** [comment]
@hussainweb - Weird... I must've pushed a bad box build last time. Can you also try running `vagrant box update` and see if the new version that's available has the additions? I just checked yesterday and it seems they were present.

**Comment by hussainweb** [comment]
I can confirm that 1604 does. I will try to create a new VM off the new version of image to check on 1404.

Also, I made the changes you requested on the PR. It is ready for you review. :)

**Comment by geerlingguy** [comment]
@hussainweb - For some strange reason, the PR has disappeared... it's still in the list here (https://github.com/geerlingguy/drupal-vm/pulls), but I get a 404 when I visit https://github.com/geerlingguy/drupal-vm/pull/951 — did you maybe delete the branch?

**Comment by hussainweb** [comment]
That's weird. I think it is a Github issue. All PRs are giving a 500 right now. The branch is there at https://github.com/hussainweb/drupal-vm but gives a 500 when I try to switch to the branch in Github.

**Comment by hussainweb** [comment]
@geerlingguy, the PR is visible now.

**Comment by geerlingguy** [comment]
Merged!
