### ISSUE TITLE
Timed out while waiting for the machine to boot.

### ISSUE THREAD

**Issue by mauriziodimatteo** [geerlingguy/drupal-vm#953]
How to reproduce the error:
`> cd ~/geerlingguy-drupal-vm-ac56269/` (straight out of the zip file)
```
> vagrant up
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Cloning VM...
==> drupalvm: Matching MAC address for NAT networking...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Setting the name of the VM: drupalvm.dev
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
```
*after a few minutes of intense suspence*

```
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.
```

I showed the GUI of the guest OS via Virtualbox and it is stuck on a black screen stating:
```
[    6.569034] piix:smbus 0000:00:0
7.0: SMbus base address uninitialized - upgrade bios or use force_addr=0xaddr mac os virtualbox
[      6.878323] intel_rapl: no valid rapl domains found in package 0
```
If I press `ESC` to display the detailed boot log I can see a new process starting:
`A start job is running for Raise network interfaces`. ([screenshot](http://imgur.com/a/mXMLj))
It lasts about 5 minutes and I'm guessing that's longer than vagrant's login timeout. If I start the VM manually from within VirtualBox and wait, after about 5 minutes I'm asked username and password.

I tried unchecking `Enable Nested Paging` and changing the virtual chipset in VirtualBox's settings, [as suggested somewhere else](http://askubuntu.com/questions/298290/smbus-bios-error-while-booting-ubuntu-in-virtualbox), but none of that helped. 

The problem doesn't show up when using a recent xenial64 box:
`> vagrant init ubuntu/xenial64`

`geerlingguy/ubuntu1204`, `geerlingguy/ubuntu1404` and `geerlingguy/centos7` don't rise this error, but they all get stuck on the login screen waiting for username and password. Go figure.

[Here](https://gist.github.com/dimatteomaurizio/a26f71658cad79d121dea2998ae6f7d4) it is the output of `vagrant up --debug`.

My setup:
- Mac OS X Sierra  10.12.1
- Vagrant 1.8.6
- Ansible 2.1.2.0
- VirtualBox 5.0.28

**Comment by geerlingguy** [comment]
@dimatteomaurizio - Thank you SO much for the detailed error report. You have no idea how many times I have to help someone starting from an issue summary of "something doesn't work" (and that's literally it).

In this case, I'm 99% sure the issue is VirtualBox 5.0.28—I just updated the boxes to use 5.1.8 guest additions, so they will likely not work correctly with 5.0.x anymore. If you aren't able to upgrade VirtualBox to the latest version, you can install the previous Vagrant box version of `geerlingguy/ubuntu1604` and it should hopefully work correctly.

**Comment by keithcrooks** [comment]
I also experienced this issue while running VirtualBox 5.0.26 after doing a `vagrant box update` from `geerlingguy/ubuntu1604` `1.0.4` to `1.0.5`.

I've updated VirtualBox to 5.1.8 which has fixed the initial `SMbus` error above, but I'm still getting the second error regarding `intel_rapl`:

`[    7.259594] intel_rapl: no valid rapl domains found in package 0`

As per above, if you press escape it removes the error, displays the detailed boot log and starts the 
`A start job is running for Raise network interfaces` process which runs for about 5 minutes.

I tried removing 1.0.5 (`vagrant destroy` then `vagrant box remove geerlingguy/ubuntu1604 --box-version 1.0.5`) and 1.0.4 works fine.

My setup:

- Mac OS X 10.11.6 El Capitan
- Ansible 2.1.0.0
- Vagrant 1.8.6
- VirtualBox 5.1.8

**Comment by dimatteomaurizio** [comment]
> In this case, I'm 99% sure the issue is VirtualBox 5.0.28—I just updated the boxes to use 5.1.8 guest additions, so they will likely not work correctly with 5.0.x anymore. If you aren't able to upgrade VirtualBox to the latest version, you can install the previous Vagrant box version of geerlingguy/ubuntu1604 and it should hopefully work correctly.

I guess I put too much faith in auto-updates, I thought 5.0.28 was the latest.
Indeed updating to 5.1.8, deleting and re-downloading the latest box (just in case) solved the issue.

Thanks a lot :)

**Comment by geerlingguy** [comment]
Hmm... @keithcrooks due to caching/cloning, it could have still been using the same instance that was broken after you upgraded VirtualBox—can you try redownloading the box again like @dimatteomaurizio did?

**Comment by keithcrooks** [comment]
@geerlingguy You're right. My bad. I've tried updating the box to 1.0.5 again after updating VB to 5.1.8 and removing the cached versions of 1.0.5 and it works!

Thanks 👍

**Comment by geerlingguy** [comment]
Awesome! I'm going to close out this issue then. I can specify a required Vagrant and Ansible version, but I can't seem to do the same (forcibly) for VirtualBox... so it looks like I'll be seeing a bunch of these issues posted over the next month or two :D

**Comment by kbrownell** [comment]
Thank you!  This was so helpful.  Exactly my problem.  Worked right away, once I upgraded VirtualBox.

**Comment by koolstens** [comment]
Hi all,

I am new to vagrant.

I create a new machine using vagrant ini hashicorp/precise64.
When making vagrant up command i got timeout error. Is there other thing i must do please?

I am using the last 1.9.5 version on windows with oracle virtual box.

**Comment by geerlingguy** [comment]
@koolstens - That sounds like a Vagrant issue, not something that would be relevant to the Drupal VM issue queue. That issue can happen because of a large number of different issues. I'd suggest searching the Vagrant issue queue for your error and filing an issue there if you find it to be a bug: https://github.com/mitchellh/vagrant

**Comment by contactavishek** [comment]
My OS is Windows Ubuntu 16.04 and I have installed Oracle VM VirtualBox Manager 5.1.26 and vagrant 1.8.5
Even I am getting this with 'vagrant up':

Timed out while waiting for the machine to boot. This means that Vagrant was unable to communicate with the guest machine within the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that Vagrant had when attempting to connect to the machine. These errors are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly working and you're able to connect to the machine. It is a common problem that networking isn't setup properly in these boxes. Verify that authentication configurations are also setup properly, as well.

If the box appears to be booting properly, you may want to increase the timeout ("config.vm.boot_timeout") value.

I even tried adding the following to the Vagrantfile
config.vm.boot_timeout = 600

But still getting the same timeout error. Please suggest.

**Comment by robschuh** [comment]
Hi guys, I have exactly the same issue,  I am using the latest version for Ubuntu 16.04 64bits:
"Version 5.2.8 r121009)

"Timed out while waiting for the machine to boot".

**Comment by contactavishek** [comment]
I figured the best solution is starting the Oracle VM from the GUI interface and then when you use 'vagrant ssh' on the terminal, it will directly login to the VM.

**Comment by Ekiszzero** [comment]
Hi guys, I have the same issue. I am using Windows 7, VirtualBox 5.2.8, Git-2.16.2, Vagrant 2.0.3.

This error could be reproduced following these steps:
1.- git clone https://github.com/adafruit/esp8266-micropython-vagrant.git
2.- cd esp8266-micropython-vagrant
3.- vagrant up

** message **

Bringing machine 'default' up with 'virtualbox' provider...
==> default: Box 'ubuntu/trusty64' could not be found. Attempting to find and in              stall...
    default: Box Provider: virtualbox
    default: Box Version: >= 0
==> default: Loading metadata for box 'ubuntu/trusty64'
    default: URL: https://vagrantcloud.com/ubuntu/trusty64
==> default: Adding box 'ubuntu/trusty64' (v20180308.0.0) for provider: virtualb              ox
    default: Downloading: https://vagrantcloud.com/ubuntu/boxes/trusty64/version              s/20180308.0.0/providers/virtualbox.box
    default: Download redirected to host: cloud-images.ubuntu.com
    default:
==> default: Successfully added box 'ubuntu/trusty64' (v20180308.0.0) for 'virtu              albox'!
==> default: Importing base box 'ubuntu/trusty64'...
==> default: Matching MAC address for NAT networking...
==> default: Checking if box 'ubuntu/trusty64' is up to date...
==> default: Setting the name of the VM: esp8266-micropython-vagrant_default_152              1396620051_81314
==> default: Clearing any previously set forwarded ports...
Vagrant is currently configured to create VirtualBox synced folders with
the `SharedFoldersEnableSymlinksCreate` option enabled. If the Vagrant
guest is not trusted, you may want to disable this option. For more
information on this option, please refer to the VirtualBox manual:

  https://www.virtualbox.org/manual/ch04.html#sharedfolders

This option can be disabled globally with an environment variable:

  VAGRANT_DISABLE_VBOXSYMLINKCREATE=1

or on a per folder basis within the Vagrantfile:

  config.vm.synced_folder '/host/path', '/guest/path', SharedFoldersEnableSymlin              ksCreate: false
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 (guest) => 2222 (host) (adapter 1)
==> default: Running 'pre-boot' VM customizations...
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
Timed out while waiting for the machine to boot. This means that
Vagrant was unable to communicate with the guest machine within
the configured ("config.vm.boot_timeout" value) time period.

If you look above, you should be able to see the error(s) that
Vagrant had when attempting to connect to the machine. These errors
are usually good hints as to what may be wrong.

If you're using a custom box, make sure that networking is properly
working and you're able to connect to the machine. It is a common
problem that networking isn't setup properly in these boxes.
Verify that authentication configurations are also setup properly,
as well.

If the box appears to be booting properly, you may want to increase
the timeout ("config.vm.boot_timeout") value.

** end of message **


Would you please give me a hand?

Thanks.

**Comment by alika40** [comment]
I had a similar issue on Windows 8.1 64bits. I installed virtualbox version 5.1,  vagrant version 2.1.2 with ubuntu/ precise64. What solved my problem was "vagrant destroy" command after I had done a lot of things ranging from going into BIOS ---
 to enable VIRTUALIZATION TECHNOLOGY ---- to tweaking vagrantfile. I don't know how that could solve the problem but it sure did.

**Comment by naveenshankar61** [comment]
Facing the same issue in my Ubuntu-16.04.4 Environment.

**Comment by aritro90** [comment]
Just Check does your base environment VM/Machine even supporting virtualization... 
I installed the GUI version on Centos and when tried opening the console of the VM through VirtualBox, I could see the unsupported virtualization message. 
Fixing the virtualization in my environment fixed the issue. Maybe it can help someone, hence posting here.

**Comment by cp713a** [comment]
I have similar issue.  I just downloaded new vagrant version (from 2.1.2 to 2.2.6 and upgraded virtualbox (from 5.2 to 6.0)

I run into Timed out while waiting for the machine to boot at SSH author method: private key...etc...

Any help would really appreciate it.+
