### ISSUE TITLE
'postgresql_packages' is undefined

### ISSUE THREAD

**Issue by mgifford** [geerlingguy/drupal-vm#957]
I'm not sure why I am getting this error when I run `$ vagrant provision`:

```
TASK [geerlingguy.postgresql : Ensure PostgreSQL packages are installed.] ******
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "'postgresql_packages' is undefined"}
```

I can't find a solid reference to 'postgresql_packages', but have made sure that postgresql is installed:
$ brew install postgresql

It seems to be running:
$ brew services start postgresql
Service `postgresql` already started, use `brew services restart postgresql` to restart.

Where should this be defined?

This is on a Mac (obviously), but not sure where to go from here.  It was running find the last time I used DrupalVM.  Just did an update and now am rather stuck.

**Comment by geerlingguy** [comment]
@mgifford - This would be inside the VM itself... but there shouldn't be a condition when using Drupal VM where that variable isn't defined—you're using Vagrant and building a VM using one of the `geerlingguy/*` boxes, correct?

Here's the task in the Ansible role that defines the packages: https://github.com/geerlingguy/ansible-role-postgresql/blob/3cb4aaaa53b32a0a0df113db19777d4a72afcd83/tasks/variables.yml#L11-L14

Do you have something like `postgresql_packages: []` in your config.yml?

**Comment by mgifford** [comment]
1) Thanks again for being amazing.

2) I'm going to build this again with one of the geerlingguy/* boxes in the morning and will let you know. 

3) This is an older instance I'm building on. I'm pretty sure I haven't added anything special to the config.yml but will look.

**Comment by Razunter** [comment]
Same issue. Upgraded from 3.2 or older version of DrupalVM. Had to figure out how to upgrade Ansible, no mention of that in "breaking changes". But can't find workaround for this issue.

**Comment by antonyanimator** [comment]
I have the same issue, running the 14.04 vm

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/ansible-role-postgresql/issues/7

**Comment by geerlingguy** [comment]
Fixed upstream, going to fix by updating role deps here.

**Comment by mgifford** [comment]
Progress.  I'm getting different errors now. 

I ran `vagrant box update`

I made that ansible is at 2.2.0.0

I've updated the git repo for drupalvm

```
TASK [Install dependencies with composer require.] *****************************
failed: [drupalvm] (item=drupal/devel:1.x-dev) => {"changed": true, "cmd": ["/usr/bin/composer", "require", "drupal/devel:1.x-dev"], "delta": "0:01:36.563140", "end": "2016-11-03 14:32:34.734482", "failed": true, "item": "drupal/devel:1.x-dev", "rc": 2, "start": "2016-11-03 14:30:58.171342", "stderr": "Xdebug requires Zend Engine API version 220131226.\nThe Zend Engine API version 320151012 which is installed, is newer.\nContact Derick Rethans at http://xdebug.org/docs/faq#api for a later version of Xdebug.\n\n    1/7:\thttp://packagist.org/p/provider-latest$c0c6662ad794888ce8e68cd6ba32cfca086e18be85585d5a94b4abf1bcb595d1.json\n    2/7:\thttp://packagist.org/p/provider-2016-04$0ce7be03e55af28810c0959b9edcb9d1e53465c8ab4dba981394cc718ecaa5bb.json\n    3/7:\thttp://packagist.org/p/provider-2016-10$6b18182f23079270e1d8480b8f177b78671e465f68acf4745ceea94922504662.json\n    4/7:\thttp://packagist.org/p/provider-2016-01$eecfe1eb5893b58b57e271d36af9369f8768f15d2a93028c5d3337bbcf522969.json\n    5/7:\thttp://packagist.org/p/provider-2014$6f003b06f5c28bf4c4839e1d33d38f1f242d65c4f9b49b94576166464d9dc6d7.json\n    6/7:\thttp://packagist.org/p/provider-2016-07$22404a99ac2257b8c91e9fae9e02433a1c04f69f616807fb11e44e22a5c49e56.json\n    7/7:\thttp://packagist.org/p/provider-2015$f7e3729756d20a0f7120591096fd99b53e7aa071193f49599bed1556411385bf.json\n    Finished: success: 7, skipped: 0, failure: 0, total: 7\n./composer.json has been updated\n    1/7:\thttp://packagist.org/p/provider-latest$c0c6662ad794888ce8e68cd6ba32cfca086e18be85585d5a94b4abf1bcb595d1.json\n    2/7:\thttp://packagist.org/p/provider-2016-10$6b18182f23079270e1d8480b8f177b78671e465f68acf4745ceea94922504662.json\n    3/7:\thttp://packagist.org/p/provider-2014$6f003b06f5c28bf4c4839e1d33d38f1f242d65c4f9b49b94576166464d9dc6d7.json\n    4/7:\thttp://packagist.org/p/provider-2016-04$0ce7be03e55af28810c0959b9edcb9d1e53465c8ab4dba981394cc718ecaa5bb.json\n    5/7:\thttp://packagist.org/p/provider-2016-01$eecfe1eb5893b58b57e271d36af9369f8768f15d2a93028c5d3337bbcf522969.json\n    6/7:\thttp://packagist.org/p/provider-2015$f7e3729756d20a0f7120591096fd99b53e7aa071193f49599bed1556411385bf.json\n    7/7:\thttp://packagist.org/p/provider-2016-07$22404a99ac2257b8c91e9fae9e02433a1c04f69f616807fb11e44e22a5c49e56.json\n    Finished: success: 7, skipped: 0, failure: 0, total: 7\nLoading composer repositories with package information\nUpdating dependencies (including require-dev)\nYour requirements could not be resolved to an installable set of packages.\n\n  Problem 1\n    - The requested package drupal/devel could not be found in any version, there may be a typo in the package name.\n\nPotential causes:\n - A typo in the package name\n - The package is not available in a stable-enough version according to your minimum-stability setting\n   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.\n\nRead <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.\n\nInstallation failed, reverting ./composer.json to its original content.", "stdout": "", "stdout_lines": [], "warnings": []}
	to retry, use: --limit @/Users/mikegifford/drupal-vm/provisioning/playbook.retry

PLAY RECAP *********************************************************************
drupalvm                   : ok=174  changed=2    unreachable=0    failed=1   

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

Seems the problem boils down to "The requested package drupal/devel could not be found in any version".

**Comment by danepowell** [comment]
For anyone looking for a fix to the original problem here... basically the solution is to update DrupalVM to 3.5.1. It doesn't look like there was ever an upstream "fix" to Ansible.

**Comment by benjifisher** [comment]
> GitHub doesn't seem to like the long lines.

I think the long lines are fine, but maybe it is hard to tell because your browser does not show a scrollbar unless you are actively scrolling.  Is this a "feature" of recent versions of macOS?
