### ISSUE TITLE
Could not find the requested service "firewall"

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#958]
On macOS Sierra, running VirtualBox 5.1.8 and Vagrant 1.8.6, with Ansible 2.2.0, a fresh Drupal VM provision is bailing with:

```
TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************

PLAY RECAP *********************************************************************
drupalvm                   : ok=10   changed=6    unreachable=0    failed=1
```

This looks like it _could_ be related to #829, but I'm doing a little more investigation. For now, the simplest fix is to stay on Ansible 2.1.x (e.g. `pip install ansible==2.1`) instead of installing Ansible 2.2.x... something's changed with Ansible's `service` module that must be causing this issue.

On Windows, the issue can be caused by non-UNIX line endings on the firewall service file (see #829 comments), but on Mac/Linux (and on Windows in general), it looks like Ansible 2.2's `service` module gets snagged, but _only on Ubuntu 16.04_, which leads me to believe something is missing for systemd.

## Temporary Fixes

  1. Switch back to Ansible 2.1.x (e.g. `pip install ansible==2.1`)
  2. If you see this error, run `vagrant reload --provision` to restart the VM and continue provisioning)

**Comment by geerlingguy** [comment]
See also: https://github.com/geerlingguy/ansible-role-firewall/issues/17

**Comment by geerlingguy** [comment]
Ha... then since the firewall is set up but not configured properly... it looks like SSH is being blocked, so fix #2 might not work that great. Or it could be an issue with my latest iteration of the `geerlingguy/ubuntu1604` box, or with Vagrant 1.8.6. Or VMware 8.5. Grr.

**Comment by enapthine** [comment]
Getting same error. :( Tried destorying box, copying from working config, etc, no luck.

`TASK [geerlingguy.firewall : Ensure the firewall is enabled and will start on boot.] ***
fatal: [clbs]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'firewall'\": "}

RUNNING HANDLER [geerlingguy.firewall : restart firewall] **********************
	to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
clbs                       : ok=10   changed=5    unreachable=0    failed=1   
`

**Comment by enapthine** [comment]
After using `vagrant reload --provision` - I'm getting..

```
TASK [geerlingguy.postgresql : Ensure PostgreSQL packages are installed.] ******
fatal: [clbs]: FAILED! => {"failed": true, "msg": "'postgresql_packages' is undefined"}
	to retry, use: --limit @/vagrant/provisioning/playbook.retry

PLAY RECAP *********************************************************************
clbs                       : ok=106  changed=3    unreachable=0    failed=1   

```

**Comment by geerlingguy** [comment]
@enapthine - I opened https://github.com/geerlingguy/ansible-role-postgresql/issues/7 for that issue—it seems I might need to adjust a few things in a few different roles for Ansible 2.2+ compatibility.

**Comment by geerlingguy** [comment]
I have a fix for this in the `geerlingguy.firewall` role. Will continue testing.

**Comment by geerlingguy** [comment]
See upstream issue: https://github.com/geerlingguy/ansible-role-firewall/pull/22

**Comment by geerlingguy** [comment]
Heh... now that I fixed the firewall issue, I hit the same thing with the mailhog role:

```
TASK [geerlingguy.mailhog : Ensure mailhog is enabled and will start on boot.] *
fatal: [drupalvm]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'mailhog'\": "}
```

Will open another upstream role.

**Comment by geerlingguy** [comment]
And now that I fixed mailhog, I'm getting:

```
TASK [geerlingguy.java : Ensure Java is installed.] ****************************
fatal: [drupalvm]: FAILED! => {"failed": true, "msg": "'java_packages' is undefined"}
```

Ansible 2.2 is like a hydra for all my roles with custom init scripts :P

**Comment by geerlingguy** [comment]
Issue for Java role: https://github.com/geerlingguy/ansible-role-java/issues/26
