### ISSUE TITLE
Create /etc/hosts aliases for every configured vhost

### ISSUE THREAD

**Issue by phenaproxima** [geerlingguy/drupal-vm#96]
Right now, Vagrant will create a single entry in my hosts file, pointing to my Drupal VM. This is all well and good, but I have several vhosts defined in config.yml, and they do not get hosts entires. Is there any way, or can there be any way, for all of my defined vhosts to get automatically listed in /etc/hosts?

**Comment by geerlingguy** [comment]
It looks like this may be possible using https://github.com/cogitatio/vagrant-hostsupdater/issues/35 — the syntax would be:

```
config.hostsupdater.aliases = [sites]
```

I'll see how simple it is to transform the array of domains from `config.yml` to grab all the hosts and put them into that array (iff hostsupdater is available).

**Comment by phenaproxima** [comment]
That syntax does indeed work for me, so if you can add the ability to pull the aliases directly from config.yml, that would be absolutely boss. :)
