### ISSUE TITLE
Composer install is not run inside new Drupal installation

### ISSUE THREAD

**Issue by justageek** [geerlingguy/drupal-vm#964]
I ran the quick start for drupal 8, only adding the solr extra, and apparently none of the composer installs were run, there is no vendor folder with all the symfony code, etc.  I also tried to install the search_api_solr, running its composer install, and it still cannot find the required Solarium files, so something is just broken with autoloading classes.

**Comment by geerlingguy** [comment]
Can you post your config.yml customizations? With the default install, it seems it works okay if I use the included example composer file.

**Comment by geerlingguy** [comment]
Closing for now, as it's been a month without more info. Please let me know if this is still an issue for you.
