### ISSUE TITLE
Docs update or change to a role?

### ISSUE THREAD

**Issue by ccjjmartin** [geerlingguy/drupal-vm#966]
## Description of bug:
I ran into a bug and am not sure if this should be a documentation update or an update to one of the roles related to this project.  When using the latest version of DrupalVM 3.5.0 and geerlingguy/ubuntu1404 and downgrade to PHP 5.6 (using the latest instructions).  I ran into a problem where the site would run just fine but drush wouldn't connect.  I ended up coming across this article:

https://www.drupal.org/node/1058800

In which case the last comment gave me the answer I needed, I had to run:

sudo ln -sfn /usr/bin/php5.6 /etc/alternatives/php

And then drush started using php5.6 instead of php7.0 which was the original value:

$ ls -la /etc/alternatives/php
lrwxrwxrwx 1 root root 15 Nov  3 05:07 /etc/alternatives/php -> /usr/bin/php7.0

Seems like when we downgrade to PHP5.6 that value should be changed too?

**Comment by geerlingguy** [comment]
@ccjjmartin - When you downgraded—had you already run `vagrant up` once? Or was this on a fresh new VM? On a new VM it would be a bug if you had changed everything out for PHP 5.6 and the build installed both 7.0 and 5.6.

**Comment by thom8** [comment]
(linking) - https://github.com/geerlingguy/drupal-vm/pull/714

**Comment by ccjjmartin** [comment]
@geerlingguy Your right, I tried it again from a fresh install and found out that when it is installed fresh it uses the right version of PHP.  I must have switched versions after it was already running.  Not sure if I should leave this open or not.  Feel free to close this if this works as designed.

**Comment by geerlingguy** [comment]
@ccjjmartin - For now it works as designed—sooner or later we'll get #714 merged in and it will make switching versions a bit simpler.

**Comment by oxyc** [comment]
#1043 purges the old packages which also causes `/etc/alternatives` to change. Once merged this is fixed.
