### ISSUE TITLE
drush runserver port 8888 not accessible from outside VM

### ISSUE THREAD

**Issue by justinlevi** [geerlingguy/drupal-vm#969]
I need to be able to access a site running from within the VM through `drush rs --default-server=127.0.0.1:8888`

I've tried a few things and can't seem to get it to work. 
---

1. I've added `8888` to the firewall_allowed_tcp_ports

```
firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "81"
  - "443"
  - "4444"
  - "8025"
  - "8080"
  - "8443"
  - "8983"
  - "9200"
  - "8888"
  - "6081"
```

2. I've tried updating the Virtual Box Port Forwarding to add 8888 as well. I've tried entering the IP address as well as leaving them blank per this blog post: http://www.howtogeek.com/122641/how-to-forward-ports-to-a-virtual-machine-and-use-it-as-a-server/

![screen shot 2016-11-03 at 2 56 32 pm](https://cloud.githubusercontent.com/assets/1117989/20012987/e5f4c3d6-a287-11e6-84d4-c04540cb9ebb.jpg)
![screen shot 2016-11-04 at 12 08 03 pm](https://cloud.githubusercontent.com/assets/1117989/20012986/e5f30e6a-a287-11e6-9a27-ea8b96dcb12f.jpg)

Here's what my `netstat` looks like from within the VM which seems correct to me. I've also stopped the apache server not that it should matter though. 

![screen shot 2016-11-04 at 12 08 23 pm](https://cloud.githubusercontent.com/assets/1117989/20013100/4e86bc60-a288-11e6-9633-78ccb084d978.jpg)

Ultimately I'm trying to write some behat tests that verify varnish is clearing cache correctly and I'm trying to setup an environment that will mirror what I'll have running up on Travis-CI. 

Thanks for any direction!

**Comment by geerlingguy** [comment]
@justinlevi - After adding the port to the allowed ports, did you run `vagrant provision` again?

Also, I'm not seeing :8888 inside the netstat output.

Finally, what's the output of `sudo iptables -L` inside the VM?

**Comment by justinlevi** [comment]
@geerlingguy - Yeah, I ran `vagrant provision` after adding `8888` and `6081` (varnish) ports to the config.yml. 

Here's the netstat output showing :8888 from within the VM 

```
vagrant@webny:/var/www/webny/docroot$ sudo netstat -tulnp | grep 127.0.0.1
tcp        0      0 127.0.0.1:8888          0.0.0.0:*               LISTEN      6911/php        
tcp        0      0 127.0.0.1:6082          0.0.0.0:*               LISTEN      6693/varnishd   
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      6461/php-fpm.conf)
tcp        0      0 127.0.0.1:11211         0.0.0.0:*               LISTEN      1118/memcached  
udp        0      0 127.0.0.1:926           0.0.0.0:*                           750/rpc.statd   
udp        0      0 127.0.0.1:11211         0.0.0.0:*                           1118/memcached  

```

Here's the output from `sudo iptables -L` from within the VM as well. 

```
vagrant@webny:/var/www/webny/docroot$ sudo iptables -L
Chain INPUT (policy ACCEPT)
target     prot opt source               destination         
ACCEPT     all  --  anywhere             anywhere            
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:ssh
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:smtp
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:81
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:https
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:4444
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8025
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:http-alt
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8443
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8983
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:9200
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:8888
ACCEPT     tcp  --  anywhere             anywhere             tcp dpt:6081
ACCEPT     icmp --  anywhere             anywhere            
ACCEPT     udp  --  anywhere             anywhere             udp spt:ntp
ACCEPT     all  --  anywhere             anywhere             state RELATED,ESTABLISHED
DROP       all  --  anywhere             anywhere            
```

Here's what I'm seeing running `ifconfig` as well: 

```
vagrant@webny:/var/www/webny/docroot$ ifconfig
eth0      Link encap:Ethernet  HWaddr 08:00:27:96:5c:c8  
          inet addr:10.0.2.15  Bcast:10.0.2.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:fe96:5cc8/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:19135 errors:0 dropped:0 overruns:0 frame:0
          TX packets:10517 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:9072802 (9.0 MB)  TX bytes:1102727 (1.1 MB)

eth1      Link encap:Ethernet  HWaddr 08:00:27:b9:e6:0e  
          inet addr:192.168.88.90  Bcast:192.168.88.255  Mask:255.255.255.0
          inet6 addr: fe80::a00:27ff:feb9:e60e/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:89269 errors:0 dropped:0 overruns:0 frame:0
          TX packets:81485 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:27367448 (27.3 MB)  TX bytes:12535860 (12.5 MB)

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:386 errors:0 dropped:0 overruns:0 frame:0
          TX packets:386 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:178710 (178.7 KB)  TX bytes:178710 (178.7 KB)

```

I'm waaay outside of my comfort zone here so hoping you can help shed some light on the issue. Could this have something to do with a loopback issue? 


No matter what I seem to try I get the following error when I try to curl from my host machine and try to connect the php server running at `127.0.0.1:8888` - I can connect if I run the php server on 0.0.0.0 but that is not how `BLT` runs behat tests on travis by default. 

----

⚡ curl -I 192.168.88.90:88
curl: (7) Failed to connect to 192.168.88.90 port 88: Operation timed out

----
Note: the above is just me trying to configure a different port `88` on my host machine versus the `8888` on the guest port via VirtualBox. 

![screen shot 2016-11-08 at 11 33 22 am](https://cloud.githubusercontent.com/assets/1117989/20107627/36997de6-a5a7-11e6-9711-edc42990ffd4.jpg)
 

Unless I'm off my rocker, distinct possibility, then I feel like this should be possible.

**Comment by geerlingguy** [comment]
@justinlevi - Can you try `curl -I 192.168.88.90:8888`? VirtualBox should allow the port through that virtual networked device, and since it's listening and open on the firewall in the VM, it seems like that should work...

**Comment by justinlevi** [comment]
@geerlingguy Thanks for getting back to me. Unfortunately, it just seems to hang :( 

```
⚡ curl -I 192.168.88.90:88
Seems like it just hangs...curl: (7) Failed to connect to 192.168.88.90 port 88: Operation timed out
```

Screen capture attached. 
![screen shot 2016-11-08 at 3 04 07 pm](https://cloud.githubusercontent.com/assets/1117989/20115014/a4f349a8-a5c4-11e6-9774-dfa3a902f6d2.jpg)



![screenflow](https://cloud.githubusercontent.com/assets/1117989/20115251/8b0530a0-a5c5-11e6-9bda-c25a5ac75b17.gif)

**Comment by geerlingguy** [comment]
@justinlevi - But can you try connecting to `8888` (not `88`) — from your host. E.g. _not_ logged into the VM, run the exact command `curl -I 192.168.88.90:8888` — from the above output, it looks like you're trying `88`.

(Make sure drush is running inside the VM during this time).

**Comment by justinlevi** [comment]
@geerlingguy Sorry, I should have been more clear as I changed the port mapping on the Virtual Box settings from `8888` on both the host and guest  to `88` on the host and `8888` on the guest - just to try something different...

Here's the screen grab of how I have my settings right now with drush runserver running inside the VM on port `8888` via $ `drush rs --default-server=127.0.0.1:8888`.

![screen shot 2016-11-09 at 8 32 41 am](https://cloud.githubusercontent.com/assets/1117989/20140061/1a96724c-a657-11e6-9a28-cfab11437e68.jpg)

Back at a shell terminal on my host, here's what I see: 

$ `curl -I 192.168.88.90:8888`
curl: (7) Failed to connect to 192.168.88.90 port 8888: Connection refused

$ `curl -I 192.168.88.90:88`
curl: (7) Failed to connect to 192.168.88.90 port 88: Operation timed out

![screen shot 2016-11-09 at 8 35 50 am](https://cloud.githubusercontent.com/assets/1117989/20140133/8c1b2a20-a657-11e6-93a5-959a60080a6b.jpg)


Just to show that drush runserver is working, if I then ssh into the guest VM, via another ssh session, and do a $ `curl 127.0.0.1:8888`, here's what I see: 

![screen shot 2016-11-09 at 8 38 24 am](https://cloud.githubusercontent.com/assets/1117989/20140196/ec9de5a4-a657-11e6-8368-3ce531a12e9a.jpg)

Note the HTML returned in my bottom terminal and the new "log" entry on the terminal window where the drush php server is running... 

Thanks for your time on this. I really appreciate it!

**Comment by geerlingguy** [comment]
I wonder if Drush _only_ listens on localhost, and not on any network interface. I've never used it's runserver command. I'll have to do some testing later.

**Comment by justinlevi** [comment]
I don't think so because if I run $ `drush rs --default-server=0.0.0.0:8888` I can access that fine from the host machine using an the IP Address. 

Seems like it has something to do with the 127.0.0.1 address binding to the php server and not being accessible but again, I'm talking waaaaaay outside my comfort zone here.

**Comment by justinlevi** [comment]
FYI - I was able to get my Varnish behat tests up and running on Travis testing with the `0.0.0.0:8888` solution above so this might fall into the "academic exercise" territory at this point. Would love to know why, but I fully understand if you have your hands full and want to close this out. 

This is clearly an edge case that might not affect or benefit that many other people.

**Comment by geerlingguy** [comment]
> I don't think so because if I run $ drush rs --default-server=0.0.0.0:8888 I can access that fine from the host machine using an the IP Address.

Ah, so what happens is if you bind the server to 127.0.0.1, then it's only available via localhost (local to that machine). VirtualBox's network that it sets up between the VM and your host machine is a different network than 127.0.0.1, which explains why it won't work there. When you run `ifconfig`, you can see three interfaces, `eth0`, `eth1`, and `lo`.

  - If you use 127*, it's running on the local (inside-VM-only) interface.
  - If you use 10*, it will be mappable via VirtualBox, so if you did `--default-server=10.0.2.15:8888` then mapped to port 88, your curl tries would succeed, but only using `curl 10.0.2.15:88`.
  - If you run the server on `192.168.88.90`, it's accessible via that IP.
  - If you run the server on `0.0.0.0`, it's accessible via localhost, 10*, and 192* (any network interface).

When you run it on 0.0.0.0, then it's running on all available network interfaces.

This makes sense now. Thanks for sticking with it!
