### ISSUE TITLE
Include varnish in DrupalVM

### ISSUE THREAD

**Issue by davidlukac** [geerlingguy/drupal-vm#97]
I would like my dev environment to match production setup, so I would welcome Varnish as _extra_ option as well. Would you consider adding it to VM?

**Comment by geerlingguy** [comment]
@davidlukac - Definitely! I have a `geerlingguy.varnish` role and already have it integrated into a sister project, [Acquia Cloud VM](https://github.com/geerlingguy/acquia-cloud-vm). Shouldn't be too difficult to at least get it installed. I'm not yet sure how I'd do the configuration — maybe have a basic VCL template that gets configured for all site docroots, then allow that template to be overridden with a different template path, based on a variable in `config.yml`?

**Comment by davidlukac** [comment]
Great to see the Varnish is planned! I'll definitely check out the Acquia Cloud VM as well (that's the environment we're trying to get close to on local machines :-)).

Default VCL temp. + override seems as a reasonable approach.

**Comment by geerlingguy** [comment]
Working on this now.

**Comment by geerlingguy** [comment]
Added Wiki page, about to commit the addition.
