### ISSUE TITLE
macOS vagrant failed to connect via ssh 

### ISSUE THREAD

**Issue by iainhouston** [geerlingguy/drupal-vm#979]
Jeff have you any idea why this should suddenly start happening? I can't `vagrant ssh` or provision.

It may be that I haven't been using my drupal-vm since upgrading to Sierra.  

In any case I uninstalled vagrant; reinstalled it (removed the embedded `curl`); reinstalled vagrant guest addition host installer plugins; upgraded both ansible and virtualbox to most current; cloned `drupal-vm`; `diff`ed my `config.yml` with your most recent `default.config.yml` and edited a few variable names etc. but still I can't `vagrant ssh` or provision.

Typical failure:

    GuestOSType="Linux26_64"
    GuestAdditionsRunLevel=2
    GuestAdditionsVersion="5.1.8 r111374"
    GuestAdditionsFacility_VirtualBox Base Driver=50,1478691905699
    GuestAdditionsFacility_VirtualBox System Service=50,1478692033187
    GuestAdditionsFacility_Seamless Mode=0,1478691905699
    GuestAdditionsFacility_Graphics Mode=0,1478691905699
    DEBUG subprocess: Waiting for process to exit. Remaining to timeout: 32000
    DEBUG subprocess: Exit status: 0
    DEBUG virtualbox_5_0:   - [1, "ssh", 2222, 22]
    DEBUG ssh: Checking key permissions: /Users/iainhouston/.vagrant.d/insecure_private_key
     INFO interface: detail: Running ansible-playbook...
     INFO interface: detail:     drupal7vm: Running ansible-playbook...
        drupal7vm: Running ansible-playbook...
     INFO subprocess: Starting process: ["/usr/local/bin/ansible-playbook", "--connection=ssh", "--timeout=30", "--limit=drupal7vm", "--inventory-file=/Users/iainhouston/Drupal7Platforms/drupal-vm/.vagrant/provisioners/ansible/inventory", "--extra-vars={\"config_dir\":\"/Users/iainhouston/Drupal7Platforms/drupal-vm\"}", "/Users/iainhouston/Drupal7Platforms/drupal-vm/provisioning/playbook.yml"]
    DEBUG subprocess: Command not in installer, not touching env vars.
     INFO subprocess: Command not in installer, restoring original environment...
    DEBUG subprocess: Selecting on IO
    DEBUG subprocess: stdout: 
    PLAY [all] *********************************************************************
     INFO interface: detail: 
    PLAY [all] *********************************************************************

    PLAY [all] *********************************************************************
    DEBUG subprocess: stdout: 
    TASK [setup] *******************************************************************
     INFO interface: detail: 
    TASK [setup] *******************************************************************

    TASK [setup] *******************************************************************
    DEBUG subprocess: stdout: fatal: [drupal7vm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}
     INFO interface: detail: fatal: [drupal7vm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}

    fatal: [drupal7vm]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Connection timed out during banner exchange\r\n", "unreachable": true}

**Comment by WiseUA** [comment]
Try to enable virtualization.

**Comment by geerlingguy** [comment]
@iainhouston - Can you try VirtualBox 5.1.6? It sounds like a lot of people have trouble with networking in 5.1.8...

**Comment by iainhouston** [comment]
Thanks Jef: going back to Virtualbox version 5.1.6 r110634 (Qt5.5.1) seems to have fixed it. After I removed and reinstalled Vagrant 1.8.7
