### ISSUE TITLE
Use more consistent defaults for local testing domain names

### ISSUE THREAD

**Issue by nerdstein** [geerlingguy/drupal-vm#98]
Proposing xhprof.drupaltest.dev, phpmyadmin.drupaltest.dev, pimpmylog.drupaltest.dev in lieu of the current implementation.

Also should simplify the hosts file if all *.drupaltest.dev namespaces pointing to the VM

**Comment by geerlingguy** [comment]
Even better, maybe it's time to standardize on `drupalvm.dev` as the base domain... The `drupaltest.dev` domain was just what I used back when this whole project was not even a blip on the radar.

**Comment by nerdstein** [comment]
I agree

**Comment by geerlingguy** [comment]
How about:

  - drupalvm.dev
  - xhprof.drupalvm.dev
  - pimpmylog.drupalvm.dev

**Comment by geerlingguy** [comment]
Fixed!

**Comment by nerdstein** [comment]
@geerlingguy did we apply the same conventions for solr?

**Comment by nerdstein** [comment]
And, should we apply them to anything else?

**Comment by geerlingguy** [comment]
Currently, the main way to access Solr in the VM would be to just connect locally through Drupal (so no need for a domain), or via IP or any other domain with the port (e.g. `http://drupalvm.dev:8983/`).

Similarly, with phpMyAdmin, you'd just access an existing domain with `/phpmyadmin`. (Though we might also remove phpMyAdmin and use Adminer instead, see: https://github.com/geerlingguy/drupal-vm/pull/111).
