### ISSUE TITLE
Drush "site-install needs a higher bootstrap" (Vagrant 1.8.7, VirtualBox 5.1.8, Windows 7)

### ISSUE THREAD

**Issue by GhostInTheMachinesAtTSBVI** [geerlingguy/drupal-vm#982]
Getting an error when bringing Drupal VM up on a Windows 7 machine.

I piped the verbose debug output to a file that I am going to attach here and I am going to list what I found by doing a find on this file  for Ansible:

```
TASK [Check if site is already installed.] *************************************
ok: [drupalvm]

TASK [Configure database correctly if using PostgreSQL.] ***********************
skipping: [drupalvm]

TASK [Install Drupal with drush.] **********************************************
fatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:01.107022", "end": "2016-11-11 19:47:13.171638", "failed": true, "rc": 1, "start": "2016-11-11 19:47:12.064616", "stderr": "Command site-install needs a higher bootstrap level to run - you will    [error]\nneed to invoke drush from a more functional Drupal environment to run\nthis command.\nThe drush command 'site-install standard' could not be executed.         [error]", "stdout": "", "stdout_lines": [], "warnings": []}
```

I can't really see anything obvious that tells me why the process is failing.  Maybe someone can tell from the rest of the text.

[drupalVMerror.txt](https://github.com/geerlingguy/drupal-vm/files/586654/drupalVMerror.txt)

**Comment by geerlingguy** [comment]
It looks like the error is in the site install step: `Command site-install needs a higher bootstrap level to run - you will need to invoke drush from a more functional Drupal environment to run\nthis command.`

Can you run `vagrant provision` again and see if that fixes it?

Also, is this a plain/fresh install, or are you using an existing codebase? What kind of changes have you made in your `config.yml` (if any)?

**Comment by GhostInTheMachinesAtTSBVI** [comment]
I already had vagrant and virtual box installed.  All I had to do was download and unzip the DrupalVM from GitHub inside a folder I have setup.

I have tried destroying and re-running the vagrant up as well as using vagrant provision on this instance.  I also completely deleted the folders both in my working area as well as in the VirtualBoxVM folder.

The only changes I made to the vagrant file were from the following instructions:

2 - Build the Virtual Machine
Download this project and put it wherever you want.
(Optional) Copy default.config.yml to config.yml and modify it to your liking.
Create a local directory where Drupal will be installed and configure the path to that directory in config.yml (local_path, inside vagrant_synced_folders).
Open Terminal, cd to this directory (containing the Vagrantfile and this README file).
Type in vagrant up, and let Vagrant do its magic.

**Comment by geerlingguy** [comment]
Did you make any changes to `config.yml` though?

**Comment by GhostInTheMachinesAtTSBVI** [comment]
Yes,

Item 3. in the quick start directions says to:
Create a local directory where Drupal will be installed and configure the path to that directory in config.yml (local_path, inside vagrant_synced_folders).

That is the only change I made in config.yml

**Comment by GhostInTheMachinesAtTSBVI** [comment]
I deleted the box and all of the files and installed a fresh copy to test if there were any issues with the config.yml and it appears the error is the same either way.

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.

I am including the entire text of the install but I did a search on the file to see if it had the line that you mentioned above (which it does)

[0m[0m[0;31mfatal: [drupalvm]: FAILED! => {"changed": true, "cmd": ["/usr/local/bin/drush", "site-install", "standard", "-y", "--site-name=Drupal", "--account-name=admin", "--account-pass=admin", "--db-url=mysql://drupal:drupal@localhost/drupal"], "delta": "0:00:07.642329", "end": "2016-11-15 19:40:49.172734", "failed": true, "rc": 1, "start": "2016-11-15 19:40:41.530405", "stderr": **"Command site-install needs a higher bootstrap level to run** - you will    [error]\nneed to invoke drush from a more functional Drupal environment to run\nthis command.\nThe drush command 'site-install standard' could not be executed.   

I performed my vagrant up command in a command window with admin rights so it is unclear what the higher bootstrap request is asking for.
[vagrantup.txt](https://github.com/geerlingguy/drupal-vm/files/592987/vagrantup.txt)

**Comment by oxyc** [comment]
> TASK [Generate Drupal project with composer package.] **************************
skipping: [drupalvm]

Seems to be the issue. This task should not be skipped. What did you change the `local_path` value to? There seems to be an `index.php` file inside a `web/` directory in that path.

**Comment by geerlingguy** [comment]
@oxyc - Good catch!

**Comment by GhostInTheMachinesAtTSBVI** [comment]
On the laster iteration,  I left the vagrant share as the default (not touching anything) thinking it would just create the directory if it did not exist.

Initially my intent was to have both the vagrant file and the shared folder on our Development share which would allow another developer and me to modify the files jointly.  Unfortunately I don't know how to open a command window in that directory so I moved everything over to my local C drive

**Comment by GhostInTheMachinesAtTSBVI** [comment]
I can get this to work by deleting everything in the VirtualBoxVM folder, the drupal-vm-master folder and re-install everything locally on my C drive (network shares also make the script fail). 

I had hoped that using DrupalVM would allow me and another developer to share the Drupal folder and make changes that would be seen in the DrupalVM.

After re-reading the documentation I see that the drupal folder is supposed to be deleted before re-creating the box and in reality all related folders need to be removed for it to start up without errors.

**Comment by geerlingguy** [comment]
@GhostInTheMachinesAtTSBVI - Ah, yes. On Windows, it's going to cause trouble if you try using a folder on a network share or on a non-internal volume. Sometimes you can hack things together to get that to work, but not always.

I would try with the basic configuration first—just share a local folder. See if you can get that working, then consider trying to get that codebase shared with another dev. Usually teams would use Git to keep a codebase in sync while allowing different developers to work on different things.

**Comment by GhostInTheMachinesAtTSBVI** [comment]
Yes, we were using Git originally but then it looked like the shared folder capabilities would eliminate the need for it using Vagrant to spin up different environments that always used the same source files from the shared folder that was outside the VM.

I am thinking I might be able to rig something up by injecting a shell script to update the custom drupal folders at the end of the vagrant script where it will hopefully not generate any errors.
