### ISSUE TITLE
How to find out Drupal VM version?

### ISSUE THREAD

**Issue by ArtuGit** [geerlingguy/drupal-vm#983]
Sorry, I have not found any information about current version in the files.

**Comment by geerlingguy** [comment]
There's currently no file that stores a version string in it (ala CHANGELOG/etc). You'd either need to be tracking Drupal VM in Git or as a Composer dependency, or you can look at the versions section of the README.txt and roughly match it to a particular version (e.g. https://github.com/geerlingguy/drupal-vm/blob/master/README.md#1---install-vagrant-and-virtualbox).

**Comment by geerlingguy** [comment]
I'm considering adding a CHANGELOG.md file or some other indicator of project history... I just have avoided it so far due to the extra maintenance overhead (even with scripts, it's an additional step in tagging any new releases...).

**Comment by ArtuGit** [comment]
It will be fine because the ways which you have been described  are not trivial.

**Comment by geerlingguy** [comment]
Working on a changelog for the next tagged release...

**Comment by ArtuGit** [comment]
Thank you.
