### ISSUE TITLE
How to setup, configure and use drupal vm with platform.sh?

### ISSUE THREAD

**Issue by webprogrammierer** [geerlingguy/drupal-vm#984]
platform.sh is a good platform to develop drupal sites on using tools like git, bitbucket, drush and more.

I am a platform.sh beginner and want to know how I can setup my drupal vm to use it together with platform.sh or:
How can I begin using platform.sh on my drupal vm envirenment? (Windows 10).
What are the first steps to get started?

Thank you very much.

**Comment by oxyc** [comment]
platformsh has an example of how to use drupal-composer with their platform. This fits quite well with Drupal VM as drupal-composer is the default project setup.

https://github.com/platformsh/platformsh-example-drupal8

It can be a bit challenging to set up for a beginner but the repo above is probably the best reference.

**Comment by geerlingguy** [comment]
I'll leave this open a little longer if anyone else using Platform.sh wants to chime in (e.g. help with defaults, workflow, etc.)—but as I don't use it myself, but know it has most of the common bits of infrastructure that are similar to what's in Drupal VM, I would suggest that the way you use Drupal VM with Platform.sh would be similar to how you use it with Acquia Cloud, AWS, Pantheon, etc.

**Comment by webprogrammierer** [comment]
oxyc and geerlingguy thank you for the example, maybe I can use this later on.
But at the moment I want to find out the following:

On platform.sh I created a new project, I chose Drupal 7.
I can access the new Drupal 7 site directly on platform.sh (webaccess with special subdomains, this is a platform.sh feature).

The next step is to clone the code using git or cli, the platform.sh command line interface.

I am working on Windows 10 using Drupal VM.

But how can I start using platform.sh on this Drupal VM? 
Or do I have to install another linux VM (using vagrant)? I tried [this tutorial](http://awebfactory.com/node/537) but it does not work (there is no simple way to get run ansible on windows).

So I am still at the beginning:

Can I use Drupal VM (start with "vagrant up" and "vagrant ssh") to use platform.sh?
How can I do this? What are the first steps? Can you tell me 5-8 steps how to do so?

Thank you.

**Comment by oxyc** [comment]
If you have all your code checked into git and just clone it you can configure drupal vm with a local drupal codebase. http://docs.drupalvm.com/en/latest/deployment/local-codebase/

**Comment by webprogrammierer** [comment]
Yes, thank you. I can use synched folders in order to edit the files on my windows environment.

Are there any other benefits with Drupal VM when developing sites on platform.sh?

**Comment by webprogrammierer** [comment]
> I would suggest that the way you use Drupal VM with Platform.sh would be similar to how you use it with Acquia Cloud, AWS, Pantheon, etc.

I am not familiar with this, are there any tips, hints or tutorials?

**Comment by geerlingguy** [comment]
@webprogrammierer - It sounds like you're comparing developing a Drupal website using a Platform.sh development environment (in the cloud) vs. on your local computer using Drupal VM.

Basically, Drupal VM lets you run everything that Platform.sh runs, but it's all running on your local computer, and technically you could work on the website offline not connected to the internet at all.

To work on a website where you do some development in Drupal VM then push it up to your Platform.sh site, you would usually do development, then update the git code repository, then push changes in git up to Platform.sh, then run updates and clear caches on Platform.sh.

I have a feeling you might want to read through some guides to using Git for Drupal development before diving straight into running Drupal VM:

  - [Building a Drupal site with Git](https://www.drupal.org/node/803746)
  - [How to create a Git repository and add a complete Drupal site to it](https://buildamodule.com/video/change-management-and-version-control-installing-git-and-working-on-the-command-line-how-to-create-a-git-repository-and-add-a-complete-drupal-site-to-it)

You might also want to ask Platform.sh's support about how you can more easily work with the code that runs your Platform.sh-hosted websites.

**Comment by vasike** [comment]
With composer
into your.config.yml (loca.config.yml) file (composer_global_packages)
```
composer_global_packages:
  .....
  - { name: platformsh/cli }
```

of course you need to add your ssh key from the vm to platform.sh account

**Comment by geerlingguy** [comment]
@vasike - Also note that if you have `ssh-agent` running and use `ssh-add -K` to add your local identities on your host, when you run `vagrant ssh`, Vagrant is configured by Drupal VM to use your loaded keys inside the VM as well. It makes it easy to authenticate to things whether you're in or out of the VM (and it even works on Windows, if you're using a CLI that has ssh-agent, or running Pageant!).

**Comment by danbohea** [comment]
Currently, if you install the Platform.sh CLI via `composer_global_packages` you'll get a Git dependency error when trying to use `platform` to interact with your remote Platform repos (e.g. `platform get`). This wasn't always the case but it's not a version difference between CLI release either - I've let the guys at Platform.sh know. I have found that installing the platform cli without composer gets around this.

**Comment by geerlingguy** [comment]
@danbohea - Good to know! Hopefully that can get sorted so it can be managed via Composer more easily.
