### ISSUE TITLE
The box 'geerlingguy/ubuntu1404' could not be found.

### ISSUE THREAD

**Issue by petiar** [geerlingguy/drupal-vm#985]
Could you please fix the documentation so the installation of the DrupalVM with PHP 5.6 does not fail on the very first line? The error being `The box 'geerlingguy/ubuntu1404' could not be found or
could not be accessed in the remote catalog.` renders the documentation for PHP 5.6 completely useless.

It worked with the `puphpet/ubuntu1404-x64` box.

Thanks.

Vagrant 1.8.7
OSX 10.12.1
VirtualBox 5.0.16

**Comment by geerlingguy** [comment]
@petiar - Please see: https://github.com/geerlingguy/drupal-vm/issues/981

There's a major bug in Vagrant 1.8.7 (see https://github.com/mitchellh/vagrant/issues/7997 and https://github.com/mitchellh/vagrant/issues/7969) that causes new boxes to not be downloadable on macOS, and also you need to upgrade to VirtualBox 5.1.6 (or maybe 5.1.8) for best results with Drupal VM's configuration.
