### ISSUE TITLE
Missing repo adjustments for Debian in Varnish Role

### ISSUE THREAD

**Issue by xshadow** [geerlingguy/drupal-vm#987]
Dear @geerlingguy, 

it seems that you have missed to update the Varnish Repo for Debian/Ubuntu, when you updated to Varnish 5.0

Debian:

```
 -    repo: "deb http://repo.varnish-cache.org/{{ ansible_distribution | lower }}  {{ ansible_distribution_release }} varnish-{{ varnish_version }}" 
```
vs Redhat:

```
 name: https://repo.varnish-cache.org/pkg/{{ varnish_version }}/varnish-{{ varnish_version }}-1.el{{ ansible_distribution_version.split(".")[0] }}.{{ ansible_architecture }}.rpm 
``

For Debian it should be similiar:

```
https://repo.varnish-cache.org/pkg/{{ varnish_version }}/varnish-{{ varnish_version }}-1_{{ ansible_architecture }}
```

https://github.com/geerlingguy/drupal-vm/commit/88d54f675e3aabc24db08a620a5fe17f2d7a4d5e

**Comment by geerlingguy** [comment]
@xshadow - Any issues with the roles need to be filed against upstream projects: https://github.com/geerlingguy/ansible-role-varnish — note that Varnish 5.0 support is still experimental at this point, since it is using a different repo layout from 4.x and earlier releases.
