### ISSUE TITLE
Cannot upload images using VirtualBox with Drupal 8

### ISSUE THREAD

**Issue by carsonag01** [geerlingguy/drupal-vm#99]
Upon a clean install, with no real changes to the yml config files, except the file path, I could not upload an image via the image button the WYSIWYK when creating node/1.

I received a red "The file could not be uploaded." error:

![image](https://cloud.githubusercontent.com/assets/1831637/7672057/4ec8d1fc-fcaa-11e4-85bd-cc8710e5dca4.png)

Watchdog says: "The upload directory <em class="placeholder">public://inline-images</em> for the file field could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled."

![image](https://cloud.githubusercontent.com/assets/1831637/7672054/2a917834-fcaa-11e4-9614-c08b1c46ae93.png)

**Comment by geerlingguy** [comment]
This is a file permissions error that I think we might be able to fix in a couple different ways—one by setting the `vagrant` uid differently so the permissions are shared on the host and guest (at least on Mac), or by adding and install step to set permissions on the files directory so the web user can write to that directory.

The short term manual fix is to go to `~/Sites/drupalvm/drupal/sites/default/files`, get info on that folder, set permissions to 'read and write' for everyone, and apply to all enclosed items. This is NOT recommended for productions systems (effectively `chmod 777`), but since this is for local dev only, and should hopefully only be a short-term workaround, it's what I do right now if I need write access from apache.

**Comment by carsonag01** [comment]
Could this be solved by setting the group for sites/default/files to the
same group as Apache 2, then set permissions for sites/default/files to 775?

**Comment by geerlingguy** [comment]
Possibly, yes.

**Comment by geerlingguy** [comment]
A few more notes from some investigation this evening:

  - Inside the VM, the created folders are made with user:group `501:dialout`. In the Finder, they're owned by `[username]:staff`.
  - If I install Drupal 7.x, I can upload images and the admin/reports/status page reports everything's fine (`Writable (public download method)`).
  - If I install Drupal 8.0.x, I can upload images and the admin/reports/status page reports everything's fine (`Writable (public download method)`).

I'm going to close this ticket out, as it seems something else that's changed in the past month or two has possibly made this a moot point. Or it could also be just using the latest version of VMWare + Vagrant? Another thing to check—does VirtualBox handle the permissions differently?

From inside the VM in VMWare:

```
vagrant@drupalvm:/var/www/drupal/sites/default/files$ ls -lah
total 32K
drwxrwxr-x  8 501 dialout  272 Jun 18 04:47 .
dr-xr-xr-x  7 501 dialout  238 Jun 18 04:44 ..
drwxrwxr-x 36 501 dialout 1.2K Jun 18 04:47 css
drwxrwxr-x  3 501 dialout  102 Jun 18 04:47 field
drwxrwxr-x 26 501 dialout  884 Jun 18 04:47 js
drwxrwxrwx  4 501 dialout  136 Jun 18 04:46 php
drwxrwxr-x  4 501 dialout  136 Jun 18 04:47 styles
```

From the Mac/host:

```
 11:45 PM:~/Sites/drupalvm/drupal/sites/default/files $ ls -lah
total 0
drwxrwxr-x+  8 jgeerling  staff   272B Jun 17 23:47 .
dr-xr-xr-x+  7 jgeerling  staff   238B Jun 17 23:44 ..
drwxrwxr-x+ 36 jgeerling  staff   1.2K Jun 17 23:47 css
drwxrwxr-x+  3 jgeerling  staff   102B Jun 17 23:47 field
drwxrwxr-x+ 26 jgeerling  staff   884B Jun 17 23:47 js
drwxrwxrwx+  4 jgeerling  staff   136B Jun 17 23:46 php
drwxrwxr-x+  4 jgeerling  staff   136B Jun 17 23:47 styles
```

**Comment by geerlingguy** [comment]
Ah... so in Virtualbox, the permissions are _exactly_ the same, and Drupal even says it can write public files on the status report page... but when a file is uploaded, or when Drupal tries to create the .htaccess file, I get the errors:

```
Security warning: Couldn't write .htaccess file.
```

and

```
The upload directory `public://field/image` for the file field field_image could not be created or is not accessible. A newly uploaded file could not be saved in this directory as a consequence, and the upload was canceled.
```

On the front-end, when I try uploading the image, I get the errors `1 error has been found: Image` and `The file could not be uploaded.`.

**Comment by geerlingguy** [comment]
Simplest solution? I can add `www-data` (the Apache user) to the `dialout` group on Debian. On RedHat, the user and group will be different—but I'm not going to go further in testing that non-default scenario.

I will be adding a commit to fix this problem (so, no matter what, you'll always be able to upload images no matter what kind of site/shared folders you have set up) in just a few minutes :)

Thanks, @carsonag01, for bringing this to my attention!
