### ISSUE TITLE
Name of the VM

### ISSUE THREAD

**Issue by goodghost** [geerlingguy/drupal-vm#990]
Hi, 

I have this problem. I've set up a new enviroment and the VM has installed correctly (0 errors). I could get into an SSH, open the page and so on. I stopped the VM by typing 'vagrant halt'. Next time I tried to load it with 'vagrant up' but with no luck. Vagrant says: 

"The name of your virtual machine couldn't be set because VirtualBox is reporting another VM with that name already exists. Most of the time, this is because of an error with VirtualBox not cleaning up properly. To fix this, verify that no VMs with that name do exist (by opening the VirtualBox GUI). If they don't, then look at the folder in the error message from VirtualBox below and remove it folder in the error message from VirtualBox below and remove it"

It seems like vagrant tries to install it second time, but actually it should use configuration from '/drupalvm.dev' directory. I use windows 8. Any help?

**Comment by oxyc** [comment]
If you open the VirtualBox GUI do you see the VM? If you do, it seems vagrant has lost track of the vm ID. I believe this has happened to me as well on occasion.

I'm not sure how to do this on Windows but on osx you can usually fix it with: http://stackoverflow.com/a/30910282/319855

**Comment by geerlingguy** [comment]
What @oxyc said is usually the only fix; and if that doesn't work, the easiest thing is to nuke the `.vagrant` folder wherever it resides, and then build again from scratch. I never know what causes these issues, but I have seen it once or twice, and it seems that it happens to someone at least once a month :(

**Comment by goodghost** [comment]
Alright, I've rebuilded it once again, because changing id of the machine didn't work. But this time after rebuild vagrant generated 6 files into a .vagrant directory. Previously there was 3 files (creator_uid, id, index_uuid). And after 'vagrant halt' and 'vagrant up' it started as it should. Thanks guys for support good intentions.

**Comment by geerlingguy** [comment]
Great!
