### ISSUE TITLE
Drupal VM, The Next Generation

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/drupal-vm#996]
Opening this for some general discussion and as a container for bikeshedding...

Speaking of containers, I have two ideas for what Drupal VM could evolve into:

  1. Same basic setup, using Vagrant and a VM application like VirtualBox, but start building some parts internally using containers (e.g. with Ansible + Docker, or rkt).
  2. Same basic setup, but with an additional tool on top that allows Docker images to be built with the current configuration, and the idea would be to use Docker to run a giant VM-ish container, and share the built image with your team.

The advantage with number 1 is that things can evolve very slowly (e.g. just stick mailhog and some other services in Docker for now). The advantage with number 2 is that you can cut down on build time dramatically if you just build the config once and then share the Docker image (this is what I do for a lot of my personal projects). It's similar in principle to what Beetbox does right now, and I know there's another project in that space that is similar in spirit to number 2.

I'm opposed to the idea (at this time, at least) of trying to build some sort of mega-orchestrator of Docker to replicate Drupal VM in a 'correct' Docker setup (e.g. with one app per container, using a compose file, etc.), as that's (a) a nightmare to either maintain all those Docker images on Hub, or (b) a nightmare to try to glom together 90 different images from different maintainers.

Plus there are many other projects that focus on one portion of the Drupal dev environment experience (e.g. just basic LAMP/LEMP, or just LAMP+PHPUnit, etc.) that use Docker 'correctly', and I don't see value in burning a bunch of time replicating those more simple use cases, especially when they have active maintainers and support.

I'm also still on the fence about supporting Docker in particular for a few reasons:

  1. It's still early in the container space—Docker itself has evolved so radically in the past year that every six months, when I get ramped up on it again, I have to relearn all the basics (networking, IO, sharing, syntax, command flags, etc.). And there are alternatives that still haven't been counted out as 'the' standard for containers.
  2. Docker's dev team seems to be stretched thin on getting Docker working well on non-Linux platforms, as there are little bugs and performance issues that, when aggregated, become larger burdens, most especially around shared filesystem performance and networking.
  3. Docker, the company, is stretched thin and seems slightly rudderless because of the explosion in interest—they build new orchestration tools, try to scoop up different parts of the market that aren't their core competency, put on flashy trade shows, etc., but seem to care less about API stability, documentation consistency, etc. (at least as of 2014-2016).

The other major hurdle no matter what we do is the lack of something like `vagrant-hostsupdater`. A lot of Docker dev configs try to skirt around this by setting up one container as some sort of DNS server, and then you point certain subdomains at it... that sort of thing. But the ability to have a fresh new computer, download Drupal VM, run `vagrant up`, then load your project at `local.project.com` is a nice thing that I haven't seen replicated (at least not simply) in any of the Docker-based projects I've tried.

**Comment by joshbrown81** [comment]
It might be worth separating the Ubuntu 14.04 with PHP5.6 and Ubuntu 16.04 with PHP7.0 boxes into 2 different repos or branches too?

**Comment by geerlingguy** [comment]
@joshbrown81 - If we end up moving to anything containerized, there's no way I'm continuing to support Ubuntu, Debian, Fedora, and CentOS for Drupal VM. I'd likely either standardize on Debian 8 or CentOS 7 (or whatever the latest release is).

But due to the maintenance burden, I won't be splitting branches for the current architecture either—I used to do that to have a Drupal 7 and Drupal 8 branch, and since I only really care about the branch I use, I often forgot to merge changes to the other branch, meaning users on that branch kept hitting failures and filing issues, meaning I'd have even less time to work on Drupal VM (since I was dealing with those issues and then cherry picking and cleaning up commits...).

My priorities for Drupal VM development are currently:

  1. Keep maintenance burden as minimal as possible.
  2. Make sure the 80% use case is 100% stable.
  3. Always support _n_ and _n-1_ releases of stable software (Ubuntu, CentOS, PHP, MySQL, Drupal, etc.).
  4. Make sure documentation is thorough yet concise.

**Comment by joshbrown81** [comment]
That's fair enough. I can imagine because the usage of DVM is so high that you can't suit it for everyone. Keep up the great work though! Looking forward to more updates, DrupalVM alone has taught me a lot.

**Comment by fubarhouse** [comment]
Maintenance is paramount.

I'll continue to use and be happy with DrupalVM if it's isolated to a virtual machine. Should that VM use docker for some, or all of its optionally installed applications I wouldn't have a preference either way.

But, I always prefer the way that requires less maintenance and higher customizability.

The way Drupal VM is now is just that, low maintenance and super-customisable - but the applications that need to be customised for whatever reason - would we lose that capability if applications were dockerized, or would the users have the option of choosing docker-based or non-container applications?

For me, in your shoes - I would be considering some docker images for apps that essentially don't change and perhaps some others - but making docker optional.

I really don't like restriction, I actively fight restriction in every aspect of my life - so being forced into using a system which I either don't like or don't have the option of opting out - I honestly wouldn't be a fan of it. That being said, perhaps if the product was of high enough quality and customizability my opinion could just change - but I'm yet to really look at anything made with Docker and see any fun or value for the effort required.

**Comment by alexdesignworks** [comment]
@geerlingguy I think it would be really beneficial to start from identifying problems that Docker may resolve and goals that it may achieve if used as a part of Drupal VM. Until those defined, I think it is not clear why would users of Drupal VM (and Beetbox etc.) switch from current setup.

Your option 2 seems like most technically viable approach, but what does it bring to the table?
I can see, the following advantages:
1. Pre-provisioned Docker image to share in the team (but Drupal VM is about configuration, not pre-provisioned boxes - Beetbox is).
2. Potential use of pre-built image from (1) in CI builds - Docker image can be downloaded once to CI server and started within seconds rather than minutes. I see this as the most important advantage (right now, some projects take up to 15 minutes to setup LAMP stack + composer and node dependencies into bare Ubuntu).

Disadvantages:
1. Another technology to deal with. Drupal VM uses very straightforward YAML (one of the reasons I use Drupal VM over puppet-based solutions), which lowers the entry barrier. If Docker is introduced, it may make this much harder for some people to understand.
2. Docker's changing API and platform bugs (as you mentioned).
3. Large Docker images - basic LAMP images may take around 1GB.
4. Some platforms may still need a VM to run Docker.

**Comment by justinlevi** [comment]
Very interested in this thread... More than happy to help test as things progress. 

I think offloading some of the pieces that move slowly, like Mailhog and Ansible, to Docker make a lot of sense. If you could containerize some of the dependencies that seem to repeatedly cause issues, you might be able to decrease some of your maintenance time as well. 

I also think you might be able to steer a large number of people, who use Drupal VM, toward integrating automated testing, by containerizing some of the more complicated pieces. Anything you could do to ease the pain of getting a working testing environment setup will greatly benefit the community at large for years to come.

**Comment by oxyc** [comment]
Does anyone know the situation on the OSX performance issues? Is it technically possible to get the same performance from `docker-sync` or similar as with VM + rsync?

Personally my only reason for switching would be if there was a performance gain either on the host or the guest.

**Comment by derimagia** [comment]
If you can live with 1-way sync, rsync works fine and will give you native speeds.

[vagrant-rsync-back](https://github.com/smerrill/vagrant-rsync-back) worked for me a while ago as well.

My current approach is using [vagrant-unison2](https://github.com/dcosson/vagrant-unison2) which is 2 way. You can then set it up in the Vagrantfile.local:

```ruby
config.unison.host_folder = "."
config.unison.guest_folder = "/var/www/path"
config.unison.ignore = "Name {.DS_Store,.git,.idea,node_modules}"
config.unison.perms = 0 # if you get "properties changed on both sides" error
```

**Comment by oxyc** [comment]
I currently use rsync for all my VMs (I have a separate shared NFS directory for the configs) and it works well. As I'm not on Windows there's never really been a use case for working within the VM.

**Comment by geerlingguy** [comment]
The biggest problem I have with almost _all_ the current techniques is they add another shim that's harder to configure/debug than even Vagrant's mess of a situation (smb/rsync/nfs/native/plugin-based).

And some of them also require me to use Vagrant + VirtualBox... which is a double layer of insanity, because one of the top two reasons I'd ever switch _all_ my dev out of a primarily-Vagrant-based workflow would be to abandon having to mess with Vagrant and VirtualBox forever. Throw Docker on top of those two, and it's a mess.

I won't accept any solution that doesn't work solely using Docker for Mac/Docker for Windows/Docker for Linux.

**Comment by derimagia** [comment]
My last response was in a little of a misunderstanding (I was responding as if it was vagrant)

IMO the best solution for docker is still [docker-bg-sync](https://github.com/cweagans/docker-bg-sync). Unlike docker-sync, it requires no setup on the host machine and it should still support inotify events.

**Comment by geerlingguy** [comment]
++

**Comment by geerlingguy** [comment]
All right, had some great discussion in this thread, and it sounds like a lot of us agree that containers are awesome, but a shift from Vagrant/box-driven dev to fully-Dockerized dev is a bit of a shift that will require more time (and hopefully more improvements on the Docker end of things).

I'll open a new thread next time I have these thoughts popping around in my head.

For now, closing this thread and will consider opening more specific threads for particular things in the future (e.g. building an official Drupal VM docker image on Docker Hub in the future, things like that).
