### ISSUE TITLE
Couldn't open file .../drupalvm/base

### ISSUE THREAD

**Issue by jmevalentin** [geerlingguy/drupal-vm#999]
I could have sworn I had an issue open on this but it appears to have dematerialized. 

I have successfully altered my permissions to allow vagrant to run as expected, for the most part. I've done some other vagrant boxes without issues, so I'm assuming this is a drupalvm specific issue. I get the message when running vagrant up. The full body follows: 

>  default: Downloading: base
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.
>
>Couldn't open file .../drupalvm/base

I've trimmed the path.

Please advise. Thank you.

**Comment by geerlingguy** [comment]
Please see these two issues:

  - https://github.com/geerlingguy/drupal-vm/issues/981 (most likely the problem)
  - https://github.com/geerlingguy/drupal-vm/issues/672
